Repository dimagi/commcare-hq, pull requests merged in 2018-10, with the labels that each got.

#20834 batch ucrpillow
  corehq/apps/change_feed/consumer/feed.py
  corehq/apps/userreports/adapter.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/pillow.py
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/tests/test_async_indicators.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/tests/test_save_errors.py
  corehq/ex-submodules/pillow_retry/tests/test_all_pillows.py
  corehq/ex-submodules/pillow_retry/tests/test_retry.py
  corehq/ex-submodules/pillowtop/checkpoints/manager.py
  corehq/ex-submodules/pillowtop/exceptions.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  corehq/ex-submodules/pillowtop/processors/__init__.py
  corehq/ex-submodules/pillowtop/processors/elastic.py
  corehq/ex-submodules/pillowtop/processors/interface.py
  corehq/ex-submodules/pillowtop/processors/sample.py
  corehq/ex-submodules/pillowtop/utils.py
  testapps/test_pillowtop/tests/test_changes.py
  testapps/test_pillowtop/tests/test_chunk_pillow.py
Labels: awaiting QA, product/invisible

#21835 Cleanup old pillowtop cleanup migrations
  corehq/apps/cleanup/migrations/0001_convert_change_feed_checkpoint_to_sql.py
  corehq/apps/cleanup/migrations/0002_convert_mc_checkpoint_to_sql.py
  corehq/apps/cleanup/migrations/0003_convert_fluff_checkpoints_to_sql.py
  corehq/apps/cleanup/migrations/0004_convert_ucr_checkpoints_to_sql.py
  corehq/apps/cleanup/migrations/0007_convert_es_checkpoints_to_sql.py
  corehq/apps/cleanup/migrations/0008_convert_sofabed_checkpoints_to_sql.py
  corehq/apps/cleanup/migrations/0009_convert_final_checkpoints_to_sql.py
  corehq/apps/cleanup/migrations/0011_merge_couch_sql_pillows.py
  corehq/apps/cleanup/migrations/0013_migrate_kafka_checkpoint_format.py
  corehq/apps/cleanup/pillow_migrations.py
  corehq/apps/cleanup/tests/test_merge_checkpoints.py
  corehq/apps/cleanup/tests/test_migrate_kafka_checkpoint_formats.py
Labels: product/invisible

#21980 Fix logic
  corehq/apps/reports/filters/users.py
Labels: product/all-users-all-environments

#21750 Remove child_health tableau data source
  custom/icds_reports/docs/current_state_aggregation.png
  custom/icds_reports/docs/current_state_aggregation.txt
  custom/icds_reports/tests/fixtures/child_cases.csv
  custom/icds_reports/tests/fixtures/child_tasks.csv
  custom/icds_reports/tests/fixtures/person_cases.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/outputs/child_health_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/outputs/child_health_monthly_2017-05-01_sorted.csv
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/tests/reports/test_immunization_coverage.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/tests/test_fact_sheet_report.py
  custom/icds_reports/utils/aggregation.py
Labels: product/invisible

#21956 avoid line-too-long errors in commcare-version admin report
  deployment/gunicorn/gunicorn_conf.py
Labels: product/invisible

#21981 Upgrade requirements
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#21951 next subscription
  corehq/apps/domain/views.py
Labels: product/invisible

#21982 Make the deactivated users show up in all reports.
  corehq/apps/reports/filters/api.py
  corehq/apps/reports/filters/users.py
Labels: product/all-users-all-environments

#21983 setting ex
  corehq/apps/userreports/pillow.py
Labels: product/invisible

#21967 Make filter help link always show up
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/templates/reports/filters/multi_option.html
Labels: product/all-users-all-environments

#21914 [UP-NRHM] show all checklist but sum only latest
  custom/up_nrhm/reports/asha_functionality_checklist_report.py
Labels: product/custom

#21936 ONSE Clarify feature flag description
  corehq/toggles.py
Labels: product/feature-flag

#21954 [ICDS] Redo a bunch of UCRs for Mobile UCR v2
  corehq/apps/userreports/models.py
  custom/icds_reports/ucr/reports/mobile/README.md
  custom/icds_reports/ucr/reports/mobile/__init__.py
  custom/icds_reports/ucr/reports/mobile/mpr_10a_children_referred.json
  custom/icds_reports/ucr/reports/mobile/mpr_10b_pregnancies_referred.json
  custom/icds_reports/ucr/reports/mobile/mpr_11_awc_visits.json
  custom/icds_reports/ucr/reports/mobile/mpr_2a3_children_delivered.json
  custom/icds_reports/ucr/reports/mobile/mpr_2a_deaths.json
  custom/icds_reports/ucr/reports/mobile/mpr_3_children_registered.json
  custom/icds_reports/ucr/reports/mobile/mpr_3i_pregnancies.json
  custom/icds_reports/ucr/reports/mobile/mpr_4a6_preschool_education.json
  custom/icds_reports/ucr/reports/mobile/mpr_4b_iodized_salt.json
  custom/icds_reports/ucr/reports/mobile/mpr_5_child_nutrition.json
  custom/icds_reports/ucr/reports/mobile/mpr_5_pregnancy_nutrition.json
  custom/icds_reports/ucr/reports/mobile/mpr_6ac_pse_attendance.json
  custom/icds_reports/ucr/reports/mobile/mpr_6b_pse_attendance_per_year.json
  custom/icds_reports/ucr/reports/mobile/mpr_7_growth_monitored.json
  custom/icds_reports/ucr/reports/mobile/mpr_8_immunizations.json
  custom/icds_reports/ucr/reports/mobile/mpr_9_vhnd.json
  settings.py
Labels: product/custom

#21985 warn when there exists an active subscription for a domain that does …
  corehq/apps/accounting/tasks.py
Labels: product/invisible

#21970 Fix casing on case detail dropdowns
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_detail.html
Labels: product/all-users-all-environments

#21971 Fix alignment of Message Log
  corehq/apps/reports/templates/reports/filters/location_async.html
Labels: product/all-users-all-environments

#21990 modernize
  corehq/apps/app_manager/xform.py
  corehq/apps/userreports/models.py
  corehq/ex-submodules/pillowtop/processors/interface.py
  testapps/test_pillowtop/tests/test_chunk_pillow.py
Labels: product/invisible

#21973 Fix autopay indicator
  corehq/apps/accounting/static/accounting/js/stripe_card_manager.js
Labels: product/all-users-all-environments

#21972 Add form context to build error about missing question in case proper…
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/templates/app_manager/partials/form_error_message.html
Labels: product/all-users-all-environments

#21974 Add 'select all' checkbox to feature flag modal while copying app
  corehq/apps/app_manager/static/app_manager/js/app_view_application.js
Labels: product/admin

#21965 Fix edit form with attachments
  corehq/form_processor/backends/couch/processor.py
  corehq/form_processor/backends/sql/processor.py
  corehq/form_processor/interfaces/processor.py
  corehq/form_processor/tests/test_form_dbaccessor.py
Labels: product/invisible

#21992 remove assertion that fails when domain is deleted
  corehq/apps/domain/management/commands/hard_delete_forms_and_cases_in_domain.py
  corehq/apps/domain/tests/test_delete_domain.py
Labels: product/invisible

#21988 limit queries to domains that do not exist currently and have had sub…
  corehq/apps/cleanup/tasks.py
Labels: product/invisible

#21991 [ICDS] Group ASR mobile UCR by age
  custom/icds_reports/ucr/reports/mobile/asr_2_3_beneficiaries.json
  settings.py
Labels: product/custom

#21984 Check the report static-ness, not the data source
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/factory.py
  corehq/apps/userreports/reports/specs.py
  corehq/apps/userreports/tests/test_columns.py
Labels: product/invisible

#21969 linked apps master forms
  corehq/apps/app_manager/_design/views/xforms_index/map.js
  corehq/apps/app_manager/management/commands/set_linked_applications_uses_master_forms_true.py
  corehq/apps/app_manager/models.py
Labels: product/invisible, reindex/migration, run management command

#21989 delete es cases
  corehq/apps/es/management/commands/relog_deleted_cases.py
  corehq/ex-submodules/pillowtop/processors/elastic.py
Labels: product/invisible, run management command

#21986 Re-create multimedia mappings when using linked app logos
  corehq/apps/app_manager/models.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
Labels: product/invisible

#21629 Rn latest safe captured time
  corehq/apps/cleanup/migrations/0012_add_es_index_to_checkpoint_ids.py
  corehq/ex-submodules/pillowtop/checkpoints/manager.py
  corehq/ex-submodules/pillowtop/migrations/0005_kafkacheckpoint_doc_modification_time.py
  corehq/ex-submodules/pillowtop/models.py
  custom/icds_reports/const.py
  custom/icds_reports/migrations/0066_aggregatesqlprofile_last_included_doc_time.py
  custom/icds_reports/models/util.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/views.py
Labels: product/custom

#21996 check for downgrade
  corehq/apps/domain/views.py
Labels: product/invisible

#21899 Split the select2 into v3 and v4 : SmsCalculatorForm & PublicSmsCalculatorForm
  corehq/apps/accounting/static/accounting/js/software_plan_version_handler.js
  corehq/apps/domain/views.py
  corehq/apps/hqwebapp/static/hqwebapp/js/select2_handler_v3.js
  corehq/apps/hqwebapp/static/hqwebapp/js/select2_handler_v4.js
  corehq/apps/sms/static/sms/js/settings.js
  corehq/apps/smsbillables/forms.py
  corehq/apps/smsbillables/static/smsbillables/js/smsbillables.rate_calc.js
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
Labels: product/all-users-all-environments

#22008 don't report cumulative processing time for non-batch pillows
  corehq/ex-submodules/pillowtop/pillow/interface.py
Labels: product/invisible

#22006 removed kafkacheckpoint migration script from dependecy list
  corehq/apps/cleanup/migrations/0012_add_es_index_to_checkpoint_ids.py
  corehq/ex-submodules/pillowtop/migrations/0003_auto_20170411_1957.py
Labels: product/invisible

#22000 delete es mgmt cmd
  corehq/apps/es/management/commands/relog_deleted_cases.py
Labels: product/invisible

#22001 removing linked apps master app form id mgmt cmd
  corehq/apps/app_manager/management/commands/set_linked_applications_uses_master_forms_true.py
Labels: product/invisible

#22004 add check for any UCR tables belonging to a missing domain
  corehq/apps/cleanup/tasks.py
Labels: product/admin

#22003 Always show latest apk and app info
  corehq/apps/ota/views.py
Labels: product/invisible

#21908 adding an alert sent to support on large case imports
  corehq/apps/case_importer/tasks.py
  corehq/apps/hqadmin/tasks.py
Labels: product/invisible

#22010 Show case and form ids when support toggle is enabled
  corehq/apps/case_importer/static/case_importer/js/import_history.js
  corehq/apps/case_importer/templates/case_importer/import_cases.html
  corehq/apps/case_importer/templates/case_importer/partials/ko_import_history.html
Labels: product/feature-flag

#22014 Update message on subscription downgrade
  corehq/apps/accounting/subscription_changes.py
Labels: product/all-users-all-environments

#22011 Only show error when there is an error
  corehq/apps/reports/templates/reports/reportdata/form_data.html
Labels: product/invisible

#22005 Aggregate child_health_monthly by state
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/fixtures/child_tasks.csv
  custom/icds_reports/tests/fixtures/complementary_feeding.csv
  custom/icds_reports/tests/fixtures/dashboard_daily_feeding.csv
  custom/icds_reports/tests/fixtures/gm_form.csv
  custom/icds_reports/tests/fixtures/person_cases.csv
  custom/icds_reports/tests/fixtures/pnc_forms.csv
  custom/icds_reports/tests/fixtures/thr_form.csv
  custom/icds_reports/ucr/data_sources/dashboard/child_tasks.json
  custom/icds_reports/utils/aggregation.py
Labels: product/custom

#22019 pass all positional arguments
  corehq/apps/case_importer/tasks.py
Labels: product/invisible

#22002 Change Standard Plan's User limit to 125
  corehq/apps/accounting/bootstrap/config/standard_user_limit_october_2018.py
  corehq/apps/accounting/migrations/0040_auto_20181002_1721.py
Labels: product/all-users-all-environments

#22020 Change pre-filled signup text from "Email" to "Professional Email"
  corehq/apps/registration/forms.py
Labels: product/all-users-all-environments

#22021 Use total_seconds for pillow metrics to capture lag > 1 day
  corehq/ex-submodules/pillowtop/pillow/interface.py
Labels: product/invisible

#22018 Use sum_when in MPR 2a report
  custom/icds_reports/reports/ucr.py
  custom/icds_reports/ucr/reports/custom_sql_mpr_2a_person_cases.json
Labels: product/custom

#22015 Fix Dimagi logo in footer
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/navbar.less
Labels: product/all-users-all-environments

#22025 Fix search in select
  corehq/apps/hqwebapp/static/hqwebapp/js/select2_handler_v4.js
Labels: product/all-users-all-environments

#21910 Customer Billing QA
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/interface.py
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/payment_handlers.py
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/templates/accounting/email/customer_invoice.html
  corehq/apps/accounting/templates/accounting/email/customer_invoice.txt
  corehq/apps/accounting/tests/test_customer_invoicing.py
  corehq/apps/accounting/tests/test_forms.py
  corehq/apps/accounting/tests/test_wire_invoice.py
  corehq/apps/accounting/urls.py
  corehq/apps/accounting/views.py
  corehq/apps/domain/templates/domain/billing_statements.html
  corehq/apps/domain/views.py
  corehq/tabs/tabclasses.py
Labels: QA Passed, product/admin, product/all-users-all-environments

#21976 return what is stored in case of pending state
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
Labels: product/invisible

#21882 only include callcenter datasources that are used by the domain
  corehq/apps/app_manager/signals.py
  corehq/apps/callcenter/data_source.py
  corehq/apps/callcenter/fixturegenerators.py
  corehq/apps/callcenter/tests/test_datasources.py
  corehq/apps/callcenter/utils.py
  corehq/apps/domain/models.py
Labels: product/prod-india-all-users

#22013 Remove question translations from transifex
  corehq/apps/app_manager/app_translations/generators.py
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/app_manager/xform.py
  corehq/apps/reports/tests/readable_forms/mismatched_group_hierarchy.result.yaml
  corehq/apps/reports/tests/readable_forms/top_level_refless_group.result.yaml
  custom/icds/translations/integrations/transifex.py
Labels: product/custom

#22029 Only run historical aggregation once per week
  custom/icds_reports/tasks.py
Labels: product/custom

#22034 increase task lock for aggregation to 36 hours
  custom/icds_reports/tasks.py
Labels: product/invisible

#22035 remove enterprise deploy workflow
  scripts/enterprise.yaml
  scripts/rebuildstaging
Labels: product/invisible

#22028 make comment not lie
  corehq/apps/hqadmin/_design/filters/not_case_form.js
Labels: product/invisible

#22038 OpenMRS Atom Feed integration docs
  corehq/motech/openmrs/README.md
Labels: product/invisible

#22037 Check patient identifier has a value
  corehq/motech/openmrs/repeater_helpers.py
Labels: product/feature-flag, product/invisible

#22039 check if view is exempt first to reduce toggle check
  corehq/apps/domain/decorators.py
Labels: product/invisible

#21955 Mobile workers list: angular => knockout
  corehq/apps/es/fake/es_query_fake.py
  corehq/apps/hqwebapp/static/app_manager/less/navigation.less
  corehq/apps/hqwebapp/static/hqwebapp/js/pagination.ng.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/pagination.less
  corehq/apps/locations/tests/test_permissions.py
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/static/users/js/mobile_workers.ng.js
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/urls.py
  corehq/apps/users/views/mobile/users.py
Labels: product/all-users-all-environments

#22023 Release AB test for additional Get Demo button
  corehq/apps/analytics/ab_tests.py
  corehq/apps/registration/static/registration/js/register_new_user.js
  corehq/apps/registration/templates/registration/register_new_user.html
  corehq/apps/registration/views.py
Labels: product/prod-india-all-users

#22016 Standardize inheritance - locations
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/static/locations/js/location_drilldown.js
  corehq/apps/locations/static/locations/js/location_tree.js
  corehq/apps/locations/static/locations/js/location_types.js
  corehq/apps/locations/static/locations/js/locations.js
  corehq/apps/locations/static/locations/spec/location_drilldown_spec.js
  corehq/apps/locations/static/locations/spec/types_spec.js
  custom/ilsgateway/static/ilsgateway/js/slab_configuration.js
  custom/intrahealth/static/intrahealth/js/intrahealth_loc_drilldown.async.js
Labels: product/invisible

#22022 Add custom assertion blocks
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/forms/custom_assertions.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/custom_assertions.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/form_tab_settings.html
  corehq/apps/app_manager/tests/test_suite.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/toggles.py
Labels: product/feature-flag

#22040 Data types and serializers
  corehq/motech/const.py
  corehq/motech/dhis2/tests/test_dhis_config.py
  corehq/motech/openmrs/const.py
  corehq/motech/openmrs/openmrs_config.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/serializers.py
  corehq/motech/openmrs/tests/test_serializers.py
  corehq/motech/serializers.py
  corehq/motech/value_source.py
Labels: product/feature-flag, product/invisible

#22042 Refactor: Uncouple property map from Finder
  corehq/motech/openmrs/finders.py
  corehq/motech/openmrs/openmrs_config.py
  corehq/motech/openmrs/tests/test_finders.py
Labels: product/feature-flag, product/invisible

#22041 Change bbbp logo
  custom/icds/static/icds/img/poshan-logo.png
  custom/icds/templates/icds/login.html
  custom/icds_reports/templates/icds_reports/icds_app/navigation.directive.html
Labels: product/custom

#21994 upgrade architect
  corehq/apps/userreports/sql/adapter.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#22030 Use scroll to Fetch domain mobile users
  corehq/apps/hqadmin/reporting/reports.py
Labels: product/all-users-all-environments

#22046 Analytics for Find by ID page
  corehq/apps/data_interfaces/static/data_interfaces/js/find_by_id.js
Labels: product/invisible

#22027 Make Web Users have the correct label.
  corehq/apps/reports/filters/users.py
Labels: product/all-users-all-environments

#22051 Simplify template hierarchy in exports
  corehq/apps/export/templates/export/daily_saved_export_list.html
  corehq/apps/export/templates/export/dashboard_feed_list.html
  corehq/apps/export/templates/export/export_list.html
  corehq/apps/export/templates/export/partial/daily_saved_export_list_controller.html
  corehq/apps/export/templates/export/partial/dashboard_list_controller.html
  corehq/apps/export/templates/export/partial/export_list_controller.html
  corehq/apps/export/templates/export/partial/export_list_initial_page_data.html
  corehq/apps/export/views.py
Labels: product/invisible

#22062 Drop redundant `serialize()`
  corehq/motech/openmrs/repeater_helpers.py
Labels: product/feature-flag, product/invisible

#22053 Refactor get_property_map and deserialize external values
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/finders.py
  corehq/motech/openmrs/jsonpath.py
  corehq/motech/openmrs/openmrs_config.py
  corehq/motech/openmrs/tests/test_finders.py
  corehq/motech/openmrs/tests/test_jsonpath.py
Labels: product/feature-flag, product/invisible

#21975 Improvements to case rules UI
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_actions.js
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_criteria.js
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_main.js
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_rule_actions.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_rule_criteria.html
Labels: product/all-users-all-environments

#21803 Document ConditionalAggregationColumn
  corehq/apps/userreports/README.md
Labels: product/feature-flag

#22055 "partial" => "partials"
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/apps/export/templates/export/daily_saved_export_list.html
  corehq/apps/export/templates/export/download_export.html
  corehq/apps/export/templates/export/export_list.html
  corehq/apps/export/templates/export/partials/customize_export_header.html
  corehq/apps/export/templates/export/partials/export_bulk_notice.html
  corehq/apps/export/templates/export/partials/export_download_prepare.html
  corehq/apps/export/templates/export/partials/export_download_progress.html
  corehq/apps/export/templates/export/partials/export_list_controller.html
  corehq/apps/export/templates/export/partials/export_list_create_export_modal.html
  corehq/apps/export/templates/export/partials/feed_filter_modal.html
  corehq/apps/export/templates/export/partials/loading_exports.html
  corehq/apps/export/templates/export/partials/my_exports_table.html
  corehq/apps/export/templates/export/partials/new_customize_export_templates.html
  corehq/apps/export/templates/export/partials/original_exports_table.html
  corehq/apps/export/templates/export/partials/shared_exports_table.html
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/templates/reminders/partials/record_list_widget.html
  corehq/apps/settings/templates/settings/edit_my_account.html
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/partial/field.html
  corehq/apps/users/templates/users/partials/basic_info_form.html
  corehq/apps/users/templates/users/partials/basic_info_modals.html
  corehq/apps/users/templates/users/partials/edit_commtrack_user_settings.html
  corehq/apps/users/templates/users/partials/manage_my_numbers.html
  corehq/apps/users/templates/users/partials/manage_phone_numbers.html
  corehq/apps/users/templates/users/partials/reset_password.html
  corehq/apps/users/views/__init__.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/templates/scheduling/conditional_alert.html
  corehq/messaging/scheduling/templates/scheduling/create_schedule.html
  corehq/messaging/scheduling/templates/scheduling/partials/custom_event_templates.html
  corehq/messaging/scheduling/templates/scheduling/partials/days_of_month_picker.html
  corehq/messaging/scheduling/templates/scheduling/partials/message_configuration.html
  corehq/messaging/scheduling/templates/scheduling/partials/recipient_types_picker.html
  corehq/messaging/scheduling/templates/scheduling/partials/schedule_form.html
Labels: product/invisible

#22059 route icds models even in non-partitioned setup
  corehq/sql_db/routers.py
Labels: product/invisible

#22061 use headers to load data
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/fixtures/child_monthly.csv
  custom/icds_reports/tests/fixtures/person_cases.csv
  custom/icds_reports/tests/fixtures/pregnant_tasks.csv
  custom/icds_reports/tests/fixtures/usage.csv
Labels: product/invisible

#22058 Removed typo from weekly aggregation script
  custom/icds_reports/migrations/sql_templates/database_functions/aggregated_awc_data_weekly.sql
Labels: product/invisible

#22056 count awcs properly
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_awc_data.sql
Labels: product/custom

#22060 notify prior to soft assert to show exception trace in tests
  custom/icds_reports/tasks.py
Labels: product/invisible

#22043 Check for downgrade and non-trial subscriptions
  corehq/apps/accounting/static/accounting/js/confirm_plan.js
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/domain/confirm_plan.html
  corehq/apps/domain/views.py
Labels: product/all-users-all-environments

#22066 Kill another export template: daily_saved_export_list.html
  corehq/apps/export/templates/export/daily_saved_export_list.html
  corehq/apps/export/templates/export/export_list.html
  corehq/apps/export/views.py
Labels: product/invisible

#22067 Add ddtrace to requirements
  requirements/prod-requirements.in
  requirements/prod-requirements.txt
  requirements/uninstall-requirements.txt
Labels: product/invisible

#22071 Log couchdb timing metrics
  corehq/ex-submodules/dimagi/ext/couchdbkit.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#22068 Change ExportPermissionsMixin to a standalone object
  corehq/apps/dashboard/models.py
  corehq/apps/export/views.py
Labels: product/invisible

#22033 Ce/incentive report
  custom/icds_reports/const.py
  custom/icds_reports/migrations/0061_added_phone_number_to_views.py
  custom/icds_reports/migrations/0062_disha_indicators_create_view.py
  custom/icds_reports/migrations/0065_ccsrecordmonthlyview.py
  custom/icds_reports/migrations/0067_ccsrecordmonthly_dob.py
  custom/icds_reports/migrations/0069_valid_visits.py
  custom/icds_reports/migrations/sql_templates/database_views/agg_ccs_record_monthly.sql
  custom/icds_reports/migrations/sql_templates/update_tables28.sql
  custom/icds_reports/migrations/sql_templates/update_tables29.sql
  custom/icds_reports/models/__init__.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/models/views.py
  custom/icds_reports/reports/incentive.py
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/tasks.py
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
  custom/icds_reports/tests/fixtures/complementary_feeding.csv
  custom/icds_reports/tests/fixtures/pnc_forms.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/outputs/ccs_record_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/outputs/ccs_record_monthly_2017-05-01_sorted.csv
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/ucr/data_sources/dashboard/birth_preparedness_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/complementary_feeding_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/delivery_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/postnatal_care_forms.json
  custom/icds_reports/ucr/tests/test_birth_preparedness_form_ucr.py
  custom/icds_reports/ucr/tests/test_pnc_form_ucr.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/aggregation.py
  custom/icds_reports/utils/mixins.py
  custom/icds_reports/views.py
Labels: product/custom

#22076 Support old configs that don't have person_preferred_name or person_preferred_address
  corehq/motech/openmrs/openmrs_config.py
Labels: product/invisible

#22064 Update docs for Atom feed and data types
  corehq/motech/README.md
  corehq/motech/openmrs/README.md
Labels: product/invisible

#22072 Add ability to upload part of the case list and case details in app translations
  corehq/apps/app_manager/app_translations/app_translations.py
  corehq/apps/app_manager/tests/test_bulk_app_translation.py
  corehq/apps/app_manager/tests/test_repeater.py
Labels: product/custom

#22063 Case List Explorer WIP / Pre-Work
  bower.json
  corehq/apps/data_interfaces/templates/data_interfaces/explore_case_data.html
  corehq/apps/data_interfaces/urls.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_config.js
  corehq/apps/reports/static/reports/v2/js/columns.js
  corehq/apps/reports/static/reports/v2/js/context.js
  corehq/apps/reports/static/reports/v2/js/formatters.js
  corehq/apps/reports/static/reports/v2/js/utils.js
  corehq/apps/reports/static/reports/v2/js/views/case_search.js
  corehq/apps/reports/urls.py
  corehq/apps/reports/v2/__init__.py
  corehq/apps/reports/v2/endpoints/__init__.py
  corehq/apps/reports/v2/endpoints/case_column_select.py
  corehq/apps/reports/v2/endpoints/datatables.py
  corehq/apps/reports/v2/exceptions.py
  corehq/apps/reports/v2/formatters/__init__.py
  corehq/apps/reports/v2/formatters/cases.py
  corehq/apps/reports/v2/models.py
  corehq/apps/reports/v2/reports/__init__.py
  corehq/apps/reports/v2/reports/explore_case_data.py
  corehq/apps/reports/v2/urls.py
  corehq/apps/reports/v2/utils.py
  corehq/apps/reports/v2/views.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
  corehq/util/timezones/utils.py
Labels: product/feature-flag

#22070 Don't use ajax to fetch export list
  corehq/apps/export/static/export/js/list_exports.ng.js
  corehq/apps/export/static/export/spec/ListExportsController.spec.mo.js
  corehq/apps/export/templates/export/export_list.html
  corehq/apps/export/templates/export/partials/export_list_controller.html
  corehq/apps/export/templates/export/partials/loading_exports.html
  corehq/apps/export/templates/export/partials/my_exports_table.html
  corehq/apps/export/templates/export/partials/original_exports_table.html
  corehq/apps/export/templates/export/partials/shared_exports_table.html
  corehq/apps/export/views.py
Labels: product/all-users-all-environments

#22078 Use .is_downgrade_from_paid_plan()
  corehq/apps/domain/views.py
Labels: product/all-users-all-environments

#22080 fix incentive report agg issues
  custom/icds_reports/migrations/0069_valid_visits.py
  custom/icds_reports/migrations/0070_aww_name_in_agg_ccs_view.py
  custom/icds_reports/migrations/sql_templates/database_views/agg_ccs_record_monthly.sql
  custom/icds_reports/models/__init__.py
  custom/icds_reports/reports/incentive.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation.py
Labels: product/custom

#22047 fix daily indicators
  custom/icds_reports/reports/awc_daily_status.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/reports/cas_reach_data.py
  custom/icds_reports/reports/demographics_data.py
Labels: product/custom

#22069 switch MISSING and NOT_STARTED in case importer
  corehq/apps/case_importer/static/case_importer/js/import_history.js
  corehq/apps/case_importer/templates/case_importer/partials/ko_import_history.html
  corehq/apps/case_importer/tracking/task_status.py
Labels: product/invisible

#22077 move devicelog processing out of lock
  corehq/form_processor/submission_post.py
Labels: product/invisible

#22091 Kill some old exports stuff
  corehq/apps/dashboard/models.py
  corehq/apps/export/forms.py
  corehq/apps/export/static/export/js/export_list.js
  corehq/apps/export/static/export/js/list_exports.ng.js
  corehq/apps/export/static/export/spec/ListExportsController.spec.mo.js
  corehq/apps/export/templates/export/export_list.html
  corehq/apps/export/templates/export/partials/my_exports_table.html
  corehq/apps/export/templates/export/partials/original_exports_table.html
  corehq/apps/export/templates/export/partials/shared_exports_table.html
  corehq/apps/export/urls.py
  corehq/apps/export/views.py
  corehq/apps/reports/tests/test_form_export.py
  corehq/tabs/tabclasses.py
  corehq/util/couch.py
  corehq/util/tests/test_couch.py
Labels: product/invisible

#22090 upgrade ddtrace
  requirements/prod-requirements.in
  requirements/prod-requirements.txt
Labels: product/invisible

#22086 DRY up export table templates
  corehq/apps/export/templates/export/partials/export_list_controller.html
  corehq/apps/export/templates/export/partials/my_exports_table.html
  corehq/apps/export/templates/export/partials/shared_exports_table.html
  corehq/apps/export/templates/export/partials/table.html
Labels: product/invisible

#22083 Add case search to linked domains
  corehq/apps/case_search/models.py
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/management/commands/link_app_to_remote.py
  corehq/apps/linked_domain/management/commands/link_apps.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/tests/test_linked_case_claim.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/urls.py
  corehq/apps/linked_domain/views.py
Labels: product/feature-flag

#22093 Fix export can_edit param
  corehq/apps/export/views.py
Labels: product/all-users-all-environments

#22087 Upgrade select2: Scheduled reports
  corehq/apps/hqwebapp/fields.py
  corehq/apps/hqwebapp/static/hqwebapp/js/widgets.js
  corehq/apps/hqwebapp/widgets.py
  corehq/apps/reports/static/reports/js/edit_scheduled_report.js
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#22103 Fix syntax error in find_by_id.js
  corehq/apps/data_interfaces/static/data_interfaces/js/find_by_id.js
Labels: product/invisible

#22101 Change AWW incentive report name
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#22109 Fix "Edit" buttons on exports
  corehq/apps/export/templates/export/partials/table.html
Labels: product/all-users-all-environments

#22088 Redis cluster prereqs
  localsettings.example.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  scripts/test-make-requirements.sh
Labels: product/invisible

#22105 Don't allow linking apps back to master domain
  corehq/apps/app_manager/views/view_generic.py
Labels: product/feature-flag

#22111 Bump form timeout to 15 minutes
  corehq/form_processor/interfaces/processor.py
Labels: product/invisible

#22100 Ignore SSL if necessary when polling Atom feed
  corehq/motech/openmrs/atom_feed.py
Labels: product/feature-flag, product/invisible

#21942 quickcache subscription getter
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_forms.py
  corehq/apps/api/tests.py
Labels: product/invisible

#22108 fix deprecation warning
  corehq/apps/reports/v2/formatters/cases.py
Labels: product/invisible

#22107 modernize
  corehq/motech/openmrs/const.py
  corehq/motech/openmrs/openmrs_config.py
  corehq/motech/serializers.py
Labels: product/invisible

#22106 Support partial bulk translations for ID mappings
  corehq/apps/app_manager/app_translations/app_translations.py
  corehq/apps/app_manager/tests/test_bulk_app_translation.py
Labels: product/custom

#22089 Mk fix push
  corehq/apps/app_manager/app_translations/generators.py
Labels: product/custom

#22110 handle null ccs records
  custom/icds_reports/utils/aggregation.py
Labels: product/invisible

#22085 only count height if eligible
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/child_health_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/tests/test_fact_sheet_report.py
  custom/icds_reports/utils/aggregation.py
Labels: product/custom

#22113 Removed duplicate data cleaning modal
  corehq/apps/reports/templates/reports/reportdata/case_data.html
Labels: product/invisible

#22065 Analytics for enterprise dashboard
  corehq/apps/accounting/static/accounting/js/enterprise_dashboard.js
Labels: product/invisible

#22082 UAT feedback for Find by ID page
  corehq/apps/data_interfaces/static/data_interfaces/js/find_by_id.js
  corehq/apps/data_interfaces/templates/data_interfaces/find_by_id.html
  corehq/apps/hqwebapp/views.py
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments

#21902 [HQ] Added new metric calculations
  corehq/apps/api/domain_metadata.py
  corehq/apps/domain/calculations.py
  corehq/apps/domain/middleware.py
  corehq/apps/domain/migrations/0004_domainauditrecordentry.py
  corehq/apps/domain/models.py
  corehq/apps/reports/views.py
  corehq/apps/userreports/reports/builder/forms.py
  settings.py
Labels: product/admin

#22117 DHIS 2 documentation
  corehq/motech/dhis2/README.md
Labels: product/feature-flag

#22057 add soft assert for form edits
  corehq/apps/commtrack/tests/test_rebuild.py
  corehq/apps/couch_sql_migration/tests/test_diffs.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/receiverwrapper/tests/test_submissions.py
  corehq/ex-submodules/couchforms/tests/test_edits.py
  corehq/form_processor/parsers/form.py
  corehq/form_processor/tests/test_ledgers.py
  corehq/util/test_utils.py
Labels: product/invisible

#22116 check for comment present before checking its content
  corehq/apps/app_manager/app_translations/generators.py
Labels: product/custom

#22114 Translate translations messages
  corehq/apps/app_manager/app_translations/app_translations.py
Labels: product/all-users-all-environments

#22112 consolidate module translations for same context
  corehq/apps/app_manager/app_translations/generators.py
  corehq/apps/app_manager/app_translations/parser.py
Labels: product/custom

#22115 use named arguments to avoid translation warnings
  corehq/apps/domain/views.py
Labels: product/invisible

#22096 Find the number of registered deaths on icds
  custom/icds_reports/management/commands/nos_of_deaths.py
  custom/icds_reports/management/commands/sql_scripts/nos_of_deaths.sql
Labels: product/invisible

#22024 Data cleaning: dropdowns for select questions
  corehq/apps/hqwebapp/static/hqwebapp/js/knockout_bindings.ko.js
  corehq/apps/reports/formdetails/readable.py
  corehq/apps/reports/static/reports/js/data_corrections.js
  corehq/apps/reports/templates/reports/partials/data_corrections_modal.html
  corehq/apps/reports/views.py
Labels: QA Passed, product/all-users-all-environments

#22120 Add disclaimer on program summary tab
  custom/icds_reports/static/css/icds_dashboard.css
  custom/icds_reports/templates/icds_reports/icds_app/system-usage.directive.html
Labels: product/custom

#22098 Quote aww phonenumber
  custom/icds_reports/sqldata/exports/beneficiary.py
Labels: product/invisible

#22121 calculate birth month correctly
  custom/icds_reports/utils/aggregation.py
Labels: product/invisible

#22126 Speed up case importer
  corehq/apps/app_manager/app_schemas/case_properties.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/tests/test_util.py
  corehq/apps/data_dictionary/util.py
Labels: product/all-users-all-environments

#22122 Partial bulk app translations
  corehq/apps/app_manager/app_translations/app_translations.py
  corehq/apps/app_manager/tests/test_bulk_app_translation.py
Labels: product/custom

#22127 Clarify that UCR ID is a ReportConfig ID
  corehq/motech/dhis2/models.py
  corehq/motech/dhis2/templates/dhis2/partials/dhis2_dataset_map_templates.html
Labels: product/feature-flag

#22074 all forms must have a domain
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
  corehq/ex-submodules/casexml/apps/case/tests/test_domains.py
  corehq/ex-submodules/casexml/apps/case/tests/test_exclusion.py
  corehq/ex-submodules/casexml/apps/case/tests/test_from_xform.py
  corehq/ex-submodules/casexml/apps/case/tests/test_indexes.py
  corehq/ex-submodules/casexml/apps/case/tests/test_multi_case_submits.py
  corehq/ex-submodules/casexml/apps/case/tests/test_out_of_order_processing.py
  corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py
  corehq/ex-submodules/casexml/apps/case/xform.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore_v3.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_state_hash.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py
  corehq/form_processor/submission_post.py
  settings.py
Labels: product/invisible

#22135 Added more icons to export page buttons
  corehq/apps/export/templates/export/partials/table.html
Labels: product/all-users-all-environments

#22084 Pv/report metrics 2
  corehq/apps/export/static/export/js/download_export.ng.js
  corehq/apps/export/templates/export/download_export.html
  corehq/apps/export/templates/export/partial/export_download_prepare.html
  corehq/apps/export/views.py
Labels: product/invisible

#22079 Add kissmetrics to filters on reports.
  corehq/apps/export/static/export/js/download_export.ng.js
  corehq/apps/export/templates/export/download_export.html
  corehq/apps/export/templates/export/partials/export_download_prepare.html
  corehq/apps/export/views.py
  corehq/apps/reports/standard/__init__.py
  corehq/apps/reports/static/reports/js/case_list.js
  corehq/apps/reports/static/reports/js/submit_history.js
  corehq/apps/reports/templates/reports/standard/base_template.html
Labels: product/invisible

#22133 don't fail hard when Exception message contains non-ascii bytes
  corehq/apps/userreports/tasks.py
Labels: product/invisible

#22134 Fix tt_dates formatting
  custom/icds_reports/utils/__init__.py
Labels: product/invisible

#22132 Update message hist filter text
  corehq/apps/sms/filters.py
Labels: product/all-users-all-environments

#22031 retry fixture download on 502s caused by server slowness
  corehq/apps/fixtures/static/fixtures/js/lookup-manage.js
Labels: product/invisible

#22146 Tiny script to check when environments were last deployed
  scripts/last_deploy.sh
Labels: product/invisible

#22150 Account for undefined variables before calling split.(',')
  corehq/apps/export/static/export/js/download_export.ng.js
Labels: product/invisible

#22140 Add 'prefix' variable
  corehq/apps/export/static/export/js/download_export.ng.js
Labels: product/invisible

#22073 Add partitioning to child_health cases UCR data source
  custom/icds_reports/ucr/data_sources/child_health_cases.json
Labels: product/custom

#22152 Update README
  README.md
Labels: product/invisible

#22145 [Vector-Link] Exclude test forms in supervisory datasource
  custom/abt/reports/data_sources/supervisory_v2.json
Labels: product/custom
