Repository dimagi/commcare-hq, pull requests merged in 2018-12, with the labels that each got.

#22585 Consider test location check
  custom/icds_reports/tests/outputs/agg_ls_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_ls_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_ls_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_ls_2017-05-01_4_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/agg_ls_data.py
Labels: product/invisible

#22582 Fix MultipleObjectsReturned error
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/tests/test_form_dbaccessor.py
Labels: product/invisible

#22566 lower chunk size for blobdb bulk delete
  corehq/blobs/s3db.py
Labels: product/invisible

#22559 add permission to manage app releases
  corehq/apps/app_manager/views/releases.py
  corehq/apps/users/models.py
  corehq/apps/users/permissions.py
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/static/users/js/web_users.js
  corehq/apps/users/templates/users/web_users.html
  corehq/apps/users/views/__init__.py
  corehq/toggles.py
Labels: product/custom

#22581 Fix adding automatic case case rule actions
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_actions.js
Labels: product/all-users-all-environments

#22516 Populate translation app
  corehq/apps/app_manager/app_translations/__init__.py
  corehq/apps/app_manager/tests/test_generators.py
  corehq/apps/app_manager/tests/test_translations.py
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/translations.py
  corehq/apps/translations/app_translations.py
  corehq/apps/translations/const.py
  corehq/apps/translations/forms.py
  corehq/apps/translations/generators.py
  corehq/apps/translations/integrations/__init__.py
  corehq/apps/translations/integrations/transifex/__init__.py
  corehq/apps/translations/integrations/transifex/client.py
  corehq/apps/translations/integrations/transifex/const.py
  corehq/apps/translations/integrations/transifex/exceptions.py
  corehq/apps/translations/integrations/transifex/parser.py
  corehq/apps/translations/integrations/transifex/transifex.py
  corehq/apps/translations/integrations/transifex/utils.py
  corehq/apps/translations/integrations/transifex/views.py
  corehq/apps/translations/tasks.py
  corehq/apps/translations/templates/app_translations.html
  corehq/apps/translations/tests/__init__.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/apps/translations/urls.py
  corehq/apps/translations/utils.py
  corehq/apps/translations/validator.py
  corehq/apps/translations/views.py
  corehq/tabs/tabclasses.py
  custom/icds/tasks.py
  custom/icds_reports/forms.py
  custom/icds_reports/urls.py
  custom/icds_reports/views.py
Labels: product/invisible

#22587 require FormSource to get and set with unicode
  corehq/apps/aggregate_ucrs/tests/test_aggregation.py
  corehq/apps/app_manager/app_schemas/tests/test_case_properties.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_case_list_form.py
  corehq/apps/app_manager/tests/test_case_meta.py
  corehq/apps/app_manager/tests/test_child_module.py
  corehq/apps/app_manager/tests/test_extension_case.py
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/tests/test_form_xmlns.py
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/app_manager/tests/test_practice_user_config.py
  corehq/apps/app_manager/tests/test_release_notes_form.py
  corehq/apps/app_manager/tests/test_schedule.py
  corehq/apps/app_manager/util.py
  corehq/apps/cleanup/management/commands/fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/cleanup/tests/test_fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/export/tests/test_export_data_schema.py
  corehq/apps/export/tests/test_export_form_subcases.py
  corehq/apps/export/tests/test_form_schema.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/translations/app_translations.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/apps/userreports/tests/utils.py
  custom/openclinica/management/commands/odm_to_app.py
Labels: product/invisible

#22589 Update aww_no_submissions
  custom/icds/templates/icds/messaging/indicators/tam/aww_no_submissions.txt
Labels: product/custom

#22562 increase connection pool size for migrations
  manage.py
Labels: product/invisible

#22601 remove print from tests
  custom/icds_reports/tests/reports/test_children_initiated.py
  custom/icds_reports/tests/reports/test_enrolled_children.py
  custom/icds_reports/tests/reports/test_enrolled_women.py
  custom/icds_reports/tests/reports/test_institutional_deliveries_sector.py
  custom/icds_reports/tests/reports/test_prevalence_of_undernutrition.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/tests/test_fact_sheet_report.py
Labels: product/invisible

#22575 Update ICDS UCRs that are being tested
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
  custom/icds_reports/ucr/reports/testing/asr_2_3_beneficiaries.json
  custom/icds_reports/ucr/reports/testing/asr_2_3_person_cases.json
  custom/icds_reports/ucr/reports/testing/mpr_10a_children_referred.json
  custom/icds_reports/ucr/reports/testing/mpr_10a_person_cases.json
  custom/icds_reports/ucr/reports/testing/mpr_10b_person_cases.json
  custom/icds_reports/ucr/reports/testing/mpr_10b_pregnancies_referred.json
  custom/icds_reports/ucr/reports/testing/mpr_1_person_cases.json
  custom/icds_reports/ucr/reports/testing/mpr_3_children_registered.json
  custom/icds_reports/ucr/reports/testing/mpr_3i_person_cases.json
  custom/icds_reports/ucr/reports/testing/mpr_3i_pregnancies.json
  custom/icds_reports/ucr/reports/testing/mpr_3ii_person_cases.json
Labels: product/invisible

#22553 Add Tamil translation directory and templates
  custom/icds/templates/icds/messaging/indicators/tam/aww_aggregate_performance.txt
  custom/icds/templates/icds/messaging/indicators/tam/aww_no_submissions.txt
  custom/icds/templates/icds/messaging/indicators/tam/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/tam/beneficiary_negative_growth.txt
  custom/icds/templates/icds/messaging/indicators/tam/beneficiary_static_growth.txt
  custom/icds/templates/icds/messaging/indicators/tam/cf_visits_complete.txt
  custom/icds/templates/icds/messaging/indicators/tam/child_illness_reported.txt
  custom/icds/templates/icds/messaging/indicators/tam/child_vaccinations_complete.txt
  custom/icds/templates/icds/messaging/indicators/tam/dpt3_and_measles_due.txt
  custom/icds/templates/icds/messaging/indicators/tam/ls_aggregate_performance.txt
  custom/icds/templates/icds/messaging/indicators/tam/ls_no_submissions.txt
  custom/icds/templates/icds/messaging/indicators/tam/ls_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/tam/missed_cf_visit_to_aww.txt
  custom/icds/templates/icds/messaging/indicators/tam/missed_cf_visit_to_ls.txt
  custom/icds/templates/icds/messaging/indicators/tam/missed_pnc_visit_to_ls.txt
Labels: product/custom

#22579 Put get_questions on a long timeout
  corehq/apps/app_manager/models.py
Labels: product/all-users-all-environments

#22536 Add app summary link for each version
  corehq/apps/app_manager/templates/app_manager/app_view_release_manager.html
  corehq/apps/app_manager/templates/app_manager/case_summary.html
  corehq/apps/app_manager/templates/app_manager/form_summary.html
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_table.html
  corehq/apps/app_manager/views/app_summary.py
  corehq/apps/hqwebapp/static/app_manager/less/panel.less
Labels: product/all-users-all-environments

#22602 modernize
  corehq/apps/translations/utils.py
  corehq/form_processor/management/commands/run_sql.py
  custom/icds_reports/tests/reports/test_adhaar.py
  custom/icds_reports/tests/reports/test_adult_weight_scale.py
  custom/icds_reports/tests/reports/test_awc_daily_status.py
  custom/icds_reports/tests/reports/test_awcs_covered.py
  custom/icds_reports/tests/reports/test_children_initiated.py
  custom/icds_reports/tests/reports/test_clean_water.py
  custom/icds_reports/tests/reports/test_early_initiation_breastfeeding.py
  custom/icds_reports/tests/reports/test_enrolled_women.py
  custom/icds_reports/tests/reports/test_exclusive_breastfeeding.py
  custom/icds_reports/tests/reports/test_functional_toilet.py
  custom/icds_reports/tests/reports/test_immunization_coverage.py
  custom/icds_reports/tests/reports/test_institutional_deliveries_sector.py
  custom/icds_reports/tests/reports/test_lactating_enrolled_women.py
  custom/icds_reports/tests/reports/test_medicine_kit.py
  custom/icds_reports/tests/reports/test_new_born_with_low_weight.py
  custom/icds_reports/tests/reports/test_prevalence_of_severe.py
  custom/icds_reports/tests/reports/test_prevalence_of_stunting.py
  custom/icds_reports/tests/reports/test_prevalence_of_undernutrition.py
  custom/icds_reports/tests/reports/test_registered_household.py
  custom/icds_reports/utils/aggregation_helpers/agg_ls_data.py
Labels: product/invisible

#22576 Configurable couch continuous indexing
  corehq/preindex/tasks.py
  corehq/util/celery_utils.py
  corehq/util/tests/test_celery_utils.py
Labels: product/invisible

#22607 Revert "require FormSource to get and set with unicode"
  corehq/apps/aggregate_ucrs/tests/test_aggregation.py
  corehq/apps/app_manager/app_schemas/tests/test_case_properties.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_case_list_form.py
  corehq/apps/app_manager/tests/test_case_meta.py
  corehq/apps/app_manager/tests/test_child_module.py
  corehq/apps/app_manager/tests/test_extension_case.py
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/tests/test_form_xmlns.py
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/app_manager/tests/test_practice_user_config.py
  corehq/apps/app_manager/tests/test_release_notes_form.py
  corehq/apps/app_manager/tests/test_schedule.py
  corehq/apps/app_manager/util.py
  corehq/apps/cleanup/management/commands/fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/cleanup/tests/test_fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/export/tests/test_export_data_schema.py
  corehq/apps/export/tests/test_export_form_subcases.py
  corehq/apps/export/tests/test_form_schema.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/translations/app_translations.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/apps/userreports/tests/utils.py
  custom/openclinica/management/commands/odm_to_app.py
Labels: product/invisible

#22604 Added HQModalFormHelper to standardize modal form proportions
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/export/forms.py
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/users/forms.py
Labels: product/all-users-all-environments

#22608 Fix couch_reindex_schedule default logic
  corehq/preindex/tasks.py
  settings.py
Labels: product/invisible

#22610 use json versions of iterator state to avoid datetime wrapping
  corehq/util/pagination.py
Labels: product/invisible

#22545 Updated some requirements to use >= instead of == in .in file
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
Labels: product/invisible

#22606 from package
  corehq/apps/couch_sql_migration/couchsqlmigration.py
Labels: product/invisible

#22613 Pass through error messages in get_form_data_schema
  corehq/apps/app_manager/views/formdesigner.py
Labels: product/all-users-all-environments

#22618 don't decode output of get_table_name
  custom/icds_reports/utils/aggregation_helpers/agg_ccs_record.py
  custom/icds_reports/utils/aggregation_helpers/ccs_record_monthly.py
  custom/icds_reports/utils/aggregation_helpers/child_health_monthly.py
  custom/intrahealth/tests/__init__.py
  custom/up_nrhm/tests/__init__.py
Labels: product/invisible

#22619 remove couch attachments from tests
  corehq/blobs/tests/test_mixin.py
Labels: product/invisible

#22609 Revert "Revert "require FormSource to get and set with unicode""
  corehq/apps/aggregate_ucrs/tests/test_aggregation.py
  corehq/apps/app_manager/app_schemas/tests/test_case_properties.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_case_list_form.py
  corehq/apps/app_manager/tests/test_case_meta.py
  corehq/apps/app_manager/tests/test_child_module.py
  corehq/apps/app_manager/tests/test_extension_case.py
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/tests/test_form_xmlns.py
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/app_manager/tests/test_practice_user_config.py
  corehq/apps/app_manager/tests/test_release_notes_form.py
  corehq/apps/app_manager/tests/test_schedule.py
  corehq/apps/app_manager/util.py
  corehq/apps/cleanup/management/commands/fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/cleanup/tests/test_fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/export/tests/test_export_data_schema.py
  corehq/apps/export/tests/test_export_form_subcases.py
  corehq/apps/export/tests/test_form_schema.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/translations/app_translations.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/apps/userreports/tests/utils.py
  custom/openclinica/management/commands/odm_to_app.py
Labels: product/invisible

#22620 fetch bytes instead of fetching unicode and then encoding
  corehq/ex-submodules/couchexport/shortcuts.py
Labels: product/invisible

#22320 Added case sync test case for REACH
  corehq/ex-submodules/casexml/apps/phone/tests/data/case_relationship_tests.json
Labels: product/invisible

#22605 Remove unused code
  custom/icds/messaging/custom_content.py
  custom/icds/tests/test_custom_content.py
Labels: product/invisible

#22622 Upgrade django
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.in
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#22617 Remove unique AWC constraint from counting awc visits
  custom/icds_reports/migrations/0081_auto_20181204_1213.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tests/fixtures/ls_awc_mgt.csv
  custom/icds_reports/tests/outputs/agg_ls_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_ls_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_ls_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_ls_2017-05-01_4_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/agg_ls_data.py
  custom/icds_reports/utils/aggregation_helpers/ls_awc_visit_form.py
Labels: product/invisible

#22636 pass bytes to save_xform
  corehq/apps/app_manager/views/forms.py
Labels: product/invisible

#22635 Stop sending XFormLockError to sentry
  corehq/apps/receiverwrapper/views.py
Labels: product/invisible

#21329 Combining processors by document type
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/change_feed/pillow.py
  corehq/apps/change_feed/tests/test_pillow.py
  corehq/apps/hqadmin/tests/test_utils.py
  corehq/apps/hqcase/tests/test_dbaccessors.py
  corehq/apps/userreports/pillow.py
  corehq/apps/userreports/tests/test_data_source_partitioning.py
  corehq/apps/userreports/tests/test_location_data_source.py
  corehq/apps/userreports/tests/test_multi_db.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/tests/test_report_data.py
  corehq/ex-submodules/couchforms/tests/test_analytics.py
  corehq/ex-submodules/fluff/pillow.py
  corehq/ex-submodules/pillow_retry/tests/test_model.py
  corehq/ex-submodules/pillowtop/feed/interface.py
  corehq/ex-submodules/pillowtop/management/commands/create_checkpoints_for_merged_pillows.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  corehq/ex-submodules/pillowtop/processors/elastic.py
  corehq/ex-submodules/pillowtop/processors/form.py
  corehq/ex-submodules/pillowtop/processors/interface.py
  corehq/ex-submodules/pillowtop/processors/sample.py
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
  corehq/pillows/app_submission_tracker.py
  corehq/pillows/cacheinvalidate.py
  corehq/pillows/case.py
  corehq/pillows/case_search.py
  corehq/pillows/domain.py
  corehq/pillows/group.py
  corehq/pillows/groups_to_user.py
  corehq/pillows/ledger.py
  corehq/pillows/reportcase.py
  corehq/pillows/reportxform.py
  corehq/pillows/sms.py
  corehq/pillows/synclog.py
  corehq/pillows/user.py
  corehq/pillows/xform.py
  custom/_legacy/mvp_docs/pillows.py
  settings.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
  testapps/test_pillowtop/tests/test_case_pillow.py
  testapps/test_pillowtop/tests/test_case_search_pillow.py
  testapps/test_pillowtop/tests/test_form_pillow.py
  testapps/test_pillowtop/tests/test_group_pillow.py
  testapps/test_pillowtop/tests/test_grouptouser_pillow.py
  testapps/test_pillowtop/tests/test_reindexer.py
  testapps/test_pillowtop/tests/test_report_case_pillow.py
  testapps/test_pillowtop/tests/test_report_xform_pillow.py
  testapps/test_pillowtop/tests/test_user_pillow.py
  testapps/test_pillowtop/tests/test_xform_pillow.py
  testapps/test_pillowtop/utils.py
Labels: product/invisible

#22513 make name future proof
  corehq/apps/reports/util.py
  custom/icds_reports/reports/disha.py
Labels: product/custom

#22627 Add query to fix bad form attachment reparenting
  corehq/form_processor/management/commands/run_sql.py
Labels: product/invisible

#22603 RequireJS migration: custom data fields
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
  corehq/apps/custom_data_fields/templates/custom_data_fields/custom_data_fields.html
  corehq/apps/domain/views/settings.py
  corehq/apps/hqadmin/management/commands/clone_domain.py
  corehq/apps/hqwebapp/static/hqwebapp/js/toggles.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/js/toggles_template.js
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/toggle_ui/views.py
  corehq/util/context_processors.py
  settings.py
Labels: product/invisible

#22637 Requirejs migration: commtrack SMS settings page
  corehq/apps/commtrack/static/commtrack/js/sms.js
  corehq/apps/domain/templates/domain/admin/sms_settings.html
Labels: product/invisible

#22638 Requirejs migration: chat contacts page
  corehq/apps/sms/static/sms/js/chat_contacts.js
  corehq/apps/sms/templates/sms/chat_contacts.html
Labels: product/invisible

#22632 Remove zeep
  corehq/ex-submodules/dimagi/utils/post.py
  corehq/motech/README.md
  corehq/motech/repeaters/forms.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/views/__init__.py
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/repeaters.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  requirements/uninstall-requirements.txt
Labels: product/invisible

#22644 encode xform
  corehq/apps/app_manager/views/forms.py
Labels: product/invisible

#22645 Requirejs migration: products and programs
  corehq/apps/commtrack/static/commtrack/js/base_list_view_model.js
  corehq/apps/commtrack/static/commtrack/js/products_and_programs_main.js
  corehq/apps/products/templates/products/manage/product.html
  corehq/apps/products/templates/products/manage/products.html
  corehq/apps/products/templates/products/manage/upload_products.html
  corehq/apps/programs/templates/programs/manage/program.html
  corehq/apps/programs/templates/programs/manage/programs.html
Labels: product/invisible

#22643 [VectorLink] don't show data before welcome sms
  custom/abt/reports/late_pmt.py
Labels: product/custom

#22639 fill todo
  corehq/ex-submodules/pillowtop/management/commands/create_checkpoints_for_merged_pillows.py
Labels: product/invisible

#22641 server disha file via resumable endpoint
  custom/icds_reports/reports/disha.py
  custom/icds_reports/views.py
Labels: product/invisible

#22631 Remove commtrack_enabled lazy migration
  corehq/apps/app_manager/models.py
  corehq/apps/export/tests/data/question_schema_test_app.json
  corehq/apps/sms/tests/app_source.json
Labels: product/invisible

#22487 Appcues v3
  corehq/apps/analytics/ab_tests.py
  corehq/apps/app_manager/static/app_manager/template_apps/agriculture/app.json
  corehq/apps/app_manager/static/app_manager/template_apps/agriculture/multimedia.json
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/app.json
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/multimedia.json
  corehq/apps/app_manager/static/app_manager/template_apps/health/app.json
  corehq/apps/app_manager/static/app_manager/template_apps/health/multimedia.json
  corehq/apps/app_manager/static/app_manager/template_apps/wash/app.json
  corehq/apps/app_manager/static/app_manager/template_apps/wash/multimedia.json
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/registration/tasks.py
  corehq/apps/registration/utils.py
  corehq/apps/registration/views.py
  urls.py
Labels: product/all-users-all-environments

#22648 wrap map with list() before indexing
  custom/care_pathways/utils.py
Labels: product/invisible

#22528 Icds reports lady supervisor ui
  custom/icds_reports/messages.py
  custom/icds_reports/migrations/0078_add_phone_number_to_child_health_monthly.py
  custom/icds_reports/migrations/0081_auto_20181204_1213.py
  custom/icds_reports/migrations/sql_templates/database_views/agg_ls_monthly.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/reports/lady_supervisor.py
  custom/icds_reports/static/css/icds_dashboard.css
  custom/icds_reports/static/icds_reports/js/spec/location-filter.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/navigation.directive.spec.js
  custom/icds_reports/static/js/directives/lady-supervisor/lady-supervisor.directive.js
  custom/icds_reports/static/js/directives/location-filter/location-filter.directive.js
  custom/icds_reports/static/js/directives/navigation/navigation.directive.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/lady-supervisor.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/location_filter.html
  custom/icds_reports/templates/icds_reports/icds_app/navigation.directive.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
  custom/icds_reports/tests/reports/test_lady_supervisor.py
  custom/icds_reports/urls.py
  custom/icds_reports/utils/migrations.py
  custom/icds_reports/views.py
Labels: product/custom

#22628 RequireJS migration: create/edit export
  corehq/apps/export/static/export/js/const.js
  corehq/apps/export/static/export/js/customize_export_new.js
  corehq/apps/export/static/export/js/models.js
  corehq/apps/export/static/export/js/utils.js
  corehq/apps/export/static/export/spec/Exports.Utils.spec.js
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/apps/export/templates/export/partials/new_customize_export_templates.html
  corehq/apps/export/views/edit.py
  corehq/apps/export/views/new.py
  corehq/apps/export/views/utils.py
  corehq/apps/hqwebapp/static/hqwebapp/js/validators.ko.js
Labels: product/invisible

#22655 fix more python 3 tests
  corehq/apps/app_manager/tests/test_form_xmlns.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/blobs/migrate.py
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py
Labels: product/invisible

#22647 log when saving xform errors
  corehq/apps/app_manager/views/forms.py
Labels: product/invisible

#22652 Handle duplicate form attachments
  corehq/form_processor/management/commands/run_sql.py
Labels: product/invisible

#22642 overwrite version tweaks
  corehq/apps/app_manager/management/commands/overwrite_app.py
Labels: product/invisible

#22659 fix icds migrations
  custom/icds_reports/migrations/0081_auto_20181204_1213.py
Labels: product/invisible

#22661 Add toggle to preserve behaviour
  corehq/toggles.py
Labels: product/invisible

#22660 [ICDS] translations for LS reports
  custom/icds_reports/ucr/reports/ls_report_child_names.json
  custom/icds_reports/ucr/reports/ls_report_child_nutrition_status.json
  custom/icds_reports/ucr/reports/ls_report_lbw_pre_term.json
  custom/icds_reports/ucr/reports/ls_report_pregnant_women_names.json
Labels: product/custom

#22634 BlobMeta cleanup
  corehq/apps/export/models/new.py
  corehq/blobs/__init__.py
  corehq/blobs/atomic.py
  corehq/blobs/exceptions.py
  corehq/blobs/fsdb.py
  corehq/blobs/interface.py
  corehq/blobs/migrate.py
  corehq/blobs/migratingdb.py
  corehq/blobs/migrations/0006_restrict_form_attachments.py
  corehq/blobs/mixin.py
  corehq/blobs/s3db.py
  corehq/blobs/tests/test_atomic_old_api.py
  corehq/blobs/tests/test_fsdb_old_api.py
  corehq/blobs/tests/test_migratingdb_old_api.py
  corehq/blobs/tests/test_s3db_old_api.py
  corehq/blobs/tests/util.py
  corehq/blobs/util.py
  corehq/blobs/zipdb.py
  corehq/ex-submodules/soil/tests/test_download_base.py
  corehq/sql_accessors/migrations/0062_form_attachments.py
  corehq/sql_db/operations.py
  corehq/sql_proxy_accessors/migrations/0045_form_attachments.py
Labels: product/invisible

#22657 exclude __pycache__/ directory from couchapps
  corehq/preindex/preindex_plugins.py
Labels: product/invisible

#22215 Limit related case lookups to 500,000 cases
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
Labels: product/feature-flag

#22615 Show 'Unknown' option when case list is missing parent child selectio…
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
Labels: product/all-users-all-environments

#22633 Hide location dropdown filter when turned off
  corehq/apps/reports/static/reports/js/filters/main.js
  corehq/apps/reports/templates/reports/filters/location_async.html
Labels: product/invisible

#22651 Fixed password reset modal switching tabs on page underneath
  corehq/apps/app_manager/static/app_manager/js/settings/password_setter.jquery.js
Labels: product/all-users-all-environments

#22653 Move load_appcues_template_app into tasks.py
  corehq/apps/app_manager/tasks.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/registration/utils.py
Labels: product/all-users-all-environments

#22624 Improve standardization of forms in app manager
  corehq/apps/app_manager/templates/app_manager/import_app.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_detail.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_filtering.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_form_setting.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_setting.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/fixture_case_selection.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_filter.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_case_type.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_settings.html
Labels: product/all-users-all-environments

#22470 Handle errors during the archive/unarchive process
  corehq/apps/userreports/tasks.py
  corehq/ex-submodules/couchforms/migrations/0004_unfinishedarchivestub.py
  corehq/ex-submodules/couchforms/models.py
  corehq/ex-submodules/couchforms/tests/test_archive.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/models.py
  corehq/form_processor/submission_post.py
  corehq/form_processor/submission_process_tracker.py
Labels: product/invisible

#22668 Revert "Handle errors during the archive/unarchive process"
  corehq/apps/userreports/tasks.py
  corehq/ex-submodules/couchforms/migrations/0004_unfinishedarchivestub.py
  corehq/ex-submodules/couchforms/models.py
  corehq/ex-submodules/couchforms/tests/test_archive.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/models.py
  corehq/form_processor/submission_post.py
  corehq/form_processor/submission_process_tracker.py
Labels: product/invisible

#22662 update defusedxml
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#22671 remove use of undefined var
  corehq/apps/linked_domain/remote_accessors.py
Labels: product/invisible

#22650 Redirect form's source to release's page
  corehq/apps/app_manager/views/formdesigner.py
Labels: product/invisible

#22667 Update button layout for messaging insufficient privileges
  corehq/apps/domain/templates/domain/insufficient_privilege_notification.html
Labels: product/all-users-all-environments

#22673 Upgrade couchdbkit
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#22654 RequireJS migration: export download
  corehq/apps/export/static/export/js/download_export.js
  corehq/apps/export/templates/export/download_export.html
  corehq/apps/export/views/download.py
  corehq/apps/hqwebapp/static/hqwebapp/js/daterangepicker.config.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_config.js
  corehq/apps/reports/static/reports/js/reports.util.js
Labels: product/invisible

#22630 Requirejs migration: export list
  corehq/apps/export/static/export/js/create_export.js
  corehq/apps/export/static/export/js/export_list.js
  corehq/apps/export/static/export/js/export_list_main.js
  corehq/apps/export/templates/export/export_list.html
  corehq/apps/export/views/list.py
Labels: product/invisible

#22675 Fix for ICDS UCR tests.
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
  custom/icds_reports/ucr/reports/testing/mpr_10a_person_cases.json
  custom/icds_reports/ucr/reports/testing/mpr_10b_person_cases.json
  custom/icds_reports/ucr/reports/testing/mpr_3ii_person_cases.json
Labels: product/invisible

#22664 Re-use form questions cache during app build
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/app_manager/xform.py
  corehq/apps/reports/tests/readable_forms/mismatched_group_hierarchy.result.yaml
  corehq/apps/reports/tests/readable_forms/top_level_refless_group.result.yaml
Labels: product/invisible

#22678 Revert "Re-use form questions cache during app build"
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/app_manager/xform.py
  corehq/apps/reports/tests/readable_forms/mismatched_group_hierarchy.result.yaml
  corehq/apps/reports/tests/readable_forms/top_level_refless_group.result.yaml
Labels: product/invisible

#22674 don't delete media on ICDS
  corehq/apps/app_manager/tests/test_app_manager.py
  corehq/apps/hqmedia/models.py
Labels: Open for review: do not merge, product/invisible

#22682 Revert "Revert "Re-use form questions cache during app build""
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/app_manager/xform.py
  corehq/apps/reports/tests/readable_forms/mismatched_group_hierarchy.result.yaml
  corehq/apps/reports/tests/readable_forms/top_level_refless_group.result.yaml
Labels: product/invisible

#22677 Fix LS reports
  custom/icds_reports/reports/ucr.py
  custom/icds_reports/ucr/reports/ls_report_child_names.json
  custom/icds_reports/ucr/reports/ls_timely_home_visits.json
Labels: product/custom

#22683 Temporarily disable postgres error rate limiting
  corehq/util/sentry.py
Labels: product/invisible

#22681 Change data not entered message in pregnant report anemia
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#22611 Ce/hide perf
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/views.py
Labels: product/custom

#22676 Clean up language list layout and styling
  corehq/apps/app_manager/static/app_manager/js/supported_languages.js
  corehq/apps/app_manager/templates/app_manager/partials/settings/supported_languages.html
Labels: product/all-users-all-environments

#22688 Revert "Revert "Handle errors during the archive/unarchive process""
  corehq/apps/userreports/tasks.py
  corehq/ex-submodules/couchforms/migrations/0004_unfinishedarchivestub.py
  corehq/ex-submodules/couchforms/models.py
  corehq/ex-submodules/couchforms/tests/test_archive.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/models.py
  corehq/form_processor/submission_post.py
  corehq/form_processor/submission_process_tracker.py
Labels: product/invisible

#22684 add missing unicode literals import
  corehq/util/tests/test_celery_utils.py
Labels: product/invisible

#22686 add new columns to UCR
  custom/icds_reports/ucr/data_sources/child_health_cases.json
  custom/icds_reports/ucr/data_sources/person_cases_v2.json
Labels: product/invisible

#22689 Avoid MultipleObjectsReturned on metadb.get()
  corehq/blobs/metadata.py
  corehq/blobs/tests/test_metadata.py
Labels: product/invisible

#22691 Added cast to list to allow for json serialization
  corehq/apps/hqmedia/models.py
Labels: product/custom

#22697 fix media deletion logging
  corehq/apps/hqmedia/models.py
Labels: product/invisible

#22640 Fix phone number formatting in beneficiary report
  custom/icds_reports/sqldata/exports/beneficiary.py
Labels: product/custom

#22694 Added button to set language as default
  corehq/apps/app_manager/static/app_manager/js/supported_languages.js
  corehq/apps/app_manager/templates/app_manager/partials/settings/supported_languages.html
Labels: product/all-users-all-environments

#22698 [ICDS] Added translations for Gujarati
  custom/icds_reports/ucr/reports/ls_report_child_names.json
  custom/icds_reports/ucr/reports/ls_report_child_nutrition_status.json
  custom/icds_reports/ucr/reports/ls_report_lbw_pre_term.json
  custom/icds_reports/ucr/reports/ls_report_pregnant_women_names.json
Labels: product/custom

#22701 Show 404 Page for deleted export
  corehq/apps/export/views/download.py
Labels: product/all-users-all-environments

#22702 Added protection against request.project being None
  corehq/util/context_processors.py
Labels: product/invisible

#22693 Organize multimedia paths: download
  corehq/apps/hqmedia/templates/hqmedia/bulk_upload_paths.html
  corehq/apps/hqmedia/templates/hqmedia/references.html
  corehq/apps/hqmedia/urls.py
  corehq/apps/hqmedia/views.py
  corehq/toggles.py
Labels: product/custom

#22703 A/B tests: force save user session if session_key is None
  corehq/apps/analytics/ab_tests.py
Labels: product/ab-test, product/invisible

#22692 add kissmetrics events for viewing forms and cases
  corehq/apps/reports/static/reports/js/case_details.js
  corehq/apps/reports/static/reports/js/form_data_main.js
Labels: product/invisible

#22705 Clean up org structure page
  corehq/apps/locations/templates/locations/manage/locations.html
Labels: product/all-users-all-environments

#22707 Killed old multimedia_list_download view
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/multimedia.py
Labels: product/invisible

#22712 Fixed js error on accept invitation page
  corehq/apps/registration/static/registration/js/password.js
Labels: product/invisible

#22713 Removed dead code
  corehq/apps/hqmedia/views.py
Labels: product/invisible

#22687 Clean up role delete message
  corehq/apps/users/static/users/js/roles.js
Labels: product/all-users-all-environments

#22695 get blobmeta by key
  corehq/blobs/metadata.py
  corehq/blobs/tests/test_metadata.py
Labels: product/invisible

#22708 Remove old LOGSTASH_* settings
  localsettings.example.py
  settings.py
Labels: product/invisible

#22714 Standardize multimedia views
  corehq/apps/app_manager/views/modules.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/hqmedia/controller.py
  corehq/apps/hqmedia/templates/hqmedia/bulk_upload.html
  corehq/apps/hqmedia/templates/hqmedia/bulk_upload_paths.html
  corehq/apps/hqmedia/templates/hqmedia/references.html
  corehq/apps/hqmedia/templates/hqmedia/uploader_base.html
  corehq/apps/hqmedia/urls.py
  corehq/apps/hqmedia/views.py
Labels: product/all-users-all-environments

#22715 app media tests
  corehq/apps/app_manager/tests/data/suite/case_list_media_suite.xml
  corehq/apps/app_manager/tests/data/suite/form_media_suite.xml
  corehq/apps/app_manager/tests/data/suite/form_media_suite_en.xml
  corehq/apps/app_manager/tests/data/suite/form_with_media_refs.xml
  corehq/apps/app_manager/tests/test_media_suite.py
Labels: product/invisible

#22718 Fixed always-displaying error message in parent child selection
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
Labels: product/all-users-all-environments

#22710 Zero should not be considered an empty value
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
Labels: product/all-users-all-environments

#22720 Added accessibility page to style guide
  corehq/apps/styleguide/templates/styleguide/_includes/accessibility/background.html
  corehq/apps/styleguide/templates/styleguide/_includes/accessibility/design.html
  corehq/apps/styleguide/templates/styleguide/_includes/accessibility/intro.html
  corehq/apps/styleguide/templates/styleguide/_includes/nav/accessibility.html
  corehq/apps/styleguide/templates/styleguide/base.html
  corehq/apps/styleguide/templates/styleguide/pages/home.html
  corehq/apps/styleguide/urls.py
  corehq/apps/styleguide/views/__init__.py
Labels: product/admin

#22731 Hotfix-Increasae Es timeout limit to 30 seconds
  corehq/elastic.py
Labels: product/invisible

#22723 update jsonobject and jsonobject-couchdbkit
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#22727 pass text to submit_case_blocks for py3 compatibility
  corehq/apps/api/tests.py
  corehq/apps/callcenter/utils.py
  corehq/apps/commtrack/helpers.py
  corehq/apps/hqcase/utils.py
  corehq/apps/users/models.py
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
  corehq/ex-submodules/couchforms/tests/test_edits.py
  corehq/form_processor/tests/test_reprocess_errors.py
  custom/icds/rules/custom_actions.py
  custom/icds/tests/base.py
Labels: product/invisible

#22725 Remove cython from HQ requirements
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  requirements/uninstall-requirements.txt
Labels: product/invisible

#22728 provide status code for mocked post request
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: product/invisible

#22726 fix couchforms/tests/test_xml.py
  corehq/ex-submodules/couchforms/tests/test_xml.py
Labels: product/invisible

#22729 explicitly return domain logo as bytes
  corehq/apps/domain/models.py
Labels: product/invisible

#22732 Pass properties when copying attachments
  corehq/form_processor/models.py
Labels: product/invisible

#22733 Updated primary buttons in media uploader
  corehq/apps/app_manager/templates/app_manager/partials/nav_menu_media_modals.html
  corehq/apps/hqmedia/templates/hqmedia/bulk_upload.html
  corehq/apps/hqmedia/templates/hqmedia/partials/multimedia_uploader.html
Labels: product/all-users-all-environments

#22738 fix corehq.messaging.smsbackends.unicel.tests.test_create_from_request in Py3
  corehq/messaging/smsbackends/unicel/models.py
  corehq/messaging/smsbackends/unicel/tests/test_create_from_request.py
Labels: product/invisible

#22739 fix corehq.doctypemigrations.test by removing unsupported attachment …
  corehq/doctypemigrations/tests.py
Labels: product/invisible

#22735 Tests for multimedia paths download
  corehq/apps/app_manager/tests/data/one_question_two_images.xml
  corehq/apps/hqmedia/tests/__init__.py
  corehq/apps/hqmedia/tests/test_manage_paths.py
  corehq/apps/hqmedia/view_helpers.py
  corehq/apps/hqmedia/views.py
Labels: product/invisible

#22740 only pass unicode to submit_case_blocks
  corehq/apps/hqcase/utils.py
  corehq/apps/users/tests/retire.py
Labels: product/invisible

#22716 Improve commands to move blob metadata to new table
  corehq/blobs/management/commands/run_blob_migration.py
  corehq/form_processor/management/commands/run_sql.py
  corehq/form_processor/tests/test_run_sql.py
  corehq/util/teeout.py
Labels: product/invisible

#22721 Return None no matter what if location isn't found
  corehq/apps/locations/ucr_expressions.py
Labels: product/invisible

#22746 Changed related location select2 widget to v4
  corehq/apps/locations/forms.py
Labels: product/custom

#22747 Updated default HQ fonts
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/includes/variables.less
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
Labels: product/all-users-all-environments

#22745 Organize multimedia paths: upload
  .eslintrc.js
  corehq/apps/case_importer/util.py
  corehq/apps/hqmedia/static/hqmedia/js/manage_paths_main.js
  corehq/apps/hqmedia/templates/hqmedia/bulk_upload_paths.html
  corehq/apps/hqmedia/templates/hqmedia/manage_paths.html
  corehq/apps/hqmedia/tests/test_manage_paths.py
  corehq/apps/hqmedia/urls.py
  corehq/apps/hqmedia/view_helpers.py
  corehq/apps/hqmedia/views.py
Labels: product/custom

#22748 Releases page ui tweaks
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_table.html
Labels: product/all-users-all-environments

#22743 Changed build comment search to ES
  corehq/apps/app_manager/views/releases.py
  corehq/apps/es/apps.py
Labels: product/invisible

#22754 Added multimedia files when calculating ccz download progress
  corehq/apps/hqmedia/views.py
Labels: product/all-users-all-environments

#22759 Add clean method for related locations
  corehq/apps/locations/forms.py
Labels: product/feature-flag

#22753 set the Aggregation level to 4
  custom/icds_reports/views.py
Labels: product/invisible

#22742 Fix removal of translations from transifex
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/app_manager/xform.py
  corehq/apps/reports/tests/readable_forms/mismatched_group_hierarchy.result.yaml
  corehq/apps/reports/tests/readable_forms/top_level_refless_group.result.yaml
  corehq/apps/translations/generators.py
  corehq/apps/translations/tests/data/transifex_blacklist.xml
  corehq/apps/translations/tests/test_transifex_blacklisting.py
Labels: product/custom

#22656 get_xml() for couchforms should return bytes
  corehq/apps/cleanup/management/commands/fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/cleanup/management/commands/fix_xforms_with_undefined_xmlns.py
  corehq/apps/cleanup/tests/test_fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/ex-submodules/couchforms/models.py
  corehq/ex-submodules/couchforms/tests/test_edits.py
  corehq/form_processor/tests/test_form_dbaccessor.py
  corehq/form_processor/tests/test_gdpr_scrub_user_from_forms.py
Labels: product/invisible

#22750 Added copy of original comment when reverting a build
  corehq/apps/app_manager/views/releases.py
Labels: product/all-users-all-environments

#22761 Fixed multimedia download
  corehq/apps/hqmedia/views.py
Labels: product/invisible

#22758 Fix text for LS indicator incorrect
  custom/icds_reports/messages.py
  custom/icds_reports/reports/lady_supervisor.py
  custom/icds_reports/tests/reports/test_lady_supervisor.py
Labels: product/custom

#22763 fix get demo link in trial banner
  corehq/apps/hqwebapp/templates/hqwebapp/partials/get_demo_banner.html
Labels: product/prod-india-all-users

#22419 Change the position of the disclaimer in program summary page
  custom/icds_reports/static/css/icds_dashboard.css
  custom/icds_reports/static/js/directives/system-usage/system-usage.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/system-usage.directive.html
Labels: product/custom

#22762 Fix list data in the widget
  corehq/apps/locations/forms.py
Labels: product/invisible

#22771 Update linked project feature flag help text
  corehq/toggles.py
Labels: product/feature-flag

#22764 fix kissmetrics tracking on trackOutboundClick and trackClick
  corehq/apps/analytics/static/analytix/js/kissmetrix.js
Labels: product/invisible, product/prod-india-all-users

#22751 Display question IDs properly in "Edit Export"
  corehq/apps/export/static/export/js/models.js
  corehq/apps/export/static/export/spec/ExportColumn.spec.js
  corehq/apps/export/static/export/spec/data/export_instances.js
Labels: product/all-users-all-environments

#22722 adds a view to check whether a form has submissions
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/formdesigner.py
  corehq/apps/app_manager/views/forms.py
Labels: product/invisible

#22770 Add progress bar to users download
  corehq/apps/users/bulkupload.py
  corehq/apps/users/tasks.py
Labels: product/all-users-all-environments

#22766 Removed = from app string translation keys
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/tests/test_suite.py
Labels: product/invisible

#22773 [ICDS] GA integration update
  custom/icds_reports/templates/icds_reports/dashboard.html
Labels: product/invisible

#22777 Added check for no comment when reverting
  corehq/apps/app_manager/views/releases.py
Labels: product/invisible

#22778 only pass unicode representations of files to _get_change_counts
  corehq/apps/app_manager/views/download.py
Labels: product/invisible
