Repository dimagi/commcare-hq, pull requests merged in 2018-11, with the labels that each got.

#22250 full property path
  custom/abt/reports/data_sources/supervisory_v2.json
Labels: product/invisible

#22097 Correct date filter for configurable reports
  corehq/apps/userreports/reports/filters/values.py
  corehq/apps/userreports/tests/test_report_filters.py
Labels: product/all-users-all-environments

#22242 [VectorLink] fix for username and phone number
  custom/abt/reports/data_sources/late_pmt.json
  custom/abt/reports/late_pmt.py
Labels: product/custom

#22204 Split exports.views into multiple files
  corehq/apps/dashboard/models.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/export/forms.py
  corehq/apps/export/tests/test_export_views.py
  corehq/apps/export/urls.py
  corehq/apps/export/views.py
  corehq/apps/export/views/__init__.py
  corehq/apps/export/views/download.py
  corehq/apps/export/views/edit.py
  corehq/apps/export/views/list.py
  corehq/apps/export/views/new.py
  corehq/apps/export/views/utils.py
  corehq/apps/users/permissions.py
  corehq/apps/users/tests/permissions.py
  corehq/form_processor/submission_post.py
  corehq/tabs/tabclasses.py
Labels: product/invisible

#22253 Revert "Remove person_cases dependency from child_health"
  custom/icds_reports/utils/aggregation_helpers/child_health_monthly.py
Labels: product/custom

#22254 Adjust to the fact that requests 2.11+ requires header values to be strings
  corehq/apps/formplayer_api/smsforms/api.py
  corehq/ex-submodules/dimagi/utils/post.py
Labels: product/invisible

#22259 Revert "Don't create_all_files twice in live preview"
  corehq/apps/app_manager/models.py
Labels: product/invisible

#22258 Specify database for the transaction in ICDS aggregation
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tasks.py
Labels: product/custom

#22252 indexed on field in case and form API
  corehq/apps/api/es.py
  corehq/apps/api/resources/v0_4.py
  corehq/apps/api/tests.py
  corehq/apps/es/filters.py
Labels: product/all-users-all-environments

#22081 Add closed status in check for pregnant report
  custom/icds_reports/migrations/0069_valid_visits.py
  custom/icds_reports/migrations/0070_aww_name_in_agg_ccs_view.py
  custom/icds_reports/migrations/0073_ccsrecordmonthly_closed.py
  custom/icds_reports/migrations/sql_templates/database_views/ccs_record_monthly_view.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/tests/fixtures/ccs_monthly.csv
  custom/icds_reports/tests/outputs/ccs_record_monthly_2017-05-01_sorted.csv
  custom/icds_reports/tests/reports/test_awc_reports.py
Labels: product/custom

#22095 Add account service type to toggles page
  corehq/apps/toggle_ui/static/toggle_ui/js/edit-flag.js
  corehq/apps/toggle_ui/templates/toggle/edit_flag.html
  corehq/apps/toggle_ui/views.py
Labels: product/admin

#22231 migration dry run
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/progress.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/domain_migration_flags/api.py
  corehq/apps/domain_migration_flags/models.py
  corehq/apps/domain_migration_flags/tests/test_domain_migration_progress.py
Labels: product/invisible

#22269 Specify task in tasks file
  corehq/apps/app_manager/tasks.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/utils.py
Labels: product/custom

#22265 Add KM analytics for linked domains
  corehq/apps/app_manager/views/apps.py
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#22257 dont do any checks in case of no obfuscation
  custom/nic_compliance/tests/test_utils.py
  custom/nic_compliance/utils.py
Labels: product/custom

#22270 Add analytics to the case display page
  corehq/apps/reports/static/reports/js/case_details.js
  corehq/ex-submodules/casexml/apps/case/templates/case/partials/case_hierarchy.html
Labels: product/invisible

#22273 S3 timing and xform locks
  corehq/blobs/s3db.py
  corehq/ex-submodules/dimagi/utils/couch/__init__.py
  corehq/form_processor/interfaces/processor.py
Labels: product/invisible

#22264 Track restore times on large prod domains
  settings.py
Labels: product/invisible

#22274 modernize
  custom/icds_reports/migrations/0072_merge_20181029_1425.py
Labels: product/invisible

#22271 adding back pagination exception handler
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/util/pagination.py
Labels: product/invisible

#22256 Set aadhar_date as null in child_health data source
  custom/icds_reports/ucr/data_sources/child_health_cases.json
Labels: product/custom

#22266 Roll back showing full ancestry on case list page
  corehq/apps/case_migrations/views.py
  corehq/apps/reports/view_helpers.py
  corehq/ex-submodules/casexml/apps/case/templates/case/partials/case_hierarchy.html
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
Labels: product/all-users-all-environments

#22275 [UP-NRHM] use completed on in data filtering (not received_on)
  custom/up_nrhm/sql_data.py
  custom/up_nrhm/tests/reports/test_asha_reports.py
Labels: product/custom

#22278 add warning when changing "Sharing" setting of someone else's export
  corehq/apps/export/static/export/js/customize_export_new.js
  corehq/apps/export/static/export/js/models.js
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/apps/export/views/new.py
Labels: product/feature-flag

#22188 add index for domain and type
  corehq/form_processor/migrations/0075_auto_20181026_0951.py
  corehq/form_processor/models.py
Labels: product/invisible, reindex/migration

#22280 Moved user filter help text to a single line
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/templates/reports/filters/multi_option.html
Labels: product/all-users-all-environments

#22279 fix counter
  corehq/apps/couch_sql_migration/couchsqlmigration.py
Labels: product/invisible

#22277 Send Customer Invoices to Enterprise Admins
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/invoicing.py
Labels: product/all-users-all-environments

#22286 fix typos [ci skip]
  corehq/apps/export/static/export/js/models.js
Labels: product/invisible

#22283 Upgrade to couchdbkit 0.9.11
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#22184 Hide ability to make mobile reports for upstream linked domains
  corehq/apps/app_manager/templates/app_manager/managed_app.html
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/domain/views/exchange.py
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/models.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/feature-flag

#22285 replace observables with constant values
  corehq/apps/export/static/export/js/models.js
  corehq/apps/export/templates/export/customize_export_new.html
Labels: product/invisible

#22282 Add marathi
  custom/icds/translations/integrations/const.py
Labels: product/custom, product/invisible

#22241 move agg awc script to python
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_awc_data.sql
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/agg_awc.py
Labels: product/custom

#22218 Allow MOTECH to only export or only import some values to/from OpenMRS
  corehq/motech/const.py
  corehq/motech/dhis2/tests/test_dhis_config.py
  corehq/motech/openmrs/README.md
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/handler.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/tests/test_value_source.py
  corehq/motech/value_source.py
Labels: product/feature-flag

#21979 analytics tweaks
  corehq/apps/accounting/models.py
  corehq/apps/analytics/management/commands/update_hubspot_properties.py
  corehq/apps/analytics/signals.py
  corehq/apps/analytics/tasks.py
  corehq/apps/analytics/tests/test_subscription_properties.py
  corehq/apps/app_manager/models.py
  corehq/apps/users/tests/test_signals.py
Labels: product/invisible

#22299 fix corehq.motech.openmrs.tests.test_atom_feed in py3
  corehq/motech/openmrs/tests/test_atom_feed.py
Labels: product/invisible

#22284 Date range picker cleanup
  corehq/apps/export/static/export/js/download_export.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/forms.less
  corehq/apps/hqwebapp/widgets.py
Labels: product/invisible

#22302 string.letters -> string.ascii_letters
  corehq/apps/locations/tests/test_permissions.py
Labels: product/invisible

#22305 fix corehq.apps.commtrack.tests.test_locations:LocationsTest.test_arc…
  corehq/apps/commtrack/util.py
Labels: product/invisible

#22307 avoid modifying dict while iterating
  corehq/form_processor/utils/metadata.py
Labels: product/invisible

#22306 fix corehq.apps.data_interfaces.tests.tests:BulkArchiveForms
  corehq/apps/data_interfaces/tests/tests.py
Labels: product/invisible

#22304 fix custom.ilsgateway.tests.handlers.soh_slab:SOHSLABTest.test_stock_…
  corehq/apps/commtrack/sms.py
Labels: product/invisible

#22303 fix corehq.apps.case_importer.tracking.tests.test_filestorage in py3
  corehq/apps/case_importer/tracking/tests/test_filestorage.py
Labels: product/invisible

#22298 fix "TypeError: 'filter' object is not subscriptable"
  corehq/apps/api/tests.py
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/export/tests/test_export_data_schema.py
Labels: product/invisible

#22295 import StringIO from io not six
  corehq/util/tests/test_teeout.py
Labels: product/invisible

#22296 fix corehq.apps.domain.tests.test_two_factor_check:TestTwoFactorCheck…
  corehq/apps/domain/tests/test_two_factor_check.py
Labels: product/invisible

#22310 use row index instead of count in mobile UCRs
  corehq/apps/app_manager/fixtures/mobile_ucr.py
Labels: product/invisible

#22243 move aggregate_awc_daily to python
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_awc_daily.sql
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/agg_awc_daily.py
Labels: product/custom

#22312 Add roma to task notification email
  custom/icds_reports/tasks.py
Labels: product/custom

#22290 Fix unreleased form locks
  corehq/ex-submodules/couchforms/exceptions.py
  corehq/form_processor/parsers/form.py
Labels: product/invisible

#22293 fix "ValueError: empty range for randrange() (1,1, 0)" in python 3
  corehq/apps/accounting/tests/test_customer_invoicing.py
Labels: product/invisible

#22311 use view to provide active confs
  corehq/apps/userreports/data_source_providers.py
Labels: product/invisible

#22297 fix corehq.apps.dump_reload.tests.test_couch_dump_load:CouchDumpLoadT…
  corehq/apps/dump_reload/couch/dump.py
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
Labels: product/invisible

#22291 Apply subscription-level credits to customer invoices
  corehq/apps/accounting/models.py
Labels: product/all-users-all-environments

#22287 Added logging when pruning auto-generated apps
  corehq/apps/app_manager/tasks.py
Labels: product/invisible

#22317 Added correct database to dashboard transaction handling
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tasks.py
Labels: product/custom

#22318 Added help text when choosing project space name
  corehq/apps/registration/templates/registration/domain_request.html
Labels: product/all-users-all-environments

#22292 fix custom.icds_reports.tests in py3
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/utils/aggregation_helpers/__init__.py
  custom/icds_reports/utils/aggregation_helpers/agg_ccs_record.py
  custom/icds_reports/utils/aggregation_helpers/ccs_record_monthly.py
  custom/icds_reports/utils/aggregation_helpers/child_health_monthly.py
Labels: product/invisible

#22294 fix custom.up_nrhm.tests in py3
  custom/up_nrhm/tests/__init__.py
Labels: product/invisible

#22300 fix custom.champ.tests in py3
  custom/champ/tests/__init__.py
Labels: product/invisible

#22323 add missing __init__.py files
  corehq/apps/linked_domain/management/__init__.py
  corehq/apps/linked_domain/management/commands/__init__.py
Labels: product/invisible

#22324 Docs and test
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/form_processor/parsers/form.py
Labels: product/invisible

#22262 update sqlagg
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#22137 atomically update credit line balance + cleanup
  corehq/apps/accounting/models.py
Labels: product/invisible

#22326 handle output of json.dumps in a consistent manner between py2/py3
  corehq/apps/dump_reload/sql/serialization.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/messaging/scheduling/models/timed_schedule.py
Labels: product/invisible

#22329 explicitly decode output of CaseBlock.as_string()
  corehq/apps/commtrack/tests/test_xml.py
  corehq/apps/hqcase/tasks.py
  corehq/apps/hqcase/tests/test_bugs.py
  corehq/apps/hqcase/tests/test_explode_cases.py
  corehq/apps/users/tasks.py
  corehq/apps/users/tests/retire.py
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
  corehq/ex-submodules/casexml/apps/case/util.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_new_sync.py
  corehq/form_processor/tests/test_ledgers.py
  corehq/form_processor/tests/test_reprocess_errors.py
  corehq/form_processor/utils/xform.py
  corehq/util/test_utils.py
Labels: product/invisible

#22330 replace str with bytes
  corehq/ex-submodules/casexml/apps/phone/checksum.py
Labels: product/invisible

#22319 UCR cleanup
  corehq/apps/userreports/models.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/tests/test_pillow.py
  custom/icds_reports/ucr/data_sources/ccs_record_cases_monthly_tableau2.json
  custom/icds_reports/ucr/expressions.py
  custom/icds_reports/ucr/tests/test_expressions.py
Labels: product/invisible

#22327 fix test errors in py3
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
Labels: product/invisible

#22328 explicitly decode response.content
  corehq/apps/api/tests.py
  corehq/apps/hqadmin/views/users.py
  corehq/apps/ota/tests/test_formplayer_restore.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/apps/reports/tests/test_export_api.py
  corehq/apps/sms/tests/test_registration.py
  corehq/ex-submodules/casexml/apps/case/tests/test_domains.py
  corehq/messaging/smsbackends/telerivet/tests/test_log_call.py
Labels: product/invisible

#22276 Download case property history
  corehq/apps/reports/templates/reports/reportdata/case_data.html
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
  corehq/ex-submodules/casexml/apps/case/tests/test_case_history.py
  corehq/ex-submodules/casexml/apps/case/util.py
Labels: product/all-users-all-environments

#22334 don't create data sources for non-existent domain "ct-apr"
  custom/intrahealth/ucr/data_sources/commande_combined.json
  custom/intrahealth/ucr/data_sources/livraison_combined.json
  custom/intrahealth/ucr/data_sources/operateur_combined.json
  custom/intrahealth/ucr/data_sources/rapture_combined.json
  custom/intrahealth/ucr/data_sources/recouvrement_combined.json
Labels: product/invisible

#22335 move reconciliation to after form save before case save
  corehq/form_processor/backends/sql/casedb.py
  corehq/form_processor/backends/sql/processor.py
Labels: product/invisible

#22338 Remove comment that is in conflict with the code
  urls.py
Labels: product/invisible

#22336 423 Locked response on XFormLockError
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/apps/receiverwrapper/views.py
  corehq/form_processor/exceptions.py
  corehq/form_processor/interfaces/processor.py
  corehq/util/datadog/metrics.py
Labels: product/invisible

#22308 update cf visits
  custom/icds_reports/migrations/0074_expected_decimal.py
  custom/icds_reports/migrations/sql_templates/update_tables30.sql
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/reports/incentive.py
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_ccs_record_2017-05-01_5_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/agg_ccs_record.py
  custom/icds_reports/utils/aggregation_helpers/aww_incentive.py
Labels: product/custom

#22342 checking for a non falsy value
  corehq/form_processor/backends/sql/dbaccessors.py
Labels: product/invisible

#22315 Provide document_id as key for kafka partitioning
  corehq/apps/change_feed/producer.py
Labels: product/invisible

#22337 using name
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#22343 use class to get wrapped docs
  corehq/apps/userreports/data_source_providers.py
Labels: product/invisible

#22255 Use sum_when columns for MPR 2A
  custom/icds_reports/ucr/reports/custom_sql_mpr_2a_person_cases.json
  custom/icds_reports/ucr/reports/mobile/mpr_2a_deaths.json
  custom/icds_reports/ucr/reports/mpr_2a_person_cases.json
  settings.py
Labels: product/invisible

#22346 fix corehq.apps.userreports.tests.test_async_indicators:BulkAsyncIndi…
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/tests/test_async_indicators.py
  corehq/apps/userreports/tests/utils.py
Labels: product/invisible

#22347 Updated requirements
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#22339 Add ability to skip uploading entire modules and forms from transifex
  corehq/apps/app_manager/app_translations/app_translations.py
  corehq/apps/app_manager/app_translations/generators.py
Labels: product/custom

#22345 only pass bytes to hashlib.md5
  corehq/apps/userreports/sql/adapter.py
  corehq/ex-submodules/casexml/apps/phone/restore_caching.py
  corehq/ex-submodules/couchexport/models.py
  corehq/ex-submodules/dimagi/utils/django/cache.py
Labels: product/invisible

#22348 UCR cleanup
  corehq/apps/userreports/management/commands/async_rebuild_table.py
  corehq/apps/userreports/pillow.py
  corehq/apps/userreports/reports/specs.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/tests/data/configs/parent_child_data_source.json
  corehq/apps/userreports/util.py
  custom/icds_reports/ucr/tests/base_test.py
Labels: product/invisible

#22222 Configurable OpenMRS Visit and Encounter startDatetime and stopDatetime
  corehq/motech/openmrs/handler.py
  corehq/motech/openmrs/openmrs_config.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/value_source.py
Labels: product/feature-flag

#22350 include visits 7 days after reg
  custom/icds_reports/utils/aggregation_helpers/birth_preparedness_forms.py
  custom/icds_reports/utils/aggregation_helpers/complementary_forms_ccs_record.py
  custom/icds_reports/utils/aggregation_helpers/delivery_forms.py
  custom/icds_reports/utils/aggregation_helpers/postnatal_care_forms_ccs_record.py
Labels: product/custom

#22340 show warning when user changes case type
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/templates/app_manager/module_view.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_case_type.html
Labels: product/all-users-all-environments

#22352 Remove extra text
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_settings.html
Labels: product/invisible

#22359 count cf visits
  custom/icds_reports/utils/aggregation_helpers/aww_incentive.py
Labels: product/custom

#22360 aggregate correctly
  custom/icds_reports/reports/incentive.py
  custom/icds_reports/utils/aggregation_helpers/aww_incentive.py
Labels: product/custom

#22332 Fix transifex integration
  corehq/apps/app_manager/app_translations/generators.py
  corehq/apps/app_manager/app_translations/parser.py
  corehq/apps/app_manager/app_translations/validator.py
Labels: product/custom

#22357 Change Linked Domain button to be more scary
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
Labels: product/feature-flag

#22353 Don't ignore extra_fields
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/value_source.py
Labels: product/feature-flag, product/invisible

#22364 check that credit line balance matches credit adjustments
  corehq/apps/accounting/tasks.py
Labels: product/invisible

#22358 Documentation for form metadata and OpenmrsFormConfigs
  corehq/motech/openmrs/README.md
Labels: product/feature-flag, product/invisible

#22354 Better error messages for openmrs_start_datetime
  corehq/motech/exceptions.py
  corehq/motech/openmrs/handler.py
Labels: product/feature-flag, product/invisible

#22369 Profile more build operations
  corehq/apps/app_manager/models.py
  corehq/apps/hqmedia/tasks.py
Labels: product/admin

#22367 remove unused args to create_wire_credits_invoice
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/tasks.py
Labels: product/invisible

#22370 fix corehq.apps.userreports.tests.test_pillow:RebuildTableTest.test_a…
  corehq/apps/userreports/tests/test_pillow.py
Labels: product/invisible

#22371 fix intrahealth tests in py3
  custom/intrahealth/tests/__init__.py
Labels: product/invisible

#22376 bytes literal -> unicode literal
  corehq/apps/app_manager/tests/test_suite.py
Labels: product/invisible

#22377 fix soil.tests.test_download_base:TestBlobDownload
  corehq/ex-submodules/soil/tests/test_download_base.py
Labels: product/invisible

#22373 explicitly decode output of ElementTree.tostring()
  corehq/ex-submodules/casexml/apps/case/cleanup.py
  custom/bihar/utils.py
Labels: product/invisible

#22384 make get_table_name return unicode
  corehq/apps/userreports/util.py
Labels: product/invisible

#22385 fix "RuntimeError: dictionary changed size during iteration" in python 3
  corehq/apps/hqmedia/models.py
Labels: product/invisible

#22387 fix pillow_retry.tests.test_all_pillows:PillowtopRetryAllPillowsTests…
  corehq/ex-submodules/pillow_retry/tests/test_all_pillows.py
Labels: product/invisible

#22375 fix corehq/blobs/tests/ in python 3
  corehq/blobs/tests/test_blob_timeout.py
  corehq/blobs/tests/test_fsdb.py
  corehq/blobs/tests/test_fsdb_old_api.py
  corehq/blobs/tests/test_init.py
  corehq/blobs/tests/test_mixin.py
Labels: product/invisible

#22378 byte is an integer in py3
  corehq/ex-submodules/dimagi/utils/data/deid_generator.py
Labels: product/invisible

#21784 replace assertItemsEqual
  .travis.yml
  corehq/apps/accounting/tests/test_autopay.py
  corehq/apps/case_migrations/tests/test_restore.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/fixtures/tests/test_location_ownership.py
  corehq/apps/fixtures/tests/test_upload.py
  corehq/apps/hqadmin/tests/test_clone_domain.py
  corehq/apps/hqcase/tests/test_dbaccessors.py
  corehq/apps/locations/tests/test_change_has_user.py
  corehq/apps/locations/tests/test_location_fixtures.py
  corehq/apps/locations/tests/test_location_queries.py
  corehq/apps/locations/tests/test_location_utils.py
  corehq/apps/locations/tests/test_locations.py
  corehq/apps/userreports/tests/test_choice_provider.py
  corehq/apps/userreports/tests/test_location_data_source.py
  corehq/ex-submodules/casexml/apps/case/tests/test_db_accessors.py
  corehq/motech/repeaters/tests/test_dbaccessors.py
  custom/icds/tests/test_immunization.py
  testapps/test_pillowtop/tests/test_app_pillow.py
  testapps/test_pillowtop/tests/test_case_search_pillow.py
Labels: product/invisible

#22395 Revert "fix corehq.motech.repeaters.tests.test_repeater:FormRepeaterTest.test…"
  corehq/form_processor/models.py
Labels: product/invisible

#22382 remove unnecessary if
  corehq/form_processor/models.py
Labels: product/invisible

#22372 pass bytes to b64encode and decode output where necessary
  corehq/apps/api/tests.py
  corehq/apps/ota/tests/test_heartbeat.py
  corehq/apps/ota/tests/test_restore_user_check.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tests/test_registration.py
  corehq/doctypemigrations/tests.py
  custom/nic_compliance/utils.py
Labels: product/invisible

#22272 resumable iteration rebase
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/ex-submodules/pillowtop/reindexer/change_providers/couch.py
Labels: product/invisible

#22397 IPM-senegal: Add a missing args to the function input
  corehq/apps/app_manager/models.py
Labels: product/feature-flag

#22388 fix corehq.apps.reports.tests.test_filters:TestLocationRestrictedMobi…
  corehq/apps/reports/tests/test_filters.py
Labels: product/invisible

#22309 drop unused sql functions
  custom/icds_reports/migrations/0075_drop_agg_funcs.py
Labels: product/custom

#22392 add mapping for 3 langs
  custom/icds/translations/integrations/const.py
Labels: product/custom

#22368 Optimized person case UCR data source
  custom/icds_reports/management/commands/migrate_person_cases_ucr.py
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
  custom/icds_reports/ucr/reports/testing/asr_2_3_beneficiaries.json
  custom/icds_reports/ucr/reports/testing/asr_2_3_person_cases.json
  custom/icds_reports/ucr/reports/testing/mpr_3i_person_cases.json
  custom/icds_reports/ucr/reports/testing/mpr_3i_pregnancies.json
  settings.py
Labels: product/custom

#22404 fix corehq.apps.dump_reload.tests.test_couch_dump_load:CouchDumpLoadT…
  corehq/apps/mobile_auth/models.py
Labels: product/invisible

#22415 casexml.apps.case.tests.test_from_xform:CaseFromXFormTest.testCreate
  corehq/ex-submodules/casexml/apps/case/tests/util.py
Labels: product/invisible

#22416 decode bytes in tests
  corehq/ex-submodules/casexml/apps/case/mock/tests/test_case_block.py
Labels: product/invisible

#22414 pass bytes to hashlib.sha1
  corehq/apps/sms/models.py
  corehq/apps/sms/tasks.py
Labels: product/invisible

#22411 use next (not indexing) on filter
  custom/icds_reports/tests/reports/test_awc_reports.py
Labels: product/invisible

#22409 fix openclinica tests
  custom/openclinica/tests/test_odm_to_app.py
  custom/openclinica/tests/test_utils.py
Labels: product/invisible

#22407 use byte literals
  corehq/ex-submodules/couchexport/tests/test_saved.py
Labels: product/invisible

#22405 decode bytestring
  corehq/apps/reports/tests/test_scheduled_reports.py
Labels: product/invisible

#22402 use next instead of indexing on filter()
  corehq/apps/export/tests/test_export_data_schema.py
Labels: product/invisible

#22401 use byte literals (for py3)
  corehq/apps/app_manager/xpath_validator/tests.py
Labels: product/invisible

#22399 replace several self.assertItemEquals uses
  corehq/apps/linked_domain/tests/test_linked_case_claim.py
  corehq/apps/userreports/tests/test_report_aggregation.py
Labels: product/invisible

#22394 Test extra_fields
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/value_source.py
Labels: product/feature-flag, product/invisible

#22400 only pass bytes to send()
  corehq/apps/change_feed/producer.py
Labels: product/invisible

#22403 fix "TypeError: '>=' not supported between instances of 'NoneType' an…
  corehq/apps/export/utils.py
Labels: product/invisible

#22386 fix corehq.apps.ota.tests.test_formplayer_restore:FormplayerRestoreTe…
  corehq/apps/hqadmin/tests/test_utils.py
Labels: product/invisible

#22408 fix corehq.apps.ota.tests.test_demo_user:TestDemoUser.test_demo_user_…
  corehq/apps/ota/tests/test_demo_user.py
Labels: product/invisible

#22363 Fixes creating OpenMRS Encounters with encounterProvider set
  corehq/motech/openmrs/README.md
  corehq/motech/openmrs/exceptions.py
  corehq/motech/openmrs/forms.py
  corehq/motech/openmrs/repeater_helpers.py
Labels: product/feature-flag, product/invisible

#22412 fix custom.icds_reports.tests.test_aggregation_script:AggAwcAggregati…
  custom/icds_reports/tests/test_aggregation_script.py
Labels: product/invisible

#22406 fix corehq.apps.userreports.tests.test_pillow:IndicatorPillowTest.tes…
  corehq/apps/userreports/models.py
Labels: product/invisible

#22418 Commit package-lock.json
  package-lock.json
Labels: product/invisible

#22396 move reconciliation out of transaction
  corehq/form_processor/backends/sql/processor.py
Labels: product/invisible

#22206 Add rohit email to dashboard team emails
  custom/icds_reports/tasks.py
Labels: product/invisible

#22422 remove old soft_asserts
  corehq/ex-submodules/dimagi/ext/couchdbkit.py
Labels: product/invisible

#22445 fix corehq.apps.locations.tests.test_location_fixtures:LocationFixtur...
  corehq/apps/locations/models.py
Labels: product/invisible

#22444 fix corehq.apps.receiverwrapper.tests.test_auth:AuthTest.test_bad_noauth
  corehq/apps/receiverwrapper/tests/test_auth.py
Labels: product/invisible

#22442 fix custom.icds_reports.ucr.tests.test_ccs_record_monthly.TestCCSReco..
  corehq/apps/userreports/sql/adapter.py
Labels: product/invisible

#22441 fix corehq.apps.userreports.tests.test_data_source_partitioning.DataS..
  corehq/apps/userreports/sql/adapter.py
Labels: product/invisible

#22443 fix corehq.apps.userreports.tests.test_filters:BooleanExpressionFilte...
  corehq/apps/userreports/operators.py
Labels: product/invisible

#22429 replace assertItemsEqual in test_get_fixture_data_types_in_domain
  corehq/apps/fixtures/tests/test_dbaccessors.py
Labels: product/invisible
