Repository dimagi/commcare-hq, pull requests merged in 2018-02, with the labels that each got.

#19393 python-modernize . -w -f libmodernize.fixes.fix_unichr
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
Labels: product/invisible

#19385 billing tasks should ignore domains that haven't been activated
  corehq/apps/accounting/tasks.py
Labels: product/invisible

#19394 Reset get_sql_locations cache after changing assigned_location_ids
  corehq/apps/users/models.py
Labels: product/invisible

#19397 remove unreferenced HQ_INSTANCE variable
  settings.py
Labels: product/invisible

#19399 Make page heading a level higher [ci skip]
  docs/elasticsearch.rst
Labels: product/invisible

#19401 send run_case_update_rules_for_domain tasks to case_rule_queue
  corehq/apps/data_interfaces/tasks.py
Labels: product/invisible

#19396 update .stickler.yml
  .stickler.yml
Labels: product/invisible

#19298 add build info
  corehq/warehouse/migrations/0023_add_build_info.py
  corehq/warehouse/models/dimensions.py
  corehq/warehouse/models/staging.py
  corehq/warehouse/transforms/sql/application_dim.sql
Labels: product/invisible

#19398 Add datetime to shell_plus [ci skip]
  dev_settings.py
Labels: product/invisible

#19384 Hard code celery queue names
  settings.py
Labels: product/invisible

#19410 Migrate boolean columns to integer columns in infrastructure form UCR.
  custom/icds_reports/ucr/data_sources/infrastructure_form.json
Labels: product/custom

#19403 forcing translation to properly show edited forms
  corehq/apps/reports/templatetags/xform_tags.py
Labels: product/invisible

#19411 Add datadog metric for seconds since last checkpoint update.
  corehq/ex-submodules/pillowtop/tasks.py
  corehq/ex-submodules/pillowtop/utils.py
Labels: product/invisible

#19413 python-modernize . -w -f libmodernize.fixes.fix_map
  custom/enikshay/management/commands/drug_resistance_reconciliation.py
  custom/enikshay/management/commands/duplicate_occurrences_and_episodes_reconciliation.py
  custom/enikshay/management/commands/multiple_open_referrals_reconciliation.py
Labels: product/invisible

#19415 fix uses of built-in filter
  corehq/apps/case_importer/util.py
  corehq/apps/userreports/sql/util.py
  corehq/messaging/tasks.py
  corehq/util/sentry.py
  custom/enikshay/management/commands/resolve_duplicate_persons.py
Labels: product/invisible

#19400 Show error message even if response fails
  corehq/apps/userreports/static/userreports/js/expression_evaluator.js
Labels: product/all-users-all-environments

#19419 Add widowed as marital status option
  custom/enikshay/integrations/ninetyninedots/api_properties.yaml
Labels: product/custom

#19381 more linked domain progress
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/management/commands/link_app_to_remote.py
  corehq/apps/app_manager/management/commands/link_apps.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/app_view_settings.html
  corehq/apps/app_manager/templates/app_manager/partials/app-settings.html
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/domain/urls.py
  corehq/apps/linked_domain/admin.py
  corehq/apps/linked_domain/applications.py
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/management/commands/__init__.py
  corehq/apps/linked_domain/management/commands/update_linked_domain.py
  corehq/apps/linked_domain/migrations/0002_migrate_linked_apps.py
  corehq/apps/linked_domain/migrations/0003_auto_20180207_0857.py
  corehq/apps/linked_domain/migrations/0004_domainlinkhistory.py
  corehq/apps/linked_domain/migrations/0005_migrate_linked_app_toggle.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/tests/__init__.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/linked_domain/tests/test_remote_auth.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/urls.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/views.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
  urls.py
Labels: product/custom, product/feature-flag

#19405 Fix form details view
  corehq/apps/reports/templates/reports/form/partials/single_form.html
  corehq/apps/reports/templatetags/xform_tags.py
Labels: product/all-users-all-environments

#18981 Add 99DOTS unenroll patient repeater
  custom/enikshay/integrations/bets/tests/test_repeaters.py
  custom/enikshay/integrations/ninetyninedots/repeater_generators.py
  custom/enikshay/integrations/ninetyninedots/repeaters.py
  custom/enikshay/integrations/ninetyninedots/tests/test_payload_generators.py
  custom/enikshay/integrations/ninetyninedots/tests/test_repeaters.py
  custom/enikshay/integrations/ninetyninedots/urls.py
  custom/enikshay/integrations/ninetyninedots/views.py
  settings.py
Labels: product/custom

#19383 ejs confirm billing info
  corehq/apps/domain/static/domain/js/confirm_billing_info.js
  corehq/apps/domain/templates/domain/confirm_billing_info.html
Labels: product/invisible

#19376 ejs internal billing
  corehq/apps/accounting/static/accounting/js/credits.js
  corehq/apps/domain/static/domain/js/billing_statements.js
  corehq/apps/domain/templates/domain/billing_statements.html
  corehq/apps/domain/views.py
  corehq/apps/hqwebapp/templates/hqwebapp/base_paginated_crud.html
  corehq/apps/sms/templates/sms/manage_registration_invitations.html
Labels: product/invisible

#19406 externalizing confirm plan js
  corehq/apps/domain/static/domain/js/confirm_plan.js
  corehq/apps/domain/templates/domain/confirm_plan.html
Labels: product/invisible

#19423 Fix properties used in the Low Birth weight indicator
  custom/icds_reports/reports/adhaar.py
  custom/icds_reports/reports/adult_weight_scale.py
  custom/icds_reports/reports/awc_daily_status.py
  custom/icds_reports/reports/children_initiated_data.py
  custom/icds_reports/reports/clean_water.py
  custom/icds_reports/reports/early_initiation_breastfeeding.py
  custom/icds_reports/reports/exclusive_breastfeeding.py
  custom/icds_reports/reports/functional_toilet.py
  custom/icds_reports/reports/immunization_coverage_data.py
  custom/icds_reports/reports/infants_weight_scale.py
  custom/icds_reports/reports/institutional_deliveries_sector.py
  custom/icds_reports/reports/medicine_kit.py
  custom/icds_reports/reports/new_born_with_low_weight.py
  custom/icds_reports/sqldata.py
  custom/icds_reports/static/icds_reports/js/spec/newborn_with_low_weight.directive.spec.js
  custom/icds_reports/static/js/directives/newborn_with_low_weight/newborn_with_low_weight.directive.js
  custom/icds_reports/tests/reports/test_new_born_with_low_weight.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/tests/test_utils.py
  custom/icds_reports/utils.py
Labels: product/custom

#19427 ICDS Data validation task
  custom/icds_reports/tasks.py
Labels: product/custom

#19422 270212 exports events
  corehq/apps/export/static/export/js/list_exports.ng.js
  corehq/apps/export/static/export/spec/ListExportsController.spec.mo.js
  corehq/apps/reports/static/reports/js/reports.config.js
Labels: product/invisible

#19428 Preserve location custom field ordering in export
  corehq/apps/locations/tests/test_export.py
  corehq/apps/locations/util.py
Labels: product/all-users-all-environments

#19425 Only run reconcilliation task on private sector episodes
  custom/enikshay/tasks.py
  custom/enikshay/tests/test_adherence_updates.py
  custom/enikshay/tests/test_voucher_counts.py
Labels: product/custom

#19402 Resurrect exports list on dashboard
  corehq/apps/dashboard/models.py
  corehq/apps/dashboard/static/dashboard/js/dashboard.js
  corehq/apps/dashboard/templates/dashboard/base.html
  corehq/apps/dashboard/urls.py
  corehq/apps/dashboard/views.py
Labels: product/all-users-all-environments

#19392 Bump SQLAlchemy to 1.2.2
  requirements/requirements.txt
Labels: product/invisible

#19407 Update ethiopian conversion to expect datetime
  corehq/apps/userreports/tests/test_transforms.py
  corehq/apps/userreports/transforms/custom/date.py
Labels: product/all-users-all-environments

#19431 Fix order of migrations.
  corehq/apps/linked_domain/migrations/0002_migrate_linked_apps.py
  corehq/apps/linked_domain/migrations/0003_auto_20180207_0857.py
Labels: product/invisible

#19432 Fix pillow datadog metrics.
  corehq/ex-submodules/pillowtop/tasks.py
Labels: product/invisible

#19429 Also preserve order of product codes
  corehq/apps/locations/util.py
Labels: product/invisible

#19433 run remaining modernize fixers
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/remote_app.py
  corehq/apps/cleanup/management/commands/undo_uuid_clash.py
  corehq/apps/data_interfaces/migrations/0014_createscheduleinstanceactiondefinition_start_date_case_property.py
  corehq/apps/data_interfaces/migrations/0015_automaticupdaterule_locked_for_editing.py
  corehq/apps/domain/forms.py
  corehq/apps/domainsync/management/commands/copy_domain.py
  corehq/apps/es/management/commands/resave_failed_forms_and_cases.py
  corehq/apps/export/migrations/0003_emailexportwhendonerequest.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/migrations/0001_initial.py
  corehq/apps/linked_domain/models.py
  corehq/apps/locations/bulk_management.py
  corehq/apps/locations/const.py
  corehq/apps/locations/util.py
  corehq/apps/locations/views.py
  corehq/apps/sms/migrations/0028_messagingevent_source.py
  corehq/apps/sms/migrations/0029_daily_outbound_sms_limit_reached.py
  corehq/apps/smsforms/migrations/0002_add_state_tracking_fields.py
  corehq/apps/smsforms/migrations/0003_make_fields_not_null.py
  corehq/apps/userreports/decorators.py
  corehq/apps/userreports/filters/__init__.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/tests/test_tasks.py
  corehq/blobs/migrations/0007_invoicepdf.py
  corehq/ex-submodules/dimagi/utils/requestskit.py
  corehq/messaging/scheduling/migrations/0008_timedschedule_event_type.py
  corehq/messaging/scheduling/migrations/0009_randomtimedevent.py
  corehq/messaging/scheduling/migrations/0010_casepropertytimedevent.py
  corehq/messaging/scheduling/migrations/0011_add_broadcast_deleted_flag.py
  corehq/messaging/scheduling/migrations/0012_add_schedule_deleted_flag.py
  corehq/messaging/scheduling/migrations/0013_advanced_survey_options.py
  corehq/messaging/scheduling/models/timed_schedule.py
  corehq/messaging/scheduling/tests/test_schedules.py
  corehq/messaging/smsbackends/grapevine/models.py
  corehq/motech/openmrs/views.py
  corehq/motech/repeaters/models.py
  corehq/tabs/uitab.py
  corehq/tabs/utils.py
  custom/enikshay/forms.py
  custom/enikshay/management/commands/drug_resistance_reconciliation.py
  custom/enikshay/management/commands/duplicate_occurrences_and_episodes_reconciliation.py
  custom/enikshay/management/commands/investigations_reconciliation.py
  custom/enikshay/management/commands/multiple_open_referrals_reconciliation.py
  custom/enikshay/tests/test_adherence_updates.py
  custom/enikshay/user_setup.py
  custom/icds_reports/migrations/0028_auto_20171204_1922.py
  custom/icds_reports/migrations/0029_add_add_and_dob_to_intermediate_tables.py
  custom/icds_reports/migrations/0030_auto_20171128_0042.py
  custom/icds_reports/migrations/0031_agg_child_health_definitions.py
  custom/icds_reports/migrations/0032_create_datasource_views.py
  custom/icds_reports/migrations/0033_add_new_aadhaar_indicators.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/utils.py
Labels: product/invisible

#19409 Add visit scheduler integration to scheduling UI
  corehq/messaging/scheduling/async_handlers.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
  corehq/messaging/scheduling/templates/scheduling/create_schedule_base.html
  corehq/messaging/scheduling/views.py
Labels: product/feature-flag

#19434 Reorganize repeater views
  corehq/apps/domain/urls.py
  corehq/apps/domain/views.py
  corehq/motech/repeaters/views.py
  corehq/motech/repeaters/views/__init__.py
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/repeaters.py
  corehq/reports.py
  custom/enikshay/integrations/bets/urls.py
  custom/enikshay/integrations/nikshay/views.py
  custom/enikshay/reports/repeaters.py
Labels: product/invisible

#19437 use / for timedelta division
  custom/bihar/calculations/homevisit.py
  custom/ilsgateway/tanzania/warehouse/updater.py
Labels: product/invisible

#19440 Fix doubling info message
  custom/icds_reports/static/icds_reports/js/spec/awc-reports.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/progress-report.directive.spec.js
  custom/icds_reports/static/js/directives/adhaar-beneficiary/adhaar-beneficiary.directive.js
  custom/icds_reports/static/js/directives/adolescent-girls/adolescent-girls.directive.js
  custom/icds_reports/static/js/directives/adult-weight-scale/adult-weight-scale.directive.js
  custom/icds_reports/static/js/directives/awc-daily-status/awc-daily-status.directive.js
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/static/js/directives/awcs-covered/awcs-covered.directive.js
  custom/icds_reports/static/js/directives/children-initiated/children-initiated.directive.js
  custom/icds_reports/static/js/directives/clean-water/clean-water.directive.js
  custom/icds_reports/static/js/directives/early_initiation_breastfeeding/early_initiation_breastfeeding.directive.js
  custom/icds_reports/static/js/directives/enrolled-children/enrolled-children.directive.js
  custom/icds_reports/static/js/directives/enrolled-women/enrolled-women.directive.js
  custom/icds_reports/static/js/directives/exclusive-breastfeeding/exlusive-breastfeeding.directive.js
  custom/icds_reports/static/js/directives/functional-toilet/functional-toilet.directive.js
  custom/icds_reports/static/js/directives/immunization_coverage/immunization_coverage.directive.js
  custom/icds_reports/static/js/directives/infants-weight-scale/infants-weight-scale.directive.js
  custom/icds_reports/static/js/directives/institutional-deliveries/institutional-deliveries.directive.js
  custom/icds_reports/static/js/directives/lactating-enrolled-women/lactating-enrolled-women.directive.js
  custom/icds_reports/static/js/directives/medicine-kit/medicine-kit.directive.js
  custom/icds_reports/static/js/directives/newborn_with_low_weight/newborn_with_low_weight.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-severe-report/prevalence-of-severe-report.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-stunting-report/prevalence-of-stunting-report.directive.js
  custom/icds_reports/static/js/directives/progress-report/progress-report.directive.js
  custom/icds_reports/static/js/directives/registered-household/registered-household.directive.js
  custom/icds_reports/static/js/directives/underweight-children-report/underweight-children-report.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/system-usage.directive.html
Labels: product/custom

#19436 preserve int division
  corehq/apps/callcenter/checks.py
  corehq/apps/dropbox/management/commands/upload_file_to_dropbox.py
  corehq/apps/export/multiprocess.py
  corehq/apps/export/views.py
  corehq/ex-submodules/dimagi/utils/couch/loosechange.py
  corehq/ex-submodules/dimagi/utils/dates.py
  corehq/middleware.py
  corehq/util/dates.py
  custom/apps/gsid/reports/sql_reports.py
  custom/up_nrhm/reports/asha_functionality_checklist_report.py
  custom/up_nrhm/reports/block_level_af_report.py
  custom/world_vision/sqldata/main_sqldata.py
Labels: product/invisible

#19441 remove int()
  corehq/apps/callcenter/checks.py
Labels: product/invisible

#19424 Limit beneficiary requests to one and if possible retrieve limited qu…
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/static/icds_reports/js/spec/awc-reports.directive.spec.js
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/awc-reports.html
Labels: product/custom

#19418 Add filters for migration and availing services
  custom/icds_reports/ucr/reports/ls_born_last_30_days.json
Labels: product/custom

#19443 Fix card titles misalignment
  custom/icds_reports/static/css/icds_dashboard.css
  custom/icds_reports/templates/icds_reports/icds_app/kpi.directive.html
Labels: product/custom

#19444 use integer division
  custom/enikshay/user_setup.py
Labels: product/invisible

#19445 convert to py3 division
  custom/up_nrhm/reports/block_level_month_report.py
Labels: product/invisible

#19446 py3 div: some of the trickier changes
  corehq/apps/callcenter/tests/test_owner_options_view.py
  corehq/apps/reports/commtrack/standard.py
  corehq/apps/reports/standard/monitoring.py
  corehq/util/log.py
  custom/bihar/reports/display.py
  custom/ewsghana/reports/stock_levels_report.py
Labels: product/invisible

#19389 change sign up text
  corehq/apps/registration/templates/registration/partials/register_new_user/submit_info.html
Labels: product/all-users-all-environments

#19449 Remove flag required for case restore endpoint
  corehq/apps/case_migrations/views.py
Labels: product/invisible

#19438 Add feature flag to enable migrating domains to new reminders framework
  corehq/apps/reminders/util.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/views.py
  corehq/messaging/scheduling/views.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/invisible

#19461 ejs/update billing contact info
  corehq/apps/domain/static/domain/js/update_billing_contact_info.js
  corehq/apps/domain/templates/domain/update_billing_contact_info.html
  corehq/apps/domain/views.py
  scripts/externalize_js.sh
Labels: product/invisible

#19464 Set max open files for couch in docker
  docker/hq-compose.yml
Labels: product/invisible

#19467 Small updates to new reminders UI
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
Labels: product/feature-flag

#19465 delete performance sms functionality
  corehq/apps/performance_sms/__init__.py
  corehq/apps/performance_sms/_design/views/by_schedule/map.js
  corehq/apps/performance_sms/_design/views/by_schedule/reduce.js
  corehq/apps/performance_sms/dbaccessors.py
  corehq/apps/performance_sms/exceptions.py
  corehq/apps/performance_sms/forms.py
  corehq/apps/performance_sms/message_sender.py
  corehq/apps/performance_sms/models.py
  corehq/apps/performance_sms/parser.py
  corehq/apps/performance_sms/query_engine.py
  corehq/apps/performance_sms/schedule.py
  corehq/apps/performance_sms/tasks.py
  corehq/apps/performance_sms/templates/performance_sms/edit_performance_config.html
  corehq/apps/performance_sms/templates/performance_sms/list_performance_configs.html
  corehq/apps/performance_sms/tests/__init__.py
  corehq/apps/performance_sms/tests/test_dbaccessors.py
  corehq/apps/performance_sms/tests/test_parser.py
  corehq/apps/performance_sms/tests/test_schedule.py
  corehq/apps/performance_sms/urls.py
  corehq/apps/performance_sms/views.py
  corehq/apps/sms/filters.py
  corehq/apps/sms/models.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
  settings.py
  urls.py
Labels: product/feature-flag

#19469 use integer division in total row for ipm-senegal custom report
  custom/intrahealth/sqldata.py
Labels: product/invisible

#19448 Pv/new phone 266472
  corehq/apps/domain/templates/login_and_password/two_factor/profile/profile.html
  corehq/apps/hqwebapp/urls.py
  corehq/apps/settings/views.py
Labels: product/all-users-all-environments

#19468 ejs/sms add forwarding rule
  corehq/apps/sms/static/sms/js/add_forwarding_rule.js
  corehq/apps/sms/templates/sms/add_forwarding_rule.html
  scripts/externalize_js.sh
Labels: product/invisible

#19476 Fix tooltip for adolescent girls
  custom/icds_reports/static/icds_reports/js/spec/adolescent-girls.directive.spec.js
  custom/icds_reports/static/js/directives/adolescent-girls/adolescent-girls.directive.js
Labels: product/custom

#19472 Prevent doubling data from previous month info box in fact sheet and …
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/templates/icds_reports/dashboard.html
Labels: product/custom

#19470 Ability to filter releases page by "released"
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/templates/app_manager/partials/releases_table.html
  corehq/apps/app_manager/views/releases.py
Labels: product/all-users-all-environments

#19430 Add command to find datasource mismatches
  corehq/apps/userreports/management/commands/find_datasource_mismatches.py
Labels: product/invisible

#19477 use // in py2 for timedelta div
  custom/bihar/calculations/homevisit.py
  custom/ilsgateway/tanzania/warehouse/updater.py
Labels: product/invisible

#19478 ejs/externalize js script template tags
  scripts/externalize_js.sh
Labels: product/invisible

#19463 Add filters migration status availing services
  custom/icds_reports/ucr/reports/ls_timely_home_visits.json
Labels: product/custom

#19453 Add filters migration status availing services
  custom/icds_reports/ucr/reports/ls_comp_feeding.json
Labels: product/custom

#19452 Add filters migration status availing services
  custom/icds_reports/ucr/reports/ls_ebf.json
Labels: product/custom

#19451 Add filters migration status availing services
  custom/icds_reports/ucr/reports/ls_children_weighed.json
Labels: product/custom

#19450 Add filters migration status availing services
  custom/icds_reports/ucr/reports/ls_report_pregnant_women_names.json
Labels: product/custom

#19416 ejs repeat record report
  corehq/apps/domain/static/domain/js/repeat_record_report.js
  corehq/apps/domain/templates/domain/repeat_record_report.html
Labels: product/invisible

#19435 Limit periodic data task by server
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#19471 More hqDefine
  corehq/apps/app_manager/static/app_manager/js/import_app.js
  corehq/apps/app_manager/templates/app_manager/module_view.html
  corehq/apps/appstore/static/appstore/js/facet_sidebar.js
  corehq/apps/fixtures/static/fixtures/js/lookup-manage.js
  corehq/apps/fixtures/static/fixtures/js/view-table.js
  corehq/apps/hqadmin/static/hqadmin/js/domain_faceted_report.js
  corehq/apps/hqadmin/static/hqadmin/js/visualizations.js
  corehq/apps/hqadmin/templates/hqadmin/indicator_report.html
  corehq/apps/hqwebapp/static/hqwebapp/js/common.js
  corehq/apps/hqwebapp/static/hqwebapp/js/guidGenerator.js
  corehq/apps/hqwebapp/static/hqwebapp/js/lib/compression.js
Labels: product/invisible

#19439 linked domain history report
  corehq/apps/linked_domain/admin.py
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/filters.py
  corehq/apps/linked_domain/migrations/0006_auto_20180208_1139.py
  corehq/apps/linked_domain/migrations/0007_auto_20180215_1434.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/tests/test_link_domains.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/views.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#19481 Release organization tree search
  corehq/apps/locations/static/locations/js/location_tree.async.js
  corehq/apps/locations/templates/locations/manage/locations.html
  corehq/apps/locations/views.py
  corehq/toggles.py
Labels: product/all-users-all-environments

#19325 Choose the right EditFooRepeaterView
  corehq/apps/domain/templates/domain/admin/repeater_row.html
  corehq/apps/domain/urls.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/urls.py
  corehq/motech/openmrs/views.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/views/__init__.py
  corehq/motech/repeaters/views/repeaters.py
Labels: product/invisible

#19491 Resurrect hqwebapp/js/common
  corehq/apps/hqwebapp/static/hqwebapp/js/common.js
  corehq/apps/hqwebapp/static/hqwebapp/yaml/requirejs.yaml
Labels: product/invisible

#19487 update division reports/tests/sql_reports
  corehq/apps/reports/tests/sql_reports.py
Labels: product/invisible

#19466 process send_report in throttled queue for specific domains
  corehq/apps/reports/tasks.py
Labels: product/invisible

#19484 rewrite header
  scripts/externalize_js.sh
Labels: product/invisible

#19486 ejs/sms backend map
  corehq/apps/sms/static/sms/js/backend_map.js
  corehq/apps/sms/templates/sms/backend_map.html
Labels: product/invisible

#19365 Changed backup phone text
  corehq/apps/domain/templates/login_and_password/two_factor/core/phone_register.html
  corehq/apps/settings/forms.py
Labels: product/all-users-all-environments

#19480 ejs/sms add gateway
  corehq/apps/sms/static/sms/js/add_gateway.js
  corehq/apps/sms/static/sms/js/add_gateway_form_handler.ko.js
  corehq/apps/sms/templates/sms/add_gateway.html
Labels: product/invisible

#19490 Include shadow form names in bulk translations
  corehq/apps/app_manager/app_translations/app_translations.py
Labels: product/feature-flag

#19489 upgrade python-dateutil to py3 compatible version
  requirements/requirements.txt
Labels: product/invisible

#19475 Icds no arrow on kpi for difference below tenth of promile
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/templates/icds_reports/icds_app/kpi.directive.html
  custom/icds_reports/tests/reports/test_awc_infrastructure.py
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/tests/reports/test_maternal_child_data.py
  custom/icds_reports/utils.py
Labels: product/custom

#19494 Remove is_test flag in Schedule class
  corehq/messaging/scheduling/migrations/0014_remove_is_test.py
  corehq/messaging/scheduling/models/abstract.py
Labels: product/invisible

#19483 LS app report changes
  custom/icds_reports/ucr/reports/ls_above_6mo_nutrition.json
  custom/icds_reports/ucr/reports/ls_child_nutrition_status.json
  custom/icds_reports/ucr/reports/ls_handwashing.json
  custom/icds_reports/ucr/reports/ls_ifa_consumption.json
  custom/icds_reports/ucr/reports/ls_immun_complete.json
  custom/icds_reports/ucr/reports/ls_report_child_names.json
  custom/icds_reports/ucr/reports/ls_report_lbw_pre_term.json
  custom/icds_reports/ucr/reports/ls_thr_30_days.json
Labels: product/custom

#19496 Revert "Nevermind adding requirejs_main to pages that can inherit it"
  corehq/apps/accounting/templates/accounting/accounting_admins.html
  corehq/apps/data_interfaces/templates/data_interfaces/list_case_groups.html
  corehq/apps/reminders/templates/reminders/keyword_list.html
  corehq/apps/sms/templates/sms/gateway_list.html
  corehq/apps/sms/templates/sms/global_gateway_list.html
Labels: product/all-users-all-environments

#19492 Release export notice emails
  corehq/apps/export/templates/export/partial/export_download_progress.html
  corehq/toggles.py
Labels: product/all-users-all-environments

#19482 Add "Open in Web Apps" option to deploy modal
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/templates/app_manager/app_view_release_manager.html
  corehq/apps/app_manager/templates/app_manager/partials/releases_deploy_modal.html
  corehq/apps/app_manager/views/releases.py
  corehq/apps/hqwebapp/static/app_manager/less/deploy.less
Labels: product/all-users-all-environments

#19485 Move repeater html and js into repeaters app
  corehq/motech/repeaters/static/repeaters/js/add_form_repeater.js
  corehq/motech/repeaters/static/repeaters/js/repeat_record_report.js
  corehq/motech/repeaters/templates/repeaters/add_form_repeater.html
  corehq/motech/repeaters/templates/repeaters/partials/attempt_history.html
  corehq/motech/repeaters/templates/repeaters/partials/repeater_row.html
  corehq/motech/repeaters/templates/repeaters/repeat_record_report.html
  corehq/motech/repeaters/templates/repeaters/repeaters.html
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/repeaters.py
Labels: product/invisible

#19497 ejs/sms chat contacts
  corehq/apps/sms/static/sms/js/chat_contacts.js
  corehq/apps/sms/templates/sms/chat_contacts.html
Labels: product/invisible

#19500 Pv/force 2fa notest 269748
  corehq/apps/users/middleware.py
Labels: product/feature-flag

#19499 ejs/sms manage registration invitations
  corehq/apps/sms/static/sms/js/manage_registration_invitations.js
  corehq/apps/sms/templates/sms/manage_registration_invitations.html
Labels: product/invisible

#19498 ejs/sms languages
  corehq/apps/sms/static/sms/js/languages.js
  corehq/apps/sms/templates/sms/languages.html
Labels: product/invisible

#19503 update scripts/cloudant/README.md to use commcare-cloud django-manage
  scripts/cloudant/README.md
Labels: product/invisible

#19507 Fix 'My Timezone' page
  corehq/apps/hqwebapp/widgets.py
Labels: product/all-users-all-environments

#19502 Add icons for form edit and settings pages
  corehq/apps/app_manager/templates/app_manager/form_designer.html
  corehq/apps/app_manager/templates/app_manager/form_view.html
Labels: product/all-users-all-environments

#19510 More hqDefine
  corehq/apps/app_manager/static/app_manager/js/app_view_application.js
  corehq/apps/app_manager/static/app_manager/js/apps_base.js
  corehq/apps/domain/static/domain/js/commtrack_settings.js
  corehq/apps/domain/static/domain/js/info_base.js
  corehq/apps/domain/static/domain/js/my_project_settings.js
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/translations/static/translations/js/translations.js
  corehq/motech/repeaters/static/repeaters/js/add_form_repeater.js
Labels: product/invisible

#19488 last division updates
  corehq/apps/export/export.py
  corehq/apps/hqadmin/views.py
  corehq/apps/reports/commtrack/data_sources.py
  corehq/apps/reports/tests/test_scheduled_reports.py
  corehq/sql_db/tests/test_connections.py
  corehq/util/doc_processor/interface.py
  custom/fri/api.py
  custom/up_nrhm/sql_data.py
Labels: product/invisible

#19474 Measure MPTT ancestors/descendants query times
  corehq/apps/hqadmin/tests/test_clone_domain.py
  corehq/apps/locations/fixtures.py
  corehq/apps/locations/models.py
  corehq/apps/locations/queryutil.py
Labels: product/invisible

#19513 Begin to eslint the world
  corehq/apps/accounting/static/accounting/js/base_subscriptions_main.js
  corehq/apps/accounting/static/accounting/js/subscriptions_main.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_knockout_bindings.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_workflow.js
  corehq/apps/app_manager/static/app_manager/js/settings/commcare_settings.js
  corehq/apps/app_manager/static/app_manager/js/settings/linked_whitelist.js
  corehq/apps/app_manager/static/app_manager/js/summary/app_summary.ng.js
  corehq/apps/app_manager/static/app_manager/spec/releases_spec.js
  corehq/apps/builds/static/builds/js/edit-builds.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/formnav-all.js
  corehq/apps/crud/static/crud/js/crud.admin.js
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule.js
  corehq/apps/domain/static/domain/js/create_snapshot.js
  corehq/apps/domain/static/domain/js/info_basic.js
  corehq/apps/domain/static/domain/js/internal_calculations.js
  corehq/apps/fixtures/static/fixtures/js/lookup-manage.js
  corehq/apps/reminders/static/reminders/js/reminders.manage.js
  corehq/apps/reports/static/reports/js/async_maps.js
  corehq/apps/reports/static/reports/js/config.dataTables.bootstrap.js
  corehq/apps/reports/static/reports/js/maps.js
  corehq/apps/sms/static/sms/js/settings.ko.js
  corehq/apps/toggle_ui/static/toggle_ui/js/edit-flag.js
  corehq/apps/translations/static/translations/js/translations.js
  corehq/apps/userreports/static/userreports/js/configurable_report.js
  corehq/apps/userreports/static/userreports/js/expression_evaluator.js
Labels: product/invisible

#19515 Remove bootstrap timepicker
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap-timepicker.js
Labels: product/invisible

#19442 add person data dump script
  custom/enikshay/management/commands/base_data_dump.py
  custom/enikshay/management/commands/data_dumps_person_case.csv
  custom/enikshay/management/commands/data_dumps_person_case.py
Labels: product/custom

#19473 sorting fixture data items for download
  corehq/apps/fixtures/download.py
Labels: product/invisible

#19514 Remove jquery.color.js
  corehq/apps/reports/static/reports/js/jquery.color.js
Labels: product/invisible

#19516 Fix all indentation lint errors
  corehq/apps/accounting/static/accounting/js/base_subscriptions_main.js
  corehq/apps/app_manager/static/app_manager/js/app_manager_media.js
  corehq/apps/app_manager/static/app_manager/js/details/graph_config.js
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui_advanced.js
  corehq/apps/app_manager/static/app_manager/js/releases/app_diff.js
  corehq/apps/app_manager/static/app_manager/js/settings/app_logos.js
  corehq/apps/app_manager/static/app_manager/js/summary/app_summary.ng.js
  corehq/apps/app_manager/static/app_manager/js/supported_languages.js
  corehq/apps/app_manager/static/app_manager/js/visit_scheduler.js
  corehq/apps/app_manager/static/app_manager/spec/download_async_modal_spec.js
  corehq/apps/app_manager/static/app_manager/spec/utils/app_data_drilldown.utils.mo.js
  corehq/apps/app_manager/xpath_validator/nodejs/xpathConfig.js
  corehq/apps/builds/static/builds/js/edit-builds.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/hq.events.js
  corehq/apps/crud/static/crud/js/crud.admin.js
  corehq/apps/domain/static/domain/js/internal_settings.js
  corehq/apps/export/static/export/js/customize_export.js
  corehq/apps/fixtures/static/fixtures/js/lookup-manage.js
  corehq/apps/hqmedia/static/hqmedia/js/hqmedia.reference_controller.js
  corehq/apps/hqwebapp/static/hqwebapp/js/knockout_bindings.ko.js
  corehq/apps/locations/static/locations/js/location_tree.async.js
  corehq/apps/registration/static/registration/js/register_new_user.js
  corehq/apps/reports/static/reports/js/config.dataTables.bootstrap.js
  corehq/apps/reports/static/reports/js/export.manager.js
  corehq/apps/reports/static/reports/js/maps_utils.js
  corehq/apps/reports/static/reports/js/reports.config.js
  corehq/apps/translations/static/translations/js/translations.js
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/static/users/js/web_users.js
Labels: product/invisible

#19512 Always select all AWCs for combined format in issnip monthly register…
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
Labels: product/custom

#19519 Do a bit more linting
  corehq/apps/analytics/static/analytix/js/google.js
  corehq/apps/analytics/static/analytix/js/kissmetrix.js
  corehq/apps/app_manager/static/app_manager/js/case_config_utils.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui_advanced.js
  corehq/apps/app_manager/static/app_manager/js/xpathValidator.js
  corehq/apps/app_manager/static/app_manager/spec/app_data_drilldown.DrilldownToFormController.init.spec.mo.js
  corehq/apps/builds/static/builds/js/edit-builds.js
  corehq/apps/export/static/export/spec/DownloadExportFormController.init.spec.mo.js
  corehq/apps/export/static/export/spec/DownloadExportFormController.prepare.spec.mo.js
  corehq/apps/reports/static/reports/js/project_health_dashboard.js
Labels: product/invisible

#19495 Add "reminders migration in progress" flag
  corehq/apps/reminders/static/reminders/js/broadcasts_list.js
  corehq/apps/reminders/templates/reminders/broadcasts_list.html
  corehq/apps/reminders/templates/reminders/reminders_list.html
  corehq/apps/reminders/views.py
  corehq/apps/sms/views.py
  corehq/toggles.py
Labels: product/invisible

#19522 Pass correct arguments to analytics logger
  corehq/apps/analytics/static/analytix/js/google.js
  corehq/apps/analytics/static/analytix/js/hubspot.js
  corehq/apps/analytics/static/analytix/js/kissmetrix.js
Labels: product/invisible

#19374 266530: new Kissmetrics event of Saving a Question as a Case Property
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
Labels: product/invisible

#19412 externalize javascript in internal subscription management
  corehq/apps/domain/static/domain/js/internal_subscription_management.js
  corehq/apps/domain/templates/domain/internal_subscription_management.html
Labels: product/invisible

#19408 ejs current subscriptions
  corehq/apps/domain/static/domain/js/current_subscription.js
  corehq/apps/domain/templates/domain/current_subscription.html
  corehq/apps/domain/views.py
Labels: product/invisible

#19526 eslint users app
  .eslintrc.js
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/static/users/js/filtered_download.js
  corehq/apps/users/static/users/js/mobile_workers.ng.js
  corehq/apps/users/static/users/js/web_users.js
  corehq/apps/users/static/users/js/web_users_list.ng.js
Labels: product/invisible

#19527 [ICDS] fix problem with the same slug column in one datasource
  custom/icds_reports/sqldata.py
Labels: product/custom

#19529 recommend the typical build suggestions for macs
  README.md
Labels: product/invisible

#19528 Keep track of app_id as well as form_unique_id in visit scheduler form selector
  corehq/messaging/scheduling/async_handlers.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
Labels: product/invisible

#19537 Added support for distinct in ComparedQuerySet
  corehq/apps/locations/queryutil.py
Labels: product/invisible

#19538 show Report an Issue on 500 page selectively
  corehq/apps/hqwebapp/templates/500.html
Labels: product/custom

#19536 Tabular report, prevent filters from reseting after export
  custom/icds_reports/static/js/angular-services/issnip-status.service.js
  custom/icds_reports/static/js/angular-services/issnip.service.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
  custom/icds_reports/views.py
Labels: product/custom

#19539 Fix arrow in the KPI for % adhaar indicator
  custom/icds_reports/reports/demographics_data.py
  custom/icds_reports/tests/reports/test_demographics.py
Labels: product/custom

#19358 Partition UCR tables
  corehq/apps/userreports/models.py
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/tests/test_data_source_partitioning.py
  requirements/requirements.txt
  requirements/uninstall-requirements.txt
Labels: product/invisible

#19546 ejs/indentation
  scripts/externalize_js.sh
Labels: product/invisible

#19545 Exclude closed cases from SMS Case Indicators data source
  custom/abt/reports/data_sources/sms_case.json
Labels: product/custom

#19541 Removed unused indexes from person cases UCR.
  custom/icds_reports/ucr/data_sources/person_cases_v2.json
Labels: product/invisible

#19479 fixes error when software plan contains international characters
  corehq/apps/domain/views.py
Labels: product/invisible

#19544 Remove dead guided tour code
  corehq/apps/app_manager/static/app_manager/js/forms/form_designer.js
  corehq/apps/app_manager/templates/app_manager/form_designer.html
  corehq/apps/app_manager/templates/app_manager/form_view.html
Labels: product/invisible

#19549 Change "View Report" button text to "Save and View Report"
  corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
Labels: product/all-users-all-environments

#19521 ICDS Complementary Feeding Forms UCR
  custom/icds_reports/migrations/0034_aggregatecomplementaryfeedingforms.py
  custom/icds_reports/models.py
  custom/icds_reports/ucr/data_sources/dashboard/complementary_feeding_forms.json
  custom/icds_reports/ucr/expressions.py
  custom/icds_reports/ucr/tests/test_expressions.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/aggregation.py
  settings.py
Labels: Open for review: hold off on merge, product/custom

#19548 Loosen validation for custom user data properties
  corehq/apps/custom_data_fields/edit_model.py
Labels: product/all-users-all-environments

#19542 command for showing approximate doc distribution
  corehq/sql_db/management/commands/print_approximate_doc_distribution.py
Labels: product/invisible

#19551 python-modernize custom/ewsghana/ -w --future-unicode
  custom/ewsghana/__init__.py
  custom/ewsghana/alerts/__init__.py
  custom/ewsghana/alerts/alert.py
  custom/ewsghana/alerts/alerts.py
  custom/ewsghana/alerts/ongoing_non_reporting.py
  custom/ewsghana/alerts/ongoing_stockouts.py
  custom/ewsghana/alerts/urgent_alerts.py
  custom/ewsghana/filters.py
  custom/ewsghana/forms.py
  custom/ewsghana/handler.py
  custom/ewsghana/handlers/__init__.py
  custom/ewsghana/handlers/help.py
  custom/ewsghana/handlers/helpers/formatter.py
  custom/ewsghana/handlers/helpers/stock_and_receipt_parser.py
  custom/ewsghana/handlers/keyword.py
  custom/ewsghana/handlers/receipts.py
  custom/ewsghana/handlers/reminder.py
  custom/ewsghana/handlers/requisition.py
  custom/ewsghana/handlers/soh.py
  custom/ewsghana/handlers/undo.py
  custom/ewsghana/handlers/web_submission_handler.py
  custom/ewsghana/models.py
  custom/ewsghana/reminders/__init__.py
  custom/ewsghana/reminders/const.py
  custom/ewsghana/reminders/first_soh_reminder.py
  custom/ewsghana/reminders/rrirv_reminder.py
  custom/ewsghana/reminders/second_soh_reminder.py
  custom/ewsghana/reminders/stockout_reminder.py
  custom/ewsghana/reminders/third_soh_reminder.py
  custom/ewsghana/reminders/visit_website_reminder.py
  custom/ewsghana/reports/__init__.py
  custom/ewsghana/reports/email_reports.py
  custom/ewsghana/reports/maps.py
  custom/ewsghana/reports/specific_reports/dashboard_report.py
  custom/ewsghana/reports/specific_reports/reporting_rates.py
  custom/ewsghana/reports/specific_reports/stock_status_report.py
  custom/ewsghana/reports/stock_levels_report.py
  custom/ewsghana/reports/stock_transaction.py
  custom/ewsghana/resources/v0_1.py
  custom/ewsghana/tasks.py
  custom/ewsghana/tests/ews_test_reminders.py
  custom/ewsghana/tests/handlers/default.py
  custom/ewsghana/tests/handlers/formatter.py
  custom/ewsghana/tests/handlers/handler.py
  custom/ewsghana/tests/handlers/receipt.py
  custom/ewsghana/tests/handlers/reminder.py
  custom/ewsghana/tests/handlers/requisition_status.py
  custom/ewsghana/tests/handlers/stock_on_hand.py
  custom/ewsghana/tests/handlers/undo.py
  custom/ewsghana/tests/handlers/utils.py
  custom/ewsghana/tests/test_alerts.py
  custom/ewsghana/tests/test_delete_domain.py
  custom/ewsghana/tests/test_input_stock_view.py
  custom/ewsghana/tests/test_notifications.py
  custom/ewsghana/tests/test_reminders.py
  custom/ewsghana/tests/test_urgent_alerts.py
  custom/ewsghana/tests/test_utils.py
  custom/ewsghana/urls.py
  custom/ewsghana/utils.py
  custom/ewsghana/views.py
Labels: product/invisible

#19550 use int division in report test
  corehq/apps/reports/tests/sql_reports.py
Labels: product/invisible

#19552 lint accounting app
  corehq/apps/accounting/static/accounting/js/payment_method_handler.js
  corehq/apps/accounting/static/accounting/js/stripe_card_manager.js
  corehq/apps/accounting/static/accounting/js/widgets.js
Labels: product/invisible

#19556 use absolute import in migrations
  corehq/apps/linked_domain/migrations/0002_migrate_linked_apps.py
  corehq/apps/linked_domain/migrations/0003_auto_20180207_0857.py
  corehq/apps/linked_domain/migrations/0004_domainlinkhistory.py
  corehq/apps/linked_domain/migrations/0005_migrate_linked_app_toggle.py
  custom/icds_reports/migrations/0034_aggregatecomplementaryfeedingforms.py
Labels: product/invisible

#19557 override built-in zip
  corehq/apps/locations/tests/test_export.py
Labels: product/invisible

#19558 Fix file paths for mpr and APR reports.
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#19563 unicode
  corehq/apps/locations/tests/test_bulk_management.py
  corehq/apps/locations/tests/test_export.py
  corehq/apps/locations/util.py
Labels: product/invisible

#19564 Add ComparedQuerySet.select_related
  corehq/apps/locations/queryutil.py
Labels: product/invisible

#19559 ICDS aggregation fixes
  corehq/sql_db/routers.py
  custom/icds_reports/ucr/data_sources/dashboard/complementary_feeding_forms.json
  custom/icds_reports/utils/aggregation.py
Labels: product/custom

#19553 Create Enforce2FAMiddleware unit tests
  corehq/apps/users/tests/test_middleware.py
Labels: product/invisible

#19567 Add custom rule criteria for checking person case under 6 years old
  custom/icds/rules/custom_criteria.py
  custom/icds/rules/immunization.py
  custom/icds/rules/util.py
  custom/icds/tests/test_custom_rules.py
  custom/icds/tests/test_immunization.py
  settings.py
Labels: product/custom

#19569 enikshay/custom exports ui
  corehq/ex-submodules/soil/__init__.py
  custom/enikshay/forms.py
  custom/enikshay/management/commands/base_data_dump.py
  custom/enikshay/management/commands/data_dumps_person_case.py
  custom/enikshay/tasks.py
  custom/enikshay/templates/enikshay/data_dumps_task.html
  custom/enikshay/urls.py
  custom/enikshay/views.py
Labels: product/custom

#19572 simplify and fix UnicodeWriter
  corehq/ex-submodules/dimagi/utils/csv.py
Labels: product/invisible

#19547 Allow overriding daily auto case update rule limits by domain
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
  corehq/apps/domain/static/domain/js/internal_settings.js
  corehq/apps/domain/templates/domain/internal_settings.html
  corehq/apps/domain/views.py
Labels: product/invisible

#19571 Small improvements to rule progress tracking
  corehq/messaging/util.py
Labels: product/invisible

#19568 Don't wrap buttons on mobile workers page
  corehq/apps/users/templates/users/mobile_workers.html
Labels: product/all-users-all-environments

#19525 Support OpenMRS Person UUID as identifier
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/tests/test_repeaters.py
Labels: product/invisible

#19517 Add presumptive episodes dump
  custom/enikshay/management/commands/base_data_dump.py
  custom/enikshay/management/commands/data_dumps_presumptive_episodes.csv
  custom/enikshay/management/commands/data_dumps_presumptive_episodes.py
Labels: product/invisible

#19543 Mk update person data dump
  custom/enikshay/management/commands/base_data_dump.py
  custom/enikshay/management/commands/data_dumps_person_case.csv
  custom/enikshay/management/commands/data_dumps_person_case.py
Labels: product/custom
