Repository dimagi/commcare-hq, pull requests merged in 2018-05, with the labels that each got.

#20426 python-modernize . -w -f default -f libmodernize.fixes.fix_classic_di…
  custom/icds_reports/migrations/0043_merge_20180424_1426.py
  custom/icds_reports/migrations/0046_aggregatesqlprofile.py
  custom/yeksi_naa_reports/filters.py
Labels: product/invisible

#20425 Make explicit webapps link generators
  corehq/apps/cloudcare/utils.py
  custom/_legacy/pact/api.py
  custom/icds_reports/views.py
  custom/succeed/reports/all_patients.py
  custom/succeed/reports/patient_details.py
  custom/succeed/reports/patient_task_list.py
Labels: product/invisible

#20431 removing domain link validation from copy form
  corehq/apps/app_manager/forms.py
Labels: product/feature-flag

#20433 Fix ISSNIP monthly register
  custom/icds_reports/reports/issnip_monthly_register.py
  custom/icds_reports/tasks.py
  custom/icds_reports/templates/icds_reports/icds_app/pdf/issnip_monthly_register.html
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#20427 Fix agg script profiling
  custom/icds_reports/admin.py
  custom/icds_reports/utils/__init__.py
Labels: product/invisible

#20437 narrower buckets
  corehq/apps/couch_sql_migration/couchsqlmigration.py
Labels: product/invisible

#20421 default to sql
  corehq/apps/domain/models.py
  corehq/apps/users/models.py
Labels: product/invisible

#20439 add fifth column width
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
Labels: product/invisible

#20435 use io.open in tests
  corehq/apps/accounting/tests/test_subscription_permissions_changes.py
  corehq/apps/app_manager/tests/test_app_manager.py
  corehq/apps/app_manager/tests/test_build_errors.py
  corehq/apps/app_manager/tests/test_commcare_settings.py
  corehq/apps/app_manager/tests/test_xml_parsing.py
  corehq/apps/case_importer/tracking/tests/test_filestorage.py
  corehq/apps/cleanup/tests/test_fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/cleanup/tests/test_swap_duplicates.py
  corehq/apps/commtrack/tests/test_xml.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/data_interfaces/tests/tests.py
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/apps/hqwebapp/templatetags/tests/test_tag.py
  corehq/apps/hqwebapp/tests/test_compress_command.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/receiverwrapper/tests/test_auth.py
  corehq/apps/receiverwrapper/tests/test_submissions.py
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/apps/reports/tests/test_readable_formdata.py
  corehq/apps/sms/tests/util.py
  corehq/apps/userreports/tests/test_data_source_repeats.py
  corehq/apps/userreports/tests/utils.py
  corehq/blobs/tests/test_fsdb.py
  corehq/blobs/tests/test_init.py
  corehq/blobs/tests/test_migrate.py
  corehq/blobs/tests/test_mixin.py
  corehq/couchapps/tests/test_dbaccessors.py
  corehq/ex-submodules/casexml/apps/case/tests/test_exclusion.py
  corehq/ex-submodules/casexml/apps/case/tests/test_multi_case_submits.py
  corehq/ex-submodules/casexml/apps/case/tests/test_multimedia.py
  corehq/ex-submodules/casexml/apps/case/tests/test_out_of_order_processing.py
  corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py
  corehq/ex-submodules/casexml/apps/case/tests/util.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_extension_indexes.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py
  corehq/ex-submodules/couchforms/tests/test_edits.py
  corehq/form_processor/tests/test_form_dbaccessor.py
  corehq/tests/noseplugins/logfile.py
  corehq/tests/noseplugins/timing.py
  custom/_legacy/mvp_docs/tests/test_pillows.py
  custom/_legacy/pact/tests/dot_ordering.py
  custom/_legacy/pact/tests/dot_submission.py
  custom/bihar/tests/test_homevisits.py
  custom/champ/tests/__init__.py
  custom/champ/tests/utils.py
  custom/enikshay/tests/two_b_datamigration/test_logging.py
  custom/enikshay/ucr/tests/test_test_drtb.py
  custom/enikshay/ucr/tests/util.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/test_aggregation_script.py
  custom/intrahealth/tests/test_fluffs.py
  custom/intrahealth/tests/test_reports.py
  custom/uth/tests/uth_tests.py
  custom/world_vision/tests/utils.py
  custom/yeksi_naa_reports/tests/__init__.py
  custom/yeksi_naa_reports/tests/utils.py
  testapps/test_pillowtop/tests/test_settings.py
Labels: product/invisible

#20436 add missing migration, and use VisibleSubscriptionManager
  corehq/apps/accounting/migrations/0023_auto_20180501_1813.py
  corehq/apps/accounting/models.py
Labels: product/invisible

#20444 use csv342 in test
  custom/icds_reports/tests/test_aggregation_script.py
  requirements/requirements.txt
Labels: product/invisible

#20445 Total Cases includes shared cases
  corehq/apps/reports/standard/monitoring.py
Labels: product/all-users-all-environments

#20441 Kill unused report partials
  corehq/apps/reports/templates/reports/partials/case_plot.js
  corehq/apps/reports/templates/reports/partials/caselist_mapdetail.html
  corehq/apps/reports/templates/reports/partials/couch_report_partial.html
  corehq/apps/reports/templates/reports/partials/form_name.html
  corehq/apps/reports/templates/reports/partials/generic_filters.html
  corehq/apps/reports/templates/reports/partials/selector_form.html
Labels: product/invisible

#20438 Delete legacy/core.less
  corehq/apps/hqwebapp/static/hqwebapp/less/legacy/README.md
  corehq/apps/hqwebapp/static/hqwebapp/less/legacy/core.less
Labels: product/invisible

#20447 'Module' => 'Menu' in page titles
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/templates/app_manager/module_view.html
Labels: product/all-users-all-environments

#20380 Disallow hqImport in requirejs modules
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/hqwebapp/tests/test_requirejs.py
Labels: product/invisible

#20323 Upgrade celery to 3.1.25
  requirements/requirements.txt
Labels: product/invisible

#20448 Remove limitation warning for extended trial
  corehq/apps/domain/forms.py
Labels: product/admin

#20423 Data corrections: word breaking for long names
  corehq/apps/reports/static/reports/js/case_details.js
  corehq/apps/reports/templates/reports/reportdata/case_data.html
Labels: product/all-users-all-environments

#20450 update django
  requirements/requirements.txt
Labels: product/invisible

#20455 handle fixture error, extra column missing title
  corehq/apps/fixtures/tests/test_upload.py
  corehq/apps/fixtures/tests/test_upload/has_no_field_column_extra_rows.xlsx
  corehq/apps/fixtures/upload/validation.py
Labels: product/invisible

#20446 log count remaining to datadog
  corehq/apps/couch_sql_migration/progress.py
  corehq/apps/couch_sql_migration/tasks.py
Labels: product/invisible

#20454 correct ID ref
  corehq/apps/export/templates/export/partial/export_list_create_export_modal.html
Labels: product/invisible

#20456 Add 15 day option
  corehq/apps/domain/forms.py
Labels: product/all-users-all-environments

#20453 Updated insert for UCR to use bulk insert.
  corehq/apps/userreports/sql/adapter.py
Labels: product/invisible

#20451 clearing local override
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
Labels: product/invisible

#20336 move gathering persona fields to track_user_sign_in_on_hubspot
  corehq/apps/analytics/signals.py
  corehq/apps/analytics/tasks.py
  corehq/apps/registration/views.py
Labels: product/invisible

#20432 properly passing whether to include archived locations
  corehq/apps/locations/static/locations/js/location_tree.js
Labels: product/all-users-all-environments

#20458 parallelize state independent parts
  corehq/apps/couch_sql_migration/couchsqlmigration.py
Labels: product/invisible

#20440 Final form UCRs for dashboard
  custom/icds_reports/ucr/data_sources/dashboard/birth_preparedness_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/daily_feeding_forms.json
  custom/icds_reports/ucr/expressions.py
  custom/icds_reports/ucr/tests/data/birth_preparedness_form_anemia_v10326.xml
  custom/icds_reports/ucr/tests/data/birth_preparedness_form_v10326.xml
  custom/icds_reports/ucr/tests/data/daily_feeding_form_v10326.xml
  custom/icds_reports/ucr/tests/test_birth_preparedness_form_ucr.py
  custom/icds_reports/ucr/tests/test_daily_feeding_form_ucr.py
  settings.py
Labels: product/custom

#20462 fix bulk stripe payment workflow
  corehq/apps/accounting/payment_handlers.py
Labels: product/invisible

#20461 Show a change when updating case properties to blank values
  corehq/ex-submodules/casexml/apps/case/tests/test_get_case_property_changes.py
  corehq/ex-submodules/casexml/apps/case/util.py
Labels: product/invisible

#20415 Remove mailing_list_emails view
  corehq/apps/cachehq/cachemodels.py
  corehq/apps/users/_design/views/mailing_list_emails/map.js
Labels: product/invisible, reindex/migration

#20466 remove **kwargs from Subscription.change_plan
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/models.py
  corehq/apps/domain/forms.py
Labels: product/invisible

#20416 Bring back mass emails page
  corehq/apps/hqadmin/forms.py
  corehq/apps/hqadmin/tasks.py
  corehq/apps/hqadmin/templates/hqadmin/email/mass_email_base.html
  corehq/apps/hqadmin/templates/hqadmin/email/mass_email_base.txt
  corehq/apps/hqadmin/templates/hqadmin/mass_email.html
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#20463 add demo cta next to sign in button
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
Labels: product/prod-india-all-users

#19841 GDPR: Privacy policy updates
  corehq/apps/accounting/static/accounting/js/payment_method_handler.js
  corehq/apps/accounting/static/accounting/js/stripe_card_manager.js
  corehq/apps/accounting/templates/accounting/partials/new_stripe_card_template.html
  corehq/apps/accounting/templates/accounting/partials/stripe_card_ko_template.html
  corehq/apps/appstore/templates/cda.html
  corehq/apps/appstore/views.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/static/domain/js/confirm_plan.js
  corehq/apps/domain/templates/domain/activate_transfer_domain.html
  corehq/apps/domain/templates/domain/confirm_plan.html
  corehq/apps/domain/templates/login_and_password/partials/login_full.html
  corehq/apps/domain/views.py
  corehq/apps/hqwebapp/static/hqwebapp/js/main.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/appcues.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style-imports.less
  corehq/apps/hqwebapp/templates/eula.html
  corehq/apps/hqwebapp/templates/eula_v1.html
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/modal_eula.html
  corehq/apps/hqwebapp/templates/product_agreement.html
  corehq/apps/hqwebapp/views.py
  corehq/apps/registration/forms.py
  corehq/apps/registration/templates/registration/register_new_user.html
  corehq/apps/users/forms.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/extra_users_confirm_billing.js
  corehq/apps/users/templates/users/accept_invite.html
  corehq/apps/users/templates/users/extra_users_confirm_billing.html
  corehq/util/context_processors.py
  urls.py
Labels: Open for review: hold off on merge, product/all-users-all-environments

#20469 chunk malt saves
  corehq/apps/data_analytics/malt_generator.py
Labels: product/invisible

#20457 Case Search DSL
  corehq/apps/case_search/const.py
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/static/case_search/js/case_search.js
  corehq/apps/case_search/templates/case_search/case_search.html
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/views.py
  corehq/apps/cleanup/migrations/0012_add_es_index_to_checkpoint_ids.py
  corehq/apps/es/case_search.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/pillows/case_search.py
  corehq/pillows/mappings/case_search_mapping.json
  corehq/pillows/mappings/case_search_mapping.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
  testapps/test_pillowtop/tests/test_case_search_pillow.py
Labels: product/invisible, reindex/migration

#20467 handle new lines
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
Labels: product/invisible

#20477 remove ethiopian-date-converter from uninstall-requirements
  requirements/uninstall-requirements.txt
Labels: product/invisible

#20480 Revert "Remove mailing_list_emails view"
  corehq/apps/cachehq/cachemodels.py
  corehq/apps/users/_design/views/mailing_list_emails/map.js
Labels: product/invisible, product/prod-india-all-users

#20478 Revert "Case Search DSL"
  corehq/apps/case_search/const.py
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/static/case_search/js/case_search.js
  corehq/apps/case_search/templates/case_search/case_search.html
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/views.py
  corehq/apps/cleanup/migrations/0012_add_es_index_to_checkpoint_ids.py
  corehq/apps/es/case_search.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/pillows/case_search.py
  corehq/pillows/mappings/case_search_mapping.json
  corehq/pillows/mappings/case_search_mapping.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
  testapps/test_pillowtop/tests/test_case_search_pillow.py
Labels: Open for review: hold off on merge, product/invisible

#20472 add missing unicode_literals
  corehq/apps/couch_sql_migration/tasks.py
Labels: product/invisible

#20468 Update implementation invoice email
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/templates/accounting/email/invoice_contracted.html
  corehq/apps/accounting/templates/accounting/email/invoice_contracted.txt
Labels: product/invisible

#20482 Requirejs: fix billing account form missing dependency
  corehq/apps/accounting/static/accounting/js/billing_account_form.js
Labels: product/feature-flag

#20486 Revert "Revert "Case Search DSL""
  corehq/apps/case_search/const.py
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/static/case_search/js/case_search.js
  corehq/apps/case_search/templates/case_search/case_search.html
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/views.py
  corehq/apps/cleanup/migrations/0012_add_es_index_to_checkpoint_ids.py
  corehq/apps/es/case_search.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/pillows/case_search.py
  corehq/pillows/mappings/case_search_mapping.json
  corehq/pillows/mappings/case_search_mapping.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
  testapps/test_pillowtop/tests/test_case_search_pillow.py
Labels: product/invisible

#20476 Yeksi naa reports merge into intrahealth
  custom/intrahealth/filters.py
  custom/intrahealth/reports/__init__.py
  custom/intrahealth/reports/dashboard_1.py
  custom/intrahealth/reports/dashboard_2.py
  custom/intrahealth/reports/dashboard_3.py
  custom/intrahealth/sqldata.py
  custom/intrahealth/templates/yeksi_naa/location_filter.html
  custom/intrahealth/templates/yeksi_naa/months_datespan.html
  custom/intrahealth/templates/yeksi_naa/multi_report.html
  custom/intrahealth/templates/yeksi_naa/partials/report_table.html
  custom/intrahealth/templates/yeksi_naa/partials/tabular_cell.html
  custom/intrahealth/templates/yeksi_naa/program_filter.html
  custom/intrahealth/tests/__init__.py
  custom/intrahealth/tests/fixtures/yeksi_naa_reports_logisticien.csv
  custom/intrahealth/tests/fixtures/yeksi_naa_reports_visite_de_l_operateur.csv
  custom/intrahealth/tests/fixtures/yeksi_naa_reports_visite_de_l_operateur_per_product.csv
  custom/intrahealth/tests/fixtures/yeksi_naa_reports_visite_de_l_operateur_per_program.csv
  custom/intrahealth/tests/reports/test_dashboard_1.py
  custom/intrahealth/tests/reports/test_dashboard_2.py
  custom/intrahealth/tests/reports/test_dashboard_3.py
  custom/intrahealth/tests/reports/util.py
  custom/intrahealth/tests/test_logisticien_data_source.py
  custom/intrahealth/tests/test_visite_de_l_operateur_data_source.py
  custom/intrahealth/tests/test_visite_de_l_operateur_per_product_data_source.py
  custom/intrahealth/tests/utils.py
  custom/intrahealth/ucr/__init__.py
  custom/intrahealth/ucr/data_sources/__init__.py
  custom/intrahealth/ucr/data_sources/visite_de_l_operateur.json
  custom/intrahealth/ucr/data_sources/visite_de_l_operateur_per_product.json
  custom/intrahealth/ucr/data_sources/visite_de_l_operateur_per_program.json
  custom/intrahealth/ucr/data_sources/yeksi_naa_reports_logisticien.json
  custom/intrahealth/utils.py
  custom/yeksi_naa_reports/filters.py
  custom/yeksi_naa_reports/reports/__init__.py
  custom/yeksi_naa_reports/sqldata.py
  custom/yeksi_naa_reports/tests/__init__.py
  custom/yeksi_naa_reports/tests/reports/__init__.py
  custom/yeksi_naa_reports/ucr/data_sources/__init__.py
  custom/yeksi_naa_reports/utils.py
  settings.py
Labels: product/custom

#20449 Make sure the user has access to the app
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_test.js
  corehq/apps/hqwebapp/static/hqwebapp/js/initial_page_data.js
Labels: product/all-users-all-environments

#20465 Fix ICDS infrastructure form UCR.
  custom/icds_reports/ucr/data_sources/infrastructure_form.json
  custom/icds_reports/ucr/tests/data/infrastructure_details_v10326.xml
  custom/icds_reports/ucr/tests/data/infrastructure_details_v10475.xml
  custom/icds_reports/ucr/tests/test_base_form_ucr.py
  custom/icds_reports/ucr/tests/test_infra_form_ucr.py
Labels: product/custom

#20493 Remove inline js from help_bubble.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/help_bubble.html
Labels: product/invisible

#20460 Support defining UCR with YAML
  corehq/apps/userreports/models.py
  corehq/apps/userreports/tests/data/static_data_sources/sample_static_data_source.yaml
  corehq/apps/userreports/tests/data/static_reports/static_report_config.yaml
  corehq/apps/userreports/tests/test_static_data_sources.py
  corehq/apps/userreports/tests/test_static_reports.py
Labels: product/invisible

#20496 Cleanup UCR indexes for ICDS
  custom/icds_reports/ucr/data_sources/ccs_record_cases_monthly_tableau2.json
  custom/icds_reports/ucr/data_sources/child_cases_monthly_v2.json
  custom/icds_reports/ucr/data_sources/child_health_cases.json
  custom/icds_reports/ucr/data_sources/child_health_cases_monthly_tableau2.json
  custom/icds_reports/ucr/data_sources/person_cases.json
  custom/icds_reports/ucr/data_sources/person_cases_v2.json
Labels: product/custom

#20399 do partioning for large UCRs
  custom/icds_reports/ucr/data_sources/gm_forms.json
  custom/icds_reports/ucr/data_sources/household_cases.json
  custom/icds_reports/ucr/data_sources/person_cases_v2.json
  custom/icds_reports/ucr/data_sources/usage_forms.json
Labels: product/invisible

#20485 Restyle exports table
  corehq/apps/app_manager/templates/app_manager/partials/case_list_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/mobile_report_configs.html
  corehq/apps/export/static/export/js/models.js
  corehq/apps/export/templates/export/partial/new_customize_export_templates.html
  corehq/apps/hqwebapp/static/app_manager/less/navigation.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/tables.less
  corehq/apps/hqwebapp/templates/hqwebapp/partials/key_value_mapping.html
  corehq/apps/userreports/templates/userreports/partials/property_list_configuration.html
Labels: product/all-users-all-environments

#20497 Don't check accessible apps in app preview
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
Labels: product/all-users-all-environments

#20481 Use full screen modal for graph configuration
  corehq/apps/app_manager/templates/app_manager/partials/graph_configuration_modal.html
Labels: product/feature-flag

#20500 Add `preview` to getDetails params
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
Labels: product/invisible

#20491 Multi-event reminders in the new reminders framework
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0017_update_ui_type.py
  corehq/messaging/scheduling/migrations/0018_minutes_to_wait.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/models/alert_schedule.py
  corehq/messaging/scheduling/models/timed_schedule.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
  corehq/messaging/scheduling/templates/scheduling/conditional_alert.html
  corehq/messaging/scheduling/templates/scheduling/create_schedule.html
  corehq/messaging/scheduling/templates/scheduling/partial/custom_event_templates.html
  corehq/messaging/scheduling/templates/scheduling/partial/schedule_form.html
  corehq/messaging/scheduling/templates/scheduling/partial/time_picker.html
  corehq/messaging/scheduling/tests/test_schedules.py
  corehq/messaging/scheduling/views.py
Labels: product/feature-flag

#20489 Catch bad worksheet
  corehq/apps/fixtures/templates/fixtures/manage_tables.html
  corehq/apps/fixtures/views.py
  corehq/util/workbook_json/excel.py
Labels: product/invisible

#19853 use quickcache session_function
  corehq/util/global_request/middleware.py
  corehq/util/quickcache.py
  requirements/requirements.txt
Labels: product/invisible

#20507 Add script to find old reminder framework usage
  corehq/apps/reminders/management/commands/find_reminder_usage.py
Labels: product/invisible

#20506 Add datadog counter for partial es results
  corehq/apps/api/es.py
  corehq/elastic.py
Labels: product/invisible

#20514 Allow new reminders migrator to see reminder configurations for community projects
  corehq/apps/reminders/views.py
  corehq/apps/sms/views.py
  corehq/messaging/decorators.py
  corehq/messaging/scheduling/views.py
Labels: product/feature-flag

#20498 update and clarify which invoices are counted towards the threshold f…
  corehq/apps/accounting/tasks.py
Labels: product/invisible

#20501 Update case_search index to use multifields
  corehq/apps/case_search/const.py
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/cleanup/migrations/0012_add_es_index_to_checkpoint_ids.py
  corehq/apps/es/case_search.py
  corehq/pillows/case_search.py
  corehq/pillows/mappings/case_search_mapping.json
  corehq/pillows/mappings/case_search_mapping.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: product/invisible, reindex/migration

#20512 Search for case property existence
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/static/case_search/js/case_search.js
  corehq/apps/case_search/templates/case_search/case_search.html
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/views.py
  corehq/apps/es/case_search.py
Labels: product/invisible

#20520 First iteration of script to migrate to the new reminders framework
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
Labels: product/invisible

#20521 update CCHQ setup docs
  README.md
Labels: product/invisible

#20519 Kill a few old report templates
  corehq/apps/reports/templates/reports/partials/formentry_plot.js
  corehq/apps/reports/templates/reports/text/couch_report_raw.txt
Labels: product/invisible

#20517 using more generator query for malt
  corehq/apps/data_analytics/malt_generator.py
  corehq/apps/users/dbaccessors/all_commcare_users.py
Labels: product/invisible

#20525 fix show archived locations
  corehq/apps/locations/static/locations/js/location_tree.js
Labels: product/all-users-all-environments

#20488 concurrent form processing
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  manage.py
Labels: product/invisible

#20530 fix tooltip after nvd3 update
  custom/icds_reports/static/icds_reports/js/spec/awc-reports.directive.spec.js
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
Labels: product/custom

#20503 ICDS MPR/ASR - the same behavior for location filter in ASR report as we have in MPR report
  custom/icds_reports/filters.py
Labels: product/custom

#20499 Create emailed_to_list ArrayField
  corehq/apps/accounting/migrations/0025_auto_20180508_1952.py
  corehq/apps/accounting/migrations/0026_auto_20180508_1956.py
  corehq/apps/accounting/migrations/0027_auto_20180509_1857.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/views.py
  corehq/apps/api/accounting.py
Labels: Open for review: hold off on merge, product/invisible

#20531 add missing kwargs passed to Subscription.change_plan
  corehq/apps/accounting/models.py
Labels: product/invisible

#20505 Mk fix sheet name
  corehq/apps/app_manager/app_translations/app_translations.py
  corehq/apps/app_manager/app_translations/const.py
  corehq/apps/app_manager/tests/test_bulk_app_translation.py
Labels: product/all-users-all-environments

#20533 Reminders Migration Script - 2
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/apps/reminders/tasks.py
  corehq/messaging/management/commands/queue_schedule_instances.py
  corehq/messaging/tasks.py
  corehq/toggles.py
Labels: product/invisible

#20532 Create case fixtures for local testing
  corehq/ex-submodules/casexml/apps/case/management/__init__.py
  corehq/ex-submodules/casexml/apps/case/management/commands/__init__.py
  corehq/ex-submodules/casexml/apps/case/management/commands/create_case_fixtures.py
  requirements/requirements.txt
Labels: product/invisible

#20536 fix tests
  corehq/apps/app_manager/tests/test_bulk_app_translation.py
Labels: product/invisible

#20537 Simplify case property missing queries
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/es/case_search.py
Labels: product/invisible

#20538 fix yAxis and tooltip for ic AWC daily Status chart view
  custom/icds_reports/static/js/directives/awc-daily-status/awc-daily-status.directive.js
Labels: product/custom

#20484 ICDS Dashboard - (AGE) updates in indicators
  custom/icds_reports/messages.py
  custom/icds_reports/migrations/0040_add_days_ration_column.py
  custom/icds_reports/migrations/0041_added_num_anc_visits_to_agg_awc_montlhy_view.py
  custom/icds_reports/migrations/0047_added_new_wasting_and_stunting_columns_to_views.py
  custom/icds_reports/migrations/sql_templates/create_child_health_monthly_view.sql
  custom/icds_reports/migrations/sql_templates/create_datasource_views.sql
  custom/icds_reports/migrations/sql_templates/create_functions.sql
  custom/icds_reports/migrations/sql_templates/database_functions/child_health_monthly.sql
  custom/icds_reports/models.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/reports/issnip_monthly_register.py
  custom/icds_reports/reports/maternal_child.py
  custom/icds_reports/reports/prevalence_of_severe.py
  custom/icds_reports/reports/prevalence_of_stunting.py
  custom/icds_reports/sqldata.py
  custom/icds_reports/static/icds_reports/js/spec/additional-filter.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/prevalence-of-severe-report.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/prevalence-of-stunting-report.directive.spec.js
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/directives/additional-filter/additional-filter.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-severe-report/prevalence-of-severe-report.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-stunting-report/prevalence-of-stunting-report.directive.js
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/fixtures/ucr_table_name_mapping.csv
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/tests/reports/test_maternal_child_data.py
  custom/icds_reports/tests/reports/test_prevalence_of_severe.py
  custom/icds_reports/tests/reports/test_prevalence_of_stunting.py
  custom/icds_reports/tests/test_fact_sheet_report.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/views.py
Labels: product/custom

#20518 Show case property changes for cases with rebuilds
  corehq/ex-submodules/casexml/apps/case/tests/test_get_case_property_changes.py
  corehq/ex-submodules/casexml/apps/case/util.py
Labels: product/invisible

#20534 Liberate "Last Downloaded" for exports
  corehq/apps/export/templates/export/partial/export_list_controller.html
Labels: product/all-users-all-environments

#20546 Reminders Migration Script - 3
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
Labels: product/invisible

#20543 Up nrhm asha sangini custom report
  custom/up_nrhm/data_sources/asha_facilitators.json
  custom/up_nrhm/sql_data.py
  custom/up_nrhm/tests/__init__.py
  custom/up_nrhm/tests/fixtures/asha_facilitators.csv
  custom/up_nrhm/tests/fixtures/location_hierarchy.csv
  custom/up_nrhm/tests/reports/__init__.py
  custom/up_nrhm/tests/reports/test_asha_reports.py
  custom/up_nrhm/tests/utils.py
Labels: product/custom

#20547 use io.open in make_supervisor_conf
  corehq/apps/hqadmin/management/commands/make_supervisor_conf.py
Labels: product/invisible

#20513 Persona Field fixes
  corehq/apps/analytics/README.md
  corehq/apps/analytics/signals.py
  corehq/apps/analytics/tasks.py
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/registration/views.py
Labels: product/invisible, product/prod-india-all-users

#20548 remove styleguide_update
  corehq/apps/styleguide/management/commands/styleguide_update.py
Labels: product/invisible

#20552 remove mvp_archive_forms
  custom/_legacy/mvp/management/commands/mvp_archive_forms.py
Labels: product/invisible

#20315 identify standby and calculate delay util
  corehq/apps/userreports/sql/connection.py
  corehq/sql_db/connections.py
  corehq/sql_db/routers.py
  corehq/sql_db/tests/test_connections.py
  corehq/sql_db/util.py
  settings.py
Labels: Open for review: hold off on merge, product/invisible

#20452 Allow custom SQL in UCR
  corehq/apps/userreports/custom/__init__.py
  corehq/apps/userreports/custom/data_source.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/data_source.py
  custom/icds_reports/reports/ucr.py
  custom/icds_reports/ucr/reports/custom_sql_mpr_2a_person_cases.json
  settings.py
Labels: product/invisible

#20529 datadog metrics for fixtures
  corehq/apps/locations/fixtures.py
  corehq/ex-submodules/casexml/apps/phone/data_providers/standard.py
  corehq/ex-submodules/casexml/apps/phone/fixtures.py
  corehq/ex-submodules/casexml/apps/phone/restore.py
Labels: product/invisible

#19973 Data Corrections: Forms
  corehq/apps/app_manager/xform.py
  corehq/apps/cloudcare/templates/formplayer-common/base.html
  corehq/apps/hqadmin/templates/hqadmin/project_map.html
  corehq/apps/hqwebapp/static/hqwebapp/js/assert_properties.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/modals.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/readable_forms.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style-imports.less
  corehq/apps/hqwebapp/static/hqwebapp/spec/assert_properties_spec.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/base_mobile.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/core_libraries.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/less.html
  corehq/apps/hqwebapp/templates/hqwebapp/spec/mocha.html
  corehq/apps/hqwebapp/templatetags/tests/rendered/javascript_libraries_hq.html
  corehq/apps/mocha/templates/mocha/base.html
  corehq/apps/reports/formdetails/readable.py
  corehq/apps/reports/static/reports/js/case_details.js
  corehq/apps/reports/static/reports/js/data_corrections.js
  corehq/apps/reports/static/reports/js/form_data_main.js
  corehq/apps/reports/static/reports/js/single_form.js
  corehq/apps/reports/static/reports/spec/data_corrections_spec.js
  corehq/apps/reports/templates/reports/form/edit_submission.html
  corehq/apps/reports/templates/reports/form/partials/single_form.html
  corehq/apps/reports/templates/reports/form/partials/single_form_label.html
  corehq/apps/reports/templates/reports/partials/data_corrections_modal.html
  corehq/apps/reports/templates/reports/partials/data_corrections_trigger.html
  corehq/apps/reports/templates/reports/reportdata/case_data.html
  corehq/apps/reports/templates/reports/reportdata/form_data.html
  corehq/apps/reports/templates/reports/spec/mocha.html
  corehq/apps/reports/templatetags/xform_tags.py
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
  corehq/apps/styleguide/templates/styleguide/base.html
  corehq/form_processor/backends/couch/processor.py
  corehq/form_processor/backends/sql/processor.py
  corehq/form_processor/interfaces/processor.py
  corehq/form_processor/tests/test_basics.py
  corehq/form_processor/tests/test_form_dbaccessor.py
  corehq/form_processor/utils/xform.py
  corehq/toggles.py
Labels: QA Passed, product/all-users-all-environments

#20524 Allow hiding maintenance alert
  corehq/apps/hqwebapp/static/hqwebapp/js/main.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/alerts.less
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
Labels: product/all-users-all-environments

#20555 Don't 500 when no language name is found
  corehq/messaging/scheduling/forms.py
Labels: product/invisible

#20549 use io.open in more places
  app_builder_live_test/compare_perf_stats.py
  corehq/apps/accounting/management/commands/find_inactive_custom_modules.py
  corehq/apps/cleanup/management/commands/couch_integrity.py
  corehq/apps/cleanup/management/commands/fix_xforms_with_undefined_xmlns.py
  corehq/apps/cleanup/management/commands/get_doc_info.py
  corehq/apps/cleanup/management/commands/list_dynamic_reports.py
  corehq/apps/cleanup/management/commands/rebuild_cases.py
  corehq/apps/cleanup/management/commands/swap_duplicate_xforms.py
  corehq/apps/cleanup/management/commands/undelete_docs.py
  corehq/apps/cleanup/tasks.py
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
  corehq/apps/data_analytics/management/commands/add_to_malt_table.py
  corehq/apps/data_analytics/management/commands/export_form_impact_data.py
  corehq/apps/domain/utils.py
  corehq/apps/dropbox/utils.py
  corehq/apps/hqadmin/management/commands/delete_related_cases.py
  corehq/apps/hqadmin/management/commands/recent_changes.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/locations/util.py
  corehq/apps/settings/views.py
  corehq/apps/smsbillables/management/commands/bootstrap_tropo_gateway.py
  corehq/apps/userreports/management/commands/load_spec.py
  corehq/apps/userreports/management/commands/resave_couch_forms_and_cases.py
  corehq/blobs/management/commands/run_blob_migration.py
  corehq/blobs/migrate.py
  corehq/ex-submodules/auditcare/management/commands/generate_request_report.py
  corehq/ex-submodules/couchforms/management/commands/purge_forms_and_cases.py
  corehq/form_processor/management/commands/make_sharded_sql_function.py
  corehq/motech/repeaters/management/commands/delete_duplicate_cancelled_records.py
  corehq/sql_db/operations.py
  scripts/checkyaml.py
Labels: product/invisible

#20550 remove once-off fix_bad_reassigned_owner_ids
  corehq/apps/data_interfaces/management/commands/fix_bad_reassigned_owner_ids.py
Labels: product/invisible

#20551 remove once-off management commands
  corehq/apps/domain/management/commands/find_secure_submission_image_domains.py
  corehq/apps/domain/management/commands/migrate_domain_bu.py
Labels: product/invisible

#20405 Change aggregation script for PNC forms
  custom/icds_reports/docs/current_state_aggregation.png
  custom/icds_reports/docs/current_state_aggregation.txt
  custom/icds_reports/migrations/sql_templates/create_functions.sql
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/fixtures/pnc_forms.csv
  custom/icds_reports/utils/aggregation.py
Labels: product/custom

#20556 remove bihar_cleanup_case
  custom/bihar/management/commands/bihar_cleanup_case.py
Labels: product/invisible

#20560 Let developers see superuser builds
  corehq/apps/app_manager/views/apps.py
Labels: product/feature-flag

#20563 Change button color in Get Demo CTA
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
Labels: product/prod-india-all-users

#20561 Add support for SMS Surveys to new reminders framework
  corehq/apps/sms/models.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/models/content.py
Labels: product/feature-flag

#20564 Fix time icon in readable forms
  corehq/apps/app_manager/static/app_manager/js/summary/app_summary.ng.js
  corehq/apps/app_manager/xform.py
  corehq/apps/reports/formdetails/readable.py
Labels: product/all-users-all-environments

#20573 Revert "identify standby and calculate delay util"
  corehq/apps/userreports/sql/connection.py
  corehq/sql_db/connections.py
  corehq/sql_db/routers.py
  corehq/sql_db/tests/test_connections.py
  corehq/sql_db/util.py
  settings.py
Labels: product/invisible

#20571 move element to be within the scope of ko
  corehq/apps/reports/templates/reports/filters/location_async.html
Labels: product/invisible

#20568 Data corrections: search by selected property
  corehq/apps/reports/static/reports/js/data_corrections.js
  corehq/apps/reports/static/reports/spec/data_corrections_spec.js
Labels: product/feature-flag

#20583 Update link to vault docs
  corehq/apps/analytics/README.md
Labels: product/invisible

#20495 Remove usage forms v2 UCR
  custom/icds_reports/ucr/data_sources/dashboard/usage_forms_v2.json
  settings.py
Labels: product/custom

#20569 Data corrections: display labels by default
  corehq/apps/reports/static/reports/spec/data_corrections_spec.js
  corehq/apps/reports/templates/reports/partials/data_corrections_modal.html
Labels: product/feature-flag

#20578 use io.open in corehq/motech/
  corehq/motech/repeaters/management/commands/generate_repeater_report.py
  corehq/motech/repeaters/management/commands/update_cancelled_records.py
Labels: product/invisible

#20579 use io.open in find_datasource_mismatches
  corehq/apps/userreports/management/commands/find_datasource_mismatches.py
Labels: product/invisible

#20584 Don't process inbound sms when migrations are in progress
  corehq/apps/sms/api.py
  corehq/apps/sms/tasks.py
Labels: product/invisible

#20582 Add some checks around ScheduleInstance reprocessing
  corehq/messaging/management/commands/queue_schedule_instances.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/scheduling/tests/test_schedules.py
Labels: product/feature-flag

#20580 use io.open in corehq/blobs/management/commands/
  corehq/blobs/management/commands/blob_storage_report.py
  corehq/blobs/management/commands/check_blob_logs.py
Labels: product/invisible

#20590 Enable Supervisory data source on vectorlink-ethiopia
  custom/abt/reports/data_sources/sms_case.json
  custom/abt/reports/data_sources/supervisory.json
Labels: product/custom

#20567 Show option value in readable forms when option not found
  corehq/apps/reports/formdetails/readable.py
  corehq/apps/reports/templates/reports/form/partials/single_form_tree.html
Labels: product/feature-flag

#20586 Update SQLAlchemy to 1.2.7
  requirements/requirements.txt
Labels: product/invisible

#20589 Turn off appcues changes
  corehq/apps/app_manager/templates/app_manager/managed_app.html
Labels: Open for review: hold off on merge, product/ab-test, product/prod-india-all-users

#20592 Use location CTE queries everywhere
  settings.py
Labels: product/invisible

#20572 500 to error message
  corehq/util/workbook_reading/adapters/xls.py
Labels: product/invisible

#20588 Upgrade fontawesome
  bower.json
  corehq/apps/hqwebapp/static/hqstyle/css/font/FontAwesome.otf
  corehq/apps/hqwebapp/static/hqstyle/css/font/fontawesome-webfont.eot
  corehq/apps/hqwebapp/static/hqstyle/css/font/fontawesome-webfont.svg
  corehq/apps/hqwebapp/static/hqstyle/css/font/fontawesome-webfont.ttf
  corehq/apps/hqwebapp/static/hqstyle/css/font/fontawesome-webfont.woff
  corehq/apps/reports/templates/reports/partials/data_corrections_trigger.html
Labels: product/invisible

#20600 Restrict certain edit options for custom immediate schedules
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
  corehq/messaging/scheduling/templates/scheduling/partial/custom_event_templates.html
Labels: product/feature-flag

#20602 Stop datatables from making double requests on every load
  corehq/apps/reports/static/reports/js/config.dataTables.bootstrap.js
Labels: product/invisible

#20591 Open markdown links in new tabs
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
Labels: product/all-users-all-environments

#20603 Add command to export fri message bank data
  custom/fri/management/__init__.py
  custom/fri/management/commands/__init__.py
  custom/fri/management/commands/dump_fri_message_bank.py
Labels: product/invisible

#20595 Clean up airs duplicate table IDs
  custom/abt/reports/data_sources/sms.json
  custom/abt/reports/data_sources/sms_case.json
  settings.py
Labels: product/custom

#20565 Use is_distinct_from instead of !=
  custom/icds_reports/reports/ucr.py
Labels: product/custom

#20605 Fix use of io.open in LogFilePlugin
  corehq/tests/noseplugins/logfile.py
Labels: product/invisible

#20593 use io.open in more places
  corehq/apps/analytics/tasks.py
  corehq/apps/app_manager/commcare_settings.py
  corehq/apps/app_manager/management/commands/applications_with_add_ons.py
  corehq/apps/app_manager/management/commands/build_apps.py
  corehq/apps/app_manager/management/commands/download_app_forms.py
  corehq/apps/app_manager/management/commands/upload_app_forms.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/callcenter/data_source.py
  corehq/apps/case_importer/management/commands/import_cases.py
  corehq/apps/case_importer/management/commands/update_case_property.py
  corehq/apps/case_importer/tracking/views.py
  corehq/apps/cleanup/management/commands/fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/cleanup/management/commands/pillow_reset.py
  corehq/apps/cleanup/management/commands/undo_uuid_clash.py
  corehq/apps/domainsync/management/commands/copy_doc.py
  corehq/apps/export/management/commands/upload_saved_export.py
  corehq/apps/export/multiprocess.py
  corehq/apps/hqadmin/management/commands/check_case_index_ids.py
  corehq/apps/hqmedia/models.py
  corehq/apps/hqmedia/tasks.py
  corehq/apps/reminders/management/commands/find_reminder_usage.py
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/apps/userreports/models.py
  corehq/blobs/fsdb.py
  corehq/ex-submodules/casexml/apps/phone/management/commands/sync_log_debugger.py
  corehq/ex-submodules/casexml/apps/phone/management/commands/sync_log_profile.py
  corehq/ex-submodules/couchexport/files.py
  corehq/ex-submodules/dimagi/utils/post.py
  corehq/ex-submodules/phonelog/management/commands/delete_couch_devicelogs.py
  corehq/ex-submodules/pillowtop/management/commands/ptop_run_docs.py
  corehq/form_processor/management/commands/check_forms_have_xml.py
  corehq/pillows/mappings/utils.py
  corehq/warehouse/etl.py
  custom/abt/reports/expressions.py
  custom/care_pathways/utils.py
  custom/hki/management/commands/hki_case_migration.py
  custom/openclinica/management/commands/odm_to_app.py
  scripts/yaml_static_strings.py
Labels: product/invisible

#20594 Better sql session/transaction management in UCR
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/sql/data_source.py
Labels: product/invisible

#20575 use session context
  corehq/apps/reports/sqlreport.py
Labels: product/invisible

#20615 add app tag to restore metrics
  corehq/ex-submodules/casexml/apps/phone/restore.py
Labels: product/invisible

#20601 Yeksi Naa Reports | Change UCR Top level name to include french chara…
  custom/intrahealth/tests/__init__.py
  custom/intrahealth/ucr/data_sources/visite_de_l_operateur.json
  custom/intrahealth/ucr/data_sources/visite_de_l_operateur_per_product.json
  custom/intrahealth/ucr/data_sources/yeksi_naa_reports_logisticien.json
  custom/up_nrhm/tests/reports/test_asha_reports.py
Labels: product/custom

#20540 Email accounts@ if dimagi contact is blank
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_invoicing.py
Labels: product/invisible

#20613 Quick, dirty enterprise metrics for CRS
  corehq/apps/accounting/management/commands/report_on_enterprise_domain.py
Labels: product/invisible

#20614 add encoding='utf-8' to more files
  corehq/apps/analytics/tasks.py
  corehq/apps/app_manager/commcare_settings.py
  corehq/apps/app_manager/management/commands/applications_with_add_ons.py
  corehq/apps/app_manager/management/commands/build_apps.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/callcenter/data_source.py
  corehq/apps/case_importer/management/commands/import_cases.py
  corehq/apps/case_importer/management/commands/update_case_property.py
  corehq/apps/cleanup/management/commands/fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/cleanup/management/commands/pillow_reset.py
  corehq/apps/cleanup/management/commands/undo_uuid_clash.py
  corehq/apps/domainsync/management/commands/copy_doc.py
  corehq/apps/hqadmin/management/commands/check_case_index_ids.py
  corehq/apps/hqmedia/tasks.py
  corehq/apps/reminders/management/commands/find_reminder_usage.py
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/apps/userreports/models.py
  corehq/ex-submodules/casexml/apps/phone/management/commands/sync_log_debugger.py
  corehq/ex-submodules/phonelog/management/commands/delete_couch_devicelogs.py
  corehq/ex-submodules/pillowtop/management/commands/ptop_run_docs.py
  corehq/form_processor/management/commands/check_forms_have_xml.py
  corehq/pillows/mappings/utils.py
  custom/abt/reports/expressions.py
  custom/care_pathways/utils.py
  custom/hki/management/commands/hki_case_migration.py
  custom/openclinica/management/commands/odm_to_app.py
  scripts/yaml_static_strings.py
Labels: product/invisible

#20611 specify utf-8 encoding for existing usages of io.open
  app_builder_live_test/compare_perf_stats.py
  corehq/apps/app_manager/tests/test_app_manager.py
  corehq/apps/app_manager/tests/test_build_errors.py
  corehq/apps/app_manager/tests/test_commcare_settings.py
  corehq/apps/case_importer/tracking/tests/test_filestorage.py
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/data_analytics/management/commands/add_to_malt_table.py
  corehq/apps/data_interfaces/tests/tests.py
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/apps/smsbillables/management/commands/bootstrap_tropo_gateway.py
  corehq/apps/userreports/management/commands/find_datasource_mismatches.py
  corehq/apps/userreports/management/commands/load_spec.py
  corehq/apps/userreports/management/commands/resave_couch_forms_and_cases.py
  corehq/apps/userreports/tests/test_data_source_repeats.py
  corehq/apps/userreports/tests/utils.py
  corehq/blobs/management/commands/blob_storage_report.py
  corehq/blobs/management/commands/check_blob_logs.py
  corehq/blobs/management/commands/run_blob_migration.py
  corehq/blobs/tests/test_init.py
  corehq/blobs/tests/test_migrate.py
  corehq/blobs/tests/test_mixin.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_extension_indexes.py
  corehq/form_processor/management/commands/make_sharded_sql_function.py
  corehq/motech/repeaters/management/commands/delete_duplicate_cancelled_records.py
  corehq/motech/repeaters/management/commands/generate_repeater_report.py
  corehq/motech/repeaters/management/commands/update_cancelled_records.py
  corehq/sql_db/operations.py
  corehq/tests/noseplugins/timing.py
  corehq/util/test_utils.py
  custom/_legacy/mvp_docs/tests/test_pillows.py
  custom/_legacy/pact/tests/dot_ordering.py
  custom/_legacy/pact/tests/dot_submission.py
  custom/bihar/tests/test_homevisits.py
  custom/champ/tests/__init__.py
  custom/champ/tests/utils.py
  custom/icds/management/commands/cleanup_orphan_migration.py
  custom/icds/management/commands/close_orphaned_cases.py
  custom/icds/management/commands/export_orphaned_cases.py
  custom/icds/management/commands/find_cases_with_no_delivery.py
  custom/icds/management/commands/phone_number_data.py
  custom/icds/management/commands/phone_number_data_2.py
  custom/icds_reports/management/commands/export_non_aadhar.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/utils/__init__.py
  custom/intrahealth/tests/__init__.py
  custom/intrahealth/tests/test_fluffs.py
  custom/intrahealth/tests/test_reports.py
  custom/intrahealth/tests/utils.py
  custom/up_nrhm/tests/__init__.py
  custom/up_nrhm/tests/utils.py
  custom/world_vision/tests/utils.py
  scripts/checkyaml.py
  testapps/test_pillowtop/tests/test_settings.py
Labels: product/invisible

#20576 Reminders migration updates
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/apps/reminders/views.py
Labels: product/invisible

#20610 Add support for sms surveys in reminders migration
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
Labels: product/invisible

#20608 direct the manual refresh data to exports_download_queue
  corehq/apps/export/tasks.py
  corehq/apps/export/views.py
Labels: product/all-users-all-environments, product/invisible

#20612 make sure title is ascii friendly for file name when doing ucr export
  corehq/apps/userreports/tasks.py
Labels: product/all-users-all-environments, product/invisible

#20036 Add custom eslint rule to avoid new
  .eslintrc.js
  .stickler.yml
  eslint/README.md
  eslint/docs/rules/no-unblessed-new.md
  eslint/lib/index.js
  eslint/lib/rules/no-unblessed-new.js
  eslint/package.json
  eslint/tests/lib/rules/no-unblessed-new.js
  package.json
Labels: product/invisible

#20616 ICDS | Fix chart tooltip
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
Labels: product/custom

#20622 Improvements to enterprise metrics
  corehq/apps/accounting/management/commands/report_on_enterprise_domain.py
Labels: product/invisible

#20617 kill enikshay migrations
  custom/enikshay/management/commands/run_current_patient_type_choice_migration.py
  custom/enikshay/management/commands/run_patient_type_choice_migration.py
  custom/enikshay/nikshay_datamigration/exceptions.py
  custom/enikshay/nikshay_datamigration/factory.py
  custom/enikshay/nikshay_datamigration/management/__init__.py
  custom/enikshay/nikshay_datamigration/management/commands/__init__.py
  custom/enikshay/nikshay_datamigration/management/commands/base_cleanup_command.py
  custom/enikshay/nikshay_datamigration/management/commands/cleanup_followup_csv.py
  custom/enikshay/nikshay_datamigration/management/commands/cleanup_outcomes_csv.py
  custom/enikshay/nikshay_datamigration/management/commands/cleanup_patients_csv.py
  custom/enikshay/nikshay_datamigration/management/commands/create_enikshay_cases.py
  custom/enikshay/nikshay_datamigration/management/commands/delete_migrated_cases.py
  custom/enikshay/nikshay_datamigration/management/commands/testing_facility_migration.py
  custom/enikshay/nikshay_datamigration/migrations/0011_drop_all_tables.py
  custom/enikshay/nikshay_datamigration/models.py
  custom/enikshay/nikshay_datamigration/tests/__init__.py
  custom/enikshay/nikshay_datamigration/tests/test_create_enikshay_cases.py
  custom/enikshay/nikshay_datamigration/tests/test_delete_migrated_cases.py
  custom/enikshay/nikshay_datamigration/tests/utils.py
  custom/enikshay/private_sector_datamigration/factory.py
  custom/enikshay/private_sector_datamigration/management/__init__.py
  custom/enikshay/private_sector_datamigration/management/commands/__init__.py
  custom/enikshay/private_sector_datamigration/management/commands/base_cleanup_csv.py
  custom/enikshay/private_sector_datamigration/management/commands/clean_userdetails_csv.py
  custom/enikshay/private_sector_datamigration/management/commands/create_cases_by_beneficiary.py
  custom/enikshay/private_sector_datamigration/management/commands/create_dtos_and_agencies.py
  custom/enikshay/private_sector_datamigration/management/commands/update_names.py
  custom/enikshay/private_sector_datamigration/management/commands/update_user_contact_phone_number.py
  custom/enikshay/private_sector_datamigration/migrations/0017_drop_all_tables.py
  custom/enikshay/private_sector_datamigration/models/__init__.py
  custom/enikshay/private_sector_datamigration/models/jul19.py
  custom/enikshay/private_sector_datamigration/models/jul7.py
  custom/enikshay/private_sector_datamigration/models/jun14.py
  custom/enikshay/private_sector_datamigration/models/jun30.py
  custom/enikshay/private_sector_datamigration/models/migrated_beneficiary_counter.py
  custom/enikshay/private_sector_datamigration/tests/__init__.py
  custom/enikshay/private_sector_datamigration/tests/test_create_cases_for_beneficiary.py
  custom/enikshay/private_sector_datamigration/tests/test_create_dtos_and_agencies.py
  settings.py
Labels: product/invisible

#20624 use csv342 in more places
  corehq/apps/accounting/tasks.py
  corehq/apps/cleanup/management/commands/list_dynamic_reports.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/domain/views.py
  corehq/apps/hqadmin/history.py
  corehq/apps/users/views/mobile/users.py
  custom/apps/wisepill/views.py
  custom/icds_reports/tasks.py
Labels: product/invisible
