Repository dimagi/commcare-hq, pull requests merged in 2018-06, with the labels that each got.

#20744 changed not_selected for warning_type
  custom/abt/reports/flagspecs_v2.yaml
Labels: product/custom

#20739 add non binding max size and full to locking queue
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
Labels: product/invisible

#20741 Remove jplayer
  corehq/apps/hqmedia/static/hqmedia/js/Jplayer.swf
  corehq/apps/hqmedia/static/hqmedia/js/jquery.jplayer.min.js
  corehq/apps/hqmedia/templates/hqmedia/references.html
Labels: product/invisible

#20655 ICDS Dashboard - Beneficiary reports
  custom/icds_reports/migrations/0042_child_health_monthly_view.py
  custom/icds_reports/migrations/0047_added_new_wasting_and_stunting_columns_to_views.py
  custom/icds_reports/migrations/sql_templates/create_child_health_monthly_view.sql
  custom/icds_reports/migrations/sql_templates/create_datasource_views.sql
  custom/icds_reports/migrations/sql_templates/database_functions/child_health_monthly.sql
  custom/icds_reports/migrations/sql_templates/database_views/agg_awc_daily.sql
  custom/icds_reports/migrations/sql_templates/database_views/agg_awc_monthly.sql
  custom/icds_reports/migrations/sql_templates/database_views/agg_ccs_record_monthly.sql
  custom/icds_reports/migrations/sql_templates/database_views/agg_child_health_monthly.sql
  custom/icds_reports/migrations/sql_templates/database_views/awc_location_months.sql
  custom/icds_reports/migrations/sql_templates/database_views/child_health_monthly.sql
  custom/icds_reports/migrations/sql_templates/database_views/daily_attendance.sql
  custom/icds_reports/models.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/fixtures/child_cases.csv
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/tests/test_export_data.py
Labels: product/custom

#20734 remove mobile experience AB test, have it be normal functionality.
  corehq/apps/app_manager/templates/app_manager/app_view_release_manager.html
  corehq/apps/app_manager/templates/app_manager/partials/releases.html
  corehq/apps/app_manager/views/releases.py
  corehq/apps/hqwebapp/static/hqwebapp/js/mobile_experience_warning.js
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/registration/templates/registration/email/confirm_account.html
  corehq/apps/registration/templates/registration/partials/register_new_user/success.html
  corehq/apps/registration/utils.py
  corehq/apps/registration/views.py
  corehq/toggles.py
Labels: product/all-users-all-environments

#20745 Add support for TimedSchedules to reminders migration script
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0019_add_use_utc_as_default_timezone.py
  corehq/messaging/scheduling/migrations/0020_migratedreminder.py
  corehq/messaging/scheduling/models/__init__.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/models/migration.py
  corehq/messaging/scheduling/models/timed_schedule.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
Labels: product/invisible

#20746 add New Supervisory Report to vectorlink domains
  custom/abt/reports/data_sources/supervisory_v2.json
  custom/abt/reports/supervisory_report_v2.json
Labels: product/custom

#20735 Split hqadmin views
  corehq/apps/hqadmin/tests/test_authenticate_as.py
  corehq/apps/hqadmin/tests/test_views.py
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views.py
  corehq/apps/hqadmin/views/__init__.py
  corehq/apps/hqadmin/views/data.py
  corehq/apps/hqadmin/views/operations.py
  corehq/apps/hqadmin/views/reports.py
  corehq/apps/hqadmin/views/system.py
  corehq/apps/hqadmin/views/users.py
  corehq/apps/hqadmin/views/utils.py
  corehq/apps/ota/urls.py
  corehq/apps/sms/views.py
  corehq/blobs/management/commands/blob_storage_report.py
  corehq/tabs/tabclasses.py
  settings.py
Labels: product/feature-flag

#20742 hide ID fields when creating data sources and reports
  corehq/apps/userreports/ui/forms.py
Labels: product/feature-flag

#20748 Provide default for bypass_two_factor
  corehq/apps/domain/decorators.py
Labels: product/invisible

#20750 fix view source for forms in non-training modules
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/templates/app_manager/form_view.html
Labels: product/invisible

#20751 Fallback to not looking at all forms in ES
  corehq/apps/reports/filters/forms.py
  corehq/apps/reports/templates/reports/filters/form_app_module_drilldown.html
Labels: product/custom

#20755 twilio support http proxy
  corehq/apps/hqwebapp/two_factor_gateways.py
Labels: product/invisible

#20758 Py3 compatibility updates
  corehq/apps/accounting/enterprise.py
  corehq/messaging/scheduling/models/migration.py
  corehq/sql_db/util.py
Labels: product/invisible

#20754 Fix pillow metric
  corehq/ex-submodules/pillowtop/tasks.py
Labels: product/invisible

#20761 Remove ComparedQuerySet
  corehq/apps/locations/adjacencylist.py
  corehq/apps/locations/fixtures.py
  corehq/apps/locations/models.py
  corehq/apps/locations/queryutil.py
  corehq/apps/locations/tests/test_location_queries.py
Labels: product/invisible

#20752 Support bulk translations for cchq-only strings
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/id_strings.py
Labels: product/all-users-all-environments

#20762 eslint-dimagi: fix option handling for no-unblessed-new
  eslint/.eslintignore
  eslint/lib/rules/no-unblessed-new.js
  eslint/package.json
Labels: product/invisible

#20760 SMSForms error handling with formplayer backend
  corehq/apps/reminders/event_handlers.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/util.py
  corehq/messaging/scheduling/models/content.py
Labels: product/invisible

#20749 resize pools
  corehq/apps/couch_sql_migration/couchsqlmigration.py
Labels: product/invisible

#20715 Case List Explorer Report
  corehq/apps/case_search/const.py
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/models.py
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/cleanup/migrations/0012_add_es_index_to_checkpoint_ids.py
  corehq/apps/es/case_search.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/hqwebapp/static/hqwebapp/js/atwho.js
  corehq/apps/hqwebapp/static/hqwebapp/js/knockout_bindings.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/knockout_subscribables.ko.js
  corehq/apps/hqwebapp/templates/hqwebapp/includes/core_libraries.html
  corehq/apps/hqwebapp/templatetags/tests/rendered/javascript_libraries_hq.html
  corehq/apps/ota/views.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/cases/data_sources.py
  corehq/apps/reports/standard/cases/filters.py
  corehq/apps/reports/static/reports/js/filters/case_list_explorer.js
  corehq/apps/reports/static/reports/js/filters/case_list_explorer_knockout_bindings.js
  corehq/apps/reports/static/reports/js/filters/main.js
  corehq/apps/reports/templates/reports/filters/explorer_columns.html
  corehq/apps/reports/templates/reports/filters/xpath_textarea.html
  corehq/apps/reports/templates/reports/partials/filters_css.html
  corehq/apps/reports/templates/reports/partials/filters_js.html
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/ex-submodules/casexml/apps/case/management/commands/create_case_fixtures.py
  corehq/pillows/case_search.py
  corehq/pillows/mappings/case_search_mapping.json
  corehq/pillows/mappings/case_search_mapping.py
  corehq/reports.py
  corehq/toggles.py
  requirements/requirements.txt
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
  testapps/test_pillowtop/tests/test_case_search_pillow.py
  testapps/test_pillowtop/tests/test_reindexer.py
Labels: product/feature-flag, reindex/migration

#20767 remove an obsolete decorator so uploads work for users that require 2FA
  corehq/apps/hqmedia/decorators.py
  corehq/apps/hqmedia/views.py
Labels: product/invisible

#20737 Add ability to sort report by case property value
  corehq/apps/case_search/const.py
  corehq/apps/es/case_search.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
Labels: product/invisible

#20765 specify choices for celery task state
  corehq/util/management/commands/show_celery_tasks.py
Labels: product/invisible

#20773 Confirmation modal when deleting app
  corehq/apps/app_manager/templates/app_manager/apps_base.html
  corehq/apps/app_manager/templates/app_manager/partials/app-settings.html
  corehq/apps/app_manager/templates/app_manager/partials/confirm_delete_app.html
  corehq/apps/app_manager/templates/app_manager/partials/undo_delete_app.html
Labels: product/all-users-all-environments

#20772 Remove xform_display view
  corehq/apps/app_manager/templates/app_manager/suite/display.xml
  corehq/apps/app_manager/templates/app_manager/xform_display.html
  corehq/apps/app_manager/templates/app_manager/xform_display_tree.html
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/forms.py
Labels: product/invisible

#20769 Clean up form settings/builder page titles
  corehq/apps/app_manager/static/app_manager/js/app_manager.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_designer.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/templates/app_manager/form_designer.html
  corehq/apps/app_manager/templates/app_manager/form_view.html
Labels: product/all-users-all-environments

#20770 Deploy modal: don't allow Java SMS installs on non-Java CC versions
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/templates/app_manager/partials/releases_deploy_modal.html
  corehq/apps/app_manager/templates/app_manager/partials/releases_deploy_modal_sms.html
Labels: product/all-users-all-environments

#20774 remove filters for height measurement efficiency in export data
  custom/icds_reports/sqldata/exports/children.py
  custom/icds_reports/tests/test_export_data.py
Labels: product/custom

#20766 Update requirements file
  corehq/util/supervisord/api.py
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/uninstall-requirements.txt
Labels: product/invisible

#20764 Designate Customer Billing Account
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/migrations/0028_auto_20180604_1757.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/static/accounting/js/billing_account_form.js
  corehq/apps/accounting/templates/accounting/accounts.html
Labels: product/all-users-all-environments

#20606 Ce/dashboard models
  custom/icds_reports/migrations/0049_icdsauditentryrecord.py
  custom/icds_reports/migrations/0050_move_to_django.py
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_awc_data.sql
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_ccs_record.sql
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_child_health.sql
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_location_table.sql
  custom/icds_reports/migrations/sql_templates/database_functions/update_location_table.sql
  custom/icds_reports/models.py
  custom/icds_reports/models/__init__.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/models/helper.py
  custom/icds_reports/models/util.py
  custom/icds_reports/models/views.py
  custom/icds_reports/tests/test_aggregation_script.py
Labels: product/invisible

#20775 Allow cases with no owner
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/tests/test_repeaters.py
Labels: product/invisible

#20747 Case list explorer report frontend updates
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/es/case_search.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/cases/filters.py
  corehq/apps/reports/static/reports/js/config.dataTables.bootstrap.js
  corehq/apps/reports/static/reports/js/filters/case_list_explorer.js
  corehq/apps/reports/static/reports/js/filters/case_list_explorer_knockout_bindings.js
  corehq/apps/reports/static/reports/js/filters/main.js
  corehq/apps/reports/templates/reports/filters/explorer_columns.html
  corehq/apps/reports/templates/reports/filters/xpath_textarea.html
Labels: product/invisible

#20783 Pin tornado
  requirements/prod-requirements.txt
Labels: product/invisible

#20779 only get type if case
  corehq/apps/reports/views.py
Labels: product/invisible

#20780 cleanup Report an Issue and 500 emails
  corehq/apps/hqwebapp/views.py
Labels: product/all-users-all-environments

#20785 Fix import app page
  corehq/apps/app_manager/templates/app_manager/apps_base.html
  corehq/apps/app_manager/templates/app_manager/managed_app.html
Labels: product/all-users-all-environments

#20776 Added promise for location request - hide loading message when both promises are finish
  custom/icds_reports/static/js/directives/location-filter/location-filter.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/progress-report.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/system-usage.directive.html
Labels: product/custom

#20777 Fix printing | Prevent cutting last column by allowing wrapping cells
  custom/icds_reports/static/css/icds_dashboard.css
Labels: product/custom

#20782 Designate customer software subscription
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/migrations/0029_auto_20180605_1826.py
  corehq/apps/accounting/models.py
Labels: product/admin

#20789 make Location Search help text be translatable
  corehq/apps/reports/filters/users.py
Labels: product/all-users-all-environments

#20771 Externalize JavaScript: indicators
  corehq/apps/crud/interface.py
  corehq/apps/crud/models.py
  corehq/apps/crud/static/crud/js/admin.js
  corehq/apps/crud/static/crud/js/crud.admin.js
  corehq/apps/crud/templates/crud/forms/crud.add_item.html
  corehq/apps/crud/templates/crud/interfaces/crud.tabular.html
  corehq/apps/indicators/admin/__init__.py
  corehq/apps/indicators/templates/indicators/forms/crud.add_indicator.html
  corehq/apps/indicators/templates/indicators/interfaces/indicator_admin.html
  corehq/apps/indicators/templates/indicators/partials/form_label.html
  corehq/apps/indicators/views.py
  corehq/apps/reports/templates/reports/form/partials/readable_form.html
  corehq/apps/reports/templates/reports/standard/base_template.html
  custom/_legacy/mvp/models.py
  custom/_legacy/mvp/static/mvp/ko/mvp.async_table.js
Labels: product/invisible

#20781 Put case list explorer knockout bindings in module
  corehq/apps/reports/static/reports/js/filters/case_list_explorer_knockout_bindings.js
  corehq/apps/reports/static/reports/js/filters/main.js
Labels: product/invisible

#19054 Ce/auto batches
  corehq/apps/locations/migrations/0013_adding_indices_for_warehouse.py
  corehq/apps/locations/migrations/0014_merge_20180601_0608.py
  corehq/apps/locations/models.py
  corehq/apps/reports/datatables/__init__.py
  corehq/apps/reports/standard/deployments.py
  corehq/toggles.py
  corehq/warehouse/const.py
  corehq/warehouse/dbaccessors.py
  corehq/warehouse/etl.py
  corehq/warehouse/management/commands/commit_table.py
  corehq/warehouse/management/commands/create_batch.py
  corehq/warehouse/management/commands/mark_batch_complete.py
  corehq/warehouse/migrations/0012_unique_constraints.py
  corehq/warehouse/migrations/0013_auto_incrementing_batch_id.py
  corehq/warehouse/migrations/0014_batch_dag_slug.py
  corehq/warehouse/migrations/0015_batch_foreign_key.py
  corehq/warehouse/migrations/0016_readd_batch_key.py
  corehq/warehouse/migrations/0017_domain_conditional_null.py
  corehq/warehouse/migrations/0018_domain_memberships_json_field.py
  corehq/warehouse/migrations/0019_add_domainmembership_dim.py
  corehq/warehouse/migrations/0020_synclogfact.py
  corehq/warehouse/migrations/0021_location_staging_changes.py
  corehq/warehouse/migrations/0022_userstagingtable_assigned_location_ids.py
  corehq/warehouse/migrations/0023_add_build_info.py
  corehq/warehouse/migrations/0024_metafields.py
  corehq/warehouse/migrations/0025_app_status_fixes.py
  corehq/warehouse/migrations/0026_real_foreign_keys_and_no_sync_build.py
  corehq/warehouse/migrations/0027_non_null_fact.py
  corehq/warehouse/migrations/0028_nullable_user_dim.py
  corehq/warehouse/models/__init__.py
  corehq/warehouse/models/dimensions.py
  corehq/warehouse/models/facts.py
  corehq/warehouse/models/meta.py
  corehq/warehouse/models/staging.py
  corehq/warehouse/tests/test_dbaccessors.py
  corehq/warehouse/tests/test_dependencies.py
  corehq/warehouse/tests/test_dimensions.py
  corehq/warehouse/tests/test_integration.py
  corehq/warehouse/tests/test_staging.py
  corehq/warehouse/tests/utils.py
  corehq/warehouse/transforms/sql/app_status_fact.sql
  corehq/warehouse/transforms/sql/app_status_form_staging.sql
  corehq/warehouse/transforms/sql/app_status_synclog_staging.sql
  corehq/warehouse/transforms/sql/application_dim.sql
  corehq/warehouse/transforms/sql/domain_dim.sql
  corehq/warehouse/transforms/sql/domain_membership_dim.sql
  corehq/warehouse/transforms/sql/form_fact.sql
  corehq/warehouse/transforms/sql/group_dim.sql
  corehq/warehouse/transforms/sql/location_dim.sql
  corehq/warehouse/transforms/sql/location_staging.sql
  corehq/warehouse/transforms/sql/synclog_fact.sql
  corehq/warehouse/transforms/sql/user_dim.sql
  corehq/warehouse/transforms/sql/user_group_dim.sql
  corehq/warehouse/transforms/sql/user_location_dim.sql
Labels: product/invisible

#20797 Add last submitting user recipient
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/scheduling/tests/test_recipients.py
Labels: product/feature-flag

#20790 Remove icons from hqwebapp/js/main.js
  corehq/apps/app_manager/static/app_manager/js/app_manager.js
  corehq/apps/app_manager/templates/app_manager/partials/case_list_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/case_search_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/custom_instances.html
  corehq/apps/app_manager/templates/app_manager/partials/enable_schedule.html
  corehq/apps/app_manager/templates/app_manager/partials/mobile_report_configs.html
  corehq/apps/hqwebapp/static/hqwebapp/js/main.js
  corehq/apps/reports/templates/reports/filters/explorer_columns.html
  corehq/apps/translations/static/translations/js/translations.js
  corehq/apps/userreports/templates/userreports/partials/property_list_configuration.html
Labels: product/invisible

#20290 Remove FRI custom module
  custom/expired_domains.md
  custom/fri/__init__.py
  custom/fri/_design/views/extra_message/map.js
  custom/fri/_design/views/message_bank/map.js
  custom/fri/_design/views/randomized_message/map.js
  custom/fri/api.py
  custom/fri/forms.py
  custom/fri/management/__init__.py
  custom/fri/management/commands/__init__.py
  custom/fri/management/commands/dump_fri_message_bank.py
  custom/fri/models.py
  custom/fri/reports/__init__.py
  custom/fri/reports/fields.py
  custom/fri/reports/filters.py
  custom/fri/reports/reports.py
  custom/fri/templates/fri/chat.html
  custom/fri/templates/fri/message_bank.html
  custom/fri/templates/fri/phe_dashboard.html
  custom/fri/urls.py
  custom/fri/views.py
  settings.py
  urls.py
Labels: product/custom

#20787 print all failed migrations at the end
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
Labels: product/invisible

#20800 Turn on no-implicit-globals in eslint
  .eslintrc.js
Labels: product/invisible

#20804 Fix js error from ejs indicators PR
  corehq/apps/crud/static/crud/js/admin.js
Labels: product/invisible

#20801 Eslint plugin: add link to error message
  eslint/lib/rules/no-unblessed-new.js
  eslint/package.json
  package.json
Labels: product/invisible

#20807 Update package.json
  package.json
Labels: product/invisible

#20802 Add case property regular expression match as rule criteria option
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_criteria.js
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_rule_criteria.html
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/messaging/scheduling/forms.py
Labels: product/feature-flag

#20803 Stop using jquery.history
  corehq/apps/hqadmin/static/hqadmin/js/visualizations.js
  corehq/apps/hqwebapp/static/hqwebapp/js/lib/jquery.history.js
  corehq/apps/reports/static/reports/js/reports.async.js
  corehq/apps/reports/templates/reports/standard/base_template.html
Labels: product/invisible

#20788 Remove deleted case properties from data corrections
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#20805 show a useful error message when the user does not upload a valid ima…
  corehq/apps/hqmedia/exceptions.py
  corehq/apps/hqmedia/models.py
  corehq/apps/hqmedia/views.py
Labels: product/invisible

#20806 Filter out ineligible children
  custom/icds_reports/ucr/data_sources/dashboard/daily_feeding_forms.json
  custom/icds_reports/ucr/tests/test_daily_feeding_form_ucr.py
Labels: product/custom

#20808 cleanup after calling set_request in tests
  corehq/ex-submodules/casexml/apps/phone/tests/test_new_sync.py
  corehq/util/tests/test_global_request.py
Labels: product/invisible

#20811 pass viewname to reverse
  custom/ewsghana/forms.py
Labels: product/invisible

#20814 Fix migration script
  corehq/sql_db/management/commands/migrate_multi.py
Labels: product/invisible

#20817 fix teardown on tests
  corehq/tests/nose.py
Labels: product/invisible

#20812 Fix 500 in pact report
  corehq/apps/reports/templates/reports/careplan/patient_careplan.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_careplan.html
Labels: product/custom

#20815 Inline Javascript out of reports/views.py
  corehq/apps/hqwebapp/static/hqwebapp/js/main.js
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
Labels: product/invisible

#20809 requirejs migration: form data page
  .eslintrc.js
  corehq/apps/reports/static/reports/js/data_corrections.js
  corehq/apps/reports/static/reports/js/form_data_main.js
  corehq/apps/reports/static/reports/js/readable_form.js
  corehq/apps/reports/static/reports/js/single_form.js
  corehq/apps/reports/templates/reports/reportdata/form_data.html
Labels: product/invisible

#20740 Add MobileRecoveryMeasure model
  corehq/apps/ota/admin.py
  corehq/apps/ota/migrations/0004_mobilerecoverymeasure.py
  corehq/apps/ota/models.py
  corehq/apps/ota/urls.py
  corehq/apps/ota/views.py
Labels: product/invisible

#20778 Add mobile recovery measures to app profile
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_profile.py
  corehq/apps/ota/views.py
  corehq/toggles.py
Labels: product/invisible

#20820 add choices to args options
  corehq/apps/hqadmin/management/commands/check_services.py
Labels: product/invisible

#20810 Send export success/failure counts to datadog
  corehq/apps/export/export.py
  corehq/apps/export/tasks.py
  corehq/util/datadog/gauges.py
Labels: product/invisible

#20822 Handle legacy 'until' condition in reminders migration
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
Labels: product/invisible

#20830 Use debian jessie
  Dockerfile
  Dockerfile-py3
Labels: product/invisible

#20813 Fix for view lookup tables js error
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/reports/static/reports/js/filters/case_list_explorer.js
Labels: product/all-users-all-environments

#20824 Better exception handling
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/models.py
Labels: product/invisible

#20825 max_length is irrelevant for integer fields
  corehq/apps/ota/migrations/0005_rm_max_length_from_integer.py
  corehq/apps/ota/models.py
Labels: product/invisible

#20833 read don't write
  corehq/apps/case_importer/tracking/case_upload_tracker.py
Labels: product/invisible

#20826 Cache recovery measures endpoint
  corehq/apps/ota/admin.py
  corehq/apps/ota/views.py
Labels: product/invisible

#20827 Drop unused plugins
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap-combobox.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap-hoverdropdown.js
Labels: product/invisible

#20828 Migrate to requirejs: edit scheduled report
  corehq/apps/hqwebapp/static/hqwebapp/js/widgets.js
  corehq/apps/hqwebapp/widgets.py
  corehq/apps/reports/static/reports/js/edit_scheduled_report.js
  corehq/apps/reports/templates/reports/edit_scheduled_report.html
  corehq/apps/users/forms.py
Labels: product/invisible

#20798 perf improvement
  corehq/apps/app_manager/commcare_settings.py
  corehq/apps/app_manager/views/apps.py
Labels: product/invisible

#20654 Make case restore username the case's name
  corehq/apps/case_migrations/views.py
  corehq/ex-submodules/casexml/apps/phone/xml.py
Labels: product/invisible

#20832 Clean up uninstall requirements
  requirements/uninstall-requirements.txt
Labels: product/invisible

#20784 Add recovery measures history report
  corehq/apps/domain/templates/domain/admin/recovery_measures_history.html
  corehq/apps/domain/urls.py
  corehq/apps/domain/views.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#20831 Reduce bootstrap interval to 1 week for static UCR
  corehq/apps/userreports/pillow.py
Labels: product/invisible

#20818 Icds Reports | Beneficiary List Tabular Report add columns
  custom/icds_reports/migrations/sql_templates/database_views/child_health_monthly.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/sqldata/exports/beneficiary.py
  custom/icds_reports/tests/test_export_data.py
Labels: product/custom

#20705 move toggle to app config
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/supported_languages.js
  corehq/apps/app_manager/templates/app_manager/languages.html
  corehq/apps/app_manager/templates/app_manager/managed_app.html
  corehq/apps/app_manager/templates/app_manager/partials/supported-languages.html
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/formdesigner.py
  corehq/apps/notifications/ui_notify.py
  corehq/toggles.py
Labels: product/all-users-all-environments

#20823 ICDS - zscore_grading columns for denominators
  custom/icds_reports/migrations/0051_added_zscore_grading_wfh_hfa_rec_in_month_to_agg_child_health.py
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_child_health.sql
  custom/icds_reports/migrations/sql_templates/database_views/agg_child_health_monthly.sql
  custom/icds_reports/migrations/sql_templates/update_tables23.sql
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/models/views.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/reports/maternal_child.py
  custom/icds_reports/reports/prevalence_of_severe.py
  custom/icds_reports/reports/prevalence_of_stunting.py
  custom/icds_reports/sqldata/agg_child_health_monthly.py
  custom/icds_reports/sqldata/exports/children.py
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/reports/test_maternal_child_data.py
  custom/icds_reports/tests/reports/test_prevalence_of_severe.py
  custom/icds_reports/tests/reports/test_prevalence_of_stunting.py
  custom/icds_reports/tests/test_fact_sheet_report.py
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#20838 Update fields shown in smsforms admin
  corehq/apps/smsforms/admin.py
Labels: product/invisible

#20841 adding comment char
  scripts/uninstall-requirements.sh
Labels: product/invisible

#20842 Get case properties from all apps
  corehq/apps/app_manager/app_schemas/case_properties.py
Labels: product/invisible

#20852 don't fail build if post to datadog fails
  docker/run.sh
Labels: product/invisible

#20851 don't 500 on failure to publish message to redis
  corehq/apps/app_manager/views/notifications.py
Labels: product/all-users-all-environments

#20821 enable profiling in production
  corehq/apps/ota/views.py
  corehq/apps/receiverwrapper/views.py
  corehq/ex-submodules/dimagi/utils/decorators/profile.py
  docs/profiling.rst
Labels: product/invisible

#20839 Show correct properties for each suggestion instance
  corehq/apps/reports/static/reports/js/filters/case_list_explorer.js
Labels: product/invisible

#20847 handle remaining open()
  corehq/apps/builds/jadjar.py
  corehq/apps/builds/management/commands/sign_jadjar.py
  corehq/apps/hqadmin/management/commands/export_domain_forms_raw.py
Labels: product/invisible

#20849 do not activate subscription if date_start == date_end
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/tests/test_models.py
Labels: product/invisible

#20846 remove remaining code from enikshay migrations
  custom/enikshay/nikshay_datamigration/__init__.py
  custom/enikshay/nikshay_datamigration/migrations/0001_initial.py
  custom/enikshay/nikshay_datamigration/migrations/0002_delete_outcome_model.py
  custom/enikshay/nikshay_datamigration/migrations/0003_add_outcome_again.py
  custom/enikshay/nikshay_datamigration/migrations/0004_remove_all_tables.py
  custom/enikshay/nikshay_datamigration/migrations/0005_page_integer.py
  custom/enikshay/nikshay_datamigration/migrations/0006_auto_20170104_1708.py
  custom/enikshay/nikshay_datamigration/migrations/0007_auto_20170119_1705.py
  custom/enikshay/nikshay_datamigration/migrations/0008_auto_20170119_1902.py
  custom/enikshay/nikshay_datamigration/migrations/0009_followup.py
  custom/enikshay/nikshay_datamigration/migrations/0010_followup_changes.py
  custom/enikshay/nikshay_datamigration/migrations/0011_drop_all_tables.py
  custom/enikshay/nikshay_datamigration/migrations/__init__.py
  custom/enikshay/nikshay_datamigration/models.py
  custom/enikshay/private_sector_datamigration/__init__.py
  custom/enikshay/private_sector_datamigration/migrations/0001_initial.py
  custom/enikshay/private_sector_datamigration/migrations/0002_auto_20170512_1919.py
  custom/enikshay/private_sector_datamigration/migrations/0003_auto_20170513_1805.py
  custom/enikshay/private_sector_datamigration/migrations/0004_migratedbeneficiarycounter.py
  custom/enikshay/private_sector_datamigration/migrations/0005_auto_20170520_1530.py
  custom/enikshay/private_sector_datamigration/migrations/0006_auto_20170520_1638.py
  custom/enikshay/private_sector_datamigration/migrations/0007_auto_20170601_1824.py
  custom/enikshay/private_sector_datamigration/migrations/0008_episodeprescription_voucher.py
  custom/enikshay/private_sector_datamigration/migrations/0009_non_null_checks.py
  custom/enikshay/private_sector_datamigration/migrations/0010_kill_labtest.py
  custom/enikshay/private_sector_datamigration/migrations/0011_agencyTypeId_nonnull.py
  custom/enikshay/private_sector_datamigration/migrations/0012_archive_jun_14.py
  custom/enikshay/private_sector_datamigration/migrations/0013_archive_june_30_add_july_7.py
  custom/enikshay/private_sector_datamigration/migrations/0014_add_july_13.py
  custom/enikshay/private_sector_datamigration/migrations/0015_add_july_19.py
  custom/enikshay/private_sector_datamigration/migrations/0016_drop_obsolete_tables.py
  custom/enikshay/private_sector_datamigration/migrations/0017_drop_all_tables.py
  custom/enikshay/private_sector_datamigration/migrations/__init__.py
  custom/enikshay/private_sector_datamigration/models/__init__.py
  settings.py
Labels: product/invisible

#20848 remove TEST_APPS
  settings.py
  testsettings.py
Labels: product/invisible

#20843 Fix case data page
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/reports/templates/reports/reportdata/case_data.html
  corehq/apps/reports/templates/reports/reportdata/form_data.html
Labels: product/all-users-all-environments

#20837 Make permissions more consistent across messaging pages
  corehq/apps/reminders/views.py
  corehq/apps/sms/views.py
  corehq/messaging/decorators.py
Labels: product/invisible

#20850 refactor; break into two parts
  corehq/ex-submodules/pillow_retry/tests/test_all_pillows.py
  corehq/ex-submodules/pillow_retry/tests/test_retry.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
Labels: product/invisible

#20844 Migrate requirejs: add form repeater
  corehq/apps/domain/templates/domain/admin/global_sms_rates.html
  corehq/apps/hqwebapp/static/hqwebapp/js/hq.helpers.js
  corehq/apps/hqwebapp/static/hqwebapp/js/widgets.js
  corehq/apps/locations/static/locations/js/widgets_main.js
  corehq/motech/repeaters/static/repeaters/js/add_form_repeater.js
  corehq/motech/repeaters/templates/repeaters/add_form_repeater.html
Labels: product/invisible

#20854 fix py3 regressions
  corehq/apps/locations/migrations/0013_adding_indices_for_warehouse.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/warehouse/migrations/0012_unique_constraints.py
  corehq/warehouse/migrations/0013_auto_incrementing_batch_id.py
  corehq/warehouse/migrations/0014_batch_dag_slug.py
  corehq/warehouse/migrations/0016_readd_batch_key.py
  corehq/warehouse/migrations/0017_domain_conditional_null.py
  corehq/warehouse/migrations/0018_domain_memberships_json_field.py
  corehq/warehouse/migrations/0019_add_domainmembership_dim.py
  corehq/warehouse/migrations/0020_synclogfact.py
  corehq/warehouse/migrations/0021_location_staging_changes.py
  corehq/warehouse/migrations/0022_userstagingtable_assigned_location_ids.py
  corehq/warehouse/migrations/0023_add_build_info.py
  corehq/warehouse/migrations/0025_app_status_fixes.py
  corehq/warehouse/migrations/0026_real_foreign_keys_and_no_sync_build.py
  custom/icds_reports/migrations/0050_move_to_django.py
  custom/icds_reports/tests/test_fact_sheet_report.py
Labels: product/invisible

#20855 Nit
  corehq/apps/accounting/forms.py
Labels: product/invisible

#20853 SMSForms: Constrain int to 32-bit signed int
  corehq/apps/sms/handlers/form_session.py
  corehq/apps/sms/messages.py
Labels: product/invisible

#20836 Intrahealth old app rework
  custom/intrahealth/reports/__init__.py
  custom/intrahealth/reports/fiche_consommation_report.py
  custom/intrahealth/reports/fiche_consommation_report_v2.py
  custom/intrahealth/reports/recap_passage_report_v2.py
  custom/intrahealth/reports/tableu_de_board_report.py
  custom/intrahealth/reports/tableu_de_board_report_v2.py
  custom/intrahealth/reports/utils.py
  custom/intrahealth/sqldata.py
  custom/intrahealth/tests/__init__.py
  custom/intrahealth/tests/fixtures/commande_v1.csv
  custom/intrahealth/tests/fixtures/commande_v2.csv
  custom/intrahealth/tests/fixtures/operateur_v1.csv
  custom/intrahealth/tests/fixtures/operateur_v2.csv
  custom/intrahealth/tests/reports/test_fiche_consommation_report_v2.py
  custom/intrahealth/tests/reports/test_tableu_de_board_report_v2.py
  custom/intrahealth/tests/utils.py
  custom/intrahealth/ucr/data_sources/commande_v1.json
  custom/intrahealth/ucr/data_sources/commande_v2.json
  custom/intrahealth/ucr/data_sources/operateur_v1.json
  custom/intrahealth/ucr/data_sources/operateur_v2.json
  custom/intrahealth/utils.py
  settings.py
Labels: product/custom

#20857 Fix deprecation warning
  corehq/apps/userreports/ui/widgets.py
Labels: product/invisible

#20856 use csv342 in remaining places
  corehq/apps/export/management/commands/deid_export.py
  corehq/ex-submodules/couchexport/writers.py
  corehq/ex-submodules/dimagi/utils/csv.py
  corehq/ex-submodules/dimagi/utils/django/management.py
  corehq/tests/noseplugins/timing.py
Labels: product/invisible

#20860 Stock Status by Product UI fixes
  corehq/apps/reports/graph_models.py
  corehq/apps/reports/templates/reports/partials/graphs/multibar_chart.html
Labels: product/all-users-all-environments

#20858 upgrade captcha library
  requirements/requirements.txt
Labels: product/invisible

#20862 Use reasonable sorting icons
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/datatables.less
  corehq/apps/reports/datatables/__init__.py
  corehq/apps/reports/static/reports/js/config.dataTables.bootstrap.js
Labels: product/all-users-all-environments

#20861 Check consistency automatically before committing
  corehq/apps/export/utils.py
Labels: product/invisible

#20869 convert bytes to unicode before writing with csv342
  corehq/ex-submodules/couchexport/writers.py
Labels: product/invisible

#20870 revert to builtin csv
  corehq/ex-submodules/couchexport/writers.py
Labels: product/invisible

#20863 Add http libs to prod-requirements
  requirements/prod-requirements.txt
Labels: product/invisible

#20859 ICDS - QA issues
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/location-filter.directive.spec.js
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/views.py
Labels: product/custom

#20871 use csv342 and support utf-8 and ints
  corehq/ex-submodules/couchexport/tests/test_writers.py
  corehq/ex-submodules/couchexport/writers.py
Labels: product/invisible

#20875 Get rid of js_scripts option in GenericReportView
  corehq/apps/reports/generic.py
  corehq/apps/reports/standard/deployments.py
  corehq/apps/reports/standard/project_health.py
  corehq/apps/reports/templates/reports/standard/base_template.html
Labels: product/invisible

#20877 make sure activate_subscriptions doesn't try to activate past subscriptions
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/tests/test_models.py
Labels: product/invisible

#20878 Fix messaging error report and link
  corehq/apps/reports/standard/sms.py
  corehq/messaging/scheduling/views.py
Labels: product/invisible

#20736 Set minimum year to 1950
  bower.json
Labels: product/all-users-all-environments

#20868 Better username validation
  corehq/apps/users/tests/test_views.py
  corehq/apps/users/views/mobile/users.py
Labels: product/all-users-all-environments

#20835 Mk transifex pull
  corehq/apps/app_manager/app_translations/parser.py
  custom/icds/tasks.py
  custom/icds/translations/integrations/client.py
  custom/icds/translations/integrations/exceptions.py
  custom/icds/translations/integrations/transifex.py
  custom/icds_reports/forms.py
  custom/icds_reports/views.py
Labels: Open for review: hold off on merge, product/custom

#20879 Use multiple windows for growth monitoring aggregation
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/utils/aggregation.py
Labels: product/custom

#20876 Load stock status reports asynchronously
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/commtrack/standard.py
Labels: product/all-users-all-environments

#20885 Handle simple weekly schedules in reminders migration
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
Labels: product/invisible

#20886 Enterprise dashboard: last 30 days instead of 7
  corehq/apps/accounting/enterprise.py
Labels: product/feature-flag

#20884 Add dateFormat to to_json()
  corehq/apps/reports/graph_models.py
Labels: product/invisible

#20880 Update session language on login
  corehq/apps/hqwebapp/utils.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/settings/views.py
Labels: product/all-users-all-environments

#20743 batch asyncindicators
  corehq/apps/userreports/adapter.py
  corehq/apps/userreports/es/adapter.py
  corehq/apps/userreports/laboratory/adapter.py
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/tests/test_async_indicators.py
  corehq/apps/userreports/tests/test_save_errors.py
  corehq/apps/userreports/tests/utils.py
Labels: product/invisible

#20892 Revert "Update session language on login"
  corehq/apps/hqwebapp/utils.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/settings/views.py
Labels: product/all-users-all-environments

#20867 Updates for sorting rows in export
  corehq/apps/export/templates/export/partial/new_customize_export_templates.html
  corehq/apps/hqwebapp/static/hqwebapp/js/knockout_bindings.ko.js
  corehq/toggles.py
Labels: product/feature-flag

#20898 notify if bihar supervisor reports are ever loaded
  custom/bihar/reports/indicators/indicators.py
  custom/bihar/reports/supervisor.py
Labels: product/custom

#20895 multirow_sortable feedback
  corehq/apps/export/templates/export/partial/new_customize_export_templates.html
  corehq/apps/hqwebapp/static/hqwebapp/js/knockout_bindings.ko.js
Labels: product/invisible

#20894 Enterprise dashboard feedback from CRS
  corehq/apps/accounting/enterprise.py
Labels: product/feature-flag

#20896 VectoLink - changed language to french in reports for vectorlink-burkina-faso domain
  custom/abt/reports/expressions.py
Labels: product/invisible

#20897 Discrepancy in percent unweighed indicator in Program Summary
  custom/icds_reports/reports/new_born_with_low_weight.py
  custom/icds_reports/static/icds_reports/js/spec/newborn_with_low_weight.directive.spec.js
  custom/icds_reports/static/js/directives/newborn_with_low_weight/newborn_with_low_weight.directive.js
  custom/icds_reports/tests/reports/test_new_born_with_low_weight.py
Labels: product/custom

#20903 remove out of date docs
  corehq/apps/reports/README.md
  docs/reporting.rst
Labels: product/invisible

#20902 Update edit form deprecation warning
  corehq/apps/reports/templates/reports/form/edit_submission.html
Labels: product/all-users-all-environments

#20904 Add Parent Case recipient to new reminders framework
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/scheduling/tests/test_recipients.py
Labels: product/feature-flag

#20890 Add billing_admin_emails to Billing Account
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/migrations/0031_billingaccount_billing_admin_emails.py
  corehq/apps/accounting/models.py
Labels: product/admin, product/all-users-all-environments

#20893 add case type to case exports table
  corehq/apps/export/templates/export/partial/export_list_controller.html
  corehq/apps/export/views.py
Labels: product/all-users-all-environments

#20901 Custom Daily Schedule Fixes
  corehq/messaging/scheduling/forms.py
Labels: product/feature-flag

#20907 More updates to edit submission deprecation notice
  corehq/apps/reports/templates/reports/form/edit_submission.html
Labels: product/all-users-all-environments

#20888 Require customer plans for customer accounts
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_forms.py
  corehq/apps/accounting/tests/test_new_domain_subscription.py
Labels: product/admin, product/all-users-all-environments

#20908 Support Abt custom recipient in new reminders framework
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  custom/abt/messaging/custom_recipients.py
  custom/abt/tests/__init__.py
  custom/abt/tests/test_custom_recipients.py
  settings.py
Labels: product/custom

#20909 Don't overwrite all property names if there is no name
  corehq/apps/reports/views.py
Labels: product/invisible

#20905 add parent id references to autogenerated data sources
  corehq/apps/userreports/app_manager/helpers.py
  corehq/apps/userreports/tests/test_app_manager_integration.py
Labels: product/feature-flag

#20900 support partial file downloads for exports
  corehq/apps/export/tests/test_export_views.py
  corehq/apps/export/views.py
  corehq/apps/reports/views.py
  corehq/util/download.py
Labels: product/all-users-all-environments

#20906 Add form_id to CaseRuleSubmission admin searchable fields
  corehq/apps/data_interfaces/admin.py
Labels: product/invisible

#20915 Yeski Naa Reports | Recovery Rate By PPS total row discrepancy fix
  custom/intrahealth/sqldata.py
Labels: product/custom
