Repository dimagi/commcare-hq, pull requests merged in 2018-09, with the labels that each got.

#21720 Use ace in web apps debugger
  bower.json
  corehq/apps/cloudcare/static/cloudcare/js/debugger/debugger.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer-common/base.html
  corehq/apps/cloudcare/templates/formplayer/debugger.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/motech/openmrs/views.py
Labels: product/feature-flag

#21719 Catch unrecognized filter
  corehq/apps/userreports/reports/builder/forms.py
Labels: product/all-users-all-environments

#21727 Update error message when importing excel file without headers
  corehq/apps/case_importer/views.py
Labels: product/all-users-all-environments

#21736 Make UI a little clearer for specifying Provider
  corehq/motech/openmrs/README.md
  corehq/motech/openmrs/forms.py
Labels: product/feature-flag, product/invisible

#21728 UCR ES adapter cleanup
  corehq/apps/userreports/README.md
  corehq/apps/userreports/adapter.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/tests/test_columns.py
  corehq/apps/userreports/tests/test_data_source_repeats.py
  corehq/apps/userreports/tests/test_location_data_source.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/tests/test_report_aggregation.py
  corehq/apps/userreports/tests/test_report_data.py
  corehq/apps/userreports/tests/test_report_filters.py
  corehq/apps/userreports/tests/test_view.py
Labels: product/invisible

#21211 Externalize js: NIC password compliance
  corehq/apps/domain/templates/login_and_password/login.html
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/settings/templates/settings/change_my_password.html
  corehq/apps/users/static/users/js/mobile_workers.ng.js
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/mobile_workers.html
  custom/icds/templates/icds/login.html
  custom/nic_compliance/static/nic_compliance/js/encoder.js
  custom/nic_compliance/templates/nic_compliance/password_encoder.html
Labels: product/invisible

#21733 sort key must be comparable to text
  corehq/apps/userreports/dbaccessors.py
Labels: product/invisible

#21732 use byte regex with bytestring
  corehq/apps/export/tests/test_get_export_file.py
Labels: product/invisible

#21731 handle json in both python2 and python3
  corehq/ex-submodules/couchexport/writers.py
  corehq/ex-submodules/pillowtop/tests/test_bulk.py
  corehq/ex-submodules/pillowtop/utils.py
Labels: product/invisible

#21730 truediv
  custom/icds_reports/mpr_sqldata.py
Labels: product/invisible

#21729 don't pass class type to types.MethodType
  corehq/apps/app_manager/models.py
Labels: product/invisible

#21717 Test that pruning apps makes it to ES
  testapps/test_pillowtop/tests/test_app_pillow.py
Labels: product/invisible

#21664 App aware location fixture sync
  corehq/apps/app_manager/const.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/json/commcare-app-settings.yaml
  corehq/apps/app_manager/static/app_manager/json/commcare-settings-layout.yaml
  corehq/apps/app_manager/static_strings.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/locations/fixtures.py
  corehq/apps/locations/tests/test_location_fixtures.py
Labels: product/feature-flag

#21725 modernize
  corehq/apps/case_importer/util.py
  corehq/apps/case_search/tasks.py
  corehq/apps/commtrack/tasks.py
  corehq/apps/es/aggregations.py
  corehq/apps/export/models/new.py
  corehq/apps/hqwebapp/tests/test_requirejs.py
Labels: product/invisible

#21722 build_requirejs: include_directories
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
Labels: product/invisible

#21627 Skip creating pg hashlib extension (on shards)
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/tests/test_sharding.py
  corehq/sql_accessors/migrations/0056_add_hashlib_functions.py
  corehq/sql_db/management/commands/print_database_shard_data.py
  corehq/sql_db/shard_data_management.py
  corehq/sql_db/tests/test_shard_management.py
Labels: product/invisible

#21738 update couchdbkit to 0.9.9
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#21740 Implement EWS broadcast feature flag in new reminders framework
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/views.py
  custom/ewsghana/forms.py
Labels: product/custom

#21741 Turn on new reminders for everyone
  corehq/messaging/util.py
Labels: product/all-users-all-environments

#21742 Handle when 'exception' exists in the response data and is None
  corehq/apps/sms/util.py
Labels: product/invisible

#21743 Add kiss event for requesting demo
  corehq/apps/registration/static/registration/js/register_new_user.js
Labels: product/invisible

#21751 Fix sms delay issues when machine timestamps differ slightly
  corehq/apps/sms/tasks.py
Labels: product/invisible

#21749 Add feature flag to allow copying messaging alerts
  corehq/apps/data_interfaces/models.py
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_list.js
  corehq/messaging/scheduling/templates/scheduling/conditional_alert_list.html
  corehq/messaging/scheduling/views.py
  corehq/toggles.py
Labels: product/feature-flag

#21456 30 day minimum subscription
  corehq/apps/accounting/models.py
  corehq/apps/accounting/static/accounting/js/confirm_plan.js
  corehq/apps/accounting/static/accounting/js/pricing_table.js
  corehq/apps/accounting/utils.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/domain/confirm_plan.html
  corehq/apps/domain/templates/domain/select_plan.html
  corehq/apps/domain/views.py
Labels: product/all-users-all-environments

#21568 Show module/form indices on source files page
  corehq/apps/app_manager/templates/app_manager/source_files.html
  corehq/apps/app_manager/views/download.py
  corehq/apps/app_manager/views/releases.py
Labels: product/feature-flag

#21571 Case List Explorer: Shameless self promotion
  corehq/apps/reports/standard/cases/basic.py
Labels: product/admin

#21745 show smart lang option only for app manager page
  corehq/apps/app_manager/templates/app_manager/languages.html
  corehq/apps/app_manager/templates/app_manager/partials/settings/supported_languages.html
Labels: product/all-users-all-environments

#21757 Test ICDS login doesn't 500
  custom/icds/tests/test_views.py
Labels: product/invisible

#21746 Search ancestor locations for OpenMRS UUID
  corehq/motech/openmrs/handler.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/tests/test_repeaters.py
Labels: product/feature-flag

#21761 Search comments on releases page
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_table.html
  corehq/apps/app_manager/views/releases.py
  corehq/apps/es/apps.py
  corehq/apps/es/case_search.py
  corehq/apps/es/es_query.py
Labels: product/all-users-all-environments

#21737 change tooltip for newborns with low birth weight
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/reports/maternal_child.py
  custom/icds_reports/reports/new_born_with_low_weight.py
  custom/icds_reports/static/icds_reports/js/spec/newborn_with_low_weight.directive.spec.js
  custom/icds_reports/static/js/directives/newborn_with_low_weight/newborn_with_low_weight.directive.js
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/tests/reports/test_maternal_child_data.py
  custom/icds_reports/tests/reports/test_new_born_with_low_weight.py
  custom/icds_reports/utils/help_texts.py
Labels: product/custom

#21752 Standardize javascript inheritance users
  corehq/apps/users/static/users/js/mobile_workers.ng.js
  corehq/apps/users/templates/users/mobile_workers.html
Labels: product/invisible

#21723 strucutre improvement
  corehq/apps/app_manager/app_translations/generators.py
  corehq/apps/app_manager/tests/test_generators.py
  corehq/apps/translations/views.py
  custom/icds/translations/integrations/transifex.py
Labels: product/custom

#21766 Search all nodes for comments
  corehq/apps/app_manager/xform.py
Labels: product/invisible

#21009 Better error handling
  corehq/apps/locations/tests/test_views.py
  corehq/apps/locations/views.py
Labels: Open for review: do not merge, product/all-users-all-environments

#21023 check for invalid column names
  corehq/apps/app_manager/models.py
  corehq/apps/case_importer/views.py
Labels: product/all-users-all-environments

#21762 [REMINDERS] Javascript standardize inheritance
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/static/reminders/js/reminders.broadcast.ko.js
  corehq/apps/reminders/static/reminders/js/reminders.keywords.ko.js
  corehq/apps/reminders/static/reminders/js/reminders.list.js
  corehq/apps/reminders/static/reminders/js/reminders.manage.js
  corehq/apps/reminders/static/reminders/js/reminders.progressbar.js
  corehq/apps/reminders/static/reminders/js/scheduled_reminders.js
  corehq/apps/reminders/templates/reminders/partial/complex_message_table.html
  corehq/apps/reminders/templates/reminders/partial/fire_time_field.html
  corehq/apps/reminders/templates/reminders/reminders_list.html
Labels: product/invisible

#21759 Update keyword functionality to use new framework
  corehq/apps/sms/handlers/keyword.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
Labels: product/invisible

#21772 spelling
  corehq/apps/domain/forms.py
Labels: product/all-users-all-environments

#21763 Upgrade select2 in hqcase app
  corehq/apps/hqcase/static/hqcase/js/explode_cases.js
  corehq/apps/hqcase/views.py
Labels: product/admin, product/invisible

#21765 Upgrade select2 in settings app
  corehq/apps/settings/static/settings/js/edit_my_account.js
  corehq/apps/settings/views.py
Labels: product/all-users-all-environments, product/invisible

#21764 UCR Conditional Aggregations
  corehq/apps/userreports/reports/factory.py
  corehq/apps/userreports/reports/specs.py
  corehq/apps/userreports/tests/test_report_aggregation.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/feature-flag

#21780 simplify WorkbookJSONReader - fix in python 3
  corehq/util/workbook_json/excel.py
Labels: product/invisible

#21782 remove unnecessary ord()
  corehq/ex-submodules/casexml/apps/phone/checksum.py
Labels: product/invisible

#21777 Add new gateway backend for new ICDS cluster
  corehq/apps/sms/migrations/0031_airteltclbackend.py
  corehq/apps/sms/tests/test_backends.py
  corehq/messaging/smsbackends/airtel_tcl/__init__.py
  corehq/messaging/smsbackends/airtel_tcl/exceptions.py
  corehq/messaging/smsbackends/airtel_tcl/forms.py
  corehq/messaging/smsbackends/airtel_tcl/models.py
  corehq/messaging/smsbackends/airtel_tcl/tests/__init__.py
  corehq/messaging/smsbackends/airtel_tcl/tests/test_airtel_tcl.py
  settings.py
Labels: product/custom

#21564 Filter Data by Deactivated Users
  corehq/apps/callcenter/views.py
  corehq/apps/es/users.py
  corehq/apps/export/forms.py
  corehq/apps/export/models/new.py
  corehq/apps/export/tests/test_export_forms.py
  corehq/apps/export/views.py
  corehq/apps/fixtures/models.py
  corehq/apps/reports/filters/api.py
  corehq/apps/reports/filters/case_list.py
  corehq/apps/reports/filters/urls.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/models.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/inspect.py
  corehq/apps/reports/util.py
  corehq/apps/users/models.py
  corehq/toggles.py
Labels: product/all-users-all-environments, product/feature-flag

#21352 Set location using correct method
  corehq/apps/registration/forms.py
  corehq/apps/users/models.py
Labels: product/invisible

#21578 DISHA API
  corehq/toggles.py
  custom/icds_reports/management/commands/build_disha_dumps.py
  custom/icds_reports/migrations/0060_disha_indicators.py
  custom/icds_reports/migrations/sql_templates/database_views/disha_indicators.sql
  custom/icds_reports/models/__init__.py
  custom/icds_reports/models/views.py
  custom/icds_reports/reports/disha.py
  custom/icds_reports/tasks.py
  custom/icds_reports/urls.py
  custom/icds_reports/views.py
Labels: product/custom

#21778 Kafka 1.4.3 upgrade
  corehq/apps/change_feed/consumer/feed.py
  corehq/apps/change_feed/management/commands/run_form_websocket_feed.py
  corehq/apps/change_feed/tests/test_kafka_change_feed.py
  corehq/apps/change_feed/tests/test_pillow.py
  corehq/apps/change_feed/tests/utils.py
  corehq/apps/change_feed/topics.py
  corehq/apps/commtrack/tests/test_stock_state.py
  corehq/apps/userreports/pillow.py
  corehq/ex-submodules/fluff/pillow.py
  corehq/ex-submodules/pillow_retry/tests/test_retry.py
  corehq/ex-submodules/pillowtop/checkpoints/manager.py
  corehq/ex-submodules/pillowtop/management/commands/add_kafka_partition.py
  corehq/ex-submodules/pillowtop/models.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  corehq/form_processor/tests/test_kafka.py
  corehq/pillows/app_submission_tracker.py
  corehq/pillows/application.py
  corehq/pillows/case.py
  corehq/pillows/case_search.py
  corehq/pillows/domain.py
  corehq/pillows/group.py
  corehq/pillows/groups_to_user.py
  corehq/pillows/ledger.py
  corehq/pillows/reportcase.py
  corehq/pillows/reportxform.py
  corehq/pillows/sms.py
  corehq/pillows/synclog.py
  corehq/pillows/user.py
  corehq/pillows/xform.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  testapps/test_pillowtop/utils.py
Labels: product/invisible

#21792 Downgrade select2 for edit scheduled reports
  corehq/apps/reports/static/reports/js/edit_scheduled_report.js
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#21785 Split locations/js/widgets_main based on select2 version
  .eslintrc.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/locations/forms.py
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/static/locations/js/widgets_main_v3.js
  corehq/apps/locations/static/locations/js/widgets_main_v4.js
  corehq/apps/locations/templates/locations/manage/partials/autocomplete_select_widget_v3.html
  corehq/apps/locations/templates/locations/manage/partials/autocomplete_select_widget_v4.html
  corehq/apps/locations/templates/locations/manage/partials/drilldown_location_widget.html
  corehq/apps/locations/templates/locations/manage/partials/drilldown_location_widget_v3.html
  corehq/apps/locations/templates/locations/manage/partials/drilldown_location_widget_v4.html
  corehq/apps/registration/forms.py
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/templates/reminders/broadcast.html
  corehq/apps/users/forms.py
  corehq/apps/users/templates/users/base_template.html
  corehq/messaging/scheduling/static/scheduling/js/create_schedule_main.js
  corehq/motech/repeaters/forms.py
  corehq/motech/repeaters/static/repeaters/js/add_form_repeater.js
  corehq/motech/repeaters/views/repeaters.py
  custom/ewsghana/forms.py
  custom/ewsghana/templates/ewsghana/user_extension.html
Labels: product/all-users-all-environments

#21660 base all growth monitoring indicators on form tables
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/fixtures/child_monthly.csv
  custom/icds_reports/tests/fixtures/gm_form.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/outputs/child_health_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/outputs/child_health_monthly_2017-05-01_sorted.csv
  custom/icds_reports/tests/reports/test_maternal_child_data.py
  custom/icds_reports/tests/reports/test_prevalence_of_severe.py
  custom/icds_reports/tests/reports/test_prevalence_of_stunting.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/tests/test_fact_sheet_report.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/aggregation.py
Labels: product/custom

#21793 Some SMS Gateway Backend Updates
  corehq/apps/sms/admin.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tests/test_backends.py
  corehq/messaging/smsbackends/grapevine/models.py
  corehq/messaging/smsbackends/megamobile/urls.py
  corehq/messaging/smsbackends/megamobile/views.py
  corehq/messaging/smsbackends/sislog/urls.py
  corehq/messaging/smsbackends/sislog/views.py
  corehq/messaging/smsbackends/telerivet/forms.py
  corehq/messaging/smsbackends/telerivet/models.py
  corehq/messaging/smsbackends/tropo/tests/test_log_call.py
  corehq/messaging/smsbackends/tropo/urls.py
  corehq/messaging/smsbackends/tropo/views.py
  corehq/messaging/smsbackends/unicel/models.py
  corehq/messaging/smsbackends/unicel/tests/test_create_from_request.py
  corehq/messaging/smsbackends/unicel/urls.py
  corehq/messaging/smsbackends/unicel/views.py
  corehq/messaging/smsbackends/yo/urls.py
  corehq/messaging/smsbackends/yo/views.py
  docs/messaging/sms_backends.rst
  urls.py
Labels: product/invisible

#21796 Add check for location id
  corehq/apps/users/models.py
Labels: product/all-users-all-environments

#21801 remove unnecessary if/else
  corehq/util/workbook_json/excel.py
Labels: product/invisible

#21807 update jsonobject to 0.9.4
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#21809 replace six.binary_type with bytes
  corehq/apps/accounting/tasks.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/tests/util.py
  corehq/apps/app_manager/xform.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/sms/views.py
  corehq/apps/userreports/sql/columns.py
  corehq/blobs/mixin.py
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore_v3.py
  corehq/ex-submodules/couchexport/writers.py
  corehq/form_processor/models.py
  corehq/util/view_utils.py
  settingshelper.py
Labels: product/invisible

#21813 avoid pickling querset
  custom/icds_reports/views.py
Labels: product/feature-flag

#21773 report builder minor fixes
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/static/userreports/js/report_config.js
  corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
  corehq/apps/userreports/views.py
  corehq/apps/users/cases.py
  corehq/apps/users/tests/case_utils.py
  corehq/apps/users/util.py
Labels: product/all-users-all-environments

#21696 prevent error message from hiding
  corehq/apps/app_manager/static/app_manager/js/supported_languages.js
Labels: product/all-users-all-environments

#21786 capture the specific service that failed in datadog
  corehq/apps/hqwebapp/views.py
Labels: product/invisible

#21810 Add ccs_record and child_health to async UCR
  custom/icds_reports/ucr/data_sources/ccs_record_cases.json
  custom/icds_reports/ucr/data_sources/child_health_cases.json
Labels: product/custom

#21808 Downgrade select2 for Project Settings > Basic
  corehq/apps/domain/forms.py
  corehq/apps/domain/static/domain/js/info_basic.js
  corehq/apps/domain/views.py
Labels: product/invisible

#21797 select2 upgrade: locations
  corehq/apps/hqwebapp/static/hqwebapp/js/select_2_ajax_widget_v4.js
  corehq/apps/hqwebapp/static/hqwebapp/js/widgets.js
  corehq/apps/hqwebapp/static/hqwebapp/js/widgets_v4.js
  corehq/apps/locations/forms.py
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/static/locations/js/location_types.js
  corehq/apps/locations/static/locations/js/widgets_main_v4.js
  corehq/apps/locations/views.py
Labels: product/invisible

#21776 Fix migrate_metadata blob migration
  corehq/blobs/migrate_metadata.py
Labels: product/invisible

#21756 RequireJS optimization strategy: requirejs_main modules, not js dirs
  corehq/apps/app_manager/management/commands/audit_app_profile_properties.py
  corehq/apps/app_manager/management/commands/migrate_all_apps_to_cmitfb.py
  corehq/apps/app_manager/management/commands/migrate_app_to_cmitfb.py
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/static/hqwebapp/js/base_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/common.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/static/hqwebapp/js/main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/mobile_experience_warning.js
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/yaml/requirejs.yaml
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/locations/static/locations/js/import.js
  corehq/apps/sms/static/sms/js/settings.js
Labels: product/invisible

#21551 Ce/warehouse scale
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/sql_db/util.py
  corehq/warehouse/const.py
  corehq/warehouse/dbaccessors.py
  corehq/warehouse/transforms/sql/user_location_dim.sql
Labels: product/invisible

#21269 Requirejs: Project Settings > Subscription
  corehq/apps/accounting/static/accounting/js/credits.js
  corehq/apps/accounting/static/accounting/js/lib/stripe.js
  corehq/apps/accounting/static/accounting/js/payment_method_handler.js
  corehq/apps/accounting/static/accounting/js/stripe_card_manager.js
  corehq/apps/domain/static/domain/js/billing_statements.js
  corehq/apps/domain/static/domain/js/confirm_billing_info.js
  corehq/apps/domain/static/domain/js/current_subscription.js
  corehq/apps/domain/static/domain/js/internal_subscription_management.js
  corehq/apps/domain/static/domain/js/update_billing_contact_info.js
  corehq/apps/domain/templates/domain/billing_statements.html
  corehq/apps/domain/templates/domain/current_subscription.html
  corehq/apps/domain/templates/domain/internal_subscription_management.html
  corehq/apps/domain/templates/domain/update_billing_contact_info.html
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_config.js
Labels: QA Passed, product/invisible

#21812 Requirejs Migration: web user & roles
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/static/users/js/web_users.js
  corehq/apps/users/templates/users/web_users.html
Labels: product/all-users-all-environments

#21821 Safe kafka changes
  corehq/apps/change_feed/connection.py
  corehq/apps/change_feed/consumer/feed.py
  corehq/apps/change_feed/management/commands/create_kafka_topics.py
  corehq/apps/change_feed/pillow.py
  corehq/apps/change_feed/producer.py
  corehq/apps/change_feed/tests/test_kafka_change_feed.py
  corehq/apps/change_feed/tests/test_pillow.py
  corehq/apps/change_feed/tests/utils.py
  corehq/apps/change_feed/topics.py
  corehq/apps/hqadmin/service_checks.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/pillow_retry/tests/test_retry.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  settings.py
Labels: product/invisible

#21818 Remove old rule models
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/management/commands/migrate_rules.py
  corehq/apps/data_interfaces/migrations/0018_check_for_rule_migration.py
  corehq/apps/data_interfaces/migrations/0019_remove_old_rule_models.py
  corehq/apps/data_interfaces/migrations/0020_make_migrated_nullable.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/static/data_interfaces/js/add_automatic_update_rule.js
  corehq/apps/data_interfaces/templates/data_interfaces/add_automatic_update_rule.html
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/data_interfaces/tests/test_case_rule_migration.py
  corehq/apps/data_interfaces/tests/util.py
  corehq/apps/data_interfaces/urls.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/apps/hqadmin/management/commands/clone_domain.py
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/messaging/management/commands/import_conditional_alerts.py
  corehq/messaging/scheduling/views.py
Labels: product/invisible

#21819 Fix 500 on invite user page
  corehq/apps/registration/forms.py
Labels: product/all-users-all-environments

#21826 Get latest offsets from the consumer instead of utility
  corehq/apps/change_feed/consumer/feed.py
Labels: product/invisible

#21542 Allow MOTECH to create an OpenMRS patient if a case is not found
  corehq/motech/openmrs/README.md
  corehq/motech/openmrs/finders.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/tasks.py
  corehq/motech/openmrs/tests/test_finders.py
  corehq/motech/openmrs/tests/test_repeaters.py
Labels: product/feature-flag

#21791 Added Phone number to sql views and exports
  custom/icds_reports/migrations/0061_added_phone_number_to_views.py
  custom/icds_reports/migrations/sql_templates/database_views/agg_awc_daily.sql
  custom/icds_reports/migrations/sql_templates/database_views/agg_ccs_record_monthly.sql
  custom/icds_reports/migrations/sql_templates/database_views/agg_child_health_monthly.sql
  custom/icds_reports/migrations/sql_templates/database_views/child_health_monthly.sql
  custom/icds_reports/migrations/sql_templates/database_views/daily_attendance.sql
  custom/icds_reports/sqldata/exports/awc_infrastructure.py
  custom/icds_reports/sqldata/exports/beneficiary.py
  custom/icds_reports/sqldata/exports/children.py
  custom/icds_reports/sqldata/exports/demographics.py
  custom/icds_reports/sqldata/exports/pregnant_women.py
  custom/icds_reports/sqldata/exports/system_usage.py
  custom/icds_reports/tests/test_export_data.py
Labels: product/custom

#21823 Minor select2 upgrade in reports
  corehq/apps/hqadmin/templates/hqadmin/faceted_report.html
  corehq/apps/reports/templates/reports/partials/filters_js.html
  corehq/apps/reports/templates/reports/standard/base_template.html
Labels: product/invisible

#21822 ewsghana: stop including legacy select2 script tags
  custom/ewsghana/templates/ewsghana/base_template.html
  custom/ewsghana/templates/ewsghana/dashboard_print_report.html
  custom/ewsghana/templates/ewsghana/facility_page_print_report.html
  custom/ewsghana/templates/ewsghana/reporting_rates_print_report.html
  custom/ewsghana/templates/ewsghana/stock_status_print_report.html
Labels: product/invisible

#21824 Minor select2 upgrade in exports
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/hqwebapp/widgets.py
Labels: product/invisible

#21825 Remove select2-3.4.5-legacy
  bower.json
Labels: product/invisible

#21820 create view migration
  custom/icds_reports/migrations/0062_disha_indicators_create_view.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/__init__.py
Labels: product/feature-flag

#21827 Unrevert conditional aggregations
  corehq/apps/userreports/reports/factory.py
  corehq/apps/userreports/reports/specs.py
  corehq/apps/userreports/tests/test_report_aggregation.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#21834 async table
  corehq/apps/callcenter/data_sources/call_center_case_actions.json
Labels: product/invisible

#21832 Remove old reminders framework code
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/accounting/utils.py
  corehq/apps/dashboard/templates/dashboard/base.html
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
  corehq/apps/dump_reload/couch/dump.py
  corehq/apps/notifications/ui_notify.py
  corehq/apps/reminders/event_handlers.py
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/management/commands/find_ivr_usage.py
  corehq/apps/reminders/management/commands/find_reminder_usage.py
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/apps/reminders/management/commands/remove_dup_reminders.py
  corehq/apps/reminders/management/commands/run_reminder_queue.py
  corehq/apps/reminders/models.py
  corehq/apps/reminders/static/reminders/js/broadcasts_list.js
  corehq/apps/reminders/static/reminders/js/reminders.broadcast.ko.js
  corehq/apps/reminders/static/reminders/js/reminders.js
  corehq/apps/reminders/static/reminders/js/reminders.list.js
  corehq/apps/reminders/static/reminders/js/reminders.manage.js
  corehq/apps/reminders/static/reminders/js/reminders.progressbar.js
  corehq/apps/reminders/static/reminders/js/scheduled_reminders.js
  corehq/apps/reminders/tasks.py
  corehq/apps/reminders/templates/reminders/broadcast.html
  corehq/apps/reminders/templates/reminders/broadcasts_list.html
  corehq/apps/reminders/templates/reminders/manage_scheduled_reminder.html
  corehq/apps/reminders/templates/reminders/partial/complex_message_table.html
  corehq/apps/reminders/templates/reminders/partial/email_trial_message_modal.html
  corehq/apps/reminders/templates/reminders/partial/fire_time_field.html
  corehq/apps/reminders/templates/reminders/partial/scheduled_reminders.html
  corehq/apps/reminders/templates/reminders/partial/time_picker.html
  corehq/apps/reminders/templates/reminders/reminders_base.html
  corehq/apps/reminders/templates/reminders/reminders_list.html
  corehq/apps/reminders/tests/test_cache.py
  corehq/apps/reminders/tests/test_lookup.py
  corehq/apps/reminders/tests/test_message_formatting.py
  corehq/apps/reminders/tests/test_recipient.py
  corehq/apps/reminders/tests/test_responsiveness.py
  corehq/apps/reminders/tests/test_send_reminders.py
  corehq/apps/reminders/tests/utils.py
  corehq/apps/reminders/urls.py
  corehq/apps/reminders/util.py
  corehq/apps/reminders/views.py
  corehq/apps/reports/standard/sms.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/models.py
  corehq/apps/sms/views.py
  corehq/apps/users/tasks.py
  corehq/messaging/management/commands/import_conditional_alerts.py
  corehq/messaging/scheduling/util.py
  corehq/messaging/scheduling/views.py
  corehq/messaging/tasks.py
  corehq/messaging/util.py
  corehq/tabs/tabclasses.py
  corehq/util/test_utils.py
  custom/ewsghana/forms.py
Labels: product/invisible

#21831 app_reinstall_and_update requires app version
  corehq/apps/ota/admin.py
Labels: product/invisible

#21839 add management command to benchmark build times for a list of apps
  corehq/apps/app_manager/management/commands/benchmark_build_times.py
Labels: product/invisible

#21843 PR feedback to make benchmark_build_times easier to use
  corehq/apps/app_manager/management/commands/benchmark_build_times.py
Labels: product/invisible

#21844 refactor direct_ccz to separate out request from functionality
  corehq/apps/app_manager/management/commands/benchmark_direct_ccz.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/views/cli.py
Labels: product/invisible

#21830 Mk 21506 followup followup
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/views/releases.py
Labels: product/invisible

#21815 PoC report builder directly against raw data sources
  corehq/apps/app_manager/fields.py
  corehq/apps/userreports/app_manager/data_source_meta.py
  corehq/apps/userreports/const.py
  corehq/apps/userreports/datatypes.py
  corehq/apps/userreports/dbaccessors.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/builder/columns.py
  corehq/apps/userreports/reports/builder/const.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/reports/builder/sources.py
  corehq/apps/userreports/static/userreports/js/data_source_select.js
  corehq/apps/userreports/static/userreports/js/report_config.js
  corehq/apps/userreports/tests/test_data_source_types.py
  corehq/apps/userreports/tests/test_report_builder.py
  corehq/apps/userreports/ui/forms.py
  corehq/apps/userreports/views.py
  corehq/toggles.py
Labels: product/feature-flag

#21842 Extract method in xform.get_questions
  corehq/apps/app_manager/xform.py
Labels: product/invisible

#21828 Data > Find Data by ID page
  corehq/apps/data_interfaces/static/data_interfaces/js/find_by_id.js
  corehq/apps/data_interfaces/templates/data_interfaces/find_by_id.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/find_by_id_form.html
  corehq/apps/data_interfaces/urls.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/hqwebapp/views.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/all-users-all-environments

#21840 Fix javascript errors on New Structured Keyword page
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/templates/reminders/keyword.html
Labels: product/all-users-all-environments

#21838 Feature flag ui: don't allow saving blanks
  corehq/apps/toggle_ui/static/toggle_ui/js/edit-flag.js
Labels: product/admin

#21845 add management command to benchmark get_direct_ccz
  corehq/apps/app_manager/management/commands/benchmark_direct_ccz.py
Labels: product/invisible

#21848 change kafka logging
  settings.py
Labels: product/invisible

#21846 add profiling option to benchmark_build_times
  corehq/apps/app_manager/management/commands/benchmark_build_times.py
Labels: product/invisible

#11096 ILS: case 222987
  custom/ilsgateway/tanzania/handlers/la.py
Labels: No lint errors

#21849 Release appcues template app test
  corehq/apps/accounting/utils.py
  corehq/apps/analytics/ab_tests.py
  corehq/apps/app_manager/_design/views/applications_brief/map.js
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/audio/data/convulsions_counseling_message-lewuhw.mp3
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/audio/data/convulsions_counseling_message-y2u53c.mp3
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/audio/data/copy-1-of-play_your_counseling_message_now-bg9j5n.mp3
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/audio/data/copy-1-of-play_your_counseling_message_now-d29nup.mp3
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/audio/data/danger_signs-Headache-dlibab.mp3
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/audio/data/danger_signs-Headache-oyknqp.mp3
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/audio/data/play_your_counseling_message_now-emp54w.mp3
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/audio/data/play_your_counseling_message_now-tefgvo.mp3
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/audio/data/stopped_moving_counseling_message-nvg14g.mp3
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/audio/data/stopped_moving_counseling_message-wjdtac.mp3
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/image/module0_form0_en.png
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/image/module1_case_list_form_en.png
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/image/module1_en.png
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/image/module1_form0_en.png
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/image/module1_form2_en.png
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/commcare/image/module2_form0_en.png
  corehq/apps/app_manager/static/app_manager/template_apps/appcues/multimedia.json
  corehq/apps/app_manager/views/apps.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/views.py
  corehq/apps/registration/views.py
  corehq/tabs/tabclasses.py
Labels: product/prod-india-all-users

#21853 import settings
  custom/icds_reports/views.py
Labels: product/invisible

#21841 Remove SimpleProducer
  corehq/apps/change_feed/connection.py
  corehq/apps/change_feed/pillow.py
  corehq/apps/change_feed/producer.py
  corehq/apps/change_feed/tests/test_kafka_change_feed.py
  corehq/apps/change_feed/tests/test_pillow.py
  corehq/apps/change_feed/topics.py
  corehq/apps/hqadmin/service_checks.py
  corehq/apps/userreports/tests/test_location_data_source.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/ex-submodules/pillow_retry/tests/test_retry.py
Labels: product/invisible

#21836 Remove old incoming sms endpoints
  corehq/apps/sms/views.py
  corehq/messaging/smsbackends/sislog/urls.py
  corehq/messaging/smsbackends/tropo/urls.py
  corehq/messaging/smsbackends/tropo/views.py
  corehq/messaging/smsbackends/unicel/urls.py
  corehq/messaging/smsbackends/yo/urls.py
  urls.py
Labels: product/invisible

#21847 tweak sentry setup for celery
  corehq/util/sentry.py
  settingshelper.py
Labels: product/invisible

#21854 fix handling HTTPError in index_design_docs
  corehq/ex-submodules/dimagi/utils/couch/sync_docs.py
Labels: product/invisible

#21851 Backlog items
  corehq/apps/commtrack/sms.py
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/sms/admin.py
  corehq/apps/sms/api.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/migrations/0032_couch_id_blank.py
  corehq/apps/sms/models.py
  corehq/apps/sms/templates/sms/gateway_list.html
  corehq/apps/sms/views.py
  corehq/apps/smsforms/tasks.py
  corehq/apps/smsforms/tests/test_sql_session.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/scheduling_partitioned/migrations/0006_unique_indexes.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/scheduling/scheduling_partitioned/tests/test_dbaccessors_non_partitioned.py
  corehq/messaging/scheduling/scheduling_partitioned/tests/test_dbaccessors_partitioned.py
  corehq/messaging/scheduling/tasks.py
  corehq/toggles.py
  dev_settings.py
  settings.py
  testsettings.py
Labels: product/invisible

#21856 Put update location over sms behind feature flag
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/tests/update_location_keyword_test.py
  corehq/toggles.py
Labels: product/invisible

#21858 Bump sqlagg to fix intermittent failure
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#21860 write a temp file and read it back
  corehq/util/workbook_json/excel.py
Labels: product/invisible

#21861 Remove soft assert
  corehq/apps/sms/views.py
Labels: product/invisible

#21862 Stop looking up language code for users based on location
  custom/icds/messaging/custom_content.py
  custom/icds/tests/test_custom_content.py
Labels: product/custom

#21859 Make aggregation columns siblings
  corehq/apps/userreports/reports/specs.py
Labels: product/invisible

#21833 Icds reports tooltip for newborns
  custom/icds_reports/messages.py
  custom/icds_reports/reports/adhaar.py
  custom/icds_reports/reports/adolescent_girls.py
  custom/icds_reports/reports/adult_weight_scale.py
  custom/icds_reports/reports/awc_infrastracture.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/reports/awcs_covered.py
  custom/icds_reports/reports/cas_reach_data.py
  custom/icds_reports/reports/children_initiated_data.py
  custom/icds_reports/reports/demographics_data.py
  custom/icds_reports/reports/early_initiation_breastfeeding.py
  custom/icds_reports/reports/enrolled_children.py
  custom/icds_reports/reports/enrolled_women.py
  custom/icds_reports/reports/exclusive_breastfeeding.py
  custom/icds_reports/reports/functional_toilet.py
  custom/icds_reports/reports/infants_weight_scale.py
  custom/icds_reports/reports/institutional_deliveries_sector.py
  custom/icds_reports/reports/lactating_enrolled_women.py
  custom/icds_reports/reports/maternal_child.py
  custom/icds_reports/reports/medicine_kit.py
  custom/icds_reports/reports/new_born_with_low_weight.py
  custom/icds_reports/reports/prevalence_of_severe.py
  custom/icds_reports/reports/prevalence_of_undernutrition.py
  custom/icds_reports/tests/reports/test_adhaar.py
  custom/icds_reports/tests/reports/test_adult_weight_scale.py
  custom/icds_reports/tests/reports/test_awc_infrastructure.py
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/tests/reports/test_awcs_covered.py
  custom/icds_reports/tests/reports/test_children_initiated.py
  custom/icds_reports/tests/reports/test_clean_water.py
  custom/icds_reports/tests/reports/test_demographics.py
  custom/icds_reports/tests/reports/test_early_initiation_breastfeeding.py
  custom/icds_reports/tests/reports/test_enrolled_children.py
  custom/icds_reports/tests/reports/test_enrolled_women.py
  custom/icds_reports/tests/reports/test_exclusive_breastfeeding.py
  custom/icds_reports/tests/reports/test_functional_toilet.py
  custom/icds_reports/tests/reports/test_icds_cas_reach.py
  custom/icds_reports/tests/reports/test_infants_weight_scale.py
  custom/icds_reports/tests/reports/test_lactating_enrolled_women.py
  custom/icds_reports/tests/reports/test_maternal_child_data.py
  custom/icds_reports/tests/reports/test_medicine_kit.py
  custom/icds_reports/tests/reports/test_new_born_with_low_weight.py
  custom/icds_reports/tests/reports/test_prevalence_of_severe.py
  custom/icds_reports/tests/reports/test_prevalence_of_undernutrition.py
  custom/icds_reports/utils/help_texts.py
Labels: product/custom

#21868 use correctly named logger
  settings.py
Labels: product/invisible

#21863 Add required questions to downgrading subscription modal
  corehq/apps/accounting/static/accounting/js/confirm_plan.js
  corehq/apps/domain/forms.py
  corehq/apps/domain/static/domain/js/confirm_billing_info.js
  corehq/apps/domain/templates/domain/confirm_billing_info.html
  corehq/apps/domain/templates/domain/confirm_plan.html
  corehq/apps/domain/views.py
Labels: product/all-users-all-environments

#21837 use one consumer for metric gathering
  corehq/ex-submodules/pillowtop/utils.py
Labels: product/invisible

#21669 migrating corehq/sms pages requirejs
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap-multi-typeahead.js
  corehq/apps/sms/static/sms/js/add_forwarding_rule.js
  corehq/apps/sms/static/sms/js/add_gateway.js
  corehq/apps/sms/static/sms/js/add_gateway_form_handler.js
  corehq/apps/sms/static/sms/js/backend_map.js
  corehq/apps/sms/static/sms/js/compose.js
  corehq/apps/sms/templates/sms/add_forwarding_rule.html
  corehq/apps/sms/templates/sms/add_gateway.html
  corehq/apps/sms/templates/sms/backend_map.html
  corehq/apps/sms/templates/sms/compose.html
Labels: awaiting QA, product/invisible

#21870 Turn off appcues introduction
  corehq/apps/registration/views.py
Labels: product/prod-india-all-users

#21872 Include LinkedApplication in xforms_index
  corehq/apps/app_manager/_design/views/xforms_index/map.js
Labels: product/invisible, reindex/migration

#21871 [ICDS] Add UCR report config that aggregates by age range
  corehq/apps/userreports/tests/test_report_aggregation.py
  custom/icds_reports/ucr/reports/mobile_mpr_3_children_registered.json
Labels: product/custom

#21874 use similar pattern as iter_form_ids_by_xmlns to fetch case ids
  corehq/form_processor/backends/couch/dbaccessors.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/document_stores.py
  corehq/form_processor/interfaces/dbaccessors.py
Labels: product/invisible

#21875 track multi key ops in Redis
  corehq/ex-submodules/dimagi/utils/couch/cache/cache_core/lib.py
Labels: Open for review: do not merge, product/invisible

#21880 Allow filtering ES forms by case_id
  corehq/apps/es/forms.py
Labels: product/invisible

#21879 Show user if there are no sheets
  corehq/apps/case_importer/util.py
Labels: product/invisible

#21881 Check row.data for length, not row
  corehq/ex-submodules/couchexport/tests/test_writers.py
  corehq/ex-submodules/couchexport/writers.py
Labels: product/invisible

#21887 "There is no try; there is do or not do." -- Yoda
  corehq/apps/domain/views.py
Labels: product/invisible

#21876 don't re-publish changes from duplicate forms
  corehq/form_processor/backends/sql/processor.py
  corehq/form_processor/tests/test_kafka.py
Labels: product/invisible

#21891 Update wasting indicator
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/reports/test_maternal_child_data.py
  custom/icds_reports/tests/reports/test_prevalence_of_severe.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/tests/test_fact_sheet_report.py
  custom/icds_reports/utils/aggregation.py
Labels: product/custom

#21895 Fix cursor on project settings menu
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/navs.less
Labels: product/all-users-all-environments

#21894 Summit delight session
  corehq/apps/commtrack/forms.py
  corehq/apps/groups/templates/groups/group_members.html
  corehq/apps/locations/static/locations/js/location_types.js
  corehq/apps/locations/templates/locations/location_types.html
  corehq/apps/locations/templates/locations/manage/locations.html
  corehq/apps/locations/templates/locations/manage/partials/bulk_upload.html
  corehq/apps/products/templates/products/manage/products.html
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/templates/reminders/keyword_list.html
  corehq/apps/reports/templates/reports/partials/scheduled_reports_table.html
  corehq/apps/reports/templates/reports/reports_home.html
  corehq/apps/sms/forms.py
  corehq/apps/sms/templates/sms/manage_registration_invitations.html
  corehq/apps/userreports/templates/userreports/userreports_base.html
Labels: product/all-users-all-environments

#21873 Add heena's email to the dashboard emails
  custom/icds_reports/tasks.py
Labels: product/custom

#21604 Migration-RequireJs: Conditional alert and messaging dashboard pages
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_config.js
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_list.js
  corehq/messaging/scheduling/static/scheduling/js/dashboard.js
  corehq/messaging/scheduling/templates/scheduling/conditional_alert_list.html
  corehq/messaging/scheduling/templates/scheduling/dashboard.html
Labels: product/invisible

#21877 rate limit kafka errors to sentry
  corehq/util/sentry.py
Labels: product/invisible

#21890 stop querying for alert on every 500
  corehq/apps/hqwebapp/models.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
Labels: product/invisible

#21901 no space in blob name
  custom/icds_reports/reports/disha.py
Labels: product/invisible

#21897 Update page title to "Releases" not "Publish"
  corehq/apps/app_manager/static/app_manager/js/releases/app_view_release_manager.js
Labels: product/all-users-all-environments

#21893 Fix app links on SMS invitations page
  corehq/apps/hqwebapp/doc_info.py
Labels: product/all-users-all-environments

#21898 Allow overriding commcare UI translations on linked apps
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/languages.html
  corehq/apps/app_manager/templates/app_manager/partials/settings/app_settings.html
  corehq/apps/app_manager/views/translations.py
  corehq/apps/app_manager/views/utils.py
Labels: product/feature-flag

#21900 catch es error
  corehq/apps/app_manager/views/apps.py
Labels: product/invisible

#21907 Kill old edit forms
  corehq/apps/cloudcare/static/cloudcare/js/formplayer-inline.js
  corehq/apps/cloudcare/templates/cloudcare/includes/formplayer-inline.html
  corehq/apps/reports/static/reports/js/edit_submission.js
  corehq/apps/reports/templates/reports/form/edit_submission.html
  corehq/apps/reports/templates/reports/form/partials/form_breadcrumbs.html
  corehq/apps/reports/templates/reports/partials/data_corrections_modal.html
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#21906 wrap dict.keys() with list()
  corehq/ex-submodules/pillowtop/utils.py
Labels: product/invisible

#21864 Fix blob metadata migration
  corehq/blobs/migrate_metadata.py
  corehq/blobs/migrations/0003_big_content.py
  corehq/blobs/models.py
  corehq/blobs/sql_templates/big_content_length.sql
  corehq/sql_db/migrations.py
Labels: product/invisible

#21682 Update the aggregated aww data based on last 6 month historical data
  custom/icds_reports/migrations/sql_templates/database_functions/aggregated_awc_data_weekly.sql
  custom/icds_reports/tasks.py
Labels: product/custom

#21814 Migration: Requirejs- Remove globals from and Encapsulate media reference controller
  corehq/apps/app_manager/static/app_manager/js/details/case_detail_print.js
  corehq/apps/app_manager/static/app_manager/js/settings/app_logos.js
  corehq/apps/hqmedia/static/hqmedia/js/hqmedia.reference_controller.js
  corehq/apps/hqmedia/static/hqmedia/js/references_main.js
Labels: awaiting QA, product/invisible

#21892 on server error return plain 500 for phone endpoints
  corehq/apps/hqwebapp/views.py
Labels: product/invisible

#21905 modernize - use new range()
  corehq/ex-submodules/couchexport/tests/test_writers.py
Labels: product/invisible

#21909 Trim query before searching
  corehq/apps/data_interfaces/static/data_interfaces/js/find_by_id.js
Labels: product/feature-flag

#21915 Make the dot-menu allow for 7 inline dots
  custom/icds_reports/static/css/icds_dashboard.css
Labels: product/custom

#21911 Add ability to override logos for linked applications
  corehq/apps/app_manager/commcare_settings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/json/commcare-profile-settings.yaml
  corehq/apps/app_manager/templates/app_manager/partials/settings/app_settings.html
  corehq/apps/app_manager/views/utils.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/hqmedia/views.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
Labels: product/feature-flag

#21918 Restrict conditional aggs to static report configs
  corehq/apps/userreports/reports/specs.py
Labels: product/custom

#21878 Change the locations + groups filters from OR to AND (feature flag)
  corehq/apps/export/filters.py
  corehq/apps/export/forms.py
  corehq/apps/export/tests/test_export_forms.py
  corehq/apps/reports/filters/users.py
  corehq/toggles.py
Labels: product/feature-flag

#21884 Ignore select with lookup table choices
  corehq/apps/app_manager/xform.py
  corehq/apps/userreports/reports/builder/forms.py
Labels: product/all-users-all-environments
