Repository dimagi/commcare-hq, pull requests merged in 2018-07, with the labels that each got.

#21077 The test I forgot to push yesterday
  corehq/motech/openmrs/tests/test_repeaters.py
Labels: product/invisible

#21074 Speed up ICDS releases page
  corehq/apps/app_manager/dbaccessors.py
Labels: product/feature-flag

#21049 Fix resaving of missing cases and forms
  corehq/apps/data_pipeline_audit/dbacessors.py
  corehq/apps/es/management/commands/resave_failed_forms_and_cases.py
Labels: product/invisible

#21063 Fix calling popup function by providing correct values per column
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
Labels: product/custom

#21061 Ensure month filter values are integers
  custom/icds_reports/static/js/directives/month-filter/month-filter.directive.js
Labels: product/custom

#21089 Django 1.11.14
  requirements/requirements.txt
Labels: product/invisible

#21087 Data cleaning forms: fix error on question ids with hyphens
  corehq/form_processor/interfaces/processor.py
  corehq/form_processor/tests/test_basics.py
Labels: product/all-users-all-environments

#21088 For form settings, gather only case properties that are valid for sav…
  corehq/apps/app_manager/app_schemas/case_properties.py
Labels: product/all-users-all-environments

#21090 Intrahealth Update UCR
  custom/intrahealth/ucr/data_sources/commande_combined.json
  custom/intrahealth/ucr/data_sources/operateur_combined.json
Labels: product/custom

#21097 Couple of ICDS fixes
  custom/icds/management/commands/find_data_not_in_es.py
  custom/icds_reports/utils/aggregation.py
Labels: product/invisible

#21093 CodeMirror -> Ace
  corehq/motech/openmrs/templates/openmrs/edit_config.html
Labels: product/invisible

#21048 Change source for individual Beneficiary Child Page to ChildHealthMon…
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/views.py
Labels: product/custom

#21096 Allow data cleaning of unrecognized data
  corehq/apps/reports/formdetails/readable.py
Labels: product/all-users-all-environments

#21099 ICDS Reports | Beneficiary list height info fix
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#21094 Kissmetrics and Hubspot analytics improvements on login
  corehq/apps/analytics/tasks.py
  corehq/apps/registration/forms.py
  corehq/apps/registration/templates/registration/partials/register_new_user/submit_errors.html
  corehq/apps/registration/views.py
Labels: product/prod-india-all-users

#21018 ICDS Reports | Limit AWC Infrastucture indicators denominator to last…
  custom/icds_reports/management/commands/sql_scripts/update_agg_awc_num_awc_infra_last_update.sql
  custom/icds_reports/management/commands/update_agg_awc_num_awc_infra_last_update.py
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_awc_data.sql
Labels: product/custom

#21098 Update meta field value
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/xform.py
Labels: product/invisible

#21091 Replace jQuery cachedAjax plugin in repo with one from bower
  bower.json
  corehq/apps/hqwebapp/static/hqwebapp/js/lib/jquery.cachedAjax.js
  corehq/apps/reports/static/reports/js/case_details.js
  corehq/apps/reports/templates/reports/reportdata/case_data.html
Labels: product/invisible

#21104 Remove export migration commands
  corehq/apps/export/README.md
  corehq/apps/export/const.py
  corehq/apps/export/exceptions.py
  corehq/apps/export/management/commands/migrate_exports.py
  corehq/apps/export/management/commands/migrate_exports_for_domain.py
  corehq/apps/export/management/commands/revert_migrate_exports_for_domain.py
  corehq/apps/export/tests/data/saved_export_schemas/basic.json
  corehq/apps/export/tests/data/saved_export_schemas/basic_label.json
  corehq/apps/export/tests/data/saved_export_schemas/basic_with_text_nodes.json
  corehq/apps/export/tests/data/saved_export_schemas/case.json
  corehq/apps/export/tests/data/saved_export_schemas/case_history.json
  corehq/apps/export/tests/data/saved_export_schemas/conversion_ordering.json
  corehq/apps/export/tests/data/saved_export_schemas/deid_transforms.json
  corehq/apps/export/tests/data/saved_export_schemas/missing_app_id.json
  corehq/apps/export/tests/data/saved_export_schemas/parent_case.json
  corehq/apps/export/tests/data/saved_export_schemas/remote_app.json
  corehq/apps/export/tests/data/saved_export_schemas/remote_app_repeats.json
  corehq/apps/export/tests/data/saved_export_schemas/repeat.json
  corehq/apps/export/tests/data/saved_export_schemas/repeat_nested.json
  corehq/apps/export/tests/data/saved_export_schemas/single_node_repeat.json
  corehq/apps/export/tests/data/saved_export_schemas/skippable_properties.json
  corehq/apps/export/tests/data/saved_export_schemas/stock.json
  corehq/apps/export/tests/data/saved_export_schemas/stock_form_export.json
  corehq/apps/export/tests/data/saved_export_schemas/stock_form_export_repeat.json
  corehq/apps/export/tests/data/saved_export_schemas/system_properties.json
  corehq/apps/export/tests/test_export_conversion.py
  corehq/apps/export/utils.py
  corehq/apps/export/views.py
Labels: product/invisible

#21103 ICDS: Less noisy notify exception
  custom/icds/case_relationships.py
  custom/icds/exceptions.py
  custom/icds/messaging/custom_content.py
  custom/icds/messaging/custom_recipients.py
  custom/icds/tests/test_case_relationships.py
Labels: product/invisible

#21114 tiny, nit
  corehq/apps/users/forms.py
Labels: product/invisible

#21102 Use - instead of / in branch name
  scripts/rebuildstaging.py
Labels: product/invisible

#21111 [ICDS] Enable new indicators in Monthly Register Report
  custom/icds_reports/templates/icds_reports/icds_app/pdf/issnip_monthly_register.html
Labels: product/custom

#21113 make report id not required
  corehq/apps/userreports/ui/forms.py
Labels: product/invisible

#21116 Allow emailing case list explorer
  corehq/apps/reports/standard/cases/case_list_explorer.py
Labels: product/feature-flag

#21112 Rescue SpreadsheetFileExtError
  corehq/apps/case_importer/views.py
Labels: product/all-users-all-environments

#21081 Fix login as other user
  corehq/apps/hqadmin/forms.py
  corehq/apps/hqadmin/static/hqadmin/js/authenticate_as.js
  corehq/apps/hqadmin/templates/hqadmin/authenticate_as.html
  corehq/apps/hqadmin/templates/hqadmin/superuser_management.html
  corehq/apps/hqadmin/templates/hqadmin/user_administration.html
  corehq/apps/hqadmin/templates/hqadmin/web_user_lookup.html
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views/users.py
  corehq/ex-submodules/auditcare/templates/auditcare/audit_views.html
  corehq/ex-submodules/auditcare/views.py
Labels: product/invisible

#21115 l10k/echis UCR reports and data sources for use in the apps
  corehq/apps/userreports/models.py
  custom/echis_reports/ucr/data_sources/hew_performance.json
  custom/echis_reports/ucr/data_sources/hmis_mobile_job_aid.json
  custom/echis_reports/ucr/reports/hew_performance_by_health_post.json
  custom/echis_reports/ucr/reports/hew_performance_by_hew.json
  custom/echis_reports/ucr/reports/hew_performance_by_submission_date.json
  custom/echis_reports/ucr/reports/hew_performance_by_submission_date_all_forms.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_4_child_illness_r3.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_2_family_planning_r2.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_3_immun_growth_r2.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_r1.2.json
  custom/echis_reports/ucr/reports/ivr_weekly_mobile_job_aid.json
  settings.py
Labels: product/invisible

#21108 Feature flag to exclude formplayer-inline from case data and custom r…
  corehq/apps/reports/templates/reports/careplan/patient_careplan.html
  corehq/apps/reports/templates/reports/reportdata/case_data.html
  corehq/toggles.py
  custom/_legacy/pact/templates/pact/patient/pactpatient_careplan.html
Labels: product/invisible

#21079 ga for the dashboard
  corehq/apps/analytics/templates/analytics/google.html
  custom/icds_reports/templates/icds_reports/dashboard.html
Labels: product/invisible

#21119 locations/js/widgets_main requires select2
  corehq/apps/locations/static/locations/js/widgets_main.js
Labels: product/invisible

#21120 Kissmetrics analytics for old edit form usage
  corehq/apps/reports/static/reports/js/single_form.js
Labels: product/invisible

#21121 misc cleanup of new exports sort
  corehq/apps/hqwebapp/static/hqwebapp/js/knockout_bindings.ko.js
Labels: product/invisible

#21124 Valid report id
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_r1.2.json
Labels: product/custom

#21095 Resave cases & forms
  corehq/apps/data_pipeline_audit/dbacessors.py
  corehq/apps/es/management/commands/resave_failed_forms_and_cases.py
  custom/icds_reports/tasks.py
Labels: product/invisible

#21101 Fix report
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/commtrack/standard.py
  corehq/apps/reports/commtrack/util.py
Labels: product/all-users-all-environments

#21127 Fix Bulk CommCare Translations missing default values
  corehq/apps/app_manager/ui_translations/ui_translations.py
Labels: product/all-users-all-environments

#21117 make it possible (on the back end) to run reports off aggregate data sources
  corehq/apps/aggregate_ucrs/models.py
  corehq/apps/aggregate_ucrs/sql/__init__.py
  corehq/apps/aggregate_ucrs/sql/adapter.py
  corehq/apps/aggregate_ucrs/tasks.py
  corehq/apps/aggregate_ucrs/tests/data/table_definitions/monthly_aggregate_definition.yml
  corehq/apps/aggregate_ucrs/tests/test_aggregation.py
  corehq/apps/aggregate_ucrs/views.py
  corehq/apps/userreports/const.py
  corehq/apps/userreports/exceptions.py
  corehq/apps/userreports/mixins.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/data_source.py
  corehq/apps/userreports/sql/connection.py
Labels: product/invisible

#21105 Data cleaning: handle repeats that contain groups
  corehq/apps/reports/formdetails/readable.py
  corehq/apps/reports/tests/test_readable_formdata.py
  corehq/apps/reports/views.py
  corehq/form_processor/tests/test_utils.py
  corehq/form_processor/utils/xform.py
Labels: product/all-users-all-environments

#21130 Fix false error in form filters
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/forms.py
Labels: product/all-users-all-environments

#21128 Followup on pact formplayer-inline flag
  corehq/apps/reports/templates/reports/careplan/patient_careplan.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_careplan.html
Labels: product/invisible

#21122 Do ICDS task handling manually
  custom/icds_reports/tasks.py
Labels: product/custom

#21131 [ICDS] replace N/A to 0 for days_inactive and don't show forms from the future
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation.py
Labels: product/custom

#21125 Catch invalid ids
  corehq/apps/userreports/models.py
Labels: product/invisible

#21055 Remove useless columns
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_awc_data.sql
  custom/icds_reports/migrations/sql_templates/database_functions/insert_into_child_health_monthly.sql
  custom/icds_reports/migrations/sql_templates/database_views/agg_awc_monthly.sql
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/fixtures/awc_mgmt.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_daily_2017-05-28_sorted.csv
  custom/icds_reports/tests/test_aggregation_script.py
Labels: product/custom

#21132 Intrahealth recap passage
  custom/intrahealth/filters.py
  custom/intrahealth/reports/recap_passage_report_v2.py
  custom/intrahealth/reports/utils.py
  custom/intrahealth/tests/reports/test_recap_passage_report_v2.py
Labels: product/custom

#21073 Add datadog timing for requests to s3 blobdb
  corehq/blobs/s3db.py
  corehq/util/datadog/gauges.py
Labels: Open for review: hold off on merge, product/invisible

#21134 remove unused CouchPaginator and LucenePaginator
  corehq/ex-submodules/dimagi/utils/couch/pagination.py
Labels: product/invisible

#21129 Add empty template for uploads
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bulk_upload.html
  corehq/apps/locations/bulk_management.py
  corehq/apps/locations/tasks.py
  corehq/apps/locations/templates/locations/manage/partials/bulk_upload.html
  corehq/apps/locations/tests/test_bulk_management.py
  corehq/apps/locations/util.py
  corehq/apps/locations/views.py
Labels: product/invisible

#21137 Move DatatablesParam to reporting code
  corehq/apps/reports/generic.py
  corehq/apps/reports/util.py
  corehq/apps/userreports/reports/view.py
  corehq/ex-submodules/dimagi/utils/couch/pagination.py
Labels: product/invisible

#21139 Remove formplayer-inline from case data page and pact reports
  corehq/apps/reports/templates/reports/careplan/patient_careplan.html
  corehq/apps/reports/templates/reports/reportdata/case_data.html
  corehq/toggles.py
  custom/_legacy/pact/templates/pact/patient/pactpatient_careplan.html
Labels: product/invisible

#20845 Mk strict version check
  corehq/apps/app_manager/tests/app_factory.py
  corehq/apps/app_manager/tests/test_case_list_form.py
  corehq/apps/app_manager/tests/test_form_workflow.py
  corehq/apps/app_manager/tests/test_media_suite.py
  corehq/apps/app_manager/tests/test_practice_user_config.py
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/builds/models.py
  corehq/apps/builds/views.py
Labels: Open for review: hold off on merge, product/invisible

#21144 Remove type='text/javascript' from script tags
  corehq/apps/hqadmin/templates/hqadmin/domain_faceted_report.html
  corehq/apps/hqadmin/templates/hqadmin/indicator_report.html
  corehq/apps/hqadmin/templates/hqadmin/mass_email.html
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/registration/templates/registration/register_new_user.html
  custom/_legacy/mvp/templates/mvp/reports/chw_report.html
  custom/_legacy/mvp/templates/mvp/reports/fancy_report.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_edit.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_providers.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_schedule.html
  custom/apps/crs_reports/templates/crs_reports/base_template.html
  custom/bihar/templates/bihar/reports/report.html
  custom/care_pathways/templates/care_pathways/adoption_disaggregated_report.html
  custom/care_pathways/templates/care_pathways/filters/drilldown_options.html
  custom/care_pathways/templates/care_pathways/filters/single_option_with_helper.html
  custom/care_pathways/templates/care_pathways/partials/multi_bar_chart.html
  custom/care_pathways/templates/care_pathways/partials/report_table.html
  custom/care_pathways/templates/care_pathways/table_card_report.html
  custom/champ/templates/champ/knockout/base_template.html
  custom/champ/templates/champ/spec/mocha.html
  custom/common/templates/common/drilldown_options.html
  custom/common/templates/common/line_chart.html
  custom/enikshay/templates/enikshay/data_dumps_task.html
  custom/enikshay/templates/enikshay/reconciliation_tasks.html
  custom/ewsghana/templates/ewsghana/base_template.html
  custom/ewsghana/templates/ewsghana/dashboard_print_report.html
  custom/ewsghana/templates/ewsghana/datespan.html
  custom/ewsghana/templates/ewsghana/drilldown_options.html
  custom/ewsghana/templates/ewsghana/facility_page_print_report.html
  custom/ewsghana/templates/ewsghana/partials/ews_line_chart.html
  custom/ewsghana/templates/ewsghana/partials/ews_multibar_chart.html
  custom/ewsghana/templates/ewsghana/partials/ews_pie_chart.html
  custom/ewsghana/templates/ewsghana/partials/report_table.html
  custom/ewsghana/templates/ewsghana/reporting_rates_print_report.html
  custom/ewsghana/templates/ewsghana/stock_status_print_report.html
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/multi_report.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
  custom/icds_reports/templates/icds_reports/tableau.html
  custom/ilsgateway/templates/ilsgateway/datespan.html
  custom/ilsgateway/templates/ilsgateway/location_async.html
  custom/ilsgateway/templates/ilsgateway/partials/ils_multibar_chart.html
  custom/ilsgateway/templates/ilsgateway/partials/report_table_with_tabs.html
  custom/ilsgateway/templates/ilsgateway/slab/edit_location.html
  custom/intrahealth/templates/intrahealth/location_filter.html
  custom/intrahealth/templates/intrahealth/partials/report_table.html
  custom/intrahealth/templates/yeksi_naa/location_filter.html
  custom/intrahealth/templates/yeksi_naa/partials/report_table.html
  custom/m4change/templates/m4change/fields/daterange.html
  custom/m4change/templates/m4change/selectTemplate.html
  custom/succeed/templates/patient_submissions.html
  custom/succeed/templates/succeed/base_template.html
  custom/succeed/templates/succeed/report.html
  custom/succeed/templates/succeed/ucla_table.html
  custom/up_nrhm/templates/up_nrhm/datespan.html
  custom/world_vision/templates/world_vision/datespan.html
  custom/world_vision/templates/world_vision/location_filter.html
  custom/world_vision/templates/world_vision/multi_report.html
  custom/world_vision/templates/world_vision/partials/report_table_script.html
  custom/world_vision/templates/world_vision/print_report.html
Labels: product/invisible

#21141 Requirejs migration: case data page
  corehq/apps/hqwebapp/static/hqwebapp/js/lib/bootstrap-tab-hashes.js
  corehq/apps/reports/static/reports/js/case_details.js
  corehq/apps/reports/templates/reports/reportdata/case_data.html
  corehq/ex-submodules/casexml/apps/case/static/case/js/case_hierarchy.js
  corehq/ex-submodules/casexml/apps/case/static/case/js/case_property_modal.js
Labels: product/invisible

#21142 Kill logistics app
  custom/ewsghana/tests/handlers/utils.py
  custom/ilsgateway/tests/handlers/utils.py
  custom/ilsgateway/tests/test_handlers.py
  custom/ilsgateway/tests/test_reminders.py
  custom/ilsgateway/tests/test_reminders2.py
  custom/ilsgateway/tests/test_report_reminders.py
  custom/ilsgateway/tests/test_script.py
  custom/ilsgateway/tests/utils.py
  custom/ilsgateway/views.py
  custom/logistics/__init__.py
  custom/logistics/migrations/0001_initial.py
  custom/logistics/migrations/0002_auto_20151204_2142.py
  custom/logistics/migrations/0003_auto_20160401_0744.py
  custom/logistics/migrations/__init__.py
  custom/logistics/models.py
  custom/logistics/static/logistics/logistics.js
  custom/logistics/templates/logistics/config.html
  custom/logistics/tests/__init__.py
  custom/logistics/views.py
  settings.py
Labels: product/invisible

#21146 exports without owners can only be set to 'Edit and Export'
  corehq/apps/export/views.py
Labels: product/feature-flag

#21147 restrict editing shared exports by user permission
  corehq/apps/export/models/new.py
  corehq/apps/export/views.py
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/web_users.html
Labels: product/feature-flag

#21148 remove unused field DomainInvoiceFactory.is_community_invoice
  corehq/apps/accounting/invoicing.py
Labels: product/invisible

#21150 include columns for invoice related to subscription adjustment
  corehq/apps/accounting/interface.py
Labels: product/admin, product/invisible

#21152 add send form to hubspot back in signup signal
  corehq/apps/analytics/tasks.py
Labels: product/invisible, product/prod-india-all-users

#21110 Remove exports dbaccessors that now return nothing
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/export/custom_export_helpers.py
  corehq/apps/export/dbaccessors.py
  corehq/apps/export/models/new.py
  corehq/apps/export/views.py
  corehq/apps/reports/dbaccessors.py
  corehq/apps/reports/models.py
  corehq/apps/reports/tests/test_dbaccessors.py
  corehq/tabs/tabclasses.py
Labels: product/invisible

#21136 Further location download/upload improvements
  corehq/apps/locations/bulk_management.py
  corehq/apps/locations/tests/test_bulk_management.py
  corehq/apps/locations/tests/test_export.py
  corehq/apps/locations/tests/util.py
  corehq/apps/locations/util.py
Labels: product/invisible

#21153 fix hubspot data
  corehq/apps/analytics/tasks.py
Labels: product/invisible, product/prod-india-all-users

#21138 adding alerts page to admin ops block
  corehq/apps/hqwebapp/views.py
  corehq/tabs/tabclasses.py
Labels: Open for review: hold off on merge, product/invisible

#21154 278199 value throttling
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
Labels: product/invisible

#21151 Remove ddtrace
  requirements/requirements.txt
  requirements/uninstall-requirements.txt
Labels: product/invisible

#21156 Web Apps: show active tab in case detail
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/module.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
Labels: product/all-users-all-environments

#21106 Case attachment refactor
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/ex-submodules/casexml/apps/case/sharedmodels.py
  corehq/ex-submodules/casexml/apps/case/templates/case/partials/case_attachments.html
  corehq/ex-submodules/casexml/apps/case/xml/parser.py
  corehq/form_processor/abstract_models.py
  corehq/form_processor/backends/couch/update_strategy.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/backends/sql/update_strategy.py
  corehq/form_processor/migrations/0071_case_attachment_refactor.py
  corehq/form_processor/models.py
  corehq/form_processor/tests/test_case_dbaccessor.py
  corehq/form_processor/utils/sql.py
  corehq/pillows/mappings/reportcase_mapping.py
  corehq/sql_accessors/migrations/0059_case_attachment_refactor.py
  corehq/sql_accessors/sql_templates/get_case_attachment_by_name.sql
  corehq/sql_proxy_accessors/migrations/0041_case_attachment_refactor.py
  corehq/sql_proxy_accessors/sql_templates/get_case_attachment_by_name.sql
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: product/invisible, reindex/migration

#21158 Remove legacy cloudcare styles
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare-main.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare.debug.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/appicon.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/breadcrumbs.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/case.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/datepicker.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/form.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/formnav.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/grid.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/module.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/navigation.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/notifications.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/paginate.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/request.less
  corehq/apps/hqwebapp/static/cloudcare/less/cloudcare/version.less
  corehq/apps/hqwebapp/static/preview_app/less/preview_app-main.less
  corehq/apps/hqwebapp/static/preview_app/less/preview_app/mixins.less
Labels: product/invisible

#21029 improve user caching
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/apps/users/middleware.py
  corehq/apps/users/models.py
  custom/ilsgateway/tests/handlers/utils.py
Labels: product/invisible

#21161 remaining echis UCRs
  custom/echis_reports/ucr/reports/hew_performance_report_focal_person.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_focal_person.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_focal_person_family_planning.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_focal_person_immun_growth.json
Labels: product/custom

#21155 Rename billing admin to enterprise admin
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/migrations/0033_auto_20180709_1837.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/views.py
  corehq/util/context_processors.py
Labels: product/admin

#21157 Document saving a little more
  corehq/apps/locations/bulk_management.py
Labels: product/invisible

#21167 Define can_view_statement() for Wire Billing Records
  corehq/apps/accounting/models.py
Labels: product/admin

#21162 [ICDS] - beneficiary details performance
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/views.py
Labels: product/custom

#21165 remove l10k domain
  custom/echis_reports/ucr/data_sources/hew_performance.json
  custom/echis_reports/ucr/data_sources/hmis_mobile_job_aid.json
  custom/echis_reports/ucr/reports/hew_performance_by_health_post.json
  custom/echis_reports/ucr/reports/hew_performance_by_hew.json
  custom/echis_reports/ucr/reports/hew_performance_by_submission_date.json
  custom/echis_reports/ucr/reports/hew_performance_by_submission_date_all_forms.json
  custom/echis_reports/ucr/reports/hew_performance_report_focal_person.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_4_child_illness_r3.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_2_family_planning_r2.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_3_immun_growth_r2.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_focal_person.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_focal_person_family_planning.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_focal_person_immun_growth.json
  custom/echis_reports/ucr/reports/hmis_monthly_mobile_job_aid_r1.2.json
  custom/echis_reports/ucr/reports/ivr_weekly_mobile_job_aid.json
Labels: product/custom

#21163 ensure all static UCR files have 'server_environment'
  corehq/apps/api/tests.py
  corehq/apps/callcenter/data_source.py
  corehq/apps/userreports/models.py
  corehq/util/test_utils.py
  custom/_legacy/mvp/ucr/reports/data_sources/va_datasource.json
  custom/_legacy/mvp/ucr/reports/deidentified_va_report.json
  custom/abt/reports/data_sources/sms_case.json
  custom/abt/reports/data_sources/supervisory.json
  custom/abt/reports/data_sources/supervisory_v2.json
  custom/abt/reports/incident_report.json
  custom/abt/reports/sms_indicator_report.json
  custom/abt/reports/spray_progress_country.json
  custom/abt/reports/spray_progress_level_1.json
  custom/abt/reports/spray_progress_level_2.json
  custom/abt/reports/spray_progress_level_3.json
  custom/abt/reports/spray_progress_level_4.json
  custom/abt/reports/supervisory_report.json
  custom/abt/reports/supervisory_report_v2.json
  custom/intrahealth/ucr/data_sources/commande_combined.json
  custom/intrahealth/ucr/data_sources/livraison_combined.json
  custom/intrahealth/ucr/data_sources/operateur_combined.json
  custom/intrahealth/ucr/data_sources/rapture_combined.json
  custom/intrahealth/ucr/data_sources/recouvrement_combined.json
  custom/intrahealth/ucr/data_sources/visite_de_l_operateur.json
  custom/intrahealth/ucr/data_sources/visite_de_l_operateur_per_product.json
  custom/intrahealth/ucr/data_sources/visite_de_l_operateur_per_program.json
  custom/intrahealth/ucr/data_sources/yeksi_naa_reports_logisticien.json
  custom/pnlppgi/resources/malaria.json
  custom/pnlppgi/resources/site_reporting_rates.json
  custom/reports/mc/data_sources/malaria_consortium.json
  custom/reports/mc/data_sources/weekly_forms.json
  custom/succeed/data_sources/patient_task_list.json
  custom/succeed/data_sources/submissions.json
  custom/up_nrhm/data_sources/asha_facilitators.json
  custom/up_nrhm/data_sources/location_hierarchy.json
Labels: product/invisible

#21166 Change offset to bigint
  corehq/ex-submodules/pillowtop/migrations/0004_offset_to_big_int.py
  corehq/ex-submodules/pillowtop/models.py
Labels: product/invisible

#21181 Remove reference to url
  corehq/apps/formplayer_api/smsforms/api.py
Labels: product/invisible

#21164 Icds Reports | Don't cache values in program summary if only zeros ar…
  custom/icds_reports/static/js/directives/location-filter/location-filter.directive.js
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/views.py
Labels: product/custom

#21020 update jsonobject-couchdbkit
  corehq/apps/users/management/commands/restore_domain_membership.py
  corehq/apps/users/tests/test_restore_domain_membership.py
  requirements/requirements.txt
Labels: product/invisible

#21175 kill date_delay_invoicing
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/migrations/0034_remove_subscription_date_delay_invoicing.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/static/accounting/js/base_subscriptions_main.js
  corehq/apps/accounting/templates/accounting/partials/subscriptions_tab.html
  corehq/apps/accounting/tests/test_forms.py
  corehq/apps/api/accounting.py
  corehq/apps/domain/forms.py
  corehq/sql_db/operations.py
Labels: product/admin

#21180 ICDS Reports | Height info fix in wasting
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/static/icds_reports/js/spec/awc-reports.directive.spec.js
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
Labels: product/custom

#21171 Fix JS error for empty enterprise email list
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/static/accounting/js/billing_account_form.js
  corehq/apps/accounting/templates/accounting/accounts.html
Labels: product/admin

#21145 python-modernize . -w
  corehq/apps/reports/commtrack/standard.py
Labels: product/invisible

#21182 allow sorting by server_modified_on
  corehq/apps/api/resources/v0_4.py
Labels: product/all-users-all-environments

#21184 adding error message to unretire/restore
  corehq/apps/users/models.py
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#21186 Revert ES index changes from PR #21106
  corehq/pillows/mappings/reportcase_mapping.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: product/invisible

#21168 Data cleaning forms: better handle nodes that can't be cleaned
  corehq/apps/reports/formdetails/readable.py
  corehq/apps/reports/static/reports/js/data_corrections.js
  corehq/apps/reports/tests/test_readable_formdata.py
  corehq/apps/reports/views.py
  corehq/form_processor/exceptions.py
  corehq/form_processor/interfaces/processor.py
  corehq/form_processor/tests/test_form_dbaccessor.py
  corehq/form_processor/utils/xform.py
Labels: QA Passed, product/all-users-all-environments

#21185 get persona from cleaned data
  corehq/apps/registration/forms.py
Labels: product/invisible

#21188 Revert "update jsonobject-couchdbkit"
  corehq/apps/users/management/commands/restore_domain_membership.py
  corehq/apps/users/tests/test_restore_domain_membership.py
  requirements/requirements.txt
Labels: product/invisible

#20865 Use getAppEntity function to check if user has access to application
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_test.js
Labels: product/invisible

#21177 add check for number of languages
  corehq/apps/app_manager/static/app_manager/js/supported_languages.js
  corehq/apps/app_manager/views/formdesigner.py
Labels: product/all-users-all-environments

#21170 Fix locations lock and log task progress and results in dev mode
  corehq/apps/locations/tasks.py
  corehq/apps/locations/views.py
  corehq/util/workbook_json/excel_importer.py
Labels: product/invisible

#21183 skip cache at this point
  corehq/apps/registration/views.py
  corehq/apps/users/models.py
Labels: product/invisible

#21172 PR feedback from #21092
  corehq/apps/custom_data_fields/__init__.py
  corehq/apps/custom_data_fields/dbaccessors.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/locations/bulk_management.py
  corehq/apps/locations/forms.py
  corehq/apps/locations/tasks.py
  corehq/apps/locations/tests/test_bulk_management.py
  corehq/apps/locations/tests/test_location_fixtures.py
  corehq/apps/locations/util.py
  corehq/apps/locations/views.py
  corehq/apps/products/views.py
  corehq/apps/users/bulkupload.py
  corehq/apps/users/forms.py
  corehq/apps/users/views/mobile/custom_data_fields.py
  corehq/apps/users/views/mobile/users.py
  custom/enikshay/user_setup.py
  custom/ewsghana/tests/test_utils.py
  custom/ilsgateway/tests/handlers/utils.py
Labels: product/invisible

#21187 ICDS Reports | Decode Url in location service upon loading page
  custom/icds_reports/static/js/icds_app.js
Labels: product/custom

#21191 ICDS Reports | Remove unused code
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#21159 upgrade openpyxl
  corehq/ex-submodules/couchexport/writers.py
  corehq/util/workbook_json/excel.py
  requirements/requirements.txt
Labels: product/invisible

#21196 fix date created hubspot property
  corehq/apps/analytics/tasks.py
Labels: product/invisible, product/prod-india-all-users

#21189 tweak s3db timings
  corehq/blobs/s3db.py
  corehq/ex-submodules/dimagi/utils/logging.py
  corehq/util/datadog/gauges.py
Labels: product/invisible

#21195 assign_explicit_community_subscription should record a more specific …
  corehq/apps/accounting/filters.py
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/tests/test_migrations.py
  corehq/apps/appstore/views.py
  corehq/apps/registration/utils.py
Labels: product/admin

#21204 Reminders migration: allow migrating broadcasts that use multiple locations
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
Labels: product/invisible

#21199 Delete incomplete_email.html
  corehq/apps/domain/templates/domain/incomplete_email.html
Labels: product/invisible

#21208 Externalize js: champ reports
  custom/champ/static/champ/js/base.js
  custom/champ/static/champ/js/knockout/prevision_vs_achievement_graph.js
  custom/champ/static/champ/js/knockout/prevision_vs_achievement_table.js
  custom/champ/static/champ/js/knockout/service_uptake.js
  custom/champ/static/champ/js/spec/prevision_vs_achievement_graph.spec.js
  custom/champ/static/champ/js/spec/prevision_vs_achievement_table.spec.js
  custom/champ/static/champ/js/spec/service_uptake.spec.js
  custom/champ/templates/champ/knockout/base_template.html
  custom/champ/templates/champ/knockout/prevision_vs_achievements_graph.html
  custom/champ/templates/champ/knockout/prevision_vs_achievements_table.html
  custom/champ/templates/champ/knockout/service_uptake.html
Labels: product/invisible

#21207 Add generic custom recipients to new reminders framework
  corehq/apps/reminders/custom_recipients.py
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/messaging/scheduling/custom_recipients.py
  corehq/messaging/scheduling/tests/test_recipients.py
  settings.py
Labels: product/invisible

#21206 Data cleaning: handle form submissions with questions that are attributes
  corehq/form_processor/tests/test_utils.py
  corehq/form_processor/utils/xform.py
Labels: product/all-users-all-environments

#21210 Externalize js: ICDS aggregation script page
  custom/icds_reports/templates/icds_reports/aggregation_script.html
Labels: product/invisible

#21209 Externalize js: crs_reports
  custom/apps/crs_reports/templates/crs_reports/base_template.html
Labels: product/invisible

#21143 Kill world_vision custom code
  corehq/apps/cleanup/migrations/0003_convert_fluff_checkpoints_to_sql.py
  corehq/apps/hqwebapp/tests/test_default_landing_page.py
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
  corehq/tabs/tabclasses.py
  custom/world_vision/__init__.py
  custom/world_vision/charts.py
  custom/world_vision/custom_queries.py
  custom/world_vision/filters.py
  custom/world_vision/models.py
  custom/world_vision/reports/__init__.py
  custom/world_vision/reports/child_report.py
  custom/world_vision/reports/mixed_report.py
  custom/world_vision/reports/mother_report.py
  custom/world_vision/sqldata/__init__.py
  custom/world_vision/sqldata/child_sqldata.py
  custom/world_vision/sqldata/main_sqldata.py
  custom/world_vision/sqldata/mother_sqldata.py
  custom/world_vision/static/world_vision/css/world_vision.css
  custom/world_vision/static/world_vision/css/world_vision_print.css
  custom/world_vision/static/world_vision/ko/report_filter.drilldown_options.js
  custom/world_vision/templates/world_vision/accordion_report.html
  custom/world_vision/templates/world_vision/datespan.html
  custom/world_vision/templates/world_vision/location_filter.html
  custom/world_vision/templates/world_vision/mixed_report.html
  custom/world_vision/templates/world_vision/multi_report.html
  custom/world_vision/templates/world_vision/partials/chart.html
  custom/world_vision/templates/world_vision/partials/horizontal_report_table.html
  custom/world_vision/templates/world_vision/partials/report_table.html
  custom/world_vision/templates/world_vision/partials/report_table_script.html
  custom/world_vision/templates/world_vision/partials/table.html
  custom/world_vision/templates/world_vision/partials/tabular_cell.html
  custom/world_vision/templates/world_vision/print_report.html
  custom/world_vision/tests/__init__.py
  custom/world_vision/tests/data/test_child_case.json
  custom/world_vision/tests/data/test_mother_case.json
  custom/world_vision/tests/test_child_fluff.py
  custom/world_vision/tests/test_mother_fluff.py
  custom/world_vision/tests/utils.py
  custom/world_vision/user_calcs.py
  settings.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: product/invisible

#21214 modernize
  corehq/apps/api/tests.py
  corehq/apps/formplayer_api/smsforms/api.py
  corehq/apps/formplayer_api/smsforms/exceptions.py
  corehq/apps/formplayer_api/smsforms/signals.py
  corehq/apps/formplayer_api/smsforms/sms.py
Labels: product/invisible

#21202 Ce/aadhar sum
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_awc_data.sql
  custom/icds_reports/ucr/data_sources/ccs_record_cases_monthly_tableau2.json
  custom/icds_reports/ucr/data_sources/child_health_cases_monthly_tableau2.json
Labels: product/invisible

#21216 Use ace for UCR expression debugger
  corehq/apps/userreports/static/userreports/js/expression_debugger.js
  corehq/apps/userreports/static/userreports/js/expression_evaluator.js
Labels: product/invisible

#21176 Compare two report configurations
  corehq/apps/app_manager/fixtures/mobile_ucr.py
  corehq/apps/userreports/laboratory/__init__.py
  corehq/apps/userreports/laboratory/experiment.py
  corehq/apps/userreports/tasks.py
  settings.py
Labels: product/invisible

#21160 remove version requirement
  corehq/apps/app_manager/const.py
  corehq/apps/app_manager/tests/data/bulk_app_translation/basic/change_upload_form.xml
  corehq/apps/app_manager/tests/data/bulk_app_translation/form_modifications/expected_form.xml
  corehq/apps/app_manager/tests/data/case_list_form/case_list_form_advanced_form.xml
  corehq/apps/app_manager/tests/data/case_list_form/case_list_form_basic_form.xml
  corehq/apps/app_manager/tests/data/extension_case/preload_host_case.xml
  corehq/apps/app_manager/tests/data/extension_case/preload_host_case_adv.xml
  corehq/apps/app_manager/tests/data/extension_case/update_host_case.xml
  corehq/apps/app_manager/tests/data/extension_case/update_host_case_adv.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/close_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/complex-case-sharing.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/gps_no_question.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/gps_no_question_auto.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/gps_with_question.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/gps_with_question_auto.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/multiple_subcase_repeat.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/no_actions.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/open_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/open_case_external_id.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/open_update_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/subcase-parent-ref.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/subcase-repeat-sharing.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/subcase-repeat.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/subcase_repeat_mixed_form_post.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/update_attachment_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/update_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/update_parent_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/update_preload_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/child_module_adjusted_case_id_advanced.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/child_module_adjusted_case_id_basic.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/close_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/extension-case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/no_actions.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/open_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/open_close_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/open_update_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/subcase-open.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/subcase-repeat-multiple.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/subcase-repeat-sharing.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/subcase-repeat.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/subcase.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/update_attachment_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/update_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/update_parent_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/update_preload_case.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2_advanced/update_preload_case_multiple.xml
  corehq/apps/app_manager/tests/data/suite/advanced_submodule_xform.xml
  corehq/apps/app_manager/tests/data/suite/basic_submodule_xform.xml
  corehq/apps/app_manager/tests/data/suite/child-module-preload-parent-ref.xml
  corehq/apps/app_manager/tests/data/suite/child-module-rename-session-vars.xml
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/xform.py
Labels: product/invisible

#21212 Remove old ICDS dashboard feature flag
  corehq/toggles.py
  custom/icds_reports/reports/__init__.py
  custom/icds_reports/reports/reports.py
  custom/icds_reports/static/tableau.min.js
  custom/icds_reports/static/tableau_app.js
  custom/icds_reports/templates/icds_reports/tableau.html
  custom/icds_reports/views.py
Labels: product/custom

#21218 use max_row/column instead of get_highest_row/column()
  corehq/motech/repeaters/management/commands/generate_repeater_report.py
  corehq/util/workbook_json/excel_importer.py
  custom/enikshay/management/commands/generate_nikshay_notification_report.py
Labels: product/all-users-all-environments

#21197 Revert "Revert "update jsonobject-couchdbkit""
  corehq/apps/users/management/commands/restore_domain_membership.py
  corehq/apps/users/tests/test_restore_domain_membership.py
  requirements/requirements.txt
Labels: product/invisible

#21201 include a web user when applicable in the default community sub adj
  corehq/apps/accounting/tasks.py
  corehq/apps/appstore/views.py
  corehq/apps/registration/utils.py
Labels: product/admin

#21193 Update Pillow to 5.2.0
  requirements/requirements.txt
Labels: product/invisible

#21220 Add user data filter to new reminders framework
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0021_add_user_data_filter.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
  corehq/messaging/scheduling/tests/test_recipients.py
Labels: product/all-users-all-environments

#21133 Allow tracked CommCare.jad file in .gitignore
  .gitignore
Labels: product/invisible

#21070 Don't autocomplete inside quotes
  corehq/apps/reports/static/reports/js/filters/case_list_explorer_knockout_bindings.js
Labels: product/feature-flag

#21221 Allow data cleaning for bar codes and callouts
  corehq/apps/app_manager/xform.py
Labels: product/all-users-all-environments

#21223 Champ reports: include d3 styles
  custom/champ/templates/champ/knockout/base_template.html
Labels: product/custom

#21203 Delete model, leave table
  corehq/motech/dhis2/migrations/0005_delete_jsonapilog.py
Labels: product/invisible

#21226 bump jsonobject-couchdbkit to 0.9.1
  requirements/requirements.txt
Labels: product/invisible

#21227 use text formatting for mobile users download
  corehq/apps/users/bulkupload.py
  corehq/ex-submodules/couchexport/writers.py
Labels: product/all-users-all-environments

#21234 start migrating CommCareBuild attachments to blob storage
  corehq/apps/app_manager/management/commands/secure_submissions_all_apps.py
  corehq/apps/app_manager/models.py
  corehq/apps/builds/__init__.py
  corehq/apps/builds/models.py
  corehq/blobs/migrate.py
Labels: product/invisible

#21231 Requirejs: case exploder, manage notifications, stock levels
  corehq/apps/commtrack/static/commtrack/js/stock_levels.js
  corehq/apps/commtrack/templates/commtrack/manage/stock_levels.html
  corehq/apps/hqcase/static/hqcase/js/explode_cases.js
  corehq/apps/hqcase/templates/hqcase/explode_cases.html
  corehq/apps/notifications/static/notifications/js/manage_notifications.js
  corehq/apps/notifications/templates/notifications/manage_notifications.html
Labels: product/invisible

#21236 Add urllib3[secure] to prod-requirements.txt
  requirements/prod-requirements.txt
Labels: product/invisible

#21240 Fix Periodic Analytics Task
  corehq/apps/analytics/tasks.py
  corehq/apps/export/dbaccessors.py
Labels: product/invisible, product/prod-india-all-users

#21238 Fully release phone number on signup
  corehq/apps/analytics/ab_tests.py
  corehq/apps/registration/forms.py
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/registration/static/registration/js/register_new_user.js
  corehq/apps/registration/templates/registration/register_new_user.html
  corehq/apps/registration/views.py
Labels: product/all-users-all-environments

#21237 delete forms and cases in SQL when a domain is deleted
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
Labels: product/admin

#21244 remove obsolete call for XFormInstance Couch attachments
  corehq/form_processor/backends/couch/dbaccessors.py
Labels: product/invisible

#21246 [skip ci] remove not prepended date created from task
  corehq/apps/analytics/tasks.py
Labels: product/invisible, product/prod-india-all-users

#21247 improvements to domain deletion
  corehq/apps/domain/deletion.py
Labels: product/admin

#21249 Revert "Add urllib3[secure] to prod-requirements.txt"
  requirements/prod-requirements.txt
Labels: product/invisible

#21241 adding advanced setting help text
  corehq/apps/app_manager/static/app_manager/json/commcare-app-settings.yaml
  corehq/apps/app_manager/static_strings.py
Labels: product/all-users-all-environments

#21242 Registration date in the exported list of mobile user
  corehq/apps/users/bulkupload.py
Labels: product/all-users-all-environments

#21243 keep static UCR configs in memeory
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/tests/test_get_report_configs.py
  corehq/apps/userreports/tests/test_static_data_sources.py
  corehq/apps/userreports/tests/test_static_reports.py
  docs/decisions/0001-record-architecture-decisions.md
  docs/decisions/0002-keep-static-ucr-configurations-in-memory.md
Labels: product/invisible

#21250 Add 'until' condition to new reminders framework for parity with the old
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_scheduling_integration.py
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0022_add_stop_date_case_property_name.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
  corehq/messaging/scheduling/tasks.py
  corehq/messaging/scheduling/tests/test_schedules.py
Labels: product/all-users-all-environments

#21257 Allow some custom recipients to migrate the user_data_filter
  corehq/apps/reminders/management/commands/migrate_to_new_reminders.py
Labels: product/invisible

#21253 delete case_search data on domain deletion
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
Labels: product/admin

#21239 move Domain attachments to blob storage
  corehq/apps/domain/models.py
  corehq/blobs/migrate.py
  corehq/blobs/tests/test_migrate.py
Labels: product/invisible

#21219 make sure mobile UX popup appears only once
  corehq/apps/hqwebapp/static/hqwebapp/js/mobile_experience_warning.js
Labels: product/invisible, product/prod-india-all-users

#21248 Deduplicate Daily Feeding forms
  custom/icds_reports/docs/current_state_aggregation.png
  custom/icds_reports/docs/current_state_aggregation.txt
  custom/icds_reports/migrations/0054_add_pse_conducted_to_daily.py
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_awc_data.sql
  custom/icds_reports/migrations/sql_templates/database_functions/insert_into_daily_attendance.sql
  custom/icds_reports/migrations/sql_templates/update_tables24.sql
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/fixtures/daily_feeding.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/daily_attendance_2017-04-01_sorted.csv
  custom/icds_reports/tests/outputs/daily_attendance_2017-05-01_sorted.csv
  custom/icds_reports/tests/test_aggregation_script.py
Labels: product/custom

#21140 Slightly better agg_child_health performance
  custom/icds_reports/migrations/sql_templates/database_functions/aggregate_child_health.sql
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/test_aggregation_script.py
  custom/icds_reports/utils/aggregation.py
Labels: product/custom

#21260 Revert "rate limit on raw answer"
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
Labels: product/invisible

#21259 Ability to search CommCare data by de-activated users.
  corehq/apps/callcenter/views.py
  corehq/apps/reports/filters/api.py
  corehq/apps/reports/filters/users.py
Labels: product/all-users-all-environments
