Repository dimagi/commcare-hq, pull requests merged in 2018-03, with the labels that each got.

#19639 chunking periodic data submission
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#19640 tweak allow_report_an_issue logic in ENTERPRISE_MODE
  corehq/util/context_processors.py
Labels: product/custom

#19630 ejs/locations import
  corehq/apps/locations/static/locations/js/import.js
  corehq/apps/locations/templates/locations/manage/import.html
Labels: product/invisible

#19628 ejs/location location 2
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/static/locations/js/location_drilldown.async.js
  corehq/apps/locations/static/locations/spec/location_drilldown_spec.js
  corehq/apps/locations/templates/locations/manage/location.html
  corehq/apps/locations/templates/locations/spec/mocha.html
  corehq/apps/reports/templates/reports/filters/location_async.html
  corehq/apps/reports_core/templates/reports_core/filters/location_async/location_async.js
  custom/ilsgateway/templates/ilsgateway/location_async.html
  custom/intrahealth/templates/intrahealth/location_filter.html
Labels: product/invisible

#19646 Revert "Pv/back btns 268514"
  corehq/apps/domain/templates/login_and_password/two_factor/core/phone_register.html
  corehq/apps/domain/templates/login_and_password/two_factor/core/setup.html
  corehq/apps/settings/forms.py
  corehq/apps/settings/validators.py
  corehq/apps/settings/views.py
Labels: product/all-users-all-environments

#19629 ICDS - changed property for weight children in wasting indicator
  custom/icds_reports/reports/prevalence_of_severe.py
  custom/icds_reports/static/icds_reports/js/spec/prevalence-of-severe-report.directive.spec.js
  custom/icds_reports/static/js/directives/prevalence-of-severe-report/prevalence-of-severe-report.directive.js
  custom/icds_reports/tests/reports/test_prevalence_of_severe.py
Labels: product/custom

#19642 change number of AWCs opened yesterday when current month not selecte…
  custom/icds_reports/reports/cas_reach_data.py
  custom/icds_reports/tests/reports/test_icds_cas_reach.py
Labels: product/custom

#19645 Fix info message on ICDS CAS Fact Sheet page and Tabular reports down…
  custom/icds_reports/static/icds_reports/js/spec/progress-report.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/static/js/directives/progress-report/progress-report.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/progress-report.directive.html
Labels: product/custom

#19643 Fix refreshing info message after changing date filter
  custom/icds_reports/static/js/icds_app.js
Labels: product/custom

#19647 Set username and id as empty if there are no users in user_subreport
  corehq/ex-submodules/phonelog/utils.py
Labels: product/invisible

#19650 Swap button order so the Enter key triggers 'Next' instead of Back
  corehq/apps/settings/forms.py
Labels: product/all-users-all-environments

#19652 python-modernize testapps/ -w --future-unicode
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_elasticsearch/tests/test_require_elastic.py
  testapps/test_elasticsearch/tests/test_xform_es.py
  testapps/test_pillowtop/tests/test_app_pillow.py
  testapps/test_pillowtop/tests/test_case_pillow.py
  testapps/test_pillowtop/tests/test_case_search_pillow.py
  testapps/test_pillowtop/tests/test_changes.py
  testapps/test_pillowtop/tests/test_domain_pillow.py
  testapps/test_pillowtop/tests/test_form_pillow.py
  testapps/test_pillowtop/tests/test_group_pillow.py
  testapps/test_pillowtop/tests/test_grouptouser_pillow.py
  testapps/test_pillowtop/tests/test_ledger_pillow.py
  testapps/test_pillowtop/tests/test_pillows_cases.py
  testapps/test_pillowtop/tests/test_pillows_xforms.py
  testapps/test_pillowtop/tests/test_reindexer.py
  testapps/test_pillowtop/tests/test_report_case_pillow.py
  testapps/test_pillowtop/tests/test_report_xform_pillow.py
  testapps/test_pillowtop/tests/test_settings.py
  testapps/test_pillowtop/tests/test_sms_pillow.py
  testapps/test_pillowtop/tests/test_user_pillow.py
  testapps/test_pillowtop/tests/test_xform_pillow.py
  testapps/test_pillowtop/utils.py
Labels: product/invisible

#19651 python-modernize corehq/tests/ -w --future-unicode
  corehq/tests/nose.py
  corehq/tests/noseplugins/cmdline_params.py
  corehq/tests/noseplugins/debug.py
  corehq/tests/noseplugins/dividedwerun.py
  corehq/tests/noseplugins/djangomigrations.py
  corehq/tests/noseplugins/logfile.py
  corehq/tests/noseplugins/output.py
  corehq/tests/noseplugins/timing.py
  corehq/tests/noseplugins/uniformresult.py
Labels: product/invisible

#19614 meta fields just model change
  corehq/ex-submodules/couchforms/models.py
  corehq/form_processor/migrations/0069_add_metafields.py
  corehq/form_processor/models.py
  corehq/form_processor/serializers.py
Labels: product/invisible

#19660 Revert "ejs/location location 2"
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/static/locations/js/location_drilldown.async.js
  corehq/apps/locations/static/locations/spec/location_drilldown_spec.js
  corehq/apps/locations/templates/locations/manage/location.html
  corehq/apps/locations/templates/locations/spec/mocha.html
  corehq/apps/reports/templates/reports/filters/location_async.html
  corehq/apps/reports_core/templates/reports_core/filters/location_async/location_async.js
  custom/ilsgateway/templates/ilsgateway/location_async.html
  custom/intrahealth/templates/intrahealth/location_filter.html
Labels: product/invisible

#19590 more lint
  corehq/apps/case_importer/static/case_importer/js/excel_fields.js
  corehq/apps/commtrack/static/commtrack/js/location_bulk_upload_file.js
  corehq/apps/commtrack/static/commtrack/js/products_and_programs.async.js
  corehq/apps/domain/static/domain/js/internal_settings.js
  corehq/apps/domain/static/domain/js/media_manager.js
  corehq/apps/domain/static/domain/js/pro-bono.js
  corehq/apps/domain/static/domain/js/snapshot_settings.js
  corehq/apps/domain/templates/domain/partials/project_version_display.html
  corehq/apps/hqadmin/static/hqadmin/js/couch_changes.js
  corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js
  corehq/apps/hqadmin/static/hqadmin/js/domain_faceted_report.js
  corehq/apps/hqadmin/static/hqadmin/js/nvd3_charts_helper.js
  corehq/apps/hqadmin/static/hqadmin/js/project_map.js
  corehq/apps/hqadmin/static/hqadmin/js/raw_couch.js
  corehq/apps/hqadmin/static/hqadmin/js/system_info.js
  corehq/apps/hqadmin/static/hqadmin/js/visualizations.js
  corehq/apps/hqwebapp/static/hqwebapp/js/base_list_view_model.js
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/notifications/static/notifications/js/notifications_service.js
  corehq/apps/notifications/static/notifications/spec/NotificationsService.spec.mo.js
  corehq/apps/smsbillables/static/smsbillables/js/smsbillables.rate_calc.js
  corehq/apps/tour/static/tour/js/tour.utils.js
Labels: product/invisible

#19661 ICDS dashboard UI fixes
  custom/icds_reports/reports/prevalence_of_stunting.py
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/progress-report.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/static/js/directives/month-filter/month-filter.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
  custom/icds_reports/tests/reports/test_prevalence_of_stunting.py
Labels: product/custom

#19634 perform the correct check when disabling the calculated xpath add-on
  corehq/apps/app_manager/add_ons.py
Labels: product/invisible

#19655 remove multimedia and conditional ID formatting for calculated proper…
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
Labels: product/all-users-all-environments

#19657 ICDS - refator beneficiary detail and list
  custom/icds_reports/queries.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/static/icds_reports/js/spec/progress-report.directive.spec.js
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/views.py
Labels: product/custom

#19658 ejs/hqcase explode cases
  corehq/apps/hqcase/static/hqcase/js/explode_cases.js
  corehq/apps/hqcase/templates/hqcase/explode_cases.html
  scripts/externalize_js.sh
Labels: product/invisible

#19663 Use new telerivet api
  corehq/messaging/smsbackends/telerivet/exceptions.py
  corehq/messaging/smsbackends/telerivet/models.py
  corehq/messaging/smsbackends/telerivet/templates/telerivet/partials/step1.html
Labels: product/invisible

#19672 declare encoding
  custom/intrahealth/filters.py
Labels: product/invisible

#19667 Ce/scroll periodic
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#19675 Make "sync to dropbox" a button
  corehq/ex-submodules/soil/templates/soil/partials/dl_status.html
Labels: product/all-users-all-environments

#19680 ICDS reports tabular reports monthly register download button fix
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#19681 Icds reports cas reach data current_month_selected code refactor
  custom/icds_reports/reports/cas_reach_data.py
Labels: product/custom

#19674 Add rebuilding message to rebuildstaging
  scripts/rebuildstaging
Labels: product/invisible

#19673 Update local nginx instructions
  corehq/apps/builds/README.md
Labels: product/invisible

#19612 label change
  corehq/apps/app_manager/forms.py
Labels: product/feature-flag

#19671 hide select2 func inside each block
  corehq/apps/reports/static/reports/js/filters.js
Labels: product/invisible

#19676 removing mobile login code
  corehq/apps/domain/templates/login_and_password/mobile_login.html
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/views.py
Labels: product/invisible

#19690 Delete expired blobs in batches
  corehq/blobs/tasks.py
Labels: product/invisible

#19686 django 1.11.11
  requirements/requirements.txt
Labels: product/invisible

#19700 meta properties on form fact/staging
  corehq/warehouse/migrations/0023_auto_20180306_1258.py
  corehq/warehouse/models/facts.py
  corehq/warehouse/models/staging.py
  corehq/warehouse/transforms/sql/form_fact.sql
Labels: product/invisible

#19688 ICDS custom sms recipients and criteria
  custom/icds/messaging/custom_recipients.py
  custom/icds/rules/custom_criteria.py
  custom/icds/tests/test_custom_recipients.py
  custom/icds/tests/test_custom_rules.py
  settings.py
Labels: product/custom

#19701 allow whitelisting of repeaters via localsettings
  corehq/motech/repeaters/signals.py
  custom/enikshay/integrations/bets/repeaters.py
  custom/enikshay/integrations/nikshay/repeaters.py
  custom/enikshay/integrations/ninetyninedots/repeaters.py
  settings.py
Labels: Open for review: hold off on merge, product/invisible

#19698 python-modernize corehq/apps/hqadmin/ -w --future-unicode
  corehq/apps/hqadmin/admin.py
  corehq/apps/hqadmin/escheck.py
  corehq/apps/hqadmin/forms.py
  corehq/apps/hqadmin/history.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_grandfather_privs.py
  corehq/apps/hqadmin/management/commands/check_case_index_ids.py
  corehq/apps/hqadmin/management/commands/check_services.py
  corehq/apps/hqadmin/management/commands/clear_supervisor_confs.py
  corehq/apps/hqadmin/management/commands/clone_domain.py
  corehq/apps/hqadmin/management/commands/delete_related_cases.py
  corehq/apps/hqadmin/management/commands/deploy_in_progress.py
  corehq/apps/hqadmin/management/commands/export_domain_forms_raw.py
  corehq/apps/hqadmin/management/commands/fix_checkpoint_after_rewind.py
  corehq/apps/hqadmin/management/commands/fix_checkpoints_from_date.py
  corehq/apps/hqadmin/management/commands/fix_checkpoints_from_file.py
  corehq/apps/hqadmin/management/commands/import_domain_forms_raw.py
  corehq/apps/hqadmin/management/commands/kill_stale_celery_workers.py
  corehq/apps/hqadmin/management/commands/list_deploys.py
  corehq/apps/hqadmin/management/commands/mail_admins.py
  corehq/apps/hqadmin/management/commands/make_supervisor_conf.py
  corehq/apps/hqadmin/management/commands/make_supervisor_pillowtop_conf.py
  corehq/apps/hqadmin/management/commands/preindex_everything.py
  corehq/apps/hqadmin/management/commands/prune_couch_views.py
  corehq/apps/hqadmin/management/commands/prune_elastic_indices.py
  corehq/apps/hqadmin/management/commands/recent_changes.py
  corehq/apps/hqadmin/management/commands/record_deploy_success.py
  corehq/apps/hqadmin/management/commands/shutdown_celery_worker_by_hostname.py
  corehq/apps/hqadmin/management/commands/update_django_locales.py
  corehq/apps/hqadmin/management/commands/update_site_setup.py
  corehq/apps/hqadmin/management/utils.py
  corehq/apps/hqadmin/models.py
  corehq/apps/hqadmin/pillow_settings.py
  corehq/apps/hqadmin/reporting/reports.py
  corehq/apps/hqadmin/reports.py
  corehq/apps/hqadmin/service_checks.py
  corehq/apps/hqadmin/tasks.py
  corehq/apps/hqadmin/tests/test_authenticate_as.py
  corehq/apps/hqadmin/tests/test_clone_domain.py
  corehq/apps/hqadmin/tests/test_utils.py
  corehq/apps/hqadmin/tests/test_views.py
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/utils.py
  corehq/apps/hqadmin/views.py
Labels: product/invisible

#19697 python-modernize corehq/apps/zapier/ -w --future-unicode
  corehq/apps/zapier/admin.py
  corehq/apps/zapier/api/v0_5.py
  corehq/apps/zapier/apps.py
  corehq/apps/zapier/consts.py
  corehq/apps/zapier/signals/receivers.py
  corehq/apps/zapier/tests/test_create_update_cases_from_zapier.py
  corehq/apps/zapier/tests/test_fields.py
  corehq/apps/zapier/tests/test_utils.py
  corehq/apps/zapier/tests/test_zapier_forwarding.py
  corehq/apps/zapier/tests/test_zapier_hooks.py
  corehq/apps/zapier/urls.py
  corehq/apps/zapier/views.py
Labels: product/invisible

#19696 python-modernize corehq/apps/styleguide/ -w --future-unicode
  corehq/apps/styleguide/example_forms.py
  corehq/apps/styleguide/examples/controls_demo/forms.py
  corehq/apps/styleguide/examples/controls_demo/urls.py
  corehq/apps/styleguide/examples/controls_demo/views.py
  corehq/apps/styleguide/examples/simple_crispy_form/forms.py
  corehq/apps/styleguide/examples/simple_crispy_form/urls.py
  corehq/apps/styleguide/examples/simple_crispy_form/views.py
  corehq/apps/styleguide/management/commands/styleguide_update.py
  corehq/apps/styleguide/palette.py
  corehq/apps/styleguide/tabs.py
  corehq/apps/styleguide/urls.py
  corehq/apps/styleguide/views/__init__.py
  corehq/apps/styleguide/views/docs.py
Labels: product/invisible

#19695 python-modernize corehq/apps/es/ -w --future-unicode
  corehq/apps/es/aggregations.py
  corehq/apps/es/apps.py
  corehq/apps/es/case_search.py
  corehq/apps/es/cases.py
  corehq/apps/es/domains.py
  corehq/apps/es/es_query.py
  corehq/apps/es/fake/es_query_fake.py
  corehq/apps/es/fake/forms_fake.py
  corehq/apps/es/fake/groups_fake.py
  corehq/apps/es/fake/users_fake.py
  corehq/apps/es/filters.py
  corehq/apps/es/forms.py
  corehq/apps/es/groups.py
  corehq/apps/es/ledgers.py
  corehq/apps/es/management/commands/resave_failed_forms_and_cases.py
  corehq/apps/es/management/commands/restore_es_snapshot.py
  corehq/apps/es/queries.py
  corehq/apps/es/sms.py
  corehq/apps/es/tests/test_aggregations.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/es/tests/test_esquery.py
  corehq/apps/es/tests/test_esqueryset.py
  corehq/apps/es/tests/test_filters.py
  corehq/apps/es/tests/test_queries.py
  corehq/apps/es/tests/test_sms.py
  corehq/apps/es/tests/utils.py
  corehq/apps/es/users.py
  corehq/apps/es/utils.py
Labels: product/invisible

#19694 python-modernize corehq/apps/tzmigration/ -w --future-unicode
  corehq/apps/tzmigration/__init__.py
  corehq/apps/tzmigration/api.py
  corehq/apps/tzmigration/management/commands/tzmigrate.py
  corehq/apps/tzmigration/planning.py
  corehq/apps/tzmigration/test_utils.py
  corehq/apps/tzmigration/tests/test_timezone_migration_progress.py
  corehq/apps/tzmigration/tests/test_timezonemigration.py
  corehq/apps/tzmigration/timezonemigration.py
Labels: product/invisible

#19693 python-modernize corehq/apps/users/ -w --future-unicode
  corehq/apps/users/__init__.py
  corehq/apps/users/admin.py
  corehq/apps/users/analytics.py
  corehq/apps/users/bulkupload.py
  corehq/apps/users/cases.py
  corehq/apps/users/const.py
  corehq/apps/users/custom_data.py
  corehq/apps/users/dbaccessors/all_commcare_users.py
  corehq/apps/users/dbaccessors/couch_users.py
  corehq/apps/users/decorators.py
  corehq/apps/users/exceptions.py
  corehq/apps/users/export.py
  corehq/apps/users/fixturegenerators.py
  corehq/apps/users/forms.py
  corehq/apps/users/landing_pages.py
  corehq/apps/users/management/commands/add_multi_location_property.py
  corehq/apps/users/management/commands/clear_bad_user_data.py
  corehq/apps/users/management/commands/create_billing_admin_role.py
  corehq/apps/users/management/commands/delete_user.py
  corehq/apps/users/management/commands/deleted_users.py
  corehq/apps/users/management/commands/restore_domain_membership.py
  corehq/apps/users/management/commands/resync_location_user_data.py
  corehq/apps/users/middleware.py
  corehq/apps/users/models.py
  corehq/apps/users/permissions.py
  corehq/apps/users/signals.py
  corehq/apps/users/tasks.py
  corehq/apps/users/tests/bulk_upload.py
  corehq/apps/users/tests/case_utils.py
  corehq/apps/users/tests/create.py
  corehq/apps/users/tests/fixture_status.py
  corehq/apps/users/tests/forms.py
  corehq/apps/users/tests/permissions.py
  corehq/apps/users/tests/phone_users.py
  corehq/apps/users/tests/retire.py
  corehq/apps/users/tests/sync.py
  corehq/apps/users/tests/test_analytics.py
  corehq/apps/users/tests/test_db_accessors.py
  corehq/apps/users/tests/test_get_domain_language.py
  corehq/apps/users/tests/test_get_owner_ids.py
  corehq/apps/users/tests/test_location_assignment.py
  corehq/apps/users/tests/test_middleware.py
  corehq/apps/users/tests/test_models.py
  corehq/apps/users/tests/test_remove_unused_custom_fields.py
  corehq/apps/users/tests/test_restore_domain_membership.py
  corehq/apps/users/tests/test_signals.py
  corehq/apps/users/tests/test_user_model.py
  corehq/apps/users/tests/test_util.py
  corehq/apps/users/tests/test_views.py
  corehq/apps/users/tests/update.py
  corehq/apps/users/urls.py
  corehq/apps/users/util.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/custom_data_fields.py
  corehq/apps/users/views/mobile/groups.py
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#19689 Release new ICDS dashboard beneficiary columns.
  custom/icds_reports/tests/reports/test_adhaar.py
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/tests/reports/test_demographics.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/tests/test_fact_sheet_report.py
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#19699 Added managment command to migrate ICDS UCRs.
  custom/icds_reports/management/commands/migrate_ucr.py
Labels: product/invisible

#19704 ICDS reports limit filtering to start from march 2017
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/month-filter.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/static/js/directives/month-filter/month-filter.directive.js
Labels: product/custom

#19691 Add more debugging info to the form page when processing failed
  corehq/apps/reports/templates/reports/reportdata/form_data.html
Labels: product/feature-flag

#19703 moving periodic data task to 4am to avoid midnight congestion
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#19501 Add default values to form summary
  corehq/apps/app_manager/static/app_manager/js/summary/app_summary.ng.js
  corehq/apps/app_manager/templates/app_manager/ng_partials/form_summary_view.html
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/app_manager/xform.py
  corehq/apps/reports/formdetails/readable.py
  corehq/apps/reports/tests/readable_forms/mismatched_group_hierarchy.result.yaml
  corehq/apps/reports/tests/readable_forms/top_level_refless_group.result.yaml
  corehq/apps/reports/tests/test_readable_formdata.py
Labels: product/all-users-all-environments

#19687 Enable access to ISSNIP Register to everyone
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#19705 Blob DB size stats
  corehq/blobs/fsdb.py
  corehq/blobs/s3db.py
  corehq/blobs/tests/test_fsdb.py
  corehq/util/test_utils.py
Labels: product/invisible

#19709 python-modernize corehq/apps/domain/ -w --future-unicode
  corehq/apps/domain/__init__.py
  corehq/apps/domain/auth.py
  corehq/apps/domain/calculations.py
  corehq/apps/domain/dbaccessors.py
  corehq/apps/domain/decorators.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/management/commands/bootstrap.py
  corehq/apps/domain/management/commands/bootstrap_app.py
  corehq/apps/domain/management/commands/delete_domain.py
  corehq/apps/domain/management/commands/fill_last_modified_date.py
  corehq/apps/domain/management/commands/find_secure_submission_image_domains.py
  corehq/apps/domain/management/commands/make_superuser.py
  corehq/apps/domain/management/commands/mark_snapshot_head.py
  corehq/apps/domain/management/commands/migrate_can_use_data.py
  corehq/apps/domain/management/commands/migrate_domain_bu.py
  corehq/apps/domain/management/commands/migrate_domain_countries.py
  corehq/apps/domain/management/commands/migrate_impact_annotations.py
  corehq/apps/domain/management/commands/update_dimagi_created_self_started_projects.py
  corehq/apps/domain/models.py
  corehq/apps/domain/project_access/middleware.py
  corehq/apps/domain/project_access/models.py
  corehq/apps/domain/shortcuts.py
  corehq/apps/domain/signals.py
  corehq/apps/domain/tasks.py
  corehq/apps/domain/tests/test_auth_type.py
  corehq/apps/domain/tests/test_dbaccessors.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/domain/tests/test_forms.py
  corehq/apps/domain/tests/test_transform_domain_for_elasticsearch.py
  corehq/apps/domain/tests/test_utils.py
  corehq/apps/domain/urls.py
  corehq/apps/domain/utils.py
  corehq/apps/domain/views.py
Labels: product/invisible

#19710 python-modernize corehq/apps/tour/ -w --future-unicode
  corehq/apps/tour/management/commands/mark_tour_as_seen.py
  corehq/apps/tour/management/commands/unmark_tour_as_seen.py
  corehq/apps/tour/models.py
  corehq/apps/tour/tests/test_models.py
  corehq/apps/tour/tours.py
  corehq/apps/tour/urls.py
  corehq/apps/tour/views.py
Labels: product/invisible

#19713 Fix awcs covered map
  custom/icds_reports/static/js/directives/awcs-covered/awcs-covered.directive.js
Labels: product/custom

#19715 Remove task to deactivate users
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/users/tasks.py
Labels: product/invisible

#19665 Update phone location
  corehq/apps/locations/models.py
  corehq/apps/locations/tests/test_location_fixtures.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_location_assignment.py
Labels: product/invisible

#19711 Add "repeat every" to scheduling UI
  corehq/apps/data_interfaces/tests/test_scheduling_integration.py
  corehq/apps/users/tests/util.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0015_rename_schedule_length_to_repeat_every.py
  corehq/messaging/scheduling/models/timed_schedule.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
  corehq/messaging/scheduling/tests/test_schedules.py
  custom/enikshay/tests/test_custom_recipients.py
  custom/icds/tests/test_custom_content.py
  custom/icds/tests/test_custom_rules.py
Labels: product/feature-flag

#19719 Add some print statements for debugging.
  corehq/ex-submodules/pillow_retry/management/commands/send_pillow_retry_queue_through_pillows.py
Labels: product/invisible

#19717 Use autocomplete for auto-added case list/detail column
  corehq/apps/app_manager/models.py
Labels: product/all-users-all-environments

#19669 Revert 19660 revert 19628 jr/ejs/location location 2
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/static/locations/js/location_drilldown.async.js
  corehq/apps/locations/static/locations/spec/location_drilldown_spec.js
  corehq/apps/locations/templates/locations/location_types.html
  corehq/apps/locations/templates/locations/manage/location.html
  corehq/apps/locations/templates/locations/manage/partials/loc_type_widget.html
  corehq/apps/locations/templates/locations/spec/mocha.html
  corehq/apps/reports/templates/reports/filters/location_async.html
  corehq/apps/reports_core/templates/reports_core/filters/location_async/location_async.js
  custom/ilsgateway/templates/ilsgateway/location_async.html
  custom/intrahealth/templates/intrahealth/location_filter.html
Labels: product/invisible

#19712 Send persona info to hubspot
  corehq/apps/registration/views.py
Labels: product/invisible

#19726 linked domain fixes
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/views.py
Labels: product/feature-flag

#19724 make sure special characters don't break auth
  corehq/apps/domain/auth.py
Labels: product/invisible

#19722 python-modernize deployment/ -w --future-unicode
  deployment/gunicorn/commcarehq_wsgi.py
  deployment/gunicorn/gunicorn_conf.py
  deployment/websocket_wsgi.py
Labels: product/invisible

#19721 python-modernize scripts/ -w --future-unicode
  scripts/checkyaml.py
  scripts/cloudant/create_databases.py
  scripts/cloudant/generate_api_key.py
  scripts/cloudant/grant_api_key.py
  scripts/cloudant/manage_cloudant.py
  scripts/cloudant/revoke_api_key.py
  scripts/elasticsearch-administer.py
  scripts/gitutils.py
  scripts/kafka-administer.py
  scripts/rebuildstaging.py
  scripts/sh_verbose.py
  scripts/yaml_static_strings.py
Labels: product/invisible

#19723 Add date and time to data source names
  corehq/apps/userreports/reports/builder/forms.py
Labels: product/invisible

#19685 Remove migration data when no longer needed
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/data/bulk_app_translation/download/app.json
  corehq/apps/app_manager/tests/data/form_preparation_v2/subcase-parent-ref.json
  corehq/apps/app_manager/tests/data/yesno.json
Labels: product/all-users-all-environments

#19730 Form designer js add appcues event on form ready
  corehq/apps/analytics/static/analytix/js/appcues.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_designer.js
Labels: product/invisible

#19732 join bytes with bytestring
  corehq/apps/hqadmin/views.py
Labels: product/invisible

#19718 Blob storage report
  corehq/blobs/management/commands/blob_storage_report.py
  corehq/util/log.py
Labels: product/invisible

#19733 python-modernize corehq/doctypemigrations/ -w --future-unicode
  corehq/doctypemigrations/bulk_migrate.py
  corehq/doctypemigrations/changes.py
  corehq/doctypemigrations/continuous_migrate.py
  corehq/doctypemigrations/djangomigrations.py
  corehq/doctypemigrations/management/commands/run_doctype_migration.py
  corehq/doctypemigrations/migrator.py
  corehq/doctypemigrations/migrator_instances.py
  corehq/doctypemigrations/tests.py
Labels: product/invisible

#19734 Analytics: don't scroll periodic data query
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#19727 fix icds image deletion task
  custom/icds/tasks.py
Labels: product/custom

#19737 Fixes 2 broken 'Undo' buttons
  corehq/apps/dashboard/static/dashboard/js/dashboard.js
  corehq/apps/groups/static/groups/js/all_groups.js
Labels: product/all-users-all-environments

#19738 Custom Dashboard report queue
  custom/icds_reports/tasks.py
Labels: product/custom

#19714 rate limit NoMoreData errors from couchdb
  corehq/util/sentry.py
Labels: product/invisible

#19728 send celery task errors to sentry
  corehq/util/sentry.py
Labels: product/invisible

#19729 only allow domain requests from web users
  corehq/apps/domain/decorators.py
Labels: product/invisible

#19195 Cleanup of get_reverse_indexed_cases
  corehq/form_processor/README.md
  corehq/sql_accessors/migrations/0050_faster_get_reverse_indexed_cases.py
  corehq/sql_accessors/migrations/0058_drop_old_reverse_indexed_fn.py
  corehq/sql_accessors/sql_templates/get_reverse_indexed_cases_2.sql
  corehq/sql_proxy_accessors/migrations/0001_initial.py
  corehq/sql_proxy_accessors/migrations/0040_drop_old_reverse_indexed_fn.py
  corehq/sql_proxy_accessors/sql_templates/get_reverse_indexed_cases.sql
Labels: Open for review: hold off on merge, product/invisible

#19743 python-modernize corehq/pillows/ -w --future-unicode
  corehq/pillows/app_submission_tracker.py
  corehq/pillows/application.py
  corehq/pillows/base.py
  corehq/pillows/cacheinvalidate.py
  corehq/pillows/case.py
  corehq/pillows/case_search.py
  corehq/pillows/core.py
  corehq/pillows/domain.py
  corehq/pillows/group.py
  corehq/pillows/groups_to_user.py
  corehq/pillows/ledger.py
  corehq/pillows/mappings/__init__.py
  corehq/pillows/mappings/app_mapping.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/case_search_mapping.py
  corehq/pillows/mappings/domain_mapping.py
  corehq/pillows/mappings/group_mapping.py
  corehq/pillows/mappings/ledger_mapping.py
  corehq/pillows/mappings/reportcase_mapping.py
  corehq/pillows/mappings/reportxform_mapping.py
  corehq/pillows/mappings/sms_mapping.py
  corehq/pillows/mappings/user_mapping.py
  corehq/pillows/mappings/utils.py
  corehq/pillows/mappings/xform_mapping.py
  corehq/pillows/reportcase.py
  corehq/pillows/reportxform.py
  corehq/pillows/sms.py
  corehq/pillows/synclog.py
  corehq/pillows/user.py
  corehq/pillows/utils.py
  corehq/pillows/xform.py
Labels: product/invisible

#19744 python-modernize corehq/apps/export/ -w --future-unicode
  corehq/apps/export/const.py
  corehq/apps/export/conversion_mappings.py
  corehq/apps/export/custom_export_helpers.py
  corehq/apps/export/dbaccessors.py
  corehq/apps/export/esaccessors.py
  corehq/apps/export/exceptions.py
  corehq/apps/export/export.py
  corehq/apps/export/filters.py
  corehq/apps/export/forms.py
  corehq/apps/export/management/commands/deid_export.py
  corehq/apps/export/management/commands/download_saved_export.py
  corehq/apps/export/management/commands/migrate_export_toggle.py
  corehq/apps/export/management/commands/migrate_exports.py
  corehq/apps/export/management/commands/migrate_exports_for_domain.py
  corehq/apps/export/management/commands/process_skipped_pages.py
  corehq/apps/export/management/commands/rebuild_export.py
  corehq/apps/export/management/commands/revert_migrate_exports_for_domain.py
  corehq/apps/export/management/commands/update_export_with_newest_data.py
  corehq/apps/export/management/commands/upload_saved_export.py
  corehq/apps/export/models/deprecated.py
  corehq/apps/export/models/new.py
  corehq/apps/export/multiprocess.py
  corehq/apps/export/system_properties.py
  corehq/apps/export/tasks.py
  corehq/apps/export/tests/test_add_inferred_export_properties.py
  corehq/apps/export/tests/test_daily_saved_exports.py
  corehq/apps/export/tests/test_dbaccessors.py
  corehq/apps/export/tests/test_esaccessors.py
  corehq/apps/export/tests/test_export_column.py
  corehq/apps/export/tests/test_export_conversion.py
  corehq/apps/export/tests/test_export_data_schema.py
  corehq/apps/export/tests/test_export_filters.py
  corehq/apps/export/tests/test_export_form_subcases.py
  corehq/apps/export/tests/test_export_forms.py
  corehq/apps/export/tests/test_export_instance.py
  corehq/apps/export/tests/test_export_item.py
  corehq/apps/export/tests/test_export_views.py
  corehq/apps/export/tests/test_form_schema.py
  corehq/apps/export/tests/test_get_export_file.py
  corehq/apps/export/tests/test_inferred_schema.py
  corehq/apps/export/tests/test_sms_export.py
  corehq/apps/export/tests/test_table_configuration.py
  corehq/apps/export/tests/util.py
  corehq/apps/export/transforms.py
  corehq/apps/export/urls.py
  corehq/apps/export/utils.py
  corehq/apps/export/views.py
Labels: product/invisible

#19716 CHAMP - added function call to get filters data
  custom/champ/static/champ/js/knockout/prevision_vs_achievement_table.js
Labels: product/custom

#19746 update DOMAIN_MODULE_MAP with prod's DOMAIN_MODULE_CONFIG
  settings.py
Labels: product/invisible

#19742 python-modernize corehq/motech/ -w --future-unicode
  corehq/motech/dhis2/api.py
  corehq/motech/dhis2/const.py
  corehq/motech/dhis2/dbaccessors.py
  corehq/motech/dhis2/forms.py
  corehq/motech/dhis2/management/commands/send_datasets.py
  corehq/motech/dhis2/models.py
  corehq/motech/dhis2/tasks.py
  corehq/motech/dhis2/tests.py
  corehq/motech/dhis2/urls.py
  corehq/motech/dhis2/utils.py
  corehq/motech/dhis2/view.py
  corehq/motech/openmrs/const.py
  corehq/motech/openmrs/dbaccessors.py
  corehq/motech/openmrs/forms.py
  corehq/motech/openmrs/handler.py
  corehq/motech/openmrs/logger.py
  corehq/motech/openmrs/models.py
  corehq/motech/openmrs/openmrs_config.py
  corehq/motech/openmrs/repeater_generator.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/tasks.py
  corehq/motech/openmrs/tests/test_parsers.py
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/openmrs/urls.py
  corehq/motech/openmrs/views.py
  corehq/motech/repeaters/const.py
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/forms.py
  corehq/motech/repeaters/management/commands/delete_duplicate_cancelled_records.py
  corehq/motech/repeaters/management/commands/generate_repeater_report.py
  corehq/motech/repeaters/management/commands/update_cancelled_records.py
  corehq/motech/repeaters/migrations/0001_adjust_auth_field_format.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/signals.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_auth_field_migration.py
  corehq/motech/repeaters/tests/test_dbaccessors.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/utils.py
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/repeaters.py
  corehq/motech/tests/test_utils.py
  corehq/motech/utils.py
Labels: product/invisible

#19391 synclog to SQL
  corehq/apps/change_feed/data_sources.py
  corehq/apps/change_feed/topics.py
  corehq/apps/commtrack/tests/test_fixture.py
  corehq/apps/dump_reload/management/commands/dump_domain_data.py
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
  corehq/ex-submodules/casexml/apps/case/tests/test_sync_purge.py
  corehq/ex-submodules/casexml/apps/phone/admin.py
  corehq/ex-submodules/casexml/apps/phone/analytics.py
  corehq/ex-submodules/casexml/apps/phone/change_publishers.py
  corehq/ex-submodules/casexml/apps/phone/dbaccessors/sync_logs_by_user.py
  corehq/ex-submodules/casexml/apps/phone/document_store.py
  corehq/ex-submodules/casexml/apps/phone/management/commands/invalidate_sync_heads.py
  corehq/ex-submodules/casexml/apps/phone/migrations/0002_synclogsql.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/ex-submodules/casexml/apps/phone/tests/dbaccessors.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_dbaccessors.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_log_assertions.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_synclog_pillow.py
  corehq/ex-submodules/casexml/apps/phone/utils.py
  corehq/form_processor/abstract_models.py
  corehq/form_processor/tests/utils.py
  corehq/pillows/synclog.py
  corehq/sql_db/__init__.py
  corehq/sql_db/routers.py
  corehq/sql_db/tests/test_routers.py
  corehq/warehouse/dbaccessors.py
  corehq/warehouse/tests/test_dbaccessors.py
  localsettings.example.py
  settings.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: product/invisible

#19654 ejs/locations locations
  corehq/apps/locations/static/locations/js/location_tree.async.js
  corehq/apps/locations/static/locations/js/locations.js
  corehq/apps/locations/static/locations/js/utils.js
  corehq/apps/locations/templates/locations/manage/locations.html
  custom/ilsgateway/static/ilsgateway/js/slab_configuration.js
  custom/ilsgateway/templates/ilsgateway/slab/slab_configuration.html
Labels: product/invisible

#19741 Allow starting a conditional alert on a specific date
  corehq/apps/data_interfaces/migrations/0016_createscheduleinstanceactiondefinition_specific_start_date.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_scheduling_integration.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/models/timed_schedule.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
Labels: product/feature-flag

#19735 minor updates to setup instructions
  README.md
  localsettings.example.py
Labels: product/invisible

#19750 fix py3 compatibility regressions
  corehq/apps/app_manager/models.py
  corehq/blobs/management/commands/blob_storage_report.py
  corehq/ex-submodules/pillow_retry/management/commands/send_pillow_retry_queue_through_pillows.py
Labels: product/invisible

#19753 ICDS Code Cleanup
  custom/icds/messaging/custom_content.py
  custom/icds/messaging/scheduling_config.py
  custom/icds/rules/immunization.py
  custom/icds/tasks.py
  custom/icds/templates/icds/messaging/indicators/test_indicators.html
  custom/icds/tests/test_custom_content.py
  custom/icds/urls.py
  custom/icds/views.py
  settings.py
  urls.py
Labels: product/custom

#19754 Appcues: don't use event properties
  corehq/apps/app_manager/static/app_manager/js/forms/form_designer.js
Labels: product/invisible

#19761 catch correct exception
  corehq/ex-submodules/casexml/apps/case/util.py
Labels: product/invisible

#19760 make sure ID is always a UUID object
  corehq/ex-submodules/casexml/apps/phone/change_publishers.py
  corehq/ex-submodules/casexml/apps/phone/models.py
Labels: product/invisible

#19755 Use DELETE method when deleting single object
  corehq/blobs/s3db.py
Labels: product/invisible

#19748 patch time and select
  scripts/rebuildstaging.py
Labels: product/invisible

#19759 revert observable to boolean variable
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
Labels: product/invisible

#19764 db router fixes
  corehq/sql_db/routers.py
  corehq/sql_db/tests/test_routers.py
Labels: product/invisible

#19756 Refactor OpenMRS handler & helpers
  corehq/motech/openmrs/handler.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/repeaters.py
Labels: product/invisible

#19767 sumologic log task
  corehq/ex-submodules/phonelog/tasks.py
  corehq/ex-submodules/phonelog/utils.py
Labels: product/invisible

#19765 remove restriction on 'custom' databases
  corehq/sql_db/__init__.py
Labels: product/invisible

#19762 Bump ipdb version
  requirements/dev-requirements.txt
Labels: product/invisible

#19747 Added 3 new questions to infrastructure details UCR.
  custom/icds_reports/tests/fixtures/infrastructure.csv
  custom/icds_reports/ucr/data_sources/infrastructure_form.json
Labels: product/custom

#19768 store calculated property in an xpath variable
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/data/suite/normal-suite.xml
  corehq/apps/app_manager/tests/data/suite/search_command_detail.xml
  corehq/apps/app_manager/tests/data/suite/suite-case-detail-instances.xml
  corehq/apps/app_manager/tests/data/suite/suite-case-detail-tabs-with-nodesets.xml
Labels: product/invisible

#19772 Added cbo filter to the table report and loading message after ajax call
  custom/champ/static/champ/js/knockout/prevision_vs_achievement_graph.js
  custom/champ/static/champ/js/knockout/prevision_vs_achievement_table.js
  custom/champ/static/champ/js/knockout/service_uptake.js
  custom/champ/static/champ/js/spec/prevision_vs_achievement_table.spec.js
  custom/champ/templates/champ/knockout/base_async_template.html
  custom/champ/templates/champ/knockout/prevision_vs_achievements_table.html
  custom/champ/tests/test_pva_table.py
  custom/champ/views.py
Labels: product/custom

#19769 Update case type suggestions used in old reminders framework
  corehq/apps/reminders/views.py
Labels: product/all-users-all-environments

#19739 saas/make mobile great again
  corehq/apps/app_manager/templates/app_manager/form_designer.html
  corehq/apps/app_manager/templates/app_manager/partials/releases.html
  corehq/apps/app_manager/views/releases.py
  corehq/apps/hqwebapp/static/hqwebapp/images/yikes_face.png
  corehq/apps/hqwebapp/static/hqwebapp/js/main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/mobile_experience_warning.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/modals.less
  corehq/apps/registration/forms.py
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/registration/templates/registration/email/confirm_account.html
  corehq/apps/registration/templates/registration/email/fancy_email.html
  corehq/apps/registration/templates/registration/email/mobile_signup_reminder.html
  corehq/apps/registration/templates/registration/email/mobile_signup_reminder.txt
  corehq/apps/registration/templates/registration/partials/register_new_user/success.html
  corehq/apps/registration/urls.py
  corehq/apps/registration/utils.py
  corehq/apps/registration/views.py
  corehq/toggles.py
Labels: product/all-users-all-environments

#19751 remove references to DOMAIN_MODULE_CONFIG
  corehq/apps/domain/models.py
  corehq/apps/domain/utils.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/reports/views.py
  custom/ewsghana/models.py
  custom/ewsghana/tests/test_input_stock_view.py
  custom/ilsgateway/models.py
  custom/utils/utils.py
  settings.py
Labels: product/invisible

#19752 python-modernize deployment/ -w --future-unicode
  deployment/gunicorn/commcarehq_wsgi.py
  deployment/gunicorn/gunicorn_conf.py
  deployment/websocket_wsgi.py
Labels: Open for review: hold off on merge, product/invisible

#19779 Add debug info to pr emails
  corehq/apps/hqadmin/management/utils.py
Labels: product/invisible

#19780 Clarified scheduled report message on 'Send Test'
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#19788 python-modernize corehq/ex-submodules/auditcare/ -w --future-unicode
  corehq/ex-submodules/auditcare/decorators/login.py
  corehq/ex-submodules/auditcare/decorators/manual.py
  corehq/ex-submodules/auditcare/forms.py
  corehq/ex-submodules/auditcare/inspect.py
  corehq/ex-submodules/auditcare/management/commands/compute_diffs.py
  corehq/ex-submodules/auditcare/management/commands/generate_request_report.py
  corehq/ex-submodules/auditcare/management/commands/resolve_urls.py
  corehq/ex-submodules/auditcare/middleware.py
  corehq/ex-submodules/auditcare/models.py
  corehq/ex-submodules/auditcare/signals.py
  corehq/ex-submodules/auditcare/tests/auth.py
  corehq/ex-submodules/auditcare/tests/modelevents.py
  corehq/ex-submodules/auditcare/tests/testutils.py
  corehq/ex-submodules/auditcare/urls.py
  corehq/ex-submodules/auditcare/utils/__init__.py
  corehq/ex-submodules/auditcare/utils/export.py
  corehq/ex-submodules/auditcare/utils/resolver.py
  corehq/ex-submodules/auditcare/utils/show_urls.py
  corehq/ex-submodules/auditcare/views.py
Labels: product/invisible

#19792 python-modernize corehq/apps/fixtures/ -w --future-unicode
  corehq/apps/fixtures/__init__.py
  corehq/apps/fixtures/dbaccessors.py
  corehq/apps/fixtures/dispatcher.py
  corehq/apps/fixtures/download.py
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/fixtures/interface.py
  corehq/apps/fixtures/models.py
  corehq/apps/fixtures/resources/v0_1.py
  corehq/apps/fixtures/tasks.py
  corehq/apps/fixtures/tests/test_dbaccessors.py
  corehq/apps/fixtures/tests/test_field_names.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/fixtures/tests/test_location_ownership.py
  corehq/apps/fixtures/tests/test_upload.py
  corehq/apps/fixtures/upload/__init__.py
  corehq/apps/fixtures/upload/const.py
  corehq/apps/fixtures/upload/definitions.py
  corehq/apps/fixtures/upload/failure_messages.py
  corehq/apps/fixtures/upload/location_cache.py
  corehq/apps/fixtures/upload/run_upload.py
  corehq/apps/fixtures/upload/validation.py
  corehq/apps/fixtures/upload/workbook.py
  corehq/apps/fixtures/urls.py
  corehq/apps/fixtures/utils.py
  corehq/apps/fixtures/views.py
Labels: product/invisible

#19787 python-modernize corehq/apps/locations/ -w --future-unicode
  corehq/apps/locations/admin.py
  corehq/apps/locations/analytics.py
  corehq/apps/locations/bulk_management.py
  corehq/apps/locations/const.py
  corehq/apps/locations/dbaccessors.py
  corehq/apps/locations/document_store.py
  corehq/apps/locations/fixtures.py
  corehq/apps/locations/forms.py
  corehq/apps/locations/management/commands/fix_loc_type_reference.py
  corehq/apps/locations/management/commands/release_location_locks.py
  corehq/apps/locations/management/commands/update_parent_location.py
  corehq/apps/locations/middleware.py
  corehq/apps/locations/models.py
  corehq/apps/locations/permissions.py
  corehq/apps/locations/resources/v0_1.py
  corehq/apps/locations/resources/v0_5.py
  corehq/apps/locations/signals.py
  corehq/apps/locations/tasks.py
  corehq/apps/locations/tests/test_bulk_management.py
  corehq/apps/locations/tests/test_change_administrative_status.py
  corehq/apps/locations/tests/test_change_has_user.py
  corehq/apps/locations/tests/test_dbaccessors.py
  corehq/apps/locations/tests/test_location_expressions.py
  corehq/apps/locations/tests/test_location_fixtures.py
  corehq/apps/locations/tests/test_location_groups.py
  corehq/apps/locations/tests/test_location_queries.py
  corehq/apps/locations/tests/test_location_set.py
  corehq/apps/locations/tests/test_location_types.py
  corehq/apps/locations/tests/test_location_utils.py
  corehq/apps/locations/tests/test_locations.py
  corehq/apps/locations/tests/test_permissions.py
  corehq/apps/locations/tests/test_products_at_location.py
  corehq/apps/locations/tests/test_site_code.py
  corehq/apps/locations/tests/util.py
  corehq/apps/locations/tree_utils.py
  corehq/apps/locations/ucr_expressions.py
  corehq/apps/locations/urls.py
  corehq/apps/locations/util.py
  corehq/apps/locations/views.py
Labels: product/invisible

#19789 python-modernize corehq/dbaccessors/ -w --future-unicode
  corehq/dbaccessors/couchapps/all_docs.py
  corehq/dbaccessors/couchapps/cases_by_server_date/by_owner_server_modified_on.py
  corehq/dbaccessors/couchapps/cases_by_server_date/by_server_modified_on.py
Labels: product/invisible

#19786 python-modernize corehq/ex-submodules/phonelog/ -w --future-unicode
  corehq/ex-submodules/phonelog/admin.py
  corehq/ex-submodules/phonelog/management/commands/delete_couch_devicelogs.py
  corehq/ex-submodules/phonelog/management/commands/migrate_device_entry.py
  corehq/ex-submodules/phonelog/models.py
  corehq/ex-submodules/phonelog/reports.py
  corehq/ex-submodules/phonelog/tasks.py
  corehq/ex-submodules/phonelog/tests/test_sumologic.py
  corehq/ex-submodules/phonelog/utils.py
Labels: product/invisible

#19785 python-modernize corehq/apps/settings/ -w --future-unicode
  corehq/apps/settings/forms.py
  corehq/apps/settings/tests/test_utils.py
  corehq/apps/settings/urls.py
  corehq/apps/settings/views.py
Labels: product/invisible

#19784 python-modernize corehq/apps/reminders/ -w --future-unicode
  corehq/apps/reminders/event_handlers.py
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/management/commands/find_ivr_usage.py
  corehq/apps/reminders/management/commands/remove_dup_reminders.py
  corehq/apps/reminders/management/commands/run_reminder_queue.py
  corehq/apps/reminders/models.py
  corehq/apps/reminders/tasks.py
  corehq/apps/reminders/tests/test_cache.py
  corehq/apps/reminders/tests/test_lookup.py
  corehq/apps/reminders/tests/test_message_formatting.py
  corehq/apps/reminders/tests/test_recipient.py
  corehq/apps/reminders/tests/test_responsiveness.py
  corehq/apps/reminders/tests/test_send_reminders.py
  corehq/apps/reminders/tests/test_util.py
  corehq/apps/reminders/tests/utils.py
  corehq/apps/reminders/urls.py
  corehq/apps/reminders/util.py
  corehq/apps/reminders/views.py
Labels: product/invisible

#19766 add system check to ensure DB tables queryable
  corehq/sql_db/__init__.py
Labels: Open for review: hold off on merge, product/invisible

#19796 use strings with __import__
  corehq/ex-submodules/auditcare/signals.py
Labels: product/invisible

#19797 remove legacy auditcare models
  corehq/ex-submodules/auditcare/models.py
  corehq/sql_db/__init__.py
Labels: product/invisible

#19798 fix and refactor DB routers
  corehq/sql_db/routers.py
  corehq/sql_db/tests/test_routers.py
  settings.py
Labels: product/invisible

#19682 270213: kissmetrics form and case export events
  corehq/apps/export/views.py
Labels: product/invisible

#19736 Changed Tableau view to a RedirectView
  custom/icds_reports/views.py
Labels: product/custom

#19795 don't show unfinished rebuilt in place data source as complete if pre…
  corehq/apps/userreports/tasks.py
Labels: product/invisible

#19778 change_plan should always set skip_auto_downgrade to False
  corehq/apps/accounting/models.py
  corehq/apps/domain/forms.py
Labels: product/invisible

#19776 make salesforce_contract_id and no_invoice_reason non-nullable
  corehq/apps/accounting/migrations/0017_nonnullable_char_fields.py
  corehq/apps/accounting/models.py
Labels: product/invisible

#19793 ejs/settings edit my account
  corehq/apps/settings/static/settings/js/edit_my_account.js
  corehq/apps/settings/templates/settings/edit_my_account.html
Labels: product/invisible

#19781 ejs/hqadmin indicator report
  corehq/apps/hqadmin/static/hqadmin/js/indicator_report.js
  corehq/apps/hqadmin/static/hqadmin/js/visualizations.js
  corehq/apps/hqadmin/templates/hqadmin/indicator_report.html
Labels: product/invisible

#19801 assign default empty string in migration
  corehq/apps/accounting/migrations/0017_nonnullable_char_fields.py
Labels: product/invisible

#19800 pformat_json accepts both strings and data
  corehq/motech/repeaters/views/repeat_records.py
Labels: product/invisible

#19794 ejs/custom data fields custom data fields
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
  corehq/apps/custom_data_fields/templates/custom_data_fields/custom_data_fields.html
Labels: product/invisible

#19791 python-modernize corehq/apps/hqwebapp/ -w --future-unicode
  corehq/apps/hqwebapp/async_handler.py
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/hqwebapp/decorators.py
  corehq/apps/hqwebapp/doc_info.py
  corehq/apps/hqwebapp/encoders.py
  corehq/apps/hqwebapp/fields.py
  corehq/apps/hqwebapp/forms.py
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/management/commands/fix_less_imports_collectstatic.py
  corehq/apps/hqwebapp/management/commands/purge_compressed_files.py
  corehq/apps/hqwebapp/management/commands/resource_static.py
  corehq/apps/hqwebapp/management/commands/update_manifest.py
  corehq/apps/hqwebapp/models.py
  corehq/apps/hqwebapp/precompilers.py
  corehq/apps/hqwebapp/session_details_endpoint/tests.py
  corehq/apps/hqwebapp/session_details_endpoint/views.py
  corehq/apps/hqwebapp/signals.py
  corehq/apps/hqwebapp/tasks.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/templatetags/mainreport_tags.py
  corehq/apps/hqwebapp/templatetags/proptable_tags.py
  corehq/apps/hqwebapp/templatetags/tests/test_tag.py
  corehq/apps/hqwebapp/tests/test_compress_command.py
  corehq/apps/hqwebapp/tests/test_csrf_middleware.py
  corehq/apps/hqwebapp/tests/test_default_landing_page.py
  corehq/apps/hqwebapp/tests/test_hq_shared_tags.py
  corehq/apps/hqwebapp/tests/test_password_lockout.py
  corehq/apps/hqwebapp/tests/test_proptable_tags.py
  corehq/apps/hqwebapp/tests/test_views.py
  corehq/apps/hqwebapp/two_factor_gateways.py
  corehq/apps/hqwebapp/uglify.py
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/utils.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/hqwebapp/widgets.py
  corehq/util/hmac_request.py
Labels: product/invisible

#19775 Add default values to form summary download
  corehq/apps/app_manager/views/app_summary.py
Labels: product/all-users-all-environments

#19809 fix 'pending trigger events' error
  corehq/apps/accounting/migrations/0017_nonnullable_char_fields.py
  corehq/apps/accounting/migrations/0018_alter_nonnullable_char_fields.py
Labels: product/invisible

#19813 Revert "python-modernize corehq/apps/hqwebapp/ -w --future-unicode"
  corehq/apps/hqwebapp/async_handler.py
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/hqwebapp/decorators.py
  corehq/apps/hqwebapp/doc_info.py
  corehq/apps/hqwebapp/encoders.py
  corehq/apps/hqwebapp/fields.py
  corehq/apps/hqwebapp/forms.py
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/management/commands/fix_less_imports_collectstatic.py
  corehq/apps/hqwebapp/management/commands/purge_compressed_files.py
  corehq/apps/hqwebapp/management/commands/resource_static.py
  corehq/apps/hqwebapp/management/commands/update_manifest.py
  corehq/apps/hqwebapp/models.py
  corehq/apps/hqwebapp/precompilers.py
  corehq/apps/hqwebapp/session_details_endpoint/tests.py
  corehq/apps/hqwebapp/session_details_endpoint/views.py
  corehq/apps/hqwebapp/signals.py
  corehq/apps/hqwebapp/tasks.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/templatetags/mainreport_tags.py
  corehq/apps/hqwebapp/templatetags/proptable_tags.py
  corehq/apps/hqwebapp/templatetags/tests/test_tag.py
  corehq/apps/hqwebapp/tests/test_compress_command.py
  corehq/apps/hqwebapp/tests/test_csrf_middleware.py
  corehq/apps/hqwebapp/tests/test_default_landing_page.py
  corehq/apps/hqwebapp/tests/test_hq_shared_tags.py
  corehq/apps/hqwebapp/tests/test_password_lockout.py
  corehq/apps/hqwebapp/tests/test_proptable_tags.py
  corehq/apps/hqwebapp/tests/test_views.py
  corehq/apps/hqwebapp/two_factor_gateways.py
  corehq/apps/hqwebapp/uglify.py
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/utils.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/hqwebapp/widgets.py
  corehq/util/hmac_request.py
Labels: product/invisible

#19803 externalize js script
  scripts/externalize_js.sh
Labels: product/invisible

#19805 only pass necessary cookies to celery
  corehq/apps/analytics/signals.py
  corehq/apps/analytics/tasks.py
  corehq/apps/analytics/views.py
  corehq/apps/registration/views.py
Labels: product/invisible

#19806 Added restriction to the PDF export when combined option selected
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
Labels: product/custom

#19604 ICDS Postnatal Care Forms UCRs
  custom/icds_reports/const.py
  custom/icds_reports/migrations/0035_add_pnc_aggregate_models.py
  custom/icds_reports/models.py
  custom/icds_reports/ucr/data_sources/dashboard/postnatal_care_forms.json
  custom/icds_reports/ucr/tests/data/ebf_form_v10326.xml
  custom/icds_reports/ucr/tests/data/pnc_form_v10326.xml
  custom/icds_reports/ucr/tests/test_pnc_form_ucr.py
  custom/icds_reports/utils/aggregation.py
  settings.py
Labels: product/custom

#19817 python-modernize corehq/apps/groups/ -w --future-unicode
  corehq/apps/groups/__init__.py
  corehq/apps/groups/dbaccessors.py
  corehq/apps/groups/models.py
  corehq/apps/groups/tests/test_groups.py
  corehq/apps/groups/tests/test_utils.py
  corehq/apps/groups/urls.py
  corehq/apps/groups/views.py
Labels: product/invisible

#19816 python-modernize corehq/ex-submodules/soil/ -w --future-unicode
  corehq/ex-submodules/soil/__init__.py
  corehq/ex-submodules/soil/heartbeat.py
  corehq/ex-submodules/soil/progress.py
  corehq/ex-submodules/soil/tasks.py
  corehq/ex-submodules/soil/tests/test_download_base.py
  corehq/ex-submodules/soil/urls.py
  corehq/ex-submodules/soil/util.py
  corehq/ex-submodules/soil/views.py
Labels: product/invisible

#19815 python-modernize corehq/apps/sms/ -w --future-unicode
  corehq/apps/sms/api.py
  corehq/apps/sms/change_publishers.py
  corehq/apps/sms/dbaccessors.py
  corehq/apps/sms/filters.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/handlers/form_session.py
  corehq/apps/sms/handlers/forwarding.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/management/commands/delete_messaging_couch_phone_numbers.py
  corehq/apps/sms/management/commands/fix_phonenumber_couch_id.py
  corehq/apps/sms/management/commands/fix_smslog_recipient_doc_type.py
  corehq/apps/sms/management/commands/requeue_outgoing_messages.py
  corehq/apps/sms/management/commands/run_sms_queue.py
  corehq/apps/sms/messages.py
  corehq/apps/sms/migration_status.py
  corehq/apps/sms/mixin.py
  corehq/apps/sms/models.py
  corehq/apps/sms/phonenumbers_helper.py
  corehq/apps/sms/resources/v0_5.py
  corehq/apps/sms/serializers.py
  corehq/apps/sms/tasks.py
  corehq/apps/sms/tests/inbound_handlers.py
  corehq/apps/sms/tests/opt_tests.py
  corehq/apps/sms/tests/test_backends.py
  corehq/apps/sms/tests/test_chat.py
  corehq/apps/sms/tests/test_dbaccessors.py
  corehq/apps/sms/tests/test_phone_numbers.py
  corehq/apps/sms/tests/test_queueing.py
  corehq/apps/sms/tests/test_registration.py
  corehq/apps/sms/tests/test_util.py
  corehq/apps/sms/tests/update_location_keyword_test.py
  corehq/apps/sms/tests/util.py
  corehq/apps/sms/urls.py
  corehq/apps/sms/util.py
  corehq/apps/sms/verify.py
  corehq/apps/sms/views.py
Labels: product/invisible

#19820 better error logging
  corehq/form_processor/reprocess.py
Labels: product/invisible

#19821 Remove gevent dependency from rebuildstaging
  scripts/rebuildstaging.py
Labels: product/invisible

#19773 make scheduled reports return 403 not 500
  corehq/apps/reports/views.py
Labels: product/invisible

#19824 remove is mobile from invitation form
  corehq/apps/registration/forms.py
Labels: product/all-users-all-environments

#19812 Add custom ICDS SMS rule criteria
  custom/icds/rules/custom_criteria.py
  custom/icds/tests/test_custom_rules.py
  settings.py
Labels: product/custom

#19825 Send bytestrings to sumo
  corehq/ex-submodules/phonelog/utils.py
Labels: product/invisible

#19822 Make rebuild_stock_state smaller
  corehq/apps/commtrack/views.py
Labels: product/feature-flag

#19823 [ICDS] create QRcode locally and don't use pygooglechart
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/__init__.py
  requirements/requirements.txt
Labels: product/custom
