Repository dimagi/commcare-hq, pull requests merged in 2019-11, with the labels that each got.

#25785 Catch TypeError when converting to int
  corehq/motech/openmrs/tests/test_serializers.py
  corehq/motech/serializers.py
  corehq/motech/tests/test_serializers.py
Labels: product/feature-flag

#25787 build in sanity checks in cchq_prbac_grandfather_privs
  corehq/apps/hqadmin/management/commands/cchq_prbac_grandfather_privs.py
Labels: product/all-users-all-environments

#25782 Ce/agg child from temp
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-child-health.distributed.txt
Labels: product/invisible

#25396 [ICDS Dashboard]Awc eligibility for performance report
  custom/icds_reports/tasks.py
Labels: product/custom

#25758 [ICDS Dashboard] Added growth monitoring indicator for wcd dashboard
  custom/icds_reports/migrations/0142_gm_column_agg_awc.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_5_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
Labels: product/custom

#25784 remove unused group views
  corehq/apps/cachehq/cachemodels.py
  corehq/apps/groups/_design/views/by_hierarchy_type/map.js
  corehq/apps/groups/_design/views/by_hierarchy_type/reduce.js
  corehq/apps/groups/_design/views/by_user_type/map.js
  corehq/apps/groups/_design/views/by_user_type/reduce.js
Labels: product/invisible

#25770 cache value in locmem between tasks
  corehq/apps/data_interfaces/models.py
Labels: product/invisible

#25788 Prune premature case diffs
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
  corehq/apps/couch_sql_migration/util.py
  corehq/util/teeout.py
  corehq/util/tests/test_teeout.py
Labels: product/invisible

#25750 Updated last_released header format
  corehq/apps/app_manager/views/download.py
Labels: product/invisible

#25790 Move PillowError actions to django admin (and remove old view & app)
  corehq/apps/hqadmin/views/system.py
  corehq/apps/hqpillow_retry/__init__.py
  corehq/apps/hqpillow_retry/filters.py
  corehq/apps/hqpillow_retry/management/__init__.py
  corehq/apps/hqpillow_retry/management/commands/__init__.py
  corehq/apps/hqpillow_retry/management/commands/run_pillow_retry_queue.py
  corehq/apps/hqpillow_retry/models.py
  corehq/apps/hqpillow_retry/static/hqpillow_retry/js/pillow_errors.js
  corehq/apps/hqpillow_retry/static/hqpillow_retry/js/single.js
  corehq/apps/hqpillow_retry/templates/hqpillow_retry/fb.txt
  corehq/apps/hqpillow_retry/templates/hqpillow_retry/pillow_errors.html
  corehq/apps/hqpillow_retry/templates/hqpillow_retry/single.html
  corehq/apps/hqpillow_retry/tests.py
  corehq/apps/hqpillow_retry/urls.py
  corehq/apps/hqpillow_retry/views.py
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/ex-submodules/pillow_retry/admin.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
  settings.py
  urls.py
Labels: product/admin

#25793 Resolve DeprecationWarnings from memoized
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#25717 Revert to daily feeding state based aggregation
  custom/icds_reports/README.md
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/daily_feeding_forms_child_health.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/daily-feeding-forms-child-health.distributed.txt
Labels: product/custom

#25792 change 21 day indicator text
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
Labels: product/custom

#25791 Remove recent couch changes view
  corehq/apps/hqadmin/static/hqadmin/js/couch_changes.js
  corehq/apps/hqadmin/templates/hqadmin/couch_changes.html
  corehq/apps/hqadmin/templates/hqadmin/system_info.html
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views/__init__.py
  corehq/apps/hqadmin/views/system.py
  corehq/tabs/tabclasses.py
Labels: product/admin

#25794 dont rely on naming that can change
  corehq/apps/hqadmin/views/data.py
Labels: product/invisible

#25796 Better fake for tee_output tests
  corehq/util/teeout.py
  corehq/util/tests/test_teeout.py
Labels: product/invisible

#25798 Add 'ndoh' to tracked domains
  settings.py
Labels: product/invisible

#25805 Fix Elasticsearch library regression for index prune command
  corehq/apps/hqadmin/management/commands/prune_elastic_indices.py
Labels: product/invisible

#25797 Don't export import-only Observations
  corehq/motech/openmrs/tests/test_workflow_tasks.py
  corehq/motech/openmrs/workflow_tasks.py
Labels: product/feature-flag

#25804 Update app manager README
  corehq/apps/app_manager/README.md
Labels: product/invisible

#25795 Notify admins on OpenmrsImporter errors
  corehq/motech/openmrs/models.py
  corehq/motech/openmrs/tasks.py
  corehq/motech/openmrs/tests/test_tasks.py
Labels: product/feature-flag

#25807 Remove some dead code
  corehq/apps/fixtures/tasks.py
  corehq/apps/reports/util.py
Labels: product/invisible

#25664 Hot-swap staging table with live table for agg_child_health
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/distributed/base.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-child-health.distributed.txt
Labels: product/custom

#25726 Batch user reporting metadata updates for app status report
  corehq/apps/receiverwrapper/util.py
  corehq/apps/users/migrations/0005_add_user_reporting_metadata.py
  corehq/apps/users/models.py
  corehq/apps/users/tasks.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_synclog_pillow.py
  corehq/ex-submodules/pillowtop/processors/form.py
  corehq/pillows/synclog.py
  settings.py
  testapps/test_pillowtop/tests/test_xform_pillow.py
Labels: product/invisible

#25781 Leave a tombstone when a domain is deleted
  .stickler.yml
  corehq/apps/accounting/models.py
  corehq/apps/domain/_design/views/deleted_domains/map.js
  corehq/apps/domain/_design/views/deleted_domains/reduce.js
  corehq/apps/domain/dbaccessors.py
  corehq/apps/domain/management/commands/delete_domain.py
  corehq/apps/domain/models.py
  corehq/apps/domain/shortcuts.py
  corehq/apps/domain/templates/domain/tombstone_management.html
  corehq/apps/domain/tests/test_dbaccessors.py
  corehq/apps/domain/utils.py
  corehq/apps/domain/views/tombstone.py
  corehq/apps/hqadmin/urls.py
  corehq/apps/reports/tests/test_filters.py
  corehq/apps/users/tests/create.py
  corehq/apps/users/tests/fixture_status.py
  corehq/form_processor/tests/test_basics.py
  corehq/tabs/tabclasses.py
  testapps/test_pillowtop/tests/test_domain_pillow.py
Labels: product/invisible

#25813 Remove ledgers from pillow map
  corehq/apps/hqcase/management/commands/ptop_preindex.py
Labels: product/invisible

#25812 fix bad reference to moved test module
  custom/icds_reports/management/commands/populate_local_db_with_icds_dashboard_test_data.py
Labels: product/invisible

#25806 Remove instances of LEDGER_INDEX_INFO
  corehq/apps/hqcase/management/commands/ptop_preindex.py
  corehq/elastic.py
  corehq/pillows/ledger.py
  corehq/pillows/mappings/ledger_mapping.json
  corehq/pillows/mappings/ledger_mapping.py
  corehq/pillows/utils.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: product/invisible

#25811 Use CELERY_BROKER_URL
  corehq/apps/hqadmin/service_checks.py
  corehq/apps/hqadmin/views/system.py
  settings.py
Labels: product/invisible

#25815 Batch App Status fixes
  corehq/apps/users/models.py
  corehq/pillows/synclog.py
  testapps/test_pillowtop/tests/test_xform_pillow.py
Labels: product/invisible

#25721 [ICDS Dashboard]Remove group by from view
  custom/icds_reports/migrations/0143_remove_group_by_thr_view.py
  custom/icds_reports/migrations/sql_templates/database_views/thr_report_view.sql
Labels: product/custom

#25817 Updated app manager README
  corehq/apps/app_manager/README.md
Labels: product/invisible

#25799 kafka producer audit logging
  corehq/apps/change_feed/management/commands/reconcile_producer_logs.py
  corehq/apps/change_feed/producer.py
  corehq/apps/change_feed/tests/test_producer_reconciliation.py
  settings.py
Labels: product/invisible

#25533 [ICDS Dashboard] fix for ICDS-922
  custom/icds_reports/static/icds_reports/js/spec/map-or-sector-view.directive.spec.js
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
Labels: product/custom

#25789 UCR/ES/Kafka reconciliation task
  custom/icds_reports/admin.py
  custom/icds_reports/migrations/0143_add_ucrreconciliationstatus_squashed.py
  custom/icds_reports/models/util.py
  custom/icds_reports/tasks.py
Labels: product/custom

#25823 Create merged migration
  custom/icds_reports/migrations/0144_merge_20191106_1522.py
Labels: product/invisible

#25819 single setting to override logging config
  dev_settings.py
  docker/localsettings.py
  settings.py
Labels: product/invisible

#25826 Revert "Renamed a few attributes in SMS/reminders"
  corehq/apps/reminders/forms.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/views.py
Labels: product/invisible

#25809 [ICDS Dashboard] Incorrect Aadhaar Spelling - Program Summary Demographics
  custom/icds_reports/messages.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/static/icds_reports/js/spec/adhaar-beneficiary.directive.spec.js
  custom/icds_reports/static/js/directives/adhaar-beneficiary/adhaar-beneficiary.directive.js
  custom/icds_reports/tests/agg_tests/reports/test_awc_reports.py
  custom/icds_reports/tests/agg_tests/reports/test_demographics.py
Labels: product/custom

#25820 Drop comment
  corehq/motech/requests.py
Labels: product/invisible

#25825 Revert "Remove signal firing from form submission metadata tracker pillow"
  corehq/ex-submodules/pillowtop/processors/form.py
Labels: product/invisible

#25829 Fix app status pillows when record already exists
  corehq/apps/users/models.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_synclog_pillow.py
  testapps/test_pillowtop/tests/test_xform_pillow.py
Labels: product/invisible

#25800 Automatically skip previous month aggregation
  custom/icds_reports/management/commands/create_aggregation_record.py
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/migrations/0145_add_interval_to_aggregationrecord.py
  custom/icds_reports/models/util.py
  custom/icds_reports/tests/test_utils.py
  custom/icds_reports/utils/aggregation_helpers/__init__.py
Labels: product/custom

#25720 Add new fields to CAS delivery UCRs
  corehq/apps/userreports/tests/test_rebuild_migrate.py
  custom/icds_reports/ucr/data_sources/ccs_record_cases.json
  custom/icds_reports/ucr/data_sources/dashboard/delivery_forms.json
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
  custom/icds_reports/ucr/tests/data/delivery_form_v10326.xml
  custom/icds_reports/ucr/tests/test_base_form_ucr.py
  custom/icds_reports/ucr/tests/test_delivery_form_ucr.py
  custom/icds_reports/ucr/tests/test_gm_form_ucr.py
Labels: product/custom

#25814 restructure plproxy config
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/sql/load.py
  corehq/form_processor/tests/test_sharding.py
  corehq/messaging/scheduling/scheduling_partitioned/tests/test_dbaccessors_partitioned.py
  corehq/sql_db/config.py
  corehq/sql_db/management/commands/configure_pl_proxy_cluster.py
  corehq/sql_db/migrations.py
  corehq/sql_db/routers.py
  corehq/sql_db/shard_data_management.py
  corehq/sql_db/tests/test_model_partitioning.py
  corehq/sql_db/tests/test_partition_config.py
  corehq/sql_db/tests/test_shard_management.py
  corehq/sql_db/tests/utils.py
  corehq/sql_db/util.py
  docker/localsettings.py
  localsettings.example.py
Labels: product/invisible

#25822 [ICDS Dashboard] username regex issue dashbaord usage
  custom/icds_reports/sqldata/exports/dashboard_usage.py
Labels: product/custom

#25818 [ICDS Dashboard] Locations appearing as IDs rather than names
  custom/icds_reports/sqldata/exports/dashboard_usage.py
Labels: product/custom

#25834 add notification with some info to begin with
  corehq/apps/receiverwrapper/util.py
Labels: product/custom

#25838 [ICDS Dashboard] Dashboard Usage report shows usernames as the complete login instead of just username
  custom/icds_reports/sqldata/exports/dashboard_usage.py
Labels: product/custom

#25840 Fix docstring
  corehq/motech/value_source.py
Labels: product/invisible

#25831 More flexible delete_domain command
  corehq/apps/domain/management/commands/delete_domain.py
  corehq/apps/domain/models.py
Labels: product/invisible

#25830 Fix tests on es2
  corehq/apps/api/odata/tests/test_feed.py
  corehq/apps/api/odata/tests/utils.py
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
  corehq/pillows/case_search.py
  corehq/pillows/user.py
  corehq/util/elastic.py
  testapps/test_pillowtop/tests/test_sms_pillow.py
Labels: product/invisible

#25832 Limit task to ICDS
  custom/icds_reports/tasks.py
Labels: product/invisible

#25841 Resolve DeprecationWarning
  corehq/motech/tests/test_value_source.py
Labels: product/invisible

#25827 Revert "Revert "Renamed a few attributes in SMS/reminders""
  corehq/apps/reminders/forms.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/views.py
  corehq/messaging/smsbackends/telerivet/forms.py
Labels: product/invisible

#25833 remove redundant py3 section of dev setup instructions
  DEV_SETUP.md
Labels: product/invisible

#25777 [ICDS Dashboard] LS launched indicator
  custom/icds_reports/migrations/0146_auto_20191030_1120.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tests/agg_tests/outputs/agg_ls_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_ls_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_ls_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_ls_2017-05-01_4_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_ls_data.py
  custom/icds_reports/utils/aggregation_helpers/distributed/ls_awc_visit_form.py
  custom/icds_reports/utils/aggregation_helpers/distributed/ls_beneficiary_form.py
  custom/icds_reports/utils/aggregation_helpers/distributed/ls_vhnd_form.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-ls.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/ls-awc-mgt-form.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/ls-beneficiary-form.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/ls-vhnd-form.distributed.txt
Labels: product/custom

#25845 fix syntax error 'AttributeError: 'Settings' object has no attribute …
  corehq/sql_db/config.py
Labels: product/invisible

#25835 ICDS dashboard login page customizations prework
  corehq/apps/hqwebapp/login_utils.py
  corehq/apps/hqwebapp/tests/test_custom_login_page.py
  corehq/apps/hqwebapp/views.py
  custom/icds/tests/test_views.py
  custom/icds_reports/mobile_views.py
  custom/icds_reports/templates/icds_reports/mobile_login.html
  custom/icds_reports/urls.py
Labels: product/invisible

#25847 Do not silently ignore LOCAL_LOGGING_CONFIG keys
  settings.py
Labels: product/invisible

#25846 Added deprecation warnings to exchange
  corehq/apps/appstore/views.py
  corehq/apps/domain/views/exchange.py
Labels: product/all-users-all-environments

#25854 restore pillow retry queue
  corehq/ex-submodules/pillow_retry/management/commands/run_pillow_retry_queue.py
Labels: product/invisible

#25844 refactor sql_db.connection_manager to make it easier to reason about
  corehq/apps/callcenter/tests/test_indicators.py
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/sql/connection.py
  corehq/apps/userreports/sql/data_source.py
  corehq/apps/userreports/tests/test_multi_db.py
  corehq/sql_db/connections.py
  corehq/sql_db/routers.py
  corehq/sql_db/tests/test_connections.py
  corehq/sql_db/tests/test_routers.py
  corehq/sql_db/util.py
Labels: product/invisible

#25851 [IntraHealth] Fix for "Recap Passage 2"
  custom/intrahealth/sqldata.py
Labels: product/custom

#25857 Improve error propagation during gevent pooled aggregation commands
  custom/icds_reports/management/commands/run_aggregation_query.py
Labels: product/invisible

#25842 [ICDS Dashboard] Made domain name static
  custom/icds_reports/sqldata/exports/dashboard_usage.py
Labels: product/custom

#25852 [ICDS Dashboard] Disclaimer/Info is present above the Report Filters on the Dashboard
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#25839 Better error message
  corehq/motech/openmrs/repeater_helpers.py
Labels: product/invisible

#25860 Nit: Drop irrelevant args
  corehq/motech/value_source.py
Labels: product/invisible

#25855 Docs for DB configuration
  docs/Makefile
  docs/conf.py
  docs/databases.rst
  docs/images/django_db_monolith.png
  docs/images/django_db_sharded.png
  docs/index.rst
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#25869 add ability to "take the dashboard down" with a feature flag
  corehq/toggles.py
  custom/icds_reports/templates/icds_reports/dashboard_down.html
  custom/icds_reports/views.py
Labels: product/custom

#25866 properly handle greenlet errors in child health monthly
  custom/icds_reports/tasks.py
Labels: product/invisible

#25861 Refactor ConstantValue
  corehq/motech/tests/test_value_source.py
  corehq/motech/value_source.py
Labels: product/invisible

#25843 use temp child table for agg_awc
  custom/icds_reports/utils/aggregation_helpers/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
Labels: product/custom

#25821 Catch bad request, bad response
  corehq/motech/openmrs/tasks.py
Labels: product/feature-flag

#25872 [ICDS Dashboard] Added last 7 days filter for dashboard uage report
  custom/icds_reports/sqldata/exports/dashboard_usage.py
Labels: product/custom

#25867 [ICDS Dashboard] Block column is populated with locations instead of 'All' for district user
  custom/icds_reports/sqldata/exports/dashboard_usage.py
Labels: product/custom

#25856 Make delete_domain a little smoother
  corehq/apps/domain/models.py
Labels: product/invisible

#25862 Import Observations as extension cases
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/openmrs_config.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/tests/test_atom_feed.py
  corehq/motech/tests/test_value_source.py
  corehq/motech/value_source.py
Labels: product/feature-flag

#25757 Add app id to SMS surveys and structured SMS keyword actions
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/app_manager/util.py
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
  corehq/apps/domain/views/exchange.py
  corehq/apps/ivr/migrations/0002_call_app_id.py
  corehq/apps/ivr/models.py
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/migrations/0002_app_id.py
  corehq/apps/reminders/models.py
  corehq/apps/reminders/static/reminders/js/reminders.keywords.ko.js
  corehq/apps/reminders/util.py
  corehq/apps/reminders/views.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/migrations/0037_app_id.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tests/inbound_handlers.py
  corehq/apps/sms/tests/util.py
  corehq/messaging/scheduling/async_handlers.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0024_app_id.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_main.js
  corehq/messaging/scheduling/views.py
  custom/ewsghana/forms.py
  testapps/test_pillowtop/tests/test_sms_pillow.py
Labels: QA Passed, product/invisible

#25884 Revert "Add app id to SMS surveys and structured SMS keyword actions"
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/app_manager/util.py
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
  corehq/apps/domain/views/exchange.py
  corehq/apps/ivr/migrations/0002_call_app_id.py
  corehq/apps/ivr/models.py
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/migrations/0002_app_id.py
  corehq/apps/reminders/models.py
  corehq/apps/reminders/static/reminders/js/reminders.keywords.ko.js
  corehq/apps/reminders/util.py
  corehq/apps/reminders/views.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/migrations/0037_app_id.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tests/inbound_handlers.py
  corehq/apps/sms/tests/util.py
  corehq/messaging/scheduling/async_handlers.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0024_app_id.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_main.js
  corehq/messaging/scheduling/views.py
  custom/ewsghana/forms.py
  testapps/test_pillowtop/tests/test_sms_pillow.py
Labels: product/invisible

#25850 Add button to force 412s for a user's device on next sync
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/urls.py
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#25870 Make bypass-sessions into a random toggle
  corehq/middleware.py
  corehq/toggles.py
Labels: product/invisible

#25885 Add option to migrate skipped forms
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
Labels: product/invisible

#25894 [ci skip] language change request from support
  custom/icds_reports/templates/icds_reports/dashboard_down.html
Labels: product/custom

#25888 [ICDS Dashboard] Reformatted the date , added 'N/A' for empty values and fixed the sr no issue in dashboard usage report
  custom/icds_reports/sqldata/exports/dashboard_usage.py
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#25863 Update mpr 4b infra forms report
  custom/icds_reports/ucr/reports/mpr/ucr_v2/mpr_4b_iodized_salt.json
Labels: product/custom

#25890 Strip loc_type name in view
  corehq/apps/locations/views.py
Labels: product/invisible

#25887 Revert 25884 revert 25757 jls/add app id to sms surveys and keywords
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/app_manager/util.py
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
  corehq/apps/domain/views/exchange.py
  corehq/apps/ivr/migrations/0002_call_app_id.py
  corehq/apps/ivr/models.py
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/migrations/0002_app_id.py
  corehq/apps/reminders/models.py
  corehq/apps/reminders/static/reminders/js/reminders.keywords.ko.js
  corehq/apps/reminders/util.py
  corehq/apps/reminders/views.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/migrations/0037_app_id.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tests/inbound_handlers.py
  corehq/apps/sms/tests/util.py
  corehq/messaging/scheduling/async_handlers.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0024_app_id.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_main.js
  corehq/messaging/scheduling/views.py
  custom/ewsghana/forms.py
  testapps/test_pillowtop/tests/test_sms_pillow.py
Labels: product/feature-flag

#25875 memoize filter_out_stale_standbys cache storage
  corehq/sql_db/util.py
Labels: product/invisible

#25891 use correct type
  corehq/form_processor/models.py
Labels: product/invisible

#25886 Fix tests on es 2.4.1
  corehq/apps/api/odata/tests/test_feed.py
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/es/filters.py
  corehq/apps/es/tests/test_filters.py
  corehq/apps/reports/tests/test_esaccessors.py
  testapps/test_pillowtop/tests/test_xform_pillow.py
Labels: product/invisible

#25897 Added flag to ignore remote apps in SMS app id migration
  corehq/apps/app_manager/util.py
Labels: product/invisible

#25895 make agg child indices on staging table
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-child-health.distributed.txt
Labels: product/invisible

#25896 Added a few eslint rules
  .eslintrc.js
Labels: product/invisible

#25741 Removed IVR reports
  corehq/apps/reports/standard/ivr.py
  corehq/reports.py
Labels: product/all-users-all-environments

#25904 Remove ews and ils tests
  custom/ewsghana/tests/__init__.py
  custom/ewsghana/tests/data/sample_dailyreports.json
  custom/ewsghana/tests/data/sample_locations.json
  custom/ewsghana/tests/data/sample_monthlyreports.json
  custom/ewsghana/tests/data/sample_products.json
  custom/ewsghana/tests/data/sample_smsusers.json
  custom/ewsghana/tests/data/sample_stocktransactions.json
  custom/ewsghana/tests/data/sample_webusers.json
  custom/ewsghana/tests/data/sample_weeklyreports.json
  custom/ewsghana/tests/ews_test_reminders.py
  custom/ewsghana/tests/handlers/__init__.py
  custom/ewsghana/tests/handlers/default.py
  custom/ewsghana/tests/handlers/formatter.py
  custom/ewsghana/tests/handlers/handler.py
  custom/ewsghana/tests/handlers/receipt.py
  custom/ewsghana/tests/handlers/reminder.py
  custom/ewsghana/tests/handlers/requisition_status.py
  custom/ewsghana/tests/handlers/stock_on_hand.py
  custom/ewsghana/tests/handlers/undo.py
  custom/ewsghana/tests/handlers/utils.py
  custom/ewsghana/tests/test_alerts.py
  custom/ewsghana/tests/test_calculate_last_period.py
  custom/ewsghana/tests/test_delete_domain.py
  custom/ewsghana/tests/test_input_stock_view.py
  custom/ewsghana/tests/test_notifications.py
  custom/ewsghana/tests/test_reminders.py
  custom/ewsghana/tests/test_urgent_alerts.py
  custom/ewsghana/tests/test_utils.py
  custom/ilsgateway/tests/__init__.py
  custom/ilsgateway/tests/data/sample_deliverygroupreports.json
  custom/ilsgateway/tests/data/sample_locations.json
  custom/ilsgateway/tests/data/sample_products.json
  custom/ilsgateway/tests/data/sample_productstocks.json
  custom/ilsgateway/tests/data/sample_smsusers.json
  custom/ilsgateway/tests/data/sample_stocktransactions.json
  custom/ilsgateway/tests/data/sample_supplypointstatuses.json
  custom/ilsgateway/tests/data/sample_webusers.json
  custom/ilsgateway/tests/handlers/__init__.py
  custom/ilsgateway/tests/handlers/stockonhand.py
  custom/ilsgateway/tests/handlers/stockout.py
  custom/ilsgateway/tests/handlers/utils.py
  custom/ilsgateway/tests/test_delete_domain.py
  custom/ilsgateway/tests/test_handlers.py
  custom/ilsgateway/tests/test_parse_report.py
  custom/ilsgateway/tests/test_reminders.py
  custom/ilsgateway/tests/test_reminders2.py
  custom/ilsgateway/tests/test_report_reminders.py
  custom/ilsgateway/tests/test_script.py
  custom/ilsgateway/tests/utils.py
Labels: product/custom

#25868 Mk/compare mm size 2
  corehq/apps/app_manager/static/app_manager/js/source_files.js
  corehq/apps/app_manager/templates/app_manager/app_diff.html
  corehq/apps/app_manager/templates/app_manager/partials/multimedia_sizes.html
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/multimedia.py
  corehq/apps/app_manager/views/utils.py
Labels: product/feature-flag

#25878 [ICDS Dashboard] Header text 'Tabular Report Download Frequency (Last 1 week)' is missing from the CSV download of the Dashboard Usage Report
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#25899 Removed LOCATION_SAFETY_EXEMPTION feature flag
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/static/users/js/roles_and_permissions.js
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/apps/users/templates/users/roles_and_permissions.html
  corehq/apps/users/views/__init__.py
  corehq/toggles.py
Labels: product/feature-flag

#25900 Removed feature flag EWS_INVALID_REPORT_RESPONSE
  corehq/toggles.py
  custom/ewsghana/handlers/soh.py
Labels: product/feature-flag

#25901 Removed EWS_WEB_USER_EXTENSION feature flag
  corehq/apps/users/templates/users/edit_web_user.html
  corehq/toggles.py
  custom/ewsghana/forms.py
  custom/ewsghana/templates/ewsghana/user_extension.html
  custom/ewsghana/urls.py
  custom/ewsghana/views.py
Labels: product/feature-flag

#25905 Removed MULTIPLE_CHOICE_CUSTOM_FIELD feature flag
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
  corehq/apps/custom_data_fields/templates/custom_data_fields/custom_data_fields.html
  corehq/toggles.py
Labels: product/feature-flag

#25776 Remove xforms index
  corehq/apps/app_manager/_design/views/xforms_index/map.js
  corehq/apps/app_manager/exceptions.py
  corehq/apps/app_manager/models.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/reminders/views.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/models.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/models/content.py
Labels: product/feature-flag, product/invisible, reindex/migration

#25892 refactor standby DB config
  corehq/sql_db/__init__.py
  corehq/sql_db/tests/test_checks.py
  corehq/sql_db/tests/test_connections.py
  corehq/sql_db/tests/test_routers.py
  corehq/sql_db/util.py
  docs/databases.rst
Labels: product/invisible

#25906 Removed CUSTOM_MENU_BAR feature flag
  corehq/apps/dashboard/views.py
  corehq/apps/domain/utils.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/feature-flag

#25902 Removed EWS_BROADCAST_BY_ROLE feature flag
  corehq/messaging/scheduling/views.py
  corehq/toggles.py
  custom/ewsghana/forms.py
Labels: product/feature-flag

#25910 Removed USE_SMS_WITH_INACTIVE_CONTACTS flag
  corehq/apps/sms/tasks.py
  corehq/toggles.py
Labels: product/feature-flag

#25858 Fix line item logic when multiple subscriptions are present in account level invoices
  corehq/apps/accounting/invoice_pdf.py
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/tests/test_customer_invoicing.py
Labels: product/all-users-all-environments

#25849 [ICDS Dashboard] MWCD API view
  corehq/toggles.py
  custom/icds_reports/migrations/0147_mwcd_report_view.py
  custom/icds_reports/migrations/sql_templates/database_views/mwcd_dashboard.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/reports/mwcd_indicators.py
  custom/icds_reports/tests/agg_tests/test_nic_indicators_api.py
  custom/icds_reports/urls.py
  custom/icds_reports/views.py
Labels: product/custom

#25871 [ICDS Dashboard]New Ls launched definition
  custom/icds_reports/tasks.py
  custom/icds_reports/ucr/data_sources/ls_app_usage_forms.json
  custom/icds_reports/ucr/tests/data/ls_home_visits.xml
  custom/icds_reports/ucr/tests/test_ls_usage_ucr.py
  settings.py
Labels: product/custom

#25915 Change dict -> set
  custom/icds_reports/tasks.py
Labels: product/custom

#25918 Fix single case api, broken by ES refactor
  corehq/apps/api/es.py
Labels: product/invisible

#25909 Removed LOGIN_AS_ALWAYS_OFF feature flag
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/toggles.py
Labels: product/feature-flag

#25913 Speed up User API with an ES backend (under a toggle)
  corehq/apps/api/query_adapters.py
  corehq/apps/api/resources/v0_1.py
  corehq/apps/api/tests/user_resources.py
  corehq/apps/users/analytics.py
  corehq/toggles.py
Labels: product/invisible

#25911 Removed LOCATION_TYPE_STOCK_RATES feature flag
  corehq/apps/commtrack/forms.py
  corehq/apps/commtrack/static/commtrack/js/stock_levels.js
  corehq/apps/commtrack/templates/commtrack/manage/stock_levels.html
  corehq/apps/commtrack/urls.py
  corehq/apps/commtrack/views.py
  corehq/apps/locations/models.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/feature-flag

#25914 Removed EWSLocationResource API test
  corehq/apps/api/tests/internal_resources.py
Labels: product/invisible

#25908 Updated info about Dimagi-only test subscription
  corehq/apps/domain/forms.py
Labels: product/admin

#25927 Updated general migration docs
  docs/migrations.rst
Labels: product/invisible

#25922 Removed "if app" condition from managed_app.html
  corehq/apps/app_manager/templates/app_manager/apps_base.html
  corehq/apps/app_manager/templates/app_manager/import_app.html
  corehq/apps/app_manager/templates/app_manager/managed_app.html
  corehq/apps/app_manager/templates/app_manager/partials/new_app_buttons.html
Labels: product/invisible

#25928 Add environment more prominently to preindex emails
  corehq/apps/hqadmin/management/commands/preindex_everything.py
Labels: product/invisible

#25921 Mk/update notification
  corehq/apps/receiverwrapper/util.py
Labels: product/invisible

#25923 Ignore weird user ids when marking latest submission.
  corehq/ex-submodules/pillowtop/processors/form.py
Labels: product/invisible

#25736 Remove uses_master_app_form_ids
  corehq/apps/app_manager/migrations/0008_remove_uses_master_app_form_ids.py
  corehq/apps/app_manager/models.py
Labels: product/invisible

#25930 Sort group_ids in user api to normalize the output
  corehq/apps/api/query_adapters.py
Labels: product/invisible

#25931 Remove confirm dialog from Force Full Refresh UI
  corehq/apps/users/templates/users/edit_commcare_user.html
Labels: product/invisible

#25941 Added output to preindex_everything --check
  corehq/apps/hqadmin/management/commands/preindex_everything.py
Labels: product/invisible

#25936 [ICDS Dashboard] fix for string to int conversion in indicator count
  custom/icds_reports/sqldata/exports/dashboard_usage.py
Labels: product/custom

#25876 ICDS dashboard refactoring
  custom/icds_reports/dashboard_utils.py
  custom/icds_reports/static/icds_reports/js/spec/program-summary.directive.spec.js
  custom/icds_reports/static/js/directives/program-summary/program-summary.directive.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/program-summary.directive.html
  custom/icds_reports/templates/icds_reports/partials/dashboard_initial_page_data.html
  custom/icds_reports/templates/icds_reports/partials/register_dashboard_urls.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
  custom/icds_reports/views.py
Labels: product/custom

#25948 [ICDS Dashboard] Ignoring the dashboard usage count in the report
  custom/icds_reports/sqldata/exports/dashboard_usage.py
Labels: product/custom

#25938 [ICDS Dashboard]fix home visit calculation in SDD
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/agg_tests/reports/test_service_delivery.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
Labels: product/custom

#25944 Kill most ewsghana views
  custom/ewsghana/forms.py
  custom/ewsghana/handlers/web_submission_handler.py
  custom/ewsghana/templates/ewsghana/global_stats.html
  custom/ewsghana/templates/ewsghana/input_stock.html
  custom/ewsghana/urls.py
  custom/ewsghana/views.py
Labels: product/custom

#25907 Fix agg skipping logic
  custom/icds_reports/management/commands/create_aggregation_record.py
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/migrations/0148_auto_20191112_2123.py
  custom/icds_reports/models/util.py
  custom/icds_reports/tests/test_agg_skipping.py
  custom/icds_reports/tests/test_utils.py
  custom/icds_reports/utils/aggregation_helpers/__init__.py
Labels: product/custom

#25824 [VectorLink] Exclude deactivated users from 'Late PMT' report
  custom/abt/reports/data_sources/late_pmt.json
Labels: product/custom

#25836 Drop openmrs.logger
  corehq/motech/openmrs/finders.py
  corehq/motech/openmrs/logger.py
  corehq/motech/openmrs/repeaters.py
Labels: product/invisible

#25864 Compare Multimedia Size
  corehq/apps/app_manager/static/app_manager/js/download_index_main.js
  corehq/apps/app_manager/static/app_manager/js/multimedia_size_util.js
  corehq/apps/app_manager/static/app_manager/js/source_files.js
  corehq/apps/app_manager/templates/app_manager/app_diff.html
  corehq/apps/app_manager/templates/app_manager/download_index.html
  corehq/apps/app_manager/templates/app_manager/partials/multimedia_sizes.html
  corehq/apps/app_manager/templates/app_manager/source_files.html
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/multimedia.py
  corehq/apps/app_manager/views/utils.py
Labels: product/feature-flag

#25951 Fix intermittent js test failures: don't overwrite initial_page_data urls
  corehq/apps/hqwebapp/static/hqwebapp/js/initial_page_data.js
Labels: product/invisible

#25880 Templated sum when
  corehq/apps/userreports/README.rst
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/factory.py
  corehq/apps/userreports/reports/specs.py
  corehq/apps/userreports/sql/columns.py
  corehq/apps/userreports/tests/test_columns.py
  corehq/apps/userreports/tests/test_report_aggregation.py
  corehq/toggles.py
  custom/icds_reports/sqldata/agg_ccs_record_monthly.py
  custom/icds_reports/sqldata/agg_child_health_monthly.py
  custom/icds_reports/sqldata/exports/children.py
  custom/icds_reports/sqldata/exports/demographics.py
  custom/icds_reports/sqldata/exports/pregnant_women.py
  custom/icds_reports/ucr/reports/asr/asr_2_3_person_cases.json
  custom/icds_reports/ucr/reports/asr/ucr_v2/asr_2_3_beneficiaries.json
  custom/icds_reports/ucr/reports/dashboard/asr_2_3_person_cases.json
  custom/icds_reports/ucr/reports/mpr/dashboard/mpr_10ab_person_cases.json
  custom/icds_reports/ucr/reports/mpr/mpr_10a_person_cases.json
  custom/icds_reports/ucr/reports/mpr/mpr_10b_person_cases.json
  custom/icds_reports/ucr/reports/mpr/mpr_1_person_cases.json
  custom/icds_reports/ucr/reports/mpr/mpr_2a_person_cases.json
  custom/icds_reports/ucr/reports/mpr/mpr_2bi_preg_delivery_death_list.json
  custom/icds_reports/ucr/reports/mpr/mpr_3i_person_cases.json
  custom/icds_reports/ucr/reports/mpr/mpr_3ii_person_cases.json
  custom/icds_reports/ucr/reports/mpr/ucr_v2/mpr_10a_children_referred.json
  custom/icds_reports/ucr/reports/mpr/ucr_v2/mpr_10b_pregnancies_referred.json
  custom/icds_reports/ucr/reports/mpr/ucr_v2/mpr_2a_deaths.json
  custom/icds_reports/ucr/reports/mpr/ucr_v2/mpr_3_children_registered.json
  custom/icds_reports/ucr/reports/mpr/ucr_v2/mpr_3i_pregnancies.json
  custom/up_nrhm/sql_data.py
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/feature-flag

#25925 CasePropertyConstantValue
  corehq/motech/openmrs/tests/test_atom_feed.py
  corehq/motech/tests/test_value_source.py
  corehq/motech/value_source.py
Labels: product/invisible

#25924 Test JsonPathCasePropertyMap
  corehq/motech/openmrs/tests/test_atom_feed.py
Labels: product/invisible

#25937 OpenMRS Atom feed owner_id
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/tasks.py
  corehq/motech/openmrs/tests/test_atom_feed.py
Labels: product/invisible

#25952 better icds login screen on smaller devices
  custom/icds/templates/icds/login.html
Labels: product/custom

#25917 ICDS Dashboard: rename locations when populating local data
  custom/icds_reports/management/commands/populate_local_db_with_icds_dashboard_test_data.py
Labels: product/custom

#25689 use indicator strings instead of magic numbers in data exports
  custom/icds_reports/queries.py
  custom/icds_reports/static/js/directives/cas-export/cas-export.directive.js
  custom/icds_reports/tests/agg_tests/test_cas_data_export.py
  custom/icds_reports/views.py
Labels: product/invisible

#25935 mobile dashboard prototype landing page
  corehq/apps/hqwebapp/views.py
  custom/icds_reports/mobile_views.py
  custom/icds_reports/static/icds_reports/js/spec/kpi.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/program-summary.directive.spec.js
  custom/icds_reports/static/js/angular-services/template-provider.service.js
  custom/icds_reports/static/js/directives/kpi/kpi.directive.js
  custom/icds_reports/static/js/directives/program-summary/program-summary.directive.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/kpi.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/program-summary.directive.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
  custom/icds_reports/templates/icds_reports/mobile_login.html
  custom/icds_reports/templates/icds_reports/partials/dashboard_initial_page_data.html
  custom/icds_reports/templates/icds_reports/partials/register_dashboard_urls.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
  custom/icds_reports/urls.py
  custom/icds_reports/views.py
Labels: product/custom

#25883 Drop unnecessary method
  corehq/motech/value_source.py
Labels: product/invisible

#25881 Notify admins of errors sending Events to DHIS2
  corehq/motech/dhis2/events_helpers.py
  corehq/motech/dhis2/repeaters.py
Labels: product/invisible

#25965 [ci skip] remove czue from dashboard codeowners
  .github/CODEOWNERS
Labels: product/invisible

#25960 [ICDS Dashboard] added the ls indicator to api
  custom/icds_reports/reports/mwcd_indicators.py
  custom/icds_reports/tests/agg_tests/test_nic_indicators_api.py
Labels: product/custom

#25953 Refactor stagnant case calculation
  custom/icds_reports/tasks.py
Labels: product/custom
