Repository dimagi/commcare-hq, pull requests merged in 2019-07, with the labels that each got.

#24634 Unicode name in Unicode name test
  corehq/blobs/tests/test_fsdb.py
Labels: product/invisible

#24694 Remove redundant method
  corehq/apps/linked_domain/remote_accessors.py
Labels: product/invisible

#24687 fix csv342 imports in Python 3
  custom/icds_reports/management/commands/export_inactive_dashboard_users.py
  custom/icds_reports/tests/test_inactive_dashboard_users.py
Labels: product/invisible

#24690 allow for inline editing an Odata feed name
  corehq/apps/export/static/export/js/export_list.js
  corehq/apps/export/templates/export/partials/table.html
  corehq/apps/export/urls.py
  corehq/apps/export/views/edit.py
  corehq/apps/export/views/list.py
Labels: product/feature-flag

#24684 forms_not_in_es management command
  corehq/apps/hqadmin/management/commands/forms_not_in_es.py
Labels: product/invisible

#24697 run modernize
  corehq/blobs/tests/test_fsdb.py
  custom/icds_reports/ucr/tests/test_thr_v2_ucr.py
Labels: product/invisible

#24689 remove age range changes from feature flag
  custom/icds_reports/reports/maternal_child.py
Labels: product/invisible

#24698 upgrade django to latest security fix
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#24681 Remove enabling feature for just user from app status report
  corehq/apps/reports/standard/deployments.py
  corehq/toggles.py
Labels: product/custom

#24699 'Copy' -> 'Save'
  corehq/apps/export/static/export/js/models.js
Labels: product/feature-flag

#24652 Add ability to migrate transifex project
  corehq/apps/translations/exceptions.py
  corehq/apps/translations/forms.py
  corehq/apps/translations/integrations/transifex/const.py
  corehq/apps/translations/integrations/transifex/exceptions.py
  corehq/apps/translations/integrations/transifex/project_migrator.py
  corehq/apps/translations/integrations/transifex/views.py
  corehq/apps/translations/tasks.py
  corehq/apps/translations/templates/migrate_project.html
  corehq/apps/translations/urls.py
  corehq/tabs/tabclasses.py
Labels: product/custom, product/feature-flag

#24701 use correct column name
  custom/icds_reports/utils/aggregation_helpers/distributed/inactive_awws.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/inactive-awws.distributed.txt
Labels: product/invisible

#24676 Disable collect_inactive_awws on all but ICDS_ENVS
  custom/icds_reports/tasks.py
Labels: product/invisible

#24700 update help text when export multi-sort flag is enabled
  corehq/apps/export/templates/export/partials/new_customize_export_templates.html
Labels: product/feature-flag

#24696 Already logged
  corehq/motech/openmrs/tasks.py
Labels: product/invisible

#24680 Retry task when standby cancels the query, also track in DD
  corehq/util/sentry.py
  custom/icds_reports/reports/disha.py
Labels: product/custom

#24703 make OData feed description editable
  corehq/apps/export/static/export/js/export_list.js
  corehq/apps/export/templates/export/partials/table.html
  corehq/apps/export/urls.py
  corehq/apps/export/views/edit.py
  corehq/apps/export/views/list.py
Labels: product/feature-flag

#24626 Rn aggregate thr image data
  custom/icds_reports/const.py
  custom/icds_reports/migrations/0125_aggregatethrform.py
  custom/icds_reports/migrations/0126_agg_awc_image_column.py
  custom/icds_reports/migrations/sql_templates/update_tables47.sql
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/fixtures/thr_form_v2.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_5_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/distributed/thr_form_v2.py
  custom/icds_reports/utils/aggregation_helpers/helpers.py
  custom/icds_reports/utils/aggregation_helpers/monolith/__init__.py
  custom/icds_reports/utils/aggregation_helpers/monolith/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/monolith/thr_form_v2.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc_weekly.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc_weekly.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/thr-form-v2.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/thr-form-v2.monolith.txt
Labels: product/custom, product/invisible

#24636 Added THR db view
  custom/icds_reports/migrations/0127_thr_report_view.py
  custom/icds_reports/migrations/sql_templates/database_views/thr_report_view.sql
  custom/icds_reports/models/views.py
Labels: product/custom

#24706 Ability to specify custom pillow reorg mapping and run check mode by default
  corehq/ex-submodules/pillowtop/management/commands/create_checkpoints_for_merged_pillows.py
Labels: product/custom

#24707 Disambiguate parent/child relationship
  corehq/ex-submodules/casexml/apps/phone/tests/test_extension_indexes.py
Labels: product/invisible

#24712 pip-compile should update the requirements.txt matching the Python version
  Makefile
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  requirements/prod-requirements.in
  requirements/prod-requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
Labels: product/invisible

#24711 Make conditionally_location_safe importer appear
  corehq/apps/case_importer/base.py
  corehq/apps/locations/permissions.py
Labels: product/feature-flag

#24617 Added named variables to translation strings
  corehq/apps/translations/app_translations/upload_app.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: product/invisible

#24702 Fix encoder for citus/UCR comparisons
  corehq/apps/userreports/migrations/0015_auto_20190701_2006.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/tasks.py
Labels: product/invisible

#24691 Allow setting practice mobile worker on Linked App
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/json/commcare-app-settings.yaml
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
Labels: product/feature-flag

#24714 Fix test-make-requirements.sh
  scripts/test-make-requirements.sh
Labels: product/invisible

#24718 Updated test value for flavor to be more realistic
  corehq/apps/app_manager/static/app_manager/spec/releases_spec.js
Labels: product/invisible

#24722 run tests in Python 3 if flag is provided in test matrix
  .travis.yml
Labels: product/invisible

#24654 Generate thr excel report(xlsx/csv)
  custom/icds_reports/const.py
  custom/icds_reports/reports/take_home_ration.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/views.py
Labels: Open for review: do not merge, product/custom

#24719 better naming
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/views/releases.py
Labels: product/invisible

#24692 Add view for profile based app releases
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/serializers.py
  corehq/apps/app_manager/static/app_manager/js/manage_releases_by_app_profile.js
  corehq/apps/app_manager/static/app_manager/js/manage_releases_by_location.js
  corehq/apps/app_manager/views/releases.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/domain/manage_releases_by_app_profile.html
  corehq/apps/domain/templates/domain/manage_releases_by_location.html
  corehq/apps/domain/urls.py
  corehq/apps/domain/views/releases.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#24721 Added except blocks for CaseError thrown when getting case properties
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/app_manager/views/view_generic.py
Labels: product/feature-flag

#24720 Removed advanced modules warning
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#24716 handle loss of internet connection when submitting forms in webapps
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
Labels: product/all-users-all-environments

#24725 Codify CCHQ_IS_FRESH_INSTALL for wider use
  corehq/apps/sms/migration_status.py
  corehq/apps/userreports/migrations/0009_rename_ucr_tables.py
  corehq/blobs/migrations/0001_squashed_0009_domains.py
  corehq/doctypemigrations/djangomigrations.py
  corehq/util/django_migrations.py
Labels: product/invisible

#24731 remove obsolete comment
  .travis.yml
Labels: product/invisible

#24695 update text on feature previews page
  corehq/apps/domain/templates/domain/admin/feature_previews.html
Labels: product/all-users-all-environments

#24709 Cousins sync bug
  corehq/ex-submodules/casexml/apps/phone/models.py
Labels: product/invisible

#24686 configure case OData feed
  corehq/apps/api/odata/serializers.py
  corehq/apps/api/odata/tests/data/populated_case_odata_metadata_document_from_config.xml
  corehq/apps/api/odata/tests/test_feed.py
  corehq/apps/api/odata/tests/test_metadata.py
  corehq/apps/api/odata/tests/test_serializers.py
  corehq/apps/api/odata/tests/test_service.py
  corehq/apps/api/odata/tests/utils.py
  corehq/apps/api/odata/utils.py
  corehq/apps/api/odata/views.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/templates/api/case_odata_metadata.xml
  corehq/apps/api/urls.py
  corehq/apps/export/dbaccessors.py
  corehq/apps/export/static/export/js/export_list.js
  corehq/apps/export/views/list.py
Labels: product/feature-flag

#24715 Don't trigger a reorder when changing module settings
  corehq/apps/app_manager/static/app_manager/js/app_manager.js
Labels: product/feature-flag

#24730 Update end of form nav "previous screen" to support parent/child menus
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/data/form_workflow/suite-workflow-module-in-root.xml
  corehq/apps/app_manager/tests/data/form_workflow/suite-workflow-module.xml
  corehq/apps/app_manager/tests/data/form_workflow/suite-workflow-previous.xml
  corehq/apps/app_manager/tests/data/form_workflow/suite-workflow-root.xml
  corehq/apps/app_manager/tests/data/suite/child-module-form-workflow-previous.xml
  corehq/apps/app_manager/tests/test_form_workflow.py
Labels: product/feature-flag

#24734 Removed J2ME app settings from UI for non-J2ME builds
  corehq/apps/app_manager/commcare_settings.py
  corehq/apps/app_manager/views/apps.py
Labels: product/all-users-all-environments

#24738 allow setting OData feature flag at user level
  corehq/toggles.py
Labels: product/feature-flag

#24728 Add note field
  corehq/toggles.py
  custom/icds/forms.py
  custom/icds/migrations/0005_hostedccz_note.py
  custom/icds/models.py
  custom/icds/serializers.py
  custom/icds/static/icds/js/manage_hosted_ccz.js
  custom/icds/templates/icds/manage_hosted_ccz.html
  custom/icds/tests/serializers/test_hosted_ccz_serializer.py
Labels: product/custom, product/feature-flag

#24708 create targeted ccz if build has commcare flavor set
  corehq/apps/app_manager/models.py
  custom/icds/tasks/hosted_ccz.py
Labels: product/feature-flag

#24473 Removed overly broad exception handling from app building
  corehq/apps/app_manager/helpers/validators.py
Labels: product/invisible

#24739 set custom max_limit and default limit for OData case feed
  corehq/apps/api/resources/v0_5.py
  corehq/apps/export/views/list.py
Labels: product/feature-flag

#24737 send OData metrics to datadog
  corehq/apps/api/odata/utils.py
  corehq/apps/api/resources/v0_5.py
Labels: product/invisible

#24713 fix comparison of data with Decimals and dates
  corehq/apps/userreports/laboratory/experiment.py
Labels: product/invisible

#24726 remove soft asserts
  corehq/apps/reports/sqlreport.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/parsers/form.py
Labels: product/invisible

#24742 Manage lookup tables page: stop fetching tables twice
  corehq/apps/fixtures/static/fixtures/js/lookup-manage.js
  corehq/apps/fixtures/templates/fixtures/manage_tables.html
  corehq/apps/fixtures/urls.py
  corehq/apps/fixtures/views.py
Labels: product/all-users-all-environments

#24736 Allow negative numbers in comparisons and equality operations
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/tests/test_filter_dsl.py
Labels: product/invisible

#24743 Removed conditional alerts flag
  corehq/apps/hqwebapp/forms.py
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bulk_upload.html
  corehq/messaging/scheduling/templates/scheduling/conditional_alert_list.html
  corehq/messaging/scheduling/views.py
  corehq/toggles.py
Labels: product/all-users-all-environments

#24745 remove hope api
  corehq/apps/api/resources/v0_4.py
  corehq/apps/api/tests/case_resources.py
  corehq/apps/api/urls.py
  custom/expired_domains.md
  custom/hope/__init__.py
  custom/hope/const.py
  custom/hope/models.py
  custom/hope/tests.py
  settings.py
Labels: product/custom

#24746 Delete RHEL-INSTALL.rst
  RHEL-INSTALL.rst
Labels: product/invisible

#24732 Fix remaining bugs & requests in Explore Case Data report
  corehq/apps/data_interfaces/templates/data_interfaces/explore_case_data.html
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/datagrid.less
  corehq/apps/reports/static/reports/v2/js/datagrid.js
  corehq/apps/reports/static/reports/v2/js/datagrid/columns.js
  corehq/apps/reports/static/reports/v2/js/datagrid/data_models.js
  corehq/apps/reports/v2/endpoints/datagrid.py
  corehq/apps/reports/v2/filters/xpath_column.py
Labels: product/feature-flag

#24741 allow sorting by indexed_on
  corehq/apps/api/resources/v0_4.py
Labels: product/all-users-all-environments

#24754 change submission_type tag from 'unknown' to 'error'
  corehq/apps/receiverwrapper/views.py
Labels: product/invisible

#24727 pull dob from person case for child health case
  custom/icds_reports/tests/fixtures/child_cases.csv
  custom/icds_reports/tests/fixtures/person_cases.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
  custom/icds_reports/utils/aggregation_helpers/monolith/child_health_monthly.py
Labels: product/custom

#24747 Add report headers and descriptions to bulk application translations
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/app_translations/upload_module.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: product/feature-flag

#24750 Remove missing doc task
  custom/icds_reports/tasks.py
Labels: product/invisible

#24753 Fix the method to return a boolean
  corehq/messaging/util.py
Labels: product/invisible

#24744 Added flaky
  corehq/apps/sms/tests/test_backends.py
  requirements-python3/dev-requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
Labels: product/invisible

#24378 Updated signature of build_application_zip
  corehq/apps/app_manager/views/cli.py
  corehq/apps/hqadmin/views/users.py
  corehq/apps/hqmedia/tasks.py
  corehq/apps/hqmedia/views.py
Labels: product/invisible

#24756 Removed ability to data clean case name and type
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#24755 run modernize
  corehq/apps/hqadmin/management/commands/forms_not_in_es.py
  corehq/apps/translations/integrations/transifex/project_migrator.py
  corehq/ex-submodules/pillowtop/management/commands/create_checkpoints_for_merged_pillows.py
  custom/icds_reports/migrations/0125_aggregatethrform.py
Labels: product/invisible

#24656 [ICDS] month filter in SSD report start from Feb 2018
  custom/icds_reports/static/js/directives/month-filter/month-filter.directive.js
  custom/icds_reports/static/js/directives/navigation/navigation.directive.js
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/templates/icds_reports/icds_app/service-delivery-dashboard.html
Labels: product/custom

#24757 Added @flaky to test_change_has_user
  corehq/apps/locations/tests/test_change_has_user.py
Labels: product/invisible

#24761 replace assertions with exceptions
  corehq/form_processor/backends/sql/update_strategy.py
  corehq/form_processor/exceptions.py
Labels: product/invisible

#24717 Remove partitioned query that uses iterator
  corehq/apps/commtrack/tests/test_xml.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_scheduling_integration.py
  corehq/apps/data_pipeline_audit/management/commands/find_sql_forms_not_in_es.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/messaging/scheduling/scheduling_partitioned/dbaccessors.py
  corehq/messaging/scheduling/scheduling_partitioned/tests/test_dbaccessors_both.py
  corehq/messaging/scheduling/tests/test_bulk_conditional_alerts.py
  corehq/messaging/tasks.py
  corehq/sql_db/util.py
Labels: product/invisible

#24765 document that line_profiler doesn't work in Python 3.7
  requirements/dev-requirements.in
Labels: product/invisible

#24764 split EMWF saved report values against choice delimiter
  corehq/apps/reports/filters/users.py
Labels: product/all-users-all-environments

#24752 implement configurable form OData feed
  corehq/apps/api/odata/serializers.py
  corehq/apps/api/odata/tests/data/populated_form_odata_metadata_document_from_config.xml
  corehq/apps/api/odata/tests/test_feed.py
  corehq/apps/api/odata/tests/test_metadata.py
  corehq/apps/api/odata/tests/test_serializers.py
  corehq/apps/api/odata/tests/test_service.py
  corehq/apps/api/odata/tests/utils.py
  corehq/apps/api/odata/utils.py
  corehq/apps/api/odata/views.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/templates/api/form_odata_metadata.xml
  corehq/apps/api/urls.py
  corehq/apps/export/dbaccessors.py
  corehq/apps/export/views/list.py
Labels: product/feature-flag

#24760 handle integrity error when saving error forms
  corehq/form_processor/models.py
  corehq/form_processor/submission_post.py
Labels: product/invisible

#24526 Create mobile workers: angular => knockout
  bower.json
  corehq/apps/app_manager/templates/app_manager/spec/mocha.html
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/dashboard/views.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/export/views/download.py
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/hqwebapp/decorators.py
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/multi_field.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/angular.html
  corehq/apps/hqwebapp/utils.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/locations/forms.py
  corehq/apps/locations/tests/test_change_has_user.py
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/static/users/js/mobile_workers.ng.js
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/tests/test_views.py
  corehq/apps/users/views/mobile/users.py
  custom/icds_reports/templates/icds_reports/spec/mocha.html
  docs/js-guide/libraries.md
Labels: QA Passed, product/invisible

#24767 paginate rule query
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/sql_db/util.py
Labels: product/invisible

#24769 Revert "Added @flaky to test_change_has_user"
  corehq/apps/locations/tests/test_change_has_user.py
Labels: product/invisible

#24758 Change FF from "Solutions" to "Solutions - Open Use"
  corehq/toggles.py
Labels: product/all-users-all-environments

#24482 run travis tests in python 2 and 3
  .travis.yml
Labels: product/invisible

#24771 Added form errors as messages when testing form is valid
  corehq/apps/locations/forms.py
  corehq/apps/locations/tests/test_change_has_user.py
Labels: product/invisible

#24775 Fix html element sizes for child menu forms
  corehq/apps/hqwebapp/static/app_manager/less/navigation.less
Labels: product/feature-flag

#24770 patch utils to guarantee sorted order in tests instead of sorting in …
  corehq/apps/api/odata/tests/test_metadata.py
  corehq/apps/api/odata/views.py
Labels: product/invisible

#24768 Removed password format check on build validation for non-J2ME apps
  corehq/apps/app_manager/commcare_settings.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/tests/test_build_errors.py
  corehq/apps/app_manager/tests/test_child_module.py
  corehq/apps/builds/models.py
Labels: product/all-users-all-environments

#24776 add Zip64
  corehq/apps/hqmedia/tasks.py
Labels: product/invisible

#24778 write to csv file in text mode
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#24704 few parallel agg fixes
  custom/icds_reports/tasks.py
Labels: product/custom

#24779 do not compare ints and strings
  custom/icds_reports/reports/awc_infrastracture.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/reports/maternal_child.py
Labels: product/invisible

#24773 JSON UI for DHIS2 config
  corehq/apps/hqwebapp/static/hqwebapp/js/base_ace.js
  corehq/motech/dhis2/static/dhis2/js/dhis2_map_settings.js
  corehq/motech/dhis2/templates/dhis2/dataset_map.html
  corehq/motech/dhis2/templates/dhis2/partials/json_dhis2_dataset_map_template.html
  corehq/motech/dhis2/view.py
  corehq/motech/openmrs/static/openmrs/js/openmrs_importers.js
Labels: product/feature-flag

#24780 pass unicode to form_content
  corehq/apps/smsforms/app.py
Labels: product/invisible

#24781 encode text before writing to binary file
  corehq/apps/case_importer/tracking/filestorage.py
Labels: product/invisible

#24774 remove duplicate method
  corehq/apps/data_pipeline_audit/dbacessors.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/sql_db/config.py
Labels: product/invisible

#24787 git should ignore python 3 virtualenv
  .gitignore
Labels: product/invisible

#24710 Add docs for invalidating memoized properties
  docs/caching_and_memoization.rst
Labels: product/invisible

#24648 Typo
  corehq/apps/fixtures/tests/test_fixture_data.py
Labels: product/invisible

#24784 fix int/None comparison
  corehq/apps/userreports/util.py
  corehq/apps/userreports/views.py
Labels: product/invisible

#24786 use cmp_to_key to replace usages of cmp in sorted
  corehq/apps/sms/handlers/keyword.py
  custom/_legacy/pact/dot_data.py
Labels: product/invisible

#24788 pass bytes to hashlib.md5
  corehq/apps/reports/tasks.py
Labels: product/invisible

#24789 handle TypeError
  corehq/apps/app_manager/models.py
Labels: product/invisible

#24791 don't use cached app attachments if is unicode
  corehq/apps/app_manager/models.py
Labels: product/invisible

#24783 Tag flaky tests
  corehq/apps/api/odata/tests/test_metadata.py
  corehq/apps/api/tests/user_resources.py
Labels: product/invisible

#24777 No need to bust keys that are never cached and avoid using redis KEYS command
  custom/icds_reports/tasks.py
Labels: product/invisible

#24798 correctly get first element in dict values
  custom/icds_reports/reports/ucr.py
Labels: product/invisible

#24799 turn generator to list to avoid TypeError
  corehq/apps/reports/standard/deployments.py
Labels: product/invisible

#24800 raise BadRequest if data_type_id is not defined
  corehq/apps/fixtures/resources/v0_1.py
Labels: product/invisible

#24801 pass unicode to pact submit_xform
  custom/_legacy/pact/api.py
Labels: product/invisible

#24802 remove '\r' from xpath before validation
  corehq/apps/app_manager/xpath_validator/wrapper.py
Labels: product/invisible

#24806 pass text to soft assert
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#24805 Rollout Explore Case Data [Beta]
  corehq/apps/dashboard/templates/dashboard/base.html
  corehq/apps/data_interfaces/templates/data_interfaces/explore_case_data.html
  corehq/apps/domain/templates/domain/admin/feature_previews.html
  corehq/apps/notifications/ui_notify.py
  corehq/apps/reports/management/commands/rollout_ecd_preview.py
  corehq/apps/reports/v2/reports/explore_case_data.py
  corehq/feature_previews.py
  corehq/tabs/tabclasses.py
  corehq/tabs/uitab.py
  corehq/toggles.py
Labels: product/feature-flag

#24796 remove unused function
  corehq/ex-submodules/casexml/apps/phone/fixtures.py
Labels: product/invisible

#24808 pass valid json to json.dumps
  corehq/messaging/smsbackends/apposit/models.py
Labels: product/invisible

#24809 pass correct arguments to six.reraise
  corehq/messaging/smsbackends/http/models.py
Labels: product/invisible

#24810 fix comparison of data with Decimals and dates (icds)
  custom/icds_reports/experiment.py
Labels: product/invisible

#24797 Update migration pattern docs with best practice
  docs/migration_command_pattern.rst
Labels: product/invisible

#24803 add mack to hubspot failure email
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#24811 don't re-use context manager
  corehq/apps/builds/jadjar.py
Labels: product/invisible

#24813 send soft assert for debugging messaging dashboard issue
  corehq/messaging/scheduling/views.py
Labels: product/invisible

#24812 fix errors when downloading app .zip
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/views/apps.py
Labels: product/invisible

#24816 store response in variable so more info is logged to Sentry
  corehq/apps/formplayer_api/smsforms/api.py
  corehq/apps/smsforms/app.py
Labels: product/invisible

#24785 only check delay for relevant machines
  corehq/sql_db/tests/test_connections.py
  corehq/sql_db/util.py
Labels: product/invisible

#24815 Better arguments for make async build
  corehq/apps/app_manager/tasks.py
  corehq/apps/app_manager/tests/test_app_manager.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/download.py
  corehq/apps/users/tasks.py
  testapps/test_pillowtop/tests/test_app_pillow.py
Labels: product/invisible

#24825 Added translations for aww_vhnd_survey.txt files
  custom/icds/templates/icds/messaging/indicators/asm/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/ben/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/grt/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/guj/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/kha/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/lus/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/mal/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/mar/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/mni/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/pan/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/tam/aww_vhnd_survey.txt
Labels: product/custom

#24795 use wraps decorator for inner function
  corehq/apps/ota/utils.py
Labels: product/invisible

#24826 __repr__ must return text
  corehq/apps/locations/models.py
Labels: product/invisible

#24817 Document conditional alert active status
  corehq/messaging/scheduling/tasks.py
  corehq/messaging/scheduling/views.py
Labels: product/invisible

#24740 Reduce target_commcare_flavor to just a property
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/static/app_manager/spec/releases_spec.js
  corehq/apps/app_manager/tests/views/test_paginate_releases.py
  corehq/apps/app_manager/views/download.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  custom/icds/tasks/hosted_ccz.py
Labels: product/feature-flag, product/invisible

#24823 Route analytics periodic data failure to support
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#24804 Rn disha api v2
  corehq/toggles.py
  custom/icds_reports/migrations/0128_nic_indicators.py
  custom/icds_reports/migrations/sql_templates/database_views/nic_indicators.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/tests/test_nic_indicators_api.py
  custom/icds_reports/urls.py
  custom/icds_reports/utils/data_accessor.py
  custom/icds_reports/views.py
Labels: Open for review: do not merge, product/custom

#24834 decode bytes
  corehq/apps/linked_domain/util.py
Labels: product/invisible

#24841 stagger citus and normal agg
  custom/icds_reports/tasks.py
Labels: product/invisible

#24663 Profile based revisit
  corehq/apps/app_manager/migrations/0004_latestenabledbuildprofiles_active.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/serializers.py
  corehq/apps/app_manager/static/app_manager/js/manage_releases_by_app_profile.js
  corehq/apps/app_manager/static/app_manager/js/manage_releases_by_location.js
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/domain/manage_releases_by_app_profile.html
  corehq/apps/domain/templates/domain/manage_releases_by_location.html
  corehq/apps/domain/urls.py
  corehq/apps/domain/views/releases.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#24782 do not fail on lag check
  custom/icds_reports/utils/__init__.py
Labels: product/invisible

#24827 Notify user in case of failure
  custom/icds/forms.py
  custom/icds/models.py
  custom/icds/tasks/hosted_ccz.py
  custom/icds/tests/models/test_hosted_ccz.py
  custom/icds/tests/tasks/test_setup_ccz_file_for_hosting.py
  custom/icds/views/hosted_ccz.py
Labels: product/feature-flag

#24828 pass unicode to json.dumps
  corehq/apps/settings/views.py
Labels: product/invisible

#24824 transform bytes into int
  corehq/apps/sms/tasks.py
Labels: product/invisible

#24835 move code independent of context manager to outside of with statement
  corehq/apps/app_manager/xpath_validator/wrapper.py
Labels: product/invisible

#24829 use temp table for thr
  custom/icds_reports/utils/aggregation_helpers/distributed/thr_form_v2.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/thr-form-v2.distributed.txt
Labels: product/custom

#24662 [ICDS] replace SDD age filter to the dots at the bottom of page
  custom/icds_reports/reports/service_delivery_dashboard.py
  custom/icds_reports/static/icds_reports/js/spec/awc-reports.directive.spec.js
  custom/icds_reports/static/js/directives/additional-filter/additional-filter.directive.js
  custom/icds_reports/static/js/directives/adhaar-beneficiary/adhaar-beneficiary.directive.js
  custom/icds_reports/static/js/directives/adolescent-girls/adolescent-girls.directive.js
  custom/icds_reports/static/js/directives/adult-weight-scale/adult-weight-scale.directive.js
  custom/icds_reports/static/js/directives/awc-daily-status/awc-daily-status.directive.js
  custom/icds_reports/static/js/directives/awc-opened-yesterday/awc-opened-yesterday.directive.js
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/static/js/directives/awcs-covered/awcs-covered.directive.js
  custom/icds_reports/static/js/directives/children-initiated/children-initiated.directive.js
  custom/icds_reports/static/js/directives/clean-water/clean-water.directive.js
  custom/icds_reports/static/js/directives/early_initiation_breastfeeding/early_initiation_breastfeeding.directive.js
  custom/icds_reports/static/js/directives/enrolled-children/enrolled-children.directive.js
  custom/icds_reports/static/js/directives/enrolled-women/enrolled-women.directive.js
  custom/icds_reports/static/js/directives/exclusive-breastfeeding/exlusive-breastfeeding.directive.js
  custom/icds_reports/static/js/directives/functional-toilet/functional-toilet.directive.js
  custom/icds_reports/static/js/directives/immunization_coverage/immunization_coverage.directive.js
  custom/icds_reports/static/js/directives/infants-weight-scale/infants-weight-scale.directive.js
  custom/icds_reports/static/js/directives/institutional-deliveries/institutional-deliveries.directive.js
  custom/icds_reports/static/js/directives/lactating-enrolled-women/lactating-enrolled-women.directive.js
  custom/icds_reports/static/js/directives/lady-supervisor/lady-supervisor.directive.js
  custom/icds_reports/static/js/directives/medicine-kit/medicine-kit.directive.js
  custom/icds_reports/static/js/directives/newborn_with_low_weight/newborn_with_low_weight.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-severe-report/prevalence-of-severe-report.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-stunting-report/prevalence-of-stunting-report.directive.js
  custom/icds_reports/static/js/directives/progress-report/progress-report.directive.js
  custom/icds_reports/static/js/directives/registered-household/registered-household.directive.js
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
  custom/icds_reports/static/js/directives/system-usage/system-usage.directive.js
  custom/icds_reports/static/js/directives/underweight-children-report/underweight-children-report.directive.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/templates/icds_reports/icds_app/additional-filter.html
  custom/icds_reports/templates/icds_reports/icds_app/filters.html
  custom/icds_reports/templates/icds_reports/icds_app/service-delivery-dashboard.html
  custom/icds_reports/tests/reports/test_service_delivery.py
  custom/icds_reports/views.py
Labels: product/custom

#24807 record submission lag as metric in datadog
  corehq/apps/receiverwrapper/views.py
Labels: product/invisible

#24836 toggle to disable 'run_case_update_rules' task
  corehq/apps/data_interfaces/tasks.py
  corehq/toggles.py
Labels: product/invisible

#24842 Management command to reassign SMS phone # backend
  corehq/apps/sms/management/commands/change_phonenumber_backend.py
Labels: product/invisible

#24851 switch to ./manage.py [ci skip]
  DEV_SETUP.md
Labels: product/invisible

#24848 make button text say 'Copy' when export ownership flag is set
  corehq/apps/export/templates/export/partials/table.html
Labels: product/feature-flag

#24853 remove python 2 travis tests
  .travis.yml
Labels: product/invisible

#24849 default to console email backend in dev_settings
  dev_settings.py
Labels: product/invisible

#24843 fix RuntimeError
  corehq/ex-submodules/dimagi/utils/subprocess_manager.py
Labels: product/invisible

#24844 don't try to encode bytes
  corehq/apps/app_manager/models.py
Labels: product/invisible

#24759 Removed build_application_zip_v2
  corehq/apps/hqmedia/tasks.py
Labels: product/invisible

#24846 Added UTF-8 encoding in FormBase.validate_form
  corehq/apps/app_manager/models.py
Labels: product/all-users-all-environments

#24839 Added comment and used more generic code in xpath validator
  corehq/apps/app_manager/xpath_validator/wrapper.py
Labels: product/invisible
