Repository dimagi/commcare-hq, pull requests merged in 2019-08, with the labels that each got.

#24987 Fix intermittent test failures due to quickcache collisions
  corehq/apps/sms/tests/test_backends.py
  corehq/ex-submodules/casexml/apps/case/models.py
  corehq/util/quickcache.py
  corehq/util/tests/test_quickcache.py
Labels: product/invisible

#24986 Remove OData legacy and duplication
  corehq/apps/api/odata/serializers.py
  corehq/apps/api/odata/tests/data/empty_metadata_document.xml
  corehq/apps/api/odata/tests/data/populated_case_metadata_document.xml
  corehq/apps/api/odata/tests/data/populated_form_metadata_document.xml
  corehq/apps/api/odata/tests/test_auth.py
  corehq/apps/api/odata/tests/test_feed.py
  corehq/apps/api/odata/tests/test_metadata.py
  corehq/apps/api/odata/tests/test_models.py
  corehq/apps/api/odata/tests/test_serializers.py
  corehq/apps/api/odata/tests/test_service.py
  corehq/apps/api/odata/tests/test_utils.py
  corehq/apps/api/odata/tests/utils.py
  corehq/apps/api/odata/utils.py
  corehq/apps/api/odata/views.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/urls.py
Labels: product/invisible

#24856 [ICDS] National user sees national view on icds report entry
  custom/icds_reports/views.py
Labels: product/custom

#24980 Removed ilsgateway's ReceiptTest
  custom/ilsgateway/tests/handlers/rec.py
  custom/ilsgateway/tests/handlers/soh_slab.py
Labels: product/invisible

#24979 Removed testAuditViews
  corehq/ex-submodules/auditcare/tests/auth.py
Labels: product/invisible

#24982 Remove pnlppgi custom module
  custom/expired_domains.md
  custom/pnlppgi/__init__.py
  custom/pnlppgi/expressions.py
  custom/pnlppgi/filters.py
  custom/pnlppgi/reports.py
  custom/pnlppgi/resources/malaria.json
  custom/pnlppgi/resources/site_reporting_rates.json
  custom/pnlppgi/sqldata.py
  custom/pnlppgi/templates/pnlppgi/cumulative_malaria.html
  custom/pnlppgi/templates/pnlppgi/pnlppgi_base.html
  custom/pnlppgi/templates/pnlppgi/site_reporting.html
  custom/pnlppgi/templates/pnlppgi/weekly_malaria.html
  custom/pnlppgi/utils.py
  settings.py
Labels: product/invisible

#24981 Add "last form submission" info to custom module audit script
  corehq/apps/accounting/management/commands/find_inactive_custom_modules.py
Labels: product/invisible

#24989 typo foramt -> format [ci skip]
  corehq/apps/userreports/management/commands/prune_old_datasources.py
Labels: product/invisible

#24963 child report add absolute number column
  custom/icds_reports/sqldata/exports/children.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#24972 Covert NIC indicator api just perform with normal JSON as rest API
  custom/icds_reports/tests/test_nic_indicators_api.py
  custom/icds_reports/utils/data_accessor.py
  custom/icds_reports/views.py
Labels: product/custom

#24977 Replaced assertRaisesRegexp with assertRaisesRegex
  corehq/apps/app_manager/tests/test_extension_case.py
  corehq/apps/hqwebapp/templatetags/tests/test_tag.py
  corehq/apps/tzmigration/tests/test_timezonemigration.py
  corehq/apps/userreports/tests/test_data_source_validaton.py
  corehq/ex-submodules/casexml/apps/case/tests/test_indexes.py
  corehq/ex-submodules/dimagi/utils/tests/dates.py
  corehq/form_processor/tests/test_ledger_dbaccessor.py
Labels: product/invisible

#24971 cache LatestAppInfo.get_latest_apk_version
  corehq/apps/app_manager/util.py
Labels: product/invisible

#24993 Added XML mode and search box back to ace
  corehq/apps/hqwebapp/static/hqwebapp/js/base_ace.js
Labels: product/feature-flag

#24978 fix percent rendering in mpr
  custom/icds_reports/mpr_sqldata.py
Labels: product/custom

#24994 Ignore in celery check any blockage under 5 minutes
  corehq/apps/hqadmin/service_checks.py
Labels: product/invisible

#24999 ECD: add analytics for sending kiss events at certain initial load thresholds
  corehq/apps/reports/static/reports/v2/js/datagrid/data_models.js
Labels: product/invisible

#24998 Fixed inability to delete non-last load action in advanced form settings
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/case_config_ui.js
Labels: product/feature-flag

#25000 Fixed inability to select "Unknown "Module" when creating form export
  corehq/apps/app_manager/fields.py
  corehq/apps/export/forms.py
Labels: product/all-users-all-environments

#25001 Renamed location widgets
  corehq/apps/hqwebapp/static/hqwebapp/js/select_2_ajax_widget.js
  corehq/apps/hqwebapp/widgets.py
  corehq/apps/locations/static/locations/js/widgets.js
  corehq/apps/locations/templates/locations/manage/partials/autocomplete_select_widget.html
  corehq/apps/locations/templates/locations/manage/partials/drilldown_location_widget.html
Labels: product/invisible

#24996 Turn off weekly inactive SMS messages based on warehouse lag
  corehq/warehouse/utils.py
  custom/icds/messaging/indicators.py
  custom/icds/tests/test_aww_no_submissions.py
Labels: product/custom

#24879 Remove "icds-new" from ICDS_ENVS
  corehq/toggles.py
  custom/icds_reports/tests/reports/test_adhaar.py
  custom/icds_reports/tests/reports/test_adolescent_girls.py
  custom/icds_reports/tests/reports/test_adult_weight_scale.py
  custom/icds_reports/tests/reports/test_awc_daily_status.py
  custom/icds_reports/tests/reports/test_awcs_covered.py
  custom/icds_reports/tests/reports/test_children_initiated.py
  custom/icds_reports/tests/reports/test_clean_water.py
  custom/icds_reports/tests/reports/test_early_initiation_breastfeeding.py
  custom/icds_reports/tests/reports/test_enrolled_children.py
  custom/icds_reports/tests/reports/test_enrolled_women.py
  custom/icds_reports/tests/reports/test_exclusive_breastfeeding.py
  custom/icds_reports/tests/reports/test_functional_toilet.py
  custom/icds_reports/tests/reports/test_immunization_coverage.py
  custom/icds_reports/tests/reports/test_infants_weight_scale.py
  custom/icds_reports/tests/reports/test_institutional_deliveries_sector.py
  custom/icds_reports/tests/reports/test_issnip_monthly_register.py
  custom/icds_reports/tests/reports/test_lactating_enrolled_women.py
  custom/icds_reports/tests/reports/test_medicine_kit.py
  custom/icds_reports/tests/reports/test_new_born_with_low_weight.py
  custom/icds_reports/tests/reports/test_prevalence_of_stunting.py
  custom/icds_reports/tests/reports/test_prevalence_of_undernutrition.py
  custom/icds_reports/tests/reports/test_registered_household.py
  custom/icds_reports/tests/test_aggregation_script.py
  custom/icds_reports/ucr/data_sources/awc_locations.json
  custom/icds_reports/ucr/data_sources/awc_mgt_forms.json
  custom/icds_reports/ucr/data_sources/cbe_form.json
  custom/icds_reports/ucr/data_sources/ccs_record_cases.json
  custom/icds_reports/ucr/data_sources/ccs_record_cases_monthly_v2.json
  custom/icds_reports/ucr/data_sources/child_cases_monthly_v2.json
  custom/icds_reports/ucr/data_sources/child_delivery_forms.json
  custom/icds_reports/ucr/data_sources/child_health_cases.json
  custom/icds_reports/ucr/data_sources/daily_feeding_forms.json
  custom/icds_reports/ucr/data_sources/gm_forms.json
  custom/icds_reports/ucr/data_sources/hardware_cases.json
  custom/icds_reports/ucr/data_sources/home_visit_forms.json
  custom/icds_reports/ucr/data_sources/household_cases.json
  custom/icds_reports/ucr/data_sources/infrastructure_form.json
  custom/icds_reports/ucr/data_sources/infrastructure_form_v2.json
  custom/icds_reports/ucr/data_sources/it_report_follow_issue.json
  custom/icds_reports/ucr/data_sources/ls_home_visit_forms_filled.json
  custom/icds_reports/ucr/data_sources/ls_vhnd_form.json
  custom/icds_reports/ucr/reports/ls/ls_awc_days_open.json
  custom/icds_reports/ucr/reports/mpr/testing/mpr5_custom_sql.json
  custom/icds_reports/ucr/reports/other/it_issues_activity.json
  settings.py
Labels: product/invisible

#25009 Fix convert to excel
  corehq/apps/translations/integrations/transifex/views.py
  custom/icds_reports/utils/data_accessor.py
Labels: product/invisible

#25005 Removed 'Active Project Map' admin report
  corehq/apps/hqadmin/reports.py
  corehq/apps/hqadmin/static/hqadmin/css/project_map.css
  corehq/apps/hqadmin/static/hqadmin/js/project_map.js
  corehq/apps/hqadmin/templates/hqadmin/project_map.html
  corehq/reports.py
  corehq/tabs/tabclasses.py
Labels: product/admin

#25011 Response.text decodes content bytes
  corehq/motech/repeaters/views/repeaters.py
Labels: product/invisible

#24990 View Changes Button updates
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/static/app_manager/spec/releases_spec.js
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_table.html
Labels: product/feature-flag

#25013 Updated mobile worker password reset to show encoded password less often
  custom/nic_compliance/static/nic_compliance/js/encoder.js
Labels: product/custom

#25012 use contextlib2
  scripts/rebuildstaging.py
Labels: product/invisible

#25016 remove old commands
  corehq/apps/domain/management/commands/bootstrap.py
  corehq/apps/hqadmin/management/commands/make_supervisor_conf.py
  corehq/apps/hqadmin/management/commands/make_supervisor_pillowtop_conf.py
Labels: product/invisible

#24997 handle missing xml during form processing
  corehq/apps/commtrack/processing.py
  corehq/apps/couch_sql_migration/asyncforms.py
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/ex-submodules/couchforms/models.py
  corehq/form_processor/backends/sql/processor.py
  corehq/form_processor/exceptions.py
  corehq/form_processor/models.py
  corehq/form_processor/parsers/form.py
  corehq/form_processor/parsers/ledgers/form.py
Labels: product/invisible

#24914 optionally drop case actions and xform IDs from ES index
  corehq/apps/reports/standard/monitoring.py
  corehq/pillows/case.py
  settings.py
Labels: product/custom, product/invisible

#25020 keep field enabled when changing values
  custom/nic_compliance/static/nic_compliance/js/encoder.js
Labels: product/custom

#25021 dont disable field
  custom/nic_compliance/static/nic_compliance/js/encoder.js
Labels: product/custom

#25006 upgrade couchdbkit
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#25017 Add informational popovers to app diff
  corehq/apps/app_manager/app_schemas/form_metadata.py
  corehq/apps/app_manager/app_schemas/tests/test_app_diffs.py
  corehq/apps/app_manager/static/app_manager/js/summary/models.js
  corehq/apps/app_manager/templates/app_manager/form_summary_base.html
Labels: product/feature-flag

#25025 Disambiguate page titles, etc.
  corehq/motech/dhis2/repeaters.py
  corehq/motech/repeaters/views/repeaters.py
Labels: product/invisible

#24965 notify data team on GIR failure
  corehq/apps/data_analytics/tasks.py
Labels: product/invisible

#25015 Fix the way responses are handled when a payload has nothing to send
  corehq/motech/dhis2/repeaters.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: product/invisible

#25023 new rate limits for sentry
  corehq/util/sentry.py
Labels: product/invisible

#25026 DHIS2 Repeaters don't need their own form
  corehq/motech/repeaters/forms.py
  corehq/motech/repeaters/views/repeaters.py
Labels: product/invisible

#25029 Removed link to mm reference checker from mm download zip area
  corehq/apps/hqmedia/templates/hqmedia/partials/multimedia_zip_notice.html
  corehq/apps/hqmedia/templates/hqmedia/references.html
Labels: product/all-users-all-environments

#25024 Updated NIC-compliant password fields to hide password while request …
  custom/nic_compliance/static/nic_compliance/js/encoder.js
Labels: product/custom

#25031 Removed hard-coded support email
  corehq/apps/app_manager/views/download.py
  corehq/apps/hqadmin/tasks.py
Labels: product/invisible

#25032 BI Integration: Fix Filtering, small text change
  corehq/apps/api/resources/v0_5.py
  corehq/apps/export/templates/export/partials/table.html
Labels: product/feature-flag

#24992 Diff cases in separate process and reduce memory load
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/lrudict.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_lrudict.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
  corehq/apps/tzmigration/planning.py
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#25027 Moved resource_versions to YAML and only update it in build_requirejs
  .gitignore
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/management/commands/resource_static.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  get_resource_versions.py
Labels: product/invisible

#24976 Speed up requirejs tests
  corehq/apps/hqwebapp/tests/test_requirejs.py
Labels: product/invisible

#24934 Simplify Disha script, force to master after max retries on standby
  custom/icds_reports/management/commands/build_disha_dumps.py
  custom/icds_reports/reports/disha.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/test_disha_dump.py
  custom/icds_reports/views.py
Labels: product/invisible

#25038 Update "view changed only" button to filter list in app diff
  corehq/apps/app_manager/static/app_manager/js/summary/form_diff.js
  corehq/apps/app_manager/static/app_manager/js/summary/models.js
  corehq/apps/app_manager/templates/app_manager/base_summary.html
Labels: product/feature-flag

#25033 Filter user download by location
  corehq/apps/users/dbaccessors/all_commcare_users.py
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/filtered_download.js
  corehq/apps/users/tests/test_db_accessors.py
  corehq/toggles.py
Labels: product/feature-flag

#25040 Add deprecation warning to faceted admin reports
  corehq/apps/hqadmin/reports.py
Labels: product/admin

#24975 Remove hsph code
  custom/_legacy/hsph/__init__.py
  custom/_legacy/hsph/models.py
  custom/_legacy/hsph/tasks.py
  custom/_legacy/hsph/tests.py
  custom/expired_domains.md
  settings.py
Labels: product/invisible

#25037 Use warehouse for app status export
  corehq/apps/reports/standard/deployments.py
  corehq/ex-submodules/pillowtop/reindexer/change_providers/django_model.py
  corehq/toggles.py
  corehq/util/queries.py
Labels: product/invisible

#25022 Notify weekly SMS rule
  corehq/warehouse/utils.py
  custom/icds/const.py
  custom/icds/messaging/indicators.py
Labels: product/invisible

#24623 Correct the age check
  custom/icds_reports/reports/awc_reports.py
Labels: product/custom

#25042 Removed RETRY_SMS_INDEFINITELY flag
  corehq/apps/sms/tasks.py
  corehq/apps/sms/tests/test_queueing.py
  corehq/toggles.py
Labels: product/invisible

#25045 Removed "Enikshay: Add option to index custom location fields" flag
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
  corehq/apps/custom_data_fields/templates/custom_data_fields/custom_data_fields.html
  corehq/apps/locations/fixtures.py
  corehq/apps/locations/tests/test_location_fixtures.py
  corehq/apps/locations/views.py
  corehq/toggles.py
Labels: product/feature-flag

#25046 Removed REMOTE_REQUEST_QUESTION_TYPE flag
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/views/formdesigner.py
  corehq/toggles.py
Labels: product/feature-flag

#25047 Kill custom calendar fixture feature flag
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/tests/test_advanced_suite.py
  corehq/apps/calendar_fixture/fixture_provider.py
  corehq/apps/calendar_fixture/forms.py
  corehq/apps/calendar_fixture/migrations/0003_delete_calendarfixturesettings.py
  corehq/apps/calendar_fixture/models.py
  corehq/apps/calendar_fixture/tests.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/domain/urls.py
  corehq/apps/domain/views/__init__.py
  corehq/apps/domain/views/fixtures.py
  corehq/apps/hqadmin/management/commands/clone_domain.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
  settings.py
Labels: product/feature-flag

#25010 Improve mm pull
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/partials/settings/app_settings.html
  corehq/apps/app_manager/templates/app_manager/partials/settings/multimedia_ajax.html
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/multimedia.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/hqmedia/tasks.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/linked_domain/urls.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/views.py
Labels: product/feature-flag

#25049 Resolve Sislog SSL errors
  corehq/messaging/smsbackends/http/models.py
Labels: product/invisible

#25044 Renamed a few feature flags
  corehq/toggles.py
Labels: product/invisible

#25054 Simplify view_generic and back_to_main
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/app_manager/views/view_generic.py
Labels: product/invisible

#25053 Add help text
  corehq/apps/linked_domain/management/commands/link_app_to_remote.py
  corehq/apps/linked_domain/models.py
  corehq/apps/translations/validator.py
Labels: product/invisible

#25051 Ensure present domain can be copied to
  corehq/apps/app_manager/views/view_generic.py
Labels: product/admin

#24973 sync case messaging pillow
  corehq/apps/change_feed/connection.py
  corehq/apps/change_feed/management/commands/create_kafka_topics.py
  corehq/apps/change_feed/topics.py
  corehq/apps/commtrack/tests/test_stock_state.py
  corehq/apps/commtrack/tests/test_xml.py
  corehq/blobs/mixin.py
  corehq/blobs/tests/test_mixin.py
  corehq/blobs/tests/test_util.py
  corehq/blobs/util.py
  corehq/ex-submodules/pillowtop/processors/sample.py
  corehq/form_processor/tests/test_kafka.py
  corehq/messaging/pillow.py
  corehq/messaging/scheduling/tests/test_recipients.py
  corehq/messaging/signals.py
  corehq/messaging/tasks.py
  corehq/pillows/case.py
  corehq/util/io.py
  corehq/util/tests/test_io.py
  settings.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
  testapps/test_pillowtop/tests/test_case_pillow.py
  testapps/test_pillowtop/tests/test_xform_pillow.py
  testapps/test_pillowtop/utils.py
Labels: product/invisible

#25035 Remove aggregation dependency on awc location UCR
  custom/icds_reports/exceptions.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/fixtures/awc_location.csv
  custom/icds_reports/tests/fixtures/awc_location_local.csv
  custom/icds_reports/tests/fixtures/location_ucr.csv
  custom/icds_reports/tests/test_aggregation_script.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/distributed/awc_location.py
  custom/icds_reports/utils/aggregation_helpers/monolith/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/monolith/agg_ls_data.py
  custom/icds_reports/utils/aggregation_helpers/monolith/awc_location.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-ls.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/location.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/location.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/tests.py
Labels: product/custom

#25052 Make date filters inclusive on SMS Billables Report
  corehq/apps/smsbillables/interface.py
Labels: product/admin

#25058 fix url
  corehq/tabs/tabclasses.py
Labels: product/invisible

#24705 Attempt at an efficient rate-limiter implementation
  corehq/project_limits/__init__.py
  corehq/project_limits/rate_counter/__init__.py
  corehq/project_limits/rate_counter/interfaces.py
  corehq/project_limits/rate_counter/presets.py
  corehq/project_limits/rate_counter/rate_counter.py
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/tests/__init__.py
  corehq/project_limits/tests/test_rate_counter.py
  corehq/project_limits/tests/test_rate_limiter.py
Labels: product/invisible

#24055 Remove autogeneration of users for locations
  corehq/apps/locations/forms.py
  corehq/apps/locations/models.py
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/static/locations/js/location_types.js
  corehq/apps/locations/tasks.py
  corehq/apps/locations/templates/locations/location_types.html
  corehq/apps/locations/templates/locations/manage/location.html
  corehq/apps/locations/tests/test_change_has_user.py
  corehq/apps/locations/tests/test_views.py
  corehq/apps/locations/views.py
  corehq/toggles.py
  custom/aaa/fixtures/locations.json
Labels: product/invisible

#25050 Released multimedia integrity check
  corehq/apps/app_manager/tests/test_ccz.py
  corehq/apps/hqmedia/tasks.py
Labels: product/all-users-all-environments

#25048 Kill custom calendar fixture feature flag - cleanup
  corehq/apps/calendar_fixture/__init__.py
  corehq/apps/calendar_fixture/migrations/0001_initial.py
  corehq/apps/calendar_fixture/migrations/0002_auto_20171121_1803.py
  corehq/apps/calendar_fixture/migrations/0003_delete_calendarfixturesettings.py
  corehq/apps/calendar_fixture/migrations/__init__.py
  settings.py
Labels: product/invisible

#25062 Fix monolith awc_location changed condition
  custom/icds_reports/utils/aggregation_helpers/monolith/awc_location.py
Labels: product/custom

#25066 Use ANY instead of IN for list adaptation
  custom/icds_reports/utils/aggregation_helpers/monolith/awc_location.py
Labels: product/invisible

#25004 Add future functionality for enforcing child case privileges
  corehq/apps/app_manager/add_ons.py
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
  corehq/apps/app_manager/templates/app_manager/partials/settings/add_ons.html
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/hqwebapp/templates/hqwebapp/partials/generic_feature_upgrade.html
Labels: product/invisible

#25063 Add error logging to calculate_users_in_all_domains
  corehq/apps/accounting/tasks.py
Labels: product/invisible

#25061 Move progenitor_app_id attribute
  corehq/apps/app_manager/models.py
  corehq/apps/linked_domain/applications.py
  corehq/pillows/mappings/app_mapping.json
Labels: product/invisible

#25077 Updated requirements
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#25073 Improve Email Consistency in Templates
  corehq/apps/accounting/models.py
  corehq/apps/accounting/static/accounting/js/pricing_table.js
  corehq/apps/appstore/templates/cda.html
  corehq/apps/domain/templates/domain/select_plan.html
  corehq/apps/domain/views/accounting.py
  corehq/apps/export/templates/export/partials/customize_export_header.html
  corehq/apps/hqwebapp/templates/404.html
  corehq/apps/hqwebapp/templates/csrf_failure.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/modal_eula.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/generic_feature_upgrade.html
  corehq/apps/reports/filters/forms.py
  corehq/apps/reports/templates/reports/filters/partials/fuzzy_checkbox.html
  corehq/apps/sms/templates/sms/wall.html
  corehq/apps/userreports/templates/userreports/base_report_builder.html
  corehq/apps/userreports/templates/userreports/paywall/activating_subscription.html
  corehq/apps/userreports/templates/userreports/paywall/pricing.html
  corehq/apps/userreports/views.py
  corehq/util/context_processors.py
  settings.py
Labels: product/all-users-all-environments

#25076 Retry on awc_covered page when there are all 0s
  custom/icds_reports/tests/test_data_accessor.py
  custom/icds_reports/utils/data_accessor.py
  custom/icds_reports/views.py
Labels: product/custom

#25041 Odata feeds: Add Repeat Group, Parent Cases, and De-Id support
  corehq/apps/api/odata/serializers.py
  corehq/apps/api/odata/tests/test_metadata.py
  corehq/apps/api/odata/tests/test_models.py
  corehq/apps/api/odata/tests/test_serializers.py
  corehq/apps/api/odata/utils.py
  corehq/apps/api/odata/views.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/urls.py
  corehq/apps/export/models/new.py
  corehq/apps/export/static/export/js/export_list.js
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/apps/export/templates/export/partials/new_customize_export_templates.html
  corehq/apps/export/templates/export/partials/table.html
  corehq/apps/export/views/edit.py
  corehq/apps/export/views/list.py
  corehq/apps/export/views/new.py
  corehq/apps/export/views/utils.py
Labels: product/feature-flag

#25083 Citus should use local table for awc_location agg
  custom/icds_reports/utils/aggregation_helpers/distributed/awc_location.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/location.distributed.txt
Labels: product/custom

#25087 Fix usercase edit mode
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
Labels: product/all-users-all-environments

#25074 Updated which js modules require timepicker
  corehq/apps/hqwebapp/static/hqwebapp/js/select2_handler.js
  corehq/apps/sms/static/sms/js/settings.js
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
Labels: product/invisible

#25072 Removed allow_form_workflow context variable
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/form_tab_settings.html
  corehq/apps/app_manager/views/forms.py
Labels: product/invisible

#25089 Encrypt and decrypt functions must return Unicode
  corehq/motech/tests/test_utils.py
  corehq/motech/utils.py
Labels: product/invisible

#25081 Export intrahealth reports to excel format
  custom/intrahealth/utils.py
Labels: product/custom

#25084 Removed HQMediaMapItem.output_size
  corehq/apps/accounting/tests/data/app-commcare-icon-build.json
  corehq/apps/accounting/tests/data/app-commcare-icon-standard.json
  corehq/apps/app_manager/tests/data/yesno.json
  corehq/apps/hqmedia/models.py
  corehq/apps/translations/tests/data/bulk_app_translation/moved_module/app.json
  corehq/pillows/mappings/app_mapping.json
  corehq/pillows/mappings/app_mapping.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: product/invisible

#25069 Updated case list properties dropdown to show current value even if u…
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
Labels: product/feature-flag

#25019 fix last modified view
  corehq/couchapps/last_modified/views/by_last_modified/map.js
Labels: product/invisible, reindex/migration

#25090 fix advanced menu case issues
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/actions.js
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/case_config_ui.js
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
Labels: product/all-users-all-environments

#25091 Added hqmedia README
  corehq/apps/hqmedia/README.md
Labels: product/invisible

#25003 Added ability to copy a specific version of an app
  corehq/apps/app_manager/exceptions.py
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/widgets.js
  corehq/apps/app_manager/templates/app_manager/app_view_settings.html
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/doctypemigrations/migrator_instances.py
Labels: QA Passed, product/all-users-all-environments

#25064 compare like with like
  corehq/messaging/pillow.py
Labels: product/invisible

#25093 Include filter columns in reports with custom backends
  corehq/apps/app_manager/tests/test_filters.py
  corehq/apps/userreports/custom/data_source.py
  corehq/apps/userreports/mixins.py
  corehq/apps/userreports/sql/data_source.py
Labels: product/custom

#25080 Disallow same domain app linking
  corehq/apps/app_manager/views/apps.py
Labels: product/feature-flag

#25094 Renamed a few app_manager test files and moved a test
  corehq/apps/app_manager/tests/test_apps.py
  corehq/apps/app_manager/tests/test_modules.py
Labels: product/invisible

#25095 Replaced codecs with more standard get_xml
  corehq/apps/app_manager/tests/test_apps.py
Labels: product/invisible

#25100 Daily Saved Exports -- move isFeed check to ko if tag, not visible
  corehq/apps/export/templates/export/partials/table.html
Labels: product/all-users-all-environments

#25101 Renamed get_built_app_ids_for_app_id and added get_build_ids
  corehq/apps/app_manager/dbaccessors.py
  corehq/apps/app_manager/tests/test_apps.py
  corehq/apps/app_manager/tests/test_dbaccessors.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/export/models/deprecated.py
Labels: product/invisible

#25096 Use standard cryptographic padding, take 2
  corehq/motech/tests/test_utils.py
  corehq/motech/utils.py
Labels: product/invisible

#25104 Refactor linked apps tests
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/linked_domain/tests/test_update_roles.py
Labels: product/invisible

#25108 set status to completed if file already present
  custom/icds/models.py
Labels: product/feature-flag

#25099 pillow error queue changes
  corehq/apps/hqpillow_retry/management/commands/run_pillow_retry_queue.py
  corehq/apps/hqpillow_retry/tests.py
  corehq/ex-submodules/pillow_retry/api.py
Labels: product/invisible

#25109 more changes to pillow error queue
  corehq/apps/change_feed/producer.py
  corehq/apps/hqpillow_retry/management/commands/run_pillow_retry_queue.py
  corehq/ex-submodules/pillow_retry/api.py
  corehq/ex-submodules/pillow_retry/management/commands/send_pillow_retry_queue_through_pillows.py
  manage.py
Labels: product/invisible

#25079 [IntraHealth] New dashboards
  custom/intrahealth/filters.py
  custom/intrahealth/reports/__init__.py
  custom/intrahealth/reports/consommation_dashboard.py
  custom/intrahealth/reports/disponibilite_dashboard.py
  custom/intrahealth/reports/indicateurs_de_base_dasboard.py
  custom/intrahealth/reports/recap_passage_one_dashboard.py
  custom/intrahealth/reports/recap_passage_two_dashboard.py
  custom/intrahealth/reports/taux_de_peremption_dashboard.py
  custom/intrahealth/reports/taux_de_perte_dashboard.py
  custom/intrahealth/reports/taux_de_rupture_dashboard.py
  custom/intrahealth/reports/taux_de_satisfaction_dashboard.py
  custom/intrahealth/reports/valuer_des_stocks_pna_disponible_dashboard.py
  custom/intrahealth/sqldata.py
  custom/intrahealth/templates/yeksi_naa/partials/aggregated_table.html
  custom/intrahealth/templates/yeksi_naa/partials/report_table.html
  custom/intrahealth/templates/yeksi_naa/recap_passage.html
  custom/intrahealth/templates/yeksi_naa/tabular_report.html
  custom/intrahealth/ucr/data_sources/date_effective_de_livraison.json
  custom/intrahealth/ucr/data_sources/operateur_combined2.json
  custom/intrahealth/ucr/data_sources/visite_de_l_operateur_per_product_v2.json
  custom/intrahealth/ucr/data_sources/visite_de_l_operateur_product_consumption.json
  custom/intrahealth/utils.py
  settings.py
Labels: product/custom

#25106 Add logging to timing in RestoreConfig
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/ex-submodules/casexml/apps/phone/tasks.py
  corehq/util/timer.py
Labels: product/invisible

#25059 Cmdline copy app with report references
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/views/apps.py
  custom/icds/management/commands/copy_icds_app.py
Labels: product/custom

#25110 Remove links to old admin reports
  corehq/apps/hqadmin/reports.py
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views/utils.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
Labels: product/admin

#25112 Fixed string formatting
  corehq/apps/hqmedia/tasks.py
Labels: product/feature-flag

#24531 switch to full join
  custom/icds_reports/migrations/sql_templates/database_views/daily_attendance.sql
Labels: product/custom

#25067 Alert dashboard team when locations change
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/awc_location.py
  custom/icds_reports/utils/aggregation_helpers/monolith/awc_location.py
Labels: product/custom

#25117 allow citus flag for domains
  corehq/toggles.py
  custom/icds_reports/middleware.py
Labels: product/invisible

#25113 Scope automatic instance declarations to the app
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/features/mobile_ucr.py
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/tests/test_report_config.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/app_manager/xform.py
Labels: product/feature-flag

#25120 Added back in 'Tracks Stock' header in locations table
  corehq/apps/locations/templates/locations/location_types.html
Labels: product/feature-flag

#25114 fix empty build-version issue in app-status-staging SQL
  corehq/warehouse/transforms/sql/app_status_form_staging.sql
Labels: product/invisible

#25118 Minor improvements
  corehq/apps/app_manager/static/app_manager/js/manage_releases_by_app_profile.js
  corehq/apps/app_manager/static/app_manager/js/manage_releases_by_location.js
  corehq/apps/domain/forms.py
  corehq/apps/domain/views/releases.py
Labels: product/feature-flag

#25115 Add a "FormQuestionMap" example to OpenMRS documentation
  corehq/motech/openmrs/README.md
Labels: product/invisible

#25121 Change AsyncIndicator primary key to bigint
  corehq/apps/userreports/migrations/0016_change_primary_key_to_bigint.py
  corehq/apps/userreports/models.py
Labels: product/invisible

#24751 skip creating default build files on build
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/views/download.py
  corehq/toggles.py
Labels: product/feature-flag, product/invisible

#25124 fix audit url generation
  corehq/sql_db/routers.py
  custom/icds_reports/middleware.py
  custom/icds_reports/urls.py
Labels: product/invisible

#25128 Fix setuptools version
  requirements-python3/dev-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#25123 Couch to SQL: live migration part 1
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/progress.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/form_processor/exceptions.py
  corehq/form_processor/parsers/form.py
  corehq/util/pagination.py
Labels: product/invisible

#25129 Updated hqmedia README
  corehq/apps/hqmedia/README.md
Labels: product/invisible

#25131 use citus for sqldata requests as well
  custom/icds_reports/sqldata/base.py
Labels: product/custom

#25126 refactor 'queue' commands
  corehq/apps/hqpillow_retry/management/commands/run_pillow_retry_queue.py
  corehq/form_processor/management/commands/run_submission_reprocessing_queue.py
  hqscripts/generic_queue.py
  settings.py
Labels: product/invisible

#25122 Remove TimingContext repr
  corehq/util/timer.py
Labels: product/invisible

#25133 [IntraHealth] Hotfix for 500 error in new custom reports
  custom/intrahealth/sqldata.py
Labels: product/custom

#25134 add changed xmlns for cbe form
  custom/icds_reports/ucr/data_sources/cbe_form.json
Labels: product/custom

#25135 [ci skip] add a few simple instructions for loading the dashboard locally
  custom/icds_reports/README.md
Labels: product/custom

#25140 Fixed TestLinkedApps.test_update_from_specific_build
  corehq/apps/linked_domain/tests/test_linked_apps.py
Labels: product/invisible

#25142 Use pip-compile --allow-unsafe throughout
  Makefile
  requirements-python3/dev-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
Labels: product/invisible

#25116 Gather some metrics for app-status-report export
  corehq/apps/reports/tasks.py
Labels: product/invisible

#25125 Util to backfill app-status-facts with build-version
  corehq/warehouse/management/commands/one_off_backfill_version.py
Labels: product/invisible

#25139 Correctly update metadata
  custom/icds_reports/tests/test_aggregation_script.py
  custom/icds_reports/utils/aggregation_helpers/distributed/awc_location.py
  custom/icds_reports/utils/aggregation_helpers/monolith/awc_location.py
Labels: product/custom

#24604 Skip blacklisted app translations in downloads
  corehq/apps/app_manager/static/app_manager/js/settings/translations.js
  corehq/apps/app_manager/templates/app_manager/partials/bulk_upload_app_translations.html
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/app_translations/utils.py
  corehq/apps/translations/generators.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/apps/translations/tests/test_transifex_blacklisting.py
  corehq/apps/translations/validator.py
  corehq/apps/translations/views.py
Labels: product/feature-flag

#25145 Remove Python 2 test jobs
  .travis.yml
Labels: product/invisible

#25065 Fixed behavior of EOF nav to previous screen for forms with parent me…
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/data/form_workflow/advanced-app.xml
  corehq/apps/app_manager/tests/data/form_workflow/advanced_app.json
  corehq/apps/app_manager/tests/data/form_workflow/suite-workflow-previous.xml
  corehq/apps/app_manager/tests/data/suite/child-module-form-workflow-previous.xml
  corehq/apps/app_manager/tests/test_form_workflow.py
  corehq/util/test_utils.py
Labels: product/all-users-all-environments

#24938 Moved resource_versions to YAML and only update it in build_requirejs…
  corehq/apps/hqwebapp/management/commands/resource_static.py
  corehq/apps/hqwebapp/tests/test_static_resource_command.py
  get_resource_versions.py
Labels: product/invisible

#25149 Switch docker file to Python 3
  Dockerfile
Labels: product/invisible

#25152 Ignore absolute_import warning [ci skip]
  .stickler.yml
Labels: product/invisible

#25147 Remove Python 2 requirements and docker
  .travis.yml
  DEV_SETUP.md
  Dockerfile
  Dockerfile-py3
  Makefile
  docker/run.sh
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  scripts/docker
Labels: product/invisible

#25159 Removed python 2 pickle code
  docker/localsettings.py
  localsettings.example.py
  manage.py
Labels: product/invisible

#25146 kill dimagisphere
  corehq/apps/change_feed/management/commands/run_form_websocket_feed.py
  corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js
  corehq/apps/hqadmin/templates/hqadmin/dimagisphere/form_feed.html
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views/__init__.py
  corehq/apps/hqadmin/views/reports.py
  corehq/tabs/tabclasses.py
  docs/change_feeds.rst
Labels: product/invisible

#25162 [IntraHealth] Hotfix for 500 error in new custom reports - set up UCR engine id
  custom/intrahealth/sqldata.py
Labels: product/custom

#25043 [ICDS Dashboard] MPR and ASR report changes
  corehq/apps/reports/filters/fixtures.py
  corehq/apps/reports/generic.py
  corehq/apps/reports/templates/reports/filters/location_async.html
  corehq/apps/reports/templates/reports/standard/partials/filter_panel.html
  custom/icds_reports/reports/reports.py
  custom/icds_reports/static/icds_reports/js/base.js
  custom/icds_reports/templates/icds_reports/icds_app/navigation.directive.html
  custom/icds_reports/ucr/reports/dashboard/asr_2_3_person_cases.json
Labels: product/custom

#25163 properly get engine id
  corehq/sql_db/routers.py
  custom/icds_reports/sqldata/base.py
Labels: product/invisible

#25143 Fix download type for dashboard location changes
  custom/icds_reports/tasks.py
Labels: product/custom

#25008 [ICDS Dashboard] awc data changed from daily table to monthly table in
  custom/icds_reports/reports/cas_reach_data.py
Labels: product/custom

#23998 Aggregate agg_awc_daily for last 3 days
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/reports/test_awc_daily_status.py
  custom/icds_reports/tests/reports/test_awc_reports.py
  custom/icds_reports/tests/reports/test_demographics.py
  custom/icds_reports/tests/reports/test_icds_cas_reach.py
Labels: product/custom
