Repository dimagi/commcare-hq, pull requests merged in 2019-06, with the labels that each got.

#24418 Explore Case Data UI Updates
  corehq/apps/data_interfaces/templates/data_interfaces/explore_case_data.html
  corehq/apps/data_interfaces/views.py
  corehq/apps/hqwebapp/models.py
  corehq/apps/hqwebapp/static/hqwebapp/js/components/pagination.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hq.helpers.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/datagrid.less
  corehq/apps/hqwebapp/templates/hqwebapp/base_section.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/breadcrumbs.html
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/standard/cases/utils.py
  corehq/apps/reports/static/reports/v2/js/context.js
  corehq/apps/reports/static/reports/v2/js/datagrid.js
  corehq/apps/reports/static/reports/v2/js/datagrid/binding_handlers.js
  corehq/apps/reports/static/reports/v2/js/datagrid/columns.js
  corehq/apps/reports/static/reports/v2/js/datagrid/data_models.js
  corehq/apps/reports/static/reports/v2/js/datagrid/report_filters.js
  corehq/apps/reports/static/reports/v2/js/views/explore_case_data.js
  corehq/apps/reports/v2/endpoints/case_properties.py
  corehq/apps/reports/v2/endpoints/case_type.py
  corehq/apps/reports/v2/endpoints/datagrid.py
  corehq/apps/reports/v2/filters/case_report.py
  corehq/apps/reports/v2/formatters/cases.py
  corehq/apps/reports/v2/models.py
  corehq/apps/reports/v2/reports/explore_case_data.py
  corehq/apps/reports/v2/views.py
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments, product/feature-flag

#24462 Refactoring and cleanup of get cases referenced by form
  corehq/apps/api/resources/v0_4.py
  corehq/ex-submodules/casexml/apps/case/xform.py
  corehq/form_processor/parsers/ledgers/form.py
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: product/invisible

#24453 allow filtering by other 'non_analyzed' fields
  corehq/apps/api/es.py
  corehq/apps/api/tests/case_resources.py
  corehq/apps/api/tests/form_resources.py
Labels: product/all-users-all-environments

#24471 Fixed incorrect translations on mobile due to outdated markdown
  corehq/apps/translations/app_translations/upload_form.py
  corehq/apps/translations/tests/data/bulk_app_translation/basic/app.json
  corehq/apps/translations/tests/data/bulk_app_translation/basic/change_upload_form.xml
  corehq/apps/translations/tests/data/bulk_app_translation/basic/change_upload_form_en.xml
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: product/all-users-all-environments

#24474 run modernize
  corehq/apps/case_importer/migrations/0013_make_duplicates_errors.py
Labels: product/invisible

#24469 Add __repr__ method to TimingContext
  corehq/util/timer.py
Labels: product/invisible

#24468 Test restore_config.__repr__() in get_async_restore_payload
  corehq/ex-submodules/casexml/apps/phone/tasks.py
Labels: product/invisible

#24478 Edit case_list media if module.case_list exists
  corehq/apps/app_manager/views/modules.py
Labels: product/all-users-all-environments

#24444 Incorporate session into Requests
  corehq/motech/models.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/requests.py
  corehq/motech/tests/test_models.py
  corehq/motech/tests/test_requests.py
  corehq/motech/tests/test_utils.py
  corehq/motech/utils.py
Labels: product/invisible

#24476 More ignore rules for couch to SQL migration
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/couch_sql_migration/tests/test_diffs.py
Labels: product/invisible

#24480 Add command to show started migrations
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/management/commands/show_started_migrations.py
  corehq/apps/domain_migration_flags/api.py
  corehq/apps/tzmigration/planning.py
Labels: product/invisible

#24475 script for citus qa
  custom/icds_reports/management/commands/dashboard_citus_qa.py
Labels: product/custom

#24396 Bulk conditional alerts: support content upload/download
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bulk_upload.html
  corehq/apps/sms/util.py
  corehq/messaging/scheduling/exceptions.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/tests/test_bulk_conditional_alerts.py
  corehq/messaging/scheduling/view_helpers.py
  corehq/messaging/scheduling/views.py
  corehq/toggles.py
Labels: QA Passed, product/feature-flag

#24486 upgrade django to include latest security update
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#24488 [ICDS] replace the title of section 10 in MPR report fix old typo
  custom/icds_reports/mpr_sqldata.py
Labels: product/custom

#24489 Updated retirement date for old edit forms
  corehq/apps/reports/templates/reports/form/edit_submission.html
  corehq/apps/reports/templates/reports/partials/data_corrections_modal.html
Labels: product/all-users-all-environments

#24485 DRYer tests
  corehq/motech/tests/test_models.py
Labels: product/invisible

#24492 Omit blank lines when there are no diff stats
  corehq/apps/couch_sql_migration/management/commands/show_started_migrations.py
Labels: product/invisible

#24493 Prepare fixtures for db migration
  corehq/apps/fixtures/dbaccessors.py
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/fixtures/models.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/fixtures/upload/run_upload.py
Labels: product/invisible

#24487 update username in nightly web user deletion task
  corehq/apps/cleanup/tasks.py
Labels: product/invisible

#24265 weasy returns
  DEV_SETUP.md
  custom/icds_reports/utils/__init__.py
Labels: product/invisible

#24490 Some small bugfixes for Explore Case Data
  corehq/apps/data_interfaces/templates/data_interfaces/explore_case_data.html
  corehq/apps/data_interfaces/views.py
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/datagrid.less
  corehq/apps/reports/static/reports/v2/js/datagrid/data_models.js
Labels: product/all-users-all-environments, product/feature-flag

#24496 Notify exception in timer stop
  corehq/util/timer.py
Labels: product/invisible

#24491 support legacy API date format
  corehq/apps/api/es.py
Labels: product/all-users-all-environments

#24498 Fixed select2 not updating other filters properly on up-nrhm reports
  custom/up_nrhm/templates/up_nrhm/asha_report.html
Labels: product/custom

#24497 Fixed select2 js error on champ reports
  custom/champ/static/champ/js/knockout/select2-binding.js
Labels: product/custom

#24484 cleanup some expensive DB access
  corehq/apps/case_migrations/migration.py
  corehq/apps/cleanup/tasks.py
  corehq/apps/sms/tasks.py
  corehq/form_processor/backends/couch/dbaccessors.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/document_stores.py
  corehq/form_processor/interfaces/dbaccessors.py
Labels: product/invisible

#24500 Small improvements to show_started_migrations command
  corehq/apps/couch_sql_migration/management/commands/show_started_migrations.py
Labels: product/invisible

#24501 blob backend migrator that checks destination first
  corehq/blobs/migrate.py
Labels: product/invisible

#24499 Only add case filter group which is selected
  corehq/apps/reports/filters/case_list.py
Labels: product/all-users-all-environments

#24505 Fix RestoreConfig.__repr__ error
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/ex-submodules/casexml/apps/phone/tasks.py
Labels: product/invisible

#24312 Optimize pillow startup
  corehq/apps/userreports/pillow.py
Labels: product/invisible

#24461 Fix error when there is large exponent
  corehq/ex-submodules/couchforms/jsonobject_extensions.py
Labels: product/invisible

#24502 Fix case management refresh
  corehq/apps/app_manager/static/app_manager/js/forms/case_knockout_bindings.js
Labels: product/all-users-all-environments

#24338 Ce/static incentive
  corehq/apps/accounting/tasks.py
  corehq/apps/calendar_fixture/fixture_provider.py
  corehq/apps/calendar_fixture/tests.py
  corehq/apps/ota/views.py
  corehq/apps/reports/tasks.py
  corehq/const.py
  corehq/ex-submodules/soil/__init__.py
  corehq/pillows/utils.py
  custom/aaa/const.py
  custom/icds_reports/migrations/0122_incentive_columns.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/reports/incentive.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/aww_incentive.py
  custom/icds_reports/utils/aggregation_helpers/monolith/aww_incentive.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/awc-incentive.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/awc-incentive.monolith.txt
Labels: product/invisible

#24105 Rn add start end time to agg email
  custom/icds_reports/tasks.py
Labels: product/custom

#24518 Install same version of pip-tools as dev-requirements
  scripts/test-make-requirements.sh
Labels: product/invisible

#24479 add index on form_id
  corehq/form_processor/migrations/0091_auto_20190603_2023.py
  corehq/form_processor/models.py
Labels: product/invisible

#24514 Make requirements with pip-tools 3.8.0
  .travis.yml
  requirements-python3/dev-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  scripts/run-tests.sh
  scripts/test-make-requirements.sh
Labels: product/invisible

#24509 Switch docker S3 service from Riak CS to minio
  corehq/blobs/tests/test_s3db.py
  docker/README.md
  docker/hq-compose-runserver.yml
  docker/hq-compose-services.yml
  docker/hq-compose.yml
  docker/localsettings.py
  scripts/docker
Labels: product/invisible

#24341 Add Location columns to app status report just for icds
  corehq/apps/reports/standard/deployments.py
  corehq/toggles.py
Labels: product/custom

#24517 Updated case reassignment select2 to use new API
  corehq/apps/data_interfaces/static/data_interfaces/js/case_management.js
  corehq/apps/data_interfaces/templates/data_interfaces/interfaces/case_management.html
Labels: product/all-users-all-environments

#24523 Revert "cleanup some expensive DB access"
  corehq/apps/case_migrations/migration.py
  corehq/apps/cleanup/tasks.py
  corehq/apps/sms/tasks.py
  corehq/form_processor/backends/couch/dbaccessors.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/document_stores.py
  corehq/form_processor/interfaces/dbaccessors.py
Labels: product/invisible

#24521 fixes to static perf report work
  custom/icds_reports/reports/incentive.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/__init__.py
Labels: product/invisible

#24512 skip query if case list is empty
  custom/icds_reports/reports/awc_reports.py
Labels: product/invisible

#24515 Updated quietMillis to delay
  corehq/apps/accounting/static/accounting/js/widgets.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view_report.js
  corehq/apps/translations/static/translations/js/translations.js
  corehq/apps/users/static/users/js/mobile_workers.ng.js
Labels: product/invisible

#24516 use awc_location_local instead of temp table in citus query
  custom/icds_reports/utils/aggregation_helpers/distributed/inactive_awws.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/inactive-awws.distributed.txt
Labels: product/custom

#24525 Add delete endpoint for blacklist translations
  corehq/apps/translations/integrations/transifex/views.py
  corehq/apps/translations/models.py
  corehq/apps/translations/templates/blacklist_translations.html
  corehq/apps/translations/urls.py
Labels: product/custom

#24528 enforce that Domain.get_all_names return a list of unique names
  corehq/apps/domain/models.py
Labels: product/invisible

#24530 include stack trace with billing record error logging
  corehq/apps/accounting/views.py
  corehq/apps/domain/views/accounting.py
Labels: product/invisible

#24510 Fix UCR renaming on fresh installs
  corehq/apps/userreports/migrations/0009_rename_ucr_tables.py
Labels: product/invisible

#24524 migrating forms a bit DRYer
  corehq/apps/couch_sql_migration/couchsqlmigration.py
Labels: product/invisible

#24529 calculate_users_in_all_domains should not fail hard in case of Integr…
  corehq/apps/accounting/tasks.py
Labels: product/invisible

#24527 fix invoicing when subscription ends in the middle of the month
  corehq/apps/accounting/invoicing.py
Labels: product/invisible

#24534 run modernize
  corehq/messaging/scheduling/tests/test_bulk_conditional_alerts.py
  custom/icds_reports/management/commands/dashboard_citus_qa.py
Labels: product/invisible

#24535 release static perf report
  custom/icds_reports/reports/incentive.py
  custom/icds_reports/tasks.py
Labels: product/custom

#24508 Tools for Explore Case Data Rollout
  corehq/apps/reports/management/commands/enable_case_search_for_ecd.py
  corehq/apps/reports/v2/reports/explore_case_data.py
  corehq/pillows/case_search.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/invisible

#24536 remove warning about unescaped backslash in python 3
  custom/aaa/urls.py
Labels: product/invisible

#24538 Search within question children in form summary
  corehq/apps/app_manager/static/app_manager/js/summary/form_models.js
Labels: product/invisible

#24540 Remove -e from repo requirements
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
Labels: product/invisible

#24539 use values at all levels
  custom/icds_reports/reports/incentive.py
Labels: product/invisible

#24541 turn set to list before passing to celery task using JSON serializer
  corehq/apps/fixtures/models.py
Labels: product/invisible

#24506 Fix assign case regression
  corehq/apps/reports/filters/case_list.py
Labels: product/all-users-all-environments

#24543 use csv342 in test
  custom/icds_reports/tests/test_inactive_dashboard_users.py
Labels: product/invisible

#24544 decode request.body before passing to json.loads
  corehq/apps/api/es.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/app_manager/views/settings.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/cloudcare/views.py
  corehq/apps/domain/views/settings.py
  corehq/apps/export/views/new.py
  corehq/apps/hqwebapp/session_details_endpoint/views.py
  corehq/apps/reports/views.py
  corehq/apps/userreports/views.py
  corehq/apps/users/views/__init__.py
  corehq/apps/zapier/views.py
  corehq/messaging/smsbackends/apposit/views.py
  corehq/messaging/smsbackends/tropo/views.py
  custom/champ/views.py
  custom/zipline/views.py
Labels: product/invisible

#24533 Revert 24523 revert 24484 sk/get by domain
  corehq/apps/case_migrations/migration.py
  corehq/apps/change_feed/data_sources.py
  corehq/apps/cleanup/tasks.py
  corehq/apps/sms/tasks.py
  corehq/form_processor/backends/couch/dbaccessors.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/document_stores.py
  corehq/form_processor/interfaces/dbaccessors.py
  corehq/form_processor/tests/test_reindex_accessors.py
Labels: product/invisible

#24537 Renamed some variables and functions
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
Labels: product/invisible

#24542 Added very basic linked app docs
  corehq/apps/linked_domain/README.md
Labels: product/invisible

#24503 Always interact with global items via IO
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/fixtures/tests/test_fixture_data.py
Labels: product/invisible

#24522 Run test-make-requirements.sh after other tests
  .gitignore
  .travis.yml
  Dockerfile
  Dockerfile-py3
  Makefile
  docker/run.sh
  requirements-python3/dev-requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
  scripts/pip-post-compile-edx.sh
  scripts/pip-post-compile.sh
  scripts/run-tests.sh
  scripts/test-make-requirements.sh
Labels: product/invisible

#24481 Implement OData feed for forms
  corehq/apps/api/odata/serializers.py
  corehq/apps/api/odata/tests/data/populated_case_metadata_document.xml
  corehq/apps/api/odata/tests/data/populated_form_metadata_document.xml
  corehq/apps/api/odata/tests/test_feed.py
  corehq/apps/api/odata/tests/test_metadata.py
  corehq/apps/api/odata/tests/test_service.py
  corehq/apps/api/odata/tests/test_utils.py
  corehq/apps/api/odata/tests/utils.py
  corehq/apps/api/odata/utils.py
  corehq/apps/api/odata/views.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/templates/api/odata_form_metadata.xml
  corehq/apps/api/urls.py
Labels: product/feature-flag

#24546 explicitly try encoding sent text as ascii instead of using python2's…
  corehq/messaging/smsbackends/unicel/models.py
  corehq/messaging/smsbackends/vertex/models.py
Labels: product/invisible

#24552 add mirroring for ICDS citus
  custom/icds_reports/ucr/data_sources/awc_locations.json
  custom/icds_reports/ucr/data_sources/awc_mgt_forms.json
  custom/icds_reports/ucr/data_sources/cbe_form.json
  custom/icds_reports/ucr/data_sources/ccs_record_cases.json
  custom/icds_reports/ucr/data_sources/ccs_record_cases_monthly_v2.json
  custom/icds_reports/ucr/data_sources/child_cases_monthly_v2.json
  custom/icds_reports/ucr/data_sources/child_delivery_forms.json
  custom/icds_reports/ucr/data_sources/child_health_cases.json
  custom/icds_reports/ucr/data_sources/daily_feeding_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/birth_preparedness_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/child_tasks.json
  custom/icds_reports/ucr/data_sources/dashboard/commcare_user_cases.json
  custom/icds_reports/ucr/data_sources/dashboard/complementary_feeding_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/daily_feeding_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/dashboard_growth_monitoring.json
  custom/icds_reports/ucr/data_sources/dashboard/delivery_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/postnatal_care_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/pregnant_tasks.json
  custom/icds_reports/ucr/data_sources/dashboard/thr_forms.json
  custom/icds_reports/ucr/data_sources/gm_forms.json
  custom/icds_reports/ucr/data_sources/hardware_cases.json
  custom/icds_reports/ucr/data_sources/home_visit_forms.json
  custom/icds_reports/ucr/data_sources/household_cases.json
  custom/icds_reports/ucr/data_sources/infrastructure_form.json
  custom/icds_reports/ucr/data_sources/infrastructure_form_v2.json
  custom/icds_reports/ucr/data_sources/it_report_follow_issue.json
  custom/icds_reports/ucr/data_sources/ls_home_visit_forms_filled.json
  custom/icds_reports/ucr/data_sources/ls_vhnd_form.json
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
  custom/icds_reports/ucr/data_sources/tasks_cases.json
  custom/icds_reports/ucr/data_sources/tech_issue_cases.json
  custom/icds_reports/ucr/data_sources/thr_forms_v2.json
  custom/icds_reports/ucr/data_sources/usage_forms.json
  custom/icds_reports/ucr/data_sources/vhnd_form.json
  custom/icds_reports/ucr/data_sources/visitorbook_forms.json
Labels: product/custom

#24455 Static data source and report for REACH mobile indicators 1-9
  custom/aaa/ucr/data_sources/pop_totals_person_mobile.json
  custom/aaa/ucr/reports/mpr_pop_totals_1_to_9.json
  settings.py
Labels: product/custom

#24513 fix household calculation
  custom/icds_reports/tests/fixtures/household_cases.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/reports/test_demographics.py
  custom/icds_reports/tests/reports/test_registered_household.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/tests/test_fact_sheet_report.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/monolith/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc_weekly.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc_weekly.monolith.txt
Labels: product/custom

#24547 citus migration readme
  custom/icds_reports/management/commands/create_citus_child_tables.py
  custom/icds_reports/management/commands/generate_migration_tables.py
  custom/icds_reports/scripts/README.md
  custom/icds_reports/scripts/migrate_tables.py
Labels: product/custom

#24557 Actually delete fixture ownership docs
  corehq/apps/fixtures/tasks.py
Labels: product/invisible

#24556 icds citus migration improvements
  custom/icds_reports/scripts/migrate_tables.py
Labels: product/custom

#24520 don't use temp table where it isn't needed
  custom/icds_reports/utils/aggregation_helpers/distributed/aww_incentive.py
  custom/icds_reports/utils/aggregation_helpers/monolith/aww_incentive.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/awc-incentive.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/awc-incentive.monolith.txt
Labels: product/invisible

#24561 Refactor command line parameters for couch2sql management command
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
Labels: product/invisible

#24563 More gracefully handle forms with missing XML
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/show_started_migrations.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
Labels: product/invisible

#24564 Fix success setting in s3 deletes
  corehq/blobs/s3db.py
Labels: product/invisible

#24569 workaround for travis failure in python 3
  corehq/util/tests/test_teeout.py
Labels: product/invisible

#24562 Update Product feature flags
  corehq/toggles.py
Labels: product/admin

#24565 add soft asserts when processing incoming SMS
  corehq/apps/sms/api.py
  corehq/messaging/smsbackends/grapevine/models.py
Labels: product/invisible

#24566 more tweaks to citus migration
  custom/icds_reports/management/commands/generate_migration_tables.py
  custom/icds_reports/scripts/README.md
  custom/icds_reports/scripts/migrate_tables.py
Labels: product/custom

#24243 Web user reports project access
  corehq/apps/accounting/enterprise.py
  corehq/apps/app_manager/tasks.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/domain/project_access/middleware.py
  corehq/apps/users/models.py
  corehq/apps/users/tasks.py
Labels: QA Passed, product/all-users-all-environments

#24567 Remove outdated blob migration code
  corehq/form_processor/management/commands/run_sql.py
  corehq/form_processor/tests/test_run_sql.py
Labels: product/invisible

#24574 Revert "show Max unique sop's from the beginning of data collection"
  custom/abt/reports/views.py
Labels: product/custom

#24571 rename _sms_content_is_unicode to _py3_soft_assert
  corehq/apps/sms/api.py
Labels: product/invisible

#24573 OData Configuration for Forms
  corehq/apps/dashboard/models.py
  corehq/apps/domain/calculations.py
  corehq/apps/export/dbaccessors.py
  corehq/apps/export/tests/test_dbaccessors.py
  corehq/apps/export/tests/test_export_views.py
  corehq/apps/export/urls.py
  corehq/apps/export/views/edit.py
  corehq/apps/export/views/list.py
  corehq/apps/export/views/new.py
  corehq/apps/export/views/utils.py
  corehq/couchapps/export_instances_by_domain/views/view/map.js
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments, product/feature-flag

#24577 remove comments
  corehq/apps/reports/signals.py
Labels: product/invisible

#24560 AB test MPR/ASR dynamic-agg, fix dd issues
  corehq/toggles.py
  custom/icds_reports/resources/block_mpr.json
  custom/icds_reports/utils/__init__.py
Labels: product/invisible

#24578 Added support for case list menu item label to bulk app translations
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/app_translations/upload_module.py
  corehq/apps/translations/tests/data/bulk_app_translation/basic/app.json
  corehq/apps/translations/tests/data/bulk_app_translation/download/app.json
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: product/all-users-all-environments

#24570 Correctly access location type name
  custom/icds_reports/views.py
Labels: product/custom

#24572 Extract queue and pool logic into a class
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
Labels: product/invisible

#24553 CAS Data export for previous month available from the 1st day of the current month
  custom/icds_reports/static/js/directives/cas-export/cas-export.directive.js
Labels: product/custom

#24532 [ICDS] Added logging information when 0 in Program Summary report
  custom/icds_reports/reports/awc_infrastracture.py
  custom/icds_reports/reports/cas_reach_data.py
  custom/icds_reports/reports/demographics_data.py
  custom/icds_reports/reports/maternal_child.py
  custom/icds_reports/utils/data_accessor.py
  custom/icds_reports/views.py
Labels: product/invisible

#24554 Explore Case Data migration script update
  corehq/apps/reports/management/commands/enable_case_search_for_ecd.py
Labels: product/invisible

#24588 Tiny update to ECD migration script
  corehq/apps/reports/management/commands/enable_case_search_for_ecd.py
Labels: product/invisible

#24580 filter OData feed by case type
  corehq/apps/api/resources/v0_5.py
Labels: product/invisible

#24585 run modernize
  corehq/apps/reports/management/commands/enable_case_search_for_ecd.py
  custom/icds_reports/scripts/migrate_tables.py
Labels: product/invisible

#24550 correct elgibility calculation
  custom/icds_reports/utils/aggregation_helpers/distributed/aww_incentive.py
  custom/icds_reports/utils/aggregation_helpers/monolith/aww_incentive.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/awc-incentive.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/awc-incentive.monolith.txt
Labels: product/invisible

#24584 Fix table for the 1366x768 resolution and smaller
  custom/icds_reports/static/css/icds_dashboard.css
  custom/icds_reports/templates/icds_reports/icds_app/progress-report.directive.html
Labels: product/custom

#24575 Add solutions feature flag recommendations
  corehq/apps/toggle_ui/static/toggle_ui/js/flags.js
  corehq/apps/toggle_ui/views.py
  corehq/tests/test_toggles.py
  corehq/toggles.py
Labels: product/admin

#24587 ECD Report Feedback, pt1
  corehq/apps/data_interfaces/templates/data_interfaces/explore_case_data.html
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/datagrid.less
  corehq/apps/hqwebapp/templates/hqwebapp/partials/ko_feedback.html
  corehq/apps/reports/static/reports/v2/js/datagrid/columns.js
  corehq/apps/reports/static/reports/v2/js/datagrid/data_models.js
  corehq/apps/reports/v2/filters/xpath_column.py
  corehq/apps/reports/v2/reports/explore_case_data.py
Labels: product/feature-flag

#24579 ignore form export schema without group_schemas
  corehq/apps/api/odata/utils.py
Labels: product/invisible

#24494 Bulk conditional alerts: custom schedules
  corehq/messaging/scheduling/tests/test_bulk_conditional_alerts.py
  corehq/messaging/scheduling/view_helpers.py
Labels: QA Passed, product/feature-flag

#24591 Fixed spacing in case_management.html
  corehq/apps/data_interfaces/templates/data_interfaces/interfaces/case_management.html
Labels: product/invisible

#24581 don't soft assert when text is None
  corehq/apps/sms/api.py
Labels: product/invisible

#24586 Persist migration state so it is not lost on stop/resume
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
  corehq/apps/tzmigration/planning.py
  corehq/ex-submodules/dimagi/utils/chunked.py
Labels: product/invisible

#24593 List Last Access Date before domain name
  corehq/apps/accounting/enterprise.py
Labels: product/all-users-all-environments

#24598 Add Last Access Date header to headers list
  corehq/apps/accounting/enterprise.py
Labels: product/all-users-all-environments

#24594 ICDS SMS: kan translations
  custom/icds/templates/icds/messaging/indicators/kan/aww_aggregate_performance.txt
  custom/icds/templates/icds/messaging/indicators/kan/aww_no_submissions.txt
  custom/icds/templates/icds/messaging/indicators/kan/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/kan/beneficiary_negative_growth.txt
  custom/icds/templates/icds/messaging/indicators/kan/beneficiary_static_growth.txt
  custom/icds/templates/icds/messaging/indicators/kan/cf_visits_complete.txt
  custom/icds/templates/icds/messaging/indicators/kan/child_illness_reported.txt
  custom/icds/templates/icds/messaging/indicators/kan/child_vaccinations_complete.txt
  custom/icds/templates/icds/messaging/indicators/kan/dpt3_and_measles_due.txt
  custom/icds/templates/icds/messaging/indicators/kan/ls_aggregate_performance.txt
  custom/icds/templates/icds/messaging/indicators/kan/ls_no_submissions.txt
  custom/icds/templates/icds/messaging/indicators/kan/ls_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/kan/missed_cf_visit_to_aww.txt
  custom/icds/templates/icds/messaging/indicators/kan/missed_cf_visit_to_ls.txt
  custom/icds/templates/icds/messaging/indicators/kan/missed_pnc_visit_to_ls.txt
Labels: product/custom

#24597 Fixed releases page pagination using 10 instead of cookie value
  corehq/apps/app_manager/static/app_manager/js/releases/app_view_release_manager.js
Labels: product/all-users-all-environments

#24599 avoid nonetype error
  corehq/messaging/smsbackends/grapevine/models.py
Labels: product/invisible

#24548 Fix new lang update
  corehq/apps/app_manager/templates/app_manager/partials/settings/app_settings.html
  corehq/apps/translations/utils.py
Labels: product/feature-flag

#24601 fix vertex tests in python 3
  corehq/messaging/smsbackends/vertex/tests/test_request.py
Labels: product/invisible

#24600 updates to case OData format
  corehq/apps/api/odata/serializers.py
  corehq/apps/api/odata/tests/data/populated_case_metadata_document.xml
  corehq/apps/api/odata/tests/test_serializers.py
  corehq/apps/api/odata/utils.py
  corehq/apps/api/odata/views.py
  corehq/apps/api/templates/api/odata_metadata.xml
Labels: product/feature-flag

#24568 Location-safe case import
  corehq/apps/case_importer/base.py
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/exceptions.py
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/case_importer/tests/test_owner.py
  corehq/apps/case_importer/tracking/dbaccessors.py
  corehq/apps/case_importer/tracking/permissions.py
  corehq/apps/case_importer/tracking/tests/test_dbaccessors.py
  corehq/apps/case_importer/tracking/views.py
  corehq/apps/case_importer/urls.py
  corehq/apps/case_importer/views.py
  corehq/toggles.py
Labels: product/all-users-all-environments

#24611 Text updates for sub-menus feature
  corehq/apps/app_manager/templates/app_manager/partials/menu/appnav_menu.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_settings.html
  corehq/apps/app_manager/views/modules.py
  corehq/toggles.py
Labels: product/feature-flag

#24608 Add message about disabled configuration option
  corehq/messaging/scheduling/forms.py
Labels: product/invisible

#24607 Skip messaging rule run for inactive rule
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/messaging/management/commands/import_conditional_alerts.py
  corehq/messaging/scheduling/view_helpers.py
  corehq/messaging/scheduling/views.py
  corehq/messaging/tasks.py
Labels: product/invisible

#24610 Add pagination to case id fetching
  corehq/messaging/tasks.py
  corehq/sql_db/util.py
Labels: product/all-users-all-environments

#24590 Update weighing efficiency in performance report
  custom/icds_reports/migrations/0117_awc_location_local.py
  custom/icds_reports/migrations/0123_weighing_new_columng_agg_awc.py
  custom/icds_reports/migrations/0124_update_agg_awc_view.py
  custom/icds_reports/migrations/sql_templates/database_views/agg_awc_monthly.sql
  custom/icds_reports/migrations/sql_templates/update_tables46.sql
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_awc_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/distributed/aww_incentive.py
  custom/icds_reports/utils/aggregation_helpers/monolith/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/monolith/aww_incentive.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc_weekly.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc_weekly.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/awc-incentive.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/awc-incentive.monolith.txt
Labels: product/custom

#24576 Optimize usage forms queries
  custom/icds_reports/tests/test_aggregation_script.py
  custom/icds_reports/utils/aggregation_helpers/distributed/inactive_awws.py
  custom/icds_reports/utils/aggregation_helpers/monolith/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/monolith/inactive_awws.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc_weekly.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/inactive-awws.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/inactive-awws.monolith.txt
Labels: product/custom

#24583 Add command to update invalid phone numbers
  custom/icds/management/commands/sanitize_phone_numbers.py
Labels: product/custom

#24615 pull out methods into functions
  corehq/apps/api/odata/serializers.py
  corehq/apps/api/odata/tests/test_serializers.py
Labels: product/invisible

#24612 add tests for sending unicel and fix sending in python 3
  corehq/messaging/smsbackends/unicel/models.py
  corehq/messaging/smsbackends/unicel/tests/test_send.py
Labels: product/invisible

#24613 Removed unnecessary assignment
  corehq/messaging/scheduling/view_helpers.py
Labels: product/invisible

#24614 cleanup users created in tests
  custom/ilsgateway/tests/test_reminders2.py
  custom/ilsgateway/tests/test_report_reminders.py
Labels: product/invisible

#24606 Add and fix some tests for the couch to SQL forms and cases migration
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/ex-submodules/dimagi/utils/tests/test_chunked.py
Labels: product/invisible

#24595 Add pillow ETL metrics
  corehq/apps/userreports/pillow.py
  corehq/ex-submodules/pillowtop/processors/elastic.py
Labels: product/invisible

#24620 Remove unnecessary pillow deletes
  corehq/apps/userreports/pillow.py
Labels: product/invisible

#24589 Fix "Unknown Module" in Add Export modal
  corehq/apps/app_manager/fields.py
Labels: product/all-users-all-environments

#24621 Headers should skip Transifex too
  corehq/apps/translations/validator.py
Labels: product/invisible

#24625 Try get the first value
  corehq/apps/cleanup/tasks.py
Labels: product/invisible

#24622 Fixes module reordering error
  corehq/apps/translations/app_translations/upload_app.py
  corehq/apps/translations/app_translations/utils.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/apps/translations/views.py
Labels: product/invisible

#24628 Odata QA followup
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/apps/export/templates/export/partials/customize_export_header.html
  corehq/apps/export/templates/export/partials/new_customize_export_templates.html
  corehq/apps/export/views/__init__.py
  corehq/apps/export/views/edit.py
  corehq/apps/export/views/list.py
  corehq/apps/export/views/new.py
  corehq/apps/export/views/utils.py
Labels: product/feature-flag

#24629 Add/update mar translation files
  custom/icds/templates/icds/messaging/indicators/mar/aww_aggregate_performance.txt
  custom/icds/templates/icds/messaging/indicators/mar/aww_no_submissions.txt
  custom/icds/templates/icds/messaging/indicators/mar/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/mar/beneficiary_negative_growth.txt
  custom/icds/templates/icds/messaging/indicators/mar/beneficiary_static_growth.txt
  custom/icds/templates/icds/messaging/indicators/mar/cf_visits_complete.txt
  custom/icds/templates/icds/messaging/indicators/mar/child_illness_reported.txt
  custom/icds/templates/icds/messaging/indicators/mar/ls_aggregate_performance.txt
  custom/icds/templates/icds/messaging/indicators/mar/ls_no_submissions.txt
  custom/icds/templates/icds/messaging/indicators/mar/ls_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/mar/missed_cf_visit_to_aww.txt
  custom/icds/templates/icds/messaging/indicators/mar/missed_cf_visit_to_ls.txt
  custom/icds/templates/icds/messaging/indicators/mar/missed_pnc_visit_to_ls.txt
Labels: product/custom

#24638 Add/update mar translation files
  custom/icds/templates/icds/messaging/indicators/mar/aww_aggregate_performance.txt
  custom/icds/templates/icds/messaging/indicators/mar/aww_no_submissions.txt
  custom/icds/templates/icds/messaging/indicators/mar/aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/mar/beneficiary_negative_growth.txt
  custom/icds/templates/icds/messaging/indicators/mar/beneficiary_static_growth.txt
  custom/icds/templates/icds/messaging/indicators/mar/cf_visits_complete.txt
  custom/icds/templates/icds/messaging/indicators/mar/child_illness_reported.txt
  custom/icds/templates/icds/messaging/indicators/mar/ls_aggregate_performance.txt
  custom/icds/templates/icds/messaging/indicators/mar/ls_no_submissions.txt
  custom/icds/templates/icds/messaging/indicators/mar/ls_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/mar/missed_cf_visit_to_aww.txt
  custom/icds/templates/icds/messaging/indicators/mar/missed_cf_visit_to_ls.txt
  custom/icds/templates/icds/messaging/indicators/mar/missed_pnc_visit_to_ls.txt
Labels: product/custom

#24630 Add description and docs link for Custom Data flag
  corehq/toggles.py
Labels: product/feature-flag

#24631 Make auxiliary case views location-safe
  corehq/apps/api/object_fetch_api.py
  corehq/apps/locations/permissions.py
  corehq/apps/reports/static/reports/js/case_details.js
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#24635 Nit: "type_code" could also be missing
  corehq/blobs/metadata.py
  corehq/blobs/tests/test_metadata.py
Labels: product/invisible

#24641 run modernize
  corehq/messaging/scheduling/view_helpers.py
  custom/icds/management/commands/sanitize_phone_numbers.py
Labels: product/invisible

#24624 Add new field to thr ucr for new image question
  custom/icds_reports/ucr/data_sources/thr_forms_v2.json
  custom/icds_reports/ucr/tests/data/thr_form_v2.xml
  custom/icds_reports/ucr/tests/data/thr_form_v2_without_image.xml
  custom/icds_reports/ucr/tests/test_thr_v2_ucr.py
Labels: product/custom

#24632 SMS improvements
  corehq/messaging/tasks.py
  corehq/messaging/util.py
Labels: product/invisible

#24627 use own method, not subclass's method
  corehq/apps/api/odata/tests/utils.py
Labels: product/invisible

#24646 Add create_only flag to plproxy config for monolith deploy
  corehq/sql_db/management/commands/configure_pl_proxy_cluster.py
Labels: product/invisible

#24647 Show service success if Rabbit is not needed
  corehq/apps/hqadmin/service_checks.py
Labels: product/invisible
