Repository dimagi/commcare-hq, pull requests merged in 2019-12, with the labels that each got.

#26097 override X-Frame-Options header for mobile dashboard
  custom/icds_reports/mobile_views.py
Labels: product/custom

#26092 [ICDS Dashboard] update mwcd api format
  custom/icds_reports/reports/mwcd_indicators.py
  custom/icds_reports/tests/agg_tests/test_nic_indicators_api.py
Labels: product/custom

#26073 signals for management command + DD event
  corehq/apps/domain/management/commands/make_superuser.py
  corehq/apps/hqadmin/app_config.py
  corehq/apps/hqadmin/signals.py
  corehq/util/signals.py
  settings.py
Labels: product/invisible

#26098 Ce/gevent pool
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/tasks.py
Labels: product/invisible

#26083 [Community / Trial Revamp] Merge in Data Forwarding privilege changes
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0045_grandfather_data_forwarding_privs.py
  corehq/apps/accounting/migrations/0046_new_plans.py
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/reports/dispatcher.py
  corehq/motech/repeaters/signals.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/repeaters.py
  corehq/privileges.py
  corehq/tabs/tabclasses.py
Labels: product/prod-india-all-users

#26090 [IntraHealth] Recap Passage 2 update
  custom/intrahealth/sqldata.py
Labels: product/custom

#26077 fix blobdb delete metrics
  corehq/blobs/metadata.py
Labels: product/invisible

#26080 Get any values from Observations
  corehq/motech/exceptions.py
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/tests/test_atom_feed.py
  corehq/motech/value_source.py
Labels: product/feature-flag

#26104 order agg states by awcs
  custom/icds_reports/management/commands/create_aggregation_record.py
Labels: product/invisible

#26106 skip failing tests
  custom/icds/tests/test_aww_vhnd_survey.py
  custom/icds/tests/test_ls_vhnd_survey.py
Labels: product/invisible

#26084 ICDS Dashboard: wire up mobile location selectors
  custom/icds_reports/static/icds_reports/mobile/css/app.less
  custom/icds_reports/static/icds_reports/mobile/css/filters.less
  custom/icds_reports/static/icds_reports/mobile/images/back-icon.png
  custom/icds_reports/static/icds_reports/mobile/images/drop-down-icon.png
  custom/icds_reports/static/icds_reports/mobile/images/filter-top-section.png
  custom/icds_reports/static/js/angular-services/locations.service.js
  custom/icds_reports/static/js/directives/filter-opener/filter-opener.directive.js
  custom/icds_reports/static/js/directives/location-filter/location-filter.directive.js
  custom/icds_reports/static/js/directives/mobile-filters/mobile-filters.directive.js
  custom/icds_reports/static/js/directives/program-summary/program-summary.directive.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/filter-opener.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/location_filter.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/mobile-filters.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/program-summary.directive.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
Labels: product/custom

#26107 filter options for UcrReconciliationStatusAdmin
  custom/icds_reports/admin.py
Labels: product/invisible

#26102 Fix reconcile task
  custom/icds_reports/tasks.py
Labels: product/custom

#26069 Remove fire_signals from user saves for reporting data
  corehq/apps/users/tasks.py
  corehq/ex-submodules/pillowtop/processors/form.py
Labels: product/invisible

#26066 Correct growth monitoring forms indexes
  custom/icds_reports/ucr/data_sources/dashboard/dashboard_growth_monitoring.json
Labels: product/custom

#26044 Refactor value source
  corehq/motech/const.py
  corehq/motech/dhis2/dhis2_config.py
  corehq/motech/dhis2/events_helpers.py
  corehq/motech/dhis2/tests/test_dhis_config.py
  corehq/motech/dhis2/tests/test_events_helpers.py
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/finders.py
  corehq/motech/openmrs/models.py
  corehq/motech/openmrs/openmrs_config.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/tasks.py
  corehq/motech/openmrs/tests/test_finders.py
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/openmrs/tests/test_workflow_tasks.py
  corehq/motech/openmrs/workflow_tasks.py
  corehq/motech/tests/test_value_source.py
  corehq/motech/value_source.py
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/feature-flag

#26103 [ICDS Dashboard] Fix SDD to use pse eligible
  custom/icds_reports/migrations/0151_fix_sdd_view.py
  custom/icds_reports/migrations/sql_templates/database_views/service_delivery_monthly.sql
  custom/icds_reports/tests/agg_tests/reports/test_service_delivery.py
Labels: product/custom

#25920 MOTECH docs
  corehq/motech/README.md
  corehq/motech/dhis2/README.md
  corehq/motech/docs/value_source.rst
  corehq/motech/openmrs/docs/index.rst
  corehq/motech/openmrs/finders.py
  corehq/motech/openmrs/openmrs_config.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/repeaters/README.md
  corehq/motech/repeaters/models.py
  corehq/motech/value_source.py
  docs/index.rst
  docs/openmrs.rst
Labels: product/invisible

#26035 Track build profile id via heartbeat
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_profile.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/ota/views.py
  corehq/apps/receiverwrapper/util.py
  corehq/apps/reports/standard/deployments.py
  corehq/apps/users/models.py
  corehq/apps/users/util.py
  corehq/ex-submodules/phonelog/utils.py
  corehq/toggles.py
  custom/icds/tasks/__init__.py
  custom/icds/views/hosted_ccz.py
  custom/icds_reports/views.py
Labels: product/custom

#26078 Sk/query routing
  corehq/apps/cleanup/management/commands/dedupe_case_indices.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/staterebuilder.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/sql/load.py
  corehq/apps/export/models/new.py
  corehq/apps/reports/management/commands/project_stats_report.py
  corehq/apps/users/models.py
  corehq/blobs/metadata.py
  corehq/blobs/migrate.py
  corehq/blobs/migrate_metadata.py
  corehq/blobs/models.py
  corehq/blobs/tests/test_blob_timeout.py
  corehq/blobs/tests/test_metadata.py
  corehq/blobs/tests/test_migrate_metadata.py
  corehq/blobs/tests/util.py
  corehq/ex-submodules/casexml/apps/phone/tasks.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/management/commands/populate_form_date_modified.py
  corehq/form_processor/models.py
  corehq/form_processor/tests/test_case_dbaccessor.py
  corehq/form_processor/tests/test_form_dbaccessor.py
  corehq/form_processor/tests/test_serialization.py
  corehq/form_processor/tests/utils.py
  corehq/messaging/scheduling/scheduling_partitioned/tests/test_dbaccessors_partitioned.py
  corehq/sql_db/models.py
  corehq/sql_db/routers.py
  corehq/sql_db/shard_data_management.py
  corehq/sql_db/tests/test_model_partitioning.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/base.py
Labels: Open for review: do not merge, product/invisible

#26108 using India time in filter
  custom/icds/messaging/indicators.py
  custom/icds/tests/test_aww_vhnd_survey.py
  custom/icds/tests/test_ls_vhnd_survey.py
Labels: product/invisible

#26087 support declaring icds toggles via localsettings
  corehq/toggles.py
  settings.py
Labels: product/invisible

#26113 Add tools to migrate missing forms and resolve diffs
  corehq/apps/couch_sql_migration/asyncforms.py
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/couch_sql_migration/diffrule.py
  corehq/apps/couch_sql_migration/json2xml.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_asyncforms.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_diffs.py
  corehq/apps/couch_sql_migration/tests/test_json2xml.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
  corehq/blobs/models.py
  corehq/form_processor/backends/sql/update_strategy.py
Labels: product/invisible

#26099 Parse DHIS2 import summaries
  corehq/motech/dhis2/parse_response.py
  corehq/motech/dhis2/tests/data/ignored.json
  corehq/motech/dhis2/tests/data/imported.json
  corehq/motech/dhis2/tests/test_parse_response.py
Labels: product/feature-flag

#26100 [Community / Trial Revamp] Update pricing plan descriptions
  corehq/apps/accounting/models.py
  corehq/apps/accounting/user_text.py
  corehq/apps/domain/views/accounting.py
  corehq/apps/hqwebapp/static/accounting/less/pricing-main.less
Labels: product/prod-india-all-users

#26095 Rate limit by the number of users "allocated"
  corehq/apps/accounting/tests/utils.py
  corehq/apps/sms/tests/opt_tests.py
  corehq/apps/sms/tests/test_backends.py
  corehq/apps/sms/tests/util.py
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/test_get_n_users_for_rate_limiting.py
  corehq/project_limits/tests/test_rate_limiter.py
Labels: product/invisible

#26101 remove numeric id default length restriction in web apps
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
Labels: product/all-users-all-environments

#26114 Fix permanent unprocessed archive stubs
  corehq/apps/userreports/tasks.py
  corehq/form_processor/tests/test_form_dbaccessor.py
Labels: product/invisible

#26048 Cleanup indexes on citus
  custom/icds_reports/migrations/0150_update_agg_awc_monthly_view.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/ucr/data_sources/child_delivery_forms.json
  custom/icds_reports/ucr/data_sources/daily_feeding_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/daily_feeding_forms.json
  custom/icds_reports/ucr/data_sources/thr_forms_v2.json
  custom/icds_reports/ucr/data_sources/visitorbook_forms.json
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc_daily.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc-daily.distributed.txt
Labels: product/custom

#26112 Remove force_citus_engine
  corehq/sql_db/routers.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/test_nic_indicators_api.py
  custom/icds_reports/utils/data_accessor.py
  custom/icds_reports/views.py
Labels: product/custom

#26120 Remove always_enabled/disabled support from HQ code
  corehq/toggles.py
Labels: product/invisible

#26121 update expresssion to ignore blank values
  corehq/apps/userreports/reports/sum_when_templates.py
Labels: product/custom

#26119 [Exports] Improve performance of get_column in TableConfiguration
  corehq/apps/export/models/new.py
  corehq/toggles.py
Labels: product/all-users-all-environments, product/feature-flag

#26122 add translations for urdu
  custom/icds_reports/ucr/reports/ls/ls_report_child_names.json
  custom/icds_reports/ucr/reports/ls/ls_report_child_nutrition_status.json
  custom/icds_reports/ucr/reports/ls/ls_report_lbw_pre_term.json
  custom/icds_reports/ucr/reports/ls/ls_report_pregnant_women_names.json
  custom/icds_reports/ucr/reports/mpr/mpr_2bi_preg_delivery_death_list.json
  custom/icds_reports/ucr/reports/mpr/mpr_2bii_child_death_list.json
  custom/icds_reports/ucr/reports/mpr/mpr_2ci_child_birth_list.json
Labels: product/custom

#26109 update static UCRs
  custom/icds_reports/ucr/data_sources/daily_feeding_forms.json
  custom/icds_reports/ucr/reports/mpr/mpr_1_person_cases.json
  custom/icds_reports/ucr/reports/mpr/mpr_2bii_child_death_list.json
Labels: product/custom

#26127 Route formplayer requests based on user_id, not sessionid
  corehq/apps/cloudcare/middleware.py
  corehq/apps/formplayer_api/smsforms/api.py
  settings.py
Labels: product/invisible

#26117 change "data syncs" to "data submissions" on dashboard footer and exports
  custom/icds_reports/reports/incentive.py
  custom/icds_reports/templates/icds_reports/icds_app/program-summary.directive.html
  custom/icds_reports/tests/agg_tests/test_export_data.py
Labels: product/custom

#26126 only create standby proxy if it is configured
  corehq/sql_db/management/commands/configure_pl_proxy_cluster.py
Labels: product/invisible

#26123 Casting value source
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/workflow_tasks.py
  corehq/motech/value_source.py
Labels: product/invisible

#26070 [ICDS Dashboard] Restrict access to usage report for block users
  custom/icds_reports/dashboard_utils.py
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/partials/dashboard_initial_page_data.html
Labels: product/custom

#26129 Make reprocess_archive_stubs run serially
  corehq/apps/userreports/tasks.py
Labels: product/invisible

#26135 Move reprocess_archive_stubs task to form_processor/tasks.py
  corehq/apps/userreports/tasks.py
  corehq/ex-submodules/couchforms/tests/test_archive.py
  corehq/form_processor/tasks.py
Labels: product/invisible

#26138 Document current status of AAA
  custom/aaa/README.md
Labels: product/custom

#26134 Mark migration flag "solutions limited"
  corehq/toggles.py
Labels: product/feature-flag

#26079 Removed feature flag STOCK_AND_RECEIPT_SMS_HANDLER
  corehq/apps/commtrack/sms.py
  corehq/apps/commtrack/tests/test_sms_reporting.py
  corehq/toggles.py
  custom/ewsghana/models.py
Labels: product/feature-flag

#26137 Disable intermittently failing aaa mocha test pregnant_women.spec.js
  Gruntfile.js
  custom/aaa/static/aaa/spec/filters/beneficiary_type_filter.spec.js
  custom/aaa/static/aaa/spec/filters/location_filter.spec.js
  custom/aaa/static/aaa/spec/filters/month_year_filter.spec.js
  custom/aaa/static/aaa/spec/fixture/program_overview_fixture.js
  custom/aaa/static/aaa/spec/models/child.spec.js
  custom/aaa/static/aaa/spec/models/eligible_couple.spec.js
  custom/aaa/static/aaa/spec/models/model_utils.spec.js
  custom/aaa/static/aaa/spec/models/person.spec.js
  custom/aaa/static/aaa/spec/models/pregnant_women.spec.js
  custom/aaa/static/aaa/spec/reports/program_overview.spec.js
  custom/aaa/static/aaa/spec/reports/unified_beneficiary.spec.js
  custom/aaa/static/aaa/spec/reports/unified_beneficiary_details.spec.js
  custom/aaa/static/aaa/spec/utils/reach_utils.spec.js
  custom/aaa/templates/aaa/spec/mocha.html
Labels: product/invisible

#26125 [ICDS Dashboard]dix discrepancy in wasting: Exclude age_tranche=nulll
  custom/icds_reports/reports/maternal_child.py
  custom/icds_reports/reports/prevalence_of_severe.py
  custom/icds_reports/tests/agg_tests/reports/test_prevalence_of_severe.py
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#26140 ICDS Dashboard: Port more map/chart reports to mobile
  custom/icds_reports/static/icds_reports/js/spec/awc-daily-status.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/awcs-covered.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/children-initiated.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/early_initiation_breastfeeding.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/exlusive-breastfeeding.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/immunization_coverage.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/institutional-deliveries.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/newborn_with_low_weight.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/prevalence-of-severe-report.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/prevalence-of-stunting-report.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/utils.js
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/angular-services/template-provider.service.js
  custom/icds_reports/static/js/directives/awc-daily-status/awc-daily-status.directive.js
  custom/icds_reports/static/js/directives/awcs-covered/awcs-covered.directive.js
  custom/icds_reports/static/js/directives/children-initiated/children-initiated.directive.js
  custom/icds_reports/static/js/directives/early_initiation_breastfeeding/early_initiation_breastfeeding.directive.js
  custom/icds_reports/static/js/directives/exclusive-breastfeeding/exlusive-breastfeeding.directive.js
  custom/icds_reports/static/js/directives/immunization_coverage/immunization_coverage.directive.js
  custom/icds_reports/static/js/directives/institutional-deliveries/institutional-deliveries.directive.js
  custom/icds_reports/static/js/directives/newborn_with_low_weight/newborn_with_low_weight.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-severe-report/prevalence-of-severe-report.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-stunting-report/prevalence-of-stunting-report.directive.js
  custom/icds_reports/static/js/directives/underweight-children-report/underweight-children-report.directive.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
  custom/icds_reports/templates/icds_reports/partials/shared_component_directives.html
  custom/icds_reports/templates/icds_reports/partials/shared_report_directives.html
  custom/icds_reports/templates/icds_reports/partials/shared_report_services.html
  custom/icds_reports/templates/icds_reports/partials/shared_utility_services.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
Labels: product/custom

#26130 ICDS Dashboard: Initial porting of the drilldown functionality to mobile
  custom/icds_reports/static/icds_reports/js/spec/awc-daily-status.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/awcs-covered.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/children-initiated.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/early_initiation_breastfeeding.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/exlusive-breastfeeding.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/immunization_coverage.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/institutional-deliveries.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/newborn_with_low_weight.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/prevalence-of-severe-report.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/prevalence-of-stunting-report.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/underweight-children-report.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/utils.js
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/angular-services/navigation.service.js
  custom/icds_reports/static/js/angular-services/template-provider.service.js
  custom/icds_reports/static/js/directives/adhaar-beneficiary/adhaar-beneficiary.directive.js
  custom/icds_reports/static/js/directives/adolescent-girls/adolescent-girls.directive.js
  custom/icds_reports/static/js/directives/adult-weight-scale/adult-weight-scale.directive.js
  custom/icds_reports/static/js/directives/awc-daily-status/awc-daily-status.directive.js
  custom/icds_reports/static/js/directives/awcs-covered/awcs-covered.directive.js
  custom/icds_reports/static/js/directives/children-initiated/children-initiated.directive.js
  custom/icds_reports/static/js/directives/clean-water/clean-water.directive.js
  custom/icds_reports/static/js/directives/early_initiation_breastfeeding/early_initiation_breastfeeding.directive.js
  custom/icds_reports/static/js/directives/enrolled-children/enrolled-children.directive.js
  custom/icds_reports/static/js/directives/enrolled-women/enrolled-women.directive.js
  custom/icds_reports/static/js/directives/exclusive-breastfeeding/exlusive-breastfeeding.directive.js
  custom/icds_reports/static/js/directives/functional-toilet/functional-toilet.directive.js
  custom/icds_reports/static/js/directives/immunization_coverage/immunization_coverage.directive.js
  custom/icds_reports/static/js/directives/infantometer/infantometer.directive.js
  custom/icds_reports/static/js/directives/infants-weight-scale/infants-weight-scale.directive.js
  custom/icds_reports/static/js/directives/institutional-deliveries/institutional-deliveries.directive.js
  custom/icds_reports/static/js/directives/kpi/kpi.directive.js
  custom/icds_reports/static/js/directives/lactating-enrolled-women/lactating-enrolled-women.directive.js
  custom/icds_reports/static/js/directives/medicine-kit/medicine-kit.directive.js
  custom/icds_reports/static/js/directives/navigation/navigation.directive.js
  custom/icds_reports/static/js/directives/newborn_with_low_weight/newborn_with_low_weight.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-severe-report/prevalence-of-severe-report.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-stunting-report/prevalence-of-stunting-report.directive.js
  custom/icds_reports/static/js/directives/program-summary/program-summary.directive.js
  custom/icds_reports/static/js/directives/registered-household/registered-household.directive.js
  custom/icds_reports/static/js/directives/stadiometer/stadiometer.directive.js
  custom/icds_reports/static/js/directives/underweight-children-report/underweight-children-report.directive.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/kpi.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/program-summary.directive.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
  custom/icds_reports/templates/icds_reports/partials/shared_component_directives.html
  custom/icds_reports/templates/icds_reports/partials/shared_report_directives.html
  custom/icds_reports/templates/icds_reports/partials/shared_report_services.html
  custom/icds_reports/templates/icds_reports/partials/shared_utility_services.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
Labels: product/custom

#26133 Move a test file into its test/ directory
  corehq/project_limits/tests/test_get_n_users_for_rate_limiting.py
Labels: product/invisible

#26141 Removed dead code
  corehq/apps/hqwebapp/templatetags/mainreport_tags.py
Labels: product/invisible

#26039 Sk/shard replication delay
  .github/CODEOWNERS
  corehq/sql_db/__init__.py
  corehq/sql_db/app_config.py
  corehq/sql_db/config.py
  corehq/sql_db/management/commands/configure_pl_proxy_cluster.py
  corehq/sql_db/management/commands/migrate_multi.py
  corehq/sql_db/migrations.py
  corehq/sql_db/routers.py
  corehq/sql_db/tests/test_connections.py
  corehq/sql_db/tests/test_model_partitioning.py
  corehq/sql_db/tests/test_partition_config.py
  corehq/sql_db/tests/test_routers.py
  corehq/sql_db/util.py
  corehq/sql_proxy_accessors/migrations/0001_initial.py
  corehq/sql_proxy_standby_accessors/__init__.py
  corehq/sql_proxy_standby_accessors/migrations/0001_initial.py
  corehq/sql_proxy_standby_accessors/migrations/__init__.py
  corehq/sql_proxy_standby_accessors/models.py
  corehq/sql_proxy_standby_accessors/sql_templates/_template.sql
  corehq/sql_proxy_standby_accessors/sql_templates/get_replication_delay.sql
  docs/databases.rst
  settings.py
Labels: product/invisible

#26065 Create hash index on doc_id for distributed tables
  corehq/apps/userreports/sql/adapter.py
  custom/icds_reports/ucr/data_sources/daily_feeding_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/daily_feeding_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/dashboard_growth_monitoring.json
  custom/icds_reports/ucr/data_sources/dashboard/thr_forms.json
  custom/icds_reports/ucr/data_sources/primary_private_school_form_ucr.json
  custom/icds_reports/ucr/data_sources/thr_forms_v2.json
  custom/icds_reports/ucr/data_sources/usage_forms.json
Labels: product/invisible

#26139 Rate limit only at high load
  corehq/apps/domain/templates/domain/admin/partials/project_limits_table.html
  corehq/apps/domain/templates/domain/admin/project_limits.html
  corehq/apps/domain/views/internal.py
  corehq/apps/hqadmin/templates/hqadmin/global_thresholds.html
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views/system.py
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/project_limits/admin.py
  corehq/project_limits/migrations/0001_initial.py
  corehq/project_limits/migrations/__init__.py
  corehq/project_limits/models.py
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/tests/test_dynamic_rate_definition.py
  corehq/tabs/tabclasses.py
  settings.py
Labels: product/feature-flag

#26082 Create DATA_FORWARDING privilege
  corehq/apps/accounting/migrations/0045_grandfather_data_forwarding_privs.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/reports/dispatcher.py
  corehq/motech/repeaters/signals.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/repeaters.py
  corehq/privileges.py
  corehq/tabs/tabclasses.py
Labels: product/prod-india-all-users

#26152 Fix edge case in app stauts
  corehq/apps/users/models.py
  corehq/apps/users/tasks.py
  corehq/ex-submodules/pillowtop/processors/form.py
  corehq/pillows/synclog.py
Labels: product/custom

#26153 Retry `UnfinishedArchiveStub`s only up to 3 times
  corehq/ex-submodules/couchforms/migrations/0006_unfinishedarchivestub_attempts.py
  corehq/ex-submodules/couchforms/models.py
  corehq/form_processor/tasks.py
Labels: product/invisible

#26148 UCR index cleanup
  corehq/apps/userreports/rebuild.py
Labels: product/invisible

#25803 Allow manually overriding suite resource IDs
  corehq/apps/app_manager/exceptions.py
  corehq/apps/app_manager/management/commands/add_resource_overrides.py
  corehq/apps/app_manager/migrations/0009_resourceoverride.py
  corehq/apps/app_manager/suite_xml/generator.py
  corehq/apps/app_manager/suite_xml/post_process/resources.py
  corehq/apps/app_manager/tests/test_advanced_suite.py
  corehq/apps/app_manager/tests/test_case_detail_distance.py
  corehq/apps/app_manager/tests/test_case_list_form.py
  corehq/apps/app_manager/tests/test_case_list_lookup.py
  corehq/apps/app_manager/tests/test_child_module.py
  corehq/apps/app_manager/tests/test_days_ago_migration.py
  corehq/apps/app_manager/tests/test_form_workflow.py
  corehq/apps/app_manager/tests/test_grid_menus.py
  corehq/apps/app_manager/tests/test_media_suite.py
  corehq/apps/app_manager/tests/test_release_notes_form.py
  corehq/apps/app_manager/tests/test_schedule.py
  corehq/apps/app_manager/tests/test_shadow_forms.py
  corehq/apps/app_manager/tests/test_shadow_modules.py
  corehq/apps/app_manager/tests/test_suite.py
  corehq/apps/app_manager/tests/test_suite_form_filter_errors.py
  corehq/apps/app_manager/tests/test_suite_formats.py
  corehq/apps/app_manager/tests/test_suite_name_enums.py
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/tests/test_suite_resource_overrides.py
  corehq/apps/app_manager/tests/test_suite_shadow_module.py
  corehq/apps/app_manager/tests/test_suite_training_module.py
  corehq/apps/app_manager/tests/util.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/linked_domain/applications.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/linked_domain/urls.py
  corehq/apps/linked_domain/views.py
Labels: QA Passed, product/invisible

#26147 ICDS Dashboard: basic mobile map support
  custom/icds_reports/static/icds_reports/js/spec/indie-map.directive.spec.js
  custom/icds_reports/static/icds_reports/mobile/css/less.min.js
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
  custom/icds_reports/templates/icds_reports/partials/shared_report_directives.html
Labels: product/custom

#26157 Updated add_resource_overrides to skip failing apps
  corehq/apps/app_manager/management/commands/add_resource_overrides.py
Labels: product/invisible

#26158 ICDS Dashboard: move include tag out of compress block
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
Labels: product/custom

#26159 ICDS Dashboard: default initial filter to location and not month
  custom/icds_reports/static/js/directives/mobile-filters/mobile-filters.directive.js
Labels: product/custom

#26161 Removed add_resource_overrides call from migration
  corehq/apps/app_manager/migrations/0009_resourceoverride.py
Labels: product/invisible

#26164 split up compression similar to how it is on web
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
Labels: product/custom

#26165 update db docs with more detail
  docs/databases.rst
  docs/images/django_db_sharded.png
  docs/images/django_db_sharded_standbys.png
Labels: product/invisible

#26036 [ICDS Dashboard] aggregate dashboard activity report
  custom/icds_reports/const.py
  custom/icds_reports/migrations/0152_dashboarduseractivityreport.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/test_aggregation_script.py
  custom/icds_reports/tests/agg_tests/test_dashboard_activity_report.py
  custom/icds_reports/utils/aggregation_helpers/distributed/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_dashboard_activity.py
Labels: product/custom

#26131 [ICDS Dashboard] generation of dashboard usage report
  custom/icds_reports/sqldata/exports/dashboard_usage.py
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#26154 Fix incorrect unknown user_type values in ES forms
  corehq/pillows/tasks.py
  corehq/pillows/utils.py
Labels: product/invisible

#26167 [Exports] do a feature flag check for optimization outside of large loops
  corehq/apps/export/models/new.py
Labels: product/all-users-all-environments, product/feature-flag

#26149 Added couch model to sql model docs
  docs/couch_to_sql_models.rst
  docs/migrations.rst
Labels: product/invisible

#26162 Added restrictions on all django tags except static to TestDjangoComp…
  corehq/apps/hqwebapp/tests/test_compress_command.py
  corehq/apps/reports/templates/reports/standard/base_template.html
Labels: product/invisible

#26168 Add "corehq.pillows" to INSTALLED_APPS to load its tasks
  settings.py
Labels: product/invisible

#26163 Bug fixes, and improved error reporting
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/tests/test_repeaters.py
Labels: product/invisible

#26170 Rewrite unfinished_archive to update attempts on existing stubs
  corehq/ex-submodules/couchforms/migrations/0007_auto_20191210_2206.py
  corehq/ex-submodules/couchforms/models.py
  corehq/form_processor/submission_process_tracker.py
  corehq/form_processor/tasks.py
Labels: product/invisible

#26174 [ICDS Dashboard] fix minor bugs activity report
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_dashboard_activity.py
Labels: product/custom

#26156 short circuit for duplicate forms on ICDS
  corehq/form_processor/parsers/form.py
Labels: product/invisible

#26143 Use citus standby for mobile UCR read queries
  corehq/apps/app_manager/fixtures/mobile_ucr.py
  corehq/sql_db/connections.py
  corehq/sql_db/tests/test_connections.py
Labels: product/invisible

#26160 ICDS Dashboard: port basic version of block view to mobile
  custom/icds_reports/static/icds_reports/js/spec/adhaar-beneficiary.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/adolescent-girls.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/adult-weight-scale.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/clean-water.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/enrolled-children.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/enrolled-women.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/functional-toilet.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/infantometer.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/infants-weight-scale.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/lactating-enrolled-women.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/map-or-sector-view.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/medicine-kit.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/registered-household.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/stadiometer.directive.spec.js
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
Labels: product/custom

#26182 ICDS Dashboard: Basic port of AWC reports to mobile
  custom/icds_reports/static/icds_reports/js/spec/awc-reports.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/underweight-children-report.directive.spec.js
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/kpi.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/partials/mobile-heading.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/program-summary.directive.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
  custom/icds_reports/templates/icds_reports/partials/shared_report_directives.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
Labels: product/custom

#26169 Added docs on selecting a couch model to migrate [ci skip]
  docs/couch_to_sql_models.rst
Labels: product/invisible

#26179 Improvements to add_resource_overrides
  corehq/apps/app_manager/management/commands/add_resource_overrides.py
  corehq/apps/app_manager/suite_xml/post_process/resources.py
  corehq/apps/linked_domain/applications.py
Labels: product/invisible

#26151 [Community / Trial Revamp] Update subscription text again
  corehq/apps/accounting/static/accounting/js/pricing_table.js
  corehq/apps/domain/templates/domain/select_plan.html
  corehq/apps/domain/views/accounting.py
  corehq/apps/hqwebapp/static/accounting/less/pricing-main.less
Labels: product/prod-india-all-users

#26150 [Community / Trial Revamp] Make sure Paused Plans can actually look at their invoices
  corehq/apps/domain/views/accounting.py
Labels: product/prod-india-all-users

#26184 [ICDS Dashboard]Rn change text dashboard activity report
  custom/icds_reports/sqldata/exports/dashboard_usage.py
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/tasks.py
Labels: product/custom

#26124 Ce/attendance state
  custom/icds_reports/migrations/0135_index_gm_forms_month.py
  custom/icds_reports/migrations/0153_daily_attendance_state.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tests/agg_tests/outputs/daily_attendance_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/daily_attendance_2017-05-01_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/daily_attendance.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/daily-attendance.distributed.txt
  custom/icds_reports/utils/migrations.py
Labels: product/invisible

#26185 add logging around gevent and flush stdout
  custom/icds_reports/management/commands/run_aggregation_query.py
Labels: product/invisible

#26025 Migrate GlobalAppConfig from couch to sql (1 of 3)
  corehq/apps/app_manager/management/commands/populate_sql_global_app_config.py
  corehq/apps/app_manager/migrations/0009_add_sqlglobalappconfig.py
  corehq/apps/app_manager/models.py
Labels: product/invisible

#26171 Track fix_user_type progress through better metrics
  corehq/pillows/tasks.py
Labels: product/invisible

#26181 [IntraHealth] Fix calculations of 'SYNTHESE' row
  custom/intrahealth/sqldata.py
Labels: product/custom

#26187 Fix migration conflict
  corehq/apps/app_manager/migrations/0010_merge_20191211_1921.py
Labels: product/invisible

#26188 Optimize send_unknown_user type stats
  corehq/pillows/tasks.py
Labels: product/invisible

#26190 Fix filter logic in fix_user_types
  corehq/pillows/tasks.py
Labels: product/invisible

#26178 upgrade sentry
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#26177 controlled rollout / testing of using standby DBs in livequery restore
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
  corehq/toggles.py
Labels: product/invisible

#26172 Import observation metadata
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/openmrs_config.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/tests/test_atom_feed.py
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/openmrs/workflow_tasks.py
Labels: product/feature-flag

#26194 pass options only to Citus DB
  corehq/sql_db/connections.py
Labels: product/invisible

#25998 Remove code that updates form unique ids
  corehq/apps/app_manager/migrations/0010_run_add_resource_overrides.py
  corehq/apps/app_manager/migrations/0011_merge_20191212_0936.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/util.py
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
Labels: QA Passed, product/invisible

#26173 use partitioned temp chm
  custom/icds_reports/migrations/0154_child_health_state.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tests/agg_tests/outputs/child_health_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/child_health_monthly_2017-05-01_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
Labels: product/invisible

#26191 add state to daily feeding join
  custom/icds_reports/utils/aggregation_helpers/distributed/daily_feeding_forms_child_health.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/daily-feeding-forms-child-health.distributed.txt
Labels: product/invisible

#26192 Removed phone number views
  corehq/apps/sms/management/commands/delete_messaging_couch_phone_numbers.py
  corehq/apps/sms/mixin.py
  corehq/couchapps/phone_numbers/views/verified_number_by_domain/map.js
  corehq/couchapps/phone_numbers/views/verified_number_by_domain/reduce.js
  corehq/couchapps/phone_numbers/views/verified_number_by_number/map.js
  corehq/couchapps/phone_numbers/views/verified_number_by_owner_id/map.js
  corehq/couchapps/phone_numbers/views/verified_number_by_suffix/map.js
Labels: product/invisible

#26200 Make auto-escalation workflow reuse delegate case on re-escalation
  corehq/apps/hqcase/utils.py
  custom/icds/rules/custom_actions.py
  custom/icds/tests/test_custom_rules.py
Labels: product/custom

#26195 ICDS Dashboard: mobile nav tweaks
  corehq/apps/hqwebapp/views.py
  custom/icds_reports/mobile_views.py
  custom/icds_reports/templates/icds_reports/icds_app/mobile/navigation.directive.html
  custom/icds_reports/urls.py
  custom/icds_reports/views.py
Labels: product/custom

#26132 [ICDS Dashbaord] Spelling corrections in infantomter and stadiometer
  custom/icds_reports/static/icds_reports/js/spec/stadiometer.directive.spec.js
  custom/icds_reports/static/js/directives/kpi/kpi.directive.js
  custom/icds_reports/static/js/directives/stadiometer/stadiometer.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/kpi.directive.html
Labels: product/custom

#26207 ICDS Dashboard: put maps behind a flag on mobile
  corehq/toggles.py
  custom/icds_reports/mobile_views.py
  custom/icds_reports/static/icds_reports/js/spec/utils.js
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-or-sector-view.directive.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
  custom/icds_reports/templates/icds_reports/partials/dashboard_initial_page_data.html
  custom/icds_reports/views.py
Labels: product/custom

#26206 ICDS Dashboard: Add loading indicator to mobile pages
  custom/icds_reports/static/icds_reports/mobile/css/app.less
  custom/icds_reports/static/icds_reports/mobile/images/loader.gif
  custom/icds_reports/templates/icds_reports/icds_app/mobile/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/busy.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/program-summary.directive.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
Labels: product/custom

#26210 ICDS Dashboard: Use closer to standard HQ practices around less files
  custom/icds_reports/static/icds_reports/mobile/css/app.less
  custom/icds_reports/static/icds_reports/mobile/css/filters.less
  custom/icds_reports/templates/icds_reports/base_minimal.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
  custom/icds_reports/templates/icds_reports/mobile_login.html
Labels: product/custom

#26142 Fix MPR miscalcualtion for severe underweight
  custom/icds_reports/mpr_sqldata.py
Labels: product/custom

#26189 Handle voided OpenMRS patients.
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/tests/data/voided_patient.json
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/openmrs/tests/utils.py
Labels: product/feature-flag

#26203 Pillow updates
  corehq/ex-submodules/pillowtop/management/commands/merge_pillow_checkpoints.py
  corehq/ex-submodules/pillowtop/management/commands/split_pillow_checkpoints.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  corehq/ex-submodules/pillowtop/processors/elastic.py
Labels: product/invisible

#25646 Regularly prune intermediate dashboard tables
  custom/icds_reports/utils/aggregation_helpers/distributed/base.py
  custom/icds_reports/utils/aggregation_helpers/distributed/birth_preparedness_forms.py
  custom/icds_reports/utils/aggregation_helpers/distributed/complementary_forms.py
  custom/icds_reports/utils/aggregation_helpers/distributed/complementary_forms_ccs_record.py
  custom/icds_reports/utils/aggregation_helpers/distributed/delivery_forms.py
  custom/icds_reports/utils/aggregation_helpers/distributed/growth_monitoring_forms.py
  custom/icds_reports/utils/aggregation_helpers/distributed/postnatal_care_forms_ccs_record.py
  custom/icds_reports/utils/aggregation_helpers/distributed/postnatal_care_forms_child_health.py
  custom/icds_reports/utils/aggregation_helpers/distributed/thr_form_v2.py
  custom/icds_reports/utils/aggregation_helpers/distributed/thr_forms_ccs_record.py
  custom/icds_reports/utils/aggregation_helpers/distributed/thr_forms_child_health.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/birth-preparedness-forms.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/complementary-forms-ccs-record.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/complementary-forms.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/growth-monitoring-forms.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/postnatal-care-forms-ccs-record.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/postnatal-care-forms-child-health.distributed.txt
Labels: product/custom

#26204 make partition drop and creation sequential
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
Labels: product/invisible

#26205 distribute agg child health calculations
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/distributed/base.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-child-health.distributed.txt
Labels: product/invisible

#26196 Deduplicate code into get_case_block_kwargs_from_concepts() function
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/tests/test_atom_feed.py
Labels: product/invisible

#26202 Throttle and measure case imports
  corehq/apps/case_importer/do_import.py
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/form_processor/submission_post.py
  corehq/project_limits/rate_limiter.py
Labels: product/invisible

#26217 Rate limit two factor phone sms/call setup
  corehq/apps/hqwebapp/two_factor_gateways.py
Labels: product/invisible

#26218 Fix error in two_factor_setup_rate_limiter
  corehq/apps/hqwebapp/two_factor_gateways.py
Labels: product/invisible

#26220 Actually report usage to global_two_factor_setup_rate_limiter
  corehq/apps/hqwebapp/two_factor_gateways.py
Labels: product/invisible

#26221 Make case importer timing buckets cover a more relevent range
  corehq/apps/case_importer/do_import.py
Labels: product/invisible

#26219 revert partitioning of temp child table
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
Labels: product/invisible

#26197 [ICDS Dashboard] Activity report QA fixes
  custom/icds_reports/sqldata/exports/dashboard_usage.py
  custom/icds_reports/tests/agg_tests/test_dashboard_activity_report.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_dashboard_activity.py
Labels: product/custom

#26214 ICDS Dashboard: move arrows to the right place
  custom/icds_reports/templates/icds_reports/icds_app/mobile/kpi.directive.html
Labels: product/custom

#26212 upgrade less.js to match version used on servers
  bower.json
  corehq/apps/cloudcare/templates/formplayer-common/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/styleguide/templates/styleguide/base.html
  custom/icds_reports/static/icds_reports/mobile/css/app.less
  custom/icds_reports/static/icds_reports/mobile/css/less.min.js
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/templates/icds_reports/base_minimal.html
Labels: product/invisible

#26175 [ICDS Dashboard][fix]: Tabs remains consistent while drilling down from the P.S. to AWC report
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
Labels: product/custom

#26226 Check whether value is for export
  corehq/motech/openmrs/workflow_tasks.py
Labels: product/invisible

#26225 [ICDS Dashboard] Change title of usage report csv
  custom/icds_reports/sqldata/exports/dashboard_usage.py
Labels: product/custom

#26166 [ICDS Dashboard] Add UCR for Adolescent girl changes
  custom/icds_reports/ucr/data_sources/adolescent_girl_register_form_ucr.json
  custom/icds_reports/ucr/tests/data/adolescent_girl_oos_again.xml
  custom/icds_reports/ucr/tests/data/adolescent_girl_school_admit.xml
  custom/icds_reports/ucr/tests/data/adolescent_girls.xml
  custom/icds_reports/ucr/tests/test_adolescent_girl_ucr.py
  settings.py
Labels: product/custom

#26229 Tests
  corehq/motech/openmrs/tests/test_workflow_tasks.py
Labels: product/invisible

#26233 Ce/chm partition 2
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
Labels: product/invisible

#26231 [ICDS Dashboard] Removed feature flag for infantometer and stadiometer
  custom/icds_reports/static/js/directives/kpi/kpi.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/kpi.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/navigation.directive.html
Labels: product/custom

#26201 [Community / Trial Revamp] fix tests
  corehq/apps/accounting/tests/test_migrations.py
Labels: product/prod-india-all-users

#26211 [ICDS Dashboard] Qa activity report fixes
  custom/icds_reports/sqldata/exports/dashboard_usage.py
  custom/icds_reports/tasks.py
Labels: product/custom

#26232 [ICDS Dashboard] Removed ff for dashboard usage activity report
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#26227 ICDS Reports: Support jumping to AWC report from mobile filters
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/angular-services/navigation.service.js
  custom/icds_reports/static/js/directives/location-filter/location-filter.directive.js
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
  custom/icds_reports/static/js/directives/program-summary/program-summary.directive.js
Labels: product/custom

#26026 Migrate GlobalAppConfig from couch to sql (2 of 3)
  corehq/apps/app_manager/management/commands/populate_sql_global_app_config.py
  corehq/apps/app_manager/migrations/0010_sqlglobalappconfig.py
  corehq/apps/app_manager/migrations/0011_merge_20191212_0106.py
  corehq/apps/app_manager/models.py
Labels: product/invisible

#26216 use person ucr for migration and availing
  custom/icds_reports/tests/agg_tests/fixtures/ccs_cases.csv
  custom/icds_reports/tests/agg_tests/fixtures/person_cases.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc-st1-2017-05-01.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_daily_2017-05-28_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/ccs_record_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/ccs_record_monthly_2017-05-01_sorted.csv
  custom/icds_reports/tests/agg_tests/test_cas_data_export.py
  custom/icds_reports/utils/aggregation_helpers/distributed/ccs_record_monthly.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/ccs-record-monthly.distributed.txt
Labels: product/invisible

#26209 Revert "Revert "Make auto-escalation workflow reuse delegate case on re-escalation""
  corehq/apps/hqcase/utils.py
  corehq/toggles.py
  custom/icds/rules/custom_actions.py
  custom/icds/tests/test_custom_rules.py
Labels: product/custom

#26223 ICDS Dashboard: Add chart-based navigation to mobile
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
Labels: product/custom

#26237 Added merge migration
  corehq/apps/app_manager/migrations/0012_merge_20191217_0605.py
Labels: product/invisible

#26239 remove excess whitespace from fact sheets header
  custom/icds_reports/reports/fact_sheets.py
  custom/icds_reports/templates/icds_reports/icds_app/progress-report.directive.html
Labels: product/custom

#26235 Verified filter for icds ucr reconciliation status
  custom/icds_reports/admin.py
  custom/icds_reports/tasks.py
Labels: product/admin

#26234 Send out automated report for Credits on HQ each month to finance
  corehq/apps/accounting/automated_reports.py
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/templates/accounting/email/credits_on_hq.html
  corehq/apps/accounting/templates/accounting/email/credits_on_hq.txt
  settings.py
Labels: product/prod-india-all-users

#26236 Add table showing which is_superuser/is_staff users have two factor enabled
  corehq/apps/hqadmin/templates/hqadmin/superuser_management.html
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views/users.py
Labels: product/invisible

#26245 [Community / Trial Revamp] Pricing Plans Text Updates
  corehq/apps/accounting/user_text.py
  corehq/apps/domain/views/accounting.py
Labels: product/prod-india-all-users

#26246 [Community / Trial Revamp] Fix repeaters test
  corehq/apps/app_manager/tests/test_repeater.py
Labels: product/prod-india-all-users

#26244 Ce/dist loc update
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/distributed/base.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-child-health.distributed.txt
Labels: product/custom

#26241 convert remaining ICDS sms indicators to use dashboard data instead of ES
  custom/icds/messaging/indicators.py
  custom/icds/tests/test_ls_no_submissions.py
  custom/icds/tests/test_ls_vhnd_survey.py
Labels: product/invisible

#26249 [Community / Trial Revamp] q4 data forwarding quick fix
  corehq/motech/repeaters/signals.py
  corehq/motech/repeaters/tasks.py
Labels: product/prod-india-all-users

#25976 [ICDS Dashboard] Addition of fields in cas data export for pregnant and locatating women
  custom/icds_reports/migrations/0155_added_new_fields_css_record_monthly_and_delivery_forms.py
  custom/icds_reports/migrations/sql_templates/database_views/ccs_record_monthly_view.sql
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/models/views.py
  custom/icds_reports/tests/agg_tests/fixtures/ccs_cases.csv
  custom/icds_reports/tests/agg_tests/fixtures/delivery_form.csv
  custom/icds_reports/tests/agg_tests/fixtures/person_cases.csv
  custom/icds_reports/tests/agg_tests/outputs/ccs_record_monthly-st1-2017-05-01.csv
  custom/icds_reports/tests/agg_tests/outputs/ccs_record_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/ccs_record_monthly_2017-05-01_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/ccs_record_monthly.py
  custom/icds_reports/utils/aggregation_helpers/distributed/delivery_forms.py
  custom/icds_reports/utils/aggregation_helpers/distributed/mbt.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/ccs-record-monthly.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/css-mbt.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/delivery-forms.distributed.txt
  custom/icds_reports/utils/migrations.py
Labels: product/custom

#26238 ICDS Dashboard: Implement Demographics and AWC Reports on Mobile
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/directives/adhaar-beneficiary/adhaar-beneficiary.directive.js
  custom/icds_reports/static/js/directives/adolescent-girls/adolescent-girls.directive.js
  custom/icds_reports/static/js/directives/adult-weight-scale/adult-weight-scale.directive.js
  custom/icds_reports/static/js/directives/awc-daily-status/awc-daily-status.directive.js
  custom/icds_reports/static/js/directives/awcs-covered/awcs-covered.directive.js
  custom/icds_reports/static/js/directives/children-initiated/children-initiated.directive.js
  custom/icds_reports/static/js/directives/clean-water/clean-water.directive.js
  custom/icds_reports/static/js/directives/early_initiation_breastfeeding/early_initiation_breastfeeding.directive.js
  custom/icds_reports/static/js/directives/enrolled-children/enrolled-children.directive.js
  custom/icds_reports/static/js/directives/enrolled-women/enrolled-women.directive.js
  custom/icds_reports/static/js/directives/exclusive-breastfeeding/exlusive-breastfeeding.directive.js
  custom/icds_reports/static/js/directives/functional-toilet/functional-toilet.directive.js
  custom/icds_reports/static/js/directives/immunization_coverage/immunization_coverage.directive.js
  custom/icds_reports/static/js/directives/infantometer/infantometer.directive.js
  custom/icds_reports/static/js/directives/infants-weight-scale/infants-weight-scale.directive.js
  custom/icds_reports/static/js/directives/institutional-deliveries/institutional-deliveries.directive.js
  custom/icds_reports/static/js/directives/lactating-enrolled-women/lactating-enrolled-women.directive.js
  custom/icds_reports/static/js/directives/medicine-kit/medicine-kit.directive.js
  custom/icds_reports/static/js/directives/newborn_with_low_weight/newborn_with_low_weight.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-severe-report/prevalence-of-severe-report.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-stunting-report/prevalence-of-stunting-report.directive.js
  custom/icds_reports/static/js/directives/registered-household/registered-household.directive.js
  custom/icds_reports/static/js/directives/stadiometer/stadiometer.directive.js
  custom/icds_reports/static/js/directives/underweight-children-report/underweight-children-report.directive.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/navigation.directive.html
  custom/icds_reports/templates/icds_reports/partials/shared_report_directives.html
  custom/icds_reports/templates/icds_reports/partials/shared_report_services.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
Labels: product/custom
