Repository dimagi/commcare-hq, pull requests merged in 2019-09, with the labels that each got.

#25219 [ICDS Dashboard]Make functioning awcs same as reporting awc in ASR and MPR report
  custom/icds_reports/sqldata/base_operationalization.py
Labels: product/custom

#25236 [ICDS Dashboard]Correct syntax of Inactive aww report task
  custom/icds_reports/tasks.py
Labels: product/custom

#25223 update rebuildstaging with new deploy command
  scripts/rebuildstaging
Labels: product/invisible

#25086 Ledger simplification
  corehq/apps/es/aggregations.py
  corehq/apps/es/tests/test_aggregations.py
  corehq/apps/reports/analytics/dbaccessors.py
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/commtrack/data_sources.py
  corehq/apps/reports/commtrack/standard.py
  corehq/apps/reports/management/commands/project_stats_report.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/reports/tests/test_supply_accessors.py
  corehq/form_processor/backends/couch/dbaccessors.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/document_stores.py
  corehq/form_processor/interfaces/dbaccessors.py
  corehq/sql_accessors/migrations/0063_get_ledger_values_for_cases_2.py
  corehq/sql_accessors/sql_templates/get_ledger_values_for_cases_2.sql
  corehq/sql_proxy_accessors/migrations/0046_get_ledger_values_for_cases_2.py
  corehq/sql_proxy_accessors/sql_templates/get_ledger_values_for_cases_2.sql
  custom/icds/rules/immunization.py
Labels: product/invisible

#25222 Simple filter for MOTECH logs
  corehq/motech/templates/motech/logs.html
  corehq/motech/views.py
Labels: product/invisible

#25225 Replaced generic error with specific one when advanced module referen…
  corehq/apps/app_manager/helpers/validators.py
Labels: product/feature-flag

#25227 Removed logic to propagate web apps permissions to linked apps
  corehq/apps/linked_domain/tests/test_update_roles.py
  corehq/apps/linked_domain/updates.py
Labels: product/invisible

#25234 Removed some more six.iteritems
  corehq/apps/accounting/tests/generator.py
  corehq/apps/analytics/tasks.py
  corehq/apps/api/accounting.py
  corehq/apps/api/models.py
  corehq/apps/api/resources/v0_1.py
  corehq/apps/appstore/views.py
  corehq/apps/callcenter/fixturegenerators.py
  corehq/apps/case_search/models.py
  corehq/apps/cleanup/management/commands/fix_forms_and_apps_with_missing_xmlns.py
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/data_analytics/gir_generator.py
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/domain/management/commands/migrate_domain_countries.py
  corehq/apps/export/utils.py
  corehq/apps/hqmedia/view_helpers.py
  corehq/apps/hqmedia/views.py
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/locations/bulk_management.py
  corehq/apps/locations/models.py
  corehq/apps/locations/tests/test_bulk_management.py
  corehq/apps/locations/util.py
  corehq/apps/products/models.py
  corehq/apps/products/views.py
  corehq/apps/reports/commtrack/standard.py
  corehq/apps/reports/standard/maps.py
  corehq/apps/reports/standard/monitoring.py
  corehq/apps/reports/tasks.py
  corehq/apps/smsbillables/tests/test_gateway_fees.py
  corehq/apps/smsbillables/tests/test_usage_fees.py
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/tests/test_updating_app_from_trans_dict.py
  corehq/apps/translations/views.py
  corehq/apps/tzmigration/tests/test_timezonemigration.py
  corehq/apps/userreports/expressions/factory.py
  corehq/apps/userreports/indicators/__init__.py
  corehq/apps/userreports/pillow.py
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/tests/test_async_indicators.py
  corehq/apps/userreports/tests/test_report_filters.py
  corehq/apps/zapier/api/v0_5.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/smsbackends/grapevine/models.py
Labels: product/invisible

#25224 [ICDS Dashboard]Change default behaviour of "Child Beneficiary List" to include children till 6 years
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/sqldata/exports/beneficiary.py
  custom/icds_reports/tests/reports/test_awc_reports.py
Labels: product/custom

#25242 Couch to SQL: improve error handling and verify system actions
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/system_action.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/form_processor/submission_post.py
  corehq/form_processor/system_action.py
  corehq/form_processor/tests/test_system_action.py
Labels: product/invisible

#25240 create indexes on the correct table
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_ccs_record.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/monolith/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/monolith/agg_ccs_record.py
  custom/icds_reports/utils/aggregation_helpers/monolith/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/monolith/agg_ls_data.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-ccs-record.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-ccs-record.monolith.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-child-health.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-child-health.monolith.txt
Labels: product/custom

#25172 [ICDS Dashboard] cas data export, previous month data available from 7th fix
  custom/icds_reports/static/js/directives/cas-export/cas-export.directive.js
Labels: product/custom

#25141 Allow for cross domain copies
  custom/icds/management/commands/copy_icds_app.py
Labels: product/invisible

#25253 Pass `case_ids` to `_try_to_process_form()`
  corehq/apps/couch_sql_migration/asyncforms.py
Labels: product/invisible

#25218 Restrict to permitted apps only
  corehq/apps/domain/forms.py
  corehq/apps/domain/views/releases.py
  corehq/apps/users/permissions.py
Labels: product/feature-flag

#25231 Added more validation for parameters in CCUI bulk translations
  corehq/apps/app_manager/tests/test_bulk_ui_translation.py
  corehq/apps/app_manager/ui_translations/ui_translations.py
Labels: product/all-users-all-environments

#25247 Migrated Recent Couch Changes to requirejs
  corehq/apps/hqadmin/static/hqadmin/js/couch_changes.js
  corehq/apps/hqadmin/templates/hqadmin/couch_changes.html
Labels: product/invisible

#25252 Continue live migration
  corehq/apps/domain_migration_flags/api.py
  corehq/apps/domain_migration_flags/tests/test_domain_migration_progress.py
Labels: product/invisible

#25251 Mk/validate single sheet redone
  corehq/apps/translations/app_translations/utils.py
  corehq/apps/translations/const.py
  corehq/apps/translations/validator.py
Labels: product/feature-flag

#25256 Migrated filtered user download to requirejs
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/filtered_download.js
  corehq/apps/users/templates/users/filter_and_download.html
Labels: product/invisible

#25248 [ICDS Dashboard] fix for ICDS-789; increased bar chart initial height
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
Labels: product/custom

#25259 Conditionally set default topic for couch pillows
  corehq/apps/change_feed/pillow.py
Labels: product/invisible

#25260 Record diffs for forms that cannot be wrapped
  corehq/apps/couch_sql_migration/asyncforms.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
Labels: product/invisible

#25164 Fix bug with sorting stock states
  corehq/apps/reports/views.py
Labels: product/invisible

#25230 Remove support for UCR partitioning
  corehq/apps/userreports/models.py
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/tests/test_data_source_partitioning.py
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#25265 Warn user before deleting data rather than taunting them afterwards
  custom/_legacy/pact/static/pact/js/main.js
Labels: product/custom

#25263 Only run rebuilds on one process
  corehq/pillows/case.py
  corehq/pillows/user.py
  corehq/pillows/xform.py
Labels: product/invisible

#25266 Added DatespanMixin to ASHAReports to replace old NRHMDatespanMixin
  custom/up_nrhm/reports/asha_reports.py
Labels: product/custom

#25269 Revert Externalize javascript: up_nrhm reports
  corehq/apps/reports/templates/reports/standard/base_template.html
  custom/up_nrhm/filters.py
  custom/up_nrhm/reports/asha_functionality_checklist_report.py
  custom/up_nrhm/reports/asha_reports.py
  custom/up_nrhm/static/up_nrhm/js/main.js
  custom/up_nrhm/templates/up_nrhm/asha_report.html
  custom/up_nrhm/templates/up_nrhm/datespan.html
Labels: product/custom

#25238 Better ICDS Dashboard static file management
  custom/icds_reports/templates/icds_reports/dashboard.html
Labels: product/custom

#25270 Various fixes for issues found while migrating a real domain
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_diffs.py
Labels: product/invisible

#25257 Fix copy_icds_app success message
  custom/icds/management/commands/copy_icds_app.py
Labels: product/invisible

#25271 result is a list of dicts, not objects
  corehq/apps/reports/views.py
Labels: product/invisible

#25273 [ICDS Dashboard] fix for ICDS-861
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
Labels: product/custom

#25268 Hide CLE message for enterprise environments
  corehq/apps/reports/standard/cases/basic.py
Labels: product/feature-flag

#25267 Make form metadata optional for combined pillow
  corehq/pillows/xform.py
  settings.py
Labels: product/invisible

#25169 Use user's first domain to store HQ-wide reports
  corehq/apps/reports/tasks.py
Labels: product/invisible

#25280 Revert Fixed behavior of EOF nav to previous screen for forms with parent menus
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/data/form_workflow/advanced-app.xml
  corehq/apps/app_manager/tests/data/form_workflow/advanced_app.json
  corehq/apps/app_manager/tests/data/form_workflow/suite-workflow-previous.xml
  corehq/apps/app_manager/tests/data/suite/child-module-form-workflow-previous.xml
  corehq/apps/app_manager/tests/test_form_workflow.py
  corehq/util/test_utils.py
Labels: product/all-users-all-environments

#25283 Updated docs on version handling for static files
  docs/js-guide/static-files.md
Labels: product/invisible

#25282 Clean up queue exit handlers
  corehq/apps/couch_sql_migration/asyncforms.py
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/tests/test_asyncforms.py
Labels: product/invisible

#25249 [ICDS Dashboard] fix for ICDS-729; modal open twice in awc report on …
  custom/icds_reports/static/js/directives/location-filter/location-filter.directive.js
Labels: product/custom

#25279 Revert "Revert "Better ICDS Dashboard static file management""
  custom/icds_reports/templates/icds_reports/dashboard.html
Labels: product/custom

#25290 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: product/invisible

#25289 Add very basic static UCRs for QA
  custom/ccqa/ucr/data_sources/patients.json
  custom/ccqa/ucr/reports/patients.json
  settings.py
Labels: product/admin

#25293 Added note about form questions to hqmedia README
  corehq/apps/hqmedia/README.md
Labels: product/invisible

#25291 Added compress blocks
  corehq/apps/app_manager/templates/app_manager/partials/xpathValidator.html
  corehq/apps/cloudcare/templates/cloudcare/includes/formplayer-inline.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/apps/hqadmin/templates/hqadmin/faceted_report.html
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/reports/templates/reports/partials/filters_js.html
  corehq/apps/reports/templates/reports/partials/graphs/charts_js.html
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/apps/reports_core/templates/reports_core/base_template_new.html
  corehq/apps/userreports/templates/userreports/configurable_report.html
  corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
  corehq/apps/userreports/templates/userreports/userreports_base.html
  corehq/motech/dhis2/templates/dhis2/edit_config.html
  corehq/motech/openmrs/templates/openmrs/edit_config.html
Labels: product/invisible

#25278 undo superclass __init__ change
  custom/icds_reports/sqldata/exports/beneficiary.py
Labels: product/custom

#25285 Make case search and unknown user pillows configurable via settings
  corehq/pillows/case.py
  corehq/pillows/user.py
  corehq/pillows/xform.py
  settings.py
Labels: product/invisible

#25284 Removed caching from resource_static
  corehq/apps/hqwebapp/exceptions.py
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/management/commands/resource_static.py
Labels: product/invisible

#25276 switch UCRs to citus
  custom/icds_reports/ucr/data_sources/awc_locations.json
  custom/icds_reports/ucr/data_sources/awc_mgt_forms.json
  custom/icds_reports/ucr/data_sources/cbe_form.json
  custom/icds_reports/ucr/data_sources/ccs_record_cases.json
  custom/icds_reports/ucr/data_sources/child_delivery_forms.json
  custom/icds_reports/ucr/data_sources/child_health_cases.json
  custom/icds_reports/ucr/data_sources/daily_feeding_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/birth_preparedness_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/child_tasks.json
  custom/icds_reports/ucr/data_sources/dashboard/commcare_user_cases.json
  custom/icds_reports/ucr/data_sources/dashboard/complementary_feeding_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/daily_feeding_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/dashboard_growth_monitoring.json
  custom/icds_reports/ucr/data_sources/dashboard/delivery_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/postnatal_care_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/pregnant_tasks.json
  custom/icds_reports/ucr/data_sources/dashboard/thr_forms.json
  custom/icds_reports/ucr/data_sources/household_cases.json
  custom/icds_reports/ucr/data_sources/infrastructure_form.json
  custom/icds_reports/ucr/data_sources/infrastructure_form_v2.json
  custom/icds_reports/ucr/data_sources/ls_home_visit_forms_filled.json
  custom/icds_reports/ucr/data_sources/ls_vhnd_form.json
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
  custom/icds_reports/ucr/data_sources/thr_forms_v2.json
  custom/icds_reports/ucr/data_sources/usage_forms.json
  custom/icds_reports/ucr/data_sources/vhnd_form.json
  testsettings.py
Labels: product/invisible

#25127 Add check that custom case detail xml id matches
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/tests/test_suite.py
Labels: product/feature-flag

#25288 always expire cache
  corehq/apps/app_manager/decorators.py
Labels: product/invisible

#25144 [ICDS Dashboard] asana task: updated disclaimer messages in icds dashboard
  custom/icds_reports/static/js/directives/info-message/info-message.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/cas-export.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/info-message.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/progress-report.directive.html
Labels: product/custom

#25250 [ICDS Dashboard] fix for ICDS-675; AWW performance report made availa…
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#25302 Eliminate multi-process shared state db
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
Labels: product/invisible

#25237 remove deprecated method
  corehq/apps/api/tests/case_resources.py
  corehq/apps/case_importer/do_import.py
  corehq/apps/commtrack/helpers.py
  corehq/apps/commtrack/tests/test_xml.py
  corehq/apps/hqcase/tasks.py
  corehq/apps/hqcase/tests/test_explode_cases.py
  corehq/apps/users/tasks.py
  corehq/apps/users/tests/retire.py
  corehq/ex-submodules/casexml/apps/case/mock/case_block.py
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
  corehq/ex-submodules/couchforms/tests/test_edits.py
  corehq/form_processor/tests/test_ledgers.py
  corehq/form_processor/tests/test_reprocess_errors.py
  corehq/form_processor/utils/xform.py
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/tests/test_atom_feed.py
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/util/test_utils.py
Labels: product/invisible

#25221 upgrade sentry SDK
  DEV_SETUP.md
  corehq/apps/hqadmin/management/commands/record_deploy_success.py
  corehq/apps/hqwebapp/templates/500.html
  corehq/apps/hqwebapp/tests/test_views.py
  corehq/apps/hqwebapp/views.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/form_processor/backends/sql/update_strategy.py
  corehq/middleware.py
  corehq/util/sentry.py
  corehq/util/soft_assert/api.py
  corehq/util/soft_assert/core.py
  corehq/util/tests/test_sentry.py
  dev_settings.py
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
  settingshelper.py
Labels: product/invisible

#25306 add initial page data
  corehq/apps/users/templates/users/edit_commcare_user.html
Labels: product/invisible

#25307 [ICDS Dashboard] Asana task; added title to ICDS Dashboard
  custom/icds_reports/templates/icds_reports/dashboard.html
Labels: product/custom

#25298 Catch all errors/exceptions when creating DomainUserHistory objects
  corehq/apps/accounting/tasks.py
Labels: product/invisible

#25303 Fixed relevancy of child menus using display-only forms
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/sections/menus.py
  corehq/apps/app_manager/tests/test_child_module.py
Labels: product/all-users-all-environments

#25297 Tableau / BI Integration: don't include errorred or archived forms
  corehq/apps/api/resources/v0_5.py
Labels: product/feature-flag

#25296 use proper import and force citus
  custom/icds_reports/management/commands/create_aggregation_record.py
  custom/icds_reports/management/commands/run_aggregation_query.py
Labels: product/invisible

#25229 [ICDS Dashboard] update pregnant report to use same month logic as lactating
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/tests/reports/test_awc_reports.py
Labels: product/custom

#25295 more explicit handling of `excluded_states`
  custom/icds_reports/sqldata/exports/beneficiary.py
  custom/icds_reports/tests/__init__.py
  custom/icds_reports/tests/test_citus_comparison.py
  custom/icds_reports/utils/mixins.py
Labels: product/custom

#25275 add a management command to populate local icds test data
  custom/icds_reports/README.md
  custom/icds_reports/management/commands/populate_local_db_with_icds_dashboard_test_data.py
  custom/icds_reports/tests/__init__.py
Labels: product/custom

#25309 Allow user location to be changed during migration
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/system_action.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/domain/management/commands/hard_delete_forms_and_cases_in_domain.py
  corehq/form_processor/backends/couch/processor.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/interfaces/processor.py
  corehq/form_processor/submission_post.py
  corehq/form_processor/system_action.py
  corehq/form_processor/tests/test_form_dbaccessor.py
  corehq/form_processor/tests/test_system_action.py
Labels: product/invisible

#25287 Rename child beneficiary report and add disclaimer
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
Labels: product/custom

#25313 remove periodic aggregation
  custom/icds_reports/tasks.py
Labels: product/invisible

#25310 Remove eventlet from requirements and uninstall
  requirements-python3/prod-requirements.txt
  requirements-python3/uninstall-requirements.txt
  requirements/prod-requirements.txt
  requirements/uninstall-requirements.txt
  scripts/pip-post-compile.sh
Labels: product/invisible

#25294 Rn reformat nic indicator api
  custom/icds_reports/migrations/0132_update_nic_view.py
  custom/icds_reports/migrations/sql_templates/database_views/nic_indicators.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/tests/test_nic_indicators_api.py
  custom/icds_reports/utils/data_accessor.py
  custom/icds_reports/views.py
Labels: product/custom

#25281 Report user counts every minute (with caching)
  corehq/apps/domain/calculations.py
  corehq/apps/reports/tasks.py
Labels: product/invisible

#25318 move join out of the loop
  custom/icds_reports/tasks.py
Labels: product/custom

#25286 Allow OpenMRS Importers to run daily
  corehq/motech/openmrs/const.py
  corehq/motech/openmrs/static/openmrs/js/openmrs_importers.js
  corehq/motech/openmrs/tasks.py
Labels: product/feature-flag

#25319 [ICDS Dashboard] tabular report ui hot fix
  custom/icds_reports/static/js/directives/info-message/info-message.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
Labels: product/custom

#25311 don't log success as errors
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#25314 Remove line-profiler and fix readthedocs
  .readthedocs.yml
  corehq/ex-submodules/dimagi/utils/decorators/profile.py
  docs/profiling.rst
  requirements-python3/dev-requirements.txt
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
Labels: product/invisible

#25320 [ICDS Dashboard]Testing API for AP request webservice
  corehq/toggles.py
  custom/icds_reports/urls.py
  custom/icds_reports/views.py
Labels: product/custom

#25330 Drop `# coding=utf-8`
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/tests/test_notifications.py
  corehq/apps/app_manager/tests/test_xform_parsing.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/change_feed/tests/test_pillow.py
  corehq/apps/commtrack/tests/test_utils.py
  corehq/apps/receiverwrapper/util.py
  corehq/apps/reports/sqlreport.py
  corehq/apps/reports/tests/sql_reports.py
  corehq/apps/translations/app_translations/utils.py
  corehq/blobs/tests/test_fsdb.py
  corehq/blobs/tests/test_migrate.py
  corehq/blobs/tests/test_migrate_metadata.py
  corehq/ex-submodules/couchexport/tests/test_saved.py
  corehq/ex-submodules/couchforms/openrosa_response.py
  corehq/ex-submodules/couchforms/tests/test_xml.py
  corehq/ex-submodules/pillowtop/tests/test_bulk.py
  corehq/form_processor/submission_post.py
  corehq/motech/openmrs/serializers.py
  corehq/motech/openmrs/tests/test_serializers.py
  corehq/util/tests/test_sentry.py
  custom/intrahealth/reports/__init__.py
  custom/intrahealth/reports/consommation_dashboard.py
  custom/intrahealth/reports/dashboard_1.py
  custom/intrahealth/reports/dashboard_2.py
  custom/intrahealth/reports/dashboard_3.py
  custom/intrahealth/reports/disponibilite_dashboard.py
  custom/intrahealth/reports/indicateurs_de_base_dasboard.py
  custom/intrahealth/reports/recap_passage_one_dashboard.py
  custom/intrahealth/reports/recap_passage_two_dashboard.py
  custom/intrahealth/reports/taux_de_peremption_dashboard.py
  custom/intrahealth/reports/taux_de_perte_dashboard.py
  custom/intrahealth/reports/taux_de_rupture_dashboard.py
  custom/intrahealth/reports/taux_de_satisfaction_dashboard.py
  custom/intrahealth/reports/utils.py
  custom/intrahealth/reports/valuer_des_stocks_pna_disponible_dashboard.py
  custom/intrahealth/tests/reports/test_dashboard_1.py
  custom/intrahealth/tests/reports/test_dashboard_2.py
  custom/intrahealth/tests/reports/test_dashboard_3.py
  custom/intrahealth/tests/reports/test_fiche_consommation_report_v2.py
  custom/intrahealth/tests/reports/test_recap_passage_report_v2.py
  custom/intrahealth/tests/reports/test_tableu_de_board_report_v2.py
  custom/intrahealth/tests/test_utils.py
  custom/intrahealth/utils.py
Labels: product/invisible

#25316 Paginate Group API in db
  corehq/apps/api/couch.py
  corehq/apps/api/resources/v0_4.py
  corehq/apps/domain/dbaccessors.py
Labels: product/all-users-all-environments

#25332 Set SENTRY_CONFIGURED=False when it isn't set up
  settings.py
Labels: product/invisible

#25331 Simplify doctests
  corehq/apps/app_manager/app_schemas/case_properties.py
  corehq/apps/locations/forms.py
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/serializers.py
  corehq/motech/utils.py
  corehq/motech/value_source.py
  corehq/util/itertools.py
Labels: product/invisible

#25329 Various fixes for Couch to SQL migration
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
  corehq/apps/reports/management/commands/project_stats_report.py
  corehq/apps/tzmigration/planning.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/sql_db/util.py
  corehq/util/log.py
Labels: product/invisible

#25334 Optimize form UCR deletes on Citus
  corehq/apps/userreports/sql/adapter.py
Labels: product/invisible

#25323 better fix for https://github.com/dimagi/commcare-hq/pull/25319
  custom/icds_reports/static/css/icds_dashboard.css
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
Labels: product/custom

#25315 On Demand Device Logs
  corehq/apps/ota/admin.py
  corehq/apps/ota/migrations/0009_devicelogrequest.py
  corehq/apps/ota/models.py
  corehq/apps/ota/tests/test_heartbeat.py
  corehq/apps/ota/views.py
  corehq/apps/receiverwrapper/views.py
  corehq/ex-submodules/phonelog/utils.py
  corehq/form_processor/submission_post.py
Labels: product/invisible

#25335 Fixed shadow forms erroring out while updating multimedia paths in bulk
  corehq/apps/hqmedia/models.py
  corehq/apps/hqmedia/view_helpers.py
Labels: product/feature-flag

#25333 Uninstall eventlet after pip install
  requirements-python3/uninstall-requirements.txt
  requirements/uninstall-requirements-after-install.txt
  requirements/uninstall-requirements.txt
Labels: product/invisible

#25304 Remove LedgerES dependency from exports
  corehq/apps/export/esaccessors.py
  corehq/apps/export/migrations/0007_auto_20190906_0149.py
  corehq/apps/export/migrations/0008_auto_20190906_2008.py
  corehq/apps/export/models/new.py
  corehq/apps/export/tests/test_esaccessors.py
  corehq/apps/export/tests/test_export_column.py
  corehq/pillows/ledger.py
Labels: product/invisible

#25232 Make new user registration and related views use requirejs
  corehq/apps/domain/templates/login_and_password/login.html
  corehq/apps/domain/templates/login_and_password/password_reset_confirm.html
  corehq/apps/domain/templates/login_and_password/password_reset_form.html
  corehq/apps/hqwebapp/static/hqwebapp/js/captcha.js
  corehq/apps/hqwebapp/static/hqwebapp/js/password_validators.ko.js
  corehq/apps/hqwebapp/static/registration/less/registration-main.less
  corehq/apps/registration/static/registration/js/login.js
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/registration/static/registration/js/password.js
  corehq/apps/registration/static/registration/js/password_reset_confirm.js
  corehq/apps/registration/static/registration/js/password_reset_form.js
  corehq/apps/registration/static/registration/js/register_new_user.js
  corehq/apps/registration/templates/registration/register_new_user.html
  corehq/apps/settings/static/settings/js/change_my_password.js
  corehq/apps/settings/templates/settings/change_my_password.html
  corehq/apps/users/static/users/js/accept_invite.js
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/templates/users/accept_invite.html
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/mobile_workers.html
  custom/icds/templates/icds/login.html
  custom/nic_compliance/static/nic_compliance/js/encoder.js
Labels: awaiting QA, product/all-users-all-environments

#25341 Update hqmedia README
  corehq/apps/hqmedia/README.md
Labels: product/invisible

#25324 ICDS - Non Role Mobile worker should not report an issue
  corehq/util/context_processors.py
Labels: product/invisible

#25337 Track submissions that would be rate limited
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/apps/receiverwrapper/views.py
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/tests/test_rate_limiter.py
Labels: product/invisible

#25338 Improve with_progress_bar update interval
  corehq/util/log.py
Labels: product/invisible

#25342 Fix a bit of jankiness in the builds menu page
  corehq/apps/builds/templates/builds/edit_menu.html
  corehq/apps/builds/views.py
Labels: product/admin

#25255 parse more variety of app-version info texts
  corehq/apps/receiverwrapper/util.py
Labels: product/invisible

#25346 [ci skip] update citus docs for dashboard development
  CITUSDB_SETUP.md
  custom/icds_reports/README.md
Labels: product/custom

#25312 [ICDS Dashboard] pull site code for dashboard
  custom/icds_reports/tests/test_aggregation_script.py
  custom/icds_reports/utils/aggregation_helpers/distributed/awc_location.py
  custom/icds_reports/utils/aggregation_helpers/monolith/awc_location.py
Labels: product/custom

#25356 [ICDS Dashboard] Rename beneficiary table to GM table
  custom/icds_reports/const.py
  custom/icds_reports/tasks.py
  custom/icds_reports/views.py
Labels: product/custom

#24820 Multi master linked apps migrations
  corehq/apps/app_manager/migrations/0006_multi_master_linked_apps.py
  corehq/apps/app_manager/migrations/0007_add_linked_app_fields_to_es.py
  corehq/dbaccessors/couchapps/all_docs.py
  corehq/pillows/mappings/app_mapping.json
Labels: product/invisible, reindex/migration

#25364 prepend Copy of to name when copying odata feed
  corehq/apps/export/views/utils.py
Labels: product/feature-flag

#25352 Fix py3 lambda tuple unpacking issue
  corehq/apps/reports/views.py
Labels: product/invisible

#25351 Make sure prefilters with empty prevalues such as last7 dates are not…
  corehq/apps/userreports/static/userreports/js/report_config.js
Labels: product/invisible

#25367 active mobile workers metric
  corehq/apps/reports/tasks.py
Labels: product/invisible

#25363 Cleanup and more predictable interrupt handling
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
Labels: product/invisible

#25372 Process fewer apps at a time in migration
  corehq/apps/app_manager/migrations/0006_multi_master_linked_apps.py
  corehq/util/couch.py
Labels: product/invisible

#25374 Followup for "Migrated Recent Couch Changes to requirejs"
  corehq/apps/hqadmin/static/hqadmin/js/hqadmin_base_report.js
  corehq/apps/hqadmin/templates/hqadmin/hqadmin_base_report.html
  corehq/apps/reports/static/reports/js/datepicker.js
  corehq/apps/reports/static/reports/js/tabular.js
Labels: product/invisible

#25365 Mk/fix multi sheet
  corehq/apps/translations/app_translations/upload_app.py
  corehq/apps/translations/app_translations/utils.py
  corehq/apps/translations/generators.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/apps/translations/validator.py
  corehq/apps/translations/views.py
Labels: product/feature-flag

#25340 [ICDS Dashboard]update immunization age calculation
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_4_sorted.csv
  custom/icds_reports/tests/outputs/agg_child_health_2017-05-01_5_sorted.csv
  custom/icds_reports/tests/outputs/child_health_monthly-st1-2017-05-01.csv
  custom/icds_reports/tests/outputs/child_health_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/outputs/child_health_monthly_2017-05-01_sorted.csv
  custom/icds_reports/tests/reports/test_immunization_coverage.py
  custom/icds_reports/tests/test_export_data.py
  custom/icds_reports/tests/test_fact_sheet_report.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
  custom/icds_reports/utils/aggregation_helpers/monolith/child_health_monthly.py
Labels: product/custom

#25245 Externalize javascript: m4change reports
  custom/m4change/fields.py
  custom/m4change/static/m4change/javascripts/main.js
  custom/m4change/templates/m4change/fields/daterange.html
  custom/m4change/templates/m4change/report.html
  custom/m4change/templates/m4change/selectTemplate.html
Labels: product/invisible

#25376 Address issues with saved report filters (1 of 2)
  corehq/apps/reports/filters/base.py
  corehq/apps/reports/migrations/0003_multiselect_report_filters_are_lists.py
  corehq/apps/reports/standard/monitoring.py
  corehq/apps/reports/static/reports/js/report_config_models.js
  corehq/apps/reports_core/filters.py
  corehq/apps/saved_reports/models.py
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/tests/test_report_filters.py
Labels: product/all-users-all-environments

#25375 fix knockout logic for data dict description fields
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
Labels: product/all-users-all-environments

#25369 sentry ignore pillowtop logs
  settingshelper.py
Labels: product/invisible

#25379 Institute soft rate limiting through brief delays
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/apps/receiverwrapper/views.py
  corehq/project_limits/rate_limiter.py
  corehq/util/datadog/gauges.py
  corehq/util/decorators.py
Labels: product/prod-india-all-users

#25381 Cz/rename legacy view
  custom/icds_reports/urls.py
  custom/icds_reports/views.py
Labels: product/invisible

#25392 fix issue with case config on data dict domains...hasPrivilege is not an observable
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
Labels: product/all-users-all-environments

#25378 Add tests for RateDefinition arithmetic
  corehq/project_limits/tests/test_rate_definition.py
Labels: product/invisible

#25385 Externalize JavaScript: mc reports
  custom/reports/mc/reports/sql.py
  custom/reports/mc/static/mc/js/main.js
  custom/reports/mc/templates/mc/base_template.html
  custom/reports/mc/templates/mc/reports/drillable_async.html
Labels: product/invisible

#25388 Removed unnecessary js from m4change base report
  custom/m4change/templates/m4change/report.html
Labels: product/custom

#25389 Added isort to stickler
  .stickler.yml
Labels: product/invisible

#25387 Python 3.7 applies PEP-479
  corehq/util/itertools.py
Labels: product/invisible

#25386 Import patients in their own task
  corehq/motech/openmrs/models.py
  corehq/motech/openmrs/tasks.py
  corehq/motech/openmrs/tests/test_importer.py
  corehq/motech/openmrs/views.py
Labels: product/feature-flag

#25336 Handle Unix timestamps better
  corehq/motech/openmrs/forms.py
  corehq/motech/openmrs/models.py
  corehq/motech/openmrs/serializers.py
  corehq/motech/openmrs/static/openmrs/js/openmrs_importers.js
  corehq/motech/openmrs/tasks.py
  corehq/motech/openmrs/tests/test_tasks.py
Labels: product/feature-flag

#25393 Use raw_username in device log requests
  corehq/apps/ota/models.py
Labels: product/invisible

#25391 create index on synclogstagingtable.user_id
  corehq/warehouse/migrations/0032_auto_20190917_1542.py
  corehq/warehouse/models/staging.py
Labels: product/invisible

#25395 Bump up limits for small projects
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/tests/test_rate_definition.py
Labels: product/invisible

#25394 Updated js docs on naming conventions
  docs/js-guide/libraries.md
Labels: product/invisible

#25403 Include all SMSs, both incoming and outgoing in enterprise report
  corehq/apps/accounting/enterprise.py
Labels: product/all-users-all-environments

#25327 Re-apply "Added compress blocks"
  corehq/apps/app_manager/templates/app_manager/partials/xpathValidator.html
  corehq/apps/cloudcare/templates/cloudcare/includes/formplayer-inline.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/apps/hqadmin/templates/hqadmin/faceted_report.html
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/reports/templates/reports/partials/filters_js.html
  corehq/apps/reports/templates/reports/partials/graphs/charts_js.html
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/apps/reports_core/templates/reports_core/base_template_new.html
  corehq/apps/userreports/templates/userreports/configurable_report.html
  corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
  corehq/apps/userreports/templates/userreports/userreports_base.html
  corehq/motech/dhis2/templates/dhis2/edit_config.html
  corehq/motech/openmrs/templates/openmrs/edit_config.html
Labels: Open for review: do not merge, product/invisible

#25397 [Intrahealth] Recap Passage 1 calculation changes
  custom/intrahealth/sqldata.py
Labels: product/custom

#25398 Limit memory used by case diff process and other improvements
  corehq/apps/couch_sql_migration/asyncforms.py
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/staterebuilder.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/tzmigration/planning.py
Labels: product/invisible

#25410 [ci skip] update license year
  LICENSE
Labels: product/invisible

#25399 update citus docs [ci skip]
  custom/icds_reports/README.md
Labels: product/invisible

#25402 cleanup warehouse form table indexes
  corehq/warehouse/migrations/0033_form_fact_user_id_index.py
  corehq/warehouse/models/staging.py
Labels: product/invisible

#25409 Refactor async form processing queue
  corehq/apps/couch_sql_migration/asyncforms.py
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/status.py
  corehq/apps/couch_sql_migration/tests/test_asyncforms.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
Labels: product/invisible

#25400 add section on the contents of our kafka feeds to the docs
  docs/change_feeds.rst
Labels: product/invisible

#25407 Updated mc reports to run js on ajaxComplete, not document ready
  custom/reports/mc/static/mc/js/main.js
Labels: product/custom

#25406 Fixed js error on admin report User List
  corehq/apps/hqadmin/templates/hqadmin/faceted_report.html
Labels: product/admin

#25243 Externalize javascript: Pact reports
  corehq/apps/reports/static/reports/js/tabular.js
  corehq/apps/reports_core/static/reports_core/js/base_template_new.js
  custom/_legacy/pact/reports/patient.py
  custom/_legacy/pact/static/pact/js/main.js
  custom/_legacy/pact/templates/pact/dots/dots_report.html
  custom/_legacy/pact/templates/pact/patient/base.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_base.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_careplan.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_edit.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_log.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_providers.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_schedule.html
Labels: product/invisible

#25325 agg cleanup misc
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/tasks.py
Labels: product/custom

#25411 Bubble up gevent errors to main thread
  custom/icds_reports/management/commands/run_aggregation_query.py
Labels: product/custom

#25408 Remove ghost roles from domain admins
  corehq/apps/users/migrations/0004_rm_role_id_from_admins.py
  corehq/apps/users/models.py
Labels: product/all-users-all-environments, reindex/migration

#25405 Add ES backend for Group API
  corehq/apps/api/query_adapters.py
  corehq/apps/api/resources/v0_1.py
  corehq/apps/api/resources/v0_4.py
  corehq/toggles.py
Labels: product/feature-flag

#25416 Revert "Externalize javascript: Pact reports"
  corehq/apps/reports/static/reports/js/tabular.js
  corehq/apps/reports_core/static/reports_core/js/base_template_new.js
  custom/_legacy/pact/reports/patient.py
  custom/_legacy/pact/static/pact/js/main.js
  custom/_legacy/pact/templates/pact/dots/dots_report.html
  custom/_legacy/pact/templates/pact/patient/base.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_base.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_careplan.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_edit.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_log.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_providers.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_schedule.html
Labels: product/custom

#25244 Externalize javascript: succeed reports
  custom/succeed/reports/all_patients.py
  custom/succeed/reports/patient_submissions.py
  custom/succeed/static/succeed/js/patient_list.js
  custom/succeed/static/succeed/js/patient_submissions.js
  custom/succeed/templates/patient_submissions.html
  custom/succeed/templates/succeed/patient_list_report.html
  custom/succeed/templates/succeed/patient_list_submissions.html
  custom/succeed/templates/succeed/report.html
  custom/succeed/templates/succeed/ucla_table.html
Labels: product/invisible

#25384 fix icds dashboard mobile user / role based access
  corehq/toggles.py
  custom/icds_reports/tests/test_views_first_days_of_month.py
  custom/icds_reports/views.py
Labels: product/custom

#25368 close consumer
  corehq/ex-submodules/pillowtop/utils.py
Labels: product/invisible

#25390 location dimension set hierarchy
  corehq/warehouse/transforms/sql/location_dim.sql
Labels: product/invisible

#25413 ucr filter tiny cleanup
  corehq/apps/userreports/reports/view.py
Labels: product/invisible

#25419 [ci skip] add note / link to airflow docs
  DEV_SETUP.md
Labels: product/invisible
