Repository dimagi/commcare-hq, pull requests merged in 2020-06, with the labels that each got.

#27671 use distinct from in default filter
  corehq/apps/userreports/reports/builder/forms.py
Labels: product/all-users-all-environments

#27673 use correct name for operator
  corehq/apps/userreports/reports/builder/forms.py
Labels: product/all-users-all-environments

#27643 updated dashboard domain to include icds-staging
  custom/icds_reports/const.py
Labels: product/custom

#27553 THR report new filter ui
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
  custom/icds_reports/views.py
Labels: product/custom

#27677 [ICDS Dashboard]: Fixes in the Dashboard_usage_report.py
  custom/icds_reports/management/commands/dashboard_usage_report.py
Labels: product/invisible

#27678 add ability to dynamically add data sources during pillow processing
  corehq/apps/userreports/_design/views/data_sources_by_last_modified/map.js
  corehq/apps/userreports/_design/views/data_sources_by_last_modified/reduce.js
  corehq/apps/userreports/data_source_providers.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/pillow.py
  corehq/apps/userreports/tests/test_data_source_providers.py
  corehq/apps/userreports/tests/test_pillow.py
Labels: product/all-users-all-environments

#27600 Error messages on UI when from or module Id is invalid
  corehq/apps/translations/validator.py
Labels: product/custom

#27661 Mark bounced emails in pending invitations list
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/web_users.html
Labels: product/invisible

#27681 Add middleware to get logged out domain and IP
  corehq/middleware.py
  corehq/toggles.py
  settings.py
Labels: product/invisible

#27639 Updated case data link in nav to better handle blank names
  corehq/apps/reports/standard/cases/basic.py
Labels: product/all-users-all-environments

#27680 Fixed problems with inactivity timeout
  corehq/apps/hqwebapp/static/hqwebapp/js/inactivity.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/iframe_login.html
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/views.py
Labels: product/all-users-all-environments

#27313 [ICDS Dashboard] Exclude test states from sdr view
  custom/icds_reports/migrations/sql_templates/database_views/service_delivery_report_view.sql
  custom/icds_reports/reports/service_delivery_report.py
Labels: product/custom

#27646 Changed case inclusion window
  custom/icds_reports/tasks.py
Labels: product/custom

#27682 Dump & reload case_importer models
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#27670 Added labels to feature flags in popup when copying app
  corehq/apps/app_manager/static/app_manager/js/app_view_application.js
  corehq/apps/app_manager/templates/app_manager/partials/toggle_diff_modal.html
  corehq/apps/domain/views/internal.py
Labels: product/admin

#27653 [ICDS Dashboard] Fix for num launched awcs 0 issue in sdd api
  custom/icds_reports/migrations/sql_templates/database_views/service_delivery_report_view.sql
  custom/icds_reports/reports/service_delivery_dashboard_data.py
  custom/icds_reports/tests/agg_tests/reports/test_service_delivery_data.py
  custom/icds_reports/tests/agg_tests/reports/test_service_delivery_details.py
Labels: product/custom

#27685 Add session_started and session_ended metrics for sms form sessions
  corehq/apps/smsforms/models.py
  corehq/messaging/scheduling/models/content.py
Labels: product/invisible

#27668 One phone number, multiple contacts
  corehq/apps/sms/api.py
  corehq/apps/sms/handlers/form_session.py
  corehq/apps/smsforms/management/commands/handle_survey_actions.py
  corehq/apps/smsforms/models.py
  corehq/apps/smsforms/tasks.py
  corehq/apps/smsforms/tests/test_session_synchronization.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/models/content.py
  corehq/toggles.py
Labels: product/invisible

#27675 Infobip backend improvements
  corehq/apps/sms/templates/sms/whatsapp_templates.html
  corehq/apps/sms/views.py
  corehq/messaging/smsbackends/infobip/forms.py
  corehq/messaging/smsbackends/infobip/models.py
  corehq/messaging/smsbackends/infobip/views.py
  corehq/messaging/smsbackends/turn/models.py
  corehq/tabs/tabclasses.py
Labels: product/invisible

#27684 Handle empty fixture values
  custom/abt/reports/fixture_utils.py
  custom/abt/reports/tests/test_fixture_utils.py
Labels: product/custom, product/invisible

#27674 update emails
  custom/icds/tasks/sms.py
Labels: product/custom

#27622 Add indian financial year date filter
  corehq/apps/app_manager/models.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/reports/daterange.py
  corehq/apps/reports/tests/test_daterange.py
  corehq/util/context_processors.py
  settings.py
Labels: product/custom, product/prod-india-all-users

#27627 Add ability to control which non-admin roles can assign a non-admin role
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/static/users/js/roles_and_permissions.js
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/apps/users/templates/users/roles_and_permissions.html
  corehq/apps/users/views/__init__.py
Labels: product/all-users-all-environments

#27686 Added notifications URL to URLs that bypass session
  corehq/middleware.py
Labels: product/invisible

#27662 Tests for ping_login
  corehq/apps/hqwebapp/session_details_endpoint/tests.py
  corehq/apps/hqwebapp/static/hqwebapp/js/inactivity.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/inactivity_spec.js
  corehq/apps/hqwebapp/templates/hqwebapp/spec/mocha.html
Labels: product/invisible

#27690 remove email
  custom/icds/tasks/sms.py
Labels: product/custom

#27691 Fix recently broken handle_survey_actions (ONE_PHONE_NUMBER_MULTIPLE_CONTACTS)
  corehq/apps/smsforms/management/commands/handle_survey_actions.py
Labels: product/invisible

#27638 [ICDS Report] THR report backend new
  custom/icds_reports/const.py
  custom/icds_reports/migrations/0193_adding_fields_to_sdd.py
  custom/icds_reports/migrations/0194_auto_20200528_1024.py
  custom/icds_reports/migrations/sql_templates/database_views/service_delivery_report_view.sql
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/models/views.py
  custom/icds_reports/reports/take_home_ration.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_service_delivery_report.py
Labels: product/custom

#27695 Report error message with details of bad formplayer response
  corehq/apps/formplayer_api/smsforms/api.py
Labels: product/invisible

#27683 Use ECO lookup tables instead of DCV
  custom/abt/reports/filters_2020.py
  custom/abt/reports/fixture_utils.py
Labels: product/custom, product/invisible

#27699 PR feedback on logout inactivity
  corehq/apps/hqwebapp/static/hqwebapp/js/inactivity.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/views.py
Labels: product/invisible

#27705 Revert "PR feedback on logout inactivity"
  corehq/apps/hqwebapp/static/hqwebapp/js/inactivity.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/views.py
Labels: product/invisible

#27688 Trumpia message status
  corehq/messaging/smsbackends/trumpia/models.py
  corehq/messaging/smsbackends/trumpia/tests/test_outgoing.py
Labels: product/invisible

#27707 Refactor Trumpia backend to use HTTP API (v2)
  corehq/messaging/smsbackends/trumpia/models.py
  corehq/messaging/smsbackends/trumpia/tests/test_outgoing.py
Labels: product/invisible

#27710 combine null and empty choices in UCR / report builder filters
  corehq/apps/reports/util.py
  corehq/apps/reports_core/filters.py
  corehq/apps/userreports/reports/filters/choice_providers.py
  corehq/apps/userreports/reports/filters/values.py
Labels: product/all-users-all-environments

#27704 Fixed runaway ping_login poll when inactivity setting is flipped
  corehq/apps/hqwebapp/static/hqwebapp/js/inactivity.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/inactivity_spec.js
Labels: product/invisible

#27706 Stop conditional alerts polling on bad data
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_list.js
Labels: product/invisible

#27702 INDDEX reports enhancements
  custom/inddex/const.py
  custom/inddex/filters.py
  custom/inddex/food.py
  custom/inddex/management/commands/populate_inddex_test_domain.py
  custom/inddex/reports/__init__.py
  custom/inddex/reports/r1_master_data.py
  custom/inddex/reports/r2a_gaps_summary.py
  custom/inddex/reports/r2b_gaps_detail.py
  custom/inddex/reports/r3_nutrient_intake.py
  custom/inddex/reports/r4_nutrient_stats.py
  custom/inddex/tests/data/1_master.csv
  custom/inddex/tests/data/2a_conv_factor_gaps_summary.csv
  custom/inddex/tests/data/2a_fct_gaps_summary.csv
  custom/inddex/tests/data/2b_gaps_by_item_details.csv
  custom/inddex/tests/data/2b_gaps_by_item_summary.csv
  custom/inddex/tests/data/3_aggr_daily_intake_by_rspndnt.csv
  custom/inddex/tests/data/4_nutr_intake_summary_stats.csv
  custom/inddex/tests/data/conv_factor_gaps_summary.csv
  custom/inddex/tests/data/fct_gaps_summary.csv
  custom/inddex/tests/data/gaps_by_item_details.csv
  custom/inddex/tests/data/gaps_by_item_summary.csv
  custom/inddex/tests/data/master.csv
  custom/inddex/tests/test_master_report.py
Labels: product/custom

#27713 Revert "Revert "PR feedback on logout inactivity""
  corehq/apps/hqwebapp/static/hqwebapp/js/inactivity.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/iframe_domain_login.html
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/views.py
Labels: product/invisible

#27692 Open up a few utility views for location-restricted users
  corehq/apps/cloudcare/views.py
  corehq/apps/export/views/download.py
  corehq/apps/reports_core/filters.py
  corehq/apps/userreports/reports/util.py
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/views.py
Labels: product/all-users-all-environments

#27714 Allow non-admins to access locations API
  corehq/apps/locations/resources/v0_5.py
Labels: product/all-users-all-environments

#27719 Moved template
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/ko_pagination.html
  corehq/apps/styleguide/templates/styleguide/base.html
Labels: product/invisible

#27716 add monitoring metrics for pending user confirmations
  corehq/apps/users/tasks.py
Labels: product/invisible

#27717 track when we hard bounce emails
  corehq/ex-submodules/dimagi/utils/django/email.py
Labels: product/invisible

#27718 Remove unused pact domain API
  corehq/apps/api/domainapi.py
  corehq/apps/api/urls.py
  custom/_legacy/pact/api.py
  custom/_legacy/pact/forms/patient_form.py
  custom/_legacy/pact/forms/weekly_schedule_form.py
  custom/_legacy/pact/tasks.py
Labels: product/invisible

#27711 fix editing of the new default filter types
  corehq/apps/userreports/reports/builder/const.py
  corehq/apps/userreports/reports/builder/filter_formats.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/tests/test_report_builder_filters.py
Labels: product/all-users-all-environments

#27703 Block data interfaces for icds-cas
  corehq/apps/data_interfaces/dispatcher.py
  corehq/apps/data_interfaces/views.py
  corehq/tabs/tabclasses.py
  custom/icds/const.py
  custom/icds/view_utils.py
Labels: product/custom

#27698 Linked Reports Enhancements
  corehq/apps/userreports/static/userreports/js/configure_report.js
  corehq/apps/userreports/static/userreports/js/edit_report_config.js
  corehq/apps/userreports/templates/userreports/edit_report_config.html
  corehq/apps/userreports/templates/userreports/partials/link_reports.html
  corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
  corehq/apps/userreports/views.py
Labels: product/feature-flag

#27724 Removed UCR polling while rebuild is in progress
  corehq/apps/userreports/static/userreports/js/build_in_progress_warning.js
  corehq/apps/userreports/templates/userreports/configurable_report.html
  corehq/apps/userreports/templates/userreports/partials/build_in_progress_warning.html
  corehq/apps/userreports/templates/userreports/preview_data.html
  corehq/apps/userreports/urls.py
  corehq/apps/userreports/views.py
Labels: product/all-users-all-environments

#27696 enforce rule to not allow reusing usernames from deleted users
  corehq/apps/users/dbaccessors/all_commcare_users.py
  corehq/apps/users/forms.py
  corehq/apps/users/views/mobile/users.py
Labels: product/all-users-all-environments

#27727 use format constants in a few more places
  corehq/apps/userreports/reports/builder/forms.py
Labels: product/invisible

#27730 Updated build_requirejs to fail deploy if r.js fails
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
Labels: product/invisible

#27732 Fix rebuildstaging
  scripts/rebuildstaging
  scripts/rebuildstaging.py
Labels: product/invisible

#27701 Revert "Revert "Add ability to control which non-admin roles can assign a non-admin role""
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/static/users/js/roles_and_permissions.js
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/apps/users/templates/users/roles_and_permissions.html
  corehq/apps/users/views/__init__.py
Labels: product/all-users-all-environments

#27733 return None to handle notify no cases
  custom/icds/location_reassignment/download.py
Labels: product/feature-flag

#27687 [ICDS Dashboard] Find the fact sheet data at same level for which it was queried
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#27641 [ICDS Dashboard] Added 21-24days and atleast 25 days columns in sdr report
  custom/icds_reports/reports/service_delivery_report.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#27725 Remove domain-level inactivity timeout
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
  corehq/apps/domain/views/settings.py
  corehq/apps/hqwebapp/session_details_endpoint/views.py
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/middleware.py
  corehq/util/context_processors.py
Labels: product/feature-flag

#27640 [ICDS Dashboard]: AWW Activity Report
  custom/icds_reports/const.py
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/migrations/0195_add_fields_aww_inactivity_report.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/sqldata/exports/aww_activity_report.py
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/inactive_awws.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/inactive-awws.distributed.txt
  custom/icds_reports/views.py
Labels: product/custom

#27742 allow user access to web apps via domain mirroring
  corehq/apps/cloudcare/views.py
Labels: product/invisible

#27693 sw/adding a new ucr for lactating women
  custom/icds_reports/ucr/reports/ls/ls_v2_report_lactating_women_names.json
Labels: product/custom

#27483 Update aww_vhnd_survey.txt
  custom/icds/templates/icds/messaging/indicators/kan/aww_vhnd_survey.txt
Labels: product/custom

#27723 Removed logged out middleware
  corehq/middleware.py
  corehq/toggles.py
  settings.py
Labels: product/invisible

#27744 Remove extra multiselect definition
  corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
Labels: product/invisible

#27729 INDDEX report changes
  corehq/apps/reports/standard/cases/utils.py
  custom/inddex/const.py
  custom/inddex/filters.py
  custom/inddex/food.py
  custom/inddex/reports/r1_master_data.py
  custom/inddex/reports/r2a_gaps_summary.py
  custom/inddex/reports/r2b_gaps_detail.py
  custom/inddex/reports/r3_nutrient_intake.py
  custom/inddex/reports/r4_nutrient_stats.py
  custom/inddex/reports/utils.py
  custom/inddex/tests/data/1_master.csv
  custom/inddex/tests/data/2a_conv_factor_gaps_summary.csv
  custom/inddex/tests/data/2a_fct_gaps_summary.csv
  custom/inddex/tests/data/2b_gaps_by_item_details.csv
  custom/inddex/tests/data/2b_gaps_by_item_summary.csv
  custom/inddex/tests/data/3_aggr_daily_intake_by_rspndnt.csv
  custom/inddex/tests/data/3_disaggr_intake_data_by_rspndnt.csv
  custom/inddex/tests/data/4_nutr_intake_summary_stats.csv
  custom/inddex/tests/test_master_report.py
  custom/inddex/ucr/data_sources/food_consumption_indicators.json
Labels: product/custom

#27748 add mirror domains to allowed web apps domains
  corehq/apps/hqwebapp/session_details_endpoint/views.py
  corehq/apps/ota/utils.py
Labels: product/feature-flag

#27746 fixes keyword update conflict
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/views.py
Labels: product/all-users-all-environments

#27750 Fix SESSION_COOKIE_SECURE & CSRF_COOKIE_SECURE values
  settings.py
Labels: product/invisible

#27625 Show only non-admin roles in filter for non-admin users when filtering mobile workers
  corehq/apps/reminders/util.py
  corehq/apps/users/forms.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/filtered_download.js
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
  corehq/apps/users/views/utils.py
  corehq/tabs/tabclasses.py
  custom/icds/view_utils.py
Labels: product/custom

#27738 update test for existing usernames
  corehq/apps/users/tests/test_db_accessors.py
Labels: product/invisible

#27326 ICDS Dashboard: Adding "not launched" to map legend
  custom/icds_reports/reports/adhaar.py
  custom/icds_reports/reports/adolescent_girls.py
  custom/icds_reports/reports/adult_weight_scale.py
  custom/icds_reports/reports/awc_daily_status.py
  custom/icds_reports/reports/children_initiated_data.py
  custom/icds_reports/reports/clean_water.py
  custom/icds_reports/reports/early_initiation_breastfeeding.py
  custom/icds_reports/reports/enrolled_children.py
  custom/icds_reports/reports/enrolled_women.py
  custom/icds_reports/reports/exclusive_breastfeeding.py
  custom/icds_reports/reports/functional_toilet.py
  custom/icds_reports/reports/immunization_coverage_data.py
  custom/icds_reports/reports/infantometer.py
  custom/icds_reports/reports/infants_weight_scale.py
  custom/icds_reports/reports/institutional_deliveries_sector.py
  custom/icds_reports/reports/lactating_enrolled_women.py
  custom/icds_reports/reports/medicine_kit.py
  custom/icds_reports/reports/new_born_with_low_weight.py
  custom/icds_reports/reports/prevalence_of_severe.py
  custom/icds_reports/reports/prevalence_of_stunting.py
  custom/icds_reports/reports/prevalence_of_undernutrition.py
  custom/icds_reports/reports/registered_household.py
  custom/icds_reports/reports/stadiometer.py
  custom/icds_reports/views.py
Labels: product/custom

#27754 fix typo
  custom/inddex/food.py
Labels: product/invisible

#27749 fix BadValueError when FilterSpec.wrap is called
  corehq/apps/userreports/reports/filters/specs.py
Labels: product/invisible

#27741 `generate_identifier()` to support AuthManager
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/tests/test_repeater_helpers.py
Labels: product/invisible

#27745 Fixed 'Go back to organization strucutre' link on the export_status page
  corehq/apps/locations/views.py
Labels: product/all-users-all-environments

#27757 Added cast to string when looking up couch doc by id during couch to …
  corehq/ex-submodules/dimagi/utils/couch/migration.py
Labels: product/invisible

#27758 fix get_active_users_by_email
  corehq/apps/domain/auth.py
Labels: product/invisible

#27721 continue processing messages after opt keywords
  corehq/apps/sms/api.py
Labels: product/all-users-all-environments

#27637 add new web apps permission
  corehq/apps/cloudcare/decorators.py
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/hqwebapp/tests/test_default_landing_page.py
  corehq/apps/users/migrations/0016_webappspermissions.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/static/users/js/roles_and_permissions.js
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/apps/users/templates/users/roles_and_permissions.html
  corehq/apps/users/views/__init__.py
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments

#27759 fix var name
  corehq/util/model_log.py
Labels: product/invisible

#27760 Bulk modify web users
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/tasks.py
Labels: product/all-users-all-environments

#27763 Revert "Revert "add new web apps permission""
  corehq/apps/cloudcare/decorators.py
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/hqwebapp/tests/test_default_landing_page.py
  corehq/apps/users/migrations/0016_webappspermissions.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/static/users/js/roles_and_permissions.js
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/apps/users/templates/users/roles_and_permissions.html
  corehq/apps/users/views/__init__.py
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments

#27770 Updated django admin for ExchangeApplication
  corehq/apps/app_manager/models.py
Labels: product/admin

#27767 Extend existing BlobDB dumps
  corehq/blobs/export.py
  corehq/blobs/management/commands/run_blob_export.py
  corehq/blobs/targzipdb.py
  corehq/blobs/tests/test_export.py
Labels: product/all-users-all-environments

#27381 upgarde sentry sdk
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#27329 remove unused settings
  localsettings.example.py
  settings.py
Labels: product/invisible

#27376 skip cleanliness rebuild for domains that are only livequery
  corehq/ex-submodules/casexml/apps/phone/cleanliness.py
Labels: product/invisible

#27771 [INDDEX] Rework filtering logic for 2B report
  custom/inddex/filters.py
  custom/inddex/food.py
  custom/inddex/reports/r2b_gaps_detail.py
  custom/inddex/tests/test_master_report.py
Labels: product/custom

#27776 fix key error in report filter spec
  corehq/apps/userreports/reports/filters/specs.py
Labels: product/invisible

#27774 add method in base class
  corehq/messaging/scheduling/models/abstract.py
Labels: product/invisible

#27777 Fix secure session cookie locally again
  settings.py
Labels: product/invisible

#27782 add option to add case IDs to report builder reports behind a flag
  corehq/apps/userreports/reports/builder/forms.py
  corehq/toggles.py
Labels: product/feature-flag

#27202 ICDS Dashboard: Nomenclature change in AWC block map view
  custom/icds_reports/reports/awcs_covered.py
  custom/icds_reports/reports/cas_reach_data.py
  custom/icds_reports/tests/agg_tests/reports/test_awcs_covered.py
Labels: product/custom

#27342 allow filtering models during load
  corehq/apps/dump_reload/couch/load.py
  corehq/apps/dump_reload/interface.py
  corehq/apps/dump_reload/management/commands/load_domain_data.py
  corehq/apps/dump_reload/sql/load.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#27780 add case filter for location with descendants
  corehq/apps/userreports/reports/builder/const.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/tests/test_report_builder.py
  corehq/toggles.py
Labels: product/feature-flag

#27785 more detail to soft assert
  corehq/util/metrics/prometheus.py
Labels: product/invisible

#27791 update text to read Advanced plan rather than Standard
  corehq/apps/locations/templates/locations/downgrade_locations.html
Labels: product/all-users-all-environments

#27712 [ICDS Dashboard]: PPR(Poshan Progress Report) UI
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
Labels: product/custom

#27792 INDDEX Reports text updates
  custom/inddex/const.py
  custom/inddex/reports/r3_nutrient_intake.py
  custom/inddex/tests/data/1_master.csv
  custom/inddex/tests/data/2a_conv_factor_gaps_summary.csv
  custom/inddex/tests/data/2a_fct_gaps_summary.csv
  custom/inddex/tests/data/2b_gaps_by_item_details.csv
  custom/inddex/tests/data/2b_gaps_by_item_summary.csv
  custom/inddex/tests/data/3_disaggr_intake_data_by_rspndnt.csv
Labels: product/custom

#27778 do not force password if web user
  corehq/apps/user_importer/validation.py
Labels: product/all-users-all-environments

#27790 Support multiple date formats in case list config
  corehq/apps/api/data/suite.xml
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/tests/data/days_ago_suite.xml
  corehq/apps/app_manager/tests/data/suite/call-center.xml
  corehq/apps/app_manager/tests/data/suite/multi-sort.json
  corehq/apps/app_manager/tests/data/suite/multi-sort.xml
  corehq/apps/app_manager/tests/data/suite/normal-suite.xml
  corehq/apps/app_manager/tests/data/suite/suite-case-tiles.xml
Labels: product/all-users-all-environments

#27697 [ICDS Dashboard]: Poshan Progress Report
  custom/icds_reports/const.py
  custom/icds_reports/migrations/0196_ppr_update_view.py
  custom/icds_reports/migrations/sql_templates/database_views/poshan_progress_report_view.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/sqldata/exports/poshan_progress_report.py
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/migrations.py
  custom/icds_reports/views.py
Labels: product/custom

#27793 Don't include case name column in emailed reports
  corehq/apps/reports/standard/cases/case_list_explorer.py
Labels: product/feature-flag

#27694 ICDS Dashboard: SDD detailing UI changes
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
Labels: product/custom

#27734 Location reassignment reassign other cases code cleanup
  custom/icds/location_reassignment/download.py
  custom/icds/location_reassignment/parser.py
  custom/icds/location_reassignment/tasks.py
  custom/icds/location_reassignment/tests/test_download.py
  custom/icds/location_reassignment/utils.py
  custom/icds/location_reassignment/views.py
Labels: product/feature-flag

#27795 Mark download_data_files to allow XSS_BODY
  corehq/apps/export/urls.py
Labels: product/invisible

#27788 Kev/sms messaging email model
  corehq/apps/sms/migrations/0040_email.py
  corehq/apps/sms/models.py
Labels: product/all-users-all-environments

#27779 Moved last_visited_domain from request to cache
  corehq/apps/domain/middleware.py
  corehq/apps/domain/templates/domain/select.html
  corehq/apps/domain/views/base.py
Labels: product/all-users-all-environments

#27722 DRY up case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
Labels: QA Passed, awaiting QA, product/invisible

#27797 Removed custom eslint plugin from stickler
  .eslintrc.js
  .stickler.yml
Labels: product/invisible

#27813 Commented out RequestsOAuth2Tests
  corehq/motech/tests/test_requests.py
Labels: product/invisible

#27808 Fixed can_edit_data call
  corehq/apps/data_interfaces/views.py
Labels: product/invisible

#27784 Remove TCL Karix sms gateway (icds)
  corehq/apps/sms/migrations/0040_remove_karix_backend.py
  corehq/apps/sms/tests/test_backends.py
  corehq/messaging/smsbackends/karix/__init__.py
  corehq/messaging/smsbackends/karix/exceptions.py
  corehq/messaging/smsbackends/karix/forms.py
  corehq/messaging/smsbackends/karix/models.py
  corehq/messaging/smsbackends/karix/tests/__init__.py
  corehq/messaging/smsbackends/karix/tests/test_karix.py
  settings.py
Labels: product/invisible

#27804 Fix bug in export/import compressed blobs
  corehq/blobs/__init__.py
  corehq/blobs/export.py
  corehq/blobs/migrate.py
  corehq/blobs/tests/test_export.py
  corehq/blobs/tests/test_migrate_compress.py
  corehq/blobs/tests/util.py
Labels: product/invisible

#27818 Updated search function to protect against null values
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
Labels: product/all-users-all-environments

#27820 incremented migration and modified date field
  corehq/apps/sms/migrations/0041_email.py
  corehq/apps/sms/models.py
Labels: product/all-users-all-environments

#27811 INDDEX reports changes
  custom/inddex/food.py
  custom/inddex/reports/r3_nutrient_intake.py
  custom/inddex/tests/data/1_master.csv
  custom/inddex/tests/data/3_aggr_daily_intake_by_rspndnt.csv
  custom/inddex/tests/data/3_disaggr_intake_data_by_rspndnt.csv
  custom/inddex/tests/data/4_nutr_intake_summary_stats.csv
Labels: product/custom

#27810 restrict debugger to edit data
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/preview_app/base.html
Labels: product/all-users-all-environments

#27672 Push linked domains
  corehq/apps/app_manager/views/utils.py
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/views.py
Labels: QA Passed, product/feature-flag

#27812 Remove domain name from the names of cookies
  corehq/apps/reports/static/reports/js/hq_report.js
Labels: product/invisible

#27817 Skip on Travis
  corehq/motech/tests/test_requests.py
Labels: product/invisible

#27814 Move WAF regex compaction from here to commcare-cloud
  corehq/apps/hqwebapp/management/commands/list_waf_allow_patterns.py
Labels: product/invisible

#27823 Made CommCareUserConfirmAccountView location safe
  corehq/apps/users/views/mobile/users.py
Labels: product/feature-flag

#27822 Updated menu tabs to run _is_viewable before locations check
  corehq/tabs/uitab.py
Labels: product/all-users-all-environments

#27800 Turn backend improvements
  corehq/apps/smsbillables/exceptions.py
  corehq/apps/smsbillables/migrations/0021_infobip_gateway_fee_amount_null.py
  corehq/apps/smsbillables/models.py
  corehq/apps/smsbillables/tests/generator.py
  corehq/apps/smsbillables/utils.py
  corehq/messaging/smsbackends/infobip/models.py
  corehq/messaging/smsbackends/turn/models.py
Labels: product/all-users-all-environments

#27787 [ICDS Dashboard] Fix table header fixes
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#27587 Prompted updates respect build profile
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_util.py
  corehq/apps/app_manager/util.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/ota/views.py
Labels: product/custom, product/feature-flag

#27669 Support for lazily loading multimedia in Commcare
  corehq/apps/app_manager/static/app_manager/json/commcare-profile-settings.yaml
  corehq/apps/app_manager/static/app_manager/json/commcare-settings-layout.yaml
  corehq/apps/app_manager/static_strings.py
  corehq/apps/app_manager/suite_xml/generator.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/data/suite/media-suite-lazy-false.xml
  corehq/apps/app_manager/tests/data/suite/media-suite-lazy-true.xml
  corehq/apps/app_manager/tests/test_media_suite.py
  corehq/toggles.py
Labels: product/all-users-all-environments

#27829 add closed_on to report builder columns
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/tests/test_report_builder.py
Labels: product/all-users-all-environments

#27805 Kev/sms messaging email filter
  corehq/apps/reports/standard/sms.py
  corehq/apps/sms/filters.py
  corehq/messaging/scheduling/models/content.py
Labels: product/all-users-all-environments

#27802 add email details to message details report
  corehq/apps/reports/standard/sms.py
Labels: product/all-users-all-environments

#27799 Add Bounced, Send, Delivered status to email messages
  corehq/apps/hqwebapp/tasks.py
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/reports/standard/sms.py
  corehq/apps/sms/filters.py
  corehq/apps/sms/models.py
  corehq/ex-submodules/dimagi/utils/django/email.py
  corehq/messaging/scheduling/models/content.py
  docs/email_monitoring_SES.rst
  settings.py
Labels: product/all-users-all-environments

#27819 [ICDS Dashboard] Fixes in the AWC Activity Report
  custom/icds_reports/sqldata/exports/aww_activity_report.py
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/tests/agg_tests/test_export_data.py
Labels: product/custom

#27831 fix pagination of location and location type APIs
  corehq/apps/locations/resources/v0_5.py
Labels: product/all-users-all-environments

#27827 Add KAFKA_ADVERTISED_PORT to docker kafka environment
  docker/hq-compose-services.yml
Labels: product/invisible

#27826 Fixed dropzone permissions to work with domain mirroring
  corehq/apps/export/templates/export/download_data_files.html
  corehq/apps/users/permissions.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#27834 Annotate UserFieldsView with waf_allow
  corehq/apps/users/urls.py
Labels: product/invisible

#27828 separate content filter for messaging history
  corehq/apps/reports/standard/sms.py
  corehq/apps/sms/filters.py
Labels: product/all-users-all-environments

#27837 Set email status to error when sending fails
  corehq/apps/hqwebapp/tasks.py
  corehq/apps/sms/models.py
  corehq/messaging/scheduling/models/content.py
Labels: product/all-users-all-environments

#27840 Upgrade jsonfield to Django 1.11/2.2 compatible version
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#27841 sms email use logged_subevent recipient
  corehq/messaging/scheduling/models/content.py
Labels: product/all-users-all-environments

#27796 Added error code filter to Messaging History
  corehq/apps/reports/standard/sms.py
  corehq/apps/sms/filters.py
Labels: product/all-users-all-environments

#27843 update nodejs version in Dockerfile
  Dockerfile
Labels: product/invisible

#27844 rebuild the data too
  corehq/apps/userreports/pillow.py
Labels: product/invisible

#27614 ES auto-create-index to False again
  corehq/ex-submodules/pillowtop/processors/elastic.py
  docker/files/elasticsearch.yml
  testsettings.py
Labels: product/invisible

#27852 fixing issues with negative price values
  corehq/apps/smsbillables/models.py
Labels: product/invisible

#27825 Added support for app logo in web apps
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/json/commcare-profile-settings.yaml
  corehq/apps/app_manager/static/app_manager/json/commcare-settings-layout.yaml
  corehq/apps/app_manager/static_strings.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/views.js
  corehq/apps/cloudcare/templates/formplayer/grid_view.html
  corehq/apps/cloudcare/views.py
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/appicon.less
Labels: product/all-users-all-environments

#27853 update Dockerhub image
  Dockerfile
  docker/Dockerfile
Labels: product/invisible

#27856 Make "Rebuilding table" message show up in pillow logs
  corehq/apps/userreports/pillow.py
Labels: product/invisible

#27854 fix UCR tests for new behavior
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/tests/test_rebuild_migrate.py
Labels: product/invisible
