Repository dimagi/commcare-hq, pull requests merged in 2020-12, with the labels that each got.

#28825 command to export blobs using meta from file
  corehq/blobs/management/commands/export_selected_blobs.py
  corehq/blobs/management/commands/run_blob_export.py
Labels: product/invisible

#28818 refactoring of couch dump code to allow excludes
  corehq/apps/dump_reload/couch/dump.py
  corehq/apps/dump_reload/couch/id_providers.py
  corehq/apps/dump_reload/management/commands/dump_domain_data.py
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
Labels: product/invisible

#28826 Couch to SQL forms & cases docs
  corehq/apps/couch_sql_migration/README.md
Labels: product/invisible

#28799 Fix pygooglechart missing image issue
  corehq/apps/reports/standard/monitoring.py
Labels: product/invisible

#28830 add 'natural_key' to blob meta
  corehq/blobs/models.py
Labels: product/invisible

#28819 further changes do dump command for better reuse
  corehq/apps/dump_reload/couch/dump.py
  corehq/apps/dump_reload/couch/load.py
  corehq/apps/dump_reload/interface.py
  corehq/apps/dump_reload/management/commands/load_domain_data.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/sql/filters.py
  corehq/apps/dump_reload/sql/load.py
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
  corehq/apps/dump_reload/tests/test_slugs.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/blobs/export.py
Labels: product/invisible

#28785 Extract captcha from draconian features as HQ feature
  corehq/apps/domain/forms.py
  corehq/apps/hqwebapp/forms.py
  corehq/apps/registration/forms.py
  settings.py
Labels: Open for review: do not merge, Risk: High, product/invisible

#28797 remove UI password hints/checks
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/views/mobile/users.py
  settings.py
Labels: product/custom

#28787 correctly update form on ajax
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/partials/reset_password.html
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
Labels: product/all-users-all-environments

#28803 install jquery-treetable.js from github instead of npm
  package.json
  yarn.lock
Labels: dependencies, product/all-users-all-environments

#28796 extract setting to configure autocomplete
  corehq/apps/domain/forms.py
  corehq/apps/domain/tests/test_views.py
  settings.py
Labels: product/custom

#28786 Allow custom password clean from extensions
  corehq/apps/domain/extension_points.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/tests/test_forms.py
  corehq/apps/domain/views/settings.py
  corehq/apps/registration/views.py
  corehq/apps/settings/views.py
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
  settings.py
Labels: Risk: High, product/invisible

#28688 remove icds references from settings
  docker/localsettings.py
  settings.py
  testsettings.py
Labels: product/custom

#28834 Couch to SQL: bad dates and better docs
  corehq/apps/couch_sql_migration/README.md
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
Labels: product/invisible

#28838 [Accounting Admin] Tools to optimize workflow for upgrading customer software plans
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/templates/accounting/partials/customer_plan_version_tools.html
  corehq/apps/accounting/templates/accounting/partials/version_summary_tab.html
  corehq/apps/accounting/templates/accounting/plan_version.html
  corehq/apps/accounting/tests/generator.py
  corehq/apps/accounting/tests/test_admin_software_plans.py
  corehq/apps/accounting/urls.py
  corehq/apps/accounting/utils/software_plans.py
  corehq/apps/accounting/views.py
Labels: product/admin

#28839 Update ABT supervisory reports for 2020
  custom/abt/commcare_extensions.py
  custom/abt/reports/data_sources/supervisory_v2020.json
  custom/abt/reports/expressions.py
  custom/abt/reports/flagspecs_v2020.yaml
  custom/abt/reports/supervisory_report_v2020.json
  settings.py
Labels: product/custom

#28844 keep default behaviour for test
  corehq/apps/user_importer/tests/test_importer.py
Labels: Risk: Medium, product/invisible

#28751 Added explicit error on passing user_data during user creation
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_user_model.py
Labels: product/invisible

#28846 Fix calendar appearing on clicking help text
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: Risk: Medium, product/all-users-all-environments

#28817 Added initial pull of multimedia to link_app
  corehq/apps/linked_domain/applications.py
Labels: product/invisible

#28788 Added auto launching of actions
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/data/suite/search_command_detail.xml
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
  corehq/toggles.py
Labels: QA Passed, product/feature-flag

#28852 Drop unused, broken module
  corehq/motech/openmrs/repeater_generator.py
Labels: product/invisible

#28859 only dump TransifexOrganization once
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#28861 Add JS Dependencies to dependabot
  .github/dependabot.yml
  .github/labels.yml
Labels: product/invisible

#28784 Use thread workers to update facility cases
  custom/onse/const.py
  custom/onse/management/commands/update_onse_facility_cases.py
  custom/onse/tasks.py
  custom/onse/tests.py
Labels: product/invisible

#28843 prevent SQL loader from hanging if there's an error
  corehq/apps/dump_reload/sql/load.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#28853 Drop unused payload generator result handlers
  corehq/motech/repeaters/management/commands/update_cancelled_records.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/repeater_generators.py
Labels: product/invisible

#28873 draw progress bar at start of iteration
  corehq/util/log.py
Labels: product/invisible

#28842 Revert il-conceived skip logic
  corehq/apps/dump_reload/interface.py
  corehq/apps/dump_reload/management/commands/load_domain_data.py
Labels: product/invisible

#28841 Updated label and help text for case claim relevant attribute
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
Labels: product/feature-flag

#28831 Web apps: Fixed custom logo not appearing on apps
  corehq/apps/cloudcare/views.py
Labels: QA Passed, Risk: Medium, product/all-users-all-environments

#28857 Removed corehq/apps/api/data/
  corehq/apps/api/data/default/app_strings.txt
  corehq/apps/api/data/en/app_strings.txt
  corehq/apps/api/data/media_profile.ccpr
  corehq/apps/api/data/media_profile.xml
  corehq/apps/api/data/media_suite.xml
  corehq/apps/api/data/modules-0/forms-0.xml
  corehq/apps/api/data/modules-0/forms-1.xml
  corehq/apps/api/data/modules-0/forms-2.xml
  corehq/apps/api/data/modules-0/forms-3.xml
  corehq/apps/api/data/modules-0/forms-4.xml
  corehq/apps/api/data/modules-0/forms-5.xml
  corehq/apps/api/data/modules-1/forms-0.xml
  corehq/apps/api/data/modules-1/forms-1.xml
  corehq/apps/api/data/modules-1/forms-2.xml
  corehq/apps/api/data/modules-1/forms-3.xml
  corehq/apps/api/data/modules-1/forms-4.xml
  corehq/apps/api/data/modules-2/forms-0.xml
  corehq/apps/api/data/modules-3/forms-0.xml
  corehq/apps/api/data/modules-4/forms-0.xml
  corehq/apps/api/data/modules-4/forms-1.xml
  corehq/apps/api/data/modules-4/forms-2.xml
  corehq/apps/api/data/modules-5/forms-0.xml
  corehq/apps/api/data/modules-6/forms-0.xml
  corehq/apps/api/data/modules-7/forms-0.xml
  corehq/apps/api/data/modules-7/forms-1.xml
  corehq/apps/api/data/modules-7/forms-2.xml
  corehq/apps/api/data/modules-8/forms-0.xml
  corehq/apps/api/data/modules-8/forms-1.xml
  corehq/apps/api/data/modules-8/forms-2.xml
  corehq/apps/api/data/modules-9/forms-0.xml
  corehq/apps/api/data/profile.ccpr
  corehq/apps/api/data/profile.xml
  corehq/apps/api/data/suite.xml
Labels: Risk: High, product/invisible

#28875 Add a link to view the data source
  corehq/apps/userreports/templates/userreports/edit_report_config.html
Labels: product/all-users-all-environments

#28858 Auto launching of actions, round 2
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
Labels: Risk: Medium, product/feature-flag

#28871 disable datadog trace startup logs by default
  settings.py
Labels: product/invisible

#28872 allow running migrations test in isolation
  docker/run.sh
Labels: product/invisible

#28882 add admin for RateLimitedTwoFactorLog
  corehq/project_limits/admin.py
Labels: product/invisible

#28883 Increase CASE_SEARCH_MAX_RESULTS
  corehq/apps/case_search/const.py
  corehq/apps/case_search/utils.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/pillows/mappings/case_search_mapping.py
Labels: product/feature-flag

#28886 Added username as a required argument to update_case_index_relationship
  custom/covid/management/commands/update_case_index_relationship.py
Labels: product/invisible

#28881 prefix progress output if not 'oneline'
  corehq/util/log.py
Labels: product/invisible

#28880 fix dump when using load balanced databases
  corehq/apps/dump_reload/sql/dump.py
Labels: product/invisible

#28874 add reporting DB mapping to citus regardless of whether or not ICDS code is present
  docker/localsettings.py
Labels: product/invisible

#28860 delete all data for a domain
  corehq/apps/domain/deletion.py
  corehq/apps/domain/models.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/domain/tests/test_deletion_models.py
Labels: product/invisible

#28879 pass usernames directly to filter
  corehq/apps/dump_reload/sql/filters.py
Labels: product/invisible

#28888 Refactor DHIS2 DataSetMap models
  corehq/motech/dhis2/models.py
  corehq/motech/dhis2/tasks.py
  corehq/motech/dhis2/tests/test_datasetmap.py
  corehq/motech/dhis2/tests/test_models.py
  corehq/motech/dhis2/utils.py
Labels: product/invisible

#28887 Couch to SQL forms & cases migration fixes
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/casepatch.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/patches.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
Labels: product/invisible

#28895 support getting count without querying
  corehq/apps/dump_reload/sql/filters.py
Labels: product/invisible

#28885 prevent closed in case import
  corehq/apps/case_importer/util.py
Labels: product/all-users-all-environments

#28801 added feature flag for app_analytics
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/util.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_test.js
  corehq/apps/mocha/templates/mocha/base.html
  corehq/toggles.py
Labels: Risk: Medium, product/invisible

#28870 Removed dead code
  corehq/apps/app_manager/suite_xml/sections/entries.py
Labels: product/invisible

#28898 Added translations
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
Labels: Risk: Medium, product/invisible

#28899 move APP_USER_PROFILES privilege to advanced and above
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0053_app_user_profiles_advanced.py
Labels: product/invisible, reindex/migration

#28878 Fix case exports dropdown visibility
  corehq/apps/export/views/utils.py
Labels: product/all-users-all-environments

#28897 Add a setting for enabling TTS feature in mobile
  corehq/apps/app_manager/static/app_manager/json/commcare-profile-settings.yaml
  corehq/apps/app_manager/static/app_manager/json/commcare-settings-layout.yaml
  corehq/apps/app_manager/static_strings.py
Labels: product/all-users-all-environments

#28877 Clean up some Repeat Record Report code
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/tests/test_tasks.py
  corehq/apps/data_interfaces/tests/test_utils.py
  corehq/apps/data_interfaces/utils.py
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/templates/repeaters/repeat_record_report.html
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/tests/test_repeat_records.py
Labels: product/invisible

#28906 Fixed missing instances in apps using multiple case search menus
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/tests/data/suite/remote_request.xml
  corehq/apps/app_manager/tests/data/suite/search_command_detail.xml
  corehq/apps/app_manager/tests/data/suite/search_config_blacklisted_owners.xml
  corehq/apps/app_manager/tests/data/suite/search_config_default_only.xml
  corehq/apps/app_manager/tests/test_suite_remote_request.py
Labels: product/feature-flag

#28905 Fixed lookup table pull for remote linked apps
  corehq/apps/linked_domain/remote_accessors.py
Labels: product/feature-flag

#28911 Feature/ush 426 app analytics for case claim
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: Risk: Medium, product/feature-flag

#28913 Added help link to APP_ANALYTICS feature flag
  corehq/toggles.py
Labels: product/admin

#28909 ignore couch doc types in sql exporter
  corehq/apps/dump_reload/sql/dump.py
Labels: product/invisible

#28908 configurable chunk size
  corehq/apps/dump_reload/sql/filters.py
Labels: product/invisible

#28894 read blob meta from zip file
  corehq/apps/dump_reload/management/commands/load_domain_data.py
  corehq/blobs/management/commands/export_selected_blobs.py
Labels: product/invisible

#28917 blob export fixes
  corehq/blobs/management/commands/export_selected_blobs.py
Labels: product/invisible

#28915 Allow configuring "Search All Cases" text in case claim
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/templatetags/xforms_extras.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/util.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: Risk: Medium, product/feature-flag

#28914 Add any search_filter instances to remote request
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/tests/data/suite/remote_request.xml
  corehq/apps/app_manager/tests/data/suite/remote_request_custom_detail.xml
  corehq/apps/app_manager/tests/test_suite_remote_request.py
Labels: product/invisible

#28918 Fix modal classes
  docs/ui_helpers.rst
Labels: product/invisible

#28814 Removed unused fields from app passed to initial page data in web apps
  corehq/apps/cloudcare/views.py
Labels: QA Passed, Risk: Medium, product/invisible

#28919 Add headings to Connection Settings pages
  corehq/motech/forms.py
  corehq/motech/templates/motech/connection_settings.html
  corehq/motech/templates/motech/connection_settings_detail.html
Labels: product/invisible

#28910 Add feature flag for default export settings
  corehq/toggles.py
Labels: product/invisible

#28925 Update and translate case import error message
  corehq/apps/case_importer/views.py
Labels: Risk: High, product/all-users-all-environments

#28926 Fixed case claim relevancy UI
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/views/modules.py
Labels: QA Passed, product/invisible

#28920 Count messaging email sends and bounces by domain
  corehq/apps/sms/event_handlers.py
  corehq/ex-submodules/dimagi/utils/django/email.py
  corehq/messaging/scheduling/models/content.py
Labels: product/invisible

#28928 Configure auto case rule run time by domain
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
  corehq/apps/domain/static/domain/js/internal_settings.js
  corehq/apps/domain/views/internal.py
  settings.py
Labels: product/admin

#28812 Added ability to copy editable version of linked app
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/app_view.html
  corehq/apps/app_manager/templates/app_manager/partials/settings/app_settings.html
  corehq/apps/app_manager/tests/test_apps.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/linked_domain/management/commands/unlink_apps.py
Labels: QA Passed, product/feature-flag

#28848 webapps submit lazy accumulation
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
Labels: QA Passed, Risk: Medium, product/all-users-all-environments

#28901 Refactor enterprise related logic to its own app
  corehq/apps/README.rst
  corehq/apps/accounting/exceptions.py
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/urls.py
  corehq/apps/accounting/utils/downgrade.py
  corehq/apps/accounting/utils/subscription.py
  corehq/apps/accounting/views.py
  corehq/apps/domain/views/accounting.py
  corehq/apps/enterprise/__init__.py
  corehq/apps/enterprise/enterprise.py
  corehq/apps/enterprise/exceptions.py
  corehq/apps/enterprise/forms.py
  corehq/apps/enterprise/management/__init__.py
  corehq/apps/enterprise/management/commands/__init__.py
  corehq/apps/enterprise/management/commands/report_on_enterprise_domain.py
  corehq/apps/enterprise/models.py
  corehq/apps/enterprise/static/enterprise/js/enterprise_dashboard.js
  corehq/apps/enterprise/static/enterprise/js/enterprise_settings.js
  corehq/apps/enterprise/tasks.py
  corehq/apps/enterprise/templates/enterprise/enterprise_dashboard.html
  corehq/apps/enterprise/templates/enterprise/enterprise_settings.html
  corehq/apps/enterprise/tests/__init__.py
  corehq/apps/enterprise/tests/test_enterprise_tasks.py
  corehq/apps/enterprise/urls.py
  corehq/apps/enterprise/views.py
  settings.py
  urls.py
Labels: QA Passed, product/invisible

#28927 Update store_billable max_retries and default_retry_delay to account for Twilio delays
  corehq/apps/sms/tasks.py
  corehq/apps/smsbillables/exceptions.py
  corehq/apps/smsbillables/models.py
Labels: product/invisible

#28929 Added support for EOF nav to search-first case lists
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
Labels: Risk: Medium, product/feature-flag

#28933 Updated TestReportMultipleAggregationsSQL dates
  corehq/apps/userreports/tests/test_report_aggregation.py
Labels: product/feature-flag

#28932 Switched allow_mirroring for message log default location
  corehq/apps/reports/filters/fixtures.py
Labels: product/feature-flag

#28821 Added domain tag to commcare.two_factor.setup_requests
  corehq/apps/hqwebapp/two_factor_gateways.py
Labels: product/invisible

#28934 Add namespace to export settings toggle
  corehq/toggles.py
Labels: product/invisible

#27597 Couch to SQL migration: CommtrackConfig (1 of 3)
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/cleanup/tests/test_couch_to_sql_commtrack.py
  corehq/apps/commtrack/management/commands/populate_commtrackconfig.py
  corehq/apps/commtrack/migrations/0003_create_config_models.py
  corehq/apps/commtrack/models.py
  corehq/apps/custom_data_fields/management/commands/populate_custom_data_fields.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/mobile_auth/management/commands/populate_mobileauthkeyrecord.py
  corehq/apps/reports/commtrack/standard.py
Labels: QA Passed, Risk: Medium, product/invisible

#28793 Add DefaultExportSettings model
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/export/migrations/0010_defaultexportsettings.py
  corehq/apps/export/models/__init__.py
  corehq/apps/export/models/export_settings.py
Labels: product/invisible, reindex/migration

#28942 make sure docker has xmlsec1 required by python3-saml
  Dockerfile
Labels: product/invisible

#28944 dockerfile: only install libxmlsec1-dev as docker build is complaining it can't find libxml2-dev
  Dockerfile
Labels: product/invisible

#28945 dockerfile: docker build still throwing errors with libxmlsec1-dev, removing requirement for now
  Dockerfile
Labels: product/invisible

#28862 improve case lists pagination
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/case_list_pagination_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/templates/cloudcare/spec/form_entry/mocha.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/users.html
Labels: QA Passed, Risk: Medium, product/all-users-all-environments
