Repository dimagi/commcare-hq, pull requests merged in 2020-05, with the labels that each got.

#27336 Upgrade pip tools to work with pip 20.1 (fix travis tests)
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
Labels: product/invisible

#27341 Update valid response codes for incremental push
  corehq/apps/export/models/incremental.py
Labels: product/invisible

#27133 [ICDS Dashboard]: Fix Availing Services Model - Agg AWC
  custom/icds_reports/tests/agg_tests/fixtures/availing_services_form.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_5_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
Labels: product/custom

#27340 Manually implement form setters/getters for connection settings model
  corehq/motech/forms.py
Labels: product/invisible

#27344 Do not deactivate users in case of extract
  custom/icds/location_reassignment/models.py
Labels: product/feature-flag

#27332 Location reassignment validate usernames
  custom/icds/location_reassignment/parser.py
  custom/icds/location_reassignment/tests/test_parser.py
Labels: product/feature-flag

#27337 Rename testImportNone to testImportFileMissing
  corehq/apps/case_importer/tests/test_importer.py
Labels: product/invisible

#27338 Fix "Manage releases per location"
  corehq/apps/domain/forms.py
  corehq/apps/domain/views/releases.py
Labels: product/feature-flag

#27347 Remove colons from sent filename
  corehq/apps/export/models/incremental.py
Labels: product/invisible

#27350 Added new sum when template
  corehq/apps/userreports/reports/factory.py
  corehq/apps/userreports/reports/sum_when_templates.py
Labels: product/feature-flag

#27318 Added custom metadata to SMS metrics
  corehq/apps/sms/tasks.py
Labels: product/invisible

#27352 Show either editable or read-only property descriptions
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
Labels: product/feature-flag

#27319 add archived_on on locations
  corehq/apps/locations/migrations/0018_auto_20200430_1601.py
  corehq/apps/locations/models.py
  corehq/apps/locations/tests/test_locations.py
Labels: product/invisible

#27343 Be explicit about valid operations
  custom/icds/location_reassignment/tasks.py
Labels: product/feature-flag

#27353 Ce/temp ucr tables
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/location_reassignment.py
Labels: product/invisible

#27356 Update buttons text
  custom/icds/location_reassignment/views.py
Labels: product/feature-flag

#27358 allow multiple operations
  custom/icds/location_reassignment/models.py
  custom/icds/location_reassignment/tests/test_models.py
Labels: product/feature-flag

#27306 [ICDS Dashboard] Removed feature flag for total household numbers in demographics report
  custom/icds_reports/sqldata/exports/demographics.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
Labels: product/custom

#27346 model may be dumped in multiple ways
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#27359 update parser check for descendants
  custom/icds/location_reassignment/parser.py
Labels: product/feature-flag

#27363 Location Reassignment - Realign fixes
  custom/icds/location_reassignment/models.py
  custom/icds/location_reassignment/parser.py
  custom/icds/location_reassignment/tasks.py
  custom/icds/location_reassignment/views.py
Labels: product/feature-flag

#27361 More improvements to evaluate_couch_model_for_sql
  corehq/apps/cleanup/management/commands/evaluate_couch_model_for_sql.py
Labels: product/invisible

#27331 Revert "Removed caching logic from SMS chat contacts" and tweak cache
  corehq/apps/sms/views.py
Labels: product/invisible

#27366 updated the perfect scrollbar
  bower.json
  custom/icds_reports/templates/icds_reports/dashboard.html
Labels: product/custom

#27369 Ce/loc qa
  custom/icds_reports/migrations/0186_refresh_views.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/awc_location.py
  custom/icds_reports/views.py
Labels: product/custom

#27309 Location Reassignment: UCR Changes
  corehq/apps/userreports/adapter.py
  corehq/apps/userreports/data_source_providers.py
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/tasks.py
  custom/icds/location_reassignment/tasks.py
  custom/icds/location_reassignment/utils.py
Labels: product/feature-flag

#27375 fix _get_report_fixture_for_user
  custom/icds/messaging/indicators.py
  custom/icds/tests/test_ls_aggregate_performance.py
Labels: product/invisible

#27103 [ICDS Dashboard]: Child Growth Tracker Report
  custom/icds_reports/const.py
  custom/icds_reports/migrations/0185_updated_chm_voew.py
  custom/icds_reports/migrations/0186_merge_20200429_1556.py
  custom/icds_reports/migrations/0187_merge_20200505_0719.py
  custom/icds_reports/migrations/sql_templates/database_views/child_health_monthly.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/sqldata/exports/growth_tracker_report.py
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/views.py
Labels: product/custom

#27360 Use PASSWORD_PLACEHOLDER
  corehq/motech/forms.py
Labels: product/invisible

#27328 Fix data checks for deleted domains
  corehq/apps/cleanup/tasks.py
Labels: product/invisible

#27370 simplify filtering for TransifexOrganization
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/sql/filters.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#27365 Renamed flag
  corehq/toggles.py
Labels: product/invisible

#27380 [ICDS Dashboard]: Migration Order Fix
  custom/icds_reports/migrations/0185_updated_chm_voew.py
  custom/icds_reports/migrations/0186_merge_20200429_1556.py
  custom/icds_reports/migrations/0187_chm_view_growth_tracker.py
Labels: product/custom, product/invisible

#27372 Add LMP field for mother API
  custom/icds_reports/migrations/sql_templates/database_views/bihar_api_mother_view.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/reports/bihar_api.py
  custom/icds_reports/tests/agg_tests/reports/test_bihar_api_mother_details.py
Labels: product/custom

#27386 Update .eslintrc.js to allow single-line functions
  .eslintrc.js
Labels: product/invisible

#27310 Location Reassignment - Realign
  custom/icds/location_reassignment/const.py
  custom/icds/location_reassignment/download.py
  custom/icds/location_reassignment/dumper.py
  custom/icds/location_reassignment/exceptions.py
  custom/icds/location_reassignment/models.py
  custom/icds/location_reassignment/parser.py
  custom/icds/location_reassignment/processor.py
  custom/icds/location_reassignment/tasks.py
  custom/icds/location_reassignment/tests/test_dumper.py
  custom/icds/location_reassignment/tests/test_models.py
  custom/icds/location_reassignment/tests/test_parser.py
  custom/icds/location_reassignment/tests/test_processor.py
  custom/icds/location_reassignment/tests/test_processors.py
  custom/icds/location_reassignment/tests/test_utils.py
  custom/icds/location_reassignment/utils.py
  custom/icds/location_reassignment/views.py
Labels: product/feature-flag

#27383 account for national view
  custom/icds_reports/reports/fact_sheets.py
Labels: product/invisible

#27384 Updated data cleaning to only edit properties that user touched
  corehq/apps/reports/static/reports/js/data_corrections.js
Labels: QA Passed, product/all-users-all-environments

#27390 Actionable followup to cleanup checks
  corehq/apps/cleanup/tasks.py
  corehq/apps/userreports/management/commands/prune_old_datasources.py
Labels: product/invisible

#27388 Updates to LS reports, including new AG girls out of school report
  custom/icds_reports/ucr/data_sources/ccs_record_cases.json
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
  custom/icds_reports/ucr/reports/ls/ls_v2_ag_out_of_school.json
  custom/icds_reports/ucr/reports/mpr/mpr_v2_3ii_person_cases.json
Labels: product/custom

#27382 Update location_id fetch
  custom/icds/forms.py
Labels: product/custom

#27396 Add filter
  custom/icds_reports/ucr/reports/mpr/mpr_v2_3ii_person_cases.json
Labels: product/custom

#27395 [ICDS Dashboard]: Removal of extra condition in the Child growth tracker report
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#27391 Added handling of missing source domains
  corehq/apps/appstore/management/commands/export_exchange.py
Labels: product/invisible

#27393 Add test utils for reentrant redis locks
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/tests/locks.py
  corehq/tests/noseplugins/redislocks.py
  corehq/tests/test_locks.py
  testsettings.py
Labels: product/invisible

#27389 Have docker-compose declare zookeeper as a dependency of kafka
  docker/hq-compose-services.yml
Labels: product/invisible

#27348 Use request log id for log URL
  corehq/apps/export/views/incremental.py
Labels: product/feature-flag

#27339 Accommodate friendly write-offs in HQ as a "credit adjustment" type
  corehq/apps/accounting/async_handlers.py
  corehq/apps/accounting/filters.py
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/interface.py
  corehq/apps/accounting/migrations/0048_friendly_writeoff.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/views.py
Labels: product/invisible

#27398 Add docs on restrictions of core models
  corehq/apps/locations/permissions.py
Labels: product/invisible

#27392 Ignore case_type when data cleaning
  corehq/apps/export/const.py
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#26604 Migrate DefaultConsumption to SQL (3 of 3)
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/commtrack/tests/test_stock_state.py
  corehq/apps/consumption/_design/views/consumption_index/map.js
  corehq/apps/consumption/_design/views/consumption_index/reduce.js
  corehq/apps/consumption/management/commands/populate_defaultconsumption.py
  corehq/apps/consumption/migrations/0003_remove_sqldefaultconsumption_couch_id.py
  corehq/apps/consumption/migrations/0004_rename_sqldefaultconsumption.py
  corehq/apps/consumption/models.py
  corehq/apps/consumption/shortcuts.py
  corehq/apps/consumption/tests.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/couch/dump.py
  corehq/apps/dump_reload/sql/dump.py
Labels: product/invisible

#27401 use dateutil parser to get datetime
  custom/icds_reports/reports/fact_sheets.py
  custom/icds_reports/utils/__init__.py
Labels: product/invisible

#27402 PR feedback for reentrant redis locks
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/tests/locks.py
  corehq/tests/noseplugins/redislocks.py
  corehq/tests/test_locks.py
Labels: product/invisible

#27291 Require read rather than edit permissions to download bulk users
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#27405 [ci skip] add help link to location safe report builder flag
  corehq/toggles.py
Labels: product/feature-flag

#27411 Revert "Have docker-compose declare zookeeper as a dependency of kafka"
  docker/hq-compose-services.yml
Labels: product/invisible

#27410 use last day for real instead of today
  corehq/apps/reports/tests/test_daterange.py
  corehq/util/dates.py
Labels: product/all-users-all-environments

#27412 Report web-apps/formplayer request failures to datadog & sentry
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
  corehq/apps/cloudcare/static/cloudcare/js/util.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/cloudcare/tests/test_doc_tests.py
  corehq/apps/cloudcare/urls.py
  corehq/apps/cloudcare/views.py
  corehq/ex-submodules/dimagi/utils/logging.py
Labels: product/invisible

#27413 Web Apps: block submit while validation in progress
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/webformsession_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer-inline.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: QA Passed, product/all-users-all-environments

#27418 set soft time limit much higher than default
  corehq/messaging/tasks.py
Labels: product/invisible

#27404 Ce/fact sheet dates
  custom/icds_reports/static/js/directives/cas-export/cas-export.directive.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/cas-export.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
  custom/icds_reports/ucr/data_sources/ccs_record_cases.json
  custom/icds_reports/ucr/data_sources/child_health_cases.json
  custom/icds_reports/ucr/data_sources/dashboard/child_tasks.json
  custom/icds_reports/ucr/data_sources/dashboard/pregnant_tasks.json
  custom/icds_reports/ucr/data_sources/household_cases.json
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
Labels: product/invisible

#27420 Updated README.md [ci skip]
  corehq/apps/app_manager/README.md
Labels: product/invisible

#27414 [ICDS Dashboard]: Convert month(date) to string
  custom/icds/forms.py
Labels: product/custom, product/invisible

#27394 Fix Prometheus consistent tags issue
  corehq/apps/userreports/tasks.py
Labels: product/invisible

#27421 Extend visibility of volatility warning based on user feedback
  corehq/apps/cloudcare/static/cloudcare/js/util.js
Labels: product/feature-flag

#27426 Fixed 'Submitted by' label to show non-domain users
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#27427 Enable action.auto_create_index in docker ES
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
  docker/files/elasticsearch.yml
Labels: product/invisible

#27417 Location Reassignment: Improvements to checks for site codes
  corehq/apps/locations/forms.py
  corehq/apps/locations/util.py
  custom/icds/location_reassignment/parser.py
  custom/icds/location_reassignment/tests/test_parser.py
Labels: product/feature-flag

#27231 Keep only last two months table
  custom/icds_reports/utils/aggregation_helpers/distributed/bihar_api_demographics.py
Labels: product/custom

#27374 Handle None
  corehq/apps/userreports/tasks.py
Labels: product/invisible

#27434 Location reassignment update check for parents
  custom/icds/location_reassignment/models.py
  custom/icds/location_reassignment/parser.py
Labels: product/feature-flag

#27422 Refer case repeater
  corehq/motech/repeaters/const.py
  corehq/motech/repeaters/exceptions.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/signals.py
  corehq/motech/urls.py
  corehq/toggles.py
Labels: product/custom

#27431 [ICDS Dashboard]: Style Fixes in the Child Growth Tracker Report
  custom/icds_reports/sqldata/exports/growth_tracker_report.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#27435 Location reassignment fix descendants check
  custom/icds/location_reassignment/parser.py
Labels: product/feature-flag

#27357 Location reassignment add view for state users
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bulk_upload.html
  corehq/tabs/tabclasses.py
  corehq/toggles.py
  custom/icds/location_reassignment/views.py
  custom/icds/urls.py
Labels: product/feature-flag

#27438 Location reassignment: allow and ignore extra
  custom/icds/location_reassignment/const.py
  custom/icds/location_reassignment/download.py
  custom/icds/location_reassignment/parser.py
  custom/icds/location_reassignment/views.py
Labels: product/feature-flag

#27425 Removed modified_on filter and AG out of school report
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
  custom/icds_reports/ucr/reports/ls/ls_v2_ag_out_of_school.json
Labels: product/custom

#27355 Use filters saved in daily saved exports to send incremental exports
  corehq/apps/export/forms.py
  corehq/apps/export/tasks.py
  corehq/apps/export/tests/test_incremental.py
Labels: product/invisible

#27416 update list to be comma separated string instead
  custom/icds/location_reassignment/models.py
  custom/icds/location_reassignment/tests/test_models.py
Labels: product/feature-flag

#27324 ICDS Dashboard: Location reassignment changes for mobile dashboard
  custom/icds_reports/static/icds_reports/js/spec/location-filter.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/program-summary.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/utils.js
  custom/icds_reports/static/js/directives/adhaar-beneficiary/adhaar-beneficiary.directive.js
  custom/icds_reports/static/js/directives/adolescent-girls/adolescent-girls.directive.js
  custom/icds_reports/static/js/directives/adult-weight-scale/adult-weight-scale.directive.js
  custom/icds_reports/static/js/directives/awc-daily-status/awc-daily-status.directive.js
  custom/icds_reports/static/js/directives/awcs-covered/awcs-covered.directive.js
  custom/icds_reports/static/js/directives/children-initiated/children-initiated.directive.js
  custom/icds_reports/static/js/directives/clean-water/clean-water.directive.js
  custom/icds_reports/static/js/directives/early_initiation_breastfeeding/early_initiation_breastfeeding.directive.js
  custom/icds_reports/static/js/directives/enrolled-children/enrolled-children.directive.js
  custom/icds_reports/static/js/directives/enrolled-women/enrolled-women.directive.js
  custom/icds_reports/static/js/directives/exclusive-breastfeeding/exlusive-breastfeeding.directive.js
  custom/icds_reports/static/js/directives/functional-toilet/functional-toilet.directive.js
  custom/icds_reports/static/js/directives/immunization_coverage/immunization_coverage.directive.js
  custom/icds_reports/static/js/directives/infantometer/infantometer.directive.js
  custom/icds_reports/static/js/directives/infants-weight-scale/infants-weight-scale.directive.js
  custom/icds_reports/static/js/directives/institutional-deliveries/institutional-deliveries.directive.js
  custom/icds_reports/static/js/directives/lactating-enrolled-women/lactating-enrolled-women.directive.js
  custom/icds_reports/static/js/directives/location-filter/location-filter.directive.js
  custom/icds_reports/static/js/directives/medicine-kit/medicine-kit.directive.js
  custom/icds_reports/static/js/directives/newborn_with_low_weight/newborn_with_low_weight.directive.js
  custom/icds_reports/static/js/directives/program-summary/program-summary.directive.js
  custom/icds_reports/static/js/directives/progress-report/progress-report.directive.js
  custom/icds_reports/static/js/directives/reassignment-message/reassignment-message.directive.js
  custom/icds_reports/static/js/directives/registered-household/registered-household.directive.js
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
  custom/icds_reports/static/js/directives/stadiometer/stadiometer.directive.js
  custom/icds_reports/static/js/directives/underweight-children-report/underweight-children-report.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/location_filter.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/program-summary.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/progress-report.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/reassignment-message.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/service-delivery-dashboard.html
Labels: product/custom

#27409 ICDS Dashboard: select all filter option for Child Growth Monitoring Tabular Report
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
Labels: product/custom

#27177 Address De-Id OData QA Feedback (Mostly Permissions Issues)
  corehq/apps/api/odata/tests/test_feed.py
  corehq/apps/api/odata/tests/test_metadata.py
  corehq/apps/api/odata/tests/test_service.py
  corehq/apps/api/odata/tests/utils.py
  corehq/apps/api/odata/views.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/export/templates/export/partials/new_customize_export_templates.html
  corehq/apps/export/views/list.py
  corehq/apps/export/views/utils.py
  corehq/apps/users/permissions.py
  corehq/tabs/tabclasses.py
Labels: awaiting QA, product/all-users-all-environments, product/feature-flag

#27441 update deprecates
  custom/icds_reports/reports/fact_sheets.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/awc_location.py
Labels: product/invisible

#27400 Small updates to invoice email soft asserts
  corehq/apps/accounting/models.py
Labels: product/invisible

#27354 [ICDS Dashboard]: Multiple fixes in the Django mgt command django_usage_report
  custom/icds_reports/management/commands/dashboard_usage_report.py
Labels: product/custom

#27430 Allow End-User Lock Eviction
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/layout/views/settings.js
  corehq/apps/cloudcare/static/cloudcare/js/util.js
  corehq/apps/cloudcare/templates/formplayer/settings_view.html
Labels: product/all-users-all-environments

#27440 Code generation for couch to sql migration
  corehq/apps/cleanup/management/commands/evaluate_couch_model_for_sql.py
  docs/couch_to_sql_models.rst
Labels: product/invisible

#27437 Add archived on to json
  corehq/apps/locations/models.py
  corehq/apps/locations/tests/test_locations.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: product/invisible

#27454 support sending account confirmation emails from bulk upload
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/user_importer/validation.py
Labels: product/feature-flag

#27334 Exclude not launched locations from map and charts
  custom/icds_reports/reports/children_initiated_data.py
  custom/icds_reports/reports/early_initiation_breastfeeding.py
  custom/icds_reports/reports/enrolled_children.py
  custom/icds_reports/reports/enrolled_women.py
  custom/icds_reports/reports/exclusive_breastfeeding.py
  custom/icds_reports/reports/immunization_coverage_data.py
  custom/icds_reports/reports/institutional_deliveries_sector.py
  custom/icds_reports/reports/lactating_enrolled_women.py
  custom/icds_reports/reports/new_born_with_low_weight.py
  custom/icds_reports/reports/prevalence_of_severe.py
  custom/icds_reports/reports/prevalence_of_stunting.py
  custom/icds_reports/reports/prevalence_of_undernutrition.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/views.py
Labels: product/custom

#27456 remove update_usercase
  custom/icds/location_reassignment/models.py
  custom/icds/location_reassignment/tasks.py
  custom/icds/location_reassignment/tests/test_models.py
Labels: product/feature-flag

#27373 remove duplicate "edition" on confirm subscription page
  corehq/apps/accounting/templates/accounting/partials/confirm_plan_summary.html
Labels: product/prod-india-all-users

#27445 Send DHIS2 aggregated data weekly
  corehq/motech/dhis2/const.py
  corehq/motech/dhis2/models.py
  corehq/motech/dhis2/static/dhis2/js/dhis2_map_settings.js
  corehq/motech/dhis2/templates/dhis2/partials/dhis2_dataset_map_templates.html
  corehq/motech/dhis2/tests/test_datasetmap.py
Labels: product/feature-flag

#27460 Mk/location reassignment add blank sheet
  custom/icds/location_reassignment/const.py
  custom/icds/location_reassignment/download.py
Labels: product/feature-flag

#27457 better messages for unexpected parents
  custom/icds/location_reassignment/parser.py
  custom/icds/location_reassignment/tests/test_parser.py
Labels: product/feature-flag

#27461 ensure no mismatch in household cases
  custom/icds/location_reassignment/parser.py
Labels: product/feature-flag

#27448 Release De-ID'd OData Feeds
  corehq/apps/export/views/new.py
  corehq/toggles.py
Labels: product/invisible

#27458 Update DEV_SETUP.md
  DEV_SETUP.md
Labels: product/invisible

#27451 Add separate sms metrics
  corehq/apps/sms/api.py
Labels: product/invisible

#27419 Add more info to Formplayer browser error reports
  corehq/apps/cloudcare/static/cloudcare/js/util.js
  corehq/apps/cloudcare/views.py
Labels: product/invisible

#27424 Add username consistently to sentry reports
  corehq/middleware.py
Labels: product/invisible

#27459 Remove unnecessary deepcopy
  corehq/apps/callcenter/data_source.py
Labels: product/invisible

#27462 Fix user.username sentry tag
  corehq/middleware.py
Labels: product/invisible

#27450 limit login as to specified users
  corehq/apps/cloudcare/esaccessors.py
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/toggles.py
Labels: product/custom

#27463 pull return out of loop and open case
  corehq/motech/repeaters/repeater_generators.py
Labels: product/custom

#27466 ICDS Dashboard: Changing y/n to yes/no in awc reports
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/tests/agg_tests/reports/test_awc_reports.py
Labels: product/custom

#27464 ICDS Dashboard: Removing Feature flag for mobile
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/navigation.directive.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
Labels: product/custom

#27452 [ICDS Dashboard]: Added fields in Person Case UCRs for Bihar API Modifications
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
Labels: product/custom

#27469 mark view location safe
  custom/icds/location_reassignment/views.py
Labels: product/feature-flag

#27472 Added risk assessment to PR template [ci skip]
  .github/PULL_REQUEST_TEMPLATE.md
Labels: product/invisible

#27467 Location reassignment name format changes
  custom/icds/location_reassignment/const.py
  custom/icds/location_reassignment/download.py
  custom/icds/location_reassignment/parser.py
  custom/icds/location_reassignment/tests/test_parser.py
  custom/icds/location_reassignment/utils.py
Labels: product/feature-flag

#27429 Dump and reload ZapierSubscription model
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#27473 Location reassignment fix households
  custom/icds/location_reassignment/download.py
  custom/icds/location_reassignment/tasks.py
  custom/icds/location_reassignment/tests/test_download.py
  custom/icds/location_reassignment/tests/test_dumper.py
  custom/icds/location_reassignment/tests/utils.py
  custom/icds/location_reassignment/views.py
Labels: product/feature-flag

#27475 Disable django compress in tests
  corehq/apps/hqwebapp/templatetags/tests/test_tag.py
  settings.py
Labels: product/invisible

#27455 Location reassignment reassign all cases
  custom/icds/location_reassignment/download.py
  custom/icds/location_reassignment/models.py
  custom/icds/location_reassignment/processor.py
  custom/icds/location_reassignment/tasks.py
  custom/icds/location_reassignment/tests/test_download.py
  custom/icds/location_reassignment/tests/test_dumper.py
  custom/icds/location_reassignment/tests/test_processors.py
  custom/icds/location_reassignment/tests/utils.py
  custom/icds/location_reassignment/utils.py
  custom/icds/location_reassignment/views.py
Labels: product/feature-flag

#27476 Add profiling decorator/context manager
  corehq/apps/app_manager/management/commands/benchmark_build_times.py
  corehq/apps/app_manager/management/commands/benchmark_direct_ccz.py
  corehq/apps/ota/views.py
  corehq/apps/receiverwrapper/views.py
  corehq/ex-submodules/dimagi/utils/__init__.py
  corehq/ex-submodules/dimagi/utils/decorators/profile.py
  corehq/ex-submodules/dimagi/utils/tests/test_decorators.py
  docs/profiling.rst
Labels: product/invisible

#27480 Mk/location reassignment reassign all cases 2
  custom/icds/location_reassignment/const.py
  custom/icds/location_reassignment/download.py
  custom/icds/location_reassignment/forms.py
  custom/icds/location_reassignment/parser.py
  custom/icds/location_reassignment/processor.py
  custom/icds/location_reassignment/tasks.py
  custom/icds/location_reassignment/utils.py
  custom/icds/location_reassignment/views.py
  custom/icds/static/icds/js/location_reassignment.js
Labels: product/feature-flag

#27482 utc js
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/directives/cas-export/cas-export.directive.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/static/js/directives/lady-supervisor/lady-supervisor.directive.js
  custom/icds_reports/static/js/directives/location-filter/location-filter.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/reassignment-message.html
  custom/icds_reports/templates/icds_reports/icds_app/reassignment-message.html
  custom/icds_reports/tests/test_views_location_filter.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/views.py
Labels: product/feature-flag

#27477 Faster pillow tests
  testapps/test_pillowtop/tests/base.py
  testapps/test_pillowtop/tests/test_report_case_pillow.py
  testapps/test_pillowtop/tests/test_user_pillow.py
Labels: product/invisible

#27471 [ICDS Dashboard] fix the state location level index
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#27479 Removed one step of ICDS's app copy management commands
  custom/icds/management/commands/copy_icds_app.py
  custom/icds/management/commands/copy_icds_app_2_of_2.py
Labels: product/invisible

#27478 Removed MULTI_MASTER_BYPASS_VERSION_CHECK feature flag
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/forms.py
  corehq/toggles.py
Labels: product/feature-flag

#27486 only override COMPRESS_PRECOMPILERS in tests
  settings.py
Labels: product/invisible

#26687 Migrate Invitation to SQL (3 of 3)
  corehq/apps/cachehq/cachemodels.py
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/domain/views/base.py
  corehq/apps/users/_design/views/open_invitations_by_email/map.js
  corehq/apps/users/_design/views/open_invitations_by_email/reduce.js
  corehq/apps/users/management/commands/populate_usersinvitation.py
  corehq/apps/users/migrations/0013_remove_sqlinvitation_ids.py
  corehq/apps/users/migrations/0014_rename_usersinvitation.py
  corehq/apps/users/models.py
  corehq/apps/users/tasks.py
  corehq/apps/users/tests/test_models.py
  corehq/apps/users/views/__init__.py
  settings.py
Labels: product/invisible

#27481 [ICDS Dashboard]: Added fields in bp and pnc form ucr for bihar api
  custom/icds_reports/ucr/data_sources/dashboard/birth_preparedness_forms.json
  custom/icds_reports/ucr/data_sources/dashboard/postnatal_care_forms.json
  custom/icds_reports/ucr/tests/test_birth_preparedness_form_ucr.py
  custom/icds_reports/ucr/tests/test_pnc_form_ucr.py
Labels: product/custom, product/invisible

#27488 archived_on is column not metadata
  custom/icds_reports/views.py
Labels: product/invisible

#27465 Ce/limit login as
  corehq/apps/cloudcare/esaccessors.py
  corehq/apps/cloudcare/tests/test_esaccessors.py
  corehq/apps/cloudcare/views.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/users/decorators.py
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/toggles.py
Labels: product/custom

#27439 Added ordering to HqDeploy
  corehq/apps/hqadmin/migrations/0016_hqdeploy_ordering.py
  corehq/apps/hqadmin/models.py
  corehq/apps/hqadmin/views/system.py
Labels: product/invisible

#27487 Added help text for gateway settings domain list
  corehq/apps/sms/forms.py
Labels: product/all-users-all-environments

#27490 Cherry picks from enterprise linked domains
  corehq/apps/domain/models.py
  corehq/apps/domain/templates/domain/select.html
  corehq/apps/domain/views/base.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/settings/views.py
  corehq/apps/users/models.py
Labels: product/all-users-all-environments

#27489 Allow contractors to manage messaging gateways
  corehq/apps/sms/forms.py
  corehq/apps/sms/views.py
Labels: product/invisible

#27493 Added access_api permission
  corehq/apps/api/resources/auth.py
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/partials/edit_role_modal.html
Labels: product/all-users-all-environments

#27492 Ce/api ip whitelist
  corehq/apps/domain/decorators.py
  corehq/apps/hqwebapp/admin.py
  corehq/apps/hqwebapp/migrations/0004_apikeysettings.py
  corehq/apps/hqwebapp/models.py
Labels: product/invisible

#27494 return date string for archived_on
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/views.py
Labels: product/invisible

#27500 fix bad reference to "closed" property in case schemas
  corehq/apps/export/det/schema_generator.py
Labels: product/feature-flag

#27502 Revert "Removed MULTI_MASTER_BYPASS_VERSION_CHECK feature flag"
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/forms.py
  corehq/toggles.py
Labels: product/feature-flag

#27501 Revert "Removed one step of ICDS's app copy management commands"
  custom/icds/management/commands/copy_icds_app_1_of_2.py
  custom/icds/management/commands/copy_icds_app_2_of_2.py
Labels: product/invisible

#27498 Location reassignment skip worker case
  custom/icds/location_reassignment/const.py
  custom/icds/location_reassignment/download.py
  custom/icds/location_reassignment/utils.py
Labels: product/feature-flag

#27499 add passed filename name into attached file
  custom/icds/location_reassignment/tasks.py
Labels: product/feature-flag

#27447 Use UTC dates to filter exports
  corehq/apps/export/views/incremental.py
Labels: product/feature-flag

#27446 Reset Incremental Export checkpoints
  corehq/apps/export/forms.py
  corehq/apps/export/models/incremental.py
  corehq/apps/export/static/export/js/incremental_export.js
  corehq/apps/export/tasks.py
  corehq/apps/export/templates/export/incremental_export.html
  corehq/apps/export/tests/test_incremental.py
  corehq/apps/export/urls.py
  corehq/apps/export/utils.py
  corehq/apps/export/views/incremental.py
  corehq/apps/hqwebapp/static/hqwebapp/js/crud_paginated_list.js
  corehq/apps/hqwebapp/static/hqwebapp/js/crud_paginated_list_init.js
  corehq/apps/hqwebapp/templates/hqwebapp/base_paginated_crud.html
  corehq/apps/hqwebapp/views.py
  docs/ui_helpers.rst
Labels: product/feature-flag

#27503 sw/update-report-date-formats
  custom/icds_reports/ucr/reports/ls/ls_v2_report_child_names.json
  custom/icds_reports/ucr/reports/ls/ls_v2_report_child_nutrition_status.json
  custom/icds_reports/ucr/reports/ls/ls_v2_report_lbw_pre_term.json
  custom/icds_reports/ucr/reports/ls/ls_v2_report_pregnant_women_names.json
Labels: product/custom

#27505 Do no count null as 32767, count it as 0
  custom/icds_reports/utils/aggregation_helpers/distributed/thr_forms_child_health.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/thr-forms-child-health.distributed.txt
Labels: product/custom

#27509 automatically log in users with one valid mobile worker
  corehq/apps/cloudcare/views.py
Labels: product/feature-flag

#27510 Mirrored domain-level permissions
  corehq/apps/domain/decorators.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/templates/domain/select.html
  corehq/apps/domain/views/base.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/hqwebapp/templates/hqwebapp/includes/domain_list_dropdown.html
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/users/admin.py
  corehq/apps/users/migrations/0015_domainpermissionsmirror.py
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/domain_permissions_mirror.html
  corehq/apps/users/tests/test_mirroring.py
  corehq/apps/users/urls.py
  corehq/apps/users/views/__init__.py
  corehq/middleware.py
  corehq/tabs/tabclasses.py
  corehq/util/context_processors.py
Labels: product/feature-flag

#27511 DRYed up implemenations of CRUDPaginatedViewMixin.parameters
  corehq/apps/accounting/views.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/domain/views/accounting.py
  corehq/apps/export/views/incremental.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/reminders/views.py
  corehq/apps/sms/views.py
  docs/ui_helpers.rst
Labels: product/invisible

#27497 Mk/location reassignment validate new code type
  custom/icds/location_reassignment/parser.py
  custom/icds/location_reassignment/tests/test_parser.py
Labels: product/feature-flag

#27495 Mobile Endpoint Access Permissions
  corehq/apps/ota/decorators.py
  corehq/apps/ota/views.py
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/toggles.py
Labels: product/feature-flag

#27496 More about contractors and messaging
  corehq/apps/sms/forms.py
  corehq/apps/sms/templates/sms/gateway_list.html
  corehq/apps/sms/tests/test_util.py
  corehq/apps/sms/tests/test_views.py
  corehq/apps/sms/util.py
  corehq/apps/sms/views.py
Labels: product/feature-flag

#27442 [ICDS Dashboard]: Bihar API Mother modifications
  custom/icds_reports/migrations/0188_rebuild_view_bihar_api.py
  custom/icds_reports/migrations/sql_templates/database_views/bihar_api_mother_view.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/reports/bihar_api.py
  custom/icds_reports/tests/agg_tests/fixtures/pregnant_tasks.csv
  custom/icds_reports/tests/agg_tests/outputs/ccs_record_monthly-st1-2017-05-01.csv
  custom/icds_reports/tests/agg_tests/outputs/ccs_record_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/ccs_record_monthly_2017-05-01_sorted.csv
  custom/icds_reports/tests/agg_tests/reports/test_bihar_api_mother_details.py
Labels: product/custom
