Repository dimagi/commcare-hq, pull requests merged in 2020-03, with the labels that each got.

#26720 build migration table
  custom/icds_reports/utils/build_migration_table.py
Labels: Open for review: do not merge

#26668 [ICDS Dashboard] key error awc_id issue fix
  custom/icds_reports/views.py
Labels: product/custom

#26750 Fixes #26749
  corehq/motech/repeaters/views/tests/test_repeat_records.py
Labels: product/invisible

#26754 [ci skip] add note about docker data volumes
  docker/README.md
Labels: product/invisible

#26685 Migrate Invitation to SQL (1 of 3)
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/users/management/commands/populate_usersinvitation.py
  corehq/apps/users/migrations/0009_sqlinvitation.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_models.py
Labels: QA Passed, product/invisible

#26757 Properly ignore pillow errors trying to delete a deleted doc from ES
  corehq/ex-submodules/pillowtop/utils.py
Labels: product/invisible

#26747 Add new USE_KAFKA_SHORTEST_BACKLOG_PARTITIONER option
  corehq/apps/change_feed/partitioners.py
  corehq/apps/change_feed/producer.py
  settings.py
Labels: product/invisible

#26759 Ignore errors finding the partition with the shortest backlog
  corehq/apps/change_feed/partitioners.py
Labels: product/invisible

#26746 Updated dummy classes to not inherit from Document
  corehq/apps/cleanup/models.py
  corehq/apps/hqcase/models.py
  custom/apps/crs_reports/models.py
  custom/succeed/models.py
Labels: product/invisible

#26758 Improve couch to sql migration instructions
  corehq/apps/api/management/commands/populate_apiuser.py
  corehq/apps/app_manager/management/commands/populate_sql_global_app_config.py
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/cloudcare/management/commands/populate_application_access.py
  corehq/apps/consumption/management/commands/populate_defaultconsumption.py
  corehq/apps/hqadmin/management/commands/populate_sql_hq_deploy.py
  corehq/apps/registration/management/commands/populate_sql_registration_request.py
  corehq/apps/users/management/commands/populate_usersinvitation.py
  corehq/motech/dhis2/management/commands/populate_sql_dhis2_connection.py
  docs/couch_to_sql_models.rst
Labels: product/invisible

#26760 Add clarifying note to pillows.rst about partitions and processes
  docs/pillows.rst
Labels: product/invisible

#26756 fix error during reprocessing caused by missing form xml
  corehq/apps/commtrack/processing.py
  corehq/form_processor/parsers/ledgers/__init__.py
  corehq/form_processor/parsers/ledgers/form.py
  corehq/form_processor/tests/test_reprocess_errors.py
Labels: product/invisible

#26762 ICDS Dashboard: Service delivery dashboard initial changes
  custom/icds_reports/const.py
  custom/icds_reports/dashboard_utils.py
  custom/icds_reports/static/icds_reports/mobile/images/babyboy.png
  custom/icds_reports/static/icds_reports/mobile/images/info-white.png
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/navigation.directive.html
  custom/icds_reports/templates/icds_reports/partials/dashboard_initial_page_data.html
  custom/icds_reports/templates/icds_reports/partials/shared_report_directives.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
Labels: product/custom

#26763 Update to add sort block
  corehq/apps/app_manager/suite_xml/features/mobile_ucr.py
  corehq/apps/app_manager/tests/test_report_config.py
Labels: product/feature-flag

#26686 Migrate Invitation to SQL (2 of 3)
  corehq/apps/domain/dbaccessors.py
  corehq/apps/domain/templates/domain/select.html
  corehq/apps/domain/views/base.py
  corehq/apps/users/migrations/0010_populate_usersinvitation.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/web_users.js
  corehq/apps/users/tasks.py
  corehq/apps/users/templates/users/web_users.html
  corehq/apps/users/tests/test_models.py
  corehq/apps/users/views/__init__.py
Labels: QA Passed, product/invisible

#26504 Bulk app translation format fixes
  corehq/apps/app_manager/templates/app_manager/partials/bulk_upload_app_translations.html
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/app_translations/upload_app.py
  corehq/apps/translations/app_translations/utils.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/apps/translations/validator.py
  corehq/apps/translations/views.py
  corehq/apps/userreports/tasks.py
Labels: QA Passed, product/feature-flag

#26761 Remove hard request timeout on kafka consumer
  corehq/apps/change_feed/connection.py
Labels: product/invisible

#26767 Fixed typo in UCR docs
  corehq/apps/userreports/README.rst
Labels: product/invisible

#26713 ICDS Dashboard: add mobile dashboard auditing
  custom/icds_reports/middleware.py
  custom/icds_reports/tests/test_audit_data.py
Labels: product/custom

#26738 Late PMT 2020
  custom/abt/reports/__init__.py
  custom/abt/reports/filters.py
  custom/abt/reports/filters_2020.py
  custom/abt/reports/fixture_utils.py
  custom/abt/reports/late_pmt.py
  custom/abt/reports/late_pmt_2020.py
  custom/abt/reports/tests/__init__.py
  custom/abt/reports/tests/test_fixture_utils.py
  custom/abt/reports/tests/test_late_pmt_2020.py
Labels: product/custom

#26773 Exception messages
  corehq/apps/change_feed/consumer/feed.py
  corehq/apps/users/models.py
  corehq/ex-submodules/pillowtop/feed/couch.py
  corehq/ex-submodules/pillowtop/feed/interface.py
Labels: product/invisible

#26766 Removed unused consumption code
  corehq/apps/consumption/shortcuts.py
  corehq/apps/consumption/tests.py
Labels: product/invisible

#26776 Change timeend to datetime
  custom/icds_reports/ucr/data_sources/dashboard/migrations_form.json
Labels: product/custom

#26775 ucr user "name" transform
  corehq/apps/userreports/README.rst
  corehq/apps/userreports/transforms/custom/users.py
  corehq/apps/userreports/transforms/specs.py
  corehq/apps/users/tests/test_util.py
  corehq/apps/users/util.py
Labels: product/feature-flag

#26765 ICDS Dashboard: Service Delivery Dashboard Mobile UI
  custom/icds_reports/static/icds_reports/js/spec/month-filter.directive.spec.js
  custom/icds_reports/static/icds_reports/mobile/css/app.less
  custom/icds_reports/static/icds_reports/mobile/css/filters.less
  custom/icds_reports/static/icds_reports/mobile/css/variables.less
  custom/icds_reports/static/js/directives/mobile-filters/mobile-filters.directive.js
  custom/icds_reports/static/js/directives/month-filter/month-filter.directive.js
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
  custom/icds_reports/static/js/directives/sortable-kpi/sortable-kpi.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/mobile-filters.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/month-filter.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/service-delivery-dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/sortable-kpi.directive.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
Labels: product/custom

#26769 OData - fix 500 issue on edge case feed
  corehq/apps/export/views/new.py
Labels: product/all-users-all-environments, product/invisible

#26774 [ci skip] UCR doc tweaks
  corehq/apps/userreports/README.rst
  docs/ucr/examples.md
Labels: product/feature-flag

#26782 [ci skip] clarify docs a bit
  corehq/apps/userreports/README.rst
Labels: product/invisible

#26779 Upgarde to celery 4.4.0
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#26784 properly add navigation to SDD for feature-flagged users
  custom/icds_reports/templates/icds_reports/icds_app/mobile/navigation.directive.html
Labels: product/custom

#26783 [ci skip] update mobile apk file
  custom/icds_reports/static/media/cas-mobile-dashboard.apk
  custom/icds_reports/templates/icds_reports/mobile_dashboard_download.html
Labels: product/custom

#26780 Ran eslint --fix on ICDS dashboard
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/angular-services/demographics.service.js
  custom/icds_reports/static/js/angular-services/download.service.js
  custom/icds_reports/static/js/angular-services/icds-cas-reach.service.js
  custom/icds_reports/static/js/angular-services/infrastructure.service.js
  custom/icds_reports/static/js/angular-services/locations.service.js
  custom/icds_reports/static/js/angular-services/maternal-child.service.js
  custom/icds_reports/static/js/angular-services/navigation.service.js
  custom/icds_reports/static/js/angular-services/progress-report.service.js
  custom/icds_reports/static/js/angular-services/storage.service.js
  custom/icds_reports/static/js/angular-services/system-usage.service.js
  custom/icds_reports/static/js/angular-services/template-provider.service.js
  custom/icds_reports/static/js/directives/additional-filter/additional-filter.directive.js
  custom/icds_reports/static/js/directives/adhaar-beneficiary/adhaar-beneficiary.directive.js
  custom/icds_reports/static/js/directives/adult-weight-scale/adult-weight-scale.directive.js
  custom/icds_reports/static/js/directives/awc-daily-status/awc-daily-status.directive.js
  custom/icds_reports/static/js/directives/awc-opened-yesterday/awc-opened-yesterday.directive.js
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/static/js/directives/awcs-covered/awcs-covered.directive.js
  custom/icds_reports/static/js/directives/children-initiated/children-initiated.directive.js
  custom/icds_reports/static/js/directives/clean-water/clean-water.directive.js
  custom/icds_reports/static/js/directives/dot-link/dot-link.directive.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/static/js/directives/early_initiation_breastfeeding/early_initiation_breastfeeding.directive.js
  custom/icds_reports/static/js/directives/enrolled-children/enrolled-children.directive.js
  custom/icds_reports/static/js/directives/enrolled-women/enrolled-women.directive.js
  custom/icds_reports/static/js/directives/exclusive-breastfeeding/exlusive-breastfeeding.directive.js
  custom/icds_reports/static/js/directives/filters/filters.directive.js
  custom/icds_reports/static/js/directives/functional-toilet/functional-toilet.directive.js
  custom/icds_reports/static/js/directives/immunization_coverage/immunization_coverage.directive.js
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/static/js/directives/infantometer/infantometer.directive.js
  custom/icds_reports/static/js/directives/infants-weight-scale/infants-weight-scale.directive.js
  custom/icds_reports/static/js/directives/info-message/info-message.directive.js
  custom/icds_reports/static/js/directives/institutional-deliveries/institutional-deliveries.directive.js
  custom/icds_reports/static/js/directives/kpi/kpi.directive.js
  custom/icds_reports/static/js/directives/lactating-enrolled-women/lactating-enrolled-women.directive.js
  custom/icds_reports/static/js/directives/location-filter/location-filter.directive.js
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
  custom/icds_reports/static/js/directives/medicine-kit/medicine-kit.directive.js
  custom/icds_reports/static/js/directives/month-filter/month-filter.directive.js
  custom/icds_reports/static/js/directives/navigation/navigation.directive.js
  custom/icds_reports/static/js/directives/newborn_with_low_weight/newborn_with_low_weight.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-severe-report/prevalence-of-severe-report.directive.js
  custom/icds_reports/static/js/directives/prevalence-of-stunting-report/prevalence-of-stunting-report.directive.js
  custom/icds_reports/static/js/directives/print/print.directive.js
  custom/icds_reports/static/js/directives/program-summary/program-summary.directive.js
  custom/icds_reports/static/js/directives/progress-report/progress-report.directive.js
  custom/icds_reports/static/js/directives/registered-household/registered-household.directive.js
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
  custom/icds_reports/static/js/directives/stadiometer/stadiometer.directive.js
  custom/icds_reports/static/js/directives/underweight-children-report/underweight-children-report.directive.js
  custom/icds_reports/static/js/filters/india-numbers/india-numbers.filter.js
  custom/icds_reports/static/js/filters/property-filter/property.filter.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
Labels: product/invisible

#26777 Improvements to populate sql script
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/cloudcare/management/commands/populate_application_access.py
Labels: product/invisible

#26791 Added sum when templates for ccs_phase
  corehq/apps/userreports/reports/factory.py
  corehq/apps/userreports/reports/sum_when_templates.py
Labels: product/invisible

#26770 [Icds Dashboard] make sdr available starting from 2020
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#26785 Late PMT report: Do not show deleted users
  custom/abt/reports/data_sources/late_pmt.json
Labels: product/custom

#26752 Pull out awc_location step as a separate step
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/__init__.py
Labels: product/custom

#26798 correct mapping
  corehq/apps/userreports/reports/factory.py
Labels: product/invisible

#26797 change function declaration eslint rule to "first"
  .eslintrc.js
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
Labels: product/invisible

#26768 Couch to SQL: missing forms, cases, and ledgers
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/missingdocs.py
  corehq/apps/couch_sql_migration/rebuildcase.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/form_processor/backends/sql/processor.py
  corehq/form_processor/tests/test_sql_update_strategy.py
Labels: product/invisible

#26557 Migrate RegistrationRequest to SQL (3 of 4)
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/registration/management/commands/populate_sql_registration_request.py
  corehq/apps/registration/migrations/0004_rename_sqlregistrationrequest.py
  corehq/apps/registration/models.py
Labels: product/invisible

#26778 Fix a few Django 2 deprecation warnings
  corehq/apps/app_manager/views/download.py
  corehq/form_processor/models.py
  custom/champ/tests/test_pva_chart.py
  custom/champ/tests/test_pva_table.py
  custom/champ/tests/test_service_uptake.py
  custom/icds_reports/tests/agg_tests/test_views_first_days_of_month.py
  custom/icds_reports/tests/test_views_location_filter.py
  settings.py
Labels: product/invisible

#26795 Added last sync and last submission to mobile user download
  corehq/apps/user_importer/importer.py
  corehq/apps/users/bulk_download.py
Labels: product/all-users-all-environments

#26786 fix the reconcilation script to rebuild cases as well
  custom/icds_reports/tasks.py
Labels: product/custom

#26801 Check base_doc, not is_deleted
  custom/abt/reports/data_sources/late_pmt.json
Labels: product/invisible

#26792 Django 2 compatability
  corehq/apps/app_manager/views/download.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/ex-submodules/couchforms/models.py
  corehq/middleware.py
  corehq/util/django2_shim/__init__.py
  corehq/util/django2_shim/template/__init__.py
  corehq/util/django2_shim/template/base.py
  corehq/util/django2_shim/urls.py
Labels: product/invisible

#26709 Implement performance improvement for exports get_column
  corehq/apps/export/models/new.py
  corehq/toggles.py
Labels: QA Passed, product/all-users-all-environments, product/invisible

#26794 [Userless New Domains] Remove useless logging and add more useful logging
  corehq/apps/domain/views/base.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/registration/utils.py
  corehq/apps/registration/views.py
Labels: product/invisible, product/prod-india-all-users

#26799 [Icds dashboard] mark not null when not toilet
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
Labels: product/custom

#26804 Update django-prbac to support Django 2.2.x
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#26806 Updated migration instructions
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
Labels: product/invisible

#26800 [ICDS Dashboard] changed the 'last month' text to 'current month' in sector and map view for Institutional deliveries and Early Initiation of Breastfeeding and to 'given month' in chart view
  custom/icds_reports/messages.py
  custom/icds_reports/reports/early_initiation_breastfeeding.py
  custom/icds_reports/reports/institutional_deliveries_sector.py
  custom/icds_reports/static/icds_reports/js/spec/early_initiation_breastfeeding.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/institutional-deliveries.directive.spec.js
  custom/icds_reports/static/js/directives/early_initiation_breastfeeding/early_initiation_breastfeeding.directive.js
  custom/icds_reports/static/js/directives/institutional-deliveries/institutional-deliveries.directive.js
  custom/icds_reports/tests/agg_tests/reports/test_early_initiation_breastfeeding.py
  custom/icds_reports/tests/agg_tests/reports/test_institutional_deliveries_sector.py
  custom/icds_reports/tests/agg_tests/reports/test_maternal_child_data.py
Labels: product/custom

#26796 [ICDS Dashbaord]Added check for awc selected in awc reports to avoid unnecessary backend calls
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/awc-reports.html
Labels: product/custom

#26715 Avoid ES aggregation in a util that hits AppES
  corehq/apps/app_manager/dbaccessors.py
  corehq/apps/app_manager/models.py
  corehq/apps/users/views/__init__.py
  corehq/pillows/mappings/app_mapping.json
  corehq/pillows/mappings/app_mapping.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: product/invisible

#26706 [ICDS Dashboard]: Fix the Agg Child Health Helper
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
Labels: product/custom

#26702 Migration StandaloneTranslationDoc to SQL (1 of 3)
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/translations/management/commands/populate_smstranslations.py
  corehq/apps/translations/migrations/0006_add_smstranslations.py
  corehq/apps/translations/models.py
Labels: QA Passed, product/invisible

#26811 make kafka wait for zookeeper
  docker/hq-compose.yml
  docker/run.sh
Labels: product/invisible

#26809 Upgrade django-partial-index to 0.6.0 for Django 2.2 compatibility
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#26808 Upgrade jsonobject-couchdbkit to 1.0.1 for Django 2 compatability
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#26753 put yes/no for cbe and vhnd in SDR
  custom/icds_reports/reports/service_delivery_report.py
Labels: product/custom

#26790 Use separate memoized KafkaConsumer for choose_best_partition_for_topic
  corehq/apps/change_feed/partitioners.py
Labels: product/invisible

#26815 Switched User Org recipients search to use standard location search
  corehq/apps/locations/views.py
  corehq/apps/reports/filters/controllers.py
  corehq/messaging/scheduling/async_handlers.py
  corehq/messaging/scheduling/forms.py
Labels: product/all-users-all-environments

#26818 Fixed AdvancedForm import
  corehq/messaging/scheduling/forms.py
Labels: product/feature-flag

#26820 Force fresh data to fix error creating new domain
  corehq/apps/accounting/subscription_changes.py
Labels: product/invisible

#26823 Fixed alignment of billing modals
  corehq/apps/accounting/forms.py
Labels: product/admin

#26814 Made device_id optional in DeviceLogRequest
  corehq/apps/ota/migrations/0010_alter_devicelogrequest.py
  corehq/apps/ota/models.py
  corehq/ex-submodules/phonelog/utils.py
Labels: product/invisible

#26812 [ICDS Dashboard] THR report is available before 2019 fix
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#26822 Bulk lookup for mobile users
  corehq/apps/users/static/users/js/bulk_lookup.js
  corehq/apps/users/templates/users/bulk_lookup.html
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/urls.py
  corehq/apps/users/views/mobile/users.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/feature-flag

#26817 Removed rule run for bulk content changes
  corehq/messaging/scheduling/tests/test_bulk_conditional_alerts.py
  corehq/messaging/scheduling/view_helpers.py
Labels: product/all-users-all-environments

#26703 Migration StandaloneTranslationDoc to SQL (2 of 3)
  corehq/apps/sms/messages.py
  corehq/apps/sms/util.py
  corehq/apps/sms/views.py
  corehq/apps/translations/migrations/0006_add_smstranslations.py
  corehq/apps/translations/migrations/0007_populate_smstranslations.py
  corehq/apps/translations/models.py
  corehq/apps/users/views/__init__.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/tests/test_content.py
Labels: QA Passed, product/invisible

#26550 [ICDS Dashboard] updated the migration_status in child_health_monthly
  custom/icds_reports/tests/agg_tests/agg_setup.py
  custom/icds_reports/tests/agg_tests/fixtures/migration_form.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
Labels: product/custom

#26825 Late PMT: Filter out locations named "Other"
  custom/abt/reports/filters_2020.py
  custom/abt/reports/fixture_utils.py
  custom/abt/reports/tests/test_fixture_utils.py
Labels: product/custom

#26736 [ICDS Dashboard] Use Migration table in ccs record monthly table
  custom/icds_reports/tests/agg_tests/fixtures/migration_form.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/ccs_record_monthly.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/ccs-record-monthly.distributed.txt
Labels: product/custom

#26828 Added commit_adding_migration to populate_smstranslations
  corehq/apps/translations/management/commands/populate_smstranslations.py
Labels: product/invisible

#26832 remove high dimensional tags
  corehq/apps/receiverwrapper/views.py
Labels: product/invisible

#26829 Update ES index.max_result_window setting in docker
  docker/files/elasticsearch.yml
Labels: product/invisible

#26831 Make sure invoices check related subscriptions for available credits
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_credit_lines.py
Labels: product/invisible

#26826 Remove clunky retry, which attempted but failed to fix new domain errors
  corehq/apps/accounting/subscription_changes.py
Labels: product/invisible

#26821 [Current Subscription Page] Small Payment Workflow Updates
  corehq/apps/accounting/static/accounting/js/payment_method_handler.js
  corehq/apps/domain/templates/domain/current_subscription.html
Labels: product/prod-india-all-users

#26836 show query for ConfigurableReportCustomDataSource
  corehq/apps/userreports/custom/data_source.py
  custom/icds_reports/reports/ucr.py
Labels: product/invisible

#26835 Use the `other` field
  custom/abt/reports/filters_2020.py
  custom/abt/reports/fixture_utils.py
Labels: product/custom

#26840 Removed DeviceLogRequest.device_id
  corehq/apps/ota/admin.py
  corehq/apps/ota/migrations/0011_remove_devicelogrequest_deviceid.py
  corehq/apps/ota/models.py
  corehq/apps/ota/tests/test_heartbeat.py
  corehq/apps/ota/views.py
  corehq/ex-submodules/phonelog/utils.py
Labels: product/admin

#26838 Added support for linked app visit schedulers to conditional alerts
  corehq/messaging/scheduling/async_handlers.py
  corehq/messaging/scheduling/forms.py
Labels: product/feature-flag

#26841 make sure subscriptions scheduled to end are also paused
  corehq/apps/accounting/tasks.py
Labels: product/invisible, product/prod-india-all-users

#26848 disable national breadcrumb for lower level users
  custom/icds_reports/templates/icds_reports/icds_app/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/lady-supervisor.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/program-summary.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/progress-report.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/service-delivery-dashboard.html
Labels: product/custom

#26849 update location tables in separate command
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/management/commands/update_location_tables.py
Labels: product/custom

#26850 Mini Exchange
  corehq/apps/app_manager/migrations/0014_create_exchangeapplication.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/app_exchange.html
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/apps.py
Labels: product/all-users-all-environments

#26852 Mini Exchange updates
  corehq/apps/app_manager/templates/app_manager/app_exchange.html
  corehq/apps/app_manager/views/apps.py
Labels: product/all-users-all-environments

#26842 Process feeds all the way to the end
  corehq/apps/change_feed/consumer/feed.py
  corehq/apps/change_feed/tests/test_kafka_change_feed.py
  corehq/apps/userreports/tests/test_location_data_source.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_synclog_pillow.py
  corehq/ex-submodules/pillowtop/checkpoints/manager.py
  corehq/ex-submodules/pillowtop/feed/couch.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  testapps/test_pillowtop/tests/test_app_pillow.py
  testapps/test_pillowtop/tests/test_case_search_pillow.py
  testapps/test_pillowtop/tests/test_changes.py
  testapps/test_pillowtop/tests/test_chunk_pillow.py
  testapps/test_pillowtop/tests/test_domain_pillow.py
  testapps/test_pillowtop/tests/test_form_pillow.py
  testapps/test_pillowtop/tests/test_group_pillow.py
  testapps/test_pillowtop/tests/test_grouptouser_pillow.py
  testapps/test_pillowtop/tests/test_sms_pillow.py
  testapps/test_pillowtop/tests/test_user_pillow.py
  testapps/test_pillowtop/utils.py
Labels: product/invisible

#26844 Add "add_hours" UCR expression
  corehq/apps/userreports/README.rst
  corehq/apps/userreports/expressions/date_specs.py
  corehq/apps/userreports/expressions/factory.py
  corehq/apps/userreports/expressions/getters.py
  corehq/apps/userreports/tests/test_date_expressions.py
  corehq/apps/userreports/tests/test_expressions.py
  custom/icds_reports/ucr/tests/test_adolescent_girl_ucr.py
  custom/icds_reports/ucr/tests/test_cbe_form_ucr.py
  custom/icds_reports/ucr/tests/test_gm_form_ucr.py
  custom/icds_reports/ucr/tests/test_ls_usage_ucr.py
  custom/icds_reports/ucr/tests/test_ls_vhnd_form_ucr.py
  custom/icds_reports/ucr/tests/test_migration_form.py
  custom/icds_reports/ucr/tests/test_pnc_form_ucr.py
  custom/icds_reports/ucr/tests/test_private_school_ucr.py
  custom/icds_reports/ucr/tests/test_thr_form_ucr.py
Labels: product/feature-flag

#26843 ICDS Dashboard: Factsheets for mobile dashboard
  custom/icds_reports/dashboard_utils.py
  custom/icds_reports/static/css/fact_sheets.less
  custom/icds_reports/static/icds_reports/js/spec/progress-report.directive.spec.js
  custom/icds_reports/static/icds_reports/mobile/css/app.less
  custom/icds_reports/static/icds_reports/mobile/css/fact-sheets.less
  custom/icds_reports/static/icds_reports/mobile/images/all.png
  custom/icds_reports/static/icds_reports/mobile/images/behavior_change.png
  custom/icds_reports/static/icds_reports/mobile/images/demographics.png
  custom/icds_reports/static/icds_reports/mobile/images/interventions.png
  custom/icds_reports/static/icds_reports/mobile/images/maternal_and_child.png
  custom/icds_reports/static/icds_reports/mobile/images/water_sanitation_hygiene.png
  custom/icds_reports/static/js/directives/progress-report/progress-report.directive.js
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/navigation.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/progress-report.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/progress-report.directive.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
  custom/icds_reports/templates/icds_reports/partials/dashboard_initial_page_data.html
  custom/icds_reports/templates/icds_reports/partials/shared_report_directives.html
  custom/icds_reports/templates/icds_reports/partials/shared_utility_services.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
Labels: product/custom

#26853 [Icds Dashboard] fix agg errors
  custom/icds_reports/management/commands/update_location_tables.py
  custom/icds_reports/tasks.py
Labels: product/custom

#26803 Update to django-angular==0.8.6 including rename to djng
  corehq/apps/data_interfaces/views.py
  corehq/apps/linked_domain/views.py
  corehq/apps/notifications/views.py
  corehq/apps/registration/views.py
  corehq/apps/users/views/mobile/users.py
  custom/icds_reports/templates/icds_reports/spec/mocha.html
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
Labels: product/invisible

#26851 [exports] catch date-like strings incorrectly handled as dates by the date parser
  corehq/ex-submodules/couchexport/tests/test_excel_format_value.py
  corehq/ex-submodules/couchexport/util.py
Labels: product/all-users-all-environments, product/invisible

#26856 Added haveAccessToAllLocations variable to scope
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/static/js/directives/lady-supervisor/lady-supervisor.directive.js
  custom/icds_reports/static/js/directives/program-summary/program-summary.directive.js
  custom/icds_reports/static/js/directives/progress-report/progress-report.directive.js
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
Labels: product/custom

#26858 Use agg
  corehq/apps/app_manager/dbaccessors.py
Labels: product/invisible

#26863 [ci skip] delete commented out test
  corehq/apps/users/tests/phone_users.py
Labels: product/invisible

#26859 Rename class and document current behaviour
  corehq/motech/openmrs/workflow_tasks.py
Labels: product/feature-flag

#26867 Unauthenticated link for mini-exchange
  corehq/apps/app_manager/urls.py
  corehq/apps/domain/decorators.py
  corehq/apps/domain/templates/domain/select.html
  corehq/apps/domain/views/base.py
  corehq/apps/hqwebapp/views.py
  urls.py
Labels: QA Passed, product/invisible

#26860 Couch to SQL: resolve more case and ledger diffs
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/util.py
  corehq/form_processor/backends/sql/ledger.py
Labels: product/invisible

#26866 Make to_omrs_boolean() available to DHIS2
  corehq/motech/dhis2/serializers.py
  corehq/motech/openmrs/serializers.py
  corehq/motech/serializers.py
Labels: product/feature-flag

#26875 Added release date and help link to mini exchange
  corehq/apps/app_manager/migrations/0015_alter_exchangeapplication.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/app_exchange.html
  corehq/apps/app_manager/views/apps.py
Labels: product/all-users-all-environments

#26870 Add test showing duplicates do not steal their originals' attachments
  corehq/form_processor/tests/test_basics.py
Labels: product/invisible

#26558 Migrate RegistrationRequest to SQL (4 of 4)
  corehq/apps/registration/_design/views/requests_by_guid/map.js
  corehq/apps/registration/_design/views/requests_by_guid/reduce.js
  corehq/apps/registration/_design/views/requests_by_time/map.js
  corehq/apps/registration/_design/views/requests_by_time/reduce.js
  corehq/apps/registration/_design/views/requests_by_username/map.js
  corehq/apps/registration/_design/views/requests_by_username/reduce.js
Labels: product/invisible

#26857 Some more django 2 code changes
  corehq/apps/domain/urls.py
  corehq/apps/domain/views/__init__.py
  corehq/apps/domain/views/settings.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/locations/bulk_management.py
  corehq/apps/users/forms.py
  custom/icds_reports/mobile_views.py
Labels: product/invisible

#26878 Removed dashboard_default view
  corehq/apps/dashboard/urls.py
  corehq/apps/dashboard/views.py
  corehq/apps/hqwebapp/views.py
Labels: product/invisible

#26880 remove check
  corehq/apps/userreports/reports/view.py
Labels: product/invisible

#26881 remove second primary key
  custom/icds_reports/models/views.py
Labels: product/invisible

#26824 [ICDS Dashboard] Added vhsnd monthly report
  custom/icds_reports/const.py
  custom/icds_reports/data_pull/data_pulls.py
  custom/icds_reports/data_pull/exceptions.py
  custom/icds_reports/data_pull/exporter.py
  custom/icds_reports/data_pull/queries.py
  custom/icds_reports/data_pull/sql_queries/vhsnd_monthly_report.sql
Labels: product/custom

#26884 Add TEST_FORM_SUBMISSION_RATE_LIMIT_RESPONSE flag
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/toggles.py
Labels: product/invisible

#26864 Initial two-stage user provisioning modeling, tests, and import flow
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/user_importer/tests/test_validators.py
  corehq/apps/user_importer/validation.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_create_mobile_workers.py
  corehq/toggles.py
Labels: product/feature-flag

#26883 enable order for custom data source
  corehq/apps/userreports/custom/data_source.py
  custom/icds_reports/reports/ucr.py
Labels: product/custom

#26886 ICDS Dashboard: Whatsapp sharing feature
  custom/icds_reports/static/icds_reports/mobile/css/app.less
  custom/icds_reports/static/icds_reports/mobile/images/share-icon.png
  custom/icds_reports/static/js/directives/filter-opener/filter-opener.directive.js
  custom/icds_reports/static/js/directives/mobile-filters/mobile-filters.directive.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
Labels: product/custom

#26888 add test that an empty value for is_account_confirmed triggers validation
  corehq/apps/user_importer/tests/test_validators.py
Labels: product/invisible

#26877 Updated feature flag category for mobile self reg
  corehq/toggles.py
Labels: product/admin

#26892 Use standard bulk download/upload workflow for location rationalization
  corehq/tabs/config.py
  corehq/tabs/tabclasses.py
  custom/icds/location_rationalization/forms.py
  custom/icds/location_rationalization/views.py
  custom/icds/static/icds/js/location_rationalization.js
  custom/icds/templates/icds/location_rationalization.html
  custom/icds/templates/icds/partials/location_rationalization.html
  custom/icds/templates/location_rationalization/download.html
  custom/icds/templates/location_rationalization/validate.html
  custom/icds/urls.py
Labels: product/invisible

#26885 Inddex reports very rough draft
  corehq/apps/fixtures/dbaccessors.py
  corehq/apps/fixtures/models.py
  corehq/apps/fixtures/tests/test_dbaccessors.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/fixtures/tests/test_location_ownership.py
  corehq/apps/reports/sqlreport.py
  corehq/tests/nose.py
  custom/abt/reports/fixture_utils.py
  custom/inddex/const.py
  custom/inddex/couch_db_data_collector.py
  custom/inddex/example_data/__init__.py
  custom/inddex/example_data/conv_factors.csv
  custom/inddex/example_data/data.py
  custom/inddex/example_data/expected_result.csv
  custom/inddex/example_data/food_cases.csv
  custom/inddex/example_data/food_composition_table.csv
  custom/inddex/example_data/food_list.csv
  custom/inddex/example_data/foodrecall_cases.csv
  custom/inddex/example_data/recipes.csv
  custom/inddex/filters.py
  custom/inddex/management/__init__.py
  custom/inddex/management/commands/__init__.py
  custom/inddex/management/commands/populate_inddex_test_domain.py
  custom/inddex/reports/__init__.py
  custom/inddex/reports/gaps_report_by_item.py
  custom/inddex/reports/gaps_summary_by_food_type.py
  custom/inddex/reports/master_data_file.py
  custom/inddex/reports/nutrient_intakes.py
  custom/inddex/reports/summary_statistics_report.py
  custom/inddex/sqldata.py
  custom/inddex/templates/inddex/multi_report.html
  custom/inddex/templates/inddex/partials/report_table.html
  custom/inddex/tests/__init__.py
  custom/inddex/tests/test_couch_db_data_collector.py
  custom/inddex/tests/test_master_report.py
  custom/inddex/ucr/data_providers/gaps_report_by_item_data.py
  custom/inddex/ucr/data_providers/gaps_summary_data.py
  custom/inddex/ucr/data_providers/master_data_file_data.py
  custom/inddex/ucr/data_providers/mixins.py
  custom/inddex/ucr/data_providers/nutrient_intakes_data.py
  custom/inddex/ucr/data_providers/summary_statistics_data.py
  custom/inddex/ucr/data_sources/food_consumption_indicators.json
  custom/inddex/utils.py
Labels: product/custom

#26895 Improve FundamentalCaseTests.test_duplicate_with_attachment test
  corehq/form_processor/tests/test_basics.py
Labels: product/invisible

#26896 Updated text for COVID app template page
  corehq/apps/app_manager/templates/app_manager/app_exchange.html
Labels: product/all-users-all-environments

#26771 Updated flow of 'Request Commcare Trial"
  .gitignore
  corehq/apps/analytics/static/analytix/js/hubspot.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/utils.less
  corehq/apps/registration/static/registration/js/register_new_user.js
  corehq/apps/registration/templates/registration/partials/start_trial_modal.html
Labels: awaiting QA, javascript, product/prod-india-all-users

#26899 Revert "Never checkpoint later than the latest offset"
  corehq/apps/change_feed/consumer/feed.py
Labels: product/invisible

#26889 Rn updated app version expression
  custom/icds_reports/ucr/expressions.py
  custom/icds_reports/ucr/tests/data/daily_feeding_attendence.xml
  custom/icds_reports/ucr/tests/test_daily_feeding_daily_attendance.py
Labels: product/custom

#26890 add stub user account confirmation page and tests for error cases
  corehq/apps/sms/admin.py
  corehq/apps/users/templates/users/commcare_user_confirm_account.html
  corehq/apps/users/tests/test_confirm_account_view.py
  corehq/apps/users/urls.py
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#26894 ICDS Dashboard: removing additional request params added to url after request completion
  custom/icds_reports/static/js/directives/service-delivery-dashboard/service-delivery-dashboard.directive.js
Labels: product/custom

#26876 monitoring functional
  corehq/apps/api/odata/utils.py
  corehq/apps/case_importer/tasks.py
  corehq/apps/hqwebapp/tasks.py
  corehq/apps/receiverwrapper/views.py
  corehq/apps/sms/tasks.py
  corehq/motech/repeaters/tasks.py
  corehq/util/datadog/gauges.py
  corehq/util/datadog/metrics.py
  corehq/util/metrics/__init__.py
  corehq/util/metrics/datadog.py
  corehq/util/metrics/metrics.py
  corehq/util/metrics/prometheus.py
  corehq/util/metrics/tests/__init__.py
  corehq/util/metrics/tests/test_metrics.py
  corehq/util/metrics/tests/utils.py
  corehq/util/metrics/urls.py
  corehq/util/metrics/views.py
  deployment/gunicorn/gunicorn_conf.py
  deployment/prometheus_server.py
  docs/index.rst
  docs/metrics.rst
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
  urls.py
Labels: product/invisible

#26872 Changes for bumping Django version
  corehq/apps/domain/forms.py
  corehq/apps/hqwebapp/widgets.py
  corehq/apps/reminders/forms.py
  corehq/apps/users/forms.py
Labels: product/invisible

#26903 only enable metrics view in DEBUG mode
  corehq/util/metrics/views.py
Labels: product/invisible

#26907 Add command to delete all couch databases
  corehq/apps/cleanup/management/commands/delete_couch_dbs.py
  corehq/apps/cleanup/utils.py
Labels: product/invisible

#26910 Couch to SQL: couch domains report, bug fixes, new default case diff
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/casediffqueue.py
  corehq/apps/couch_sql_migration/casedifftool.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/couch_domain_report.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/missingdocs.py
  corehq/apps/couch_sql_migration/tests/test_casedifftool.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_tinypanda.py
  corehq/apps/couch_sql_migration/tinypanda.py
  corehq/apps/couch_sql_migration/util.py
Labels: product/invisible

#26908 metric event api
  corehq/apps/hqadmin/management/commands/record_deploy_success.py
  corehq/apps/hqadmin/signals.py
  corehq/apps/hqwebapp/views.py
  corehq/util/datadog/const.py
  corehq/util/datadog/utils.py
  corehq/util/metrics/__init__.py
  corehq/util/metrics/const.py
  corehq/util/metrics/datadog.py
  corehq/util/metrics/metrics.py
  custom/icds_reports/utils/data_accessor.py
Labels: product/invisible

#26911 Revert breaking prometheus changes to gunicorn_conf.py
  deployment/gunicorn/gunicorn_conf.py
Labels: product/invisible

#26912 Fix record_deploy_success
  corehq/apps/hqadmin/management/commands/record_deploy_success.py
Labels: product/invisible

#26906 convert more metrics
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/tasks.py
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/missingdocs.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/elastic.py
  corehq/util/metrics/__init__.py
  corehq/util/metrics/metrics.py
  corehq/util/metrics/tests/utils.py
Labels: product/invisible

#26909 very basic ability to confirm an unconfirmed user account
  corehq/apps/domain/utils.py
  corehq/apps/registration/forms.py
  corehq/apps/users/exceptions.py
  corehq/apps/users/forms.py
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/commcare_user_confirm_account.html
  corehq/apps/users/templates/users/mobile/commcare_user_self_register.html
  corehq/apps/users/tests/test_confirm_account.py
  corehq/apps/users/tests/test_confirm_account_view.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
Labels: product/custom

#26854 increase cache timeout
  corehq/apps/app_manager/dbaccessors.py
Labels: product/invisible

#26916 [ci skip] change basename to name
  corehq/util/metrics/prometheus.py
Labels: product/invisible

#26918 Updated a few class names in dashboard
  custom/icds_reports/static/css/icds_dashboard.less
  custom/icds_reports/templates/icds_reports/icds_app/awc-opened-yesterday.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/cas-export.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/lady-supervisor.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/program-summary.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/progress-report.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/service-delivery-dashboard.html
Labels: product/invisible

#26861 [ICDS Dashboard] Added fields to household ucr for bihar api
  custom/icds_reports/ucr/data_sources/household_cases.json
Labels: product/custom

#26901 [Icds Dashboard] added wards to commcare use case
  custom/icds_reports/ucr/data_sources/dashboard/commcare_user_cases.json
Labels: product/custom

#26919 Fix name of toggle used in URL to be lowercase
  corehq/toggles.py
Labels: product/invisible

#26887 [Icds dashboard] add person case field
  custom/icds_reports/ucr/data_sources/person_cases_v3.json
Labels: product/custom

#26914 Fix query display
  corehq/apps/userreports/custom/data_source.py
Labels: product/invisible

#26923 Make pre-commit run flake8 command that stickler runs
  .flake8
  .stickler.yml
  git-hooks/pre-commit.sh
  requirements-python3/dev-requirements.txt
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
Labels: product/invisible

#26917 invitation form cleanup + reconciliation
  corehq/apps/registration/forms.py
  corehq/apps/users/forms.py
  corehq/apps/users/templates/users/accept_invite.html
  corehq/apps/users/templates/users/commcare_user_confirm_account.html
  corehq/apps/users/templates/users/partials/register_user_form_fields.html
  corehq/apps/users/tests/test_confirm_account.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#26882 use supervisor first in group by
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
Labels: product/invisible

#26921 Added help text to edit conditional alert
  corehq/messaging/scheduling/templates/scheduling/conditional_alert.html
  corehq/messaging/scheduling/views.py
Labels: product/all-users-all-environments

#26924 Updated _location_types to get full objects
  custom/icds/location_rationalization/dumper.py
  custom/icds/location_rationalization/parser.py
  custom/icds/location_rationalization/views.py
  custom/icds/templates/icds/partials/location_rationalization.html
Labels: product/invisible

#26930 add back knockout dependency for strong passwords
  corehq/apps/users/static/users/js/edit_commcare_user.js
Labels: product/all-users-all-environments

#26934 Added is_active to mobile users bulk lookup
  corehq/apps/users/templates/users/bulk_lookup.html
  corehq/apps/users/views/mobile/users.py
Labels: product/feature-flag

#26931 [ICDS Dashbaord] kpi pmo api aggregation changes changes
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_2_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_3_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_4_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_1_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_2_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_3_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_4_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
Labels: product/custom
