Repository dimagi/commcare-hq, pull requests merged in 2020-02, with the labels that each got.

#26503 [ICDS Dashboard] CAS data export + Tabular Reports usage data pulls
  custom/icds_reports/management/commands/dashboard_usage_report.py
Labels: product/custom

#26452 [ICDS Dashboard] Added LS indicator to system usage report
  custom/icds_reports/migrations/0165_added_system_usage_report_view.py
  custom/icds_reports/migrations/sql_templates/database_views/system_usage_report_view.sql
  custom/icds_reports/models/views.py
  custom/icds_reports/sqldata/exports/system_usage.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
Labels: product/custom

#26538 Search DB for transaction if form is saved
  corehq/form_processor/models.py
  corehq/form_processor/tests/test_reprocess_errors.py
Labels: product/invisible

#26535 add basic page for people to download the mobile dashboard app
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/mobile_dashboard_download.html
  custom/icds_reports/urls.py
  custom/icds_reports/views.py
Labels: product/custom

#26444 ICDS Dashboard: Web and mobile navigation menu common datastructure
  custom/icds_reports/dashboard_utils.py
  custom/icds_reports/static/icds_reports/js/spec/navigation.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/program-summary.directive.spec.js
  custom/icds_reports/static/js/directives/navigation/navigation.directive.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/navigation.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/navigation.directive.html
  custom/icds_reports/templates/icds_reports/partials/dashboard_initial_page_data.html
Labels: product/custom

#26540 Fixed migration flag logic in populate_sql_model_from_couch_model
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
Labels: product/invisible

#26536 ICDS Dashboard: Bar chart responsiveness
  custom/icds_reports/static/icds_reports/js/spec/awc-reports.directive.spec.js
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
Labels: product/custom

#26544 move task to different queue
  custom/icds_reports/tasks.py
Labels: product/invisible

#26545 ICDS Dashboard: Remove empty tooltip
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
Labels: product/custom

#26515 disable _all field for sms index
  corehq/ex-submodules/pillowtop/reindexer/change_providers/django_model.py
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
  corehq/pillows/mappings/sms_mapping.py
  corehq/pillows/sms.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: product/invisible, reindex/migration

#26304 ICDS Custom Data Pull Setup
  corehq/const.py
  corehq/toggles.py
  corehq/util/context_managers.py
  corehq/util/exceptions.py
  custom/icds/const.py
  custom/icds/forms.py
  custom/icds/static/icds/js/custom_data_pull.js
  custom/icds/tasks/data_pulls.py
  custom/icds/templates/icds/custom_data_pull.html
  custom/icds/urls.py
  custom/icds/utils/data_pull.py
  custom/icds/utils/location.py
  custom/icds/views/data_pull.py
  custom/icds_reports/const.py
  custom/icds_reports/data_pull/__init__.py
  custom/icds_reports/data_pull/data_pulls.py
  custom/icds_reports/data_pull/exceptions.py
  custom/icds_reports/data_pull/exporter.py
  custom/icds_reports/data_pull/queries.py
  custom/icds_reports/data_pull/sql_queries/awcs_electricity_and_cbe_count.sql
  custom/icds_reports/data_pull/sql_queries/awcs_facilities_count.sql
  custom/icds_reports/data_pull/sql_queries/awcs_infra_forms_count.sql
  custom/icds_reports/data_pull/sql_queries/awcs_launched.sql
  custom/icds_reports/data_pull/sql_queries/cbe_conducted.sql
  custom/icds_reports/data_pull/sql_queries/children_count.sql
  custom/icds_reports/data_pull/sql_queries/children_height_and_weight_count.sql
  custom/icds_reports/data_pull/sql_queries/children_pse_count.sql
  custom/icds_reports/data_pull/sql_queries/children_stunted_and_wasted_count.sql
  custom/icds_reports/data_pull/sql_queries/children_thr_count.sql
  custom/icds_reports/data_pull/sql_queries/create_dummy_thr_table.sql
  custom/icds_reports/data_pull/sql_queries/create_tmp_pse_table.sql
  custom/icds_reports/data_pull/sql_queries/create_tmp_thr_table.sql
  custom/icds_reports/data_pull/sql_queries/deliveries_and_ration_count.sql
  custom/icds_reports/data_pull/sql_queries/hot_cooked_meal_stats.sql
  custom/icds_reports/data_pull/sql_queries/lunch_above_3_years.sql
  custom/icds_reports/data_pull/sql_queries/lunch_above_5_years.sql
  custom/icds_reports/data_pull/sql_queries/pse_above_3_years.sql
  custom/icds_reports/data_pull/sql_queries/pse_above_5_years.sql
  custom/icds_reports/data_pull/sql_queries/pw_and_lm_thr_count.sql
  custom/icds_reports/data_pull/sql_queries/thr_children.sql
  custom/icds_reports/data_pull/sql_queries/thr_lactating.sql
  custom/icds_reports/data_pull/sql_queries/thr_pregnant.sql
  custom/icds_reports/management/commands/run_custom_data_pull.py
Labels: product/custom

#26546 Add STALE_EXPORT_THRESHOLD
  corehq/apps/export/exceptions.py
  corehq/apps/export/tasks.py
  corehq/celery_monitoring/signals.py
  settings.py
Labels: product/invisible

#26493 Vectorlink logic clarification
  custom/abt/reports/late_pmt.py
Labels: product/invisible

#26547 [Excel Formatting] Fix percentages in excel being multiplied by 100
  corehq/ex-submodules/couchexport/tests/test_excel_format_value.py
  corehq/ex-submodules/couchexport/util.py
Labels: product/all-users-all-environments, product/feature-flag

#26409 Partition Child Health Monthly by Month
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/agg_setup.py
  custom/icds_reports/utils/aggregation_helpers/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-child-health.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/child-health-monthly.distributed.txt
Labels: product/invisible

#26483 [ICDS Dashboard] CBE aggregation for gov dashboard
  custom/icds_reports/const.py
  custom/icds_reports/migrations/0166_auto_20200123_0748.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/reports/governance_apis.py
  custom/icds_reports/tests/agg_tests/fixtures/cbe_form.csv
  custom/icds_reports/tests/agg_tests/test_governance_apis.py
  custom/icds_reports/urls.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_gov_dashboard.py
  custom/icds_reports/views.py
Labels: product/custom

#26552 add view to the migration list
  custom/icds_reports/utils/migrations.py
Labels: product/custom

#24001 Add more details to Telerivet error message
  corehq/messaging/smsbackends/telerivet/models.py
Labels: product/invisible

#26551 Rn change the availablity gov dashboard
  custom/icds_reports/views.py
Labels: product/custom

#26328 Migrate ApplicationAccess from couch to sql (3 of 3)
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/cloudcare/dbaccessors.py
  corehq/apps/cloudcare/management/commands/populate_application_access.py
  corehq/apps/cloudcare/migrations/0002_sqlapplicationaccess.py
  corehq/apps/cloudcare/migrations/0003_rename_sqlapplicationaccess.py
  corehq/apps/cloudcare/models.py
  corehq/apps/cloudcare/tests/test_models.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
Labels: product/invisible

#26549 Properly show case importer errors to user
  corehq/apps/case_importer/tasks.py
  corehq/apps/case_importer/templates/case_importer/partials/ko_import_status.html
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/case_importer/tracking/task_status.py
  corehq/apps/case_importer/util.py
Labels: product/invisible

#26541 update recipients
  custom/icds/tasks/sms.py
Labels: product/custom

#26537 Fix command
  custom/icds/management/commands/populate_mother_name.py
Labels: product/custom

#26559 Updated couch_to_sql_models.rst [ci skip]
  docs/couch_to_sql_models.rst
Labels: product/invisible

#26314 [ICDS Dashboard] Fix awcs/state/districts/supervisors/blocks launched count on open yesterday
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc_daily.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc-daily.distributed.txt
Labels: product/custom

#26561 ICDS Dashboard: Bar chart tooltip positioning
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-or-sector-view.directive.html
Labels: product/custom

#26508 App manager support for report last sync tile
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view_report.js
  corehq/apps/app_manager/static/app_manager/js/modules/report_module.js
  corehq/apps/app_manager/suite_xml/features/mobile_ucr.py
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/sections/menus.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/mobile_report_configs.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_settings.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/report_context_tile.html
  corehq/apps/app_manager/tests/data/yesno_default_app_strings.txt
  corehq/apps/app_manager/tests/data/yesno_en_app_strings.txt
  corehq/apps/app_manager/tests/data/yesno_es_app_strings.txt
  corehq/apps/app_manager/tests/test_report_config.py
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#26539 Use pmt_data case properties for all columns
  custom/abt/reports/data_sources/sms_case.json
Labels: product/custom

#26553 Couch to SQL forms and cases: robust process pool + misc fixes
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/casediffqueue.py
  corehq/apps/couch_sql_migration/casedifftool.py
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/rebuildcase.py
  corehq/apps/couch_sql_migration/rewind.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_casediffqueue.py
  corehq/apps/couch_sql_migration/tests/test_casedifftool.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
Labels: product/invisible

#26569 Make ES default timeout configurable per env and try to filter before agg
  corehq/elastic.py
  settings.py
Labels: product/invisible

#26554 [Excel Formatting] Hide checkbox in Excel Dashboard Feeds and remove Feature Flag
  corehq/apps/export/export.py
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/toggles.py
Labels: product/all-users-all-environments

#26570 add jquery ui lib
  custom/icds/views/data_pull.py
  custom/icds_reports/data_pull/data_pulls.py
Labels: product/custom

#26440 Migrate HqDeploy to SQL (1 of 3)
  corehq/apps/hqadmin/management/commands/populate_sql_hq_deploy.py
  corehq/apps/hqadmin/migrations/0010_sqlhqdeploy.py
  corehq/apps/hqadmin/models.py
Labels: product/invisible

#26572 Removed clone_domain command
  corehq/apps/hqadmin/management/commands/clone_domain.py
  corehq/apps/hqadmin/tests/test_clone_domain.py
Labels: product/invisible

#26574 Ce/gevent timeout
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/child-health-monthly.distributed.txt
Labels: product/invisible

#26576 Removed gbova from code owners
  .github/CODEOWNERS
Labels: product/invisible

#26563 ICDS Dashboard: split J&K and Ladakh into two states
  custom/icds_reports/management/commands/split_j_and_k_state.py
  custom/icds_reports/static/icds_reports/js/spec/indie-map.directive.spec.js
  custom/icds_reports/static/js/angular-services/topojson.service.js
  custom/icds_reports/static/js/topojsons/README.md
  custom/icds_reports/static/js/topojsons/district_topojson_data.json
  custom/icds_reports/static/js/topojsons/districts_v4.topojson
  custom/icds_reports/static/js/topojsons/states_v4.topojson
  custom/icds_reports/utils/topojson_util/topojson_util.py
Labels: product/custom

#26568 ICDS Dashboard: add mobile dashboard installation instructions
  custom/icds_reports/static/media/Mobile_Dashboard_Installation_Instructions.pdf
  custom/icds_reports/templates/icds_reports/mobile_dashboard_download.html
Labels: product/custom

#26459 Memoize get_app_cached
  corehq/apps/app_manager/dbaccessors.py
Labels: product/invisible

#26575 Removed wrap arg from Program.by_domain
  corehq/apps/commtrack/tests/test_programs.py
  corehq/apps/products/forms.py
  corehq/apps/programs/forms.py
  corehq/apps/programs/models.py
  corehq/apps/registration/forms.py
  corehq/apps/users/forms.py
Labels: product/invisible

#26571 filter case_ids that we know are open
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
Labels: product/invisible

#26562 attach empty list when no prefetched models exist
  corehq/form_processor/backends/sql/dbaccessors.py
Labels: product/invisible

#26548 Bulk delete users
  corehq/apps/hqwebapp/forms.py
  corehq/apps/hqwebapp/utils.py
  corehq/apps/users/templates/users/bulk_delete.html
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/urls.py
  corehq/apps/users/views/mobile/custom_data_fields.py
  corehq/apps/users/views/mobile/users.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
  settings.py
Labels: product/feature-flag

#26579 include database name in metric for rate limited PG error
  corehq/util/sentry.py
Labels: product/invisible

#26582 Switched dict access to get in populate_sql_deploy
  corehq/apps/hqadmin/management/commands/populate_sql_hq_deploy.py
Labels: product/invisible

#26580 ICDS Dashboard: update APK and add overview doc
  custom/icds_reports/static/media/Mobile_Dashboard_Overview.pdf
  custom/icds_reports/static/media/cas-mobile-dashboard.apk
  custom/icds_reports/templates/icds_reports/mobile_dashboard_download.html
Labels: product/custom

#26578 make management command consistent with pillow retry queue
  corehq/ex-submodules/pillow_retry/management/commands/send_pillow_retry_queue_through_pillows.py
Labels: product/invisible

#26583 Altered HqDeploy.environment to allow null
  corehq/apps/hqadmin/migrations/0011_alter_hqdeploy_environment.py
  corehq/apps/hqadmin/models.py
Labels: product/invisible

#26581 run chm aggregate function
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-child-health.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/child-health-monthly.distributed.txt
Labels: product/invisible

#26587 Add Danny and Biyeun as billing & accounting CODEOWNERS
  .github/CODEOWNERS
Labels: product/invisible

#26588 [Amazon SES] Management commands to check and remove bounced emails from the list
  corehq/util/management/commands/check_bounced_email.py
  corehq/util/management/commands/unbounce_email.py
Labels: product/all-users-all-environments, product/invisible

#26593 [ICDS Dashboard ]rebuild child health view P1
  custom/icds_reports/migrations/0167_rebuild_child_health_monthly_view.py
Labels: product/custom

#26594 Fix args for tiered cache
  corehq/apps/app_manager/dbaccessors.py
  corehq/apps/app_manager/tests/test_dbaccessors.py
Labels: product/invisible

#26586 Removed unused template tags
  corehq/apps/accounting/templates/accounting/partials/invoice_table.html
  corehq/apps/case_importer/templates/case_importer/excel_config.html
  corehq/apps/case_importer/templates/case_importer/excel_fields.html
  corehq/apps/case_importer/templates/case_importer/import_cases.html
  corehq/apps/data_interfaces/templates/data_interfaces/interfaces/archive_forms.html
  corehq/apps/data_interfaces/templates/data_interfaces/interfaces/case_management.html
  corehq/apps/fixtures/templates/fixtures/manage_tables.html
  corehq/apps/fixtures/templates/fixtures/view_table.html
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/reports/templates/reports/async/aggregate_user_status.html
  corehq/apps/reports/templates/reports/async/basic.html
  corehq/apps/reports/templates/reports/async/project_health_dashboard.html
  corehq/apps/reports/templates/reports/async/summary_tabular.html
  corehq/apps/reports/templates/reports/partials/scheduled_reports_table.html
  corehq/apps/reports/templates/reports/project_health/partials/last_month_stats.html
  corehq/apps/reports/templates/reports/project_health/partials/users_tables.html
  corehq/apps/reports/templates/reports/project_health/project_health_email.html
  corehq/apps/reports/templates/reports/reports_home.html
  corehq/apps/reports/templates/reports/tabular.html
  corehq/apps/reports/templatetags/report_tags.py
  custom/_legacy/pact/templates/pact/chw/pact_chw_profile_submissions.html
  custom/_legacy/pact/templates/pact/patient/pactpatient_submissions.html
  custom/icds_reports/templates/icds_reports/multi_report.html
  custom/icds_reports/templates/icds_reports/partials/report_table.html
  custom/icds_reports/templates/icds_reports/partials/sections_report_table.html
  custom/icds_reports/templates/icds_reports/partials/subreport.html
  custom/ilsgateway/templates/ilsgateway/multi_report.html
  custom/ilsgateway/templates/ilsgateway/partials/report_table.html
  custom/ilsgateway/templates/ilsgateway/partials/report_table_with_tabs.html
  custom/ilsgateway/templates/ilsgateway/partials/tabs.html
  custom/inddex/templates/inddex/multi_report.html
  custom/inddex/templates/inddex/partials/report_table.html
  custom/inddex/templates/inddex/tabular_report.html
  custom/intrahealth/templates/intrahealth/multi_report.html
  custom/intrahealth/templates/intrahealth/partials/report_table.html
  custom/intrahealth/templates/yeksi_naa/multi_report.html
  custom/intrahealth/templates/yeksi_naa/partials/aggregated_table.html
  custom/intrahealth/templates/yeksi_naa/partials/report_table.html
  custom/intrahealth/templates/yeksi_naa/recap_passage.html
  custom/intrahealth/templates/yeksi_naa/tabular_report.html
  custom/m4change/templates/m4change/activateStatus.html
  custom/m4change/templates/m4change/anc_hmis_report_content.html
  custom/m4change/templates/m4change/approveStatus.html
  custom/m4change/templates/m4change/paidStatus.html
  custom/m4change/templates/m4change/report.html
  custom/m4change/templates/m4change/report_content.html
  custom/m4change/templates/m4change/reviewStatus.html
  custom/m4change/templates/m4change/selectTemplate.html
  custom/succeed/templates/patient_submissions.html
Labels: product/invisible

#26589 Altered HqDeploy.diff_url to be longer
  corehq/apps/hqadmin/migrations/0012_alter_hqdeploy_diffurl.py
  corehq/apps/hqadmin/models.py
Labels: product/invisible

#26584 Update couch_to_sql_models.rst
  docs/couch_to_sql_models.rst
Labels: product/invisible

#26595 change J&K name to Jammu & Kashmir to prevent drilldown
  custom/icds_reports/management/commands/split_j_and_k_state.py
  custom/icds_reports/static/js/topojsons/states_v4.topojson
Labels: product/custom

#26573 Fix Custom data pull
  custom/icds/forms.py
  custom/icds/tasks/data_pulls.py
  custom/icds/views/data_pull.py
  custom/icds_reports/data_pull/data_pulls.py
  custom/icds_reports/data_pull/sql_queries/create_dummy_thr_table.sql
Labels: product/custom

#26591 Mark case uploads older than threshold missing task as Failed in UI
  corehq/apps/case_importer/static/case_importer/js/import_history.js
  corehq/apps/case_importer/templates/case_importer/partials/ko_import_history.html
  corehq/apps/case_importer/tracking/jsmodels.py
Labels: product/invisible

#26598 Set local less version back to one that works for app builder
  bower.json
  corehq/apps/hqwebapp/templates/hqwebapp/partials/less_debug.html
Labels: product/invisible

#26577 Fix duplicate location column issue in map report in report builder
  corehq/apps/reports/static/reports/js/config.dataTables.bootstrap.js
  corehq/apps/userreports/reports/builder/forms.py
Labels: product/all-users-all-environments

#26606 Use freezegun instead of sleep to make auth tests fast and consistent
  corehq/ex-submodules/auditcare/tests/auth.py
Labels: product/invisible

#26615 ICDS Dashboard: update documentation around how feature flags are used
  corehq/toggles.py
  custom/icds_reports/README.md
Labels: product/custom

#26590 SMS: Don't require translations for all languages
  corehq/apps/domain/models.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/views.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/templates/scheduling/partials/message_configuration.html
  corehq/messaging/scheduling/tests/test_content.py
Labels: product/all-users-all-environments

#26600 Added evaluate_couch_model_for_sql
  corehq/apps/app_manager/management/commands/populate_sql_global_app_config.py
  corehq/apps/cleanup/management/commands/evaluate_couch_model_for_sql.py
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/cloudcare/management/commands/populate_application_access.py
  corehq/apps/hqadmin/management/commands/populate_sql_hq_deploy.py
  corehq/motech/dhis2/management/commands/populate_sql_dhis2_connection.py
  docs/couch_to_sql_models.rst
Labels: product/invisible

#26613 update to use array_agg_last_value
  custom/icds_reports/ucr/reports/mpr/ucr_v2/mpr_4b_iodized_salt.json
Labels: product/custom

#26348 Use Enterprise Subscription on Enterprise environments
  corehq/apps/accounting/bootstrap/utils.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_customer_invoicing.py
  corehq/apps/accounting/tests/test_enterprise_mode.py
  corehq/apps/accounting/tests/test_invoicing.py
  corehq/apps/registration/utils.py
Labels: awaiting QA, product/invisible

#26617 Fixed get_or_create calls in couch to sql data migrations
  corehq/apps/app_manager/management/commands/populate_sql_global_app_config.py
  corehq/apps/hqadmin/management/commands/populate_sql_hq_deploy.py
Labels: product/invisible

#26585 Allow moving locs w children, disallow changing their type
  corehq/apps/locations/forms.py
Labels: product/all-users-all-environments

#26441 Migrate HqDeploy to SQL (2 of 3)
  corehq/apps/hqadmin/management/commands/list_deploys.py
  corehq/apps/hqadmin/migrations/0013_populate_sqlhqdeploy.py
  corehq/apps/hqadmin/models.py
  corehq/apps/hqadmin/templates/hqadmin/partials/deploy_history.html
  corehq/apps/hqadmin/views/system.py
Labels: product/invisible

#26607 Migrate ApiUser to SQL (1 of 3)
  corehq/apps/api/management/commands/populate_apiuser.py
  corehq/apps/api/migrations/0001_initial.py
  corehq/apps/api/migrations/__init__.py
  corehq/apps/api/models.py
  corehq/apps/sms/tests/test_backends.py
Labels: product/invisible

#26616 Removed a few Domain attributes
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/domain/models.py
  corehq/apps/es/domains.py
  corehq/pillows/mappings/domain_mapping.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: product/invisible, reindex/migration

#26605 [Amazon SES] Use the new metadata from SNS
  corehq/ex-submodules/dimagi/utils/django/email.py
  corehq/util/models.py
  corehq/util/tests/test_bounced_emails.py
Labels: product/prod-india-all-users

#26618 Added default value to SQLApiUser.permissions
  corehq/apps/api/migrations/0002_alter_permissions.py
  corehq/apps/api/models.py
Labels: product/invisible

#26619 Fix 500 when deleting an SMS lanaguge
  corehq/apps/sms/views.py
Labels: product/invisible

#26622 Set permissions to empty list when populating SQLApiUser
  corehq/apps/api/management/commands/populate_apiuser.py
Labels: product/invisible

#26608 Migrate ApiUser to SQL (2 of 3)
  corehq/apps/api/decorators.py
  corehq/apps/api/migrations/0003_populate_apiuser.py
  corehq/apps/api/models.py
Labels: product/invisible

#26511 Labels
  corehq/motech/openmrs/const.py
  corehq/motech/openmrs/docs/index.rst
  corehq/motech/openmrs/forms.py
  corehq/motech/openmrs/views.py
Labels: product/feature-flag

#26627 ICDS Dashboard: use mapbox token from settings
  custom/icds_reports/dashboard_utils.py
  custom/icds_reports/static/icds_reports/js/spec/awc-reports.directive.spec.js
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/partials/dashboard_initial_page_data.html
Labels: product/custom

#26610 Streamline data clean up
  corehq/toggles.py
  custom/icds/data_management/__init__.py
  custom/icds/data_management/base.py
  custom/icds/data_management/const.py
  custom/icds/data_management/doc_processors.py
  custom/icds/data_management/es.py
  custom/icds/data_management/forms.py
  custom/icds/data_management/migrations/0001_initial.py
  custom/icds/data_management/migrations/__init__.py
  custom/icds/data_management/models.py
  custom/icds/data_management/sql.py
  custom/icds/data_management/static/data_management/js/data_management.js
  custom/icds/data_management/tasks.py
  custom/icds/data_management/templates/data_management/data_management.html
  custom/icds/data_management/urls.py
  custom/icds/data_management/views.py
  custom/icds/utils/location.py
  settings.py
  urls.py
Labels: product/custom

#26620 [SAASP-10264] Fix 500 error when saving OData feeds
  corehq/apps/export/views/new.py
Labels: product/all-users-all-environments, product/invisible

#26601 Revamp staticfiles dev setup and kill LESS_DEBUG
  DEV_SETUP.md
  bower.json
  corehq/apps/app_manager/templates/app_manager/base_summary.html
  corehq/apps/app_manager/templates/app_manager/partials/apps_stylesheets.html
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer-common/base.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/dashboard/templates/dashboard/base.html
  corehq/apps/domain/templates/domain/base_change_plan.html
  corehq/apps/domain/templates/login_and_password/login.html
  corehq/apps/hqwebapp/precompilers.py
  corehq/apps/hqwebapp/static/accounting/less/pricing.debug.less
  corehq/apps/hqwebapp/static/app_manager/less/app_manager.debug.less
  corehq/apps/hqwebapp/static/app_manager/less/preview_app.debug.less
  corehq/apps/hqwebapp/static/app_manager/less/summary.debug.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common.debug.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp.debug.less
  corehq/apps/hqwebapp/static/dashboard/less/dashboard.debug.less
  corehq/apps/hqwebapp/static/hqwebapp/less/bootstrap.debug.less
  corehq/apps/hqwebapp/static/hqwebapp/less/docs-style.debug.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style.debug.less
  corehq/apps/hqwebapp/static/preview_app/less/preview_app.debug.less
  corehq/apps/hqwebapp/static/registration/less/registration.debug.less
  corehq/apps/hqwebapp/static/reports/less/reports.debug.less
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/base_mobile.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/less.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/less_debug.html
  corehq/apps/hqwebapp/uglify.py
  corehq/apps/mocha/templates/mocha/base.html
  corehq/apps/reports/templates/reports/form/edit_submission.html
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/apps/styleguide/templates/styleguide/base.html
  corehq/util/context_processors.py
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/mobile/base_mobile.html
  docker/localsettings.py
  docs/js-guide/static-files.md
  localsettings.example.py
  package-lock.json
  package.json
  settings.py
Labels: product/invisible

#26632 Updated bulk user upload errors to block entire download
  corehq/apps/users/views/mobile/users.py
Labels: product/feature-flag

#26633 Removed doctypemigrations django app
  corehq/apps/hqadmin/management/commands/republish_doc_changes.py
  corehq/apps/hqcase/management/commands/backfill_couch_forms_and_cases.py
  corehq/doctypemigrations/README.md
  corehq/doctypemigrations/__init__.py
  corehq/doctypemigrations/bulk_migrate.py
  corehq/doctypemigrations/changes.py
  corehq/doctypemigrations/continuous_migrate.py
  corehq/doctypemigrations/djangomigrations.py
  corehq/doctypemigrations/management/__init__.py
  corehq/doctypemigrations/management/commands/__init__.py
  corehq/doctypemigrations/management/commands/run_doctype_migration.py
  corehq/doctypemigrations/migrations/0001_initial.py
  corehq/doctypemigrations/migrations/0002_auto_20150924_1930.py
  corehq/doctypemigrations/migrations/0003_doctypemigration_cleanup_complete.py
  corehq/doctypemigrations/migrations/0004_auto_20151001_1809.py
  corehq/doctypemigrations/migrations/0005_auto_20151013_0819.py
  corehq/doctypemigrations/migrations/0006_domain_migration_20151118.py
  corehq/doctypemigrations/migrations/0007_apps_20160129.py
  corehq/doctypemigrations/migrations/__init__.py
  corehq/doctypemigrations/migrator.py
  corehq/doctypemigrations/migrator_instances.py
  corehq/doctypemigrations/models.py
  corehq/doctypemigrations/stats.py
  corehq/doctypemigrations/tests.py
  corehq/ex-submodules/dimagi/utils/couch/settingshelper.py
  corehq/util/couch.py
  settings.py
Labels: product/invisible

#26637 [Icds Dashboard] fix tabular report location access
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#26631 Atom feed to update only
  corehq/motech/const.py
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/openmrs_config.py
Labels: product/feature-flag

#26640 improvements to ICDS form attachment deletion
  custom/icds/tasks/__init__.py
Labels: product/custom

#26630 Download just usernames
  corehq/apps/users/bulk_download.py
  corehq/apps/users/dbaccessors/all_commcare_users.py
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/filtered_download.js
  corehq/apps/users/tasks.py
  corehq/apps/users/views/mobile/users.py
Labels: product/feature-flag

#26644 replace existing form instead of deprecate if no case transactions exist
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/form_processor/backends/couch/processor.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/backends/sql/processor.py
  corehq/form_processor/interfaces/processor.py
  corehq/form_processor/parsers/form.py
Labels: product/invisible

#26641 add location validation for tabular reports
  custom/icds_reports/views.py
Labels: product/invisible

#26645 run deletion for each DB in separate tasks
  custom/icds/tasks/__init__.py
Labels: product/custom

#26628 Couch to SQL: missing forms and cases
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/casedifftool.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/missingdocs.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_casedifftool.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
  corehq/ex-submodules/dimagi/utils/couch/database.py
  corehq/ex-submodules/dimagi/utils/retry.py
  corehq/ex-submodules/dimagi/utils/tests/test_database.py
  corehq/ex-submodules/dimagi/utils/tests/test_retry.py
  corehq/util/pagination.py
Labels: product/invisible

#26526 [ICDS Dashboard] Removed feature flag for AWC changes in icds cas reach
  custom/icds_reports/reports/cas_reach_data.py
  custom/icds_reports/utils/data_accessor.py
Labels: product/custom

#26638 Drop MOTECH logs older than 90 days
  corehq/motech/repeaters/tasks.py
Labels: product/feature-flag, product/invisible

#26651 fix argument order
  corehq/messaging/scheduling/models/content.py
Labels: product/invisible

#26654 Added check for element before applying bindings
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
Labels: product/all-users-all-environments

#26648 Use string encoding in dump/reload code
  corehq/apps/dump_reload/couch/dump.py
  corehq/apps/dump_reload/management/commands/dump_domain_data.py
  corehq/apps/dump_reload/sql/serialization.py
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#26555 Migrate RegistrationRequest to SQL (1 of 4)
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/registration/management/commands/populate_sql_registration_request.py
  corehq/apps/registration/migrations/0001_initial.py
  corehq/apps/registration/migrations/__init__.py
  corehq/apps/registration/models.py
Labels: QA Passed, product/invisible

#26602 Migration DefaultConsumption to SQL (1 of 3)
  corehq/apps/consumption/management/commands/populate_defaultconsumption.py
  corehq/apps/consumption/migrations/0001_initial.py
  corehq/apps/consumption/migrations/__init__.py
  corehq/apps/consumption/models.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
Labels: product/invisible

#26621 [AWS SES] Add datadog counters and error tracking to bounced email manager
  corehq/apps/hqwebapp/tasks.py
  corehq/util/bounced_email_manager.py
Labels: product/prod-india-all-users

#26660 Altered request_ip to allow nulls
  corehq/apps/registration/migrations/0002_alter_request_ip.py
  corehq/apps/registration/models.py
Labels: product/invisible

#26661 Updated blank/None logic in default consumption migration
  corehq/apps/consumption/management/commands/populate_defaultconsumption.py
Labels: product/invisible

#26649 Take the launched numbers from the agg_Awc table only for the current date
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc_daily.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc-daily.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/tests.py
Labels: product/custom

#26635 add new J&K and Ladakh district files, and make clickable again
  custom/icds_reports/management/commands/split_j_and_k_state.py
  custom/icds_reports/static/js/topojsons/districts_v4.topojson
  custom/icds_reports/static/js/topojsons/states_v4.topojson
  custom/icds_reports/utils/topojson_util/topojson_util.py
Labels: product/custom

#26527 [Icds Dashboard] Rn add cbe vhnd for Service Delivery Report
  custom/icds_reports/migrations/0168_add_cbe_vhnd_column_to_agg_awc.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_5_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-05-01_5_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_awc.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-awc.distributed.txt
Labels: product/custom

#26657 remove tzinfo
  custom/icds/tasks/__init__.py
Labels: product/invisible

#26662 ICDS Dashboard: remove openstreetmap option from dashboard
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
Labels: product/custom

#26658 Add Feature Flag for Using De-Identification in OData Feeds
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/apps/export/views/new.py
  corehq/toggles.py
Labels: product/all-users-all-environments, product/feature-flag

#25898 Use elasticsearch 2.4.6 in docker setup
  docker/hq-compose.yml
  docker/localsettings.py
  localsettings.example.py
Labels: product/invisible

#26634 ICDS Dashboard: Additional filters for mobile dashboard
  custom/icds_reports/static/icds_reports/js/spec/additional-filter.directive.spec.js
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/directives/additional-filter/additional-filter.directive.js
  custom/icds_reports/static/js/directives/mobile-filters/mobile-filters.directive.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/additional-filter.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/mobile-filters.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/program-summary.directive.html
  custom/icds_reports/templates/icds_reports/partials/shared_component_directives.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
Labels: product/custom

#26653 [ICDS Dashboard] Made the LS indicator field available in system usage report from jan 2020
  custom/icds_reports/sqldata/exports/system_usage.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
Labels: product/custom

#26626 [ICDS Dashboard] Changed the incremented aggregation level to original value for undernutrition data
  custom/icds_reports/views.py
Labels: product/custom

#26543 [ICDS Dashboard] Chaning the indicator casting value from integer to text for tabular data pull
  custom/icds_reports/management/commands/dashboard_usage_report.py
Labels: product/custom

#26532 [ICDS Dashboard] Removed the feature flag for ICDS-904
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/reports/demographics_data.py
  custom/icds_reports/tests/agg_tests/reports/test_awc_reports.py
  custom/icds_reports/tests/agg_tests/reports/test_demographics.py
Labels: product/custom

#26650 [ICDS Dashboard] Fixed the incorrect message displayed when no LS is launched for a location
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/mixins.py
Labels: product/custom

#26268 [ICDS Dashboard]Added the Migration Form Model
  custom/icds_reports/const.py
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/migrations/0165_auto_20200131_1000.py
  custom/icds_reports/migrations/0169_merge_20200217_1447.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_1_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_awc_2017-04-01_2_sorted.csv
  custom/icds_reports/ucr/data_sources/dashboard/migrations_form.json
  custom/icds_reports/ucr/tests/data/migration_form_v32203.xml
  custom/icds_reports/ucr/tests/test_migration_form.py
  custom/icds_reports/utils/aggregation_helpers/distributed/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/ccs_record_monthly.py
  custom/icds_reports/utils/aggregation_helpers/distributed/migration_forms.py
  settings.py
Labels: product/custom

#26556 Migrate RegistrationRequest to SQL (2 of 4)
  corehq/apps/registration/migrations/0003_populate_sqlregistrationrequest.py
  corehq/apps/registration/models.py
Labels: QA Passed, product/invisible

#26666 Nh/omrs/missing values
  corehq/motech/openmrs/tests/test_workflow_tasks.py
  corehq/motech/openmrs/workflow_tasks.py
Labels: product/feature-flag

#26646 Reconcile location searches
  corehq/apps/export/forms.py
  corehq/apps/locations/forms.py
  corehq/apps/locations/static/locations/js/widgets.js
  corehq/apps/locations/templates/locations/manage/locations.html
  corehq/apps/locations/urls.py
  corehq/apps/locations/views.py
  corehq/apps/registration/forms.py
  corehq/apps/reports/filters/controllers.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/templates/reports/filters/multi_option.html
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/motech/repeaters/forms.py
Labels: product/all-users-all-environments

#26669 Don't include billing context in ENTERPRISE_MODE
  corehq/apps/accounting/models.py
  corehq/util/context_processors.py
Labels: product/invisible

#26665 Dump usernames followup
  corehq/apps/users/bulk_download.py
  corehq/apps/users/dbaccessors/all_commcare_users.py
Labels: product/feature-flag

#26667 Added a few real examples to style guide [ci skip]
  corehq/apps/styleguide/templates/styleguide/_includes/molecules/inline_edit.html
  corehq/apps/styleguide/templates/styleguide/_includes/molecules/pagination.html
  corehq/apps/styleguide/templates/styleguide/_includes/molecules/search_box.html
Labels: product/invisible

#26675 ICDS Dashboard: Changing additional filters heading
  custom/icds_reports/templates/icds_reports/icds_app/mobile/mobile-filters.directive.html
Labels: product/custom

#26674 ICDS Dashboard: Making maps responsive for different screen sizes
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/partials/mobile-heading.html
Labels: product/custom

#26652 [ICDS Dashboard] Add ui element tabular report
  custom/icds_reports/const.py
  custom/icds_reports/static/icds_reports/js/spec/download.directive.spec.js
  custom/icds_reports/static/js/directives/download/download.directive.js
  custom/icds_reports/tasks.py
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
  custom/icds_reports/views.py
Labels: product/custom

#26680 Update expired_domains.md
  custom/expired_domains.md
Labels: product/invisible

#26682 Fixed locations not saving on various pages
  corehq/apps/locations/views.py
  corehq/apps/reports/filters/controllers.py
  corehq/apps/reports/filters/users.py
Labels: product/all-users-all-environments

#26683 Updated location_tree to not look for l__ prefix
  corehq/apps/locations/static/locations/js/location_tree.js
Labels: product/all-users-all-environments

#26678 [ICDS Dashboard] reverting the old change which is causing the ranks to not load
  custom/icds_reports/views.py
Labels: product/custom

#26681 Added string casts for usernames
  corehq/apps/users/util.py
Labels: product/feature-flag

#26672 Add management command delete_form_attachments
  corehq/form_processor/management/commands/delete_form_attachments.py
Labels: product/invisible

#26684 Removed now-unnecessary computed observable
  corehq/apps/locations/static/locations/js/location_tree.js
  corehq/apps/locations/templates/locations/manage/locations.html
Labels: product/invisible

#26677 raise ESError when unable to fetch all docs
  corehq/util/es/interface.py
Labels: product/invisible

#26691 implement v4 bilty API
  corehq/util/bitly.py
Labels: product/invisible

#26690 Updated couch_to_sql_models.rst [ci skip]
  docs/couch_to_sql_models.rst
Labels: product/invisible

#26670 Require two factor for superusers
  corehq/apps/domain/decorators.py
  corehq/apps/hqadmin/views/users.py
  settings.py
Labels: product/invisible

#26689 Update block-level files for J&K and Ladakh
  custom/icds_reports/management/commands/split_j_and_k_state.py
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/static/js/topojsons/blocks/jk_blocks_v4.topojson
  custom/icds_reports/static/js/topojsons/blocks/ladakh_blocks_v4.topojson
  custom/icds_reports/static/js/topojsons/district_topojson_data.json
  custom/icds_reports/static/js/topojsons/districts_v4.topojson
Labels: product/custom

#26694 Removed last sync on mobile UCR case detail if report liveness tile i…
  corehq/apps/app_manager/suite_xml/features/mobile_ucr.py
Labels: product/feature-flag

#26688 ICDS Dashboard: Map view loading widget
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/angular-services/navigation.service.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
Labels: product/custom

#26697 ICDS Dashboard: always set mobile height to available height (even if it's less)
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
Labels: product/custom

#26671 Make location path queries more powerful
  corehq/apps/callcenter/views.py
  corehq/apps/locations/models.py
  corehq/apps/locations/tests/test_location_queries.py
  corehq/apps/reports/filters/controllers.py
  corehq/apps/reports/filters/users.py
  corehq/apps/userreports/reports/filters/choice_providers.py
Labels: product/all-users-all-environments

#26673 Get rid of old NEW_*_DB settings for couch db names
  corehq/apps/app_manager/__init__.py
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/fixtures/__init__.py
  corehq/apps/groups/__init__.py
  corehq/apps/users/__init__.py
  corehq/couchapps/__init__.py
  corehq/ex-submodules/fluff/management/commands/ptop_reindexer_fluff.py
  settings.py
Labels: product/invisible

#26642 Prevent user from creating redundant exports
  corehq/apps/export/static/export/js/download_export.js
Labels: QA Passed, product/all-users-all-environments

#26679 Couch to SQL: missing docs features and misc fixes
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/casediffqueue.py
  corehq/apps/couch_sql_migration/casedifftool.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/missingdocs.py
  corehq/apps/couch_sql_migration/rebuildcase.py
  corehq/apps/couch_sql_migration/rewind.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/system_action.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_casedifftool.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
Labels: product/invisible

#26698 Resize raw doc editor to show all content
  corehq/apps/hqadmin/static/hqadmin/js/raw_doc.js
Labels: product/admin

#26699 Show that empty input yields all locs
  corehq/apps/locations/tests/test_location_queries.py
  corehq/apps/reports/filters/users.py
Labels: product/invisible

#26609 Migrate ApiUser to SQL (3 of 3)
  corehq/apps/api/decorators.py
  corehq/apps/api/management/commands/populate_apiuser.py
  corehq/apps/api/migrations/0004_rename_apiuser.py
  corehq/apps/api/models.py
  corehq/apps/cleanup/deletable_doc_types.py
Labels: product/invisible

#26442 Migrate HqDeploy to SQL (3 of 3)
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/hqadmin/_design/views/deploy_history/map.js
  corehq/apps/hqadmin/management/commands/populate_sql_hq_deploy.py
  corehq/apps/hqadmin/management/commands/record_deploy_success.py
  corehq/apps/hqadmin/migrations/0014_remove_sqlhqdeploy_couch_id.py
  corehq/apps/hqadmin/migrations/0015_rename_sqlhqdeploy.py
  corehq/apps/hqadmin/models.py
  corehq/apps/hqadmin/views/system.py
Labels: product/invisible

#26611 update new paths
  custom/icds_reports/ucr/data_sources/awc_mgt_forms.json
  custom/icds_reports/ucr/tests/data/awc_visit_form_with_location.xml
  custom/icds_reports/ucr/tests/data/awc_visit_form_without_location.xml
  custom/icds_reports/ucr/tests/test_awc_mng_form_ucr.py
Labels: product/custom

#26696 Add available metadata to docs
  corehq/motech/value_source.py
Labels: product/feature-flag
