Repository dimagi/commcare-hq, pull requests merged in 2020-10, with the labels that each got.

#28575 bug fix geocoder key error
  corehq/apps/domain/forms.py
Labels: product/invisible

#28578 catch errored SMSBillables that were delivered but have a null price
  corehq/apps/sms/tasks.py
  corehq/apps/smsbillables/exceptions.py
  corehq/apps/smsbillables/models.py
Labels: product/invisible

#28579 fixed misspelling in app user bubble
  corehq/apps/users/templates/users/mobile_workers.html
Labels: product/all-users-all-environments

#28525 Add integration models to linked spaces
  corehq/apps/linked_domain/README.md
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/tests/test_release_manager.py
  corehq/apps/linked_domain/tests/test_update_dialer_settings.py
  corehq/apps/linked_domain/tests/test_update_hmac_callout_settings.py
  corehq/apps/linked_domain/tests/test_update_otp_settings.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/urls.py
  corehq/apps/linked_domain/views.py
Labels: QA Passed, product/feature-flag

#28570 Create Login-As All Users and remove login privileges from edit user permission
  corehq/apps/api/tests/user_resources.py
  corehq/apps/cloudcare/esaccessors.py
  corehq/apps/users/migrations/0024_add_login_as_all_users.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/templates/users/partials/edit_role_modal.html
Labels: product/all-users-all-environments

#28581 Touch up generate_request_report
  corehq/ex-submodules/auditcare/management/commands/generate_request_report.py
Labels: product/invisible

#28544 check for missing migrations in build
  docker/hq-compose.yml
  docker/localsettings.py
  docker/run.sh
  scripts/test-django-migrations.sh
Labels: product/invisible

#28582 Fixed inability to filter on indexed_on for form and case APIs
  corehq/apps/api/es.py
  corehq/apps/api/tests/form_resources.py
Labels: product/invisible

#28577 Rollback celery 4.4.7 (and kombu) due to pickling issues on prod
  corehq/ex-submodules/casexml/apps/phone/tests/test_async_restore.py
  corehq/motech/repeaters/tests/test_repeater.py
  dev_settings.py
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  requirements/uninstall-requirements.txt
  scripts/uninstall-requirements.sh
Labels: dependencies, product/invisible

#28547 Remove password obfuscation web
  corehq/apps/domain/auth.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/login_and_password/login.html
  corehq/apps/domain/views/settings.py
  corehq/apps/hqwebapp/forms.py
  corehq/apps/hqwebapp/utils.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/registration/forms.py
  corehq/apps/registration/static/registration/js/login.js
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/registration/templates/registration/register_new_user.html
  corehq/apps/registration/views.py
  corehq/apps/settings/forms.py
  corehq/apps/settings/static/settings/js/change_my_password.js
  corehq/apps/settings/templates/settings/change_my_password.html
  corehq/apps/settings/views.py
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/views/mobile/users.py
  custom/nic_compliance/const.py
  custom/nic_compliance/forms.py
  custom/nic_compliance/static/nic_compliance/js/encoder.js
  custom/nic_compliance/templates/__init__.py
  custom/nic_compliance/templates/nic_compliance/__init__.py
  custom/nic_compliance/tests/test_utils.py
  custom/nic_compliance/utils.py
Labels: product/custom

#28587 Missing Linked Domain migration
  corehq/apps/linked_domain/migrations/0013_auto_20201005_2215.py
Labels: product/invisible

#28463 change form lang
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/util.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
  corehq/apps/cloudcare/views.py
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/breadcrumbs.less
  corehq/toggles.py
Labels: product/feature-flag

#28586 Separate rate limiters for IP, user, and number
  corehq/apps/hqwebapp/two_factor_gateways.py
Labels: product/invisible

#28590 update to better texts
  corehq/apps/app_manager/static/app_manager/js/manage_releases_by_app_profile.js
Labels: product/custom, product/feature-flag

#28588 Fixed required asterisk not displaying for nested collapsible groups
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
Labels: product/all-users-all-environments

#28594 Depandabot config
  .github/dependabot.yml
Labels: product/invisible

#28595 Revert package-ecosystem
  .github/dependabot.yml
Labels: product/invisible

#28601 make requirements like dependabot
  Makefile
  requirements/Makefile
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  scripts/pip-post-compile.sh
Labels: product/invisible

#28517 ILM Prefactor
  corehq/apps/domain/tests/test_domain_calculated_properties.py
  corehq/apps/es/tests/test_filters.py
  corehq/apps/export/esaccessors.py
  corehq/apps/hqadmin/tests/test_stale_data_in_es.py
  corehq/elastic.py
  corehq/ex-submodules/pillowtop/es_utils.py
  corehq/ex-submodules/pillowtop/processors/elastic.py
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
  corehq/util/es/interface.py
  settings.py
  testapps/test_elasticsearch/tests/test_xform_es.py
Labels: product/invisible

#28607 Set python version for dependabot
  .gitignore
  requirements/.python-version
Labels: product/invisible

#28593 Feature/ush 348 updates overwrite caselist
  corehq/apps/app_manager/add_ons.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_module_overwrite.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_actions.html
  corehq/apps/app_manager/tests/test_modules.py
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#28603 Improve status metric and add window metric
  corehq/apps/hqwebapp/two_factor_gateways.py
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/tests/test_rate_limiter.py
Labels: product/invisible

#28589 Sort on keyword type not text field
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/messaging/scheduling/async_handlers.py
Labels: product/invisible

#28608 Model & migration for domain-scoped API keys
  corehq/apps/users/migrations/0025_hqapikey_domain.py
  corehq/apps/users/models.py
Labels: product/invisible

#28585 Fix location api permissions
  corehq/apps/api/resources/auth.py
  corehq/apps/locations/resources/v0_1.py
Labels: product/all-users-all-environments

#28610 escape first/last name
  corehq/apps/cloudcare/templates/formplayer/users.html
Labels: product/all-users-all-environments, product/invisible

#28584 Web Apps: serialize formplayer requests
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/webformsession_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/task_queue.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
Labels: QA Passed, product/invisible

#28617 use new column name
  corehq/apps/user_importer/models.py
  corehq/apps/user_importer/tasks.py
Labels: product/invisible

#28619 Added help link to form link feature flag
  corehq/toggles.py
Labels: product/admin

#28616 Pass arguments (--push) through to safe-commit-files
  scripts/commit-staging
Labels: product/invisible

#28615 ICDS Dashboard: Captcha validation
  corehq/apps/hqwebapp/forms.py
Labels: product/custom, product/feature-flag

#28622 Upgrade pillow
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#28458 Validate file extensions
  corehq/apps/receiverwrapper/tests/data/suspicious_form.abc
  corehq/apps/receiverwrapper/tests/test_submissions.py
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/apps/receiverwrapper/views.py
  corehq/ex-submodules/couchforms/exceptions.py
  corehq/ex-submodules/couchforms/getters.py
Labels: product/all-users-all-environments

#28633 Added git hook installation instructions to the dev guide
  DEV_SETUP.md
Labels: product/invisible

#28628 add test for user upload record
  corehq/apps/user_importer/tests/test_importer.py
Labels: product/invisible

#28618 authenticate download index page
  corehq/apps/app_manager/views/download.py
Labels: product/all-users-all-environments, product/invisible

#28632 Remove errand-boy
  corehq/apps/app_manager/xpath_validator/wrapper.py
  corehq/apps/builds/jadjar.py
  corehq/ex-submodules/dimagi/utils/subprocess_manager.py
  requirements/Makefile
  requirements/prod-requirements.in
  requirements/prod-requirements.txt
  requirements/uninstall-requirements-after-install.txt
  requirements/uninstall-requirements.txt
  scripts/_vendor/pip-post-compile.sh
  scripts/pip-post-compile-edx.sh
  scripts/pip-post-compile.sh
Labels: product/invisible

#28643 Fixed help link for mobile workers search
  corehq/apps/users/templates/users/mobile_workers.html
Labels: product/all-users-all-environments

#28627 Added clear button to combined multiple choice questions in web apps
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments

#28614 remove app json from being downloaded
  corehq/apps/app_manager/views/download.py
  corehq/apps/hqmedia/tasks.py
Labels: product/invisible

#28631 Track role update
  corehq/apps/settings/views.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/forms.py
  corehq/apps/users/util.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
Labels: product/all-users-all-environments, product/invisible

#28642 Kick retries on paused repeaters 7 days later
  corehq/motech/repeaters/tasks.py
Labels: product/invisible

#28621 Upgrade all Redis-related packages to their latest versions
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, dependencies, product/invisible

#28644 fixing modal class id issue
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_module_overwrite.html
Labels: product/all-users-all-environments

#28641 Use pip-sync to install test requirements
  docker/run.sh
  scripts/uninstall-requirements.sh
Labels: product/invisible

#28609 Skip doc existence check before deleting/index docs in ES
  corehq/ex-submodules/pillowtop/processors/elastic.py
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
  corehq/pillows/user.py
  corehq/util/es/interface.py
Labels: product/invisible

#28629 fix ledger incompatabilities
  corehq/apps/commtrack/models.py
  corehq/apps/reports/analytics/dbaccessors.py
  corehq/apps/reports/commtrack/data_sources.py
  corehq/apps/reports/commtrack/standard.py
  corehq/apps/reports/commtrack/util.py
  corehq/apps/reports/tests/commtrack/__init__.py
  corehq/apps/reports/tests/commtrack/test_datasources.py
  corehq/ex-submodules/casexml/apps/stock/consumption.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/models.py
  corehq/sql_accessors/migrations/0063_get_ledger_values_for_cases_2.py
  corehq/sql_accessors/migrations/0065_get_ledger_values_for_cases_3.py
  corehq/sql_accessors/sql_templates/get_ledger_values_for_cases_3.sql
  corehq/sql_proxy_accessors/migrations/0046_get_ledger_values_for_cases_2.py
  corehq/sql_proxy_accessors/migrations/0048_get_ledger_values_for_cases_3.py
  corehq/sql_proxy_accessors/sql_templates/get_ledger_values_for_cases_3.sql
Labels: product/invisible

#28639 Add log table for rate limited 2FA attempts.
  corehq/apps/hqwebapp/two_factor_gateways.py
  corehq/project_limits/migrations/0002_ratelimitedtwofactorlog.py
  corehq/project_limits/models.py
Labels: product/invisible, reindex/migration

#28652 Add help link for app changes toggle
  corehq/toggles.py
Labels: product/feature-flag

#27020 update sqlagg
  corehq/apps/reports/api.py
  corehq/apps/reports/sqlreport.py
  corehq/apps/reports/tests/test_sql_reports.py
  corehq/apps/userreports/tests/test_report_aggregation.py
  custom/champ/sqldata.py
  custom/champ/tests/test_pva_chart.py
  custom/champ/tests/test_pva_table.py
  custom/champ/views.py
  custom/up_nrhm/reports/asha_facilitators_report.py
  custom/up_nrhm/reports/block_level_month_report.py
  custom/up_nrhm/tests/reports/test_asha_reports.py
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#28647 pass timezone to formplayer
  corehq/apps/cloudcare/static/cloudcare/js/debugger/debugger.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/api.js
Labels: product/all-users-all-environments

#28653 Safety check before creating rate limit log entry
  corehq/apps/hqwebapp/two_factor_gateways.py
  corehq/project_limits/models.py
Labels: product/invisible

#28655 Added command to convert cases from child to extension
  custom/covid/management/__init__.py
  custom/covid/management/commands/__init__.py
  custom/covid/management/commands/update_case_index_relationship.py
  settings.py
Labels: product/invisible

#28659 Remove "lately" from fm outreach email
  corehq/apps/domain/templates/domain/email/fm_outreach.html
  corehq/apps/domain/templates/domain/email/fm_outreach.txt
Labels: product/admin

#28661 Fixed misspelled error message and added notify_exception
  corehq/apps/integration/views.py
Labels: product/feature-flag

#28662 track role update via
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/forms.py
  corehq/apps/users/util.py
Labels: product/all-users-all-environments, product/invisible

#28649 remove supply_point_dynamically_created soft assert
  corehq/form_processor/backends/couch/supply.py
  corehq/form_processor/backends/sql/supply.py
Labels: product/invisible

#28669 Added user_id to update_case_index_relationship
  custom/covid/management/commands/update_case_index_relationship.py
Labels: product/invisible

#28668 Remove uninstall-requirements.txt
  requirements/uninstall-requirements.txt
Labels: product/invisible

#28670 Added jump to top of page on navigation in web apps
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/middleware.js
Labels: product/all-users-all-environments

#28664 Updated pricing_table with escaped variable interpolation, by default
  corehq/apps/accounting/static/accounting/js/pricing_table.js
Labels: javascript, product/invisible

#28645 Clarify comment about repeat record check
  corehq/motech/repeaters/models.py
Labels: product/invisible

#28626 Add Trigger Autopayments view to accounting test UI
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/payment_handlers.py
  corehq/apps/accounting/templates/accounting/trigger_accounting_tests.html
  corehq/apps/accounting/urls.py
  corehq/apps/accounting/views.py
  corehq/tabs/tabclasses.py
Labels: product/admin

#28657 remove ES7 test matrix
  .travis.yml
Labels: product/invisible

#28674 Management command to copy permissions
  corehq/apps/users/management/commands/copy_web_permissions_to_all_apps.py
  corehq/util/couch.py
Labels: product/custom

#28672 skip deletes during reindex unless doing in-place reindex
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
Labels: product/invisible

#28675 Fix django-nose and celery requirements for pip-sync
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
Labels: product/invisible

#28673 don't fail during reindexing on bulk doc errors
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
Labels: product/invisible

#28648 Fix non keyword agg for ES7
  corehq/apps/analytics/tasks.py
  corehq/apps/data_pipeline_audit/dbacessors.py
  corehq/apps/es/es_query.py
  corehq/apps/es/forms.py
  corehq/apps/es/tests/test_esquery.py
  corehq/apps/es/users.py
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/management/commands/project_stats_report.py
  corehq/apps/reports/tasks.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/user_mapping.py
Labels: product/invisible

#28682 Add pdbpp to dev-requirements
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
Labels: product/invisible

#28665 Add APHL Exposure Notifications
  corehq/apps/integration/forms.py
  corehq/apps/integration/migrations/0005_gaenotpserversettings_server_type.py
  corehq/apps/integration/models.py
  corehq/apps/integration/static/integration/js/dialer/dialer_utils.js
  corehq/apps/integration/static/integration/js/dialer/domain_dialer_main.js
  corehq/apps/integration/views.py
Labels: product/feature-flag

#28663 Added README for django apps
  corehq/README.rst
  corehq/apps/README.rst
  corehq/ex-submodules/README.rst
Labels: product/invisible

#28686 Make sure api-key auth user is populated before LocationAccessMiddleware
  corehq/apps/users/middleware.py
Labels: product/all-users-all-environments

#28695 Revert "Fix non keyword agg for ES7"
  corehq/apps/analytics/tasks.py
  corehq/apps/data_pipeline_audit/dbacessors.py
  corehq/apps/es/es_query.py
  corehq/apps/es/forms.py
  corehq/apps/es/tests/test_esquery.py
  corehq/apps/es/users.py
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/management/commands/project_stats_report.py
  corehq/apps/reports/tasks.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/user_mapping.py
Labels: product/invisible

#28689 remove redundant command
  corehq/apps/cleanup/management/commands/local_commcare_export.py
Labels: product/custom, product/invisible

#28692 remove references in texts
  corehq/apps/userreports/reports/sum_when_templates.py
  corehq/util/tests/test_files.py
Labels: product/custom

#28676 Add ability to restrict Hubspot data by account and email domains to Billing Accounts
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/migrations/0051_hubspot_restrictions.py
  corehq/apps/accounting/models.py
  corehq/apps/analytics/management/commands/list_blocked_from_hubspot.py
  corehq/apps/analytics/tasks.py
  corehq/apps/analytics/tests/test_hubspot.py
  corehq/apps/analytics/utils.py
Labels: QA post deploy, product/admin, reindex/migration

#28693 make sure monthly credit report task is run on india and swiss as well as production
  corehq/apps/accounting/tasks.py
Labels: product/invisible

#28704 update label bot to handle WIP workflow
  .github/labels.yml
Labels: Open for review: do not merge, product/invisible

#28705 add the labels we use
  .github/labels.yml
Labels: product/invisible

#28691 allow ignoring demo user submissions
  corehq/apps/receiverwrapper/tests/test_submissions.py
  corehq/apps/receiverwrapper/util.py
  settings.py
Labels: product/custom

#28687 remove redundant icds_nic
  corehq/apps/sms/migrations/0048_delete_sqlicdsbackend.py
  corehq/apps/sms/tests/test_backends.py
  corehq/apps/smsbillables/management/commands/bootstrap_icds_gateway.py
  corehq/apps/smsbillables/migrations/0015_bootstrap_icds_rates.py
  corehq/messaging/smsbackends/icds_nic/__init__.py
  corehq/messaging/smsbackends/icds_nic/models.py
  settings.py
Labels: product/custom, product/invisible, reindex/migration

#28706 add public docs about our usage of labels
  CONTRIBUTING.rst
Labels: product/invisible

#28707 OTP Config Settings - adds filler text for auth_token field input
  corehq/apps/integration/forms.py
Labels: product/feature-flag

#28698 Add display name to gateway form
  corehq/apps/sms/forms.py
  corehq/apps/sms/views.py
Labels: product/invisible

#28690 move use of phone entries to settings
  corehq/apps/sms/tasks.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/tests/test_recipients.py
  corehq/messaging/tasks.py
  corehq/messaging/util.py
  settings.py
Labels: Open for review: do not merge, product/custom

#28708 Allow 'can view' web users to view pending invites
  corehq/apps/users/templates/users/web_users.html
Labels: product/all-users-all-environments

#28714 Updated get_linked_domains to exclude deleted domains
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/filters.py
Labels: product/feature-flag

#28715 remove unused code
  corehq/apps/hqcase/esaccessors.py
Labels: product/invisible

#28620 Only allow ipv4 addresses when specifying the api key allowlist
  corehq/apps/settings/forms.py
Labels: product/all-users-all-environments

#28699 Allow adding and removing of translations
  corehq/apps/app_manager/app_schemas/form_metadata.py
  corehq/apps/app_manager/app_schemas/tests/test_app_diffs.py
Labels: product/feature-flag

#28634 drop old get_ledger_values_for_cases_2 sql function
  corehq/sql_accessors/migrations/0066_drop_get_ledger_values_for_cases_2.py
  corehq/sql_proxy_accessors/migrations/0049_drop_get_ledger_values_for_cases_2.py
Labels: product/invisible, reindex/migration

#28717 Added git-heat script
  scripts/git-heat.sh
Labels: product/invisible

#28667 Add ESQuery wrapper for user data searches
  corehq/apps/custom_data_fields/models.py
  corehq/apps/es/tests/test_user_es.py
  corehq/apps/es/users.py
Labels: product/invisible

#28709 Fixed web apps tile display for medium-width screens
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
Labels: product/all-users-all-environments

#28710 Track user create on upload
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
Labels: product/all-users-all-environments, product/invisible

#28718 fixed resource leak with GzipFile
  corehq/apps/dump_reload/management/commands/dump_domain_data_raw.py
  corehq/apps/export/multiprocess.py
  corehq/blobs/fsdb.py
Labels: product/invisible

#28721 Add click tracking for app diff buttons on releases table
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_table.html
Labels: product/invisible

#28722 Added support for deleting linked reports
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/templates/userreports/configurable_report.html
  corehq/apps/userreports/templates/userreports/edit_report_config.html
  corehq/apps/userreports/templates/userreports/partials/delete_report_button.html
  corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
  corehq/apps/userreports/util.py
  corehq/apps/userreports/views.py
Labels: product/feature-flag
