Repository dimagi/commcare-hq, pull requests merged in 2020-01, with the labels that each got.

#26322 RepeatRecord.fire() has no "post_fn" param
  corehq/apps/cleanup/management/commands/fire_repeaters.py
Labels: product/invisible

#26292 Es/notify restricted domain
  corehq/apps/domain/decorators.py
  settings.py
Labels: product/admin

#26335 Fix new year edge cases
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/invisible

#26336 A Y2K20 bug?
  corehq/apps/userreports/tests/test_report_aggregation.py
Labels: product/invisible

#26294 Only do Dimagi stuff on Dimagi environments
  corehq/apps/hqadmin/forms.py
  corehq/apps/hqadmin/tasks.py
  settings.py
Labels: product/admin

#26270 handle existing rows in blob deletion
  corehq/blobs/metadata.py
Labels: product/invisible

#26277 remove the includes line at the bottom of each plan description
  corehq/apps/accounting/static/accounting/js/pricing_table.js
  corehq/apps/domain/templates/domain/select_plan.html
  corehq/apps/domain/views/accounting.py
  corehq/apps/hqwebapp/static/accounting/less/pricing-main.less
Labels: product/prod-india-all-users

#26312 escape a resource conflict error on clear_login_attempts and retry
  corehq/apps/hqwebapp/signals.py
Labels: product/all-users-all-environments

#26337 reverse order_by on previous_subscription
  corehq/apps/accounting/models.py
Labels: product/prod-india-all-users

#26310 Added app manager SQL models to delete_domain
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
Labels: product/invisible

#26333 Associate MOTECH requests with payload
  corehq/motech/dhis2/repeaters.py
  corehq/motech/migrations/0002_requestlog_payload_id.py
  corehq/motech/migrations/0003_auto_20200102_1006.py
  corehq/motech/models.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/requests.py
  corehq/motech/templates/motech/log_detail.html
  corehq/motech/templates/motech/logs.html
  corehq/motech/tests/test_models.py
  corehq/motech/views.py
Labels: product/feature-flag

#26339 Fix import
  custom/icds/tasks/__init__.py
  custom/icds/tasks/sms.py
  custom/icds/tests/models/test_hosted_ccz.py
  custom/icds/tests/tasks/test_setup_ccz_file_for_hosting.py
Labels: product/custom

#26343 part 1 of trying to diagnose how to fix the 2FA login problem
  corehq/apps/hqwebapp/two_factor_gateways.py
Labels: product/prod-india-all-users

#26344 Fix 2FA on login for prod and india
  corehq/apps/hqwebapp/two_factor_gateways.py
Labels: product/prod-india-all-users

#26329 drop and recreate indices for df
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/agg_setup.py
  custom/icds_reports/utils/aggregation_helpers/distributed/base.py
  custom/icds_reports/utils/aggregation_helpers/distributed/daily_feeding_forms_child_health.py
  custom/icds_reports/utils/aggregation_helpers/distributed/growth_monitoring_forms.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/daily-feeding-forms-child-health.distributed.txt
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/growth-monitoring-forms.distributed.txt
Labels: product/invisible

#26345 MOTECH docs
  corehq/motech/dhis2/README.md
  corehq/motech/docs/value_source.rst
  corehq/motech/openmrs/const.py
  corehq/motech/openmrs/docs/index.rst
Labels: product/feature-flag

#26330 [ICDS Dashboard]state names api for governance dashboard
  custom/icds_reports/const.py
  custom/icds_reports/reports/governance_apis.py
  custom/icds_reports/tests/agg_tests/test_governance_apis.py
  custom/icds_reports/views.py
Labels: product/invisible

#26347 Repeater retries
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: product/invisible

#26350 first part of setting up processes to handle SES bounces
  corehq/ex-submodules/dimagi/utils/django/email.py
  settings.py
Labels: product/prod-india-all-users

#26349 Remove some unused exports code
  corehq/apps/export/conversion_mappings.py
  corehq/apps/export/dbaccessors.py
Labels: product/invisible

#26351 ICDS Dashboard:V1 release trello tasks
  custom/icds_reports/static/icds_reports/mobile/css/filters.less
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/directives/location-filter/location-filter.directive.js
  custom/icds_reports/static/js/directives/mobile-datepicker/mobile-datepicker.directive.js
  custom/icds_reports/static/js/directives/mobile-filters/mobile-filters.directive.js
  custom/icds_reports/static/js/directives/month-filter/month-filter.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/location_filter.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/mobile-filters.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/month-filter.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/navigation.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/partials/mobile-heading.html
Labels: product/custom

#26354 Fetch test state names dynamically
  custom/icds/management/commands/sanitize_phone_numbers.py
Labels: product/invisible

#26357 [ci skip] document change management process for mobile dashboard vs web
  custom/icds_reports/README.md
Labels: product/invisible

#26331 [ICDS Dashboard] Better pagination
  custom/icds_reports/reports/governance_apis.py
  custom/icds_reports/tests/agg_tests/test_governance_apis.py
  custom/icds_reports/views.py
Labels: product/custom

#26355 [ICDS Dashboard] fix navigation menu visibility
  custom/icds_reports/const.py
  custom/icds_reports/static/js/directives/navigation/navigation.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/navigation.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/navigation.directive.html
Labels: product/custom

#26353 Process bounced emails from SES and stop sending to them
  corehq/apps/hqwebapp/tasks.py
  corehq/ex-submodules/dimagi/utils/django/email.py
  corehq/util/bounced_email_manager.py
  corehq/util/management/commands/process_bounced_emails.py
  corehq/util/migrations/0001_initial.py
  corehq/util/migrations/__init__.py
  corehq/util/models.py
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
Labels: product/prod-india-all-users

#26291 [Exports] Correctly type data in excel exports
  corehq/apps/export/export.py
  corehq/apps/export/models/new.py
  corehq/ex-submodules/couchexport/export.py
  corehq/ex-submodules/couchexport/tests/test_excel_format_value.py
  corehq/ex-submodules/couchexport/util.py
  corehq/ex-submodules/couchexport/writers.py
Labels: product/all-users-all-environments

#26361 [Amazon SES] Responses to #26353
  corehq/apps/hqwebapp/tasks.py
  corehq/ex-submodules/dimagi/utils/django/email.py
  corehq/util/bounced_email_manager.py
  corehq/util/management/commands/process_bounced_emails.py
Labels: product/prod-india-all-users

#26303 Memoize Domain.get_by_name for ICDS env
  corehq/apps/domain/models.py
Labels: product/invisible

#26305 Move heartbeat user-reporting update to async staging pipeline
  corehq/apps/ota/tests/test_heartbeat.py
  corehq/apps/ota/views.py
  corehq/apps/users/migrations/0006_auto_20191225_1207.py
  corehq/apps/users/models.py
  corehq/apps/users/tasks.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_synclog_pillow.py
  corehq/pillows/synclog.py
  testapps/test_pillowtop/tests/test_xform_pillow.py
Labels: product/invisible

#26356 [ICDS Dashboard] fixed the year issue on banner
  custom/icds_reports/static/js/directives/info-message/info-message.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/info-message.directive.html
Labels: product/custom

#26319 Ability to copy in multimedia from another app
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/templates/app_manager/partials/settings/multimedia_ajax.html
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/multimedia.py
  corehq/apps/hqmedia/models.py
  corehq/apps/hqmedia/views.py
  corehq/apps/hqwebapp/static/hqwebapp/js/widgets.js
Labels: product/feature-flag

#26338 Added support for user choosing bulk app translation download format
  corehq/apps/app_manager/static/app_manager/js/settings/translations.js
  corehq/apps/app_manager/templates/app_manager/partials/bulk_upload_app_translations.html
  corehq/apps/translations/views.py
Labels: product/feature-flag

#26363 [Amazon SES] Improvements to fetching bounced_email from headers
  corehq/util/bounced_email_manager.py
Labels: product/prod-india-all-users

#26360 Couch to SQL: gevent-compatible process pool
  corehq/apps/couch_sql_migration/parallel.py
  corehq/apps/couch_sql_migration/tests/test_parallel.py
  corehq/tests/noseplugins/dividedwerun.py
  corehq/util/test_utils.py
  corehq/util/tests/test_utils.py
Labels: product/invisible

#26364 Fix Web Users UI query for ES 2
  corehq/apps/users/views/__init__.py
Labels: product/invisible

#26317 Added audio translator file download
  corehq/apps/app_manager/tests/data/duplicate_text_questions.xml
  corehq/apps/hqmedia/static/hqmedia/js/manage_paths_main.js
  corehq/apps/hqmedia/templates/hqmedia/audio_translator.html
  corehq/apps/hqmedia/templates/hqmedia/manage_paths.html
  corehq/apps/hqmedia/templates/hqmedia/partials/manage_paths.html
  corehq/apps/hqmedia/templates/hqmedia/translations_coverage.html
  corehq/apps/hqmedia/tests/test_audio_translator_files.py
  corehq/apps/hqmedia/urls.py
  corehq/apps/hqmedia/view_helpers.py
  corehq/apps/hqmedia/views.py
Labels: product/feature-flag

#26362 ICDS Dashboard: remove toggle for mobile maps and always show them
  corehq/toggles.py
  custom/icds_reports/mobile_views.py
  custom/icds_reports/static/icds_reports/js/spec/utils.js
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
  custom/icds_reports/static/js/icds_dashboard_utils.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-or-sector-view.directive.html
  custom/icds_reports/templates/icds_reports/partials/dashboard_initial_page_data.html
  custom/icds_reports/views.py
Labels: product/custom

#26366 [ICDS Dashboard] Fixed name convention of indicators
  custom/icds_reports/const.py
  custom/icds_reports/reports/fact_sheets.py
  custom/icds_reports/sqldata/exports/demographics.py
Labels: product/custom

#26359 Prevent the date filter to select date prior to April 2019 foR AG
  custom/icds_reports/static/icds_reports/js/spec/month-filter.directive.spec.js
  custom/icds_reports/static/js/angular-services/date-helper.service.js
  custom/icds_reports/static/js/directives/month-filter/month-filter.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/month-filter.html
Labels: product/custom

#26341 Added template type to sum_when error message
  corehq/apps/userreports/reports/factory.py
Labels: product/feature-flag

#26370 ICDS Dashboard: add UI feedback if password is wrong
  custom/icds_reports/templates/icds_reports/mobile_login.html
Labels: product/custom

#26369 ICDS Dashboard: enable password reset from mobile embed
  corehq/apps/domain/templates/login_and_password/password_reset_form.html
  corehq/apps/domain/templates/login_and_password/two_factor/_wizard_forms.html
  corehq/apps/domain/urls.py
  custom/icds_reports/mobile_views.py
  custom/icds_reports/urls.py
Labels: product/custom

#26373 ICDS Dashboard: Add map legend to mobile
  custom/icds_reports/static/css/icds_dashboard.css
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
Labels: product/custom

#26372 Removed test_couch_dump_load.test_multimedia
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
Labels: product/invisible

#26346 [ICDS Dashboard]Identifying the areas in the Dashboard where the height eligiblity is 6mnth to 5 years and not 0-5 years
  custom/icds_reports/tests/agg_tests/outputs/agg_child_health_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_child_health_2017-05-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/child_health_monthly-st1-2017-05-01.csv
  custom/icds_reports/tests/agg_tests/outputs/child_health_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/child_health_monthly_2017-05-01_sorted.csv
  custom/icds_reports/tests/agg_tests/reports/test_prevalence_of_severe.py
  custom/icds_reports/tests/agg_tests/reports/test_prevalence_of_stunting.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
  custom/icds_reports/tests/agg_tests/test_fact_sheet_report.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_child_health.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/agg-child-health.distributed.txt
Labels: product/custom

#26379 Remove new sort added
  custom/icds_reports/ucr/reports/mpr/mpr_2bii_child_death_list.json
Labels: product/custom

#26367 ICDS Dashboard: barcharts in mobile
  custom/icds_reports/static/icds_reports/mobile/css/app.less
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/awc-reports.html
Labels: product/custom

#26378 [ICDS Dashboard] reverse sort order in AG Chart page.
  custom/icds_reports/reports/adolescent_girls.py
  custom/icds_reports/tests/agg_tests/reports/test_adolescent_girls.py
Labels: product/custom

#26375 fix generator in reconciliation task
  custom/icds_reports/tasks.py
Labels: product/invisible

#26384 update column names
  corehq/apps/translations/integrations/transifex/views.py
Labels: product/feature-flag

#26376 Fix TestReportMultipleAggregationsSQL more robustly
  corehq/apps/userreports/tests/test_report_aggregation.py
Labels: product/invisible

#26365 Couch to SQL forms & cases: parallel case diff
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/parallel.py
  corehq/apps/couch_sql_migration/rebuildcase.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_couch_sql_diff.py
  corehq/apps/couch_sql_migration/tests/test_diffs.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_rebuildcase.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
  corehq/apps/couch_sql_migration/util.py
  corehq/apps/tzmigration/timezonemigration.py
  corehq/ex-submodules/dimagi/test_utils/base.py
  corehq/ex-submodules/dimagi/utils/chunked.py
Labels: product/invisible

#26387 fix report
  custom/icds_reports/ucr/reports/asr/asr_2_3_person_cases.json
Labels: product/custom

#26377 Rewrite ES "not (A and B)" like we do for "or"
  corehq/apps/es/filters.py
  corehq/apps/es/tests/test_filters.py
  corehq/apps/es/tests/test_sms.py
Labels: product/invisible

#26391 [Icds dashboard] remove disappear condition from sag
  custom/icds_reports/const.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/reports/demographics_data.py
  custom/icds_reports/reports/fact_sheets.py
  custom/icds_reports/sqldata/exports/demographics.py
  custom/icds_reports/static/icds_reports/js/spec/month-filter.directive.spec.js
  custom/icds_reports/static/js/angular-services/date-helper.service.js
  custom/icds_reports/static/js/directives/month-filter/month-filter.directive.js
  custom/icds_reports/static/js/directives/navigation/navigation.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/navigation.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/navigation.directive.html
Labels: product/custom

#26392 update to show 3 decimal places
  custom/icds_reports/ucr/reports/mpr/mpr_2ci_child_birth_list.json
Labels: product/custom

#26389 [Excel Formatting] Handle issues with datatypes that come from user reports and app summary
  corehq/ex-submodules/couchexport/tests/test_excel_format_value.py
  corehq/ex-submodules/couchexport/util.py
Labels: product/all-users-all-environments

#26388 make sure reserved properties also contain the `info` tag
  corehq/apps/export/static/export/js/models.js
Labels: product/all-users-all-environments

#26395 display configurable report query
  corehq/apps/reports/api.py
  corehq/apps/reports_core/templates/reports_core/base_template_new.html
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/sql/data_source.py
Labels: product/invisible

#26394 [ICDS Dashboard] Remove feature flag SAG
  custom/icds_reports/reports/adolescent_girls.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/reports/demographics_data.py
  custom/icds_reports/reports/fact_sheets.py
  custom/icds_reports/sqldata/agg_awc_monthly.py
  custom/icds_reports/sqldata/exports/demographics.py
  custom/icds_reports/static/icds_reports/js/spec/adolescent-girls.directive.spec.js
  custom/icds_reports/static/js/directives/adolescent-girls/adolescent-girls.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/navigation.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/navigation.directive.html
  custom/icds_reports/tests/agg_tests/reports/test_adolescent_girls.py
  custom/icds_reports/tests/agg_tests/reports/test_awc_reports.py
  custom/icds_reports/tests/agg_tests/reports/test_demographics.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
  custom/icds_reports/tests/agg_tests/test_fact_sheet_report.py
Labels: product/custom

#26396 Reverse the color of SAG
  custom/icds_reports/reports/demographics_data.py
  custom/icds_reports/reports/fact_sheets.py
  custom/icds_reports/tests/agg_tests/reports/test_demographics.py
  custom/icds_reports/tests/agg_tests/test_fact_sheet_report.py
Labels: product/custom

#26397 show a list instead
  corehq/apps/reports_core/templates/reports_core/base_template_new.html
  corehq/apps/userreports/reports/view.py
Labels: product/invisible

#26334 drop varchar ops indices from intermediate tables
  custom/icds_reports/migrations/0160_drop_like_indices.py
Labels: product/invisible

#26401 Fix case diff bugs
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/parallel.py
  corehq/apps/couch_sql_migration/rebuildcase.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_parallel.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
Labels: product/invisible

#26385 pillow topic assignments command
  corehq/apps/change_feed/management/commands/pillow_topic_assignments.py
Labels: product/invisible

#26393 change ICDS UCRs to use 'location' filter type instead of 'owner'
  custom/icds_reports/ucr/reports/ls/ls_report_child_names.json
  custom/icds_reports/ucr/reports/ls/ls_report_child_nutrition_status.json
  custom/icds_reports/ucr/reports/ls/ls_report_lbw_pre_term.json
  custom/icds_reports/ucr/reports/ls/ls_report_pregnant_women_names.json
  custom/icds_reports/ucr/reports/mpr/mpr_2bi_preg_delivery_death_list.json
  custom/icds_reports/ucr/reports/mpr/mpr_2bii_child_death_list.json
  custom/icds_reports/ucr/reports/mpr/mpr_2ci_child_birth_list.json
  custom/icds_reports/ucr/reports/other/list_pnc_delivery_complications.json
Labels: product/custom

#26352 use @periodic_task_on_envs decorator
  custom/icds/tasks/__init__.py
  custom/icds/tasks/sms.py
  custom/icds_reports/tasks.py
Labels: product/invisible

#26298 Fix None comparision issue caused by DB errors
  corehq/sql_db/util.py
Labels: product/invisible

#26404 [ci skip] fix indicator name in docs
  corehq/apps/userreports/README.rst
Labels: product/invisible

#26405 ICDS Dashboard: remove leading "Info!" from a bunch of info messages
  custom/icds_reports/templates/icds_reports/icds_app/cas-export.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/download.directive.html
  custom/icds_reports/templates/icds_reports/icds_app/location_filter.html
  custom/icds_reports/templates/icds_reports/icds_app/map-chart.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/location_filter.html
Labels: product/custom

#26407 Don't strip is_location_safe prop from view fn
  corehq/apps/accounting/decorators.py
Labels: product/all-users-all-environments

#26390 Add custom rule criteria for ccs_record cases availing services
  custom/icds/case_relationships.py
  custom/icds/rules/custom_criteria.py
  custom/icds/tests/test_case_relationships.py
  custom/icds/tests/test_custom_rules.py
  settings.py
Labels: product/custom

#26383 ICDS Dashboard: override password reset templates on mobile
  corehq/apps/domain/templates/login_and_password/partials/password_reset_form_only.html
  corehq/apps/domain/templates/login_and_password/password_reset_form.html
  custom/icds_reports/mobile_views.py
  custom/icds_reports/templates/icds_reports/mobile/base_mobile.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
  custom/icds_reports/templates/icds_reports/mobile/mobile_accounts_base.html
  custom/icds_reports/templates/icds_reports/mobile/mobile_login.html
  custom/icds_reports/templates/icds_reports/mobile/mobile_password_reset_done.html
  custom/icds_reports/templates/icds_reports/mobile/mobile_password_reset_form.html
Labels: product/custom

#26406 ICDS Dashboard: Better styling of mobile map legend
  custom/icds_reports/static/css/icds_dashboard.css
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
Labels: product/custom

#26408 Updated linked app pull to allow re-pulling same app on multimaster
  corehq/apps/app_manager/views/utils.py
Labels: product/feature-flag

#26398 Migrate Dhis2Connection from couch to sql (1 of 3)
  corehq/apps/app_manager/management/commands/populate_sql_global_app_config.py
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/motech/dhis2/management/commands/populate_sql_dhis2_connection.py
  corehq/motech/dhis2/migrations/0006_sqldhis2connection.py
  corehq/motech/dhis2/models.py
Labels: product/invisible

#26403 ICDS Dashboard: add maintenance alerts to mobile dashboard
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  custom/icds_reports/static/icds_reports/mobile/css/app.less
  custom/icds_reports/static/icds_reports/mobile/css/filters.less
  custom/icds_reports/templates/icds_reports/icds_app/mobile/location_filter.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
Labels: product/custom

#26420 simplify ES accessors to only fetch required data from ES
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/tests/test_esaccessors.py
  custom/icds/messaging/indicators.py
Labels: product/invisible

#26418 Rankings page info icon
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
Labels: product/custom

#26422 Removed dead code
  corehq/apps/reminders/util.py
Labels: product/invisible

#26326 Migrate ApplicationAccess from couch to sql (1 of 3)
  corehq/apps/cloudcare/management/commands/populate_application_access.py
  corehq/apps/cloudcare/migrations/0001_initial.py
  corehq/apps/cloudcare/migrations/__init__.py
  corehq/apps/cloudcare/models.py
Labels: product/invisible

#26416 Docs: updates to couch_to_sql_models
  docs/couch_to_sql_models.rst
Labels: product/invisible

#26415 Support downloading a subset of location tree
  corehq/apps/locations/forms.py
  corehq/apps/locations/static/locations/js/widgets.js
  corehq/apps/locations/tasks.py
  corehq/apps/locations/templates/locations/filter_and_download.html
  corehq/apps/locations/templates/locations/manage/locations.html
  corehq/apps/locations/templates/locations/manage/partials/autocomplete_select_widget.html
  corehq/apps/locations/urls.py
  corehq/apps/locations/util.py
  corehq/apps/locations/views.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/feature-flag

#26423 Provide default value for skip_cert_verify in SQLDhis2Connection migr…
  corehq/motech/dhis2/management/commands/populate_sql_dhis2_connection.py
Labels: product/invisible

#26007 Remove some hqmedia couch views
  corehq/apps/hqmedia/_design/views/by_domain/map.js
  corehq/apps/hqmedia/_design/views/tags/map.js
  corehq/apps/hqmedia/_design/views/tags/reduce.js
Labels: product/invisible, reindex/migration

#26414 [ICDS Dashbaord] home visit api changes as per new spec
  custom/icds_reports/reports/governance_apis.py
  custom/icds_reports/tests/agg_tests/test_governance_apis.py
  custom/icds_reports/views.py
Labels: product/custom

#26325 [ICDS Dashboard] add another datapoint to gov dashboard API
  custom/icds_reports/const.py
  custom/icds_reports/management/commands/run_aggregation_query.py
  custom/icds_reports/migrations/0158_add_in_month_column.py
  custom/icds_reports/migrations/0161_added_gov_Dashboard_child_cols.py
  custom/icds_reports/migrations/0162_auto_20200115_0733.py
  custom/icds_reports/migrations/sql_templates/database_views/agg_awc_monthly.sql
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/reports/governance_apis.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/outputs/agg_child_health_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/agg_child_health_2017-05-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/child_health_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/child_health_monthly_2017-05-01_sorted.csv
  custom/icds_reports/tests/agg_tests/test_governance_apis.py
  custom/icds_reports/urls.py
  custom/icds_reports/utils/aggregation_helpers/distributed/__init__.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_gov_dashboard.py
  custom/icds_reports/utils/aggregation_helpers/distributed/base.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
  custom/icds_reports/views.py
Labels: product/custom

#26419 ICDS Dashboard: Add two-click chart navigation workflow to mobile
  custom/icds_reports/static/icds_reports/js/spec/indie-map.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/map-or-sector-view.directive.spec.js
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/angular-services/locations.service.js
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-or-sector-view.directive.html
Labels: product/custom

#26430 FIxed date check ON governance dashboard
  custom/icds_reports/views.py
Labels: product/custom

#26417 Limit map zoomout
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/indie-map.directive.html
Labels: product/custom

#26432 Update to django==1.11.27 for security fix
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#26155 Removed SMS forwarding
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/sms/dbaccessors.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/handlers/forwarding.py
  corehq/apps/sms/models.py
  corehq/apps/sms/static/sms/js/add_forwarding_rule.js
  corehq/apps/sms/templates/sms/add_forwarding_rule.html
  corehq/apps/sms/templates/sms/list_forwarding_rules.html
  corehq/apps/sms/tests/test_dbaccessors.py
  corehq/apps/sms/urls.py
  corehq/apps/sms/views.py
  settings.py
Labels: product/invisible

#26427 Fix bulk archive bug
  corehq/apps/data_interfaces/tests/test_xform_management.py
  corehq/apps/data_interfaces/views.py
Labels: product/invisible

#26410 Consolidate case diff logic
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_couch_sql_diff.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
Labels: product/invisible

#26399 Migrate Dhis2Connection from couch to sql (2 of 3)
  corehq/motech/dhis2/dbaccessors.py
  corehq/motech/dhis2/forms.py
  corehq/motech/dhis2/migrations/0007_populate_sqldhis2connection.py
  corehq/motech/dhis2/views.py
Labels: product/invisible

#26435 Stopped fetching case types for edit conditional alert page
  corehq/messaging/scheduling/forms.py
Labels: product/all-users-all-environments

#26424 "Soft" Rollback Data-Typing in Exports
  corehq/ex-submodules/couchexport/util.py
  corehq/ex-submodules/couchexport/writers.py
Labels: product/all-users-all-environments

#26434 Disable new setup of sms/call as a user's default two factor method
  corehq/apps/settings/forms.py
  settings.py
Labels: product/invisible

#26436 Revert "Migrate Dhis2Connection from couch to sql (2 of 3)"
  corehq/motech/dhis2/dbaccessors.py
  corehq/motech/dhis2/forms.py
  corehq/motech/dhis2/migrations/0007_populate_sqldhis2connection.py
  corehq/motech/dhis2/views.py
Labels: product/invisible

#26443 Clear UserReportingMetadataStaging records when users are deleted
  corehq/apps/users/tasks.py
Labels: product/invisible

#26447 Revert "ICDS Dashboard: Add two-click chart navigation workflow to mobile"
  custom/icds_reports/static/icds_reports/js/spec/indie-map.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/map-or-sector-view.directive.spec.js
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/angular-services/locations.service.js
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-or-sector-view.directive.html
Labels: product/custom

#26431 change dashboard css to less and tweak colors
  custom/icds_reports/static/css/fact_sheets.less
  custom/icds_reports/static/css/icds_dashboard.less
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/icds_app/progress-report.directive.html
Labels: product/custom

#26425 make last value available by array agg
  corehq/apps/userreports/const.py
  corehq/apps/userreports/reports/factory.py
  corehq/apps/userreports/reports/specs.py
  corehq/apps/userreports/tests/test_report_aggregation.py
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/all-users-all-environments

#26439 Revert "Revert "Migrate Dhis2Connection from couch to sql (2 of 3)""
  corehq/motech/dhis2/dbaccessors.py
  corehq/motech/dhis2/forms.py
  corehq/motech/dhis2/migrations/0007_populate_sqldhis2connection.py
  corehq/motech/dhis2/views.py
Labels: product/invisible

#26111 add columns for data pull
  custom/icds_reports/migrations/0163_update_agg_awc_monthly_view.py
  custom/icds_reports/migrations/sql_templates/database_views/agg_awc_monthly.sql
  custom/icds_reports/models/views.py
Labels: ICDS: Data Pull Request, product/custom

#26433 DRY up configuration for less_debug
  corehq/apps/cloudcare/templates/formplayer-common/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/less_debug.html
  corehq/apps/styleguide/templates/styleguide/base.html
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/mobile/base_mobile.html
Labels: product/invisible

#26412 Renamed incorrect case property in ICDS data sources
  custom/icds_reports/ucr/data_sources/ccs_record_cases_monthly_v2.json
  custom/icds_reports/ucr/data_sources/child_cases_monthly_v2.json
Labels: product/custom

#26451 Reference make requirements in CONTRIBUTING.rst
  CONTRIBUTING.rst
Labels: product/invisible

#26453 Improve submission throughput for domains sharing an enterprise account
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/tests/test_get_n_users_for_rate_limiting.py
Labels: product/invisible

#26457 Fixed syntax error in formplayer-common.base.html
  corehq/apps/cloudcare/templates/formplayer-common/base.html
Labels: product/invisible

#26456 Upgrade pip-tools to fix `make requirements` test
  requirements-python3/dev-requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
Labels: product/invisible

#26446 [ICDS Dashboard]: Close nav menu when clicked outside
  custom/icds_reports/static/js/directives/nav-menu-opener/nav-menu-opener.directive.js
  custom/icds_reports/static/js/icds_app_mobile.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/nav-menu-opener.directive.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
Labels: product/custom

#26449 fix two click charts
  custom/icds_reports/static/icds_reports/js/spec/indie-map.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/map-or-sector-view.directive.spec.js
  custom/icds_reports/static/icds_reports/mobile/css/map-chart.less
  custom/icds_reports/static/js/angular-services/baseControllers.service.js
  custom/icds_reports/static/js/angular-services/locations.service.js
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/static/js/directives/map-or-sector-view/map-or-sector-view.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-or-sector-view.directive.html
Labels: product/custom

#26460 Set serializer to picker
  custom/icds_reports/tasks.py
Labels: product/custom

#26438 Couch to SQL: mostly changes for case diffs
  corehq/apps/couch_sql_migration/casediff.py
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/management/commands/unsort_sql_cases.py
  corehq/apps/couch_sql_migration/rebuildcase.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_asyncforms.py
  corehq/apps/couch_sql_migration/tests/test_casediff.py
  corehq/apps/couch_sql_migration/tests/test_couch_sql_diff.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_rebuildcase.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
  corehq/apps/tzmigration/planning.py
  corehq/apps/tzmigration/timezonemigration.py
Labels: product/invisible

#26421 [INDDEX] Create drafts of new reports with hardcoded data
  custom/inddex/__init__.py
  custom/inddex/filters.py
  custom/inddex/reports/__init__.py
  custom/inddex/reports/gaps_report_by_item.py
  custom/inddex/reports/gaps_summary_by_food_type.py
  custom/inddex/reports/nutrient_intakes.py
  custom/inddex/reports/summary_statistics_report.py
  custom/inddex/sqldata.py
  custom/inddex/templates/inddex/multi_report.html
  custom/inddex/templates/inddex/partials/report_table.html
  custom/inddex/templates/inddex/tabular_report.html
  custom/inddex/ucr/__init__.py
  custom/inddex/ucr/data_providers/__init__.py
  custom/inddex/ucr/data_providers/gaps_report_by_item_data.py
  custom/inddex/ucr/data_providers/gaps_summary_data.py
  custom/inddex/ucr/data_providers/mixins.py
  custom/inddex/ucr/data_providers/nutrient_intakes_data.py
  custom/inddex/ucr/data_providers/summary_statistics_data.py
  custom/inddex/ucr/data_sources/food_consumption_indicators.json
  custom/inddex/utils.py
  settings.py
Labels: product/custom

#26455 form processing DB access tweaks
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/models.py
  corehq/form_processor/tests/test_form_dbaccessor.py
  corehq/util/test_utils.py
Labels: product/invisible

#26463 Fixed thr test cases
  custom/icds_reports/tests/agg_tests/test_export_data.py
Labels: product/invisible

#26471 [reports / analytics / esaccessors] make sure form.@name is never null
  corehq/apps/reports/analytics/esaccessors.py
Labels: product/all-users-all-environments, product/invisible

#26466 [Excel Formatting] Add feature flag to enable export data typing on form and case exports
  corehq/apps/export/export.py
  corehq/apps/export/models/new.py
  corehq/apps/export/static/export/js/models.js
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/ex-submodules/couchexport/export.py
  corehq/ex-submodules/couchexport/tests/test_excel_format_value.py
  corehq/ex-submodules/couchexport/util.py
  corehq/ex-submodules/couchexport/writers.py
  corehq/toggles.py
Labels: product/all-users-all-environments, product/feature-flag

#26470 Switch saas rate limiting to use RATE_LIMIT_SUBMISSIONS setting
  corehq/apps/receiverwrapper/rate_limiter.py
  settings.py
Labels: product/invisible

#26475 ICDS Dashboard: Nav menu options unclickable (Bug)
  custom/icds_reports/static/icds_reports/mobile/css/navigation-menu.less
Labels: product/custom

#26472 Fixed dropdown that isn't searching
  corehq/messaging/scheduling/forms.py
Labels: product/feature-flag

#26478 Only include launched awcs
  custom/icds_reports/views.py
Labels: product/custom

#26464 reduce hits to plproxy (part 1)
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/tests/test_case_dbaccessor.py
  corehq/form_processor/tests/test_form_dbaccessor.py
  corehq/form_processor/tests/test_serialization.py
Labels: product/invisible

#26461 [ICDS Dashboard] Add new CBE fields
  custom/icds_reports/ucr/data_sources/cbe_form.json
  custom/icds_reports/ucr/tests/data/cbe_form_annaprasan_diwas.xml
  custom/icds_reports/ucr/tests/data/cbe_form_coming_of_age.xml
  custom/icds_reports/ucr/tests/data/cbe_form_public_health_message.xml
  custom/icds_reports/ucr/tests/data/cbe_form_suposhan_diwas.xml
  custom/icds_reports/ucr/tests/test_cbe_form_ucr.py
Labels: product/custom

#26468 INDDEX reports simplifications
  custom/inddex/reports/nutrient_intakes.py
  custom/inddex/reports/summary_statistics_report.py
  custom/inddex/sqldata.py
  custom/inddex/utils.py
Labels: product/custom

#26458 Attempt not to 429 burst submissions if a delay will do
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/project_limits/rate_limiter.py
Labels: product/invisible

#26473 Removed couch_class from PopulateSQLCommand
  corehq/apps/app_manager/management/commands/populate_sql_global_app_config.py
  corehq/apps/app_manager/migrations/0009_add_sqlglobalappconfig.py
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/cloudcare/management/commands/populate_application_access.py
  corehq/motech/dhis2/management/commands/populate_sql_dhis2_connection.py
Labels: product/invisible

#26476 ICDS Dashboard: remove info button
  custom/icds_reports/templates/icds_reports/icds_app/mobile/map-chart.html
Labels: product/custom

#26484 ICDS Dashboard: Backlog from 26160
  custom/icds_reports/static/icds_reports/js/spec/adhaar-beneficiary.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/adolescent-girls.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/adult-weight-scale.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/awc-daily-status.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/awc-reports.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/awcs-covered.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/children-initiated.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/clean-water.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/early_initiation_breastfeeding.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/enrolled-children.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/enrolled-women.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/exlusive-breastfeeding.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/functional-toilet.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/immunization_coverage.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/indie-map.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/infantometer.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/infants-weight-scale.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/institutional-deliveries.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/lactating-enrolled-women.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/map-or-sector-view.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/medicine-kit.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/newborn_with_low_weight.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/prevalence-of-severe-report.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/prevalence-of-stunting-report.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/registered-household.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/stadiometer.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/underweight-children-report.directive.spec.js
  custom/icds_reports/static/icds_reports/js/spec/utils.js
Labels: product/custom

#26474 resolve map issues when district name is duplicated across states
  custom/icds_reports/management/commands/find_duplicate_district_topojsons.py
  custom/icds_reports/static/js/angular-services/topojson.service.js
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/static/js/topojsons/README.md
  custom/icds_reports/static/js/topojsons/blocks/bihar_blocks_v3.topojson
  custom/icds_reports/static/js/topojsons/blocks/chhattisgarh_blocks_v3.topojson
  custom/icds_reports/static/js/topojsons/blocks/himachal_pradesh_blocks_v3.topojson
  custom/icds_reports/static/js/topojsons/blocks/karnataka_blocks_v3.topojson
  custom/icds_reports/static/js/topojsons/blocks/maharashtra_blocks_v3.topojson
  custom/icds_reports/static/js/topojsons/blocks/rajasthan_blocks_v3.topojson
  custom/icds_reports/static/js/topojsons/blocks/uttar_pradesh_blocks_v3.topojson
  custom/icds_reports/tests/test_views_location_filter.py
  custom/icds_reports/utils/topojson_util/README.md
  custom/icds_reports/utils/topojson_util/topojson_util.py
  custom/icds_reports/views.py
Labels: product/custom

#26488 Convert password to bytes
  corehq/motech/dhis2/forms.py
Labels: product/invisible

#26482 Multimaster: add overrides when copying master app
  corehq/apps/app_manager/suite_xml/post_process/resources.py
  corehq/apps/app_manager/tests/test_suite_resource_overrides.py
  corehq/apps/linked_domain/applications.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/urls.py
  corehq/apps/linked_domain/views.py
  custom/icds/management/commands/copy_icds_app.py
Labels: product/feature-flag

#26491 bump version
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/custom

#26490 Updated app_manager README
  corehq/apps/app_manager/README.md
Labels: product/invisible

#26469 Removed ExportMigrationMeta
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/export/models/__init__.py
  corehq/apps/export/models/new.py
Labels: product/invisible

#26480 Kill wisepill
  corehq/apps/cleanup/deletable_doc_types.py
  custom/apps/wisepill/__init__.py
  custom/apps/wisepill/_design/views/device/map.js
  custom/apps/wisepill/_design/views/device_event/map.js
  custom/apps/wisepill/models.py
  custom/apps/wisepill/urls.py
  custom/apps/wisepill/views.py
  settings.py
  testapps/test_pillowtop/tests/test_pillows_cases.py
  urls.py
Labels: product/custom

#26492 DRY up django migrations for couch to SQL model migration
  corehq/apps/app_manager/management/commands/populate_sql_global_app_config.py
  corehq/apps/app_manager/migrations/0010_sqlglobalappconfig.py
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/cloudcare/management/commands/populate_application_access.py
  corehq/apps/cloudcare/migrations/0002_sqlapplicationaccess.py
  corehq/motech/dhis2/management/commands/populate_sql_dhis2_connection.py
  corehq/motech/dhis2/migrations/0007_populate_sqldhis2connection.py
Labels: product/invisible

#26445 pick non null out of new and old values
  corehq/apps/ota/views.py
  corehq/apps/users/migrations/0007_userreportingmetadatastaging_created_on.py
  corehq/apps/users/models.py
  corehq/apps/users/tasks.py
  corehq/pillows/synclog.py
Labels: product/invisible

#26494 Unblock saved exports by detecting missing/expired task
  corehq/ex-submodules/soil/progress.py
Labels: product/invisible

#26462 update contrib
  CONTRIBUTING.rst
Labels: product/invisible

#26496 Removed dead code
  corehq/apps/reports/views.py
  corehq/apps/users/models.py
  corehq/ex-submodules/dimagi/utils/couch/loosechange.py
Labels: product/invisible

#26497 Yet another icds copy app command
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/suite_xml/post_process/resources.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/linked_domain/applications.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/urls.py
  corehq/apps/linked_domain/views.py
  custom/icds/management/commands/copy_icds_app_1_of_2.py
  custom/icds/management/commands/copy_icds_app_2_of_2.py
Labels: product/feature-flag

#26382 add mgmt command to populate mother name
  custom/icds/management/commands/populate_mother_name.py
  custom/icds/management/commands/sanitize_phone_numbers.py
Labels: product/custom

#26485 ICDS Dashboard: removing info icon in chart page(web)
  custom/icds_reports/templates/icds_reports/icds_app/map-chart.html
Labels: product/custom

#26489 report fixture index
  corehq/apps/app_manager/fixtures/mobile_ucr.py
  corehq/apps/app_manager/tests/test_report_config.py
  corehq/apps/app_manager/tests/test_report_fixtures_provider.py
  corehq/apps/ota/tests/test_app_aware_restore.py
Labels: product/feature-flag

#26368 [ICDS Dashboard] Added vhnds api for governance dashboard
  custom/icds_reports/const.py
  custom/icds_reports/migrations/0164_auto_20200123_0702.py
  custom/icds_reports/models/aggregate.py
  custom/icds_reports/reports/governance_apis.py
  custom/icds_reports/tests/agg_tests/test_governance_apis.py
  custom/icds_reports/urls.py
  custom/icds_reports/utils/aggregation_helpers/distributed/agg_gov_dashboard.py
  custom/icds_reports/views.py
Labels: product/custom

#26498 Fixed typo [ci skip]
  corehq/apps/app_manager/forms.py
Labels: product/feature-flag
