Repository dimagi/commcare-hq, pull requests merged in 2020-07, with the labels that each got.

#27846 added another field for datetime timeend
  custom/icds_reports/ucr/data_sources/dashboard/delivery_forms.json
  custom/icds_reports/ucr/tests/test_delivery_form_ucr.py
Labels: product/custom

#28005 Convert unfinishedsubmissionstub.id to bigint
  corehq/ex-submodules/couchforms/migrations/0008_auto_20200701_0742.py
  corehq/ex-submodules/couchforms/models.py
Labels: product/invisible

#27995 use single cache for app version info
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_util.py
  corehq/apps/ota/views.py
Labels: product/invisible

#28006 don't assume request has a domain
  corehq/apps/domain/auth.py
Labels: product/all-users-all-environments

#27997 [ICDS Dashboard] exclude those kids from wasting numerator whose height is not measured
  custom/icds_reports/tests/agg_tests/outputs/agg_child_health_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/child_health_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/reports/test_maternal_child_data.py
  custom/icds_reports/tests/agg_tests/reports/test_prevalence_of_severe.py
  custom/icds_reports/tests/agg_tests/test_export_data.py
  custom/icds_reports/tests/agg_tests/test_fact_sheet_report.py
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
Labels: product/custom

#27983 Prevent linking to domains with existing report links
  corehq/apps/linked_domain/ucr.py
  corehq/apps/userreports/templates/userreports/edit_report_config.html
  corehq/apps/userreports/templates/userreports/partials/link_reports.html
  corehq/apps/userreports/views.py
Labels: product/feature-flag

#28002 Add a few utility functions for old couch revs
  corehq/util/couch.py
Labels: product/invisible

#28004 Fixed linked project history for lookup tables
  corehq/apps/app_manager/views/utils.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/views.py
  corehq/apps/userreports/views.py
Labels: product/feature-flag

#28009 Allows searching and viewing the date a case was closed in CLE
  corehq/apps/case_search/const.py
Labels: product/feature-flag

#28013 Update Formplayer instructions in DEV_SETUP.md
  DEV_SETUP.md
Labels: product/invisible

#28008 Cache the National aggregate data on redis level
  custom/icds_reports/reports/fact_sheets.py
  custom/icds_reports/sqldata/agg_ccs_record_monthly.py
Labels: product/custom

#28017 Revert "Prevent linking to domains with existing report links"
  corehq/apps/linked_domain/ucr.py
  corehq/apps/userreports/templates/userreports/edit_report_config.html
  corehq/apps/userreports/templates/userreports/partials/link_reports.html
  corehq/apps/userreports/views.py
Labels: product/all-users-all-environments

#28019 Ignore Formplayer settings filename
  .gitignore
Labels: product/invisible

#27860 Fix timezone fallback
  corehq/apps/domain/static/domain/js/my_project_settings.js
  corehq/util/timezones/tests/__init__.py
  corehq/util/timezones/tests/test_utils.py
  corehq/util/timezones/utils.py
Labels: product/custom

#28024 install yarn in docker image so that tests pass
  Dockerfile
Labels: product/invisible

#28026 add phantomjs-prebuilt with yarn
  Dockerfile
Labels: product/invisible

#28025 Revert "Couch to SQL migration: Custom Data Fields (2 of 3)"
  corehq/apps/app_manager/app_schemas/case_properties.py
  corehq/apps/custom_data_fields/README.rst
  corehq/apps/custom_data_fields/dbaccessors.py
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/custom_data_fields/management/commands/populate_custom_data_fields.py
  corehq/apps/custom_data_fields/migrations/0002_populate_customdatafieldsdefinition.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/locations/fixtures.py
  corehq/apps/locations/tests/test_bulk_management.py
  corehq/apps/locations/tests/test_export.py
  corehq/apps/locations/tests/test_location_fixtures.py
  corehq/apps/locations/util.py
  corehq/apps/products/fixtures.py
  corehq/apps/products/forms.py
  corehq/apps/products/views.py
  corehq/apps/users/bulk_download.py
  corehq/apps/users/custom_data.py
Labels: product/invisible

#28027 Revert "Revert "Couch to SQL migration: Custom Data Fields (2 of 3)""
  corehq/apps/app_manager/app_schemas/case_properties.py
  corehq/apps/custom_data_fields/README.rst
  corehq/apps/custom_data_fields/dbaccessors.py
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/custom_data_fields/management/commands/populate_custom_data_fields.py
  corehq/apps/custom_data_fields/migrations/0002_populate_customdatafieldsdefinition.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/locations/fixtures.py
  corehq/apps/locations/tests/test_bulk_management.py
  corehq/apps/locations/tests/test_export.py
  corehq/apps/locations/tests/test_location_fixtures.py
  corehq/apps/locations/util.py
  corehq/apps/products/fixtures.py
  corehq/apps/products/forms.py
  corehq/apps/products/views.py
  corehq/apps/users/bulk_download.py
  corehq/apps/users/custom_data.py
Labels: product/invisible

#28028 Updated commit_adding_migration for custom data fields [ci skip]
  corehq/apps/custom_data_fields/management/commands/populate_custom_data_fields.py
Labels: product/invisible

#27937 Set multiprocess_mode for Prometheus gauge metrics
  corehq/apps/analytics/tasks.py
  corehq/apps/case_importer/tasks.py
  corehq/apps/couch_sql_migration/tasks.py
  corehq/apps/hqwebapp/tasks.py
  corehq/apps/hqwebapp/two_factor_gateways.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/apps/reports/tasks.py
  corehq/apps/sms/tasks.py
  corehq/apps/userreports/tasks.py
  corehq/apps/users/tasks.py
  corehq/celery_monitoring/heartbeat.py
  corehq/celery_monitoring/signals.py
  corehq/ex-submodules/dimagi/utils/django/email.py
  corehq/ex-submodules/pillow_retry/tasks.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  corehq/ex-submodules/pillowtop/tasks.py
  corehq/form_processor/management/commands/run_submission_reprocessing_queue.py
  corehq/form_processor/tasks.py
  corehq/motech/repeaters/tasks.py
  corehq/pillows/tasks.py
  corehq/util/metrics/__init__.py
  corehq/util/metrics/const.py
  corehq/util/metrics/metrics.py
  corehq/util/metrics/prometheus.py
Labels: product/custom

#28030 update translation
  custom/icds_reports/ucr/reports/mpr/mpr_2bi_preg_delivery_death_list.json
  custom/icds_reports/ucr/reports/mpr/mpr_2bii_child_death_list.json
  custom/icds_reports/ucr/reports/mpr/mpr_2ci_child_birth_list.json
Labels: product/custom

#28035 Return a query object when getting ids
  corehq/apps/reports/standard/cases/utils.py
Labels: product/invisible

#27988 Add itemset selection to case search
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#28029 Fixed product comparison
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/products/forms.py
Labels: product/feature-flag

#28023 Fixes for update_domain_date
  corehq/apps/users/tasks.py
  corehq/apps/users/tests/test_tasks.py
Labels: product/invisible

#28022 remove legacy tableau code
  custom/icds_reports/const.py
  custom/icds_reports/exceptions.py
  custom/icds_reports/views.py
  settings.py
Labels: product/invisible

#28021 move ICDS code referenced by CommCare to new app
  corehq/apps/data_interfaces/dispatcher.py
  corehq/apps/reports/filters/fixtures.py
  corehq/apps/sms/urls.py
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/users/forms.py
  corehq/blobs/migrate_metadata.py
  corehq/blobs/tests/test_migrate_metadata.py
  corehq/tabs/tabclasses.py
  custom/icds/const.py
  custom/icds/location_reassignment/views.py
  custom/icds/tasks/sms.py
  custom/icds/urls.py
  custom/icds/views/custom_sms_report.py
  custom/icds/views/hosted_ccz.py
  custom/icds_core/__init__.py
  custom/icds_core/const.py
  custom/icds_core/db.py
  custom/icds_core/view_utils.py
  custom/icds_reports/dashboard_utils.py
  custom/icds_reports/migrations/0119_distribute_tables.py
  custom/icds_reports/migrations/0156_auto_20191217_0932.py
  custom/icds_reports/migrations/0165_auto_20200131_1000.py
  custom/icds_reports/migrations/0172_auto_20200312_0606.py
  custom/icds_reports/permissions.py
  custom/icds_reports/tasks.py
  custom/icds_reports/tests/agg_tests/agg_setup.py
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/utils/migrations.py
  custom/icds_reports/views.py
Labels: product/invisible

#28040 Prevent linking to domains with existing report links, take 2
  corehq/apps/linked_domain/ucr.py
  corehq/apps/userreports/templates/userreports/edit_report_config.html
  corehq/apps/userreports/templates/userreports/partials/link_reports.html
  corehq/apps/userreports/views.py
Labels: product/feature-flag

#28037 Add email address to the enterprise dashboard mobile worker report
  corehq/apps/accounting/enterprise.py
Labels: product/invisible

#27991 Use username for API_THROTTLE_WHITELIST
  corehq/apps/api/resources/auth.py
  corehq/apps/api/tests/core_api.py
  corehq/apps/domain/auth.py
Labels: product/feature-flag

#28020 Pull data monthly in fact sheet
  custom/icds_reports/reports/fact_sheets.py
  custom/icds_reports/sqldata/agg_awc_monthly.py
  custom/icds_reports/sqldata/agg_ccs_record_monthly.py
  custom/icds_reports/sqldata/agg_child_health_monthly.py
Labels: product/custom

#28041 Override support email on mobile for non-Dimagi envs
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/profile.xml
  corehq/apps/app_manager/tests/test_profile.py
Labels: product/invisible

#28049 Make web user lookup search case-insensitive
  corehq/apps/hqadmin/views/users.py
Labels: product/admin

#28047 Don't translate placeholders
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
Labels: product/invisible

#28046 Tweaks to make Citus and Kafka work on rootless docker
  docker/hq-compose-citus.yml
  docker/hq-compose-services.yml
  docker/hq-compose.yml
Labels: product/invisible

#28048 Add test for query_location_restricted_cases
  corehq/apps/reports/tests/test_esaccessors.py
Labels: product/invisible

#28044 always include app tag
  corehq/ex-submodules/casexml/apps/phone/restore.py
Labels: product/invisible

#28053 Remove non-existent --list parameter
  corehq/sql_db/management/commands/migrate_multi.py
Labels: product/invisible

#27848 add test coverage for users-es-accessors
  corehq/apps/es/users.py
  corehq/apps/export/forms.py
  corehq/apps/export/tests/test_export_forms.py
  corehq/apps/locations/dbaccessors.py
  corehq/apps/locations/models.py
  corehq/apps/locations/tasks.py
  corehq/apps/locations/tests/test_dbaccessors.py
  corehq/apps/reports/standard/cases/utils.py
Labels: product/invisible

#28043 [ICDS Dashboard]: Fixes in the tabular reports
  custom/icds_reports/static/js/directives/download/download.directive.js
Labels: product/custom

#28051 Added high-level docs to corehq/toggles.py
  corehq/toggles.py
Labels: product/invisible

#28062 [ci skip] add a bit more info about ptop and celery
  DEV_SETUP.md
Labels: product/invisible

#28039 log as error
  corehq/messaging/scheduling/scheduling_partitioned/models.py
Labels: product/all-users-all-environments

#28045 Added Child task case ucr to reconciliation script
  custom/icds_reports/models/util.py
Labels: product/custom

#28011 Removed polling from messaging dashboard
  corehq/messaging/scheduling/static/scheduling/js/dashboard.js
Labels: product/all-users-all-environments

#28060 [ICDS Dashboard] Pull the phone number from the person case ucr
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/tests/agg_tests/fixtures/child_cases.csv
  custom/icds_reports/tests/agg_tests/fixtures/person_cases.csv
  custom/icds_reports/tests/agg_tests/outputs/child_health_monthly_2017-04-01_sorted.csv
  custom/icds_reports/tests/agg_tests/outputs/child_health_monthly_2017-05-01_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/child_health_monthly.py
Labels: product/custom

#28064 Removed Schedule Once widget
  corehq/apps/domain/templates/domain/current_subscription.html
  corehq/apps/domain/templates/domain/partials/schedule_once.html
Labels: product/prod-india-all-users

#28070 Allow docker tests to be run more than once
  CITUSDB_SETUP.md
  docker/hq-compose-citus.yml
  docker/hq-compose.yml
  docker/localsettings.py
  scripts/docker
Labels: product/invisible

#28057 Missing FuzzyProperties breaks FK constraint
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#27962 recreate Table object
  corehq/apps/aggregate_ucrs/ingestion.py
  corehq/apps/aggregate_ucrs/models.py
  corehq/apps/callcenter/queries.py
  corehq/apps/userreports/sql/adapter.py
Labels: product/invisible

#27994 [ICDS Dashboard]: Including new reports in the dashboard usage reports
  custom/icds_reports/management/commands/dashboard_usage_report.py
Labels: product/invisible

#28063 add overview sections to docs and update index
  docs/databases.rst
  docs/images/functional_architecture.png
  docs/images/repeaters_flow.png
  docs/images/reporting_architecture.png
  docs/index.rst
  docs/overview/architecture.rst
  docs/overview/platform.rst
Labels: product/invisible

#28071 Add up_nrhm to new domain (on india)
  settings.py
Labels: product/invisible

#28014 Add management command to inspect max-val of id column for db tables
  corehq/sql_db/management/commands/print_max_id_of_pg_tables.py
Labels: product/invisible

#28073 CouchDataLoader.__init__() missing param
  corehq/apps/dump_reload/couch/load.py
Labels: product/invisible

#28069 Pull data monthly on clean water chart view
  custom/icds_reports/reports/clean_water.py
Labels: product/custom

#28054 delete old sms events daily on ICDS
  custom/icds/tasks/sms.py
  custom/icds/tests/test_delete_sms_events.py
Labels: product/custom

#28076 Remove the inter dependency of test cases
  custom/icds_reports/tests/agg_tests/__init__.py
  custom/icds_reports/tests/agg_tests/agg_setup.py
  custom/icds_reports/tests/agg_tests/reports/test_bihar_api_demographics.py
  custom/icds_reports/tests/agg_tests/reports/test_bihar_api_mother_details.py
Labels: product/custom

#28055 allow adding values via localsettings and remove ICDS values
  custom/icds/tests/test_custom_content.py
  custom/icds/tests/test_custom_recipients.py
  custom/icds/tests/test_custom_rules.py
  settings.py
Labels: Open for review: do not merge

#28061 fix and document case importer management command
  corehq/apps/case_importer/management/commands/import_cases.py
Labels: product/invisible

#28077 allow session auth and check permissions on report API
  corehq/apps/api/resources/v0_5.py
Labels: product/all-users-all-environments

#28052 Removed expanded audio from formbuilder
  corehq/apps/app_manager/management/commands/get_domains_with_itext_usage.py
  corehq/apps/app_manager/tests/data/suite/app_expanded_audio.json
  corehq/apps/app_manager/tests/test_media_suite.py
  corehq/apps/app_manager/xform.py
Labels: product/invisible

#28082 Removed dead code in cloudcare
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
Labels: product/invisible

#28079 Updated messaging docs to reflect "new" reminders framework
  docs/messaging/messaging.rst
  docs/messaging/reminders.rst
  docs/messaging/schedules.rst
Labels: product/invisible

#28072 Only dump messaging backend mappings that have domain backends
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/sql/filters.py
  corehq/apps/dump_reload/sql/load.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#28084 Bump statici18n to version supporting Django 2.2
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
Labels: product/invisible

#28075 [ICDS Dashboard] Pull the program summary data on the same level
  custom/icds_reports/utils/__init__.py
  custom/icds_reports/views.py
Labels: product/custom

#28087 Fix sorting for FCT count column
  corehq/apps/reports/standard/monitoring.py
Labels: product/all-users-all-environments

#28083 Added exception handling for mismatched rows in CSV bulk upload
  corehq/apps/case_importer/views.py
  corehq/util/workbook_reading/adapters/raw_data.py
  corehq/util/workbook_reading/tests/files/csv/mixed.csv
  corehq/util/workbook_reading/tests/test_errors.py
Labels: product/invisible

#28066 Avoid line break before long report names
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/forms.less
Labels: product/all-users-all-environments

#28080 CEP docs
  CONTRIBUTING.rst
  docs/cep.rst
  docs/index.rst
Labels: product/invisible

#28081 minor refactor to UITab classes
  corehq/apps/styleguide/tabs.py
  corehq/tabs/tabclasses.py
  corehq/tabs/uitab.py
  corehq/tabs/utils.py
Labels: product/invisible

#27850 [ICDS Dashboard]use Datetime field delivery form
  custom/icds_reports/tests/agg_tests/fixtures/delivery_form.csv
  custom/icds_reports/tests/agg_tests/outputs/ccs_record_monthly_2017-05-01_sorted.csv
  custom/icds_reports/utils/aggregation_helpers/distributed/delivery_forms.py
  custom/icds_reports/utils/aggregation_helpers/tests/sql_output/delivery-forms.distributed.txt
Labels: product/custom

#28098 Remove m4change custom reports from settings.py
  settings.py
Labels: product/invisible

#28042 Couch to SQL migration verification
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/cleanup/tests/test_couch_to_sql_custom_data_fields.py
  corehq/apps/custom_data_fields/management/commands/populate_custom_data_fields.py
  corehq/apps/custom_data_fields/models.py
  corehq/ex-submodules/dimagi/utils/couch/migration.py
Labels: product/invisible

#28000 Added account name filter to SMS Billing Report
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/select2s.less
  corehq/apps/reports/static/reports/js/filters/select2s.js
  corehq/apps/reports/templates/reports/filters/single_option.html
  corehq/apps/smsbillables/interface.py
Labels: QA Passed, product/prod-india-all-users

#27998 Updates in ICDS staging deploy process
  scripts/commit-icds-staging
  scripts/commit-staging-util
  scripts/icds-staging.yaml
  scripts/rebuild-icds-staging
  scripts/rebuildstaging-util
  scripts/staging.yaml
Labels: product/invisible

#28097 Add Vectorlink reports for Côte d'Ivoire
  custom/abt/reports/data_sources/late_pmt.json
  custom/abt/reports/data_sources/sms_case.json
  custom/abt/reports/data_sources/supervisory_v2019.json
  custom/abt/reports/sms_indicator_report.json
  custom/abt/reports/spray_progress_country.json
  custom/abt/reports/spray_progress_level_1.json
  custom/abt/reports/spray_progress_level_2.json
  custom/abt/reports/spray_progress_level_3.json
  custom/abt/reports/spray_progress_level_4.json
  custom/abt/reports/supervisory_report_v2019.json
  settings.py
Labels: product/invisible

#28092 push metrics after celery task complete
  corehq/celery_monitoring/signals.py
  corehq/util/metrics/__init__.py
  corehq/util/metrics/metrics.py
  corehq/util/metrics/prometheus.py
Labels: product/invisible

#28059 formplayer geowidget from google maps to mapbox
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entrycontrols_full_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/main.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/cloudcare/views.py
  corehq/apps/hqwebapp/static/cloudcare/css/webforms.css
  corehq/apps/reports/static/reports/js/edit_submission.js
  corehq/apps/reports/templates/reports/form/edit_submission.html
  corehq/apps/reports/views.py
  settings.py
Labels: product/all-users-all-environments

#28074 Make Volatility Warnings Persistent
  corehq/apps/cloudcare/static/cloudcare/js/util.js
Labels: product/feature-flag

#28110 Extracted partials from custom_data_fields.html
  corehq/apps/custom_data_fields/templates/custom_data_fields/custom_data_fields.html
  corehq/apps/custom_data_fields/templates/custom_data_fields/partials/fields_tab.html
  corehq/apps/custom_data_fields/templates/custom_data_fields/partials/modal_delete.html
  corehq/apps/custom_data_fields/templates/custom_data_fields/partials/purge_existing_fields.html
Labels: product/invisible

#28106 remove myself from a soft assert
  corehq/util/metrics/prometheus.py
Labels: product/invisible

#28067 Remove link from usernames when user don't have form view permissions
  corehq/apps/reports/standard/monitoring.py
Labels: product/all-users-all-environments

#28107 don't crash on UCR report API if there are prefilters
  corehq/apps/api/resources/v0_5.py
Labels: product/all-users-all-environments

#28104 Track unretire
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/retire.py
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#28116 Renamed variable
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#28114 Added tests for bulk user download
  corehq/apps/users/bulk_download.py
  corehq/apps/users/tests/test_download.py
Labels: product/invisible

#28090 Web users invitations search and pagination
  corehq/apps/users/static/users/js/web_users.js
  corehq/apps/users/templates/users/web_users.html
  corehq/apps/users/views/__init__.py
Labels: QA Passed, product/all-users-all-environments

#28115 Fix Subscription Renewal Workflow
  corehq/apps/accounting/models.py
  corehq/apps/accounting/templates/accounting/partials/confirm_plan_summary.html
  corehq/apps/domain/templates/domain/base_change_plan.html
  corehq/apps/domain/templates/domain/confirm_subscription_renewal.html
  corehq/apps/domain/templates/domain/renew_plan.html
  corehq/apps/domain/views/accounting.py
  corehq/apps/hqwebapp/static/accounting/less/pricing-main.less
Labels: QA post deploy, product/prod-india-all-users

#28122 explicit kw is needed for Django 2.2
  corehq/apps/registration/forms.py
Labels: product/invisible

#28129 Fixed links to old js-guide repository
  corehq/apps/analytics/README.md
  docs/js-guide/code-organization.md
  docs/js-guide/integration-patterns.md
  docs/js-guide/migrating.md
Labels: product/invisible

#28112 Updated custom_data_fields.js to match standards
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
Labels: product/invisible

#28111 Migrated KeyValList and InputMap to RequireJS
  corehq/apps/groups/templates/groups/group_members.html
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-input-map.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-key-val-list.js
Labels: product/invisible

#28126 Backward-compatible Django 2.2 updates (part 2)
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/ex-submodules/casexml/apps/case/tests/test_multimedia.py
  corehq/form_processor/models.py
  corehq/sql_db/config.py
  custom/icds_reports/tests/agg_tests/reports/test_awc_reports.py
Labels: product/invisible

#28130 Backward-compatible Django 2.2 updates (part 3)
  corehq/apps/data_interfaces/views.py
  corehq/apps/hqwebapp/urls.py
  corehq/sql_db/models.py
  corehq/sql_db/routers.py
Labels: product/invisible

#28131 Backward-compatible Django 2.2 updates (part 4)
  corehq/form_processor/tests/utils.py
  corehq/tests/noseplugins/patches.py
  custom/icds_reports/tests/agg_tests/__init__.py
Labels: product/invisible

#28134 Fixed js-guide links for real this time
  corehq/apps/analytics/README.md
  docs/js-guide/code-organization.md
  docs/js-guide/integration-patterns.md
  docs/js-guide/migrating.md
Labels: product/invisible

#28139 Adapt AWC report tests to Django 2.2
  custom/icds_reports/tests/agg_tests/reports/test_awc_reports.py
Labels: product/invisible

#27955 Fix progress bar for messaging rules
  corehq/apps/data_interfaces/tests/test_scheduling_integration.py
  corehq/messaging/tasks.py
  corehq/messaging/util.py
Labels: product/all-users-all-environments

#28128 management command to search kafka change feed
  corehq/ex-submodules/pillowtop/management/commands/search_kafka_changes.py
Labels: product/invisible

#28135 Updated last_deploy script to handle icds-staging
  scripts/last_deploy.sh
Labels: product/invisible

#28109 Fixed spacing on download message
  corehq/apps/hqwebapp/templates/hqwebapp/partials/shared_download_status.html
Labels: product/all-users-all-environments

#28100 Fix Issue Triggering customer invoices when domains have been deleted
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/tests/test_customer_invoicing.py
  corehq/apps/domain/dbaccessors.py
Labels: product/invisible

#28127 remove ga for hipaa domains
  corehq/util/context_processors.py
Labels: product/all-users-all-environments

#28144 Added Nirmal district to Telangana
  custom/icds_reports/static/js/topojsons/districts_v4.topojson
Labels: product/custom

#28145 Marked ADD_USERS_FROM_LOCATION deprecated
  corehq/toggles.py
Labels: product/admin

#28136 Added more docs for linked domains
  corehq/apps/linked_domain/README.md
Labels: product/invisible

#28012 Move from Bower/NPM to Yarn
  .bowerrc
  .gitignore
  DEV_SETUP.md
  Dockerfile
  bower.json
  corehq/apps/app_manager/templates/app_manager/partials/xpathValidator.html
  corehq/apps/app_manager/xpath_validator/nodejs/xpathConfig.js
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/management/commands/fix_less_imports_collectstatic.py
  corehq/apps/hqwebapp/static/accounting/less/pricing.less
  corehq/apps/hqwebapp/static/app_manager/less/app_manager.less
  corehq/apps/hqwebapp/static/app_manager/less/preview_app.less
  corehq/apps/hqwebapp/static/app_manager/less/summary.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp.less
  corehq/apps/hqwebapp/static/dashboard/less/dashboard.less
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/less/bootstrap.less
  corehq/apps/hqwebapp/static/hqwebapp/less/docs-style.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style.less
  corehq/apps/hqwebapp/static/preview_app/less/preview_app.less
  corehq/apps/hqwebapp/static/registration/less/registration.less
  corehq/apps/hqwebapp/static/reports/less/reports.less
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/core_libraries.html
  corehq/apps/hqwebapp/templatetags/tests/rendered/javascript_libraries_hq.html
  corehq/apps/mocha/templates/mocha/base.html
  custom/champ/templates/champ/spec/mocha.html
  custom/icds_reports/static/js/directives/indie-map/indie-map.directive.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/mobile/dashboard/mobile_dashboard.html
  custom/icds_reports/templates/icds_reports/spec/mocha.html
  docker/README.md
  docker/run.sh
  docs/js-guide/README.md
  docs/js-guide/code-organization.md
  docs/js-guide/external-packages.md
  docs/js-guide/libraries.md
  docs/js-guide/static-files.md
  docs/js-guide/testing.md
  eslint/README.md
  package-lock.json
  package.json
  scripts/hammer.sh
  scripts/update-translations.sh
  settings.py
  yarn.lock
Labels: QA Passed, dependencies, javascript, product/invisible

#28113 SQLField refactors and tests
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/custom_data_fields/tests/__init__.py
  corehq/apps/custom_data_fields/tests/test_fields.py
Labels: product/invisible

#28146 This fixes the map size issue
  custom/icds_reports/static/js/topojsons/districts_v4.topojson
Labels: product/custom

#27862 Concurrent import
  corehq/apps/dump_reload/sql/load.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/blobs/management/commands/run_blob_import.py
  corehq/blobs/tests/test_blob_import.py
Labels: product/all-users-all-environments

#28148 Removed dead code
  corehq/apps/users/urls.py
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#28102 fix varname
  corehq/apps/reports/templates/reports/project_health/partials/last_month_stats.html
Labels: product/invisible

#28153 Silence meaningless "Script error." jserror
  corehq/apps/hqwebapp/static/hqwebapp/js/hq.helpers.js
Labels: product/invisible

#28151 Increase timeout for iterating repeat records
  corehq/motech/repeaters/tasks.py
Labels: product/invisible

#28003 Ce/user upload record
  corehq/apps/user_importer/admin.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/migrations/0001_initial.py
  corehq/apps/user_importer/migrations/__init__.py
  corehq/apps/user_importer/models.py
  corehq/apps/user_importer/tasks.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#28147 remove name from case details title
  corehq/apps/reports/templates/reports/reportdata/case_data.html
Labels: product/all-users-all-environments

#27740 ICDS Dashboard: Pictures on PSE page
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/static/js/directives/awc-reports/awc-reports.directive.js
  custom/icds_reports/templates/icds_reports/icds_app/awc-reports.html
  custom/icds_reports/templates/icds_reports/icds_app/mobile/awc-reports.html
  custom/icds_reports/tests/agg_tests/reports/test_awc_reports.py
Labels: product/custom

#28068 ICDS Dashboard: Release notes
  corehq/toggles.py
  custom/icds_reports/static/css/navbar.less
  custom/icds_reports/static/icds_reports/js/update_release_notes.js
  custom/icds_reports/static/img/release_notes.png
  custom/icds_reports/static/js/icds_app.js
  custom/icds_reports/templates/icds_reports/dashboard.html
  custom/icds_reports/templates/icds_reports/partials/register_dashboard_urls.html
  custom/icds_reports/templates/icds_reports/update_release_notes.html
  custom/icds_reports/urls.py
  custom/icds_reports/views.py
Labels: product/custom

#28149 add new users
  custom/nic_compliance/const.py
Labels: product/custom

#28157 Avoid BytesWarning for Django 2 upgrade
  corehq/apps/api/tests/case_resources.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/receiverwrapper/util.py
  corehq/motech/models.py
  corehq/motech/tests/test_models.py
  corehq/util/__init__.py
  corehq/util/metrics/metrics.py
  corehq/util/tests/test_view_utils.py
  corehq/util/view_utils.py
Labels: product/invisible

#28155 It's a BytesWarning in Py3
  corehq/motech/tests/test_value_source.py
Labels: product/invisible

#28015 Disable form and case edit options on ICDS
  corehq/apps/reports/views.py
Labels: product/custom

#28164 Fixed link in docs [ci skip]
  docs/messaging/schedules.rst
Labels: product/invisible

#28156 Removed top_five_projects_by_country
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views/__init__.py
  corehq/apps/hqadmin/views/reports.py
Labels: product/invisible

#28150 track de-re-activate
  corehq/apps/users/views/mobile/users.py
Labels: product/invisible

#28166 Fix JsonResponse lists.
  corehq/apps/hqadmin/views/system.py
Labels: product/invisible

#28163 Add bulk app translations to waf allow list
  corehq/apps/translations/views.py
Labels: product/invisible

#28137 Django 2.2 upgrade
  requirements-python3/dev-requirements.txt
  requirements-python3/prod-requirements.txt
  requirements-python3/requirements.txt
  requirements-python3/test-requirements.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, product/invisible

#28170 Fix two-factor twilio URL
  corehq/apps/hqwebapp/two_factor_gateways.py
  corehq/apps/hqwebapp/urls.py
Labels: product/invisible

#28142 Update django admin to allow searching PillowErrors by doc_id
  corehq/ex-submodules/pillow_retry/admin.py
Labels: product/invisible

#28032 Refactor tests to not fake ES and add more tests, Delete some stale code
  corehq/apps/api/es.py
  corehq/apps/api/resources/v0_3.py
  corehq/apps/api/resources/v0_4.py
  corehq/apps/api/tests/case_resources.py
  corehq/apps/api/tests/core_api.py
  corehq/apps/api/tests/form_resources.py
  corehq/apps/api/tests/utils.py
  corehq/apps/cleanup/management/commands/local_commcare_export.py
  corehq/apps/hqcase/utils.py
  corehq/apps/reports/tests/test_esaccessors.py
  custom/_legacy/pact/forms/patient_form.py
  custom/_legacy/pact/management/commands/pact_compute_dots.py
  custom/_legacy/pact/reports/chw.py
  custom/_legacy/pact/reports/chw_schedule.py
  custom/_legacy/pact/reports/dot.py
  custom/_legacy/pact/reports/patient.py
  custom/_legacy/pact/reports/patient_list.py
  custom/_legacy/pact/utils.py
  custom/apps/crs_reports/reports.py
Labels: QA Passed, product/invisible

#28099 refactor custom app routing
  corehq/sql_db/__init__.py
  corehq/sql_db/connections.py
  corehq/sql_db/routers.py
  corehq/sql_db/tests/test_connections.py
  corehq/sql_db/tests/test_routers.py
  custom/aaa/const.py
  custom/aaa/dbaccessors.py
  custom/aaa/models.py
  custom/aaa/tasks.py
  custom/aaa/utils.py
  custom/icds_reports/management/commands/imbalanced_indicator.py
  custom/icds_reports/management/commands/stale_data_in_ucr.py
  custom/icds_reports/management/commands/update_agg_awc_num_awc_infra_last_update.py
  custom/icds_reports/management/commands/update_child_health_monthly.py
  custom/icds_reports/reports/disha.py
  custom/icds_reports/tasks.py
  custom/icds_reports/utils/aggregation_helpers/distributed/location_reassignment.py
  custom/icds_reports/utils/connections.py
  settings.py
Labels: product/invisible

#28168 keep yarn.lock frozen during tests
  DEV_SETUP.md
  docker/run.sh
  docs/js-guide/testing.md
  package.json
  scripts/hammer.sh
  yarn.lock
Labels: product/invisible

#28172 use count instead
  corehq/apps/users/models.py
  corehq/apps/users/views/__init__.py
Labels: product/invisible

#28174 Fix scheduled reports encoding
  corehq/apps/reports/views.py
  corehq/apps/saved_reports/models.py
  corehq/apps/saved_reports/tasks.py
  corehq/apps/saved_reports/tests/test_scheduled_reports.py
Labels: product/invisible

#28175 use npm version of ui-select
  package.json
  scripts/test-make-requirements.sh
  yarn.lock
Labels: dependencies, javascript, product/invisible

#28089 Incorporate Project Space Dialer through AWS CCP package
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/main.js
  corehq/apps/cloudcare/static/cloudcare/js/util.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/cloudcare/views.py
  corehq/apps/domain/urls.py
  corehq/apps/integration/forms.py
  corehq/apps/integration/migrations/0002_dialersettings.py
  corehq/apps/integration/models.py
  corehq/apps/integration/static/integration/css/dialerstyle.css
  corehq/apps/integration/static/integration/images/blackLED.png
  corehq/apps/integration/static/integration/images/greenLED.png
  corehq/apps/integration/static/integration/images/redLED.png
  corehq/apps/integration/static/integration/images/user-icon.png
  corehq/apps/integration/static/integration/js/dialer/amazon-connect-min.js
  corehq/apps/integration/static/integration/js/dialer/connect-streams-min.js
  corehq/apps/integration/static/integration/js/dialer/dialer_utils.js
  corehq/apps/integration/static/integration/js/dialer/domain_dialer_main.js
  corehq/apps/integration/templates/integration/base_cloudcare_template.html
  corehq/apps/integration/templates/integration/dialer_settings.html
  corehq/apps/integration/templates/integration/web_app_dialer.html
  corehq/apps/integration/urls.py
  corehq/apps/integration/util.py
  corehq/apps/integration/views.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
  package.json
  urls.py
  yarn.lock
Labels: product/feature-flag

#28177 attempts at fixing yarn.lock issues in travis tests
  docker/run.sh
  scripts/test-make-requirements.sh
Labels: product/invisible

#26733 Use ES aliases instead of index names in queries
  corehq/apps/api/es.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/domain/tests/test_domain_calculated_properties.py
  corehq/apps/es/case_search.py
  corehq/apps/es/es_query.py
  corehq/apps/hqadmin/escheck.py
  corehq/apps/hqadmin/management/commands/forms_not_in_es.py
  corehq/apps/hqcase/management/commands/ptop_preindex.py
  corehq/apps/hqcase/tests/test_dbaccessors.py
  corehq/apps/reports/tasks.py
  corehq/elastic.py
  corehq/ex-submodules/couchforms/tests/test_analytics.py
  corehq/ex-submodules/pillowtop/es_utils.py
  corehq/ex-submodules/pillowtop/processors/elastic.py
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
  corehq/ex-submodules/pillowtop/tests/test_bulk.py
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
  corehq/ex-submodules/pillowtop/tests/utils.py
  corehq/ex-submodules/pillowtop/utils.py
  corehq/form_processor/tests/utils.py
  corehq/pillows/case_search.py
  corehq/pillows/domain.py
  corehq/pillows/group.py
  corehq/pillows/mappings/app_mapping.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/case_search_mapping.py
  corehq/pillows/mappings/domain_mapping.py
  corehq/pillows/mappings/group_mapping.py
  corehq/pillows/mappings/reportcase_mapping.py
  corehq/pillows/mappings/reportxform_mapping.py
  corehq/pillows/mappings/sms_mapping.py
  corehq/pillows/mappings/user_mapping.py
  corehq/pillows/mappings/xform_mapping.py
  corehq/pillows/user.py
  corehq/util/elastic.py
  corehq/util/es/interface.py
  docs/elasticsearch.rst
  settings.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/test_domain_pillow.py
  testapps/test_pillowtop/tests/test_group_pillow.py
  testapps/test_pillowtop/tests/test_user_pillow.py
Labels: QA Passed, product/invisible

#28171 Removed dead code
  corehq/apps/locations/models.py
Labels: product/invisible

#28178 Mentioned CCHQ_TESTING in DEV_SETUP.md
  DEV_SETUP.md
Labels: product/invisible

#28173 Test reverse two_factor_twilio:call_app URL
  corehq/apps/hqwebapp/tests/test_two_factor_gateways.py
Labels: product/invisible

#28007 add folders in the 'extra' folder to the python path
  manage.py
Labels: product/invisible

#28132 Added Show All option
  corehq/apps/userreports/reports/filters/choice_providers.py
Labels: QA Passed, product/all-users-all-environments

#28094 move more ICDS settings to localsettings
  docker/localsettings.py
  settings.py
  testsettings.py
  urls.py
Labels: product/invisible

#28103 Whatsapp multimedia messages
  corehq/apps/formplayer_api/smsforms/api.py
  corehq/apps/sms/api.py
  corehq/apps/sms/handlers/form_session.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tests/inbound_handlers.py
  corehq/apps/sms/views.py
  corehq/apps/smsbillables/exceptions.py
  corehq/apps/smsbillables/management/commands/bootstrap_gateway_fees.py
  corehq/apps/smsbillables/migrations/0010_gateway_fee_amount_null.py
  corehq/apps/smsbillables/migrations/0021_infobip_gateway_fee_amount_null.py
  corehq/apps/smsbillables/migrations/0022_pinpoint_gateway_fee_amount_null.py
  corehq/apps/smsbillables/models.py
  corehq/apps/smsbillables/tests/generator.py
  corehq/apps/smsbillables/tests/test_gateway_fees.py
  corehq/apps/smsbillables/tests/test_usage_fees.py
  corehq/apps/smsbillables/tests/utils.py
  corehq/apps/smsbillables/utils.py
  corehq/apps/smsforms/app.py
  corehq/apps/smsforms/tasks.py
  corehq/apps/smsforms/util.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/smsbackends/infobip/models.py
  corehq/messaging/smsbackends/infobip/views.py
  corehq/messaging/smsbackends/test/models.py
  corehq/messaging/smsbackends/turn/exceptions.py
  corehq/messaging/smsbackends/turn/models.py
  corehq/messaging/smsbackends/twilio/models.py
  corehq/messaging/whatsapputil.py
Labels: product/all-users-all-environments

#28160 ICDS Dashboard: Corrections in UI and reports
  custom/icds_reports/reports/adolescent_girls.py
  custom/icds_reports/reports/awc_reports.py
  custom/icds_reports/static/js/directives/adolescent-girls/adolescent-girls.directive.js
  custom/icds_reports/tests/agg_tests/reports/test_adolescent_girls.py
  custom/icds_reports/utils/__init__.py
Labels: product/custom

#28182 make high frequency ids bigints
  corehq/apps/users/models.py
  corehq/ex-submodules/pillow_retry/models.py
Labels: product/invisible
