Repository dimagi/commcare-hq, pull requests merged in 2020-09, with the labels that each got.

#28454 Revert "Merge pull request #28208 from dimagi/jls/CustomDataFieldsPro…
  corehq/apps/api/resources/v0_1.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/user_resources.py
  corehq/apps/app_manager/models.py
  corehq/apps/callcenter/sync_user_case.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/cloudcare/tests/test_session.py
  corehq/apps/cloudcare/views.py
  corehq/apps/commtrack/tests/util.py
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/custom_data_fields/migrations/0005_customdatafieldsprofile.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
  corehq/apps/custom_data_fields/tasks.py
  corehq/apps/custom_data_fields/templates/custom_data_fields/custom_data_fields.html
  corehq/apps/custom_data_fields/templates/custom_data_fields/partials/fields_tab.html
  corehq/apps/custom_data_fields/templates/custom_data_fields/partials/modal_delete.html
  corehq/apps/custom_data_fields/templates/custom_data_fields/partials/profiles_tab.html
  corehq/apps/custom_data_fields/tests/test_profiles.py
  corehq/apps/custom_data_fields/tests/test_verification.py
  corehq/apps/hqwebapp/static/hqwebapp/js/select2_knockout_bindings.ko.js
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/tests/test_update_custom_data_fields.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/sms/api.py
  corehq/apps/sms/tests/test_registration.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/user_importer/tests/test_validators.py
  corehq/apps/user_importer/validation.py
  corehq/apps/users/bulk_download.py
  corehq/apps/users/custom_data.py
  corehq/apps/users/forms.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/custom_data_fields.js
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/tests/test_download.py
  corehq/apps/users/tests/test_user_model.py
  corehq/apps/users/views/mobile/custom_data_fields.py
  corehq/apps/users/views/mobile/users.py
  corehq/ex-submodules/casexml/apps/phone/tests/utils.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/scheduling/tests/test_recipients.py
  corehq/pillows/user.py
  corehq/toggles.py
Labels: product/all-users-all-environments

#28413 Remove users in test locations for CPMU role
  corehq/apps/reports/extension_points.py
  corehq/apps/reports/filters/controllers.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/util.py
Labels: product/custom

#28461 increase limit for case api
  corehq/apps/api/resources/v0_4.py
Labels: product/invisible

#28459 Change custom/up_nrhm DOMAIN to nhm-af-up
  custom/up_nrhm/sql_data.py
  custom/up_nrhm/tests/__init__.py
  custom/up_nrhm/tests/reports/test_asha_reports.py
  custom/up_nrhm/tests/utils.py
Labels: product/custom

#28466 temporarily disable icds JS tests
  .travis.yml
Labels: product/invisible

#28462 Removed one of the two identical LoginAndDomainMixin classes
  corehq/apps/app_manager/views/app_summary.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/dashboard/views.py
  corehq/apps/domain/views/__init__.py
  corehq/apps/domain/views/accounting.py
  corehq/apps/domain/views/base.py
  corehq/apps/domain/views/settings.py
Labels: product/invisible

#28415 Feature/covid geocoder proximity
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/cloudcare/views.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
  corehq/apps/domain/static/domain/js/info_basic.js
  corehq/apps/domain/templates/domain/admin/info_basic.html
  corehq/apps/domain/views/settings.py
  corehq/apps/hqwebapp/static/hqwebapp/js/widgets.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/widgets.py
  corehq/apps/reports/static/reports/js/edit_submission.js
  corehq/apps/reports/templates/reports/form/edit_submission.html
Labels: product/all-users-all-environments

#28457 Linked docs to location safe report builder flag
  corehq/toggles.py
Labels: product/admin

#28465 [ICDS Dashboard]: Minor MPR UI fix
  corehq/apps/reports/templates/reports/filters/location_async.html
Labels: product/custom

#28464 Add index on sms processed timestamp
  corehq/apps/sms/migrations/0045_auto_20200902_0938.py
  corehq/apps/sms/models.py
Labels: product/invisible, reindex/migration

#28477 only close checkin case
  custom/covid/__init__.py
  custom/covid/rules/custom_actions.py
  custom/covid/tests/__init__.py
  custom/covid/tests/test_custom_rules.py
Labels: product/custom

#27888 On ICDS restrict the users who don't have access to the app
  corehq/apps/app_manager/fixtures/mobile_ucr.py
  corehq/apps/cloudcare/views.py
  corehq/apps/ota/views.py
  corehq/apps/users/models.py
  custom/icds_core/view_utils.py
Labels: product/custom

#28379 run tests without ICDS code
  corehq/apps/userreports/expressions/date_specs.py
  corehq/apps/userreports/expressions/factory.py
  custom/aaa/commcare_extensions.py
  custom/aaa/tests/test_child_query_helper.py
  custom/aaa/tests/test_eligible_couple_query_helper.py
  custom/aaa/tests/test_pregnant_woman_query_helper.py
  custom/aaa/ucr/data_sources/birth_preparedness_forms.json
  custom/aaa/ucr/data_sources/household_cases.json
  custom/aaa/ucr/data_sources/pop_totals_person_mobile.json
  custom/aaa/ucr/expressions.py
  settings.py
Labels: Open for review: do not merge

#28475 fix generated xmlns property in DET schemas
  corehq/apps/export/det/schema_generator.py
  corehq/apps/export/tests/data/det/form_export_instance.json
  corehq/apps/export/tests/test_det_schema_generation.py
Labels: product/feature-flag

#28473 update rebuildstaging workflow to use external tool
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  scripts/checkyaml.py
  scripts/commit-staging
  scripts/gitutils.py
  scripts/rebuildstaging
  scripts/rebuildstaging.py
  scripts/sh_verbose.py
  scripts/vellum-to-hq
Labels: product/invisible

#28476 get_alias works in ES7 and ES2
  corehq/ex-submodules/pillowtop/management/commands/ptop_es_manage.py
Labels: product/invisible

#28444 updated how the bulk user upload process, so that editing a web user …
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
Labels: product/all-users-all-environments

#28472 [ICDS Dashboard] Added captcha in registration page
  corehq/apps/registration/forms.py
  corehq/apps/registration/static/registration/js/new_user.ko.js
Labels: product/custom, product/feature-flag

#28479 Always check api access on top of any other permissions
  corehq/apps/api/tests/test_auth.py
  corehq/apps/users/decorators.py
Labels: product/all-users-all-environments

#28482 use standard date format
  corehq/motech/repeaters/repeater_generators.py
Labels: product/invisible

#28451 Add mapbox and open street map attribution to report builder map
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/mapbox.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style-imports.less
  corehq/apps/reports/static/reports/js/maps_utils.js
  corehq/apps/reports_core/static/reports_core/js/maps.js
Labels: product/invisible

#28485 Add .python-version to gitignore
  .gitignore
Labels: product/invisible

#28481 Fix form submissions counts returning zero
  corehq/apps/reports/standard/monitoring.py
Labels: product/invisible

#28483 disable static device throttling
  settings.py
Labels: product/invisible

#28486 Toggle mistaken reindex/standard ES settings
  corehq/ex-submodules/pillowtop/index_settings.py
Labels: product/invisible

#28489 Revert "[ICDS Dashboard] Added captcha in registration page"
  corehq/apps/registration/forms.py
  corehq/apps/registration/static/registration/js/new_user.ko.js
Labels: product/all-users-all-environments

#28480 wait a minute before requesting confirmation email for project again
  corehq/apps/registration/views.py
Labels: product/all-users-all-environments

#28488 Daily Form Activity report results appear to be a day behind
  corehq/apps/reports/analytics/esaccessors.py
Labels: product/invisible

#28491 noop migration changes display name of "bearer"
  corehq/motech/migrations/0007_auto_20200909_2138.py
Labels: product/invisible

#28474 upgrade datatables to 1.10.12
  package.json
  yarn.lock
Labels: dependencies, javascript, product/all-users-all-environments

#28498 Minor text changes to code-organization readme file
  docs/js-guide/code-organization.md
Labels: product/invisible

#28496 Add ES query tests for recent bugs found
  corehq/apps/reports/tests/test_esaccessors.py
Labels: product/invisible

#28494 Refactor, test and fix doc_in_es
  corehq/apps/hqadmin/views/data.py
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
Labels: product/invisible

#28497 Mark invites as bounced before sending
  corehq/apps/hqwebapp/tasks.py
  corehq/ex-submodules/dimagi/utils/django/email.py
Labels: product/invisible

#28499 Update pillow docs
  DEV_SETUP.md
  corehq/ex-submodules/pillowtop/management/commands/run_ptop.py
Labels: product/invisible

#28353 ICDS Dashboard: sp/angularjs migration
  package.json
  yarn.lock
Labels: awaiting QA, product/custom

#28503 Skip domain migration in ES on fresh install
  corehq/apps/domain/migrations/0006_fix_domain_es_docs.py
Labels: product/invisible

#28502 command to log kafka changes
  corehq/ex-submodules/pillowtop/management/commands/tail_kafka.py
Labels: product/invisible

#28509 Move standard docs to main repo
  STANDARDS.rst
Labels: product/invisible

#28492 Add New UCR Filter "Case Owner (Location w/ Descendants and Archived Locations)"
  corehq/apps/userreports/reports/builder/const.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/reports/filters/choice_providers.py
  corehq/apps/userreports/tests/test_report_builder.py
Labels: product/all-users-all-environments

#28510 Fixed web apps js error due to undefined object
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
Labels: product/all-users-all-environments

#28513 Update contributions expectations
  CONTRIBUTING.rst
Labels: product/invisible

#28514 Removed dead CSS class [ci skip]
  corehq/apps/users/templates/users/partials/basic_info_modals.html
Labels: product/invisible

#28507 reduce oauth access token expiry to 15 minutes
  settings.py
Labels: product/all-users-all-environments

#28511 Make enterprise permissions UI editable
  corehq/apps/users/forms.py
  corehq/apps/users/templates/users/domain_permissions_mirror.html
  corehq/apps/users/urls.py
  corehq/apps/users/views/__init__.py
Labels: product/feature-flag

#28118 Remove invalid error message for non admin users
  corehq/apps/users/views/mobile/users.py
Labels: product/custom

#28500 All data forwarders notify on errors
  corehq/motech/openmrs/tests/test_tasks.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/requests.py
  corehq/motech/tests/test_models.py
  corehq/motech/tests/test_requests.py
Labels: product/all-users-all-environments

#28519 Moved app manager docs to ReadTheDocs
  corehq/apps/app_manager/README.md
  corehq/apps/app_manager/commcaresettings-README.md
  docs/app_manager/advanced_app_features.rst
  docs/app_manager/settings.rst
  docs/app_manager/terminology.rst
  docs/index.rst
Labels: product/invisible

#28515 added the grocoder permission
  corehq/apps/domain/forms.py
Labels: product/all-users-all-environments

#28516 Kill mobile worker self-registration
  corehq/apps/api/urls.py
  corehq/apps/app_manager/dbaccessors.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/sms/admin.py
  corehq/apps/sms/api.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/messages.py
  corehq/apps/sms/migrations/0046_delete_selfregistrationinvitation.py
  corehq/apps/sms/models.py
  corehq/apps/sms/resources/v0_5.py
  corehq/apps/sms/static/sms/js/manage_registration_invitations.js
  corehq/apps/sms/templates/sms/manage_registration_invitations.html
  corehq/apps/sms/tests/test_registration.py
  corehq/apps/sms/urls.py
  corehq/apps/sms/views.py
  corehq/apps/users/forms.py
  corehq/apps/users/templates/users/mobile/commcare_user_self_register.html
  corehq/apps/users/urls.py
  corehq/apps/users/views/mobile/users.py
  corehq/const.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/invisible

#28467 Remove location.group_id
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/commtrack/tests/test_supply_points.py
  corehq/apps/locations/models.py
  corehq/apps/locations/tests/test_location_groups.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/fixture_status.py
Labels: product/invisible

#28501 Allow Case Summary To Be Downloaded Through API
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/app_manager/views/app_summary.py
Labels: product/all-users-all-environments

#28521 Pulled a few more READMEs into ReadTheDocs
  corehq/apps/builds/README.md
  corehq/apps/builds/README.rst
  corehq/apps/hqmedia/README.md
  corehq/apps/hqmedia/README.rst
  corehq/apps/mocha/README.md
  corehq/apps/mocha/README.rst
  corehq/ex-submodules/toggle/README.md
  corehq/ex-submodules/toggle/management/commands/make_toggle.py
  corehq/toggles.py
  docs/apps/advanced_app_features.rst
  docs/apps/builds.rst
  docs/apps/multimedia.rst
  docs/apps/settings.rst
  docs/apps/terminology.rst
  docs/apps/translations.rst
  docs/es_fake.rst
  docs/index.rst
  docs/mocha.rst
  docs/toggles.rst
Labels: product/invisible

#28522 Kev/email logging
  corehq/util/email_event_utils.py
Labels: product/all-users-all-environments, product/invisible

#28504 require timezone in date regex
  corehq/ex-submodules/dimagi/ext/jsonobject.py
  corehq/ex-submodules/dimagi/ext/tests/test_jsonobject.py
  corehq/form_processor/tests/test_utils.py
  corehq/form_processor/utils/xform.py
Labels: product/all-users-all-environments

#28518 Support for markdown tables on Webapps
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/views/formdesigner.py
  corehq/apps/cloudcare/static/cloudcare/less/markdown-table.less
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
Labels: product/all-users-all-environments

#28526 Files updated to deploy Vellum
  corehq/apps/app_manager/static/app_manager/js/vellum/src/main-components.js
  corehq/apps/app_manager/static/app_manager/js/vellum/style.css
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: product/all-users-all-environments

#28520 Add API support for linked applications
  corehq/apps/api/resources/v0_4.py
Labels: product/invisible

#28333 Revert "Revert "add captcha to login page""
  corehq/apps/hqwebapp/forms.py
  corehq/apps/registration/static/registration/js/login.js
Labels: product/custom

#28326 adding unsent forms column to app status report
  corehq/apps/reports/standard/deployments.py
Labels: product/all-users-all-environments

#28527 Add role column to mobile worker enterprise export
  corehq/apps/accounting/enterprise.py
Labels: product/invisible

#28209 Upgrade Celery to 4.4.7 and get rid of redis-py-cluster
  corehq/apps/userreports/rebuild.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_async_restore.py
  corehq/motech/repeaters/tests/test_repeater.py
  dev_settings.py
  localsettings.example.py
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  requirements/uninstall-requirements.txt
Labels: QA Passed, dependencies, product/invisible

#28505 Upgrade ES to 7.9.1 from 7.6.2; pip-compile
  docker/hq-compose.yml
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible

#28529 Added search to case import history
  corehq/apps/case_importer/static/case_importer/js/import_history.js
  corehq/apps/case_importer/templates/case_importer/import_cases.html
  corehq/apps/case_importer/templates/case_importer/partials/ko_import_history.html
  corehq/apps/case_importer/tracking/dbaccessors.py
  corehq/apps/case_importer/tracking/tests/test_dbaccessors.py
  corehq/apps/case_importer/tracking/views.py
Labels: product/all-users-all-environments

#28534 Updated default module name for flagged module types to use 'Menu' not 'Module'
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/views/apps.py
Labels: product/feature-flag

#28532 skip UCRs during migrations
  corehq/apps/domain_migration_flags/api.py
  corehq/apps/userreports/pillow.py
  corehq/apps/userreports/tests/utils.py
Labels: product/invisible

#28450 ES7 Rollout commands
  corehq/apps/hqcase/management/commands/initialize_es_indices.py
  corehq/apps/hqcase/management/commands/reindex_es_from_remote.py
  corehq/apps/hqcase/management/commands/reprocess_form_case_es_deletes.py
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
  corehq/pillows/mappings/reportxform_mapping.py
Labels: product/invisible

#28540 Enterprise Web User Report name and email columns are swapped
  corehq/apps/accounting/enterprise.py
Labels: product/invisible

#28539 Migrate to new Mapbox Static Tiles API
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/reports_core/static/reports_core/js/maps.js
Labels: product/invisible

#28541 Updated SQLAppGroup.group_id to allow nulls
  corehq/apps/cloudcare/models.py
Labels: product/invisible

#28533 Include Account & Subscription-level Product / Feature Credits in Monthly Credits Report for Accounting
  corehq/apps/accounting/automated_reports.py
  corehq/apps/accounting/models.py
Labels: product/invisible

#28548 Add portuguese
  settings.py
Labels: product/all-users-all-environments

#28528 Added web_user column to exports
  corehq/apps/export/system_properties.py
  corehq/apps/userreports/tests/test_report_builder.py
Labels: product/all-users-all-environments

#28487 Upgrade requirements
  docker/run.sh
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, dependencies, product/invisible

#28553 Tests and fixes for MobileAuthKeyRecord couch to sql migration
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/cleanup/tests/test_couch_to_sql_mobile_auth.py
  corehq/apps/custom_data_fields/management/commands/populate_custom_data_fields.py
  corehq/apps/mobile_auth/management/commands/populate_mobileauthkeyrecord.py
  corehq/ex-submodules/dimagi/utils/couch/migration.py
Labels: product/invisible

#28556 fix syntax warnings
  corehq/apps/commtrack/models.py
  corehq/apps/reports/tasks.py
  corehq/ex-submodules/couchexport/writers.py
  corehq/project_limits/rate_counter/rate_counter.py
  custom/m4change/views.py
Labels: product/invisible

#28555 Minor tweaks to couch to sql docs
  docs/couch_to_sql_models.rst
Labels: product/invisible

#28554 Updated user import to fully remove fields that are set to blank
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
Labels: product/invisible

#28542 Make migrations
  corehq/apps/accounting/migrations/0049_auto_20200924_1753.py
  corehq/apps/custom_data_fields/migrations/0006_auto_20200924_1753.py
  corehq/apps/domain/migrations/0007_auto_20200924_1753.py
  corehq/apps/locations/migrations/0019_auto_20200924_1753.py
  corehq/apps/translations/migrations/0009_auto_20200924_1753.py
  corehq/form_processor/migrations/0092_auto_20200924_1753.py
Labels: product/invisible

#28432 Linked Keywords
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/keywords.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/tests/test_linked_keywords.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reminders/static/reminders/js/keywords_list.js
  corehq/apps/reminders/templates/reminders/keyword_list.html
  corehq/apps/reminders/templates/reminders/link_keywords_modal.html
  corehq/apps/reminders/urls.py
  corehq/apps/reminders/views.py
  corehq/apps/sms/migrations/0046_keywords_linked_domain_fields.py
  corehq/apps/sms/migrations/0047_merge_20200918_1641.py
  corehq/apps/sms/models.py
Labels: QA Passed, product/feature-flag

#28563 Uninstall enum34
  requirements/uninstall-requirements.txt
Labels: product/invisible

#28495 Feature/ush 142 overwrite caselists
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/templates/app_manager/module_view.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_module_overwrite.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_actions.html
  corehq/apps/app_manager/tests/test_modules.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/notifications/ui_notify.py
Labels: QA Passed, product/all-users-all-environments

#28561 ensure apisettings have been migrated before deleting the model
  corehq/apps/hqwebapp/migrations/0005_delete_apikeysettings.py
Labels: product/invisible

#28559 disable ddtrace if not in use
  corehq/util/metrics/__init__.py
  corehq/util/metrics/datadog.py
Labels: product/invisible

#28558 remove unnecessary settings from localsettings.example.py
  localsettings.example.py
Labels: product/invisible

#28565 add missing migrations
  corehq/apps/linked_domain/migrations/0012_auto_20200929_0809.py
Labels: product/invisible

#28552 RequireJS migration: translations, confirm billing info
  corehq/apps/domain/static/domain/js/confirm_billing_info.js
  corehq/apps/domain/templates/domain/confirm_billing_info.html
  corehq/apps/hqwebapp/static/hqwebapp/js/rollout_modal.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-checkbox.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-input.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-langcode-button.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-select.js
  corehq/apps/translations/static/translations/js/translations.js
Labels: product/invisible

#28567 better title to reflect options
  corehq/apps/data_interfaces/views.py
Labels: product/all-users-all-environments

#28568 remove data management
  docker/localsettings.py
  testsettings.py
Labels: product/custom

#28564 Re-release tests and fixes for MobileAuthKeyRecord couch to sql migration
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/cleanup/tests/test_couch_to_sql_mobile_auth.py
  corehq/apps/custom_data_fields/management/commands/populate_custom_data_fields.py
  corehq/apps/mobile_auth/management/commands/populate_mobileauthkeyrecord.py
  corehq/ex-submodules/dimagi/utils/couch/migration.py
Labels: product/invisible

#28447 access root properties correctly
  corehq/apps/users/static/users/js/roles.js
Labels: product/feature-flag

#28569 Updated linked_domain README
  corehq/apps/linked_domain/README.md
Labels: product/invisible

#28523 Web Apps: add `for` and `aria-required` attributes
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments

#28530 Migrated fullform-ui.js to hqDefine
  corehq/apps/cloudcare/static/cloudcare/js/debugger/debugger.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entrycontrols_full_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/fullform-ui_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/webformsession_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
Labels: product/invisible

#28571 Fixed help not displaying in web apps for questions not present on fo…
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
Labels: product/all-users-all-environments

#28557 add flag for skipping fixtures on restore
  corehq/apps/ota/views.py
  corehq/ex-submodules/casexml/apps/phone/data_providers/__init__.py
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_fixtures.py
  corehq/ex-submodules/casexml/apps/phone/utils.py
Labels: product/invisible

#28484 Web Apps collapsible groups
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/css/webforms.css
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: QA Passed, product/all-users-all-environments

#28551 upgrade to redis-py 3.3.0 (on top of dm/requirements
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, dependencies, product/invisible
