Repository dimagi/commcare-hq, pull requests merged in 2021-08, with the labels that each got.

#30143 refactor alert_user.js + add option to have messages fade out after a fixed interval
  corehq/apps/hqwebapp/static/hqwebapp/js/alert_user.js
  corehq/apps/hqwebapp/templates/hqwebapp/base_navigation.html
Labels: product/invisible

#30172 set date created for test data
  corehq/apps/enterprise/tests/test_interface.py
Labels: product/invisible

#30163 add task to track pg primary key
  corehq/apps/hqadmin/tasks.py
Labels: product/invisible

#30173 Added feature flag help link
  corehq/toggles.py
Labels: product/admin

#30174 Fixed decorator on ScheduledReportsView
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#30165 update prune_synclogs
  corehq/ex-submodules/casexml/apps/phone/tasks.py
Labels: product/invisible

#30152 Only disable linked apps for release management privilege
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/templates/app_manager/app_view_settings.html
  corehq/apps/app_manager/views/view_generic.py
Labels: product/invisible

#30175 Added help text to data dictionary date fields if validation is on
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
Labels: product/feature-flag

#30168 remove unused function
  corehq/apps/users/cases.py
  corehq/apps/users/tests/case_utils.py
Labels: product/invisible

#30167 data registry signals and invitation email
  corehq/apps/registry/app_config.py
  corehq/apps/registry/notifications.py
  corehq/apps/registry/signals.py
  corehq/apps/registry/templates/registry/email/invitation.html
  corehq/apps/registry/templates/registry/email/invitation.txt
  corehq/apps/registry/utils.py
  settings.py
Labels: product/custom

#30183 Temporarily hide Enterprise SMS Billables Report
  corehq/tabs/tabclasses.py
Labels: product/invisible

#30176 fix bugs in track_es_doc_counts
  corehq/apps/hqadmin/tasks.py
Labels: product/invisible

#30185 Fix access control for release management/linked projects
  corehq/apps/linked_domain/tests/test_decorators.py
  corehq/apps/linked_domain/util.py
Labels: product/invisible

#30184 use freezegun in test
  corehq/ex-submodules/casexml/apps/phone/tests/test_prune.py
Labels: product/invisible

#30186 Fix remote reports issues
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#30191 Reference fetched datasource to account for remote links
  corehq/apps/linked_domain/ucr.py
Labels: product/invisible

#30153 Custom product data fields should be a feature flag data model
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/migrations/0016_reorder_history_model_choices.py
  corehq/apps/linked_domain/tests/test_view_helpers.py
Labels: product/invisible, reindex/migration

#30170 remove unused export utils
  corehq/apps/reports/tests/test_case_export.py
  corehq/apps/reports/util.py
Labels: product/invisible

#30194 Minor stickler comments in domain_links.js
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
Labels: product/invisible

#30192 fix soft assert
  corehq/apps/hqadmin/tasks.py
Labels: product/invisible

#30193 Add domain link create and push events to kissmetrics
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#30195 Fix mock test issue
  corehq/tabs/tests.py
Labels: product/invisible

#29962 Enterprise Release Management changes
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/templates/app_manager/app_view_settings.html
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/filters.py
  corehq/apps/linked_domain/migrations/0017_update_remote_base_url_help_text.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/get_started.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/manage_downstream_domains_tab.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/pull_release_content_tab.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/push_release_content_tab.html
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/tests/test_decorators.py
  corehq/apps/linked_domain/tests/test_domain_link_methods.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/linked_domain/tests/test_linked_domain_utils.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/reports/urls.py
  corehq/tabs/tabclasses.py
  corehq/tabs/tests.py
Labels: QA Passed, product/all-users-all-environments, reindex/migration

#30197 Add gherceg to owners file for apps/linked_domain
  .github/CODEOWNERS
Labels: product/invisible

#30198 Define self before use
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
Labels: product/invisible

#30149 [User History] Add UserChangeMessage
  corehq/apps/domain/deletion.py
  corehq/apps/domain/models.py
  corehq/apps/hqadmin/views/users.py
  corehq/apps/settings/views.py
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/audit/__init__.py
  corehq/apps/users/audit/change_messages.py
  corehq/apps/users/forms.py
  corehq/apps/users/tests/test_log_user_change.py
  corehq/apps/users/util.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
  corehq/apps/users/views/utils.py
  scripts/staging.yaml
Labels: Risk: Medium, product/invisible

#30117 [User History] Track UI edits for mobile and web users
  corehq/apps/domain/deletion.py
  corehq/apps/domain/models.py
  corehq/apps/groups/models.py
  corehq/apps/groups/tests/test_groups.py
  corehq/apps/groups/views.py
  corehq/apps/hqadmin/views/users.py
  corehq/apps/locations/forms.py
  corehq/apps/locations/views.py
  corehq/apps/settings/views.py
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/audit/__init__.py
  corehq/apps/users/audit/change_messages.py
  corehq/apps/users/forms.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_log_user_change.py
  corehq/apps/users/util.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
  corehq/apps/users/views/utils.py
Labels: QA Passed, Risk: Medium, product/all-users-all-environments, product/invisible

#30199 Revert "refactor alert_user.js + add option to have messages fade out after a fixed interval"
  corehq/apps/hqwebapp/static/hqwebapp/js/alert_user.js
  corehq/apps/hqwebapp/templates/hqwebapp/base_navigation.html
Labels: product/invisible

#30201 Revert "Define self before use"
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
Labels: product/invisible

#30202 Revert "Enterprise Release Management changes"
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/templates/app_manager/app_view_settings.html
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/filters.py
  corehq/apps/linked_domain/migrations/0017_update_remote_base_url_help_text.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/get_started.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/manage_downstream_domains_tab.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/pull_release_content_tab.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/push_release_content_tab.html
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/tests/test_decorators.py
  corehq/apps/linked_domain/tests/test_domain_link_methods.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/linked_domain/tests/test_linked_domain_utils.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/reports/urls.py
  corehq/tabs/tabclasses.py
  corehq/tabs/tests.py
Labels: product/invisible, reindex/migration

#30160 Rc/show hierarchy
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: awaiting QA, QA Passed, product/all-users-all-environments, Risk: Medium

#30204 Update staging.yaml
  scripts/staging.yaml
Labels: product/admin

#30207 Update staging.yaml
  scripts/staging.yaml
Labels: product/invisible

#30100 Validates label on Web Apps
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/web_form_session_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#30209 Update profiling.rst
  docs/profiling.rst
Labels: product/invisible

#30177 add more auth details to case claim forms
  corehq/apps/ota/tests/test_claim.py
  corehq/apps/ota/views.py
  corehq/apps/reports/views.py
  corehq/ex-submodules/casexml/apps/case/cleanup.py
  corehq/ex-submodules/casexml/apps/phone/models.py
Labels: product/all-users-all-environments

#30180 add dependency for enterprise permissions migration
  corehq/apps/enterprise/migrations/0001_initial.py
Labels: reindex/migration, product/invisible

#30085 Cowin integration updates
  custom/cowin/const.py
  custom/cowin/repeater_generators.py
  custom/cowin/repeaters.py
  custom/cowin/tests.py
Labels: product/feature-flag

#30212 Smart linking MVP: stop claiming cases on HQ
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/ota/urls.py
  corehq/apps/ota/views.py
Labels: product/invisible, Risk: Medium

#30210 alter taskmeta sequence
  corehq/apps/hqadmin/migrations/0019_celery_taskmeta_sequence.py
Labels: reindex/migration, product/invisible

#30203 quote tablename
  corehq/apps/hqadmin/tasks.py
Labels: product/invisible

#30158 Filters invites by is_accepted=False for web user upload
  corehq/apps/user_importer/importer.py
Labels: product/all-users-all-environments, Risk: Medium

#30215 Updated web apps question error button text & icon
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#30042 Rc/tableau models linked spaces
  corehq/apps/linked_domain/README.md
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/migrations/0017_add_tableau_choice_20210720_1908.py
  corehq/apps/linked_domain/migrations/0018_auto_20210806_1526.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/tests/test_update_tableau_server.py
  corehq/apps/linked_domain/tests/test_update_tableau_visualization.py
  corehq/apps/linked_domain/tests/test_view_helpers.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/urls.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reports/migrations/0007_tableauvisualization_upstream_id.py
  corehq/apps/reports/models.py
  corehq/apps/users/static/users/js/enterprise_users.js
Labels: reindex/migration, awaiting QA, QA Passed, product/feature-flag

#30217 Update docs on creating remote domain links
  corehq/apps/linked_domain/README.md
Labels: product/invisible

#30213 refactor UCR view report_preview_data
  corehq/apps/userreports/reports/util.py
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/userreports/views.py
Labels: product/invisible

#30178 couch user role cleanup
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/test_auth.py
  corehq/apps/api/tests/user_resources.py
  corehq/apps/domain/calculations.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_dbaccessors.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/apps/enterprise/tests/test_permissions.py
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/hqwebapp/tests/test_default_landing_page.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/tests/test_update_roles.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/locations/tests/util.py
  corehq/apps/reports/tests/test_views.py
  corehq/apps/saved_reports/tests/test_scheduled_reports.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/users/bulk_download.py
  corehq/apps/users/dbaccessors.py
  corehq/apps/users/forms.py
  corehq/apps/users/management/commands/add_download_reports_permission.py
  corehq/apps/users/management/commands/populate_user_role.py
  corehq/apps/users/migrations/0028_migrate_roles_to_sql.py
  corehq/apps/users/migrations/0028_remove_domainpermissionsmirror.py
  corehq/apps/users/migrations/0033_rename_sqluserrole.py
  corehq/apps/users/models.py
  corehq/apps/users/models_role.py
  corehq/apps/users/role_utils.py
  corehq/apps/users/tests/create.py
  corehq/apps/users/tests/test_dbaccessors.py
  corehq/apps/users/tests/test_migrate_roles_to_sql.py
  corehq/apps/users/tests/test_role_utils.py
  corehq/apps/users/tests/test_user_role.py
  corehq/apps/users/tests/test_views.py
  corehq/apps/users/tests/test_web_user_download.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/utils.py
Labels: reindex/migration, product/invisible, Risk: High, Risk: Medium

#30200 Use ugligy3 to minify JS
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/static/hqwebapp/yaml/requirejs.yaml
  package.json
  scripts/build-requirejs.sh
  yarn.lock
Labels: QA Passed, product/invisible, dependencies

#30220 Revert "Revert "refactor alert_user.js + add option to have messages fade out after a fixed interval""
  corehq/apps/hqwebapp/static/hqwebapp/js/alert_user.js
  corehq/apps/hqwebapp/templates/hqwebapp/base_navigation.html
Labels: product/invisible

#30206 Moving available custom rule config to HQ
  settings.py
Labels: product/invisible

#30223 Resolve some doc warnings
  corehq/apps/userreports/README.rst
  docs/js-guide/module-history.md
  docs/overview/architecture.rst
  docs/overview/platform.rst
  docs/web_apps.rst
Labels: product/invisible

#30214 Mobile user bulk upload: handle empty phone numbers
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
Labels: Risk: Medium

#30227 Couch to SQL Forms & Cases: migration utilities
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/management/commands/migrate_multiple_domains_from_couch_to_sql.py
  scripts/migrate-forms.py
Labels: product/invisible

#30228 Disable pact form submission signal
  custom/_legacy/pact/signals.py
Labels: product/invisible

#30234 Fixed menu name displayed in form linking form dropdown
  corehq/apps/app_manager/views/forms.py
Labels: product/feature-flag

#30233 Kill most pact reports
  custom/_legacy/pact/models.py
  custom/_legacy/pact/reports/__init__.py
  custom/_legacy/pact/reports/admin_chw_reports.py
  custom/_legacy/pact/reports/admin_dot_reports.py
  custom/_legacy/pact/reports/chw.py
  custom/_legacy/pact/reports/chw_list.py
  custom/_legacy/pact/reports/dot.py
  custom/_legacy/pact/reports/dot_calendar.py
  custom/_legacy/pact/reports/patient_list.py
  custom/_legacy/pact/signals.py
  custom/_legacy/pact/static/pact/icons/bucket.png
  custom/_legacy/pact/static/pact/icons/check.jpg
  custom/_legacy/pact/static/pact/icons/exclamation-point.jpg
  custom/_legacy/pact/static/pact/icons/info.png
  custom/_legacy/pact/static/pact/icons/minus.png
  custom/_legacy/pact/static/pact/icons/plus.png
  custom/_legacy/pact/static/pact/icons/warning.png
  custom/_legacy/pact/static/pact/icons/x-mark.png
  custom/_legacy/pact/static/pact/stylesheets/dots.css
  custom/_legacy/pact/tasks.py
  custom/_legacy/pact/templates/pact/admin/pact_chw_schedule_admin.html
  custom/_legacy/pact/templates/pact/admin/pact_dot_admin.html
  custom/_legacy/pact/templates/pact/chw/pact_chw_profile_base.html
  custom/_legacy/pact/templates/pact/chw/pact_chw_profile_info.html
  custom/_legacy/pact/templates/pact/chw/pact_chw_profile_schedule.html
  custom/_legacy/pact/templates/pact/chw/pact_chw_profile_submissions.html
  custom/_legacy/pact/templates/pact/dots/dots_report.html
  custom/_legacy/pact/templates/pact/dots/dots_report_nopatient.html
  custom/_legacy/pact/templates/pact/dots/dots_report_visits.html
  custom/_legacy/pact/utils.py
Labels: product/custom

#30148 Cs/sc 1530 location hierarchy links
  corehq/apps/locations/resources/v0_1.py
  corehq/apps/locations/static/locations/css/manage.css
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/templates/locations/manage/location.html
  corehq/apps/locations/templates/locations/manage/location_template.html
  corehq/apps/locations/templates/locations/manage/locations.html
Labels: product/all-users-all-environments

#30146 Memoize result of render_xform
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/views/download.py
Labels: product/all-users-all-environments

#30218 Fix sorted to handle str
  corehq/apps/reports/management/commands/project_stats_report.py
Labels: product/invisible

#30129 [js dependencies] ensure normalize-url resolves to at least 4.5.1
  package.json
  yarn.lock
Labels: QA Passed, product/invisible, dependencies, dependencies/javascript

#30211 Revert 30202 revert 29962 gh/improve erm UI
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/templates/app_manager/app_view_settings.html
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/filters.py
  corehq/apps/linked_domain/migrations/0019_update_remote_base_url_help_text.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/get_started.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/manage_downstream_domains_tab.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/pull_release_content_tab.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/push_release_content_tab.html
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/tests/test_decorators.py
  corehq/apps/linked_domain/tests/test_domain_link_methods.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/linked_domain/tests/test_linked_domain_utils.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/reports/urls.py
  corehq/tabs/tabclasses.py
  corehq/tabs/tests.py
Labels: reindex/migration, QA Passed, product/invisible

#30121 DomainChoiceProvider for domain filtering
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/filters/choice_providers.py
  corehq/apps/userreports/tests/test_choice_provider.py
Labels: product/invisible

#30236 ensure 'commcare_project' is always present in user data for restore
  corehq/apps/cloudcare/tests/test_session.py
  corehq/apps/cloudcare/touchforms_api.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/reports/views.py
  corehq/apps/smsforms/tests/test_app.py
  corehq/apps/users/models.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/casexml/apps/phone/tests/dummy.py
Labels: product/invisible, Risk: Medium

#30221 UCR builder refactor
  corehq/apps/userreports/app_manager/data_source_meta.py
  corehq/apps/userreports/reports/builder/README.md
  corehq/apps/userreports/reports/builder/columns.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/tests/test_report_builder.py
  corehq/apps/userreports/views.py
Labels: product/invisible

#30238 Make ucr data source on monolith envs
  custom/inddex/ucr/data_sources/food_consumption_indicators.json
Labels: product/custom

#30222 Remove the API key display from django admin
  corehq/apps/users/admin.py
Labels: product/invisible

#30239 Add some caching to the app build
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/tests/test_suite.py
Labels: product/invisible

#30243 Pass through two more env vars for codecov
  docker/hq-compose.yml
  scripts/docker
Labels: product/invisible

#30231 Switched web apps success messaging from channel to event
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  docs/web_apps.rst
Labels: product/invisible, Risk: Medium

#30232 Renamed 'steps' to 'selections' in CloudcareURL
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
  corehq/apps/cloudcare/utils.py
  docs/web_apps.rst
Labels: product/invisible, Risk: Medium

#30216 Smart linking MVP: suite changes to support claiming cases on formplayer
  corehq/apps/app_manager/suite_xml/sections/endpoints.py
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/tests/data/session_endpoint_remote_request.xml
  corehq/apps/app_manager/tests/test_suite_session_endpoints.py
Labels: product/invisible

#30224 fix pillow rewind command
  corehq/apps/hqadmin/management/commands/fix_checkpoint_after_rewind.py
Labels: product/invisible

#29941 [couch-to-sql] Management command for auditcare migration
  corehq/apps/auditcare/couch_to_sql.py
  corehq/apps/auditcare/management/commands/copy_events_to_sql.py
  corehq/apps/auditcare/migrations/0005_auditcaremigrationmeta.py
  corehq/apps/auditcare/migrations/0006_auto_20210811_1215.py
  corehq/apps/auditcare/models.py
  corehq/apps/auditcare/tests/data/auditcare_migration.py
  corehq/apps/auditcare/tests/test_auditcare_migration.py
  corehq/apps/auditcare/utils/migration.py
  manage.py
Labels: reindex/migration, product/invisible

#30248 Remove tzmigration app
  corehq/apps/README.rst
  corehq/apps/domain/models.py
  corehq/apps/domain/templates/domain/admin/flags_and_privileges.html
  corehq/apps/domain_migration_flags/migrations/0002_migrate_data_from_tzmigration.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/apps/hqwebapp/templates/hqwebapp/includes/global_navigation_bar.html
  corehq/apps/tzmigration/__init__.py
  corehq/apps/tzmigration/api.py
  corehq/apps/tzmigration/management/__init__.py
  corehq/apps/tzmigration/management/commands/__init__.py
  corehq/apps/tzmigration/management/commands/tzmigrate.py
  corehq/apps/tzmigration/migrations/0001_initial.py
  corehq/apps/tzmigration/migrations/0002_delete_timezonemigrationprogress.py
  corehq/apps/tzmigration/migrations/__init__.py
  corehq/apps/tzmigration/models.py
  corehq/apps/tzmigration/planning.py
  corehq/apps/tzmigration/templatetags/__init__.py
  corehq/apps/tzmigration/templatetags/tzmigration.py
  corehq/apps/tzmigration/test_utils.py
  corehq/apps/tzmigration/tests/__init__.py
  corehq/apps/tzmigration/tests/data/case-tz.json
  corehq/apps/tzmigration/tests/data/case.json
  corehq/apps/tzmigration/tests/data/form-tz.json
  corehq/apps/tzmigration/tests/data/form.json
  corehq/apps/tzmigration/tests/data/form.xml
  corehq/apps/tzmigration/tests/test_timezone_migration_progress.py
  corehq/apps/tzmigration/tests/test_timezonemigration.py
  corehq/apps/tzmigration/timezonemigration.py
  corehq/ex-submodules/couchforms/tests/test_post.py
  corehq/form_processor/models.py
  corehq/form_processor/tests/test_adjust_datetimes.py
  corehq/form_processor/utils/xform.py
  corehq/util/tests/test_timezone_conversions.py
  corehq/util/timezones/conversions.py
  settings.py
  settingshelper.py
Labels: reindex/migration, product/invisible, Risk: High

#30258 Don't memoize a generator - convert to a list
  corehq/apps/app_manager/models.py
Labels: product/invisible

#30242 make build_requirejs show minimal output by default
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
Labels: product/invisible

#30262 Fix race condition in Auditcare migration
  corehq/apps/auditcare/couch_to_sql.py
  corehq/apps/auditcare/tests/test_auditcare_migration.py
  corehq/apps/auditcare/utils/migration.py
Labels: product/invisible

#30241 add reconciliation tasks and command to fetch results
  corehq/apps/hqadmin/management/commands/fetch_reconciliation_records.py
  corehq/apps/hqadmin/management/commands/republish_doc_changes.py
  corehq/apps/hqadmin/tasks.py
  corehq/toggles.py
Labels: product/invisible

#30264 Add proposed custom code guidelines
  custom/CONTRIBUTING.rst
Labels: product/invisible

#30271 Revert "Validates label on Web Apps"
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/web_form_session_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#30263 Add config option for case searching a registry
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/case_search/models.py
  corehq/apps/registry/models.py
Labels: product/feature-flag

#30245 Added build error for session endpoints to menus using display-only forms
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/tests/test_build_errors.py
Labels: product/feature-flag

#30225 always pass request to authenticate
  corehq/apps/domain/auth.py
  corehq/apps/registration/views.py
  corehq/apps/users/views/web.py
Labels: QA Passed, product/invisible, Risk: High

#30244 Smart linking MVP: Added encoding for endpoint args
  corehq/apps/cloudcare/views.py
Labels: product/invisible, Risk: Medium

#30252 Added logic to block endpoints for forms in shadow menus
  corehq/apps/app_manager/suite_xml/sections/endpoints.py
Labels: product/invisible

#30275 Fixed pact imports
  custom/_legacy/pact/reports/__init__.py
Labels: product/custom

#30265 Add ES5 containers to docker-compose configuration
  corehq/ex-submodules/pillowtop/index_settings.py
  corehq/ex-submodules/pillowtop/processors/elastic.py
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
  corehq/util/es/elasticsearch.py
  docker/README.md
  docker/files/elasticsearch_5.yml
  docker/hq-compose-runserver.yml
  docker/hq-compose-services.yml
  docker/hq-compose.yml
  docker/run.sh
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  scripts/docker
  scripts/elasticsearch-administer.py
Labels: product/invisible, dependencies

#30247 Updated default login as permission checkbox to be disabled when user…
  corehq/apps/users/templates/users/partials/edit_role_modal.html
Labels: product/feature-flag

#30281 Remove unused dev dependencies
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
Labels: product/invisible, dependencies

#30273 Add checkbox toggle for SMS billable report visibility in the accounting UI + remove "show" filter in sms detailed reports
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/migrations/0057_add_sms_report_toggle.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/static/accounting/js/billing_account_form.js
  corehq/apps/accounting/templates/accounting/accounts.html
  corehq/apps/enterprise/dispatcher.py
  corehq/apps/enterprise/interface.py
  corehq/apps/enterprise/tests/test_interface.py
  corehq/tabs/tabclasses.py
Labels: reindex/migration, QA Passed, product/admin

#30283 Update staging.yaml
  scripts/staging.yaml
Labels: product/invisible

#30274 Correct order of patched parameters
  corehq/tabs/tests.py
Labels: product/invisible

#30286 [fix] do not invoice paused subscriptions with $0 invoices
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/tests/test_invoice_factory.py
Labels: product/invisible

#30289 Fix multiselect knockout binding bug
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/templates/linked_domain/tabs/push_release_content_tab.html
Labels: product/invisible

#30270 Remove Couch backend (part 1)
  corehq/apps/change_feed/tests/test_data_sources.py
  corehq/apps/cleanup/management/commands/rebuild_domain_cases.py
  corehq/apps/cleanup/management/commands/reprocess_error_forms.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/data_interfaces/tests/test_scheduling_integration.py
  corehq/apps/data_interfaces/tests/util.py
  corehq/apps/users/tests/util.py
  corehq/ex-submodules/casexml/apps/case/tests/util.py
  corehq/form_processor/tests/utils.py
  corehq/messaging/scheduling/tests/test_recipients.py
  corehq/messaging/scheduling/tests/test_schedules.py
  corehq/motech/fhir/tests/test_tasks.py
  docs/forms_and_cases.rst
Labels: product/invisible, Risk: High

#30016 DHIS2: Add support for sending geolocation
  corehq/motech/dhis2/README.md
  corehq/motech/dhis2/dhis2_config.py
  corehq/motech/dhis2/entities_helpers.py
  corehq/motech/dhis2/events_helpers.py
  corehq/motech/dhis2/tests/data/tracked_entity_type.json
  corehq/motech/dhis2/tests/test_entities_helpers.py
  corehq/motech/dhis2/tests/test_events_helpers.py
Labels: awaiting QA, product/feature-flag

#30310 data registry suite file changes for loading case data into forms
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/tests/test_suite_remote_request.py
Labels: product/feature-flag

#30297 Remove Couch: hqcase, hqwebapp, receiverwrapper, reports, userreports
  corehq/apps/hqcase/management/commands/delete_cases.py
  corehq/apps/hqcase/tests/test_explode_cases.py
  corehq/apps/hqcase/tests/test_loadtest_users.py
  corehq/apps/hqcase/tests/test_serialization.py
  corehq/apps/hqcase/utils.py
  corehq/apps/hqcase/views.py
  corehq/apps/hqwebapp/management/commands/synch_phone_nums.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/receiverwrapper/tests/test_submissions.py
  corehq/apps/receiverwrapper/views.py
  corehq/apps/reports/analytics/couchaccessors.py
  corehq/apps/reports/commtrack/data_sources.py
  corehq/apps/reports/commtrack/standard.py
  corehq/apps/reports/management/commands/enable_case_search_for_ecd.py
  corehq/apps/reports/management/commands/project_stats_report.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/reports/tests/test_supply_accessors.py
  corehq/apps/userreports/tests/test_expressions.py
  corehq/apps/userreports/tests/test_extension_expressions.py
  corehq/apps/userreports/tests/test_indicators.py
  corehq/apps/userreports/tests/test_pillow.py
Labels: product/invisible

#30314 add missing domain param
  corehq/motech/dhis2/tests/test_entities_helpers.py
Labels: product/invisible

#30318 Update staging.yaml
  scripts/staging.yaml
Labels: product/invisible

#30317 Remove TESTS_SHOULD_USE_SQL_BACKEND reads
  corehq/ex-submodules/casexml/apps/case/tests/test_factory.py
  corehq/ex-submodules/casexml/apps/case/tests/test_from_xform.py
  corehq/ex-submodules/casexml/apps/case/tests/test_multimedia.py
  corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py
  corehq/ex-submodules/couchforms/tests/data/posts/cloudant-template-tz.json
  corehq/ex-submodules/couchforms/tests/data/posts/cloudant-template.json
  corehq/ex-submodules/couchforms/tests/data/posts/cloudant-template.xml
  corehq/ex-submodules/couchforms/tests/data/posts/decimalmeta.json
  corehq/ex-submodules/couchforms/tests/data/posts/duplicate.json
  corehq/ex-submodules/couchforms/tests/data/posts/meta.json
  corehq/ex-submodules/couchforms/tests/data/posts/meta_bad_username.json
  corehq/ex-submodules/couchforms/tests/data/posts/meta_dict_appversion.json
  corehq/ex-submodules/couchforms/tests/data/posts/namespaces.json
  corehq/ex-submodules/couchforms/tests/data/posts/unicode.json
  corehq/ex-submodules/couchforms/tests/test_duplicates.py
  corehq/ex-submodules/couchforms/tests/test_edits.py
  corehq/ex-submodules/couchforms/tests/test_meta.py
  corehq/ex-submodules/couchforms/tests/test_post.py
  corehq/form_processor/tests/test_basics.py
  corehq/form_processor/tests/test_ledgers.py
  testapps/test_pillowtop/tests/test_reindexer.py
  testapps/test_pillowtop/tests/test_user_pillow.py
Labels: product/invisible, Risk: High

#30315 Add support for batch size in Auditcare Migration command
  corehq/apps/auditcare/couch_to_sql.py
  corehq/apps/auditcare/management/commands/copy_events_to_sql.py
  corehq/apps/auditcare/tests/test_auditcare_migration.py
Labels: product/invisible

#30304 update instructions for removed once off migrations
  corehq/util/django_migrations.py
Labels: product/invisible
