Repository dimagi/commcare-hq, pull requests merged in 2021-10, with the labels that each got.

#30460 [Hubspot] Improve metrics for track_periodic_data
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#30508 Shorten the data dictionary valid values sheet suffix.
  corehq/apps/data_dictionary/tests/data/broken_data_dictionary.xlsx
  corehq/apps/data_dictionary/tests/data/clean_data_dictionary.xlsx
  corehq/apps/data_dictionary/tests/test_import_export.py
  corehq/apps/data_dictionary/views.py
Labels: product/invisible

#30497 Smart linking in web apps: app manager config
  corehq/apps/app_manager/const.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/sections/endpoints.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/test_suite_session_endpoints.py
  corehq/apps/app_manager/views/modules.py
Labels: product/invisible

#30506 create case types in the Data Dictionary via the UI
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/urls.py
  corehq/apps/data_dictionary/views.py
Labels: product/feature-flag

#30501 re-work suite file for data registry search modules
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/data/suite_registry/form_link_followup_module_registry.xml
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/app_manager/tests/util.py
  corehq/apps/app_manager/util.py
  corehq/apps/registry/fixtures.py
Labels: product/feature-flag

#30510 [Hubspot] No longer block users based on email domain, only on domains whose Billing Accounts have blocked hubspot
  corehq/apps/accounting/forms.py
  corehq/apps/analytics/management/commands/list_blocked_from_hubspot.py
  corehq/apps/analytics/management/commands/manually_cleanup_blocked_hubspot_contacts.py
  corehq/apps/analytics/tasks.py
  corehq/apps/analytics/tests/test_hubspot.py
  corehq/apps/analytics/utils.py
Labels: product/invisible

#30515 Removed users/base_template.html
  corehq/apps/users/static/users/js/invite_web_user.js
  corehq/apps/users/templates/users/base_template.html
  corehq/apps/users/templates/users/confirm_turn_off_demo_mode.html
  corehq/apps/users/templates/users/deleted_account.html
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/edit_web_user.html
  corehq/apps/users/templates/users/extra_users_confirm_billing.html
  corehq/apps/users/templates/users/filter_and_download.html
  corehq/apps/users/templates/users/invite_web_user.html
  docs/class_views.rst
Labels: product/invisible

#30521 Update edit messaging permission description
  corehq/apps/users/static/users/js/roles.js
Labels: product/all-users-all-environments

#30512 Dropdown UI for custom filters & actions
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_rule_actions.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_rule_criteria.html
Labels: product/all-users-all-environments

#30520 Prevent error if there is no 'edit_data' permission
  corehq/apps/users/migrations/0037_add_edit_messaging_permission.py
Labels: reindex/migration, product/invisible

#30523 Fixed smart linking of linked app
  corehq/apps/cloudcare/views.py
Labels: product/feature-flag, Risk: Medium

#30439 Add permissions to edit ucrs
  corehq/apps/userreports/views.py
  corehq/apps/users/migrations/0038_add_ucr_permissions.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/apps/users/views/__init__.py
  corehq/tabs/tabclasses.py
Labels: reindex/migration, QA Passed, product/feature-flag

#30526 Added instances for query prompts in entries
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/data/suite_registry/form_link_followup_module_registry.xml
  corehq/apps/app_manager/tests/test_suite_registry_search.py
Labels: product/feature-flag

#30518 Revert "Revert "create case types in the Data Dictionary via the UI""
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/urls.py
  corehq/apps/data_dictionary/views.py
Labels: product/feature-flag

#30522 Allow case searching by "commcare_project"
  corehq/apps/case_search/tests/test_case_search_registry.py
  corehq/apps/case_search/utils.py
Labels: product/feature-flag

#30519 disable case updates for 'registry cases'
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config.html
  corehq/apps/app_manager/tests/test_extension_case.py
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/xform.py
Labels: product/feature-flag

#30529 get_or_create() returns a tuple
  corehq/apps/users/migrations/0037_add_edit_messaging_permission.py
Labels: reindex/migration, product/invisible

#30485 [User History] Updates report to filter by for_domain
  corehq/apps/reports/standard/users/reports.py
Labels: product/feature-flag

#30525 Case API pagination
  corehq/apps/hqcase/api/get_list.py
  corehq/apps/hqcase/tests/test_case_list_api.py
Labels: product/feature-flag

#30492 Updates to error reporting on case import
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/exceptions.py
  corehq/apps/case_importer/templates/case_importer/partials/ko_import_status.html
  corehq/apps/case_importer/tracking/task_status.py
  corehq/apps/data_dictionary/models.py
Labels: product/invisible

#30513 Check domain_obj is not None
  corehq/motech/dhis2/tasks.py
  corehq/motech/dhis2/tests/test_tasks.py
Labels: product/invisible

#30542 Fixed categorization of USH case claim flag
  corehq/toggles.py
Labels: product/admin

#30502 Reorganize PULL_REQUEST_TEMPLATE.md to flow better
  .github/PULL_REQUEST_TEMPLATE.md
Labels: product/invisible

#30539 [Hubspot] Additional cleanup with metrics and unused methods
  corehq/apps/analytics/tasks.py
  corehq/apps/analytics/utils.py
Labels: product/invisible
