Repository dimagi/commcare-hq, pull requests merged in 2021-07, with the labels that each got.

#29955 Remove the unused is_commtrack function
  corehq/util/context_processors.py
Labels: product/invisible

#29982 add date modified column to SMS and Email models
  corehq/apps/sms/migrations/0050_sms_email_date_modified.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tasks.py
  corehq/apps/sms/tests/data_generator.py
  corehq/apps/sms/tests/test_queueing.py
  testapps/test_pillowtop/tests/test_sms_pillow.py
Labels: product/invisible, reindex/migration

#29909 [User History] Report
  corehq/apps/reports/dispatcher.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/standard/users/__init__.py
  corehq/apps/reports/standard/users/reports.py
  corehq/apps/reports/urls.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/custom, product/feature-flag

#29990 move cowin app to custom
  custom/cowin/__init__.py
  custom/cowin/repeater_generators.py
  custom/cowin/repeaters.py
  custom/cowin/signals.py
  custom/cowin/tests.py
  settings.py
Labels: product/invisible

#29988 Query to grab keyword object based on id
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#29991 add 'date_last_activity' to messaging event API and allow ordering / filtering on it
  corehq/apps/api/resources/messaging_event/filters.py
  corehq/apps/api/resources/messaging_event/serializers.py
  corehq/apps/api/resources/messaging_event/utils.py
  corehq/apps/api/resources/messaging_event/view.py
  corehq/apps/api/tests/test_messaging_event_api.py
  corehq/apps/sms/tests/data_generator.py
Labels: Risk: High, product/invisible

#29997 Only save a generated invoice pdf once
  corehq/apps/accounting/invoice_pdf.py
Labels: product/invisible

#29976 Use integer division to calculate months
  corehq/apps/data_pipeline_audit/dbacessors.py
  corehq/apps/data_pipeline_audit/management/commands/compare_doc_ids.py
Labels: product/invisible

#29849 FHIRImporter Admin
  corehq/motech/fhir/admin.py
  corehq/motech/fhir/migrations/0008_blank_search_params.py
  corehq/motech/fhir/models.py
Labels: product/feature-flag, product/invisible, reindex/migration

#29959 [couch-to-sql roles] replace usages of couch role with SQL for authorization
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/api/tests/test_auth.py
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/hqwebapp/tests/test_default_landing_page.py
  corehq/apps/locations/tests/util.py
  corehq/apps/reports/tests/test_views.py
  corehq/apps/saved_reports/tests/test_scheduled_reports.py
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/users/management/commands/populate_user_role.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/permissions.py
  corehq/apps/users/views/__init__.py
Labels: QA Passed, Risk: High, product/invisible

#30000 Use id, not couch_id to get keyword
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#29993 Fix duplicate export properties
  corehq/apps/export/models/new.py
  corehq/apps/export/tests/test_table_configuration.py
Labels: product/invisible

#29973 [User History] Track domain membership removal
  corehq/apps/domain/deletion.py
  corehq/apps/domain/models.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/domain/tests/test_domain_transfer.py
  corehq/apps/domain/views/internal.py
  corehq/apps/settings/views.py
  corehq/apps/users/util.py
  corehq/apps/users/views/__init__.py
Labels: product/invisible

#29975 FHIRImporter: Create parent-child relationships
  corehq/motech/fhir/migrations/0009_jsonpathtoresourcetype_related_resource_is_parent.py
  corehq/motech/fhir/models.py
  corehq/motech/fhir/tasks.py
  corehq/motech/fhir/tests/test_tasks.py
Labels: product/feature-flag, product/invisible, reindex/migration

#29996 FHIRImporter docs
  corehq/motech/fhir/docs/data_dictionary.png
  corehq/motech/fhir/docs/data_forwarding.png
  corehq/motech/fhir/docs/fhir_api.rst
  corehq/motech/fhir/docs/fhir_importer.rst
  corehq/motech/fhir/docs/fhir_repeater.rst
  corehq/motech/fhir/docs/index.rst
Labels: product/invisible

#30006 Modified Service Delivery Reports
  custom/echis_reports/ucr/reports/6_1_Maternal_Health__ANC_BA_FP_.json
  custom/echis_reports/ucr/reports/6_2_Child_Health__CH_EPI_.json
  custom/echis_reports/ucr/reports/6_3_CDC_Nutrition__EPDS_HCSM.json
  custom/echis_reports/ucr/reports/6_4_service_delivery_quarterly_report.json
  custom/echis_reports/ucr/reports/6_5_service_delivery_annual_report.json
Labels: product/custom

#30003 FHIRImporter follow-up
  corehq/apps/domain/deletion.py
  corehq/motech/const.py
  corehq/motech/fhir/admin.py
  corehq/motech/fhir/apps.py
  corehq/motech/fhir/bundle.py
  corehq/motech/fhir/const.py
  corehq/motech/fhir/docs/fhir_import_config.rst
  corehq/motech/fhir/docs/index.rst
  corehq/motech/fhir/migrations/0005_fhirimportconfig.py
  corehq/motech/fhir/migrations/0006_fhirimportresourcetype_resourcetyperelationship.py
  corehq/motech/fhir/migrations/0007_fhirimportresourceproperty.py
  corehq/motech/fhir/migrations/0008_blank_search_params.py
  corehq/motech/fhir/migrations/0009_resourcetyperelationship_related_resource_is_parent.py
  corehq/motech/fhir/migrations/0010_fhirimportconfig_frequency_choices.py
  corehq/motech/fhir/migrations/0011_fhirimportconfig_owner_type.py
  corehq/motech/fhir/models.py
  corehq/motech/fhir/tasks.py
  corehq/motech/fhir/tests/test_fhir_views.py
  corehq/motech/fhir/tests/test_matchers.py
  corehq/motech/fhir/tests/test_models.py
  corehq/motech/fhir/tests/test_tasks.py
  corehq/motech/openmrs/const.py
  corehq/motech/openmrs/forms.py
  corehq/motech/openmrs/models.py
  corehq/motech/openmrs/tests/test_importer.py
  corehq/motech/openmrs/tests/test_tasks.py
Labels: product/feature-flag, reindex/migration

#29844 FHIRImporter
  corehq/apps/domain/deletion.py
  corehq/motech/const.py
  corehq/motech/exceptions.py
  corehq/motech/fhir/admin.py
  corehq/motech/fhir/apps.py
  corehq/motech/fhir/bundle.py
  corehq/motech/fhir/const.py
  corehq/motech/fhir/docs/data_dictionary.png
  corehq/motech/fhir/docs/data_forwarding.png
  corehq/motech/fhir/docs/fhir_api.rst
  corehq/motech/fhir/docs/fhir_import_config.rst
  corehq/motech/fhir/docs/fhir_repeater.rst
  corehq/motech/fhir/docs/index.rst
  corehq/motech/fhir/json-schema/r4/ResourceList.schema.json
  corehq/motech/fhir/json-schema/r4/ServiceRequest.schema.json
  corehq/motech/fhir/migrations/0005_fhirimportconfig.py
  corehq/motech/fhir/migrations/0006_fhirimportresourcetype_resourcetyperelationship.py
  corehq/motech/fhir/migrations/0007_fhirimportresourceproperty.py
  corehq/motech/fhir/migrations/0008_blank_search_params.py
  corehq/motech/fhir/migrations/0009_resourcetyperelationship_related_resource_is_parent.py
  corehq/motech/fhir/migrations/0010_fhirimportconfig_frequency_choices.py
  corehq/motech/fhir/migrations/0011_fhirimportconfig_owner_type.py
  corehq/motech/fhir/models.py
  corehq/motech/fhir/searchers.py
  corehq/motech/fhir/serializers.py
  corehq/motech/fhir/tasks.py
  corehq/motech/fhir/tests/test_bundle.py
  corehq/motech/fhir/tests/test_fhir_views.py
  corehq/motech/fhir/tests/test_matchers.py
  corehq/motech/fhir/tests/test_models.py
  corehq/motech/fhir/tests/test_tasks.py
  corehq/motech/fhir/tests/test_validators.py
  corehq/motech/openmrs/const.py
  corehq/motech/openmrs/forms.py
  corehq/motech/openmrs/models.py
  corehq/motech/openmrs/tests/test_importer.py
  corehq/motech/openmrs/tests/test_tasks.py
Labels: product/feature-flag, product/invisible, reindex/migration

#29995 mgmt command to delete case indices
  corehq/apps/cleanup/management/commands/delete_case_indices.py
Labels: product/invisible

#30015 remove dead code
  corehq/apps/userreports/data_source_providers.py
  corehq/apps/userreports/tests/test_data_source_providers.py
  corehq/apps/userreports/views.py
Labels: product/invisible

#30009 do not index large case property values
  corehq/pillows/mappings/case_search_mapping.json
Labels: product/invisible

#29923 Ensure All Worker Activity Report columns are visible
  corehq/apps/reports/standard/monitoring.py
Labels: product/all-users-all-environments

#30020 Added more time_method decorators within create_suite
  corehq/apps/app_manager/suite_xml/features/scheduler.py
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/post_process/menu.py
  corehq/apps/app_manager/suite_xml/post_process/resources.py
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/sections/endpoints.py
  corehq/apps/app_manager/suite_xml/sections/fixtures.py
  corehq/apps/app_manager/suite_xml/sections/resources.py
Labels: product/invisible

#30022 [User history] fix only userdata log
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/tests/test_importer.py
Labels: product/all-users-all-environments

#30017 Enterprise user overview page
  corehq/apps/cloudcare/esaccessors.py
  corehq/apps/es/users.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/enterprise_users.js
  corehq/apps/users/static/users/js/web_users.js
  corehq/apps/users/static/users/js/web_users_list.js
  corehq/apps/users/templates/users/enterprise_users.html
  corehq/apps/users/urls.py
  corehq/apps/users/views/__init__.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: Risk: Medium, product/feature-flag

#30010 [User History] filter by bulk upload
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/standard/users/reports.py
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tasks.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/migrations/0030_userhistory_user_upload_record.py
  corehq/apps/users/models.py
  corehq/apps/users/util.py
Labels: reindex/migration

#29986 [SSO] Fall back to Display Name if First and Last names are blank
  corehq/apps/sso/tests/generator.py
  corehq/apps/sso/tests/test_backends.py
  corehq/apps/sso/utils/session_helpers.py
Labels: product/feature-flag, product/invisible

#30025 Match columns with rows
  corehq/apps/reports/management/commands/project_stats_report.py
Labels: product/invisible

#30004 Prevent common properties in Case Search properties and filters
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_module_overwrite.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
Labels: product/feature-flag

#30036 Revert "Prevent common properties in Case Search properties and filters"
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_module_overwrite.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
Labels: product/feature-flag

#30028 DEV_SETUP.md Improvements
  DEV_SETUP.md
Labels: product/invisible

#29900 Mixed Type Case Lists and Case Search
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_case_type.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_settings.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/app_manager/xpath.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/apps/ota/views.py
Labels: QA Passed, product/feature-flag

#30034 [User History] track superuser web edit
  corehq/apps/users/forms.py
  corehq/apps/users/views/__init__.py
Labels: product/invisible

#30027 [User History] Improvements
  corehq/apps/api/tests/core_api.py
  corehq/apps/api/tests/user_resources.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/cleanup/tasks.py
  corehq/apps/domain/tests/test_domain_transfer.py
  corehq/apps/hqadmin/views/users.py
  corehq/apps/receiverwrapper/tests/test_submissions.py
  corehq/apps/reports/filters/users.py
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/util.py
Labels: product/invisible

#30024 [User History] log role update only when role changes
  corehq/apps/users/forms.py
Labels: product/invisible

#29998 Remove @ prefix from v0.6 case API
  corehq/apps/hqcase/api/core.py
  corehq/apps/hqcase/api/updates.py
  corehq/apps/hqcase/tests/test_case_sharing.py
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/hqcase/tests/test_get_case.py
  corehq/apps/hqcase/tests/test_serialization.py
  corehq/apps/hqcase/views.py
Labels: product/feature-flag

#30040 Reminders/Session Endpoints: Exclude datums that can be computed
  corehq/apps/app_manager/suite_xml/sections/endpoints.py
  corehq/apps/app_manager/tests/test_suite_session_endpoints.py
Labels: product/feature-flag

#30037 Revert "Revert "Prevent common properties in Case Search properties and filters""
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_module_overwrite.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
Labels: product/feature-flag

#30029 Validate xpath expressions in search and claim options
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#30005 Nit: isort jsonschema
  .isort.cfg
Labels: product/invisible

#30014 UCR pillow refactor in preparation for cross domain UCRs
  corehq/apps/userreports/pillow.py
  corehq/apps/userreports/pillow_utils.py
  corehq/apps/userreports/rebuild.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/tests/test_rebuild_migrate.py
  corehq/pillows/case.py
  corehq/pillows/user.py
  corehq/pillows/xform.py
  testapps/test_pillowtop/tests/base.py
Labels: product/invisible

#30033 Fix location restriction bug in Worker Activity Report
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/standard/inspect.py
Labels: product/invisible

#30044 Fix docs, take 2
  corehq/apps/es/es_query.py
  corehq/motech/fhir/README.txt
  corehq/motech/openmrs/docs/index.rst
  corehq/pillows/case.py
  docs/conf.py
  docs/fhir.rst
  docs/fhir/data_dictionary.png
  docs/fhir/data_forwarding.png
  docs/fhir/fhir_api.rst
  docs/fhir/fhir_import_config.rst
  docs/fhir/fhir_repeater.rst
  docs/fhir/index.rst
  docs/index.rst
  docs/motech.rst
  docs/value_source.rst
  requirements/base-requirements.in
  requirements/docs-requirements.in
  requirements/docs-requirements.txt
Labels: dependencies, product/invisible

#29992 [SSO] ensure that the username received by the Identity Provider is in lowercase
  corehq/apps/sso/backends.py
  corehq/apps/sso/tests/test_backends.py
Labels: QA Passed, product/feature-flag, product/invisible

#29999 [SSO] Ensure that the first domain for new SSO users is active
  corehq/apps/registration/tests/test_utils.py
  corehq/apps/registration/utils.py
  corehq/apps/sso/views/saml.py
Labels: QA Passed, Risk: High, product/invisible, product/prod-india-all-users

#30047 Add domain param to user delete
  corehq/apps/registration/tests/test_utils.py
Labels: product/invisible

#29985 Followup Forms as Case List Form for parent/select modules
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_form_setting.html
  corehq/apps/app_manager/tests/test_case_list_form.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/hqwebapp/static/hqwebapp/js/components/select_toggle.js
  corehq/apps/hqwebapp/templates/hqwebapp/partials/ko_select_toggle.html
  corehq/toggles.py
Labels: QA Passed, Risk: Medium, product/feature-flag

#30045 [SSO] Update documentation links
  corehq/apps/sso/forms.py
  corehq/apps/sso/utils/url_helpers.py
Labels: product/prod-india-all-users

#30046 [SSO] ensure that the check for the user redirect on the invitation view matches what is expected for validating the form
  corehq/apps/users/views/web.py
Labels: product/invisible

#30030 [SSO] ensure that SSO superusers do not have access to superuser functionality beyond their domain
  corehq/apps/domain/decorators.py
  corehq/apps/reports/dispatcher.py
  corehq/tabs/tabclasses.py
Labels: QA Passed, Risk: High, product/all-users-all-environments

#30031 [SSO] Remove ENTERPRISE_SSO toggle/feature flag
  corehq/apps/domain/decorators.py
  corehq/apps/domain/tests/test_two_factor_check.py
  corehq/apps/settings/views.py
  corehq/apps/sso/views/accounting_admin.py
  corehq/apps/sso/views/enterprise_admin.py
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/invite_web_user.js
  corehq/apps/users/templates/users/edit_web_user.html
  corehq/apps/users/templates/users/web_users.html
  corehq/apps/users/views/__init__.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: QA Passed, Risk: High, product/all-users-all-environments

#30041 Remove inheritance of reports templates from tableau visualizations
  corehq/apps/reports/templates/reports/tableau_template.html
Labels: product/feature-flag

#30048 Disabled Calculate Total from Service Delivery Reports
  custom/echis_reports/ucr/reports/6_4_service_delivery_quarterly_report.json
  custom/echis_reports/ucr/reports/6_5_service_delivery_annual_report.json
Labels: product/invisible

#30018 Remote Linked Reports
  corehq/apps/app_manager/views/utils.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/partials/link_remote_ucr.html
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/linked_domain/tests/test_linked_userreports.py
  corehq/apps/linked_domain/ucr.py
  corehq/apps/linked_domain/urls.py
  corehq/apps/linked_domain/views.py
Labels: product/feature-flag

#30035 Add lookup table info to app summary
  corehq/apps/app_manager/app_schemas/app_case_metadata.py
  corehq/apps/app_manager/app_schemas/form_metadata.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/form_summary_base.html
Labels: product/all-users-all-environments

#30054 add missing method override
  corehq/apps/userreports/pillow.py
  corehq/apps/userreports/tests/test_pillow.py
Labels: product/invisible

#30053 [Enterprise] Don't throw a 500 if `couch_user` is not an attribute of `request`
  corehq/apps/accounting/utils/account.py
  corehq/apps/enterprise/decorators.py
Labels: product/invisible

#30060 Move complexity metrics into python
  corehq/apps/hqadmin/management/commands/static_analysis.py
  docker/run.sh
  scripts/static-analysis.sh
Labels: product/invisible

#30059 Add linked project privilege for enterprise subscriptions
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0055_linked_projects.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
Labels: product/invisible, reindex/migration

#30051 ES cleanup: remove ES7 logic
  corehq/apps/es/es_query.py
  corehq/apps/es/tests/test_esqueryset.py
  corehq/apps/hqcase/management/commands/reindex_es_from_remote.py
  corehq/apps/reports/analytics/esaccessors.py
  corehq/ex-submodules/pillowtop/es_utils.py
  corehq/ex-submodules/pillowtop/index_settings.py
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
  corehq/ex-submodules/pillowtop/tests/utils.py
  corehq/ex-submodules/pillowtop/utils.py
  corehq/pillows/case_search.py
  corehq/pillows/core.py
  corehq/pillows/mappings/utils.py
  corehq/util/es/elasticsearch.py
  corehq/util/es/interface.py
  docker/localsettings.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  testsettings.py
Labels: Risk: High, dependencies, product/invisible

#29936 Split feature flags and feature previews into their own data models
  corehq/apps/linked_domain/README.md
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/filters.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/migrations/0015_add_previews_to_choices_20210617_2010.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/tests/test_update_previews.py
  corehq/apps/linked_domain/tests/test_update_toggles.py
  corehq/apps/linked_domain/tests/test_view_helpers.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
Labels: QA Passed, product/feature-flag, reindex/migration

#30066 Search for deleted domain links in linked report migration
  corehq/apps/linked_domain/management/commands/add_app_id_to_linked_reports.py
Labels: product/invisible

#30068 Only show list if data_source is defined
  corehq/apps/app_manager/templates/app_manager/form_summary_base.html
Labels: product/invisible

#30052 [ERM UI] Landing page if domain contains no links
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/get_started.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/manage_downstream_domains_tab.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/pull_release_content_tab.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/push_release_content_tab.html
  corehq/apps/linked_domain/views.py
Labels: product/feature-flag

#30073 Revert "Split feature flags and feature previews into their own data models"
  corehq/apps/linked_domain/README.md
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/filters.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/migrations/0015_add_previews_to_choices_20210617_2010.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/tests/test_update_previews.py
  corehq/apps/linked_domain/tests/test_update_toggles.py
  corehq/apps/linked_domain/tests/test_view_helpers.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
Labels: reindex/migration

#30039 Smart Linking MVP: Login As
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
  corehq/apps/cloudcare/views.py
  corehq/apps/ota/views.py
Labels: Risk: Medium, product/invisible

#30071 Remove computed var
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
Labels: product/invisible

#30069 [Case Search] Make property = '' match both blank and missing values
  corehq/apps/es/case_search.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/hqcase/tasks.py
Labels: product/invisible

#30026 Smart linking MVP: claim cases
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/cloudcare/views.py
  corehq/apps/ota/urls.py
  corehq/apps/ota/views.py
Labels: Risk: Medium, product/invisible

#30070 Remove unnecessary reference to outdated variable
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#30080 Remove unused import
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#30076 Revert "Revert "Split feature flags and feature previews into their own data models""
  corehq/apps/linked_domain/README.md
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/filters.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/migrations/0015_add_previews_to_choices_20210617_2010.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/tests/test_update_previews.py
  corehq/apps/linked_domain/tests/test_update_toggles.py
  corehq/apps/linked_domain/tests/test_view_helpers.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
Labels: product/feature-flag, reindex/migration

#30074 reset date modified for legacy sms and email data
  corehq/apps/sms/migrations/0051_reset_modified_on.py
Labels: product/invisible, reindex/migration

#30079 Single view for Tableau reports
  corehq/apps/reports/models.py
  corehq/apps/reports/standard/tableau.py
  corehq/apps/reports/templates/reports/tableau_template.html
  corehq/apps/reports/urls.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#30086 Fix failing test on base branch
  corehq/apps/linked_domain/tests/test_dbaccessors.py
Labels: product/invisible

#30065 Added README for web apps front end (docs only)
  docs/cloudcare.rst
  docs/web_apps.rst
Labels: product/invisible

#30087 Updated ReadTheDocs TOC
  docs/index.rst
Labels: product/invisible

#30094 Update staging.yaml
  scripts/staging.yaml
Labels: product/invisible

#30091 Add release management priv to enterprise_plan_v1
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0056_add_release_management.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
Labels: product/invisible, reindex/migration

#30092 remove unlinking cleanup
  corehq/apps/linked_domain/views.py
Labels: product/feature-flag

#30081 Linked projects UI depends on feature flag vs privilege
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0056_add_release_management.py
  corehq/apps/es/case_search.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/hqcase/tasks.py
  corehq/apps/linked_domain/README.md
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/filters.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/migrations/0015_add_previews_to_choices_20210617_2010.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/manage_downstream_domains_tab.html
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/tests/test_update_previews.py
  corehq/apps/linked_domain/tests/test_update_toggles.py
  corehq/apps/linked_domain/tests/test_view_helpers.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reports/models.py
  corehq/apps/reports/standard/tableau.py
  corehq/apps/reports/templates/reports/tableau_template.html
  corehq/apps/reports/urls.py
  corehq/apps/sms/migrations/0051_reset_modified_on.py
  corehq/privileges.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
  docs/cloudcare.rst
  docs/index.rst
  docs/web_apps.rst
  scripts/staging.yaml
Labels: product/feature-flag, reindex/migration

#30064 [User History] Don't translate messages
  corehq/apps/domain/models.py
  corehq/apps/settings/views.py
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/importer.py
  corehq/apps/users/util.py
  corehq/apps/users/views/__init__.py
Labels: product/invisible

#30097 add es6 support to eslintrc
  .eslintrc.js
Labels: product/invisible

#30096 Always run static analysis code
  corehq/apps/hqadmin/management/commands/static_analysis.py
  docker/run.sh
Labels: product/invisible

#30067 Restrict Tableau server dropdown to just servers configured within the domain
  corehq/apps/reports/forms.py
Labels: product/feature-flag

#30049 remove unused functions
  corehq/apps/userreports/tests/utils.py
Labels: product/invisible

#30088 [SSO] temporarily make default state of general login form show both username and password fields initially
  corehq/apps/registration/static/registration/js/user_login_form.js
Labels: product/prod-india-all-users

#30061 [SSO] If a domain is not using SSO, do not enforce SSO login on the domain-specifc login UI
  corehq/apps/hqwebapp/views.py
  corehq/apps/sso/models.py
  corehq/apps/sso/tests/test_domain_helpers.py
  corehq/apps/sso/utils/domain_helpers.py
Labels: product/prod-india-all-users

#30093 Replace comment to be more explicit
  corehq/apps/custom_data_fields/models.py
Labels: Risk: Medium, product/invisible

#30089 Re-release: Moved enterprise permissions to enterprise console (2 of 3)
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/generator.py
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/domain/decorators.py
  corehq/apps/domain/views/base.py
  corehq/apps/enterprise/models.py
  corehq/apps/enterprise/tasks.py
  corehq/apps/enterprise/templates/enterprise/enterprise_permissions.html
  corehq/apps/enterprise/templates/enterprise/partials/enterprise_permissions_table.html
  corehq/apps/enterprise/tests/test_permissions.py
  corehq/apps/enterprise/tests/utils.py
  corehq/apps/enterprise/urls.py
  corehq/apps/enterprise/views.py
  corehq/apps/es/users.py
  corehq/apps/formplayer_api/clear_user_data.py
  corehq/apps/formplayer_api/sync_db.py
  corehq/apps/formplayer_api/utils.py
  corehq/apps/hqwebapp/session_details_endpoint/views.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/ota/utils.py
  corehq/apps/reports/filters/fixtures.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/saved_reports/models.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/user_importer/validation.py
  corehq/apps/users/admin.py
  corehq/apps/users/forms.py
  corehq/apps/users/migrations/0028_remove_domainpermissionsmirror.py
  corehq/apps/users/models.py
  corehq/apps/users/tasks.py
  corehq/apps/users/templates/users/domain_permissions_mirror.html
  corehq/apps/users/tests/test_tasks.py
  corehq/apps/users/urls.py
  corehq/apps/users/views/__init__.py
  corehq/middleware.py
  corehq/tabs/tabclasses.py
  corehq/tabs/templatetags/menu_tags.py
  corehq/tabs/uitab.py
Labels: Risk: High, Risk: Medium, product/feature-flag, reindex/migration

#30098 Remove domain username override option
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/reports/forms.py
  corehq/apps/reports/migrations/0006_remove_tableauserver_allow_domain_username_override.py
  corehq/apps/reports/models.py
  corehq/apps/reports/standard/tableau.py
Labels: product/feature-flag, reindex/migration

#30101 Clear cache for upstream domain, not downstream
  corehq/apps/linked_domain/models.py
Labels: product/invisible

#30063 Only return domains that are eligible to link downstream
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/tests/test_dbaccessors.py
Labels: product/invisible

#30082 Add management commands to setup linked domains
  corehq/apps/linked_domain/README.md
  corehq/apps/linked_domain/management/commands/add_downstream_domain.py
  corehq/apps/linked_domain/management/commands/link_to_upstream_domain.py
Labels: product/feature-flag

#30109 Use repeater name in success message
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/views/repeaters.py
Labels: product/invisible

#30106 Smart Linking: Removed case id validation
  corehq/apps/cloudcare/views.py
Labels: Risk: Medium, product/invisible

#30108 don't restrict knockout select2 binding to single selects
  corehq/apps/hqwebapp/static/hqwebapp/js/select2_knockout_bindings.ko.js
Labels: product/invisible

#30104 Validate case name and external ID max length
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/exceptions.py
  corehq/apps/case_importer/tests/test_importer.py
  corehq/form_processor/backends/sql/update_strategy.py
  corehq/form_processor/models.py
Labels: Risk: High, product/all-users-all-environments

#30112 Web apps js file renames
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/form_ui_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/web_form_session_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/hq_events.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/hq_events_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer_inline.js
  corehq/apps/cloudcare/templates/cloudcare/includes/formplayer-inline.html
  corehq/apps/cloudcare/templates/cloudcare/spec/form_entry/mocha.html
  corehq/apps/cloudcare/templates/cloudcare/spec/mocha.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/apps/reports/templates/reports/form/edit_submission.html
  docs/web_apps.rst
Labels: Risk: Medium, product/invisible

#30105 Linked Project Space UI Improvements
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/get_started.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/manage_downstream_domains_tab.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/pull_release_content_tab.html
  corehq/apps/linked_domain/templates/linked_domain/tabs/push_release_content_tab.html
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#30103 Fix tab issue
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
Labels: product/invisible

#30107 Cleanup for make superuser access
  corehq/apps/domain/management/commands/make_superuser.py
  settings.py
Labels: product/invisible

#30055 Cs/sc 1622 Feature flags download button
  corehq/apps/toggle_ui/static/toggle_ui/js/flags.js
  corehq/apps/toggle_ui/templates/toggle/flags.html
  corehq/apps/toggle_ui/urls.py
  corehq/apps/toggle_ui/utils.py
  corehq/apps/toggle_ui/views.py
Labels: product/admin

#30114 added label with count of linked mobile users
  corehq/apps/users/templates/users/enterprise_users.html
Labels: product/feature-flag

#30118 Updated success messages for enterprise permissions
  corehq/apps/enterprise/views.py
Labels: product/feature-flag

#30120 Added README.md [ci skip]
  corehq/apps/cloudcare/README.md
Labels: Risk: Medium, product/invisible

#29965 Create missing form repeat records
  corehq/motech/repeaters/management/commands/find_missing_repeat_records.py
Labels: product/invisible

#30124 Add migration for remote_base_url help_text field
  corehq/apps/linked_domain/migrations/0016_update_remote_base_url_help_text.py
Labels: product/invisible, reindex/migration

#30123 Removed duplicate button
  corehq/apps/data_interfaces/templates/data_interfaces/case_rule.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_rule_actions.html
Labels: product/all-users-all-environments

#29865 Moved enterprise permissions to enterprise console (3 of 3)
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/users/migrations/0031_delete_domainpermissionsmirror.py
  corehq/apps/users/models.py
Labels: product/invisible, reindex/migration

#30058 User history report UX updates
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/standard/users/reports.py
  corehq/apps/reports/static/reports/js/user_history.js
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/apps/reports/templates/reports/standard/partials/user_history_changes.html
  corehq/apps/reports/urls.py
  corehq/apps/users/models.py
  corehq/apps/users/urls.py
Labels: product/feature-flag

#30130 Update text on Linked Project Space History report
  corehq/apps/linked_domain/filters.py
  corehq/apps/linked_domain/views.py
Labels: product/all-users-all-environments

#30119 get doc shard counts
  corehq/apps/hqadmin/tasks.py
Labels: product/invisible

#30122 Updated save button trigger on custom fields page
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
Labels: Risk: Medium, product/invisible

#30131 [js dependencies] resolve minimist to at least 0.2.1
  package.json
  yarn.lock
Labels: dependencies, dependencies/javascript, product/invisible

#30001 Move help text in forms
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/utils.less
Labels: QA Passed, Risk: Medium, awaiting QA, product/all-users-all-environments

#30116 Disable Copy as Linked Application when appropriate
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/templates/app_manager/app_view_settings.html
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/linked_domain/tests/test_linked_domain_utils.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/views.py
Labels: product/all-users-all-environments

#30132 Added help link for enterprise user management UI
  corehq/toggles.py
Labels: product/admin

#30135 Dynamic options for multiselect custom binding
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/templates/linked_domain/tabs/push_release_content_tab.html
Labels: product/all-users-all-environments

#30137 Moved tableau import to fix docs build
  corehq/apps/reports/standard/tableau.py
Labels: product/invisible

#30138 Limit upstream domains based on account vs user
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/tests/test_linked_domain_utils.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#30111 Enable the case search index when turning on new case API flag
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/hqcase/views.py
  corehq/pillows/case_search.py
  corehq/toggles.py
Labels: product/feature-flag

#30144 mention snakevis in profiling readme
  docs/profiling.rst
Labels: product/invisible

#30140 Fixed notification popup for required questions always displaying
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: Risk: Medium, product/all-users-all-environments

#30139 Updated URL for smart links
  corehq/apps/cloudcare/urls.py
  corehq/apps/hqwebapp/urls.py
Labels: Risk: Medium, product/invisible

#30126 Added uniqueness constraint on EnterprisePermissions.account
  corehq/apps/enterprise/migrations/0002_enterprisepermissions_account_unique.py
  corehq/apps/enterprise/models.py
Labels: product/invisible, reindex/migration

#30077 Add ERM section to Project Settings with appropriate permissions
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/tests/test_decorators.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/reports/urls.py
  corehq/tabs/tabclasses.py
  corehq/tabs/tests.py
Labels: product/invisible

#29954 CSRF protection for formplayer
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/formplayer_api/form_validation.py
  corehq/apps/hqwebapp/static/hqwebapp/js/hq.helpers.js
Labels: Risk: High, product/all-users-all-environments

#29836 Added a new smsbillable report for enterprise users
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_models.py
  corehq/apps/enterprise/dispatcher.py
  corehq/apps/enterprise/filters.py
  corehq/apps/enterprise/interface.py
  corehq/apps/enterprise/tests/test_interface.py
  corehq/apps/enterprise/urls.py
  corehq/apps/reports/static/reports/css/daterange-font-color.css
  corehq/apps/reports/templates/reports/filters/daterange.html
  corehq/apps/saved_reports/models.py
  corehq/apps/smsbillables/interface.py
  corehq/apps/smsbillables/models.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
Labels: awaiting QA, product/admin

#30095 Case upload validate dates
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/exceptions.py
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/tests/test_models.py
  corehq/apps/data_dictionary/tests/utils.py
  corehq/apps/data_dictionary/util.py
  corehq/toggles.py
Labels: QA Passed, product/feature-flag

#30154 tag domain for all restore timings
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/util/metrics/utils.py
  settings.py
Labels: product/invisible

#30083 Reverse execution order in Auditcare Migration
  corehq/apps/auditcare/couch_to_sql.py
  corehq/apps/auditcare/tests/test_auditcare_migration.py
  corehq/apps/auditcare/utils/migration.py
Labels: Risk: High, Risk: Medium, reindex/migration

#30011 Data models for Data Registries
  corehq/apps/domain/deletion.py
  corehq/apps/domain/utils.py
  corehq/apps/registry/README.md
  corehq/apps/registry/__init__.py
  corehq/apps/registry/admin.py
  corehq/apps/registry/exceptions.py
  corehq/apps/registry/migrations/0001_initial.py
  corehq/apps/registry/migrations/__init__.py
  corehq/apps/registry/models.py
  corehq/apps/registry/tests/__init__.py
  corehq/apps/registry/tests/test_logging.py
  corehq/apps/registry/tests/test_models.py
  corehq/apps/registry/tests/utils.py
  corehq/toggles.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
Labels: dependencies, product/invisible, reindex/migration

#30157 Modified Date Indicators, Modified Service Delivery Indicators, Bug Fix
  custom/echis_reports/ucr/data_sources/service_delivery_dsV11.json
  custom/echis_reports/ucr/data_sources/service_delivery_dsV13.json
  custom/echis_reports/ucr/reports/6_1_Maternal_Health__ANC_BA_FP_.json
  custom/echis_reports/ucr/reports/6_2_Child_Health__CH_EPI_.json
  custom/echis_reports/ucr/reports/6_3_CDC_Nutrition__EPDS_HCSM.json
Labels: product/feature-flag

#30050 Add download and email reports permission
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/apps/hqadmin/templates/hqadmin/hqadmin_base_report.html
  corehq/apps/reports/templates/reports/partials/filter_panel.html
  corehq/apps/reports/templates/reports/reports_home.html
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/apps/reports/templates/reports/standard/partials/filter_panel.html
  corehq/apps/reports/views.py
  corehq/apps/users/management/commands/add_download_reports_permission.py
  corehq/apps/users/migrations/0032_add_download_reports_permission.py
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/partials/edit_role_modal.html
Labels: QA Passed, product/feature-flag, reindex/migration

#30125 Get some more detail on app build timings
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/hqadmin/views/users.py
  corehq/apps/hqmedia/tasks.py
Labels: product/admin

#30159 Fixed form linking logic to support form in a different child module
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/data/form_workflow/form_link_submodule.xml
  corehq/apps/app_manager/tests/test_form_workflow.py
Labels: product/feature-flag

#30141 Updated web apps error navigation to not happen until submit
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
Labels: QA Passed, Risk: Medium, product/all-users-all-environments

#30162 Switched EnterprisePermissions.account to a OneToOneField
  corehq/apps/enterprise/migrations/0003_enterprisepermissions_modify_account.py
  corehq/apps/enterprise/models.py
Labels: product/invisible, reindex/migration

#30127 Cs/sc 1529 multiple mobile numbers upload
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/bulk_download.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_download.py
Labels: Risk: Medium, awaiting QA

#30151 Fix conflicting active tabs on linked projects page
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
Labels: product/invisible

#30078 Report on code coverage
  .travis.yml
  codecov.yml
  docker/hq-compose.yml
  docker/run.sh
  docs/test_coverage.rst
  requirements/dev-requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
  scripts/docker
Labels: dependencies, product/invisible

#30164 Change query to use a substitute for 'exclude'
  corehq/apps/users/management/commands/add_download_reports_permission.py
Labels: product/invisible
