Repository dimagi/commcare-hq, pull requests merged in 2021-11, with the labels that each got.

#30621 Upgrade xlrd for Python 3.9
  corehq/apps/smsbillables/management/commands/bootstrap_mach_gateway.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, product/invisible, dependencies

#30611 Upgrade gevent and greenlet
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, product/invisible, dependencies

#30664 add correct form command when computing app workflow
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/data/form_workflow/suite-workflow-module-in-root.xml
  corehq/apps/app_manager/tests/data/form_workflow/suite-workflow-previous.xml
Labels: product/invisible

#30673 Use https instead of git
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#30624 deleted RegistryPermission model and related import
  corehq/apps/domain/deletion.py
  corehq/apps/registry/admin.py
  corehq/apps/registry/migrations/0007_delete_registrypermission.py
  corehq/apps/registry/models.py
Labels: reindex/migration, product/invisible

#30675 Move submodules to pull from https
  .gitmodules
Labels: product/invisible

#30672 Airflow is no longer used
  DEV_SETUP.md
Labels: product/invisible

#30680 Renamed xml_model.XPath => TextXPath
  corehq/apps/app_manager/suite_xml/features/mobile_ucr.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/xml_models.py
Labels: product/invisible

#30677 Removed smart linking from app preview
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
Labels: product/invisible, Risk: Medium

#30625 Smart linking in web apps: Stack jumps
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/post_process/endpoints.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/data/suite_registry/detail_tabs.xml
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/formdesigner.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/xform.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/util.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer/case_detail.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/cloudcare/views.py
Labels: product/invisible, Risk: Medium

#30182 Stop using ES search_type=scan
  corehq/apps/data_interfaces/tests/test_xform_management.py
  corehq/apps/es/es_query.py
  corehq/apps/es/exceptions.py
  corehq/apps/es/forms.py
  corehq/apps/es/registry.py
  corehq/apps/es/tests/test_registry.py
  corehq/apps/es/tests/test_test_utils.py
  corehq/apps/es/tests/utils.py
  corehq/apps/hqadmin/tests/test_stale_data_in_es.py
  corehq/apps/hqadmin/views/data.py
  corehq/apps/hqcase/management/commands/initialize_es_indices.py
  corehq/apps/hqcase/management/commands/reindex_es_native.py
  corehq/apps/hqcase/tests/test_dbaccessors.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/userreports/util.py
  corehq/elastic.py
  corehq/ex-submodules/couchforms/tests/test_analytics.py
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
  corehq/ex-submodules/pillowtop/tests/test_bulk.py
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
  corehq/ex-submodules/pillowtop/tests/utils.py
  corehq/pillows/app_config.py
  corehq/pillows/mappings/__init__.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/const.py
  corehq/pillows/mappings/xform_mapping.py
  corehq/pillows/user.py
  corehq/tests/test_elastic.py
  corehq/util/es/elasticsearch.py
  corehq/util/es/interface.py
  corehq/util/es/tests/__init__.py
  corehq/util/es/tests/test_interface.py
  settings.py
Labels: reindex/migration, product/invisible, Risk: High

#30676 Limited data registries to CC 2.53+
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/registry/tests/test_fixtures.py
Labels: product/feature-flag

#30687 Revert "Stop using ES search_type=scan"
  corehq/apps/data_interfaces/tests/test_xform_management.py
  corehq/apps/es/es_query.py
  corehq/apps/es/exceptions.py
  corehq/apps/es/forms.py
  corehq/apps/es/registry.py
  corehq/apps/es/tests/test_registry.py
  corehq/apps/es/tests/test_test_utils.py
  corehq/apps/es/tests/utils.py
  corehq/apps/hqadmin/tests/test_stale_data_in_es.py
  corehq/apps/hqadmin/views/data.py
  corehq/apps/hqcase/management/commands/initialize_es_indices.py
  corehq/apps/hqcase/management/commands/reindex_es_native.py
  corehq/apps/hqcase/tests/test_dbaccessors.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/userreports/util.py
  corehq/elastic.py
  corehq/ex-submodules/couchforms/tests/test_analytics.py
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
  corehq/ex-submodules/pillowtop/tests/test_bulk.py
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
  corehq/ex-submodules/pillowtop/tests/utils.py
  corehq/pillows/app_config.py
  corehq/pillows/mappings/__init__.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/const.py
  corehq/pillows/mappings/xform_mapping.py
  corehq/pillows/user.py
  corehq/tests/test_elastic.py
  corehq/util/es/elasticsearch.py
  corehq/util/es/interface.py
  corehq/util/es/tests/__init__.py
  corehq/util/es/tests/test_interface.py
  settings.py
Labels: reindex/migration, product/invisible, Risk: High

#30448 Use localhost instead of 0.0.0.0 in DEV_SETUP.md
  DEV_SETUP.md
Labels: product/invisible

#30684 Fix moved help link
  corehq/toggles.py
Labels: product/invisible

#30682 Provide some feedback when importing builds
  corehq/apps/builds/management/commands/add_commcare_build.py
Labels: product/invisible

#30679 Added daylight savings command for reports
  corehq/apps/saved_reports/management/commands/daylight_savings.py
  corehq/apps/saved_reports/tests/test_daylight_savings.py
Labels: product/invisible

#30669 registry case update changes
  corehq/apps/registry/helper.py
  corehq/ex-submodules/casexml/apps/case/mock/case_block.py
  corehq/form_processor/exceptions.py
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_payload_generator.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_repeater.py
Labels: product/feature-flag, Risk: High

#30685 change how "additional registry queries" works
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/data/suite_registry/form_link_followup_module_registry.xml
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/app_manager/xform.py
  corehq/apps/ota/tests/test_registry_case_details.py
  corehq/apps/ota/views.py
  corehq/apps/registry/helper.py
  corehq/apps/registry/tests/test_helper.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/exceptions.py
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_payload_generator.py
Labels: product/feature-flag, Risk: High

#30425 Case Deduplication
  corehq/apps/data_interfaces/admin.py
  corehq/apps/data_interfaces/deduplication.py
  corehq/apps/data_interfaces/migrations/0023_auto_20210914_1726.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/static/data_interfaces/js/case_dedupe_main.js
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/templates/data_interfaces/edit_deduplication_rule.html
  corehq/apps/data_interfaces/templates/data_interfaces/list_deduplication_rules.html
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/apps/data_interfaces/urls.py
  corehq/apps/data_interfaces/utils.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/domain/deletion.py
  corehq/apps/hqcase/utils.py
  corehq/apps/linked_domain/README.md
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/cases/duplicate_cases.py
  corehq/apps/reports/standard/cases/filters.py
  corehq/apps/users/tasks.py
  corehq/messaging/management/commands/manage_rule_run.py
  corehq/messaging/tasks.py
  corehq/messaging/util.py
  corehq/pillows/xform.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
  settings.py
Labels: reindex/migration, product/feature-flag

#30681 Management command to call task synchronously
  custom/onse/management/commands/update_onse_facility_cases.py
  custom/onse/tasks.py
  custom/onse/tests.py
Labels: product/invisible

#30693 for web users the username is used for owner ids of scheduled reports
  corehq/apps/reports/views.py
Labels: product/invisible

#30699 swapped columns
  corehq/apps/reports/standard/users/reports.py
Labels: product/feature-flag

#30667 delete clean owners
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/domain/deletion.py
  corehq/apps/domain/models.py
  corehq/apps/domain/templates/domain/admin/flags_and_privileges.html
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/domain/views/internal.py
  corehq/apps/formplayer_api/sync_db.py
  corehq/apps/hqcase/tasks.py
  corehq/apps/ota/views.py
  corehq/ex-submodules/casexml/apps/case/xform.py
  corehq/ex-submodules/casexml/apps/phone/admin.py
  corehq/ex-submodules/casexml/apps/phone/cleanliness.py
  corehq/ex-submodules/casexml/apps/phone/const.py
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/clean_owners.py
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/providers.py
  corehq/ex-submodules/casexml/apps/phone/exceptions.py
  corehq/ex-submodules/casexml/apps/phone/management/commands/set_cleanliness_flags.py
  corehq/ex-submodules/casexml/apps/phone/migrations/0007_delete_ownershipcleanlinessflag.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/ex-submodules/casexml/apps/phone/tasks.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_cleanliness.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_extension_indexes.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_new_sync.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py
  corehq/ex-submodules/casexml/apps/phone/utils.py
  corehq/form_processor/submission_post.py
  corehq/toggles.py
Labels: reindex/migration, product/invisible, Risk: High, Risk: Medium

#30535 [User History] tracks invitations accepted by existing users
  corehq/apps/users/views/web.py
Labels: product/invisible

#30697 remove registry access check in get_granted_domains
  corehq/apps/registry/models.py
  corehq/apps/registry/tests/test_models.py
Labels: product/feature-flag

#30527 [User history] update report property filter
  corehq/apps/reports/standard/users/reports.py
  corehq/apps/users/audit/change_messages.py
Labels: product/feature-flag

#30695 Refs QA-3628 Consistent use of italic blank for empty strings...
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-input-map.js
Labels: product/invisible

#30698 [security] upgrade set-value to 4.0.1
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#30700 Added back handling for smart links in web apps
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
Labels: product/invisible, Risk: Medium

#30705 Sk/dr workflow
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#30701 Allow inactive duplicate rules to show in explorer
  corehq/apps/data_interfaces/models.py
Labels: product/feature-flag

#30696 Encode username in redirect url
  corehq/apps/hqadmin/tests/test_views.py
  corehq/apps/hqadmin/views/users.py
Labels: product/invisible

#30708 Attempt to access multimedia blob when finding missing media
  corehq/apps/linked_domain/util.py
Labels: product/feature-flag

#30709 [Hubspot] update rejected.get_user_hubspot_id to use metrics_counter instead of metrics_gauge
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#30706 Use html.escape instead of cgi.escape
  corehq/apps/reports/standard/message_event_display.py
  corehq/apps/reports/tests/test_message_event_display.py
Labels: product/invisible

#30689 Add details about reference updates
  docs/apps/advanced_app_features.rst
Labels: product/invisible

#30703 Add pickle5 support for Python 3.6
  corehq/tests/test_pickle.py
  manage.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
Labels: product/invisible, dependencies

#30665 Add support to resume cancelled batches
  corehq/apps/auditcare/couch_to_sql.py
  corehq/apps/auditcare/management/commands/copy_events_to_sql.py
  corehq/apps/auditcare/tests/test_auditcare_migration.py
  corehq/apps/auditcare/utils/migration.py
Labels: product/invisible

#30702 Updated smart link generation to include endpoint args
  corehq/apps/app_manager/suite_xml/generator.py
  corehq/apps/app_manager/suite_xml/post_process/endpoints.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/test_suite_remote_request.py
Labels: product/invisible

#30715 fix JS error in report builder data source select
  corehq/apps/userreports/static/userreports/js/data_source_select.js
Labels: product/invisible

#30716 fix casedb schema for advanced modules
  corehq/apps/app_manager/app_schemas/casedb_schema.py
  corehq/apps/app_manager/app_schemas/tests/test_schema.py
Labels: product/invisible

#30694 User cases not updating on profile change
  corehq/apps/callcenter/tasks.py
  corehq/apps/custom_data_fields/edit_model.py
Labels: awaiting QA, product/feature-flag, Risk: Medium

#30711 Make linked apps/domains docs a bit easier to read
  corehq/apps/linked_domain/README.md
  corehq/apps/linked_domain/management/commands/link_app_to_remote.py
Labels: product/invisible

#30704 set date_opened and date_modified for cases updated by DR
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_payload_generator.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_repeater.py
Labels: product/feature-flag

#30666 [Security] Upgrade babel to >= 2.9.1
  corehq/apps/settings/tests/test_validators.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, product/invisible, dependencies

#30722 Bump git-build-branch version
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
Labels: product/invisible

#30720 [Security] ensure getobject is at least v 1.0.0 due to security vulnerability
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#30717 [Hubspot] Update datadog metrics and move error logging to datadog instead of sentry
  corehq/apps/analytics/utils.py
Labels: product/invisible

#30688 auditcare export additions and improvements
  corehq/apps/auditcare/management/commands/export_domain_logins.py
  corehq/apps/auditcare/management/commands/generate_request_report.py
  corehq/apps/auditcare/tests/test_export.py
  corehq/apps/auditcare/utils/export.py
Labels: product/invisible

#30723 Add option to force pull remote multimedia
  corehq/apps/app_manager/templates/app_manager/partials/settings/multimedia_ajax.html
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/views.py
Labels: product/feature-flag

#30674 Do/exclude users forward forms
  corehq/motech/repeaters/forms.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/views/repeaters.py
Labels: awaiting QA, product/feature-flag

#30719 Hack pickle.HIGHEST_PROTOCOL for Celery on Python 3.6
  deployment/gunicorn/commcarehq_wsgi.py
  manage.py
Labels: product/invisible

#30725 Smart linking: don't allow Select Parent First
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
Labels: product/invisible

#30726 Celery pickle patch
  manage.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#30731 Execute tests against hotfix-deploy
  .github/workflows/tests.yml
Labels: product/invisible

#30732 Mjr/hotfix base
  .github/workflows/tests.yml
  corehq/apps/data_interfaces/admin.py
  corehq/apps/data_interfaces/deduplication.py
  corehq/apps/data_interfaces/migrations/0023_auto_20210914_1726.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/static/data_interfaces/js/case_dedupe_main.js
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/templates/data_interfaces/edit_deduplication_rule.html
  corehq/apps/data_interfaces/templates/data_interfaces/list_deduplication_rules.html
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/apps/data_interfaces/urls.py
  corehq/apps/data_interfaces/utils.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/domain/deletion.py
  corehq/apps/hqcase/utils.py
  corehq/apps/linked_domain/README.md
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/cases/duplicate_cases.py
  corehq/apps/reports/standard/cases/filters.py
  corehq/apps/users/tasks.py
  corehq/messaging/management/commands/manage_rule_run.py
  corehq/messaging/tasks.py
  corehq/messaging/util.py
  corehq/pillows/xform.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
  settings.py
Labels: reindex/migration, product/invisible

#30362 Smh/cross domain ucr UI updates
  corehq/apps/app_manager/fields.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/static/userreports/js/data_source_select_model.js
  corehq/apps/userreports/templates/userreports/reportbuilder/data_source_select.html
  corehq/apps/userreports/views.py
Labels: product/feature-flag

#30714 build correct data source type
  corehq/apps/api/resources/v0_5.py
  corehq/apps/domain/dbaccessors.py
  corehq/apps/userreports/dbaccessors.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/rebuild.py
  corehq/apps/userreports/reports/builder/columns.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/reports/filters/choice_providers.py
  corehq/apps/userreports/reports/filters/factory.py
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/tests/test_resume_rebuild.py
  corehq/apps/userreports/ui/fields.py
  corehq/apps/userreports/util.py
  corehq/couchapps/__init__.py
  corehq/motech/dhis2/forms.py
  corehq/motech/dhis2/models.py
  corehq/reports.py
Labels: product/invisible, Risk: High

#30729 more validation for registry case update repeater
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_payload_generator.py
Labels: product/feature-flag

#30651 Ad/auto update rules for linked spaces
  corehq/apps/data_interfaces/migrations/0024_add_automaticupdaterule_upstream_id.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/linked_domain/const.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/migrations/0020_auto_20211102_1501.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/tests/test_update_auto_update_rules.py
  corehq/apps/linked_domain/tests/test_view_helpers.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/urls.py
  corehq/apps/linked_domain/views.py
Labels: reindex/migration, product/feature-flag

#30734 Sk/cross domain ucr build
  corehq/couchapps/registry_report_configs/views/view/map.js
  corehq/couchapps/registry_report_configs/views/view/reduce.js
Labels: product/invisible

#30743 feature flag export fixes
  corehq/apps/toggle_ui/tasks.py
Labels: product/invisible

#30616 data registry form linking
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/test_suite_registry_search.py
Labels: QA Passed, product/feature-flag

#30736 update db checks to no longer query the table
  corehq/sql_db/__init__.py
Labels: product/invisible

#30745 Release management decorator does not check for admin of specific domain
  corehq/apps/linked_domain/util.py
Labels: product/invisible

#30741 Generic Case Repeater
  corehq/apps/userreports/ui/fields.py
  corehq/motech/repeaters/expression/__init__.py
  corehq/motech/repeaters/expression/forms.py
  corehq/motech/repeaters/expression/repeater_generators.py
  corehq/motech/repeaters/expression/repeaters.py
  corehq/motech/repeaters/expression/tests.py
  corehq/motech/repeaters/expression/views.py
  corehq/motech/repeaters/signals.py
  corehq/motech/repeaters/static/repeaters/js/add_form_repeater.js
  corehq/motech/urls.py
  corehq/toggles.py
  settings.py
Labels: product/feature-flag

#30738 [Hubspot] Ensure that users who have ever accepted an invitation from a blocked domain continue to stay blocked from hubspot
  corehq/apps/analytics/management/commands/manually_cleanup_blocked_hubspot_contacts.py
  corehq/apps/analytics/tasks.py
  corehq/apps/analytics/tests/test_hubspot.py
  corehq/apps/analytics/utils.py
Labels: product/invisible

#30733 added sorting by timestamp
  corehq/apps/reports/standard/users/reports.py
Labels: product/feature-flag

#30744 USH: Fix custom case rules
  corehq/apps/es/case_search.py
  custom/covid/rules/custom_actions.py
  custom/covid/rules/custom_criteria.py
  custom/covid/tests/test_custom_rules.py
Labels: product/custom

#30749 Mjr/xml upload
  corehq/apps/app_manager/tests/test_xform.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/xform.py
Labels: product/invisible

#30747 Rc/add repr fields
  corehq/apps/users/migrations/0040_add_repr_and_changed_by_repr.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_log_user_change.py
  corehq/apps/users/util.py
  corehq/util/django_migrations.py
Labels: reindex/migration, product/feature-flag

#30750 Make parse_xml raise DangerousXmlException
  corehq/apps/app_manager/exceptions.py
  corehq/apps/app_manager/xform.py
Labels: product/invisible

#30754 Fix parse_xml test
  corehq/apps/app_manager/tests/test_xform.py
Labels: product/invisible

#30735 Sk/dr copy from case
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_payload_generator.py
Labels: product/feature-flag

#30707 Option to enable computed functions in session endpoints
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/endpoints.py
  corehq/apps/app_manager/templates/app_manager/partials/forms/form_tab_settings.html
  corehq/apps/app_manager/templates/app_manager/partials/function_datum_endpoints.html
  corehq/apps/app_manager/tests/test_suite_session_endpoints.py
  corehq/apps/app_manager/views/forms.py
Labels: product/feature-flag, product/invisible

#30752 Removed build wrapping in web apps session endpoint view
  corehq/apps/cloudcare/views.py
Labels: product/feature-flag, Risk: Medium

#30756 Added sorting to Source Menu dropdown in menu settings
  corehq/apps/app_manager/static/app_manager/js/modules/shadow_module_settings.js
Labels: product/feature-flag

#30757 Add kenya-vca for VectorLink reports
  custom/abt/reports/data_sources/late_pmt.json
  custom/abt/reports/data_sources/sms_case.json
  custom/abt/reports/data_sources/supervisory_v2.json
  custom/abt/reports/data_sources/supervisory_v2019.json
  custom/abt/reports/data_sources/supervisory_v2020.json
  custom/abt/reports/sms_indicator_report.json
  custom/abt/reports/spray_progress_country.json
  custom/abt/reports/spray_progress_level_1.json
  custom/abt/reports/spray_progress_level_2.json
  custom/abt/reports/spray_progress_level_3.json
  custom/abt/reports/spray_progress_level_4.json
  custom/abt/reports/supervisory_report_v2.json
  custom/abt/reports/supervisory_report_v2019.json
  custom/abt/reports/supervisory_report_v2020.json
  settings.py
Labels: product/invisible

#30748 Case Rules: Limit damage of individual case failures
  corehq/apps/data_interfaces/migrations/0025_domaincaserulerun_num_errors.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/data_interfaces/utils.py
Labels: reindex/migration, product/invisible

#30075 Command to revoke privileges, opposite of grandfather command
  corehq/apps/accounting/tests/test_revoke_grants.py
  corehq/apps/accounting/utils/__init__.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_revoke_privs.py
Labels: product/invisible

#30739 Docker compose for devs with ARM64 chip
  DEV_SETUP.md
  docker/hq-compose-arch-arm64.yml
  docker/hq-compose-arch-x86.yml
  docker/hq-compose.yml
  scripts/docker
Labels: product/invisible

#30712 Re-apply "Stop using ES search_type=scan"
  corehq/apps/data_interfaces/tests/test_xform_management.py
  corehq/apps/es/es_query.py
  corehq/apps/es/exceptions.py
  corehq/apps/es/forms.py
  corehq/apps/es/registry.py
  corehq/apps/es/tests/test_registry.py
  corehq/apps/es/tests/test_test_utils.py
  corehq/apps/es/tests/utils.py
  corehq/apps/hqadmin/tests/test_stale_data_in_es.py
  corehq/apps/hqadmin/views/data.py
  corehq/apps/hqcase/management/commands/initialize_es_indices.py
  corehq/apps/hqcase/management/commands/reindex_es_native.py
  corehq/apps/hqcase/tests/test_dbaccessors.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/userreports/util.py
  corehq/elastic.py
  corehq/ex-submodules/couchforms/tests/test_analytics.py
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
  corehq/ex-submodules/pillowtop/tests/test_bulk.py
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
  corehq/ex-submodules/pillowtop/tests/utils.py
  corehq/pillows/app_config.py
  corehq/pillows/mappings/__init__.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/const.py
  corehq/pillows/mappings/xform_mapping.py
  corehq/pillows/user.py
  corehq/tests/test_elastic.py
  corehq/util/es/elasticsearch.py
  corehq/util/es/interface.py
  corehq/util/es/tests/__init__.py
  corehq/util/es/tests/test_interface.py
  settings.py
Labels: reindex/migration, QA Passed, product/invisible, Risk: High

#30657 Smart linking in web apps
  corehq/apps/app_manager/const.py
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/generator.py
  corehq/apps/app_manager/suite_xml/post_process/endpoints.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/data/suite_registry/detail_tabs.xml
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/tests/test_suite_session_endpoints.py
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/formdesigner.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/app_manager/xform.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/views.py
Labels: QA Passed, product/feature-flag, Risk: Medium

#30710 Tabular structure for more than one check box question
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#30762 Revert "Tabular structure for more than one check box question"
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#30760 Refs QA-3629 Refine behavior of matching excel fields to deprecated p…
  corehq/apps/app_manager/app_schemas/case_properties.py
  corehq/apps/case_importer/static/case_importer/js/excel_fields.js
  corehq/apps/case_importer/static/case_importer/js/main.js
  corehq/apps/case_importer/suggested_fields.py
  corehq/apps/case_importer/templates/case_importer/import_cases.html
  corehq/apps/case_importer/templates/case_importer/partials/excel_field_rows.html
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/util.py
Labels: product/invisible

#30764 Added parens to XPath.not_
  corehq/apps/app_manager/tests/data/suite/smart_link_remote_request.xml
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/tests/test_xpath.py
  corehq/apps/app_manager/xpath.py
Labels: product/feature-flag

#30765 Removed param from format_odata_error
  corehq/apps/api/odata/utils.py
Labels: product/invisible, Risk: High

#30768 Refs QA-3629 some final tweaks to case importer validation
  corehq/apps/case_importer/templates/case_importer/excel_fields.html
  corehq/apps/case_importer/templates/case_importer/partials/excel_field_rows.html
Labels: product/invisible

#30658 Added ability to enable usercase from error
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/form_filter.html
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/apps.py
Labels: QA Passed, product/all-users-all-environments

#30769 Migration to add domain field for mobile endpoint restriction setting (1 of 2 PRs)
  corehq/apps/domain/migrations/0009_restrict_mob_access_from_FF.py
  corehq/apps/domain/models.py
Labels: reindex/migration, product/invisible

#30771 Fix SuggestedFieldTest to not not need DB access.
  corehq/apps/case_importer/tests/test_suggested_fields.py
Labels: product/invisible

#30763 Update template response email to use pause instead of the community plan
  corehq/apps/accounting/templates/accounting/email/subscription_ending_reminder_dimagi.html
  corehq/apps/accounting/templates/accounting/email/subscription_ending_reminder_dimagi.txt
Labels: product/invisible

#30668 [Security] ensure that datatables.net as a subdependency also resolves to 1.11.3
  package.json
  yarn.lock
Labels: awaiting QA, product/invisible, dependencies, dependencies/javascript

#30766 Client Credentials OAuth grant type for Repeaters
  corehq/motech/auth.py
  corehq/motech/const.py
  corehq/motech/forms.py
  corehq/motech/migrations/0009_auto_20211122_2011.py
  corehq/motech/migrations/0010_auto_20211124_1931.py
  corehq/motech/models.py
  corehq/motech/static/motech/js/connection_settings_detail.js
  corehq/motech/tests/test_api_settings_migration.py
  corehq/motech/utils.py
Labels: reindex/migration, product/all-users-all-environments

#30751 Rc/user history populate reprs
  corehq/apps/reports/standard/users/reports.py
  corehq/apps/users/management/commands/migrate_reprs.py
  corehq/apps/users/migrations/0041_migrate_reprs.py
Labels: reindex/migration, product/feature-flag

#30781 Change content_type of app_strings.txt
  corehq/apps/app_manager/views/download.py
Labels: product/invisible

#30782 Encode select2 dropdown menu options
  corehq/apps/app_manager/static/app_manager/js/forms/case_knockout_bindings.js
Labels: product/invisible

#30773 support POST reqeusts for registry_case endpoint
  corehq/apps/ota/tests/test_registry_case_details.py
  corehq/apps/ota/views.py
Labels: product/invisible

#30730 add Data Registry UCR processor to `case-pillow`
  corehq/apps/userreports/pillow.py
  corehq/pillows/case.py
  corehq/pillows/user.py
  corehq/pillows/xform.py
Labels: product/invisible

#30774 restict case search and DR endpoints using feature flags
  corehq/apps/ota/tests/test_registry_case_details.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/apps/ota/views.py
Labels: product/feature-flag

#30775 restrict login-as users access during restore
  corehq/apps/ota/tests/test_utils.py
  corehq/apps/ota/utils.py
Labels: product/feature-flag

#30779 Revert "Revert "Tabular structure for more than one check box question""
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#30786 Only narrow the width of "Create new property" column...
  corehq/apps/case_importer/templates/case_importer/excel_fields.html
  corehq/apps/case_importer/templates/case_importer/partials/excel_field_rows.html
  corehq/apps/data_dictionary/tests/utils.py
Labels: product/invisible
