Repository dimagi/commcare-hq, pull requests merged in 2021-01, with the labels that each got.

#28943 Mjr/multiple aggregations test date fix
  corehq/apps/userreports/reports/specs.py
  corehq/apps/userreports/tests/test_report_aggregation.py
Labels: product/invisible

#28947 Fixed typo [ci skip]
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
Labels: product/all-users-all-environments

#28951 Fixed error resulting from blank case claim condition
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
Labels: product/feature-flag

#28937 Track fresh restore case loads
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
Labels: product/invisible

#28936 Re-bucket restore case load metric
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
Labels: product/invisible

#28956 trying to install libxmlsec1-dev with a different package name
  Dockerfile
Labels: product/invisible

#28959 Revert "improve case lists pagination"
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/case_list_pagination_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/templates/cloudcare/spec/form_entry/mocha.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/users.html
Labels: Risk: Medium

#28902 Make links in Web Apps more accessible
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/grid_view.html
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
  corehq/apps/cloudcare/templates/formplayer/session_list.html
Labels: QA Passed, Risk: Medium, product/all-users-all-environments

#28837 Disable Submit button and autosubmit the form when the backend says so
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js
Labels: Risk: Medium, product/all-users-all-environments

#28775 Add SMS Backend support for both an API and a specific gateway fee
  corehq/apps/smsbillables/README.rst
  corehq/apps/smsbillables/models.py
  corehq/apps/smsbillables/tests/test_billable_creation.py
  corehq/apps/smsbillables/tests/test_gateway_charges.py
  corehq/apps/smsbillables/tests/test_gateway_fees.py
  corehq/apps/smsbillables/tests/utils.py
Labels: QA Passed, product/invisible

#28954 Fix bug in corrupt_couch date parsing
  corehq/apps/hqadmin/corrupt_couch.py
Labels: product/invisible

#28948 A few small refactors around repeaters
  corehq/apps/api/resources/v0_4.py
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/signals.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_dbaccessors.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/utils.py
  corehq/motech/repeaters/views/repeaters.py
Labels: Risk: High, product/invisible

#28952 SQLRepeatRecord
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/motech/repeaters/const.py
  corehq/motech/repeaters/migrations/0002_sqlrepeatrecord.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_models.py
Labels: product/invisible, reindex/migration

#28958 Create ConnectionSettings for all Repeaters
  corehq/motech/repeaters/migrations/0003_migrate_connectionsettings.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_models.py
Labels: product/invisible, reindex/migration

#28966 Revert "Create ConnectionSettings for all Repeaters"
  corehq/motech/repeaters/migrations/0003_migrate_connectionsettings.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_models.py
Labels: reindex/migration

#28967 Sanitize user input urls
  corehq/motech/forms.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/requests.py
  corehq/motech/tests/test_models.py
  corehq/motech/tests/test_requests.py
  corehq/motech/views.py
  corehq/util/urlsanitize/__init__.py
  corehq/util/urlsanitize/test/__init__.py
  corehq/util/urlsanitize/test/test_urlsanitize.py
  corehq/util/urlsanitize/urlsanitize.py
Labels: product/invisible

#28968 Handle missing form with no XML blob
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
Labels: product/invisible

#28973 [ci skip] fix the inline display of the conditional expression spec
  corehq/apps/userreports/expressions/specs.py
Labels: product/invisible

#28965 Added case_type as a required argument to update_case_index_relationship
  custom/covid/management/commands/update_case_index_relationship.py
Labels: product/invisible

#28971 Added post datum instance in remote request suite generation
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
Labels: QA Passed, product/feature-flag

#28975 Only run on environments with an "onse-iss" domain
  custom/onse/tasks.py
Labels: product/invisible

#28977 Bring back case search admin view and add profiling data
  corehq/apps/case_search/static/case_search/js/case_search.js
  corehq/apps/case_search/templates/case_search/case_search.html
  corehq/apps/case_search/urls.py
  corehq/apps/case_search/views.py
  corehq/apps/domain/templates/domain/admin/case_search.html
  corehq/apps/domain/views/settings.py
  corehq/apps/es/es_query.py
  corehq/tabs/tabclasses.py
  urls.py
Labels: product/admin

#28979 🔪 Drop unused `test_repeater()` view
  corehq/motech/repeaters/templates/repeaters/add_form_repeater.html
  corehq/motech/repeaters/views/__init__.py
  corehq/motech/repeaters/views/repeaters.py
  corehq/motech/urls.py
Labels: product/invisible

#28974 Reapply ConnectionSettings migration
  corehq/motech/repeaters/migrations/0003_migrate_connectionsettings.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_models.py
Labels: product/invisible, reindex/migration

#28969 Support couch_sql_diff ... patch --select=with-[diffs|changes]
  corehq/apps/couch_sql_migration/casedifftool.py
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/tests/test_casedifftool.py
Labels: product/invisible

#28970 Fixed case claim UI checkbox again
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
Labels: QA Passed, product/feature-flag

#28983 Revert "Make links in Web Apps more accessible"
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/grid_view.html
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
  corehq/apps/cloudcare/templates/formplayer/session_list.html
Labels: Risk: Medium, product/all-users-all-environments

#28984 Fixed bug in case detail nodeset sorting
  corehq/apps/app_manager/detail_screen.py
Labels: product/feature-flag

#28988 Remove a thing
  corehq/apps/userreports/templates/userreports/edit_report_config.html
Labels: product/feature-flag

#28987 use default travis python version
  .travis.yml
Labels: product/invisible

#28651 Add Email-Domain Namespace to Toggles
  corehq/apps/toggle_ui/views.py
  corehq/ex-submodules/toggle/shortcuts.py
  corehq/ex-submodules/toggle/tests.py
  corehq/toggles.py
Labels: product/admin, product/feature-flag

#28990 Couch to SQL forms & cases: ignore bad ledgers
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/couch_sql_diff.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
  corehq/apps/couch_sql_migration/patches.py
  corehq/apps/couch_sql_migration/statedb.py
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/couch_sql_migration/tests/test_statedb.py
Labels: product/invisible

#28991 Add toggles to block domains and email domains from outgoing emails
  corehq/apps/hqwebapp/tasks.py
  corehq/ex-submodules/dimagi/utils/django/email.py
  corehq/messaging/scheduling/models/content.py
  corehq/toggles.py
  corehq/util/models.py
  corehq/util/tests/test_bounced_emails.py
Labels: product/invisible

#28992 Save mobile worker user_ids to all checkin cases
  custom/covid/management/commands/add_hq_user_id_to_case.py
  custom/covid/tests/test_management_commands.py
Labels: product/invisible

#28981 [JS Vulnerability Fix] Update Datatables to 1.10.23 and remove (unused) angular-datatables
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer-common/base.html
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_config.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  custom/aaa/templates/aaa/dashboard.html
  package.json
  yarn.lock
Labels: QA Passed, Risk: Medium, dependencies, dependencies/javascript, product/all-users-all-environments

#28854 moving run_migrations task to a dedicated_process_num
  corehq/apps/change_feed/consumer/feed.py
  corehq/apps/userreports/pillow.py
  corehq/ex-submodules/pillowtop/management/commands/run_ptop.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  corehq/ex-submodules/pillowtop/processors/interface.py
  corehq/pillows/case.py
  corehq/pillows/user.py
  corehq/pillows/xform.py
Labels: product/invisible

#28994 FHIR endpoint tests
  corehq/motech/fhir/__init__.py
  corehq/motech/fhir/tests/__init__.py
  corehq/motech/fhir/tests/test_api_endpoints.py
  settings.py
Labels: product/invisible

#28989 management command to prime formplayer user DBs
  corehq/apps/domain/auth.py
  corehq/apps/formplayer_api/exceptions.py
  corehq/apps/formplayer_api/management/__init__.py
  corehq/apps/formplayer_api/management/commands/__init__.py
  corehq/apps/formplayer_api/management/commands/prime_formplayer_restores.py
  corehq/apps/formplayer_api/sync_db.py
  settings.py
Labels: product/invisible

#28840 fix command
  corehq/apps/dump_reload/management/commands/print_domain_stats.py
Labels: product/invisible

#29001 enable sessions for the application API
  corehq/apps/api/resources/v0_4.py
Labels: product/all-users-all-environments

#29002 Allow session auth for user-domains API, and clean up decorators
  corehq/apps/api/resources/auth.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/domain/decorators.py
Labels: Risk: High, product/all-users-all-environments

#29005 add logging to assist debug of auth workflows
  corehq/apps/domain/auth.py
  corehq/apps/domain/decorators.py
  corehq/apps/ota/decorators.py
  corehq/util/hmac_request.py
  settings.py
Labels: product/invisible

#28995 [javascript security vulnerability] ensure that at least yargs-parser ^18.1.3 is installed
  package.json
  yarn.lock
Labels: dependencies, dependencies/javascript, product/invisible

#28996 Create CaseUpdateCommand
  custom/covid/management/commands/add_hq_user_id_to_case.py
  custom/covid/management/commands/update_case_index_relationship.py
  custom/covid/management/commands/update_cases.py
  custom/covid/tests/test_management_commands.py
Labels: product/invisible

#28957 avoid failing if no display
  corehq/apps/userreports/models.py
Labels: product/invisible

#29003 Couch to SQL forms & cases: minor fixup
  corehq/apps/couch_sql_migration/couchsqlmigration.py
  corehq/apps/couch_sql_migration/management/commands/migrate_domain_from_couch_to_sql.py
Labels: product/invisible

#29008 fix digest auth on APIs using LoginAndDomainAuthentication
  corehq/apps/api/resources/auth.py
Labels: Risk: High, product/all-users-all-environments

#29007 Add tests for untested feature
  corehq/apps/es/tests/test_case_search_es.py
Labels: product/invisible

#29006 track formplayer restores
  corehq/apps/ota/tests/test_formplayer_restore.py
  corehq/apps/ota/tests/test_utils.py
  corehq/apps/ota/utils.py
  corehq/apps/users/models.py
  corehq/ex-submodules/casexml/apps/phone/migrations/0005_auto_20210119_1001.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/casexml/apps/phone/restore.py
Labels: product/invisible, reindex/migration

#29004 Case claim option to configure session variable
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#29011 Update owner_id case command
  custom/covid/management/commands/update_owner_ids.py
  custom/covid/tests/test_management_commands.py
Labels: product/invisible

#29012 put sum when behind ff like sum when template
  corehq/apps/userreports/README.rst
  corehq/apps/userreports/reports/specs.py
  corehq/toggles.py
Labels: product/feature-flag

#28949 Support creating extension cases in case-importer
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/suggested_fields.py
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/case_importer/util.py
Labels: QA Passed, product/all-users-all-environments

#29016 don't 500 if no messages
  corehq/messaging/smsbackends/turn/views.py
Labels: product/invisible

#29009 Drop unused functions from Case Search
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/tests/test_filter_dsl.py
Labels: product/invisible

#28993 Mjr/missing attachments
  corehq/apps/receiverwrapper/views.py
  corehq/ex-submodules/couchforms/models.py
  corehq/form_processor/interfaces/processor.py
  corehq/form_processor/models.py
  corehq/form_processor/parsers/form.py
  corehq/form_processor/submission_post.py
  corehq/form_processor/tests/test_models.py
Labels: Risk: High, product/invisible

#29013 Fix Supervisor Report v.2021
  custom/abt/reports/expressions.py
  custom/abt/reports/flagspecs_v2020.yaml
Labels: product/invisible

#29017 Set default filter for "Remote API Logs" page
  corehq/motech/templates/motech/logs.html
  corehq/motech/views.py
Labels: product/invisible

#29024 prune synclogs for formplayer users
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_purge.py
Labels: product/invisible

#29028 🐞 Fix pagination of ConnectionSettings
  corehq/motech/views.py
Labels: product/invisible

#28930 HQ support for query screen prompt defaults
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/templates/formplayer/query_view.html
Labels: QA Passed, Risk: Medium, product/feature-flag

#29027 Add Enterprise SSO feature flag
  corehq/toggles.py
Labels: product/feature-flag

#28955 Web apps case claim itemsets
  corehq/apps/app_manager/exceptions.py
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/views/formdesigner.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
  corehq/apps/cloudcare/templates/formplayer/query_view.html
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/fixtures/interface.py
Labels: QA Passed, Risk: Medium, product/feature-flag

#28950 Parent/child support for case claim
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/util.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
Labels: QA Passed, Risk: Medium, product/feature-flag

#28982 Use couch file formats in DefaultExportSettings
  corehq/apps/export/migrations/0011_defaultexportsettings_usecouchfiletypes.py
  corehq/apps/export/models/export_settings.py
Labels: reindex/migration

#29037 Switched a few text inputs for textareas
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
Labels: product/feature-flag

#29026 Update instructions for adding a build
  corehq/apps/builds/README.rst
Labels: product/invisible

#29019 query synclogs to get list of users for formplayer sync prime
  corehq/apps/formplayer_api/management/commands/prime_formplayer_restores.py
  corehq/util/argparse_types.py
Labels: product/invisible

#29041 Fix YAML indentation
  custom/abt/reports/flagspecs_v2020.yaml
  custom/abt/reports/tests/test_flagspecs.py
Labels: product/invisible

#29040 Vectorlink reports
  custom/abt/reports/late_pmt.py
  custom/abt/reports/late_pmt_2020.py
  custom/abt/reports/supervisory_report_v2020.json
Labels: product/custom

#29038 Standardized and condensed lookup table popup
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
Labels: product/feature-flag

#28938 Add SSO Models and initial SAML2 views
  DEV_SETUP.md
  corehq/apps/README.rst
  corehq/apps/accounting/tests/generator.py
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/sso/__init__.py
  corehq/apps/sso/certificates.py
  corehq/apps/sso/configuration.py
  corehq/apps/sso/decorators.py
  corehq/apps/sso/exceptions.py
  corehq/apps/sso/management/__init__.py
  corehq/apps/sso/management/commands/__init__.py
  corehq/apps/sso/migrations/0001_initial.py
  corehq/apps/sso/migrations/__init__.py
  corehq/apps/sso/models.py
  corehq/apps/sso/tasks.py
  corehq/apps/sso/tests/__init__.py
  corehq/apps/sso/tests/generator.py
  corehq/apps/sso/tests/test_decorators.py
  corehq/apps/sso/tests/test_tasks.py
  corehq/apps/sso/urls.py
  corehq/apps/sso/utils.py
  corehq/apps/sso/views.py
  requirements/apt-packages.txt
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
  urls.py
Labels: dependencies, product/invisible, reindex/migration

#28961 Use default export settings when creating new exports if they exist
  corehq/apps/export/models/new.py
  corehq/apps/export/tests/test_export_instance.py
  corehq/apps/export/tests/test_export_utils.py
  corehq/apps/export/utils.py
  corehq/apps/export/views/new.py
Labels: product/feature-flag

#29043 Purge alternate device_id (due to recent formplayer change)
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_purge.py
Labels: product/invisible

#28935 Allow selection of non-parent in 'Select Parent First' workflow
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/utils.py
  corehq/apps/app_manager/templates/app_manager/module_view.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
  corehq/apps/app_manager/tests/data/suite/advanced_module_parent_null_relationship.xml
  corehq/apps/app_manager/tests/data/suite/parent_null_relationship_same_type.xml
  corehq/apps/app_manager/tests/test_advanced_suite.py
  corehq/apps/app_manager/views/modules.py
  corehq/toggles.py
Labels: product/custom

#28931 Create support for referencing the owner_id property
  corehq/apps/app_manager/app_schemas/case_properties.py
  corehq/apps/app_manager/app_schemas/casedb_schema.py
  corehq/apps/app_manager/app_schemas/tests/test_case_properties.py
  corehq/apps/app_manager/app_schemas/tests/test_schema.py
  corehq/apps/userreports/tests/test_report_builder.py
Labels: product/all-users-all-environments

#28939 create metrics for failed logins
  corehq/apps/domain/decorators.py
  corehq/apps/hqwebapp/forms.py
  corehq/apps/hqwebapp/signals.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_confirm_account.py
  corehq/apps/users/tests/test_user_model.py
Labels: awaiting QA, product/invisible

#29055 add some more notes about xmlsec to DEV_SETUP
  DEV_SETUP.md
Labels: product/invisible

#28978 process_repeater_stub() task
  corehq/motech/repeaters/const.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_models_slow.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/tests/test_tasks.py
Labels: product/invisible

#29046 tar is more strict about paths on Linux than MacOS
  scripts/vellum-to-hq
Labels: product/invisible

#29059 Updated web apps search algorithms to not mutate combobox options
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
Labels: Risk: Medium, product/all-users-all-environments

#29051 Redo "Purge alternate device_id (due to recent formplayer change)" with random toggle
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_purge.py
  corehq/toggles.py
Labels: product/invisible

#29053 output all rows to stdout unless in 'quiet' mode
  corehq/apps/formplayer_api/management/commands/prime_formplayer_restores.py
Labels: product/invisible

#29054 fix rendering of days in woker activity times
  corehq/apps/reports/standard/monitoring.py
Labels: product/all-users-all-environments

#29042 Add link to refresh data dictionary
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/urls.py
  corehq/apps/data_dictionary/views.py
Labels: product/feature-flag

#29061 remove unused DomainRateLimiter
  corehq/ex-submodules/dimagi/utils/rate_limit.py
  corehq/ex-submodules/dimagi/utils/tests/test_rate_limit.py
Labels: product/invisible

#29060 Upgrade pip-tools
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies, product/invisible

#29049 rate limit ajax requests from multi-option filters
  corehq/apps/reports/static/reports/js/filters/select2s.js
Labels: product/invisible

#29066 Update grunt installation instructions
  DEV_SETUP.md
Labels: product/invisible

#29067 Dont send emails to Dev with every search query
  corehq/apps/reports/standard/cases/case_list_explorer.py
Labels: product/invisible
