Repository dimagi/commcare-hq, pull requests merged in 2021-03, with the labels that each got.

#29221 Use updated question ids
  custom/nutrition_project/ucr/data_sources/supplementary_nutrition_hcm_v1.json
Labels: product/custom, product/feature-flag

#29239 auditcare cleanup
  corehq/ex-submodules/auditcare/decorators/__init__.py
  corehq/ex-submodules/auditcare/decorators/login.py
  corehq/ex-submodules/auditcare/decorators/manual.py
  corehq/ex-submodules/auditcare/forms.py
  corehq/ex-submodules/auditcare/inspect.py
  corehq/ex-submodules/auditcare/management/commands/compute_diffs.py
  corehq/ex-submodules/auditcare/management/commands/export_audit_data.py
  corehq/ex-submodules/auditcare/management/commands/gdpr_scrub_user_auditcare.py
  corehq/ex-submodules/auditcare/management/commands/generate_request_report.py
  corehq/ex-submodules/auditcare/management/commands/resolve_urls.py
  corehq/ex-submodules/auditcare/middleware.py
  corehq/ex-submodules/auditcare/models.py
  corehq/ex-submodules/auditcare/signals.py
  corehq/ex-submodules/auditcare/tests/auth.py
  corehq/ex-submodules/auditcare/tests/modelevents.py
  corehq/ex-submodules/auditcare/tests/navigationevents.py
  corehq/ex-submodules/auditcare/tests/test_gdpr_scrub_user_auditcare.py
  corehq/ex-submodules/auditcare/urls.py
  corehq/ex-submodules/auditcare/utils/__init__.py
  corehq/ex-submodules/auditcare/utils/export.py
  corehq/ex-submodules/auditcare/views.py
  corehq/ex-submodules/dimagi/utils/threadlocals.py
Labels: product/invisible

#29247 Added error message for failed form validation while making build
  corehq/apps/app_manager/views/releases.py
Labels: product/all-users-all-environments

#29257 Added UCRs to reports handled by linked project space user roles
  corehq/apps/linked_domain/updates.py
Labels: product/feature-flag

#29255 Fixed 500 on linked projects page when lookup table has been deleted
  corehq/apps/linked_domain/views.py
Labels: product/feature-flag

#29246 Removed HIDE_MESSAGING_DASHBOARD_FROM_NON_SUPERUSERS flag
  corehq/apps/sms/views.py
  corehq/messaging/util.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
Labels: product/feature-flag

#29254 Updated update_case_index_relationship to allow for 'patient' indices
  custom/covid/management/commands/update_case_index_relationship.py
  custom/covid/tests/test_management_commands.py
Labels: product/invisible

#29253 Added caching for Marionette templates
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  package.json
  yarn.lock
Labels: Risk: Medium, dependencies, product/invisible

#29219 Added some sorting
  corehq/apps/linked_domain/views.py
  custom/covid/management/commands/update_cases.py
Labels: product/feature-flag

#29022 Web Apps: Use SelectWoo, a more accessible fork of Select2, for comboboxes
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/cloudcare/spec/form_entry/mocha.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  package.json
  yarn.lock
Labels: QA Passed, Risk: Medium, dependencies, product/all-users-all-environments

#29021 Add response headers to RequestLog
  corehq/motech/migrations/0008_requestlog_response_headers.py
  corehq/motech/models.py
  corehq/motech/requests.py
  corehq/motech/templates/motech/log_detail.html
  corehq/motech/tests/test_models.py
  corehq/motech/tests/test_simple_post.py
Labels: product/invisible, reindex/migration

#29231 Remove include_duplicates fields from export settings
  corehq/apps/enterprise/forms.py
  corehq/apps/export/migrations/0012_defaultexportsettings_remove_duplicates_option.py
  corehq/apps/export/models/export_settings.py
  corehq/apps/export/models/new.py
  corehq/apps/export/tests/test_export_instance.py
  corehq/apps/export/views/new.py
Labels: product/feature-flag, product/invisible, reindex/migration

#29268 Remove unused AuditCommand
  corehq/ex-submodules/auditcare/models.py
Labels: product/invisible

#29263 Fix filters in Case List Report
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/utils.py
  corehq/apps/reports/tests/data/case_list_report_data.py
  corehq/apps/reports/tests/test_case_list_report.py
  corehq/apps/reports/v2/filters/case_report.py
Labels: QA Passed, product/invisible

#27598 Couch to SQL migration: CommtrackConfig (2 of 3)
  corehq/apps/commtrack/consumption.py
  corehq/apps/commtrack/management/commands/populate_commtrackconfig.py
  corehq/apps/commtrack/migrations/0005_populate_config_models.py
  corehq/apps/commtrack/models.py
  corehq/apps/commtrack/sms.py
  corehq/apps/commtrack/tests/test_settings.py
  corehq/apps/commtrack/tests/test_stock_state.py
  corehq/apps/commtrack/tests/test_utils.py
  corehq/apps/commtrack/tests/test_xml.py
  corehq/apps/commtrack/util.py
  corehq/apps/commtrack/views.py
  corehq/apps/domain/dbaccessors.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/models.py
  corehq/apps/domain/tests/test_dbaccessors.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/locations/models.py
  corehq/apps/reports/commtrack/standard.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/views.py
  corehq/ex-submodules/casexml/apps/stock/tests/test_logistics_consumption.py
  corehq/form_processor/parsers/ledgers/helpers.py
  corehq/pillows/ledger.py
Labels: QA Passed, Risk: High, product/invisible, reindex/migration

#29271 Updated enterprise permissions page to disallow a mirror whose source…
  corehq/apps/users/forms.py
  corehq/apps/users/views/__init__.py
Labels: product/invisible

#29267 change_plan does not support start_date
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_admin_software_plans.py
  corehq/apps/accounting/utils/software_plans.py
Labels: product/admin

#29270 Removed soft assert
  corehq/apps/app_manager/views/view_generic.py
Labels: product/invisible

#29273 Pollish Export Settings UI
  corehq/apps/enterprise/forms.py
Labels: product/feature-flag, product/invisible

#29266 Mjr/xss misc
  corehq/apps/sms/forms.py
  corehq/motech/repeaters/views/repeat_records.py
  custom/apps/crs_reports/reports.py
  custom/succeed/reports/all_patients.py
  custom/succeed/reports/patient_submissions.py
  custom/succeed/reports/patient_task_list.py
  docs/class_views.rst
  docs/ui_helpers.rst
Labels: product/invisible

#29245 Mjr/xss locations
  corehq/apps/locations/permissions.py
  corehq/apps/locations/views.py
Labels: product/invisible

#29265 removed mark_safe usages in settings
  corehq/apps/settings/forms.py
Labels: product/invisible

#29244 Add additional find_question_id check for last path component
  corehq/apps/reports/tasks.py
  corehq/apps/reports/tests/test_tasks.py
Labels: product/invisible

#29278 mark domain decorators.py as high risk
  .github/labels.yml
Labels: product/invisible

#29277 Revert "Web Apps: Use SelectWoo, a more accessible fork of Select2, for comboboxes"
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/cloudcare/spec/form_entry/mocha.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  package.json
  yarn.lock
Labels: Risk: Medium, dependencies, product/invisible

#29274 Remove ModelActionAudit and associated features
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/ex-submodules/auditcare/inspect.py
  corehq/ex-submodules/auditcare/management/commands/compute_diffs.py
  corehq/ex-submodules/auditcare/models.py
  corehq/ex-submodules/auditcare/signals.py
  corehq/ex-submodules/auditcare/templates/auditcare/model_changes.html
  corehq/ex-submodules/auditcare/templates/auditcare/model_instance_history.html
  corehq/ex-submodules/auditcare/templates/auditcare/single_model_changes.html
  corehq/ex-submodules/auditcare/tests/auth.py
  corehq/ex-submodules/auditcare/tests/modelevents.py
  corehq/ex-submodules/auditcare/urls.py
  corehq/ex-submodules/auditcare/utils/__init__.py
  corehq/ex-submodules/auditcare/utils/export.py
  corehq/ex-submodules/auditcare/views.py
  docker/localsettings.py
  settings.py
  testsettings.py
Labels: product/invisible

#29258 ValueSource supports case relationships
  corehq/form_processor/tests/utils.py
  corehq/motech/tests/test_value_source.py
  corehq/motech/value_source.py
Labels: Risk: High, product/invisible

#29240 Added condition if a domain does not have a traveler active location
  custom/covid/management/commands/run_all_management_command.py
Labels: product/invisible

#29256 Data dictionary upload error handling improvements
  corehq/apps/data_dictionary/views.py
Labels: product/feature-flag

#29283 Updated USH script to fix all "'patient'" cases
  custom/covid/management/commands/update_case_index_relationship.py
Labels: product/invisible

#29281 DHIS2: Support "coordinate" and "geometry" in enrollments
  corehq/motech/dhis2/schema.py
Labels: product/invisible

#29289 add wiki link
  corehq/toggles.py
Labels: product/invisible

#29262 Raw-delete RequestLog
  corehq/motech/models.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_tasks.py
Labels: product/invisible

#29282 Move auditcare from ex-submodules to corehq.apps
  .isort.cfg
  corehq/apps/README.rst
  corehq/apps/auditcare/__init__.py
  corehq/apps/auditcare/_design/filters/auditdocs.js
  corehq/apps/auditcare/_design/util/shared_funcs.js
  corehq/apps/auditcare/_design/views/all_events/map.js
  corehq/apps/auditcare/_design/views/by_date/map.js
  corehq/apps/auditcare/_design/views/by_date_access_events/map.js
  corehq/apps/auditcare/_design/views/by_date_events/map.js
  corehq/apps/auditcare/_design/views/login_events/map.js
  corehq/apps/auditcare/_design/views/model_actions_by_id/map.js
  corehq/apps/auditcare/_design/views/model_actions_by_id/reduce.js
  corehq/apps/auditcare/_design/views/urlpath_by_user_date/map.js
  corehq/apps/auditcare/_design/views/urlpath_by_user_date/reduce.js
  corehq/apps/auditcare/decorators/__init__.py
  corehq/apps/auditcare/decorators/login.py
  corehq/apps/auditcare/management/__init__.py
  corehq/apps/auditcare/management/commands/__init__.py
  corehq/apps/auditcare/management/commands/export_audit_data.py
  corehq/apps/auditcare/management/commands/gdpr_scrub_user_auditcare.py
  corehq/apps/auditcare/management/commands/generate_request_report.py
  corehq/apps/auditcare/management/commands/resolve_urls.py
  corehq/apps/auditcare/middleware.py
  corehq/apps/auditcare/models.py
  corehq/apps/auditcare/signals.py
  corehq/apps/auditcare/templates/auditcare/audit_views.html
  corehq/apps/auditcare/templates/auditcare/auditcare_config_broken.html
  corehq/apps/auditcare/templates/auditcare/index.html
  corehq/apps/auditcare/templates/auditcare/partials/base_event.html
  corehq/apps/auditcare/templates/auditcare/partials/couch_model_event.html
  corehq/apps/auditcare/templates/auditcare/partials/django_model_event.html
  corehq/apps/auditcare/templates/auditcare/partials/model_property_change.html
  corehq/apps/auditcare/templates/auditcare/partials/navigation_event.html
  corehq/apps/auditcare/tests/__init__.py
  corehq/apps/auditcare/tests/auth.py
  corehq/apps/auditcare/tests/test_gdpr_scrub_user_auditcare.py
  corehq/apps/auditcare/tests/testutils.py
  corehq/apps/auditcare/urls.py
  corehq/apps/auditcare/utils/__init__.py
  corehq/apps/auditcare/utils/export.py
  corehq/apps/auditcare/utils/resolver.py
  corehq/apps/auditcare/utils/show_urls.py
  corehq/apps/auditcare/views.py
  corehq/apps/hqadmin/corrupt_couch.py
  corehq/apps/hqadmin/reports.py
  corehq/apps/hqadmin/views/system.py
  corehq/ex-submodules/README.rst
  corehq/ex-submodules/auditcare/decorators/manual.py
  corehq/ex-submodules/dimagi/utils/couch/bulk.py
  corehq/tests/nose.py
  dev_settings.py
  settings.py
  testsettings.py
  urls.py
Labels: product/invisible

#29276 [SSO] Block users from viewing Domain if logged in with SSO and Domain does not Trust IdP
  corehq/apps/domain/decorators.py
  corehq/apps/sso/async_handlers.py
  corehq/apps/sso/backends.py
  corehq/apps/sso/exceptions.py
  corehq/apps/sso/models.py
  corehq/apps/sso/tests/generator.py
  corehq/apps/sso/tests/test_request_helpers.py
  corehq/apps/sso/utils/request_helpers.py
  corehq/apps/sso/utils/user_helpers.py
Labels: Risk: High, product/feature-flag, product/invisible

#29290 Updated linked domains to fail when downstream app reference is ambig…
  corehq/apps/linked_domain/applications.py
  corehq/apps/linked_domain/exceptions.py
  corehq/apps/linked_domain/keywords.py
  corehq/apps/linked_domain/ucr.py
Labels: product/feature-flag

#29285 Make case claim properties sortable
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
Labels: product/feature-flag

#29280 formpalyer docker revamp
  corehq/apps/cloudcare/views.py
  corehq/apps/formplayer_api/utils.py
  docker/hq-compose-runserver.yml
  docker/hq-compose-services.yml
  docker/hq-compose.yml
  docker/localsettings.py
  docker/run.sh
Labels: Risk: Medium, product/invisible

#29269 add fixture information to questions in Application API
  corehq/apps/api/resources/v0_4.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/data/form_with_fixtures.xml
  corehq/apps/app_manager/tests/test_get_questions.py
  corehq/apps/app_manager/tests/test_xform_parsing.py
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/xform.py
Labels: Risk: High, product/all-users-all-environments

#29294 Add max elgible counts in a month
  custom/nutrition_project/ucr/data_sources/supplementary_nutrition_hcm_v1.json
  custom/nutrition_project/ucr/data_sources/supplementary_nutrition_thr_v1.json
  custom/nutrition_project/ucr/reports/hcm_report_v1.json
  custom/nutrition_project/ucr/reports/thr_report_v1.json
Labels: product/custom, product/feature-flag

#29298 Format request body
  corehq/motech/models.py
  corehq/motech/tests/test_models.py
  corehq/util/__init__.py
Labels: product/all-users-all-environments

#29295 Add report for delivery deaths
  corehq/apps/userreports/reports/factory.py
  custom/nutrition_project/ucr/data_sources/deliveries_v1.json
  custom/nutrition_project/ucr/reports/delivery_deaths_v1.json
  custom/nutrition_project/ucr/reports/member_registrations_v1.json
  custom/nutrition_project/ucr/sum_when_templates.py
Labels: product/custom, product/feature-flag

#29301 temporarily remove datetimepicker from requirejs files while we figure out weird rjs bug
  corehq/apps/sso/static/sso/js/enterprise_edit_identity_provider.js
  corehq/apps/sso/views/enterprise_admin.py
Labels: product/feature-flag

#29303 add missed column in data source
  custom/nutrition_project/ucr/data_sources/deliveries_v1.json
Labels: product/custom, product/feature-flag

#29302 raise CaseNotFound if domain is mismatched
  corehq/apps/api/resources/v0_3.py
Labels: Risk: High, product/invisible

#29305 Remove unnecessary block that adds filters and date_range again
  corehq/apps/saved_reports/models.py
Labels: product/invisible

#29297 [SSO] Add user-friendly view when a user tries to access domain that doesn't trust IdP
  corehq/apps/domain/decorators.py
  corehq/apps/sso/templates/sso/permissions/untrusted_identity_provider_for_domain.html
  corehq/apps/sso/utils/view_helpers.py
Labels: Risk: High, product/feature-flag

#29307 Add basic sms data generator
  corehq/apps/sms/management/commands/generate_fake_sms_data.py
  corehq/apps/sms/tests/data_generator.py
  testapps/test_pillowtop/tests/test_sms_pillow.py
Labels: product/invisible

#29306 Check for locations also while creating case list es query
  corehq/apps/reports/standard/cases/basic.py
Labels: QA Passed, product/invisible

#29310 new datetimepicker (cleanup old datetimepicker EXCEPT in webapps)
  corehq/apps/hqwebapp/decorators.py
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/datetimepicker.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style-imports.less
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/sso/forms.py
  corehq/apps/sso/static/sso/js/enterprise_edit_identity_provider.js
  corehq/apps/sso/views/enterprise_admin.py
  package.json
  yarn.lock
Labels: Risk: High, Risk: Medium, dependencies, product/feature-flag

#29264 Renamed Application.master_id => origin_id
  corehq/apps/app_manager/management/commands/add_resource_overrides.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/resources.py
  corehq/apps/app_manager/tests/test_suite_resource_overrides.py
  corehq/apps/app_manager/tests/test_util.py
  corehq/apps/app_manager/views/app_summary.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/cloudcare/views.py
  corehq/apps/export/models/new.py
  corehq/apps/hqadmin/templates/hqadmin/app_build_timings.html
  corehq/apps/ota/views.py
  corehq/apps/reminders/util.py
  docs/apps/terminology.rst
Labels: Risk: Medium, product/invisible

#29249 FHIRRepeater part 1
  corehq/motech/dhis2/views.py
  corehq/motech/openmrs/forms.py
  corehq/motech/openmrs/urls.py
  corehq/motech/openmrs/views.py
  corehq/motech/repeaters/forms.py
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_payload_generators.py
  corehq/motech/repeaters/views/__init__.py
  corehq/motech/repeaters/views/repeaters.py
  corehq/motech/urls.py
Labels: product/invisible

#29260 Alter FHIRResourceType
  corehq/motech/fhir/migrations/0002_fhirresourcetype.py
  corehq/motech/fhir/models.py
Labels: product/invisible, reindex/migration

#29314 Add new sum when templates
  corehq/apps/userreports/reports/factory.py
  custom/nutrition_project/ucr/sum_when_templates.py
Labels: product/custom, product/feature-flag

#29287 Updated sticky search to work with daterange inputs
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: QA Passed, Risk: Medium, product/feature-flag

#29296 Removed old band-aid from build_requirejs
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
Labels: product/invisible

#29116 Removed autolaunch flag from web apps
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/util.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
Labels: QA Passed, Risk: Medium, product/invisible

#29316 clear page on query
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
Labels: Risk: Medium, product/invisible

#29308 add basic messaging event API
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/test_messaging_event_api.py
  corehq/apps/api/urls.py
Labels: Risk: High, product/custom

#29319 Shows notification message for EOF navigation
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
Labels: Risk: Medium, product/all-users-all-environments

#29284 Add option for output file for logging for the casedb scripts
  custom/covid/management/commands/add_assignment_cases.py
  custom/covid/management/commands/add_hq_user_id_to_case.py
  custom/covid/management/commands/run_all_management_command.py
  custom/covid/management/commands/update_case_index_relationship.py
  custom/covid/management/commands/update_cases.py
  custom/covid/management/commands/update_owner_ids.py
Labels: product/invisible

#29315 auditcare cleanup
  corehq/apps/auditcare/decorators/__init__.py
  corehq/apps/auditcare/decorators/login.py
  corehq/apps/auditcare/middleware.py
  corehq/apps/auditcare/models.py
  corehq/apps/auditcare/signals.py
  corehq/apps/auditcare/tests/auth.py
  corehq/apps/auditcare/tests/test_auth.py
  corehq/apps/auditcare/tests/test_middleware.py
  corehq/apps/auditcare/urls.py
  corehq/apps/auditcare/views.py
Labels: product/invisible

#29318 [SSO] Alert created_by user on first time visiting a Domain that recently auto-trusted their new IdP
  corehq/apps/sso/models.py
  corehq/apps/sso/tests/generator.py
  corehq/apps/sso/tests/test_request_helpers.py
  corehq/apps/sso/utils/message_helpers.py
  corehq/apps/sso/utils/request_helpers.py
Labels: product/feature-flag

#29299 FHIRRepeater part 3 of 4
  corehq/motech/fhir/const.py
  corehq/motech/fhir/forms.py
  corehq/motech/fhir/models.py
  corehq/motech/fhir/repeater_helpers.py
  corehq/motech/fhir/repeaters.py
  corehq/motech/fhir/serializers.py
  corehq/motech/fhir/tests/test_model_functions.py
  corehq/motech/fhir/tests/test_models.py
  corehq/motech/fhir/tests/test_patient_reg.py
  corehq/motech/fhir/tests/test_repeater_helpers.py
  corehq/motech/fhir/views.py
  corehq/motech/serializers.py
  corehq/motech/urls.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
Labels: dependencies, product/feature-flag

#29323 PR feedback on messaging tests
  corehq/apps/api/tests/test_messaging_event_api.py
Labels: product/invisible

#29322 Fixed queryData not getting cleared
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
Labels: Risk: Medium, product/feature-flag

#29317 Removed mark_safe usages in translations
  corehq/apps/translations/app_translations/download.py
Labels: product/invisible

#29327 auditcare write once
  corehq/apps/auditcare/middleware.py
  corehq/apps/auditcare/models.py
  corehq/apps/auditcare/tests/test_middleware.py
  corehq/apps/auditcare/tests/test_models.py
Labels: product/invisible

#29324 Admin site tweaks for FHIR
  corehq/apps/data_dictionary/models.py
  corehq/motech/fhir/admin.py
  corehq/motech/fhir/models.py
Labels: product/feature-flag, product/invisible

#29275 Es/case list api
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/es/case_search.py
  corehq/apps/es/cases.py
  corehq/apps/hqcase/api/core.py
  corehq/apps/hqcase/api/get_list.py
  corehq/apps/hqcase/api/updates.py
  corehq/apps/hqcase/tests/test_case_list_api.py
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/hqcase/tests/test_serialization.py
  corehq/apps/hqcase/views.py
Labels: product/admin

#29330 Prevent admin site users linking across domains
  corehq/motech/fhir/admin.py
Labels: product/invisible

#29332 Add new domain to india nutrition project reports
  custom/nutrition_project/ucr/data_sources/death_records_v1.json
  custom/nutrition_project/ucr/data_sources/deliveries_v1.json
  custom/nutrition_project/ucr/data_sources/member_cases_v1.json
  custom/nutrition_project/ucr/data_sources/member_registrations_v1.json
  custom/nutrition_project/ucr/data_sources/nutrition_delivery_children_3_to_6_v1.json
  custom/nutrition_project/ucr/data_sources/pregnancy_registrations_v1.json
  custom/nutrition_project/ucr/data_sources/supplementary_nutrition_hcm_3years_6years.json
  custom/nutrition_project/ucr/data_sources/supplementary_nutrition_hcm_v1.json
  custom/nutrition_project/ucr/data_sources/supplementary_nutrition_thr_6months_3years.json
  custom/nutrition_project/ucr/data_sources/supplementary_nutrition_thr_pw_lw.json
  custom/nutrition_project/ucr/data_sources/supplementary_nutrition_thr_v1.json
  custom/nutrition_project/ucr/data_sources/weight_and_height_records_v1.json
  custom/nutrition_project/ucr/reports/deaths_v1.json
  custom/nutrition_project/ucr/reports/deliveries_v1.json
  custom/nutrition_project/ucr/reports/delivery_deaths_v1.json
  custom/nutrition_project/ucr/reports/growth_monitoring_v1.json
  custom/nutrition_project/ucr/reports/hcm_3years_6years_v1.json
  custom/nutrition_project/ucr/reports/hcm_report_v1.json
  custom/nutrition_project/ucr/reports/member_cases_v1.json
  custom/nutrition_project/ucr/reports/member_registrations_v1.json
  custom/nutrition_project/ucr/reports/number_of_days_center_open_v1.json
  custom/nutrition_project/ucr/reports/pregnancy_registrations_v1.json
  custom/nutrition_project/ucr/reports/thr_6months_3years_v1.json
  custom/nutrition_project/ucr/reports/thr_lw_v1.json
  custom/nutrition_project/ucr/reports/thr_pw_v1.json
  custom/nutrition_project/ucr/reports/thr_report_v1.json
Labels: product/custom, product/feature-flag

#29334 Sanitized mark_safe references in hqadmin
  corehq/apps/hqadmin/utils.py
Labels: product/invisible

#29333 Handled unauthorized user logouts
  corehq/apps/hqwebapp/login_handlers.py
  corehq/apps/hqwebapp/tests/test_login_handlers.py
Labels: product/invisible

#29340 Removed unused code in users.models
  corehq/apps/commtrack/util.py
  corehq/apps/users/models.py
Labels: product/invisible

#26647 Removed related locations
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/domain/deletion.py
  corehq/apps/locations/admin.py
  corehq/apps/locations/fixtures.py
  corehq/apps/locations/forms.py
  corehq/apps/locations/migrations/0020_delete_locationrelation.py
  corehq/apps/locations/models.py
  corehq/apps/locations/templates/locations/manage/location.html
  corehq/apps/locations/tests/data/related_location.xml
  corehq/apps/locations/tests/data/related_location_with_distance.xml
  corehq/apps/locations/tests/test_location_fixtures.py
  corehq/apps/locations/views.py
  corehq/toggles.py
  settings.py
Labels: product/feature-flag, reindex/migration

#29329 [SSO] update sso form tests
  corehq/apps/sso/tests/test_forms.py
Labels: product/feature-flag

#29328 [SSO] cleanup SSO async handler tests and fix small bug
  corehq/apps/sso/async_handlers.py
  corehq/apps/sso/tests/test_async_handlers.py
Labels: product/feature-flag

#29338 Removed unused JS_COMPRESSOR support
  corehq/apps/hqwebapp/uglify.py
  dev_settings.py
  docker/localsettings.py
  settings.py
Labels: product/invisible

#29351 Added link to feature flag docs & updated roles UI
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/toggles.py
Labels: product/admin, product/feature-flag

#29339 Add Default Export Settings Privilege
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0054_default_export_settings.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
Labels: product/invisible, reindex/migration

#29352 Update Ivory Coast MTN Gateway Params
  corehq/messaging/smsbackends/ivory_coast_mtn/models.py
Labels: product/custom

#29354 Removed ICDS-specific code from context_processors
  corehq/util/context_processors.py
Labels: product/invisible

#29362 Get last value instead of grouping for changing case props
  custom/nutrition_project/ucr/reports/hcm_3years_6years_v1.json
  custom/nutrition_project/ucr/reports/thr_6months_3years_v1.json
  custom/nutrition_project/ucr/reports/thr_lw_v1.json
  custom/nutrition_project/ucr/reports/thr_pw_v1.json
Labels: product/custom, product/feature-flag

#29366 Fix default export settings privilege slug typo
  corehq/privileges.py
Labels: product/invisible

#29209 Geocoder Widget in Webapps Case Search
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/templates/formplayer/query_view.html
Labels: QA Passed, Risk: Medium, product/all-users-all-environments

#29363 add temporary script to catch disappearing form
  scripts/tmp-disappearing-form-poller.py
Labels: product/invisible

#29365 Removed MONITOR_2FA_CHANGES
  corehq/apps/domain/forms.py
  corehq/apps/hqwebapp/utils.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/settings/views.py
  corehq/toggles.py
Labels: product/feature-flag

#29353 Added help link to feature flag
  corehq/toggles.py
Labels: product/admin

#29127 Web Apps pagination: limit pages, add "per page" dropdown and "go to" search
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/case_list_pagination_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
  corehq/apps/cloudcare/templates/cloudcare/spec/form_entry/mocha.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/pagination.html
  corehq/apps/cloudcare/templates/formplayer/users.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
  corehq/apps/hqwebapp/static/preview_app/less/preview_app/module.less
Labels: QA Passed, Risk: Medium, product/all-users-all-environments

#29350 Add documentation about endpoint for smsforms
  corehq/apps/case_migrations/views.py
Labels: product/invisible

#29343 Remove "Please update your project settings" emails
  corehq/apps/domain/tasks.py
  corehq/apps/domain/templates/domain/email/fm_outreach.html
  corehq/apps/domain/templates/domain/email/fm_outreach.txt
Labels: product/admin

#29370 use user's timezone if it's set
  corehq/util/timezones/tests/test_utils.py
  corehq/util/timezones/utils.py
Labels: product/invisible

#29279 web apps add new repeat translation
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: Risk: Medium, product/all-users-all-environments

#29374 Added comments to COVID custom rule
  custom/covid/rules/custom_actions.py
  custom/covid/rules/custom_criteria.py
Labels: product/invisible

#29375 Revert "use user's timezone if it's set"
  corehq/util/timezones/tests/test_utils.py
  corehq/util/timezones/utils.py
Labels: product/invisible

#29372 sanitized mark_safe usages in data_interfaces
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/interfaces.py
Labels: product/invisible

#29361 sanitize mark_safe references in domain
  corehq/apps/domain/forms.py
  corehq/apps/domain/views/accounting.py
  corehq/apps/domain/views/internal.py
Labels: product/invisible

#29367 enable Oauth in api_auth decorated functions
  corehq/apps/domain/auth.py
  corehq/apps/domain/decorators.py
  corehq/apps/domain/tests/test_auth_decorators.py
Labels: Risk: High, product/invisible

#29373 Make the case API available to flagged domains
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/hqcase/views.py
  corehq/toggles.py
Labels: product/feature-flag

#29349 Support parent properties as case search fields
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/case_search.py
  corehq/apps/ota/views.py
Labels: product/feature-flag

#29378 sanitized mark_safe references in smaller applications
  corehq/ex-submodules/phonelog/reports.py
  corehq/toggles.py
  corehq/util/markup.py
  corehq/util/tests/test_markup.py
  custom/_legacy/pact/reports/chw.py
  custom/_legacy/pact/reports/chw_list.py
  custom/_legacy/pact/reports/patient.py
  custom/_legacy/pact/reports/patient_list.py
  custom/icds_core/view_utils.py
Labels: product/invisible

#29382 Change description for New High Performing Users on Project Performance Report
  corehq/apps/reports/standard/project_health.py
  corehq/apps/reports/templates/reports/project_health/partials/users_tables.html
Labels: product/invisible

#29371 Replace default_export_settings ff with privilege
  corehq/apps/enterprise/forms.py
  corehq/apps/enterprise/views.py
  corehq/apps/export/tests/test_export_utils.py
  corehq/apps/export/utils.py
  corehq/apps/export/views/new.py
  corehq/toggles.py
Labels: QA Passed, product/admin

#29288 Clean up urlsanitize tests and comments
  corehq/util/urlsanitize/test/test_urlsanitize.py
  corehq/util/urlsanitize/urlsanitize.py
Labels: product/invisible

#29384 add confluence link
  corehq/toggles.py
Labels: product/invisible

#29381 Add INDDEX reports to two new domains
  custom/inddex/ucr/data_sources/food_consumption_indicators.json
  settings.py
Labels: product/custom

#29383 Add missing encoding parameter
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/app_manager/tests/test_report_fixtures_provider.py
  corehq/apps/translations/app_translations/upload_form.py
Labels: product/invisible

#29380 Sk/report cleanup
  corehq/apps/reports/commtrack/maps.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/maps.py
Labels: product/invisible

#29385 Optionally dump only specified models
  corehq/apps/dump_reload/couch/dump.py
  corehq/apps/dump_reload/interface.py
  corehq/apps/dump_reload/management/commands/dump_domain_data.py
  corehq/apps/dump_reload/management/commands/print_domain_stats.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
Labels: product/invisible

#29386 Add vectorlink-sierra-leone
  custom/abt/reports/data_sources/late_pmt.json
  custom/abt/reports/data_sources/sms_case.json
  custom/abt/reports/data_sources/supervisory_v2.json
  custom/abt/reports/data_sources/supervisory_v2019.json
  custom/abt/reports/data_sources/supervisory_v2020.json
  custom/abt/reports/sms_indicator_report.json
  custom/abt/reports/spray_progress_country.json
  custom/abt/reports/spray_progress_level_1.json
  custom/abt/reports/spray_progress_level_2.json
  custom/abt/reports/spray_progress_level_3.json
  custom/abt/reports/spray_progress_level_4.json
  custom/abt/reports/supervisory_report_v2.json
  custom/abt/reports/supervisory_report_v2019.json
  custom/abt/reports/supervisory_report_v2020.json
  settings.py
Labels: product/custom

#29377 SQL auditcare
  corehq/apps/auditcare/__init__.py
  corehq/apps/auditcare/management/commands/gdpr_scrub_user_auditcare.py
  corehq/apps/auditcare/middleware.py
  corehq/apps/auditcare/migrations/0001_sqlmodels.py
  corehq/apps/auditcare/migrations/__init__.py
  corehq/apps/auditcare/models.py
  corehq/apps/auditcare/tests/test_auth.py
  corehq/apps/auditcare/tests/test_export.py
  corehq/apps/auditcare/tests/test_gdpr_scrub_user_auditcare.py
  corehq/apps/auditcare/tests/test_models.py
  corehq/apps/auditcare/tests/testutils.py
  corehq/apps/auditcare/utils/__init__.py
  corehq/apps/auditcare/utils/export.py
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/hqadmin/reports.py
  corehq/apps/hqwebapp/login_handlers.py
  corehq/apps/hqwebapp/migrations/0007_user_access_agent.py
  corehq/apps/hqwebapp/models.py
  corehq/apps/hqwebapp/tests/test_login_handlers.py
  corehq/apps/hqwebapp/tests/test_models.py
  corehq/blobs/migrations/0002_blobmeta.py
  corehq/blobs/models.py
  corehq/blobs/util.py
  corehq/tests/noseplugins/patches.py
  corehq/util/models.py
  corehq/util/test_utils.py
  corehq/util/tests/test_models.py
  docs/databases.rst
  settings.py
Labels: product/invisible, reindex/migration

#29346 [SSO] Create project admin accessible UI for trusting external IdP of Web Users who are existing members
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/alerts.less
  corehq/apps/sso/models.py
  corehq/apps/sso/tests/test_async_handlers.py
  corehq/apps/sso/tests/test_caches.py
  corehq/apps/sso/tests/test_request_helpers.py
  corehq/apps/users/templates/users/edit_web_user.html
  corehq/apps/users/templates/users/web_users.html
  corehq/apps/users/views/__init__.py
Labels: product/feature-flag

#29391 Fixes for auditcare issues
  corehq/apps/auditcare/models.py
  corehq/util/models.py
  corehq/util/tests/test_models.py
Labels: product/invisible

#29336 Bulk upload fhir mapping
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
  corehq/motech/fhir/migrations/0003_auto_20210319_0948.py
  corehq/motech/fhir/models.py
  corehq/motech/fhir/validators.py
Labels: product/custom, product/feature-flag, reindex/migration

#29335 Add fhir resource get/search views
  corehq/motech/fhir/urls.py
  corehq/motech/fhir/utils.py
  corehq/motech/fhir/views.py
  urls.py
Labels: product/custom, product/feature-flag

#29394 add management command for getting repeaters stats
  corehq/motech/repeaters/management/commands/generate_repeaters_summary.py
Labels: product/invisible

#29397 Match expected API base url and param names
  corehq/messaging/smsbackends/ivory_coast_mtn/models.py
Labels: product/invisible

#29393 Make foreign values unique
  corehq/apps/auditcare/migrations/0002_uniques.py
  corehq/apps/auditcare/models.py
  corehq/util/models.py
Labels: product/invisible, reindex/migration

#29401 Revert "Make foreign values unique"
  corehq/apps/auditcare/migrations/0002_uniques.py
  corehq/apps/auditcare/models.py
  corehq/util/models.py
Labels: product/invisible, reindex/migration

#29392 Test showing FHIR model integrity
  corehq/motech/fhir/tests/test_models.py
Labels: product/invisible

#29396 Paginate queryset based on ID
  corehq/apps/dump_reload/sql/filters.py
  corehq/util/queries.py
  corehq/util/tests/test_queries.py
Labels: product/invisible

#29403 add feature flag that immediately blocks all restores for a specific domain
  corehq/apps/ota/rate_limiter.py
  corehq/toggles.py
Labels: product/feature-flag, product/invisible

#29345 Sanitized mark_safe usages in hqwebapp
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/hqwebapp/forms.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/templatetags/proptable_tags.py
  corehq/apps/hqwebapp/tests/test_proptable_tags.py
  corehq/apps/hqwebapp/widgets.py
Labels: product/invisible

#29364 sanitized mark_safe usages in tabs
  corehq/tabs/tabclasses.py
  corehq/tabs/templatetags/menu_tags.py
Labels: product/invisible

#29248 Sanitized mark_safe references in registration
  corehq/apps/registration/forms.py
Labels: Risk: High, product/invisible

#29218 Mjr/xss app manager
  corehq/apps/app_manager/templatetags/xforms_extras.py
  corehq/apps/app_manager/tests/templatetags/__init__.py
  corehq/apps/app_manager/tests/templatetags/test_xforms_extras.py
  corehq/apps/app_manager/views/modules.py
Labels: awaiting QA, product/invisible

#29404 Auditcare unique values
  corehq/apps/auditcare/migrations/0002_uniques.py
  corehq/apps/auditcare/models.py
  corehq/util/models.py
  corehq/util/tests/test_models.py
Labels: product/invisible, reindex/migration

#29408 Add feature flag to specifically skip fixtures on restores based on project
  corehq/apps/hqadmin/views/users.py
  corehq/apps/ota/views.py
  corehq/toggles.py
Labels: product/feature-flag, product/invisible

#29409 Revert "Auditcare unique values"
  corehq/apps/auditcare/migrations/0002_uniques.py
  corehq/apps/auditcare/models.py
  corehq/util/models.py
  corehq/util/tests/test_models.py
Labels: reindex/migration

#29376 Conditional alert warning modal
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_main.js
  corehq/messaging/scheduling/templates/scheduling/partials/conditional_alert_save.html
  corehq/messaging/scheduling/views.py
Labels: QA Passed, product/all-users-all-environments

#29344 Add location fields to web user download
  corehq/apps/users/bulk_download.py
Labels: product/all-users-all-environments

#29410 Revert "Revert "Auditcare unique values""
  corehq/apps/auditcare/migrations/0002_uniques.py
  corehq/apps/auditcare/models.py
  corehq/util/models.py
  corehq/util/tests/test_models.py
Labels: product/invisible, reindex/migration

#29398 Update venv and Docker setup instructions.
  DEV_SETUP.md
Labels: product/invisible

#29412 add links to readme
  README.md
Labels: product/invisible

#29413 update DET schema generation to use form.id instead of meta.instanceID
  corehq/apps/export/det/schema_generator.py
  corehq/apps/export/tests/test_det_schema_generation.py
Labels: product/feature-flag

#29379 Revert 29375 revert 29370 sk/timezone override
  corehq/apps/hqwebapp/templatetags/proptable_tags.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/data_sources.py
  corehq/apps/reports/v2/formatters/cases.py
  corehq/apps/reports/v2/utils.py
  corehq/apps/reports/views.py
  corehq/util/timezones/conversions.py
  corehq/util/timezones/tests/test_utils.py
  corehq/util/timezones/utils.py
Labels: product/all-users-all-environments

#29395 record timing data for slow form submissions
  corehq/apps/couch_sql_migration/tests/test_migration.py
  corehq/apps/locations/middleware.py
  corehq/apps/locations/permissions.py
  corehq/apps/receiverwrapper/views.py
  corehq/form_processor/submission_post.py
  corehq/middleware.py
  corehq/tests/test_middleware.py
  corehq/util/timer.py
Labels: Risk: High, product/invisible

#29414 a few changes to docs based on some new data flow diagrams
  docs/api.rst
  docs/images/data_pipeline_async.png
  docs/images/data_pipeline_sync.png
  docs/images/reporting_architecture.png
  docs/overview/architecture.rst
Labels: product/invisible

#29415 de-duplicate email validation in javascript
  corehq/apps/accounting/static/accounting/js/widgets.js
  corehq/apps/domain/static/domain/js/pro-bono.js
  corehq/apps/hqwebapp/static/hqwebapp/js/utils/email.js
  corehq/apps/sso/static/sso/js/edit_identity_provider.js
  corehq/apps/sso/static/sso/js/enterprise_edit_identity_provider.js
Labels: product/invisible

#29411 Application API performance tweak
  corehq/apps/api/resources/pagination.py
  corehq/apps/api/resources/v0_4.py
  corehq/apps/api/tests/app_resources.py
  corehq/apps/api/tests/utils.py
  corehq/apps/app_manager/app_schemas/case_properties.py
  corehq/apps/app_manager/xform_builder.py
Labels: Risk: High, product/all-users-all-environments

#29399 [SSO] Allow SSO-logged in users to view 2FA domain (if Trust was established)
  corehq/apps/domain/decorators.py
  corehq/apps/domain/tests/test_two_factor_check.py
Labels: Risk: High, product/invisible

#29419 Combine CaseInfo and CaseDisplay
  corehq/apps/data_interfaces/interfaces.py
  corehq/apps/locations/permissions.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/cases/data_sources.py
  custom/apps/crs_reports/reports.py
Labels: product/invisible

#29428 Bump lxml from 4.6.2 to 4.6.3
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies, product/invisible

#29425 Remove commcare_build_importer and jenkinsapi
  corehq/apps/builds/management/commands/commcare_build_importer.py
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
Labels: dependencies, product/invisible

#29426 Delete repeat records associated with deleted repeater
  corehq/motech/repeaters/tasks.py
Labels: product/invisible

#29355 upgrade js-xpath to 0.0.4
  corehq/apps/app_manager/templates/app_manager/partials/xpathValidator.html
  corehq/apps/app_manager/xpath_validator/nodejs/xpathConfig.js
  package.json
  yarn.lock
Labels: dependencies, product/invisible

#29433 don't return None
  corehq/apps/locations/models.py
Labels: product/invisible

#29069 Add Ethiopian date widget to webapps
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entrycontrols_full_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/calendar-picker-translations.js
  corehq/apps/cloudcare/templates/cloudcare/spec/form_entry/mocha.html
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  package.json
  yarn.lock
Labels: Risk: Medium, dependencies, product/all-users-all-environments

#29423 Jinja2 2.11.3
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies, product/invisible
