Repository dimagi/commcare-hq, pull requests merged in 2021-12, with the labels that each got.

#30777 Smh/user report enterprise domain support
  corehq/apps/enterprise/tests/test_enterprise_utils.py
  corehq/apps/enterprise/utils.py
  corehq/apps/es/users.py
  corehq/apps/reports/filters/controllers.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/standard/users/reports.py
  corehq/apps/reports/tests/test_esaccessors.py
Labels: product/feature-flag

#30783 Transition mobile access restrictions from FF to GA setting (PR 2 of 2)
  corehq/apps/domain/forms.py
  corehq/apps/domain/views/settings.py
  corehq/apps/ota/decorators.py
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/toggles.py
Labels: product/feature-flag

#30759 SMS user registration alerts
  corehq/apps/domain/models.py
  corehq/apps/sms/api.py
  corehq/apps/sms/forms.py
  corehq/apps/sms/static/sms/js/settings.js
  corehq/apps/sms/templates/sms/email/new_sms_user.html
  corehq/apps/sms/tests/test_registration.py
  corehq/apps/sms/views.py
Labels: product/all-users-all-environments

#30691 add time to start metrics celery service check
  corehq/apps/hqadmin/service_checks.py
  corehq/celery_monitoring/heartbeat.py
Labels: product/invisible

#30795 [hotfix] Revert "restrict login-as users access during restore"
  corehq/apps/ota/tests/test_utils.py
  corehq/apps/ota/utils.py
Labels: product/feature-flag

#30794 Revert "restrict login-as users access during restore"
  corehq/apps/ota/tests/test_utils.py
  corehq/apps/ota/utils.py
Labels: product/feature-flag

#30785 [Hubspot] Introduce additional metrics for tracking Hubspot tasks and actions
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#30792 More HTTP Verbs for Repeaters
  corehq/apps/app_manager/tests/test_repeater.py
  corehq/apps/domain/tests/test_views.py
  corehq/motech/const.py
  corehq/motech/repeaters/forms.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_models_slow.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/tests/test_tasks.py
  corehq/motech/repeaters/views/repeaters.py
  corehq/motech/requests.py
  corehq/motech/tests/test_simple_post.py
Labels: product/all-users-all-environments

#30784 Added alias for submission API with @api_auth
  corehq/apps/receiverwrapper/urls.py
  corehq/apps/receiverwrapper/views.py
Labels: product/invisible

#30802 Mobile access restriction GA setting form-not-saving-on-submit bug fix
  corehq/apps/domain/forms.py
Labels: product/feature-flag

#30804 Revert "Smh/user report enterprise domain support"
  corehq/apps/enterprise/tests/test_enterprise_utils.py
  corehq/apps/enterprise/utils.py
  corehq/apps/es/users.py
  corehq/apps/reports/filters/controllers.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/standard/users/reports.py
  corehq/apps/reports/tests/test_esaccessors.py
Labels: product/feature-flag

#30803 Add docstring to `deprecated_init` for clarity
  corehq/ex-submodules/casexml/apps/case/mock/case_block.py
Labels: product/invisible

#30800 remove config that ignores HMAC auth when in DEBUG mode
  corehq/apps/domain/auth.py
  corehq/apps/hqwebapp/session_details_endpoint/tests.py
  corehq/ex-submodules/dimagi/utils/logging.py
  corehq/util/hmac_request.py
  settings.py
Labels: product/invisible

#30808 Removed full-doc fetching from smart link requests
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/cloudcare/views.py
Labels: product/invisible, Risk: Medium

#30787 [Dependencies] Add readme to /requirements and unpin requirements without comments
  requirements/README.md
  requirements/base-requirements.in
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.in
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/sso-requirements.in
  requirements/test-requirements.in
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#30670 [hackathon] Always use user.get_email() for communications
  corehq/apps/accounting/models.py
  corehq/apps/accounting/templates/accounting/email/invoice_autopay_setup.html
  corehq/apps/app_manager/views/apps.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
  corehq/apps/enterprise/management/commands/report_on_enterprise_domain.py
  corehq/apps/enterprise/tasks.py
  corehq/apps/fixtures/views.py
  corehq/apps/hqadmin/tasks.py
  corehq/apps/hqadmin/views/operations.py
  corehq/apps/hqadmin/views/users.py
  corehq/apps/registration/tasks.py
  corehq/apps/registration/views.py
  corehq/apps/translations/views.py
Labels: product/invisible, Risk: High, Risk: Medium

#30780 [HubSpot] Management command to audit a user's hubspot status
  corehq/apps/analytics/management/commands/audit_user_in_hubspot.py
  corehq/apps/analytics/management/commands/blocked_hubspot_users_summary.py
  corehq/apps/analytics/utils.py
Labels: product/invisible

#30806 Check all mobile endpoints besides submissions
  corehq/apps/domain/decorators.py
  corehq/apps/mobile_auth/views.py
  corehq/apps/ota/decorators.py
  corehq/apps/ota/views.py
Labels: product/feature-flag, product/invisible, Risk: High

#30796 Revert "Revert "restrict login-as users access during restore""
  corehq/apps/cloudcare/tests/test_esaccessors.py
  corehq/apps/ota/tests/test_utils.py
  corehq/apps/ota/utils.py
Labels: product/feature-flag, Risk: Medium

#30811 fix creating case with index
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_payload_generator.py
Labels: product/feature-flag

#30813 Add expired domains
  custom/expired_domains.md
Labels: product/invisible

#30814 Update messaging around data dictionary valid values...
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/partials/valid_values_th_content.html
Labels: product/invisible

#30817 Pretty print evaluated expression
  corehq/apps/userreports/static/userreports/js/expression_evaluator.js
Labels: product/feature-flag

#30805 combine celery checks so both print
  corehq/apps/hqadmin/service_checks.py
Labels: product/invisible

#30812 set default values for system properties just in time
  corehq/ex-submodules/casexml/apps/case/mock/case_block.py
  corehq/ex-submodules/casexml/apps/case/mock/tests/test_case_block.py
Labels: product/invisible

#30548 Python 3.9 Dockerfile
  Dockerfile
Labels: product/invisible

#30612 Run tests against Python 3.9
  docker/Dockerfile
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, product/invisible, dependencies

#30821 Update service_checks.py
  corehq/apps/hqadmin/service_checks.py
Labels: product/invisible

#30820 Require edit data and API permission for submit api
  corehq/apps/receiverwrapper/views.py
Labels: product/all-users-all-environments

#30828 ucr task domain tagging
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/linked_domain/ucr.py
  corehq/apps/userreports/pillow_utils.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/views.py
Labels: product/invisible

#30826 remove case migrations
  corehq/apps/case_migrations/README.md
  corehq/apps/case_migrations/forms.py
  corehq/apps/case_migrations/migration.py
  corehq/apps/case_migrations/templates/case_migrations/migration.html
  corehq/apps/case_migrations/tests/__init__.py
  corehq/apps/case_migrations/urls.py
  corehq/apps/case_migrations/views.py
  corehq/apps/ota/case_restore.py
  corehq/apps/ota/tests/test_case_restore.py
  corehq/apps/ota/urls.py
  corehq/apps/ota/views.py
  corehq/toggles.py
Labels: product/invisible

#30823 remove unused toggle
  corehq/toggles.py
Labels: product/invisible

#30818 [data registry] form linking multiple case types
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/data/suite_registry/form_link_followup_module_registry.xml
  corehq/apps/app_manager/tests/test_form_workflow_multipe_case_types.py
  corehq/apps/app_manager/tests/test_shadow_forms.py
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/app_manager/tests/util.py
  corehq/apps/locations/tests/test_location_fixtures.py
  corehq/tests/util/xml.py
Labels: product/feature-flag

#30827 Remove CommCareCase - part 1
  corehq/apps/api/es.py
  corehq/apps/api/models.py
  corehq/apps/api/resources/v0_3.py
  corehq/apps/api/tests/case_resources.py
  dev_settings.py
Labels: product/invisible, Risk: High

#30789 GitHub migrations checks
  .github/labels.yml
  .gitignore
  Makefile
  docker/run.sh
  migrations.lock
  scripts/bash-utils.sh
  scripts/copy_domain_to_remote.sh
  scripts/datadog-utils.sh
  scripts/test-django-migrations.sh
  scripts/test-make-requirements.sh
Labels: product/invisible

#30833 Add Docker setup group for Github Actions
  docker/run.sh
  scripts/docker
Labels: product/invisible

#30829 utilty function ordered case types
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/utils.py
Labels: product/invisible

#30836 Use an evaluation context with the filter
  corehq/motech/repeaters/expression/repeaters.py
  corehq/motech/repeaters/expression/tests.py
Labels: product/feature-flag

#30835 Move make migrations.lock action into makemigrations management command
  Makefile
  hqscripts/management/commands/makemigrations.py
  migrations.lock
  scripts/test-django-migrations.sh
Labels: product/invisible

#30839 Hotfix: Use an evaluation context with the filter
  corehq/motech/repeaters/expression/repeaters.py
  corehq/motech/repeaters/expression/tests.py
Labels: product/feature-flag

#30834 Add expand_id_property to case search model and suite xml
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/case_search/models.py
Labels: product/invisible

#30838 exanded case search results
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/data/suite/smart_link_remote_request.xml
  corehq/apps/app_manager/tests/data/suite_registry/form_link_followup_module_registry.xml
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/case_search/models.py
  corehq/apps/case_search/tests/test_models.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/ota/tests/test_registry_case_details.py
  corehq/apps/ota/views.py
  corehq/ex-submodules/casexml/apps/case/models.py
  corehq/form_processor/abstract_models.py
  corehq/form_processor/models.py
Labels: product/feature-flag, Risk: High

#30842 Update `migrations.lock` preamble to clarify origin and purpose.
  hqscripts/management/commands/makemigrations.py
  migrations.lock
Labels: product/invisible

#30798 Added management command to find entities
  corehq/apps/app_manager/management/commands/check_for_form_entities.py
Labels: product/invisible

#30797 Requires Python 3.9
  corehq/form_processor/models.py
  corehq/form_processor/tests/test_models.py
Labels: product/invisible, Risk: High

#30849 Update data dictionary export/import...
  corehq/apps/data_dictionary/tests/data/broken_data_dictionary.xlsx
  corehq/apps/data_dictionary/tests/data/clean_data_dictionary.xlsx
  corehq/apps/data_dictionary/tests/test_import_export.py
  corehq/apps/data_dictionary/views.py
Labels: product/invisible

#30742 User must be admin in both domains to link domains
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/exceptions.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/tests/test_views.py
  corehq/apps/linked_domain/views.py
Labels: product/all-users-all-environments

#30844 related case lookup fixups
  corehq/apps/ota/tests/test_registry_case_details.py
  corehq/apps/ota/views.py
Labels: product/invisible

#30851 exclude related cases from query results
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/data/suite_registry/form_link_followup_module_registry.xml
  corehq/apps/app_manager/tests/test_suite_registry_search.py
Labels: product/feature-flag

#30790 Rc/track bulk group updates
  corehq/apps/groups/models.py
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/util.py
Labels: product/feature-flag, Risk: Medium

#30770 Data dictionary valid values
  corehq/apps/app_manager/app_schemas/case_properties.py
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/exceptions.py
  corehq/apps/case_importer/static/case_importer/js/excel_fields.js
  corehq/apps/case_importer/static/case_importer/js/main.js
  corehq/apps/case_importer/suggested_fields.py
  corehq/apps/case_importer/templates/case_importer/excel_fields.html
  corehq/apps/case_importer/templates/case_importer/import_cases.html
  corehq/apps/case_importer/templates/case_importer/partials/excel_field_rows.html
  corehq/apps/case_importer/templates/case_importer/partials/ko_import_status.html
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/case_importer/tests/test_suggested_fields.py
  corehq/apps/case_importer/tracking/task_status.py
  corehq/apps/case_importer/views.py
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
  corehq/apps/data_dictionary/migrations/0008_casepropertyallowedvalue.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/templates/data_dictionary/partials/valid_values_th_content.html
  corehq/apps/data_dictionary/tests/data/broken_data_dictionary.xlsx
  corehq/apps/data_dictionary/tests/data/clean_data_dictionary.xlsx
  corehq/apps/data_dictionary/tests/test_import_export.py
  corehq/apps/data_dictionary/tests/test_models.py
  corehq/apps/data_dictionary/tests/test_util.py
  corehq/apps/data_dictionary/tests/test_view.py
  corehq/apps/data_dictionary/tests/utils.py
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/groups/static/groups/js/group_members.js
  corehq/apps/hqwebapp/static/case_importer/less/case_importer.less
  corehq/apps/hqwebapp/static/data_dictionary/less/data_dictionary.less
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-input-map.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-key-val-list.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/navs.less
  migrations.lock
Labels: reindex/migration, QA Passed, product/feature-flag, Risk: High, Risk: Medium

#30847 Added progress message for smart links
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
Labels: product/feature-flag, Risk: Medium

#30857 Added docs on XSS to js guide
  docs/js-guide/README.md
  docs/js-guide/security.md
Labels: product/invisible

#30856 Allow customizing batch size for entity checks
  corehq/apps/app_manager/management/commands/check_for_form_entities.py
Labels: product/invisible

#30832 Make post_api handle its own auth
  corehq/apps/receiverwrapper/tests/test_auth.py
  corehq/apps/receiverwrapper/views.py
Labels: product/invisible

#30858 Disable workflow group for docker setup
  docker/run.sh
  scripts/docker
Labels: product/invisible

#30852 Fix js undefined var error
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/actions.js
Labels: product/invisible

#30859 Replace web apps progress bar with spinner when progress is unknown
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/layout/views/progress_bar.js
  corehq/apps/cloudcare/templates/formplayer/progress.html
Labels: product/all-users-all-environments, Risk: Medium

#30863 permit indexing a case that's being created in the data registry case update repeater
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_payload_generator.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_repeater.py
Labels: product/feature-flag

#30864 add test file missing from 30838
  corehq/apps/case_search/tests/test_utils.py
Labels: product/invisible

#30285 Cross domain UCR: report builder changes
  corehq/apps/api/resources/v0_5.py
  corehq/apps/app_manager/fields.py
  corehq/apps/domain/dbaccessors.py
  corehq/apps/userreports/dbaccessors.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/rebuild.py
  corehq/apps/userreports/reports/builder/README.md
  corehq/apps/userreports/reports/builder/columns.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/reports/filters/choice_providers.py
  corehq/apps/userreports/reports/filters/factory.py
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/static/userreports/js/configure_report.js
  corehq/apps/userreports/static/userreports/js/data_source_select_model.js
  corehq/apps/userreports/static/userreports/js/report_config.js
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
  corehq/apps/userreports/templates/userreports/reportbuilder/data_source_select.html
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/tests/test_registry_data_source_config.py
  corehq/apps/userreports/tests/test_registry_pillow.py
  corehq/apps/userreports/tests/test_report_builder.py
  corehq/apps/userreports/tests/test_resume_rebuild.py
  corehq/apps/userreports/ui/fields.py
  corehq/apps/userreports/util.py
  corehq/apps/userreports/views.py
  corehq/couchapps/__init__.py
  corehq/couchapps/registry_report_configs/views/view/map.js
  corehq/couchapps/registry_report_configs/views/view/reduce.js
  corehq/motech/dhis2/forms.py
  corehq/motech/dhis2/models.py
  corehq/reports.py
Labels: QA Passed, product/feature-flag, Risk: High

#30831 User filter update to support enterprise domains for User History Report
  corehq/apps/enterprise/tests/test_enterprise_utils.py
  corehq/apps/enterprise/utils.py
  corehq/apps/es/users.py
  corehq/apps/reports/filters/controllers.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/standard/users/reports.py
  corehq/apps/reports/tests/test_esaccessors.py
Labels: product/feature-flag

#30776 Enable user case creation for Web Users
  corehq/apps/app_manager/tasks.py
  corehq/apps/callcenter/sync_usercase.py
  corehq/apps/callcenter/tasks.py
  corehq/apps/callcenter/tests/test_indicators.py
  corehq/apps/callcenter/tests/test_location_owners.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/callcenter/tests/test_web_user_sync_usercases.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/retire.py
  corehq/toggles.py
  custom/covid/tests/test_custom_rules.py
Labels: awaiting QA, product/feature-flag

#30841 [USH] Enable users to load "unrelated" cases in case search results
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/case_search/models.py
  corehq/apps/case_search/tests/test_models.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/tests/test_case_search_es.py
Labels: QA Passed, product/feature-flag, product/custom

#30867 Revert "User filter update to support enterprise domains for User History Report"
  corehq/apps/enterprise/tests/test_enterprise_utils.py
  corehq/apps/enterprise/utils.py
  corehq/apps/es/users.py
  corehq/apps/reports/filters/controllers.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/standard/users/reports.py
  corehq/apps/reports/tests/test_esaccessors.py
Labels: product/feature-flag

#30819 Build MALT table in chunks
  corehq/apps/data_analytics/malt_generator.py
  corehq/apps/data_analytics/tasks.py
  corehq/apps/data_analytics/util.py
Labels: product/invisible

#30865 UCR export docs
  corehq/apps/userreports/README.rst
  corehq/apps/userreports/views.py
Labels: product/invisible

#30869 Added missing usercase param
  corehq/apps/callcenter/tasks.py
Labels: product/all-users-all-environments

#30871 Revert "Cross domain UCR: report builder changes"
  corehq/apps/api/resources/v0_5.py
  corehq/apps/app_manager/fields.py
  corehq/apps/domain/dbaccessors.py
  corehq/apps/userreports/dbaccessors.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/rebuild.py
  corehq/apps/userreports/reports/builder/README.md
  corehq/apps/userreports/reports/builder/columns.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/reports/filters/choice_providers.py
  corehq/apps/userreports/reports/filters/factory.py
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/static/userreports/js/configure_report.js
  corehq/apps/userreports/static/userreports/js/data_source_select_model.js
  corehq/apps/userreports/static/userreports/js/report_config.js
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
  corehq/apps/userreports/templates/userreports/reportbuilder/data_source_select.html
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/tests/test_registry_data_source_config.py
  corehq/apps/userreports/tests/test_registry_pillow.py
  corehq/apps/userreports/tests/test_report_builder.py
  corehq/apps/userreports/tests/test_resume_rebuild.py
  corehq/apps/userreports/ui/fields.py
  corehq/apps/userreports/util.py
  corehq/apps/userreports/views.py
  corehq/couchapps/__init__.py
  corehq/couchapps/registry_report_configs/views/view/map.js
  corehq/couchapps/registry_report_configs/views/view/reduce.js
  corehq/motech/dhis2/forms.py
  corehq/motech/dhis2/models.py
  corehq/reports.py
Labels: product/feature-flag, Risk: High

#30862 Updated celery logger to prevent duplicate messages
  settings.py
Labels: product/invisible

#30845 case search config refactor
  corehq/apps/case_search/models.py
  corehq/apps/case_search/tests/test_case_search_endpoint.py
  corehq/apps/case_search/tests/test_case_search_registry.py
  corehq/apps/case_search/tests/test_models.py
  corehq/apps/case_search/utils.py
  corehq/apps/ota/views.py
  corehq/pillows/case_search.py
Labels: product/invisible

#30860 Adding logging for export to excel parameters
  corehq/apps/reports/tasks.py
Labels: product/invisible

#30855 Add lite release management privilege
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0059_add_lite_release_management_priv.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
  migrations.lock
Labels: reindex/migration, product/invisible

#30875 Hotfix: Replace celery.chunks with our own chunking
  corehq/apps/data_analytics/tasks.py
  corehq/apps/reports/tasks.py
Labels: product/invisible

#30874 Replace celery.chunks with our own chunking
  corehq/apps/data_analytics/tasks.py
  corehq/apps/reports/tasks.py
Labels: product/invisible

#30878 update python 3.6 references to 3.9
  .gitignore
  DEV_SETUP.md
  requirements/.python-version
Labels: product/invisible, dependencies

#30692 [couch-to-sql] [Repeaters] Proxy model CreateCaseRepeaters
  corehq/motech/repeaters/migrations/0007_add_repeater_type.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_proxy_models.py
Labels: reindex/migration, product/invisible

#30868 Disable Add Downstream Domain button if nothing selected
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
Labels: product/invisible

#30815 Added exclude_if_none to some app sub-models
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_modules.py
  corehq/apps/app_manager/views/schedules.py
Labels: product/invisible

#30882 Updated link in toggles.rst
  docs/toggles.rst
Labels: product/invisible

#30887 Revert "Removed @flaky_slow from offending test"
  corehq/apps/sms/tests/test_backends.py
Labels: product/invisible

#30885 Allow adding case property descriptions from form settings
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
  corehq/apps/data_dictionary/util.py
  corehq/apps/hqwebapp/templates/hqwebapp/partials/ko_inline_edit.html
Labels: product/feature-flag

#30888 Hopefully fix intermittent sms test error
  corehq/apps/sms/tests/test_backends.py
Labels: product/invisible

#30889 Mark DD validation flag as USH
  corehq/toggles.py
Labels: product/invisible

#30886 Revert rename from multiselectProperties back to multiselect
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/templates/linked_domain/partials/push_content.html
  corehq/apps/registry/templates/registry/registry_edit.html
Labels: product/invisible

#30893 added check for role column and adjusted tests
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
Labels: product/all-users-all-environments, Risk: Medium

#30866 Add auth to view
  corehq/apps/export/views/utils.py
Labels: product/feature-flag

#30900 Updated invitation flow to create user as non-admin
  corehq/apps/users/views/web.py
Labels: product/all-users-all-environments

#30898 Remove unused mobile lockout toggle
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_user_model.py
  corehq/toggles.py
Labels: product/invisible
