Repository dimagi/commcare-hq, pull requests merged in 2021-04, with the labels that each got.

#29447 Upgrade ssri from 6.0.1 to 8.0.1
  package.json
  yarn.lock
Labels: dependencies, dependencies/javascript, product/invisible

#29449 Sk/deviceid not date
  corehq/apps/hqwebapp/templatetags/proptable_tags.py
  corehq/apps/reports/views.py
Labels: product/invisible

#29450 Format meta file for human readability
  corehq/apps/dump_reload/management/commands/dump_domain_data.py
Labels: product/invisible

#29300 Test claiming a case from a different domain fails
  corehq/apps/ota/tests/test_claim.py
Labels: product/invisible

#29210 allow setting up fhir resource type and path
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
  corehq/motech/fhir/const.py
  corehq/motech/fhir/migrations/0003_auto_20210319_0948.py
  corehq/motech/fhir/models.py
  corehq/motech/fhir/tests/test_utils.py
  corehq/motech/fhir/tests/test_validators.py
  corehq/motech/fhir/urls.py
  corehq/motech/fhir/utils.py
  corehq/motech/fhir/validators.py
  corehq/motech/fhir/views.py
  urls.py
Labels: product/custom, product/feature-flag, reindex/migration

#29430 Emit histogram of number of lookup table items sent in each restore
  corehq/apps/fixtures/fixturegenerators.py
Labels: Risk: Medium, product/invisible

#29456 Drop `FHIRResourceType.template`
  corehq/motech/fhir/migrations/0004_remove_fhirresourcetype_template.py
  corehq/motech/fhir/models.py
  corehq/motech/fhir/tests/test_api_endpoints.py
  corehq/motech/fhir/tests/test_model_functions.py
  corehq/motech/fhir/tests/test_repeater_helpers.py
Labels: product/invisible, reindex/migration

#29459 Custom requirements in local.txt
  .gitignore
  DEV_SETUP.md
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  requirements/local.txt.sample
Labels: dependencies, product/invisible

#29422 Upgrade Pillow from 7.1.0 to 8.1.2
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, dependencies, product/invisible

#29453 SMART Metadata URLs
  corehq/motech/fhir/const.py
  corehq/motech/fhir/tests/test_smart_metadata_endpoints.py
  corehq/motech/fhir/urls.py
  corehq/motech/fhir/utils.py
  corehq/motech/fhir/views.py
Labels: product/feature-flag

#29451 Update advanced_app_features.rst
  docs/apps/advanced_app_features.rst
Labels: product/invisible

#29452 [SSO] Allow Use of Token Encryption / Encrypted Assertions
  corehq/apps/sso/configuration.py
  corehq/apps/sso/forms.py
  corehq/apps/sso/migrations/0002_identityprovider_require_encrypted_assertions.py
  corehq/apps/sso/models.py
  corehq/apps/sso/tests/test_forms.py
Labels: product/feature-flag, reindex/migration

#29309 Sanitize User mark_safe
  corehq/apps/hqwebapp/tests/utils/__init__.py
  corehq/apps/hqwebapp/tests/utils/test_translation.py
  corehq/apps/hqwebapp/utils/__init__.py
  corehq/apps/hqwebapp/utils/translation.py
  corehq/apps/users/forms.py
  corehq/apps/users/tasks.py
  corehq/apps/users/tests/test_util.py
  corehq/apps/users/util.py
  corehq/apps/users/views/__init__.py
Labels: QA Passed, product/invisible

#29464 Revert "Conditional alert warning modal"
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_main.js
  corehq/messaging/scheduling/templates/scheduling/partials/conditional_alert_save.html
  corehq/messaging/scheduling/views.py
Labels: product/all-users-all-environments

#29438 repeat translation find dictionary
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
Labels: Risk: Medium, product/all-users-all-environments

#29481 get translation find parent fix
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
Labels: Risk: Medium, product/all-users-all-environments

#29468 Update Pygments version
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies, product/invisible

#29461 Remove case_details.html
  corehq/apps/cloudcare/templates/cloudcare/includes/case_details.html
Labels: Risk: Medium, product/invisible

#29368 add allow_cors decorator and allow CORS for new case API
  corehq/apps/api/cors.py
  corehq/apps/api/decorators.py
  corehq/apps/api/resources/__init__.py
  corehq/apps/domain/tests/test_auth_decorators.py
  corehq/apps/hqcase/views.py
Labels: Risk: High, product/invisible

#29478 Fix docs on requirements/local workflow
  DEV_SETUP.md
  requirements/local.in.sample
  requirements/local.txt.sample
Labels: dependencies, product/invisible

#29483 Add formplayer to list of containers
  DEV_SETUP.md
Labels: product/invisible

#29480 add management command to calculate the disk size of a domain's forms and cases
  corehq/apps/domain/management/commands/calculate_physical_size.py
Labels: product/invisible

#29454 Change Hubspot/Kissmetrics failure email recipient
  corehq/apps/analytics/tasks.py
  corehq/util/email_event_utils.py
  settings.py
Labels: product/invisible

#29457 Auditcare cleanup and PR feedback
  corehq/apps/auditcare/middleware.py
  corehq/apps/auditcare/migrations/0003_truncatechars.py
  corehq/apps/auditcare/models.py
  corehq/apps/auditcare/tests/test_middleware.py
  corehq/apps/auditcare/tests/test_models.py
  corehq/apps/auditcare/utils/export.py
  corehq/ex-submodules/casexml/apps/stock/models.py
  corehq/form_processor/models.py
  corehq/util/models.py
Labels: Risk: High, product/invisible, reindex/migration

#29485 Updated django app README
  corehq/apps/README.rst
Labels: product/invisible

#29465 Handle an empty project space filter
  corehq/apps/accounting/async_handlers.py
Labels: product/invisible

#29490 Use FHIR version name in URL
  corehq/motech/fhir/tests/test_utils.py
  corehq/motech/fhir/utils.py
  corehq/motech/fhir/views.py
Labels: product/invisible

#29494 Removed NEW_MULTIMEDIA_UPLOADER toggle
  corehq/apps/app_manager/templates/app_manager/partials/new_multimedia_uploader.html
  corehq/toggles.py
Labels: product/invisible

#29390 Sanitized mark_safe usages in accounting
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/interface.py
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/accounting/views.py
Labels: QA Passed, product/invisible

#29484 FHIR Data dictionary code followup
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/views.py
Labels: product/custom, product/feature-flag

#29491 Fix the files where KO was parsing text as HTML
  corehq/apps/app_manager/templates/app_manager/partials/settings/commcare_settings.html
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/apps/users/templates/users/roles_and_permissions.html
Labels: product/invisible

#29499 Remove unused download_fixture_file
  corehq/apps/fixtures/urls.py
  corehq/apps/fixtures/views.py
Labels: Risk: Medium, product/invisible

#29498 Include couch data in auditcare reports
  corehq/apps/auditcare/management/commands/gdpr_scrub_user_auditcare.py
  corehq/apps/auditcare/tests/test_export.py
  corehq/apps/auditcare/tests/test_gdpr_scrub_user_auditcare.py
  corehq/apps/auditcare/tests/testutils.py
  corehq/apps/auditcare/utils/export.py
Labels: product/invisible

#29503 Allow colons in WhatsApp template variables
  corehq/messaging/smsbackends/turn/tests/test_template_messages.py
  corehq/messaging/whatsapputil.py
Labels: product/invisible

#29487 PKCE Support for OAuth 2
  corehq/apps/hqwebapp/admin.py
  corehq/apps/hqwebapp/migrations/0008_hqoauthapplication.py
  corehq/apps/hqwebapp/models.py
  corehq/apps/hqwebapp/tasks.py
  corehq/apps/hqwebapp/templates/hqwebapp/oauth_application_registration_form.html
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/views.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
  urls.py
Labels: dependencies, reindex/migration

#29496 add help link
  corehq/toggles.py
Labels: product/custom, product/feature-flag

#29502 A few more auditcare cleanups
  corehq/apps/auditcare/middleware.py
  corehq/apps/auditcare/tests/test_middleware.py
  corehq/apps/auditcare/urls.py
  corehq/apps/auditcare/views.py
  docker/localsettings.py
  settings.py
  testsettings.py
Labels: product/invisible

#29507 casedb add_assignment_cases script modification
  custom/covid/management/commands/add_assignment_cases.py
  custom/covid/tests/test_management_commands.py
Labels: product/invisible

#29508 Added fuzzy matching support for case search related case queries
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/case_search.py
Labels: product/feature-flag

#29495 Updated to correct link at 403 page
  corehq/apps/locations/permissions.py
Labels: product/all-users-all-environments

#29509 Use `resource_url()`
  corehq/motech/fhir/repeater_helpers.py
Labels: product/invisible

#29448 fix broken 2FA link
  corehq/apps/hqadmin/templates/hqadmin/disable_two_factor.html
Labels: product/admin

#29500 Added FAQ for UCR docs
  docs/ucr/faq.md
Labels: product/invisible

#29497 [SSO] Cleanup admin forms, certificate uploads and downloads
  corehq/apps/sso/certificates.py
  corehq/apps/sso/forms.py
  corehq/apps/sso/static/sso/js/enterprise_edit_identity_provider.js
  corehq/apps/sso/templates/sso/enterprise_admin/edit_identity_provider.html
  corehq/apps/sso/tests/generator.py
  corehq/apps/sso/tests/test_forms.py
  corehq/apps/sso/utils/url_helpers.py
  corehq/apps/sso/views/accounting_admin.py
  corehq/apps/sso/views/enterprise_admin.py
Labels: product/feature-flag

#29517 don't error on app sorting if no date_created is set
  corehq/apps/api/resources/v0_4.py
  corehq/apps/api/tests/app_resources.py
Labels: product/all-users-all-environments

#29518 Add ERM_DEVELOPMENT feature flag
  corehq/toggles.py
Labels: product/invisible

#29520 Fix typo
  docs/formplayer.rst
Labels: product/invisible

#29519 Removed AgeInMonthsBucketsColumn
  corehq/apps/userreports/README.rst
  corehq/apps/userreports/reports/factory.py
  corehq/apps/userreports/reports/specs.py
  corehq/apps/userreports/tests/test_report_aggregation.py
Labels: product/invisible

#29511 Decrease from 10000 (default) to 5000
  corehq/motech/repeaters/tasks.py
Labels: product/invisible

#29525 Increase timeout for Repeater.by_domain to 1h
  corehq/motech/repeaters/models.py
Labels: product/invisible

#29455 Paginate incomplete-forms
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/controller.js
  corehq/apps/cloudcare/templates/formplayer/session_list.html
  package.json
  yarn.lock
Labels: QA Passed, Risk: Medium, dependencies, product/all-users-all-environments

#29523 Added related case property search support to case search admin page
  corehq/apps/case_search/views.py
Labels: product/admin

#29029 SQL Repeat Record Report & Case Data Report
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/tests/test_tasks.py
  corehq/apps/data_interfaces/tests/test_utils.py
  corehq/apps/data_interfaces/utils.py
  corehq/ex-submodules/casexml/apps/case/templates/case/partials/repeat_records.html
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/migrations/0004_attempt_strings.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/templates/repeaters/partials/attempt_history.html
  corehq/motech/repeaters/templates/repeaters/partials/repeater_row.html
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/views/__init__.py
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/repeaters.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
Labels: product/invisible, reindex/migration

#29521 Removed copy_multimedia view
  corehq/apps/app_manager/templates/app_manager/partials/settings/multimedia_ajax.html
  corehq/apps/app_manager/urls.py
  corehq/apps/hqmedia/views.py
Labels: product/invisible

#29531 Updated help text on case search config
  corehq/apps/domain/templates/domain/admin/case_search.html
Labels: product/feature-flag

#29524 Moved linked project tasks to their own queue
  corehq/apps/linked_domain/tasks.py
Labels: product/invisible

#29537 [SSO] add SAML user data debug view for staging
  corehq/apps/sso/urls.py
  corehq/apps/sso/views/saml.py
Labels: product/invisible

#29526 Only report user fixture counts, but get them right
  corehq/apps/fixtures/fixturegenerators.py
Labels: Risk: Medium, product/invisible

#29538 Add metric counting new repeat records
  corehq/motech/repeaters/models.py
Labels: product/invisible

#29533 use stale query while creating repeaters
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/signals.py
Labels: product/invisible

#29479 Sanitize mark_safe usages for reports
  corehq/apps/hqadmin/reports.py
  corehq/apps/reports/display.py
  corehq/apps/reports/filters/forms.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/formdetails/readable.py
  corehq/apps/reports/generic.py
  corehq/apps/reports/models.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/data_sources.py
  corehq/apps/reports/standard/cases/filters.py
  corehq/apps/reports/standard/deployments.py
  corehq/apps/reports/standard/forms/reports.py
  corehq/apps/reports/standard/inspect.py
  corehq/apps/reports/standard/message_event_display.py
  corehq/apps/reports/standard/monitoring.py
  corehq/apps/reports/standard/sms.py
  corehq/apps/reports/templates/reports/async/partials/tabular_cell.html
  corehq/apps/reports/tests/test_generic.py
  corehq/apps/reports/tests/test_models.py
  corehq/apps/reports/util.py
  corehq/apps/reports/views.py
  corehq/apps/userreports/reports/view.py
  corehq/ex-submodules/phonelog/reports.py
  corehq/motech/repeaters/views/repeat_records.py
Labels: QA Passed, product/invisible

#29486 Escaped user-submitted field names on forms
  corehq/apps/commtrack/forms.py
  corehq/apps/custom_data_fields/edit_entity.py
Labels: QA Passed, Risk: Medium, product/invisible

#29505 Sanitized mark_safe usages in hqwebapp (2nd attempt)
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/hqwebapp/forms.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/templatetags/proptable_tags.py
  corehq/apps/hqwebapp/tests/test_proptable_tags.py
  corehq/apps/hqwebapp/widgets.py
Labels: QA Passed, product/invisible

#29458 Revert "Revert "Mjr/xss app manager""
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templatetags/xforms_extras.py
  corehq/apps/app_manager/tests/templatetags/__init__.py
  corehq/apps/app_manager/tests/templatetags/test_xforms_extras.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/hqmedia/models.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/views.py
Labels: QA Passed, product/invisible

#29406 Sanitize mark_safe usages in exports
  corehq/apps/export/views/incremental.py
  corehq/apps/export/views/list.py
  corehq/apps/export/views/new.py
Labels: QA Passed, product/invisible

#29516 stick with default escaping for multi select2
  corehq/apps/hqwebapp/static/hqwebapp/js/select_2_ajax_widget.js
  corehq/apps/reports/static/reports/js/filters/select2s.js
Labels: QA Passed, product/invisible

#29469 Escape HTML in underscore templates for other apps
  corehq/apps/accounting/static/accounting/js/pricing_table.js
  corehq/apps/enterprise/static/enterprise/js/enterprise_settings.js
  corehq/apps/export/static/export/js/create_export.js
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/static/locations/js/location_tree.js
  corehq/apps/reports/templates/reports/partials/base_maps.html
  corehq/apps/reports_core/static/reports_core/js/maps.js
  corehq/apps/sms/static/sms/js/chat_contacts.js
  corehq/apps/userreports/static/userreports/js/configurable_reports_home.js
Labels: QA Passed, product/invisible

#29476 Escape html in users
  corehq/apps/users/static/users/js/filtered_download.js
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/static/users/js/web_users.js
Labels: QA Passed, product/invisible

#29470 Escape html templates in app manager
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/actions.js
  corehq/apps/app_manager/static/app_manager/js/section_changer.js
  corehq/apps/app_manager/static/app_manager/js/summary/models.js
  corehq/apps/app_manager/static/app_manager/js/supported_languages.js
  corehq/apps/app_manager/templates/app_manager/managed_app.html
  corehq/apps/app_manager/templates/app_manager/partials/toggle_diff_modal.html
Labels: QA Passed, product/invisible

#29473 Escape html in multimedia
  corehq/apps/hqmedia/templates/hqmedia/uploader/details_multi.html
  corehq/apps/hqmedia/templates/hqmedia/uploader/errors.html
  corehq/apps/hqmedia/templates/hqmedia/uploader/preview_audio_single.html
  corehq/apps/hqmedia/templates/hqmedia/uploader/preview_html_single.html
  corehq/apps/hqmedia/templates/hqmedia/uploader/preview_image_single.html
  corehq/apps/hqmedia/templates/hqmedia/uploader/preview_video_single.html
  corehq/apps/hqmedia/templates/hqmedia/uploader/queue_multi.html
  corehq/apps/hqmedia/templates/hqmedia/uploader/queue_single.html
  corehq/apps/hqmedia/templates/hqmedia/uploader/status_multi.html
Labels: QA Passed, product/invisible

#29472 Escape templates in datainterfaces
  corehq/apps/data_interfaces/static/data_interfaces/js/find_by_id.js
  corehq/apps/data_interfaces/templates/data_interfaces/explore_case_data.html
  corehq/apps/data_interfaces/templates/data_interfaces/manage_case_groups.html
Labels: QA Passed, product/invisible

#29532 be more explict with attr reference
  corehq/apps/api/resources/v0_4.py
Labels: product/invisible

#29474 Escape html in hqwebapp
  corehq/apps/hqwebapp/static/hqwebapp/js/components/pagination.js
  corehq/apps/hqwebapp/static/hqwebapp/js/inactivity.js
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-key-val-mapping.js
Labels: QA Passed, Risk: Medium, product/invisible

#29471 Escape html in Cloudcare
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/templates/formplayer/case_detail.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/grid_view.html
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
  corehq/apps/cloudcare/templates/formplayer/pagination.html
  corehq/apps/cloudcare/templates/formplayer/progress.html
  corehq/apps/cloudcare/templates/formplayer/query_view.html
  corehq/apps/cloudcare/templates/formplayer/settings_view.html
  corehq/apps/cloudcare/templates/formplayer/users.html
Labels: QA Passed, Risk: Medium, product/invisible

#29512 Removed icds-ucr from testsettings
  testsettings.py
Labels: product/invisible

#29540 Fix data dictionary upload
  corehq/apps/data_dictionary/views.py
Labels: product/feature-flag

#29510 Removed all code regarding logging in as a different superuser
  corehq/apps/hqadmin/forms.py
  corehq/apps/hqadmin/tests/test_authenticate_as.py
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views/__init__.py
  corehq/apps/hqadmin/views/users.py
  corehq/tabs/tabclasses.py
Labels: product/admin

#29542 add celery task name to couch logs
  corehq/util/log.py
  settings.py
Labels: product/invisible

#29522 Add fhir view tests
  corehq/apps/domain/shortcuts.py
  corehq/motech/fhir/tests/test_api_endpoints.py
  corehq/motech/fhir/tests/test_fhir_views.py
  corehq/motech/fhir/tests/utils.py
Labels: product/feature-flag, product/invisible

#29506 markdown in help modal
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: Risk: Medium, product/all-users-all-environments

#29544 Properly escape phone numbers for SMS gateways
  corehq/apps/sms/templates/sms/add_gateway.html
Labels: product/invisible

#29482 add location fixtures to case restore
  corehq/apps/case_migrations/tests/test_restore.py
  corehq/apps/case_migrations/views.py
  corehq/apps/locations/fixtures.py
  corehq/apps/locations/tests/test_location_fixtures.py
  corehq/toggles.py
  testsettings.py
Labels: Open for review: do not merge, product/custom, product/feature-flag

#29535 Added accessibility documentation in style guide
  corehq/apps/styleguide/templates/styleguide/_includes/atoms/accessibility.html
Labels: product/invisible

#29543 [SSO] refactor activate_new_user method
  corehq/apps/registration/utils.py
  corehq/apps/registration/views.py
  corehq/apps/users/views/__init__.py
Labels: Risk: High, product/invisible

#29488 Ce/multidropdown webapps
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: Risk: Medium, product/all-users-all-environments

#29547 change 'None' columns to display as empty
  corehq/apps/userreports/reports/view.py
Labels: product/invisible

#29549 Updated case search button label
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
Labels: product/feature-flag

#29528 Update pip tools
  requirements/dev-requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
Labels: dependencies, product/invisible

#29529 Update django version
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies, product/invisible

#29530 properly generate parent ID reference in DET schemas for single-parent case types
  corehq/apps/export/det/schema_generator.py
  corehq/apps/export/models/new.py
  corehq/apps/export/tests/data/det/case_export_instance.json
  corehq/apps/export/tests/test_det_schema_generation.py
Labels: product/feature-flag

#29418 refactor for "portable tags"
  corehq/apps/domain/models.py
  corehq/apps/hqwebapp/templatetags/proptable_tags.py
  corehq/apps/hqwebapp/tests/test_proptable_tags.py
  corehq/apps/reports/views.py
  corehq/ex-submodules/casexml/apps/case/views.py
  custom/_legacy/pact/models.py
Labels: QA Passed, product/invisible

#29539 add sentry breadcrumb for metric timings
  corehq/util/metrics/__init__.py
Labels: product/invisible

#29432 consolidate doc lookup
  corehq/apps/hqadmin/views/__init__.py
  corehq/apps/hqadmin/views/data.py
  corehq/apps/hqwebapp/doc_info.py
  corehq/apps/hqwebapp/doc_lookup.py
  corehq/apps/hqwebapp/tests/test_doc_info.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/reports/standard/sms.py
  corehq/blobs/management/commands/blob_storage_report.py
Labels: QA Passed, product/invisible

#29550 It's going to be "usercase" not "user case"
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/app_manager/app_schemas/tests/test_schema.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/suite_xml/sections/menus.py
  corehq/apps/app_manager/tasks.py
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/form_filter.html
  corehq/apps/app_manager/tests/test_case_list_form.py
  corehq/apps/app_manager/tests/test_suite_form_filter_errors.py
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/callcenter/sync_usercase.py
  corehq/apps/callcenter/tasks.py
  corehq/apps/callcenter/tests/test_indicators.py
  corehq/apps/callcenter/tests/test_location_owners.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/couch_sql_migration/tests/test_diffs.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/hqcase/tests/test_explode_cases.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/retire.py
  corehq/apps/users/tests/test_signals.py
  corehq/apps/users/tests/util.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/tests/test_recipients.py
  corehq/privileges.py
  custom/covid/rules/custom_criteria.py
  custom/covid/tests/test_custom_rules.py
  custom/covid/tests/test_management_commands.py
Labels: product/invisible

#29548 add s3 blobdb for tests
  dev_settings.py
Labels: product/invisible

#29554 safer timer name
  corehq/util/metrics/__init__.py
Labels: product/invisible

#29556 A few more usercase renames
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/exceptions.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/sections/menus.py
  corehq/apps/app_manager/tests/test_child_module.py
  corehq/apps/app_manager/tests/test_suite_regex.py
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/xpath.py
  corehq/apps/callcenter/tests/test_utils.py
Labels: product/invisible

#29545 [SSO] refactor request_new_domain method
  corehq/apps/registration/utils.py
  corehq/apps/registration/views.py
Labels: Risk: High, product/invisible

#29559 Add warning to toggle
  corehq/toggles.py
Labels: product/invisible

#29565 Fixed an issue with ipv6 repeater addresses
  corehq/util/urlsanitize/ip_resolver.py
  corehq/util/urlsanitize/test/test_ip_resolver.py
  corehq/util/urlsanitize/test/test_urlsanitize.py
  corehq/util/urlsanitize/urlsanitize.py
Labels: product/invisible

#29562 Updated docs
  docs/couch_to_sql_models.rst
Labels: product/invisible

#29561 Ethiopian date widget UAT fixes
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: Risk: Medium, product/invisible

#29568 Added @skip_on_fresh_install to couch to sql django migrations
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
Labels: product/invisible

#29569 Drop old couch to sql commands
  corehq/apps/api/management/commands/populate_apiuser.py
  corehq/apps/api/migrations/0003_populate_apiuser.py
  corehq/apps/app_manager/management/commands/populate_sql_global_app_config.py
  corehq/apps/app_manager/migrations/0010_sqlglobalappconfig.py
  corehq/apps/cloudcare/management/commands/populate_application_access.py
  corehq/apps/cloudcare/migrations/0002_sqlapplicationaccess.py
  corehq/apps/consumption/management/commands/populate_defaultconsumption.py
  corehq/apps/consumption/migrations/0002_populate_sqldefaultconsumption.py
  corehq/apps/hqadmin/management/commands/populate_sql_hq_deploy.py
  corehq/apps/hqadmin/migrations/0013_populate_sqlhqdeploy.py
  corehq/apps/registration/management/commands/populate_sql_registration_request.py
  corehq/apps/registration/migrations/0003_populate_sqlregistrationrequest.py
  corehq/apps/translations/management/commands/populate_smstranslations.py
  corehq/apps/translations/migrations/0007_populate_smstranslations.py
  corehq/apps/users/management/commands/populate_usersinvitation.py
  corehq/apps/users/migrations/0010_populate_usersinvitation.py
  corehq/motech/dhis2/management/commands/populate_sql_dhis2_connection.py
  corehq/motech/dhis2/migrations/0007_populate_sqldhis2connection.py
Labels: product/invisible

#29571 Fix escaping on custom icon badges
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
Labels: Risk: Medium, product/invisible

#29566 more handling of messaging errors
  corehq/apps/sms/api.py
  corehq/apps/sms/models.py
  corehq/apps/smsforms/tasks.py
  corehq/messaging/smsbackends/twilio/models.py
Labels: product/all-users-all-environments

#29573 management command to test motech connections
  corehq/motech/management/__init__.py
  corehq/motech/management/commands/__init__.py
  corehq/motech/management/commands/ping_motech_connections.py
  corehq/motech/requests.py
Labels: product/invisible

#29572 Kill dead templates
  corehq/apps/products/templates/products/manage/products.html
  corehq/apps/programs/templates/programs/manage/program.html
  corehq/apps/users/templates/users/mobile/partials/base_users_table.html
  corehq/apps/users/templates/users/mobile/partials/pagination.html
Labels: product/invisible

#29575 add 'send_email' command
  corehq/apps/hqadmin/management/commands/mail_admins.py
  corehq/apps/hqadmin/management/commands/send_email.py
Labels: product/invisible

#29574 add enabled toggles and previews to session details response
  corehq/apps/hqwebapp/session_details_endpoint/tests.py
  corehq/apps/hqwebapp/session_details_endpoint/views.py
  corehq/feature_previews.py
  corehq/toggles.py
Labels: product/invisible

#29579 Include only locations in the domain
  corehq/apps/case_migrations/tests/test_restore.py
  corehq/apps/case_migrations/views.py
Labels: product/custom, product/feature-flag

#29578 Removed ICDS view_utils
  corehq/apps/data_interfaces/dispatcher.py
  corehq/apps/ota/views.py
  corehq/apps/reports/filters/fixtures.py
  corehq/apps/reports/generic.py
  corehq/apps/reports/views.py
  corehq/apps/users/forms.py
  corehq/tabs/tabclasses.py
  corehq/toggles.py
  custom/icds_core/view_utils.py
Labels: product/invisible

#29564 [SSO] refactor process for accepting an invitation and joining domain
  corehq/apps/domain/views/base.py
  corehq/apps/hqwebapp/utils/__init__.py
  corehq/apps/users/models.py
  corehq/apps/users/views/__init__.py
Labels: product/invisible

#29466 put multidomain user upload behind flag
  corehq/apps/user_importer/importer.py
  corehq/apps/users/views/mobile/users.py
Labels: Risk: Medium, product/feature-flag

#29577 Fixed minor bug in form validation
  corehq/apps/app_manager/helpers/validators.py
Labels: product/all-users-all-environments

#29435 UCR based dropdowns in case-search screen
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
  corehq/apps/app_manager/views/modules.py
  corehq/apps/fixtures/fixturegenerators.py
Labels: QA Passed, Risk: Medium, product/custom

#29588 mark case owner as safe
  corehq/apps/reports/standard/cases/data_sources.py
Labels: product/all-users-all-environments

#29592 dont' auto-convert dates in ReportConfiguration
  corehq/apps/userreports/models.py
  corehq/apps/userreports/tests/test_report_config.py
Labels: product/invisible

#29347 Upgrade to select2 4.1.0 release candidate
  corehq/apps/locations/static/locations/js/search.js
  package.json
  yarn.lock
Labels: QA Passed, Risk: Medium, dependencies, product/all-users-all-environments

#29570 Switch livequery to a domain setting and turn it on for all new domains
  corehq/apps/app_manager/migrations/0006_multi_master_linked_apps.py
  corehq/apps/app_manager/migrations/0008_remove_uses_master_app_form_ids.py
  corehq/apps/domain/migrations/0008_use_livequery.py
  corehq/apps/domain/models.py
  corehq/apps/domain/templates/domain/admin/flags_and_privileges.html
  corehq/apps/domain/views/internal.py
  corehq/apps/reports/migrations/0003_multiselect_report_filters_are_lists.py
  corehq/ex-submodules/casexml/apps/case/xform.py
  corehq/ex-submodules/casexml/apps/phone/cleanliness.py
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/toggles.py
Labels: Risk: Medium, product/invisible, reindex/migration

#29207 [enterprise] Refactor get_account_or_404 due to authorization ambiguity
  corehq/apps/accounting/utils/account.py
  corehq/apps/accounting/utils/subscription.py
  corehq/apps/domain/views/accounting.py
  corehq/apps/enterprise/decorators.py
  corehq/apps/enterprise/views.py
Labels: QA Passed, product/admin

#29594 Fixed an error with deleting repeaters
  corehq/motech/views.py
Labels: product/invisible

#29272 get_role_name returns name 'Admin' instead of the role_qualified_id 'admin'
  corehq/apps/users/models.py
Labels: QA Passed, product/all-users-all-environments

#29597 Assign sorting to correct field in case detail screen for detail tabs with nodesets
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/suite_xml/generator.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/tests/test_suite.py
  corehq/apps/app_manager/util.py
Labels: product/invisible

#29595 Removed lingering linked app whitelist code
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/settings/linked_whitelist.js
  corehq/apps/app_manager/templates/app_manager/app_view_settings.html
  corehq/apps/app_manager/templates/app_manager/partials/settings/app_settings.html
  corehq/apps/app_manager/tests/data/suite/app_case_detail_instances.json
  corehq/apps/app_manager/tests/data/suite/app_print_detail.json
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/export/tests/data/app_with_subcases.json
  corehq/apps/linked_domain/tests/test_linked_apps.py
Labels: product/invisible

#29576 move deploy notifications to commcare-cloud
  corehq/apps/hqadmin/management/commands/record_deploy_success.py
  corehq/apps/hqadmin/management/utils.py
Labels: product/invisible

#29596 update wording for overwrite menu
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_actions.html
Labels: product/all-users-all-environments

#29585 Started extracting users.views.web
  corehq/apps/domain/decorators.py
  corehq/apps/users/urls.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/web.py
Labels: Risk: High, product/invisible

#29589 remove redundant footprint filter
  corehq/apps/app_manager/models.py
  corehq/apps/cloudcare/touchforms_api.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/smsforms/app.py
  corehq/apps/smsforms/tests/test_app.py
  corehq/messaging/scheduling/models/content.py
Labels: product/all-users-all-environments, product/invisible

#29607 Return the benchmark code
  corehq/apps/app_manager/management/commands/benchmark_build_times.py
Labels: product/invisible

#29606 Get flattened data nodes once for each form
  corehq/apps/app_manager/xform.py
Labels: product/invisible

#29605 Add progress indication to blob importer
  corehq/blobs/management/commands/run_blob_import.py
Labels: product/invisible

#29608 Updates to couch to sql docs and code generation
  corehq/apps/cleanup/management/commands/evaluate_couch_model_for_sql.py
  docs/couch_to_sql_models.rst
Labels: product/invisible

#29513 Show properties from related cases in case search results
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/tests/data/suite/remote_request.xml
  corehq/apps/app_manager/tests/data/suite/remote_request_custom_detail.xml
  corehq/apps/app_manager/tests/data/suite/search_command_detail.xml
  corehq/apps/app_manager/tests/data/suite/search_config_blacklisted_owners.xml
  corehq/apps/app_manager/tests/data/suite/search_config_default_only.xml
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/ota/urls.py
  corehq/apps/ota/views.py
  corehq/util/test_utils.py
Labels: QA Passed, product/feature-flag

#29583 Removed ICDS translation logic
  corehq/apps/translations/app_translations/upload_module.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: product/invisible

#29604 fix arguments
  corehq/apps/case_migrations/tests/test_restore.py
  corehq/apps/case_migrations/views.py
Labels: product/custom, product/feature-flag

#29360 Web Apps accessibility improvements - make apps and menus keyboard navigable
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/templates/formplayer/grid_view.html
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
  corehq/apps/cloudcare/templates/formplayer/session_list.html
Labels: QA Passed, Risk: Medium, product/all-users-all-environments

#29611 Time the set_form_versions method
  corehq/apps/app_manager/models.py
Labels: product/invisible

#29598 Add setting for asterisk on required questions in a form
  corehq/apps/app_manager/static/app_manager/json/commcare-profile-settings.yaml
  corehq/apps/app_manager/static/app_manager/json/commcare-settings-layout.yaml
  corehq/apps/app_manager/static_strings.py
Labels: product/all-users-all-environments

#29417 Move case-search addons to USH FF
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/sections/remote_requests.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/views.py
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/toggles.py
Labels: QA Passed, Risk: Medium, product/all-users-all-environments

#29493 Fix adding query parameters twice for configurable reports
  corehq/apps/saved_reports/models.py
Labels: product/invisible

#29612 [SSO] Create New User on SSO Sign In if no user exists
  corehq/apps/sso/backends.py
  corehq/apps/sso/tests/generator.py
  corehq/apps/sso/tests/test_backends.py
  corehq/apps/sso/urls.py
  corehq/apps/sso/utils/session_helpers.py
  corehq/apps/sso/views/saml.py
  corehq/const.py
Labels: product/feature-flag, product/invisible

#29613 [UI Improvement] Use a Tab view in "Manage My Settings > My Information" for Web Users
  corehq/apps/settings/templates/settings/edit_my_account.html
  corehq/apps/users/templates/users/partials/manage_my_numbers.html
Labels: product/all-users-all-environments

#29614 Removed nodeset sorting from short detail overwrite
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_module_overwrite.html
  corehq/apps/app_manager/tests/test_modules.py
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#29615 send blank messages and handle error responses
  corehq/apps/sms/api.py
  corehq/apps/sms/models.py
  corehq/apps/smsforms/tasks.py
  corehq/messaging/smsbackends/twilio/models.py
Labels: product/invisible

#29617 Update flagspecs_v2020.yaml
  custom/abt/reports/flagspecs_v2020.yaml
Labels: product/invisible

#29610 Refactor method to build view models for pulling content
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/tests/test_view_helpers.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#29619 [SSO] Updates to My Account Settings for SSO logged in users
  corehq/apps/domain/templates/login_and_password/two_factor/profile/profile.html
  corehq/apps/settings/templates/settings/change_my_password.html
  corehq/apps/settings/views.py
  corehq/apps/users/forms.py
Labels: product/feature-flag

#29536 Index deletion
  corehq/apps/couch_sql_migration/diff.py
  corehq/apps/reports/view_helpers.py
  corehq/apps/users/tests/retire.py
  corehq/ex-submodules/casexml/apps/case/sharedmodels.py
  corehq/ex-submodules/casexml/apps/case/tests/test_indexes.py
  corehq/ex-submodules/casexml/apps/case/xform.py
  corehq/form_processor/backends/sql/update_strategy.py
  corehq/form_processor/models.py
  corehq/form_processor/tests/test_basics.py
Labels: Risk: High, product/invisible

#29587 Repeater URL Cleanup
  corehq/apps/export/tests/test_incremental.py
  corehq/motech/forms.py
  corehq/motech/repeaters/models.py
  corehq/motech/requests.py
  corehq/motech/tests/test_forms.py
  corehq/motech/tests/test_requests.py
  corehq/motech/views.py
  corehq/util/urlsanitize/ip_resolver.py
  corehq/util/urlsanitize/test/test_ip_resolver.py
  corehq/util/urlsanitize/test/test_urlsanitize.py
  corehq/util/urlvalidate/__init__.py
  corehq/util/urlvalidate/ip_resolver.py
  corehq/util/urlvalidate/test/__init__.py
  corehq/util/urlvalidate/test/mockipinfo.py
  corehq/util/urlvalidate/test/test_ip_resolver.py
  corehq/util/urlvalidate/test/test_urlsanitize.py
  corehq/util/urlvalidate/urlvalidate.py
Labels: product/invisible
