Repository dimagi/commcare-hq, pull requests merged in 2022-12, with the labels that each got.

#32369 [USH-2607] shadow module form links
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/test_build_errors.py
  corehq/apps/app_manager/tests/test_form_workflow.py
  corehq/apps/app_manager/tests/test_form_workflow_multiple_case_types.py
  corehq/apps/app_manager/tests/test_suite_inline_search.py
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/app_manager/views/forms.py
Labels: product/invisible

#32382 update extension point docs to mention settings
  corehq/extensions/__init__.py
Labels: product/invisible

#32383 Bump last known good DHIS2 version
  corehq/motech/dhis2/const.py
  corehq/motech/dhis2/repeaters.py
  corehq/motech/dhis2/tests/test_repeaters.py
Labels: product/invisible

#32372 Revert "register index and add adapter when using custom pillow"
  corehq/apps/es/transient_util.py
  corehq/pillows/case_search.py
Labels: product/invisible

#32388 Render value in correct place for textarea element
  corehq/apps/app_manager/templatetags/xforms_extras.py
Labels: product/invisible

#32356 Increase Visibility into UCR Rebuilds
  corehq/apps/userreports/models.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/templates/userreports/edit_data_source.html
  corehq/apps/userreports/templates/userreports/partials/build_in_progress_warning.html
  corehq/apps/userreports/views.py
  corehq/toggles/__init__.py
Labels: product/all-users-all-environments

#32378 do not throttle admin apis
  corehq/apps/api/accounting.py
  corehq/apps/api/domain_metadata.py
  corehq/apps/api/resources/meta.py
  corehq/apps/api/resources/v0_5.py
Labels: Risk: High

#32358 Change repeater name property to something else
  corehq/apps/reports/filters/select.py
  corehq/motech/management/commands/create_repeat_records.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/templates/repeaters/partials/repeater_row.html
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/views/repeaters.py
Labels: product/invisible

#32394 Fix Broken Repeater Edit Page views
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/views/repeaters.py
Labels: product/all-users-all-environments

#32395 Revert "Revert "add links to generic inbound expressions in list and edit view""
  corehq/apps/data_interfaces/urls.py
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/field_with_addons.html
  corehq/apps/userreports/views.py
  corehq/motech/generic_inbound/forms.py
  corehq/motech/generic_inbound/static/generic_inbound/js/api_edit.js
  corehq/motech/generic_inbound/static/generic_inbound/js/api_list.js
  corehq/motech/generic_inbound/static/generic_inbound/js/manage_links.js
  corehq/motech/generic_inbound/templates/generic_inbound/api_edit.html
  corehq/motech/generic_inbound/templates/generic_inbound/api_list.html
Labels: product/feature-flag

#32336 Add auditing to AutomaticUpdateRule model
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/data_interfaces/deduplication.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/tests/test_auto_update_rules.py
  corehq/apps/domain/deletion.py
  corehq/messaging/tasks.py
Labels: product/invisible

#32392 SQL Lookup Tables - Part 3: Stop writing to Couch
  corehq/apps/api/tests/lookup_table_resources.py
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/fixtures/couchmodels.py
  corehq/apps/fixtures/dbaccessors.py
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/fixtures/management/commands/base.py
  corehq/apps/fixtures/management/commands/populate_lookuptablerowowners.py
  corehq/apps/fixtures/management/commands/populate_lookuptablerows.py
  corehq/apps/fixtures/management/commands/populate_lookuptables.py
  corehq/apps/fixtures/migrations/0005_sqllookuptablemodels.py
  corehq/apps/fixtures/migrations/0008_sqllookuptables.py
  corehq/apps/fixtures/models.py
  corehq/apps/fixtures/resources/v0_1.py
  corehq/apps/fixtures/tests/test_couchsqlmigration.py
  corehq/apps/fixtures/tests/test_download.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/fixtures/tests/test_location_ownership.py
  corehq/apps/fixtures/tests/test_models.py
  corehq/apps/fixtures/tests/test_upload.py
  corehq/apps/fixtures/tests/test_views.py
  corehq/apps/fixtures/upload/run_upload.py
  corehq/apps/fixtures/utils.py
  corehq/apps/fixtures/views.py
  corehq/apps/hqadmin/tests/test_raw_doc.py
  corehq/apps/linked_domain/tests/test_update_fixtures.py
  corehq/apps/linked_domain/tests/test_view_helpers.py
  corehq/apps/linked_domain/updates.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_fixtures.py
  corehq/ex-submodules/dimagi/utils/couch/bulk.py
  custom/inddex/example_data/data.py
  custom/inddex/fixtures.py
  custom/ucla/tests.py
  docs/couchdb.rst
  migrations.lock
Labels: reindex/migration, product/invisible, Risk: High, Risk: Medium

#32381 Revert "Revert "[USH-2607] shadow module form links""
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/forms/form_workflow.js
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/test_build_errors.py
  corehq/apps/app_manager/tests/test_form_workflow.py
  corehq/apps/app_manager/tests/test_form_workflow_multiple_case_types.py
  corehq/apps/app_manager/tests/test_suite_inline_search.py
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/app_manager/views/forms.py
Labels: QA Passed

#32389 Cs/sc 2360 auto update rule overwrites case property
  corehq/apps/hqcase/utils.py
  corehq/ex-submodules/casexml/apps/case/mock/case_block.py
  corehq/ex-submodules/casexml/apps/case/tests/test_case_block.py
  corehq/toggles/__init__.py
Labels: QA Passed, product/feature-flag

#32399 Fix app builds with null case search title labels
  corehq/apps/app_manager/models.py
Labels: product/feature-flag

#32405 Updated web apps docs
  docs/web_apps.rst
Labels: product/invisible

#32397 Silenced an error with unexpected TurnIO formats
  corehq/messaging/smsbackends/turn/tests/test_views.py
  corehq/messaging/smsbackends/turn/views.py
Labels: product/invisible

#32384 [USH-2682] Allow form linking from multi-select forms
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
  corehq/apps/app_manager/views/forms.py
Labels: QA Passed, product/feature-flag

#32409 Return error when amount due in an invoice is negative
  corehq/apps/domain/views/accounting.py
Labels: product/invisible

#32408 Block users from upgrading to Enterprise for free
  corehq/apps/domain/views/accounting.py
Labels: product/invisible

#32407 Block HTML from rendering when added to end of date filter value in url
  corehq/ex-submodules/dimagi/utils/decorators/datespan.py
Labels: product/invisible

#32370 ES reindex multiplexed index command
  corehq/apps/es/client.py
  corehq/apps/es/exceptions.py
  corehq/apps/es/management/commands/elastic_sync_multiplexed.py
  corehq/apps/es/tests/test_client.py
  corehq/apps/es/tests/test_elastic_sync_multiplexed_command.py
  corehq/apps/es/utils.py
  corehq/apps/hqcase/management/commands/reindex_es_native.py
Labels: product/invisible

#32398 Escape closing script tags without a space
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
Labels: product/invisible

#32396 Remove elastic index registry logic
  corehq/apps/cleanup/management/commands/delete_es_docs_for_domain.py
  corehq/apps/es/__init__.py
  corehq/apps/es/es_query.py
  corehq/apps/es/exceptions.py
  corehq/apps/es/management/commands/elastic_sync_multiplexed.py
  corehq/apps/es/registry.py
  corehq/apps/es/tests/test_client.py
  corehq/apps/es/tests/test_elastic_sync_multiplexed_command.py
  corehq/apps/es/tests/test_registry.py
  corehq/apps/es/tests/test_test_utils.py
  corehq/apps/es/tests/utils.py
  corehq/apps/es/transient_util.py
  corehq/apps/es/utils.py
  corehq/apps/hqadmin/views/data.py
  corehq/apps/hqcase/management/commands/initialize_es_indices.py
  corehq/apps/hqcase/management/commands/reindex_es_native.py
  corehq/elastic.py
  corehq/ex-submodules/pillowtop/tests/test_bulk.py
  corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py
  corehq/pillows/app_config.py
  corehq/pillows/management/commands/print_elastic_mappings.py
  corehq/pillows/mappings/tests/test_utils.py
  corehq/util/es/interface.py
  corehq/util/tests/test_django_migrations.py
  settings.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/test_app_pillow.py
Labels: product/invisible, Risk: High

#32373 Replay Generic Inbound API
  corehq/apps/users/views/__init__.py
  corehq/motech/generic_inbound/core.py
  corehq/motech/generic_inbound/migrations/0005_remove_requestlog_unused_fields.py
  corehq/motech/generic_inbound/models.py
  corehq/motech/generic_inbound/templates/generic_inbound/request_log_detail.html
  corehq/motech/generic_inbound/tests/test_api.py
  corehq/motech/generic_inbound/tests/test_api_processing.py
  corehq/motech/generic_inbound/utils.py
  corehq/motech/generic_inbound/views.py
  corehq/motech/urls.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32387 Migration for Data Dictionary Permissions
  corehq/apps/users/management/commands/add_data_dict_permissions.py
  corehq/apps/users/migrations/0048_add_data_dict_permissions.py
  corehq/apps/users/tests/test_migration_add_data_dict_permission.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32413 [USH-2725] [bug] add uniqueId to form links when preparing context for view
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/forms/form_workflow.js
  corehq/apps/app_manager/static/app_manager/spec/form_workflow_spec.js
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/app_manager/views/forms.py
Labels: product/all-users-all-environments

#32359 Add name to Repeaters model
  corehq/motech/repeaters/management/commands/populate_repeater_names.py
  corehq/motech/repeaters/migrations/00010_add_repeater_name.py
  corehq/motech/repeaters/models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#32414 Check if xform is deleted before accessing
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
Labels: product/invisible

#32419 Remove unused ICDS Elasticsearch settings
  corehq/apps/es/client.py
  corehq/apps/es/tests/test_client.py
  corehq/apps/reports/standard/monitoring.py
  corehq/pillows/case.py
  corehq/pillows/mappings/xform_mapping.py
  settings.py
Labels: product/invisible

#32366 Data Dictionary View Mode
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/views.py
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-key-val-list.js
  corehq/apps/users/management/commands/add_data_dict_permissions.py
  corehq/apps/users/migrations/0048_add_data_dict_permissions.py
  corehq/apps/users/tests/test_migration_add_data_dict_permission.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32421 Improvement: Join connection_settings when fetching repeaters in management command
  corehq/motech/repeaters/management/commands/populate_repeater_names.py
Labels: product/all-users-all-environments, product/invisible

#32417 Missed a variable rename
  corehq/apps/hqmedia/models.py
Labels: product/invisible

#32345 Data Dictionary Permission Restriction
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/tests/test_view.py
  corehq/apps/data_dictionary/views.py
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-key-val-list.js
  corehq/apps/users/decorators.py
  corehq/apps/users/management/commands/add_data_dict_permissions.py
  corehq/apps/users/migrations/0049_add_data_dict_permissions.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/templates/users/roles_and_permissions.html
  corehq/apps/users/tests/test_migration_add_data_dict_permission.py
  corehq/apps/users/tests/test_models_role.py
  corehq/tabs/tabclasses.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32422 Set pg_isready user and password
  docker/hq-compose.yml
Labels: product/invisible

#32426 Update terminology
  corehq/apps/linked_domain/README.md
  corehq/apps/linked_domain/management/commands/link_app_to_remote.py
Labels: product/invisible

#32428 Fix form settings page for forms with broken links
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/app_manager/views/forms.py
Labels: product/feature-flag

#32361 Application Release logs release actions for logs
  corehq/apps/app_manager/migrations/0024_applicationreleaselog_info.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/releases/app_view_release_manager.js
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/templates/app_manager/partials/releases/app_release_logs.html
  corehq/apps/app_manager/views/releases.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32423 Include form name in success message on formplayer
  corehq/form_processor/submission_post.py
Labels: Risk: High

#32424 Hide "Incomplete Forms" Icon
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/views.js
  corehq/apps/cloudcare/templates/formplayer/grid_view.html
Labels: product/all-users-all-environments, Risk: Medium

#32441 Added properties check to incomplete forms setting logic
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/controller.js
Labels: product/all-users-all-environments, Risk: Medium

#32444 Update components.ko.js to return a value
  corehq/apps/hqwebapp/static/hqwebapp/js/components.ko.js
Labels: product/invisible
