Repository dimagi/commcare-hq, pull requests merged in 2022-11, with the labels that each got.

#32305 Remove custom Kafka partition code
  corehq/apps/change_feed/partitioners.py
  corehq/apps/change_feed/producer.py
  settings.py
Labels: product/invisible

#32271 Remove leftover Couch References for Auditcare
  corehq/apps/auditcare/_design/filters/auditdocs.js
  corehq/apps/auditcare/_design/util/shared_funcs.js
  corehq/apps/auditcare/_design/views/all_events/map.js
  corehq/apps/auditcare/_design/views/by_date/map.js
  corehq/apps/auditcare/_design/views/by_date_access_events/map.js
  corehq/apps/auditcare/_design/views/by_date_events/map.js
  corehq/apps/auditcare/_design/views/login_events/map.js
  corehq/apps/auditcare/_design/views/model_actions_by_id/map.js
  corehq/apps/auditcare/_design/views/model_actions_by_id/reduce.js
  corehq/apps/auditcare/_design/views/urlpath_by_user_date/map.js
  corehq/apps/auditcare/_design/views/urlpath_by_user_date/reduce.js
  corehq/apps/auditcare/management/commands/gdpr_scrub_user_auditcare.py
  corehq/apps/auditcare/tests/test_gdpr_scrub_user_auditcare.py
  corehq/apps/hqadmin/corrupt_couch.py
  settings.py
Labels: reindex/migration, product/invisible

#32307 [SAAS-14102] addf field to messaging sub-event model to record date of last activity
  corehq/apps/api/resources/messaging_event/filters.py
  corehq/apps/api/resources/messaging_event/serializers.py
  corehq/apps/api/resources/messaging_event/utils.py
  corehq/apps/api/resources/messaging_event/view.py
  corehq/apps/sms/api.py
  corehq/apps/sms/handlers/form_session.py
  corehq/apps/sms/migrations/0052_messagingsubevent_date_last_activity.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tasks.py
  corehq/apps/sms/tests/inbound_handlers.py
  corehq/apps/smsforms/app.py
  corehq/apps/smsforms/models.py
  corehq/apps/smsforms/tasks.py
  corehq/apps/smsforms/util.py
  corehq/messaging/scheduling/models/content.py
  migrations.lock
Labels: reindex/migration, product/invisible, Risk: High

#32295 update mac dev setup instructions to include the new ES plugin
  DEV_SETUP_MAC.md
Labels: product/invisible

#32310 Create update button on embedded tableau report configuration page
  corehq/apps/reports/forms.py
  corehq/apps/reports/templates/reports/tableau_visualization.html
  corehq/apps/reports/views.py
Labels: product/feature-flag

#32151 "CommCareHQ" -> "CommCare HQ"
  CONTRIBUTING.rst
  corehq/apps/README.rst
  docs/caching_and_memoization.rst
  docs/documenting.rst
  docs/index.rst
  docs/js-guide/code-organization.rst
  docs/js-guide/static-files.rst
  docs/messaging/contacts.rst
  docs/messaging/definitions.rst
  docs/messaging/messaging.rst
  docs/messaging/sms_backends.rst
  docs/metrics.rst
  docs/migration_command_pattern.rst
  docs/overview/architecture.rst
  docs/testing.rst
  docs/toggles.rst
  docs/web_apps.rst
Labels: product/invisible

#32289 Add management command to get es version when index was created
  corehq/apps/es/management/commands/es_version_for_index.py
Labels: product/invisible

#32314 Revert "[SAAS-14102] addf field to messaging sub-event model to record date of last activity"
  corehq/apps/api/resources/messaging_event/filters.py
  corehq/apps/api/resources/messaging_event/serializers.py
  corehq/apps/api/resources/messaging_event/utils.py
  corehq/apps/api/resources/messaging_event/view.py
  corehq/apps/sms/api.py
  corehq/apps/sms/handlers/form_session.py
  corehq/apps/sms/migrations/0052_messagingsubevent_date_last_activity.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tasks.py
  corehq/apps/sms/tests/inbound_handlers.py
  corehq/apps/smsforms/app.py
  corehq/apps/smsforms/models.py
  corehq/apps/smsforms/tasks.py
  corehq/apps/smsforms/util.py
  corehq/messaging/scheduling/models/content.py
  migrations.lock
Labels: reindex/migration, Risk: High

#32315 Revert "Revert "[SAAS-14102] addf field to messaging sub-event model to record date of last activity""
  corehq/apps/api/resources/messaging_event/filters.py
  corehq/apps/api/resources/messaging_event/serializers.py
  corehq/apps/api/resources/messaging_event/utils.py
  corehq/apps/api/resources/messaging_event/view.py
  corehq/apps/sms/api.py
  corehq/apps/sms/handlers/form_session.py
  corehq/apps/sms/migrations/0052_messagingsubevent_date_last_activity.py
  corehq/apps/sms/migrations/0053_alter_messagingsubevent_date_last_activity.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tasks.py
  corehq/apps/sms/tests/inbound_handlers.py
  corehq/apps/smsforms/app.py
  corehq/apps/smsforms/models.py
  corehq/apps/smsforms/tasks.py
  corehq/apps/smsforms/util.py
  corehq/messaging/scheduling/models/content.py
  migrations.lock
Labels: reindex/migration, product/invisible, Risk: High

#32298 Fix: Shadow module to get its persist context and inline details from its own module during build
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/test_suite_shadow_module.py
Labels: QA Passed, product/feature-flag

#32311 [SAAS-14102] backfill subevent "date_last_activity"
  corehq/apps/domain_migration_flags/api.py
  corehq/apps/sms/management/commands/backfill_sms_subevent_date.py
  corehq/apps/sms/tests/test_backfill_subevent.py
Labels: product/invisible

#32317 Optimize EnterpriseFormReport.total_for_domain()
  corehq/apps/enterprise/enterprise.py
Labels: product/invisible

#31285 Removed safe from SMS
  corehq/apps/sms/templates/sms/backend_map.html
Labels: product/invisible

#31286 Removed safe usage from users
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/edit_web_user.html
  corehq/apps/users/templates/users/partials/basic_info_form.html
Labels: product/invisible

#31287 Removed safe usages from HQAdmin
  corehq/apps/hqadmin/tasks.py
  corehq/apps/hqadmin/templates/hqadmin/email/mass_email_base.html
  corehq/apps/hqadmin/templates/hqadmin/email/mass_email_base.txt
  corehq/apps/hqadmin/templates/hqadmin/system_info.html
Labels: product/invisible

#31288 remove safe from domain templates
  corehq/apps/domain/templates/domain/admin/feature_previews.html
  corehq/apps/domain/templates/domain/partials/report_list.html
  corehq/apps/domain/templates/domain/select_plan.html
  corehq/apps/domain/views/accounting.py
Labels: product/invisible

#31289 Remove safe filter from report templates
  corehq/apps/reports/datatables/__init__.py
  corehq/apps/reports/templates/reports/async/filters.html
  corehq/apps/reports/templates/reports/filters/single_option.html
  corehq/apps/reports/templates/reports/report_email.html
  corehq/apps/reports/templates/reports/report_email_content.html
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/apps/reports/templates/reports/tabular.html
  corehq/apps/reports/tests/test_datatables_columns.py
  corehq/apps/reports/views.py
  corehq/apps/reports_core/templates/reports_core/base_template_new.html
  corehq/apps/saved_reports/models.py
Labels: product/invisible

#31290 Removed safe filter from feature flags
  corehq/apps/toggle_ui/templates/toggle/edit_flag.html
Labels: product/invisible

#31292 Removed safe filter from accounting
  corehq/apps/accounting/templates/accounting/partials/confirm_plan_summary.html
  corehq/apps/accounting/templates/accounting/partials/invoice_table.html
Labels: product/invisible

#31293 Remove safe filter from custom data fields
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/custom_data_fields/templates/custom_data_fields/custom_data_fields.html
Labels: product/invisible, Risk: Medium

#31294 remove safe filter from openmrs
  corehq/motech/openmrs/forms.py
  corehq/motech/openmrs/templates/openmrs/partials/openmrs_importer_template.html
Labels: product/invisible

#31295 Remove safe filter from inddex
  corehq/apps/reports/datatables/__init__.py
  corehq/apps/reports/tests/test_datatables.py
  custom/inddex/templates/inddex/partials/report_table.html
Labels: product/invisible

#31296 removed safe filter from casexml
  corehq/ex-submodules/casexml/apps/case/templates/case/partials/case_hierarchy.html
Labels: product/invisible

#31297 Removed safe filter from app manager templates
  corehq/apps/app_manager/templates/app_manager/app_diff.html
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/templates/app_manager/managed_app.html
  corehq/apps/app_manager/templates/app_manager/module_view.html
  corehq/apps/app_manager/templates/app_manager/module_view_report.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_breadcrumbs.html
  corehq/apps/app_manager/views/releases.py
Labels: product/invisible

#31298 Removed safe filter from crispy text field
  corehq/apps/accounting/forms.py
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/field.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/field/field_with_text.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/field/hidden_with_errors.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/field_with_help_bubble.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/form_actions.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/hidden_with_errors.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/multi_inline_field.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/radioselect.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/text_field.html
Labels: product/invisible

#30960 Removed safe from accept_invite
  corehq/apps/users/templates/users/accept_invite.html
  corehq/apps/users/views/web.py
Labels: product/invisible

#31085 Removed the safe filter from userreports templates
  corehq/apps/hqwebapp/tests/utils/test_html.py
  corehq/apps/hqwebapp/utils/html.py
  corehq/apps/userreports/templates/userreports/report_error.html
  corehq/apps/userreports/templates/userreports/summary_data_source.html
  corehq/apps/userreports/tests/test_views.py
  corehq/apps/userreports/views.py
Labels: product/invisible

#31096 remove careplan report templates
  corehq/apps/reports/templates/reports/careplan/nopatient.html
  corehq/apps/reports/templates/reports/careplan/patient_careplan.html
Labels: product/invisible

#31284 remove safe from conditional alerts
  corehq/messaging/scheduling/templates/scheduling/conditional_alert.html
  corehq/messaging/scheduling/views.py
Labels: product/invisible

#31291 Removed safe filter from fixtures
  corehq/apps/fixtures/templates/fixtures/fixtures_base.html
  corehq/apps/fixtures/templates/fixtures/view_table.html
Labels: product/invisible, Risk: Medium

#32211 Remove paginated crud view mixin from auto update rule view
  corehq/apps/data_interfaces/static/data_interfaces/js/auto_update_rules.js
  corehq/apps/data_interfaces/static/data_interfaces/js/deduplication_rules.js
  corehq/apps/data_interfaces/templates/data_interfaces/auto_update_rules.html
  corehq/apps/data_interfaces/templates/data_interfaces/list_automatic_update_rules.html
  corehq/apps/data_interfaces/templates/data_interfaces/list_deduplication_rules.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/auto_update_rule_list.html
  corehq/apps/data_interfaces/views.py
Labels: QA Passed, product/invisible

#32265 ElasticSearch Multiplexer Adapter.
  corehq/apps/api/tests/test_es.py
  corehq/apps/es/README.rst
  corehq/apps/es/app_config.py
  corehq/apps/es/apps.py
  corehq/apps/es/case_search.py
  corehq/apps/es/cases.py
  corehq/apps/es/client.py
  corehq/apps/es/domains.py
  corehq/apps/es/forms.py
  corehq/apps/es/groups.py
  corehq/apps/es/sms.py
  corehq/apps/es/tests/test_client.py
  corehq/apps/es/tests/test_test_utils.py
  corehq/apps/es/tests/utils.py
  corehq/apps/es/transient_util.py
  corehq/apps/es/users.py
  corehq/apps/export/tests/test_export_models_new.py
  corehq/apps/hqadmin/management/commands/prune_elastic_indices.py
  corehq/apps/hqcase/api/get_bulk.py
  corehq/apps/hqcase/views.py
  corehq/elastic.py
  corehq/form_processor/submission_post.py
  corehq/pillows/case_search.py
  corehq/pillows/mappings/app_mapping.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/case_search_mapping.py
  corehq/pillows/mappings/domain_mapping.py
  corehq/pillows/mappings/group_mapping.py
  corehq/pillows/mappings/sms_mapping.py
  corehq/pillows/mappings/user_mapping.py
  corehq/pillows/mappings/xform_mapping.py
  corehq/util/es/interface.py
Labels: reindex/migration, product/invisible, Risk: High

#32290 Add checkbox to case search fields
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
  corehq/apps/app_manager/tests/data/suite/remote_request.xml
  corehq/apps/app_manager/tests/data/suite/remote_request_custom_detail.xml
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/templates/formplayer/query_view.html
Labels: QA Passed, product/feature-flag, Risk: Medium

#32326 Only check for data registry if not remote domain link
  corehq/apps/linked_domain/ucr.py
  corehq/apps/userreports/models.py
Labels: product/invisible

#32258 Add auto update rule history tab
  corehq/apps/data_interfaces/static/data_interfaces/js/auto_update_rules.js
  corehq/apps/data_interfaces/templates/data_interfaces/auto_update_rules.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/auto_update_rule_list.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/auto_update_rule_run_history.html
  corehq/apps/data_interfaces/views.py
Labels: product/invisible

#32330 Update README for `scripts/docker runserver`
  docker/README.md
  docker/README.rst
Labels: product/invisible

#32328 Catch missing parent case, and missing config
  corehq/motech/dhis2/entities_helpers.py
Labels: product/invisible

#32334 [USH-2606] backfill remaining data in subevent table
  corehq/apps/sms/management/commands/backfill_sms_subevent_date.py
  corehq/apps/sms/tests/test_backfill_subevent.py
Labels: product/invisible

#32098 Pull some models out of UNKNOWN in the domain dump test
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_dump_models.py
Labels: product/invisible

#32296 Specify custom auto-drill option on UCR location filter
  corehq/apps/reports_core/filters.py
  corehq/apps/reports_core/templates/reports_core/filters/location_async.html
  corehq/apps/userreports/tests/test_report_filters.py
Labels: QA Passed, product/feature-flag

#32333 small fixes for admin restore view
  corehq/apps/hqadmin/views/users.py
Labels: product/invisible

#32312 Changed process_reporting_metadata_staging task to lock 1 row instead of 5
  corehq/apps/users/tasks.py
Labels: product/invisible

#32297 Rc/generic inbound api basic log report
  corehq/apps/reports/tests/test_dispatcher.py
  corehq/motech/generic_inbound/reports.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#32339 [USH-2623] add domain to MessagingSubevent
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/apps/sms/management/commands/backfill_sms_subevent_date.py
  corehq/apps/sms/migrations/0054_messagingsubevent_domain.py
  corehq/apps/sms/models.py
  corehq/apps/sms/tests/data_generator.py
  corehq/apps/sms/tests/test_backfill_subevent.py
  corehq/apps/sms/tests/test_form_session_handler.py
  migrations.lock
Labels: reindex/migration, product/invisible

#32342 Point flower to github repo
  requirements/prod-requirements.in
  requirements/prod-requirements.txt
Labels: product/invisible, dependencies

#32343 docstring update (prune_old_datasources -> delete_orphaned_ucrs)
  corehq/apps/userreports/dbaccessors.py
Labels: product/invisible

#32304 Multi-select case list: force auto select xml changes
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/data/suite/multi_select_case_list/basic_remote_request.xml
  corehq/apps/app_manager/tests/test_suite_inline_search.py
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
Labels: QA Passed, product/feature-flag

#32303 Multi-select case list: force auto select app configuration
  corehq/apps/app_manager/const.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_multi_select.html
  corehq/apps/app_manager/tests/data/suite/multi_select_case_list/basic_remote_request.xml
  corehq/apps/app_manager/tests/test_suite_inline_search.py
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js
Labels: QA Passed, product/feature-flag, Risk: Medium

#32340 [USH-2623] messaging subevent domain index and usage
  corehq/apps/api/resources/messaging_event/utils.py
  corehq/apps/api/resources/messaging_event/view.py
  corehq/apps/api/tests/test_messaging_event_api.py
  corehq/apps/sms/management/commands/backfill_sms_subevent_date.py
  corehq/apps/sms/migrations/0055_messagingsubevent_index_domain_date_id.py
  corehq/apps/sms/models.py
  migrations.lock
Labels: reindex/migration, Open for review: do not merge, product/invisible, Risk: High

#32346 Rc/generic inbound api basic log report
  corehq/motech/generic_inbound/reports.py
  corehq/motech/generic_inbound/templates/generic_inbound/request_log_detail.html
  corehq/motech/urls.py
Labels: product/feature-flag

#32227 Allow users to temporarily disable API keys
  corehq/apps/api/tests/test_auth.py
  corehq/apps/hqwebapp/templates/hqwebapp/base_paginated_crud.html
  corehq/apps/settings/forms.py
  corehq/apps/settings/static/settings/js/user_api_keys.js
  corehq/apps/settings/templates/settings/user_api_keys.html
  corehq/apps/settings/views.py
  corehq/apps/users/migrations/0048_expiring_keys.py
  corehq/apps/users/models.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/all-users-all-environments, Risk: High

#32316 Add metric to track form/case submissions without associated metadata
  corehq/form_processor/submission_post.py
Labels: product/invisible, Risk: High

#32325 Added Application Release History Logs
  corehq/apps/app_manager/const.py
  corehq/apps/app_manager/migrations/0023_applicationreleaselog.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/releases/app_view_release_manager.js
  corehq/apps/app_manager/templates/app_manager/app_view_release_manager.html
  corehq/apps/app_manager/templates/app_manager/partials/releases/app_release_logs.html
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases.html
  corehq/apps/app_manager/tests/views/test_release_build.py
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32352 Bump pillow to v9.3.0
  corehq/apps/hqmedia/models.py
  corehq/apps/hqmedia/tests/test_pillow_library_usage.py
  corehq/ex-submodules/dimagi/utils/django/cached_object.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#32351 Generic inbound API tweaks
  corehq/motech/generic_inbound/core.py
  corehq/motech/generic_inbound/reports.py
  corehq/motech/generic_inbound/templates/generic_inbound/request_log_detail.html
  corehq/motech/generic_inbound/tests/test_api.py
  corehq/motech/generic_inbound/views.py
Labels: product/invisible

#32353 Bump django-field-audit to v1.2.4
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#32364 Move setting up in file
  settings.py
Labels: product/feature-flag

#32338 Case search screen subtitle/description text
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/features/mobile_ucr.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/templatetags/xforms_extras.py
  corehq/apps/app_manager/tests/app_factory.py
  corehq/apps/app_manager/tests/templatetags/test_xforms_extras.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/templates/formplayer/query_view.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/app_translations/upload_module.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: QA Passed, product/feature-flag, Risk: Medium

#32350 Execute git push in the foreground to support interactive pre-push hooks
  scripts/vellum-to-hq
Labels: product/invisible

#32360 add links to generic inbound expressions in list and edit view
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/hqwebapp/static/hqwebapp/js/initial_page_data.js
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/field_with_addons.html
  corehq/motech/generic_inbound/forms.py
  corehq/motech/generic_inbound/static/generic_inbound/js/api_edit.js
  corehq/motech/generic_inbound/static/generic_inbound/js/api_list.js
  corehq/motech/generic_inbound/static/generic_inbound/js/manage_links.js
  corehq/motech/generic_inbound/templates/generic_inbound/api_edit.html
  corehq/motech/generic_inbound/templates/generic_inbound/api_list.html
Labels: product/feature-flag

#32347 Do not set multiplexer mappings in init
  corehq/apps/es/client.py
Labels: product/invisible

#32363 [DHIS2] Check relationship existence before trying to create it
  corehq/motech/dhis2/entities_helpers.py
  corehq/motech/dhis2/tests/test_entities_helpers.py
Labels: awaiting QA, product/all-users-all-environments

#32371 Stop api filter from clearing on apply
  corehq/motech/generic_inbound/reports.py
Labels: product/feature-flag
