Repository dimagi/commcare-hq, pull requests merged in 2022-10, with the labels that each got.

#32162 Better error when food is missing from fixture
  custom/inddex/food.py
Labels: product/invisible

#32212 Update DHIS2 schema
  corehq/motech/dhis2/schema.py
  corehq/motech/dhis2/tests/data/tracked_entity_instance_1.json
Labels: product/custom, product/invisible

#31919 Updated logging configuration to fix celery logging issues
  corehq/apps/celery/__init__.py
  settings.py
Labels: product/invisible

#32238 Multi-Select: Remove selections upon form submission
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
Labels: product/feature-flag, Risk: Medium

#32241 [Marketing] Remove Schedule Once for booking demo/trial times
  corehq/apps/analytics/static/analytix/js/cta_forms.js
  corehq/apps/analytics/static/analytix/js/hubspot.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/schedule.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style-imports.less
  corehq/apps/hqwebapp/templates/hqwebapp/partials/get_demo_modals.html
  corehq/apps/registration/static/registration/js/register_new_user.js
  corehq/apps/registration/templates/registration/partials/start_trial_modal.html
Labels: product/prod-india-all-users

#32242 add pool_recycle to sqlalchemy engine
  corehq/sql_db/connections.py
Labels: product/invisible

#32244 Removed old edit forms functionality
  corehq/apps/cloudcare/static/cloudcare/js/formplayer_inline.js
  corehq/apps/cloudcare/templates/cloudcare/includes/formplayer-inline.html
  corehq/apps/cloudcare/urls.py
  corehq/apps/cloudcare/views.py
  corehq/apps/reports/exceptions.py
  corehq/apps/reports/static/reports/js/edit_submission.js
  corehq/apps/reports/templates/reports/form/edit_submission.html
  corehq/apps/reports/templates/reports/partials/data_corrections_modal.html
  corehq/apps/reports/tests/test_util.py
  corehq/apps/reports/urls.py
  corehq/apps/reports/util.py
  corehq/apps/reports/views.py
  settings.py
Labels: product/all-users-all-environments, Risk: Medium

#32248 turn off sqlalchemy connection pooling
  corehq/sql_db/connections.py
Labels: product/invisible

#32250 Revert sqlalchemy pool changes
  corehq/sql_db/connections.py
Labels: product/invisible

#32230 Add requirements.txt/M1 issues section to dev_setup_mac
  DEV_SETUP_MAC.md
Labels: product/invisible

#32226 Use bind parameters in jsonops
  corehq/sql_db/jsonops.py
  corehq/sql_db/tests/test_jsonops.py
Labels: product/invisible

#32254 Add waf_allow decorator to `accept_invitation`
  corehq/apps/users/templates/users/accept_invite.html
  corehq/apps/users/views/web.py
Labels: product/invisible

#32251 register index and add adapter when using custom pillow
  corehq/apps/es/transient_util.py
  corehq/pillows/case_search.py
Labels: product/invisible

#32253 Use ubuntu-22.04 for tests on Github Actions
  .github/workflows/tests.yml
Labels: product/invisible

#32190 Annotate location import view with waf allow
  corehq/apps/locations/urls.py
Labels: product/invisible

#32218 [USH-2415] Generic inbound API request filtering
  corehq/motech/generic_inbound/core.py
  corehq/motech/generic_inbound/exceptions.py
  corehq/motech/generic_inbound/forms.py
  corehq/motech/generic_inbound/migrations/0004_add_filter_expression.py
  corehq/motech/generic_inbound/models.py
  corehq/motech/generic_inbound/tests/test_api_processing.py
  corehq/motech/generic_inbound/views.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32220 Add workflow field to DomainCaseRuleRun
  corehq/apps/data_interfaces/migrations/0030_add_workflow_choices.py
  corehq/apps/data_interfaces/migrations/0031_add_domaincaserulerun_status_choices.py
  corehq/apps/data_interfaces/models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#32252 Re-updated app manager intro content
  corehq/apps/app_manager/views/releases.py
Labels: product/all-users-all-environments

#32213 SQL Lookup Tables - Part 2
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/api/fields.py
  corehq/apps/api/tests/lookup_table_resources.py
  corehq/apps/api/tests/utils.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_modules.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cachehq/mixins.py
  corehq/apps/domain/calculations.py
  corehq/apps/dump_reload/couch/dump.py
  corehq/apps/fixtures/couchmodels.py
  corehq/apps/fixtures/dbaccessors.py
  corehq/apps/fixtures/download.py
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/fixtures/interface.py
  corehq/apps/fixtures/management/commands/populate_lookuptablerowowners.py
  corehq/apps/fixtures/management/commands/populate_lookuptablerows.py
  corehq/apps/fixtures/management/commands/populate_lookuptables.py
  corehq/apps/fixtures/migrations/0008_sqllookuptables.py
  corehq/apps/fixtures/models.py
  corehq/apps/fixtures/resources/v0_1.py
  corehq/apps/fixtures/static/fixtures/js/lookup-manage.js
  corehq/apps/fixtures/tasks.py
  corehq/apps/fixtures/tests/test_dbaccessors.py
  corehq/apps/fixtures/tests/test_download.py
  corehq/apps/fixtures/tests/test_field_names.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/fixtures/tests/test_location_ownership.py
  corehq/apps/fixtures/tests/test_models.py
  corehq/apps/fixtures/tests/test_upload.py
  corehq/apps/fixtures/tests/test_views.py
  corehq/apps/fixtures/tests/test_workbook.py
  corehq/apps/fixtures/upload/run_upload.py
  corehq/apps/fixtures/upload/workbook.py
  corehq/apps/fixtures/utils.py
  corehq/apps/fixtures/views.py
  corehq/apps/hqadmin/corrupt_couch.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/tests/test_update_fixtures.py
  corehq/apps/linked_domain/tests/test_view_helpers.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_fixtures.py
  corehq/ex-submodules/dimagi/utils/couch/bulk.py
  corehq/ex-submodules/dimagi/utils/couch/migration.py
  corehq/util/tests/test_couch.py
  custom/abt/reports/filters_2020.py
  custom/abt/reports/fixture_utils.py
  custom/abt/reports/tests/test_fixture_utils.py
  custom/champ/views.py
  custom/inddex/example_data/data.py
  custom/inddex/fixtures.py
  custom/inddex/tests/test_master_report.py
  custom/reports/mc/reports/models.py
  custom/reports/mc/reports/sql.py
  custom/ucla/api.py
  custom/ucla/tests.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/invisible, Risk: High, Risk: Medium

#32256 First arg is request or None, not string
  corehq/apps/users/tasks.py
  corehq/util/signals.py
Labels: product/invisible

#31688 Upgrade Kafka+Zookeeper Docker Containers
  docker/hq-compose.yml
Labels: product/invisible

#32257 Set appropriate workflows when creating `DomainCaseRuleRun`s
  corehq/apps/data_interfaces/deduplication.py
  corehq/apps/data_interfaces/tasks.py
Labels: product/invisible

#32262 Upgrade moment-timezone
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#32240 Multi-select detail popup fixes
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: QA Passed, product/feature-flag, Risk: Medium

#32224 remove notice that OIDC is still in development from accounting admin edit IdP form
  corehq/apps/sso/forms.py
Labels: product/admin

#32268 Revert "Revert sqlalchemy pool changes"
  corehq/sql_db/connections.py
Labels: product/invisible

#31933 base implementation of hq project limits for APIs
  corehq/apps/api/odata/tests/test_feed.py
  corehq/apps/api/resources/auth.py
  corehq/apps/api/resources/meta.py
  corehq/apps/api/resources/v0_4.py
  corehq/apps/api/tests/core_api.py
  corehq/apps/domain/auth.py
  corehq/apps/enterprise/tests/test_permissions.py
  corehq/apps/zapier/tests/test_polling.py
Labels: product/invisible, Risk: High

#32273 Improve management command to verify SSL connections
  corehq/apps/hqadmin/management/commands/verify_ssl_connections.py
  corehq/messaging/smsbackends/airtel_tcl/models.py
  corehq/messaging/smsbackends/airtel_tcl/tests/test_airtel_tcl.py
  corehq/messaging/smsbackends/grapevine/models.py
  corehq/messaging/smsbackends/http/models.py
  corehq/messaging/smsbackends/infobip/models.py
  corehq/messaging/smsbackends/ivory_coast_mtn/models.py
  corehq/messaging/smsbackends/mach/models.py
  corehq/messaging/smsbackends/megamobile/models.py
  corehq/messaging/smsbackends/push/models.py
  corehq/messaging/smsbackends/smsgh/models.py
  corehq/messaging/smsbackends/starfish/models.py
  corehq/messaging/smsbackends/starfish/tests/test_outgoing.py
  corehq/messaging/smsbackends/start_enterprise/models.py
  corehq/messaging/smsbackends/telerivet/models.py
  corehq/messaging/smsbackends/tropo/models.py
  corehq/messaging/smsbackends/trumpia/models.py
  corehq/messaging/smsbackends/turn/models.py
  corehq/messaging/smsbackends/twilio/models.py
  corehq/messaging/smsbackends/unicel/models.py
  corehq/messaging/smsbackends/vertex/models.py
  corehq/messaging/tests/test_smsbackends.py
  corehq/motech/management/commands/verify_motech_connections.py
  manage.py
Labels: product/invisible

#32274 disable api throttle in tests
  corehq/motech/generic_inbound/tests/test_api.py
Labels: product/invisible

#32276 Super minor typo: perfom -> perform
  corehq/form_processor/reprocess.py
Labels: product/invisible, Risk: High

#32275 Switch Kafka image from bitnami to confluentinc
  .github/workflows/tests.yml
  docker/hq-compose-services.yml
  docker/hq-compose.yml
Labels: product/invisible

#32264 Cs/update data values schema
  corehq/motech/dhis2/schema.py
  corehq/motech/dhis2/tests/data/tracked_entity_instance_1.json
Labels: product/custom, product/invisible

#32280 Lookup Table Owners Issue
  corehq/apps/fixtures/download.py
Labels: product/invisible, Risk: Medium

#32260 [USH-2427] Form Multi-Field Validation User Experience Improvement
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/feature-flag, Risk: Medium

#32279 Update minimatch to ^3.0.5 (3.1.2)
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#32278 Fix KeyError on missing lookup table row owner
  corehq/apps/fixtures/download.py
  corehq/apps/fixtures/tests/test_download.py
Labels: product/invisible, Risk: Medium

#32281 Add notes about migration completeness
  docs/couch_to_sql_models.rst
Labels: product/invisible

#32283 Do not use transaction for Couch to SQL migrations
  corehq/apps/fixtures/migrations/0008_sqllookuptables.py
Labels: reindex/migration, product/invisible, Risk: Medium

#32287 Fix bug in LookupTableRowManager.iter_by_user
  corehq/apps/fixtures/models.py
  corehq/apps/fixtures/tests/test_models.py
Labels: product/invisible, Risk: Medium

#32173 Rc/update case search settings mapping
  corehq/ex-submodules/pillowtop/es_utils.py
  corehq/pillows/mappings/case_search_mapping.py
  docker/files/Dockerfile.es.2
  docker/files/Dockerfile.es.5
  docker/hq-compose.yml
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
Labels: reindex/migration, product/feature-flag, Risk: High

#32233 Standardize internal web apps js imports
  corehq/apps/cloudcare/static/cloudcare/js/debugger/debugger.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/errors.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/case_list_pagination_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/form_ui_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/web_form_session_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/hq_events.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/models.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/models.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/main.js
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/preview_app.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/cloudcare/templates/formplayer-common/base.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/apps/cloudcare/views.py
Labels: QA Passed, product/invisible, Risk: Medium

#32292 small tweaks to reindexer status output
  corehq/ex-submodules/pillowtop/reindexer/reindexer.py
Labels: product/invisible

#32282 tests and fixes for generic api filtering / validation
  corehq/motech/generic_inbound/tests/test_api.py
  corehq/motech/generic_inbound/views.py
Labels: product/invisible

#32294 Stay within shadow menu when form linking within same menu
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/test_form_workflow.py
  corehq/apps/app_manager/tests/test_form_workflow_multiple_case_types.py
Labels: product/feature-flag

#32044 upgrade pyOpenSSL to 22.0.0
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, product/invisible, product/prod-india-all-users, dependencies
