Repository dimagi/commcare-hq, pull requests merged in 2022-07, with the labels that each got.

#31851 don't cleary query data unless necessary
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
Labels: product/invisible, Risk: Medium

#31747 Run update-translations every Wed
  .github/workflows/update-translations.yml
Labels: product/invisible

#31852 Better error messaging when reverting to a bad build
  corehq/apps/app_manager/views/releases.py
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/fra/LC_MESSAGES/django.po
  locale/hi/LC_MESSAGES/django.po
  locale/hin/LC_MESSAGES/django.po
  locale/por/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/sw/LC_MESSAGES/django.po
Labels: product/all-users-all-environments

#31853 Add note about how translations work
  docs/translations.rst
Labels: product/invisible

#31856 Delink translations from PRs
  docker/run.sh
  scripts/test-make-translations.sh
Labels: product/invisible

#31817 Configurable row limit for operator
  corehq/apps/domain/admin.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/migrations/0012_operatorcalllimitsettings.py
  corehq/apps/domain/models.py
  corehq/apps/domain/tests/test_forms.py
  corehq/apps/dump_reload/sql/dump.py
  custom/samveg/case_importer/operations.py
  custom/samveg/case_importer/validators.py
  custom/samveg/commcare_extensions.py
  custom/samveg/const.py
  custom/samveg/tests/case_importer/operations.py
  custom/samveg/tests/case_importer/validators.py
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/fra/LC_MESSAGES/django.po
  locale/hi/LC_MESSAGES/django.po
  locale/hin/LC_MESSAGES/django.po
  locale/por/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/sw/LC_MESSAGES/django.po
  migrations.lock
Labels: reindex/migration, product/custom

#31855 Check if domain is active before deleting forms and cases
  corehq/apps/domain/management/commands/hard_delete_forms_and_cases_in_domain.py
Labels: product/invisible

#31859 Changed the redirect when a report is deleted
  corehq/apps/userreports/views.py
Labels: product/all-users-all-environments

#30933 Saved Reports now uses standarized date picker
  corehq/apps/reports/static/reports/js/report_config_models.js
  corehq/apps/reports/templates/reports/partials/save_reports_modal.html
  corehq/apps/reports/views.py
Labels: product/invisible

#31863 Moved multi-select save into case list section of case detail save
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#31835 Call clear_login_attempts after resetting mobile user password
  corehq/apps/users/forms.py
  corehq/apps/users/tests/forms.py
Labels: product/invisible

#31802 Fix Zapier integrations to not require API_ACESS permission
  corehq/apps/api/resources/__init__.py
  corehq/apps/zapier/api/v0_5.py
  corehq/apps/zapier/tests/test_polling.py
Labels: product/invisible, Risk: High

#31847 Enhancements to mobile worker signup process
  corehq/apps/domain/deletion.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/migrations/0013_accountconfirmationsettings_squashed_0016_alter_smsaccountconfirmationsettings_project_name.py
  corehq/apps/domain/models.py
  corehq/apps/domain/tests/test_forms.py
  corehq/apps/domain/tests/test_utils.py
  corehq/apps/domain/utils.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/registration/forms.py
  corehq/apps/registration/templates/registration/mobile/mobile_worker_account_confirmation_success_sms.txt
  corehq/apps/users/account_confirmation.py
  corehq/apps/users/forms.py
  corehq/apps/users/templates/users/commcare_user_confirm_account.html
  corehq/apps/users/views/mobile/users.py
  locale/en/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/djangojs.po
  locale/es/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/djangojs.po
  locale/fr/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/djangojs.po
  locale/fra/LC_MESSAGES/django.po
  locale/fra/LC_MESSAGES/djangojs.po
  locale/hi/LC_MESSAGES/django.po
  locale/hi/LC_MESSAGES/djangojs.po
  locale/hin/LC_MESSAGES/django.po
  locale/hin/LC_MESSAGES/djangojs.po
  locale/por/LC_MESSAGES/django.po
  locale/por/LC_MESSAGES/djangojs.po
  locale/pt/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/djangojs.po
  locale/sw/LC_MESSAGES/django.po
  locale/sw/LC_MESSAGES/djangojs.po
  migrations.lock
Labels: reindex/migration, QA Passed, product/feature-flag, Risk: High

#31865 Bump Django from 3.2.13 to 3.2.14
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31829 add api throttle to more api views
  corehq/apps/api/resources/messaging_event/view.py
  corehq/apps/app_manager/views/cli.py
  corehq/apps/fixtures/views.py
  corehq/apps/userreports/views.py
Labels: product/invisible, Risk: High, Risk: Medium

#31864 Fixed save button enabling when it shouldn't
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
Labels: product/feature-flag

#31861 Fixed ShadowMenu grid validation issue
  corehq/apps/app_manager/suite_xml/sections/menus.py
Labels: product/feature-flag

#31870 Fixed 500 on viewing tableau report when logged out
  corehq/apps/reports/standard/tableau.py
Labels: product/feature-flag

#31840 Change multimedia export to check for duplicates
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/tasks.py
  corehq/apps/reports/tests/test_esaccessors.py
Labels: product/invisible

#31872 Change Update Translations PR/commit text to skip CI
  .github/workflows/update-translations.yml
Labels: product/invisible

#31878 Minor linked domains error handling refactor + message improvement
  corehq/apps/linked_domain/exceptions.py
  corehq/apps/linked_domain/tests/test_views.py
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#31881 Fixed attr binding for web apps password input
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/invisible, Risk: Medium

#31883 Add an option to filter by can_view_report to UserDomains API endpoint
  corehq/apps/api/resources/v0_5.py
Labels: product/invisible, Risk: High

#31889 Fix range validation for integer fields
  corehq/apps/domain/forms.py
  corehq/apps/domain/tests/test_forms.py
Labels: product/feature-flag

#31887 Add ability to change custom_base_url for downstream apps
  corehq/apps/app_manager/static/app_manager/json/commcare-app-settings.yml
Labels: product/feature-flag

#31884 Disable submit button when password fail validation
  corehq/apps/users/templates/users/accept_invite.html
  corehq/apps/users/templates/users/commcare_user_confirm_account.html
  corehq/apps/users/templates/users/partials/register_user_form_fields.html
  corehq/apps/users/views/mobile/users.py
  corehq/apps/users/views/web.py
Labels: QA Passed, product/all-users-all-environments, product/feature-flag

#31844 Enforce minimum password length
  corehq/apps/domain/extension_points.py
  corehq/apps/domain/tests/test_password_strength.py
  corehq/apps/hqwebapp/static/hqwebapp/js/password_validators.ko.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/registration/static/registration/js/password.js
  corehq/apps/registration/static/registration/js/password_reset_confirm.js
  corehq/apps/settings/static/settings/js/change_my_password.js
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/accept_invite.js
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/templates/users/accept_invite.html
  corehq/apps/users/templates/users/commcare_user_confirm_account.html
  corehq/apps/users/templates/users/partials/register_user_form_fields.html
  corehq/apps/users/views/mobile/users.py
  corehq/apps/users/views/web.py
  corehq/util/context_processors.py
  settings.py
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#31888 Updated max usage in _merge_dicts for python 3
  corehq/apps/export/models/new.py
Labels: product/feature-flag

#31886 Updated value logic in query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: QA Passed, product/feature-flag, Risk: Medium

#31761 only do a full bootstrap on startup or the migration process
  corehq/apps/userreports/pillow.py
  corehq/apps/userreports/tests/test_pillow.py
Labels: product/invisible

#31898 display session timeouts
  corehq/apps/settings/templates/settings/my_projects.html
  corehq/apps/settings/views.py
Labels: product/all-users-all-environments

#31901 Updated logic for py3-friendly max function
  corehq/apps/export/models/new.py
Labels: product/invisible

#31900 add vertical resize
  corehq/apps/hqwebapp/templates/hqwebapp/partials/ko_feedback.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/ko_inline_edit.html
Labels: product/invisible, product/admin

#31903 update get_all_case_modules to use app.get_modules() not app.modules
  corehq/apps/app_manager/views/modules.py
Labels: product/invisible

#31904 Fix argument in DHIS2 error handler
  corehq/motech/dhis2/static/dhis2/js/dhis2_entity_config.js
  corehq/motech/dhis2/templates/dhis2/dataset_map_json.html
  corehq/motech/dhis2/templates/dhis2/dhis2_entity_config.html
  corehq/motech/dhis2/templates/dhis2/dhis2_events_config.html
Labels: product/feature-flag

#31902 Added resize guidelines to style guide
  corehq/apps/styleguide/templates/styleguide/_includes/organisms/forms.html
  corehq/apps/styleguide/templates/styleguide/examples/html_form.html
Labels: product/invisible, product/admin

#31885 [USH] Case search: Custom messages for required conditions
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
Labels: Open for review: do not merge, product/feature-flag

#31465 Create page for getting users to offboard
  corehq/apps/hqadmin/forms.py
  corehq/apps/hqadmin/templates/hqadmin/superuser_management.html
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/views/users.py
  corehq/tabs/tabclasses.py
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/fra/LC_MESSAGES/django.po
  locale/hi/LC_MESSAGES/django.po
  locale/hin/LC_MESSAGES/django.po
  locale/por/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/sw/LC_MESSAGES/django.po
Labels: product/invisible

#31854 Add autocompletes for case properties in case update rules and conditional alerts
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/static/data_interfaces/js/case_property_input.js
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_actions.js
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_criteria.js
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_main.js
  corehq/apps/data_interfaces/templates/data_interfaces/case_rule.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_rule_actions.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_rule_criteria.html
  corehq/apps/data_interfaces/views.py
  corehq/apps/hqwebapp/static/hqwebapp/js/select2_knockout_bindings.ko.js
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_main.js
  corehq/messaging/scheduling/templates/scheduling/conditional_alert.html
  corehq/messaging/scheduling/views.py
Labels: QA Passed, product/feature-flag

#31667 Cs/sc 1789 update user mapping
  corehq/apps/locations/dbaccessors.py
  corehq/apps/locations/tasks.py
  corehq/apps/locations/tests/test_dbaccessors.py
  corehq/ex-submodules/pillowtop/management/commands/sync_es_webusers.py
  corehq/pillows/mappings/user_mapping.py
Labels: product/all-users-all-environments, product/invisible, Risk: High

#31907 Moved visibility of select2
  corehq/apps/data_interfaces/static/data_interfaces/js/case_property_input.js
Labels: QA Passed, product/all-users-all-environments

#31909 Use inserted_at time for form aggregation
  custom/covid/management/commands/fetch_form_case_counts.py
Labels: product/custom

#31803 Remove report cases and report xforms
  corehq/apps/api/es.py
  corehq/apps/api/tests/form_resources.py
  corehq/apps/es/cases.py
  corehq/apps/es/forms.py
  corehq/apps/es/transient_util.py
  corehq/apps/hqcase/management/commands/ptop_preindex.py
  corehq/apps/hqcase/management/commands/ptop_reindexer_v2.py
  corehq/apps/hqcase/management/commands/reprocess_form_case_es_deletes.py
  corehq/ex-submodules/pillowtop/es_utils.py
  corehq/ex-submodules/pillowtop/management/commands/create_checkpoints_for_merged_pillows.py
  corehq/ex-submodules/pillowtop/migrations/0007_copy_xforms_checkpoint.py
  corehq/ex-submodules/pillowtop/utils.py
  corehq/pillows/base.py
  corehq/pillows/case.py
  corehq/pillows/mappings/__init__.py
  corehq/pillows/mappings/reportcase_mapping.py
  corehq/pillows/mappings/reportxform_mapping.py
  corehq/pillows/reportcase.py
  corehq/pillows/reportxform.py
  corehq/pillows/xform.py
  docs/elasticsearch.rst
  migrations.lock
  settings.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
  testapps/test_pillowtop/tests/test_pillows_cases.py
  testapps/test_pillowtop/tests/test_pillows_xforms.py
  testapps/test_pillowtop/tests/test_reindexer.py
  testapps/test_pillowtop/tests/test_report_case_pillow.py
  testapps/test_pillowtop/tests/test_report_xform_pillow.py
Labels: reindex/migration, Open for review: do not merge, product/invisible, Risk: High

#31689 remove messaging signals
  corehq/apps/data_interfaces/tests/test_scheduling_integration.py
  corehq/apps/hqadmin/views/operations.py
  corehq/apps/ivr/tests/util.py
  corehq/apps/sms/tasks.py
  corehq/apps/sms/tests/opt_tests.py
  corehq/apps/sms/tests/test_backends.py
  corehq/apps/sms/tests/test_phone_numbers.py
  corehq/apps/sms/tests/test_util.py
  corehq/messaging/__init__.py
  corehq/messaging/management/commands/resync_case_type.py
  corehq/messaging/pillow.py
  corehq/messaging/scheduling/tests/test_recipients.py
  corehq/messaging/signals.py
  corehq/messaging/tasks.py
  docs/messaging/schedules.rst
  settings.py
Labels: product/invisible

#31911 replace `post_case_blocks` with `submit_case_blocks`
  corehq/apps/aggregate_ucrs/tests/test_aggregation.py
  corehq/apps/api/tests/ucr_resources.py
  corehq/apps/change_feed/tests/test_data_sources.py
  corehq/apps/hqcase/tests/test_bugs.py
  corehq/apps/hqcase/tests/test_case_sharing.py
  corehq/apps/ota/tests/test_claim.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/apps/sms/tests/util.py
  corehq/apps/userreports/tests/test_columns.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/zapier/tests/test_zapier_forwarding.py
  corehq/ex-submodules/casexml/apps/case/mock/mock.py
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
  corehq/ex-submodules/casexml/apps/case/tests/test_indexes.py
  corehq/ex-submodules/casexml/apps/case/tests/test_rebuild.py
  corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py
  corehq/ex-submodules/casexml/apps/case/tests/util.py
  corehq/ex-submodules/casexml/apps/case/util.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py
  corehq/ex-submodules/casexml/apps/phone/utils.py
  corehq/ex-submodules/casexml/apps/stock/mock.py
  corehq/form_processor/tests/test_basics.py
  corehq/form_processor/tests/test_dbcache.py
  corehq/form_processor/tests/test_reprocess_errors.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_repeater.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/util/test_utils.py
  custom/covid/tests/test_management_commands.py
  custom/inddex/example_data/data.py
Labels: product/invisible, Risk: High

#31912 case rule from identification
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/hqcase/utils.py
  custom/covid/rules/custom_actions.py
  custom/gcc_sangath/rules/custom_actions.py
Labels: product/invisible

#31913 Cleanup "submit_case_blocks"
  corehq/apps/hqcase/utils.py
  corehq/ex-submodules/casexml/apps/case/mock/mock.py
  corehq/form_processor/tests/test_basics.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_repeater.py
Labels: product/invisible, Risk: High

#31895 Use deleted domains view directly in cleanup tasks + refactor
  corehq/apps/cleanup/dbaccessors.py
  corehq/apps/cleanup/tasks.py
  corehq/apps/cleanup/tests/test_dbaccessors.py
  corehq/apps/cleanup/tests/util.py
  corehq/apps/domain/models.py
  corehq/apps/domain/tests/test_domain_name_generation.py
  corehq/apps/domain/tests/test_utils.py
  corehq/apps/domain/utils.py
  corehq/apps/userreports/tests/test_utils.py
  corehq/apps/userreports/util.py
Labels: product/invisible

#31792 [couch-to-sql] [Repeaters] Add to_json in sql repeater model
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/optionvalue.py
  corehq/motech/repeaters/tests/data/repeaters.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_optionvalue.py
  corehq/motech/repeaters/tests/test_proxy_models.py
Labels: product/invisible

#31926 USH Case Search: Fix default and sticky selections in multiselect elements
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/custom, Risk: Medium

#31915 Es/validation conditions qa
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
Labels: product/feature-flag

#31927 Add metric for python deps on outdated major release
  scripts/track-dependency-status.sh
Labels: product/invisible

#31928 Flag priority improvement areas
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/app_manager/xform.py
  corehq/apps/fixtures/download.py
  corehq/apps/user_importer/importer.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/tabs/tabclasses.py
Labels: product/invisible

#31932 Add metrics for python deps outdated by more than 1 major version
  scripts/track-dependency-status.sh
Labels: product/invisible

#31923 allow submitting system forms with a name for display to users
  corehq/apps/data_interfaces/models.py
  corehq/apps/hqcase/templates/hqcase/xml/case_block.xml
  corehq/apps/hqcase/utils.py
  corehq/apps/reports/display.py
  corehq/apps/reports/standard/cases/case_data.py
  corehq/apps/reports/standard/forms/reports.py
  corehq/apps/reports/tests/test_display.py
  corehq/ex-submodules/casexml/apps/case/cleanup.py
  corehq/ex-submodules/casexml/apps/case/mock/mock.py
  corehq/ex-submodules/casexml/apps/case/tests/test_factory.py
  corehq/ex-submodules/casexml/apps/case/tests/test_rebuild.py
  corehq/ex-submodules/casexml/apps/case/util.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_new_sync.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py
  corehq/ex-submodules/casexml/apps/phone/utils.py
  custom/covid/rules/custom_actions.py
  custom/gcc_sangath/rules/custom_actions.py
Labels: product/all-users-all-environments

#31924 Remove ability to set is_superuser/is_staff via Django Admin
  corehq/apps/users/admin.py
  corehq/apps/users/tests/test_admin.py
Labels: product/invisible

#31931 Fix ESQuery scroll size bugs
  corehq/apps/es/es_query.py
  corehq/apps/es/tests/test_esquery.py
Labels: product/invisible

#31929 fixed styling issue
  corehq/apps/hqwebapp/static/hqwebapp/css/proptable.css
Labels: product/all-users-all-environments

#31925 Removed proteusvacuum from CODEOWNERS
  .github/CODEOWNERS
Labels: product/invisible

#31934 Add rich metrics for outdated JS dependencies
  scripts/outdated-dependency-metrics.py
  scripts/pip-dep-debt.py
  scripts/track-dependency-status.sh
Labels: product/invisible

#31937 Updated case search error messaging styling
  corehq/apps/cloudcare/templates/formplayer/query_view.html
Labels: product/invisible, Risk: Medium

#31871 [USH] Case Search validation conditions
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#31879 add input validation errors below input
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/templates/formplayer/query_view.html
Labels: product/feature-flag, Risk: Medium

#31939 Add new utility `yarn-list.py` for listing yarn packages
  scripts/outdated-dependency-metrics.py
  scripts/track-dependency-status.sh
  scripts/yarn-list.py
Labels: product/invisible

#31941 UI tweaks to superuser management
  corehq/apps/hqadmin/templates/hqadmin/superuser_management.html
  corehq/apps/hqadmin/views/users.py
  corehq/tabs/tabclasses.py
Labels: product/admin

#31922 don't double report errors
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/web_form_session_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/util.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/util.js
Labels: product/invisible, Risk: Medium

#31906 Removed re-render of case search fields on every value change
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: QA Passed, product/feature-flag, Risk: Medium

#31935 Prohibit ESQuery aggregations with scroll queries
  corehq/apps/es/es_query.py
  corehq/apps/es/tests/test_esquery.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/userreports/tests/test_pillow.py
Labels: product/invisible

#31943 Only open dependabot PRs for major version upgrades
  .github/dependabot.yml
Labels: product/invisible

#31951 Log transient bounced invites as Delivered
  corehq/apps/users/event_handlers.py
  corehq/apps/users/models.py
  corehq/util/email_event_utils.py
Labels: product/all-users-all-environments

#31947 Building URLs smarter
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/json/commcare-app-settings.yml
  corehq/apps/app_manager/static_strings.py
  corehq/apps/app_manager/suite_xml/generator.py
  corehq/apps/app_manager/tests/test_util.py
Labels: product/invisible

#31959 Revert case search "required" suite changes
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag
