Repository dimagi/commcare-hq, pull requests merged in 2022-02, with the labels that each got.

#31029 [SAMVEG] Adds test domain
  custom/samveg/const.py
Labels: product/custom

#31033 [SAMVEG] Adds test domain hotfix
  custom/samveg/const.py
Labels: product/custom

#31024 Add some IDE help in reports dispatcher
  .isort.cfg
  corehq/apps/reports/dispatcher.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31032 Fix queueing of broadcast messages
  corehq/messaging/scheduling/tasks.py
  corehq/messaging/scheduling/views.py
Labels: product/invisible

#31034 Pass correct named parameters to scheduled broadcasts
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/messaging/scheduling/views.py
Labels: product/invisible

#31037 Fix queueing of broadcast messages
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/messaging/scheduling/tasks.py
  corehq/messaging/scheduling/views.py
Labels: product/invisible

#31038 Fix queueing of broadcast messages
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/messaging/scheduling/tasks.py
  corehq/messaging/scheduling/views.py
Labels: product/invisible

#31015 Pick display format from style itself
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/templates/formplayer/case_detail.html
Labels: product/all-users-all-environments

#31022 Fix ptop_preindex now that couch cases are gone
  corehq/apps/hqcase/management/commands/ptop_preindex.py
Labels: product/invisible

#30801 Add view to play form attachment audio in browser
  corehq/apps/api/object_fetch_api.py
  corehq/apps/api/urls.py
  corehq/apps/reports/templates/reports/form/partials/single_form.html
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments

#31039 Allow Vellum HQ commit to skip commit hooks
  scripts/vellum-to-hq
Labels: product/invisible

#30946 Save only edit fields-- xml changes
  corehq/apps/app_manager/const.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/xform.py
Labels: product/invisible

#30591 Remove serializer='pickle' from analytics
  corehq/apps/analytics/signals.py
  corehq/apps/analytics/tasks.py
  corehq/apps/analytics/views.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/registration/views.py
  corehq/apps/userreports/views.py
Labels: product/invisible, Risk: High

#30924 "Only save a field if it's been edited" new feature UI
  corehq/apps/app_manager/static/app_manager/js/case_config_utils.js
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
  corehq/apps/hqwebapp/static/app_manager/less/table.less
Labels: product/all-users-all-environments

#31041 Add status embed code in to Commcare HQ
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/util/context_processors.py
  settings.py
Labels: product/all-users-all-environments, Risk: Medium

#31001 Remove redundant aggregation on username
  corehq/apps/data_analytics/esaccessors.py
  corehq/apps/data_analytics/malt_generator.py
  corehq/apps/data_analytics/management/commands/update_malt_table.py
  corehq/apps/data_analytics/tasks.py
  corehq/apps/data_analytics/tests/test_esaccessors.py
  corehq/apps/data_analytics/tests/test_malt_generator.py
  corehq/apps/users/util.py
Labels: product/invisible

#31035 Removed MOBILE_UCR_LINKED_DOMAIN
  corehq/apps/app_manager/templates/app_manager/managed_app.html
  corehq/apps/app_manager/views/apps.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#31021 Add Partner Analytics
  corehq/apps/analytics/migrations/0001_initial.py
  corehq/apps/analytics/migrations/__init__.py
  corehq/apps/analytics/models.py
  corehq/apps/analytics/tasks.py
  corehq/apps/analytics/templates/analytics/email/partner_analytics_report.html
  corehq/apps/analytics/templates/analytics/email/partner_analytics_report.txt
  corehq/apps/analytics/tests/test_partner_analytics_utils.py
  corehq/apps/analytics/utils/partner_analytics.py
  corehq/apps/api/odata/views.py
  corehq/apps/domain/tests/test_deletion_models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31025 Move form accessors into XFormInstance.objects - phase 3
  corehq/apps/analytics/tasks.py
  corehq/apps/api/object_fetch_api.py
  corehq/apps/api/urls.py
  corehq/apps/change_feed/tests/test_data_sources.py
  corehq/apps/cleanup/management/commands/reprocess_error_forms.py
  corehq/apps/cleanup/management/commands/undo_uuid_clash.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/data_interfaces/utils.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/management/commands/hard_delete_forms_and_cases_in_domain.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/apps/hqadmin/management/commands/export_domain_forms_raw.py
  corehq/apps/hqcase/management/commands/reindex_sql_forms_in_domain.py
  corehq/apps/hqcase/tasks.py
  corehq/apps/ota/tests/test_registry_case_details.py
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/apps/reports/tasks.py
  corehq/apps/reports/views.py
  corehq/apps/sms/tests/util.py
  corehq/apps/users/management/commands/archive_forms_submitted_by_user.py
  corehq/apps/users/management/commands/gdpr_scrub_user_from_forms.py
  corehq/apps/users/models.py
  corehq/apps/users/tasks.py
  corehq/apps/users/tests/retire.py
  corehq/ex-submodules/couchforms/management/commands/purge_forms_and_cases.py
  corehq/ex-submodules/couchforms/tests/test_archive.py
  corehq/ex-submodules/pillowtop/reindexer/change_providers/form.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/backends/sql/processor.py
  corehq/form_processor/document_stores.py
  corehq/form_processor/interfaces/dbaccessors.py
  corehq/form_processor/management/commands/archive_all_forms_for_user_in_domain.py
  corehq/form_processor/management/commands/check_forms_have_xml.py
  corehq/form_processor/management/commands/get_case_ids_from_forms.py
  corehq/form_processor/management/commands/list_data_by_shard.py
  corehq/form_processor/models/__init__.py
  corehq/form_processor/models/attachment.py
  corehq/form_processor/models/forms.py
  corehq/form_processor/models/util.py
  corehq/form_processor/reprocess.py
  corehq/form_processor/system_action.py
  corehq/form_processor/tasks.py
  corehq/form_processor/tests/test_basics.py
  corehq/form_processor/tests/test_form_dbaccessor.py
  corehq/form_processor/tests/test_forms.py
  corehq/form_processor/tests/test_gdpr_scrub_user_from_forms.py
  corehq/form_processor/tests/test_reprocess_errors.py
  corehq/form_processor/tests/test_system_action.py
  corehq/motech/repeaters/tests/test_payload_generators.py
  corehq/motech/repeaters/tests/test_tasks.py
  docs/forms_and_cases.rst
  testapps/test_pillowtop/tests/test_xform_pillow.py
Labels: product/invisible, Risk: High

#31043 Fix redundant global admin URL pattern resolvers
  corehq/apps/api/urls.py
Labels: product/invisible, Risk: High

#31042 Revert "Merge pull request #30559 from dimagi/dependabot/pip/requirem…
  corehq/util/workbook_reading/adapters/xlsx.py
  corehq/util/workbook_reading/tests/test_spreadsheets.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31031 Update user facing text
  corehq/apps/export/views/download.py
Labels: product/invisible

#31045 Move form accessors into XFormInstance.objects - final
  corehq/apps/api/object_fetch_api.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/backends/sql/supply.py
  corehq/form_processor/interfaces/dbaccessors.py
  corehq/form_processor/migrations/0001_initial.py
  corehq/form_processor/models/abstract.py
  corehq/form_processor/models/forms.py
  corehq/form_processor/parsers/ledgers/form.py
  corehq/form_processor/tests/test_form_dbaccessor.py
  corehq/form_processor/tests/test_kafka.py
  dev_settings.py
  docs/caching_and_memoization.rst
  docs/forms_and_cases.rst
Labels: reindex/migration, product/invisible, Risk: High

#31044 Require API access for v6 Case API
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/hqcase/views.py
Labels: product/feature-flag

#30758 add retry backoff to conditional alerts
  corehq/messaging/scheduling/scheduling_partitioned/migrations/0008_track_attempts.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/scheduling/tasks.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31052 Move and optimize fetchall_as_namedtuple
  corehq/apps/cleanup/management/commands/dedupe_case_indices.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/models/forms.py
  corehq/form_processor/models/util.py
  corehq/form_processor/utils/sql.py
Labels: product/invisible, Risk: High

#31055 [USH] One-off case migration
  corehq/apps/hqcase/bulk.py
  corehq/apps/hqcase/tests/test_bulk.py
  custom/covid/management/commands/update_all_activity_complete_date.py
  custom/covid/tests/test_management_commands.py
Labels: product/custom

#31030 hide case search config options until case search is active
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
Labels: product/feature-flag

#31058 raise custom exception for deleted report configs
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/util.py
Labels: product/invisible

#31059 add null check for domain membership
  corehq/apps/users/forms.py
Labels: product/invisible

#31062 moves auth decorators first
  corehq/apps/api/object_fetch_api.py
  corehq/apps/reports/views.py
Labels: product/invisible

#30935 modified exportinstance to contain new integration type property
  corehq/apps/export/views/list.py
  corehq/ex-submodules/couchexport/models.py
Labels: product/invisible

#31053 Add last_run_date to MALTRow
  corehq/apps/data_analytics/migrations/0010_maltrow_last_run_date.py
  corehq/apps/data_analytics/models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31057 Support domains that are legacied into RELEASE_MANAGEMENT but not enterprise accounts
  corehq/apps/accounting/utils/account.py
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#31054 Fix broken tabclass tests after MRM changes
  corehq/tabs/tests.py
Labels: product/invisible

#31073 Revert "Merge to master and solve conflict"
  corehq/apps/reports/forms.py
  corehq/apps/reports/static/reports/js/report_config_models.js
  corehq/apps/reports/static/reports/js/saved_reports_main.js
  corehq/apps/reports/templates/reports/reports_home.html
  corehq/apps/reports/views.py
  corehq/apps/saved_reports/models.py
  corehq/apps/saved_reports/tests/test_models.py
  corehq/apps/saved_reports/tests/test_views.py
Labels: product/all-users-all-environments

#31075 Replace check_toggle with include_toggle
  corehq/apps/app_manager/forms.py
Labels: product/invisible

#31027 Reject weak password (backend)
  corehq/apps/domain/views/settings.py
  corehq/apps/settings/views.py
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/views/__init__.py
Labels: product/invisible

#31065 Move case accessors into CommCareCase.objects - part 3
  corehq/apps/api/models.py
  corehq/apps/api/object_fetch_api.py
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/change_feed/tests/test_data_sources.py
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/domain/management/commands/hard_delete_forms_and_cases_in_domain.py
  corehq/apps/hqadmin/management/commands/delete_related_cases.py
  corehq/apps/hqcase/api/updates.py
  corehq/apps/hqcase/tasks.py
  corehq/apps/ota/tests/test_registry_case_details.py
  corehq/apps/userreports/expressions/specs.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/users/tasks.py
  corehq/ex-submodules/casexml/apps/case/tests/test_db_accessors.py
  corehq/ex-submodules/casexml/apps/case/tests/test_multi_case_submits.py
  corehq/ex-submodules/casexml/apps/case/tests/util.py
  corehq/form_processor/backends/sql/casedb.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/backends/sql/processor.py
  corehq/form_processor/interfaces/dbaccessors.py
  corehq/form_processor/models/cases.py
  corehq/form_processor/reprocess.py
  corehq/form_processor/tests/test_case_dbaccessor.py
  corehq/form_processor/tests/test_cases.py
  corehq/form_processor/tests/test_reindex_accessors.py
  corehq/form_processor/tests/test_reprocess_errors.py
  corehq/form_processor/tests/test_sql_update_strategy.py
  corehq/form_processor/tests/utils.py
  corehq/motech/fhir/tests/test_fhir_views.py
  corehq/motech/fhir/views.py
  corehq/motech/value_source.py
  corehq/util/test_utils.py
  custom/eqa/expressions.py
Labels: product/invisible, Risk: High

#31081 Specify keyword arg for fire_synchronously
  corehq/motech/repeaters/models.py
Labels: product/invisible

#31080 Removed Summary Tabular Report
  corehq/apps/reports/generic.py
  corehq/apps/reports/templates/reports/async/summary_tabular.html
Labels: product/invisible

#31082 Force keyword arguments
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_models.py
Labels: product/invisible

#31061 Implement last_run_date on MALTRow
  corehq/apps/data_analytics/malt_generator.py
  corehq/apps/data_analytics/tests/test_malt_generator.py
Labels: product/invisible

#31063 use delete / undo utils instead of re-implementing them + fix them
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/tests/test_utils.py
  corehq/apps/userreports/util.py
  corehq/ex-submodules/dimagi/utils/couch/undo.py
Labels: product/invisible

#31083 Move case accessors into CommCareCase.objects - part 4
  corehq/apps/callcenter/utils.py
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/management/commands/hard_delete_forms_and_cases_in_domain.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/apps/hqcase/tests/test_bulk.py
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/hqcase/tests/test_explode_cases.py
  corehq/apps/ota/tests/test_claim.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/retire.py
  corehq/apps/zapier/tests/test_create_update_cases_from_zapier.py
  corehq/ex-submodules/casexml/apps/case/tests/test_exclusion.py
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/backends/sql/supply.py
  corehq/form_processor/interfaces/dbaccessors.py
  corehq/form_processor/management/commands/list_data_by_shard.py
  corehq/form_processor/models/cases.py
  corehq/form_processor/tests/test_case_dbaccessor.py
  corehq/form_processor/tests/test_cases.py
  corehq/form_processor/tests/test_forms.py
  corehq/form_processor/tests/test_ledgers.py
  corehq/form_processor/tests/test_reprocess_errors.py
  corehq/form_processor/tests/utils.py
  corehq/messaging/management/commands/run_rule.py
  corehq/motech/repeaters/models.py
  custom/covid/management/commands/add_assignment_cases.py
  custom/covid/management/commands/update_case_index_relationship.py
  custom/covid/management/commands/update_cases.py
  custom/covid/tests/test_custom_rules.py
  custom/covid/tests/test_management_commands.py
  custom/inddex/example_data/data.py
  custom/inddex/tests/test_master_report.py
  custom/onse/tasks.py
  docs/forms_and_cases.rst
Labels: product/invisible, Risk: High

#31084 Add nose support for TestCase.addClassCleanup
  corehq/tests/noseplugins/classcleanup.py
  corehq/tests/test_classcleanup.py
  testsettings.py
Labels: product/invisible

#30987 Ignore missing scheduled reports in queue
  corehq/apps/saved_reports/exceptions.py
  corehq/apps/saved_reports/tasks.py
  corehq/apps/saved_reports/tests/test_tasks.py
Labels: product/invisible

#31068 Generate malt related tasks from periodic queue to avoid blocking malt queue
  corehq/apps/data_analytics/tasks.py
Labels: product/invisible

#31087 properly set Access-Control-Allow-Methods in CORS headers
  corehq/apps/api/cors.py
  corehq/apps/api/decorators.py
  corehq/apps/api/resources/__init__.py
  corehq/apps/domain/tests/test_auth_decorators.py
Labels: product/all-users-all-environments, Risk: High

#31094 Fixed intrusive progress screen
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/controller.js
Labels: product/feature-flag, Risk: Medium

#31066 [Auto-Deactivate Mobile Workers] Add Models
  corehq/apps/domain/deletion.py
  corehq/apps/enterprise/migrations/0004_enterprisemobileworkersettings.py
  corehq/apps/enterprise/models.py
  corehq/apps/users/migrations/0042_deactivatemobileworkertrigger.py
  corehq/apps/users/models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31093 Upgrade Django to 2.2.27
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31092 Move case accessors into CommCareCase.objects - part 5
  corehq/apps/callcenter/sync_usercase.py
  corehq/apps/callcenter/tests/test_indicators.py
  corehq/apps/callcenter/tests/test_location_owners.py
  corehq/apps/callcenter/tests/test_sync_usercases_tasks.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/case_importer/tests/test_util.py
  corehq/apps/case_importer/util.py
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/tests/util.py
  corehq/apps/users/models.py
  corehq/ex-submodules/casexml/apps/case/tests/test_close_extension_chain.py
  corehq/ex-submodules/casexml/apps/case/xform.py
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/interfaces/dbaccessors.py
  corehq/form_processor/models/cases.py
  corehq/form_processor/tests/test_case_dbaccessor.py
  corehq/form_processor/tests/test_cases.py
  corehq/form_processor/tests/test_extension_cases.py
  corehq/form_processor/tests/test_usercase_dbaccessor.py
  corehq/motech/fhir/tasks.py
  corehq/sql_db/tests/utils.py
  custom/covid/casesync.py
  dev_settings.py
Labels: product/invisible, Risk: High

#31107 Update transifex client config files for cli v1.0.0
  .transifexrc.example
  .tx/config
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
Labels: product/invisible, dependencies

#31113 Upgrade pip tools
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31112 Add docstrings to test_public_only_session
  corehq/motech/tests/test_public_only_session.py
Labels: product/invisible

#31090 [GSheets] Add ProjectLimit model
  corehq/apps/domain/migrations/0010_projectlimit.py
  corehq/apps/domain/models.py
  corehq/apps/domain/tests/test_deletion_models.py
  migrations.lock
Labels: reindex/migration, product/all-users-all-environments

#31098 [Auto-Deactivate Mobile Workers] Add Feature Flag
  corehq/toggles/__init__.py
Labels: product/invisible

#31111 Dm/case accessors 6
  corehq/apps/domain/deletion.py
  corehq/apps/hqadmin/management/commands/delete_related_cases.py
  corehq/apps/hqcase/tasks.py
  corehq/apps/sms/tests/util.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/users/models.py
  corehq/apps/users/tasks.py
  corehq/apps/users/tests/retire.py
  corehq/ex-submodules/casexml/apps/case/mock/mock.py
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
  corehq/ex-submodules/casexml/apps/case/tests/test_rebuild.py
  corehq/ex-submodules/casexml/apps/case/tests/util.py
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py
  corehq/ex-submodules/couchforms/management/commands/purge_forms_and_cases.py
  corehq/ex-submodules/pillowtop/tests/test_utils.py
  corehq/form_processor/backends/sql/casedb.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/backends/sql/processor.py
  corehq/form_processor/backends/sql/update_strategy.py
  corehq/form_processor/interfaces/dbaccessors.py
  corehq/form_processor/models/cases.py
  corehq/form_processor/reprocess.py
  corehq/form_processor/tests/test_case_dbaccessor.py
  corehq/form_processor/tests/test_cases.py
  corehq/form_processor/tests/test_kafka.py
  corehq/form_processor/tests/test_usercase_dbaccessor.py
  corehq/form_processor/tests/utils.py
  corehq/motech/fhir/tests/test_fhir_views.py
  corehq/motech/tests/test_value_source.py
  corehq/util/test_utils.py
  testapps/test_pillowtop/tests/test_case_pillow.py
Labels: product/invisible, Risk: High

#31114 Remove unused concurrent-log-handler dependency
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31074 Remote API Logs CSV export
  corehq/motech/templates/motech/logs.html
  corehq/motech/urls.py
  corehq/motech/views.py
Labels: product/feature-flag

#31088 Add an API for UCR data sources
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/urls.py
Labels: product/feature-flag, Risk: High

#31119 [SANGATH] Custom case update
  custom/gcc_sangath/__init__.py
  custom/gcc_sangath/const.py
  custom/gcc_sangath/rules/custom_actions.py
  custom/gcc_sangath/tests/__init__.py
  custom/gcc_sangath/tests/test_custom_actions.py
  settings.py
Labels: product/custom

#31126 Update text to reflect possible actions
  corehq/apps/data_interfaces/templates/data_interfaces/list_automatic_update_rules.html
Labels: product/all-users-all-environments

#31123 Move case accessors into CommCareCase.objects - part 7 (final)
  corehq/apps/case_importer/management/commands/update_case_property.py
  corehq/apps/case_importer/util.py
  corehq/apps/hqcase/bulk.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_utils.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/interfaces/dbaccessors.py
  corehq/form_processor/tests/test_case_dbaccessor.py
  corehq/form_processor/tests/test_cases.py
  corehq/form_processor/tests/test_reindex_accessors.py
  corehq/form_processor/tests/test_sql_update_strategy.py
  docs/forms_and_cases.rst
Labels: product/invisible, Risk: High

#31131 Improve Tests
  corehq/apps/analytics/tests/test_hubspot.py
  corehq/apps/userreports/tests/test_pillow.py
Labels: product/invisible

#31121 Fix missing instance in data registry query for shadow menu
  corehq/apps/app_manager/management/commands/migrate_case_search_prompt_itemset_ids.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/data/suite_registry/form_link_followup_module_registry.xml
  corehq/apps/app_manager/tests/data/suite_registry/shadow_module_entry.xml
  corehq/apps/app_manager/tests/data/suite_registry/shadow_module_remote_request.xml
  corehq/apps/app_manager/tests/test_management_commands.py
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/fixtures/fixturegenerators.py
Labels: product/feature-flag, Risk: Medium

#31102 add attempt number to scheduled messages report
  corehq/apps/reports/standard/sms.py
Labels: product/all-users-all-environments

#31086 add non blocking case rate limits
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/form_processor/submission_post.py
Labels: product/invisible, Risk: High

#31124 Raise 404 if no couch user
  corehq/apps/linked_domain/decorators.py
Labels: product/invisible

#31091 fix formatting issue with partner analytics CSV
  corehq/apps/analytics/tests/test_partner_analytics_utils.py
  corehq/apps/analytics/utils/partner_analytics.py
Labels: product/invisible

#31132 Updated default logic in migrate_case_search_prompt_itemset_ids
  corehq/apps/app_manager/management/commands/migrate_case_search_prompt_itemset_ids.py
Labels: product/invisible

#31133 Update translations script tx push -s -t instead of -st
  scripts/update-translations.sh
Labels: product/invisible

#31134 Add malt_generation_queue to heartbeat thresholds
  settings.py
Labels: product/invisible

#31141 Delete secure_submissions_all_apps.py
  corehq/apps/app_manager/management/commands/secure_submissions_all_apps.py
Labels: product/invisible

#31139 Delete find_case_metadata_with_errors.py
  corehq/apps/app_manager/management/commands/find_case_metadata_with_errors.py
Labels: product/invisible

#31142 Removed app_builder_live_test
  app_builder_live_test/README.txt
  app_builder_live_test/compare_perf_stats.py
  app_builder_live_test/diff
  app_builder_live_test/fetch_app_source.sh
  app_builder_live_test/hitlist.txt
  corehq/apps/app_manager/management/commands/build_apps.py
Labels: product/invisible

#31136 Removes use of deprecated property
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
Labels: product/invisible

#31122 Remove pygments dependency from base-requirements.in
  corehq/apps/hqadmin/templates/hqadmin/email/error_email.html
  corehq/util/log.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
Labels: product/invisible, dependencies

#31143 Updates to migrate_case_search_prompt_itemset_ids
  corehq/apps/app_manager/management/commands/helpers.py
  corehq/apps/app_manager/management/commands/migrate_case_search_prompt_itemset_ids.py
  corehq/apps/app_manager/tests/test_management_commands.py
Labels: product/invisible

#31145 SQL Lookup Table models reorganization
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/fixtures/couchmodels.py
  corehq/apps/fixtures/migrations/0004_userlookuptablestatus.py
  corehq/apps/fixtures/models.py
  corehq/apps/locations/tasks.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/fixture_status.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  migrations.lock
Labels: reindex/migration, product/invisible, Risk: Medium

#31137 Support for float values in peer rating
  custom/gcc_sangath/rules/custom_actions.py
  custom/gcc_sangath/tests/test_custom_actions.py
Labels: product/custom

#31135 Cleanup UUID pickling errors
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/data_interfaces/models.py
  corehq/messaging/scheduling/models/alert_schedule.py
  corehq/messaging/scheduling/models/timed_schedule.py
  corehq/messaging/scheduling/scheduling_partitioned/dbaccessors.py
  corehq/messaging/scheduling/tasks.py
  corehq/messaging/scheduling/tests/test_schedules.py
  corehq/messaging/scheduling/views.py
Labels: product/invisible

#31150 Re-upgrade protobuf after accidental revert
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31089 [GSheets] Add new app for OAuth Integration
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/export/exceptions.py
  corehq/apps/oauth_integrations/__init__.py
  corehq/apps/oauth_integrations/migrations/0001_initial.py
  corehq/apps/oauth_integrations/migrations/__init__.py
  corehq/apps/oauth_integrations/models.py
  corehq/apps/oauth_integrations/tests/__init__.py
  corehq/apps/oauth_integrations/tests/test_util.py
  corehq/apps/oauth_integrations/tests/test_views.py
  corehq/apps/oauth_integrations/urls.py
  corehq/apps/oauth_integrations/utils.py
  corehq/apps/oauth_integrations/views/__init__.py
  corehq/apps/oauth_integrations/views/google.py
  migrations.lock
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
  urls.py
Labels: reindex/migration, product/invisible, dependencies

#31100 USH: Make new version of case migration script
  corehq/apps/hqcase/bulk.py
  corehq/apps/hqcase/tests/test_bulk.py
  custom/covid/management/commands/update_all_activity_complete_date.py
  custom/covid/tests/test_management_commands.py
Labels: product/custom

#31151 report case thresholds to datadog
  corehq/apps/receiverwrapper/rate_limiter.py
Labels: product/invisible

#31154 Cs/support 12674 check permission on web user
  corehq/apps/users/forms.py
  corehq/apps/users/tests/test_views.py
Labels: product/all-users-all-environments

#31129 Django migration for case search prompt itemset migration
  corehq/apps/app_manager/migrations/0021_migrate_case_search_itemset_ids.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#31106 Registry Permissions: restrict domains for filtering report
  corehq/apps/userreports/reports/filters/choice_providers.py
  corehq/apps/userreports/tests/test_choice_provider.py
Labels: QA Passed, product/feature-flag

#31159 use correct name of rate limiter
  corehq/apps/receiverwrapper/rate_limiter.py
Labels: product/invisible

#31153 Added Google Sheet Static Toggle
  corehq/toggles/__init__.py
Labels: product/feature-flag

#31155 refactor cases search query builder
  corehq/apps/case_search/models.py
  corehq/apps/case_search/tests/test_case_search_endpoint.py
  corehq/apps/case_search/tests/test_case_search_es_queries.py
  corehq/apps/case_search/tests/test_case_search_filters.py
  corehq/apps/case_search/tests/test_case_search_registry.py
  corehq/apps/case_search/tests/test_get_related_cases.py
  corehq/apps/case_search/tests/test_models.py
  corehq/apps/case_search/tests/utils.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/es/tests/utils.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
Labels: product/invisible

#31158 Optimize Web app refresh feature and make some enhancements
  corehq/apps/app_manager/dbaccessors.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/hqwebapp/static/hqwebapp/js/inactivity.js
  corehq/apps/hqwebapp/views.py
Labels: product/invisible

#31165 Couch to SQL migration improvements
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  docs/couch_to_sql_models.rst
Labels: product/invisible

#31067 Additional permissions for building registry reports
  corehq/apps/app_manager/fields.py
  corehq/apps/registry/utils.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/views.py
Labels: QA Passed, product/feature-flag

#31166 Improve domain tests
  corehq/apps/domain/tests/test_delete_domain.py
Labels: product/invisible

#31163 [bug fix] check that module_id is not None
  corehq/apps/app_manager/app_schemas/session_schema.py
  corehq/apps/app_manager/app_schemas/tests/test_schema.py
Labels: product/invisible

#31103 Add domain settings for restricting UCR expressions
  corehq/apps/domain/deletion.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/migrations/0011_alloweducrexpressionsettings.py
  corehq/apps/domain/models.py
  corehq/apps/domain/signals.py
  corehq/apps/domain/static/domain/js/internal_settings.js
  corehq/apps/domain/tests/test_utils.py
  corehq/apps/domain/utils.py
  corehq/apps/domain/views/internal.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#31167 Change configurable case forwarder name for consistency
  corehq/motech/repeaters/expression/repeaters.py
Labels: product/feature-flag

#31070 Remove pickling from motech module
  corehq/motech/dhis2/management/commands/send_datasets.py
  corehq/motech/dhis2/tasks.py
  corehq/motech/openmrs/tasks.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/tests/test_tasks.py
Labels: QA Passed, product/invisible

#31146 Allow superuser to bypass lite release management (MRM) push constraints
  corehq/apps/linked_domain/exceptions.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/tests/test_views.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#31069 Added metrics to export creation
  corehq/apps/export/static/export/js/export_list_main.js
  corehq/apps/export/templates/export/export_list.html
  corehq/apps/export/views/new.py
  corehq/apps/export/views/utils.py
Labels: product/invisible
