Repository dimagi/commcare-hq, pull requests merged in 2022-04, with the labels that each got.

#31355 restrict editing of DR reports via the advanced UI
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/util.py
  corehq/apps/userreports/views.py
Labels: product/feature-flag

#31386 DEFAULT_AUTO_FIELD to avoid deprecation warnings
  settings.py
Labels: product/invisible

#31357 feature flag dependencies
  corehq/apps/domain/tests/test_domain_transfer.py
  corehq/apps/enterprise/tests/test_enterprise_mobile_worker_settings.py
  corehq/apps/hqcase/tests/test_loadtest_users.py
  corehq/apps/toggle_ui/admin.py
  corehq/apps/toggle_ui/templates/toggle/edit_flag.html
  corehq/apps/toggle_ui/views.py
  corehq/apps/users/tests/test_views.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_new_sync.py
  corehq/toggles/__init__.py
Labels: product/invisible

#31313 pin sub-sub dependency minimist to 1.2.6 or greater due to CVE
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#31368 update Dev Setup instructions
  DEV_SETUP.md
  DEV_SETUP_MAC.md
Labels: product/invisible

#31340 waf_allow on audio and video upload endpoints
  corehq/apps/hqmedia/urls.py
Labels: product/invisible

#31384 Replace hard-coded value for app_version with actual version in CaseSessionDataHelper
  corehq/apps/cloudcare/touchforms_api.py
  corehq/apps/smsforms/tests/test_app.py
Labels: product/invisible, Risk: Medium

#31390 Fix broken table formatting in doc
  docs/forms_and_cases.rst
Labels: product/invisible

#31389 case search query context
  corehq/apps/case_search/dsl_utils.py
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/tests/test_value_functions.py
  corehq/apps/case_search/xpath_functions/query_functions.py
  corehq/apps/case_search/xpath_functions/subcase_functions.py
  corehq/apps/case_search/xpath_functions/value_functions.py
Labels: product/invisible

#31307 Add test for parent case updates for dedupe rules
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
Labels: product/invisible

#31392 SC-1947 SC-1948 Deduplication edit and create rules changes
  corehq/apps/data_interfaces/tests/test_deduplication_rules.py
  corehq/apps/data_interfaces/views.py
Labels: product/feature-flag

#31394 don't 500 in multimedia size request for app that isn't a build
  corehq/apps/app_manager/views/multimedia.py
  corehq/apps/app_manager/views/utils.py
Labels: product/feature-flag

#31393 test child module parent select other rewrite filter
  corehq/apps/app_manager/suite_xml/utils.py
  corehq/apps/app_manager/tests/data/suite/child-module-entry-datums-parent-select-other-same-case-type.xml
  corehq/apps/app_manager/tests/data/suite/child-module-entry-datums-parent-select-other.xml
  corehq/apps/app_manager/tests/test_child_module.py
Labels: product/invisible

#31388 case search "date_add" function
  corehq/apps/case_search/dsl_utils.py
  corehq/apps/case_search/tests/test_value_functions.py
  corehq/apps/case_search/xpath_functions/__init__.py
  corehq/apps/case_search/xpath_functions/value_functions.py
Labels: product/feature-flag

#31349 Multi select web apps UI-- checkboxes
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_detail.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
Labels: product/feature-flag, Risk: Medium

#31403 Added help link for multiple referrals feature flag
  corehq/toggles/__init__.py
Labels: product/admin

#31274 Patched os.path.exists in testBuildTemplateApps
  corehq/apps/app_manager/tests/test_apps.py
Labels: product/invisible

#31304 Multiple case claim handling on mobile endpoint
  corehq/apps/ota/tests/test_claim.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/apps/ota/views.py
  corehq/ex-submodules/casexml/apps/case/cleanup.py
Labels: product/feature-flag

#31409 Fix issues with UCR data source summary page
  corehq/apps/userreports/views.py
Labels: product/feature-flag

#31412 Add ethiopian calendar expressions
  corehq/apps/userreports/expressions/date_specs.py
  corehq/apps/userreports/expressions/factory.py
  corehq/apps/userreports/tests/test_date_expressions.py
  corehq/apps/userreports/transforms/custom/date.py
Labels: product/feature-flag

#31414 remove pending invites task
  corehq/apps/users/tasks.py
Labels: product/invisible

#31401 fix enterprise rate limits
  corehq/apps/data_dictionary/views.py
  corehq/apps/domain/views/internal.py
  corehq/apps/hqwebapp/two_factor_gateways.py
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/tests/test_get_n_users_for_rate_limiting.py
  corehq/project_limits/tests/test_rate_limiter.py
Labels: product/invisible

#30524 Remove serializer='pickle' from phonelog
  corehq/ex-submodules/phonelog/tasks.py
  corehq/ex-submodules/phonelog/utils.py
Labels: QA Passed, product/invisible

#31417 Freeze usages of serializer='pickle' to prevent backsliding
  .gitignore
  Makefile
  docker/run.sh
  scripts/make-serializer-pickle-files
  scripts/test-serializer-pickle-files.sh
  serializer-pickle-files.lock
Labels: product/invisible

#31421 Renamed _create_casexml_2* functions
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/xform.py
Labels: product/invisible

#31411 Multiple referrals: suite.xml remote-request changes
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/data/suite/multi_select_case_list.xml
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
  corehq/apps/app_manager/xpath.py
Labels: product/feature-flag

#31427 separate redis DB for tests
  dev_settings.py
  docker/localsettings.py
  settingshelper.py
  testsettings.py
Labels: product/invisible

#31420 De-pickle (and clean up) metrics_gauge_task
  corehq/apps/case_importer/tasks.py
  corehq/apps/sms/tasks.py
  corehq/motech/repeaters/tasks.py
  corehq/util/metrics/__init__.py
  serializer-pickle-files.lock
Labels: product/invisible

#31415 Update to schema==0.7.5 and contextlib2==21.6.0
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31423 Upgrade python dependencies requiring single point release bump
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31402 Index geopoint case properties in case search index
  corehq/apps/app_manager/migrations/0007_add_linked_app_fields_to_es.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
  corehq/apps/es/case_search.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/userreports/reports/specs.py
  corehq/ex-submodules/couchforms/datatypes.py
  corehq/ex-submodules/couchforms/geopoint.py
  corehq/ex-submodules/couchforms/jsonobject_extensions.py
  corehq/ex-submodules/couchforms/tests/__init__.py
  corehq/ex-submodules/couchforms/tests/test_geopoint.py
  corehq/ex-submodules/couchforms/tests/test_meta.py
  corehq/ex-submodules/pillowtop/migrations/0006_add_geopoint_to_case_search_index.py
  corehq/pillows/case_search.py
  corehq/pillows/mappings/case_search_mapping.json
  corehq/pillows/xform.py
  corehq/toggles/__init__.py
  corehq/util/django_migrations.py
  migrations.lock
  testapps/test_pillowtop/tests/test_case_search_pillow.py
Labels: reindex/migration, product/feature-flag, product/invisible, Risk: High

#31419 Removed cmitfb scripts
  corehq/apps/app_manager/management/commands/migrate_all_apps_to_cmitfb.py
  corehq/apps/app_manager/management/commands/migrate_app_to_cmitfb.py
Labels: product/invisible

#31428 Improve error on metrics provider lookup failure
  corehq/util/metrics/__init__.py
Labels: product/invisible

#31431 Fix missing default value on Django 3.0
  corehq/apps/fixtures/tests/test_views.py
  corehq/apps/fixtures/views.py
Labels: product/invisible, Risk: Medium

#31348 User History Report "Export to Excel"
  corehq/apps/reports/standard/users/reports.py
Labels: product/feature-flag

#31433 New script for dependency version parsing
  scripts/pip-dep-debt.py
Labels: product/invisible

#31247 Upgrade to architect 0.6.0
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31422 De-pickle serial_task
  corehq/apps/app_manager/tasks.py
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/locations/tasks.py
  corehq/apps/userreports/tasks.py
  corehq/util/decorators.py
  serializer-pickle-files.lock
Labels: product/invisible

#31429 Update translations workflow
  .github/workflows/update-translations.yml
  scripts/update-translations.sh
Labels: product/invisible

#31437 Improve performance of collapsible groups in web apps
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#31442 Make .editorconfig match our YAML style of 2-space indents
  .editorconfig
Labels: product/invisible

#31323 Create LiveGoogleSheetView edit classes
  corehq/apps/export/urls.py
  corehq/apps/export/views/edit.py
  corehq/apps/export/views/list.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#31446 Standardize .yml extension
  corehq/apps/app_manager/commcare_settings.py
  corehq/apps/app_manager/static/app_manager/json/commcare-app-settings.yml
  corehq/apps/app_manager/static/app_manager/json/commcare-profile-settings.yml
  corehq/apps/app_manager/static/app_manager/json/commcare-settings-layout.yml
  corehq/apps/app_manager/static/app_manager/json/vellum-app-callout-templates.yml
  corehq/apps/app_manager/tests/test_commcare_settings.py
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/management/commands/resource_static.py
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/yaml/requirejs.yml
  corehq/apps/linked_domain/README.md
  corehq/apps/reports/tests/readable_forms/mismatched_group_hierarchy.py2.result.yml
  corehq/apps/reports/tests/readable_forms/mismatched_group_hierarchy.py3.result.yml
  corehq/apps/reports/tests/readable_forms/top_level_refless_group.py2.result.yml
  corehq/apps/reports/tests/readable_forms/top_level_refless_group.py3.result.yml
  corehq/apps/reports/tests/test_readable_formdata.py
  corehq/apps/userreports/tests/data/static_data_sources/sample_static_data_source.yml
  corehq/apps/userreports/tests/data/static_reports/static_report_config.yml
  corehq/apps/userreports/tests/test_static_data_sources.py
  corehq/apps/userreports/tests/test_static_reports.py
  custom/abt/reports/expressions.py
  custom/abt/reports/flagspecs.yml
  custom/abt/reports/flagspecs_uganda.yml
  custom/abt/reports/flagspecs_v2.yml
  custom/abt/reports/flagspecs_v2019.yml
  custom/abt/reports/flagspecs_v2020.yml
  docs/apps/settings.rst
  docs/js-guide/migrating.rst
  docs/js-guide/static-files.rst
  get_resource_versions.py
  scripts/commit-staging
  scripts/rebuildstaging
  scripts/staging.yml
  scripts/vellum-to-hq
  scripts/yaml_static_strings.py
Labels: product/invisible, Risk: High

#31448 Bump jsonobject to 2.0.0 and make requirements
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31208 Upgrade to Django 3.2
  migrations.lock
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: reindex/migration, QA Passed, product/invisible, dependencies

#31444 Improve update translations workflow
  .github/workflows/update-translations.yml
Labels: product/invisible

#31449 Updated get_apps_modules
  corehq/apps/app_manager/views/forms.py
Labels: product/feature-flag

#31434 [SSO] add feature flag for OIDC development
  corehq/toggles/__init__.py
Labels: product/invisible

#31436 [SSO] Update IdentityProvider to include new fields for OIDC
  corehq/apps/sso/migrations/0003_oidc_onelogin_idp_update.py
  corehq/apps/sso/models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31453 Revert bad depickle if add_inferred_export_properties
  corehq/apps/export/tasks.py
  serializer-pickle-files.lock
Labels: product/invisible

#31408 Upgrade Node.js to v14
  DEV_SETUP.md
  Dockerfile
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#31435 Multiple referrals: add instance-datum to suite XML
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/data/suite/multi_select_case_list.xml
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
Labels: product/feature-flag

#31454 allow specifying the index identifier for the DR repeater
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_payload_generator.py
Labels: product/feature-flag

#31455 Updated multiple referrals to not use AUTO_LAUNCH_EXPRESSION
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
Labels: product/feature-flag

#31441 Add docs on recommended migration patterns
  docs/migrations.rst
  docs/migrations_in_practice.rst
Labels: product/invisible

#31460 Case search `proximity()` function
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/tests/test_xpath_functions.py
  corehq/apps/case_search/xpath_functions/__init__.py
  corehq/apps/case_search/xpath_functions/query_functions.py
  corehq/apps/case_search/xpath_functions/utils.py
  corehq/apps/case_search/xpath_functions/value_functions.py
  corehq/apps/es/case_search.py
  corehq/apps/es/queries.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/es/tests/test_queries.py
  corehq/ex-submodules/couchforms/geopoint.py
  testapps/test_pillowtop/tests/test_case_search_pillow.py
  testapps/test_pillowtop/tests/test_xform_pillow.py
Labels: product/feature-flag

#31462 Include workaround instructions in update-translations PRs
  .github/workflows/update-translations.yml
Labels: product/invisible

#31457 Multi-select case lists: select parent first
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/tests/data/suite/multi_select_case_list/basic_remote_request.xml
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
Labels: product/feature-flag

#31425 Elasticsearch mapping modernization: multi_field
  corehq/ex-submodules/pillowtop/migrations/0007_elastic_v5_mapping_compatibility.py
  corehq/pillows/management/commands/print_elastic_mappings.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/case_search_mapping.py
  corehq/pillows/mappings/domain_mapping.py
  corehq/pillows/mappings/group_mapping.py
  corehq/pillows/mappings/reportcase_mapping.py
  corehq/pillows/mappings/reportxform_mapping.py
  corehq/pillows/mappings/sms_mapping.py
  corehq/pillows/mappings/tests/test_case_search_mapping.py
  corehq/pillows/mappings/user_mapping.py
  corehq/pillows/mappings/xform_mapping.py
  corehq/util/django_migrations.py
  corehq/util/tests/test_django_migrations.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/invisible, Risk: High

#31456 Added build errors for multiple referrals used with data registries
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/tests/test_build_errors.py
Labels: product/feature-flag

#31464 Formplayer-in-HQ docs on navigation
  docs/formplayer.rst
Labels: product/invisible

#31466 Fix UPDATE_TRANSLATIONS_SKIP_GIT bug
  scripts/update-translations.sh
Labels: product/invisible

#31459 Setup Celery as part of Django setup
  corehq/__init__.py
  corehq/apps/README.rst
  corehq/apps/celery/__init__.py
  corehq/apps/celery/tests/__init__.py
  corehq/apps/celery/tests/test_celery_app.py
  corehq/apps/users/tests/test_signals.py
  corehq/celery.py
  deployment/gunicorn/commcarehq_wsgi.py
  manage.py
  settings.py
Labels: product/invisible

#31468 Revert "Elasticsearch mapping modernization: multi_field"
  corehq/ex-submodules/pillowtop/migrations/0007_elastic_v5_mapping_compatibility.py
  corehq/pillows/management/commands/print_elastic_mappings.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/case_search_mapping.py
  corehq/pillows/mappings/domain_mapping.py
  corehq/pillows/mappings/group_mapping.py
  corehq/pillows/mappings/reportcase_mapping.py
  corehq/pillows/mappings/reportxform_mapping.py
  corehq/pillows/mappings/sms_mapping.py
  corehq/pillows/mappings/tests/test_case_search_mapping.py
  corehq/pillows/mappings/user_mapping.py
  corehq/pillows/mappings/xform_mapping.py
  corehq/util/django_migrations.py
  corehq/util/tests/test_django_migrations.py
  migrations.lock
Labels: product/invisible

#31467 Resolve some deprecation warnings
  corehq/apps/analytics/tasks.py
  corehq/apps/analytics/tests/test_hubspot.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/test_suite_formats.py
  corehq/apps/domain_migration_flags/api.py
  corehq/apps/export/tests/test_export_form_subcases.py
  corehq/apps/export/tests/test_get_export_file.py
  corehq/apps/hqadmin/views/users.py
  corehq/apps/hqwebapp/tests/test_compress_command.py
  corehq/apps/notifications/views.py
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/ex-submodules/couchexport/writers.py
  corehq/ex-submodules/dimagi/utils/decorators/profile.py
  corehq/ex-submodules/dimagi/utils/system.py
  corehq/motech/openmrs/tests/test_tasks.py
  corehq/sql_db/tests/test_checks.py
  corehq/sql_db/tests/test_connections.py
  corehq/sql_db/tests/test_partition_config.py
  corehq/sql_db/tests/test_routers.py
  corehq/sql_db/tests/utils.py
  corehq/tests/util/tests/__init__.py
  corehq/tests/util/tests/test_warnings.py
  corehq/tests/util/warnings.py
  corehq/util/tests/test_argparse_types.py
  corehq/util/tests/test_couchdb_management.py
Labels: product/invisible

#31469 Updated datum ids for multi-select datums in entries
  corehq/apps/app_manager/suite_xml/utils.py
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
Labels: product/feature-flag

#31473 Update requirements to ipython==8.2.0
  requirements/prod-requirements.txt
Labels: product/invisible, dependencies

#31476 Use new Django 3 enum type for choices
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
Labels: product/invisible

#31471 Mark closed cases as duplicates during backfill
  corehq/apps/data_interfaces/deduplication.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
Labels: product/feature-flag

#31472 Organize migration docs together
  docs/index.rst
  docs/migrations_in_practice.rst
Labels: product/invisible

#31479 Updated relevant condition for multi-select remote request post
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/tests/data/suite/multi_select_case_list/basic_remote_request.xml
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/xpath.py
Labels: product/feature-flag

#31205 OBH: Exclude Sub-case Query From Search Filter
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
Labels: QA Passed, product/feature-flag

#31439 Case claim title translate prep work
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/models.py
Labels: product/invisible

#31461 add new default option
  corehq/apps/hqcase/management/commands/ptop_reindexer_v2.py
Labels: product/invisible

#31452 Multi-Select Case list: Select all checkbox
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: product/feature-flag, Risk: Medium

#31481 Upgrade pip (22.0.4) and pip-tools (6.6.0)
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31482 Add deprecation whiltelist and raise errors on non-whitelisted deprecation warnings
  .github/CODEOWNERS
  corehq/apps/accounting/mixins.py
  corehq/apps/app_manager/__init__.py
  corehq/apps/callcenter/views.py
  corehq/apps/commtrack/sms.py
  corehq/apps/data_dictionary/tests/test_import_export.py
  corehq/apps/data_interfaces/__init__.py
  corehq/apps/data_interfaces/tests/test_xform_management.py
  corehq/apps/domain/tests/test_views.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/apps/export/tests/test_incremental.py
  corehq/apps/hqwebapp/tests/test_csrf_middleware.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/standard/monitoring.py
  corehq/apps/reports/util.py
  corehq/apps/sso/tests/generator.py
  corehq/apps/sso/tests/test_request_helpers.py
  corehq/apps/userreports/tests/test_alembic_diffs.py
  corehq/apps/users/__init__.py
  corehq/apps/users/apps.py
  corehq/apps/users/tests/test_download_with_profile.py
  corehq/form_processor/tests/test_basics.py
  corehq/form_processor/tests/test_sharding.py
  corehq/messaging/__init__.py
  corehq/motech/fhir/__init__.py
  corehq/motech/models.py
  corehq/tests/util/tests/test_warnings.py
  corehq/tests/util/warnings.py
  corehq/util/jqueryrmi.py
  corehq/warnings.py
  custom/cowin/__init__.py
  manage.py
  settings.py
Labels: product/invisible, Risk: High

#31451 [SSO] Update Accounting Admin UIs to support OIDC and OneLogin
  corehq/apps/sso/forms.py
  corehq/apps/sso/models.py
  corehq/apps/sso/static/sso/js/new_identity_provider.js
  corehq/apps/sso/tasks.py
  corehq/apps/sso/templates/sso/accounting_admin/new_identity_provider.html
  corehq/apps/sso/tests/test_forms.py
  corehq/apps/sso/urls.py
  corehq/apps/sso/utils/url_helpers.py
  corehq/apps/sso/views/accounting_admin.py
  corehq/apps/sso/views/oidc.py
Labels: product/admin

#31480 Remove ERM_DEVELOPMENT toggle
  corehq/apps/linked_domain/tests/test_release_manager.py
  corehq/toggles/__init__.py
Labels: product/invisible

#31485 Enable saving Linked Project Space History reports
  corehq/apps/saved_reports/models.py
Labels: product/invisible

#31487 Check username
  corehq/apps/export/tests/test_incremental.py
  corehq/motech/const.py
  corehq/motech/forms.py
  corehq/motech/models.py
Labels: product/invisible

#31491 rename 'date_add' to 'date-add' for consistency
  corehq/apps/case_search/tests/test_value_functions.py
  corehq/apps/case_search/xpath_functions/__init__.py
  corehq/apps/case_search/xpath_functions/value_functions.py
Labels: product/invisible

#31488 rename proximity to within-distance
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/tests/test_xpath_functions.py
  corehq/apps/case_search/xpath_functions/__init__.py
  corehq/apps/case_search/xpath_functions/query_functions.py
Labels: product/feature-flag

#31496 Fix syntax error
  corehq/tests/noseplugins/uniformresult.py
Labels: product/invisible

#31486 Respect default answers in GPS questions
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
Labels: product/invisible, Risk: Medium

#31484 Add post-make-requirements script to purge appnope
  requirements/Makefile
  scripts/purge-platform-pkgs.py
Labels: product/invisible, dependencies

#31495 Pin minimum Django version to 3.2.13
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31497 Whitelist error with ipython in pyenv virtualenv
  corehq/warnings.py
Labels: product/invisible

#31498 Change default django Referrer-Policy header
  settings.py
Labels: product/invisible

#31478 Multi select checkbox clearing bug fix
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: product/feature-flag, Risk: Medium

#31500 Move geopoint functionality under general USH flag
  corehq/apps/data_dictionary/util.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/pillows/case_search.py
  corehq/toggles/__init__.py
  testapps/test_pillowtop/tests/test_case_search_pillow.py
Labels: product/feature-flag

#31503 fix bad escape sequences
  corehq/apps/fixtures/tests/test_field_names.py
  corehq/blobs/tests/test_s3db.py
Labels: product/invisible, Risk: Medium

#31458 Case claim request: Return 204 based on user's sync token
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/apps/ota/views.py
Labels: product/feature-flag

#31395 Remove linked_domains toggle
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/linked_domain/README.md
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/management/commands/migrate_feature_flag_domains.py
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/partials/manage_downstream_domains.html
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/tests/test_decorators.py
  corehq/apps/linked_domain/tests/test_linked_domain_utils.py
  corehq/apps/linked_domain/tests/test_release_manager.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reminders/templates/reminders/keyword_list.html
  corehq/apps/reminders/templates/reminders/link_keywords_modal.html
  corehq/apps/reminders/urls.py
  corehq/apps/reminders/views.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/userreports/templates/userreports/edit_report_config.html
  corehq/apps/userreports/templates/userreports/partials/link_reports.html
  corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
  corehq/apps/userreports/urls.py
  corehq/apps/userreports/views.py
  corehq/tabs/tabclasses.py
  corehq/tabs/tests.py
  corehq/toggles/__init__.py
Labels: QA Passed, product/invisible

#31502 Purge packages script improvements
  scripts/purge-platform-pkgs.py
  scripts/tests/__init__.py
  scripts/tests/test_purge_platform_pkgs.py
Labels: product/invisible

#31507 Elasticsearch mapping modernize utils
  corehq/pillows/management/commands/print_elastic_mappings.py
  corehq/util/django_migrations.py
  corehq/util/tests/test_django_migrations.py
Labels: product/invisible

#31505 Removed soft assert
  corehq/apps/app_manager/models.py
Labels: product/invisible

#31501 remove old enterprise count
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/tests/test_rate_limiter.py
Labels: product/invisible

#31511 Fixed get_multimedia_sizes_for_build params
  corehq/apps/app_manager/views/multimedia.py
Labels: product/feature-flag

#31504 Sk/case search refactor
  corehq/apps/case_search/dsl_utils.py
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/hqcase/tests/test_case_list_api.py
Labels: product/invisible

#31514 implement fuzzy-match case search query function
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/xpath_functions/__init__.py
  corehq/apps/case_search/xpath_functions/query_functions.py
Labels: product/feature-flag

#31508 Multiple referrals: block default case management
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config.html
  corehq/apps/app_manager/tests/data/form_preparation_v2/multi_no_actions.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/multi_open_update_case.xml
  corehq/apps/app_manager/tests/test_form_preparation_v2.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/xform.py
Labels: product/feature-flag

#31517 Added docs link
  docs/formplayer.rst
Labels: product/invisible

#31512 Remove CRS report
  corehq/apps/reports/dispatcher.py
  corehq/apps/reports/dont_use/README.rst
  corehq/apps/reports/dont_use/__init__.py
  corehq/apps/reports/dont_use/fields.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/templates/reports/dont_use_fields/select_generic.html
  corehq/apps/reports/templates/reports/partials/checkbox.html
  custom/apps/crs_reports/fields.py
  custom/apps/crs_reports/reports.py
  custom/apps/crs_reports/views.py
Labels: product/custom

#31523 support looking up SMS and SQLMobileBackend models via raw docs view
  corehq/apps/hqwebapp/doc_lookup.py
  corehq/apps/sms/models.py
  corehq/apps/sms/serializers.py
Labels: product/invisible

#31520 Updated shadow modules to inherit multi-select property from source
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
Labels: product/feature-flag

#31519 Updated advanced modules to not support multi-select case lists
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
  corehq/apps/app_manager/tests/test_advanced_suite.py
Labels: product/feature-flag

#31345 Do not allow editing username via User API
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/user_resources.py
Labels: product/invisible, Risk: High

#31522 Remove the rest of the CRS custom report code
  corehq/apps/reports/urls.py
  corehq/apps/reports/util.py
  custom/apps/__init__.py
  custom/apps/crs_reports/__init__.py
  custom/apps/crs_reports/reports.py
  custom/apps/crs_reports/templates/crs_reports/base_template.html
  custom/apps/crs_reports/templates/crs_reports/partials/mothers_form_reports_template.html
  custom/apps/crs_reports/urls.py
  custom/apps/crs_reports/views.py
  settings.py
Labels: product/invisible

#31525 Remove ReportFormESView
  corehq/apps/api/es.py
  corehq/pillows/base.py
  testapps/test_pillowtop/tests/test_pillows_cases.py
  testapps/test_pillowtop/tests/test_pillows_xforms.py
Labels: product/invisible, Risk: High

#31046 Retry upgrading Openpyxl to 3.0.9
  corehq/ex-submodules/couchexport/tests/test_excel_format_value.py
  corehq/ex-submodules/couchexport/util.py
  corehq/util/workbook_reading/adapters/xlsx.py
  corehq/util/workbook_reading/tests/test_spreadsheets.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, product/invisible, dependencies

#31430 Multi select case list "Continue" workflow
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/util.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: product/feature-flag, Risk: Medium

#31518 Added multi-select option to case list overwrite
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_module_overwrite.html
  corehq/apps/app_manager/tests/test_modules.py
Labels: product/feature-flag

#31526 Fixed menu for user history report
  corehq/apps/reports/standard/users/reports.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#31499 upgrade dompurify to latest npm version
  package.json
  yarn.lock
Labels: QA Passed, product/invisible, dependencies, dependencies/javascript

#31528 Add deprecation warnings documentation
  DEV_SETUP.md
  corehq/warnings.py
Labels: product/invisible

#31516 Create better messaging for historical migrations
  corehq/apps/app_manager/migrations/0021_migrate_case_search_itemset_ids.py
  corehq/apps/users/migrations/0003_roles_permissions_update.py
  corehq/apps/users/migrations/0028_migrate_roles_to_sql.py
  corehq/apps/users/migrations/0041_migrate_reprs.py
  corehq/util/django_migrations.py
  docs/migrations_in_practice.rst
Labels: reindex/migration, product/invisible

#31529 Add support to update mobile worker 'default_phone_number' via API
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/user_resources.py
Labels: product/invisible, Risk: High

#31524 OpenMRS Importer must handle empty names
  corehq/motech/openmrs/tasks.py
  corehq/motech/openmrs/tests/test_tasks.py
Labels: product/invisible

#31513 [auditcare][couch-to-sql]Remove code reading couch data
  corehq/apps/auditcare/tests/test_export.py
  corehq/apps/auditcare/utils/export.py
  corehq/apps/auditcare/utils/migration.py
Labels: product/invisible

#31531 use unique datum ID for remote requests when using multi-select
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/tests/data/suite/multi_select_case_list/basic_remote_request.xml
  corehq/apps/app_manager/xpath.py
Labels: product/invisible

#31308 tests & validation for "one number multiple contacts"
  corehq/apps/sms/api.py
  corehq/apps/sms/handlers/fallback.py
  corehq/apps/sms/handlers/form_session.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/messages.py
  corehq/apps/sms/tests/test_form_session_handler.py
  corehq/apps/sms/tests/test_inbound_sms_phone_entry_assignment.py
  corehq/apps/sms/verify.py
  corehq/apps/smsforms/models.py
Labels: product/feature-flag

#31538 Fixed ShadowModule.is_multi_select
  corehq/apps/app_manager/models.py
Labels: product/feature-flag

#31533 Include deleted DomainLink objects in django admin
  corehq/apps/linked_domain/admin.py
Labels: product/invisible

#31544 Remove UsersMiddlewhere app check
  corehq/apps/users/middleware.py
Labels: product/invisible

#31548 Remove compatibility fixes for Django 2.2 and 3.1
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/auditcare/tests/testutils.py
  corehq/apps/hqwebapp/forms.py
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/apps/reports/tests/test_export_response.py
  corehq/form_processor/tests/utils.py
  manage.py
Labels: product/invisible, Risk: High

#31546 Multiple referrals UI fixes
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
Labels: product/feature-flag, Risk: Medium

#31542 display html for unknown form usernames
  corehq/apps/reports/display.py
Labels: product/invisible

#31549 Updated icons on module settings header to match menu
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_heading.html
Labels: product/feature-flag

#31535 case v6 rate limits
  corehq/apps/api/decorators.py
  corehq/apps/api/resources/auth.py
  corehq/apps/api/resources/meta.py
  corehq/apps/hqcase/api/updates.py
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/hqcase/views.py
Labels: product/invisible, Risk: High

#31483 apply rate limiting delay to auto update rules and condtional alerts
  corehq/apps/data_interfaces/models.py
  corehq/apps/hqcase/utils.py
Labels: product/invisible

#31539 Refactor access methods for linked domains feature
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/tests/test_decorators.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reports/dispatcher.py
  corehq/tabs/tabclasses.py
  corehq/tabs/tests.py
Labels: product/invisible

#31532 Make toggles available to build errors
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/views/cli.py
  corehq/apps/app_manager/views/download.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/toggle_ui/tests.py
  corehq/apps/toggle_ui/views.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#31555 Revert "use real types instead of namedtuples"
  corehq/apps/smsforms/models.py
Labels: product/invisible

#31558 use correct argument name
  corehq/apps/app_manager/views/cli.py
  corehq/apps/hqadmin/views/system.py
Labels: product/invisible

#30348 [couch-to-sql] [Repeaters] Migrate Repeaters to SQL
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/data_interfaces/tests/test_utils.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/motech/const.py
  corehq/motech/dhis2/repeaters.py
  corehq/motech/dhis2/tests/test_dhis_config.py
  corehq/motech/dhis2/tests/test_entities_helpers.py
  corehq/motech/dhis2/tests/test_events_helpers.py
  corehq/motech/dhis2/tests/test_repeaters.py
  corehq/motech/fhir/repeaters.py
  corehq/motech/migrations/0011_connectionsettings_is_deleted.py
  corehq/motech/models.py
  corehq/motech/openmrs/repeaters.py
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/repeaters/apps.py
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/exceptions.py
  corehq/motech/repeaters/expression/repeaters.py
  corehq/motech/repeaters/management/commands/migrate_all_repeaters.py
  corehq/motech/repeaters/management/commands/migrate_appstructurerepeater.py
  corehq/motech/repeaters/management/commands/migrate_beneficiaryregistrationrepeater.py
  corehq/motech/repeaters/management/commands/migrate_beneficiaryvaccinationrepeater.py
  corehq/motech/repeaters/management/commands/migrate_caseexpressionrepeater.py
  corehq/motech/repeaters/management/commands/migrate_caserepeater.py
  corehq/motech/repeaters/management/commands/migrate_createcaserepeater.py
  corehq/motech/repeaters/management/commands/migrate_dataregistrycaseupdaterepeater.py
  corehq/motech/repeaters/management/commands/migrate_dhis2entityrepeater.py
  corehq/motech/repeaters/management/commands/migrate_dhis2repeater.py
  corehq/motech/repeaters/management/commands/migrate_fhirrepeater.py
  corehq/motech/repeaters/management/commands/migrate_formrepeater.py
  corehq/motech/repeaters/management/commands/migrate_locationrepeater.py
  corehq/motech/repeaters/management/commands/migrate_openmrsrepeater.py
  corehq/motech/repeaters/management/commands/migrate_refercaserrepeater.py
  corehq/motech/repeaters/management/commands/migrate_shortformrepeater.py
  corehq/motech/repeaters/management/commands/migrate_updatecaserepeater.py
  corehq/motech/repeaters/management/commands/migrate_userrepeater.py
  corehq/motech/repeaters/migrations/0006_add_proxy_models.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/optionvalue.py
  corehq/motech/repeaters/tests/data/repeaters.py
  corehq/motech/repeaters/tests/test_dbaccessors.py
  corehq/motech/repeaters/tests/test_display.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_models_slow.py
  corehq/motech/repeaters/tests/test_optionvalue.py
  corehq/motech/repeaters/tests/test_populate_caserepeater.py
  corehq/motech/repeaters/tests/test_proxy_models.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/tests/test_repeaters_migration.py
  corehq/motech/repeaters/tests/test_tasks.py
  corehq/motech/repeaters/utils.py
  custom/cowin/repeaters.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/invisible, Risk: High

#31559 Add some tests demonstrating current behavior
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
Labels: product/invisible

#31560 Update lazy translation docs
  docs/translations.rst
Labels: product/invisible

#31562 Updated get_add_case_preloads_case_id_xpath to check for multi-select
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
  corehq/apps/app_manager/xform.py
Labels: product/feature-flag
