Repository dimagi/commcare-hq, pull requests merged in 2022-03, with the labels that each got.

#31169 Removed remnants of corehq/ex-submodules/toggles
  corehq/ex-submodules/toggle/models.py
Labels: product/invisible

#31174 Split test_suite.py
  corehq/apps/app_manager/tests/test_copy_form.py
  corehq/apps/app_manager/tests/test_suite.py
  corehq/apps/app_manager/tests/test_suite_assertions.py
  corehq/apps/app_manager/tests/test_suite_case_tiles.py
  corehq/apps/app_manager/tests/test_suite_commtrack.py
  corehq/apps/app_manager/tests/test_suite_detail_tabs.py
  corehq/apps/app_manager/tests/test_suite_filters.py
  corehq/apps/app_manager/tests/test_suite_fixture_to_case_selection.py
  corehq/apps/app_manager/tests/test_suite_formats.py
  corehq/apps/app_manager/tests/test_suite_graphing.py
  corehq/apps/app_manager/tests/test_suite_instances.py
  corehq/apps/app_manager/tests/test_suite_sorting.py
  corehq/apps/app_manager/tests/test_suite_subcases.py
  corehq/apps/app_manager/tests/test_suite_usercase.py
Labels: product/invisible

#31097 [Auto-Deactivate Mobile Workers] Add backend utilities and methods
  corehq/apps/enterprise/models.py
  corehq/apps/enterprise/tasks.py
  corehq/apps/enterprise/tests/test_enterprise_mobile_worker_settings.py
  corehq/apps/enterprise/tests/test_tasks.py
  corehq/apps/enterprise/tests/utils.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_deactivate_mobile_worker_trigger.py
  corehq/apps/users/tests/test_util.py
  corehq/apps/users/util.py
  corehq/const.py
Labels: product/invisible

#31182 Add waf_allow decorator to edit_advanced_form_actions view
  corehq/apps/app_manager/urls.py
Labels: product/invisible

#31179 Improve Couch document evaluation command
  corehq/apps/cleanup/management/commands/evaluate_couch_model_for_sql.py
  corehq/dbaccessors/couchapps/all_docs.py
  corehq/util/doc_processor/couch.py
Labels: product/invisible

#31183 Fix calculation to truncate values to 1 dp
  custom/gcc_sangath/rules/custom_actions.py
  custom/gcc_sangath/tests/test_custom_actions.py
Labels: product/custom

#30873 Support multibar charts in reports
  corehq/apps/app_manager/suite_xml/features/mobile_ucr.py
  corehq/apps/app_manager/tests/data/suite/reports_module_summary_detail_hide_data_table.xml
  corehq/apps/app_manager/tests/data/suite/reports_module_summary_detail_use_localized_description.xml
  corehq/apps/app_manager/tests/data/suite/reports_module_summary_detail_use_xpath_description.xml
  corehq/apps/app_manager/tests/test_report_config.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/tests/data/configs/sample_report_config.json
  corehq/apps/userreports/tests/test_view.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#31168 Refactor covid scripts
  corehq/apps/hqcase/bulk.py
  corehq/apps/hqcase/tests/test_bulk.py
  custom/covid/management/commands/README.rst
  custom/covid/management/commands/add_assignment_cases.py
  custom/covid/management/commands/add_hq_user_id_to_case.py
  custom/covid/management/commands/clear_owner_ids.py
  custom/covid/management/commands/run_all_management_command.py
  custom/covid/management/commands/update_all_activity_complete_date.py
  custom/covid/management/commands/update_case_index_relationship.py
  custom/covid/management/commands/update_cases.py
  custom/covid/management/commands/update_owner_ids.py
  custom/covid/tests/test_management_commands.py
Labels: product/invisible

#31177 don't require case type when updating cases via data registry repeater
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_payload_generator.py
Labels: product/feature-flag

#31185 fix potentially flaky test
  corehq/apps/enterprise/tests/test_tasks.py
Labels: product/invisible

#31178 Added custom rule to update all_activity_complete_date to today
  custom/covid/rules/custom_actions.py
  custom/covid/tests/test_custom_rules.py
  settings.py
Labels: product/custom

#31186 Remove acks_late from build_last_month_MALT
  corehq/apps/data_analytics/tasks.py
Labels: product/invisible

#31138 Modify logic for returning available domains to link
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/tests/test_dbaccessors.py
Labels: product/invisible

#31149 Disable newly linked domain if necessary in linked project spaces
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
Labels: product/invisible

#31152 Moved force_manual_action from request level to command level
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/util.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
Labels: Open for review: do not merge, Risk: Medium

#31192 Remove top level import
  .readthedocs.yml
  custom/covid/rules/custom_actions.py
Labels: product/invisible

#31193 Remove unused FailedLoginTotal
  corehq/apps/users/failed_login_total.py
  corehq/apps/users/tests/test_failed_login_total.py
Labels: product/invisible

#31194 Add OS for readthedocs build
  .readthedocs.yml
Labels: product/invisible

#31190 Removed some deprecated_init
  corehq/apps/commtrack/helpers.py
  corehq/apps/commtrack/management/commands/update_supply_point_locations.py
  corehq/apps/commtrack/tests/test_xml.py
Labels: product/invisible

#31189 Add acks_late back to build_last_month_MALT
  corehq/apps/data_analytics/tasks.py
Labels: product/invisible

#31172 Create LiveGoogleSheetRefreshStatus model
  corehq/apps/oauth_integrations/migrations/0003_livegooglesheetrefreshstatus.py
  corehq/apps/oauth_integrations/models.py
  migrations.lock
  settings.py
Labels: reindex/migration, product/invisible

#31195 moves auth decorators first
  corehq/apps/reports/views.py
Labels: product/invisible

#31171 Create LiveGoogleSheetSchedule model
  corehq/apps/oauth_integrations/migrations/0002_livegooglesheetschedule.py
  corehq/apps/oauth_integrations/migrations/0003_livegooglesheetrefreshstatus.py
  corehq/apps/oauth_integrations/migrations/0004_auto_20220304_1139.py
  corehq/apps/oauth_integrations/models.py
  migrations.lock
  settings.py
Labels: reindex/migration, product/invisible

#31191 [SAMVEG] Adds ability to skip call validator
  custom/samveg/case_importer/exceptions.py
  custom/samveg/case_importer/validators.py
  custom/samveg/const.py
  custom/samveg/tests/case_importer/validators.py
Labels: product/custom

#31196 Lint advanced form js files
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/actions.js
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/case_config_ui.js
Labels: product/invisible

#31184 Allow oauth decorator to handle custom scopes and add reports:view oa…
  corehq/apps/domain/decorators.py
  corehq/apps/domain/tests/test_auth_decorators.py
  corehq/apps/userreports/views.py
  settings.py
Labels: product/invisible, Risk: High

#31199 [fix] add missing URL for system info page JS
  corehq/apps/hqadmin/templates/hqadmin/system_info.html
Labels: product/invisible

#31201 Revert "Removed request-level 'Search Again' flag"
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
Labels: Risk: Medium

#31200 Removed more deprecated_init
  corehq/form_processor/tests/test_basics.py
  corehq/form_processor/tests/test_dbcache.py
  corehq/form_processor/tests/test_ledgers.py
  corehq/form_processor/tests/test_reprocess_errors.py
  corehq/form_processor/utils/xform.py
Labels: product/invisible, Risk: High

#31210 Drop Django 1.1 workaround
  corehq/form_processor/models/attachment.py
Labels: product/invisible, Risk: High

#31211 Removed old 'dynamic reports' feature
  corehq/apps/cleanup/management/commands/delete_dynamic_reports.py
  corehq/apps/cleanup/management/commands/list_dynamic_reports.py
  corehq/apps/domain/models.py
  corehq/apps/reports/management/commands/add_dynamic_report.py
  corehq/pillows/mappings/domain_mapping.py
  corehq/reports.py
  docs/maps.rst
  docs/reporting.rst
Labels: reindex/migration, product/invisible, Risk: High

#31212 Hard-delete forms and cases with domain
  corehq/apps/domain/management/commands/delete_domain.py
Labels: product/invisible

#31209 Removed Domain.report_whitelist
  corehq/apps/domain/models.py
  corehq/apps/reports/management/commands/edit_report_whitelist.py
  corehq/reports.py
Labels: product/invisible

#31213 Removed some more deprecated_init
  corehq/apps/users/models.py
  corehq/apps/users/tasks.py
  corehq/apps/users/tests/retire.py
  corehq/ex-submodules/casexml/apps/case/cleanup.py
  corehq/ex-submodules/casexml/apps/case/mock/mock.py
  corehq/ex-submodules/casexml/apps/case/mock/tests/test_case_block.py
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
  corehq/ex-submodules/casexml/apps/case/tests/test_case_block.py
  corehq/ex-submodules/casexml/apps/case/tests/test_rebuild.py
  corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore_v3.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_state_hash.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py
  custom/inddex/example_data/data.py
Labels: product/invisible

#31216 Docs fixes
  corehq/apps/userreports/README.rst
  docs/formplayer.rst
  docs/js-guide/static-files.md
  docs/metrics.rst
  docs/ucr/faq.md
Labels: product/invisible

#31214 Add ability to close cases via the API
  corehq/apps/hqcase/api/updates.py
  corehq/apps/hqcase/tests/test_case_update_api.py
Labels: product/feature-flag

#31217 Create specific builds via cmdline
  corehq/apps/builds/README.rst
  corehq/apps/builds/management/commands/add_commcare_build.py
Labels: product/invisible

#31198 Update nanoid
  package.json
Labels: product/invisible, dependencies, dependencies/javascript

#31161 Link UCR Expression permissions to UCR expressions
  corehq/apps/domain/models.py
  corehq/apps/domain/views/internal.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/tests/test_data_source_config.py
  corehq/apps/userreports/tests/test_data_source_repeats.py
  corehq/apps/userreports/tests/test_registry_data_source_config.py
  corehq/apps/userreports/tests/test_report_config.py
  corehq/apps/userreports/tests/test_static_data_sources.py
  corehq/apps/userreports/ui/forms.py
  corehq/apps/userreports/util.py
  corehq/apps/userreports/views.py
  corehq/apps/users/util.py
Labels: QA Passed, product/invisible

#31219 Rename Configurable Reports to Custom Web Reports
  corehq/apps/userreports/static/userreports/js/configurable_reports_home.js
  corehq/apps/userreports/templates/userreports/configurable_reports_home.html
  corehq/apps/userreports/templates/userreports/edit_data_source.html
  corehq/apps/userreports/templates/userreports/edit_report_config.html
  corehq/apps/userreports/templates/userreports/partials/delete_report_button.html
  corehq/apps/userreports/templates/userreports/userreports_base.html
  corehq/apps/userreports/views.py
  corehq/apps/users/static/users/js/roles.js
Labels: product/all-users-all-environments

#31206 add unique constraint to prevent race conditions with partner analytics
  corehq/apps/analytics/migrations/0002_data_point_unique_constraint.py
  corehq/apps/analytics/models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31207 Removed unused Domain attributes
  corehq/apps/domain/models.py
  corehq/pillows/mappings/domain_mapping.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
  testapps/test_pillowtop/tests/data/all-pillow-meta.json
Labels: reindex/migration, product/invisible, Risk: High

#31223 Add --divided-we-run=XX option to test command
  .github/workflows/tests.yml
Labels: product/invisible

#31226 Removed some deprecated_init
  corehq/apps/aggregate_ucrs/tests/test_aggregation.py
  corehq/apps/api/tests/form_resources.py
  corehq/apps/api/tests/ucr_resources.py
  corehq/apps/hqadmin/tests/test_stale_data_in_es.py
  corehq/apps/hqcase/tests/test_explode_cases.py
  corehq/apps/reports/views.py
  corehq/apps/userreports/tests/test_columns.py
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/zapier/tests/test_zapier_forwarding.py
  corehq/ex-submodules/couchforms/tests/test_edits.py
Labels: product/invisible

#31215 Delete domain fixes
  corehq/apps/domain/deletion.py
  corehq/apps/domain/management/commands/delete_domain.py
  corehq/apps/domain/management/commands/hard_delete_forms_and_cases_in_domain.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/formplayer_api/migrations/0001_drop_old_tables.py
  corehq/apps/formplayer_api/migrations/__init__.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31221 Update json-schema to 0.4.0
  package.json
Labels: product/invisible, dependencies

#31224 Removes redundant custom command added
  corehq/apps/app_manager/management/commands/convert_basic_module_to_advanced.py
Labels: product/invisible

#31229 [bugfix] remove extra quote from template
  corehq/apps/userreports/templates/userreports/edit_data_source.html
Labels: product/invisible

#31115 subcase search support for case search
  corehq/apps/case_search/exceptions.py
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/tests/test_subcase_query_parser.py
  corehq/apps/case_search/utils.py
  corehq/apps/case_search/xpath_functions/__init__.py
  corehq/apps/case_search/xpath_functions/query_functions.py
  corehq/apps/case_search/xpath_functions/subcase_functions.py
  corehq/apps/case_search/xpath_functions/value_functions.py
  corehq/apps/hqcase/api/get_list.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
Labels: product/feature-flag

#31222 Fix test that was failing locally
  corehq/apps/saved_reports/tests/test_models.py
Labels: product/invisible

#31233 Revert Rename Configurable Reports to Custom Web Reports
  corehq/apps/userreports/static/userreports/js/configurable_reports_home.js
  corehq/apps/userreports/templates/userreports/configurable_reports_home.html
  corehq/apps/userreports/templates/userreports/edit_data_source.html
  corehq/apps/userreports/templates/userreports/edit_report_config.html
  corehq/apps/userreports/templates/userreports/partials/delete_report_button.html
  corehq/apps/userreports/templates/userreports/userreports_base.html
  corehq/apps/userreports/views.py
  corehq/apps/users/static/users/js/roles.js
Labels: product/all-users-all-environments

#31234 Adjust for Django 3.0 backwards incompatibilities
  corehq/apps/app_manager/models.py
  corehq/apps/domain/decorators.py
Labels: product/invisible, Risk: High

#31232 add lock to reporting metadata task
  corehq/apps/users/tasks.py
Labels: product/invisible

#31187 Query generator functions for multivalued property searches
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/tests/test_case_search_filters.py
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/xpath_functions/__init__.py
  corehq/apps/case_search/xpath_functions/query_functions.py
  corehq/apps/case_search/xpath_functions/subcase_functions.py
  corehq/apps/case_search/xpath_functions/value_functions.py
  corehq/apps/es/case_search.py
  corehq/apps/es/queries.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/es/tests/test_queries.py
Labels: product/invisible

#31231 [bugfix] fix application case summary when using advanced modules
  corehq/apps/app_manager/app_schemas/app_case_metadata.py
  corehq/apps/app_manager/app_schemas/tests/test_case_meta.py
Labels: product/all-users-all-environments

#31235 Adjust for Django 3.1 backwards incompatibilities
  corehq/apps/auditcare/tests/testutils.py
  corehq/apps/locations/adjacencylist.py
  corehq/form_processor/tests/utils.py
Labels: product/invisible

#30550 Remove serializer='pickle' from user_imports
  corehq/apps/user_importer/tasks.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/views/__init__.py
Labels: QA Passed, product/invisible, Risk: Medium

#31237 name 'metrics_counter' is not defined
  corehq/apps/users/tasks.py
Labels: product/invisible

#31242 Use POST for EmailReportForm
  corehq/apps/reports/static/reports/js/hq_report.js
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/apps/reports/tests/test_views.py
  corehq/apps/reports/views.py
Labels: product/invisible

#31202 Removed request-level 'Search Again' flag
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/util.js
Labels: product/invisible, Risk: Medium

#31248 Removed more deprecated init
  corehq/apps/callcenter/sync_usercase.py
  corehq/apps/ota/tests/test_claim.py
  corehq/apps/sms/tests/util.py
  corehq/motech/openmrs/atom_feed.py
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/tasks.py
  corehq/motech/openmrs/tests/test_atom_feed.py
  corehq/motech/openmrs/tests/test_repeaters.py
Labels: product/invisible

#31254 update lock file for dependencies updated
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#31250 Replace django-partial-index with Index + condition
  corehq/blobs/migrations/0002_blobmeta.py
  corehq/blobs/migrations/0010_auto_20191023_0938.py
  corehq/blobs/migrations/0012_rename_indexes.py
  corehq/blobs/migrations/0013_drop_icds_cas_index.py
  corehq/blobs/models.py
  migrations.lock
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: reindex/migration, product/invisible, dependencies

#31246 [bugfix] set query data inputs to null to indicate no inputs
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
Labels: product/feature-flag, Risk: Medium

#31256 fix celery service check
  corehq/apps/hqadmin/service_checks.py
  corehq/celery_monitoring/heartbeat.py
Labels: product/invisible

#31251 Added feature flag for multiple referrals
  corehq/toggles/__init__.py
Labels: product/invisible

#31262 [bugfix] fix application case summary when using advanced modules
  corehq/apps/app_manager/app_schemas/app_case_metadata.py
  corehq/apps/app_manager/app_schemas/tests/test_case_meta.py
Labels: product/invisible

#31181 Xml logic changes for ID mapping on multi select properties
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/data/suite/call-center.xml
  corehq/apps/app_manager/tests/data/suite/normal-suite.xml
  corehq/apps/app_manager/tests/data/suite/suite-case-tiles.xml
  corehq/apps/app_manager/tests/test_suite.py
  corehq/apps/app_manager/tests/test_suite_formats.py
Labels: QA Passed, product/all-users-all-environments

#31264 Added geocoder support for latitude and longitude
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
Labels: product/feature-flag, Risk: Medium

#31176 remove legacy perm check
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_authorization.py
Labels: product/invisible, Risk: Medium

#31238 Track dependencies status
  docker/run.sh
  scripts/track-dependency-status.sh
Labels: product/invisible

#31188 Fix linked_domain dbaccessor tests
  corehq/apps/linked_domain/tests/test_dbaccessors.py
Labels: product/invisible

#31265 Remove django-angular and internalize jquery.rmi integration
  corehq/apps/linked_domain/views.py
  corehq/apps/notifications/views.py
  corehq/apps/registration/views.py
  corehq/apps/users/views/mobile/users.py
  corehq/util/jqueryrmi.py
  corehq/util/tests/test_jqueryrmi.py
  docs/js-guide/integration-patterns.rst
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
Labels: product/invisible, dependencies, Risk: High

#31269 Fix user_importer test suite
  corehq/apps/user_importer/tests/test_importer.py
Labels: product/invisible, Risk: Medium

#31263 Multiple referrals app manager config UI
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_multi_select.html
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag

#31267 Web apps docs: added section on HQ
  docs/images/web_apps_case_search_false.png
  docs/images/web_apps_case_search_true.png
  docs/web_apps.rst
Labels: product/invisible

#31270 Use get_public_only_session when following request body SubscribeURL property
  corehq/apps/hqwebapp/views.py
  corehq/messaging/smsbackends/amazon_pinpoint/views.py
  corehq/motech/auth.py
  corehq/util/public_only_requests/__init__.py
  corehq/util/public_only_requests/public_only_requests.py
  corehq/util/public_only_requests/tests/__init__.py
  corehq/util/public_only_requests/tests/test_public_only_session.py
Labels: product/invisible

#31243 Improve fragile logic in pillowtop `build_bulk_payload()` utility
  corehq/ex-submodules/pillowtop/tests/test_utils.py
  corehq/ex-submodules/pillowtop/utils.py
Labels: product/invisible

#31277 Rename metric commcare.security.ssrf_attempt to reflect more general usage
  corehq/motech/auth.py
  corehq/motech/forms.py
  corehq/motech/requests.py
Labels: product/invisible

#31272 Update modernizer to 3.12.0
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#31273 [bugfix] fix search again workflows in Web Apps
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/util.js
Labels: product/feature-flag, Risk: Medium

#31278 Use default username max length in auth forms
  corehq/apps/hqwebapp/forms.py
  corehq/apps/hqwebapp/tests/test_sso_enforced_login.py
Labels: product/invisible

#31279 Remove enterprise specific "limitation"
  corehq/apps/accounting/utils/account.py
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/tests/test_dbaccessors.py
Labels: product/invisible

#30607 Remove serialize='pickle' from reports and saved_reports
  corehq/apps/accounting/filters.py
  corehq/apps/export/views/download.py
  corehq/apps/reports/const.py
  corehq/apps/reports/generic.py
  corehq/apps/reports/tasks.py
  corehq/apps/reports/tests/test_views.py
  corehq/apps/reports/views.py
  corehq/apps/saved_reports/models.py
  corehq/apps/saved_reports/tasks.py
  corehq/ex-submodules/dimagi/utils/dates.py
Labels: QA Passed, product/invisible

#31301 Add dependecy watchers as codeowners of requirements
  .github/CODEOWNERS
Labels: product/invisible

#31299 use 'spec' reporter when running in verbose mode
  Gruntfile.js
Labels: product/invisible

#31306 Django 3.2 fixes: response headers and empty keyword actions set
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/linked_domain/keywords.py
  corehq/apps/receiverwrapper/tests/test_submit_errors.py
  corehq/apps/reports/tests/test_export_response.py
Labels: product/invisible

#31311 add 'today()' function to ES filter DSL
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/tests/test_value_functions.py
  corehq/apps/case_search/xpath_functions/__init__.py
  corehq/apps/case_search/xpath_functions/value_functions.py
Labels: product/feature-flag

#31305 Extra amendments to 'Remove serialize='pickle' from reports and saved_reports'
  corehq/apps/reports/app_config.py
  corehq/apps/reports/const.py
  corehq/apps/reports/generic.py
  corehq/apps/reports/tasks.py
  corehq/apps/reports/views.py
  corehq/apps/saved_reports/tasks.py
Labels: product/invisible

#31276 Refactor and add tests to submit_unfinished_form innards
  corehq/apps/formplayer_api/smsforms/api.py
  corehq/apps/formplayer_api/smsforms/exceptions.py
  corehq/apps/smsforms/app.py
  corehq/apps/smsforms/tests/test_app.py
Labels: product/invisible

#31180 [Auto-Deactivate Mobile Workers] UI Changes & task activation
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/utils/subscription.py
  corehq/apps/domain/urls.py
  corehq/apps/domain/views/settings.py
  corehq/apps/enterprise/forms.py
  corehq/apps/enterprise/mixins.py
  corehq/apps/enterprise/models.py
  corehq/apps/enterprise/templates/enterprise/manage_mobile_workers.html
  corehq/apps/enterprise/tests/test_enterprise_mobile_worker_settings.py
  corehq/apps/enterprise/tests/test_forms.py
  corehq/apps/enterprise/urls.py
  corehq/apps/enterprise/views.py
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/audit/change_messages.py
  corehq/apps/users/bulk_download.py
  corehq/apps/users/forms.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/tests/test_audit.py
  corehq/apps/users/tests/test_deactivate_mobile_worker_trigger.py
  corehq/apps/users/views/mobile/users.py
  corehq/ex-submodules/dimagi/utils/dates.py
  corehq/ex-submodules/dimagi/utils/tests/dates.py
  corehq/tabs/tabclasses.py
Labels: QA Passed, product/feature-flag, Risk: Medium

#31315 Replace ugettext with gettext
  corehq/apps/domain/views/settings.py
  corehq/apps/enterprise/forms.py
  corehq/apps/enterprise/mixins.py
  corehq/apps/enterprise/views.py
  corehq/apps/users/forms.py
Labels: product/invisible

#31312 Add LOADTEST_USERS privilege
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0060_add_loadtest_users_priv.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31316 Fix flaky test by changing assertion method
  corehq/apps/enterprise/tests/test_forms.py
Labels: product/invisible

#31020 Command to migrate feature flag users to release management
  corehq/apps/accounting/management/commands/change_role_for_software_plan_version.py
  corehq/apps/accounting/tests/test_change_role_for_software_plan_version.py
  corehq/apps/linked_domain/management/commands/migrate_feature_flag_domains.py
  corehq/apps/linked_domain/tests/test_migrate_feature_flag_domains.py
Labels: product/invisible

#31321 only add registry slug if it's supported by the app
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
Labels: product/feature-flag

#31319 TypeError: Abstract models cannot be instantiated
  corehq/messaging/scheduling/tests/test_content.py
  corehq/messaging/scheduling/tests/test_recipients.py
  corehq/util/test_utils.py
Labels: product/invisible

#31303 Add name to module output in API
  corehq/apps/api/resources/v0_4.py
  corehq/apps/api/tests/app_resources.py
Labels: product/all-users-all-environments, Risk: High

#31328 Fix kafka docker socket path for podman
  docker/hq-compose.yml
  scripts/docker
Labels: product/invisible

#31324 allow passing a string as the property name to selected* functions
  corehq/apps/case_search/tests/test_case_search_filters.py
  corehq/apps/case_search/xpath_functions/query_functions.py
Labels: product/feature-flag

#31329 replattr -> patch.object
  corehq/blobs/tests/test_migrate.py
  corehq/blobs/tests/test_migratingdb.py
  corehq/ex-submodules/dimagi/utils/tests/test_decorators.py
Labels: product/invisible

#31334 Update DEV_FAQ.md
  DEV_FAQ.md
Labels: product/invisible

#31275 Updated web apps docs
  docs/js-guide/migrating.rst
  docs/pillows.rst
  docs/web_apps.rst
Labels: product/invisible

#31326 unwrap date function args
  corehq/apps/case_search/dsl_utils.py
  corehq/apps/case_search/filter_dsl.py
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/case_search/tests/test_value_functions.py
  corehq/apps/case_search/xpath_functions/value_functions.py
Labels: product/feature-flag

#31337 Updated copy
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
Labels: product/feature-flag

#31339 Updated HTTP return codes for case claim request
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/apps/ota/views.py
Labels: product/invisible

#31344 Removed migrate_case_search_relevant
  corehq/apps/app_manager/management/commands/migrate_case_search_relevant.py
  corehq/apps/app_manager/migrations/0017_migrate_case_search_relevant.py
Labels: product/invisible

#31342 Finishing touches on feature flag migration command
  corehq/apps/linked_domain/management/commands/migrate_feature_flag_domains.py
  corehq/apps/linked_domain/tests/test_migrate_feature_flag_domains.py
Labels: product/invisible

#31350 Fix warning from $URL in kafka init script
  docker/hq-compose.yml
Labels: product/invisible

#31280 Create migration to add release management to enterprise plans
  corehq/apps/accounting/migrations/0062_add_release_management_to_enterprise.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31353 Revert "Multi-Environment Release Management"
  corehq/apps/accounting/utils/account.py
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/exceptions.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/partials/manage_downstream_domains.html
  corehq/apps/linked_domain/templates/linked_domain/partials/push_content.html
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/tests/test_decorators.py
  corehq/apps/linked_domain/tests/test_release_manager.py
  corehq/apps/linked_domain/tests/test_views.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reminders/views.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/styleguide/templates/styleguide/_includes/molecules/selections.html
  corehq/apps/styleguide/templates/styleguide/examples/multiselect.html
  corehq/apps/userreports/views.py
  corehq/tabs/tabclasses.py
  corehq/tabs/tests.py
Labels: product/invisible

#31347 separate feature flag for Data Registry reports
  corehq/apps/userreports/reports/builder/forms.py
  corehq/apps/userreports/templates/userreports/report_error.html
  corehq/apps/userreports/util.py
  corehq/apps/userreports/views.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#31271 Updated geocoder to broadcast single geopoint value
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
Labels: product/all-users-all-environments, Risk: Medium

#31338 lower locked rows
  corehq/apps/users/tasks.py
Labels: product/invisible

#31354 Multi-Environment Release Management (for real)
  corehq/apps/accounting/utils/account.py
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/exceptions.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/partials/manage_downstream_domains.html
  corehq/apps/linked_domain/templates/linked_domain/partials/push_content.html
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/tests/test_decorators.py
  corehq/apps/linked_domain/tests/test_release_manager.py
  corehq/apps/linked_domain/tests/test_views.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reminders/views.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/styleguide/templates/styleguide/_includes/molecules/selections.html
  corehq/apps/styleguide/templates/styleguide/examples/multiselect.html
  corehq/apps/userreports/views.py
  corehq/tabs/tabclasses.py
  corehq/tabs/tests.py
Labels: product/all-users-all-environments

#31317 Revert PRs that remove pickling from reports
  corehq/apps/accounting/filters.py
  corehq/apps/export/views/download.py
  corehq/apps/reports/app_config.py
  corehq/apps/reports/generic.py
  corehq/apps/reports/tasks.py
  corehq/apps/reports/tests/test_views.py
  corehq/apps/reports/views.py
  corehq/apps/saved_reports/models.py
  corehq/apps/saved_reports/tasks.py
  corehq/ex-submodules/dimagi/utils/dates.py
Labels: product/invisible

#31346 Add migration for replacing linked projects toggle with ERM privilege
  corehq/apps/accounting/migrations/0063_replace_linked_projects_ff_with_erm.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31240 Add management command to find XSS attempts
  corehq/apps/app_manager/management/commands/_form_iterator.py
  corehq/apps/app_manager/management/commands/check_for_form_entities.py
  corehq/apps/app_manager/management/commands/check_for_xss_attempts.py
Labels: product/invisible

#31358 Add migration for notification field type alteration
  corehq/apps/notifications/migrations/0008_add_notification_types.py
  corehq/apps/notifications/models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#31320 Add feature discovery notification types
  corehq/apps/notifications/models.py
  corehq/apps/notifications/static/notifications/js/notifications_service.js
  corehq/apps/notifications/templates/notifications/partials/global_notifications.html
  corehq/apps/notifications/views.py
Labels: QA Passed, product/all-users-all-environments

#31300 add enterprise limits to per user rate definitions
  corehq/apps/domain/views/internal.py
  corehq/apps/hqwebapp/two_factor_gateways.py
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/tests/test_get_n_users_for_rate_limiting.py
  corehq/project_limits/tests/test_rate_limiter.py
Labels: product/invisible

#31365 Delete update_supply_point_locations.py
  corehq/apps/commtrack/management/commands/update_supply_point_locations.py
Labels: product/invisible

#31378 Allow linking domains that user is an admin in for ERM,
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#31377 Fix minor bug with Feature Discoverability
  corehq/apps/notifications/views.py
Labels: product/all-users-all-environments

#31379 The actual release of Multi-Environment Release Management
  corehq/apps/accounting/utils/account.py
  corehq/apps/app_manager/forms.py
  corehq/apps/app_manager/views/view_generic.py
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/linked_domain/dbaccessors.py
  corehq/apps/linked_domain/decorators.py
  corehq/apps/linked_domain/exceptions.py
  corehq/apps/linked_domain/models.py
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/linked_domain/tasks.py
  corehq/apps/linked_domain/templates/linked_domain/domain_links.html
  corehq/apps/linked_domain/templates/linked_domain/partials/manage_downstream_domains.html
  corehq/apps/linked_domain/templates/linked_domain/partials/push_content.html
  corehq/apps/linked_domain/tests/test_dbaccessors.py
  corehq/apps/linked_domain/tests/test_decorators.py
  corehq/apps/linked_domain/tests/test_release_manager.py
  corehq/apps/linked_domain/tests/test_views.py
  corehq/apps/linked_domain/util.py
  corehq/apps/linked_domain/view_helpers.py
  corehq/apps/linked_domain/views.py
  corehq/apps/reminders/views.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/styleguide/templates/styleguide/_includes/molecules/selections.html
  corehq/apps/styleguide/templates/styleguide/examples/multiselect.html
  corehq/apps/userreports/views.py
  corehq/tabs/tabclasses.py
  corehq/tabs/tests.py
Labels: product/all-users-all-environments

#31375 Upgrade to private release of django-websocket-redis
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#31373 Django 3.2 test fixes
  corehq/apps/hqwebapp/templatetags/tests/rendered/initial_page_data.html
  corehq/apps/hqwebapp/templatetags/tests/test_tag.py
  corehq/apps/hqwebapp/tests/test_compress_command.py
  corehq/apps/oauth_integrations/migrations/0003_livegooglesheetrefreshstatus.py
Labels: reindex/migration, product/invisible

#31335 Added comment to CaseClaimXpath.default_relevant
  corehq/apps/app_manager/xpath.py
Labels: product/invisible

#31356 caselist and casedetail are each two words
  corehq/apps/app_manager/const.py
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/templates/app_manager/partials/menu/appnav_menu.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_module_overwrite.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_settings.html
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_detail.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/users.html
  corehq/apps/hqcase/tests/test_case_list_api.py
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/menu.less
  corehq/apps/hqwebapp/static/preview_app/less/preview_app/case.less
  corehq/apps/hqwebapp/static/preview_app/less/preview_app/module.less
  corehq/toggles/__init__.py
Labels: product/invisible, Risk: Medium

#31130 Remove Itemset.wrap
  corehq/apps/app_manager/management/commands/migrate_case_search_prompt_itemset_ids.py
  corehq/apps/app_manager/migrations/0021_migrate_case_search_itemset_ids.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_management_commands.py
Labels: product/invisible

#31362 Delete migrate_domain_countries.py
  corehq/apps/domain/management/commands/migrate_domain_countries.py
Labels: product/invisible

#31382 Revert "add enterprise limits to per user rate definitions"
  corehq/apps/domain/views/internal.py
  corehq/apps/hqwebapp/two_factor_gateways.py
  corehq/apps/receiverwrapper/rate_limiter.py
  corehq/project_limits/rate_limiter.py
  corehq/project_limits/tests/test_get_n_users_for_rate_limiting.py
  corehq/project_limits/tests/test_rate_limiter.py
Labels: product/invisible

#31366 Delete mark_snapshot_head.py
  corehq/apps/domain/management/commands/mark_snapshot_head.py
Labels: product/invisible

#31363 Delete migrate_impact_annotations.py
  corehq/apps/domain/management/commands/migrate_impact_annotations.py
Labels: product/invisible

#31387 Django 3.2 JSONField moved into django.db.models
  corehq/apps/cleanup/management/commands/evaluate_couch_model_for_sql.py
  corehq/apps/cleanup/management/commands/templates/sql_model.j2
  corehq/apps/commtrack/migrations/0003_create_config_models.py
  corehq/apps/commtrack/models.py
  corehq/apps/custom_data_fields/migrations/0001_initial.py
  corehq/apps/custom_data_fields/migrations/0005_customdatafieldsprofile.py
  corehq/apps/custom_data_fields/migrations/0006_auto_20200924_1753.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/data_interfaces/migrations/0017_alter_domaincaserulerun.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/linked_domain/migrations/0004_domainlinkhistory.py
  corehq/apps/linked_domain/migrations/0006_auto_20180208_1139.py
  corehq/apps/linked_domain/models.py
  corehq/apps/registration/migrations/0005_asyncsignuprequest.py
  corehq/apps/registration/models.py
  corehq/apps/registry/migrations/0001_initial.py
  corehq/apps/registry/migrations/0003_schema_validation.py
  corehq/apps/registry/models.py
  corehq/apps/smsforms/migrations/0002_add_state_tracking_fields.py
  corehq/apps/smsforms/migrations/0003_make_fields_not_null.py
  corehq/apps/smsforms/models.py
  corehq/apps/translations/migrations/0006_add_smstranslations.py
  corehq/apps/translations/models.py
  corehq/apps/user_importer/migrations/0001_initial.py
  corehq/apps/user_importer/models.py
  corehq/apps/userreports/migrations/0011_datasourceactionlog.py
  corehq/apps/userreports/migrations/0013_reportcomparisondiff_reportcomparisonexception_reportcomparisontiming.py
  corehq/apps/userreports/migrations/0015_auto_20190701_2006.py
  corehq/apps/userreports/models.py
  corehq/apps/users/migrations/0005_add_user_reporting_metadata.py
  corehq/apps/users/migrations/0029_userhistory.py
  corehq/apps/users/migrations/0034_auto_20210813_1121.py
  corehq/apps/users/migrations/0038_auto_20210930_1235.py
  corehq/apps/users/models.py
  corehq/ex-submodules/casexml/apps/phone/migrations/0002_synclogsql.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/messaging/scheduling/migrations/0013_advanced_survey_options.py
  corehq/messaging/scheduling/migrations/0023_add_remaining_content_models.py
  corehq/messaging/scheduling/models/content.py
  corehq/util/migrations/0002_complaintbouncemeta_permanentbouncemeta_transientbounceemail.py
  corehq/util/models.py
  manage.py
Labels: reindex/migration, product/invisible, Risk: High, Risk: Medium
