Repository dimagi/commcare-hq, pull requests merged in 2023-09, with the labels that each got.

#33413 Update DEV_SETUP.md for a partitioned database
  DEV_SETUP.md
Labels: product/invisible

#33054 Add ability to copy cases between mobile workers for load testing (FF)
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0084_copy_cases_priv.py
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/tasks.py
  corehq/apps/case_search/const.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_interfaces/interfaces.py
  corehq/apps/data_interfaces/static/data_interfaces/js/case_management.js
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/templates/data_interfaces/interfaces/case_management.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_copy_complete_email.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_copy_status.html
  corehq/apps/data_interfaces/urls.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/es/case_search.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/hqcase/case_helper.py
  corehq/apps/hqcase/tests/test_case_copier.py
  corehq/apps/hqcase/tests/test_case_helper.py
  corehq/apps/hqcase/tests/test_utils.py
  corehq/apps/hqcase/utils.py
  corehq/apps/reports/filters/api.py
  corehq/apps/reports/filters/urls.py
  corehq/apps/reports/standard/__init__.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/data_sources.py
  corehq/apps/reports/standard/cases/filters.py
  corehq/apps/reports/templates/reports/filters/sensitive_columns.html
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/apps/reports/tests/test_case_copy.py
  corehq/apps/reports/tests/test_util.py
  corehq/apps/reports/urls.py
  corehq/apps/reports/util.py
  corehq/apps/reports/v2/formatters/cases.py
  corehq/apps/reports/views.py
  corehq/apps/users/signals.py
  corehq/apps/users/tasks.py
  corehq/apps/users/tests/test_tasks.py
  corehq/ex-submodules/couchexport/deid.py
  corehq/form_processor/models/cases.py
  corehq/form_processor/tests/test_cases.py
  corehq/privileges.py
  corehq/reports.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/feature-flag, Risk: High

#33430 Remove reference to old CHANGE_FORM_LANGUAGE FF
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_spec.js
Labels: product/invisible, Risk: Medium

#33427 WebUser feature should not be required when updating software plan
  corehq/apps/accounting/forms.py
Labels: QA Passed, product/admin

#33410 [B5] Migrate license pages to Bootstrap 5 (first real views!)
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/alert_user.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/hq-bug-report.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/hq.helpers.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_containers.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_dropdown.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_nav.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_navbar.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_type.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables.scss
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/core_libraries.html
  corehq/apps/hqwebapp/templatetags/tests/rendered/javascript_libraries_hq_bootstrap5.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/alert_user.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/hq-bug-report.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/hq.helpers.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/dropdowns._dropdown.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/layouts._containers.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/navs._nav.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/typography._type.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/style-imports.commcarehq.style.diff.txt
  corehq/apps/hqwebapp/tests/utils/test_bootstrap_changes.py
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/js-modal.txt
  corehq/apps/hqwebapp/views.py
  package.json
  yarn.lock
Labels: dependencies, Risk: High, Risk: Medium

#33425 Geohash aggregation and bounding box filter
  corehq/apps/es/aggregations.py
  corehq/apps/es/filters.py
  corehq/apps/es/tests/test_aggregations.py
  corehq/apps/es/tests/test_filters.py
Labels: product/feature-flag, product/invisible

#33444 Fix hubspot.js issue on prelogin pages
  corehq/apps/analytics/static/analytix/js/hubspot.js
Labels: product/invisible

#33440 [B5] Replace page-header with bootstrap 5's styling
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_type.scss
  corehq/apps/hqwebapp/templates/hqwebapp/bootstrap5/base_page.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/base_page.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/typography._type.style.diff.txt
Labels: product/invisible

#33433 Migration to remove free 50 sms
  corehq/apps/accounting/bootstrap/config/remove_free_50_sms_sep_2023.py
  corehq/apps/accounting/bootstrap/utils.py
  corehq/apps/accounting/migrations/0085_remove_free_50_sms.py
  corehq/apps/accounting/tests/test_invoicing.py
  migrations.lock
Labels: reindex/migration, product/admin

#33233 Modified the index with a comment to rebuild the domain index
  corehq/apps/domain/_design/views/domains/map.js
  corehq/preindex/couchviews.lock
  corehq/preindex/migrations/0002_initial.py
  migrations.lock
Labels: reindex/migration, product/invisible

#33438 [B5] Initial migration for notifications js (notifications_service)
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/base_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/base_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/resource_versions.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diff_config.json
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/base_main.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/notifications/notifications_service.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/notifications/notifications_service_main.js.diff.txt
  corehq/apps/notifications/static/notifications/js/bootstrap3/notifications_service.js
  corehq/apps/notifications/static/notifications/js/bootstrap3/notifications_service_main.js
  corehq/apps/notifications/static/notifications/js/bootstrap5/notifications_service.js
  corehq/apps/notifications/static/notifications/js/bootstrap5/notifications_service_main.js
  corehq/apps/notifications/static/notifications/spec/NotificationsService.spec.mo.js
  corehq/apps/notifications/templates/notifications/spec/mocha.html
Labels: product/invisible, Risk: Medium

#33426 Add geospatial case property validation
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/tests/test_view.py
  corehq/apps/data_dictionary/views.py
  corehq/apps/geospatial/forms.py
  corehq/apps/geospatial/static/geospatial/js/geo_config.js
  corehq/apps/geospatial/templates/geospatial/settings.html
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#33452 ap+dmr hotfix deploy branches
  corehq/apps/domain/_design/views/domains/map.js
  corehq/apps/es/client.py
  corehq/apps/es/tests/test_client.py
  corehq/apps/es/utils.py
  corehq/apps/hqcase/api/get_list.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/preindex/couchviews.lock
  corehq/preindex/migrations/0002_initial.py
  migrations.lock
Labels: reindex/migration

#33429 Split Screen Case Search: Dynamically update results
  corehq/apps/app_manager/management/commands/enable_dynamic_results_ff_for_sscs_domains.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_spec.js
  corehq/toggles/__init__.py
Labels: product/feature-flag, Risk: Medium

#33428 Modify Pprent/child relationship FF for Dynamically Updating Results in SSCS
  corehq/toggles/__init__.py
Labels: product/feature-flag

#33437 check xpath expressions in text for instance references
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/test_media_suite.py
Labels: product/all-users-all-environments, Core Compatibility

#33457 Fix pre 2.54 menu instance references
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/tests/test_suite_instances.py
Labels: product/all-users-all-environments

#33463 Update DD toggle check + documentation
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_table.html
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/reports/templates/reports/reportdata/case_data.html
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments

#33420 Create GPS capture page
  corehq/apps/data_dictionary/tests/test_view.py
  corehq/apps/es/es_query.py
  corehq/apps/es/filters.py
  corehq/apps/es/users.py
  corehq/apps/geospatial/const.py
  corehq/apps/geospatial/migrations/0003_auto_20230908_0927.py
  corehq/apps/geospatial/models.py
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/gps_capture.js
  corehq/apps/geospatial/templates/gps_capture.html
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/tests/test_utils.py
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/urls.py
  corehq/apps/geospatial/utils.py
  corehq/apps/geospatial/views.py
  corehq/tabs/tabclasses.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/feature-flag

#33456 Disable dynamic search if response type is query
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/feature-flag, Risk: Medium

#33464 Add a partial index on deleted_on for XFormInstance
  corehq/form_processor/migrations/0094_add_partial_index_xforms.py
  corehq/form_processor/models/forms.py
  migrations.lock
Labels: reindex/migration, Risk: High

#33380 Export Data Source endpoint to support JSON and pagination
  corehq/apps/api/resources/pagination.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/test_ucr_resources.py
  corehq/apps/api/urls.py
  corehq/apps/api/util.py
  corehq/apps/userreports/adapter.py
  corehq/apps/userreports/indicators/factory.py
  corehq/apps/userreports/management/commands/add_inserted_at_index.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/rebuild.py
  corehq/apps/userreports/tests/test_rebuild_migrate.py
Labels: product/invisible, Risk: High

#33470 Revert "Add a partial index on deleted_on for XFormInstance"
  corehq/form_processor/migrations/0094_add_partial_index_xforms.py
  corehq/form_processor/models/forms.py
  migrations.lock
Labels: reindex/migration, Risk: High

#33469 Revert "remove usage of XFormInstance.DELETED (part 1)"
  corehq/apps/data_pipeline_audit/dbacessors.py
  corehq/apps/data_pipeline_audit/management/commands/find_sql_forms_not_in_es.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/models/forms.py
  corehq/sql_accessors/migrations/0068_remove_deleted_state.py
  corehq/sql_accessors/sql_templates/get_form_ids_for_user_2.sql
  corehq/sql_accessors/sql_templates/soft_delete_forms_3.sql
  corehq/sql_accessors/sql_templates/soft_undelete_forms_3.sql
  corehq/sql_proxy_accessors/migrations/0050_remove_deleted_state.py
  corehq/sql_proxy_accessors/sql_templates/get_form_ids_for_user_2.sql
  corehq/sql_proxy_accessors/sql_templates/soft_delete_forms_3.sql
  corehq/sql_proxy_accessors/sql_templates/soft_undelete_forms_3.sql
  migrations.lock
Labels: reindex/migration, Risk: High

#33364 [INDIV-197,INDIV-205] Add custom case update action for dfci swasth project
  custom/dfci_swasth/__init__.py
  custom/dfci_swasth/constants.py
  custom/dfci_swasth/rules/custom_actions.py
  custom/dfci_swasth/tests/__init__.py
  custom/dfci_swasth/tests/test_custom_actions.py
  settings.py
Labels: QA Passed, product/custom

#33424 Management command to keep software plan consistent
  corehq/apps/accounting/management/commands/list_customer_billing_account_software_plan.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_admin_software_plans.py
  corehq/apps/accounting/utils/software_plans.py
Labels: product/invisible

#33467 Adds map to gps capture page
  corehq/apps/geospatial/static/geospatial/js/gps_capture.js
  corehq/apps/geospatial/templates/gps_capture.html
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#33453 Make split screen case search filters collapsible on small screens
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/query_view.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/breadcrumbs.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/menu.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/query.less
Labels: Risk: Medium

#33448 Add a new column "duplicate_invoice_id" in Invoice model
  corehq/apps/accounting/migrations/0086_add_duplicate_invoice_id_to_invoice_model.py
  corehq/apps/accounting/models.py
  migrations.lock
Labels: reindex/migration

#33476 update the pre-commit hook to handle deleted files
  git-hooks/pre-commit.sh
Labels: product/invisible

#33471 Load Mobile Worker GPS Data in Map (Back-end)
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/urls.py
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#33468 Version aware ES mappings in migrations
  corehq/apps/es/management/commands/make_elastic_migration.py
  corehq/apps/es/migration_operations.py
  corehq/apps/es/migrations/0001_bootstrap_es_indexes.py
  corehq/apps/es/migrations/0002_add_tombstones.py
  corehq/apps/es/migrations/0003_add_assigned_location_ids.py
  corehq/apps/es/migrations/0004_make_new_indexes.py
  corehq/apps/es/migrations/0005_add_epoch_as_valid_date_to_forms.py
  corehq/apps/es/tests/test_command_make_elastic_migration.py
  corehq/apps/es/tests/test_migration_operations.py
Labels: reindex/migration

#33490 Use the domain-table_id hash as the sheet name for data source exports
  corehq/apps/export/const.py
  corehq/apps/export/models/new.py
Labels: product/feature-flag

#33446 [B5] Migrate schedule demo modal to bootstrap 5
  corehq/apps/analytics/static/analytix/js/hubspot.js
  corehq/apps/analytics/templates/analytics/forms/bootstrap3/hubspot_cta_form.html
  corehq/apps/analytics/templates/analytics/forms/bootstrap5/hubspot_cta_form.html
  corehq/apps/hqwebapp/templates/hqwebapp/bootstrap5/base_navigation.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap3/get_demo_modals.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/get_demo_modals.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diff_config.json
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/analytics/forms/hubspot_cta_form.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/base_navigation.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/partials/get_demo_modals.html.diff.txt
  corehq/apps/registration/templates/registration/partials/start_trial_modal.html
Labels: product/invisible

#33493 Change EXPORT_DATA_SOURCE_DATA's tag to TAG_CUSTOM
  corehq/toggles/__init__.py
Labels: product/all-users-all-environments, product/feature-flag, product/invisible, product/admin

#33487 Refactor repeaters code and tests
  corehq/apps/accounting/tests/utils.py
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/ex-submodules/dimagi/utils/couch/migration.py
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/expression/tests.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_repeater.py
  corehq/motech/repeaters/tests/test_dbaccessors.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: product/invisible

#33443 media upload clear button
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/feature-flag, Risk: Medium

#33499 Overflowing Tables Small Screen
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: product/all-users-all-environments

#33479 Revert "Revert "Add a partial index on deleted_on for XFormInstance""
  corehq/form_processor/migrations/0094_add_partial_index_xforms.py
  corehq/form_processor/models/forms.py
  migrations.lock
Labels: reindex/migration, Risk: High

#33480 Revert "Revert "remove usage of XFormInstance.DELETED (part 1)""
  corehq/apps/data_pipeline_audit/dbacessors.py
  corehq/apps/data_pipeline_audit/management/commands/find_sql_forms_not_in_es.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/form_processor/backends/sql/dbaccessors.py
  corehq/form_processor/models/forms.py
  corehq/sql_accessors/migrations/0068_remove_deleted_state.py
  corehq/sql_accessors/sql_templates/get_form_ids_for_user_2.sql
  corehq/sql_accessors/sql_templates/soft_delete_forms_3.sql
  corehq/sql_accessors/sql_templates/soft_undelete_forms_3.sql
  corehq/sql_proxy_accessors/migrations/0050_remove_deleted_state.py
  corehq/sql_proxy_accessors/sql_templates/get_form_ids_for_user_2.sql
  corehq/sql_proxy_accessors/sql_templates/soft_delete_forms_3.sql
  corehq/sql_proxy_accessors/sql_templates/soft_undelete_forms_3.sql
  migrations.lock
Labels: reindex/migration, Risk: High

#33511 prevent multiple calls to clear answer
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
Labels: product/feature-flag, Risk: Medium

#33396 Editor UI for custom variables
  corehq/apps/app_manager/management/commands/migrate_case_list_custom_variables.py
  corehq/apps/app_manager/migrations/0028_case_list_custom_variable_xml_to_dict.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_detail.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/custom_detail_variables.html
  corehq/apps/app_manager/tests/test_migrate_case_list_custom_variables.py
  corehq/apps/app_manager/tests/test_suite.py
  corehq/apps/app_manager/views/modules.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration

#33519 Use table_id to list datasource options on Export Data Source Data page
  corehq/apps/export/forms.py
Labels: product/feature-flag

#33488 Mobile worker GPS data in map (front-end)
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/templates/geospatial/map_visualization_base.html
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#33494 Cs/sc 3104 add mobile workers page gps capture page
  corehq/apps/geospatial/static/geospatial/js/gps_capture.js
  corehq/apps/geospatial/templates/gps_capture.html
  corehq/apps/geospatial/templates/manage_gps_data.html
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#33521 Support mapbox geocoder
  corehq/apps/geospatial/static/geospatial/js/gps_capture.js
  corehq/apps/geospatial/templates/manage_gps_data.html
Labels: product/feature-flag

#33421 Ensure pre-filled filters get checked before pulling data
  corehq/apps/userreports/reports/filters/choice_providers.py
Labels: product/feature-flag

#33527 add domain tag to blob metadata metrics
  corehq/blobs/metadata.py
Labels: product/feature-flag

#33514 [B5] SCSS updates to button and variables
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_buttons.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/buttons._buttons.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
Labels: product/invisible

#33513 [B5] Migrate maintenance alerts admin page to bootstrap 5
  corehq/apps/hqwebapp/templates/hqwebapp/bootstrap5/maintenance_alerts.html
  corehq/apps/hqwebapp/templates/hqwebapp/maintenance_alerts.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/maintenance_alerts.html.diff.txt
  corehq/apps/hqwebapp/views.py
Labels: product/invisible, product/admin

#33515 [B5] Update migration script spec for bootstrap 5 migraiton
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/form-group.txt
  corehq/apps/hqwebapp/utils/bootstrap/spec/bootstrap_3_to_5.json
Labels: product/invisible

#33531 Update munch
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33512 Web apps responsive design bugfixes (pre-QA)
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/spec/utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
Labels: product/invisible, Risk: Medium

#33535 Cache `get_geo_(case|user)_property()`
  corehq/apps/geospatial/models.py
  corehq/apps/geospatial/tests/test_models.py
  corehq/apps/geospatial/tests/test_utils.py
  corehq/apps/geospatial/utils.py
Labels: product/invisible

#33542 Data model for 'clickable case list icons'
  corehq/apps/app_manager/models.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/toggles/__init__.py
Labels: product/invisible

#33510 Remove usage of XFormInstance.DELETED (part 2)
  corehq/form_processor/migrations/0095_remove_xforminstance_deleted_state.py
  corehq/form_processor/models/forms.py
  corehq/sql_accessors/migrations/0012_soft_deletion.py
  corehq/sql_accessors/migrations/0014_ledger_transactions.py
  corehq/sql_accessors/migrations/0015_ledger_transactions_update.py
  corehq/sql_accessors/migrations/0055_set_form_modified_on.py
  corehq/sql_accessors/migrations/0069_drop_DELETED_references_fn.py
  corehq/sql_accessors/sql_templates/get_form_ids_for_user.sql
  corehq/sql_accessors/sql_templates/soft_delete_forms2.sql
  corehq/sql_accessors/sql_templates/soft_undelete_forms2.sql
  corehq/sql_proxy_accessors/migrations/0009_soft_delete.py
  corehq/sql_proxy_accessors/migrations/0027_add_undelete_functions.py
  corehq/sql_proxy_accessors/migrations/0051_drop_DELETED_references_fn.py
  corehq/sql_proxy_accessors/sql_templates/get_form_ids_for_user.sql
  corehq/sql_proxy_accessors/sql_templates/soft_delete_forms.sql
  corehq/sql_proxy_accessors/sql_templates/soft_undelete_forms.sql
  migrations.lock
Labels: reindex/migration, Risk: High

#33503 Make sure individual form deletion populates deleted_on field
  corehq/apps/reports/templates/reports/form/partials/single_form.html
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
  corehq/form_processor/management/commands/populate_missing_delete_on_values.py
  corehq/form_processor/models/forms.py
  corehq/form_processor/tests/test_basics.py
Labels: product/invisible, Risk: High

#33543 Suite XML for 'clickable case list icons'
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/tests/test_suite_formats.py
Labels: product/feature-flag, Core Compatibility

#33536 Web apps case list "skip to bottom" button
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/menu.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/includes/variables.less
Labels: product/all-users-all-environments, Risk: Medium

#32964 [SAAS-14520] Add conditionally_location_safe decorator to scheduling report views
  corehq/apps/reports/tests/test_scheduled_reports.py
  corehq/apps/reports/views.py
  corehq/apps/reports_core/filters.py
  corehq/apps/saved_reports/models.py
  corehq/apps/userreports/reports/util.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#33533 Case Search Geocoder - Adds Search by City, Zipcode, or State
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/feature-flag, Risk: Medium

#33550 add empty display element
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/tests/test_suite_formats.py
Labels: product/invisible

#33534 Update attrs to 23.1.0
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33481 Web apps signature capture question type
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  package.json
  yarn.lock
Labels: QA Passed, product/feature-flag, dependencies, Risk: Medium

#33545 Misc reporting cleanup (no functional changes)
  corehq/apps/app_manager/tasks.py
  corehq/apps/callcenter/sync_usercase.py
  corehq/apps/callcenter/tests/test_indicators.py
  corehq/apps/callcenter/tests/test_location_owners.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/generic.py
  corehq/apps/reports/models.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/utils.py
  corehq/apps/reports/standard/inspect.py
  corehq/apps/reports/templates/reports/filters/filter_users.html
  corehq/apps/users/tests/retire.py
  settings.py
Labels: product/invisible

#33403 Add unique constraints to prevent race conditions
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/migrations/0087_invoice_unique_constraints.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_race_condition_is_prevented.py
  migrations.lock
Labels: reindex/migration, product/invisible

#33538 Add filters for cases on "Manage GPS Data" page
  corehq/apps/geospatial/filters.py
  corehq/apps/geospatial/static/geospatial/js/gps_capture.js
  corehq/apps/geospatial/templates/base_template.html
  corehq/apps/geospatial/templates/geospatial/map_visualization_base.html
  corehq/apps/geospatial/templates/gps_capture.html
  corehq/apps/geospatial/templates/gps_capture_view.html
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/views.py
  corehq/apps/reports/generic.py
  corehq/apps/reports/standard/cases/basic.py
Labels: product/feature-flag

#33559 [USH-3711] Updated allowed heights logic in case tile definition UI
  corehq/apps/app_manager/static/app_manager/js/details/column.js
Labels: product/feature-flag
