Repository dimagi/commcare-hq, pull requests merged in 2023-05, with the labels that each got.

#32891 Restrict logo file size
  corehq/apps/domain/forms.py
Labels: product/all-users-all-environments

#32820 Upgrade Sentry, Requests, Boto3 to latest version
  corehq/warnings.py
  requirements/Makefile
  requirements/dev-requirements.txt
  requirements/docs-requirements.in
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#32855 Allow end of form navigation from multi to single-select forms
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
Labels: QA Passed, product/feature-flag

#32915 Revert "Obfuscate URL on Case List and Case List Explorer pages"
  corehq/apps/reports/static/reports/js/reports.async.js
  corehq/apps/reports/tasks.py
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
Labels: product/all-users-all-environments, product/feature-flag

#32912 Upgrade diff-match-patch
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#32911 Upgrade Faker
  requirements/dev-requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#32913 Updated case tiles to always treat templates as markdown in web apps
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: product/feature-flag, Risk: Medium

#32916 Upgrade js-xpath to v0.0.7
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#32895 Add instance declaration for assertion xpaths
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/tests/test_suite_assertions.py
Labels: product/feature-flag

#32906 Dhis2Repeater to skip system forms with data from DHIS2
  corehq/motech/dhis2/repeaters.py
  corehq/motech/dhis2/tests/test_repeaters.py
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/tests/test_dbaccessors.py
Labels: product/invisible

#32921 Fix save button for custom assertions
  corehq/apps/app_manager/static/app_manager/js/custom_assertions.js
Labels: product/feature-flag

#32867 [USH-1524] Link sort properties to calculated columns
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/const.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/static/app_manager/js/details/sort_rows.js
  corehq/apps/app_manager/static/app_manager/js/details/utils.js
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_properties.html
  corehq/apps/app_manager/tests/test_suite_sorting.py
  corehq/apps/app_manager/util.py
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-input.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/ui-element-select.js
Labels: awaiting QA, product/all-users-all-environments

#32919 Create radial cost matrix proximity algorithm
  corehq/apps/geospatial/exceptions.py
  corehq/apps/geospatial/models.py
  corehq/apps/geospatial/tests.py
  corehq/apps/geospatial/tests/__init__.py
  corehq/apps/geospatial/tests/test_models.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#32838 Add `export_ownership` privilege to pro plan or higher
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0073_export_ownership_priv.py
  corehq/apps/export/static/export/js/export_list.js
  corehq/apps/export/static/export/js/export_list_main.js
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/apps/export/templates/export/export_list.html
  corehq/apps/export/templates/export/partials/table.html
  corehq/apps/export/views/list.py
  corehq/apps/export/views/new.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/users/templates/users/roles_and_permissions.html
  corehq/apps/users/views/__init__.py
  corehq/privileges.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32818 [USH-3094] POC HL7v2 API using the generic inbound API
  corehq/motech/generic_inbound/backend/__init__.py
  corehq/motech/generic_inbound/backend/base.py
  corehq/motech/generic_inbound/backend/hl7.py
  corehq/motech/generic_inbound/backend/json.py
  corehq/motech/generic_inbound/core.py
  corehq/motech/generic_inbound/forms.py
  corehq/motech/generic_inbound/migrations/0006_backend_external_response.py
  corehq/motech/generic_inbound/models.py
  corehq/motech/generic_inbound/templates/generic_inbound/api_edit.html
  corehq/motech/generic_inbound/tests/data/adt_a01_2.8.er7
  corehq/motech/generic_inbound/tests/data/adt_a01_2.8.json
  corehq/motech/generic_inbound/tests/data/oru_r01_2.5.1.er7
  corehq/motech/generic_inbound/tests/data/oru_r01_2.5.1.json
  corehq/motech/generic_inbound/tests/test_api.py
  corehq/motech/generic_inbound/tests/test_api_hl7.py
  corehq/motech/generic_inbound/tests/test_api_processing.py
  corehq/motech/generic_inbound/tests/test_hl7_json_conversion.py
  corehq/motech/generic_inbound/utils.py
  corehq/motech/generic_inbound/views.py
  migrations.lock
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: reindex/migration, product/feature-flag, dependencies

#32926 Just use `venv`
  DEV_SETUP.md
Labels: product/invisible

#32932 Fix incorrect sort query
  corehq/apps/es/es_query.py
  corehq/apps/es/tests/test_sorting.py
Labels: product/invisible

#32931 Ze/change icons in repeat record report
  corehq/motech/repeaters/templates/repeaters/repeat_record_report.html
  corehq/motech/repeaters/views/repeat_records.py
Labels: product/all-users-all-environments

#32935 Update comment to provide clarity on terms
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
Labels: product/invisible

#32941 Attendance Tracking | Order events by descending start time
  corehq/apps/events/models.py
  corehq/apps/events/views.py
Labels: product/feature-flag

#32946 Added toggle help link
  corehq/toggles/__init__.py
Labels: product/admin

#32944 Module to check privileges in JS
  corehq/apps/hqwebapp/static/hqwebapp/js/privileges.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/util/context_processors.py
  docs/js-guide/integration-patterns.rst
  settings.py
Labels: product/invisible, Risk: Medium

#32945 API Key auth for repeaters
  corehq/motech/auth.py
  corehq/motech/const.py
  corehq/motech/migrations/0013_alter_connectionsettings_auth_type.py
  corehq/motech/models.py
  corehq/motech/static/motech/js/connection_settings_detail.js
  migrations.lock
Labels: reindex/migration

#32953 lbounds in mapbox response can be undefined
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
Labels: Risk: Medium

#32948 don't make a details request if there is no details view configured
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#32940 Accessiblity: Screen Readable Labels widget for Forms
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: Risk: Medium

#32954 Rc/force annual tos
  corehq/apps/api/resources/v0_1.py
  corehq/apps/api/tests/user_resources.py
  corehq/apps/registration/views.py
  corehq/apps/users/models.py
  corehq/apps/users/views/__init__.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/toggles/__init__.py
Labels: product/feature-flag, Risk: High

#32955 Improve bulk case import workflow
  corehq/apps/case_importer/static/case_importer/js/main.js
  corehq/apps/case_importer/templates/case_importer/excel_config.html
  corehq/apps/case_importer/templates/case_importer/excel_fields.html
  corehq/apps/case_importer/views.py
Labels: product/all-users-all-environments, Risk: High

#32970 fix type for version in License Agreement
  corehq/apps/registration/views.py
Labels: product/feature-flag, Risk: High

#32928 Markdown for case lists
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/static/app_manager/js/details/utils.js
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#32933 Make case tile widths dynamic
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
Labels: QA Passed, product/feature-flag, Risk: Medium

#32947 remove migration that is no longer viable
  corehq/apps/app_manager/management/commands/migrate_to_conditional_case_update.py
  corehq/apps/app_manager/migrations/0022_migrate_to_conditional_case_update.py
  corehq/apps/app_manager/migrations/0026_conditional_case_update_deleted_apps.py
Labels: reindex/migration, product/invisible

#32951 Remove two-factor backup token from user pages
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/edit_web_user.html
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
Labels: product/all-users-all-environments

#32974 Add support for case search to case tiles
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/tests/test_suite_case_tiles.py
Labels: product/feature-flag

#32918 Remove redundant `navigate_menu` request from case search
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: QA Passed, product/invisible, Risk: Medium

#32973 Reduce hard coding in case tile templates
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/case_tile_templates/person_simple.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/person_simple.xml
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_properties.html
  corehq/apps/app_manager/views/modules.py
Labels: product/invisible

#32992 Show the name of the repeater / remote service
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/views/repeat_record_display.py
  corehq/motech/repeaters/views/repeat_records.py
Labels: product/invisible

#32962 Repeat records view responses change
  corehq/motech/repeaters/static/repeaters/js/repeat_record_report.js
  corehq/motech/repeaters/templates/repeaters/partials/attempt_history.html
  corehq/motech/repeaters/tests/test_display.py
  corehq/motech/repeaters/views/repeat_record_display.py
  corehq/motech/repeaters/views/repeat_records.py
Labels: product/all-users-all-environments

#32883 Dependent Dropdown/Checkbox Bug Fix
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/query_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
  corehq/apps/cloudcare/templates/cloudcare/spec/mocha.html
  corehq/apps/cloudcare/templates/formplayer/query_view.html
Labels: QA Passed, product/feature-flag, Risk: Medium

#32960 Replace scripts with github action that collects dependency metrics
  .github/workflows/dependency-metrics.yml
  docker/run.sh
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  scripts/outdated-dependency-metrics.py
  scripts/track-dependency-status.sh
  scripts/yarn-list.py
Labels: dependencies

#32993 Delivery Attempts column shows timestamps
  corehq/motech/repeaters/templates/repeaters/partials/attempt_history.html
Labels: product/invisible

#32952 Update repeat record column headers
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/templates/repeaters/partials/attempt_history.html
  corehq/motech/repeaters/views/repeat_record_display.py
  corehq/motech/repeaters/views/repeat_records.py
Labels: product/all-users-all-environments

#33007 Bump git-build-branch from v0.1.14 to v0.1.15
  requirements/dev-requirements.txt
Labels: dependencies

#32996 import version const and update pre-existing eula
  corehq/apps/registration/views.py
  corehq/apps/users/models.py
Labels: product/feature-flag, Risk: High

#32988 Accessibility: Screen reader accessible help button on forms
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/form.less
Labels: QA Passed, Risk: Medium

#32969 Remove UCR experiment code
  corehq/apps/app_manager/fixtures/mobile_ucr.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  corehq/apps/userreports/admin.py
  corehq/apps/userreports/laboratory/__init__.py
  corehq/apps/userreports/laboratory/experiment.py
  corehq/apps/userreports/migrations/0020_delete_ucr_comparison_models.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/tests/test_resume_rebuild.py
  corehq/tests/locks.py
  corehq/toggles/__init__.py
  migrations.lock
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  serializer-pickle-files.lock
  settings.py
Labels: reindex/migration, dependencies

#33000 Obfuscate URL on Case List and Case List Explorer pages (version 2)
  corehq/apps/reports/static/reports/js/hq_report.js
  corehq/apps/reports/static/reports/js/reports.async.js
  corehq/apps/reports/tasks.py
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
Labels: QA Passed, product/all-users-all-environments, product/feature-flag

#32997 Add deleted_on field to AutomaticUpdateRule, Broadcast, and Schedule
  corehq/apps/cleanup/tests/test_utils.py
  corehq/apps/cleanup/utils.py
  corehq/apps/data_interfaces/migrations/0033_automaticupdaterule_deleted_on.py
  corehq/apps/data_interfaces/models.py
  corehq/messaging/scheduling/migrations/0025_schedule_and_broadcast_deleted_on.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/models/alert_schedule.py
  corehq/messaging/scheduling/models/timed_schedule.py
  corehq/sql_db/tests/test_utils.py
  corehq/sql_db/util.py
  migrations.lock
Labels: reindex/migration, product/invisible

#33008 Revert "Remove UCR experiment code"
  corehq/apps/app_manager/fixtures/mobile_ucr.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  corehq/apps/userreports/admin.py
  corehq/apps/userreports/laboratory/__init__.py
  corehq/apps/userreports/laboratory/experiment.py
  corehq/apps/userreports/migrations/0020_delete_ucr_comparison_models.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/tests/test_resume_rebuild.py
  corehq/tests/locks.py
  corehq/toggles/__init__.py
  migrations.lock
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  serializer-pickle-files.lock
  settings.py
Labels: reindex/migration, dependencies

#33009 Create DeletedCouchDoc table
  corehq/apps/cleanup/migrations/0014_deletedcouchdoc.py
  corehq/apps/cleanup/models.py
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#32943 Event.location
  corehq/apps/es/tests/utils.py
  corehq/apps/events/es.py
  corehq/apps/events/forms.py
  corehq/apps/events/migrations/0010_event_location.py
  corehq/apps/events/models.py
  corehq/apps/events/static/events/js/new_event.js
  corehq/apps/events/templates/events_list.html
  corehq/apps/events/tests/test_es.py
  corehq/apps/events/tests/test_forms.py
  corehq/apps/events/tests/test_models.py
  corehq/apps/events/views.py
  corehq/ex-submodules/casexml/apps/case/tests/test_close_extension_chain.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#33010 Remove UCR Experiment (code only)
  corehq/apps/app_manager/fixtures/mobile_ucr.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/userreports/admin.py
  corehq/apps/userreports/laboratory/__init__.py
  corehq/apps/userreports/laboratory/experiment.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/tests/test_resume_rebuild.py
  corehq/tests/locks.py
  corehq/toggles/__init__.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  serializer-pickle-files.lock
  settings.py
Labels: product/invisible, dependencies

#33012 Upgrade dependency-metrics from v0.1.0 to v0.1.1
  requirements/dev-requirements.txt
Labels: dependencies

#32902 DD case data styling
  corehq/apps/hqwebapp/static/hqwebapp/css/proptable.css
  corehq/apps/reports/standard/cases/case_data.py
  corehq/apps/reports/static/reports/js/case_details.js
  corehq/apps/reports/templates/reports/reportdata/case_data.html
Labels: product/feature-flag

#33015 Revert "[B5 Migration] Add support for ES6 Modules and split core javascript into bootstrap5 and bootstrap3 versions"
  .github/labels.yml
  corehq/apps/cloudcare/templates/formplayer-common/base.html
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/static/hqwebapp/js/base_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/sticky_tabs.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/base_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/common.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5_loader.js
  corehq/apps/hqwebapp/static/hqwebapp/js/common.js
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/js/sticky_tabs.js
  corehq/apps/hqwebapp/static/hqwebapp/yaml/bootstrap3/requirejs.yml
  corehq/apps/hqwebapp/static/hqwebapp/yaml/requirejs.yml
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/core_libraries.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/requirejs.html
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/templatetags/tests/rendered/javascript_libraries_hq.html
  corehq/apps/hqwebapp/templatetags/tests/rendered/javascript_libraries_hq_bootstrap5.html
  corehq/apps/hqwebapp/templatetags/tests/templates/javascript_libraries_hq.html
  corehq/apps/hqwebapp/templatetags/tests/test_tag.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diff_config.json
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/base_main.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/common.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/requirejs_config.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/sticky_tabs.js.diff.txt
  corehq/apps/hqwebapp/tests/test_requirejs.py
  docs/js-guide/migrating.rst
  package.json
  yarn.lock
Labels: dependencies, Risk: High, Risk: Medium

#32554 Sync data after claim: check date modification dates
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/test_suite.py
  corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py
  corehq/apps/app_manager/tests/util.py
  corehq/apps/case_search/migrations/0012_casesearchconfig_sync_cases_on_form_entry.py
  corehq/apps/case_search/models.py
  corehq/apps/domain/static/domain/js/case_search.js
  corehq/apps/domain/templates/domain/admin/case_search.html
  corehq/apps/domain/views/settings.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/apps/ota/views.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/feature-flag, product/invisible

#32991 Upgrade Dependencies to fix issues with Apple Silicon
  DEV_SETUP_MAC.md
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33019 Update tornado version to 6.3.2
  requirements/prod-requirements.txt
Labels: dependencies

#32821 Data Dictionary: Migration for group field to a model - 2
  corehq/apps/data_dictionary/migrations/0012_populate_case_property_groups.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/tests/test_update_data_dictionary.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/reports/standard/cases/case_data.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32995 Accessibility: Screen readable breadcrumbs and improved dropdown
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/breadcrumbs.less
Labels: QA Passed, Risk: Medium

#32987 Ensure location from domain when creating CommCare User
  corehq/apps/users/forms.py
  corehq/apps/users/views/mobile/users.py
Labels: QA Passed, product/all-users-all-environments, product/invisible

#32897 Disable account access for unverified accouts
  corehq/apps/domain/decorators.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/settings/views.py
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments

#32949 Update node installation for required minimum version
  DEV_SETUP.md
Labels: product/invisible

#33034 Strip email part from attendance takers' usernames
  corehq/apps/events/forms.py
Labels: product/feature-flag

#33027 Change case history arrow column
  corehq/apps/reports/templates/reports/reportdata/case_data.html
Labels: product/all-users-all-environments

#32942 Riese/multi select case tile
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_test.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
Labels: awaiting QA, product/feature-flag, Risk: Medium

#33043 Filtered bulk user download to GA
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0074_filtered_bulk_user_download_priv.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/users/decorators.py
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/tests/test_views.py
  corehq/privileges.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration

#33014 Ancestor-exists() Case Query Function and Allow multiple terms case search field
  corehq/apps/case_search/models.py
  corehq/apps/case_search/tests/test_ancestor_functions.py
  corehq/apps/case_search/tests/test_models.py
  corehq/apps/case_search/utils.py
  corehq/apps/case_search/xpath_functions/__init__.py
  corehq/apps/case_search/xpath_functions/ancestor_functions.py
  corehq/apps/case_search/xpath_functions/comparison.py
  corehq/apps/case_search/xpath_functions/value_functions.py
Labels: QA Passed, product/feature-flag

#33031 Create unique constraint on doc_id and doc_type
  corehq/apps/cleanup/migrations/0015_deletedcouchdoc_unique_id_and_type.py
  corehq/apps/cleanup/models.py
  migrations.lock
Labels: reindex/migration
