Repository dimagi/commcare-hq, pull requests merged in 2023-12, with the labels that each got.

#33832 Bump cryptography from 41.0.4 to 41.0.6 in /requirements
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33833 add username filter to link query
  corehq/apps/domain/auth.py
Labels: product/invisible

#33837 Modify ChangeMeta to support dynamic properties
  corehq/ex-submodules/pillowtop/feed/interface.py
Labels: product/invisible

#33808 Move deduplication pillow from xform to case processor
  .github/workflows/tests.yml
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/ex-submodules/casexml/apps/case/tests/test_xform.py
  corehq/ex-submodules/casexml/apps/case/tests/xml/test_parser.py
  corehq/ex-submodules/casexml/apps/case/xform.py
  corehq/ex-submodules/casexml/apps/case/xml/parser.py
  corehq/pillows/case.py
  corehq/pillows/xform.py
Labels: product/invisible

#33835 Jt/form group style adjustment
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/form_ui_spec.js
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/breadcrumbs.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: product/all-users-all-environments, Risk: Medium

#33838 Rc/adjust input size
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
Labels: Risk: Medium

#33807 Add associated document id field to ChangeMeta
  .github/workflows/tests.yml
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/apps/hqcase/utils.py
  corehq/ex-submodules/casexml/apps/case/tests/test_xform.py
  corehq/ex-submodules/casexml/apps/case/tests/xml/test_parser.py
  corehq/ex-submodules/casexml/apps/case/xform.py
  corehq/ex-submodules/casexml/apps/case/xml/parser.py
  corehq/ex-submodules/pillowtop/feed/interface.py
  corehq/form_processor/backends/sql/processor.py
  corehq/form_processor/change_publishers.py
  corehq/pillows/case.py
  corehq/pillows/xform.py
Labels: product/invisible, Risk: High

#33839 Bump django-prbac from 1.0.1 to 1.1.0
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33820 Anchored Submit Button for Web Apps
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/includes/variables.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables_bootstrap3.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables_bootstrap3.style.diff.txt
  corehq/toggles/__init__.py
Labels: product/all-users-all-environments, product/feature-flag, Risk: Medium

#33848 Fix stack generation for query datum Endpoints
  corehq/apps/app_manager/suite_xml/post_process/endpoints.py
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/test_suite_session_endpoints.py
Labels: product/custom

#33826 Moved repeat group button in web apps away from border
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#33849 Add config for lazy loading case lists
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/module_view.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_lazy_loading.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_settings.html
  corehq/apps/app_manager/views/modules.py
  corehq/toggles/__init__.py
Labels: Core Compatibility

#33847 add second button
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/multi_select_continue_button.html
Labels: product/feature-flag, Risk: Medium

#33759 Handle request failure on disbursement runs
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
Labels: product/feature-flag

#33844 Apply repeat striping with stripe-repeats appearance attribute
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: product/all-users-all-environments, Risk: Medium

#33857 Speed up User API
  corehq/apps/api/query_adapters.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_user_data.py
  corehq/apps/users/user_data.py
Labels: Risk: High

#33795 Cs/sc 3067 set up repeater on ds get
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/userreports/urls.py
  corehq/apps/userreports/views.py
Labels: product/feature-flag, product/invisible

#33863 Cap active banners to 3 max
  corehq/apps/domain/templates/domain/admin/manage_alerts.html
  corehq/apps/domain/views/settings.py
Labels: product/feature-flag

#33767 Add chunk size argument to load_domain_data
  corehq/apps/dump_reload/couch/load.py
  corehq/util/couch.py
Labels: product/invisible

#33874 Add a new permission for managing project alerts
  corehq/apps/domain/views/settings.py
  corehq/apps/users/decorators.py
  corehq/apps/users/migrations/0056_add_manage_domain_alerts_permission.py
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/tabs/tabclasses.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#33738 Inline Case Search Parent Select
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/tests/test_build_errors_inline_search.py
  corehq/apps/app_manager/tests/test_suite_inline_search.py
  corehq/apps/app_manager/tests/test_suite_session_endpoints.py
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/xpath.py
Labels: product/feature-flag

#33830 Display mobile UCR count to user
  corehq/apps/app_manager/models.py
  corehq/apps/cloudcare/tests/test_utils.py
  corehq/apps/cloudcare/utils.py
  corehq/apps/cloudcare/views.py
Labels: Risk: Medium

#33729 Enable 'fail_hard' for Bulk User Uploads
  corehq/apps/user_importer/importer.py
  corehq/apps/users/models.py
Labels: product/invisible, Risk: Medium

#33879 Disable permenant deletion task
  corehq/apps/cleanup/tasks.py
Labels: product/invisible

#33869 Linter
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/app_translations/upload_form.py
Labels: product/all-users-all-environments

#33883 New Metric for CommCareHQ Calculated Properties: 365 Active Mobile Workers
  corehq/apps/domain/calculations.py
  corehq/apps/domain/tests/test_domain_calculated_properties.py
Labels: product/invisible

#33878 Form submit button: Add check for document.visibilityState
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
Labels: product/all-users-all-environments, Risk: Medium

#33876 Hide Search and Clear buttons
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/split_screen_case_search_spec.js
Labels: Risk: Medium

#33894 fix silentlly failing query_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/query_spec.js
Labels: product/invisible

#33895 Show case tile sort options in configured order, not header order
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: Risk: Medium

#33827 Removed question labels altogether when they have no content
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#33887 Underlines links created via markup
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/markdown.js
  corehq/apps/cloudcare/static/cloudcare/js/spec/markdown_spec.js
Labels: Risk: Medium

#33897 Proteusvacuum fr/add rich text emails waf
  corehq/apps/hqwebapp/static/hqwebapp/js/ckeditor_knockout_bindings.js
  corehq/apps/sms/migrations/0058_email_html_body.py
  corehq/apps/sms/models.py
  corehq/blobs/__init__.py
  corehq/messaging/scheduling/const.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0027_emailcontent_html_message.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
  corehq/messaging/scheduling/tasks.py
  corehq/messaging/scheduling/templates/scheduling/conditional_alert.html
  corehq/messaging/scheduling/templates/scheduling/create_schedule.html
  corehq/messaging/scheduling/templates/scheduling/create_schedule_base.html
  corehq/messaging/scheduling/templates/scheduling/partials/rich_text_email_template.html
  corehq/messaging/scheduling/templates/scheduling/partials/rich_text_message_configuration.html
  corehq/messaging/scheduling/templates/scheduling/rich_text_email_styles.css
  corehq/messaging/scheduling/tests/test_views.py
  corehq/messaging/scheduling/urls.py
  corehq/messaging/scheduling/views.py
  corehq/toggles/__init__.py
  migrations.lock
  package.json
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
  yarn.lock
Labels: reindex/migration, dependencies

#33798 Rich text emails
  corehq/apps/hqwebapp/static/hqwebapp/js/ckeditor_knockout_bindings.js
  corehq/apps/sms/migrations/0058_email_html_body.py
  corehq/apps/sms/models.py
  corehq/blobs/__init__.py
  corehq/messaging/scheduling/const.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0027_emailcontent_html_message.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.ko.js
  corehq/messaging/scheduling/tasks.py
  corehq/messaging/scheduling/templates/scheduling/conditional_alert.html
  corehq/messaging/scheduling/templates/scheduling/create_schedule.html
  corehq/messaging/scheduling/templates/scheduling/create_schedule_base.html
  corehq/messaging/scheduling/templates/scheduling/partials/rich_text_email_template.html
  corehq/messaging/scheduling/templates/scheduling/partials/rich_text_message_configuration.html
  corehq/messaging/scheduling/templates/scheduling/rich_text_email_styles.css
  corehq/messaging/scheduling/tests/test_views.py
  corehq/messaging/scheduling/urls.py
  corehq/messaging/scheduling/views.py
  corehq/toggles/__init__.py
  migrations.lock
  package.json
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
  yarn.lock
Labels: reindex/migration, dependencies

#33898 WebApps UI for grouped search fields
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/fake_formplayer.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/fixtures/split_screen_case_list.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/query_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/split_screen_case_search_spec.js
  corehq/apps/cloudcare/templates/cloudcare/spec/mocha.html
  corehq/apps/cloudcare/templates/formplayer/query_view.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/query.less
Labels: Risk: Medium

#33828 Jt/visually segmented query search categories
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_property.html
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
Labels: QA Passed, product/feature-flag, Core Compatibility

#33885 Form submission notification text translation
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/app_translations/upload_form.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: product/all-users-all-environments

#33868 Form submit button translation
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/app_translations/upload_form.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: product/all-users-all-environments, Risk: Medium

#33900 Case Search Screen Style
  corehq/apps/cloudcare/templates/formplayer/query_view.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/query.less
Labels: Risk: Medium

#33881 Form model changes for text translations
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/data/yesno_default_app_strings.txt
  corehq/apps/app_manager/tests/data/yesno_en_app_strings.txt
  corehq/apps/app_manager/tests/data/yesno_es_app_strings.txt
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/app_translations/upload_form.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
  corehq/form_processor/submission_post.py
Labels: Risk: High, Risk: Medium

#33905 Add force_manual_search to request for case search validation
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/feature-flag, Risk: Medium

#33908 Rc/case tile shading
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/style_configuration_modal.html
  corehq/apps/app_manager/tests/test_report_config.py
  corehq/apps/app_manager/tests/test_suite_case_tiles.py
  corehq/apps/app_manager/tests/test_suite_custom_case_tiles.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: Risk: Medium, Core Compatibility

#33919 Added visibility binding for case tile dropdown
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
Labels: product/feature-flag

#33917 Extracted templates in app manager
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_tile_preview.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_tile_templates.html
Labels: product/invisible
