Repository dimagi/commcare-hq, pull requests merged in 2023-10, with the labels that each got.

#33568 Prevent HTML error on validating empty case property input
  corehq/apps/data_interfaces/static/data_interfaces/js/case_property_input.js
Labels: product/invisible

#33558 Fix duplicate session id error message
  corehq/apps/app_manager/tests/views/test_session_endpoint_utils.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/data_interfaces/models.py
Labels: product/feature-flag

#33563 Drop the Late PMT 2019 custom report
  custom/abt/reports/__init__.py
  custom/abt/reports/late_pmt.py
Labels: product/custom, product/invisible

#33530 Set ES case_search replicas to 0 for dev envs
  dev_settings.py
Labels: product/invisible

#33517 Improve property selection for deduplication
  corehq/apps/data_interfaces/static/data_interfaces/js/case_dedupe_main.js
  corehq/apps/data_interfaces/static/data_interfaces/js/case_property_input.js
  corehq/apps/data_interfaces/templates/data_interfaces/edit_deduplication_rule.html
Labels: product/invisible

#33524 Web apps responsive design updates
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/spec/utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/apps/cloudcare/templates/formplayer/pagination.html
  corehq/apps/cloudcare/templates/formplayer/query_view.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/breadcrumbs.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/menu.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/query.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/includes/variables.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables_bootstrap3.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables_bootstrap3.style.diff.txt
  package.json
  yarn.lock
Labels: QA Passed, product/all-users-all-environments, product/feature-flag, dependencies, Risk: Medium

#33529 Clickable Icon UI
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: Risk: Medium

#33580 Update dependabot.yml to check Github actions
  .github/dependabot.yml
Labels: product/invisible

#33567 Don't fail usercase task on missing users
  corehq/apps/callcenter/tasks.py
  corehq/apps/users/models.py
Labels: product/invisible

#33588 remove travis build config
  .travis.yml
Labels: product/invisible

#33560 endpoint action
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/module_view.html
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/tests/test_suite_formats.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/toggles/__init__.py
Labels: product/feature-flag, Core Compatibility

#33594 Move help popovers in small screen SSCS
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/hq.helpers.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/hq.helpers.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/hq.helpers.js.diff.txt
Labels: QA Passed, product/feature-flag, Risk: Medium

#33507 Add configure case grouping page
  corehq/apps/geospatial/README.md
  corehq/apps/geospatial/forms.py
  corehq/apps/geospatial/migrations/0004_auto_20230920_0821.py
  corehq/apps/geospatial/models.py
  corehq/apps/geospatial/static/geospatial/js/geo_config.js
  corehq/apps/geospatial/templates/geospatial/settings.html
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/views.py
  corehq/tabs/tabclasses.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#33602 PEP8 line length for easier reading
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
Labels: product/invisible

#33598 Add Geospatial Case Grouping Page
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/templates/case_grouping_map.html
  corehq/apps/geospatial/templates/geospatial/case_grouping_map_base.html
  corehq/apps/geospatial/tests/test_reports.py
Labels: product/feature-flag

#33577 Clean up logic in _process_repeat_record
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/tests/test_tasks.py
Labels: product/invisible

#33613 Remove unused disbursement algorithms
  corehq/apps/geospatial/models.py
  corehq/apps/geospatial/tests/test_models.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/feature-flag, product/invisible, dependencies

#33518 [USH-3466,3469] Email Gateway Settings
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/email/__init__.py
  corehq/apps/email/forms.py
  corehq/apps/email/migrations/0001_initial.py
  corehq/apps/email/migrations/__init__.py
  corehq/apps/email/models.py
  corehq/apps/email/static/email/js/email_settings.js
  corehq/apps/email/templates/email/email_settings.html
  corehq/apps/email/tests/__init__.py
  corehq/apps/email/tests/test_email_form.py
  corehq/apps/email/urls.py
  corehq/apps/email/views.py
  corehq/tabs/tabclasses.py
  corehq/toggles/__init__.py
  migrations.lock
  settings.py
  urls.py
Labels: reindex/migration, product/feature-flag

#33556 vellum:9f539058684ab5d834fcad120e5b41c9550536b6
  corehq/apps/app_manager/static/app_manager/js/vellum/src/main-components.js
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: product/feature-flag

#33605 Replace invoice logo
  corehq/apps/accounting/invoice_pdf.py
  corehq/apps/accounting/static/accounting/images/Dimagi-Deep-Purple-Standard-Logo.jpg
  corehq/apps/accounting/static/accounting/images/Dimagi-Logo-RGB.jpg
Labels: product/prod-india-all-users

#33551 Add clean up command for custom variables
  corehq/apps/app_manager/management/commands/delete_case_list_custom_variables_xml.py
  corehq/apps/app_manager/migrations/0029_delete_case_list_custom_variable_xml.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_delete_case_list_custom_variables_xml.py
  migrations.lock
Labels: reindex/migration

#33610 Export Case Groups to CSV
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/templates/case_grouping_map.html
Labels: product/feature-flag

#33562 Dynamic search: fix for single date field
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/feature-flag, Risk: Medium

#33611 Collapsible tiles
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
Labels: Risk: Medium

#33625 Update CommCare and Dimagi Logos
  corehq/apps/hqwebapp/_fonts/commcarehq_font/CommCareHQFont.glyphs
  corehq/apps/hqwebapp/static/app_manager/less/font-workflow/core.less
  corehq/apps/hqwebapp/static/app_manager/less/img/loading_flower.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-flower-lg.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-flower.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-120x120.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-152x152.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-167x167.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-180x180.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-57x57.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-76x76.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-logo-mobile.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-logo-small.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcarehq-icon-large.png
  corehq/apps/hqwebapp/static/hqwebapp/font/CommCareHQFont-Regular.otf
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehqfont-regular.eot
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehqfont-regular.svg
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehqfont-regular.ttf
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehqfont-regular.woff
  corehq/apps/hqwebapp/static/hqwebapp/images/commcare-flower-footer.png
  corehq/apps/hqwebapp/static/hqwebapp/images/commcare-flower.png
  corehq/apps/hqwebapp/static/hqwebapp/images/dimagi-footer.png
  corehq/apps/hqwebapp/static/hqwebapp/images/favicon.png
  corehq/apps/hqwebapp/static/hqwebapp/images/favicon2.png
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/includes/variables.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/navbar.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_navbar.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables_bootstrap3.scss
  corehq/apps/hqwebapp/templates/hqwebapp/svg/dimagi_logo.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables_bootstrap3.style.diff.txt
Labels: product/all-users-all-environments

#33626 Do not use force rerun with migration
  corehq/apps/app_manager/migrations/0029_delete_case_list_custom_variable_xml.py
Labels: reindex/migration

#33624 Removed Jenny from front end files in CODEOWNERS
  .github/CODEOWNERS
Labels: product/invisible

#33553 Correctly map dedupe user properties to their system equivalents
  corehq/apps/data_interfaces/migrations/0034_case_name_actions.py
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/ex-submodules/casexml/apps/case/tests/xml/__init__.py
  corehq/ex-submodules/casexml/apps/case/tests/xml/test_parser.py
  corehq/ex-submodules/casexml/apps/case/xml/parser.py
  migrations.lock
Labels: reindex/migration, product/invisible

#33570 Add more filters for software plan
  corehq/apps/accounting/async_handlers.py
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/static/accounting/js/base_subscriptions_main.js
  corehq/apps/accounting/static/accounting/js/subscriptions_main.js
  corehq/apps/accounting/tests/test_software_plan_version_filter.py
Labels: product/admin

#33631 Upgrade executing from v0.8.3 to v2.0.0
  requirements/dev-requirements.txt
  requirements/prod-requirements.txt
Labels: dependencies

#33633 Update registration form styling to remove old commcare mobile background
  corehq/apps/domain/templates/login_and_password/login.html
  corehq/apps/hqwebapp/static/hqwebapp/images/molly.jpg
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/backgrounds.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/includes/variables.less
  corehq/apps/hqwebapp/static/registration/less/registration-main.less
  corehq/apps/hqwebapp/templates/hqwebapp/iframe_domain_login.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/backgrounds._backgrounds.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables_bootstrap3.style.diff.txt
  corehq/apps/registration/static/registration/js/login.js
  corehq/apps/registration/templates/registration/partials/choose_your_plan.html
  corehq/apps/registration/templates/registration/partials/feature_list.html
  package.json
  yarn.lock
Labels: dependencies

#33642 Remove obsolete backward compatibility flag for case search dropdowns
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/query_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
Labels: Risk: Medium

#33639 Dynamic Clustering + Map for Case Grouping Page
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/templates/case_grouping_map.html
Labels: product/feature-flag

#33649 Location filter for mobile workers on Case Management page
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/templates/geospatial/map_visualization_base.html
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#33621 Case search custom ES sort
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/test_suite_remote_request.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/case_search/models.py
  corehq/apps/case_search/tests/test_case_search_es_queries.py
  corehq/apps/case_search/tests/test_models.py
  corehq/apps/case_search/tests/utils.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/case_search.py
  corehq/apps/es/es_query.py
  corehq/apps/es/tests/test_sorting.py
Labels: QA Passed, product/feature-flag

#33418 Alter Repeater and SQLRepeatRecord columns for the Couch to SQL migration
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/motech/repeaters/apps.py
  corehq/motech/repeaters/migrations/0003_id_fields.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tasks.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/invisible

#33655 Fix subscription form validation error
  corehq/apps/accounting/forms.py
Labels: QA Passed, product/admin

#33654 Hide locations filter on failed update rule submissions
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_criteria.js
  corehq/apps/data_interfaces/tests/test_forms.py
Labels: product/invisible

#33659 switch default value of useDynamicSearch in notifyParentOfFieldChange
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/feature-flag, Risk: Medium

#33667 Dynamically set case tile row options based on number of properties
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
Labels: product/feature-flag

#33634 Add 365 days option to auto-deactivation Inactivity Period
  corehq/apps/enterprise/forms.py
Labels: product/feature-flag

#33675 Remove redundant metric
  corehq/apps/hqwebapp/tasks.py
Labels: product/invisible

#33661 Disable changing used geolocation property
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
Labels: product/feature-flag

#33677 Upgrade gevent sub-dependencies
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#33676 Upgrade Faker
  requirements/dev-requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#33670 Add migration to resolve whitelist bug on existing repeaters
  corehq/motech/repeaters/migration_utils.py
  corehq/motech/repeaters/migrations/0004_fix_whitelist_bug_repeaters.py
  corehq/motech/repeaters/tests/test_migration_utils.py
  migrations.lock
Labels: reindex/migration

#33644 Fixes for QA for custom domain banners
  corehq/apps/domain/auth.py
  corehq/apps/domain/decorators.py
  corehq/apps/domain/tests/test_auth.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
Labels: Risk: High

#33645 Fix clickable icons on tiles
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/suite_xml/case_tile_templates/icon_text_grid.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_3X_two_4X_one_2X.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one_one.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_two.xml
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: Risk: Medium

#33683 Update case after clickable icon update
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#33686 Disable dynamic search until first search
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
Labels: product/feature-flag, Risk: Medium
