Repository dimagi/commcare-hq, pull requests merged in 2023-03, with the labels that each got.

#32677 Hide couchdb unclosed socket warnings in tests
  DEV_SETUP.md
  testsettings.py
Labels: product/invisible

#32678 Switch to HubSpot new token model
  corehq/apps/analytics/README.md
  corehq/apps/analytics/management/commands/blocked_hubspot_users_summary.py
  corehq/apps/analytics/tasks.py
  corehq/apps/analytics/utils/hubspot.py
  corehq/util/context_processors.py
  corehq/util/tests/test_context_processors.py
  settings.py
Labels: product/invisible

#32668 Resolve sphinx warnings
  corehq/apps/builds/README.rst
  corehq/apps/es/README.rst
  corehq/apps/es/client.py
  corehq/apps/es/es_query.py
  corehq/apps/userreports/README.rst
  corehq/apps/userreports/expressions/list_specs.py
  docs/apps/suite_generation.rst
  docs/couch_to_sql_models.rst
  docs/documenting.rst
  docs/es_query.rst
  docs/js-guide/migrating.rst
  docs/metrics.rst
  docs/sso/local_setup.rst
  docs/translations.rst
  docs/ui_helpers.rst
  docs/web_apps.rst
Labels: product/invisible

#32681 Mismatch in help output and actual arg name
  corehq/apps/domain/management/commands/hard_delete_forms_and_cases_in_domain.py
Labels: product/invisible

#32687 ignore direnv files
  .gitignore
Labels: product/invisible

#32672 Cs/sc 2485 create ate page
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/events/__init__.py
  corehq/apps/events/apps.py
  corehq/apps/events/exceptions.py
  corehq/apps/events/forms.py
  corehq/apps/events/migrations/0001_add_events_model.py
  corehq/apps/events/migrations/__init__.py
  corehq/apps/events/models.py
  corehq/apps/events/static/events/js/new_event.js
  corehq/apps/events/templates/events_list.html
  corehq/apps/events/templates/new_event.html
  corehq/apps/events/tests/__init__.py
  corehq/apps/events/tests/test_events.py
  corehq/apps/events/tests/test_views.py
  corehq/apps/events/urls.py
  corehq/apps/events/views.py
  corehq/apps/settings/urls.py
  corehq/apps/users/models.py
  corehq/tabs/config.py
  corehq/tabs/tabclasses.py
  migrations.lock
  settings.py
Labels: reindex/migration, product/feature-flag

#32688 update dev readme with note about running pillows
  DEV_SETUP.md
Labels: product/invisible

#32647 Regex Field Validation to GA
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0068_regex_field_validation_privilege.py
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
  corehq/apps/custom_data_fields/templates/custom_data_fields/custom_data_fields.html
  corehq/apps/custom_data_fields/templates/custom_data_fields/partials/fields_tab.html
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, Risk: Medium

#32685 Add management command to fix broken app docs
  corehq/apps/app_manager/management/commands/fix_unwrappable_apps.py
Labels: product/invisible

#32686 Minor requirements updates
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.in
  requirements/docs-requirements.txt
Labels: dependencies

#32691 Fix app migration management command
  corehq/apps/app_manager/management/commands/fix_unwrappable_apps.py
Labels: product/invisible

#32689 [USH-2911] download reports permission fix
  corehq/apps/users/models.py
  corehq/apps/users/role_utils.py
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/apps/users/tests/test_models_role.py
Labels: product/all-users-all-environments

#32694 Bump myst-parser from 0.18.1 to 0.19.1
  requirements/docs-requirements.txt
Labels: dependencies

#32697 Fully removed the toggles dependency to fix an import bug
  corehq/apps/custom_data_fields/static/custom_data_fields/js/custom_data_fields.js
Labels: Risk: Medium

#32692 Update django-field-audit to v1.2.6
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#32695 Bump sphinx from 5.3.0 to 6.1.3
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
Labels: dependencies

#32675 [USH-2948] fix form datums view
  corehq/apps/app_manager/static/app_manager/js/forms/form_workflow.js
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/templates/app_manager/partials/forms/form_workflow.html
  corehq/apps/app_manager/tests/views/test_get_form_datums.py
  corehq/apps/app_manager/views/forms.py
Labels: product/invisible

#32462 Supports all FHIR resource types
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/views.py
  corehq/apps/hqwebapp/static/data_dictionary/less/data_dictionary.less
  corehq/motech/fhir/const.py
  corehq/motech/fhir/tests/test_utils.py
  corehq/motech/fhir/tests/test_validators.py
  corehq/motech/fhir/utils.py
  corehq/motech/fhir/validators.py
Labels: product/feature-flag

#32202 Use new instance connector definitions
  corehq/apps/app_manager/app_schemas/casedb_schema.py
  corehq/apps/app_manager/app_schemas/tests/test_schema.py
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/tests/data/form_preparation_v2/multi_no_actions.xml
  corehq/apps/app_manager/tests/data/form_preparation_v2/multi_open_update_case.xml
  corehq/apps/app_manager/tests/data/suite/multi_select_case_list/basic_remote_request.xml
  corehq/apps/app_manager/tests/test_suite_inline_search.py
  corehq/apps/app_manager/tests/test_suite_instances.py
  corehq/apps/app_manager/xform.py
Labels: QA Passed, product/invisible

#32628 Homogenize case search and form entry datepickers
  corehq/apps/case_search/models.py
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: awaiting QA, product/feature-flag, Risk: Medium

#32641 Add print button hidden behind hamburger menu in forms
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_test.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/utils_spec.js
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
  corehq/toggles/__init__.py
Labels: QA Passed, product/feature-flag, Risk: Medium

#32715 Fix time entry default values
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
Labels: product/prod-india-all-users, Risk: Medium

#32702 Upgrade NodeJS to 16.x and npm to 8.x
  DEV_SETUP.md
  Dockerfile
  package.json
  yarn.lock
Labels: dependencies

#32710 GA for Location Safe Case Imports FF
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0069_location_safe_case_imports_priv.py
  corehq/apps/case_importer/base.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration

#32716 if signature question make UnsupportedEntry
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
Labels: QA Passed, Risk: Medium

#32718 Drop unused methods
  corehq/apps/data_interfaces/models.py
Labels: product/invisible

#32719 set_location() and unset_location() save the user
  corehq/apps/callcenter/tests/test_location_owners.py
Labels: product/invisible

#32700 Add options and logging to audit_case_search_config
  corehq/apps/app_manager/management/commands/audit_case_search_config.py
Labels: product/invisible

#32722 Add DATA_UPLOAD_MAX_NUMBER_FILES to settings
  settings.py
Labels: product/invisible

#32705 Attendance Tracking: Attendees
  corehq/apps/events/exceptions.py
  corehq/apps/events/forms.py
  corehq/apps/events/models.py
  corehq/apps/events/static/events/js/event_attendees.js
  corehq/apps/events/static/events/js/new_event.js
  corehq/apps/events/templates/event_attendees.html
  corehq/apps/events/templates/events_list.html
  corehq/apps/events/templates/new_event.html
  corehq/apps/events/tests/test_events.py
  corehq/apps/events/tests/test_models.py
  corehq/apps/events/tests/test_views.py
  corehq/apps/events/urls.py
  corehq/apps/events/views.py
  corehq/apps/users/decorators.py
  corehq/tabs/tabclasses.py
Labels: product/invisible

#32698 Remove advanced query search function
  corehq/apps/es/es_query.py
  corehq/apps/es/queries.py
  corehq/apps/es/tests/test_queries.py
  corehq/apps/toggle_ui/utils.py
Labels: product/all-users-all-environments

#32558 Towards making the Case API location-safe
  corehq/apps/api/resources/v0_5.py
  corehq/apps/hqcase/api/get_list.py
  corehq/apps/hqcase/tests/test_case_api_permissions.py
  corehq/apps/hqcase/tests/test_case_list_api.py
  corehq/apps/hqcase/views.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/utils.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/reports/v2/reports/explore_case_data.py
  corehq/ex-submodules/pillowtop/es_utils.py
Labels: Open for review: do not merge, product/invisible, Risk: High

#32737 add help link and parent toggle
  corehq/toggles/__init__.py
Labels: product/invisible

#32732 [B5 Migration] Part 2 of splitting the base templates
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_breadcrumb.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_dropdown.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_forms.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_navbar.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_type.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables.scss
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/bootstrap3/base_navigation.html
  corehq/apps/hqwebapp/templates/hqwebapp/bootstrap5/base_navigation.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/modal_report_issue.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/domain_list_dropdown.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/global_navigation_bar.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/modal_report_issue.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap3/footer.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/footer.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/navigation_left_sidebar.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/base_navigation.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/domain_list_dropdown.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/global_navigation_bar.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/modal_report_issue.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/partials/footer.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/partials/navigation_left_sidebar.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/notifications/partials/global_notifications.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/breadcrumbs._breadcrumb.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/dropdowns._dropdown.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/forms._forms.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/typography._type.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/style-imports.commcarehq.style.diff.txt
  corehq/apps/notifications/templates/notifications/partials/bootstrap5/global_notifications.html
  corehq/tabs/templates/tabs/bootstrap5/menu_main.html
Labels: product/invisible, Risk: Medium

#32741 Attendance Tracking config
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/events/management/__init__.py
  corehq/apps/events/management/commands/__init__.py
  corehq/apps/events/management/commands/set_attendee_case_type.py
  corehq/apps/events/migrations/0002_attendancetrackingconfig.py
  corehq/apps/events/models.py
  corehq/apps/events/tests/test_models.py
  corehq/apps/events/tests/test_views.py
  migrations.lock
Labels: reindex/migration, product/invisible

#32734 Strip tags to address XSS vulnerability
  corehq/apps/app_manager/views/modules.py
Labels: product/invisible

#32749 Fix two year date correction
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
Labels: product/all-users-all-environments, Risk: Medium

#32736 update UCR named expression docs
  corehq/apps/userreports/expressions/specs.py
  corehq/apps/userreports/tests/test_data_source_config.py
Labels: product/invisible

#32711 Implement Bulk Case Reassignment
  corehq/apps/case_importer/do_import.py
  corehq/apps/data_interfaces/dispatcher.py
  corehq/apps/data_interfaces/interfaces.py
  corehq/apps/data_interfaces/static/data_interfaces/js/case_management.js
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/templates/data_interfaces/interfaces/case_management.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_reassign_complete_email.html
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_reassign_status.html
  corehq/apps/data_interfaces/urls.py
  corehq/apps/data_interfaces/views.py
Labels: product/all-users-all-environments

#32742 Fix meta.next URL in web user list view
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/user_resources.py
Labels: product/all-users-all-environments, Risk: High

#32761 Resolve search bar issue in sphinx docs
  docs/conf.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
Labels: dependencies

#32752 Add attendee
  corehq/apps/events/forms.py
  corehq/apps/events/static/events/js/event_attendees.js
  corehq/apps/events/templates/event_attendees.html
  corehq/apps/events/views.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#32766 remove question mark from checkbox option
  corehq/apps/export/templates/export/customize_export_new.html
Labels: product/invisible

#32671 Conditional alert stop sending broadcast when the condition becomes false
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/tasks.py
Labels: QA Passed

#32587 Option to Pull Parent, Child, and Extension Cases to Case Search
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/case_search/models.py
  corehq/apps/case_search/tests/test_case_search_registry.py
  corehq/apps/case_search/tests/test_get_related_cases.py
  corehq/apps/case_search/tests/test_models.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/case_search.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
Labels: QA Passed, product/feature-flag

#32746 Data Dictionary add index field for case properties
  corehq/apps/data_dictionary/migrations/0010_caseproperty_index.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
  migrations.lock
Labels: reindex/migration

#32738 Add placeholder and pattern to daterange picker widget
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
Labels: product/feature-flag, Risk: Medium

#32769 Attempt to fix intermittent test failure
  corehq/tests/test_nose_timing.py
Labels: product/invisible

#32655 Catch ResourceNotFound
  corehq/apps/reports/formdetails/readable.py
Labels: product/invisible

#32775 Create form- and case ids download privilege
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0070_form_case_ids_case_importer_priv.py
  corehq/apps/case_importer/templates/case_importer/partials/ko_import_history.html
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32765 Fix Form Print Layout
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#32776 Add comments for clarity. Change "Client Grant" label to "Client Credentials Grant"
  corehq/motech/const.py
  corehq/motech/migrations/0012_alter_connectionsettings_auth_type.py
  migrations.lock
Labels: reindex/migration, product/invisible

#32788 Add domain filter to query
  corehq/motech/generic_inbound/views.py
Labels: product/invisible

#32771 [Accessibility] Tabular radio button - NVDA reader
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: Risk: Medium

#32759 [CLE GA A2.1] Moving to opening Case Search Index for all domains
  corehq/apps/case_search/migrations/0011_domainsnotincasesearchindex.py
  corehq/apps/case_search/models.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/es/tests/test_case_search_es.py
  corehq/apps/hqadmin/management/commands/stale_data_in_es.py
  corehq/apps/hqadmin/tests/test_stale_data_in_es.py
  corehq/apps/ota/tests/test_search_claim_endpoints.py
  corehq/apps/reports/management/commands/enable_case_search_for_ecd.py
  corehq/pillows/case_search.py
  corehq/toggles/__init__.py
  migrations.lock
  testapps/test_pillowtop/tests/test_case_pillow.py
  testapps/test_pillowtop/tests/test_case_search_pillow.py
  testapps/test_pillowtop/tests/test_reindexer.py
Labels: reindex/migration, product/invisible

#32634 fix on change behavior for media entries
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
Labels: QA Passed, Risk: Medium

#32680 Confirm whether current_meta.is_deletion is true or false in logs
  corehq/ex-submodules/pillowtop/processors/elastic.py
Labels: product/invisible

#32770 api key expiration
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/test_auth.py
  corehq/apps/domain/static/domain/js/internal_subscription_management.js
  corehq/apps/hqwebapp/static/hqwebapp/js/widgets.js
  corehq/apps/settings/forms.py
  corehq/apps/settings/static/settings/js/user_api_keys.js
  corehq/apps/settings/tasks.py
  corehq/apps/settings/templates/settings/email/about_to_expire_api_key.html
  corehq/apps/settings/templates/settings/email/about_to_expire_api_key.txt
  corehq/apps/settings/templates/settings/user_api_keys.html
  corehq/apps/settings/views.py
  corehq/apps/users/models.py
Labels: Risk: High

#32747 Add task to calculate active Web Users in a billing account
  corehq/apps/accounting/migrations/0071_add_billingaccountwebuserhistory.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/tests/generator.py
  corehq/apps/accounting/tests/test_domain_user_history.py
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  migrations.lock
Labels: reindex/migration

#32792 Update attendance tracking event status
  corehq/apps/events/models.py
  corehq/apps/events/tests/test_events.py
  corehq/apps/events/views.py
Labels: product/feature-flag

#32794 Removed APP_ANALYTICS flag
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_test.js
  corehq/toggles/__init__.py
Labels: product/feature-flag, product/invisible, Risk: Medium

#32748 Enable Mobile Worker Attendees
  corehq/apps/accounting/subscription_changes.py
  corehq/apps/accounting/tests/test_subscription_changes.py
  corehq/apps/events/forms.py
  corehq/apps/events/models.py
  corehq/apps/events/static/events/js/event_attendees.js
  corehq/apps/events/tasks.py
  corehq/apps/events/templates/event_attendees.html
  corehq/apps/events/tests/test_events.py
  corehq/apps/events/tests/test_models.py
  corehq/apps/events/tests/test_tasks.py
  corehq/apps/events/tests/test_views.py
  corehq/apps/events/urls.py
  corehq/apps/events/views.py
  corehq/apps/users/tests/test_views.py
  corehq/apps/users/views/mobile/users.py
  corehq/tabs/tabclasses.py
  corehq/util/test_utils.py
Labels: product/feature-flag
