Repository dimagi/commcare-hq, pull requests merged in 2023-06, with the labels that each got.

#33020 Geospatial map with case list filters
  corehq/apps/geospatial/dispatchers.py
  corehq/apps/geospatial/models.py
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/templates/geospatial/map_visualization_base.html
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/tests/test_models.py
  corehq/apps/geospatial/urls.py
  corehq/apps/geospatial/views.py
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/reports.py
  corehq/tabs/tabclasses.py
  package.json
  yarn.lock
Labels: dependencies

#33052 [USH-3134] form link child module manual linking fix
  corehq/apps/app_manager/suite_xml/post_process/workflow.py
  corehq/apps/app_manager/tests/test_form_workflow.py
Labels: product/all-users-all-environments

#33050 Diagnose DHIS2 errors
  corehq/motech/dhis2/const.py
  corehq/motech/dhis2/parse_response.py
  corehq/motech/repeaters/templates/repeaters/partials/attempt_history.html
  corehq/motech/repeaters/views/repeat_records.py
Labels: product/all-users-all-environments

#33029 Split screen case search UI: field type accommodation
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer/query_view.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp-main.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/query.less
Labels: awaiting QA, product/feature-flag, Risk: Medium

#32972 Split screen case search "search again" workflow
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/app_factory.py
  corehq/apps/app_manager/tests/test_suite_split_screen_case_search.py
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: awaiting QA, product/feature-flag, Risk: Medium

#33056 Fix Exports Timezone Issue
  corehq/apps/domain/models.py
  corehq/apps/domain/tests/test_models.py
  corehq/apps/hqwebapp/static/hqwebapp/js/daterangepicker.config.js
  corehq/apps/reports/tests/test_util.py
  corehq/apps/reports/util.py
  corehq/ex-submodules/dimagi/utils/dates.py
Labels: product/invisible

#33071 Replace removed constant
  corehq/apps/app_manager/tests/test_suite_case_tiles.py
Labels: product/invisible

#33063 Display notification when data source rebuild failed
  corehq/apps/userreports/models.py
  corehq/apps/userreports/templates/userreports/edit_data_source.html
  corehq/apps/userreports/templates/userreports/partials/build_in_progress_warning.html
Labels: product/invisible

#32922 "Login/Logout" tracking API - Querying
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/audit_resources.py
  corehq/apps/api/urls.py
  corehq/toggles/__init__.py
Labels: QA Passed, product/feature-flag, Risk: High

#33065 Add new template for case list tiles
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.xml
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/tests/test_suite_case_tiles.py
Labels: product/feature-flag

#33076 Added markdown table class to case list, detail, tiles
  corehq/apps/cloudcare/templates/formplayer/case_detail.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: product/prod-india-all-users, Risk: Medium

#33078 Application error report GA
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0075_application_error_report_priv.py
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_table.html
  corehq/apps/app_manager/views/releases.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/reports/standard/deployments.py
  corehq/privileges.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration

#33094 Record web apps user ip
  corehq/apps/api/resources/v0_4.py
  corehq/ex-submodules/couchforms/getters.py
Labels: Risk: High

#33099 increase limit to 4MB
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
Labels: product/feature-flag, Risk: Medium

#33084 Removes Null users from Login/Logout API Response
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/audit_resources.py
Labels: product/feature-flag, Risk: High

#33108 Move repeaters SQL data to a separate database
  corehq/motech/repeaters/migrations/0001_adjust_auth_field_format_squashed_0015_drop_connection_settings_fk.py
  corehq/motech/repeaters/migrations/0002_repeaters_db.py
  migrations.lock
Labels: reindex/migration, product/invisible

#32878 Data Dictionary: UI for editable / sortable Groups
  corehq/apps/data_dictionary/migrations/0013_auto_20230529_1614.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/tests/test_view.py
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
  corehq/apps/hqwebapp/static/data_dictionary/less/data_dictionary.less
  migrations.lock
  package.json
  yarn.lock
Labels: reindex/migration, QA Passed, product/feature-flag, dependencies, QA post deploy

#33115 Small refactor
  corehq/apps/hqcase/tests/test_loadtest_users.py
  corehq/apps/users/forms.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/casexml/apps/phone/restore_caching.py
  testapps/test_pillowtop/tests/test_chunk_pillow.py
Labels: product/invisible

#33123 Simplify password func
  corehq/apps/users/forms.py
  corehq/apps/users/tests/test_forms.py
Labels: product/invisible

#33124 Add comments to added dependencies
  requirements/base-requirements.in
Labels: product/invisible, dependencies

#33101 CLE error modal clean up
  corehq/apps/reports/static/reports/js/reports.async.js
  corehq/apps/reports/views.py
Labels: QA Passed, product/feature-flag

#33130 Refactor
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_extension_indexes.py
  corehq/form_processor/models/cases.py
Labels: product/invisible, Risk: High

#33128 Create case tile templates
  corehq/apps/app_manager/suite_xml/case_tile_templates/README.md
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one_one.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one_one.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/person_simple.xml
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
Labels: product/feature-flag

#33111 Add more detail to conflicting instances error
  corehq/apps/app_manager/suite_xml/post_process/instances.py
Labels: product/invisible

#33051 Update sphinx, sphinxcontrib-django(multi-major), sphinx-rtd-theme
  corehq/__init__.py
  docs/conf.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.in
  requirements/docs-requirements.txt
Labels: dependencies

#33126 Move functions from ghdiff package to corehq.utils
  corehq/apps/app_manager/views/releases.py
  corehq/apps/translations/app_translations/upload_app.py
  corehq/apps/translations/validator.py
  corehq/util/ghdiff.py
  corehq/util/tests/test_ghdiff.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33069 support formplayer help media
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/fixtures.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#33110 Show banner with link to invalid geo-cases
  corehq/apps/geospatial/const.py
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
Labels: product/feature-flag

#33133 Split Screen Case Search UI updates
  corehq/__init__.py
  corehq/apps/app_manager/suite_xml/case_tile_templates/README.md
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one_one.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one_one.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/person_simple.xml
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/views/releases.py
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/fixtures.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/geospatial/const.py
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/reports/static/reports/js/reports.async.js
  corehq/apps/reports/views.py
  corehq/apps/translations/app_translations/upload_app.py
  corehq/apps/translations/validator.py
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_extension_indexes.py
  corehq/form_processor/models/cases.py
  corehq/util/ghdiff.py
  corehq/util/tests/test_ghdiff.py
  docs/conf.py
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/fra/LC_MESSAGES/django.po
  locale/hi/LC_MESSAGES/django.po
  locale/hin/LC_MESSAGES/django.po
  locale/por/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/sw/LC_MESSAGES/django.po
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.in
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/feature-flag, dependencies, Risk: High, Risk: Medium

#33137 Split Screen Case Search UI updates
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/cloudcare/templates/formplayer/pagination.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
Labels: product/feature-flag, Risk: Medium

#33140 Use smaller fields and tighter spacing in split screen case search
  corehq/apps/cloudcare/templates/formplayer/query_view.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/query.less
Labels: product/feature-flag, Risk: Medium

#33142 Revert "Align behavior of "childextension" cases"
  corehq/ex-submodules/casexml/apps/phone/data_providers/case/livequery.py
  corehq/ex-submodules/casexml/apps/phone/models.py
  corehq/ex-submodules/casexml/apps/phone/tests/data/case_relationship_tests.json
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py
  corehq/sql_accessors/migrations/0067_livequery_sql_include_child_indices.py
  corehq/sql_accessors/migrations/0067_livequery_sql_include_deleted_indices.py
  corehq/sql_accessors/sql_templates/get_related_indices.sql
  migrations.lock
Labels: reindex/migration

#33024 [CLE GA] UI Improvements to CLE ACE editor (and editor upgrade)
  corehq/apps/hqwebapp/static/hqwebapp/js/base_ace.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/ace_cle.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style-imports.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_ace_cle.scss
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diff_config.json
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/ace_cle._ace_cle.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/style-imports.commcarehq.style.diff.txt
  corehq/apps/reports/static/reports/js/filters/case_list_explorer_knockout_bindings.js
  package.json
  yarn.lock
Labels: QA Passed, product/all-users-all-environments, dependencies, Risk: Medium, dependencies/javascript

#33120 [CLE] add management command to assist maintainers of HQ instances with preparing for CLE GA
  corehq/apps/reports/management/commands/prepare_projects_for_case_list_explorer.py
Labels: product/invisible

#33147 [USH-3277] allow the geocoder widget to use the user's location
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
  corehq/toggles/__init__.py
Labels: Risk: Medium

#33088 USH-2887 Bulk case eport for domain
  corehq/apps/app_manager/fields.py
  corehq/apps/export/forms.py
  corehq/apps/export/static/export/js/create_export.js
Labels: QA Passed, product/all-users-all-environments

#33122 Use eval_lazy before getting object type on lazy objects
  corehq/apps/userreports/expressions/evaluator/main.py
Labels: product/invisible

#33129 Add ability to save Drawn polygons in Mapbox
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/geospatial/const.py
  corehq/apps/geospatial/migrations/0001_create_geopolygon.py
  corehq/apps/geospatial/models.py
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/templates/geospatial/map_visualization_base.html
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/urls.py
  corehq/apps/geospatial/views.py
  corehq/apps/settings/urls.py
  migrations.lock
  urls.py
Labels: reindex/migration, product/invisible

#33148 Dont fail for missing user
  corehq/apps/linked_domain/views.py
Labels: product/invisible

#33166 Small fix
  corehq/apps/data_dictionary/views.py
Labels: product/invisible

#33161 Update Mac Dev Setup doc
  DEV_SETUP.md
  DEV_SETUP_MAC.md
Labels: product/invisible

#33164 Change the position of the case list map to sticky
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/menu.less
Labels: Risk: Medium

#33170 Removed case tiles ID mapping validation
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
Labels: product/feature-flag

#33149 Add address_popup format
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/static/app_manager/js/details/utils.js
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one_one.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one_one.xml
  corehq/apps/app_manager/tests/data/suite/normal-suite.xml
  corehq/apps/app_manager/tests/test_suite_formats.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#33096 Removed icon validation in case tiles
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
Labels: QA Passed, product/feature-flag

#33061 Split screen case search: javascript testing
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/fixtures/split_screen_case_list.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/split_screen_case_search_spec.js
  corehq/apps/cloudcare/templates/cloudcare/spec/mocha.html
Labels: product/invisible, Risk: Medium

#33106 [USH-3286] case tile group initial
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
  corehq/apps/app_manager/tests/test_suite_case_tiles.py
  corehq/apps/app_manager/tests/test_suite_case_tiles_grouping.py
  corehq/apps/app_manager/views/modules.py
Labels: Core Compatibility

#33160 Make case tiles work with split screen case search
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/details.py
Labels: QA Passed, product/feature-flag

#33175 Update CONTRIBUTING.rst
  CONTRIBUTING.rst
Labels: product/invisible

#33157 Case Tile Grouping UI
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/menu.less
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/ace_cle._ace_cle.style.diff.txt
Labels: QA Passed, product/feature-flag, Risk: Medium

#33171 Riese/map ff
  corehq/apps/app_manager/static/app_manager/js/details/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/toggles/__init__.py
Labels: Risk: Medium

#33125 Case Tiles Sorting
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.xml
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/tests/test_suite_case_tiles.py
Labels: QA Passed, product/feature-flag

#33176 Change the max initial zoom level for case list map
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#33179 Switch back to original release of flower
  requirements/prod-requirements.in
  requirements/prod-requirements.txt
Labels: dependencies

#33162 Make downloadable links to server files
  corehq/apps/hqadmin/management/commands/get_download_url.py
  corehq/apps/hqadmin/urls.py
  corehq/apps/hqadmin/utils.py
  corehq/apps/hqadmin/views/data.py
Labels: product/invisible

#33180 Split Screen Case Search: field validation fix
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/feature-flag, Risk: Medium

#33077 Jt/login logout api params separation
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/audit_resources.py
Labels: product/feature-flag, Risk: High

#33182 Applied line break fix to mapping popup
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: product/feature-flag, Risk: Medium

#33185 A few tweaks to Attendance Tracking
  corehq/apps/events/forms.py
  corehq/apps/events/static/events/js/new_event.js
Labels: product/invisible
