Repository dimagi/commcare-hq, pull requests merged in 2023-11, with the labels that each got.

#33673 Create Case on GPS Capture Page
  corehq/apps/geospatial/static/geospatial/js/gps_capture.js
  corehq/apps/geospatial/templates/gps_capture.html
  corehq/apps/geospatial/templates/gps_capture_view.html
  corehq/apps/geospatial/tests/test_utils.py
  corehq/apps/geospatial/utils.py
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#33656 Cs/sc 3057 lock case grouping
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/templates/case_grouping_map.html
Labels: product/feature-flag

#33662 Replace ortools with pulp
  corehq/apps/geospatial/routing_solvers/pulp.py
  corehq/apps/geospatial/tests/test_pulp.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/feature-flag, product/invisible, dependencies

#33592 Allow domain to add their own banners
  corehq/apps/domain/auth.py
  corehq/apps/domain/decorators.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/static/domain/js/manage_alerts.js
  corehq/apps/domain/templates/domain/admin/manage_alerts.html
  corehq/apps/domain/tests/test_auth.py
  corehq/apps/domain/tests/test_views.py
  corehq/apps/domain/urls.py
  corehq/apps/domain/views/settings.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  corehq/apps/hqwebapp/migrations/0011_add_new_columns_and_rename_model.py
  corehq/apps/hqwebapp/models.py
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/main.js
  corehq/apps/hqwebapp/templates/hqwebapp/maintenance_alerts.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap3/maintenance_alerts.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/maintenance_alerts.html
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/partials/maintenance_alerts.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/main.js.diff.txt
  corehq/apps/hqwebapp/tests/test_models.py
  corehq/apps/hqwebapp/tests/test_views.py
  corehq/apps/hqwebapp/views.py
  corehq/tabs/tabclasses.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/all-users-all-environments

#33593 Turn user.metadata into accessor class - user.get_user_data(domain)
  corehq/apps/api/resources/v0_1.py
  corehq/apps/api/tests/test_user_updates.py
  corehq/apps/api/tests/user_resources.py
  corehq/apps/api/user_updates.py
  corehq/apps/app_manager/models.py
  corehq/apps/callcenter/sync_usercase.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/cloudcare/tests/test_session.py
  corehq/apps/cloudcare/views.py
  corehq/apps/commtrack/tests/util.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/custom_data_fields/tests/test_profiles.py
  corehq/apps/es/tests/test_user_es.py
  corehq/apps/es/users.py
  corehq/apps/geospatial/tests/test_utils.py
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/utils.py
  corehq/apps/geospatial/views.py
  corehq/apps/ota/tests/test_utils.py
  corehq/apps/ota/utils.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/sms/api.py
  corehq/apps/smsforms/tests/test_app.py
  corehq/apps/user_importer/helpers.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/userreports/tests/test_choice_provider.py
  corehq/apps/users/analytics.py
  corehq/apps/users/bulk_download.py
  corehq/apps/users/custom_data.py
  corehq/apps/users/forms.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/custom_data_fields.js
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/tasks.py
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/tests/test_download.py
  corehq/apps/users/tests/test_download_with_profile.py
  corehq/apps/users/tests/test_location_assignment.py
  corehq/apps/users/tests/test_log_user_change.py
  corehq/apps/users/tests/test_remove_unused_custom_fields.py
  corehq/apps/users/tests/test_user_data.py
  corehq/apps/users/tests/test_user_model.py
  corehq/apps/users/user_data.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
  corehq/ex-submodules/casexml/apps/phone/tests/dummy.py
  corehq/ex-submodules/casexml/apps/phone/tests/utils.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/messaging/scheduling/tests/test_recipients.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: product/invisible, Risk: High, Risk: Medium

#33693 Added a temporary workaround to minio images lacking curl
  docker/hq-compose.yml
Labels: product/invisible

#33687 Disable dynamic search when smallScreenEnabled
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/feature-flag, Risk: Medium

#33699 Fixed attribute name in case tile config UI
  corehq/apps/app_manager/static/app_manager/js/details/column.js
Labels: product/feature-flag

#33447 During sign up only allow email address the invite was send to
  corehq/apps/domain/forms.py
  corehq/apps/domain/models.py
  corehq/apps/domain/tests/test_forms.py
  corehq/apps/domain/views/settings.py
  corehq/apps/registration/forms.py
  corehq/apps/users/tests/test_user_invitation.py
  corehq/apps/users/views/web.py
Labels: Risk: High

#33708 Update Geospatial Menu
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/views.py
  corehq/reports.py
  corehq/tabs/config.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#33704 Polygon Filtering Support for Case Grouping Page
  corehq/apps/es/filters.py
  corehq/apps/es/tests/test_filters.py
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/templates/case_grouping_map.html
  corehq/apps/geospatial/templates/geospatial/case_grouping_map_base.html
  corehq/apps/geospatial/tests/test_utils.py
  corehq/apps/geospatial/utils.py
Labels: product/feature-flag

#33682 [Bootstrap 5] Updates to crispy forms widgets and hqcrispy fields
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_forms.scss
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/bootstrap3/checkbox_widget.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/bootstrap3/form_actions.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/bootstrap5/checkbox_widget.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/bootstrap5/form_actions.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/checkbox_widget.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/form_actions.html
  corehq/apps/hqwebapp/templates/hqwebapp/crispy/switch_widget.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/crispy/checkbox_widget.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/crispy/form_actions.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/forms._forms.style.diff.txt
  corehq/apps/hqwebapp/widgets.py
Labels: product/invisible

#33713 Updated Web Apps progress bar text
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
Labels: product/all-users-all-environments, Risk: Medium

#33711 Fixed minio healthcheck warnings
  docker/hq-compose.yml
Labels: product/invisible

#33697 Cs/sc 2876 implement disbursement
  corehq/apps/geospatial/models.py
  corehq/apps/geospatial/routing_solvers/base.py
  corehq/apps/geospatial/routing_solvers/mapbox_optimize.py
  corehq/apps/geospatial/routing_solvers/pulp.py
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/templates/geospatial/map_visualization_base.html
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/tests/test_pulp.py
  corehq/apps/geospatial/urls.py
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#33717 Update Geospatial Map Button + Saved Polygon Fix
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/templates/map_visualization.html
Labels: product/feature-flag

#33712 [B5] Updates to modal knockout bindings
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/knockout_bindings.ko.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/requirejs.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/knockout_bindings.ko.js.diff.txt
Labels: product/invisible, Risk: Medium

#33714 [B5] change button style from btn-outline-secondary to btn-outline-primary in 500 template
  corehq/apps/hqwebapp/templates/500.html
Labels: product/invisible

#33710 Fit Map Bounds to Case Data
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
Labels: product/feature-flag

#33719 fix attribute error with BootstrapCheckboxInput widget
  corehq/apps/hqwebapp/widgets.py
Labels: product/invisible

#33720 Tiny web apps UI tweaks
  corehq/apps/cloudcare/static/cloudcare/less/markdown-table.less
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: Risk: Medium

#33705 do away with iframe for clickable icons
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#33721 Replaced domain name with human-readable name in invitation email
  corehq/apps/domain/templates/domain/email/domain_invite.txt
  corehq/apps/users/models.py
Labels: product/all-users-all-environments

#33694 Prefactor; cleanup unused ES methods, add tests
  corehq/apps/es/users.py
  corehq/apps/hqadmin/reports.py
  corehq/apps/locations/dbaccessors.py
  corehq/apps/locations/tests/test_dbaccessors.py
  corehq/apps/users/dbaccessors.py
  corehq/apps/users/tests/test_dbaccessors.py
Labels: product/invisible

#33715 Custom Case Tile Layout Index Bug Fix
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
Labels: product/feature-flag

#33727 delay call to get_details
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#33728 clean up web user success message
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
Labels: Risk: Medium

#33641 Cache flattened case properties for better performance
  corehq/apps/app_manager/app_schemas/case_properties.py
  corehq/apps/app_manager/models.py
Labels: product/all-users-all-environments, product/invisible

#33716 Custom Gateway Form Validation for "Host"
  corehq/apps/email/forms.py
  corehq/apps/email/tests/test_email_form.py
Labels: product/feature-flag

#33733 Revert "delay call to get_details"
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#33736 Use correct setting
  corehq/apps/geospatial/routing_solvers/pulp.py
Labels: product/feature-flag

#33734 Remove success message banner for clickable icons
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
Labels: Risk: Medium

#33723 Fully qualify docker images
  docker/files/Dockerfile.couch
  docker/files/Dockerfile.es.2
  docker/files/Dockerfile.es.5
  docker/hq-compose-os-default.yml
  docker/hq-compose-os-macos-m1-11.yml
  docker/hq-compose-os-macos-m1-12.yml
  docker/hq-compose.yml
Labels: product/invisible

#33731 Geospatial Code Refactor
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/static/geospatial/js/utils.js
  corehq/apps/geospatial/templates/base_template.html
  corehq/apps/geospatial/templates/map_visualization.html
Labels: product/feature-flag, product/invisible

#33735 Cs/sc 3059 group cases manually
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/templates/case_grouping_map.html
  corehq/apps/locations/tests/test_dbaccessors.py
  corehq/apps/users/dbaccessors.py
Labels: product/feature-flag

#33749 Question Tile 1 per row adjustment
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
Labels: product/all-users-all-environments, Risk: Medium

#33692 Use Domain Custom Gateway for System Emails
  corehq/apps/accounting/models.py
  corehq/apps/app_manager/views/utils.py
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/domain/models.py
  corehq/apps/email/forms.py
  corehq/apps/email/migrations/0002_emailsettings_return_path_email.py
  corehq/apps/email/models.py
  corehq/apps/enterprise/tasks.py
  corehq/apps/enterprise/tests/test_enterprise_tasks.py
  corehq/apps/fixtures/tasks.py
  corehq/apps/hqwebapp/tasks.py
  corehq/apps/linked_domain/util.py
  corehq/apps/registry/notifications.py
  corehq/apps/reports/tasks.py
  corehq/apps/reports/util.py
  corehq/apps/saved_reports/models.py
  corehq/apps/saved_reports/tasks.py
  corehq/apps/saved_reports/tests/test_models.py
  corehq/apps/settings/tasks.py
  corehq/apps/sms/api.py
  corehq/apps/translations/app_translations/upload_app.py
  corehq/apps/translations/tasks.py
  corehq/apps/userreports/tasks.py
  corehq/apps/users/account_confirmation.py
  corehq/apps/users/models.py
  corehq/apps/users/views/mobile/users.py
  corehq/ex-submodules/dimagi/utils/django/email.py
  corehq/ex-submodules/soil/util.py
  corehq/motech/openmrs/tests/test_tasks.py
  corehq/motech/requests.py
  corehq/motech/tests/test_requests.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, Risk: Medium

#33750 Removed unsupported kafka depends condition
  docker/hq-compose.yml
Labels: product/invisible

#33622 Dynamic search suite changes
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/json/commcare-app-settings.yml
  corehq/apps/app_manager/static/app_manager/json/commcare-settings-layout.yml
  corehq/apps/app_manager/static_strings.py
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/data/suite/multi_select_case_list/basic_remote_request.xml
  corehq/apps/app_manager/tests/data/suite/remote_request.xml
  corehq/apps/app_manager/tests/data/suite/remote_request_custom_detail.xml
  corehq/apps/app_manager/tests/data/suite/search_config_blacklisted_owners.xml
  corehq/apps/app_manager/tests/data/suite/search_config_default_only.xml
  corehq/apps/app_manager/tests/data/suite/smart_link_remote_request.xml
  corehq/apps/app_manager/tests/data/suite_inline_search/shadow_module_entry.xml
  corehq/apps/app_manager/tests/data/suite_registry/form_link_followup_module_registry.xml
  corehq/apps/app_manager/tests/data/suite_registry/shadow_module_entry.xml
  corehq/apps/app_manager/tests/data/suite_registry/shadow_module_remote_request.xml
  corehq/apps/app_manager/tests/test_advanced_suite.py
  corehq/apps/app_manager/tests/test_suite_inline_search.py
  corehq/apps/app_manager/tests/test_suite_registry_search.py
  corehq/apps/app_manager/tests/test_suite_split_screen_case_search.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/modules.py
Labels: product/feature-flag, Core Compatibility

#33623 Dynamic search retrieve hasDynamicSearch from formplayer and configure
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/feature-flag, Risk: Medium

#33576 [ush-3507,USH-3508] Remove CaseProperty.group and rename CaseProperty.group_obj to CaseProperty.group
  corehq/apps/data_dictionary/management/commands/populate_case_prop_groups.py
  corehq/apps/data_dictionary/migrations/0016_remove_case_property_group_and_rename_group_obj_caseproperty_group.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/tests/test_view.py
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
  corehq/apps/linked_domain/local_accessors.py
  corehq/apps/linked_domain/tests/test_update_data_dictionary.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/reports/standard/cases/case_data.py
  corehq/apps/reports/tests/test_case_data.py
  corehq/apps/userreports/tests/test_report_builder.py
  migrations.lock
Labels: reindex/migration

#33748 Remove ops email for hubspot error and send it to sentry
  corehq/apps/analytics/tasks.py
Labels: product/invisible

#33706 Add Stripe test to interact with stripe
  .github/workflows/tests.yml
  corehq/apps/accounting/models.py
  corehq/apps/accounting/payment_handlers.py
  corehq/apps/accounting/tests/test_autopay_with_api.py
  corehq/apps/accounting/tests/test_stripe_payment_method_with_api.py
  corehq/apps/accounting/tests/test_stripe_utils_with_api.py
  corehq/apps/accounting/utils/__init__.py
  corehq/apps/accounting/utils/stripe.py
  corehq/apps/domain/views/accounting.py
  corehq/apps/enterprise/views.py
  docker/hq-compose.yml
  scripts/docker
  testsettings.py
Labels: product/invisible

#33761 Update Vellum (sanitize comments)
  corehq/apps/app_manager/static/app_manager/js/vellum/manifest.txt
  corehq/apps/app_manager/static/app_manager/js/vellum/src/main-components.js
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: product/all-users-all-environments

#33752 [B5] Updates to validators.ko.js for bootstrap 5
  corehq/apps/analytics/static/analytix/js/cta_forms.js
  corehq/apps/export/static/export/js/export_list.js
  corehq/apps/export/static/export/js/models.js
  corehq/apps/hqwebapp/crispy.py
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/validators.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/validators.ko.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/validators.ko.js.diff.txt
  corehq/apps/users/static/users/js/invite_web_user.js
  corehq/apps/users/static/users/js/mobile_workers.js
Labels: product/invisible, Risk: Medium

#33765 [Branding] Temporarily rollback color, style and logo changes requested by marketing
  corehq/apps/domain/templates/login_and_password/login.html
  corehq/apps/hqwebapp/_fonts/commcarehq_font/CommCareHQFont.glyphs
  corehq/apps/hqwebapp/static/app_manager/less/font-workflow/core.less
  corehq/apps/hqwebapp/static/app_manager/less/img/loading_flower.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-flower-lg.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-flower.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-120x120.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-152x152.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-167x167.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-180x180.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-57x57.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-icon-76x76.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-logo-mobile.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcare-logo-small.png
  corehq/apps/hqwebapp/static/hqstyle/images/commcarehq-icon-large.png
  corehq/apps/hqwebapp/static/hqwebapp/font/CommCareHQFont-Regular.otf
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehqfont-regular.eot
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehqfont-regular.svg
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehqfont-regular.ttf
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehqfont-regular.woff
  corehq/apps/hqwebapp/static/hqwebapp/images/commcare-flower-footer.png
  corehq/apps/hqwebapp/static/hqwebapp/images/commcare-flower.png
  corehq/apps/hqwebapp/static/hqwebapp/images/dimagi-footer.png
  corehq/apps/hqwebapp/static/hqwebapp/images/favicon.png
  corehq/apps/hqwebapp/static/hqwebapp/images/favicon2.png
  corehq/apps/hqwebapp/static/hqwebapp/images/molly.jpg
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/backgrounds.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/includes/variables.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/navbar.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_navbar.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables_bootstrap3.scss
  corehq/apps/hqwebapp/static/registration/less/registration-main.less
  corehq/apps/hqwebapp/templates/hqwebapp/iframe_domain_login.html
  corehq/apps/hqwebapp/templates/hqwebapp/svg/dimagi_logo.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/backgrounds._backgrounds.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables_bootstrap3.style.diff.txt
  corehq/apps/registration/static/registration/images/commcare.png
  corehq/apps/registration/static/registration/images/commcare_by_dimagi.png
  corehq/apps/registration/static/registration/images/dimagi.png
  corehq/apps/registration/static/registration/images/hero-bg.jpg
  corehq/apps/registration/static/registration/images/hero-bg.png
  corehq/apps/registration/static/registration/js/login.js
  corehq/apps/registration/templates/registration/email/_base.html
  corehq/apps/registration/templates/registration/email/password_reset_email_hq.html
  corehq/apps/registration/templates/registration/partials/choose_your_plan.html
  corehq/apps/registration/templates/registration/partials/feature_list.html
  package.json
  yarn.lock
Labels: product/all-users-all-environments, dependencies

#33766 make 500 more user friendly
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
Labels: Risk: Medium

#33763 Removed formplayer status icon from Web Apps questions
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: product/all-users-all-environments, Risk: Medium

#33747 Increase information density in web apps
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/includes/variables.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/select2s.less
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables_bootstrap3.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/select2s._select2.style.diff.txt
Labels: product/all-users-all-environments, Risk: Medium

#33771 Updated label question styling in web apps
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: Open for review: do not merge, product/all-users-all-environments, Risk: Medium

#33770 Form Nested Group and Repeat Header - style improvement
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/form_ui_spec.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: product/all-users-all-environments, Risk: Medium

#33782 Fix Empty Case ID Column for CSV Export
  corehq/apps/geospatial/static/geospatial/js/models.js
Labels: product/feature-flag

#33764 Add show/hide button for case list map
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/menu.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/query.less
Labels: Risk: Medium

#33784 Remove unused datatables extension libraries and dt style library
  package.json
  yarn.lock
Labels: dependencies, dependencies/javascript

#33785 Removal of unused javascript dependencies
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/requirejs_config.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/requirejs_config.js.diff.txt
  package.json
  yarn.lock
Labels: dependencies, Risk: High, dependencies/javascript

#33777 Reduced vertical padding for web apps page header
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
Labels: product/all-users-all-environments

#33791 Select Owner on Case Create
  corehq/apps/geospatial/static/geospatial/js/gps_capture.js
  corehq/apps/geospatial/templates/gps_capture.html
  corehq/apps/geospatial/templates/gps_capture_view.html
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#33796 Scroll to Top After Case Create
  corehq/apps/geospatial/static/geospatial/js/gps_capture.js
Labels: product/feature-flag

#33794 Updates button text
  corehq/apps/geospatial/templates/gps_capture.html
Labels: product/feature-flag

#33778 Added markdown support to collapsible header sections in Web Apps
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#33688 Move User Data to SQL
  corehq/apps/api/tests/user_resources.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/cloudcare/tests/test_esaccessors.py
  corehq/apps/cloudcare/tests/test_session.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/es/users.py
  corehq/apps/smsforms/tests/test_app.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/userreports/tests/test_choice_provider.py
  corehq/apps/users/README.rst
  corehq/apps/users/management/commands/populate_sql_user_data.py
  corehq/apps/users/migrations/0055_add_user_data.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_signals.py
  corehq/apps/users/tests/test_tasks.py
  corehq/apps/users/tests/test_user_data.py
  corehq/apps/users/tests/util.py
  corehq/apps/users/user_data.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_restore_user.py
  migrations.lock
  testapps/test_pillowtop/tests/test_grouptouser_pillow.py
Labels: reindex/migration, QA Passed, product/invisible, Risk: High, Risk: Medium

#33756 Updated messaging for invitations that have been used
  corehq/apps/users/views/web.py
Labels: product/all-users-all-environments

#33792 Change KO Pagination Component Button Text
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap3/ko_pagination.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/ko_pagination.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/partials/ko_pagination.html.diff.txt
Labels: product/all-users-all-environments

#33804 Update prompt in build_requirejs.py
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
Labels: product/invisible

#33800 Apply Polygon Filtering Before Disbursement
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/templates/map_visualization.html
Labels: product/feature-flag

#33678 [USH-3692] Add datadog metrics for dynamic search
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/urls.py
  corehq/apps/cloudcare/views.py
  corehq/apps/ota/views.py
Labels: Risk: Medium

#33783 Add option for tile fields to have a border
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_3X_two_4X_one_2X.xml
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/module_view.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/style_configuration_modal.html
  corehq/apps/app_manager/tests/test_report_config.py
  corehq/apps/app_manager/tests/test_suite_case_tiles.py
  corehq/apps/app_manager/tests/test_suite_custom_case_tiles.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: Risk: Medium, Core Compatibility

#33768 Single-Select Button Entry in Web Apps
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/css/webforms.css
Labels: product/all-users-all-environments, Risk: Medium

#33790 Customize text of “Clear” button for file uploads in Web Apps
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#33684 Prevent web apps/app preview usage if a domain has too many mobile UCRs
  corehq/apps/cloudcare/templates/block_web_apps.html
  corehq/apps/cloudcare/templates/preview_app/block_app_preview.html
  corehq/apps/cloudcare/tests/test_utils.py
  corehq/apps/cloudcare/urls.py
  corehq/apps/cloudcare/utils.py
  corehq/apps/cloudcare/views.py
  corehq/toggles/__init__.py
  settings.py
Labels: QA Passed, Risk: Medium

#33812 No btn class for clickable icons
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: Risk: Medium

#33802 Rc/clickable icons filter case list
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: product/feature-flag, Risk: Medium

#33799 Case search: geocoder widget value maintain value between searches
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
Labels: product/feature-flag, Risk: Medium

#33818 Fix datetime user data
  corehq/apps/api/tests/user_resources.py
  corehq/apps/users/tests/test_user_data.py
  corehq/apps/users/user_data.py
Labels: product/all-users-all-environments, Risk: High

#33813 [B5] Updates to variables.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
Labels: product/invisible

#33814 [B5] This adds bootstrap 5 support to the multiselect widget
  corehq/apps/hqwebapp/static/hqwebapp/js/multiselect_utils.js
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_forms.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/forms._forms.style.diff.txt
Labels: product/invisible

#33815 [B5] Bootstrap 5 support for datatables
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_datatables.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/requirejs_config.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/datatables._datatables.style.diff.txt
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#33816 [B5] fix small issue with bootstrap 5 version of sticky tabs
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/sticky_tabs.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/sticky_tabs.js.diff.txt
Labels: product/invisible
