Repository dimagi/commcare-hq, pull requests merged in 2023-04, with the labels that each got.

#32802 Remove the `end_date` constraint when creating events
  corehq/apps/events/forms.py
  corehq/apps/events/migrations/0006_remove_end_date_constraint.py
  corehq/apps/events/models.py
  corehq/apps/events/tests/test_models.py
  corehq/apps/events/views.py
  migrations.lock
Labels: reindex/migration

#32756 Display Attendee list sorted by Date and Name
  corehq/apps/events/models.py
  corehq/apps/events/templates/events_list.html
  corehq/apps/events/tests/test_models.py
  corehq/apps/events/views.py
Labels: product/feature-flag

#32804 Users can set Form Forwarders to only forward specific forms
  corehq/motech/repeaters/forms.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/views/repeaters.py
Labels: product/all-users-all-environments

#32806 Drop unused const
  corehq/motech/repeaters/tests/test_models.py
Labels: product/invisible

#32782 Return status 204 when there is no data to send to DHIS2
  corehq/motech/dhis2/entities_helpers.py
  corehq/motech/dhis2/events_helpers.py
  corehq/motech/dhis2/tests/test_entities_helpers.py
  corehq/motech/dhis2/tests/test_events_helpers.py
  corehq/motech/repeaters/const.py
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/migrations/0014_add_new_state_empty.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/templates/repeaters/partials/attempt_history.html
  corehq/motech/repeaters/views/repeat_record_display.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32805 Update AT event editing
  corehq/apps/events/forms.py
  corehq/apps/events/views.py
Labels: product/feature-flag

#32807 Remove Incremental Export
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  corehq/apps/export/filters.py
  corehq/apps/export/forms.py
  corehq/apps/export/migrations/0013_rm_incrementalexport.py
  corehq/apps/export/models/__init__.py
  corehq/apps/export/models/incremental.py
  corehq/apps/export/tasks.py
  corehq/apps/export/templates/export/incremental_export.html
  corehq/apps/export/tests/test_incremental.py
  corehq/apps/export/urls.py
  corehq/apps/export/views/incremental.py
  corehq/apps/reports/dispatcher.py
  corehq/apps/reports/filters/select.py
  corehq/apps/reports/tests/test_dispatcher.py
  corehq/motech/models.py
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/repeaters/tests/test_tasks.py
  corehq/motech/views.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32809 GA EXPORT_MULTISORT
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0072_export_multisort_priv.py
  corehq/apps/export/templates/export/partials/new_customize_export_templates.html
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, product/all-users-all-environments

#32813 Fix case type used by `Event.mark_attendance()`
  corehq/apps/events/models.py
  corehq/apps/events/tests/test_models.py
  corehq/form_processor/models/cases.py
  corehq/form_processor/tests/test_extension_cases.py
Labels: product/invisible, Risk: High

#32781 ABDM M1 API enhancements
  custom/abdm/milestone_one/utils/abha_creation_util.py
  custom/abdm/milestone_one/utils/abha_verification_util.py
  custom/abdm/milestone_one/utils/response_util.py
  custom/abdm/milestone_one/views/abha_creation_views.py
  custom/abdm/milestone_one/views/abha_verification_views.py
  custom/abdm/tests/test_abha_creation.py
  custom/abdm/tests/test_abha_verification.py
  custom/abdm/urls.py
Labels: product/feature-flag, product/custom

#32822 Return 204 response, not True, on empty payload
  corehq/motech/dhis2/repeaters.py
  corehq/motech/fhir/repeater_helpers.py
  corehq/motech/fhir/tests/test_repeater_helpers.py
Labels: product/invisible

#32763 Update mapbox-geocoder
  package.json
  yarn.lock
Labels: QA Passed, dependencies

#32767 Ze/add descendants to location alert
  corehq/apps/api/es.py
  corehq/apps/locations/tests/test_permissions.py
  corehq/apps/users/templates/users/partials/edit_commtrack_user_settings.html
  corehq/apps/users/tests/test_util.py
  corehq/apps/users/views/mobile/users.py
  corehq/apps/users/views/utils.py
Labels: Risk: High

#32825 Event.status
  corehq/apps/events/forms.py
  corehq/apps/events/migrations/0007_alter_event_attendee_list_status.py
  corehq/apps/events/models.py
  corehq/apps/events/tests/test_events.py
  corehq/apps/events/tests/test_forms.py
  corehq/apps/events/tests/test_models.py
  corehq/apps/events/views.py
  migrations.lock
Labels: reindex/migration, product/invisible

#32826 Replace CaseFactory with CaseHelper
  corehq/apps/events/migrations/0008_alter_event__case_id.py
  corehq/apps/events/models.py
  corehq/apps/events/tests/test_models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#32811 Include All Related Cases Bug Fix
  corehq/apps/case_search/tests/test_case_search_registry.py
  corehq/apps/case_search/tests/test_get_related_cases.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/case_search.py
Labels: QA Passed, product/feature-flag

#32831 Add temporary workaround for deprecation warnings
  corehq/warnings.py
Labels: product/invisible

#32834 detect instaces with whitespace around instance names
  corehq/apps/app_manager/suite_xml/post_process/instances.py
  corehq/apps/app_manager/tests/test_suite_instances.py
Labels: product/all-users-all-environments

#32787 Ze/bulk export all case types
  corehq/apps/app_manager/fields.py
  corehq/apps/export/const.py
  corehq/apps/export/exceptions.py
  corehq/apps/export/export.py
  corehq/apps/export/models/__init__.py
  corehq/apps/export/models/new.py
  corehq/apps/export/static/export/js/const.js
  corehq/apps/export/tasks.py
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/apps/export/tests/test_export_data_schema.py
  corehq/apps/export/tests/test_export_instance.py
  corehq/apps/export/tests/test_export_item.py
  corehq/apps/export/views/download.py
  corehq/apps/export/views/edit.py
  corehq/apps/export/views/list.py
  corehq/apps/export/views/new.py
  corehq/apps/export/views/utils.py
Labels: product/all-users-all-environments

#32797 Bugfix for remote linked multimedia that already exists downstream
  corehq/apps/app_manager/views/utils.py
  corehq/apps/hqmedia/models.py
  corehq/apps/linked_domain/remote_accessors.py
  corehq/apps/linked_domain/tests/test_linked_apps.py
  corehq/apps/linked_domain/util.py
Labels: QA Passed, product/invisible

#32798 Ze/bulk import all case types
  corehq/apps/case_importer/const.py
  corehq/apps/case_importer/tasks.py
  corehq/apps/case_importer/templates/case_importer/excel_config.html
  corehq/apps/case_importer/templates/case_importer/excel_fields.html
  corehq/apps/case_importer/tracking/case_upload_tracker.py
  corehq/apps/case_importer/util.py
  corehq/apps/case_importer/views.py
Labels: product/all-users-all-environments, Risk: High

#32839 Fix bug saving form values
  corehq/apps/events/models.py
  corehq/apps/events/tests/test_models.py
Labels: product/invisible

#32783 Best guess at adding new Q6a to Vectorlink report
  custom/abt/reports/flagspecs_v2019.yml
Labels: product/custom

#32832 Adds size limit to attachments for form submission API
  corehq/apps/receiverwrapper/tests/test_submissions.py
  corehq/ex-submodules/couchforms/exceptions.py
  corehq/ex-submodules/couchforms/getters.py
  settings.py
Labels: product/invisible

#32853 Es/codeowners
  .github/CODEOWNERS
Labels: product/invisible

#32799 Data Dictionary: Migration for group field to a model
  corehq/apps/data_dictionary/management/commands/populate_case_prop_groups.py
  corehq/apps/data_dictionary/migrations/0011_casepropertygroup.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32854 Add dropdown divider to form dropdown
  corehq/apps/cloudcare/templates/formplayer/menu_list.html
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/dropdowns.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_dropdown.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/dropdowns._dropdown.style.diff.txt
Labels: product/feature-flag, Risk: Medium

#32843 Delete attendees
  corehq/apps/events/exceptions.py
  corehq/apps/events/models.py
  corehq/apps/events/tasks.py
  corehq/apps/events/templates/edit_attendee.html
  corehq/apps/events/tests/test_models.py
  corehq/apps/events/tests/test_views.py
  corehq/apps/events/urls.py
  corehq/apps/events/views.py
Labels: product/all-users-all-environments

#32850 Remove Repeater.connection_settings foreign key constraint
  corehq/apps/auditcare/models.py
  corehq/apps/hqwebapp/models.py
  corehq/apps/users/models_role.py
  corehq/apps/zapier/tests/test_zapier_forwarding.py
  corehq/apps/zapier/tests/test_zapier_hooks.py
  corehq/motech/dhis2/tests/test_views.py
  corehq/motech/models.py
  corehq/motech/openmrs/tests/test_atom_feed.py
  corehq/motech/repeaters/management/commands/populate_repeater_names.py
  corehq/motech/repeaters/migrations/0015_drop_connection_settings_fk.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_proxy_models.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/util/models.py
  corehq/util/tests/test_models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#32842 Custom assertions in app manager
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/exceptions.py
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/static/app_manager/js/custom_assertions.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/suite_xml/generator.py
  corehq/apps/app_manager/suite_xml/post_process/menu.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/suite_xml/sections/menus.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/custom_assertions.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_settings.html
  corehq/apps/app_manager/templates/app_manager/partials/settings/app_settings.html
  corehq/apps/app_manager/tests/test_suite_assertions.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/app_manager/views/utils.py
Labels: product/feature-flag, Core Compatibility

#32858 Generate token for Update Translations workflow
  .github/workflows/update-translations.yml
Labels: product/invisible

#32866 Unindent lines
  .github/workflows/update-translations.yml
Labels: product/invisible

#32851 Update case export select logic
  corehq/apps/export/models/new.py
  corehq/apps/export/templates/export/partials/new_customize_export_templates.html
  corehq/apps/export/views/new.py
Labels: product/all-users-all-environments

#32865 Revert PR #32389
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/hqcase/utils.py
  corehq/ex-submodules/casexml/apps/case/mock/case_block.py
  corehq/ex-submodules/casexml/apps/case/tests/test_case_block.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#32871 Update Translations update
  .github/workflows/update-translations.yml
Labels: product/invisible

#32876 Fixed background colors for case tiles in Web Apps
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
Labels: product/feature-flag

#32652 Use ellipsis instead of undefined
  corehq/apps/callcenter/sync_usercase.py
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/tests/test_importer.py
  corehq/apps/hqcase/api/updates.py
  corehq/apps/hqcase/tests/test_case_api_updates.py
  corehq/apps/hqcase/tests/test_case_sharing.py
  corehq/ex-submodules/casexml/apps/case/mock/case_block.py
  corehq/ex-submodules/casexml/apps/case/mock/tests/test_case_block.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py
  corehq/motech/fhir/tasks.py
  corehq/motech/fhir/tests/test_tasks.py
Labels: product/invisible

#32873 add user type names for system case auto updates
  corehq/apps/data_interfaces/utils.py
  corehq/apps/hqcase/utils.py
  corehq/apps/reports/standard/cases/case_data.py
  corehq/apps/reports/standard/cases/utils.py
  corehq/apps/reports/tests/test_util.py
  corehq/ex-submodules/casexml/apps/case/util.py
Labels: product/all-users-all-environments

#32882 Update `flagspecs_v2020.yml`
  custom/abt/reports/flagspecs_v2020.yml
Labels: product/invisible

#32868 WAF_ALLOW media upload reqs
  corehq/apps/cloudcare/urls.py
Labels: Risk: Medium

#32886 Add migration to apply update to es user mapping
  corehq/apps/es/migrations/0003_add_assigned_location_ids.py
  migrations.lock
Labels: reindex/migration

#32885 Conditionally disable bulk case exports + better progress indication
  corehq/apps/export/exceptions.py
  corehq/apps/export/tasks.py
  corehq/apps/export/views/download.py
  corehq/apps/export/views/list.py
Labels: product/all-users-all-environments

#32889 Allow case tile rows to grow in height in web apps
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: product/feature-flag, Risk: Medium

#32836 Obfuscate URL on Case List and Case List Explorer pages
  corehq/apps/reports/static/reports/js/reports.async.js
  corehq/apps/reports/tasks.py
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
Labels: QA Passed, product/all-users-all-environments, product/feature-flag

#32901 Fix ARIA property name
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: Risk: Medium
