Repository dimagi/commcare-hq, pull requests merged in 2023-01, with the labels that each got.

#32348 Case List Explorer case property labels
  corehq/apps/data_interfaces/views.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/cases/filters.py
  corehq/apps/reports/static/reports/js/filters/case_list_explorer.js
  corehq/apps/reports/templates/reports/filters/explorer_columns.html
  corehq/apps/reports/tests/test_case_list_explorer_report.py
Labels: Open for review: do not merge, product/feature-flag

#32416 Multi-select case lists: throw JS error when checkboxes selected exceeds max select value
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#32433 Display date format to the user
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#32451 Migration to create initial audit events for AutomaticUpdateRule
  corehq/apps/data_interfaces/migrations/0032_bootstrap_audit_events_for_update_rules.py
  migrations.lock
Labels: reindex/migration

#32415 Maintenance alert scheduling
  corehq/apps/hqwebapp/migrations/0010_maintenancealert_scheduling.py
  corehq/apps/hqwebapp/models.py
  corehq/apps/hqwebapp/static/hqwebapp/js/maintenance_alerts.js
  corehq/apps/hqwebapp/templates/hqwebapp/maintenance_alerts.html
  corehq/apps/hqwebapp/tests/test_models.py
  corehq/apps/hqwebapp/tests/test_views.py
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/views.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/admin

#32445 Migrated hqwebapp js tests to RequireJS
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/hqwebapp/static/hqwebapp/js/common.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/static/hqwebapp/js/mocha.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/assert_properties_spec.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/inactivity_spec.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/main.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/urllib_spec.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/widgets_spec.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/requirejs.html
  corehq/apps/hqwebapp/templates/hqwebapp/spec/mocha.html
  corehq/apps/mocha/templates/mocha/base.html
Labels: product/invisible, Risk: Medium

#32455 Set a maximum form-size beyond which we will not attempt to reprocess a failed form
  corehq/form_processor/reprocess.py
Labels: product/invisible

#32456 Revert "Migrated hqwebapp js tests to RequireJS"
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/hqwebapp/static/hqwebapp/js/common.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/static/hqwebapp/js/mocha.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/assert_properties_spec.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/inactivity_spec.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/main.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/urllib_spec.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/widgets_spec.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/requirejs.html
  corehq/apps/hqwebapp/templates/hqwebapp/spec/mocha.html
  corehq/apps/mocha/templates/mocha/base.html
Labels: Risk: Medium

#32432 upgrade dropbox api library to 11.36.0
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#32459 Re-Revert "Migrated hqwebapp js tests to RequireJS"
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/static/hqwebapp/js/common.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/assert_properties_spec.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/inactivity_spec.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/main.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/urllib_spec.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/widgets_spec.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/requirejs.html
  corehq/apps/hqwebapp/templates/hqwebapp/spec/mocha.html
  corehq/apps/mocha/static/mocha/js/main.js
  corehq/apps/mocha/templates/mocha/base.html
Labels: product/invisible, Risk: Medium

#32464 upgrade wheel to 0.38.1
  requirements/dev-requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#32466 Update SQLRepeater model to allow names to be of length 255
  corehq/motech/repeaters/management/commands/populate_repeater_names.py
  corehq/motech/repeaters/migrations/0011_alter_sqlrepeater_name.py
  corehq/motech/repeaters/models.py
  migrations.lock
Labels: reindex/migration, product/all-users-all-environments, product/feature-flag, product/invisible

#32471 Increase time limit for intermittently failing test
  corehq/motech/repeaters/tests/test_models_slow.py
Labels: product/invisible

#32457 Generic Inbound API - Log Action: Archive
  corehq/apps/reports/views.py
  corehq/motech/generic_inbound/templates/generic_inbound/request_log_detail.html
  corehq/motech/generic_inbound/tests/test_api.py
  corehq/motech/generic_inbound/utils.py
  corehq/motech/generic_inbound/views.py
  corehq/motech/urls.py
Labels: product/feature-flag

#32472 Custom report cleanup and bugfix
  custom/up_nrhm/static/up_nrhm/js/main.js
Labels: product/invisible

#32458 Check if secure_session should be unset
  corehq/middleware.py
Labels: product/invisible, Risk: High

#32475 Refactor Elastic service status utils to use adapter implementation
  corehq/apps/es/tests/test_client.py
  corehq/apps/hqadmin/escheck.py
  corehq/apps/hqadmin/service_checks.py
  corehq/apps/hqadmin/tests/test_service_checks.py
Labels: product/invisible

#32460 Add Django migration operations for changing Elasticsearch indexes
  corehq/apps/es/README.rst
  corehq/apps/es/__init__.py
  corehq/apps/es/apps.py
  corehq/apps/es/case_search.py
  corehq/apps/es/cases.py
  corehq/apps/es/client.py
  corehq/apps/es/domains.py
  corehq/apps/es/forms.py
  corehq/apps/es/groups.py
  corehq/apps/es/index/__init__.py
  corehq/apps/es/index/analysis.py
  corehq/apps/es/index/settings.py
  corehq/apps/es/management/commands/make_elastic_migration.py
  corehq/apps/es/migration_operations.py
  corehq/apps/es/sms.py
  corehq/apps/es/tests/index/__init__.py
  corehq/apps/es/tests/index/test_analysis.py
  corehq/apps/es/tests/index/test_settings.py
  corehq/apps/es/tests/test_client.py
  corehq/apps/es/tests/test_command_make_elastic_migration.py
  corehq/apps/es/tests/test_migration_operations.py
  corehq/apps/es/tests/test_test_utils.py
  corehq/apps/es/tests/test_utils.py
  corehq/apps/es/tests/utils.py
  corehq/apps/es/users.py
  corehq/apps/es/utils.py
  corehq/ex-submodules/pillowtop/es_utils.py
  corehq/ex-submodules/pillowtop/management/commands/update_es_mapping.py
  corehq/ex-submodules/pillowtop/migrations/0006_add_geopoint_to_case_search_index.py
  corehq/ex-submodules/pillowtop/tests/utils.py
  corehq/pillows/management/commands/print_elastic_mappings.py
  corehq/pillows/management/commands/tests/test_utils.py
  corehq/pillows/mappings/tests/test_utils.py
  corehq/pillows/mappings/utils.py
  corehq/util/django_migrations.py
  corehq/util/es/interface.py
  corehq/util/tests/test_django_migrations.py
  corehq/warnings.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
Labels: QA Passed, product/invisible, Risk: High

#32469 Refactor ESQuery to use document adapters
  corehq/apps/es/es_query.py
  corehq/apps/es/fake/es_query_fake.py
  corehq/apps/es/tests/test_aggregations.py
  corehq/apps/es/tests/test_esquery.py
  corehq/apps/export/export.py
  corehq/apps/export/multiprocess.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/monitoring.py
  corehq/elastic.py
  custom/up_nrhm/tests/reports/test_asha_reports.py
Labels: QA Passed, product/invisible

#32465 [B5] compile sass with django compressor using dart sass (requires commcare-cloud update and maintenance)
  .scss-lint.yml
  DEV_SETUP.md
  Dockerfile
  corehq/apps/hqwebapp/precompilers.py
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/typography/_links.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/variables/_colors.scss
  corehq/apps/styleguide/templates/styleguide/base.html
  settings.py
Labels: product/invisible

#32335 [USH-2606] Django migration to backfill MessaginSubevent date column
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/reports/standard/sms.py
  corehq/apps/sms/management/commands/populate_app_id_for_sms.py
  corehq/apps/sms/migrations/0056_backfill_sms_event_date.py
  custom/abt/reports/late_pmt.py
  docs/migration_command_pattern.rst
  migrations.lock
  testapps/test_pillowtop/tests/test_sms_pillow.py
Labels: reindex/migration

#32500 Don't redo preindex if email flag not set
  corehq/apps/hqadmin/management/commands/preindex_everything.py
Labels: product/invisible

#32501 add bootstrap 5.2.3 as a dependency
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#32498 [security] resolve qs to at least 6.9.7
  package.json
  yarn.lock
Labels: product/invisible, dependencies

#32497 [security] bump future to 0.18.3
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#30718 Update build documentation
  corehq/apps/builds/README.rst
Labels: product/invisible

#32495 Make Repeater name configurable
  corehq/apps/reports/filters/select.py
  corehq/motech/management/commands/create_repeat_records.py
  corehq/motech/repeaters/forms.py
  corehq/motech/repeaters/migrations/00012_create_default_names_for_repeaters.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/templates/repeaters/partials/repeater_row.html
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/views/repeaters.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/all-users-all-environments, product/feature-flag

#32490 Disable download when playing form attachment
  corehq/apps/reports/templates/reports/form/partials/single_form.html
  corehq/apps/reports/templates/reports/reportdata/view_form_attachment.html
  corehq/apps/reports/urls.py
  corehq/apps/reports/views.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#32508 Ce/request log space
  corehq/motech/const.py
  corehq/motech/models.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_tasks.py
Labels: product/invisible

#32509 Adds additional workaround for psycopg2 error
  DEV_SETUP_MAC.md
Labels: product/invisible

#32504 Add bootstrap migration for elasticsearch indices
  corehq/apps/es/migrations/0001_bootstrap_es_indexes.py
  corehq/apps/es/migrations/__init__.py
  corehq/apps/es/tests/test_migration_operations.py
  migrations.lock
Labels: reindex/migration

#32506 [USH-1563] validate email address in email messaging content
  corehq/apps/sms/models.py
  corehq/messaging/scheduling/exceptions.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/tests/test_content.py
Labels: product/all-users-all-environments

#32403 Remove obsolete Lookup Table couch views and couch_id
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/fixtures/__init__.py
  corehq/apps/fixtures/_design/views/data_items_by_domain_type/map.js
  corehq/apps/fixtures/_design/views/data_items_by_domain_type/reduce.js
  corehq/apps/fixtures/_design/views/data_items_by_field_value/map.js
  corehq/apps/fixtures/_design/views/data_types_by_domain_tag/map.js
  corehq/apps/fixtures/_design/views/data_types_by_domain_tag/reduce.js
  corehq/apps/fixtures/_design/views/ownership/map.js
  corehq/apps/fixtures/_design/views/ownership/reduce.js
  corehq/apps/fixtures/migrations/0009_remove_lookuptablerowowner_couch_id.py
  corehq/apps/fixtures/models.py
  corehq/couchapps/__init__.py
  corehq/couchapps/tests/test_all_docs.py
  corehq/util/tests/test_couchdb_management.py
  migrations.lock
  settings.py
Labels: reindex/migration, product/invisible, Risk: Medium

#32488 add max size limit to form xml
  corehq/ex-submodules/couchforms/const.py
  corehq/ex-submodules/couchforms/exceptions.py
  corehq/ex-submodules/couchforms/getters.py
  corehq/form_processor/reprocess.py
Labels: Risk: High

#32393 Add tombstones in mappings
  corehq/apps/es/client.py
  corehq/apps/es/migrations/0002_add_tombstones.py
  corehq/pillows/mappings/app_mapping.py
  corehq/pillows/mappings/case_mapping.py
  corehq/pillows/mappings/case_search_mapping.py
  corehq/pillows/mappings/domain_mapping.py
  corehq/pillows/mappings/group_mapping.py
  corehq/pillows/mappings/sms_mapping.py
  corehq/pillows/mappings/user_mapping.py
  corehq/pillows/mappings/xform_mapping.py
  migrations.lock
Labels: reindex/migration, Risk: High

#32513 Add ReindexCouchViews migration operation
  CONTRIBUTING.rst
  corehq/ex-submodules/dimagi/utils/couch/migration_operations.py
  manage.py
Labels: product/invisible

#32507 "login" -> "log in" when used as a verb.
  DEV_SETUP.md
  corehq/apps/cloudcare/esaccessors.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/templates/formplayer/grid_view.html
  corehq/apps/cloudcare/templates/formplayer/users.html
  corehq/apps/export/system_properties.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/hqadmin/templates/hqadmin/authenticate_as.html
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/privileges.py
  corehq/toggles/__init__.py
  docs/sso/adding_idp.rst
  docs/web_apps.rst
Labels: Risk: Medium

#32516 upgrade setuptools to 65.5.1 in docs-requirements
  requirements/docs-requirements.txt
Labels: product/invisible, dependencies

#32514 Improve es_test decorator
  corehq/apps/es/tests/test_test_utils.py
  corehq/apps/es/tests/utils.py
Labels: product/invisible

#32518 Skip some github actions steps if secrets are unavailable
  .github/workflows/tests.yml
Labels: product/invisible

#32485 Refactor legacy Elastic utils in tests
  corehq/apps/domain/tests/test_domain_calculated_properties.py
  corehq/elastic.py
  testapps/test_elasticsearch/tests/test_xform_es.py
Labels: product/invisible

#32448 Cleanup UCRs in tests
  corehq/apps/accounting/tests/test_subscription_permissions_changes.py
  corehq/apps/api/tests/ucr_resources.py
  corehq/apps/cleanup/tests/test_dbaccessors.py
  corehq/apps/userreports/tests/test_async_indicators.py
  corehq/apps/userreports/tests/test_choice_provider.py
  corehq/apps/userreports/tests/test_columns.py
  corehq/apps/userreports/tests/test_data_source_config.py
  corehq/apps/userreports/tests/test_dbaccessors.py
  corehq/apps/userreports/tests/test_location_data_source.py
  corehq/apps/userreports/tests/test_registry_data_source_config.py
  corehq/apps/userreports/tests/test_report_aggregation.py
  corehq/apps/userreports/tests/test_report_config.py
  corehq/apps/userreports/tests/test_report_data.py
  corehq/apps/userreports/tests/test_report_filters.py
  corehq/apps/userreports/tests/test_save_errors.py
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/userreports/tests/utils.py
Labels: Risk: High

#32519 truncate request body as well
  corehq/motech/const.py
  corehq/motech/models.py
  corehq/motech/repeaters/models.py
Labels: product/invisible

#32531 use brief exports to populate data tile
  corehq/apps/dashboard/models.py
Labels: product/invisible

#32522 Refactor send_to_elasticsearch usage in tests
  corehq/apps/analytics/tests/test_partner_analytics_utils.py
  corehq/apps/api/tests/case_resources.py
  corehq/apps/api/tests/form_resources.py
  corehq/apps/api/tests/group_resources.py
  corehq/apps/api/tests/user_resources.py
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/app_manager/tests/views/test_paginate_releases.py
  corehq/apps/callcenter/tests/test_owner_options_view.py
  corehq/apps/callcenter/tests/test_utils.py
  corehq/apps/case_search/tests/test_filter_dsl.py
  corehq/apps/cleanup/tests/test_dbaccessors.py
  corehq/apps/cleanup/tests/test_delete_es_docs_for_domain.py
  corehq/apps/cloudcare/tests/test_esaccessors.py
  corehq/apps/custom_data_fields/tests/test_profiles.py
  corehq/apps/data_analytics/tests/test_esaccessors.py
  corehq/apps/data_analytics/tests/test_malt_generator.py
  corehq/apps/data_analytics/tests/utils.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/apps/data_interfaces/tests/test_deduplication_rules.py
  corehq/apps/domain/tests/test_domain_calculated_properties.py
  corehq/apps/enterprise/tests/test_enterprise_mobile_worker_settings.py
  corehq/apps/es/tests/test_filters.py
  corehq/apps/export/tests/test_esaccessors.py
  corehq/apps/export/tests/test_export_filters.py
  corehq/apps/export/tests/test_get_export_file.py
  corehq/apps/export/tests/test_incremental.py
  corehq/apps/hqadmin/tests/test_stale_data_in_es.py
  corehq/apps/hqcase/tests/test_serialization.py
  corehq/apps/reports/tests/test_case_list_report.py
  corehq/apps/reports/tests/test_enterprise_user_filter.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/reports/tests/test_filters.py
  corehq/apps/saved_reports/tests/end_to_end/test_scheduled_reports.py
  corehq/apps/saved_reports/tests/test_scheduled_reports.py
  corehq/apps/users/tests/test_get_domain_language.py
  corehq/apps/users/tests/test_signals.py
  corehq/ex-submodules/couchforms/tests/test_analytics.py
  custom/covid/tests/test_custom_rules.py
  testapps/test_elasticsearch/tests/test_xform_es.py
  testapps/test_pillowtop/tests/test_grouptouser_pillow.py
Labels: product/invisible, Risk: High, Risk: Medium

#32499 exclude sensitive / internal headers from generic inbound context
  corehq/motech/generic_inbound/utils.py
  corehq/motech/generic_inbound/views.py
Labels: product/feature-flag

#32406 Send emails when reaching 90% and 100% of mobile user limit
  corehq/apps/accounting/models.py
  corehq/apps/user_importer/tasks.py
  corehq/apps/users/models.py
  corehq/apps/users/templates/users/email/user_limit_notice.html
  corehq/apps/users/tests/test_email_events.py
  corehq/apps/users/views/mobile/users.py
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#32529 Add instructions for Fauxton setup
  DEV_SETUP.md
Labels: product/invisible

#32435 [USH-2701] Test using sentry for error reporting from web apps
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/middleware.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/main.js
  corehq/apps/cloudcare/static/cloudcare/js/sentry.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/util/context_processors.py
  settings.py
  settingshelper.py
Labels: Open for review: do not merge, product/invisible, Risk: Medium

#32540 remove <a> tag that was left behind in code removal
  corehq/apps/domain/templates/domain/manage_releases_by_app_profile.html
Labels: product/feature-flag

#32541 removed managehostedccz reference in js
  corehq/apps/app_manager/static/app_manager/js/manage_releases_by_app_profile.js
Labels: product/feature-flag

#32539 Updated text for button on modal to delete repeater config
  corehq/motech/repeaters/templates/repeaters/partials/repeater_row.html
  corehq/motech/repeaters/views/repeaters.py
Labels: product/all-users-all-environments

#32511 limit acceptable size of request for generic API
  corehq/apps/auditcare/models.py
  corehq/ex-submodules/couchforms/const.py
  corehq/ex-submodules/couchforms/getters.py
  corehq/form_processor/reprocess.py
  corehq/motech/generic_inbound/models.py
  corehq/motech/generic_inbound/tests/test_api.py
  corehq/motech/generic_inbound/utils.py
  corehq/motech/generic_inbound/views.py
  settings.py
Labels: product/feature-flag, Risk: High

#32548 Revert "[USH-2701] Test using sentry for error reporting from web apps"
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/middleware.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/main.js
  corehq/apps/cloudcare/static/cloudcare/js/sentry.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/util/context_processors.py
  settings.py
  settingshelper.py
Labels: Risk: Medium

#32542 include patient_case in search output if resource type matches
  corehq/motech/fhir/tests/test_fhir_views.py
  corehq/motech/fhir/views.py
Labels: product/feature-flag

#32474 Refactor corehq.apps.api.es to use Elastic adapter
  corehq/apps/api/es.py
  corehq/apps/api/tests/test_es.py
  corehq/apps/es/transient_util.py
  corehq/elastic.py
Labels: QA Passed, product/invisible, Risk: High

#32476 Update user pillow to use the document adapter
  corehq/pillows/user.py
Labels: QA Passed, product/invisible

#32517 Update `corehq.apps.users.signals` to use the document adapter
  corehq/apps/users/signals.py
  corehq/apps/users/tests/test_signals.py
  corehq/util/es/testing.py
Labels: QA Passed, product/invisible

#32549 remove static limit from log message
  corehq/ex-submodules/couchforms/getters.py
Labels: product/invisible

#32545 Revert "Incomplete forms P3 fix"
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/views.js
  corehq/apps/cloudcare/templates/formplayer/grid_view.html
Labels: awaiting QA, product/all-users-all-environments, Risk: Medium

#32547 Updated find_broken_builds to save build_broken flag and reason
  corehq/apps/app_manager/management/commands/flag_broken_builds.py
  corehq/apps/app_manager/models.py
Labels: product/invisible

#32431 Convert FORM_LINK_WORKFLOW FF to a Standard plan privilege
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0064_add_form_link_workflow_priv.py
  corehq/apps/accounting/utils/__init__.py
  corehq/apps/app_manager/tests/test_build_errors.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/hqwebapp/session_details_endpoint/tests.py
  corehq/privileges.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#32550 Revert "Revert "[USH-2701] Test using sentry for error reporting from web apps""
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/middleware.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/main.js
  corehq/apps/cloudcare/static/cloudcare/js/sentry.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/apps/cloudcare/templates/preview_app/base.html
  corehq/apps/cloudcare/urls.py
  corehq/apps/cloudcare/views.py
  corehq/apps/hqwebapp/static/sentry/js/sentry.browser.7.28.0.min.js
  corehq/util/context_processors.py
  settings.py
  settingshelper.py
Labels: QA Passed, Risk: Medium

#32532 "Switching project spaces" bugfix
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
Labels: QA Passed, product/invisible, Risk: Medium
