Repository dimagi/commcare-hq, pull requests merged in 2024-09, with the labels that each got.

#35005 Building Webpack on HQ
  .eslintrc.js
  .gitignore
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/hqadmin/templates/hqadmin/hqadmin_base_report.html
  corehq/apps/hqwebapp/management/commands/generate_webpack_settings.py
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/commcarehq.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/commcarehq.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/webpack.html
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/templatetags/tests/templates/webpack_base.html
  corehq/apps/hqwebapp/templatetags/tests/test_tag.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/commcarehq.js.diff.txt
  corehq/apps/hqwebapp/tests/utils/test_bootstrap_changes.py
  corehq/apps/mocha/templates/mocha/base.html
  corehq/apps/prototype/static/prototype/js/webpack/bootstrap3_amd.js
  corehq/apps/prototype/static/prototype/js/webpack/bootstrap5_amd.js
  corehq/apps/prototype/static/prototype/js/webpack/knockout_pagination.js
  corehq/apps/prototype/templates/prototype/webpack/bootstrap3_amd.html
  corehq/apps/prototype/templates/prototype/webpack/bootstrap5_amd.html
  corehq/apps/prototype/templates/prototype/webpack/knockout_pagination.html
  corehq/apps/prototype/urls.py
  corehq/apps/prototype/views/webpack.py
  corehq/apps/userreports/static/userreports/js/configurable_report.js
  docker/run.sh
  get_webpack_manifest.py
  package.json
  scripts/test-make-docs.sh
  webpack/appPaths.js
  webpack/generateDetails.js
  webpack/plugins.js
  webpack/utils.js
  webpack/webpack.b3.common.js
  webpack/webpack.common.js
  webpack/webpack.dev.js
  webpack/webpack.prod.js
  yarn.lock
Labels: product/prod-india-all-users, dependencies, Risk: Medium, dependencies/javascript

#35057 Fix saved report for data forwarding records being deleted
  corehq/apps/saved_reports/models.py
  corehq/apps/saved_reports/tests/test_models.py
Labels: product/all-users-all-environments

#35077 Removed jquery-timeago
  corehq/apps/hqwebapp/decorators.py
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/hq.helpers.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/hq.helpers.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templatetags/proptable_tags.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/hq.helpers.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/reports.async.js.diff.txt
  corehq/apps/hqwebapp/tests/test_proptable_tags.py
  corehq/apps/reports/static/reports/js/bootstrap3/reports.async.js
  corehq/apps/reports/static/reports/js/bootstrap5/reports.async.js
  package.json
  yarn.lock
Labels: product/invisible, dependencies, Risk: Medium

#35081 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: product/invisible

#35078 Fixed buttons displayed in Solutions Feature Request modal
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/modal_report_issue.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/modal_solutions_feature_request.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/modal_report_issue.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/modal_solutions_feature_request.html.diff.txt
Labels: product/admin

#35016 Form Expression Repeater
  corehq/motech/repeaters/expression/forms.py
  corehq/motech/repeaters/expression/repeater_generators.py
  corehq/motech/repeaters/expression/repeaters.py
  corehq/motech/repeaters/expression/tests.py
  corehq/motech/repeaters/expression/views.py
  corehq/motech/repeaters/signals.py
  corehq/motech/urls.py
  settings.py
Labels: QA Passed, product/feature-flag

#34800 Add gauge limiter class to be used to throttle async case import tasks based on pillow lag
  corehq/apps/change_feed/topics.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  corehq/project_limits/admin.py
  corehq/project_limits/gauge.py
  corehq/project_limits/migrations/0003_pillowlaggaugedefinition.py
  corehq/project_limits/models.py
  corehq/project_limits/tests/test_gauge.py
  migrations.lock
Labels: reindex/migration

#35072 put location assignment work behind feature flag
  corehq/apps/locations/static/locations/js/widgets.js
Labels: product/feature-flag

#35070 Create local_dev_guide.rst
  local_dev_guide.rst
Labels: product/invisible

#35060 Fixes the issue of adblocker blocking the tag manager HQ script
  corehq/apps/analytics/README.md
  corehq/apps/analytics/static/analytix/js/gtx.js
  corehq/apps/analytics/templates/analytics/analytics_js.html
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/base_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/base_main.js
  corehq/apps/hqwebapp/templatetags/tests/rendered/javascript_libraries_hq.html
  corehq/apps/hqwebapp/templatetags/tests/rendered/javascript_libraries_hq_bootstrap5.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/base_main.js.diff.txt
Labels: Open for review: do not merge, product/invisible

#35054 Use the HTTP response from a Configurable Repeater to update a case
  corehq/apps/hqcase/api/updates.py
  corehq/apps/hqcase/utils.py
  corehq/apps/userreports/ui/fields.py
  corehq/form_processor/models/cases.py
  corehq/motech/repeaters/expression/forms.py
  corehq/motech/repeaters/expression/repeaters.py
  corehq/motech/repeaters/expression/tests.py
  corehq/motech/repeaters/expression/views.py
  corehq/motech/repeaters/forms.py
Labels: product/feature-flag, Risk: High

#35073 Use env settings email for AEs report
  corehq/apps/hqwebapp/tasks.py
  settings.py
Labels: product/all-users-all-environments, product/invisible

#35088 Added check for region before showing it
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
Labels: product/invisible, Risk: Medium

#35041 Fill in missing filename after broadcast within same question tile
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/entry_file.html
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#35085 Case Tile UI tweaks
  corehq/apps/cloudcare/static/cloudcare/js/markdown.js
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/cell_grid_style.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/tile_grouped_item.html
Labels: Risk: Medium

#35093 Put UI change behind existing feature flag for case tiles
  corehq/apps/cloudcare/static/cloudcare/js/markdown.js
Labels: product/feature-flag, Risk: Medium

#35096 Suppress verbose make requirements output
  requirements/Makefile
Labels: dependencies

#35087 Remove Enterprise edition from select plan workflow
  corehq/apps/domain/views/accounting.py
Labels: product/all-users-all-environments

#35086 Add notices and "talk to sales" when renewing plan would be a downgrade
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/templates/accounting/partials/confirm_plan_summary.html
  corehq/apps/accounting/templates/accounting/partials/downgrade_messages.html
  corehq/apps/accounting/templates/accounting/partials/renew_plan_selection.html
  corehq/apps/accounting/tests/test_forms.py
  corehq/apps/domain/templates/domain/renew_plan.html
  corehq/apps/domain/templates/domain/selected_annual_plan.html
  corehq/apps/domain/templates/domain/selected_plan_contact.html
  corehq/apps/domain/urls.py
  corehq/apps/domain/views/accounting.py
Labels: product/all-users-all-environments

#35066 Make Greater Than or Equal Date Criteria Explicit
  corehq/apps/data_interfaces/forms.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_criteria.js
  corehq/apps/data_interfaces/templates/data_interfaces/partials/case_rule_criteria.html
  corehq/apps/data_interfaces/tests/test_auto_case_updates.py
  corehq/apps/data_interfaces/tests/test_models.py
Labels: product/all-users-all-environments

#35103 Replace nose attrs and yield tests to a use `pytest.mark`
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/auditcare/tests/test_models.py
  corehq/apps/case_search/tests/test_subcase_query_parser.py
  corehq/apps/case_search/tests/test_value_functions.py
  corehq/apps/case_search/tests/test_xpath_functions.py
  corehq/apps/es/tests/test_test_utils.py
  corehq/apps/es/tests/test_utils.py
  corehq/apps/es/tests/utils.py
  corehq/apps/es/transient_util.py
  corehq/apps/export/tests/test_dbaccessors.py
  corehq/apps/export/tests/test_export_models_new.py
  corehq/apps/hqadmin/tests/test_corrupt_couch.py
  corehq/apps/hqwebapp/tests/test_compress_command.py
  corehq/apps/locations/tests/test_location_safety.py
  corehq/apps/user_importer/tests/test_validators.py
  corehq/apps/userreports/tests/test_utils.py
  corehq/ex-submodules/couchexport/tests/test_excel_format_value.py
  corehq/ex-submodules/couchforms/tests/test_geopoint.py
  corehq/ex-submodules/dimagi/utils/tests/test_database.py
  corehq/ex-submodules/dimagi/utils/tests/test_retry.py
  corehq/ex-submodules/dimagi/utils/tests/test_web.py
  corehq/extensions/tests.py
  corehq/form_processor/tests/test_sql_update_strategy.py
  corehq/form_processor/tests/test_system_action.py
  corehq/form_processor/tests/utils.py
  corehq/messaging/tests/test_smsbackends.py
  corehq/motech/fhir/tests/test_matchers.py
  corehq/motech/fhir/tests/test_searchers.py
  corehq/motech/openmrs/tests/test_tasks.py
  corehq/project_limits/tests/test_rate_definition.py
  corehq/sql_db/tests/test_checks.py
  corehq/sql_db/tests/test_partition_config.py
  corehq/sql_db/tests/test_routers.py
  corehq/tests/noseplugins/__init__.py
  corehq/tests/pytest_compat.py
  corehq/tests/test_pickle.py
  corehq/util/test_utils.py
  corehq/util/tests/test_celery_utils.py
  corehq/util/urlvalidate/test/test_urlsanitize.py
  custom/abt/reports/tests/test_flagspecs.py
  testapps/test_gunicorn/tests.py
Labels: product/invisible, Risk: High, Risk: Medium

#35084 kill LandingPageAppView (dead code)
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/user_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/models.js
  corehq/apps/cloudcare/templates/cloudcare/partials/all_templates.html
  corehq/apps/cloudcare/templates/cloudcare/partials/grid_view/landing_page_app.html
Labels: QA Passed, Risk: Medium

#35106 Disable `custom.onse`
  custom/onse/README.rst
  settings.py
Labels: product/custom, product/invisible

#35109 Add explicit toggle states to test
  corehq/apps/cloudcare/static/cloudcare/js/spec/markdown_spec.js
Labels: product/invisible, Risk: Medium

#35090 Management Command to Update Geopoint Data in ES
  corehq/apps/geospatial/management/commands/index_geolocation_case_properties.py
  corehq/apps/geospatial/tests/test_index_geolocation_case_properties.py
Labels: product/invisible

#34993 Reassignment for Geo Cases
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/case_management.js
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/templates/case_management.html
  corehq/apps/geospatial/templates/geospatial/case_management_base.html
  corehq/apps/geospatial/tests/test_utils.py
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/urls.py
  corehq/apps/geospatial/utils.py
  corehq/apps/geospatial/views.py
Labels: QA Passed, product/feature-flag

#35037 async reassignment for geo cases
  corehq/apps/geospatial/exceptions.py
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/tasks.py
  corehq/apps/geospatial/templates/case_management.html
  corehq/apps/geospatial/tests/test_utils.py
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/utils.py
  corehq/apps/geospatial/views.py
Labels: Open for review: do not merge, QA Passed, product/feature-flag

#35092 allow up to 5 chained configurable repeaters with no cycles
  corehq/motech/repeaters/expression/repeaters.py
  corehq/motech/repeaters/expression/tests.py
Labels: product/feature-flag

#35113 Removed stock status map report
  corehq/apps/commtrack/static/commtrack/images/goodstock.png
  corehq/apps/commtrack/static/commtrack/images/no_data.png
  corehq/apps/commtrack/static/commtrack/images/overstock.png
  corehq/apps/commtrack/static/commtrack/images/stockout.png
  corehq/apps/commtrack/static/commtrack/images/warning.png
  corehq/apps/hqwebapp/decorators.py
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/base_maps.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/config.dataTables.bootstrap.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/base_template.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/partials/base_maps.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/partials/maps.html.diff.txt
  corehq/apps/reports/commtrack/__init__.py
  corehq/apps/reports/commtrack/data_sources.py
  corehq/apps/reports/commtrack/maps.py
  corehq/apps/reports/standard/maps.py
  corehq/apps/reports/static/reports/js/bootstrap3/base_maps.js
  corehq/apps/reports/static/reports/js/bootstrap3/config.dataTables.bootstrap.js
  corehq/apps/reports/static/reports/js/bootstrap5/base_maps.js
  corehq/apps/reports/static/reports/js/bootstrap5/config.dataTables.bootstrap.js
  corehq/apps/reports/templates/reports/bootstrap3/base_template.html
  corehq/apps/reports/templates/reports/bootstrap5/base_template.html
  corehq/apps/reports/templates/reports/partials/bootstrap3/base_maps.html
  corehq/apps/reports/templates/reports/partials/bootstrap3/maps.html
  corehq/apps/reports/templates/reports/partials/bootstrap5/base_maps.html
  corehq/apps/reports/templates/reports/partials/bootstrap5/maps.html
  corehq/apps/reports/templates/reports/partials/commtrack/stockstatus_mapdetail.html
  corehq/reports.py
  docs/index.rst
  docs/maps.rst
  package.json
  yarn.lock
Labels: product/feature-flag, dependencies, Risk: Medium

#35116 Added translations directory to translations/templates
  corehq/apps/translations/integrations/transifex/views.py
  corehq/apps/translations/templates/translations/app_translations.html
  corehq/apps/translations/templates/translations/blacklist_translations.html
  corehq/apps/translations/templates/translations/convert_translations.html
  corehq/apps/translations/templates/translations/download_translations.html
  corehq/apps/translations/templates/translations/migrate_project.html
  corehq/apps/translations/templates/translations/pull_resource.html
Labels: product/invisible

#35061 Improve case import UX
  corehq/apps/case_importer/static/case_importer/js/excel_fields.js
  corehq/apps/case_importer/static/case_importer/js/main.js
  corehq/apps/case_importer/suggested_fields.py
  corehq/apps/case_importer/templates/case_importer/excel_config.html
  corehq/apps/case_importer/templates/case_importer/excel_fields.html
  corehq/apps/case_importer/templates/case_importer/partials/excel_field_rows.html
  corehq/apps/case_importer/tests/test_suggested_fields.py
  corehq/apps/case_importer/views.py
Labels: QA Passed, Risk: High

#35120 PMI Evolve: Break up timespend value for different groups
  custom/abt/reports/flagspecs_v2020.yml
Labels: product/custom

#35122 Limit max row count on reports
  corehq/apps/reports/generic.py
  corehq/apps/reports/tests/test_generic.py
Labels: product/invisible

#35104 Move webpack manifest warnings to TemplateSyntaxErrors on page load
  corehq/apps/hqwebapp/management/commands/generate_webpack_settings.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/utils/webpack.py
  get_webpack_manifest.py
  scripts/test-make-docs.sh
Labels: product/invisible, dependencies/javascript

#35074 fix dashboard icon top alignment and height of cards when base font size is scaled above normal size
  corehq/apps/hqwebapp/static/dashboard/scss/dashboard-main.scss
Labels: product/prod-india-all-users

#35128 Add assertion to rule out bad test cleanup
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
Labels: product/invisible

#35118 Clean up caching for EnterprisePermissions
  corehq/apps/case_importer/tracking/dbaccessors.py
  corehq/apps/enterprise/models.py
  corehq/apps/enterprise/tests/test_permissions.py
  corehq/apps/es/users.py
  corehq/apps/users/models.py
  corehq/tabs/tabclasses.py
Labels: product/invisible

#34936 Upgrade twilio from 7.12.0 to 9.2.3
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, dependencies

#35064 Update default language when bulk uploading translations
  corehq/apps/translations/app_translations/upload_form.py
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: QA Passed

#35131 Check can_edit_or_view_location on location_lineage
  corehq/apps/locations/views.py
Labels: product/invisible

#35108 Filename broadcast bug fix 2
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
Labels: QA Passed, product/feature-flag, Risk: Medium

#35123 Get rid of extraneous white space from persistent menu navigation
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/persistent_menu.html
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/menu.scss
Labels: product/feature-flag, Risk: Medium

#35100 Update location through user api
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/test_user_resources.py
  corehq/apps/api/tests/test_user_updates.py
  corehq/apps/api/user_updates.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: product/all-users-all-environments, Risk: High

#35138 Update FF to deprecated status
  corehq/toggles/__init__.py
Labels: product/feature-flag

#35136 vellum:81a02d4222d41dad1b32ca2230c40e366f7c0a37
  corehq/apps/app_manager/static/app_manager/js/vellum/README.md
  corehq/apps/app_manager/static/app_manager/js/vellum/manifest.txt
  corehq/apps/app_manager/static/app_manager/js/vellum/src/local-deps.js
  corehq/apps/app_manager/static/app_manager/js/vellum/src/main-components.js
  corehq/apps/app_manager/static/app_manager/js/vellum/src/main.js
  corehq/apps/app_manager/static/app_manager/js/vellum/style.css
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: product/invisible

#35129 Webpack: Add Documentation Updates to the JavaScript Guide (RTD)
  DEV_FAQ.md
  DEV_SETUP.md
  docs/js-guide/README.rst
  docs/js-guide/amd-to-esm.rst
  docs/js-guide/code-organization.rst
  docs/js-guide/dependencies.rst
  docs/js-guide/migrating.rst
  docs/js-guide/module-history.rst
  docs/js-guide/requirejs-to-webpack.rst
  docs/js-guide/static-files.rst
  docs/js-guide/testing.rst
  docs/translations.rst
  scripts/codechecks/hqDefine.sh
Labels: product/invisible

#35140 [B5] Migrate Download Data Files View
  corehq/apps/export/static/export/js/bootstrap3/download_data_files.js
  corehq/apps/export/static/export/js/download_data_files.js
  corehq/apps/export/templates/export/bootstrap5/download_data_files.html
  corehq/apps/export/templates/export/download_data_files.html
  corehq/apps/export/views/utils.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/export/download_data_files.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/export/js/download_data_files.js.diff.txt
  corehq/apps/hqwebapp/utils/bootstrap/status/bootstrap3_to_5.json
Labels: product/prod-india-all-users

#35146 [B5] exports: paywall
  corehq/apps/export/templates/export/bootstrap3/paywall.html
  corehq/apps/export/templates/export/paywall.html
  corehq/apps/export/views/utils.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/export/paywall.html.diff.txt
  corehq/apps/hqwebapp/utils/bootstrap/status/bootstrap3_to_5.json
Labels: product/all-users-all-environments

#35141 Updates to bootstrap docs and migration tool
  corehq/apps/hqwebapp/management/commands/migrate_app_to_bootstrap5.py
  corehq/apps/hqwebapp/tests/utils/test_bootstrap_changes.py
  corehq/apps/hqwebapp/utils/bootstrap/changes.py
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-breadcrumb.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-checkbox.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-close.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-dl-horizontal.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-dropdown.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-file-inputs.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-form-group.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-form-inline.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-glyphicon.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-has-error.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-has-success.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-input-group-addon.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-input-group-btn.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-modal-header.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-nav.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-navbar-dark.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-navbar-light.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-navbar.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-page-header.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-pagination.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-panel.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-progress.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-select-form-control.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-well.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/form-group.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/inline-style.md
  corehq/apps/styleguide/templates/styleguide/bootstrap5/migration_guide.html
  settings.py
Labels: product/invisible

#35147 [B5] Exports: Export Data Source Data view
  corehq/apps/export/forms.py
  corehq/apps/export/templates/export/bootstrap3/datasource_export_view.html
  corehq/apps/export/templates/export/datasource_export_view.html
  corehq/apps/export/views/download.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/export/datasource_export_view.html.diff.txt
  corehq/apps/hqwebapp/utils/bootstrap/status/bootstrap3_to_5.json
Labels: product/feature-flag

#35144 Disabling invite a deactivated user
  corehq/apps/registration/forms.py
  corehq/apps/registration/tests/test_forms.py
Labels: product/all-users-all-environments, Risk: High

#35150 Set `secure` and `httponly` on `formplayer_session` cookie
  corehq/apps/cloudcare/middleware.py
  corehq/middleware.py
  settings.py
Labels: product/invisible, Risk: Medium
