Repository dimagi/commcare-hq, pull requests merged in 2024-08, with the labels that each got.

#34928 don't error if DB connection is None
  corehq/util/sentry.py
Labels: product/invisible

#34931 Bump Faker from 24.11.0 to 26.0.0
  requirements/dev-requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#34927 USH-4826: Fix alignment of button
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/question.html
Labels: Risk: Medium

#34938 Change type of button back to submit
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/entry_geo.html
Labels: Risk: Medium

#34924 add domain to `FactoryContext` to support loading DB expressions
  corehq/motech/generic_inbound/models.py
  corehq/motech/generic_inbound/tests/test_api_processing.py
  corehq/motech/repeaters/expression/forms.py
  corehq/motech/repeaters/expression/repeaters.py
Labels: product/feature-flag

#34911 Wait for serverup
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/preview_app.js
Labels: Risk: Medium

#34832 send window width in formplayer query
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
Labels: QA Passed, Risk: Medium

#34944 Drop `add_attempt()` method that does nothing
  corehq/motech/openmrs/views.py
  corehq/motech/repeaters/models.py
Labels: product/invisible

#34934 Upgrade setuptools from 70.0.0 to 72.1.0
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#34947 USH-4823: Fix alignment
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/question.html
Labels: Risk: Medium

#34957 Remove unused auditcare templates
  corehq/apps/auditcare/templates/auditcare/audit_views.html
  corehq/apps/auditcare/templates/auditcare/auditcare_config_broken.html
  corehq/apps/auditcare/templates/auditcare/index.html
  corehq/apps/auditcare/templates/auditcare/partials/base_event.html
  corehq/apps/auditcare/templates/auditcare/partials/couch_model_event.html
  corehq/apps/auditcare/templates/auditcare/partials/django_model_event.html
  corehq/apps/auditcare/templates/auditcare/partials/model_property_change.html
  corehq/apps/auditcare/templates/auditcare/partials/navigation_event.html
  corehq/apps/auditcare/utils/__init__.py
Labels: product/invisible

#34930 Reorganize and Restyle Web Apps Navbar
  corehq/apps/cloudcare/static/cloudcare/js/debugger/debugger.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/models.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/breadcrumbs.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/dropdown.html
  corehq/apps/cloudcare/templates/cloudcare/partials/sessions/list.html
  corehq/apps/cloudcare/templates/cloudcare/partials/users/restore_as_banner.html
  corehq/apps/cloudcare/templates/cloudcare/preview_app.html
  corehq/apps/hqwebapp/static/cloudcare/scss/debugger/debugger.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/breadcrumbs.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/navigation.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp-main.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/breadcrumbs.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/menu.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/navbar.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app-main.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app/breadcrumbs.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/debugger_debugger.debugger_debugger.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common_breadcrumbs.formplayer-common_breadcrumbs.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common_navigation.formplayer-common_navigation.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp-main.formplayer-webapp-main.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_breadcrumbs.formplayer-webapp_breadcrumbs.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_menu.formplayer-webapp_menu.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_navbar.formplayer-webapp_navbar.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/preview_app-main.preview_app-main.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/preview_app_breadcrumb.preview_app_breadcrumb.style.diff.txt
  docs/web_apps.rst
Labels: awaiting QA, Risk: Medium

#34962 remove unused throttle settings
  corehq/apps/api/resources/meta.py
  dev_settings.py
  docker/localsettings.py
  docker/min_settings.py
Labels: product/invisible, Risk: High

#34923 Fixes for UCR expressions in the DB
  corehq/apps/userreports/expressions/specs.py
  corehq/apps/userreports/filters/factory.py
  corehq/apps/userreports/models.py
  corehq/apps/userreports/specs.py
  corehq/apps/userreports/tests/test_data_source_config.py
  corehq/apps/userreports/views.py
Labels: product/all-users-all-environments, product/feature-flag

#34809 Support translatable words within calculated properties in case tiles
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/static/app_manager/js/details/utils.js
  corehq/apps/app_manager/suite_xml/case_tile_templates/bha_referrals.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/icon_text_grid.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_3X_two_4X_one_2X.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one_one.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_two.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/person_simple.xml
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/data/suite/suite-case-detail-instances.xml
  corehq/apps/app_manager/tests/data/suite/suite-case-tiles.xml
  corehq/apps/app_manager/tests/test_suite_formats.py
  corehq/apps/app_manager/tests/test_suite_sorting.py
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap3/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap5/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/ui_elements/ui-element-key-val-mapping.js.diff.txt
Labels: QA Passed, product/feature-flag, Core Compatibility

#34909 Change language on case search/case list screens
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
Labels: product/feature-flag, Risk: Medium

#34945 UCRs: Whitelist fields available to UCR related_doc expressions
  corehq/apps/userreports/expressions/specs.py
  corehq/apps/userreports/tests/test_expressions.py
Labels: product/invisible

#34956 Fix alignment issues
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/grouped_element_tile_row.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/sub_group.html
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/form.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app/form.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_form.formplayer-webapp_form.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/preview_app_form.preview_app_form.style.diff.txt
Labels: Risk: Medium

#34941 Repeat Group UI Improvement
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/fixtures.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/sub_group.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/form.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_form.formplayer-webapp_form.style.diff.txt
Labels: Risk: Medium

#34961 Improve test cleanup
  DEV_SETUP.md
  corehq/apps/aggregate_ucrs/tests/test_aggregation.py
  corehq/apps/app_manager/tests/test_apps.py
  corehq/apps/app_manager/tests/util.py
  corehq/apps/change_feed/tests/test_kafka_change_feed.py
  corehq/apps/cloudcare/tests/test_session.py
  corehq/apps/dump_reload/tests/test_couch_dump_load.py
  corehq/apps/smsforms/tests/test_app.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/userreports/tests/test_adapters.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/users/tests/test_signals.py
  corehq/apps/users/tests/util.py
  corehq/ex-submodules/phonelog/tests/test_sumologic.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/tests/test_middleware.py
  corehq/tests/util/context.py
  corehq/util/test_utils.py
  corehq/warnings.py
  custom/champ/tests/test_champ_cameroon.py
  custom/champ/tests/test_enhanced_peer_mobilization.py
  docker/files/Dockerfile.es.5
  manage.py
  requirements/dev-requirements.in
  requirements/dev-requirements.txt
  scent.py
Labels: dependencies, Risk: Medium

#34969 Riese/rm stripes
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/sub_group.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/form.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_form.formplayer-webapp_form.style.diff.txt
Labels: Risk: Medium

#34868 Form-submitting mobile workers invoicing
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/tests/generator.py
  corehq/apps/accounting/tests/test_invoicing.py
  corehq/apps/accounting/tests/test_tasks.py
  corehq/apps/accounting/usage.py
  corehq/apps/accounting/user_text.py
  corehq/apps/accounting/utils/__init__.py
Labels: QA Passed, product/all-users-all-environments

#34885 Add form-submitting mobile worker option to Trigger Invoice testing tools
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/tests/test_forms.py
Labels: QA Passed, product/admin

#34872 Persistent Menu Navigation in Web Apps
  corehq/apps/app_manager/templates/app_manager/profile.xml
  corehq/apps/cloudcare/static/cloudcare/js/debugger/debugger.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/models.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/cloudcare/partials/all_templates.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/breadcrumbs.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/dropdown.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/persistent_menu.html
  corehq/apps/cloudcare/templates/cloudcare/partials/sessions/list.html
  corehq/apps/cloudcare/templates/cloudcare/partials/users/restore_as_banner.html
  corehq/apps/cloudcare/templates/cloudcare/preview_app.html
  corehq/apps/hqwebapp/static/cloudcare/scss/debugger/debugger.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/breadcrumbs.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/navigation.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp-main.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/breadcrumbs.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/menu.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/navbar.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app-main.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app/breadcrumbs.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/debugger_debugger.debugger_debugger.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common_breadcrumbs.formplayer-common_breadcrumbs.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common_navigation.formplayer-common_navigation.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp-main.formplayer-webapp-main.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_breadcrumbs.formplayer-webapp_breadcrumbs.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_menu.formplayer-webapp_menu.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_navbar.formplayer-webapp_navbar.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/preview_app-main.preview_app-main.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/preview_app_breadcrumb.preview_app_breadcrumb.style.diff.txt
  docs/web_apps.rst
Labels: awaiting QA, product/feature-flag, Risk: Medium

#34977 Revert "Persistent Menu Navigation in Web Apps"
  corehq/apps/app_manager/templates/app_manager/profile.xml
  corehq/apps/cloudcare/static/cloudcare/js/debugger/debugger.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/models.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/cloudcare/partials/all_templates.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/breadcrumbs.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/dropdown.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/persistent_menu.html
  corehq/apps/cloudcare/templates/cloudcare/partials/sessions/list.html
  corehq/apps/cloudcare/templates/cloudcare/partials/users/restore_as_banner.html
  corehq/apps/cloudcare/templates/cloudcare/preview_app.html
  corehq/apps/hqwebapp/static/cloudcare/scss/debugger/debugger.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/breadcrumbs.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/navigation.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp-main.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/breadcrumbs.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/menu.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/navbar.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app-main.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app/breadcrumb.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/debugger_debugger.debugger_debugger.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common_breadcrumbs.formplayer-common_breadcrumbs.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common_navigation.formplayer-common_navigation.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp-main.formplayer-webapp-main.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_breadcrumbs.formplayer-webapp_breadcrumbs.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_menu.formplayer-webapp_menu.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_navbar.formplayer-webapp_navbar.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/preview_app-main.preview_app-main.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/preview_app_breadcrumb.preview_app_breadcrumb.style.diff.txt
  docs/web_apps.rst
Labels: Risk: Medium

#34968 Move "Add Case Property" to group
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
Labels: product/all-users-all-environments

#34978 Revert "Revert "Persistent Menu Navigation in Web Apps""
  corehq/apps/app_manager/templates/app_manager/profile.xml
  corehq/apps/cloudcare/static/cloudcare/js/debugger/debugger.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/models.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/cloudcare/partials/all_templates.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/breadcrumbs.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/dropdown.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/persistent_menu.html
  corehq/apps/cloudcare/templates/cloudcare/partials/sessions/list.html
  corehq/apps/cloudcare/templates/cloudcare/partials/users/restore_as_banner.html
  corehq/apps/cloudcare/templates/cloudcare/preview_app.html
  corehq/apps/hqwebapp/static/cloudcare/scss/debugger/debugger.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/breadcrumbs.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/navigation.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp-main.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/breadcrumbs.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/menu.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/navbar.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app-main.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app/breadcrumbs.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/debugger_debugger.debugger_debugger.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common_breadcrumbs.formplayer-common_breadcrumbs.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common_navigation.formplayer-common_navigation.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp-main.formplayer-webapp-main.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_breadcrumbs.formplayer-webapp_breadcrumbs.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_menu.formplayer-webapp_menu.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_navbar.formplayer-webapp_navbar.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/preview_app-main.preview_app-main.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/preview_app_breadcrumb.preview_app_breadcrumb.style.diff.txt
  docs/web_apps.rst
Labels: Risk: Medium

#34986 New columns for PMI Evolve Supervisory Report
  custom/abt/reports/data_sources/supervisory_v2020.json
  custom/abt/reports/expressions.py
  custom/abt/reports/flagspecs_v2020.yml
  custom/abt/reports/supervisory_report_v2020.json
Labels: product/custom

#34985 Separate login-as banner for small screens
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/breadcrumbs.html
  corehq/apps/cloudcare/templates/cloudcare/partials/sessions/list.html
  corehq/apps/cloudcare/templates/cloudcare/partials/users/restore_as_banner.html
  corehq/apps/geospatial/templates/gps_capture_view.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/module.less
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common-main.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/breadcrumbs.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/module.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/breadcrumbs.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app/breadcrumbs.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app/module.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common-main.formplayer-common-main.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common_breadcrumbs.formplayer-common_breadcrumbs.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-common_module.formplayer-common_module.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_breadcrumbs.formplayer-webapp_breadcrumbs.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/formplayer-webapp_module.formplayer-webapp_module.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/preview_app_module.preview_app_module.style.diff.txt
Labels: Risk: Medium

#34995 Drop `send_request()`
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_models_slow.py
Labels: product/invisible

#34991 Add duration field to RequestLog
  corehq/motech/migrations/0015_requestlog_duration.py
  corehq/motech/models.py
  migrations.lock
Labels: reindex/migration

#34997 Drop soft asserts
  corehq/motech/repeaters/tasks.py
Labels: product/invisible

#34996 Drop `get_payload()`
  corehq/motech/repeaters/models.py
Labels: product/invisible

#34972 Geospatial Assignment Workflow
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/static/geospatial/js/utils.js
  corehq/apps/geospatial/templates/geospatial/partials/review_assignment_modal.html
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#35004 Show Header for Display Group even without Display Text
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
Labels: Risk: Medium

#34979 Added form limits for enterprise form reports
  corehq/apps/enterprise/enterprise.py
  corehq/apps/enterprise/exceptions.py
  corehq/apps/enterprise/iterators.py
  corehq/apps/enterprise/tasks.py
  corehq/apps/enterprise/tests/test_iterators.py
Labels: product/invisible

#35002 Refactors around `ConfigurableAPI`
  corehq/apps/userreports/expressions/factory.py
  corehq/motech/generic_inbound/backend/base.py
  corehq/motech/generic_inbound/backend/hl7.py
  corehq/motech/generic_inbound/models.py
  corehq/motech/generic_inbound/templates/generic_inbound/api_edit.html
  corehq/motech/generic_inbound/tests/test_api_processing.py
  corehq/motech/generic_inbound/utils.py
  corehq/motech/generic_inbound/views.py
Labels: product/invisible

#35014 allow deleting UCR expressions
  corehq/apps/userreports/templates/userreports/ucr_expressions.html
  corehq/apps/userreports/views.py
Labels: product/feature-flag

#35021 Fix a bug with trying to fetch paginated enterprise reports
  corehq/apps/enterprise/api/resources.py
  corehq/apps/enterprise/tasks.py
Labels: product/invisible

#35015 don't clear fields on initial change event
  corehq/motech/static/motech/js/connection_settings_detail.js
Labels: product/all-users-all-environments

#35019 upgrade django to patched version to address CVE
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#35017 Updates to connection settings to support Azure AD B2C
  corehq/motech/auth.py
  corehq/motech/forms.py
  corehq/motech/migrations/0016_connectionsettings_include_client_id_and_more.py
  corehq/motech/models.py
  corehq/motech/static/motech/js/connection_settings_detail.js
  corehq/motech/utils.py
  corehq/motech/views.py
  migrations.lock
Labels: reindex/migration, product/all-users-all-environments

#34740 fix language menu for languages not showing in native script
  corehq/apps/app_manager/app_strings.py
Labels: product/invisible

#35036 Fix unable to resolve field errors in Domain Settings Form
  corehq/apps/domain/forms.py
Labels: product/invisible

#35040 Fix duplicate web user invite due to case sensitive email matching
  corehq/apps/registration/forms.py
  corehq/apps/registration/tests/test_forms.py
Labels: Risk: High

#35032 Change dimagi urls for commcare/pricing to commcare-pricing
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/urls.py
  settings.py
Labels: product/invisible

#34999 Add `InvalidPayload` status
  corehq/apps/reports/filters/select.py
  corehq/apps/zapier/tests/test_zapier_forwarding.py
  corehq/motech/repeaters/const.py
  corehq/motech/repeaters/migrations/0013_alter_repeatrecord_state_and_more.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/templates/repeaters/partials/repeater_row.html
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/views/repeat_record_display.py
  corehq/motech/repeaters/views/repeaters.py
  corehq/motech/repeaters/views/tests/test_repeat_records.py
  migrations.lock
Labels: reindex/migration, product/invisible

#35034 Drop unused `Repeater.is_ready()`
  corehq/motech/repeaters/models.py
Labels: product/invisible

#35007 RelatedCaseExpression allows UCR case lookups using external_id
  corehq/apps/change_feed/tests/test_data_sources.py
  corehq/apps/userreports/expressions/factory.py
  corehq/apps/userreports/expressions/specs.py
  corehq/apps/userreports/tests/test_expressions.py
  corehq/form_processor/document_stores.py
  corehq/motech/generic_inbound/backend/base.py
  corehq/motech/generic_inbound/tests/test_api_processing.py
  corehq/motech/generic_inbound/utils.py
Labels: product/feature-flag, Risk: High

#35001 Always Store ES Geopoint Value
  corehq/apps/es/tests/test_case_search_es.py
  corehq/pillows/case_search.py
  corehq/util/test_utils.py
  testapps/test_pillowtop/tests/test_case_search_pillow.py
Labels: product/all-users-all-environments, product/invisible

#35039 Update to latest patched versions of mapbox dependency to fix display bug
  package.json
  yarn.lock
Labels: product/invisible, dependencies

#35013 use primary/canonical app id for web apps url param appId
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
Labels: QA Passed, Risk: Medium

#35050 Add can_change_subscription check to SelectPlanView
  corehq/apps/domain/views/accounting.py
Labels: product/invisible

#34975 Make search button sticky
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/cloudcare/partials/query/list.html
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/module.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/menu.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/module.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/query.scss
Labels: awaiting QA, Risk: Medium

#35043 Fixed a deduplication bug for child locations
  corehq/apps/data_interfaces/deduplication.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
Labels: product/invisible

#35029 Disable previously selected location from the location dropdown
  corehq/apps/locations/static/locations/js/widgets.js
  corehq/toggles/__init__.py
Labels: product/all-users-all-environments

#35056 Update comments: ConfigurableAPI is inbound only
  corehq/motech/generic_inbound/models.py
Labels: product/invisible

#35055 add device_id to case transactions for easy access
  corehq/form_processor/models/cases.py
  corehq/form_processor/models/forms.py
  corehq/form_processor/tests/test_basics.py
Labels: product/invisible, Risk: High

#35059 Revert "Make search button sticky"
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/cloudcare/partials/query/list.html
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/module.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/menu.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/module.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/query.scss
Labels: Risk: Medium

#35058 Make enterprise admin match case insensitive
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_models.py
Labels: product/all-users-all-environments

#34718 Improve loading time of Clean Case Data panel
  corehq/apps/export/models/new.py
  corehq/apps/reports/standard/cases/case_data.py
Labels: product/invisible

#35071 Visually Denote Active Persistent Menu Item
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/cloudcare/partials/menu/persistent_menu.html
Labels: Risk: Medium
