Repository dimagi/commcare-hq, pull requests merged in 2024-06, with the labels that each got.

#34641 Remove a bunch of dead code from the case data page
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
  corehq/apps/ota/case_restore.py
  corehq/apps/reports/standard/cases/case_data.py
  corehq/apps/reports/view_helpers.py
  corehq/ex-submodules/casexml/apps/case/templates/case/partials/case_hierarchy.html
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
  corehq/ex-submodules/casexml/apps/case/tests/test_tags.py
  corehq/ex-submodules/casexml/apps/case/views.py
Labels: Risk: Medium

#34712 USH-4599: Add FF for force login check for links
  corehq/apps/cloudcare/views.py
  corehq/toggles/__init__.py
Labels: Risk: Medium

#34707 Fix Pagination for Locked Case Groups
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
Labels: product/feature-flag

#34714 Don't wipe out location in bulk upload when location column is not provided
  corehq/apps/user_importer/importer.py
Labels: Risk: Medium

#34709 Fix Geospatial Marker Popup Checkbox
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/static/geospatial/js/models.js
Labels: product/feature-flag

#34467 USH-4332: Support repeat group using linear layout
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/form_ui_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/templates/cloudcare/partials/bootstrap3/all_templates.html
  corehq/apps/cloudcare/templates/cloudcare/partials/bootstrap5/all_templates.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap3/add_group.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap3/sub_group.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap5/add_group.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap5/sub_group.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/cloudcare/partials/all_templates.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/cloudcare/partials/form_entry/add_group.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/cloudcare/partials/form_entry/sub_group.html.diff.txt
Labels: Risk: Medium

#34722 Fix error on question required changed
  corehq/apps/app_manager/app_schemas/form_metadata.py
  corehq/apps/app_manager/app_schemas/tests/test_app_diffs.py
  corehq/apps/app_manager/xform_builder.py
Labels: product/invisible

#34716 Show algorithm parameters when running disbursement
  corehq/apps/geospatial/models.py
  corehq/apps/geospatial/routing_solvers/pulp.py
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/tests/test_pulp.py
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#34721 Removed erroneous description for the Duplicate Cases report
  corehq/apps/reports/standard/cases/duplicate_cases.py
Labels: product/invisible

#34697 UI improvements for 'App Testing'
  corehq/apps/app_execution/db_accessors.py
  corehq/apps/app_execution/forms.py
  corehq/apps/app_execution/models.py
  corehq/apps/app_execution/static/app_execution/js/workflow_charts.js
  corehq/apps/app_execution/static/app_execution/js/workflow_logs.js
  corehq/apps/app_execution/static/app_execution/js/workflow_timing_chart.js
  corehq/apps/app_execution/templates/app_execution/components/logs.html
  corehq/apps/app_execution/templates/app_execution/workflow_list.html
  corehq/apps/app_execution/templates/app_execution/workflow_log.html
  corehq/apps/app_execution/templates/app_execution/workflow_log_list.html
  corehq/apps/app_execution/templates/app_execution/workflow_test.html
  corehq/apps/app_execution/views.py
  corehq/apps/registry/views.py
  corehq/tabs/tabclasses.py
  corehq/util/view_utils.py
Labels: product/feature-flag

#34708 HELPME: `view_generic()`
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/app_manager/views/view_generic.py
Labels: product/invisible

#34678 Add Tableau Config to Web User Invitation
  corehq/apps/registration/forms.py
  corehq/apps/users/forms.py
  corehq/apps/users/management/commands/accept_invite.py
  corehq/apps/users/templates/users/edit_web_user.html
  corehq/apps/users/views/__init__.py
Labels: QA Passed, Risk: High

#34733 Update software plan visibilities
  corehq/apps/accounting/bootstrap/utils.py
  corehq/apps/accounting/migrations/0095_update_softwareplan_visibilities.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_ensure_plans.py
  migrations.lock
Labels: reindex/migration, product/admin

#34739 Improve lookup table API validation
  corehq/apps/api/resources/__init__.py
  corehq/apps/api/tests/lookup_table_resources.py
  corehq/apps/fixtures/resources/v0_1.py
  corehq/util/validation.py
Labels: product/invisible, Risk: High, Risk: Medium

#34603 Profile Case Search
  corehq/apps/case_search/utils.py
  corehq/apps/case_search/views.py
  corehq/apps/case_search/xpath_functions/ancestor_functions.py
  corehq/apps/case_search/xpath_functions/subcase_functions.py
Labels: product/invisible

#34732 Updated base colors for B5
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
Labels: product/all-users-all-environments

#34371 Couch to SQL Repeat Records PR 3: Cleanup
  corehq/apps/app_manager/tests/test_repeater.py
  corehq/apps/cleanup/deletable_doc_types.py
  corehq/apps/cleanup/management/commands/fire_repeaters.py
  corehq/apps/cleanup/management/commands/templates/populate_command.j2
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/tests/test_utils.py
  corehq/apps/data_interfaces/utils.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/dump_reload/couch/dump.py
  corehq/apps/dump_reload/couch/id_providers.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/hqadmin/corrupt_couch.py
  corehq/apps/reports/standard/cases/case_data.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/zapier/tests/test_zapier_forwarding.py
  corehq/motech/openmrs/views.py
  corehq/motech/repeaters/_design/indexes/search/index.js
  corehq/motech/repeaters/_design/views/repeat_records/map.js
  corehq/motech/repeaters/_design/views/repeat_records/reduce.js
  corehq/motech/repeaters/_design/views/repeat_records_by_next_check/map.js
  corehq/motech/repeaters/_design/views/repeat_records_by_next_check/reduce.js
  corehq/motech/repeaters/_design/views/repeat_records_by_payload_id/map.js
  corehq/motech/repeaters/_design/views/repeaters/map.js
  corehq/motech/repeaters/_design/views/repeaters/reduce.js
  corehq/motech/repeaters/const.py
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/expression/tests.py
  corehq/motech/repeaters/management/commands/create_missing_repeaters.py
  corehq/motech/repeaters/management/commands/delete_duplicate_cancelled_records.py
  corehq/motech/repeaters/management/commands/find_missing_repeat_records.py
  corehq/motech/repeaters/management/commands/generate_repeaters_summary.py
  corehq/motech/repeaters/management/commands/populate_repeatrecords.py
  corehq/motech/repeaters/management/commands/update_cancelled_records.py
  corehq/motech/repeaters/migrations/0008_sqlrepeatrecords.py
  corehq/motech/repeaters/migrations/0010_rm_couch_artifacts.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_couchsqlmigration.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_repeater.py
  corehq/motech/repeaters/tests/test_dbaccessors.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/tests/test_tasks.py
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/repeaters.py
  corehq/motech/repeaters/views/tests/test_repeat_records.py
  corehq/preindex/couchviews.lock
  custom/cowin/tests.py
  migrations.lock
  settings.py
Labels: reindex/migration, QA Passed, product/invisible

#34717 Delete saved area for Case Management and Case Grouping page
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/templates/geospatial/case_grouping_map_base.html
  corehq/apps/geospatial/templates/geospatial/map_visualization_base.html
  corehq/apps/geospatial/templates/geospatial/partials/delete_saved_area_modal.html
  corehq/apps/geospatial/templates/geospatial/partials/saved_polygon_filter.html
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/urls.py
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#34725 Improve report builder preview error handling
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/userreports/views.py
Labels: product/invisible

#34734 Release User Metadata tab
  corehq/apps/app_manager/templates/app_manager/apps_base.html
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases.html
  corehq/apps/export/templates/export/download_data_files.html
  corehq/apps/export/views/utils.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/form/partials/form_breadcrumbs.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/reportdata/case_data.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/reportdata/form_data.html.diff.txt
  corehq/apps/reports/templates/reports/form/partials/bootstrap3/form_breadcrumbs.html
  corehq/apps/reports/templates/reports/form/partials/bootstrap5/form_breadcrumbs.html
  corehq/apps/reports/templates/reports/reportdata/bootstrap3/case_data.html
  corehq/apps/reports/templates/reports/reportdata/bootstrap3/form_data.html
  corehq/apps/reports/templates/reports/reportdata/bootstrap5/case_data.html
  corehq/apps/reports/templates/reports/reportdata/bootstrap5/form_data.html
  corehq/apps/reports/templatetags/timezone_tags.py
  corehq/apps/sms/templates/sms/compose.html
  corehq/apps/sms/templates/sms/subscribe_sms.html
  corehq/apps/toggle_ui/templates/toggle/edit_flag.html
  corehq/apps/toggle_ui/templates/toggle/flags.html
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/motech/generic_inbound/reports.py
  corehq/motech/generic_inbound/templates/generic_inbound/request_log_detail.html
Labels: product/all-users-all-environments

#34727 Rc/role UI assign profiles
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/roles.js
  corehq/apps/users/static/users/js/roles_and_permissions.js
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/apps/users/templates/users/roles_and_permissions.html
  corehq/apps/users/views/__init__.py
  corehq/toggles/__init__.py
Labels: QA Passed

#34705 Profile Permission Restriction UI
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/registration/forms.py
  corehq/apps/users/forms.py
  corehq/apps/users/models.py
  corehq/apps/users/static/users/js/custom_data_fields.js
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/static/users/js/edit_web_user.js
  corehq/apps/users/static/users/js/mobile_workers.js
  corehq/apps/users/templates/users/edit_commcare_user.html
  corehq/apps/users/templates/users/edit_web_user.html
  corehq/apps/users/templates/users/mobile_workers.html
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/custom_data_fields.py
  corehq/apps/users/views/mobile/users.py
Labels: Risk: High, Risk: Medium

#34650 UI and view changes to allow self service annual plan renewals
  corehq/apps/accounting/static/accounting/js/renew_plan_selection.js
  corehq/apps/accounting/templates/accounting/partials/renew_plan_selection.html
  corehq/apps/accounting/tests/generator.py
  corehq/apps/accounting/tests/utils.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/domain/confirm_subscription_renewal.html
  corehq/apps/domain/templates/domain/renew_plan.html
  corehq/apps/domain/tests/test_forms.py
  corehq/apps/domain/tests/test_views.py
  corehq/apps/domain/views/accounting.py
  corehq/toggles/__init__.py
Labels: QA Passed, product/feature-flag

#34755 Remove jquery-migrate
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/file_download.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/file_download.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/file_download.html.diff.txt
  package.json
  yarn.lock
Labels: product/invisible, dependencies

#34683 Updates to self-service renewals functionality
  corehq/apps/accounting/emails.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/test_renew_subscription.py
  corehq/apps/domain/views/accounting.py
Labels: QA Passed, product/feature-flag

#34761 Updates to feature flags page usage display
  corehq/apps/toggle_ui/static/toggle_ui/js/edit-flag.js
  corehq/apps/toggle_ui/templates/toggle/edit_flag.html
  corehq/apps/toggle_ui/views.py
Labels: product/admin

#34764 [B5] Darkened borders
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
Labels: product/all-users-all-environments

#34760 Fix Solutions Feedback/Bug Report Request + Rewording for B5
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/email-request.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/email-request.js
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/modal_solutions_feature_request.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/modal_report_issue.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/modal_solutions_feature_request.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/modal_report_issue.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/modal_solutions_feature_request.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/email-request.js.diff.txt
Labels: product/all-users-all-environments

#34684 [B5] reminders / keywords
  corehq/apps/hqwebapp/utils/bootstrap/status/bootstrap3_to_5.json
  corehq/apps/reminders/forms.py
  corehq/apps/reminders/static/reminders/js/keywords_list.js
  corehq/apps/reminders/static/reminders/js/reminders.keywords.ko.js
  corehq/apps/reminders/templates/reminders/keyword.html
  corehq/apps/reminders/templates/reminders/keyword_list.html
  corehq/apps/reminders/templates/reminders/partials/modal_edit.html
  corehq/apps/reminders/views.py
Labels: QA Passed, product/all-users-all-environments

#34738 override save methods and perform model validation
  corehq/apps/reports/migrations/0017_alter_tableauuser_tableau_user_id.py
  corehq/apps/reports/models.py
  corehq/apps/users/migrations/0069_alter_invitation_custom_user_data_and_more.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_user_invitation.py
  migrations.lock
Labels: reindex/migration

#34700 Refactor Function Naming
  corehq/apps/reports/standard/monitoring.py
Labels: product/all-users-all-environments, product/invisible

#34768 Solutions Feature Request Extra Email Validation
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/email-request.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/email-request.js
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/modal_report_issue.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/modal_solutions_feature_request.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/modal_report_issue.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/modal_solutions_feature_request.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/modal_report_issue.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/modal_solutions_feature_request.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/email-request.js.diff.txt
Labels: product/all-users-all-environments

#34769 [B5] Motech: DHIS2
  corehq/apps/hqwebapp/utils/bootstrap/status/bootstrap3_to_5.json
  corehq/motech/dhis2/forms.py
  corehq/motech/dhis2/static/dhis2/js/dataset_map.js
  corehq/motech/dhis2/static/dhis2/js/dataset_map_create.js
  corehq/motech/dhis2/static/dhis2/js/dataset_map_json.js
  corehq/motech/dhis2/static/dhis2/js/dataset_map_update.js
  corehq/motech/dhis2/static/dhis2/js/dhis2_entity_config.js
  corehq/motech/dhis2/static/dhis2/js/dhis2_events_config.js
  corehq/motech/dhis2/templates/dhis2/dataset_map_create.html
  corehq/motech/dhis2/templates/dhis2/dataset_map_json.html
  corehq/motech/dhis2/templates/dhis2/dataset_map_list.html
  corehq/motech/dhis2/templates/dhis2/dataset_map_update.html
  corehq/motech/dhis2/templates/dhis2/dhis2_entity_config.html
  corehq/motech/dhis2/templates/dhis2/dhis2_events_config.html
  corehq/motech/dhis2/views.py
Labels: product/feature-flag

#34775 Use USERCASE_TYPE const
  corehq/apps/app_manager/util.py
  corehq/apps/domain/calculations.py
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/standard/monitoring.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/messaging/scheduling/tests/test_recipients.py
Labels: product/invisible

#34770 Update _software_plan_name helper
  corehq/apps/accounting/bootstrap/utils.py
  corehq/apps/accounting/tests/test_customer_invoicing.py
Labels: product/invisible

#34782 Remove receiverwrapper from Couch preindex
  corehq/couchapps/__init__.py
Labels: product/invisible

#34750 Adds Export area and Save area functionality to Case Grouping page.
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/templates/geospatial/partials/saved_polygon_filter.html
  corehq/apps/geospatial/templates/map_visualization.html
Labels: QA Passed, product/feature-flag

#34772 Web apps permissions checking: updated get to or
  corehq/apps/cloudcare/tests/test_utils.py
  corehq/apps/cloudcare/utils.py
Labels: Risk: Medium

#34771 Remove self service annual renewals feature flag
  corehq/apps/accounting/models.py
  corehq/apps/accounting/static/accounting/js/renew_plan_selection.js
  corehq/apps/domain/templates/domain/renew_plan.html
  corehq/apps/domain/tests/test_views.py
  corehq/apps/domain/views/accounting.py
  corehq/toggles/__init__.py
Labels: product/all-users-all-environments

#34785 add boolean field has_users
  corehq/apps/locations/migrations/0022_locationtype_has_users.py
  corehq/apps/locations/models.py
  migrations.lock
Labels: reindex/migration

#34788 bump git-build-branch to 0.1.16
  requirements/dev-requirements.txt
Labels: product/invisible, dependencies

#34695 Cs/sc 3593 geo max distance and travel
  corehq/apps/geospatial/const.py
  corehq/apps/geospatial/forms.py
  corehq/apps/geospatial/migrations/0007_geoconfig_max_case_distance_and_more.py
  corehq/apps/geospatial/models.py
  corehq/apps/geospatial/routing_solvers/mapbox_optimize.py
  corehq/apps/geospatial/routing_solvers/mapbox_utils.py
  corehq/apps/geospatial/routing_solvers/pulp.py
  corehq/apps/geospatial/static/geospatial/js/geo_config.js
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/tests/test_mapbox_optimize.py
  corehq/apps/geospatial/tests/test_pulp.py
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/urls.py
  corehq/apps/geospatial/views.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/feature-flag

#34786 Don't include non-numbers in average
  custom/gcc_sangath/rules/custom_actions.py
  custom/gcc_sangath/tests/test_custom_actions.py
Labels: product/invisible

#34743 Reorder case properties for bulk case export
  corehq/apps/export/models/new.py
  corehq/apps/export/tests/test_export_data_schema.py
Labels: QA Passed, product/all-users-all-environments

#34751 Couch to SQL Repeat Records: post-PR-3 migrations
  corehq/motech/repeaters/migrations/0001_adjust_auth_field_format_squashed_0015_drop_connection_settings_fk.py
  corehq/motech/repeaters/migrations/0002_repeaters_db.py
  corehq/motech/repeaters/migrations/0011_remove_obsolete_entities.py
  migrations.lock
Labels: reindex/migration, product/invisible

#34792 Better Algorithm Descriptions for Geospatial Feature
  corehq/apps/geospatial/forms.py
Labels: product/feature-flag

#34797 Add zoom control to geospatial map
  corehq/apps/geospatial/static/geospatial/js/models.js
Labels: product/feature-flag

#34796 Add CCA dataset_editor role on HQ
  corehq/apps/users/views/__init__.py
Labels: product/feature-flag

#34806 Handle paginated response from Entra
  corehq/apps/sso/tasks.py
  corehq/apps/sso/utils/entra.py
  corehq/apps/sso/utils/user_helpers.py
Labels: product/all-users-all-environments

#34799 [docs] Updated style guide selection examples to replace .form-control with …
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/form_valid.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/select2_css_class.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/select2_css_class_multiple.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/select2_ko_autocomplete.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/select2_ko_dynamic.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/select2_ko_static.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/select2_manual.html
Labels: product/admin

#34811 Create release.yml
  .github/release.yml
Labels: product/invisible

#34816 Lower MAX_MOBILE_UCR_SIZE to 100,000
  settings.py
Labels: product/custom

#34818 Preserve max bucket size if limit < 250K
  corehq/apps/app_manager/fixtures/mobile_ucr.py
Labels: product/invisible

#34794 Allow case_search_display and case_search_hint values to be translated in Transifex
  corehq/apps/translations/app_translations/upload_module.py
  corehq/apps/translations/integrations/transifex/parser.py
Labels: product/feature-flag

#34825 [docs] Update B5 migration guide
  corehq/apps/hqwebapp/management/commands/migrate_app_to_bootstrap5.py
  corehq/apps/hqwebapp/tests/utils/test_bootstrap_changes.py
  corehq/apps/hqwebapp/utils/bootstrap/changes.py
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/crispy.md
  corehq/apps/styleguide/templates/styleguide/bootstrap5/migration_guide.html
Labels: product/admin

#34804 Upgrade tornado
  requirements/prod-requirements.txt
Labels: dependencies

#34828 minor version bump for dropbox
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#34805 Remove user data from couch user model
  corehq/apps/api/resources/v0_1.py
  corehq/apps/api/user_updates.py
  corehq/apps/domain_migration_flags/api.py
  corehq/apps/domain_migration_flags/tests/test_domain_migration_progress.py
  corehq/apps/geospatial/views.py
  corehq/apps/user_importer/helpers.py
  corehq/apps/userreports/expressions/specs.py
  corehq/apps/userreports/tests/test_expressions.py
  corehq/apps/users/management/commands/populate_sql_user_data.py
  corehq/apps/users/management/commands/rm_couch_user_data.py
  corehq/apps/users/migrations/0057_populate_sql_user_data.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_log_user_change.py
  corehq/apps/users/tests/test_user_data.py
  corehq/apps/users/util.py
  corehq/dbaccessors/couchapps/all_docs.py
  custom/champ/tests/test_champ_cameroon.py
  custom/champ/tests/test_enhanced_peer_mobilization.py
Labels: reindex/migration, Risk: High, Risk: Medium

#34835 Only specify path tor new property in migration
  corehq/apps/es/migrations/0013_add_formLoadTime_to_form_meta.py
Labels: reindex/migration

#34822 QA-6732: Add type button
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap3/entry_button.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap3/entry_file.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap3/entry_geo.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap3/entry_select.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap3/entry_signature.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap3/sub_group.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap5/entry_button.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap5/entry_file.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap5/entry_geo.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap5/entry_select.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap5/entry_signature.html
  corehq/apps/cloudcare/templates/cloudcare/partials/form_entry/bootstrap5/sub_group.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/cloudcare/partials/form_entry/entry_button.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/cloudcare/partials/form_entry/entry_file.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/cloudcare/partials/form_entry/entry_geo.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/cloudcare/partials/form_entry/entry_select.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/cloudcare/partials/form_entry/entry_signature.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/cloudcare/partials/form_entry/sub_group.html.diff.txt
Labels: Risk: Medium
