Repository dimagi/commcare-hq, pull requests merged in 2024-12, with the labels that each got.

#35419 Add HTMX loading styles and related documentation in styleguide
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_htmx.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/style-imports.commcarehq.style.diff.txt
  corehq/apps/styleguide/context.py
  corehq/apps/styleguide/examples/bootstrap5/htmx_alpine_form_demo.py
  corehq/apps/styleguide/templates/styleguide/bootstrap5/base.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/code_display.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/htmx_loading_button.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/htmx_loading_checkbox.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/htmx_loading_form.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/htmx_and_alpine.html
  corehq/apps/styleguide/templates/styleguide/htmx_todo/item.html
  corehq/apps/styleguide/urls.py
  corehq/apps/styleguide/views/bootstrap5.py
  corehq/apps/styleguide/views/bootstrap5_data.py
Labels: product/invisible

#35444 [WebApps] Update localStorage when user changes session language
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
Labels: Risk: Medium

#35456 Upgrade Tornado from 6.4.1 to 6.4.2
  requirements/prod-requirements.txt
Labels: dependencies

#35378 mark multimedia export as location safe
  corehq/apps/export/views/download.py
Labels: QA Passed, product/prod-india-all-users

#35421 Pytest improvements and cleanup
  corehq/tests/pytest_plugins/reusedb.py
  corehq/tests/test_middleware.py
  corehq/tests/test_reusedb.py
  custom/abt/reports/tests/test_flagspecs.py
  custom/inddex/tests/test_doctests.py
  custom/inddex/tests/test_master_report.py
Labels: product/invisible

#35459 [B5] Project Limits view migration
  corehq/apps/domain/templates/domain/admin/bootstrap3/project_limits.html
  corehq/apps/domain/templates/domain/admin/partials/bootstrap5/project_limits_table.html
  corehq/apps/domain/templates/domain/admin/project_limits.html
  corehq/apps/domain/views/internal.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/partials/project_limits_table.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/project_limits.html.diff.txt
  corehq/apps/hqwebapp/utils/bootstrap/status/bootstrap3_to_5.json
Labels: product/admin

#35400 Added security watchtower page
  corehq/apps/enterprise/static/enterprise/js/project_dashboard.js
  corehq/apps/enterprise/templates/enterprise/enterprise_dashboard.html
  corehq/apps/enterprise/templates/enterprise/partials/project_tile.html
  corehq/apps/enterprise/templates/enterprise/project_dashboard.html
  corehq/apps/enterprise/urls.py
  corehq/apps/enterprise/views.py
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/global_navigation_bar.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/global_navigation_bar.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/global_navigation_bar.html.diff.txt
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#35475 Add pmievolve-kenya to other domains
  custom/abt/reports/data_sources/late_pmt.json
  custom/abt/reports/data_sources/sms_case.json
  custom/abt/reports/data_sources/supervisory_v2020.json
  custom/abt/reports/sms_indicator_report.json
  custom/abt/reports/spray_progress_country.json
  custom/abt/reports/spray_progress_level_1.json
  custom/abt/reports/spray_progress_level_2.json
  custom/abt/reports/spray_progress_level_3.json
  custom/abt/reports/spray_progress_level_4.json
  custom/abt/reports/supervisory_report_v2020.json
  settings.py
Labels: product/custom, product/invisible

#35426 Add row limit to lookup table uploads
  corehq/apps/fixtures/exceptions.py
  corehq/apps/fixtures/upload/const.py
  corehq/apps/fixtures/upload/workbook.py
  corehq/util/workbook_json/const.py
  corehq/util/workbook_json/excel.py
  corehq/util/workbook_json/excel_importer.py
  corehq/util/workbook_json/exceptions.py
Labels: Risk: Medium

#35437 Add Enterprise SMS Report
  corehq/apps/enterprise/api/api.py
  corehq/apps/enterprise/api/resources.py
  corehq/apps/enterprise/enterprise.py
  corehq/apps/enterprise/static/enterprise/js/project_dashboard.js
  corehq/apps/enterprise/templates/enterprise/partials/project_tile.html
  corehq/apps/enterprise/views.py
Labels: product/admin

#35448 Create Invitation API [Validation]
  corehq/apps/api/tests/test_validation.py
  corehq/apps/api/validation.py
  corehq/apps/custom_data_fields/models.py
  corehq/apps/registration/forms.py
  corehq/apps/registration/tests/test_forms.py
  corehq/apps/registration/validation.py
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/user_importer/tests/test_validators.py
  corehq/apps/user_importer/validation.py
  corehq/apps/users/forms.py
  corehq/apps/users/tests/test_user_invitation.py
  corehq/apps/users/tests/test_views.py
  corehq/apps/users/validation.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
  corehq/apps/users/views/web.py
Labels: Risk: High, Risk: Medium

#35485 check toggle in other places where user reporting metadata is processed
  corehq/ex-submodules/pillowtop/processors/form.py
  corehq/pillows/synclog.py
  corehq/toggles/__init__.py
Labels: product/invisible

#35487 Remove polynomial regexps
  corehq/apps/commtrack/util.py
  corehq/apps/registration/forms.py
  corehq/apps/users/views/mobile/users.py
Labels: Risk: High

#35454 [B5] Commtrack SMS settings action table
  corehq/apps/commtrack/static/commtrack/js/sms.js
  corehq/apps/domain/templates/domain/admin/bootstrap3/commtrack_action_table.html
  corehq/apps/domain/templates/domain/admin/bootstrap5/commtrack_action_table.html
  corehq/apps/domain/templates/domain/admin/partials/commtrack_action_table.html
  corehq/apps/domain/templates/domain/admin/sms_settings.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/commtrack_action_table.html.diff.txt
  corehq/apps/hqwebapp/utils/bootstrap/status/bootstrap3_to_5.json
Labels: product/feature-flag

#35480 Allow enterprise console to handle percent summary data
  corehq/apps/enterprise/static/enterprise/js/project_dashboard.js
Labels: product/admin

#35490 Bump django from 4.2.16 to 4.2.17
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#35493 Silence export poll error
  corehq/apps/export/static/export/js/download_export.js
  corehq/apps/export/views/download.py
Labels: product/invisible

#35415 Create DomainMetrics SQL table
  corehq/apps/data_analytics/migrations/0011_domainmetrics.py
  corehq/apps/data_analytics/models.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  migrations.lock
Labels: reindex/migration

#35471 Encrypt API Key
  corehq/apps/api/odata/tests/utils.py
  corehq/apps/api/tests/core_api.py
  corehq/apps/api/tests/test_auth.py
  corehq/apps/api/tests/utils.py
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/domain/tests/test_api_key_auth.py
  corehq/apps/enterprise/tests/test_permissions.py
  corehq/apps/linked_domain/tests/test_linked_case_claim.py
  corehq/apps/linked_domain/tests/test_remote_auth.py
  corehq/apps/locations/tests/test_views.py
  corehq/apps/settings/views.py
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/users/migrations/0075_hqapikey_encrypted_key.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_views.py
  corehq/apps/zapier/tests/test_create_update_cases_from_zapier.py
  corehq/apps/zapier/tests/test_utils.py
  corehq/motech/generic_inbound/tests/test_api.py
  migrations.lock
Labels: reindex/migration, Risk: High

#35440 Add Prettier script and pre-commit check for HTML and stylesheets
  .prettierrc
  git-hooks/pre-commit.sh
  package.json
  scripts/prettify-changed.sh
  yarn.lock
Labels: dependencies

#35488 Show metric description in Enterprise Console
  corehq/apps/enterprise/enterprise.py
  corehq/apps/enterprise/templates/enterprise/partials/date_range_modal.html
  corehq/apps/enterprise/templates/enterprise/partials/project_tile.html
  corehq/apps/enterprise/templates/enterprise/project_dashboard.html
  corehq/apps/enterprise/tests/test_enterprise.py
Labels: product/all-users-all-environments

#35499 Enterprise Date Range Tiles do not display for translated languages
  corehq/apps/enterprise/static/enterprise/js/project_dashboard.js
  corehq/apps/enterprise/templates/enterprise/partials/project_tile.html
  corehq/apps/enterprise/templates/enterprise/project_dashboard.html
  corehq/apps/enterprise/views.py
Labels: product/invisible

#35500 Moved UCR base template into UCR app
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports_core/js/base_template_new.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports_core/base_template_new.html.diff.txt
  corehq/apps/reports_core/static/reports_core/js/bootstrap5/base_template_new.js
  corehq/apps/reports_core/templates/reports_core/bootstrap5/base_template_new.html
  corehq/apps/userreports/static/userreports/js/base.js
  corehq/apps/userreports/templates/userreports/base.html
  corehq/apps/userreports/templates/userreports/base_report_builder.html
  corehq/apps/userreports/templates/userreports/configurable_report.html
Labels: product/invisible

#35508 Removed punchcard.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/partials/punchcard.html.diff.txt
  corehq/apps/reports/templates/reports/partials/bootstrap3/punchcard.html
  corehq/apps/reports/templates/reports/partials/bootstrap5/punchcard.html
Labels: product/invisible

#35507 Removed ckeditor5
  corehq/apps/hqwebapp/static/hqwebapp/js/ckeditor_knockout_bindings.js
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.js
  corehq/messaging/scheduling/templates/scheduling/conditional_alert.html
  corehq/messaging/scheduling/templates/scheduling/create_schedule.html
  corehq/messaging/scheduling/templates/scheduling/partials/rich_text_message_configuration.html
  corehq/messaging/scheduling/templates/scheduling/rich_text_email_styles.css
  package.json
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  yarn.lock
Labels: product/feature-flag, dependencies

#35504 Simplify hqadmin views by removing hqadmin_base_report.html
  corehq/apps/hqadmin/static/hqadmin/js/mass_email.js
  corehq/apps/hqadmin/templates/hqadmin/disable_two_factor.html
  corehq/apps/hqadmin/templates/hqadmin/disable_user.html
  corehq/apps/hqadmin/templates/hqadmin/global_thresholds.html
  corehq/apps/hqadmin/templates/hqadmin/hqadmin_base_report.html
  corehq/apps/hqadmin/templates/hqadmin/mass_email.html
  corehq/apps/hqadmin/templates/hqadmin/messaging_case_updates.html
  corehq/apps/hqadmin/templates/hqadmin/system_info.html
  corehq/apps/hqadmin/views/__init__.py
  corehq/apps/hqadmin/views/operations.py
  corehq/apps/hqadmin/views/system.py
  corehq/apps/hqadmin/views/users.py
  corehq/apps/hqadmin/views/utils.py
Labels: product/invisible

#35501 Removed redundant script tags from ucr_expression.html
  corehq/apps/userreports/templates/userreports/ucr_expression.html
Labels: product/invisible

#35296 Move location fields out of user data
  corehq/apps/api/resources/v0_1.py
  corehq/apps/callcenter/sync_usercase.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/userreports/expressions/specs.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_location_assignment.py
  corehq/apps/users/tests/test_user_data.py
  corehq/apps/users/user_data.py
  corehq/ex-submodules/casexml/apps/phone/tests/dummy.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_restore_user.py
Labels: Risk: High, Risk: Medium

#35517 Fixed js_entry tag on B5 page
  corehq/apps/domain/templates/domain/admin/bootstrap5/flags_and_privileges.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/flags_and_privileges.html.diff.txt
Labels: product/invisible

#35518 Added dependencies for fadeVisible
  corehq/apps/commtrack/static/commtrack/js/products_and_programs_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/crud_paginated_list.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/crud_paginated_list.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/crud_paginated_list.js.diff.txt
  corehq/apps/locations/static/locations/js/location_tree.js
Labels: product/all-users-all-environments

#35513 Rename a few reports js files
  corehq/apps/export/static/export/js/download_export.js
  corehq/apps/fixtures/static/fixtures/js/view-table.js
  corehq/apps/hqadmin/static/hqadmin/js/hqadmin_base_report.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/async.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/datatables_config.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/maps_utils.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/standard_hq_report.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/tabular.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/standard/base_template.html.diff.txt
  corehq/apps/reports/generic.py
  corehq/apps/reports/static/reports/js/bootstrap3/async.js
  corehq/apps/reports/static/reports/js/bootstrap3/datatables_config.js
  corehq/apps/reports/static/reports/js/bootstrap3/maps_utils.js
  corehq/apps/reports/static/reports/js/bootstrap3/standard_hq_report.js
  corehq/apps/reports/static/reports/js/bootstrap3/tabular.js
  corehq/apps/reports/static/reports/js/bootstrap5/async.js
  corehq/apps/reports/static/reports/js/bootstrap5/datatables_config.js
  corehq/apps/reports/static/reports/js/bootstrap5/maps_utils.js
  corehq/apps/reports/static/reports/js/bootstrap5/standard_hq_report.js
  corehq/apps/reports/static/reports/js/bootstrap5/tabular.js
  corehq/apps/reports/static/reports/js/util.js
  corehq/apps/reports/templates/reports/standard/bootstrap3/base_template.html
  corehq/apps/reports/templates/reports/standard/bootstrap5/base_template.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/organisms/tables.html
  corehq/apps/toggle_ui/static/toggle_ui/js/flags.js
  corehq/apps/userreports/static/userreports/js/base.js
  corehq/apps/userreports/static/userreports/js/configurable_report.js
  corehq/apps/userreports/templates/userreports/base.html
  corehq/apps/userreports/templates/userreports/configurable_report.html
  custom/inddex/templates/inddex/partials/report_table.html
Labels: product/invisible, Risk: Medium

#35510 [webpack] UCR config pages
  corehq/apps/hqwebapp/static/hqwebapp/js/base_ace.js
  corehq/apps/userreports/static/userreports/js/configurable_reports_home.js
  corehq/apps/userreports/static/userreports/js/data_source_evaluator.js
  corehq/apps/userreports/static/userreports/js/data_source_from_app.js
  corehq/apps/userreports/static/userreports/js/data_source_select_model.js
  corehq/apps/userreports/static/userreports/js/edit_report_config.js
  corehq/apps/userreports/static/userreports/js/expression_debugger.js
  corehq/apps/userreports/static/userreports/js/expression_evaluator.js
  corehq/apps/userreports/static/userreports/js/widgets.js
  corehq/apps/userreports/templates/userreports/configurable_reports_home.html
  corehq/apps/userreports/templates/userreports/data_source_debugger.html
  corehq/apps/userreports/templates/userreports/data_source_from_app.html
  corehq/apps/userreports/templates/userreports/edit_data_source.html
  corehq/apps/userreports/templates/userreports/edit_report_config.html
  corehq/apps/userreports/templates/userreports/expression_debugger.html
  corehq/apps/userreports/templates/userreports/userreports_base.html
Labels: product/invisible

#35468 Add Enterprise CommCare Client Version Compliance Report
  corehq/apps/builds/tests/test_utils.py
  corehq/apps/builds/utils.py
  corehq/apps/enterprise/api/api.py
  corehq/apps/enterprise/api/resources.py
  corehq/apps/enterprise/enterprise.py
  corehq/apps/enterprise/static/enterprise/js/project_dashboard.js
  corehq/apps/enterprise/templates/enterprise/partials/project_tile.html
  corehq/apps/enterprise/templates/enterprise/project_dashboard.html
  corehq/apps/enterprise/views.py
  corehq/apps/reports/standard/deployments.py
  corehq/apps/reports/util.py
Labels: product/all-users-all-environments

#35446 Stale Case Data Mail Report
  corehq/apps/hqadmin/reports.py
  corehq/apps/hqadmin/tests/test_reports.py
  corehq/apps/hqwebapp/tasks.py
Labels: product/invisible

#35516 Optmise Disbursement layers on map
  corehq/apps/geospatial/static/geospatial/js/case_management.js
  corehq/apps/geospatial/static/geospatial/js/models.js
Labels: product/feature-flag, product/invisible

#35502 Updated geospatial reports to pull turf from NPM
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/standard/base_template.html.diff.txt
  corehq/apps/reports/templates/reports/standard/bootstrap3/base_template.html
  corehq/apps/reports/templates/reports/standard/bootstrap5/base_template.html
  package.json
  yarn.lock
Labels: product/invisible, dependencies

#35528 Small bug fix for Enterprise CommCare Version Compliance
  corehq/apps/reports/util.py
Labels: product/all-users-all-environments

#35496 UCR metrics using Datadog for Rebuild and Rebuild-in-place functionality
  corehq/apps/userreports/const.py
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/ui/forms.py
  corehq/apps/userreports/util.py
  corehq/apps/userreports/views.py
Labels: product/feature-flag, product/invisible

#35495 Add HTML Style Guide
  corehq/apps/styleguide/context.py
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/attribute_js.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/attribute_json.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/attribute_no_wrap.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/attribute_wrap_data.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/attribute_wrap_length.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/block_and_inline.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/final_example.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/indentation.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/self_closing.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/self_closing_line.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/examples/html_guide/standard_attributes.html
  corehq/apps/styleguide/templates/styleguide/bootstrap5/html_guide.html
  corehq/apps/styleguide/urls.py
  corehq/apps/styleguide/views/bootstrap5.py
Labels: product/all-users-all-environments

#35531 Remove enterprise dashboard improvements toggle
  corehq/apps/enterprise/views.py
  corehq/tabs/tabclasses.py
  corehq/toggles/__init__.py
Labels: product/all-users-all-environments

#35537 Change project_space to domain in CommCareVersionComplianceResource
  corehq/apps/enterprise/api/resources.py
Labels: product/all-users-all-environments

#35536 [B5] Internal project pages
  corehq/apps/domain/static/domain/js/internal_calculations.js
  corehq/apps/domain/templates/domain/activate_transfer_domain.html
  corehq/apps/domain/templates/domain/admin/bootstrap3/flags_and_privileges.html
  corehq/apps/domain/templates/domain/admin/bootstrap3/transfer_domain.html
  corehq/apps/domain/templates/domain/admin/bootstrap3/transfer_domain_pending.html
  corehq/apps/domain/templates/domain/admin/bootstrap5/transfer_domain.html
  corehq/apps/domain/templates/domain/admin/flags_and_privileges.html
  corehq/apps/domain/templates/domain/admin/transfer_domain.html
  corehq/apps/domain/templates/domain/admin/transfer_domain_pending.html
  corehq/apps/domain/templates/domain/bootstrap3/activate_transfer_domain.html
  corehq/apps/domain/templates/domain/bootstrap3/internal_calculations.html
  corehq/apps/domain/templates/domain/internal_calculations.html
  corehq/apps/domain/views/__init__.py
  corehq/apps/domain/views/internal.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/activate_transfer_domain.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/flags_and_privileges.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/transfer_domain.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/transfer_domain_pending.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/internal_calculations.html.diff.txt
  corehq/apps/hqwebapp/utils/bootstrap/status/bootstrap3_to_5.json
Labels: product/admin

#35532 Enterprise API Usage Report
  corehq/apps/enterprise/api/api.py
  corehq/apps/enterprise/api/resources.py
  corehq/apps/enterprise/enterprise.py
  corehq/apps/enterprise/views.py
Labels: product/all-users-all-environments

#35539 Pad version with zero if shorter than 3
  corehq/apps/builds/tests/test_utils.py
  corehq/apps/builds/utils.py
Labels: product/all-users-all-environments

#35541 Update sphinx-rtd-theme to 3.0.2
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
Labels: dependencies

#35544 Update packaging from v23 to v24.2
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#35547 Ported empty payload fix to B5
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/repeaters/js/repeat_record_report.js.diff.txt
  corehq/motech/repeaters/static/repeaters/js/bootstrap5/repeat_record_report.js
Labels: product/invisible

#35550 [B5] Project Admin Settings
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/domain/admin/bootstrap3/edit_alert.html
  corehq/apps/domain/templates/domain/admin/bootstrap3/feature_previews.html
  corehq/apps/domain/templates/domain/admin/bootstrap3/location_fixture.html
  corehq/apps/domain/templates/domain/admin/bootstrap3/sms_rates.html
  corehq/apps/domain/templates/domain/admin/bootstrap5/global_sms_rates.html
  corehq/apps/domain/templates/domain/admin/bootstrap5/info_basic.html
  corehq/apps/domain/templates/domain/admin/bootstrap5/location_fixture.html
  corehq/apps/domain/templates/domain/admin/bootstrap5/manage_alerts.html
  corehq/apps/domain/templates/domain/admin/bootstrap5/my_project_settings.html
  corehq/apps/domain/templates/domain/admin/bootstrap5/recovery_measures_history.html
  corehq/apps/domain/templates/domain/admin/bootstrap5/sms_rates.html
  corehq/apps/domain/templates/domain/admin/edit_alert.html
  corehq/apps/domain/templates/domain/admin/feature_previews.html
  corehq/apps/domain/templates/domain/admin/global_sms_rates.html
  corehq/apps/domain/templates/domain/admin/info_basic.html
  corehq/apps/domain/templates/domain/admin/location_fixture.html
  corehq/apps/domain/templates/domain/admin/manage_alerts.html
  corehq/apps/domain/templates/domain/admin/my_project_settings.html
  corehq/apps/domain/templates/domain/admin/project_privacy.html
  corehq/apps/domain/templates/domain/admin/recovery_measures_history.html
  corehq/apps/domain/templates/domain/admin/sms_rates.html
  corehq/apps/domain/views/fixtures.py
  corehq/apps/domain/views/settings.py
  corehq/apps/domain/views/sms.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/edit_alert.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/feature_previews.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/global_sms_rates.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/info_basic.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/location_fixture.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/manage_alerts.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/my_project_settings.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/project_privacy.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/recovery_measures_history.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/admin/sms_rates.html.diff.txt
  corehq/apps/hqwebapp/utils/bootstrap/status/bootstrap3_to_5.json
Labels: product/admin

#35538 Allow WebUser invites to be editable before the invited user accepts it
  corehq/apps/registration/forms.py
  corehq/apps/registration/validation.py
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/custom_data_fields.js
  corehq/apps/users/static/users/js/invite_web_user.js
  corehq/apps/users/static/users/js/web_users.js
  corehq/apps/users/templates/users/invite_web_user.html
  corehq/apps/users/templates/users/web_users.html
  corehq/apps/users/urls.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/custom_data_fields.py
  corehq/tabs/tabclasses.py
Labels: QA Passed, product/all-users-all-environments, Risk: High

#35553 Revert "Allow WebUser invites to be editable before the invited user accepts it"
  corehq/apps/registration/forms.py
  corehq/apps/registration/validation.py
  corehq/apps/users/forms.py
  corehq/apps/users/static/users/js/custom_data_fields.js
  corehq/apps/users/static/users/js/invite_web_user.js
  corehq/apps/users/static/users/js/web_users.js
  corehq/apps/users/templates/users/invite_web_user.html
  corehq/apps/users/templates/users/web_users.html
  corehq/apps/users/urls.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/custom_data_fields.py
  corehq/tabs/tabclasses.py
Labels: Risk: High

#35527 Extract DateTime logic
  corehq/apps/reports/util.py
  corehq/ex-submodules/dimagi/ext/jsonobject.py
  corehq/ex-submodules/dimagi/ext/tests/test_jsonobject.py
Labels: product/invisible
