Repository dimagi/commcare-hq, pull requests merged in 2024-02, with the labels that each got.

#34069 Fixed lint errors in accounting
  corehq/apps/accounting/static/accounting/js/payment_method_handler.js
  corehq/apps/accounting/static/accounting/js/software_plan_version_handler.js
  corehq/apps/accounting/static/accounting/js/stripe_card_manager.js
Labels: product/invisible

#34059 Fixed lint errors in domain app
  corehq/apps/domain/static/domain/js/commtrack_settings.js
  corehq/apps/domain/static/domain/js/internal_calculations.js
Labels: product/invisible

#34058 Fixed lint errors in analytics
  corehq/apps/analytics/static/analytix/js/drift.js
  corehq/apps/analytics/static/analytix/js/google.js
  corehq/apps/analytics/static/analytix/js/hubspot.js
  corehq/apps/analytics/static/analytix/js/logging.js
  corehq/apps/analytics/static/analytix/js/utils.js
Labels: product/invisible

#34067 Fixed lint errors in hqadmin
  corehq/apps/hqadmin/static/hqadmin/js/admin_restore.js
  corehq/apps/hqadmin/static/hqadmin/js/system_info.js
Labels: product/invisible

#34068 Fixed lint errors
  corehq/apps/app_manager/static/app_manager/js/manage_releases_by_app_profile.js
  corehq/apps/builds/static/builds/js/edit-builds.js
  corehq/apps/registry/static/registry/js/registry_edit.js
  corehq/apps/settings/static/settings/js/edit_my_account.js
  corehq/apps/settings/static/settings/js/user_api_keys.js
  corehq/apps/userreports/static/userreports/js/expression_debugger.js
  corehq/apps/userreports/static/userreports/js/ucr_expression.js
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/static/users/js/invite_web_user.js
  corehq/apps/users/static/users/js/mobile_workers.js
Labels: product/invisible

#34074 Little bit more lint
  corehq/apps/app_manager/static/app_manager/js/forms/copy_form_to_app.js
  corehq/apps/app_manager/static/app_manager/js/forms/custom_instances.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_workflow.js
  corehq/apps/app_manager/static/app_manager/js/modules/case_list_setting.js
  corehq/apps/app_manager/static/app_manager/js/modules/report_module.js
  corehq/apps/app_manager/static/app_manager/js/modules/shadow_module_settings.js
  corehq/apps/app_manager/static/app_manager/js/multimedia_size_util.js
  corehq/apps/app_manager/static/app_manager/js/nav_menu_media.js
  corehq/apps/app_manager/static/app_manager/js/nav_menu_media_common.js
  corehq/apps/app_manager/static/app_manager/js/preview_app.js
  corehq/apps/app_manager/static/app_manager/js/releases/app_diff.js
  corehq/apps/app_manager/static/app_manager/js/releases/app_view_release_manager.js
  corehq/apps/app_manager/static/app_manager/js/releases/language_profiles.js
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/static/app_manager/js/settings/app_logos.js
  corehq/apps/app_manager/static/app_manager/js/settings/password_setter.jquery.js
  corehq/apps/app_manager/static/app_manager/js/source_files.js
  corehq/apps/app_manager/static/app_manager/js/summary/form_models.js
  corehq/apps/app_manager/static/app_manager/spec/releases_spec.js
  corehq/apps/commtrack/static/commtrack/js/base_list_view_model.js
  corehq/apps/dashboard/static/dashboard/js/dashboard.js
  corehq/apps/data_interfaces/static/data_interfaces/js/archive_forms.js
  corehq/apps/events/static/events/js/new_event.js
  corehq/apps/export/static/export/js/create_export.js
  corehq/apps/sso/static/sso/js/models.js
  corehq/apps/toggle_ui/static/toggle_ui/js/edit-flag.js
  corehq/apps/toggle_ui/static/toggle_ui/js/flags.js
  corehq/apps/userreports/static/userreports/js/configurable_report.js
  corehq/apps/userreports/static/userreports/js/configure_report.js
  corehq/apps/userreports/static/userreports/js/data_source_evaluator.js
  corehq/apps/userreports/static/userreports/js/expression_debugger.js
  corehq/apps/userreports/static/userreports/js/expression_evaluator.js
  corehq/apps/userreports/static/userreports/js/report_analytix.js
  corehq/apps/userreports/static/userreports/js/report_config.js
  corehq/apps/userreports/static/userreports/js/ucr_expression.js
Labels: product/invisible

#34061 display error to user if form can't be found and user tries to edit UCR
  corehq/apps/userreports/const.py
  corehq/apps/userreports/views.py
Labels: product/all-users-all-environments

#34078 Fixed many lint errors in reports
  corehq/apps/reports/static/reports/js/aggregate_user_status.js
  corehq/apps/reports/static/reports/js/base.js
  corehq/apps/reports/static/reports/js/case_details.js
  corehq/apps/reports/static/reports/js/charts/main.js
  corehq/apps/reports/static/reports/js/config.dataTables.bootstrap.js
  corehq/apps/reports/static/reports/js/data_corrections.js
  corehq/apps/reports/static/reports/js/edit_scheduled_report.js
  corehq/apps/reports/static/reports/js/filters/case_list_explorer.js
  corehq/apps/reports/static/reports/js/filters/main.js
  corehq/apps/reports/static/reports/js/inspect_data.js
  corehq/apps/reports/static/reports/js/maps_utils.js
  corehq/apps/reports/static/reports/js/project_health_dashboard.js
  corehq/apps/reports/static/reports/js/report_config_models.js
  corehq/apps/reports/static/reports/js/reports.async.js
  corehq/apps/reports/static/reports/js/single_form.js
  corehq/apps/reports/static/reports/v2/js/datagrid.js
  corehq/apps/reports/static/reports/v2/js/datagrid/binding_handlers.js
  corehq/apps/reports/static/reports/v2/js/datagrid/columns.js
  corehq/apps/reports/static/reports/v2/js/datagrid/data_models.js
Labels: product/invisible

#34073 Fix Delete Case Type/Prop Errors for Data Dictionary
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/tests/test_view.py
  corehq/apps/data_dictionary/views.py
Labels: product/all-users-all-environments

#34080 Remove get_by_natural_key methods
  corehq/apps/dump_reload/tests/test_sql_data_loader.py
  corehq/blobs/models.py
  corehq/form_processor/models/cases.py
  corehq/form_processor/models/forms.py
  corehq/form_processor/models/ledgers.py
Labels: Risk: High

#34071 Check for multi-select indicator id instead of recreating it
  corehq/apps/userreports/reports/builder/forms.py
Labels: product/all-users-all-environments

#34052 Removes deprecated custom domain banners feature flag
  corehq/apps/accounting/migrations/0091_remove_custom_banner_alerts_feature_flag.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, product/invisible

#34085 Change Case Property Delete Button
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/templates/data_dictionary/partials/confirmation_modals.html
  corehq/apps/hqwebapp/static/data_dictionary/less/data_dictionary.less
Labels: product/all-users-all-environments

#34039 Various alignment fixes for forms
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/bootstrap5-temp.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style-imports.less
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/style-imports.commcarehq.style.diff.txt
Labels: Risk: Medium

#34035 Remove progres bar while processing file validation request
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
Labels: Risk: Medium

#34089 Remove address popup column from detail tile
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
Labels: Risk: Medium

#34087 Create Case Micro Image FF
  corehq/toggles/__init__.py
Labels: product/feature-flag

#34100 Revert "SSCS: Disabling submit button until changes are made to fields"
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
Labels: Risk: Medium

#34088 Upgrade js-xpath
  package.json
  yarn.lock
Labels: dependencies

#34104 Upgrade pytz to 2024.1
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#34026 Solutions Feature Request Report
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/base_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/email-request.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/hq-bug-report.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/base_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/email-request.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/hq-bug-report.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/global_navigation_bar.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/modal_report_issue.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/modal_solutions_feature_request.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/global_navigation_bar.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/modal_solutions_feature_request.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/global_navigation_bar.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/modal_report_issue.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/modal_solutions_feature_request.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/base_main.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/email-request.js.diff.txt
  corehq/apps/hqwebapp/tests/test_views.py
  corehq/apps/hqwebapp/urls.py
  corehq/apps/hqwebapp/views.py
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#34079 Add a second save buttom at the bottom of feature flag toggle page
  corehq/apps/toggle_ui/static/toggle_ui/js/edit-flag.js
  corehq/apps/toggle_ui/templates/toggle/edit_flag.html
Labels: product/invisible

#34115 Add SSO_REMOTE_USER_MANAGEMENT toggle
  corehq/toggles/__init__.py
Labels: product/all-users-all-environments

#34046 Generate user link with additional parameter
  corehq/apps/reports/standard/monitoring.py
Labels: QA Passed, product/prod-india-all-users

#34108 Initialize indices for fresh ES 5 envs and tests
  corehq/apps/es/mappings/user_mapping.py
  corehq/apps/es/migration_operations.py
  corehq/apps/es/migrations/0001_bootstrap_es_indexes.py
  corehq/apps/es/migrations/0007_init_indices_for_fresh_es_5.py
  corehq/apps/es/tests/test_migration_operations.py
  migrations.lock
Labels: reindex/migration

#34092 Delete Case Types and Properties in Data Dictionary V2
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/templates/data_dictionary/partials/confirmation_modals.html
  corehq/apps/data_dictionary/tests/test_util.py
  corehq/apps/data_dictionary/tests/test_view.py
  corehq/apps/data_dictionary/urls.py
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
  corehq/apps/hqwebapp/static/data_dictionary/less/data_dictionary.less
Labels: QA Passed, product/all-users-all-environments

#34094 Add `doc_id` to all index mappings root
  corehq/apps/api/tests/test_es.py
  corehq/apps/es/client.py
  corehq/apps/es/mappings/app_mapping.py
  corehq/apps/es/mappings/case_mapping.py
  corehq/apps/es/mappings/case_search_mapping.py
  corehq/apps/es/mappings/domain_mapping.py
  corehq/apps/es/mappings/group_mapping.py
  corehq/apps/es/mappings/sms_mapping.py
  corehq/apps/es/mappings/user_mapping.py
  corehq/apps/es/mappings/xform_mapping.py
  corehq/apps/es/migrations/0008_add_doc_id_to_all_mappings.py
  corehq/apps/es/tests/test_esquery.py
  migrations.lock
  testapps/test_pillowtop/tests/test_sms_pillow.py
Labels: reindex/migration, Risk: High

#34057 Excludes copied cases from the dedeuplication report
  corehq/apps/data_interfaces/deduplication.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/apps/hqcase/tests/test_utils.py
  corehq/apps/hqcase/utils.py
Labels: QA Passed, product/feature-flag

#34000 [FF] Support .geojson exports on Case Export page
  corehq/apps/export/export.py
  corehq/apps/export/models/new.py
  corehq/apps/export/static/export/js/const.js
  corehq/apps/export/static/export/js/customize_export_new.js
  corehq/apps/export/static/export/js/models.js
  corehq/apps/export/templates/export/customize_export_new.html
  corehq/apps/export/templates/export/partials/new_customize_export_templates.html
  corehq/apps/export/views/new.py
  corehq/ex-submodules/couchexport/export.py
  corehq/ex-submodules/couchexport/models.py
  corehq/ex-submodules/couchexport/tests/test_writers.py
  corehq/ex-submodules/couchexport/writers.py
  corehq/toggles/__init__.py
Labels: QA Passed, product/feature-flag

#34122 Do not store config_id and table_id on class instance
  corehq/apps/api/resources/v0_5.py
Labels: Risk: High

#33963 Remove general purpose dedupe toggle
  corehq/apps/data_interfaces/migrations/0037_add_dedupe_update_toggle.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/templates/data_interfaces/edit_deduplication_rule.html
  corehq/apps/data_interfaces/templates/data_interfaces/list_deduplication_rules.html
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/users/tasks.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration

#34123 Remove duplicate when a case is closed
  .github/workflows/tests.yml
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
Labels: product/invisible

#33860 Add dedupe backfill migration
  corehq/apps/data_interfaces/migrations/0036_backfill_dedupe_match_values.py
  corehq/apps/data_interfaces/migrations/0037_add_dedupe_update_toggle.py
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/templates/data_interfaces/edit_deduplication_rule.html
  corehq/apps/data_interfaces/templates/data_interfaces/list_deduplication_rules.html
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/reports/standard/cases/duplicate_cases.py
  corehq/apps/users/tasks.py
  corehq/reports.py
  corehq/tabs/tabclasses.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, product/invisible

#34126 Fix issue with trying to hash empty arguments
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_models.py
Labels: product/invisible

#34127 Add Check Before Applying KO Bindings
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/email-request.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/email-request.js
Labels: product/all-users-all-environments

#34129 Add Check Before Applying KO Bindings on Bug Report
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/email-request.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/email-request.js
Labels: product/all-users-all-environments, product/invisible

#34134 Pass closed cases to the dedupe action
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
Labels: product/invisible

#34132 Add metrics to track deduplication
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/tests/test_deduplication_rules.py
  corehq/apps/data_interfaces/views.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/cases/duplicate_cases.py
Labels: product/invisible

#34086 Automatically include case_id in form export
  corehq/apps/export/models/new.py
Labels: QA Passed, product/all-users-all-environments

#34135 Fix enterprise mobile form submissions report
  corehq/apps/enterprise/enterprise.py
Labels: product/invisible

#34130 Only Show Feature Request on Dimagi Environment
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/global_navigation_bar.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/global_navigation_bar.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/global_navigation_bar.html.diff.txt
  corehq/apps/hqwebapp/tests/test_views.py
  corehq/util/context_processors.py
Labels: product/all-users-all-environments, product/invisible

#34138 Design improvement to custom banners
  corehq/apps/domain/templates/domain/admin/manage_alerts.html
Labels: product/all-users-all-environments

#34142 Allow cases to be closed through adblock
  corehq/apps/reports/static/reports/js/case_details.js
Labels: product/invisible

#34144 Addressed earlier dedupe test feedback
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
Labels: product/invisible

#34143 Changed dedupe tests from run_actions_when_case_matches to run_rule
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
Labels: product/invisible

#33979 [USH-3701] N-per-row-repeat for repeat group
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/form_ui_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#34107 Allow Copy Cases Feature to copy cases that are owned by location or group
  corehq/apps/data_interfaces/interfaces.py
  corehq/apps/hqcase/case_helper.py
  corehq/apps/hqcase/tests/test_case_copier.py
Labels: QA Passed, product/feature-flag

#34150 Skip duplicate processing for CommTrack cases
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/apps/data_interfaces/tests/test_pillow.py
Labels: product/invisible

#34084 Standardize tab navigability in web apps forms
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/markdown.js
  corehq/apps/cloudcare/static/cloudcare/js/spec/markdown_spec.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/form.less
Labels: QA Passed, product/invisible, Risk: Medium

#34155 :skull: Remove web user activity report
  corehq/apps/reports/standard/web_user_activity.py
  corehq/reports.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#34149 Update Vellum
  corehq/apps/app_manager/static/app_manager/js/vellum/manifest.txt
  corehq/apps/app_manager/static/app_manager/js/vellum/src/main-components.js
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: product/invisible

#34136 Remove excess bottom padding on form title
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: product/all-users-all-environments

#33978 Couch to SQL Repeat Records PR 1: Write to SQL
  corehq/apps/cleanup/management/commands/populate_sql_model_from_couch_model.py
  corehq/apps/data_interfaces/tests/test_utils.py
  corehq/ex-submodules/dimagi/utils/couch/migration.py
  corehq/motech/repeaters/management/commands/delete_duplicate_cancelled_records.py
  corehq/motech/repeaters/management/commands/populate_repeatrecords.py
  corehq/motech/repeaters/migration_utils.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_couchsqlmigration.py
  corehq/motech/repeaters/tests/test_dbaccessors.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_proxy_models.py
  corehq/motech/repeaters/tests/test_repeater.py
  docs/couch_to_sql_models.rst
Labels: QA Passed, product/invisible

#34159 Fix handling of deleted and restored duplicate cases
  corehq/apps/data_interfaces/models.py
  corehq/apps/data_interfaces/pillow.py
  corehq/apps/data_interfaces/tests/test_case_deduplication.py
  corehq/apps/data_interfaces/tests/test_pillow.py
Labels: product/invisible

#34146 Clear Cache in Data Dictionary
  corehq/apps/data_dictionary/models.py
  corehq/apps/data_dictionary/util.py
Labels: product/all-users-all-environments, product/invisible

#34168 Apply hack to resave missing cases found during dedupe processing
  corehq/apps/data_interfaces/models.py
Labels: product/invisible

#34163 small icon fixes (fontawesome)
  corehq/tabs/tabclasses.py
Labels: product/invisible

#34166 Bootstrap 5 updates to sidebar nav SCSS and text
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_nav.scss
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/navigation_left_sidebar.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/partials/navigation_left_sidebar.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/navs._nav.style.diff.txt
Labels: product/invisible

#34165 Bootstrap 5 variables: update colors to further reflect branding guidelines
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
Labels: product/invisible

#34177 add padding to sidebar elements
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/query.less
Labels: product/feature-flag

#34044 Alt text for case list icons
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/app_manager_media.js
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/app_manager/tests/test_suite_formats.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_detail.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap3/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap5/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap3/key_value_mapping.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/key_value_mapping.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/partials/key_value_mapping.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/ui_elements/ui-element-key-val-mapping.js.diff.txt
Labels: QA Passed, product/all-users-all-environments, Risk: Medium, Core Compatibility

#33952 Upgrade django-tastypie from 0.14.4 to 0.14.6
  corehq/apps/api/resources/v0_5.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, dependencies, Risk: High

#34184 Revert "Alt text for case list icons"
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/app_manager_media.js
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/app_manager/tests/test_suite_formats.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_detail.html
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/module.less
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap3/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap5/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap3/key_value_mapping.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/key_value_mapping.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/partials/key_value_mapping.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/ui_elements/ui-element-key-val-mapping.js.diff.txt
Labels: Risk: Medium, Core Compatibility

#34180 Clear Cache on Successful Import
  corehq/apps/data_dictionary/views.py
Labels: product/all-users-all-environments, product/invisible

#34154 Expire cache on deletion of case properties on Data Dictionary
  corehq/apps/app_manager/app_schemas/case_properties.py
  corehq/apps/app_manager/models.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/export/tests/test_add_inferred_export_properties.py
Labels: QA Passed, product/all-users-all-environments

#34157 Tell the user all the missing params
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/userreports/views.py
Labels: product/invisible

#34169 Add DeletedSQLDoc model
  corehq/apps/cleanup/migrations/0016_add_deletedsqldoc.py
  corehq/apps/cleanup/models.py
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  migrations.lock
Labels: reindex/migration

#34179 Add support for pass_credentials_in_header to OAuth2ClientGrantManager
  corehq/motech/auth.py
  corehq/motech/models.py
Labels: product/invisible

#34042 Prevent adblock from interfering with updating a user
  corehq/apps/users/static/users/js/edit_commcare_user.js
Labels: product/invisible

#34077 Prevent profiles from assigning empty values to required data fields
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/custom_data_fields/tests/test_edit_model.py
  corehq/apps/users/static/users/js/custom_data_fields.js
Labels: product/all-users-all-environments, Risk: Medium

#34171 Switch SQLUserData model to be sparsely populated
  corehq/apps/users/management/commands/populate_sql_user_data.py
  corehq/apps/users/tests/test_user_data.py
  corehq/apps/users/user_data.py
Labels: product/invisible

#34198 Lengthen SQLRepeatRecord.payload_id
  corehq/motech/repeaters/migrations/0007_lengthen_payload_id.py
  corehq/motech/repeaters/models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#34175 Navigate to Dedupe Rule List from Reports
  corehq/apps/reports/standard/cases/duplicate_cases.py
  corehq/apps/reports/standard/cases/filters.py
Labels: product/all-users-all-environments
