Repository dimagi/commcare-hq, pull requests merged in 2024-01, with the labels that each got.

#33902 File Upload Button Style
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/buttons.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_buttons.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/buttons._buttons.style.diff.txt
Labels: product/all-users-all-environments

#33926 Upgrade asgiref from 3.5.0 to 3.7.2
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33937 Upgrade jsonobject-couchdbkit from 1.0.1 to 1.1.0
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33912 Order alerts by modified timestamp
  corehq/apps/domain/views/settings.py
Labels: product/feature-flag

#33922 Update columns for group export
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/tests/test_reports.py
Labels: product/feature-flag

#33935 Fix check for active alerts
  corehq/apps/domain/tests/test_views.py
  corehq/apps/domain/views/settings.py
Labels: product/feature-flag

#33910 Anchored Submit Bar Visual Fix
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: product/feature-flag, Risk: Medium

#33927 Upgrade jsonfield from 2.1.1 to 3.1.0
  corehq/blobs/tests/test_metadata.py
  corehq/messaging/scheduling/tasks.py
  corehq/util/models.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33909 Add ability to edit domain banners / alerts
  corehq/apps/domain/forms.py
  corehq/apps/domain/static/domain/js/manage_alerts.js
  corehq/apps/domain/templates/domain/admin/edit_alert.html
  corehq/apps/domain/templates/domain/admin/manage_alerts.html
  corehq/apps/domain/tests/test_views.py
  corehq/apps/domain/urls.py
  corehq/apps/domain/views/settings.py
Labels: product/feature-flag

#33941 Fix No Case Property/Type Name Validation on Data Dictionary Imports
  corehq/apps/data_dictionary/bulk.py
  corehq/apps/data_dictionary/tests/data/broken_data_dictionary.xlsx
  corehq/apps/data_dictionary/tests/test_import_export.py
  corehq/apps/data_dictionary/tests/test_util.py
  corehq/apps/data_dictionary/util.py
Labels: product/all-users-all-environments

#33931 Support CLE's Case Search filter in GeoSpatial Reports
  corehq/apps/geospatial/reports.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/cases/filters.py
Labels: product/feature-flag

#33775 Upgrade Stripe
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/generator.py
  corehq/apps/accounting/tests/test_autopay.py
  corehq/apps/accounting/tests/test_autopay_with_api.py
  corehq/apps/accounting/tests/test_models.py
  corehq/apps/accounting/tests/test_stripe_payment_method_with_api.py
  corehq/apps/accounting/tests/utils.py
  corehq/apps/accounting/utils/stripe.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, dependencies

#33951 Upgrade faker from 19.12.0 to 22.0.0
  requirements/dev-requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33947 Geospatial: Reset disbursement on saved area change
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/templates/map_visualization.html
Labels: product/feature-flag

#33928 DRY up case tile previews
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_tile_preview.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_tile_templates.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/style_configuration_modal.html
  corehq/apps/hqwebapp/static/app_manager/less/case_tile_preview.less
  corehq/apps/hqwebapp/static/app_manager/less/content.less
Labels: product/invisible

#33957 Minor updates to web apps messages
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/sessions/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js
Labels: product/invisible, Risk: Medium

#33948 Fix the conflicting IDs for filtering software plan
  corehq/apps/accounting/forms.py
  corehq/apps/accounting/static/accounting/js/subscriptions_main.js
Labels: QA Passed, product/admin

#33877 Create Repeat record for each data source row change
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/userreports/urls.py
  corehq/apps/userreports/util.py
  corehq/apps/userreports/views.py
  corehq/motech/repeaters/migrations/0005_datasourcerepeater.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/signals.py
  corehq/motech/repeaters/tests/test_repeater.py
  migrations.lock
  settings.py
Labels: reindex/migration, product/all-users-all-environments, product/feature-flag

#33949 Adds a management command migration to ensure Third party envs are reindexed
  corehq/apps/es/management/commands/ensure_indices_reindexed.py
  corehq/apps/es/migrations/0006_verify_es2_indices_reindexed.py
  corehq/apps/es/tests/test_ensure_indices_reindexed.py
  migrations.lock
  settings.py
Labels: reindex/migration

#33741 Validate Data Dictionary Case types
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
Labels: product/all-users-all-environments

#33740 Validate Data Dictionary Case Properties
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
Labels: product/all-users-all-environments

#33962 Add panel class to tile
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#33942 adjust margins for fields using borders and/or shading
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: Risk: Medium

#33972 Prevent Message Blink on Page Load (Geospatial Settings)
  corehq/apps/geospatial/templates/geospatial/settings.html
Labels: product/feature-flag

#33969 Repeat Record prefactor
  corehq/apps/zapier/tests/test_zapier_forwarding.py
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/management/commands/generate_repeater_report.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_display.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_models_slow.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/tests/test_tasks.py
Labels: product/invisible

#33971 SQLRepeatRecord db changes needed for Couch to SQL migration
  corehq/apps/data_interfaces/tasks.py
  corehq/apps/data_interfaces/tests/test_utils.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/registry/tests/test_logging.py
  corehq/apps/reports/filters/select.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/views.py
  corehq/apps/zapier/signals/receivers.py
  corehq/apps/zapier/tests/test_zapier_hooks.py
  corehq/motech/dhis2/tests/test_repeaters.py
  corehq/motech/dhis2/views.py
  corehq/motech/management/commands/create_repeat_records.py
  corehq/motech/openmrs/tests/test_atom_feed.py
  corehq/motech/openmrs/tests/test_repeaters.py
  corehq/motech/openmrs/tests/test_views.py
  corehq/motech/openmrs/views.py
  corehq/motech/repeaters/const.py
  corehq/motech/repeaters/dbaccessors.py
  corehq/motech/repeaters/management/commands/delete_duplicate_cancelled_records.py
  corehq/motech/repeaters/management/commands/update_cancelled_records.py
  corehq/motech/repeaters/migrations/0006_int_state_add_next_check_rm_repeater_id.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_payload_generator.py
  corehq/motech/repeaters/tests/test_data_registry_case_update_repeater.py
  corehq/motech/repeaters/tests/test_display.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_models_slow.py
  corehq/motech/repeaters/tests/test_proxy_models.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/tests/test_tasks.py
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/repeaters.py
  custom/hmhb/management/commands/repeat_forms_by_external_id.py
  migrations.lock
Labels: reindex/migration, product/invisible

#33965 Only Load Cases/Users with GPS Data on Map
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/templates/map_visualization.html
  corehq/apps/geospatial/tests/test_views.py
  corehq/apps/geospatial/views.py
Labels: product/feature-flag

#33970 Moved markdown-table.less to the same directory as other web apps LESS
  corehq/apps/cloudcare/templates/formplayer/dependencies.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common-main.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/markdown-table.less
Labels: product/invisible, Risk: Medium

#33958 Improve UI for Deprecating Case Types in Data Dictionary
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/tests/test_view.py
  corehq/apps/data_dictionary/views.py
Labels: product/all-users-all-environments

#33974 Access queryData on `this` from debugger
  corehq/apps/cloudcare/static/cloudcare/js/debugger/debugger.js
Labels: product/invisible, Risk: Medium

#33914 Basic Accessibility for Clickable Icons
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
Labels: QA Passed, product/feature-flag, Risk: Medium

#33980 Just some tests
  corehq/ex-submodules/dimagi/utils/tests/test_web.py
Labels: product/invisible

#33819 Sticky case tile in web apps
  corehq/apps/builds/templates/builds/edit_menu.html
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/notifications.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/breadcrumbs.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/main.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/includes/variables.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/layouts.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_containers.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_layouts.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables_bootstrap3.scss
  corehq/apps/hqwebapp/static/preview_app/less/preview_app/form.less
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/main.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables_bootstrap3.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/layouts._containers.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/layouts._layouts.style.diff.txt
  corehq/apps/integration/templates/integration/base_cloudcare_template.html
Labels: QA Passed, product/feature-flag, Risk: Medium

#33982 Eliminated inline style
  corehq/apps/cloudcare/templates/formplayer/case_detail.html
Labels: product/invisible, Risk: Medium

#33938 Dynamically load case details when clicking markers
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/management/commands/migrate_address_popup.py
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_3X_two_4X_one_2X.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_3X_two_4X_one_2X.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_one_two.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one.xml
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one_one.json
  corehq/apps/app_manager/suite_xml/case_tile_templates/one_two_one_one.xml
  corehq/apps/app_manager/tests/test_build_errors.py
  corehq/apps/app_manager/tests/test_migrate_address_popup.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#33986 Log slow case search requests in detail
  corehq/apps/ota/views.py
Labels: product/invisible

#33987 Updated usage of initialPageData in cloudcare js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
Labels: product/invisible, Risk: Medium

#33975 Add dedupe domain privilege
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0089_dedupe_priv.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
  migrations.lock
Labels: reindex/migration, product/invisible

#33996 Remove Old Geospatial TODO
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
Labels: product/feature-flag

#33989 [B5] split widgets.js into bootstrap 3 and 5 versions
  corehq/apps/app_manager/static/app_manager/js/app_exchange.js
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/static/app_manager/js/manage_releases_by_location.js
  corehq/apps/app_manager/templates/app_manager/app_view.html
  corehq/apps/case_importer/static/case_importer/js/main.js
  corehq/apps/commtrack/static/commtrack/js/products_and_programs_main.js
  corehq/apps/custom_data_fields/edit_entity.py
  corehq/apps/data_interfaces/static/data_interfaces/js/case_dedupe_main.js
  corehq/apps/domain/static/domain/js/info_basic.js
  corehq/apps/domain/static/domain/js/internal_subscription_management.js
  corehq/apps/enterprise/templates/enterprise/enterprise_permissions.html
  corehq/apps/events/static/events/js/event_attendees.js
  corehq/apps/events/static/events/js/new_event.js
  corehq/apps/hqmedia/templates/hqmedia/audio_translator.html
  corehq/apps/hqmedia/templates/hqmedia/translations_coverage.html
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/widgets.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/widgets.js
  corehq/apps/hqwebapp/static/hqwebapp/js/maintenance_alerts.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/widgets_spec.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/widgets.js.diff.txt
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/reminders/static/reminders/js/reminders.keywords.ko.js
  corehq/apps/reports/static/reports/js/edit_scheduled_report.js
  corehq/apps/reports/static/reports/js/hq_report.js
  corehq/apps/reports/templates/reports/standard/base_template.html
  corehq/apps/settings/static/settings/js/user_api_keys.js
  corehq/apps/sms/static/sms/js/gateway_list.js
  corehq/apps/sms/static/sms/js/settings.js
  corehq/apps/smsbillables/static/smsbillables/js/smsbillables.rate_calc.js
  corehq/apps/styleguide/templates/styleguide/bootstrap3/base.html
  corehq/apps/translations/static/translations/js/app_translations.js
  corehq/apps/translations/templates/blacklist_translations.html
  corehq/apps/translations/templates/pull_resource.html
  corehq/apps/userreports/templates/userreports/ucr_expression.html
  corehq/apps/userreports/templates/userreports/userreports_base.html
  corehq/apps/users/static/users/js/custom_data_fields.js
  corehq/apps/users/static/users/js/edit_commcare_user.js
  corehq/apps/users/static/users/js/filtered_download.js
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_main.js
  corehq/motech/dhis2/static/dhis2/js/dataset_map.js
  corehq/motech/dhis2/static/dhis2/js/dataset_map_create.js
  corehq/motech/dhis2/static/dhis2/js/dataset_map_update.js
  corehq/motech/repeaters/static/repeaters/js/add_form_repeater.js
  corehq/motech/static/motech/js/connection_settings.js
  docs/js-guide/dependencies.rst
Labels: product/invisible, Risk: Medium

#34003 Removed form_tree fixture
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/fixtures/form_tree.js
  corehq/apps/cloudcare/templates/cloudcare/spec/mocha.html
Labels: product/invisible, Risk: Medium

#33992 [B5] Add successor to datetimepicker and newest font awesome
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/requirejs_config.js
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/core_stylesheets.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/core_stylesheets.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/requirejs_config.js.diff.txt
  package.json
  yarn.lock
Labels: product/invisible, dependencies

#33966 Fix enterprise dashboard mobile form submission data
  corehq/apps/enterprise/enterprise.py
Labels: awaiting QA, product/all-users-all-environments

#33834 [USH-3855] N-per-row attribute for Groups
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/form_ui_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/form.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/main.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/layouts._layouts.style.diff.txt
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#33997 Save the projects default location bounding box and use in on search results
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/widgets.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/widgets.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/widgets.js.diff.txt
  corehq/toggles/__init__.py
Labels: Risk: Medium

#34016 Update check to allow link clicks in case list rows/tiles
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#34006 Adds DD tag for Case Search Input
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: Risk: Medium

#34012 Web apps tests: make toggle dependencies explicit
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/form_ui_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/web_form_session_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/query_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/utils_spec.js
  corehq/apps/hqwebapp/static/hqwebapp/js/initial_page_data.js
Labels: product/invisible, Risk: Medium

#34002 Add Mapbox Streets Layers
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/templates/base_template.html
  corehq/apps/geospatial/templates/map_visualization.html
Labels: product/feature-flag

#34022 Add zandre-eng to CODEOWNERS
  .github/CODEOWNERS
Labels: product/invisible

#33983 Case Search on Clear
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/case_claim.js
  corehq/apps/app_manager/suite_xml/post_process/remote_requests.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/partials/build_errors.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/tests/test_build_errors.py
  corehq/apps/app_manager/tests/test_suite_split_screen_case_search.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
Labels: product/feature-flag, Risk: Medium, Core Compatibility

#33976 Continue/select button translation
  corehq/apps/app_manager/app_strings.py
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/id_strings.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/tests/app_factory.py
  corehq/apps/app_manager/tests/test_app_strings.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/collections.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/multi_select_continue_button.html
  corehq/apps/translations/app_translations/download.py
  corehq/apps/translations/app_translations/upload_module.py
  corehq/apps/translations/tests/data/bulk_app_translation/download/app.json
  corehq/apps/translations/tests/test_bulk_app_translation.py
Labels: Risk: Medium, Core Compatibility

#34028 Updated build_requirejs string check
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
Labels: product/invisible

#34029 Updates message to user when limiting active alerts
  corehq/apps/domain/tests/test_views.py
  corehq/apps/domain/views/settings.py
Labels: product/feature-flag

#34013 Show Group Modification Popup on Click
  corehq/apps/geospatial/static/geospatial/js/case_grouping_map.js
  corehq/apps/geospatial/static/geospatial/js/geospatial_map.js
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/static/geospatial/js/utils.js
Labels: product/feature-flag

#34031 Added requirejs config for sentry
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/yaml/bootstrap3/requirejs.yml
  corehq/apps/hqwebapp/static/hqwebapp/yaml/bootstrap5/requirejs.yml
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/main.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/requirejs_config.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/layouts._layouts.style.diff.txt
Labels: product/invisible, Risk: High

#33858 update DEV_SETUP.md to include SASS installation instructions
  DEV_SETUP.md
Labels: product/invisible

#34015 update datatables library support (css and js) for bootstrap 5 pages
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
Labels: product/invisible, Risk: Medium

#34001 Upgrade setup-tools to latest version
  corehq/warnings.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#33999 Use natural keys for foreign key relationships during serialization/deserialization
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/dump_reload/tests/test_serialization.py
  corehq/apps/dump_reload/tests/test_sql_data_loader.py
  corehq/apps/dump_reload/tests/test_sql_dump_load.py
  corehq/blobs/models.py
  corehq/form_processor/models/cases.py
  corehq/form_processor/models/forms.py
  corehq/form_processor/models/ledgers.py
Labels: Risk: High

#34033 Removed unused ota templates
  corehq/apps/ota/forms.py
  corehq/apps/ota/templates/ota/advanced_prime_restore_cache.html
  corehq/apps/ota/templates/ota/prime_restore_cache.html
Labels: product/invisible

#33946 Keep case search query inputs out of address bar
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/router.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
Labels: QA Passed, product/feature-flag, Risk: Medium

#34032 Remove bottom margin for gr-has-no-nested-questions
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/form.less
Labels: product/all-users-all-environments

#34017 [USH-4025] Add waf_allow to EditBasicProjectInfoView
  corehq/apps/domain/urls.py
Labels: product/all-users-all-environments

#34038 [USH-4045] Margins for multi-select buttons
  corehq/apps/hqwebapp/static/cloudcare/css/webforms.css
Labels: product/all-users-all-environments

#34036 Appearance attribute to use hint as placeholder
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/const.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: Risk: Medium

#34040 Move webforms css
  corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html
  corehq/apps/cloudcare/templates/formplayer-common/base.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common-main.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-common/webforms.less
  corehq/apps/integration/templates/integration/base_cloudcare_template.html
Labels: product/invisible, Risk: Medium

#34030 [USH-4126] Multimedia question buttons' alignment
  corehq/apps/cloudcare/templates/form_entry/templates.html
Labels: product/all-users-all-environments, Risk: Medium

#33933 GA Custom Domain Alerts
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0090_custom_domain_alerts_priv.py
  corehq/apps/domain/tests/test_views.py
  corehq/apps/domain/views/settings.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/users/templates/users/partials/edit_role_modal.html
  corehq/apps/users/tests/test_views.py
  corehq/apps/users/views/__init__.py
  corehq/privileges.py
  corehq/tabs/tabclasses.py
  corehq/toggles/__init__.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/all-users-all-environments

#34041 Refresh results on form submission: followup
  corehq/form_processor/submission_post.py
Labels: product/feature-flag, Risk: High

#34049 Fix invalid profile errors presented with field data errors
  corehq/apps/custom_data_fields/edit_model.py
  corehq/apps/custom_data_fields/tests/test_edit_model.py
Labels: product/invisible, Risk: Medium

#33990 Case tiles for case detail
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/suite_xml/features/case_tiles.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_detail.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_tile_preview.html
  corehq/apps/app_manager/tests/data/suite/case-tile-case-detail-tabs.xml
  corehq/apps/app_manager/tests/data/suite/case-tile-case-detail.xml
  corehq/apps/app_manager/tests/test_build_errors.py
  corehq/apps/app_manager/tests/test_suite_custom_case_tiles.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/app_manager/less/case_tile_preview.less
  corehq/toggles/__init__.py
Labels: QA Passed, product/feature-flag, Risk: Medium

#34062 Added explicit dependencies to exports js tests
  corehq/apps/export/static/export/spec/ExportColumn.spec.js
  corehq/apps/export/static/export/spec/ExportInstance.spec.js
  corehq/apps/export/static/export/spec/Exports.Utils.spec.js
  corehq/apps/export/static/export/spec/data/export_instances.js
Labels: product/invisible

#34053 Remove Margins added to page with SCCS and Map after case search
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
Labels: Risk: Medium

#34064 Added explicit dependencies to some stray js tests
  corehq/apps/case_importer/static/case_importer/spec/excel_fields_spec.js
  corehq/apps/locations/static/locations/spec/data/locations_data.js
  corehq/apps/locations/static/locations/spec/location_drilldown_spec.js
  corehq/apps/locations/static/locations/spec/types_spec.js
Labels: product/invisible

#34014 Update bootstrap 5 version of hqwebapp/js/widgets to use Tempus Dominus for date picker widget
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/widgets.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/widgets.js.diff.txt
Labels: product/invisible

#34009 Add @use_datetimepicker decorator to use Tempus Dominus on Bootstrap 5 pages
  corehq/apps/hqwebapp/decorators.py
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/requirejs_config.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/requirejs_config.js.diff.txt
Labels: product/invisible, Risk: Medium

#34065 Persistent Case Tile Alignment
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/form.less
Labels: Risk: Medium

#34025 Adjust margin for multi select tiles
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/templates/formplayer/case_list.html
  corehq/apps/hqwebapp/static/cloudcare/less/formplayer-webapp/content.less
  corehq/toggles/__init__.py
Labels: Risk: Medium
