Repository dimagi/commcare-hq, pull requests merged in 2025-04, with the labels that each got.

#36094 Adds ability to delete a widget in dashboard
  corehq/apps/campaign/static/campaign/js/dashboard.js
  corehq/apps/campaign/templates/campaign/dashboard.html
  corehq/apps/campaign/templates/campaign/partials/add_widget_button.html
  corehq/apps/campaign/templates/campaign/partials/dashboard_gauge.html
  corehq/apps/campaign/templates/campaign/partials/dashboard_map.html
  corehq/apps/campaign/templates/campaign/partials/delete_widget_button.html
  corehq/apps/campaign/templates/campaign/partials/delete_widget_confirmation_modal.html
  corehq/apps/campaign/templates/campaign/partials/edit_widget_button.html
  corehq/apps/campaign/tests/test_views.py
  corehq/apps/campaign/views.py
Labels: product/feature-flag

#35868 Web User API Bulk user data lookup and filter via ES
  corehq/apps/api/query_adapters.py
  corehq/apps/api/resources/v0_1.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/test_user_resources.py
  corehq/apps/es/users.py
Labels: Risk: High

#36117 Updated javascript guide to remove RequireJS references
  corehq/apps/styleguide/templates/styleguide/bootstrap5/htmx_and_alpine.html
  docs/js-guide/README.rst
  docs/js-guide/amd-to-esm.rst
  docs/js-guide/dependencies.rst
  docs/js-guide/external-packages.rst
  docs/js-guide/migrating.rst
  docs/js-guide/module-history.rst
  docs/js-guide/requirejs-to-webpack.rst
  docs/js-guide/static-files.rst
Labels: product/admin

#36084 Redirect to dashboard on signup and show a better banner
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/plan_notice.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style-imports.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_plan_notice.scss
  corehq/apps/hqwebapp/templates/hqwebapp/partials/pending_plan_notice.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diff_config.json
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/plan_notice._plan_notice.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/style-imports.commcarehq.style.diff.txt
  corehq/apps/registration/tests/test_views.py
  corehq/apps/registration/views.py
Labels: product/prod-india-all-users, Risk: High

#36129 Updated B3 style guide accessibility section to point to B5 section
  corehq/apps/styleguide/templates/styleguide/bootstrap3/_includes/atoms/accessibility.html
Labels: product/all-users-all-environments

#36128 Interval Sync Bug Fix
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
  corehq/toggles/__init__.py
Labels: Risk: Medium

#36139 Drop "Gauges" and "Reports" headings
  corehq/apps/campaign/templates/campaign/dashboard.html
Labels: product/feature-flag

#36140 dashboard.js uses Bootstrap 5
  corehq/apps/campaign/static/campaign/js/dashboard.js
Labels: product/invisible

#36123 Revert "Revert "Webpack migration for pages that use Stripe""
  corehq/apps/accounting/.eslintrc.js
  corehq/apps/accounting/static/accounting/js/base_subscriptions_main.js
  corehq/apps/accounting/static/accounting/js/billing_account_form.js
  corehq/apps/accounting/static/accounting/js/confirm_plan.js
  corehq/apps/accounting/static/accounting/js/credits.js
  corehq/apps/accounting/static/accounting/js/credits_tab.js
  corehq/apps/accounting/static/accounting/js/payment_method_handler.js
  corehq/apps/accounting/static/accounting/js/pricing_table.js
  corehq/apps/accounting/static/accounting/js/renew_plan_selection.js
  corehq/apps/accounting/static/accounting/js/software_plan_version_handler.js
  corehq/apps/accounting/static/accounting/js/stripe.js
  corehq/apps/accounting/static/accounting/js/stripe_card_manager.js
  corehq/apps/accounting/static/accounting/js/subscriptions_main.js
  corehq/apps/accounting/static/accounting/js/widgets.js
  corehq/apps/accounting/templates/accounting/accounts.html
  corehq/apps/accounting/templates/accounting/accounts_base.html
  corehq/apps/accounting/templates/accounting/invoice.html
  corehq/apps/accounting/templates/accounting/partials/new_stripe_card_template.html
  corehq/apps/accounting/templates/accounting/partials/stripe_card_ko_template.html
  corehq/apps/accounting/templates/accounting/plans.html
  corehq/apps/accounting/templates/accounting/subscriptions.html
  corehq/apps/domain/.eslintrc.js
  corehq/apps/domain/static/domain/js/bootstrap3/billing_statements.js
  corehq/apps/domain/static/domain/js/bootstrap3/update_billing_contact_info.js
  corehq/apps/domain/static/domain/js/bootstrap5/billing_statements.js
  corehq/apps/domain/static/domain/js/bootstrap5/update_billing_contact_info.js
  corehq/apps/domain/static/domain/js/confirm_billing_info.js
  corehq/apps/domain/static/domain/js/current_subscription.js
  corehq/apps/domain/templates/domain/bootstrap3/billing_statements.html
  corehq/apps/domain/templates/domain/bootstrap3/confirm_billing_info.html
  corehq/apps/domain/templates/domain/bootstrap3/current_subscription.html
  corehq/apps/domain/templates/domain/bootstrap3/update_billing_contact_info.html
  corehq/apps/domain/templates/domain/bootstrap5/billing_statements.html
  corehq/apps/domain/templates/domain/bootstrap5/confirm_billing_info.html
  corehq/apps/domain/templates/domain/bootstrap5/current_subscription.html
  corehq/apps/domain/templates/domain/bootstrap5/update_billing_contact_info.html
  corehq/apps/domain/views/accounting.py
  corehq/apps/enterprise/views.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/billing_statements.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/confirm_billing_info.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/current_subscription.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/update_billing_contact_info.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/domain/js/billing_statements.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/domain/js/update_billing_contact_info.js.diff.txt
  package.json
  yarn.lock
Labels: QA Passed, dependencies

#36141 Revert "Riese/hide columns"
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/split_screen_case_search_spec.js
  corehq/apps/cloudcare/templates/cloudcare/partials/all_templates.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/config.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/config_modal.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/item.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/menu_header.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/table_container.html
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common-main.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/config.scss
Labels: Risk: Medium

#36142 Fixed typo in code-review.rst
  docs/js-guide/code-review.rst
Labels: product/invisible

#36143 Add translations for Spanish French and Portuguese
  corehq/apps/fixtures/views.py
  locale/es/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/djangojs.po
  locale/fra/LC_MESSAGES/django.po
  locale/fra/LC_MESSAGES/djangojs.po
  locale/por/LC_MESSAGES/django.po
  locale/por/LC_MESSAGES/djangojs.po
Labels: Risk: Medium

#36133 Add kyc status to payment report
  corehq/apps/integration/kyc/models.py
  corehq/apps/integration/payments/tables.py
  corehq/apps/integration/payments/tests/test_views.py
  corehq/apps/integration/payments/views.py
Labels: product/feature-flag

#36126 Python 3.13 compatibility - part 1
  corehq/apps/hqwebapp/templatetags/proptable_tags.py
  corehq/apps/hqwebapp/widgets.py
  corehq/apps/registry/tests/test_helper.py
  corehq/apps/reports/tests/test_daterange.py
  corehq/apps/userreports/util.py
  corehq/pillows/xform.py
  corehq/tests/pytest_plugins/patches.py
  corehq/util/signals.py
  corehq/warnings.py
  docker/run.sh
Labels: product/invisible

#36150 Change Campaign PDF Export Orientation
  corehq/apps/campaign/static/campaign/js/dashboard.js
  corehq/apps/campaign/templates/campaign/partials/dashboard_gauge.html
Labels: product/feature-flag

#36110 Refresh Payment Report Table on Verify Success
  corehq/apps/integration/static/integration/js/payments/payments_verify.js
  corehq/apps/integration/templates/payments/partials/payments_verify_alert.html
  corehq/apps/integration/templates/payments/payments_verify_report.html
Labels: product/feature-flag

#36137 Simplify Widget Form by automatically passing the active dashboard tab
  corehq/apps/campaign/forms.py
  corehq/apps/campaign/static/campaign/js/dashboard.js
  corehq/apps/campaign/templates/campaign/partials/add_widget_button.html
  corehq/apps/campaign/templates/campaign/partials/edit_widget_button.html
Labels: product/feature-flag

#36148 apply load styling to checkbox when checkbox triggers hx-post on parent form
  corehq/apps/data_cleaning/templates/data_cleaning/columns/selection.html
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_htmx.scss
Labels: product/all-users-all-environments

#36152 Remove rollout modal
  corehq/apps/app_manager/templates/app_manager/apps_base.html
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/rollout_modal.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/rollout_modal.js
  corehq/apps/hqwebapp/templates/hqwebapp/bootstrap3/rollout_modal.html
  corehq/apps/hqwebapp/templates/hqwebapp/bootstrap5/rollout_modal.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/rollout_modal.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/rollout_modal.js.diff.txt
Labels: product/invisible

#36125 Upgrade simpleeval==1.0.3
  corehq/apps/userreports/expressions/evaluator/main.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#35956 Add device model and OS version to device logs
  corehq/ex-submodules/phonelog/migrations/0015_devicereportentry_android_version_and_more.py
  corehq/ex-submodules/phonelog/models.py
  corehq/ex-submodules/phonelog/tests/test_sumologic.py
  corehq/ex-submodules/phonelog/utils.py
  migrations.lock
Labels: reindex/migration

#36144 Readd "Riese/hide columns""
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/fake_formplayer.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/split_screen_case_search_spec.js
  corehq/apps/cloudcare/templates/cloudcare/partials/all_templates.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/config.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/config_modal.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/item.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/menu_header.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/table_container.html
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common-main.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/config.scss
Labels: Risk: Medium

#36161 Use fixed time values to avoid flaky tests
  corehq/apps/experiments/tests/test_experiment.py
Labels: product/invisible

#36158 Dashboard Report prefactor
  corehq/apps/userreports/reports/view.py
Labels: product/invisible

#36149 [Data Cleaning] Select / De-Select page of records
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_session.js
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/templates/data_cleaning/columns/selection.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/selection_header.html
  corehq/apps/data_cleaning/tests/test_records.py
  corehq/apps/data_cleaning/views/tables.py
  corehq/apps/hqwebapp/static/hqwebapp/js/htmx_utils/hq_hx_select_all.js
Labels: product/feature-flag

#36151 Adds Missing KYC status check while fetching it.
  corehq/apps/integration/kyc/models.py
  corehq/apps/integration/kyc/tests/test_models.py
  corehq/apps/integration/kyc/views.py
  corehq/apps/integration/templates/kyc/partials/kyc_verify_status.html
Labels: product/feature-flag

#36166 Correct attribute names
  corehq/apps/campaign/static/campaign/js/dashboard.js
Labels: product/invisible

#36165 [Data Cleaning] Select / De-Select all records in current queryset
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/templates/data_cleaning/tables/table_with_controls.html
  corehq/apps/data_cleaning/tests/test_records.py
  corehq/apps/data_cleaning/views/tables.py
  corehq/apps/hqwebapp/static/hqwebapp/js/htmx_utils/hq_hx_select_all.js
Labels: product/feature-flag

#36127 Replace the current new module popover to be a modal
  corehq/apps/app_manager/static/app_manager/js/app_manager.js
  corehq/apps/app_manager/templates/app_manager/apps_base.html
  corehq/apps/app_manager/templates/app_manager/partials/add_item_templates.html
  corehq/apps/app_manager/templates/app_manager/partials/add_new_module_modal.html
  corehq/apps/app_manager/templates/app_manager/partials/menu/appnav_menu.html
  corehq/apps/app_manager/templates/app_manager/partials/module_options/module_option_advanced.html
  corehq/apps/app_manager/templates/app_manager/partials/module_options/module_option_biometrics.html
  corehq/apps/app_manager/templates/app_manager/partials/module_options/module_option_button_base.html
  corehq/apps/app_manager/templates/app_manager/partials/module_options/module_option_case.html
  corehq/apps/app_manager/templates/app_manager/partials/module_options/module_option_report.html
  corehq/apps/app_manager/templates/app_manager/partials/module_options/module_option_shadow.html
  corehq/apps/app_manager/templates/app_manager/partials/module_options/module_option_shadow_v1.html
  corehq/apps/app_manager/templates/app_manager/partials/module_options/module_option_survey.html
  corehq/apps/app_manager/templates/app_manager/partials/module_options/module_option_training.html
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/hqwebapp/static/app_manager/less/app_manager-main.less
  corehq/apps/hqwebapp/static/app_manager/less/new_module_modal.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/modals.less
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/modals._modal.style.diff.txt
Labels: product/prod-india-all-users

#36157 Revert "Remove unused plan-notice custom styles"
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/plan_notice.less
  corehq/apps/hqwebapp/static/hqwebapp/less/style-imports.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_plan_notice.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diff_config.json
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/plan_notice._plan_notice.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/style-imports.commcarehq.style.diff.txt
Labels: product/prod-india-all-users

#36171 Upgrade sqlagg==0.18.0
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#36174 Fix test
  corehq/motech/fhir/tests/test_searchers.py
Labels: product/invisible

#36173 KYC - Refresh Table on verify to show the latest data
  corehq/apps/integration/static/integration/js/kyc/kyc_verify.js
  corehq/apps/integration/templates/kyc/kyc_verify_report.html
  corehq/apps/integration/templates/kyc/partials/kyc_verify_alert.html
Labels: product/feature-flag

#36092 Updates to Select Plan page
  corehq/apps/accounting/static/accounting/js/pricing_table.js
  corehq/apps/accounting/user_text.py
  corehq/apps/domain/templates/domain/bootstrap3/select_plan.html
  corehq/apps/domain/templates/domain/bootstrap5/select_plan.html
  corehq/apps/domain/views/accounting.py
  corehq/apps/hqwebapp/static/accounting/less/pricing-main.less
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/select_plan.html.diff.txt
Labels: product/all-users-all-environments

#36168 Don't fetch $0 invoices as "unpaid"
  corehq/apps/accounting/utils/invoicing.py
Labels: product/invisible

#36172 Updated display condition of pagination of case properties on form se…
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
Labels: product/all-users-all-environments

#35968 Added a tooltip for case properties
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
Labels: product/all-users-all-environments

#36155 Hide wire payment options for customers not on Enterprise
  corehq/apps/accounting/invoice_pdf.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/templates/accounting/email/customer_invoice.html
  corehq/apps/accounting/templates/accounting/email/customer_invoice.txt
  corehq/apps/accounting/templates/accounting/email/invoice.html
  corehq/apps/accounting/templates/accounting/email/invoice.txt
  corehq/apps/accounting/templates/accounting/email/invoice_reminder.html
  corehq/apps/accounting/templates/accounting/email/invoice_reminder.txt
  corehq/apps/accounting/tests/data/invoice_000.pdf
  corehq/apps/accounting/tests/data/invoice_001.pdf
  corehq/apps/accounting/tests/data/invoice_002.pdf
  corehq/apps/accounting/tests/data/invoice_003.pdf
  corehq/apps/accounting/tests/data/invoice_004.pdf
  corehq/apps/accounting/tests/data/invoice_005.pdf
  corehq/apps/accounting/tests/data/invoice_006.pdf
  corehq/apps/accounting/tests/data/invoice_007.pdf
  corehq/apps/accounting/tests/data/invoice_008.pdf
  corehq/apps/accounting/tests/data/invoice_009.pdf
  corehq/apps/accounting/tests/test_invoice_pdf.py
  corehq/apps/accounting/utils/unpaid_invoice.py
  corehq/apps/domain/templates/domain/bootstrap3/billing_statements.html
  corehq/apps/domain/templates/domain/bootstrap5/billing_statements.html
  corehq/apps/domain/views/accounting.py
  corehq/apps/enterprise/views.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/billing_statements.html.diff.txt
Labels: product/all-users-all-environments

#36049 Upgrade kafka-python==2.1.4
  corehq/apps/change_feed/connection.py
  corehq/apps/change_feed/consumer/feed.py
  corehq/apps/change_feed/management/commands/create_kafka_topics.py
  corehq/apps/change_feed/tests/test_connection.py
  corehq/apps/change_feed/tests/test_pillow.py
  corehq/apps/change_feed/tests/utils.py
  corehq/apps/change_feed/topics.py
  corehq/ex-submodules/pillow_retry/tests/test_retry.py
  corehq/ex-submodules/pillowtop/checkpoints/manager.py
  corehq/ex-submodules/pillowtop/models.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  corehq/util/io.py
  corehq/util/tests/test_io.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  testapps/test_pillowtop/tests/test_chunk_pillow.py
Labels: product/invisible, dependencies

#36154 Removed requirejs_main template tag and associated code
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/hqwebapp/static/hqwebapp/js/django.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/requirejs.html
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/templatetags/tests/templates/requirejs_base.html
  corehq/apps/hqwebapp/templatetags/tests/test_tag.py
  corehq/apps/hqwebapp/utils/bootstrap/paths.py
  docs/translations.rst
Labels: product/invisible, Risk: Medium

#36138 Add Role based access control for Payments Report
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/kyc/views.py
  corehq/apps/integration/payments/tests/test_views.py
  corehq/apps/integration/payments/views.py
  corehq/apps/users/permissions.py
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#36167 [webpack] App manager
  corehq/apps/app_manager/static/app_manager/js/app_manager.js
  corehq/apps/app_manager/static/app_manager/js/app_manager_media.js
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/static/app_manager/js/details/case_detail_print.js
  corehq/apps/app_manager/static/app_manager/js/details/case_list_callout.js
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/static/app_manager/js/details/graph_config.js
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/static/app_manager/js/details/sort_rows.js
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/actions.js
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/copy_form_to_app.js
  corehq/apps/app_manager/static/app_manager/js/forms/custom_instances.js
  corehq/apps/app_manager/static/app_manager/js/forms/edit_form_details.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_designer.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view_report.js
  corehq/apps/app_manager/static/app_manager/js/modules/report_module.js
  corehq/apps/app_manager/static/app_manager/js/nav_menu_media.js
  corehq/apps/app_manager/static/app_manager/js/nav_menu_media_common.js
  corehq/apps/app_manager/static/app_manager/js/releases/app_view_release_manager.js
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/static/app_manager/js/settings/app_logos.js
  corehq/apps/app_manager/static/app_manager/js/settings/commcare_settings.js
  corehq/apps/app_manager/static/app_manager/js/visit_scheduler.js
  corehq/apps/app_manager/static/app_manager/js/xpathValidator.js
  corehq/apps/app_manager/templates/app_manager/app_view.html
  corehq/apps/app_manager/templates/app_manager/app_view_release_manager.html
  corehq/apps/app_manager/templates/app_manager/app_view_settings.html
  corehq/apps/app_manager/templates/app_manager/apps_base.html
  corehq/apps/app_manager/templates/app_manager/form_designer.html
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/templates/app_manager/module_view.html
  corehq/apps/app_manager/templates/app_manager/module_view_advanced.html
  corehq/apps/app_manager/templates/app_manager/module_view_report.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_properties.html
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/app_manager/xpath_validator/nodejs/xpathConfig.js
  corehq/apps/hqwebapp/static/hqwebapp/js/key-value-mapping.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap3/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap5/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap3/key_value_mapping.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/key_value_mapping.html
  webpack/webpack.b3.common.js
Labels: QA Passed, product/invisible

#36175 Disable deleting invalid case properties
  corehq/motech/openmrs/repeater_helpers.py
  corehq/motech/openmrs/tests/test_repeaters.py
Labels: product/invisible

#36180 [Data Cleaning] Add placeholder view for the data cleaning form
  corehq/apps/data_cleaning/templates/data_cleaning/forms/clean_selected_records_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/offcanvas.html
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/views/cleaning.py
Labels: product/feature-flag

#36183 delight users: add a class that wiggles a button to get a user’s attention
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_animations.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_buttons.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/buttons._buttons.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/style-imports.commcarehq.style.diff.txt
Labels: product/all-users-all-environments

#36178 [Data Cleaning] Address any concurrency issues (or potential issues) and performance imrovements
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tests/test_session.py
  corehq/apps/data_cleaning/utils/decorators.py
Labels: product/feature-flag

#36188 [Data Cleaning] ensure that users in the same domain cannot swap session ids
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/data_cleaning/views/mixins.py
Labels: product/feature-flag

#36176 Python 3.13 compatibility - part 2
  corehq/apps/accounting/tests/test_customer_invoicing.py
  corehq/apps/api/tests/audit_resources.py
  corehq/apps/app_manager/tests/test_profile.py
  corehq/apps/app_manager/xform.py
  corehq/apps/es/management/commands/elastic_sync_multiplexed.py
  corehq/apps/userreports/tests/test_choice_provider.py
  corehq/apps/users/tests/test_views.py
  corehq/blobs/tests/test_fsdb.py
  corehq/blobs/tests/test_util.py
  corehq/ex-submodules/casexml/apps/case/mock/case_block.py
  corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py
  corehq/ex-submodules/dimagi/utils/couch/__init__.py
  corehq/motech/repeaters/models.py
  corehq/util/dates.py
  corehq/util/tests/test_jsonattrs.py
  corehq/util/workbook_reading/tests/files/csv/broken-utf-8.csv
  corehq/util/workbook_reading/tests/test_errors.py
  testapps/test_pillowtop/tests/test_grouptouser_pillow.py
Labels: product/invisible, Risk: High

#36191 [Data Cleaning] uncheck header checkbox if the number of records on the page is zero
  corehq/apps/data_cleaning/tables.py
Labels: product/feature-flag

#36195 [Data Cleaning] Prevent race conditions with column remove and sort
  corehq/apps/data_cleaning/templates/data_cleaning/forms/manage_columns_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/partials/column_list_item.html
Labels: product/feature-flag

#36194 [Data Cleaning] Prevent race conditions with filter remove and sort
  corehq/apps/data_cleaning/templates/data_cleaning/forms/manage_filters_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/partials/filter_list_item.html
Labels: product/feature-flag

#36187 Prominent Loading Bar Bug Fix
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
Labels: Risk: Medium

#36091 Lookup Table Limit Restore to Recently Modified
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/fixtures/migrations/0011_lookuptable_last_modified.py
  corehq/apps/fixtures/models.py
  corehq/apps/fixtures/resources/v0_1.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/fixtures/tests/test_upload.py
  corehq/apps/fixtures/upload/run_upload.py
  corehq/apps/fixtures/utils.py
  corehq/apps/fixtures/views.py
  corehq/apps/hqadmin/tests/test_raw_doc.py
  corehq/apps/linked_domain/updates.py
  corehq/apps/ota/tests/test_case_restore.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_fixtures.py
  corehq/ex-submodules/casexml/apps/phone/utils.py
  migrations.lock
Labels: reindex/migration, Risk: Medium

#36200 Support case-contact location SMS information
  corehq/apps/sms/api.py
  corehq/apps/users/cases.py
  corehq/apps/users/tests/test_cases.py
  corehq/motech/value_source.py
Labels: product/invisible

#36182 Remove es6 prefix and bootstrap 5 loader module
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
  corehq/apps/commtrack/static/commtrack/js/base_list_view_model.js
  corehq/apps/commtrack/static/commtrack/js/products_and_programs_main.js
  corehq/apps/export/static/export/js/customize_export_new.js
  corehq/apps/export/static/export/js/export_list.js
  corehq/apps/export/static/export/js/models.js
  corehq/apps/groups/static/groups/js/all_groups.js
  corehq/apps/groups/static/groups/js/group_members.js
  corehq/apps/hqwebapp/static/hqwebapp/js/500.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/common.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/crud_paginated_list.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/email-request.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/hq.helpers.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/inactivity.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/knockout_bindings.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/mobile_experience_warning.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/sticky_tabs.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5_loader.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/common.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/crud_paginated_list.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/email-request.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/hq.helpers.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/inactivity.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/knockout_bindings.ko.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/main.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/mobile_experience_warning.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/sticky_tabs.js.diff.txt
  corehq/apps/hqwebapp/tests/test_requirejs.py
  corehq/apps/hqwebapp/tests/utils/test_bootstrap_changes.py
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/js-modal.md
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/static/locations/js/location_tree.js
  corehq/apps/registry/static/registry/js/registry_edit.js
  corehq/apps/styleguide/static/styleguide/js/main.js
  webpack/webpack.common.js
Labels: product/invisible, Risk: Medium

#36181 Removed build-related requirejs code
  corehq/apps/hqwebapp/management/commands/build_requirejs.py
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/requirejs_config.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/static/hqwebapp/js/requirejs_webpack_fake.js
  corehq/apps/hqwebapp/static/hqwebapp/js/resource_versions.js
  corehq/apps/hqwebapp/static/hqwebapp/yaml/bootstrap3/requirejs.yml
  corehq/apps/hqwebapp/static/hqwebapp/yaml/bootstrap5/requirejs.yml
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/requirejs_config.js.diff.txt
  corehq/apps/hqwebapp/utils/bootstrap/paths.py
  corehq/apps/styleguide/templates/styleguide/bootstrap5/migration_guide.html
  package.json
  scripts/build-requirejs.sh
  yarn.lock
Labels: product/invisible, dependencies, Risk: High

#36190 [Data Cleaning] fix 404 error when filtering cases on page > 1
  corehq/apps/data_cleaning/views/tables.py
  corehq/apps/hqwebapp/tables/pagination.py
Labels: product/feature-flag

#36196 [Data Cleaning] UI for Clean Selected Records Form
  corehq/apps/data_cleaning/forms/cleaning.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/templates/data_cleaning/forms/clean_selected_records_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/offcanvas.html
  corehq/apps/data_cleaning/views/cleaning.py
  corehq/apps/data_cleaning/views/columns.py
Labels: product/feature-flag

#36208 Removed requirejs files from copy_required_static_files
  corehq/apps/hqwebapp/management/commands/copy_required_static_files.py
Labels: product/invisible

#36146 Dashboard Report
  corehq/apps/campaign/models.py
  corehq/apps/campaign/static/campaign/js/dashboard.js
  corehq/apps/campaign/templates/campaign/dashboard.html
  corehq/apps/campaign/templates/campaign/partials/dashboard_map.html
  corehq/apps/campaign/templates/campaign/partials/dashboard_report.html
  corehq/apps/campaign/tests/test_models.py
  corehq/apps/campaign/urls.py
  corehq/apps/campaign/views.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/datatables_config.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/standard_hq_report.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/userreports/js/base.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/userreports/base.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/userreports/partials/report_content.html.diff.txt
  corehq/apps/reports/static/reports/js/bootstrap3/datatables_config.js
  corehq/apps/reports/static/reports/js/bootstrap3/hq_report.js
  corehq/apps/reports/static/reports/js/bootstrap3/standard_hq_report.js
  corehq/apps/reports/static/reports/js/bootstrap5/datatables_config.js
  corehq/apps/reports/static/reports/js/bootstrap5/hq_report.js
  corehq/apps/reports/static/reports/js/bootstrap5/standard_hq_report.js
  corehq/apps/userreports/reports/view.py
  corehq/apps/userreports/static/userreports/js/bootstrap3/base.js
  corehq/apps/userreports/static/userreports/js/bootstrap5/base.js
  corehq/apps/userreports/templates/userreports/bootstrap3/base.html
  corehq/apps/userreports/templates/userreports/bootstrap5/base.html
  corehq/apps/userreports/templates/userreports/partials/bootstrap3/report_content.html
  corehq/apps/userreports/templates/userreports/partials/bootstrap5/report_content.html
Labels: product/invisible

#36177 Add optimizations for advance & shadow module
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/views/utils.py
Labels: product/feature-flag

#36210 [Data Cleaning] Improve user experience by drawing attention to buttons to fix common configuration issues
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_session.js
  corehq/apps/data_cleaning/templates/data_cleaning/forms/clean_selected_records_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/button_bar.html
  corehq/apps/data_cleaning/templates/data_cleaning/tables/table_with_controls.html
  corehq/apps/hqwebapp/static/hqwebapp/js/alpinejs/components/wiggle_button.js
Labels: product/feature-flag

#36211 [Data Cleaning] Add form validation to CleanSelectedRecordsForm
  corehq/apps/data_cleaning/forms/cleaning.py
Labels: product/feature-flag

#35881 Remove websockets
  Dockerfile
  corehq/apps/app_manager/templates/app_manager/form_designer.html
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/app_manager/views/formdesigner.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/app_manager/views/notifications.py
  corehq/util/context_processors.py
  deployment/websocket_wsgi.py
  requirements/dev-requirements.txt
  requirements/prod-requirements.in
  requirements/prod-requirements.txt
  requirements/test-requirements.in
  requirements/test-requirements.txt
  scripts/test-prod-entrypoints.sh
  settings.py
  settingshelper.py
Labels: product/invisible, dependencies

#36216 Constrain user input queries by domain
  corehq/apps/locations/models.py
  corehq/apps/locations/tests/test_location_queries.py
Labels: product/invisible

#36044 Restrict project access by IP address
  corehq/apps/domain/deletion.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/static/domain/js/ip_access_config.js
  corehq/apps/domain/templates/domain/admin/ip_access_config.html
  corehq/apps/domain/urls.py
  corehq/apps/domain/views/__init__.py
  corehq/apps/domain/views/settings.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/ip_access/__init__.py
  corehq/apps/ip_access/admin.py
  corehq/apps/ip_access/middleware.py
  corehq/apps/ip_access/migrations/0001_initial.py
  corehq/apps/ip_access/migrations/__init__.py
  corehq/apps/ip_access/models.py
  corehq/apps/ip_access/tests/__init__.py
  corehq/apps/ip_access/tests/test_config.py
  corehq/apps/ip_access/tests/test_middleware.py
  corehq/apps/locations/middleware.py
  corehq/apps/locations/permissions.py
  corehq/tabs/tabclasses.py
  corehq/toggles/__init__.py
  migrations.lock
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
  settings.py
Labels: reindex/migration, dependencies

#36220 [Data Cleaning] toggle enable/disable state of Clean Selected Cases button with selection state
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_session.js
  corehq/apps/data_cleaning/templates/data_cleaning/partials/button_bar.html
  corehq/apps/data_cleaning/templates/data_cleaning/tables/table_with_controls.html
Labels: product/feature-flag

#36219 `create_repeat_records` command supports doc IDs
  corehq/motech/management/commands/create_repeat_records.py
Labels: product/invisible

#36223 Restore build-essential to Dockerfile
  Dockerfile
Labels: product/invisible

#36224 Update dependency-metrics to 0.1.2
  requirements/dev-requirements.txt
Labels: dependencies

#36213 [Data Cleaning] Show an alert to the user when there are selected records not visible in the current filtered view
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/templates/data_cleaning/tables/table_with_controls.html
  corehq/apps/hqwebapp/tables/elasticsearch/tables.py
Labels: product/feature-flag

#36227 Revert "Lookup Table Limit Restore to Recently Modified"
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/fixtures/models.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/fixtures/tests/test_upload.py
  corehq/apps/fixtures/utils.py
  corehq/blobs/models.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_fixtures.py
  corehq/ex-submodules/casexml/apps/phone/utils.py
Labels: Risk: Medium

#36186 Reset flag on DataSourceConfig
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/userreports/edit_data_source.html.diff.txt
  corehq/apps/userreports/models.py
  corehq/apps/userreports/pillow.py
  corehq/apps/userreports/pillow_utils.py
  corehq/apps/userreports/sql/adapter.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/templates/userreports/bootstrap3/edit_data_source.html
  corehq/apps/userreports/tests/test_data_source_config.py
  corehq/apps/userreports/ui/forms.py
  corehq/apps/userreports/ui/help_text.py
  corehq/apps/userreports/views.py
Labels: product/invisible

#36225 Safe URL Sanitization: Check Full URL instead of substring
  corehq/motech/auth.py
Labels: product/feature-flag

#36115 Update Standard plan pricing, users, and privileges
  corehq/apps/accounting/bootstrap/config/standard_update_april_2025.py
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0101_update_standard_plan_pricing_users_and_privs.py
  corehq/apps/domain/views/accounting.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/apps/zapier/tests/test_create_update_cases_from_zapier.py
  corehq/apps/zapier/tests/test_utils.py
  corehq/apps/zapier/tests/test_zapier_forwarding.py
  corehq/apps/zapier/tests/test_zapier_hooks.py
  migrations.lock
Labels: reindex/migration, product/all-users-all-environments

#36201 Update wording and styles for community/free banner and plan label
  corehq/apps/accounting/user_text.py
  corehq/apps/domain/templates/domain/bootstrap3/current_subscription.html
  corehq/apps/domain/templates/domain/bootstrap5/current_subscription.html
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/alerts.less
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/label.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_alert.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_label.scss
  corehq/apps/hqwebapp/templates/hqwebapp/partials/community_banner.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/alerts._alert.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/label._label.style.diff.txt
Labels: product/all-users-all-environments

#36228 Lookup Fixture Missing on Restore Bug Fix
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/fixtures/models.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/fixtures/tests/test_upload.py
  corehq/apps/fixtures/utils.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_fixtures.py
  corehq/ex-submodules/casexml/apps/phone/utils.py
Labels: Risk: Medium

#36229 [Data Cleaning] Functionality to stage edits on selected records after CleanSelectedRecordsForm submission
  corehq/apps/data_cleaning/forms/cleaning.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/templates/data_cleaning/forms/clean_selected_records_form.html
  corehq/apps/data_cleaning/views/cleaning.py
Labels: product/feature-flag

#36240 Revert "Lookup Fixture Missing on Restore Bug Fix"
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/fixtures/models.py
  corehq/apps/fixtures/tests/test_fixture_data.py
  corehq/apps/fixtures/tests/test_upload.py
  corehq/apps/fixtures/utils.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_fixtures.py
  corehq/ex-submodules/casexml/apps/phone/utils.py
Labels: Risk: Medium

#36238 Fix : Payment report is not visible while assigning permission to roles
  corehq/apps/users/permissions.py
Labels: product/feature-flag

#36241 Added dev_mode to vellum-to-hq
  scripts/vellum-to-hq
Labels: product/invisible

#36239 [Data Cleaning] Diff view for edited columns + system column UI
  corehq/apps/data_cleaning/records.py
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/templates/data_cleaning/clean_cases_session.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/column_editable.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/column_main.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/column_system.html
  corehq/apps/data_cleaning/templatetags/data_cleaning.py
  corehq/apps/hqwebapp/static/hqwebapp/scss/data_cleaning.scss
Labels: product/feature-flag

#36243 There's always a followup commit
  scripts/vellum-to-hq
Labels: product/invisible

#36244 Update links to payment info in downgrade emails
  corehq/apps/accounting/templates/accounting/email/downgrade.html
  corehq/apps/accounting/templates/accounting/email/downgrade.txt
  corehq/apps/accounting/templates/accounting/email/downgrade_warning.html
  corehq/apps/accounting/templates/accounting/email/downgrade_warning.txt
  corehq/apps/accounting/templates/accounting/email/overdue_notice.html
  corehq/apps/accounting/templates/accounting/email/overdue_notice.txt
Labels: product/invisible

#36248 Retry mounting Stripe UI after template containing it is rendered.
  corehq/apps/accounting/static/accounting/js/payment_method_handler.js
  corehq/apps/domain/templates/domain/partials/bootstrap3/payment_modal.html
  corehq/apps/domain/templates/domain/partials/bootstrap5/payment_modal.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/partials/payment_modal.html.diff.txt
Labels: product/all-users-all-environments

#36247 [Data Cleaning] Small code cleanups for requests from previous PR feedback
  corehq/apps/data_cleaning/records.py
  corehq/apps/data_cleaning/templates/data_cleaning/columns/column_editable.html
  corehq/apps/data_cleaning/templatetags/data_cleaning.py
Labels: product/feature-flag

#36106 Back off on fewer errors
  corehq/motech/openmrs/repeaters.py
  corehq/motech/repeater_helpers.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_models_slow.py
  corehq/motech/repeaters/tests/test_repeater.py
  corehq/motech/repeaters/tests/test_server_errors.py
Labels: product/invisible

#36204 Add case type modal
  corehq/apps/app_manager/dbaccessors.py
  corehq/apps/app_manager/static/app_manager/js/app_manager.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/templates/app_manager/apps_base.html
  corehq/apps/app_manager/templates/app_manager/partials/define_case_type_modal.html
  corehq/apps/app_manager/templates/app_manager/partials/menu/appnav_menu.html
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/modules.py
  corehq/apps/reports/analytics/esaccessors.py
Labels: product/all-users-all-environments

#36250 Remove usage of pygithub then remove pygithub
  corehq/apps/builds/management/commands/add_commcare_build.py
  corehq/apps/builds/tests.py
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#36249 Add zero-width spaces after underscores in custom data field labels
  corehq/apps/custom_data_fields/edit_entity.py
Labels: product/all-users-all-environments, Risk: Medium

#36122 Docs for v2 Case API
  corehq/apps/case_search/migrations/0011_domainsnotincasesearchindex.py
  corehq/apps/hqcase/tests/test_case_api_bulk_get.py
  corehq/apps/hqcase/tests/test_case_api_permissions.py
  corehq/apps/hqcase/tests/test_case_update_api.py
  corehq/apps/hqcase/views.py
  corehq/toggles/__init__.py
  docs/api/bulk-upload-cases.rst
  docs/api/case-data.rst
  docs/api/cases-v1.rst
  docs/api/cases-v2.rst
  docs/api/index.rst
Labels: reindex/migration

#36258 [Data Cleaning] value styling and whitespaces
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_session.js
  corehq/apps/data_cleaning/templates/data_cleaning/clean_cases_session.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/column_editable.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/values/empty.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/values/null.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/values/text.html
  corehq/apps/data_cleaning/templatetags/data_cleaning.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/hqwebapp/static/hqwebapp/scss/data_cleaning.scss
Labels: product/feature-flag

#36257 vellum:0b0aea9f81acbd050e39aa857be273713ae9ea0b
  corehq/apps/app_manager/static/app_manager/js/vellum/lib/ckeditor/un-minified-ckeditor.js
  corehq/apps/app_manager/static/app_manager/js/vellum/manifest.txt
  corehq/apps/app_manager/static/app_manager/js/vellum/src/main-components.js
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: product/all-users-all-environments

#36124 Upgrade celery==5.4.0 (also upgrade related dependencies)
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#36260 Create migration to enable slow logs
  corehq/apps/es/migrations/0014_enable_slowlogs.py
  migrations.lock
Labels: reindex/migration

#36262 Fix case type modal shrinking after selecting a case type
  corehq/apps/app_manager/templates/app_manager/partials/define_case_type_modal.html
Labels: product/all-users-all-environments

#36256 Show timing profile for Case List Explorer
  corehq/apps/case_search/tests/test_utils.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/README.rst
  corehq/apps/es/profiling.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/datatables_config.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/standard/base_template.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/tabular.html.diff.txt
  corehq/apps/reports/generic.py
  corehq/apps/reports/standard/__init__.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/cases/duplicate_cases.py
  corehq/apps/reports/static/reports/css/timing-profile.css
  corehq/apps/reports/static/reports/js/bootstrap3/datatables_config.js
  corehq/apps/reports/static/reports/js/bootstrap5/datatables_config.js
  corehq/apps/reports/templates/reports/bootstrap3/tabular.html
  corehq/apps/reports/templates/reports/bootstrap5/tabular.html
  corehq/apps/reports/templates/reports/standard/bootstrap3/base_template.html
  corehq/apps/reports/templates/reports/standard/bootstrap5/base_template.html
  corehq/apps/reports/tests/standard/test_mixins.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#36267 Fix filtered mobile worker download
  corehq/apps/users/bulk_download.py
  corehq/apps/users/dbaccessors.py
  corehq/apps/users/tests/test_dbaccessors.py
Labels: product/invisible

#36273 [Data Cleaning] clarify number shown next to Edits
  corehq/apps/data_cleaning/templates/data_cleaning/tables/table_with_controls.html
Labels: product/feature-flag

#36279 Call task after super.save()
  corehq/apps/app_manager/models.py
Labels: product/all-users-all-environments

#36272 [Data Cleaning] update user-facing text on EditActionType choices
  corehq/apps/data_cleaning/migrations/0006_alter_bulkeditchange_action_type.py
  corehq/apps/data_cleaning/models.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#36265 Update placeholder text
  corehq/apps/app_manager/static/app_manager/js/app_manager.js
Labels: product/all-users-all-environments

#36281 [Data Cleaning] Add placeholders for edit action confirmation modals.
  corehq/apps/data_cleaning/templates/data_cleaning/modals/base_confirm.html
  corehq/apps/data_cleaning/templates/data_cleaning/modals/confirm_apply.html
  corehq/apps/data_cleaning/templates/data_cleaning/modals/confirm_clear.html
  corehq/apps/data_cleaning/templates/data_cleaning/modals/confirm_undo.html
  corehq/apps/data_cleaning/templates/data_cleaning/summary/apply_changes.html
  corehq/apps/data_cleaning/templates/data_cleaning/summary/clear_changes.html
  corehq/apps/data_cleaning/templates/data_cleaning/summary/undo_changes.html
  corehq/apps/data_cleaning/templates/data_cleaning/tables/table_with_controls.html
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/views/summary.py
  corehq/apps/data_cleaning/views/tables.py
Labels: product/feature-flag

#36280 [Data Cleaning] Fix get_edited_case_properties after changes are removed
  corehq/apps/data_cleaning/models.py
Labels: product/feature-flag

#36283 [Data Cleaning] Implement undo functionality
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_session.js
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/templates/data_cleaning/tables/table_with_controls.html
  corehq/apps/data_cleaning/views/tables.py
Labels: product/feature-flag

#36284 [Data Cleaning] update undo changes summary modal UI
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/templates/data_cleaning/summary/undo_changes.html
  corehq/apps/data_cleaning/views/summary.py
Labels: product/feature-flag

#36231 Restrict optimizations to calculated properties only
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/tests/test_suite.py
Labels: QA Passed, product/feature-flag

#36289 [Data Cleaning] Implement "clear" functionality
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/views/tables.py
Labels: product/feature-flag

#36291 Removed appcues from form_designer.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_designer.js
Labels: product/invisible

#36292 Upgrade to cffi==1.17.1
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#36296 Upgrade tar-fs subdependency
  package.json
  yarn.lock
Labels: product/invisible, dependencies, dependencies/javascript

#36293 [Data Cleaning] "apply" changes functionality
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/views/setup.py
  corehq/apps/data_cleaning/views/tables.py
  corehq/util/htmx_action.py
Labels: product/feature-flag

#36294 [Data Cleaning] Complete the UI for the "apply" confirmation modal
  corehq/apps/data_cleaning/templates/data_cleaning/summary/apply_changes.html
  corehq/apps/data_cleaning/templates/data_cleaning/summary/clear_changes.html
  corehq/apps/data_cleaning/templates/data_cleaning/summary/partial/change_detail.html
  corehq/apps/data_cleaning/templates/data_cleaning/summary/partial/change_history.html
  corehq/apps/data_cleaning/views/summary.py
Labels: product/feature-flag
