Repository dimagi/commcare-hq, pull requests merged in 2025-03, with the labels that each got.

#35797 Add "KYC Status" and "Last Verified" columns
  corehq/apps/integration/kyc/tables.py
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/kyc/views.py
  corehq/apps/integration/templates/kyc/partials/kyc_verify_status.html
Labels: product/invisible

#35870 Use QuerySet method
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/kyc/views.py
Labels: product/invisible

#35774 KYC Service Layer
  corehq/apps/integration/kyc/forms.py
  corehq/apps/integration/kyc/models.py
  corehq/apps/integration/kyc/schemas/kyc-verify-v1.json
  corehq/apps/integration/kyc/services.py
  corehq/apps/integration/kyc/tests/test_models.py
  corehq/apps/integration/kyc/tests/test_services.py
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/kyc/views.py
  corehq/apps/integration/migrations/0009_alter_kycconfig_connection_settings.py
  corehq/apps/integration/migrations/0010_alter_kycconfig_api_field_to_user_data_map.py
  migrations.lock
  settings.py
Labels: reindex/migration, product/invisible

#35856 Bump jsonobject to 2.3.1
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#35866 Add Bulk Edit Pinned Filter UIs (part one)
  corehq/apps/data_cleaning/filters.py
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_session.js
  corehq/apps/data_cleaning/templates/data_cleaning/filters/pinned/base.html
  corehq/apps/data_cleaning/templates/data_cleaning/filters/pinned/multi_option.html
  corehq/apps/data_cleaning/templates/data_cleaning/filters/pinned/single_option.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/pinned_filter_form.html
  corehq/apps/data_cleaning/tests/test_filters.py
  corehq/apps/data_cleaning/views/filters.py
  corehq/apps/hqwebapp/static/hqwebapp/js/alpinejs/directives/report_select2.js
  corehq/apps/hqwebapp/static/hqwebapp/js/alpinejs/directives/select2.js
Labels: product/feature-flag

#35871 Added BULK_DATA_CLEANING privilege
  corehq/apps/accounting/bootstrap/features.py
  corehq/apps/accounting/migrations/0099_data_cleaning_priv.py
  corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py
  corehq/privileges.py
  migrations.lock
Labels: reindex/migration, product/invisible

#35874 Use RegexField for two-factor setup
  corehq/apps/settings/forms.py
Labels: product/invisible

#35836 Updated psycopg2 to 2.9.10
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#35853 Capture metrics for KYC User verification
  corehq/apps/integration/kyc/exceptions.py
  corehq/apps/integration/kyc/models.py
  corehq/apps/integration/kyc/services.py
  corehq/apps/integration/kyc/tests/test_models.py
  corehq/apps/integration/kyc/tests/test_services.py
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/kyc/views.py
  corehq/apps/integration/tasks.py
Labels: Open for review: do not merge, product/feature-flag, product/invisible

#35879 Do not forward forms for excluded users
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_models.py
Labels: product/invisible

#35873 Validate lookup table field names
  corehq/apps/fixtures/tests/test_field_names.py
  corehq/apps/fixtures/tests/test_upload.py
  corehq/apps/fixtures/upload/failure_messages.py
  corehq/apps/fixtures/upload/workbook.py
  corehq/apps/fixtures/utils.py
  corehq/apps/fixtures/views.py
Labels: product/invisible, Risk: Medium

#35134 Add UserAudit for user activation and deactivation
  corehq/apps/sso/backends.py
  corehq/apps/sso/tasks.py
  corehq/const.py
Labels: product/feature-flag

#35755 Add Case List Optimizations
  corehq/apps/app_manager/const.py
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/feature_support.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/suite_xml/xml_models.py
  corehq/apps/app_manager/templates/app_manager/module_view.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_settings.html
  corehq/apps/app_manager/tests/test_suite.py
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/app_manager/views/modules.py
  corehq/toggles/__init__.py
Labels: QA Passed, product/feature-flag, Core Compatibility

#35890 Standardize Domain Name across Enterprise APIs
  corehq/apps/enterprise/api/resources.py
  corehq/apps/enterprise/tests/api/test_resources.py
Labels: product/admin

#35883 Use get_menu_item_label for CommCare Version display in Manage Update Settings
  corehq/apps/app_manager/forms.py
  corehq/apps/builds/management/commands/add_commcare_build.py
Labels: product/all-users-all-environments

#35824 Web User API + Mobile Worker API - Last Modified Field
  corehq/apps/api/resources/v0_1.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/test_user_resources.py
  corehq/apps/es/mappings/user_mapping.py
  corehq/apps/es/migrations/0013_add_last_modifed.py
  corehq/apps/es/users.py
  corehq/motech/repeaters/tests/test_repeater.py
  migrations.lock
Labels: reindex/migration, Risk: High

#35897 Partial Revert "Web User API + Mobile Worker API - Last Modified Field"
  corehq/apps/api/resources/v0_1.py
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/test_user_resources.py
  corehq/apps/es/users.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: Risk: High

#35885 Tweaks to mobile worker actions page
  corehq/apps/hqwebapp/static/hqwebapp/less/b5-compatibility.less
  corehq/apps/users/templates/users/edit_commcare_user.html
Labels: product/all-users-all-environments

#35896 Visual improvements to app version comment box
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_table.html
  corehq/apps/hqwebapp/static/app_manager/less/panel.less
Labels: product/all-users-all-environments

#35901 Create Campaign Dashboard Django App
  corehq/apps/campdash/__init__.py
  corehq/apps/campdash/admin.py
  corehq/apps/campdash/apps.py
  corehq/apps/campdash/migrations/__init__.py
  corehq/apps/campdash/models.py
  corehq/apps/campdash/tests/__init__.py
  corehq/apps/campdash/urls.py
  corehq/apps/campdash/views.py
  migrations.lock
  settings.py
  urls.py
Labels: reindex/migration, product/feature-flag, product/invisible

#35791 Update "Number of overdue repeat records" metric
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_models.py
Labels: product/invisible

#35903 Revert "Updated cloudcare's date format to be more universal"
  corehq/apps/cloudcare/static/cloudcare/js/utils.js
Labels: Risk: Medium

#35902 Use dropdown for the Other case type field in KYC Config Page
  corehq/apps/integration/kyc/forms.py
  corehq/apps/integration/kyc/tests/test_views.py
Labels: product/feature-flag

#35839 Updated markupsafe to 3.0.2
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: QA Passed, product/invisible, dependencies

#35908 Fix error preventing viewing application at specific version
  corehq/apps/app_manager/dbaccessors.py
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/templates/app_manager/app_view_release_manager.html
  corehq/apps/cloudcare/urls.py
  corehq/apps/cloudcare/utils.py
  corehq/apps/cloudcare/views.py
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
Labels: product/invisible, Risk: Medium

#35876 On app save, update data dictionary with case types and properties
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tasks.py
  corehq/apps/app_manager/tests/test_apps.py
  corehq/apps/app_manager/tests/test_tasks.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/data_dictionary/util.py
Labels: product/all-users-all-environments

#35919 Increase export page limit from 10 to 5000
  corehq/apps/reports/const.py
  corehq/apps/reports/generic.py
Labels: product/invisible

#35918 Show Dashboard link even if project has no apps
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments

#35924 Campaign app refactor
  corehq/apps/campaign/__init__.py
  corehq/apps/campaign/admin.py
  corehq/apps/campaign/apps.py
  corehq/apps/campaign/migrations/__init__.py
  corehq/apps/campaign/models.py
  corehq/apps/campaign/tests/__init__.py
  corehq/apps/campaign/urls.py
  corehq/apps/campaign/views.py
  migrations.lock
  settings.py
  urls.py
Labels: reindex/migration

#35907 Implement CaseSearchES Filtering for `BulkEditPinnedFilter`s
  corehq/apps/data_cleaning/filters.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tests/test_filters.py
  corehq/apps/data_cleaning/tests/test_session.py
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/utils.py
  corehq/apps/reports/tests/standard/cases/test_utils.py
  corehq/apps/reports/v2/filters/case_report.py
  custom/inddex/food.py
Labels: product/feature-flag, product/invisible

#35928 Data cleaning tasks table improvements
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tasks.py
  corehq/apps/data_cleaning/tests/test_tasks.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/data_cleaning/views/tables.py
Labels: product/feature-flag

#35925 Add Campaign dashboard template
  corehq/apps/campaign/templates/campaign/dashboard.html
  corehq/apps/campaign/urls.py
  corehq/apps/campaign/views.py
  corehq/tabs/tabclasses.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#35911 Drops Connecttion Settings from KYC Config
  corehq/apps/integration/kyc/forms.py
  corehq/apps/integration/kyc/models.py
  corehq/apps/integration/kyc/tests/test_models.py
  corehq/apps/integration/kyc/tests/test_services.py
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/migrations/0011_remove_kycconfig_connection_settings.py
  corehq/motech/models.py
  corehq/motech/repeaters/tests/test_models.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#35931 Move report_type from ReportBuilderView to report
  corehq/apps/userreports/models.py
  corehq/apps/userreports/tests/test_report_configuration.py
  corehq/apps/userreports/views.py
Labels: product/invisible

#35933 Added case_load_counter to bulk data cleaning
  corehq/apps/data_cleaning/tasks.py
Labels: product/invisible

#35926 Delete UI models when committing session
  corehq/apps/data_cleaning/tasks.py
  corehq/apps/data_cleaning/tests/test_tasks.py
Labels: product/invisible

#35916 Show retry date for records that will be retried
  corehq/apps/cleanup/management/commands/fire_repeaters.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/motech/repeaters/const.py
  corehq/motech/repeaters/management/commands/delete_duplicate_cancelled_records.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_display.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_models_slow.py
  corehq/motech/repeaters/views/repeat_record_display.py
  corehq/motech/repeaters/views/repeat_records.py
  corehq/motech/repeaters/views/repeaters.py
Labels: product/invisible

#35937 Campaign dashboard models (rebased)
  corehq/apps/campaign/migrations/0001_initial.py
  corehq/apps/campaign/migrations/0002_dashboardmap_dashboardreport.py
  corehq/apps/campaign/models.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  migrations.lock
Labels: reindex/migration, product/invisible

#35943 auto-refresh CleanCaseTable after pinned filters are updated
  corehq/apps/data_cleaning/templates/data_cleaning/forms/pinned_filter_form.html
Labels: product/feature-flag

#35915 Payment cases can be verified in bulk
  corehq/apps/integration/payments/services.py
  corehq/apps/integration/payments/tests/test_services.py
  corehq/apps/integration/payments/tests/test_views.py
  corehq/apps/integration/payments/views.py
Labels: product/invisible

#35941 Add Column Filter UI (Bulk Data Cleaning) - Part One
  corehq/apps/app_manager/models.py
  corehq/apps/data_cleaning/forms/filters.py
  corehq/apps/data_cleaning/migrations/0004_alter_bulkeditcolumn_data_type_and_more.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_session.js
  corehq/apps/data_cleaning/static/data_cleaning/js/directives/dynamic_options_select2.js
  corehq/apps/data_cleaning/templates/data_cleaning/forms/column_filter_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/offcanvas.html
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/utils/__init__.py
  corehq/apps/data_cleaning/utils/cases.py
  corehq/apps/data_cleaning/views/filters.py
  corehq/apps/data_dictionary/models.py
  corehq/apps/hqwebapp/static/hqwebapp/js/alpinejs/directives/select2.js
  migrations.lock
Labels: reindex/migration, product/feature-flag

#35939 More improvements to data cleaning tasks table
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/templates/data_cleaning/columns/task_form_ids.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/task_status.html
  corehq/apps/data_cleaning/tests/test_tasks.py
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/data_cleaning/views/tables.py
Labels: product/feature-flag

#35929 Added case type tooltip to case modules
  corehq/apps/app_manager/templates/app_manager/partials/menu/module_link.html
Labels: product/all-users-all-environments

#35946 Fixed some cloud arrow icons
  corehq/apps/data_cleaning/templates/data_cleaning/columns/task_form_ids.html
  corehq/apps/styleguide/context.py
Labels: product/feature-flag

#35910 Change two-factor setup field to use TextInput widget
  corehq/apps/settings/forms.py
  corehq/apps/settings/tests/test_forms.py
Labels: product/all-users-all-environments

#35948 Finish UI for Add Column Filter Form
  corehq/apps/data_cleaning/forms/filters.py
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_session.js
  corehq/apps/data_cleaning/static/data_cleaning/js/directives/dynamic_options_select2.js
  corehq/apps/hqwebapp/static/hqwebapp/js/alpinejs/directives/datepicker.js
Labels: product/feature-flag

#35954 Support shadow forms in refresh_data_dictionary_from_app
  corehq/apps/app_manager/tasks.py
  corehq/apps/app_manager/tests/test_tasks.py
Labels: product/invisible

#35950 Bulk data cleaning: gate based on permission + privilege + flag
  corehq/apps/data_cleaning/decorators.py
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/views/filters.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/data_cleaning/views/setup.py
  corehq/apps/data_cleaning/views/tables.py
  corehq/tabs/tabclasses.py
  corehq/util/test_utils.py
Labels: product/invisible

#35959 Disable Interval Sync
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
  corehq/toggles/__init__.py
Labels: Risk: Medium

#35945 Dashboard widgets need to know their tab
  corehq/apps/campaign/migrations/0003_add_dashboard_widget_fields.py
  corehq/apps/campaign/models.py
  corehq/apps/campaign/tests/test_models.py
  migrations.lock
Labels: reindex/migration, product/invisible

#35964 vellum:c0e55d16572d5b458e70eb132de92dc1fcdbfe82
  corehq/apps/app_manager/static/app_manager/js/vellum/lib/ckeditor/un-minified-ckeditor.js
  corehq/apps/app_manager/static/app_manager/js/vellum/manifest.txt
  corehq/apps/app_manager/static/app_manager/js/vellum/src/main-components.js
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: product/invisible

#35960 update toggle tag for new adoption
  corehq/toggles/__init__.py
Labels: product/invisible

#35965 Update vellum-to-hq to not skip ci
  scripts/vellum-to-hq
Labels: product/admin

#35938 Adds ReadTheDocs documentation for KYC Configuration and Links it to the UI
  corehq/apps/integration/kyc/forms.py
  docs/index.rst
  docs/integrations/kyc.rst
Labels: product/feature-flag

#35962 Add comment to make schema searchable
  corehq/apps/integration/kyc/services.py
Labels: product/invisible

#35976 Shrink and center dashboard icons
  corehq/apps/dashboard/templates/dashboard/base.html
  corehq/apps/hqwebapp/static/dashboard/scss/dashboard-main.scss
Labels: product/all-users-all-environments

#35975 Resolve Docker warning
  docker/hq-compose-os-default.yml
  docker/hq-compose-os-macos-m1-11.yml
  docker/hq-compose-os-macos-m1-12.yml
  docker/hq-compose-runserver.yml
  docker/hq-compose-services.yml
  docker/hq-compose.yml
Labels: product/invisible

#35953 Campaign Dashboard Map Widget UI
  corehq/apps/campaign/static/campaign/js/dashboard.js
  corehq/apps/campaign/templates/campaign/dashboard.html
  corehq/apps/campaign/templates/campaign/partials/dashboard_map.html
  corehq/apps/campaign/tests/test_views.py
  corehq/apps/campaign/urls.py
  corehq/apps/campaign/views.py
  corehq/apps/geospatial/static/geospatial/js/models.js
  corehq/apps/geospatial/templates/geospatial/base_template.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/hq_report.js.diff.txt
  corehq/apps/reports/static/reports/js/bootstrap3/hq_report.js
  corehq/apps/reports/static/reports/js/bootstrap5/hq_report.js
Labels: product/feature-flag

#35955 Add custom headers to connection settings
  corehq/motech/auth.py
  corehq/motech/forms.py
  corehq/motech/migrations/0019_connectionsettings_custom_headers.py
  corehq/motech/models.py
  corehq/motech/requests.py
  corehq/motech/static/motech/js/connection_settings_detail.js
  corehq/motech/tests/test_models.py
  corehq/motech/tests/test_requests.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#35961 MTN MoMo payment config
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/integration/migrations/0012_momoconfig.py
  corehq/apps/integration/models.py
  corehq/apps/integration/payments/forms.py
  corehq/apps/integration/payments/models.py
  corehq/apps/integration/payments/tests/test_views.py
  corehq/apps/integration/payments/urls.py
  corehq/apps/integration/payments/views.py
  corehq/apps/integration/templates/payments/partials/payments_config_form_partial.html
  corehq/apps/integration/templates/payments/payments_config_base.html
  corehq/tabs/tabclasses.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#35974 Removed $ from HTML bindings
  corehq/apps/app_manager/templates/app_manager/partials/forms/form_filter.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_search_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_filter.html
Labels: product/invisible

#35973 Check that case search is enabled before displaying on case list
  corehq/apps/app_manager/static/app_manager/js/details/screen_config.js
  corehq/apps/app_manager/templates/app_manager/module_view.html
Labels: product/invisible

#35971 AddColumnFilterForm - form validation and UI bugfixes for POSTed/validated states
  corehq/apps/data_cleaning/forms/filters.py
  corehq/apps/data_cleaning/static/data_cleaning/js/directives/dynamic_options_select2.js
  corehq/apps/data_cleaning/views/filters.py
  corehq/apps/data_cleaning/views/setup.py
  corehq/apps/hqwebapp/static/hqwebapp/js/alpinejs/directives/datepicker.js
  corehq/apps/hqwebapp/widgets.py
Labels: product/feature-flag

#35972 Fix validation state multi-select select2 scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_select2.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/select2s._select2.style.diff.txt
Labels: product/all-users-all-environments

#35985 Correct use of `use` decorator
  corehq/apps/campaign/tests/test_models.py
Labels: product/invisible

#35936 When AuthnContext not match request a fresh authentication
  corehq/apps/sso/views/saml.py
Labels: QA Passed

#35984 Notify user when MoMo config is not configured
  corehq/apps/integration/payments/views.py
  corehq/apps/integration/templates/payments/payments_verify_report.html
Labels: product/feature-flag

#35992 Resolve Invalid Jquery Selector Bootstrap 3
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/hq_report.js.diff.txt
  corehq/apps/reports/static/reports/js/bootstrap3/hq_report.js
Labels: product/invisible

#35993 Add Code Owner for Geospatial Feature
  .github/CODEOWNERS
Labels: product/invisible

#35944 Visual change for button
  corehq/apps/app_manager/templates/app_manager/form_designer.html
  corehq/apps/hqwebapp/static/app_manager/less/form_editing.less
Labels: product/all-users-all-environments

#35994 Added langcodes to knockout bindings
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/knockout_bindings.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/knockout_bindings.ko.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/knockout_bindings.ko.js.diff.txt
Labels: product/invisible

#35996 Removed CommcareSettings.widgets.text_input
  corehq/apps/app_manager/templates/app_manager/partials/settings/app_settings.html
Labels: product/invisible

#35949 Add gauge model for campaign dashboard
  corehq/apps/campaign/const.py
  corehq/apps/campaign/migrations/0004_gauge.py
  corehq/apps/campaign/models.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  migrations.lock
Labels: reindex/migration, product/feature-flag, product/invisible

#35989 [Data Cleaning] Manage Filters Functionality & Quick Refactor
  corehq/apps/data_cleaning/exceptions.py
  corehq/apps/data_cleaning/forms/filters.py
  corehq/apps/data_cleaning/migrations/0005_rename_bulkeditcolumnfilter_bulkeditfilter.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tasks.py
  corehq/apps/data_cleaning/templates/data_cleaning/filters/list_item.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/column_filter_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/manage_filters_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/offcanvas.html
  corehq/apps/data_cleaning/tests/test_filters.py
  corehq/apps/data_cleaning/tests/test_session.py
  corehq/apps/data_cleaning/tests/test_tasks.py
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/views/filters.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#35980 create channel property and add caching
  corehq/apps/sms/models.py
  corehq/apps/users/models.py
  corehq/messaging/smsbackends/connectid/backend.py
Labels: product/invisible

#35982 KYC Dynamic Report Columns
  corehq/apps/integration/kyc/models.py
  corehq/apps/integration/kyc/services.py
  corehq/apps/integration/kyc/tables.py
  corehq/apps/integration/kyc/tests/test_tables.py
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/kyc/views.py
Labels: product/feature-flag

#36003 Make duration comparison less likely to be flaky
  corehq/apps/experiments/tests/test_experiment.py
Labels: product/invisible

#36006 Upgrade wrapt to 1.17.2
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#36007 Upgrade to zope-interface==7.2
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#36012 Upgrade to python-mimeparse>=2.0.0
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#36008 [Data Cleaning] Improve Filter List UI and Re-Order/Sort Filters
  corehq/apps/data_cleaning/forms/filters.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_session.js
  corehq/apps/data_cleaning/templates/data_cleaning/filters/formatted_value.html
  corehq/apps/data_cleaning/templates/data_cleaning/filters/list_item.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/manage_filters_form.html
  corehq/apps/data_cleaning/templatetags/__init__.py
  corehq/apps/data_cleaning/templatetags/data_cleaning_filters.py
  corehq/apps/data_cleaning/tests/test_session.py
  corehq/apps/data_cleaning/views/filters.py
  corehq/apps/hqwebapp/static/hqwebapp/js/alpinejs/directives/htmx_sortable.js
  corehq/apps/hqwebapp/static/hqwebapp/js/alpinejs/directives/tooltip.js
  package.json
  yarn.lock
Labels: product/feature-flag, dependencies

#36009 Get underscore out of HTML in icon display properties
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap3/key_value_mapping.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/key_value_mapping.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/partials/key_value_mapping.html.diff.txt
Labels: product/invisible

#36005 Combine app_view.js and app_view_application.js
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/static/app_manager/js/app_view_application.js
  corehq/apps/app_manager/templates/app_manager/app_view.html
Labels: product/invisible

#36021 Support #parent in case list filter
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/suite_xml/sections/entries.py
  corehq/apps/app_manager/tests/test_child_module.py
  corehq/apps/app_manager/xpath.py
Labels: product/all-users-all-environments

#36004 Bring back cross-cutting skip_fixtures logic
  corehq/apps/case_search/fixtures.py
  corehq/apps/fixtures/fixturegenerators.py
  corehq/apps/ota/views.py
  corehq/ex-submodules/casexml/apps/phone/fixtures.py
  corehq/ex-submodules/casexml/apps/phone/restore.py
  corehq/ex-submodules/casexml/apps/phone/tests/test_ota_fixtures.py
Labels: Risk: Medium

#36024 Upgrade hiredis==3.1.0
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#35923 Add module name to other logs
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/gtx.js
Labels: Risk: Medium

#36023 [Data Cleaning] Adds basic UI for managing columns
  corehq/apps/data_cleaning/forms/columns.py
  corehq/apps/data_cleaning/templates/data_cleaning/forms/manage_columns_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/partials/column_list_item.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/offcanvas.html
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/views/columns.py
Labels: product/feature-flag

#36020 [Data Cleaning] Cleanup references to "column filter" and related mini refactoring
  corehq/apps/data_cleaning/forms/filters.py
  corehq/apps/data_cleaning/templates/data_cleaning/forms/manage_filters_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/partials/filter_list_item.html
  corehq/apps/data_cleaning/views/filters.py
Labels: product/feature-flag

#36029 Add option to process only open cases
  corehq/apps/userreports/management/commands/async_rebuild_table.py
Labels: product/invisible

#35967 Removed notifications from form builder
  corehq/apps/app_manager/static/app_manager/js/forms/form_designer.js
Labels: product/admin

#36033 Add optimizations in suite file when supported at module level
  corehq/apps/app_manager/detail_screen.py
  corehq/apps/app_manager/suite_xml/sections/details.py
  corehq/apps/app_manager/tests/test_suite.py
Labels: product/feature-flag

#35978 Add email notification for unpaid invoices due soon
  corehq/apps/accounting/const.py
  corehq/apps/accounting/migrations/0100_alter_customerinvoicecommunicationhistory_communication_type_and_more.py
  corehq/apps/accounting/mixins.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/templates/accounting/email/invoice_reminder.html
  corehq/apps/accounting/templates/accounting/email/invoice_reminder.txt
  corehq/apps/accounting/tests/test_unpaid_invoice.py
  corehq/apps/accounting/utils/downgrade.py
  corehq/apps/accounting/utils/invoicing.py
  corehq/apps/accounting/utils/unpaid_invoice.py
  corehq/apps/accounting/views.py
  corehq/apps/domain/views/accounting.py
  migrations.lock
Labels: reindex/migration, product/all-users-all-environments

#32864 Migration to invoke command for syncing couch and es webusers
  corehq/ex-submodules/pillowtop/migrations/0008_sync_es_with_couch_webusers.py
  migrations.lock
Labels: reindex/migration

#36037 Revert "Migration to invoke command for syncing couch and es webusers"
  corehq/ex-submodules/pillowtop/migrations/0008_sync_es_with_couch_webusers.py
  migrations.lock
Labels: reindex/migration

#36031 Combined apps_base.js, managed_app.js, and app_manager.js
  corehq/apps/app_manager/static/app_manager/js/app_manager.js
  corehq/apps/app_manager/static/app_manager/js/apps_base.js
  corehq/apps/app_manager/static/app_manager/js/managed_app.js
  corehq/apps/app_manager/templates/app_manager/apps_base.html
Labels: product/invisible

#36040 Fix bug in BS3 async.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/async.js.diff.txt
  corehq/apps/reports/static/reports/js/bootstrap3/async.js
Labels: product/invisible

#36042 Update Kafka image to avoid NullPointerException
  docker/hq-compose.yml
Labels: product/invisible

#36019 Upgrade botocore==1.37.15
  corehq/blobs/__init__.py
  corehq/blobs/tests/util.py
  dev_settings.py
  docker/localsettings.py
  docker/min_settings.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#36015 Upgrade freezegun==1.5.1
  requirements/dev-requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#36045 Add deleted_on field to SQLUserData
  corehq/apps/users/migrations/0078_sqluserdata_deleted_on.py
  corehq/apps/users/user_data.py
  migrations.lock
Labels: reindex/migration

#36055 Improve basic HTMX error template
  corehq/apps/hqwebapp/static/hqwebapp/js/htmx_base.js
  corehq/apps/hqwebapp/static/hqwebapp/js/htmx_utils/errors.js
  corehq/apps/hqwebapp/templates/hqwebapp/htmx/error_modal.html
Labels: product/invisible

#36051 [Data Cleaning] add comment about column_ prefix on fields
  corehq/apps/data_cleaning/forms/columns.py
Labels: product/feature-flag

#36054 [Data Cleaning] Fix TypeError that QA noticed when loading non-data dictionary domain
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/utils/cases.py
  corehq/apps/data_cleaning/views/main.py
Labels: product/feature-flag

#36053 update django version to 4.2.20
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#36050 Upgrade gunicorn to latest version
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: dependencies

#36058 Added references to root in releases_table.html
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_table.html
Labels: product/invisible

#36057 Added missing dependencies to case_knockout_bindings.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_knockout_bindings.js
Labels: product/invisible

#36059 Removed redundant metric in case import
  corehq/apps/case_importer/do_import.py
Labels: product/invisible

#36060 Remove growth email from invoice reminder bcc
  corehq/apps/accounting/utils/unpaid_invoice.py
Labels: product/admin

#36010 Append .0 if version miss patch version
  corehq/apps/receiverwrapper/tests/test_util.py
  corehq/apps/receiverwrapper/util.py
  corehq/ex-submodules/phonelog/tests/test_sumologic.py
Labels: product/all-users-all-environments

#35921 Do not leave domain tombstone if there is an error in subscription set up.
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tests/utils.py
  corehq/apps/api/tests/test_ucr_resources.py
  corehq/apps/api/tests/utils.py
  corehq/apps/domain/models.py
  corehq/apps/domain/tests/test_delete_domain.py
  corehq/apps/domain/tests/test_utils.py
  corehq/apps/registration/tests/test_utils.py
  corehq/apps/registration/utils.py
  corehq/apps/sms/tests/test_backfill_subevent.py
  corehq/tests/util/context.py
  corehq/tests/util/tests/test_context.py
  corehq/tests/util/warnings.py
Labels: Risk: High

#36061 Visual change for case management
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
Labels: product/all-users-all-environments

#36067 Combine maps & reports
  corehq/apps/campaign/models.py
  corehq/apps/campaign/static/campaign/js/dashboard.js
  corehq/apps/campaign/templates/campaign/dashboard.html
  corehq/apps/campaign/tests/test_models.py
  corehq/apps/campaign/tests/test_views.py
  corehq/apps/campaign/views.py
Labels: product/invisible

#36069 Handle Missing Documents for DeID dates
  corehq/ex-submodules/couchexport/deid.py
  corehq/ex-submodules/couchexport/tests/test_deid.py
Labels: product/invisible

#36062 Improve criteria for whether to send invoice reminder email
  corehq/apps/accounting/tests/test_unpaid_invoice.py
  corehq/apps/accounting/utils/unpaid_invoice.py
Labels: product/invisible

#35986 Update prepayment invoice email template
  corehq/apps/accounting/models.py
  corehq/apps/accounting/templates/accounting/email/wire_invoice.html
  corehq/apps/accounting/templates/accounting/email/wire_invoice.txt
Labels: product/prod-india-all-users

#36028 Tweaks to prepayment invoice template
  corehq/apps/accounting/invoice_pdf.py
  corehq/apps/accounting/tests/data/invoice_000.pdf
  corehq/apps/accounting/tests/data/invoice_002.pdf
  corehq/apps/accounting/tests/data/invoice_004.pdf
  corehq/apps/accounting/tests/data/invoice_006.pdf
Labels: product/all-users-all-environments

#36075 Replaced hqRequire with import in reports/js/bootstrap5/datatables_config
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/datatables_config.js.diff.txt
  corehq/apps/reports/static/reports/js/bootstrap5/datatables_config.js
Labels: product/invisible

#36068 [Data Cleaning] Logic and UI hook for adding columns to BulkEditSession
  corehq/apps/data_cleaning/forms/columns.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/templates/data_cleaning/forms/manage_columns_form.html
  corehq/apps/data_cleaning/tests/test_session.py
  corehq/apps/data_cleaning/utils/cases.py
  corehq/apps/data_cleaning/views/columns.py
Labels: product/feature-flag

#36046 Revert "Revert "Migration to invoke command for syncing couch and es webusers""
  corehq/ex-submodules/pillowtop/migrations/0008_sync_es_with_couch_webusers.py
  migrations.lock
Labels: reindex/migration

#36080 Updated notify_event to do nothing
  corehq/apps/app_manager/tests/test_notifications.py
  corehq/apps/app_manager/views/notifications.py
Labels: product/invisible

#36079 Migrated soil to webpack
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/file_download.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/file_download.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/file_download.html.diff.txt
  corehq/ex-submodules/soil/static/soil/js/file_download.js
  corehq/ex-submodules/soil/templates/soil/base.html
  corehq/ex-submodules/soil/templates/soil/file_download.html
Labels: product/invisible

#36081 Cleaned up mocha/base.html
  corehq/apps/mocha/templates/mocha/base.html
Labels: product/invisible

#36082 Revert "Upgrade botocore==1.37.15"
  corehq/blobs/__init__.py
  corehq/blobs/tests/util.py
  dev_settings.py
  docker/localsettings.py
  docker/min_settings.py
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#35942 Show verification errors in table
  corehq/apps/integration/kyc/models.py
  corehq/apps/integration/kyc/services.py
  corehq/apps/integration/kyc/tests/test_models.py
  corehq/apps/integration/kyc/tests/test_services.py
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/kyc/views.py
  corehq/apps/integration/templates/kyc/partials/kyc_verify_status.html
Labels: product/feature-flag, QA post deploy

#36083 Create an empty dashboard if one doesn't exist yet
  corehq/apps/campaign/tests/test_views.py
  corehq/apps/campaign/views.py
Labels: product/invisible

#36078 [Data Cleaning] Logic + UI hook for updating column order
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/templates/data_cleaning/forms/partials/column_list_item.html
  corehq/apps/data_cleaning/tests/test_session.py
  corehq/apps/data_cleaning/views/columns.py
Labels: product/feature-flag

#36056 Mask Sensitive Fields in KYC Report
  corehq/apps/integration/kyc/models.py
  corehq/apps/integration/kyc/services.py
  corehq/apps/integration/kyc/tables.py
  corehq/apps/integration/kyc/tests/test_models.py
  corehq/apps/integration/kyc/tests/test_services.py
  corehq/apps/integration/kyc/tests/test_tables.py
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/kyc/views.py
Labels: product/feature-flag

#36064 Update Generate Prepayment Invoice form and add new details to invoice
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/static/accounting/js/credits.js
  corehq/apps/accounting/static/accounting/js/payment_method_handler.js
  corehq/apps/accounting/tasks.py
  corehq/apps/domain/templates/domain/bootstrap3/current_subscription.html
  corehq/apps/domain/templates/domain/bootstrap5/current_subscription.html
  corehq/apps/domain/templates/domain/partials/bootstrap3/payment_modal.html
  corehq/apps/domain/templates/domain/partials/bootstrap5/payment_modal.html
  corehq/apps/domain/tests/test_utils.py
  corehq/apps/domain/utils.py
  corehq/apps/domain/views/accounting.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/current_subscription.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/partials/payment_modal.html.diff.txt
Labels: product/all-users-all-environments

#36087 Migrated B3 style guide to webpack
  corehq/apps/styleguide/static/styleguide/bootstrap3/js/feedback.js
  corehq/apps/styleguide/static/styleguide/bootstrap3/js/inline_edit.js
  corehq/apps/styleguide/static/styleguide/bootstrap3/js/main.js
  corehq/apps/styleguide/static/styleguide/bootstrap3/js/multiselect.js
  corehq/apps/styleguide/static/styleguide/bootstrap3/js/pagination.js
  corehq/apps/styleguide/static/styleguide/bootstrap3/js/search_box.js
  corehq/apps/styleguide/static/styleguide/bootstrap3/js/select2.js
  corehq/apps/styleguide/templates/styleguide/bootstrap3/_includes/molecules/checkboxes/checkboxes_form.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/_includes/molecules/feedback.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/_includes/molecules/inline_edit.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/_includes/molecules/pagination.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/_includes/molecules/search_box.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/_includes/molecules/selections.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/_includes/organisms/forms.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/_includes/organisms/forms/basic_crispy.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/base.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/example.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/example_html.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/examples/button_group.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/examples/feedback.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/examples/help.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/examples/inline_edit.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/examples/multiselect.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/examples/pagination.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/examples/search_box.html
  corehq/apps/styleguide/templates/styleguide/bootstrap3/examples/select2.html
  corehq/apps/styleguide/views/__init__.py
Labels: product/invisible

#36090 Update vellum
  corehq/apps/app_manager/static/app_manager/js/vellum/manifest.txt
  corehq/apps/app_manager/static/app_manager/js/vellum/src/main-components.js
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: product/invisible

#36041 Ability to edit widget in Campagin Dashboard
  corehq/apps/campaign/forms.py
  corehq/apps/campaign/static/campaign/js/dashboard.js
  corehq/apps/campaign/templates/campaign/partials/dashboard_map.html
  corehq/apps/campaign/templates/campaign/partials/edit_widget_button.html
  corehq/apps/campaign/templates/campaign/partials/widget_form.html
  corehq/apps/campaign/templates/campaign/partials/widget_modal.html
  corehq/apps/campaign/tests/test_views.py
  corehq/apps/campaign/views.py
Labels: product/feature-flag

#35854 Report long running profiled reports to sentry
  corehq/apps/reports/const.py
  corehq/apps/reports/standard/cases/basic.py
Labels: product/invisible

#36089 [B5] Split files: Geospatial
  corehq/apps/campaign/static/campaign/js/dashboard.js
  corehq/apps/geospatial/reports.py
  corehq/apps/geospatial/static/geospatial/js/bootstrap3/case_grouping_map.js
  corehq/apps/geospatial/static/geospatial/js/bootstrap3/case_management.js
  corehq/apps/geospatial/static/geospatial/js/bootstrap3/geo_config.js
  corehq/apps/geospatial/static/geospatial/js/bootstrap3/gps_capture.js
  corehq/apps/geospatial/static/geospatial/js/bootstrap3/models.js
  corehq/apps/geospatial/static/geospatial/js/bootstrap5/case_grouping_map.js
  corehq/apps/geospatial/static/geospatial/js/bootstrap5/case_management.js
  corehq/apps/geospatial/static/geospatial/js/bootstrap5/geo_config.js
  corehq/apps/geospatial/static/geospatial/js/bootstrap5/gps_capture.js
  corehq/apps/geospatial/static/geospatial/js/bootstrap5/models.js
  corehq/apps/geospatial/templates/geospatial/bootstrap3/base_template.html
  corehq/apps/geospatial/templates/geospatial/bootstrap3/case_grouping_map.html
  corehq/apps/geospatial/templates/geospatial/bootstrap3/case_grouping_map_base.html
  corehq/apps/geospatial/templates/geospatial/bootstrap3/case_management.html
  corehq/apps/geospatial/templates/geospatial/bootstrap3/case_management_base.html
  corehq/apps/geospatial/templates/geospatial/bootstrap3/gps_capture.html
  corehq/apps/geospatial/templates/geospatial/bootstrap3/gps_capture_view.html
  corehq/apps/geospatial/templates/geospatial/bootstrap3/settings.html
  corehq/apps/geospatial/templates/geospatial/bootstrap5/base_template.html
  corehq/apps/geospatial/templates/geospatial/bootstrap5/case_grouping_map.html
  corehq/apps/geospatial/templates/geospatial/bootstrap5/case_grouping_map_base.html
  corehq/apps/geospatial/templates/geospatial/bootstrap5/case_management.html
  corehq/apps/geospatial/templates/geospatial/bootstrap5/case_management_base.html
  corehq/apps/geospatial/templates/geospatial/bootstrap5/gps_capture.html
  corehq/apps/geospatial/templates/geospatial/bootstrap5/gps_capture_view.html
  corehq/apps/geospatial/templates/geospatial/bootstrap5/settings.html
  corehq/apps/geospatial/templates/geospatial/partials/bootstrap3/delete_saved_area_modal.html
  corehq/apps/geospatial/templates/geospatial/partials/bootstrap3/review_assignment_modal.html
  corehq/apps/geospatial/templates/geospatial/partials/bootstrap3/saved_polygon_filter.html
  corehq/apps/geospatial/templates/geospatial/partials/bootstrap5/delete_saved_area_modal.html
  corehq/apps/geospatial/templates/geospatial/partials/bootstrap5/review_assignment_modal.html
  corehq/apps/geospatial/templates/geospatial/partials/bootstrap5/saved_polygon_filter.html
  corehq/apps/geospatial/views.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diff_config.json
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/base_template.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/case_grouping_map.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/case_grouping_map_base.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/case_management.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/case_management_base.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/gps_capture.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/gps_capture_view.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/partials/delete_saved_area_modal.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/partials/review_assignment_modal.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/partials/saved_polygon_filter.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/geospatial/settings.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/geospatial/js/case_grouping_map.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/geospatial/js/case_management.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/geospatial/js/geo_config.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/geospatial/js/gps_capture.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/geospatial/js/models.js.diff.txt
  corehq/apps/hqwebapp/utils/bootstrap/status/bootstrap3_to_5.json
Labels: product/invisible

#36048 UCRs to use the report URL instead of `window.location`
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/standard_hq_report.js.diff.txt
  corehq/apps/reports/static/reports/js/bootstrap3/hq_report.js
  corehq/apps/reports/static/reports/js/bootstrap3/standard_hq_report.js
  corehq/apps/reports/static/reports/js/bootstrap5/hq_report.js
  corehq/apps/reports/static/reports/js/bootstrap5/standard_hq_report.js
  corehq/apps/userreports/reports/view.py
Labels: product/invisible

#36099 Added exception to edit broadcast schedule URL to prevent 404s
  corehq/messaging/scheduling/urls.py
Labels: product/invisible

#36096 Add more gauge metrics
  corehq/apps/campaign/const.py
  corehq/apps/campaign/forms.py
  corehq/apps/campaign/services.py
  corehq/apps/campaign/static/campaign/js/dashboard.js
  corehq/apps/campaign/templates/campaign/partials/dashboard_gauge.html
  corehq/apps/campaign/tests/test_models.py
  corehq/apps/campaign/tests/test_services.py
  corehq/apps/campaign/tests/test_views.py
  corehq/apps/campaign/views.py
Labels: product/feature-flag

#36086 [Data Cleaning] Add Logic + UI hook to remove columns
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tests/test_session.py
  corehq/apps/data_cleaning/views/columns.py
Labels: product/feature-flag

#36107 Fixed DOMPurify dependencies
  corehq/apps/app_manager/static/app_manager/js/details/utils.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_knockout_bindings.js
  corehq/apps/app_manager/static/app_manager/js/summary/models.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/entries.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/form_ui.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views/query.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/utils/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/markdown.js
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/hqwebapp/static/hqwebapp/js/components/inline_edit.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hqModules.js
  corehq/apps/hqwebapp/static/hqwebapp/js/select2_knockout_bindings.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap3/ui-element-input-map.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap5/ui-element-input-map.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/ui_elements/ui-element-input-map.js.diff.txt
  corehq/apps/userreports/static/userreports/js/configurable_reports_home.js
Labels: product/invisible, Risk: Medium

#36109 Fixed translation in prepayment modal
  corehq/apps/domain/templates/domain/partials/bootstrap3/payment_modal.html
  corehq/apps/domain/templates/domain/partials/bootstrap5/payment_modal.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/partials/payment_modal.html.diff.txt
Labels: product/all-users-all-environments

#36111 Adjusted button position in prepayment modal
  corehq/apps/accounting/templates/accounting/partials/stripe_card_ko_template.html
Labels: product/all-users-all-environments

#36114 improve header styling for django2 tables sortable headers
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_tables.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/tables._tables.style.diff.txt
Labels: product/all-users-all-environments

#36118 Removed requirejs conversions from bootstrap migration tool
  corehq/apps/hqwebapp/tests/utils/test_bootstrap_changes.py
  corehq/apps/hqwebapp/utils/bootstrap/changes.py
  corehq/apps/hqwebapp/utils/bootstrap/spec/bootstrap_3_to_5.json
Labels: product/invisible

#36121 Revert "Webpack migration for pages that use Stripe"
  corehq/apps/accounting/.eslintrc.js
  corehq/apps/accounting/static/accounting/js/billing_account_form.js
  corehq/apps/accounting/static/accounting/js/payment_method_handler.js
  corehq/apps/accounting/static/accounting/js/software_plan_version_handler.js
  corehq/apps/accounting/static/accounting/js/stripe.js
  corehq/apps/accounting/static/accounting/js/stripe_card_manager.js
  corehq/apps/accounting/static/accounting/js/subscriptions_main.js
  corehq/apps/accounting/templates/accounting/accounts.html
  corehq/apps/accounting/templates/accounting/accounts_base.html
  corehq/apps/accounting/templates/accounting/invoice.html
  corehq/apps/accounting/templates/accounting/partials/new_stripe_card_template.html
  corehq/apps/accounting/templates/accounting/partials/stripe_card_ko_template.html
  corehq/apps/accounting/templates/accounting/plans.html
  corehq/apps/accounting/templates/accounting/subscriptions.html
  corehq/apps/domain/.eslintrc.js
  corehq/apps/domain/static/domain/js/bootstrap3/billing_statements.js
  corehq/apps/domain/static/domain/js/bootstrap3/update_billing_contact_info.js
  corehq/apps/domain/static/domain/js/bootstrap5/billing_statements.js
  corehq/apps/domain/static/domain/js/bootstrap5/update_billing_contact_info.js
  corehq/apps/domain/static/domain/js/confirm_billing_info.js
  corehq/apps/domain/static/domain/js/current_subscription.js
  corehq/apps/domain/templates/domain/bootstrap3/billing_statements.html
  corehq/apps/domain/templates/domain/bootstrap3/confirm_billing_info.html
  corehq/apps/domain/templates/domain/bootstrap3/current_subscription.html
  corehq/apps/domain/templates/domain/bootstrap3/update_billing_contact_info.html
  corehq/apps/domain/templates/domain/bootstrap5/billing_statements.html
  corehq/apps/domain/templates/domain/bootstrap5/confirm_billing_info.html
  corehq/apps/domain/templates/domain/bootstrap5/current_subscription.html
  corehq/apps/domain/templates/domain/bootstrap5/update_billing_contact_info.html
  corehq/apps/domain/views/accounting.py
  corehq/apps/enterprise/views.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/billing_statements.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/confirm_billing_info.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/current_subscription.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/update_billing_contact_info.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/domain/js/billing_statements.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/domain/js/update_billing_contact_info.js.diff.txt
  package.json
  yarn.lock
Labels: dependencies
