Repository dimagi/commcare-hq, pull requests merged in 2025-07, with the labels that each got.

#36645 Fix sentry-sdk on Python 3.13
  corehq/util/htmx_action.py
  uv.lock
Labels: product/invisible, dependencies

#36607 Case Search Index for co-carecoordination-perf
  corehq/apps/case_search/models.py
  corehq/apps/case_search/utils.py
  corehq/apps/es/__init__.py
  corehq/apps/es/case_search_sub.py
  corehq/apps/es/const.py
  corehq/apps/es/index/settings.py
  corehq/apps/es/migrations/0016_add_new_index_for_cc_perf.py
  corehq/apps/es/tests/index/test_settings.py
  corehq/apps/es/tests/test_case_search_adapter.py
  migrations.lock
  settings.py
  testapps/test_elasticsearch/tests/test_prod_es_indices.py
Labels: reindex/migration

#36533 Send FormUpdates as Partials, Diffs
  corehq/apps/app_manager/exceptions.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_action_diffs.js
  corehq/apps/app_manager/tests/test_exceptions.py
  corehq/apps/app_manager/tests/test_models.py
  corehq/apps/app_manager/views/forms.py
Labels: product/invisible

#36651 Remove obsolete dependabot runtime.txt
  requirements/runtime.txt
Labels: product/invisible, dependencies

#36655 Re-add server location display for production, india, eu
  corehq/apps/domain/templates/login_and_password/two_factor/core/bootstrap3/login.html
  corehq/apps/domain/templates/login_and_password/two_factor/core/bootstrap5/login.html
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/dropdowns.less
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/global_navigation_bar.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/global_navigation_bar.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/global_navigation_bar.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/login_and_password/two_factor/core/login.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/dropdowns._dropdown.style.diff.txt
  corehq/util/context_processors.py
  corehq/util/tests/test_context_processors.py
  settings.py
Labels: product/prod-india-all-users, Risk: High

#36662 Update dropdown styling on signup page
  corehq/apps/hqwebapp/static/registration/less/registration-main.less
Labels: product/all-users-all-environments

#36667 Revert "Remove redundant feature flag for onse"
  corehq/apps/export/forms.py
  corehq/apps/reports/filters/users.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#36673 Update DEV_SETUP.md
  DEV_SETUP.md
Labels: product/invisible

#36674 Mjr/barcode hack
  corehq/apps/receiverwrapper/util.py
  corehq/apps/receiverwrapper/views.py
  corehq/form_processor/tests/utils/test_xform.py
  corehq/form_processor/utils/xform.py
  corehq/toggles/__init__.py
Labels: product/invisible, Risk: High

#36677 Bump vellum
  corehq/apps/app_manager/static/app_manager/js/vellum/452.js
  corehq/apps/app_manager/static/app_manager/js/vellum/main.js
  corehq/apps/app_manager/static/app_manager/js/vellum/manifest.txt
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: dependencies/javascript

#36665 Update Offline Update Instructions on .ccz Download Screen
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_deploy_modal.html
Labels: product/all-users-all-environments

#36670 Bump ddtrace to 3.10.0
  manage.py
  uv.lock
Labels: dependencies

#36688 Revert "Send FormUpdates as Partials, Diffs"
  corehq/apps/app_manager/exceptions.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_action_diffs.js
  corehq/apps/app_manager/tests/test_exceptions.py
  corehq/apps/app_manager/tests/test_models.py
  corehq/apps/app_manager/views/forms.py
Labels: product/invisible

#36602 Riese/web user deactivation es
  corehq/apps/accounting/management/commands/get_partner_domain_user_history.py
  corehq/apps/accounting/usage.py
  corehq/apps/analytics/tasks.py
  corehq/apps/api/query_adapters.py
  corehq/apps/callcenter/sync_usercase.py
  corehq/apps/callcenter/tests/test_sync_usercases_tasks.py
  corehq/apps/campaign/services.py
  corehq/apps/campaign/tests/test_services.py
  corehq/apps/data_analytics/esaccessors.py
  corehq/apps/data_cleaning/tests/test_filters.py
  corehq/apps/data_interfaces/deduplication.py
  corehq/apps/data_pipeline_audit/dbacessors.py
  corehq/apps/enterprise/api/resources.py
  corehq/apps/enterprise/enterprise.py
  corehq/apps/enterprise/models.py
  corehq/apps/enterprise/tests/api/test_resources.py
  corehq/apps/es/fake/users_fake.py
  corehq/apps/es/management/commands/populate_user_domain_memberships.py
  corehq/apps/es/tests/test_esquery.py
  corehq/apps/es/tests/test_users_es.py
  corehq/apps/es/users.py
  corehq/apps/export/forms.py
  corehq/apps/export/tests/test_export_forms.py
  corehq/apps/export/tests/test_export_models_new.py
  corehq/apps/hqadmin/tasks.py
  corehq/apps/locations/dbaccessors.py
  corehq/apps/locations/tasks.py
  corehq/apps/locations/tests/test_dbaccessors.py
  corehq/apps/locations/tests/test_permissions.py
  corehq/apps/locations/util.py
  corehq/apps/reports/analytics/esaccessors.py
  corehq/apps/reports/filters/api.py
  corehq/apps/reports/filters/controllers.py
  corehq/apps/reports/filters/users.py
  corehq/apps/reports/models.py
  corehq/apps/reports/standard/cases/utils.py
  corehq/apps/reports/standard/users/reports.py
  corehq/apps/reports/tests/filters/user_list.py
  corehq/apps/reports/tests/test_esaccessors.py
  corehq/apps/reports/tests/test_filters.py
  corehq/apps/saved_reports/models.py
  corehq/apps/saved_reports/tests/test_models.py
  corehq/apps/users/analytics.py
  corehq/apps/users/dbaccessors.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/mobile/users.py
  corehq/messaging/scheduling/scheduling_partitioned/models.py
  corehq/util/test_utils.py
  custom/inddex/food.py
Labels: Risk: High

#36676 Add user history logging for password resets + account confirmation
  corehq/apps/domain/views/settings.py
  corehq/apps/users/audit/change_messages.py
  corehq/apps/users/views/mobile/users.py
Labels: product/all-users-all-environments

#36671 Bump attrs to 25.3.0
  uv.lock
Labels: dependencies

#36663 Bump cryptography to 45.0.5
  uv.lock
Labels: QA Passed, dependencies

#36666 Update App preview and WebApps UI
  corehq/apps/app_manager/templates/app_manager/partials/preview_app.html
  corehq/apps/cloudcare/templates/cloudcare/partials/grid_view/grid.html
  corehq/apps/cloudcare/templates/cloudcare/partials/grid_view/single_app.html
  corehq/apps/hqwebapp/static/app_manager/less/preview_app-main.less
  corehq/apps/hqwebapp/static/cloudcare/scss/debugger/debugger.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/appicon.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/formnav.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-common/webforms.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/case-tile.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/navbar.scss
  corehq/apps/hqwebapp/static/cloudcare/scss/formplayer-webapp/query.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_readable_forms.scss
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_variables.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app/breadcrumbs.scss
  corehq/apps/hqwebapp/static/preview_app/scss/preview_app/navigation.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/includes_variables._variables.style.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/readable_forms._readable_forms.style.diff.txt
Labels: Risk: Medium

#36705 Fixes "Domain Temporarily Unavailable"
  corehq/apps/domain/templates/domain/bootstrap3/data_migration_in_progress.html
  corehq/apps/domain/templates/domain/bootstrap5/data_migration_in_progress.html
Labels: product/invisible

#36691 Add api to activate/deactivate web users
  corehq/apps/api/resources/v0_5.py
  corehq/apps/api/tests/test_user_resources.py
Labels: Risk: High

#36680 Command to get copy-paste-able FF domain list
  corehq/toggles/management/__init__.py
  corehq/toggles/management/commands/__init__.py
  corehq/toggles/management/commands/list_ff_domains.py
Labels: product/invisible

#36697 Productize import app feature
  corehq/apps/app_manager/static/app_manager/js/import_app.js
  corehq/apps/app_manager/templates/app_manager/import_app.html
  corehq/apps/app_manager/urls.py
  corehq/apps/app_manager/views/__init__.py
  corehq/apps/app_manager/views/apps.py
  corehq/apps/data_cleaning/views/start.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/domain/import_app_from_another_server_main.html
  corehq/apps/domain/templates/domain/partials/import_app_step_1_instruction.html
  corehq/apps/domain/templates/domain/partials/import_app_step_2_instruction.html
  corehq/apps/domain/tests/test_forms.py
  corehq/apps/domain/urls.py
  corehq/apps/domain/views/__init__.py
  corehq/apps/domain/views/import_apps.py
  corehq/apps/domain/views/settings.py
  corehq/apps/hqwebapp/templates/hqwebapp/htmx/forms/next_action_form.html
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments

#36717 Add the domain subscription to output
  corehq/toggles/management/commands/list_ff_domains.py
Labels: product/invisible

#36706 Improve wordings of statuses in payments for better clarity.
  corehq/apps/integration/payments/const.py
  corehq/apps/integration/payments/filters.py
  corehq/apps/integration/payments/services.py
  corehq/apps/integration/payments/tables.py
  corehq/apps/integration/payments/tests/test_services.py
  corehq/apps/integration/payments/tests/test_views.py
  corehq/apps/integration/payments/views.py
  corehq/apps/integration/tasks.py
  corehq/apps/integration/templates/payments/partials/payments_verify_alert.html
Labels: product/feature-flag

#36716 add tests for `corehq.apps.data_cleaning.utils.cases`
  corehq/apps/data_cleaning/tests/test_utils_cases.py
  corehq/apps/data_cleaning/utils/cases.py
  corehq/util/test_utils.py
Labels: product/invisible

#36715 Add multimedia import instruction
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/domain/import_app_from_another_server_main.html
  corehq/apps/domain/templates/domain/import_app_step_3_instruction.html
  corehq/apps/domain/views/import_apps.py
  corehq/apps/domain/views/settings.py
Labels: product/all-users-all-environments

#36720 Clean up import app feature
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/domain/import_app_from_another_server_main.html
  corehq/apps/domain/templates/domain/partials/how_to_download_app_json.html
  corehq/apps/domain/templates/domain/partials/how_to_import_multimedia.html
  corehq/apps/domain/templates/domain/partials/how_to_start_with_import_app_feature.html
  corehq/apps/domain/tests/test_forms.py
  corehq/apps/domain/views/import_apps.py
Labels: product/all-users-all-environments

#36728 Allow contact fields to be blank
  corehq/apps/accounting/migrations/0105_alter_billingcontactinfo_city_and_more.py
  corehq/apps/accounting/models.py
  migrations.lock
Labels: reindex/migration, product/admin

#36726 update dynamic import
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/js/datatables_config.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/reports/v2/js/views/explore_case_data.js.diff.txt
  corehq/apps/reports/static/reports/js/bootstrap5/datatables_config.js
Labels: product/all-users-all-environments

#36684 Add view to the couch user DB that will replace the by_domain view going forward
  corehq/apps/reports/views.py
  corehq/apps/users/dbaccessors.py
  corehq/apps/users/tests/test_dbaccessors.py
  corehq/couchapps/__init__.py
  corehq/couchapps/users_by_domain/views/view/map.js
  corehq/couchapps/users_by_domain/views/view/reduce.js
  corehq/preindex/couchviews.lock
  corehq/preindex/migrations/0003_initial.py
  migrations.lock
Labels: reindex/migration

#36682 Drop Reports v2
  corehq/apps/hqwebapp/tables/columns.py
  corehq/apps/reports/standard/cases/data_sources.py
  corehq/apps/reports/urls.py
  corehq/apps/reports/util.py
  corehq/apps/reports/v2/__init__.py
  corehq/apps/reports/v2/endpoints/__init__.py
  corehq/apps/reports/v2/endpoints/case_owner.py
  corehq/apps/reports/v2/endpoints/case_properties.py
  corehq/apps/reports/v2/endpoints/case_type.py
  corehq/apps/reports/v2/endpoints/datagrid.py
  corehq/apps/reports/v2/exceptions.py
  corehq/apps/reports/v2/filters/__init__.py
  corehq/apps/reports/v2/filters/case_report.py
  corehq/apps/reports/v2/filters/xpath_column.py
  corehq/apps/reports/v2/formatters/__init__.py
  corehq/apps/reports/v2/formatters/cases.py
  corehq/apps/reports/v2/models.py
  corehq/apps/reports/v2/reports/__init__.py
  corehq/apps/reports/v2/urls.py
  corehq/apps/reports/v2/utils.py
  corehq/apps/reports/v2/views.py
Labels: product/invisible

#36732 Users ES Mapping "is_account_confirmed"
  corehq/apps/es/mappings/user_mapping.py
  corehq/apps/es/migrations/0017_add_is_account_confirmed.py
  corehq/apps/es/users.py
  corehq/ex-submodules/pillowtop/management/commands/sync_es_users.py
  corehq/ex-submodules/pillowtop/management/commands/sync_es_webusers.py
  migrations.lock
Labels: reindex/migration, Open for review: do not merge

#36758 Clean up uses of GROWTH_EMAIL
  corehq/apps/accounting/utils/unpaid_invoice.py
  settings.py
Labels: product/invisible

#36761 Raise company name length limit
  corehq/apps/accounting/migrations/0106_alter_billingcontactinfo_company_name.py
  corehq/apps/accounting/models.py
  corehq/apps/registration/forms.py
  migrations.lock
Labels: reindex/migration, product/all-users-all-environments, Risk: High

#36518 Command to refresh data dictionary
  corehq/apps/app_manager/tasks.py
  corehq/apps/data_dictionary/management/commands/refresh_data_dictionary.py
  corehq/apps/data_dictionary/migrations/0017_refresh_data_dictionary.py
  migrations.lock
Labels: reindex/migration, product/all-users-all-environments, migration-maintenance

#36754 Add tests for EditSelectedRecordsForm (bulk data editing)
  corehq/apps/data_cleaning/tests/test_bulk_edit_form.py
Labels: product/invisible

#36766 Move password to check to where it actually matters + slight refactor
  corehq/apps/api/resources/v0_5.py
Labels: Risk: High

#36598 AI Guidelines file
  .junie/guidelines.md
  CLAUDE.md
  ai_guidelines.md
Labels: product/invisible

#36762 Simple migration to assigns edit permissions for all toggle tags to superusers to maintain consistency with the current behavior.
  corehq/toggles/migrations/0002_assign_permissions_superusers.py
  migrations.lock
Labels: reindex/migration, product/admin

#36751 Revert "Revert "Remove redundant feature flag for onse""
  corehq/apps/export/forms.py
  corehq/apps/reports/filters/users.py
  corehq/toggles/__init__.py
Labels: product/feature-flag

#36767 Add new custom icon "fcc-manage-case"
  corehq/apps/app_manager/templates/app_manager/form_designer.html
  corehq/apps/hqwebapp/static/hqwebapp/font/CommCare HQ Font.json
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehq-font.eot
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehq-font.svg
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehq-font.ttf
  corehq/apps/hqwebapp/static/hqwebapp/font/commcarehq-font.woff
  corehq/apps/hqwebapp/static/hqwebapp/font/style.scss
  corehq/apps/hqwebapp/static/hqwebapp/font/variables.scss
  corehq/apps/styleguide/context.py
Labels: product/all-users-all-environments

#36777 Improve button spacing for pre-login language selector
  corehq/apps/hqwebapp/templates/hqwebapp/bootstrap3/base_navigation.html
  corehq/apps/hqwebapp/templates/hqwebapp/bootstrap5/base_navigation.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/base_navigation.html.diff.txt
Labels: product/all-users-all-environments

#36781 Update `form-data`
  package.json
  yarn.lock
Labels: dependencies

#36233 Check for Edit permission of user while accessing Feature Flags
  corehq/apps/domain/static/domain/js/bootstrap3/toggles.js
  corehq/apps/domain/static/domain/js/bootstrap5/toggles.js
  corehq/apps/domain/templates/domain/admin/flags_and_privileges.html
  corehq/apps/domain/tests/test_views.py
  corehq/apps/domain/views/internal.py
  corehq/apps/toggle_ui/templates/toggle/edit_flag.html
  corehq/apps/toggle_ui/templates/toggle/flags.html
  corehq/apps/toggle_ui/tests.py
  corehq/apps/toggle_ui/views.py
  corehq/toggles/migrations/0002_assign_permissions_superusers.py
  corehq/toggles/shortcuts.py
  corehq/toggles/sql_models.py
  corehq/toggles/tests.py
  migrations.lock
Labels: reindex/migration, QA Passed, product/all-users-all-environments
