Repository dimagi/commcare-hq, pull requests merged in 2025-06, with the labels that each got.

#36522 Added remaining textchange imports
  corehq/apps/app_manager/static/app_manager/js/app_manager_media.js
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/select2_knockout_bindings.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap3/ui-element-input.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap3/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap5/ui-element-input.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap5/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/main.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/ui_elements/ui-element-input.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/ui_elements/ui-element-key-val-mapping.js.diff.txt
  corehq/apps/reports/static/reports/js/filters/case_list_explorer_knockout_bindings.js
Labels: product/invisible

#36536 Add feature flag for formbuilder save-to-case work
  corehq/toggles/__init__.py
Labels: product/invisible

#36541 Update docs to remove hqDefine
  docs/js-guide/README.rst
  docs/js-guide/amd-to-esm.rst
  docs/js-guide/code-organization.rst
  docs/js-guide/dependencies.rst
  docs/js-guide/external-packages.rst
  docs/js-guide/integration-patterns.rst
  docs/js-guide/module-history.rst
Labels: product/invisible

#36540 Update and rename hqDefine.sh
  corehq/apps/hqadmin/management/commands/static_analysis.py
  docs/js-guide/dependencies.rst
  scripts/codechecks/amd.sh
Labels: product/invisible

#36537 Updated bootstrap migration test
  corehq/apps/hqwebapp/tests/utils/test_bootstrap_changes.py
Labels: product/invisible

#36524 [Data Cleaning] Prettier + djlint cleanup of template files
  corehq/apps/data_cleaning/templates/data_cleaning/bulk_edit_main.html
  corehq/apps/data_cleaning/templates/data_cleaning/bulk_edit_session.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/column_editable.html
  corehq/apps/data_cleaning/templates/data_cleaning/columns/column_system.html
  corehq/apps/data_cleaning/templates/data_cleaning/filters/pinned/base.html
  corehq/apps/data_cleaning/templates/data_cleaning/filters/pinned/multi_option.html
  corehq/apps/data_cleaning/templates/data_cleaning/filters/pinned/single_option.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/edit_selected_records_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/manage_columns_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/manage_filters_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/next_action_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/partials/active_session_exists.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/partials/column_list_item.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/partials/filter_list_item.html
  corehq/apps/data_cleaning/templates/data_cleaning/modals/base_confirm.html
  corehq/apps/data_cleaning/templates/data_cleaning/modals/confirm_apply.html
  corehq/apps/data_cleaning/templates/data_cleaning/modals/confirm_clear.html
  corehq/apps/data_cleaning/templates/data_cleaning/modals/confirm_select_all.html
  corehq/apps/data_cleaning/templates/data_cleaning/modals/confirm_undo.html
  corehq/apps/data_cleaning/templates/data_cleaning/modals/select_all_not_possible.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/offcanvas.html
  corehq/apps/data_cleaning/templates/data_cleaning/status/base_modal_body.html
  corehq/apps/data_cleaning/templates/data_cleaning/status/complete.html
  corehq/apps/data_cleaning/templates/data_cleaning/status/in_progress.html
  corehq/apps/data_cleaning/templates/data_cleaning/status/modal.html
  corehq/apps/data_cleaning/templates/data_cleaning/status/previous_session.html
  corehq/apps/data_cleaning/templates/data_cleaning/summary/partial/change_detail.html
  corehq/apps/data_cleaning/templates/data_cleaning/tables/bulk_edit_session.html
  corehq/apps/data_cleaning/templates/data_cleaning/tables/recent_sessions.html
Labels: product/invisible

#36535 [Data Cleaning] organize imports and run ruff on all of `data_cleaning`
  corehq/apps/data_cleaning/columns.py
  corehq/apps/data_cleaning/decorators.py
  corehq/apps/data_cleaning/filters.py
  corehq/apps/data_cleaning/forms/bulk_edit.py
  corehq/apps/data_cleaning/forms/columns.py
  corehq/apps/data_cleaning/forms/filters.py
  corehq/apps/data_cleaning/forms/start_session.py
  corehq/apps/data_cleaning/models/__init__.py
  corehq/apps/data_cleaning/models/change.py
  corehq/apps/data_cleaning/models/column.py
  corehq/apps/data_cleaning/models/filters.py
  corehq/apps/data_cleaning/models/record.py
  corehq/apps/data_cleaning/models/session.py
  corehq/apps/data_cleaning/models/types.py
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/tasks.py
  corehq/apps/data_cleaning/templatetags/data_cleaning.py
  corehq/apps/data_cleaning/tests/test_changes.py
  corehq/apps/data_cleaning/tests/test_filters.py
  corehq/apps/data_cleaning/tests/test_records.py
  corehq/apps/data_cleaning/tests/test_session.py
  corehq/apps/data_cleaning/tests/test_tasks.py
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/utils/cases.py
  corehq/apps/data_cleaning/utils/decorators.py
  corehq/apps/data_cleaning/views/bulk_edit.py
  corehq/apps/data_cleaning/views/columns.py
  corehq/apps/data_cleaning/views/filters.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/data_cleaning/views/mixins.py
  corehq/apps/data_cleaning/views/start.py
  corehq/apps/data_cleaning/views/status.py
  corehq/apps/data_cleaning/views/summary.py
  corehq/apps/data_cleaning/views/tables.py
Labels: product/invisible

#36542 [Data Cleaning] fix: remove comma causing js error
  corehq/apps/data_cleaning/forms/filters.py
Labels: product/invisible

#36471 Added update_multi field for FormActions
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_models.py
Labels: product/invisible

#36539 Updated and renamed hqdefine_to_esm command
  corehq/apps/hqwebapp/management/commands/amd_to_esm.py
Labels: product/invisible

#36545 Add description attribute to reports so they will show a tooltip when…
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/deployments.py
  corehq/apps/reports/standard/forms/reports.py
  corehq/apps/reports/standard/inspect.py
Labels: product/all-users-all-environments

#36529 Filter CSQL by Custom User Data - Migration
  corehq/apps/case_search/migrations/0016_csqlfixtureexpression_user_data_criteria.py
  corehq/apps/case_search/models.py
  migrations.lock
Labels: reindex/migration

#36544 Removed use_js_bundler flag
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
  corehq/apps/hqwebapp/templatetags/tests/test_tag.py
Labels: product/invisible, Risk: Medium

#35977 Create migration for removing orphaned user data
  corehq/apps/users/management/commands/rm_orphaned_user_data.py
  corehq/apps/users/migrations/0081_rm_orphaned_user_data.py
  corehq/apps/users/tests/test_rm_orphaned_user_data.py
  migrations.lock
Labels: reindex/migration

#36548 Jls/almost 90 percent
  corehq/apps/analytics/static/analytix/js/cta_forms.js
  corehq/apps/analytics/static/analytix/js/drift.js
  corehq/apps/analytics/static/analytix/js/hubspot.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/alert_user.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/base_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/common.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/downgrade_modal.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/email-request.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/hq.helpers.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/inactivity.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/knockout_bindings.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/mobile_experience_warning.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/prepaid_modal.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/sticky_tabs.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/validators.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/widgets.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/base_main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/common.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/downgrade_modal.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/email-request.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/inactivity.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/main.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/mobile_experience_warning.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/prepaid_modal.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/sticky_tabs.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/validators.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/widgets.js
  corehq/apps/hqwebapp/static/hqwebapp/js/hq_extensions.jquery.js
  corehq/apps/hqwebapp/static/hqwebapp/js/knockout_subscribables.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/layout.js
  corehq/apps/hqwebapp/static/hqwebapp/js/privileges.js
  corehq/apps/hqwebapp/static/hqwebapp/js/utils/email.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/alert_user.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/base_main.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/common.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/downgrade_modal.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/email-request.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/hq.helpers.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/inactivity.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/knockout_bindings.ko.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/main.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/mobile_experience_warning.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/prepaid_modal.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/sticky_tabs.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/validators.ko.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/widgets.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/notifications/js/notifications_service.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/notifications/js/notifications_service_main.js.diff.txt
  corehq/apps/notifications/static/notifications/js/bootstrap3/notifications_service.js
  corehq/apps/notifications/static/notifications/js/bootstrap3/notifications_service_main.js
  corehq/apps/notifications/static/notifications/js/bootstrap5/notifications_service.js
  corehq/apps/notifications/static/notifications/js/bootstrap5/notifications_service_main.js
Labels: product/invisible

#36554 Change generated by vellum-to-hq
  corehq/apps/app_manager/static/app_manager/js/vellum/224.js
  corehq/apps/app_manager/static/app_manager/js/vellum/224.js.LICENSE.txt
  corehq/apps/app_manager/static/app_manager/js/vellum/964.js
  corehq/apps/app_manager/static/app_manager/js/vellum/main.js
  corehq/apps/app_manager/static/app_manager/js/vellum/manifest.txt
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: product/all-users-all-environments

#36560 Update icon for My Saved Reports
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments

#36486 Remove duplicates and ensure duplicates cannot be created
  corehq/apps/users/migrations/0082_connectidmessagingkey_unique_active_messaging_key_per_user_and_domain.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_models.py
  migrations.lock
Labels: reindex/migration

#36565 Updated dynamic imports for ES6
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap3/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap5/ui-element-key-val-mapping.js
Labels: product/all-users-all-environments

#36570 Added default entry point for pages that don't use js_entry
  corehq/apps/hqwebapp/static/hqwebapp/js/base.js
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
Labels: product/all-users-all-environments

#36571 Make entry point for pages without their own js available to bootstra…
  corehq/apps/hqwebapp/templates/hqwebapp/base.html
  webpack/generateDetails.js
Labels: product/all-users-all-environments, Risk: High

#36569 Added name_update_multi to OpenCaseAction
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tests/test_models.py
Labels: product/invisible

#36501 Notification for Ops when Pay Annually plan fee is not automatically credited
  corehq/apps/accounting/emails.py
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/templates/accounting/email/pay_annually_unpaid.html
  corehq/apps/accounting/templates/accounting/email/pay_annually_unpaid.txt
  corehq/apps/accounting/tests/generator.py
  corehq/apps/accounting/tests/test_invoicing.py
  corehq/apps/accounting/utils/invoicing.py
Labels: product/invisible

#36587 Update B5 docs for css-nav.md
  corehq/apps/hqwebapp/utils/bootstrap/changes_guide/css-nav.md
Labels: product/invisible

#36576 Generate prorated prepayment invoice when moving from Pay Annually -> Pay Annually subscription
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/models.py
  corehq/apps/accounting/tasks.py
  corehq/apps/accounting/tests/test_invoicing.py
  corehq/apps/accounting/utils/invoicing.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/tests/test_utils.py
  corehq/apps/domain/utils.py
Labels: product/invisible

#36582 Prettier: proseWrap
  .prettierrc
  package.json
Labels: product/invisible

#36603 Show confirmation and send prepayment invoice when renewing to Pay Annually
  corehq/apps/accounting/invoicing.py
  corehq/apps/accounting/models.py
  corehq/apps/domain/forms.py
  corehq/apps/domain/templates/domain/bootstrap3/confirm_subscription_renewal.html
  corehq/apps/domain/templates/domain/bootstrap5/confirm_subscription_renewal.html
  corehq/apps/domain/tests/test_forms.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/confirm_subscription_renewal.html.diff.txt
Labels: product/all-users-all-environments

#36610 Migrate debugger.js to esm
  corehq/apps/cloudcare/static/cloudcare/js/debugger/debugger.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/debugger_spec.js
Labels: product/invisible, Risk: Medium

#36614 Add afterEach to eslintrc
  .eslintrc.js
Labels: product/invisible

#36588 Add performance warning for too many case properties
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/tests/test_views.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/static/data_dictionary/js/partials/case_property_warning.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/templates/data_dictionary/partials/case_property_warning.html
  corehq/apps/data_dictionary/util.py
  corehq/apps/data_dictionary/views.py
  corehq/project_limits/const.py
Labels: product/prod-india-all-users

#36581 DataSourceUpdate model
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/userreports/tests/test_pillow.py
  corehq/apps/userreports/util.py
  corehq/motech/repeaters/migrations/0018_datasourceupdate.py
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/repeater_generators.py
  corehq/motech/repeaters/signals.py
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_models.py
  corehq/motech/repeaters/tests/test_repeater.py
  migrations.lock
Labels: reindex/migration, product/invisible

#36616 Fix UnboundLocalError
  corehq/apps/reports/standard/sms.py
Labels: product/invisible

#36615 Add instructions for failing docker elasticsearch container
  DEV_SETUP.md
Labels: product/invisible

#36625 Default to showing annual pricing unless on a paid monthly plan
  corehq/apps/accounting/static/accounting/js/pricing_table.js
Labels: product/all-users-all-environments

#36631 Fix group sorting in data dictionary UI
  corehq/apps/data_dictionary/static/data_dictionary/js/data_dictionary.js
  corehq/apps/data_dictionary/templates/data_dictionary/base.html
  corehq/apps/data_dictionary/tests/test_views.py
  corehq/apps/data_dictionary/views.py
Labels: product/all-users-all-environments

#36636 Add url and project description to bug report emails
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap3/modal_report_issue.html
  corehq/apps/hqwebapp/templates/hqwebapp/includes/bootstrap5/modal_report_issue.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/includes/modal_report_issue.html.diff.txt
  corehq/apps/hqwebapp/views.py
Labels: product/invisible
