Repository dimagi/commcare-hq, pull requests merged in 2025-02, with the labels that each got.

#35725 Revert "TableauConnectedApp, TransifexOrganization, and OpenmrsImporter models: AES CBC encryption Migration "
  corehq/apps/reports/migrations/0021_tableauconnectedapp_use_aes_cbc_encryption.py
  corehq/apps/translations/migrations/0010_transifex_organization_api_token_encryption.py
  corehq/motech/migrations/0018_openmrsimporter_use_aes_cbc_encryption.py
  migrations.lock
Labels: Open for review: do not merge

#35723 Show technical details to superusers only
  corehq/apps/userreports/views.py
Labels: product/feature-flag

#35718 Added explicit dependencies to ui-element-key-val-mapping
  corehq/apps/app_manager/static/app_manager/js/details/case_list_callout.js
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/static/app_manager/js/details/sort_rows.js
  corehq/apps/app_manager/static/app_manager/js/managed_app.js
  corehq/apps/app_manager/static/app_manager/js/visit_scheduler.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/ui-element.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/ui-element.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap3/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/static/hqwebapp/js/ui_elements/bootstrap5/ui-element-key-val-mapping.js
  corehq/apps/hqwebapp/templates/hqwebapp/includes/ui_element_js.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/ui-element.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/ui_elements/ui-element-key-val-mapping.js.diff.txt
Labels: product/invisible

#35709 Commas for everyone
  corehq/apps/analytics/static/analytix/js/appcues.js
  corehq/apps/analytics/static/analytix/js/cta_forms.js
  corehq/apps/analytics/static/analytix/js/drift.js
  corehq/apps/analytics/static/analytix/js/google.js
  corehq/apps/analytics/static/analytix/js/gtx.js
  corehq/apps/analytics/static/analytix/js/hubspot.js
  corehq/apps/analytics/static/analytix/js/initial.js
  corehq/apps/analytics/static/analytix/js/kissmetrix.js
  corehq/apps/analytics/static/analytix/js/logging.js
  corehq/apps/analytics/static/analytix/js/utils.js
  corehq/apps/case_importer/static/case_importer/js/excel_fields.js
  corehq/apps/case_importer/static/case_importer/js/import_history.js
  corehq/apps/case_importer/static/case_importer/js/main.js
  corehq/apps/case_importer/static/case_importer/spec/excel_fields_spec.js
  corehq/apps/dashboard/static/dashboard/js/dashboard.js
  corehq/apps/export/static/export/js/create_export.js
  corehq/apps/export/static/export/js/customize_export_new.js
  corehq/apps/export/static/export/js/datasource_export.js
  corehq/apps/export/static/export/js/download_export.js
  corehq/apps/export/static/export/js/export_list.js
  corehq/apps/export/static/export/js/export_list_main.js
  corehq/apps/export/static/export/js/models.js
  corehq/apps/export/static/export/js/utils.js
  corehq/apps/export/static/export/spec/ExportColumn.spec.js
  corehq/apps/export/static/export/spec/ExportInstance.spec.js
  corehq/apps/export/static/export/spec/Exports.Utils.spec.js
  corehq/apps/linked_domain/static/linked_domain/js/domain_links.js
  corehq/apps/locations/static/locations/js/filtered_download.js
  corehq/apps/locations/static/locations/js/import.js
  corehq/apps/locations/static/locations/js/location.js
  corehq/apps/locations/static/locations/js/location_drilldown.js
  corehq/apps/locations/static/locations/js/location_tree.js
  corehq/apps/locations/static/locations/js/location_types.js
  corehq/apps/locations/static/locations/js/locations.js
  corehq/apps/locations/static/locations/js/search.js
  corehq/apps/locations/static/locations/js/widgets.js
  corehq/apps/locations/static/locations/spec/location_drilldown_spec.js
  corehq/apps/locations/static/locations/spec/types_spec.js
  corehq/apps/registration/static/registration/js/bootstrap3/password.js
  corehq/apps/registration/static/registration/js/bootstrap5/password.js
  corehq/apps/registration/static/registration/js/login.js
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/registration/static/registration/js/register_new_user.js
  corehq/apps/registration/static/registration/js/user_login_form.js
  corehq/apps/registry/static/registry/js/registry_actions.js
  corehq/apps/registry/static/registry/js/registry_edit.js
  corehq/apps/registry/static/registry/js/registry_list.js
  corehq/apps/registry/static/registry/js/registry_logs.js
  corehq/apps/registry/static/registry/js/registry_text.js
  corehq/messaging/scheduling/static/scheduling/js/conditional_alert_list.js
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.js
Labels: product/invisible

#35716 KYC Config Page
  corehq/apps/integration/kyc/forms.py
  corehq/apps/integration/kyc/models.py
  corehq/apps/integration/kyc/tests/__init__.py
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/kyc/urls.py
  corehq/apps/integration/kyc/views.py
  corehq/apps/integration/migrations/0008_kycconfig_provider_kycconfig_unique_domain_provider.py
  corehq/apps/integration/static/integration/js/kyc/kyc_configure.js
  corehq/apps/integration/templates/kyc/kyc_config_base.html
  corehq/apps/integration/templates/kyc/partials/kyc_config_form_partial.html
  corehq/reports.py
  corehq/tabs/tabclasses.py
  corehq/toggles/__init__.py
  migrations.lock
  urls.py
Labels: reindex/migration, product/feature-flag

#35628 Check for custom callouts on app builds
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/tasks.py
  corehq/apps/app_manager/tests/test_apps.py
  corehq/apps/app_manager/util.py
  corehq/apps/app_manager/views/releases.py
Labels: QA Passed, product/invisible

#35731 Convert app preview js to ESM format
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/dragscroll.js
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/main.js
  corehq/apps/cloudcare/static/cloudcare/js/preview_app/preview_app.js
  docs/js-guide/dependencies.rst
Labels: Risk: Medium

#35712 Add support for paginating elasticsearch queries for `django_tables2` (with HTMX)
  corehq/apps/case_search/utils.py
  corehq/apps/hqwebapp/tables/elasticsearch/__init__.py
  corehq/apps/hqwebapp/tables/elasticsearch/records.py
  corehq/apps/hqwebapp/tables/elasticsearch/tables.py
  corehq/apps/hqwebapp/tests/tables/__init__.py
  corehq/apps/hqwebapp/tests/tables/generator.py
  corehq/apps/hqwebapp/tests/tables/test_elastic_records.py
  corehq/apps/hqwebapp/tests/tables/test_elastic_tables.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
Labels: product/invisible

#35704 [B5] Migrate first reports to bootstrap 5!
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/filters/multi_option.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/filters/simple.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/reports/filters/single_option.html.diff.txt
  corehq/apps/hqwebapp/utils/bootstrap/reports/progress/bootstrap3_to_5.json
  corehq/apps/reports/standard/cases/basic.py
  corehq/apps/reports/standard/cases/case_list_explorer.py
  corehq/apps/reports/standard/cases/duplicate_cases.py
  corehq/apps/reports/standard/deployments.py
  corehq/apps/reports/templates/reports/filters/bootstrap5/multi_option.html
  corehq/apps/reports/templates/reports/filters/bootstrap5/simple.html
  corehq/apps/reports/templates/reports/filters/bootstrap5/single_option.html
Labels: QA Passed, product/all-users-all-environments

#35364 Ce/connect messaging
  corehq/apps/commtrack/sms.py
  corehq/apps/domain/auth.py
  corehq/apps/domain/deletion.py
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/dump_reload/sql/dump.py
  corehq/apps/reports/standard/sms.py
  corehq/apps/sms/api.py
  corehq/apps/sms/filters.py
  corehq/apps/sms/handlers/fallback.py
  corehq/apps/sms/handlers/form_session.py
  corehq/apps/sms/handlers/keyword.py
  corehq/apps/sms/migrations/0060_alter_messagingevent_content_type_and_more.py
  corehq/apps/sms/models.py
  corehq/apps/sms/templates/sms/connect_messaging_user.html
  corehq/apps/sms/tests/opt_tests.py
  corehq/apps/sms/tests/test_backends.py
  corehq/apps/sms/tests/test_form_session_handler.py
  corehq/apps/sms/urls.py
  corehq/apps/sms/verify.py
  corehq/apps/sms/views.py
  corehq/apps/smsforms/tasks.py
  corehq/apps/users/migrations/0076_connectiduserlink_messaging_consent_and_more.py
  corehq/apps/users/models.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/migrations/0029_connectmessagecontent_connectmessagesurveycontent_and_more.py
  corehq/messaging/scheduling/models/abstract.py
  corehq/messaging/scheduling/models/content.py
  corehq/messaging/smsbackends/connectid/backend.py
  corehq/messaging/smsbackends/connectid/urls.py
  corehq/messaging/smsbackends/connectid/views.py
  corehq/tabs/tabclasses.py
  docs/messaging/outbound_sms.rst
  migrations.lock
  settings.py
  urls.py
Labels: reindex/migration, product/feature-flag

#35735 Converts web apps specs to ESM
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entries_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/fixtures.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/form_ui_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/web_form_session_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/case_list_pagination_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/debugger_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/hq_events_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/main.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/query_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/session_middleware_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/split_screen_case_search_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/user_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/utils_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/spec/markdown_spec.js
  corehq/apps/cloudcare/static/cloudcare/js/spec/utils_spec.js
  docs/js-guide/dependencies.rst
Labels: Risk: Medium

#35740 Handle endpoint duration on payload error
  corehq/motech/repeaters/tasks.py
  corehq/motech/repeaters/tests/test_tasks.py
Labels: product/invisible

#35675 Create SystemLimit data model
  corehq/apps/dump_reload/tests/test_dump_models.py
  corehq/project_limits/admin.py
  corehq/project_limits/migrations/0004_systemlimit.py
  corehq/project_limits/models.py
  migrations.lock
Labels: reindex/migration

#35745 Delete ewsghana app
  corehq/apps/cleanup/migrations/0018_delete_ewsghana_models.py
  corehq/apps/reports/static/reports/js/bootstrap3/standard_hq_report.js
  corehq/apps/reports/static/reports/js/bootstrap5/standard_hq_report.js
  custom/ewsghana/models.py
  migrations.lock
Labels: reindex/migration

#35633 Avoid parallel builds
  corehq/apps/userreports/models.py
  corehq/apps/userreports/tasks.py
  corehq/apps/userreports/templates/userreports/edit_data_source.html
  corehq/apps/userreports/tests/test_tasks.py
  corehq/apps/userreports/tests/test_view.py
  corehq/apps/userreports/ui/forms.py
  corehq/apps/userreports/views.py
Labels: QA Passed, product/feature-flag

#35750 Update FHIR documentation URLs
  corehq/motech/fhir/bundle.py
  corehq/motech/fhir/const.py
  corehq/motech/fhir/tasks.py
  docs/fhir/fhir_import_config.rst
  docs/fhir/fhir_repeater.rst
  docs/fhir/index.rst
Labels: product/invisible

#35759 Revert "Bump codecov/codecov-action from 4 to 5"
  .github/workflows/tests.yml
Labels: product/invisible

#35764 Added quill to package.json
  package.json
  yarn.lock
Labels: product/invisible, dependencies

#35688 Add rate limiting for check_username_availability
  corehq/apps/registration/rate_limiter.py
  corehq/apps/registration/views.py
Labels: product/invisible, Risk: High

#35744 Log changes to Web User Invitations
  corehq/apps/api/resources/v1_0.py
  corehq/apps/api/tests/test_user_resources.py
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  corehq/apps/reports/util.py
  corehq/apps/user_importer/importer.py
  corehq/apps/users/migrations/0077_invitationhistory.py
  corehq/apps/users/model_log.py
  corehq/apps/users/models.py
  corehq/apps/users/tests/test_user_invitation.py
  corehq/apps/users/util.py
  corehq/apps/users/views/__init__.py
  corehq/apps/users/views/web.py
  corehq/const.py
  migrations.lock
Labels: reindex/migration, product/invisible, Risk: High, Risk: Medium

#35757 Updated reportlab from 3.6.13 to 4.3.0
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#35767 Excluded analytix/js/cta_forms from requirejs build
  corehq/apps/hqwebapp/static/hqwebapp/yaml/bootstrap3/requirejs.yml
  corehq/apps/hqwebapp/static/hqwebapp/yaml/bootstrap5/requirejs.yml
Labels: product/invisible

#35758 Slight tweaks to the domain analytics value
  corehq/apps/analytics/templates/analytics/initial/gtm.html
  corehq/apps/app_manager/tests/test_views.py
Labels: product/invisible

#35602 Add google analytics log to form submission
  corehq/apps/cloudcare/static/cloudcare/js/form_entry/web_form_session.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/controller.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/utils.js
  corehq/apps/cloudcare/static/cloudcare/js/gtx.js
Labels: Risk: Medium

#35768 Reset backoff when user unpauses a repeater
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: product/invisible

#35780 Accommodate when a 404 is not a client error
  corehq/motech/repeaters/models.py
Labels: product/invisible

#35771 Remove Cases with GPS Data (Microplanning)
  corehq/apps/geospatial/views.py
Labels: product/feature-flag, product/invisible

#35773 fix issue with sorting when app filter is selected
  corehq/apps/reports/standard/deployments.py
Labels: product/invisible

#35784 Create models & initial migration for Bulk Data Cleaning functionality
  corehq/apps/data_cleaning/migrations/0001_initial.py
  corehq/apps/data_cleaning/migrations/__init__.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/domain/deletion.py
  corehq/apps/dump_reload/sql/dump.py
  migrations.lock
Labels: reindex/migration, product/invisible

#35792 Reset backoff on pause instead of on resume
  corehq/motech/repeaters/models.py
  corehq/motech/repeaters/tests/test_repeater.py
Labels: product/invisible

#35793 "Retry Date" column for `process_repeaters()`
  corehq/apps/reports/standard/cases/case_data.py
  corehq/motech/repeaters/tests/test_display.py
  corehq/motech/repeaters/views/repeat_record_display.py
  corehq/motech/repeaters/views/repeat_records.py
Labels: product/invisible

#35674 Improve readability of enterprise code
  corehq/apps/enterprise/enterprise.py
Labels: product/invisible

#35795 Upgraded pyyaml from 6.0 to 6.0.2
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#35790 Make email validator case-insensitive
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/validators.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/validators.ko.js
  corehq/apps/hqwebapp/static/hqwebapp/js/constants.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/bootstrap3/main.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/bootstrap5/main.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/email_validator_spec.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/validators.ko.js.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/spec/main.js.diff.txt
  corehq/apps/registration/forms.py
Labels: Risk: High

#35804 Safe mapping
  corehq/apps/integration/kyc/forms.py
  corehq/apps/integration/kyc/models.py
  corehq/apps/integration/kyc/services.py
  corehq/apps/integration/kyc/tests/test_services.py
  corehq/apps/integration/kyc/tests/test_views.py
Labels: reindex/migration, product/invisible

#35800 Data Cleaning: placeholder form view for creating a session and a placeholder table for tasks
  corehq/apps/data_cleaning/forms.py
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_main.js
  corehq/apps/data_cleaning/static/data_cleaning/js/clean_cases_session.js
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/templates/data_cleaning/clean_cases_main.html
  corehq/apps/data_cleaning/templates/data_cleaning/clean_cases_session.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/forms/next_action_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/loading_indicator.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/start_session.html
  corehq/apps/data_cleaning/templates/data_cleaning/select_case_type.html
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/views/__init__.py
  corehq/apps/data_cleaning/views/forms.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/data_cleaning/views/tables.py
  corehq/apps/hqwebapp/static/hqwebapp/js/alpinejs/directives/select2.js
  corehq/tabs/tabclasses.py
Labels: product/feature-flag

#35799 Fixed an index error with the enterprise domains report
  corehq/apps/enterprise/api/resources.py
Labels: product/invisible

#35802 Revert "Revert "TableauConnectedApp, TransifexOrganization, and OpenmrsImporter models: AES CBC encryption Migration ""
  corehq/apps/reports/migrations/0021_tableauconnectedapp_use_aes_cbc_encryption.py
  corehq/apps/reports/models.py
  corehq/apps/translations/migrations/0010_transifex_organization_api_token_encryption.py
  corehq/motech/migrations/0018_openmrsimporter_use_aes_cbc_encryption.py
  migrations.lock
Labels: reindex/migration

#35805 Data Cleaning: add UI placeholders for Filters, Columns, and Edit + some reorg
  corehq/apps/data_cleaning/forms/__init__.py
  corehq/apps/data_cleaning/forms/setup.py
  corehq/apps/data_cleaning/templates/data_cleaning/clean_cases_session.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/button_bar.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/offcanvas.html
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/data_cleaning/views/setup.py
Labels: product/feature-flag

#35806 Added BulkEditChange.edited_value
  corehq/apps/data_cleaning/exceptions.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tests/test_models.py
Labels: product/invisible

#35743 Adapt CaseSearchProfiler for more general use
  corehq/apps/case_search/utils.py
  corehq/apps/es/profiling.py
  corehq/apps/reports/standard/__init__.py
Labels: product/invisible

#35822 fix select2 alpine directive bug when HTMX swaps the same form back into the DOM
  corehq/apps/hqwebapp/static/hqwebapp/js/alpinejs/directives/select2.js
Labels: product/invisible

#35814 Reduce hqImport usage in app_manager
  corehq/apps/app_manager/static/app_manager/js/app_manager.js
  corehq/apps/app_manager/static/app_manager/js/app_manager_media.js
  corehq/apps/app_manager/static/app_manager/js/details/column.js
  corehq/apps/app_manager/static/app_manager/js/details/screen.js
  corehq/apps/app_manager/static/app_manager/js/details/sort_rows.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/releases/releases.js
  corehq/apps/app_manager/templates/app_manager/apps_base.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config.html
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/add_property_button.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/case_list_properties.html
  corehq/apps/app_manager/templates/app_manager/partials/nav_menu_media_single_type.html
  corehq/apps/app_manager/templates/app_manager/partials/releases/releases_deploy_modal.html
Labels: product/invisible

#35818 flag_enabled on method takes precedence over class decorator
  corehq/util/test_utils.py
  corehq/util/tests/test_utils.py
Labels: product/invisible

#35698 Support API key as password for excel feeds
  corehq/apps/domain/auth.py
  corehq/apps/domain/decorators.py
  corehq/apps/domain/tests/test_api_key_auth.py
  corehq/apps/domain/tests/test_auth.py
  corehq/apps/export/views/list.py
Labels: Risk: High

#35820 Functionality for creating new session or resuming/restarting an existing session
  corehq/apps/data_cleaning/forms/setup.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/templates/data_cleaning/partials/forms/active_session_exists.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/forms/next_action_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/start_session.html
  corehq/apps/data_cleaning/tests/test_session.py
  corehq/apps/data_cleaning/views/setup.py
Labels: product/invisible

#35724 Get table name directly
  corehq/apps/userreports/sql/adapter.py
Labels: product/feature-flag

#35827 Remove test_form_actions_wrap
  corehq/apps/app_manager/tests/test_form_actions_wrap.py
Labels: product/invisible

#35807 Remove load_appcues_template_app
  corehq/apps/app_manager/tasks.py
  corehq/apps/registration/templates/registration/partials/register_new_user/submit_info.html
  corehq/apps/registration/utils.py
Labels: product/prod-india-all-users, Risk: High

#35823 Replaced inline edit's postSave callback with event on document
  corehq/apps/app_manager/static/app_manager/js/app_view.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_view.js
  corehq/apps/app_manager/static/app_manager/js/modules/module_view.js
  corehq/apps/app_manager/templates/app_manager/app_view.html
  corehq/apps/app_manager/templates/app_manager/form_view.html
  corehq/apps/app_manager/templates/app_manager/partials/modules/module_view_heading.html
  corehq/apps/app_manager/templatetags/xforms_extras.py
  corehq/apps/app_manager/tests/templatetags/test_xforms_extras.py
  corehq/apps/hqwebapp/static/hqwebapp/js/components/inline_edit.js
Labels: product/invisible, Risk: Medium

#35826 Use Data Cleaning Session in the Session View and Table View
  corehq/apps/data_cleaning/columns.py
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/templates/data_cleaning/columns/column_main.html
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/data_cleaning/views/tables.py
Labels: product/feature-flag

#35819 fix value error if there is an issue with initializing domain
  corehq/apps/registration/utils.py
Labels: product/invisible, Risk: High

#35803 Case Import Payment Validation
  corehq/apps/case_importer/const.py
  corehq/apps/case_importer/do_import.py
  corehq/apps/case_importer/views.py
  corehq/toggles/__init__.py
Labels: product/feature-flag, Risk: High

#35779 Update links for redirection
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap3/footer.html
  corehq/apps/hqwebapp/templates/hqwebapp/partials/bootstrap5/footer.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/hqwebapp/partials/footer.html.diff.txt
  corehq/apps/registration/forms.py
Labels: Risk: High

#35834 Remove obsolete pickle5 dependency
  requirements/base-requirements.in
  requirements/dev-requirements.txt
  requirements/docs-requirements.txt
  requirements/prod-requirements.txt
  requirements/requirements.txt
  requirements/test-requirements.txt
Labels: product/invisible, dependencies

#35844 Fix js-guide README link
  CONTRIBUTING.rst
Labels: product/invisible

#35842 Fixed js access in advanced form case config
  corehq/apps/app_manager/static/app_manager/js/forms/advanced/case_config_ui.js
  corehq/apps/app_manager/templates/app_manager/partials/forms/case_config_ko_templates.html
Labels: product/feature-flag

#35847 Fixed missing banner due to project missing from request
  corehq/apps/domain/decorators.py
Labels: product/all-users-all-environments, Risk: High

#35845 Add placeholder Editable Record for ElasticTable's record_class
  corehq/apps/data_cleaning/records.py
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/views/tables.py
  corehq/apps/hqwebapp/tables/elasticsearch/records.py
  corehq/apps/hqwebapp/tables/elasticsearch/tables.py
Labels: product/feature-flag

#35766 Experiment with hqcases removal
  corehq/apps/README.rst
  corehq/apps/data_pipeline_audit/dbacessors.py
  corehq/apps/domain/tests/test_deletion_models.py
  corehq/apps/dump_reload/tests/test_dump_models.py
  corehq/apps/experiments/README.md
  corehq/apps/experiments/__init__.py
  corehq/apps/experiments/admin.py
  corehq/apps/experiments/experiment.py
  corehq/apps/experiments/migrations/0001_initial.py
  corehq/apps/experiments/migrations/__init__.py
  corehq/apps/experiments/models.py
  corehq/apps/experiments/tests/__init__.py
  corehq/apps/experiments/tests/test_enabler.py
  corehq/apps/experiments/tests/test_experiment.py
  corehq/util/metrics/metrics.py
  migrations.lock
  settings.py
Labels: reindex/migration, product/invisible

#35851 Ensure KYC Config Exists for KYC Verification Report
  corehq/apps/integration/kyc/tests/test_views.py
  corehq/apps/integration/kyc/views.py
  corehq/apps/integration/templates/kyc/kyc_verify_report.html
Labels: product/feature-flag

#35848 Data cleaning: a save button
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tables.py
  corehq/apps/data_cleaning/templates/data_cleaning/clean_cases_session.html
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/data_cleaning/views/tables.py
Labels: product/feature-flag

#35828 Updated Hubspot Request-a-Demo form
  corehq/apps/analytics/static/analytix/js/cta_forms.js
  corehq/apps/analytics/static/analytix/js/hubspot.js
  corehq/apps/analytics/templates/analytics/forms/bootstrap3/hubspot_cta_form.html
  corehq/apps/analytics/templates/analytics/forms/bootstrap5/hubspot_cta_form.html
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/analytics/forms/hubspot_cta_form.html.diff.txt
Labels: product/all-users-all-environments

#35832 Add 'Organization or Company' to signup form and use for BillingContactInfo
  corehq/apps/registration/forms.py
  corehq/apps/registration/static/registration/js/new_user.ko.js
  corehq/apps/registration/utils.py
  corehq/apps/registration/views.py
Labels: product/prod-india-all-users, Risk: High

#35855 Moved flagged accounting views behind flag
  corehq/apps/accounting/views.py
Labels: product/admin

#35846 Add backend logic for column filtering
  corehq/apps/data_cleaning/exceptions.py
  corehq/apps/data_cleaning/migrations/0003_column_filter_unique_ids_match_type_updates.py
  corehq/apps/data_cleaning/models.py
  corehq/apps/data_cleaning/tests/test_filters.py
  corehq/apps/data_cleaning/tests/test_session.py
  corehq/apps/data_cleaning/views/tables.py
  migrations.lock
Labels: reindex/migration, product/feature-flag

#35857 Updated report an issue and solutions feature request emails to not c…
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/email-request.js
  corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap5/email-request.js
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/javascript/hqwebapp/js/email-request.js.diff.txt
Labels: product/all-users-all-environments

#35843 Added icons to 'Edit Data' section of menu
  corehq/apps/case_importer/base.py
  corehq/apps/data_interfaces/interfaces.py
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/navs.less
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_nav.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/navs._nav.style.diff.txt
  corehq/tabs/tabclasses.py
Labels: product/all-users-all-environments

#35695 Use QuillJS as rich text editor
  Gruntfile.js
  corehq/apps/hqwebapp/static/hqwebapp/js/components/quill.css
  corehq/apps/hqwebapp/static/hqwebapp/js/components/rich_text_knockout_bindings.js
  corehq/apps/hqwebapp/static/hqwebapp/less/_hq/bootstrap5-temp.less
  corehq/apps/hqwebapp/static/hqwebapp/spec/components/main.js
  corehq/apps/hqwebapp/static/hqwebapp/spec/components/rich_text_spec.js
  corehq/apps/hqwebapp/templates/hqwebapp/spec/components/mocha.html
  corehq/messaging/scheduling/const.py
  corehq/messaging/scheduling/forms.py
  corehq/messaging/scheduling/static/scheduling/js/create_schedule.js
  corehq/messaging/scheduling/templates/scheduling/partials/rich_text_editor.html
  corehq/messaging/scheduling/templates/scheduling/partials/rich_text_email_template.html
  corehq/messaging/scheduling/templates/scheduling/partials/rich_text_message_configuration.html
  corehq/toggles/__init__.py
  package.json
  yarn.lock
Labels: dependencies, Risk: Medium

#35825 Rc/feature flag domain specific apm traces
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/api.js
  corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/menu_list_spec.js
  corehq/toggles/__init__.py
Labels: Risk: Medium

#35858 Prepare Session View for Pinned Filters
  corehq/apps/data_cleaning/forms/setup.py
  corehq/apps/data_cleaning/templates/data_cleaning/forms/next_action_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/partials/active_session_exists.html
  corehq/apps/data_cleaning/templates/data_cleaning/forms/pinned_filter_form.html
  corehq/apps/data_cleaning/templates/data_cleaning/partials/offcanvas.html
  corehq/apps/data_cleaning/tests/test_views.py
  corehq/apps/data_cleaning/urls.py
  corehq/apps/data_cleaning/views/filters.py
  corehq/apps/data_cleaning/views/main.py
  corehq/apps/data_cleaning/views/mixins.py
  corehq/apps/data_cleaning/views/setup.py
  corehq/apps/data_cleaning/views/tables.py
Labels: product/feature-flag

#35862 Return real user status instead of always Active
  corehq/apps/users/bulk_download.py
  corehq/apps/users/tests/test_bulk_download.py
Labels: product/invisible

#35861 Lowercase input username on disable 2FA form
  corehq/apps/hqadmin/forms.py
Labels: product/admin

#35863 Fix admin enable/disable user view
  corehq/apps/hqadmin/templates/hqadmin/disable_user.html
  corehq/apps/hqadmin/views/users.py
Labels: product/invisible

#35865 Log user change via location update
  corehq/apps/locations/forms.py
  corehq/apps/locations/tasks.py
  corehq/const.py
Labels: product/invisible

#35859 vellum:b193bd450901efd6e419f952f4e42548b037b175
  corehq/apps/app_manager/static/app_manager/js/vellum/manifest.txt
  corehq/apps/app_manager/static/app_manager/js/vellum/src/main-components.js
  corehq/apps/app_manager/static/app_manager/js/vellum/version.txt
Labels: product/invisible

#35867 make select2 textarea placeholder font consistent with the rest of HQ
  corehq/apps/hqwebapp/static/hqwebapp/scss/commcarehq/_select2.scss
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/stylesheets/imports/select2s._select2.style.diff.txt
Labels: product/all-users-all-environments
