Repository dimagi/commcare-hq, pull requests merged in 2025-10, with the labels that each got.

#36997 Fetch Payment status for records that were submitted for payment
  corehq/apps/integration/payments/const.py
  corehq/apps/integration/payments/filters.py
  corehq/apps/integration/payments/services.py
  corehq/apps/integration/payments/tables.py
  corehq/apps/integration/payments/tests/test_services.py
  corehq/apps/integration/tasks.py
  corehq/apps/integration/templates/payments/partials/payments_status.html
Labels: product/feature-flag

#37014 Allow debug environments to copy apps from staging
  corehq/apps/domain/forms.py
  corehq/apps/domain/tests/test_forms.py
  corehq/apps/domain/views/import_apps.py
  corehq/apps/hqwebapp/models.py
  corehq/apps/hqwebapp/tests/test_models.py
  corehq/apps/hqwebapp/views.py
  corehq/apps/registration/forms.py
  corehq/apps/registration/views.py
  corehq/util/context_processors.py
Labels: product/invisible, Risk: High

#37009 Add customer UI to enable or disable auto renew for a subscription
  corehq/apps/domain/templates/domain/bootstrap3/current_subscription.html
  corehq/apps/domain/templates/domain/bootstrap5/current_subscription.html
  corehq/apps/domain/templates/domain/partials/bootstrap3/auto_renew_modal.html
  corehq/apps/domain/templates/domain/partials/bootstrap5/auto_renew_modal.html
  corehq/apps/domain/templates/domain/partials/disable_auto_renew.html
  corehq/apps/domain/templates/domain/partials/enable_auto_renew.html
  corehq/apps/domain/views/accounting.py
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/current_subscription.html.diff.txt
  corehq/apps/hqwebapp/tests/data/bootstrap5_diffs/domain/partials/auto_renew_modal.html.diff.txt
Labels: product/feature-flag

#37033 Avoid rendering HTML tags in user-defined case list display text
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/config_modal.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/detail.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/search_controls.html
  corehq/apps/cloudcare/templates/cloudcare/partials/case_list/table_container.html
Labels: product/invisible, Risk: Medium

#37022 Reduce pillow lag on low volume partitions
  corehq/apps/change_feed/consumer/feed.py
  corehq/apps/change_feed/tests/test_kafka_change_feed.py
  corehq/ex-submodules/pillowtop/feed/couch.py
  corehq/ex-submodules/pillowtop/feed/interface.py
  corehq/ex-submodules/pillowtop/pillow/interface.py
  corehq/ex-submodules/pillowtop/run_pillowtop.py
  corehq/ex-submodules/pillowtop/tests/test_changes.py
  corehq/ex-submodules/pillowtop/tests/test_pillow.py
  corehq/ex-submodules/pillowtop/tests/utils.py
  corehq/sql_db/connections.py
Labels: product/invisible

#37019 Adds a secondary validation by introducing a new case property `commcare_final_mobile_validation`
  corehq/apps/integration/payments/const.py
  corehq/apps/integration/payments/services.py
  corehq/apps/integration/payments/tests/test_services.py
  corehq/apps/integration/payments/tests/test_views.py
  corehq/apps/integration/payments/views.py
  corehq/apps/integration/tasks.py
Labels: product/feature-flag

#36931 Fix invitation location updates for new web users from bulk upload
  corehq/apps/user_importer/importer.py
  corehq/apps/user_importer/tests/test_importer.py
  corehq/apps/users/admin.py
  corehq/apps/users/views/__init__.py
Labels: QA Passed, product/all-users-all-environments, Risk: Medium

#37044 Decrease heartbeat threshold from 60 to 15 minutes
  settings.py
Labels: product/invisible

#36744 Mjr/show multi updates
  corehq/apps/app_manager/exceptions.py
  corehq/apps/app_manager/helpers/validators.py
  corehq/apps/app_manager/models.py
  corehq/apps/app_manager/static/app_manager/js/case_config_utils.js
  corehq/apps/app_manager/static/app_manager/js/forms/case_config_ui.js
  corehq/apps/app_manager/static/app_manager/js/forms/form_action_diffs.js
  corehq/apps/app_manager/tests/test_exceptions.py
  corehq/apps/app_manager/tests/test_models.py
  corehq/apps/app_manager/views/forms.py
  corehq/apps/hqwebapp/tests/utils/test_translation.py
  corehq/apps/translations/tests/utils.py
  corehq/toggles/__init__.py
Labels: product/invisible

#37037 Increase expiration time for mobile worker email invites to 24 hours
  corehq/apps/users/views/mobile/users.py
Labels: product/all-users-all-environments
